Repository istio/istio, pull requests merged in 2018-10, with the labels that each got.

#9010 Add robustness to prom adapter http handler
  mixer/adapter/prometheus/prometheus.go
  mixer/adapter/prometheus/prometheus_test.go
Labels: approved, cla: yes, lgtm

#8954 Port the first e2e Mixer test to the new framework.
  pkg/test/config.go
  pkg/test/deployment/attrmanifest.go
  pkg/test/deployment/bookinfo.go
  pkg/test/deployment/instance.go
  pkg/test/deployment/istio.go
  pkg/test/env/istio.go
  pkg/test/fakes/policy/backend.go
  pkg/test/framework/components/bookinfo/bookinfo.go
  pkg/test/framework/components/bookinfo/configs.go
  pkg/test/framework/components/components.go
  pkg/test/framework/components/ingress/ingress.go
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/components/prometheus/prometheus.go
  pkg/test/framework/dependency/dependencies.go
  pkg/test/framework/environment.go
  pkg/test/framework/environment/environment.go
  pkg/test/framework/environments/kubernetes/flags.go
  pkg/test/framework/environments/kubernetes/implementation.go
  pkg/test/framework/environments/kubernetes/settings.go
  pkg/test/framework/environments/local/implementation.go
  pkg/test/kube/kubectl.go
  pkg/test/util/retry.go
  tests/integration2/mixer/check_test.go
  tests/integration2/mixer/report_test.go
  tests/integration2/mixer/scenarios_test.go
  tests/integration2/tests.mk
Labels: approved, cla: yes, lgtm

#9038 Re-enable skipped tests
  mixer/pkg/config/store/fsstore_test.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  prow/lib.sh
  prow/mason_lib.sh
Labels: cla: yes

#8288 add opencensus metrics to mcp/server
  galley/pkg/server/monitoring.go
  galley/pkg/server/server.go
  galley/pkg/server/server_test.go
  pkg/mcp/server/monitoring.go
  pkg/mcp/server/server.go
  pkg/mcp/server/server_test.go
  pkg/mcp/testing/monitoring/reporter.go
  pkg/mcp/testing/server.go
  tests/e2e/tests/pilot/mock/mcp/server.go
Labels: approved, cla: yes, lgtm

#9072 Fix a few doc errors
  mixer/adapter/prometheus/config/adapter.prometheus.config.pb.html
  mixer/adapter/prometheus/config/config.pb.go
  mixer/adapter/prometheus/config/config.proto
  mixer/adapter/prometheus/config/config.proto_descriptor
  mixer/adapter/prometheus/config/prometheus.yaml
Labels: approved, cla: yes, lgtm

#8238 ensure validatingwebhookconfigurations deleted before test suite return
  tests/e2e/framework/kubernetes.go
  tests/util/kube_utils.go
Labels: approved, cla: yes, lgtm

#9071 enable envoy fetch root ca through SDS
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/caclient/client.go
  security/pkg/nodeagent/caclient/client_test.go
  security/pkg/nodeagent/model/secret.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: approved, cla: yes, lgtm

#9091 Fix port number in the istio-multicluster-gateway
  install/kubernetes/helm/istio/charts/gateways/templates/preconfigured.yaml
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: approved, cla: yes, lgtm

#9014 [test-framework] Adding k8s deployment for apps
  pkg/test/deployment/instance.go
  pkg/test/docker/registry/incluster.go
  pkg/test/framework/components/apps/kube/apps.go
  pkg/test/framework/components/apps/kube/client.go
  pkg/test/framework/components/apps/kube/deployment.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/environments/kubernetes/flags.go
  pkg/test/framework/environments/kubernetes/implementation.go
  pkg/test/framework/environments/kubernetes/settings.go
  pkg/test/helm/settings.go
  pkg/test/kube/accessor.go
  pkg/test/shell/shell.go
Labels: approved, cla: yes, lgtm

#9031 update istio/api version
  Gopkg.lock
  vendor/istio.io/api/authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  vendor/istio.io/api/authentication/v1alpha1/policy.pb.go
  vendor/istio.io/api/authentication/v1alpha1/policy.proto
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/mixer/v1/attributes.pb.go
  vendor/istio.io/api/mixer/v1/attributes.proto
  vendor/istio.io/api/mixer/v1/check.pb.go
  vendor/istio.io/api/mixer/v1/check.proto
  vendor/istio.io/api/mixer/v1/report.pb.go
  vendor/istio.io/api/mixer/v1/report.proto
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/authentication/v1alpha1/policy_pb2.py
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/attributes_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/check_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/report_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#9093 fix comments in istio/values.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9092 Do not check for services when generating cluster names
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/tls.go
Labels: approved, cla: yes, lgtm

#8987 Stop Pilot correctly in MCP test
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  tests/e2e/tests/pilot/mcp_test.go
  tests/util/pilot_server.go
Labels: approved, cla: yes, lgtm

#9060 move test command to gcb
  release/airflow/airflow_scripts.sh
  release/airflow/cloud_test.template.json
  release/airflow/gcb_build_lib.sh
  release/gcb_lib.sh
  release/generate_manifest.sh
  release/test_release.sh
Labels: approved, cla: yes, lgtm

#9100 Update istio/api
  Gopkg.lock
  istioctl/cmd/istioctl/istioctl_test.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/test/mock/config.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/gateway_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#9110 Fix "make test common-tests" errors
  pkg/test/framework/components/prometheus/prometheus.go
  security/cmd/istio_ca/main.go
Labels: approved, cla: yes, lgtm

#9108 Do not check for services when generating cluster names (#9092)
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/tls.go
Labels: approved, cla: human-approved, lgtm

#9042 Clean up MCP nil authCheck
  pkg/mcp/server/server.go
Labels: approved, cla: yes, lgtm

#9085 Refactor `istio-docker.mk` for 30 second builds
  pilot/docker/Dockerfile.proxy_debug
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#8932 Add citadel to new test framework
  pkg/test/framework/components/citadel/citadel.go
  pkg/test/framework/components/components.go
  pkg/test/framework/dependency/dependencies.go
  pkg/test/framework/environment.go
  pkg/test/framework/environment/environment.go
  pkg/test/kube/accessor.go
  tests/integration2/citadel/citadel_test_util.go
  tests/integration2/citadel/secret_creation_test.go
  tests/integration2/tests.mk
Labels: approved, cla: yes, lgtm

#9095 remove backward compat checks for 0.8 proxies
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/tls.go
Labels: approved, cla: yes

#8999 Fix hostname in Citadel service cert.
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: approved, cla: yes, lgtm

#9094 Deprecate Servicegraph.
  addons/servicegraph/README.md
Labels: approved, cla: yes, lgtm

#9105 set ChannelCredentials to be LocalCredentials in SdsSecretConfig
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: approved, cla: yes, lgtm

#9084 [Helm Installer] upgrade kiali and enable it in demo yamls
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9126 Changes to command line params in upgrade test script
  Makefile
  tests/upgrade/test_crossgrade.sh
  tests/upgrade/test_upgrade_from.sh
Labels: approved, cla: yes, lgtm

#9069 [Ansible Installer] bump up kiali version to v0.8
  install/kubernetes/ansible/istio/tasks/install_addons.yml
Labels: approved, cla: yes, lgtm

#9041 add snapshot grouping capability to MCP's snapshot package
  galley/pkg/runtime/processor.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/server/server.go
  mixer/pkg/config/mcp/backend.go
  pkg/mcp/configz/configz_test.go
  pkg/mcp/snapshot/snapshot.go
  pkg/mcp/snapshot/snapshot_test.go
  pkg/mcp/testing/server.go
Labels: approved, cla: yes, lgtm

#9082 Change coredump path, limit number of core files and add integration …
  Makefile
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/docker/Dockerfile.proxytproxy
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/inject/enable-core-dump.yaml.injected
  pilot/test/util/kubernetes.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/istio.mk
  tools/dump_kubernetes.sh
Labels: cla: yes

#9132 Cherry-picks from release-1.0
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9133 Passing green sha to githubctl.
  release/airflow/cloud_test.template.json
  release/test_release.sh
Labels: approved, cla: yes, lgtm

#9122 increase test timeout, use local manifest file
  release/airflow/cloud_publish.template.json
  release/airflow/cloud_tag.template.json
  release/airflow/cloud_test.template.json
  release/publish_release.sh
Labels: approved, cla: yes, lgtm

#9135 Assorted helm cleanups
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
Labels: approved, cla: yes, lgtm

#9137 Pull in toml 0.3.1 dependency to clean up license
  Gopkg.lock
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/tomlv/COPYING
  vendor/github.com/BurntSushi/toml/lex.go
Labels: approved, cla: yes, lgtm

#9120 Do not set TLS contexts for MC gateway
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/preconfigured.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#9131 remove the constraint of sds request.resource must be in spiffe format
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/model/secret.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: approved, cla: yes, lgtm

#9106 helm - push configuration to subcharts
  install/kubernetes/helm/istio/charts/certmanager/values.yaml
  install/kubernetes/helm/istio/charts/galley/values.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/clusterrolebindings.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/service.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  install/kubernetes/helm/istio/charts/grafana/values.yaml
  install/kubernetes/helm/istio/charts/ingress/values.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
  install/kubernetes/helm/istio/charts/mixer/values.yaml
  install/kubernetes/helm/istio/charts/nodeagent/values.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  install/kubernetes/helm/istio/charts/prometheus/values.yaml
  install/kubernetes/helm/istio/charts/security/values.yaml
  install/kubernetes/helm/istio/charts/servicegraph/values.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/values.yaml
  install/kubernetes/helm/istio/charts/telemetry-gateway/values.yaml
  install/kubernetes/helm/istio/charts/tracing/values.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9073 add e2e tests for per-path jwt authentication
  tests/e2e/tests/pilot/authn_policy_test.go
  tests/e2e/tests/pilot/testdata/authn/v1alpha1/authn-policy-jwt.yaml.tmpl
  tests/e2e/tests/pilot/testdata/authn/v1alpha1/correct_jwt2
Labels: approved, cla: yes, lgtm

#9153 don't expose ports for mesh expansion
  install/kubernetes/helm/istio/charts/gateways/templates/service.yaml
  install/kubernetes/helm/istio/charts/gateways/values.yaml
Labels: approved, cla: yes, lgtm

#9158 A few doc fixes.
  mixer/adapter/cloudwatch/config/adapter.cloudwatch.config.pb.html
  mixer/adapter/cloudwatch/config/cloudwatch.yaml
  mixer/adapter/cloudwatch/config/config.proto
  mixer/adapter/cloudwatch/config/config.proto_descriptor
  mixer/adapter/fluentd/config/adapter.fluentd.config.pb.html
  mixer/adapter/fluentd/config/config.proto
  mixer/adapter/fluentd/config/config.proto_descriptor
  mixer/adapter/fluentd/config/fluentd.yaml
  mixer/adapter/kubernetesenv/config/adapter.kubernetesenv.config.pb.html
  mixer/adapter/kubernetesenv/config/config.pb.go
  mixer/adapter/kubernetesenv/config/config.proto
  mixer/adapter/kubernetesenv/config/config.proto_descriptor
  mixer/adapter/kubernetesenv/config/kubernetesenv.yaml
Labels: cla: yes

#9134 Assorted Helm cleanups
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
Labels: approved, cla: yes

#9163 Multi-Cluster: add mock variables to secret controller for unit testing
  pkg/kube/secretcontroller/secretcontroller.go
  pkg/kube/secretcontroller/secretcontroller_test.go
Labels: approved, cla: yes

#9144 fix yaml generating issues when mcgateway,ilbgateway are enabled
  install/kubernetes/helm/istio/charts/gateways/values.yaml
Labels: approved, cla: yes, lgtm

#9167 Add report batching and dictionary compression into mixc
  mixer/cmd/mixc/cmd/check.go
  mixer/cmd/mixc/cmd/report.go
  mixer/cmd/mixc/cmd/root.go
  mixer/cmd/mixc/cmd/util.go
  mixer/cmd/mixc/cmd/util_test.go
Labels: approved, cla: yes, lgtm

#9130 Combine upgrade and downgrade.
  tests/upgrade/templates/fortio-cli.yaml
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#9136 return endpoints that is in the same namespace as its referred pod
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: approved, cla: yes, lgtm

#9179 Remove remaining reference of $ROLLBACK
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#9164 Remove the old upgrade and version skew tests.
  tests/e2e/tests/upgrade/upgrade_test.go
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#9181 run modify_values first
  release/airflow/modify_values.sh
  release/pipeline/dags/istio_common_daily.py
  release/pipeline/dags/istio_monthly_dag.py
Labels: approved, cla: yes, lgtm

#9112 pilot: add support for weighted TCP/TLS clusters
  Gopkg.lock
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/virtualservice-route-tcp-weighted.yaml
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#9178 Set SetCurrentClientCertDetails to forward client cert with correct fields
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes, lgtm

#9044 Fix rotation log configuration bug
  pkg/log/config.go
  pkg/log/config_test.go
Labels: approved, cla: yes, lgtm

#9192 Mixer minor fix
  mixer/pkg/server/args.go
  mixer/pkg/server/server.go
Labels: approved, cla: yes, lgtm

#9196 Fixed a broken link in tool's readme
  tools/README.md
Labels: cla: yes

#9201 add basic tests to keep build release pipeline working
  prow/build-tests.sh
Labels: approved, cla: yes, lgtm

#9195 [test-framework] Adding loadbalancing test
  pkg/test/deployment/attrmanifest.go
  pkg/test/deployment/helm.go
  pkg/test/deployment/instance.go
  pkg/test/deployment/settings.go
  pkg/test/framework/components/apps/kube/deployment.go
  pkg/test/framework/components/bookinfo/bookinfo.go
  pkg/test/framework/components/ingress/ingress.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/components/prometheus/prometheus.go
  pkg/test/framework/environments/kubernetes/flags.go
  pkg/test/framework/environments/kubernetes/implementation.go
  pkg/test/framework/environments/kubernetes/settings.go
  pkg/test/helm/commands.go
  pkg/test/helm/settings.go
  tests/integration2/qualification/loadbalancing_test.go
  tests/integration2/qualification/main_test.go
Labels: approved, cla: yes, lgtm

#8752 add UT for pilot/pkg/serviceregistry/kube
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: approved, cla: yes, lgtm

#9128 construct sdsconfig in cluster.tls_context
  pilot/pkg/model/authentication.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: approved, cla: yes, lgtm

#9203 [test-framework] Add dynamic port support to policybackend.
  pkg/test/fakes/policy/backend.go
  pkg/test/framework/components/policybackend/policybackend.go
Labels: approved, cla: yes, lgtm

#9151 Retry discovering CRD after server initialization
  install/kubernetes/helm/istio/charts/galley/templates/validatingwehookconfiguration.yaml.tpl
  install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml
  install/kubernetes/helm/istio/templates/crds.yaml
  mixer/pkg/config/crd/init.go
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
Labels: cla: yes

#9206 return endpoints that is in the same namespace as its referred pod
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: cla: yes

#9129 Istio Performance Dashboard
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-mesh-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-performance-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/mixer-dashboard.json
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: approved, area/perf and scalability, area/policies and telemetry, cla: yes

#9232 Support $TAG and $ISTIOCTL_BIN overide in e2e tests
  prow/e2e-suite.sh
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#9208 Inject pod labels and annotations in node.metadata
  Gopkg.lock
  Makefile
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/webhook_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/proxy/envoy/watcher.go
  pkg/bootstrap/bootstrap_config.go
  pkg/bootstrap/bootstrap_config_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running.proto
  pkg/bootstrap/testdata/running_golden.json
  tools/deb/envoy_bootstrap_v2.json
  tools/hyperistio/hyperistio.go
Labels: cla: no

#9200 Update Proxy SHA to pick a memory leak fix.
  istio.deps
Labels: approved, cla: yes, lgtm

#9218 Upgrade cert manager to v0.5.0
  install/kubernetes/helm/istio/charts/certmanager/Chart.yaml
  install/kubernetes/helm/istio/charts/certmanager/values.yaml
Labels: approved, cla: yes, lgtm

#9061 Resolve Workload from ReplicationControllers owner
  install/kubernetes/helm/istio/charts/mixer/templates/clusterrole.yaml
  mixer/adapter/kubernetesenv/cache.go
  mixer/adapter/kubernetesenv/cache_test.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
Labels: approved, cla: yes, lgtm

#9143 Revert default to unset externalTrafficPolicy for 1.0
  install/kubernetes/helm/istio/values-istio-gateways.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9180 Added domain for helm chart.
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9215 implement dynamic proto decoding
  mixer/pkg/protobuf/yaml/decoder.go
  mixer/pkg/protobuf/yaml/decoder_test.go
  mixer/pkg/protobuf/yaml/encoder.go
  mixer/pkg/protobuf/yaml/wire/wire.go
  mixer/pkg/protobuf/yaml/wire/wire_test.go
Labels: approved, cla: yes, lgtm

#9241 Add top level pilot metrics
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/lds.go
Labels: approved, cla: yes

#9244 fix TestController_Service case failed sometimes
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: approved, cla: yes, lgtm

#9210 fix the spelling mistake
  galley/pkg/crd/validation/webhook.go
  istioctl/cmd/istioctl/deprecated_cmd.go
  pilot/pkg/config/kube/crd/client.go
  pilot/pkg/config/kube/crd/conversion.go
  pilot/pkg/config/kube/crd/conversion_test.go
  pilot/tools/generate_config_crd_types.go
Labels: approved, cla: yes, lgtm

#9245 Fixed Typo for #9237
  install/kubernetes/helm/istio-remote/charts/security/templates/enable-mesh-mtls.yaml
  install/kubernetes/helm/istio/charts/security/templates/enable-mesh-mtls.yaml
Labels: approved, cla: yes, lgtm

#9198 Removed duplicated ports statement
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#9096 tracing: Add tracing to the istio-telemetry-gateway
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/NOTES.txt
  install/kubernetes/helm/istio/charts/tracing/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/tracing/values.yaml
  install/kubernetes/helm/istio/values-istio-gateways.yaml
Labels: approved, cla: yes, lgtm

#9220 fix racetest failure for `Test_KubeSecretController`
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
Labels: approved, cla: yes, lgtm

#9259 Add me to install owners
  install/OWNERS
Labels: approved, cla: yes, lgtm

#9253 Removed unused Helm values
  install/kubernetes/helm/istio/charts/mixer/values.yaml
  install/kubernetes/helm/istio/charts/nodeagent/values.yaml
Labels: approved, cla: yes, lgtm

#9262 mixer: go regenerate
  mixer/adapter/kubernetesenv/config/kubernetesenv.yaml
  mixer/template/sample/apa/Apa.yaml
  mixer/template/sample/apa/Apa_handler_service.descriptor_set
  mixer/template/sample/apa/Apa_proto.descriptor_set
  mixer/template/sample/check/CheckTesterTemplate.yaml
  mixer/template/sample/check/CheckTesterTemplate_handler_service.descriptor_set
  mixer/template/sample/check/CheckTesterTemplate_proto.descriptor_set
  mixer/template/sample/quota/QuotaTesterTemplate.yaml
  mixer/template/sample/quota/QuotaTesterTemplate_handler_service.descriptor_set
  mixer/template/sample/quota/QuotaTesterTemplate_proto.descriptor_set
  mixer/template/sample/report/ReportTesterTemplate.yaml
  mixer/template/sample/report/ReportTesterTemplate_handler_service.descriptor_set
  mixer/template/sample/report/ReportTesterTemplate_proto.descriptor_set
  mixer/test/listbackend/nosession.yaml
  mixer/test/prometheus/prometheus-nosession.yaml
  mixer/test/spyAdapter/template/apa/tmpl.yaml
  mixer/test/spyAdapter/template/apa/tmpl_handler_service.descriptor_set
  mixer/test/spyAdapter/template/apa/tmpl_proto.descriptor_set
  mixer/test/spyAdapter/template/check/tmpl.yaml
  mixer/test/spyAdapter/template/check/tmpl_handler_service.descriptor_set
  mixer/test/spyAdapter/template/check/tmpl_proto.descriptor_set
  mixer/test/spyAdapter/template/quota/quotatmpl.yaml
  mixer/test/spyAdapter/template/quota/quotatmpl_handler_service.descriptor_set
  mixer/test/spyAdapter/template/quota/quotatmpl_proto.descriptor_set
  mixer/test/spyAdapter/template/report/reporttmpl.yaml
  mixer/test/spyAdapter/template/report/reporttmpl_handler_service.descriptor_set
  mixer/test/spyAdapter/template/report/reporttmpl_proto.descriptor_set
  mixer/tools/codegen/pkg/bootstrapgen/testdata/apa/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/check/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/quota/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/report1/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/report2/template.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/BadExplicitTemplateName.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/BasicTopLevelFields.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/ExplicitTemplateName.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/MissingBothRequiredExt.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/MissingPackageName.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/MissingTemplateMessage.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/MissingTemplateVarietyExt.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/Proto2BadSyntax.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/ReservedFieldInTemplate.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/SimpleApaTemplate.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/SimpleTemplate.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedFieldTypeEnum.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedFieldTypeMessage.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedFieldTypePrimitive.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedMapKey.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedMapVal.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedTypeInAPAOutTemplate.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedValueTypeInAPA.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/WrongPkgName.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/multiFile.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/twoTemplatesError.descriptor
  mixer/tools/mixgen/cmd/adapter_test.go
  mixer/tools/mixgen/cmd/testdata/apa/template.descriptor
  mixer/tools/mixgen/cmd/testdata/check/template.descriptor
  mixer/tools/mixgen/cmd/testdata/error/template.descriptor
  mixer/tools/mixgen/cmd/testdata/quota/template.descriptor
  mixer/tools/mixgen/cmd/testdata/report/template.descriptor
Labels: approved, cla: yes, lgtm

#8479 Converts pilot to use common secret controller
  Gopkg.lock
  Gopkg.toml
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/clusterconfig.gotmpl
  pilot/pkg/config/clusterregistry/clusterregistry.gotmpl
  pilot/pkg/config/clusterregistry/conversion.go
  pilot/pkg/config/clusterregistry/conversion_test.go
  pilot/pkg/config/clusterregistry/multicluster.go
  pilot/pkg/config/clusterregistry/multicluster_test.go
  pilot/pkg/config/clusterregistry/secretcontroller.go
  tests/local/cluster_registry_test.go
  vendor/k8s.io/cluster-registry/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/.bin/marked
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/.bin/mime
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/.bin/static
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/bootstrap/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/colors/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/ejs/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/highlight.js/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/jquery.scrollto/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/jquery/AUTHORS.txt
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/jquery/LICENSE.txt
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/jquery/external/sizzle/LICENSE.txt
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/marked/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/mime/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/minimist/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/node-static/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/optimist/LICENSE
  vendor/k8s.io/cluster-registry/docs/reference/build/node_modules/wordwrap/LICENSE
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/doc.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/types.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/zz_generated.kubebuilder.go
Labels: approved, cla: yes, lgtm

#9231 [test-framework] Make helm values configurable
  pkg/test/deployment/helm.go
  pkg/test/deployment/instance.go
  pkg/test/deployment/istio.go
  pkg/test/deployment/settings.go
  pkg/test/deployment/yaml.go
  pkg/test/framework/components/apps/kube/deployment.go
  pkg/test/framework/components/bookinfo/bookinfo.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/environments/kubernetes/env.go
  pkg/test/framework/environments/kubernetes/flags.go
  pkg/test/framework/environments/kubernetes/implementation.go
  pkg/test/framework/environments/kubernetes/settings.go
Labels: approved, cla: yes, lgtm

#9236 Move NewKeyCertBundleRotator to caclient package.
  security/cmd/istio_ca/main.go
  security/pkg/caclient/keycertbundlerotator.go
  security/pkg/caclient/keycertbundlerotator_test.go
Labels: approved, cla: yes, lgtm

#9199 Cherry-pick: Add support for specifying sinkoptions when creating stackdriver sink
  Gopkg.lock
  mixer/adapter/stackdriver/config/adapter.stackdriver.config.pb.html
  mixer/adapter/stackdriver/config/config.pb.go
  mixer/adapter/stackdriver/config/config.proto
  mixer/adapter/stackdriver/config/config.proto_descriptor
  mixer/adapter/stackdriver/config/stackdriver.yaml
  mixer/adapter/stackdriver/log/log.go
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/logging/apiv2/config_client.go
  vendor/cloud.google.com/go/logging/apiv2/logging_client.go
  vendor/cloud.google.com/go/logging/apiv2/metrics_client.go
  vendor/cloud.google.com/go/logging/doc.go
  vendor/cloud.google.com/go/logging/internal/common.go
  vendor/cloud.google.com/go/logging/logadmin/logadmin.go
  vendor/cloud.google.com/go/logging/logadmin/metrics.go
  vendor/cloud.google.com/go/logging/logadmin/resources.go
  vendor/cloud.google.com/go/logging/logadmin/sinks.go
  vendor/cloud.google.com/go/logging/logging.go
  vendor/cloud.google.com/go/monitoring/apiv3/alert_policy_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/group_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/metric_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/notification_channel_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/uptime_check_client.go
  vendor/cloud.google.com/go/trace/apiv2/trace_client.go
Labels: approved, cla: yes, lgtm

#9186 Fix envoy proxy log levels in pilot agent
  pilot/cmd/pilot-agent/main.go
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: approved, cla: yes, lgtm

#9004 fix boilerplate
  istioctl/cmd/istioctl/authn.go
  istioctl/cmd/istioctl/convert_ingress.go
  istioctl/cmd/istioctl/gendeployment/cmd.go
  istioctl/cmd/istioctl/gendeployment/cmd_test.go
  istioctl/cmd/istioctl/gendeployment/yaml.go
  istioctl/cmd/istioctl/rbac.go
  istioctl/pkg/convert/ingress.go
  istioctl/pkg/kubernetes/client.go
  istioctl/pkg/writer/pilot/auth.go
  istioctl/pkg/writer/pilot/auth_test.go
  istioctl/pkg/writer/pilot/status.go
  istioctl/pkg/writer/pilot/status_test.go
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/test/server/echo/echo.go
  pilot/test/server/echo/handler.go
Labels: approved, cla: yes, lgtm

#9242 Remove redundant fakecaclient.
  security/pkg/caclient/client_test.go
  security/pkg/caclient/protocol/mock/fakeclient.go
  security/pkg/caclient/protocol/mock/fakeprotocol.go
  security/pkg/caclient/protocol/protocol.go
  security/pkg/nodeagent/vm/nodeagent_test.go
  security/pkg/probe/controller_test.go
Labels: approved, cla: yes, lgtm

#9264 nodeagent support for pluggabe CA
  install/kubernetes/helm/istio/charts/nodeagent/values.yaml
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/caclient/client.go
  security/pkg/nodeagent/caclient/client_test.go
  security/pkg/nodeagent/caclient/interface/iclient.go
  security/pkg/nodeagent/caclient/providers/google/client.go
  security/pkg/nodeagent/sds/server.go
Labels: approved, cla: yes, lgtm

#9285 fix syntax in template_mappings
  bin/mixer_codegen.sh
Labels: approved, cla: yes, lgtm

#9278 Turn off accesslog for admin
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  tools/deb/envoy_bootstrap_v2.json
Labels: approved, cla: yes, lgtm

#9276 bump up Kiali version to v0.9 in the Istio 1.0 branch
  install/kubernetes/ansible/istio/tasks/install_addons.yml
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9295 kube serviceregistry clean code
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/pod.go
Labels: approved, cla: yes, lgtm

#9287 Use `imagePullPolicy: IfNotPresent` for kubectl jobs
  install/kubernetes/helm/istio-remote/charts/security/templates/cleanup-secrets.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/security/templates/cleanup-secrets.yaml
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
Labels: approved, cla: yes, lgtm

#9309 Support $TAG and $ISTIOCTL_BIN overide in e2e tests (#9232)
  prow/e2e-suite.sh
  tests/istio.mk
Labels: approved, cla: yes

#9101 add opencensus metrics to MCP client
  galley/tools/mcpc/main.go
  mixer/pkg/config/mcp/backend.go
  pilot/pkg/bootstrap/server.go
  pkg/mcp/client/client.go
  pkg/mcp/client/client_test.go
  pkg/mcp/client/monitoring.go
  pkg/mcp/configz/configz_test.go
  pkg/mcp/testing/monitoring/reporter.go
Labels: approved, cla: yes, lgtm

#9298 fix LoggingOptions mismatch issue with configuration for galley server(#issue 9265)
  galley/cmd/galley/cmd/root.go
Labels: approved, cla: yes, lgtm

#9149 Add check flag to license scanner
  tools/license/README.md
  tools/license/get_dep_licenses.go
  tools/license/manual_append/signalfx.txt
  tools/license/manual_append/siphash.txt
Labels: approved, cla: yes, lgtm

#9311 Fix mixer attributes yaml indentation
  mixer/testdata/config/attributes.yaml
Labels: approved, cla: yes, lgtm

#9337 TCP dash fix
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-mesh-dashboard.json
Labels: approved, cla: yes, lgtm

#9282 fail nodeagent if CA provider isn't supported
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/caclient/client.go
Labels: approved, cla: yes, lgtm

#9166 Plugin: SNI DNAT gateway
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/envoyfilter/envoyfilter.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/pkg/networking/plugin/snidnat/snidnat.go
Labels: cla: no

#7847 Refresh secret when failed to parse certificates in it
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: approved, cla: yes

#8905 Stackdriver E2E test.
  Gopkg.lock
  Gopkg.toml
  tests/e2e/tests/stackdriver/README.md
  tests/e2e/tests/stackdriver/adapter.yaml
  tests/e2e/tests/stackdriver/fortio-rules.yaml
  tests/e2e/tests/stackdriver/stackdriver_test.go
  tests/istio.mk
  vendor/go.opencensus.io/opencensus.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ochttp/client.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/plugin/ochttp/span_annotator.go
  vendor/go.opencensus.io/plugin/ochttp/trace.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/trace/config.go
  vendor/go.opencensus.io/trace/export.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/google.golang.org/api/cloudtrace/v1/cloudtrace-gen.go
  vendor/google.golang.org/api/monitoring/v3/monitoring-gen.go
Labels: approved, cla: yes, lgtm

#9341 Fix codecov job failure
  bin/codecov.sh
Labels: approved, cla: yes, lgtm

#9312 Suppport ${ARTIFACTS_DIR} override in test script
  prow/lib.sh
Labels: approved, cla: yes, lgtm

#9303 [Cherry-pick] Turn off accesslog for admin
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/default_golden.json
  tools/deb/envoy_bootstrap_v2.json
Labels: approved, cla: yes, lgtm

#9283 inject SDS volume mount on gateway
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#9267 Fix racetest failures in multicluster
  pilot/pkg/config/clusterregistry/multicluster.go
  pilot/pkg/config/clusterregistry/multicluster_test.go
Labels: approved, cla: yes, lgtm

#9271 Xds cleanup
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: approved, cla: yes, lgtm

#8340 Header manipulation
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/test/client/client.go
  pilot/test/server/echo/handler.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-default-route-append-headers.yaml
Labels: approved, cla: human-approved, cla: yes, lgtm

#9204 Pilot agent changes to redirect Kubernetes liveness/readiness check.
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
Labels: approved, cla: yes, lgtm

#9352 Fix a data race in Pilot-Agent's TestAppProbe
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
Labels: approved, cla: yes, lgtm

#9357 Allow specifying pod DNS config in sidecar template
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9279 [test-framework] Make all k8s calls via Accessor
  pkg/test/deployment/helm.go
  pkg/test/deployment/instance.go
  pkg/test/deployment/util.go
  pkg/test/deployment/yaml.go
  pkg/test/docker/registry/cmd/main.go
  pkg/test/docker/registry/incluster.go
  pkg/test/framework/components/apiserver/apiserver.go
  pkg/test/framework/components/apps/kube/client.go
  pkg/test/framework/components/apps/kube/deployment.go
  pkg/test/framework/components/bookinfo/bookinfo.go
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/components/pilot/pilot.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/components/prometheus/prometheus.go
  pkg/test/framework/components/registry/registry.go
  pkg/test/framework/environments/kubernetes/implementation.go
  pkg/test/framework/environments/kubernetes/settings.go
  pkg/test/kube/accessor.go
  pkg/test/kube/config.go
  pkg/test/kube/kubectl.go
  pkg/test/kube/port_forwarder.go
  tests/e2e/tests/dashboard/dashboard_test.go
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#8886 Use a watcher to monitor CABundle in sidecar webhook
  pilot/cmd/sidecar-injector/main.go
Labels: approved, cla: yes, lgtm

#9343 Configure max message size received by mcp client
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  tests/util/pilot_server.go
Labels: approved, cla: yes, lgtm

#9331 Removed redundant map assignment
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: approved, cla: yes, lgtm

#8416 Add accessModes option to helm grafana chart
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/pvc.yaml
  install/kubernetes/helm/istio/charts/grafana/values.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9165 Incremental EDS - merge of 8722 from 1.0
  pilot/cmd/pilot-agent/status/util/listeners.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/multicluster.go
  pilot/pkg/config/clusterregistry/multicluster_test.go
  pilot/pkg/config/kube/crd/client.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/webhook_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/plugin/authz/rbac_test.go
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/client.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  pilot/pkg/serviceregistry/kube/pod.go
  pilot/pkg/serviceregistry/kube/pod_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pkg/adsc/adsc.go
Labels: approved, cla: yes

#9335 add rbac permissive mode attributes to request metrics
  install/kubernetes/helm/subcharts/mixer/templates/config.yaml
Labels: approved, cla: yes, lgtm

#9366 Racetest fix - Remove a redundant assignment of the push context
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: approved, cla: yes, lgtm

#8761 Fix wrong comment in pkg/test
  pkg/test/framework/components/apps/local/agent/pilot_agent.go
Labels: approved, cla: yes, lgtm

#9372 Fix lint errors due to recent changes
  bin/codecov.sh
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: cla: yes

#9342 Upgrade prom client_golang to 0.9.0
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/fnv.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
Labels: cla: yes

#9376 Add kube-inject configmap option
  tests/e2e/README.md
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#9365 Fix standalone Citadel yaml file
  install/kubernetes/citadel_extras/istio-citadel-standalone.yaml.tmpl
Labels: approved, cla: yes, lgtm

#9371 Update new Grafana charts location
  bin/check_dashboards.sh
Labels: approved, cla: yes, lgtm

#9328 Add REFRESH_GOLDEN functionality to HelmInject tests.
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/job.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/webhook_test.go
  pilot/test/util/diff.go
Labels: approved, cla: human-approved, cla: yes, lgtm

#9346 Split registry view based on requested networks
  Gopkg.lock
  install/kubernetes/helm/subcharts/gateways/values.yaml
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/serviceregistry/external/conversion.go
  vendor/istio.io/api/README.md
  vendor/istio.io/api/STYLE-GUIDE.md
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/policy/v1beta1/cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/policy/v1beta1/istio.policy.v1beta1.pb.html
  vendor/istio.io/api/policy/v1beta1/type.pb.go
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/gateway_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/service_entry_pb2.py
  vendor/istio.io/api/python/istio_api/policy/v1beta1/cfg_pb2.py
Labels: approved, cla: yes, lgtm

#9382 Fix failing test-integration-kubernetes
  tests/integration2/README.md
  tests/integration2/tests.mk
Labels: approved, cla: yes, lgtm

#9016 Remove dead metrics
  install/kubernetes/helm/subcharts/grafana/dashboards/pilot-dashboard.json
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: approved, cla: yes, lgtm

#9080 add istioctl validate command
  istioctl/cmd/istioctl/main.go
  istioctl/pkg/validate/validate.go
  istioctl/pkg/validate/validate_test.go
  pilot/pkg/config/kube/crd/conversion.go
Labels: approved, cla: yes, lgtm

#9401 fix build error: run dep ensure to add dependents
  Gopkg.lock
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme/scheme.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/builder_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/builder_flags_fake.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/config_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/config_flags_fake.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/doc.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/filename_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/io_options.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/json_yaml_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/jsonpath_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/kube_template_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/name_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/print_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/discard.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/interface.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/json.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/jsonpath.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/name.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/sourcechecker.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/template.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/typesetter.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/record_flags.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/builder.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/client.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/doc.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/fake.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/helper.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/interfaces.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/mapper.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/result.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/scheme.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/selector.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/template_flags.go
Labels: cla: yes

#9397 kube registry `GetProxyServiceInstances` optimization
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/util.go
  pilot/pkg/serviceregistry/kube/util_test.go
Labels: approved, cla: yes, lgtm

#9384 use ISTIO_METAJSON_ to json encode annotations
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/webhook_test.go
  pkg/bootstrap/bootstrap_config.go
  pkg/bootstrap/bootstrap_config_test.go
Labels: cla: yes

#8409 Specify resources for the proxy_init container
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/job.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
Labels: approved, cla: yes, lgtm

#9359 pilot constructs sdsconfig to enable envoy fetch/pass k8s sa jwt
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/plugin/authn/authentication.go
Labels: approved, cla: yes, lgtm

#9386 Fix release automation to update values.yaml correctly in release-1.0
  release/airflow/modify_values.sh
Labels: approved, cla: yes, lgtm

#9403 build: adjust GCP_OPTS format per gcloud reference guide
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm

#9408 [test-framework] reduce envoy log spam
  pkg/test/envoy/envoy.go
  pkg/test/framework/components/apps/local/agent/pilot_agent.go
  pkg/test/framework/components/apps/local/agent/pilot_agent_test.go
  pkg/test/framework/components/apps/local/apps.go
Labels: approved, cla: yes, lgtm

#9407 Skip pilot serviceregistry tests when not running on CI
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/kube/pod_test.go
Labels: approved, cla: yes, lgtm

#9419 Add variable for inlined Mutex
  pilot/pkg/config/clusterregistry/multicluster.go
  pilot/pkg/config/clusterregistry/multicluster_test.go
Labels: approved, cla: yes, lgtm

#9416 Update values.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9422 Remove duplicated nodeagent in chart requirements.yaml
  install/kubernetes/helm/istio/requirements.yaml
Labels: approved, cla: yes, lgtm

#9423 Added missing licenses to recently added files
  pkg/test/application/echo/batch.go
  pkg/test/application/echo/client.go
Labels: approved, cla: yes, lgtm

#9424 Temporarily disable the format linter
  Gopkg.lock
  bin/linters.sh
  galley/pkg/kube/interfaces.go
  galley/pkg/kube/interfaces_test.go
  istioctl/pkg/validate/validate.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/conversion.go
  pkg/test/application/echo/client.go
  pkg/test/framework/components/apps/local/agent/pilot_agent_test.go
  security/pkg/nodeagent/plugin/providers/google/iamclient.go
  tests/util/helm_utils.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/common.pb.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/iamcredentials.pb.go
Labels: approved, cla: yes, lgtm

#8703 Add retry to stackdriver adapter metrics push
  Gopkg.lock
  mixer/adapter/stackdriver/metric/bufferedClient.go
  mixer/adapter/stackdriver/metric/bufferedClient_test.go
  mixer/adapter/stackdriver/metric/metric.go
Labels: approved, cla: yes, lgtm

#9410 add metrics to galley/pkg/runtime
  galley/pkg/runtime/monitoring.go
  galley/pkg/runtime/processor.go
  galley/pkg/runtime/state.go
  galley/pkg/runtime/strategy.go
Labels: approved, cla: yes, lgtm

#9436 [Cherry-pick] Fix bad column name in mesh dashboard for TCP
  install/kubernetes/helm/subcharts/grafana/dashboards/istio-mesh-dashboard.json
Labels: approved, cla: yes, lgtm

#9175 rbac: adds a script to help users to upgrade to ClusterRbacConfig.
  tools/convert_RbacConfig_to_ClusterRbacConfig.sh
Labels: area/security/aaa, cla: yes
