Repository istio/istio, pull requests merged in 2018-04, with the labels that each got.

#4392 Fix bug in determining cluster version when running Ansible
  install/ansible/istio/tasks/main.yml
Labels: approved, cla: yes, lgtm

#3562 Merging iptables scripts
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
  istioctl/cmd/istioctl/inject.go
  pilot/docker/Dockerfile.proxy_init
  pilot/docker/prepare_proxy.sh
  pilot/docker/prepare_proxy_test.sh
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  tools/deb/istio-iptables.sh
  tools/istio-docker.mk
Labels: approved, area/environments, area/networking, cla: yes, kind/blocking release, kind/customer issue, kind/fixit, lgtm

#3856 update nodeSelector to affinity for chart to customize pod scheduling arch preference
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/zipkin/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/_affinity.tpl
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#4676 Add liamawhite back into istioctl approvers list
  istioctl/OWNERS
Labels: approved, cla: yes, lgtm

#4680 Add namespace to proxy-config examples
  istioctl/cmd/istioctl/config.go
Labels: approved, cla: yes, lgtm

#4640 Fix the bug that cert-chain.pem file does not have intermediate certs
  security/pkg/pki/ca/controller/secret.go
  security/pkg/pki/ca/controller/secret_test.go
Labels: approved, cla: yes, lgtm

#4663 Add files for https service example with istio
  samples/https/default.conf
  samples/https/nginx-app.yaml
Labels: approved, cla: yes, lgtm

#4672 Reconfigure mixer as a plugin, some cleanup
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/pkg/networking/util/util.go
Labels: approved, cla: yes, lgtm

#4637 Fix a racy test.
  mixer/adapter/list/list.go
  mixer/adapter/list/list_test.go
Labels: cla: yes

#4226 Update Mixer Envoy config to Report Mixer requests to Mixer itself
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
  pilot/docker/envoy_istio_policy.json
  pilot/docker/envoy_istio_policy_auth.json
  pilot/docker/envoy_istio_telemetry.json
  pilot/docker/envoy_istio_telemetry_auth.json
  pilot/docker/envoy_mixer.json
  pilot/docker/envoy_mixer_auth.json
  pilot/docker/mixer_bootstrap.sh
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/pilot/testdata/mixer.yaml.tmpl
  tests/e2e/tests/pilot/util/environment.go
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#4661 Update external k8s e2e test to work with 0.6.0
  tests/e2e_istio_preinstalled.sh
Labels: approved, cla: yes, lgtm

#4690 Ingress v2 fixes
  pilot/pkg/config/aggregate/config.go
  pilot/pkg/config/aggregate/config_test.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: human-approved

#4656 istio.io is the proper place to document Helm usage
  install/kubernetes/helm/README.md
Labels: approved, cla: yes, lgtm

#4697 Always generate request ids for mixer calls
  pilot/docker/envoy_istio_policy.json
  pilot/docker/envoy_istio_policy_auth.json
  pilot/docker/envoy_istio_telemetry.json
  pilot/docker/envoy_istio_telemetry_auth.json
Labels: approved, cla: yes, lgtm

#4699 Update mixer client tests to expect destionation.ip
  istio.deps
  mixer/test/client/auth/auth_test.go
  mixer/test/client/check_cache_hit/check_cache_hit_test.go
  mixer/test/client/check_report/check_report_test.go
  mixer/test/client/check_report_large_post_request/check_report_large_post_request_test.go
  mixer/test/client/failed_request/failed_request_test.go
  mixer/test/client/quota/quota_test.go
  mixer/test/client/quota_cache/quota_cache_test.go
  mixer/test/client/report_batch/report_batch_test.go
Labels: approved, cla: yes, lgtm

#4655 Add a Helm chart for remote Kubernetes clusters
  install/kubernetes/helm/istio-remote/Chart.yaml
  install/kubernetes/helm/istio-remote/templates/endpoints.yaml
  install/kubernetes/helm/istio-remote/templates/service.yaml
  install/kubernetes/helm/istio-remote/values.yaml
Labels: approved, cla: yes, lgtm

#4648 Ingest adapter info from into snapshot
  mixer/pkg/runtime/config/adapterInfo.go
  mixer/pkg/runtime/config/adapterInfo_test.go
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/const.go
  mixer/pkg/runtime/config/ephemeral.go
  mixer/pkg/runtime/config/kinds.go
  mixer/pkg/runtime/config/kinds_test.go
  mixer/pkg/runtime/config/monitoring.go
  mixer/pkg/runtime/config/snapshot.go
  mixer/pkg/runtime/config/strings.go
  mixer/pkg/runtime/config/testdata/adptCfg.descriptor
  mixer/pkg/runtime/config/testdata/adptCfg.proto
  mixer/pkg/runtime/config/testdata/badfoobar.descriptor
  mixer/pkg/runtime/config/testdata/bar.descriptor
  mixer/pkg/runtime/config/testdata/bar.proto
  mixer/pkg/runtime/config/testdata/baz.descriptor
  mixer/pkg/runtime/config/testdata/baz.proto
  mixer/pkg/runtime/config/testdata/foo.descriptor
  mixer/pkg/runtime/config/testdata/foo.proto
  mixer/pkg/runtime/config/testdata/reqOptionNotFound.descriptor
  mixer/pkg/runtime/config/testdata/reqOptionNotFound.proto
  mixer/pkg/runtime/config/testdata/reqOptionTmplNameNotFound.descriptor
  mixer/pkg/runtime/config/testdata/reqOptionTmplNameNotFound.proto
  mixer/pkg/runtime/config/testdata/unsupportedPkgName.descriptor
  mixer/pkg/runtime/config/testdata/unsupportedPkgName.proto
  mixer/template/sample/createinstance_test.go
Labels: approved, cla: yes, lgtm

#4707 Increase the lifetime of workload cert to 90 days
  security/cmd/istio_ca/main.go
  security/cmd/node_agent/main.go
Labels: approved, cla: yes, lgtm

#4708 Convert shortnames to FQDN during ingestion
  pilot/pkg/config/kube/crd/conversion.go
  pilot/pkg/model/config.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes

#4698 Restore defaults for istio-iptables.sh
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/auth.cert-dir.yaml.injected
  pilot/pkg/kube/inject/testdata/auth.non-default-service-account.yaml.injected
  pilot/pkg/kube/inject/testdata/auth.yaml.injected
  pilot/pkg/kube/inject/testdata/cronjob.yaml.injected
  pilot/pkg/kube/inject/testdata/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/enable-core-dump.yaml.injected
  pilot/pkg/kube/inject/testdata/format-duration.yaml.injected
  pilot/pkg/kube/inject/testdata/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-always.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-ignore.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-never.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/hello.yaml.injected
  pilot/pkg/kube/inject/testdata/job.yaml.injected
  pilot/pkg/kube/inject/testdata/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/list.yaml.injected
  pilot/pkg/kube/inject/testdata/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/single-initializer.yaml.injected
  pilot/pkg/kube/inject/testdata/statefulset.yaml.injected
  tests/e2e/tests/simple/testdata/nginx/nginx-injected.yaml.tmpl
  tools/deb/istio-iptables.sh
Labels: approved, cla: yes, lgtm

#4670 Switching to ADS
  .circleci/config.yml
  Makefile
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
  mixer/template/sample/createinstance_test.go
  mixer/test/client/env/envoy.go
  mixer/test/client/env/envoy_conf.go
  mixer/test/client/env/setup.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/memory/monitor.go
  pilot/pkg/model/config.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/proxy/envoy/v1/watcher.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/test/mock/config.go
  pkg/bootstrap/bootstrap_config.go
  pkg/bootstrap/bootstrap_config_test.go
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/pilot/controller_test.go
  tests/e2e/tests/simple/nginx_test.go
  tests/e2e/tests/simple/simple1_test.go
  tests/helm/templates/egress-rule-google.yaml
  tests/helm/templates/egress-rule-tcp-wikipedia-cidr.yaml
  tests/istio.mk
  tests/testdata/bootstrap_tmpl.json
  tests/testdata/ingress.yaml
  tools/deb/envoy_bootstrap_v2.json
Labels: cla: human-approved

#4727 use 1.10.1 golang for daily builds, tag istio/api/proxy for monthly releases
  release/cloud_build.template.json
  release/cloud_builder.sh
  release/cloud_publish.template.json
  release/cloud_tag.template.json
  release/create_tag_reference.sh
Labels: approved, cla: yes, lgtm

#4681 fail bag update if the proto carries different typed attributes with same name
  mixer/pkg/attribute/mutableBag.go
Labels: approved, cla: yes, lgtm

#4731 Updated default istio version to 0.7.1 for helm.
  istioctl/cmd/istioctl/gendeployment/cmd.go
Labels: approved, cla: yes, lgtm

#4734 Change apiversion for destination policies sample in bookinfo
  samples/bookinfo/kube/destination-policy-reviews.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#4298 refine pkg/probe tests
  pkg/probe/client.go
  pkg/probe/client_test.go
  pkg/probe/controller_test.go
  pkg/probe/option_test.go
Labels: approved, cla: yes, lgtm

#4736 nil pointer fixes in listeners
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/util/util.go
Labels: approved, cla: yes, lgtm

#4739 Ingress v2 temp fix: only process a single TLS spec
  pilot/pkg/config/kube/ingress/conversion.go
Labels: cla: yes

#4741 disable v1alpha3+v1 tests. Enable v1alpha3+v2 tests
  .circleci/config.yml
  prow/istio-pilot-e2e-v1alpha3.sh
  tests/istio.mk
Labels: cla: yes

#3746 Implementation of multicluster Istio CA.
  security/cmd/istio_ca/main.go
  security/cmd/multicluster_ca/main.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/controller/secret.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/probe/controller.go
  security/pkg/server/grpc/server.go
  security/pkg/server/grpc/server_test.go
Labels: approved, cla: yes, lgtm

#4711 Populate jwt output location for jwt filter.
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/proxy/envoy/v1/authentication.go
  pilot/pkg/proxy/envoy/v1/authentication_test.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/policy.go
  pilot/pkg/proxy/envoy/v1/testdata/lds-authn-jwt.json.golden
Labels: approved, cla: yes, lgtm

#4723 Add istioctl path in e2e script
  tests/e2e_istio_preinstalled.sh
Labels: approved, cla: yes, lgtm

#4740 Clean up multicluster CA binary.
  Makefile
  security/cmd/multicluster_ca/main.go
  security/docker/Dockerfile.multicluster-ca
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#4754 enable proxyv2 image for ingress+envoyv2
  .circleci/config.yml
  Makefile
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  install/kubernetes/helm/istio/values-istiotest.yaml
  tests/istio.mk
Labels: cla: yes

#4738 assorted fixes in pilot e2e tests
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/model/context.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/pilot/auth_exclusion_test.go
  tests/e2e/tests/pilot/authn_policy_test.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/grpc_test.go
  tests/e2e/tests/pilot/http_test.go
  tests/e2e/tests/pilot/ingress_test.go
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/tcp_test.go
  tests/e2e/tests/simple/nginx_test.go
  tests/util/common_utils.go
  tests/util/kube_utils.go
Labels: cla: yes

#4762 fix release script
  install/updateVersion.sh
Labels: approved, cla: yes, lgtm

#4630 extract spiffe id format into pki util.
  security/cmd/node_agent/management/server.go
  security/cmd/node_agent_k8s/nodeagent.yaml
  security/pkg/pki/util/san.go
  security/pkg/pki/util/san_test.go
  security/pkg/platform/gcp.go
  security/tests/integration/kubernetes_utils.go
Labels: approved, cla: yes, lgtm

#4742 Refresh adapter's logger model to match the pkg/log pattern.
  mixer/adapter/fluentd/fluentd.go
  mixer/adapter/memquota/dedup.go
  mixer/adapter/memquota/memquota.go
  mixer/adapter/prometheus/prometheus.go
  mixer/adapter/redisquota/redisquota.go
  mixer/adapter/servicecontrol/checkprocessor.go
  mixer/adapter/servicecontrol/quotaprocessor.go
  mixer/adapter/servicecontrol/reportprocessor.go
  mixer/adapter/servicecontrol/utils.go
  mixer/adapter/stackdriver/metric/metric.go
  mixer/pkg/adapter/adapter.go
  mixer/pkg/adapter/test/env.go
  mixer/pkg/runtime/handler/env.go
  mixer/pkg/runtime/handler/env_test.go
  mixer/pkg/runtime/handler/logger.go
  pkg/log/config.go
Labels: cla: yes, lgtm

#4774 bug fix for change in default port
  install/consul/templates/istio.yaml.tmpl
  install/eureka/templates/istio.yaml.tmpl
Labels: approved, cla: yes, kind/customer issue, kind/fixit, lgtm

#4775 default mesh bug fix
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, kind/customer issue, kind/fixit

#4757 Add authentication filter to listener filters chain.
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/proxy/envoy/v1/authentication.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/testdata/lds-authn-jwt.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optin.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-weighted-auth.json.golden
Labels: approved, cla: yes, lgtm

#4782 Try to avoid people changing .gitmodules accidentally (or otherwise)
  .gitignore
Labels: approved, cla: yes, lgtm

#4780 Add make init and switch test version
  tests/e2e_istio_preinstalled.sh
Labels: approved, cla: yes, lgtm

#4785 Make makefile format and linter consistent using the fmt.sh
  Makefile
  addons/grafana/dashboards/mixer-dashboard.json
  addons/grafana/fix_datasources.sh
  bin/fmt.sh
  bin/linters.sh
  galley/pkg/crd/synchronizer.go
  galley/pkg/crd/synchronizer_test.go
  istioctl/cmd/istioctl/main.go
  istioctl/pkg/convert/destination.go
  lintconfig_base.json
  mixer/pkg/adapter/test/integration.go
  mixer/pkg/config/crd/admit.go
  mixer/pkg/runtime/config/adapterInfo.go
  mixer/template/sample/createinstance_test.go
  pilot/cmd/pilot-agent/debug.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/aggregate/config.go
  pilot/pkg/config/monitor/copilot_snapshot_test.go
  pilot/pkg/config/monitor/fakes/copilot_client.go
  pilot/pkg/config/monitor/monitor_test.go
  pilot/pkg/kube/admit/admit.go
  pilot/pkg/kube/admit/admit_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  pkg/bootstrap/bootstrap_config.go
  security/cmd/node_agent/management/server.go
  security/cmd/node_agent_k8s/main.go
  security/pkg/caclient/client.go
  security/pkg/platform/onprem.go
  security/pkg/workload/secretfileserver.go
  security/pkg/workload/secretserver_test.go
  tests/e2e/tests/pilot/a_zipkin_test.go
  tests/e2e/tests/pilot/controller_test.go
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/simple/nginx_test.go
  tests/util/pilot_server.go
Labels: approved, cla: yes, lgtm

#4747 Helm templates for Ingress/Egress gateways + e2e v2 fixes
  Makefile
  install/kubernetes/helm/istio/charts/egress-gateway/Chart.yaml
  install/kubernetes/helm/istio/charts/egress-gateway/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/egress-gateway/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/egress-gateway/templates/service.yaml
  install/kubernetes/helm/istio/charts/egress-gateway/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/ingress-gateway/Chart.yaml
  install/kubernetes/helm/istio/charts/ingress-gateway/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/ingress-gateway/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress-gateway/templates/service.yaml
  install/kubernetes/helm/istio/charts/ingress-gateway/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  install/kubernetes/helm/istio/values.yaml
  tests/e2e/tests/pilot/ingress/controller_test.go
  tests/e2e/tests/pilot/ingress/main_test.go
  tests/e2e/tests/pilot/ingress_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/istio.mk
Labels: cla: yes

#4674 Ansible replace stale readme
  install/ansible/README.md
Labels: approved, cla: yes, lgtm

#4789 remove hyphen from gateway helm
  install/kubernetes/helm/istio/charts/egressgateway/Chart.yaml
  install/kubernetes/helm/istio/charts/egressgateway/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/egressgateway/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/egressgateway/templates/service.yaml
  install/kubernetes/helm/istio/charts/egressgateway/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/Chart.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/templates/service.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#4750 Remove v1alpha3 from v1
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/config_test.go
  pilot/pkg/proxy/envoy/v1/discovery.go
  pilot/pkg/proxy/envoy/v1/discovery_test.go
  pilot/pkg/proxy/envoy/v1/externalservice.go
  pilot/pkg/proxy/envoy/v1/fault.go
  pilot/pkg/proxy/envoy/v1/gateway.go
  pilot/pkg/proxy/envoy/v1/gateway_test.go
  pilot/pkg/proxy/envoy/v1/header.go
  pilot/pkg/proxy/envoy/v1/ingress.go
  pilot/pkg/proxy/envoy/v1/mock/discovery.go
  pilot/pkg/proxy/envoy/v1/policy.go
  pilot/pkg/proxy/envoy/v1/resources.go
  pilot/pkg/proxy/envoy/v1/route.go
  pilot/pkg/proxy/envoy/v1/testdata/addheaders-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/cb-route-rule-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/corspolicy-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/destination-hello-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/destination-world-cb-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/destination-world-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-route-rule.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-rule-dns-no-endpoints.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-rule-dns.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-rule-static.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-rule-tcp-dns.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-rule-tcp-static.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-rule-tcp.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/external-service-rule.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/fault-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/gateway-route-2.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway-route.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway-weighted-route.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway-wildcard-route.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway-wildcard.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway2.yaml
  pilot/pkg/proxy/envoy/v1/testdata/google-timeout-rule-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/mirror-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/multi-match-fault-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/multi-match-rewrite-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-multi-match-rewrite-v1alpha3.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/redirect-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/rewrite-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/subset-google-cb-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/subset-google-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/timeout-route-rule-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/websocket-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/weighted-route-v1alpha3.yaml.golden
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, area/networking, cla: yes, lgtm

#4769 Fix bug for external access in ADS v2
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: cla: yes

#4752 fixed a typo: include -> exclude
  istioctl/cmd/istioctl/inject.go
Labels: cla: yes

#4718 Mixer filter fixes
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/pkg/proxy/envoy/v1/mixer.go
Labels: approved, cla: yes, lgtm

#4792 Check mTLS params for nil before use
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes

#4759 Update to latest supported GKE version
  install/gcp/deployment_manager/istio-cluster.jinja
Labels: approved, cla: yes, lgtm

#4786 Setup for automatic 8 perf scenarios (400 and maxqps, cache/nocache, ing/direct)
  tools/setup_perf_cluster.sh
Labels: cla: yes, lgtm

#4802 Update cd to be relative to script
  tests/e2e_istio_preinstalled.sh
Labels: approved, cla: yes, lgtm

#4753 Hook up jwt and authn filter for v2. Move tls context code to authn plugin.
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: approved, cla: yes, lgtm

#4813 Fix debug dump and change of envoy admin API
  pilot/cmd/pilot-agent/debug.go
  pilot/cmd/pilot-agent/debug_test.go
Labels: approved, cla: yes, lgtm

#4675 Jaeger cleanup in Ansible installation
  install/ansible/istio/defaults/main.yml
  install/ansible/istio/tasks/install_istio_addons.yml
Labels: approved, cla: yes, lgtm

#4657 make TestOddballs of log module robust
  pkg/log/log_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#4667 Upgrade test: increase retry times and add more check
  install/kubernetes/webhook-create-signed-cert.sh
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/upgrade/upgrade_test.go
Labels: approved, cla: yes, lgtm

#4816 Fix zone look up in mtls envs
  pilot/pkg/proxy/envoy/v1/watcher.go
Labels: cla: yes

#4818 Source based route match
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/proxy/envoy/v2/ads.go
  security/pkg/caclient/protocol/protocol.go
Labels: cla: yes

#4804 logging error that would otherwise be eaten and lost
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: approved, cla: yes, lgtm

#4714 Add jianfei to security/OWNERS
  security/OWNERS
Labels: approved, cla: yes, lgtm

#4748 Move plugin certs to better location.
  samples/certs/ca-cert.pem
  samples/certs/ca-key.pem
  samples/certs/cert-chain.pem
  samples/certs/root-cert.pem
  security/samples/plugin_ca_certs/gen_certs.sh
Labels: approved, cla: yes, lgtm

#4772 Add dumb Vault adapter complying with CA interface.
  security/pkg/adapter/vault/ca.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/controller/secret.go
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/mock/fakekeycertbundle.go
  security/pkg/server/grpc/server.go
  security/pkg/server/grpc/server_test.go
Labels: approved, cla: yes, lgtm

#4735 Fix istio-proxy imagePullPolicy setting in pilot's helm chart
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#4682 Defaults user id to 1337, honoring docs, instead of failing
  tools/deb/istio-iptables.sh
Labels: approved, cla: yes, lgtm

#4807 Clean up files generated by node agent unit tests.
  security/cmd/node_agent/na/nodeagent_test.go
Labels: approved, cla: yes, lgtm

#4827 Prune CA interface.
  security/cmd/istio_ca/main.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/controller/secret.go
  security/pkg/pki/ca/controller/secret_test.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/probe/controller.go
  security/pkg/server/grpc/server.go
  security/pkg/server/grpc/server_test.go
Labels: approved, cla: yes, lgtm

#4833 Disable TestVMExtendsIstio that is not critical for 0.8.0
  tests/e2e/tests/bookinfo/demo_test.go
Labels: approved, cla: yes, lgtm

#4487 We should not set container/use_client_certificate if we disable legacy authorization
  DEV-GUIDE.md
Labels: cla: yes, needs-ok-to-test

#4808 Support multiple host names for istio ca grpc server.
  security/cmd/istio_ca/main.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/verify_cert.go
  security/pkg/server/grpc/server.go
  security/pkg/server/grpc/server_test.go
Labels: approved, cla: yes, lgtm

#4828 Fix data race in server_test.go
  mixer/pkg/server/server_test.go
Labels: cla: yes

#4629 Add files generated by `make test` to .gitignore
  .gitignore
Labels: approved, cla: yes, lgtm

#4829 Mixer route config
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/route/route.go
  pilot/pkg/networking/util/util.go
Labels: cla: yes

#4793 Yaml to bytes converter
  codecov.requirement
  mixer/pkg/protobuf/descriptor/parser.go
  mixer/pkg/protobuf/yaml/encoder.go
  mixer/pkg/protobuf/yaml/encoder_test.go
  mixer/pkg/protobuf/yaml/pool.go
  mixer/pkg/protobuf/yaml/resolver.go
  mixer/pkg/protobuf/yaml/testdata/all/foo.pb.html
  mixer/pkg/protobuf/yaml/testdata/all/types.descriptor
  mixer/pkg/protobuf/yaml/testdata/all/types.pb.go
  mixer/pkg/protobuf/yaml/testdata/all/types.proto
  mixer/tools/codegen/pkg/bootstrapgen/generator.go
  mixer/tools/codegen/pkg/bootstrapgen/generator_test.go
  mixer/tools/codegen/pkg/interfacegen/generator.go
  mixer/tools/codegen/pkg/modelgen/model.go
  mixer/tools/codegen/pkg/modelgen/model_test.go
Labels: approved, cla: yes, lgtm

#4781 Use kubectl 1.9.6 in GCP Deployment Manager install
  install/gcp/deployment_manager/istio-cluster.jinja
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#4846 fix alt virtual host generation
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: cla: yes

#4815 Creates a remote connection for multicluster e2e
  tests/e2e/framework/app_manager.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/kubernetes.go
  tests/e2e/framework/testInfo.go
  tests/e2e/tests/bookinfo/demo_test.go
  tests/e2e/tests/dashboard/dashboard_test.go
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/pilot/authn_policy_test.go
  tests/e2e/tests/pilot/egress_rules_test.go
  tests/e2e/tests/pilot/ingress_test.go
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/kubernetes_external_name_services_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/routing_to_egress_test.go
  tests/e2e/tests/simple/a_simple_1_test.go
  tests/e2e/tests/simple/nginx_test.go
  tests/e2e/tests/upgrade/upgrade_test.go
  tests/util/kube_utils.go
Labels: approved, cla: yes, lgtm

#4706 Refactor cluster registry to use Secret to store kubeconf
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/clusterconfig.gotmpl
  pilot/pkg/config/clusterregistry/clusterregistry.gotmpl
  pilot/pkg/config/clusterregistry/conversion.go
  pilot/pkg/config/clusterregistry/conversion_test.go
  pilot/pkg/serviceregistry/kube/client.go
Labels: approved, cla: yes, lgtm

#4884 Fixes a build breakage due to 4815 and 4706
  pilot/pkg/config/clusterregistry/conversion_test.go
  tests/e2e/framework/kubernetes.go
  tests/util/kube_utils.go
Labels: approved, cla: yes, lgtm

#4894 Fix a pointer failure and adding test
  security/pkg/pki/testdata/self-signed-root-cert.pem
  security/pkg/pki/testdata/workload-cert.pem
  security/pkg/pki/testdata/workload-key.pem
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
Labels: approved, cla: yes, lgtm

#4886 quick fix for flaky TestMixerReportingToMixer
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#4850 Add per-sidecar config dump to ADS debug
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, cla: yes

#4843 Rename istio-ca service/image to citadel.
  .gitignore
  DEV-GUIDE.md
  Makefile
  bin/istio-proxy-cfg.py
  install/README.md
  install/kubernetes/helm/istio/charts/security/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/security/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/service.yaml
  install/kubernetes/helm/istio/charts/security/templates/serviceaccount.yaml
  install/kubernetes/mesh-expansion.yaml
  install/kubernetes/templates/istio-citadel-one-namespace.yaml.tmpl
  install/kubernetes/templates/istio-citadel-plugin-certs.yaml.tmpl
  install/kubernetes/templates/istio-citadel-with-health-check.yaml.tmpl
  install/kubernetes/templates/istio-citadel.yaml.tmpl
  install/tools/setupMeshEx.sh
  install/updateVersion_orig.sh
  security/bin/e2e.sh
  security/cmd/istio_ca/main.go
  security/cmd/node_agent/main.go
  security/cmd/node_agent_k8s/main.go
  security/cmd/node_agent_k8s/nodeagent.yaml
  security/docker/Dockerfile.citadel
  security/docker/Dockerfile.citadel-test
  security/tests/integration/istio_ca_cert_rotation_env.go
  security/tests/integration/istio_ca_node_agent_env.go
  security/tests/integration/istio_ca_secret_env.go
  tests/e2e/framework/kubernetes.go
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#4893 enable cf copilot tests for v2
  .circleci/config.yml
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#4851 Update proxy sha to 04/10
  istio.deps
  mixer/test/client/disable_tcp_check_calls/disable_tcp_check_calls_test.go
  mixer/test/client/tcp_filter/tcp_filter_test.go
  mixer/test/client/tcp_filter_periodical_report/tcp_filter_periodical_report_test.go
  mixer/test/client/tcp_filter_v1_config/tcp_filter_v1_config_test.go
Labels: cla: yes, lgtm

#4800 Wire in TCP support to Gateways.
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/e2e/tests/pilot/testdata/v1alpha3/gateway-tcp-a.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-force-a-through-ingress-gateway.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-gateway-a.yaml
  tests/istio.mk
Labels: cla: yes

#4902 Add more test coverage
  security/pkg/pki/ca/controller/secret_test.go
  security/pkg/pki/util/keycertbundle_test.go
Labels: approved, cla: yes, lgtm

#4832 Release qualifications do not rebuild artifacts
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#4875 Add Connection Pool settings on the inbound path
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes

#4905 Add back skipped tests
  security/pkg/platform/aws_test.go
Labels: approved, cla: yes, lgtm

#4901 Trim test output
  .circleci/config.yml
  tests/util/kube_utils.go
Labels: cla: yes

#4831 Skip missed builds
  release/pipeline/dags/istio_common_dag.py
Labels: approved, cla: yes, lgtm

#4857 Add version skew test to e2e test suite
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#4907 Move pkg/server/grpc to pkg/server/ca.
  security/cmd/istio_ca/main.go
  security/pkg/server/ca/authenticator.go
  security/pkg/server/ca/authenticator_test.go
  security/pkg/server/ca/authorizer.go
  security/pkg/server/ca/authorizer_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: approved, cla: yes, lgtm

#4919 Make istio-certs required for istio pilot deployment
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#4891 Add debug tool to get xDS config for a sidecar
  lintconfig_base.json
  pilot/tools/debug/pilot_cli.go
Labels: approved, cla: yes, lgtm

#4921 Pilot crashes due to unpopulated clusters
  pilot/pkg/config/clusterregistry/conversion.go
Labels: approved, cla: yes, lgtm

#4890 target istio-telemetry from mixer ilb and update dnsmasq config
  install/kubernetes/mesh-expansion.yaml
  install/tools/setupMeshEx.sh
Labels: approved, cla: yes, lgtm

#4836 Add root cert to node agent server when creating KeyCertBundle.
  security/cmd/node_agent/management/server.go
  security/cmd/node_agent/management/server_test.go
  security/cmd/node_agent/na/config.go
  security/cmd/node_agent_k8s/main.go
  security/cmd/node_agent_k8s/nodeagent.yaml
  security/cmd/node_agent_k8s/workload/handler/workloadhandler.go
  security/cmd/node_agent_k8s/workload_app/workload.yaml
Labels: approved, cla: yes, lgtm

#4914 Remove EUC policy
  istioctl/cmd/istioctl/convert/cmd.go
  istioctl/cmd/istioctl/main.go
  mixer/test/client/auth/auth_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/types.go
  pilot/pkg/model/config.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/config_test.go
  pilot/pkg/proxy/envoy/v1/discovery_test.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/testdata/auth-spec-binding.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/auth-spec.yaml-binding.golden
  pilot/test/mock/config.go
Labels: approved, cla: yes, lgtm

#4943 Move our docs to the Wiki.
  DEV-CONVENTIONS.md
  DEV-GUIDE.md
  DEV-PERF.md
  DEV-TROUBLESHOOTING.md
  ON-CALL.md
  README.md
  mixer/doc/adapter-development-walkthrough.md
  mixer/doc/adapters.md
  mixer/doc/deploy-mixer-with-custom-adapter.md
  mixer/doc/img/example attr to instance.svg
  mixer/doc/img/example instance to type.svg
  mixer/doc/img/handler config.svg
  mixer/doc/img/logo.png
  mixer/doc/img/mixer adapter flow.svg
  mixer/doc/img/mixer architecture.svg
  mixer/doc/img/mixer start flow.svg
  mixer/doc/img/operator config change.svg
  mixer/doc/img/operator template adapter dev.svg
  mixer/doc/img/request time.svg
  mixer/doc/img/template generated artifacts.svg
  mixer/doc/img/template, adapter and operator config relationship.svg
  mixer/doc/running-local-mixer.md
  mixer/doc/templates.md
Labels: cla: yes

#4645 Introduce the custom resource synchronizer
  codecov.requirement
  galley/pkg/resource/accessor.go
  galley/pkg/resource/accessor_test.go
  galley/pkg/resource/equals.go
  galley/pkg/resource/equals_test.go
  galley/pkg/resource/inject.go
  galley/pkg/resource/operations.go
  galley/pkg/resource/operations_test.go
  galley/pkg/resource/rewrite.go
  galley/pkg/resource/rewrite_test.go
  galley/pkg/resource/synchronizer.go
  galley/pkg/resource/synchronizer_test.go
  galley/pkg/testing/common/mocklog.go
Labels: approved, cla: yes, lgtm

#4948 Remove stale docs
  pilot/README.md
  pilot/doc/design.md
  pilot/doc/pilot.svg
  pilot/doc/proxy-controller.md
  pilot/doc/proxy-redirection-configuration.md
  pilot/doc/service-registry.md
  tools/minikube.md
Labels: cla: yes

#4855 Test external service parity with egress rules
  pilot/pkg/model/egress_rules.go
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/eureka/conversion.go
  pilot/pkg/serviceregistry/external/controller.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  tests/e2e/tests/pilot/externalservice_test.go
  tests/e2e/tests/pilot/testdata/v1alpha3/externalservice-httpbin.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/externalservice-nghttp2.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/externalservice-tcp-wikipedia-cidr.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/externalservice-wildcard-httpbin.yaml
Labels: area/networking, cla: yes, lgtm

#4773 Cleanup to make it running on mac
  .circleci/mc-config
  Makefile
  bin/init.sh
  bin/testEnvLocalK8S.sh
  pilot/pkg/config/clusterregistry/clusterconfig.gotmpl
  tests/local/cluster_registry_test.go
  tests/local/xds_local_test.go
  tests/testdata/envoy_local.json
  tests/testdata/multicluster/envoy_local_v2.yaml
Labels: approved, cla: yes, lgtm

#4950 Refactor Galley entrypoint/test code for better mock injection
  galley/pkg/common/kube.go
  galley/pkg/crd/inject.go
  galley/pkg/crd/operations.go
  galley/pkg/crd/operations_test.go
  galley/pkg/crd/synchronizer.go
  galley/pkg/crd/synchronizer_test.go
  galley/pkg/resource/accessor.go
  galley/pkg/resource/accessor_test.go
  galley/pkg/resource/inject.go
  galley/pkg/resource/operations.go
  galley/pkg/resource/operations_test.go
  galley/pkg/resource/synchronizer.go
  galley/pkg/resource/synchronizer_test.go
  galley/pkg/testing/mock/kube.go
Labels: approved, cla: yes, lgtm

#4953 Update istio-remote to match mixer rename
  install/kubernetes/helm/istio-remote/templates/endpoints.yaml
  install/kubernetes/helm/istio-remote/templates/service.yaml
  install/kubernetes/helm/istio-remote/values.yaml
Labels: approved, cla: yes, lgtm

#4939 Introduce logging scopes.
  mixer/adapter/stdio/stdio.go
  mixer/adapter/stdio/stdio_test.go
  mixer/adapter/stdio/zap.go
  mixer/cmd/mixs/main.go
  mixer/pkg/api/grpcServer_test.go
  mixer/pkg/attribute/bag_test.go
  mixer/pkg/attribute/mutableBag.go
  mixer/pkg/attribute/protoBag.go
  mixer/pkg/perf/server.go
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/handler/logger.go
  pkg/log/config.go
  pkg/log/config_test.go
  pkg/log/default.go
  pkg/log/default_test.go
  pkg/log/log.go
  pkg/log/options.go
  pkg/log/options_test.go
  pkg/log/scope.go
  pkg/log/scope_test.go
Labels: cla: yes

#4955 Add loadBalancerIP to istio-ingress service in Helm chart
  install/kubernetes/helm/istio/charts/ingress/templates/service.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#4949 Remove stale script
  pilot/docker/mixer_bootstrap.sh
Labels: approved, cla: yes, lgtm

#4962 Mc install - enable secrets consumption
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#4730 Enable istio work offline.
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/enable-core-dump.yaml.injected
Labels: approved, cla: yes, lgtm

#4932 fix sidecar-injector command usage spelling error
  pilot/cmd/sidecar-injector/main.go
Labels: approved, cla: yes, lgtm

#4968 Try routing via ext svc in egress gateway
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-route-via-egressgateway.yaml
Labels: cla: yes, lgtm

#4931 support all proto types for converting yaml+descriptor into proto bytes
  mixer/pkg/protobuf/descriptor/parser.go
  mixer/pkg/protobuf/yaml/castUtil.go
  mixer/pkg/protobuf/yaml/castUtil_test.go
  mixer/pkg/protobuf/yaml/encoder.go
  mixer/pkg/protobuf/yaml/encoder_test.go
  mixer/pkg/protobuf/yaml/resolver.go
  mixer/pkg/protobuf/yaml/testdata/all/foo.pb.html
  mixer/pkg/protobuf/yaml/testdata/all/types.descriptor
  mixer/pkg/protobuf/yaml/testdata/all/types.pb.go
  mixer/pkg/protobuf/yaml/testdata/all/types.proto
Labels: approved, cla: yes, lgtm

#4961 Fix key and cert paths for listener TLS context.
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: approved, cla: yes, lgtm

#4923 Additional cleanup, more defaults for easier setup.
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/config/clusterregistry/conversion.go
  pilot/pkg/config/clusterregistry/conversion_test.go
Labels: cla: human-approved, cla: no

#4978 Eliminate test race conditions.
  pkg/log/config.go
  pkg/log/config_test.go
  pkg/log/default.go
  pkg/log/default_test.go
  pkg/log/scope.go
  pkg/log/scope_test.go
Labels: cla: yes

#4984 Redoing 4877, vendor fix part 2
  security/pkg/adapter/vault/ca.go
  security/pkg/adapter/vault/testdata/istio_ca.pem
  security/pkg/adapter/vault/testdata/workload-1.csr
Labels: cla: yes, lgtm

#4927 Update proxy SHA to 04/11
  istio.deps
Labels: approved, cla: yes, lgtm

#4992 Add standalone Citadel deployment.
  install/kubernetes/templates/istio-citadel-standalone.yaml.tmpl
  install/updateVersion_orig.sh
Labels: approved, cla: yes, lgtm

#4910 additional gateway tests for v2/v1alpha3
  .circleci/config.yml
  pilot/test/client/client.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-destinationrule-c-add-subset.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-destinationrule-c-del-subset.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-destinationrule-c.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-update-virtualservice.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-virtualservice.yaml
Labels: cla: yes

#4975 Implement support for multiple filter chains, SNI with multiple certs
  pilot/pkg/model/config.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-ingressgateway.yaml
Labels: cla: yes

#4936 Small optimization on pilot and tests startup.
  pilot/pkg/config/kube/crd/client.go
  tests/e2e/tests/pilot/controller_test.go
Labels: cla: yes

#4966 Enable sidecar auto injection use proxy_init as initContainer.
  install/kubernetes/templates/istio-sidecar-injector-configmap-debug.yaml.tmpl
Labels: approved, cla: yes, lgtm

#4944 use consistent service name in zipkin helm chart
  install/kubernetes/helm/istio/charts/zipkin/templates/NOTES.txt
  install/kubernetes/helm/istio/charts/zipkin/templates/ingress.yaml
Labels: approved, cla: yes, lgtm

#5001 Fix problems around level enablement for logs captured from glog
  pkg/log/config.go
  pkg/log/config_test.go
  pkg/log/options.go
Labels: approved, cla: yes, lgtm

#4942 fix extraneous newline in istioctl kube-injected yamls
  install/kubernetes/templates/istio-sidecar-injector-configmap-debug.yaml.tmpl
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/enable-core-dump.yaml.injected
  pilot/pkg/kube/inject/testdata/not-required.yaml.injected
  pilot/pkg/kube/inject/testdata/single-initializer.yaml.injected
Labels: approved, cla: yes, lgtm

#5019 Improve error reporting for proxy-config command
  istioctl/cmd/istioctl/config.go
Labels: approved, cla: yes, lgtm

#4995 Rename Istio CA to Citadel
  install/kubernetes/templates/istio-citadel-one-namespace.yaml.tmpl
  install/kubernetes/templates/istio-citadel-plugin-certs.yaml.tmpl
  install/kubernetes/templates/istio-citadel-standalone.yaml.tmpl
  install/kubernetes/templates/istio-citadel-with-health-check.yaml.tmpl
  install/kubernetes/templates/istio-citadel.yaml.tmpl
  install/kubernetes/templates/istio-rbac-beta.yaml.tmpl
  install/tools/setupMeshEx.sh
  install/updateVersion_orig.sh
  security/cmd/node_agent_k8s/nodeagent.yaml
Labels: approved, cla: yes, lgtm

#5025 Delete blank .gitmodules file
  .gitmodules
Labels: cla: yes

#4946 SecretFileServer stores all key, cert, root and add unit tests.
  security/cmd/node_agent/management/server.go
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
  security/pkg/workload/secretfileserver.go
  security/pkg/workload/secretserver.go
  security/pkg/workload/secretserver_test.go
  security/pkg/workload/server.go
Labels: approved, cla: yes, lgtm

#4892 Keep original JWT after validation (jwt filter)
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/proxy/envoy/v1/authentication_test.go
  pilot/pkg/proxy/envoy/v1/testdata/lds-authn-jwt.json.golden
Labels: approved, cla: yes, lgtm

#5031 Fixing Linting errors detected on master
  pilot/pkg/kube/inject/webhook_test.go
  pilot/pkg/proxy/envoy/v1/config_test.go
  pkg/log/config_test.go
  pkg/log/options.go
  pkg/log/scope.go
  tests/e2e/tests/pilot/ingressgateway_test.go
Labels: approved, cla: yes, lgtm

#4834 get jwks_uri from openid discovery if it's not set inside auth policy
  pilot/pkg/model/authentication.go
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/model/jwks_resolver_test.go
  pilot/pkg/model/test/mockopenidserver.go
  pilot/pkg/model/validation.go
Labels: approved, cla: yes, lgtm

#5034 Do not add jwt and authn filter for TCP listener type
  pilot/pkg/networking/plugin/authn/authentication.go
Labels: cla: yes

#4493 istioctl: fix default namespace handling for (de)register commands
  istioctl/cmd/istioctl/deregister.go
  istioctl/cmd/istioctl/register.go
Labels: approved, cla: yes, lgtm

#4957 Removed duplicate core v1 import.
  pilot/pkg/kube/inject/inject.go
Labels: approved, cla: yes, lgtm

#4896 Support multiple route rules versions in Bookinfo e2e tests
  samples/bookinfo/kube/route-rule-reviews-80-20.yaml
  samples/bookinfo/kube/route-rule-reviews-90-10.yaml
  samples/bookinfo/routing/route-rule-reviews-80-20.yaml
  samples/bookinfo/routing/route-rule-reviews-90-10.yaml
  tests/e2e/framework/test_flags.go
  tests/e2e/framework/test_flags_test.go
  tests/e2e/tests/bookinfo/demo_test.go
  tests/e2e/tests/bookinfo/main_test.go
Labels: cla: yes

#5018 Remove ForCA from CsrRequest.
  security/cmd/node_agent/na/nodeagent.go
  security/pkg/caclient/client.go
  security/proto/ca_service.pb.go
  security/proto/ca_service.proto
Labels: approved, cla: yes, lgtm

#4988 Correct IP for pilot debug tool.
  pilot/tools/debug/pilot_cli.go
Labels: approved, cla: yes, lgtm

#5048 Remove vendor files from .gitignore
  .gitignore
Labels: approved, cla: yes, lgtm

#5053 update Go control plane
  Gopkg.lock
  vendor/github.com/envoyproxy/go-control-plane/envoy/admin/v2/config_dump.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/auth/cert.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/cds.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/address.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/health_check.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/health_check.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/http_uri.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/http_uri.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint/endpoint.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint/endpoint.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/lds.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/lds.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/accesslog/v2/accesslog.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/accesslog/v2/accesslog.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/ext_authz/v2/ext_authz.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/ext_authz/v2/ext_authz.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/health_check/v2/health_check.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/health_check/v2/health_check.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/transcoder/v2/transcoder.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/transcoder/v2/transcoder.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/tcp_proxy/v2/tcp_proxy.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/metrics/v2/stats.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/metrics/v2/stats.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/attribute_context.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/attribute_context.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/external_auth.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/external_auth.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/glide.lock
  vendor/github.com/envoyproxy/go-control-plane/glide.yaml
  vendor/github.com/envoyproxy/go-control-plane/pkg/test/server.go
Labels: approved, cla: yes, lgtm

#5050 updated istio/api repo version
  Gopkg.lock
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
  vendor/istio.io/api/mixer/adapter/model/v1beta1/type.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/type.proto
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/external_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/external_service.proto
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/adapter/model/v1beta1/type_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
  vendor/istio.io/api/routing/v1alpha1/istio.routing.v1alpha1.pb.html
  vendor/istio.io/api/routing/v1alpha1/route_rule.proto
Labels: approved, cla: yes, lgtm

#5042 cleanup unused files
  prow/istio-pilot-e2e-v1alpha3.sh
Labels: approved, cla: yes, lgtm

#5035 Don't build anything in the init phase
  bin/init.sh
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#5012 Mixer filter fixes
  install/kubernetes/helm/istio/charts/mixer/templates/service.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes
