Repository istio/istio, pull requests merged in 2018-06, with the labels that each got.

#5961 Make ci2gubernator unblocking
  bin/ci2gubernator.sh
Labels: approved, cla: yes, lgtm

#5805 [test-framework] Implement Mixer related infrastructure for local environment.
  pkg/test/fakes/policy/backend.go
  pkg/test/fakes/policy/controller.go
  pkg/test/fakes/policy/controller.pb.go
  pkg/test/fakes/policy/controller.proto
  pkg/test/fakes/policy/conversion.go
  pkg/test/fakes/policy/settings.go
  pkg/test/local/environment.go
  pkg/test/local/mixer.go
  pkg/test/local/policybackend.go
  tests/e2e/tests/showcase/mixer_showcase_test.go
  tests/e2e/tests/showcase/showcase_test.go
Labels: cla: yes, lgtm

#5966 add require tiller version for kiali addon.
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
Labels: approved, cla: yes, lgtm

#5967 add README file to chart.
  install/kubernetes/helm/istio-remote/README.md
  install/kubernetes/helm/istio/README.md
Labels: cla: yes, lgtm

#5973 Preserve Ingress namespace in generated Gateway and VS
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/merged-gateway.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/myservice-gateway.yaml.golden
  istioctl/pkg/convert/ingress.go
Labels: approved, cla: yes, lgtm

#5179 Handle GOPATH with multiple paths
  Makefile
  bin/testEnvLocalK8S.sh
Labels: approved, cla: yes, lgtm

#5758 Fix broken mixer develop document link.
  mixer/README.md
Labels: approved, cla: yes, lgtm

#5798 Allow downstream to change the location of the root ca bundle file
  pilot/pkg/model/jwks_resolver.go
Labels: approved, cla: yes, lgtm

#5890 Remove mTLS enablement via service annotation.
  install/kubernetes/helm/istio/charts/grafana/templates/service.yaml
  install/kubernetes/templates/addons/grafana.yaml.tmpl
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/service.go
  pilot/pkg/proxy/envoy/v1/config_test.go
  pilot/pkg/proxy/envoy/v1/mock/discovery.go
  pilot/pkg/proxy/envoy/v1/mock/discovery_test.go
  pilot/pkg/proxy/envoy/v1/testdata/authn-hello-mtls-on.yaml.golden
  pilot/pkg/proxy/envoy/v1/testdata/authn-world-mtls-on.yaml.golden
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/consul/conversion_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  tests/e2e/tests/pilot/authn_policy_test.go
  tests/e2e/tests/pilot/grpc_test.go
  tests/e2e/tests/pilot/http_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/tcp_test.go
  tests/e2e/tests/pilot/testdata/app.yaml.tmpl
  tests/e2e/tests/pilot/testdata/authn/service-d-mtls-policy.yaml.tmpl
  tests/e2e/tests/simple/testdata/nginx/app.yaml.tmpl
  tests/helm/templates/app-d-explicit-mtls.yaml
Labels: approved, area/security/aaa, cla: yes, lgtm

#5925 Fish imagePullPolicy to istioctl in e2e test framework
  tests/e2e/framework/istioctl.go
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#5972 put matches first when building cloud foundry routes
  pilot/pkg/config/monitor/copilot_snapshot.go
  pilot/pkg/config/monitor/copilot_snapshot_test.go
Labels: cla: yes

#5958 Remove unused sds code path in NodeAgent
  security/pkg/nodeagent/secrets/secretserver.go
  security/pkg/nodeagent/secrets/secretserver_test.go
  security/pkg/nodeagent/secrets/server.go
  security/pkg/nodeagent/secrets/server_test.go
Labels: approved, cla: yes, lgtm

#5979 switch stable download to 0.8.0 (from 0.2.12)
  downloadIstio.sh
Labels: approved, cla: yes, lgtm

#5975 Merging release-0.8 to master (final round)
  .circleci/config.yml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
  istio.deps
  istioctl/cmd/istioctl/inject.go
  samples/helloworld/README.md
  samples/helloworld/helloworld.yaml
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#5948 add proxyType to pilot_cli tool
  pilot/tools/debug/pilot_cli.go
Labels: approved, cla: yes, lgtm

#5895 Update the 'long running cluster' tests
  tests/helm/setup.sh
  tests/helm/templates/app-a.yaml
  tests/helm/templates/app-b-headless.yaml
  tests/helm/templates/app-fortio-noistio.yaml
  tests/helm/templates/app-fortio.yaml
  tests/helm/templates/badhealth.yaml
  tests/helm/templates/destination-rule-all.yaml
  tests/helm/templates/destination-rule-c.yaml
  tests/helm/templates/destination-rule-fqdn.yaml
  tests/helm/templates/destination-rule-passthrough.yaml
  tests/helm/templates/destination-rule-ssl.yaml
  tests/helm/templates/egress-rule-httpbin.yaml
  tests/helm/templates/egress-rule-wildcard-httpbin.yaml
  tests/helm/templates/fortio-alpha1.yaml
  tests/helm/templates/fortio-cli.yaml
  tests/helm/templates/fortio-noistio.yaml
  tests/helm/templates/fortio-tls.yaml
  tests/helm/templates/fortio-tproxy.yaml
  tests/helm/templates/fortio.yaml
  tests/helm/templates/gateway.yaml
  tests/helm/templates/ingress-load.yaml
  tests/helm/templates/iperf3.yaml
  tests/helm/templates/rule-content-route.yaml
  tests/helm/templates/rule-default-route-append-headers.yaml
  tests/helm/templates/rule-default-route-cors-policy.yaml
  tests/helm/templates/rule-default-route-mirrored.yaml
  tests/helm/templates/rule-default-route.yaml
  tests/helm/templates/rule-fault-injection-to-egress.yaml
  tests/helm/templates/rule-fault-injection.yaml
  tests/helm/templates/rule-redirect-injection.yaml
  tests/helm/templates/rule-redirect-to-egress.yaml
  tests/helm/templates/rule-regex-route.yaml
  tests/helm/templates/rule-rewrite-authority-externalbin.yaml
  tests/helm/templates/rule-rewrite-to-egress.yaml
  tests/helm/templates/rule-route-append-headers-httpbin.yaml
  tests/helm/templates/rule-websocket-route.yaml
  tests/helm/templates/rule-weighted-route.yaml
  tests/helm/templates/service-load.yaml
  tests/helm/templates/virtual_service.yaml
  tests/helm/values-istio-test.yaml
  tests/helm/values.yaml
Labels: approved, cla: yes

#4373 Implement a spy IBP backend
  mixer/pkg/adapter/test/integration.go
  mixer/test/spybackend/args.go
  mixer/test/spybackend/nosession.go
  mixer/test/spybackend/nosession_integration_test.go
  mixer/test/spybackend/session.go
  mixer/test/spybackend/session_integration_test.go
Labels: approved, cla: yes, lgtm

#5432 Add buffering in front of REPORT adapters.
  mixer/pkg/api/grpcServer.go
  mixer/pkg/api/grpcServer_test.go
  mixer/pkg/api/perf_test.go
  mixer/pkg/perf/run.go
  mixer/pkg/runtime/dispatcher/dispatcher.go
  mixer/pkg/runtime/dispatcher/dispatcher_test.go
  mixer/pkg/runtime/dispatcher/dispatchstate.go
  mixer/pkg/runtime/dispatcher/dispatchstate_test.go
  mixer/pkg/runtime/dispatcher/monitoring.go
  mixer/pkg/runtime/dispatcher/reporter.go
  mixer/pkg/runtime/dispatcher/reporter_test.go
  mixer/pkg/runtime/dispatcher/routingcontext.go
  mixer/pkg/runtime/dispatcher/session.go
  mixer/pkg/runtime/dispatcher/session_test.go
  mixer/pkg/runtime/runtime.go
  mixer/pkg/runtime/runtime_test.go
Labels: approved, cla: yes

#5912 copy license file to chart.
  install/kubernetes/helm/istio-remote/LICENSE
  install/kubernetes/helm/istio/LICENSE
Labels: cla: yes, lgtm

#5960 Align istioctl get with kubectl and add --all-namespaces flag
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#6006 fix resources in each deployment issues.
  install/kubernetes/helm/istio-remote/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: cla: yes, lgtm

#6003 fix sidecar webhook default values missing for chart.
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes, lgtm

#5540 Add new attributes to manifests
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/pkg/attribute/list.gen.go
  mixer/testdata/config/attributes.yaml
Labels: approved, area/policies and telemetry, cla: yes

#5959 mixer: implement reporter attributes
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/testdata/config/attributes.yaml
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#5682 Add Collections support to Ctrlz
  pkg/ctrlz/assets.gen.go
  pkg/ctrlz/assets/static/css/dark_syntax.css
  pkg/ctrlz/assets/static/js/prism.js
  pkg/ctrlz/assets/static/js/prism.min.js
  pkg/ctrlz/assets/templates/layouts/base.html
  pkg/ctrlz/topics/assets.gen.go
  pkg/ctrlz/topics/assets/templates/collection/item.html
  pkg/ctrlz/topics/assets/templates/collection/list.html
  pkg/ctrlz/topics/assets/templates/collection/main.html
  pkg/ctrlz/topics/collection.go
Labels: cla: yes

#5786 Add a bypass adapter to Mixer for using gRPC backends via inline model.
  install/kubernetes/helm/istio/charts/mixer/templates/crds.yaml
  mixer/adapter/bypass/bypass.go
  mixer/adapter/bypass/bypass_test.go
  mixer/adapter/bypass/config/adapter.bypass.config.pb.html
  mixer/adapter/bypass/config/config.pb.go
  mixer/adapter/bypass/config/config.proto
  mixer/adapter/bypass/util.go
  mixer/adapter/inventory.gen.go
  mixer/adapter/inventory.yaml
Labels: cla: yes

#5970 'istioctl get all' implementation
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#5849 Retry to connect to cluster 10 times
  prow/cluster_lib.sh
  prow/e2e-suite.sh
Labels: approved, cla: yes, lgtm

#5978 Updates for lack of istio-auth.yaml in release
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm

#5881 Fixed istioctl to be able to deal with multiple paths in KUBECONFIG
  Gopkg.lock
  istioctl/cmd/istioctl/config.go
  istioctl/cmd/istioctl/inject.go
  istioctl/cmd/istioctl/main.go
  pilot/pkg/config/kube/crd/client.go
  pkg/kube/config.go
  pkg/kube/config_test.go
Labels: cla: yes, do-not-merge/hold

#5503 Run pilot e2e test in a multiple cluster environment
  install/kubernetes/helm/istio-remote/templates/endpoints.yaml
  install/kubernetes/helm/istio-remote/templates/service.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/values-istio-auth-multicluster.yaml
  install/kubernetes/helm/istio/values-istio-multicluster.yaml
  install/kubernetes/helm/istio/values.yaml
  tests/e2e/framework/kubernetes.go
  tests/e2e/framework/multicluster.go
  tests/e2e/tests/pilot/a_zipkin_test.go
  tests/e2e/tests/pilot/auth_exclusion_test.go
  tests/e2e/tests/pilot/authn_policy_test.go
  tests/e2e/tests/pilot/egress_rules_test.go
  tests/e2e/tests/pilot/egressgateway_test.go
  tests/e2e/tests/pilot/externalservice_test.go
  tests/e2e/tests/pilot/grpc_test.go
  tests/e2e/tests/pilot/headless_test.go
  tests/e2e/tests/pilot/http_test.go
  tests/e2e/tests/pilot/ingress_test.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/kubernetes_external_name_services_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/routing_to_egress_test.go
  tests/e2e/tests/pilot/tcp_test.go
  tests/e2e/tests/simple/nginx_test.go
Labels: approved, cla: yes, lgtm

#6021 Update E2E test doc to address the comments in #6015
  tests/e2e/UsingGKE.md
Labels: approved, cla: yes, lgtm

#5907 Remove redundant type conversion
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#5962 proxy: update tests
  istio.deps
  mixer/test/client/check_cache_hit/check_cache_hit_test.go
  mixer/test/client/check_report/check_report_test.go
  mixer/test/client/check_report_large_post_request/check_report_large_post_request_test.go
  mixer/test/client/disable_tcp_check_calls/disable_tcp_check_calls_test.go
  mixer/test/client/env/envoy.go
  mixer/test/client/failed_request/failed_request_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go
  mixer/test/client/report_batch/report_batch_test.go
  mixer/test/client/tcp_filter/tcp_filter_test.go
Labels: approved, cla: yes, lgtm

#6020 Use snapshot builder (ephemeral.go) for validation.
  galley/cmd/gals/cmd/validator.go
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/ephemeral.go
  mixer/pkg/runtime/config/handler.go
  mixer/pkg/runtime/config/handler_test.go
  mixer/pkg/runtime/config/monitoring.go
  mixer/pkg/runtime/config/snapshot.go
  mixer/pkg/runtime/config/validator/validator.go
  mixer/pkg/runtime/config/validator/validator_test.go
  mixer/pkg/runtime/dispatcher/dispatcher_test.go
  mixer/pkg/runtime/handler/factory.go
  mixer/pkg/runtime/handler/table.go
  mixer/pkg/runtime/handler/table_test.go
  mixer/pkg/runtime/routing/builder_test.go
  mixer/pkg/runtime/runtime.go
  mixer/pkg/runtime/runtime_test.go
  mixer/pkg/runtime/safecall/safe.go
  mixer/pkg/runtime/safecall/safe_test.go
  mixer/pkg/runtime/testing/util/snapshot.go
  mixer/pkg/runtime/validator/validator.go
  mixer/pkg/runtime/validator/validatorcache.go
  mixer/pkg/runtime/validator/validatorcache_test.go
  mixer/testdata/config/attributes.yaml
  mixer/testdata/config/cloudwatch.yaml
  mixer/testdata/config/solarwinds.yaml
Labels: approved, cla: yes, lgtm

#6044 Add namedBuilders for special input encoding of types
  .circleci/config.yml
  mixer/pkg/protobuf/yaml/dynamic/builder.go
  mixer/pkg/protobuf/yaml/dynamic/encoder.go
  mixer/pkg/protobuf/yaml/dynamic/encoder_test.go
  mixer/pkg/protobuf/yaml/dynamic/errors_test.go
  mixer/pkg/protobuf/yaml/dynamic/valueTypeEncoder.go
  mixer/pkg/protobuf/yaml/dynamic/valueTypeEncoder_test.go
  mixer/pkg/protobuf/yaml/encoder_test.go
  mixer/pkg/protobuf/yaml/testdata/all/foo.pb.html
  mixer/pkg/protobuf/yaml/testdata/all/types.descriptor
  mixer/pkg/protobuf/yaml/testdata/all/types.pb.go
  mixer/pkg/protobuf/yaml/testdata/all/types.proto
Labels: approved, cla: yes, lgtm

#6042 Bug fixes: Gateway TCP routing and timeout
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: approved, cla: yes

#6007 Handle cases when deleted object is cache.DeletionFinalStateUnknown
  pilot/pkg/serviceregistry/kube/cache.go
Labels: cla: yes

#6038 [Pilot] Adding support for config-backed service registry
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/platform.go
Labels: approved, cla: yes, lgtm

#5954 Remove unuse subset from authn policy.
  pilot/pkg/model/validation.go
Labels: cla: yes

#6008 Fix issue that replicaCount is not defined, but used in deployment.
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#6002 Do not expose tracing as lb service.
  install/kubernetes/helm/istio/charts/tracing/templates/service.yaml
Labels: cla: yes

#5952 Refactor Istio Dashboards to support larger meshes
  addons/grafana/README.md
  addons/grafana/dashboards/istio-dashboard.json
  addons/grafana/dashboards/istio-http-grpc-service-dashboard.json
  addons/grafana/dashboards/istio-mesh-dashboard.json
  addons/grafana/dashboards/istio-tcp-service-dashboard.json
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: approved, area/policies and telemetry, cla: yes, kind/needed for 1.0

#6051 Make iptables excludeIPRanges take precedence over includeIPRanges
  tools/deb/istio-iptables.sh
Labels: approved, cla: yes, lgtm

#5319 Implement the rbac effect query command in istioctl
  istioctl/cmd/istioctl/rbac.go
  mixer/adapter/rbac/controller.go
  mixer/adapter/rbac/controller_test.go
  mixer/adapter/rbac/rbac.go
  mixer/adapter/rbac/rbacStore.go
  mixer/adapter/rbac/rbacStore_test.go
  mixer/adapter/rbac/rbac_test.go
  mixer/adapter/rbac/util.go
  mixer/adapter/rbac/util_test.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#5320 CMD tool to create adapter and template custom resource configs
  bin/mixer_codegen.sh
  codecov.requirement
  mixer/cmd/mixs/cmd/crd.go
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/const.go
  mixer/pkg/runtime/config/constant/const.go
  mixer/pkg/runtime/config/ephemeral.go
  mixer/pkg/runtime/config/handler.go
  mixer/pkg/runtime/config/kinds.go
  mixer/pkg/runtime/config/kinds_test.go
  mixer/pkg/runtime/config/validator/validator.go
  mixer/pkg/runtime/dispatcher/session.go
  mixer/pkg/runtime/runtime.go
  mixer/pkg/runtime/runtime_test.go
  mixer/pkg/server/args.go
  mixer/tools/codegen/cmd/mixgenproc/main.go
  mixer/tools/mixgen/cmd/adapter.go
  mixer/tools/mixgen/cmd/adapter_test.go
  mixer/tools/mixgen/cmd/api.go
  mixer/tools/mixgen/cmd/api_go.go
  mixer/tools/mixgen/cmd/api_proto.go
  mixer/tools/mixgen/cmd/api_test.go
  mixer/tools/mixgen/cmd/root.go
  mixer/tools/mixgen/cmd/template.go
  mixer/tools/mixgen/cmd/template_test.go
  mixer/tools/mixgen/cmd/testdata/apa/template.descriptor
  mixer/tools/mixgen/cmd/testdata/apa/template.proto
  mixer/tools/mixgen/cmd/testdata/apa/template_handler.gen.go.golden
  mixer/tools/mixgen/cmd/testdata/apa/template_instance.proto.golden
  mixer/tools/mixgen/cmd/testdata/check/template.descriptor
  mixer/tools/mixgen/cmd/testdata/check/template.proto
  mixer/tools/mixgen/cmd/testdata/check/template_handler.gen.go.golden
  mixer/tools/mixgen/cmd/testdata/check/template_instance.proto.golden
  mixer/tools/mixgen/cmd/testdata/error/template.baseline
  mixer/tools/mixgen/cmd/testdata/error/template.descriptor
  mixer/tools/mixgen/cmd/testdata/error/template.proto
  mixer/tools/mixgen/cmd/testdata/quota/template.descriptor
  mixer/tools/mixgen/cmd/testdata/quota/template.proto
  mixer/tools/mixgen/cmd/testdata/quota/template_handler.gen.go.golden
  mixer/tools/mixgen/cmd/testdata/quota/template_instance.proto.golden
  mixer/tools/mixgen/cmd/testdata/report/template.descriptor
  mixer/tools/mixgen/cmd/testdata/report/template.proto
  mixer/tools/mixgen/cmd/testdata/report/template_handler.gen.go.golden
  mixer/tools/mixgen/cmd/testdata/report/template_instance.proto.golden
  mixer/tools/mixgen/cmd/testdata/simple/foo.descriptor
  mixer/tools/mixgen/cmd/testdata/simple/foo.proto
  mixer/tools/mixgen/cmd/testdata/simple/foo_without_imports.descriptor
  mixer/tools/mixgen/main.go
Labels: approved, cla: yes, lgtm

#5277 Change encoder input to be json's map[string]interface{}
  mixer/pkg/protobuf/yaml/castUtil.go
  mixer/pkg/protobuf/yaml/dynamic/encoderUtil.go
  mixer/pkg/protobuf/yaml/dynamic/encoder_test.go
  mixer/pkg/protobuf/yaml/encoder.go
  mixer/pkg/protobuf/yaml/encoder_test.go
Labels: approved, cla: yes, lgtm

#6058 Generate descriptor for the generate service proto.
  bin/mixer_codegen.sh
  mixer/adapter/bypass/config/adapter.bypass.config.pb.html
  mixer/adapter/bypass/config/config.pb.go
  mixer/adapter/kubernetesenv/template/template_handler_service.descriptor_set
  mixer/adapter/servicecontrol/template/servicecontrolreport/template_handler_service.descriptor_set
  mixer/pkg/attribute/list.gen.go
  mixer/pkg/protobuf/yaml/encoder_test.go
  mixer/pkg/protobuf/yaml/testdata/all/foo.pb.html
  mixer/template/apikey/template_handler_service.descriptor_set
  mixer/template/authorization/template_handler_service.descriptor_set
  mixer/template/checknothing/template_handler_service.descriptor_set
  mixer/template/listentry/template_handler_service.descriptor_set
  mixer/template/logentry/template_handler_service.descriptor_set
  mixer/template/metric/template_handler_service.descriptor_set
  mixer/template/quota/template_handler_service.descriptor_set
  mixer/template/reportnothing/template_handler_service.descriptor_set
  mixer/template/sample/apa/Apa_handler_service.descriptor_set
  mixer/template/sample/apa/istio.mixer.adapter.sample.myApa.pb.html
  mixer/template/sample/check/CheckTesterTemplate_handler_service.descriptor_set
  mixer/template/sample/check/istio.mixer.adapter.sample.check.pb.html
  mixer/template/sample/doc.go
  mixer/template/sample/quota/QuotaTesterTemplate_handler_service.descriptor_set
  mixer/template/sample/quota/istio.mixer.adapter.sample.quota.pb.html
  mixer/template/sample/report/ReportTesterTemplate_handler_service.descriptor_set
  mixer/template/sample/report/istio.mixer.adapter.sample.report.pb.html
  mixer/template/tracespan/tracespan_handler_service.descriptor_set
  mixer/test/spyAdapter/spyadapter.go
  mixer/test/spyAdapter/template/apa/SampleApa.pb.html
  mixer/test/spyAdapter/template/apa/tmpl_handler_service.descriptor_set
  mixer/test/spyAdapter/template/check/SampleCheck.pb.html
  mixer/test/spyAdapter/template/check/tmpl_handler_service.descriptor_set
  mixer/test/spyAdapter/template/report/SampleReport.pb.html
  mixer/test/spyAdapter/template/report/reporttmpl_handler_service.descriptor_set
Labels: approved, cla: yes, lgtm

#6063 Remove confusing double ingress, redo picture from saved source
  tools/README.md
  tools/perf_setup.svg
Labels: approved, cla: yes, lgtm

#6014 Update Pilot to provide new destination.service.* attributes
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#5920 add myself to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm

#5950 use ISTIO_CP_AUTH variable in cluster.env to enable/disable mTLS for cp in mesh ex
  install/tools/setupMeshEx.sh
Labels: approved, cla: yes, lgtm

#6034 Dispatcher improvements
  README.md
  codecov.requirement
  codecov.skip
  mixer/adapter/redisquota/redisquota_integration_test.go
  mixer/pkg/adapter/check.go
  mixer/pkg/adapter/check_test.go
  mixer/pkg/adapter/quotas.go
  mixer/pkg/adapter/quotas_test.go
  mixer/pkg/api/grpcServer.go
  mixer/pkg/api/grpcServer_test.go
  mixer/pkg/api/perf_test.go
  mixer/pkg/runtime/config/util.go
  mixer/pkg/runtime/dispatcher/dispatcher.go
  mixer/pkg/runtime/dispatcher/dispatcher_test.go
  mixer/pkg/runtime/dispatcher/session.go
  mixer/pkg/runtime/dispatcher/session_test.go
  mixer/pkg/runtime/routing/builder.go
  mixer/pkg/runtime/routing/table.go
  tools/README.md
Labels: approved, cla: yes, lgtm

#6062 Don't print usage text when commands exit on runtime error
  galley/cmd/gals/cmd/root.go
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
  pilot/cmd/sidecar-injector/main.go
Labels: approved, cla: yes, lgtm

#6076 Correct error handling cases in Mixer.
  mixer/pkg/runtime/dispatcher/dispatcher_test.go
  mixer/pkg/runtime/dispatcher/session.go
Labels: approved, cla: yes, lgtm

#6075 [pilot] Support manually specifying config controller
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes, lgtm

#6073 Enable Websocket for all v1alpha3 routes
  pilot/pkg/networking/core/v1alpha3/httproute.go
  tests/e2e/tests/pilot/routing_test.go
Labels: cla: yes

#6056 Remove populating mtlsExcludeServices in mesh config.
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/templates/istio-config.yaml.tmpl
  pilot/pkg/proxy/envoy/v1/policy.go
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/pilot/pilot_test.go
Labels: approved, cla: yes, lgtm

#6080 Add more kinds to the config vocabulary.
  mixer/pkg/runtime/config/constant/const.go
  mixer/pkg/runtime/config/kinds.go
  mixer/pkg/runtime/config/kinds_test.go
  mixer/pkg/runtime/config/util_test.go
Labels: approved, cla: yes, lgtm

#5932 Refactor k8senv adapter to generate workload info.
  Gopkg.lock
  install/kubernetes/helm/istio/charts/mixer/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/adapter/kubernetesenv/cache.go
  mixer/adapter/kubernetesenv/cache_test.go
  mixer/adapter/kubernetesenv/config/adapter.kubernetesenv.config.pb.html
  mixer/adapter/kubernetesenv/config/config.pb.go
  mixer/adapter/kubernetesenv/config/config.proto
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
  mixer/adapter/kubernetesenv/template/adapter.template.kubernetes.pb.html
  mixer/adapter/kubernetesenv/template/template.proto
  mixer/adapter/kubernetesenv/template/template_handler.gen.go
  mixer/adapter/kubernetesenv/template/template_handler_service.pb.go
  mixer/adapter/kubernetesenv/template/template_handler_service.proto
  mixer/adapter/kubernetesenv/template/template_proto.descriptor_set
  mixer/template/template.gen.go
  mixer/testdata/config/accesslog.yaml
  mixer/testdata/config/kubernetesenv.yaml
Labels: approved, area/policies and telemetry, cla: yes, kind/needed for 1.0, lgtm

#6087 Fix snapshot and rename Legacy to static and new adapters to dynamic
  mixer/pkg/runtime/config/ephemeral.go
  mixer/pkg/runtime/config/handler.go
  mixer/pkg/runtime/config/handler_test.go
  mixer/pkg/runtime/config/queries.go
  mixer/pkg/runtime/config/queries_test.go
  mixer/pkg/runtime/config/snapshot.go
  mixer/pkg/runtime/config/strings.go
  mixer/pkg/runtime/handler/signature.go
  mixer/pkg/runtime/handler/signature_test.go
  mixer/pkg/runtime/routing/builder.go
Labels: approved, cla: yes, lgtm

#6091 [helm] Don't set prom-bridge address in proxy config if mixer disabled
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: approved, cla: yes, lgtm

#6086 vendor: update api
  Gopkg.lock
  istio.deps
  mixer/cmd/mixc/cmd/check.go
  mixer/cmd/mixc/cmd/util.go
  mixer/pkg/adapter/test/integration.go
  mixer/pkg/api/grpcServer.go
  mixer/pkg/attribute/protoBag.go
  mixer/pkg/mockapi/handler.go
  mixer/pkg/mockapi/server.go
  mixer/pkg/mockapi/server_test.go
  mixer/test/client/env/mixer_server.go
  mixer/test/e2e/util_test.go
  vendor/istio.io/api/OWNERS
  vendor/istio.io/api/authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  vendor/istio.io/api/authentication/v1alpha1/policy.pb.go
  vendor/istio.io/api/authentication/v1alpha1/policy.proto
  vendor/istio.io/api/envoy/config/filter/http/authn/v2alpha1/config.pb.go
  vendor/istio.io/api/envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  vendor/istio.io/api/envoy/config/filter/http/jwt_auth/v2alpha1/config.proto
  vendor/istio.io/api/mixer/v1/attributes.pb.go
  vendor/istio.io/api/mixer/v1/check.pb.go
  vendor/istio.io/api/mixer/v1/check.proto
  vendor/istio.io/api/mixer/v1/istio.mixer.v1.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/authentication/v1alpha1/policy_pb2.py
  vendor/istio.io/api/python/istio_api/envoy/config/filter/http/jwt_auth/v2alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/check_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#6103 Ansible playbooks updated to use istio-demo*.yaml instead of istio*.yaml
  install/ansible/istio/tasks/install_on_cluster.yml
  install/ansible/istio/tasks/set_istio_distro_vars.yml
Labels: approved, cla: yes, lgtm

#6039 Golinter
  tests/util/golinter/README.md
  tests/util/golinter/e2etest_lint_test.go
  tests/util/golinter/gometalinter.json
  tests/util/golinter/integtest_lint_test.go
  tests/util/golinter/linter/lint_rules_list.go
  tests/util/golinter/linter/linter.go
  tests/util/golinter/linter/test_pattern_matcher.go
  tests/util/golinter/linter/whitelist.go
  tests/util/golinter/main.go
  tests/util/golinter/rules/lint_rules.go
  tests/util/golinter/rules/no_goroutine.go
  tests/util/golinter/rules/no_short.go
  tests/util/golinter/rules/no_sleep.go
  tests/util/golinter/rules/skip_by_issue.go
  tests/util/golinter/rules/skip_by_short.go
  tests/util/golinter/rules/util.go
  tests/util/golinter/testdata/e2e/e2e_test.go
  tests/util/golinter/testdata/integ/integtest_test.go
  tests/util/golinter/testdata/integtest_integ_test.go
  tests/util/golinter/testdata/unit_test.go
  tests/util/golinter/unittest_lint_test.go
Labels: approved, cla: yes, lgtm

#6101 A new istioctl flag to choose the context from the kuebconfig
  istioctl/cmd/istioctl/config.go
  istioctl/cmd/istioctl/inject.go
  istioctl/cmd/istioctl/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/client.go
  pkg/kube/config.go
  pkg/kube/config_test.go
  tests/e2e/tests/controller/controller_test.go
Labels: cla: yes

#6113 Custom columns for v1alpha3 types
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes

#5894 align broker kubeconfig handling with pilot
  broker/pkg/platform/kube/crd/client.go
  broker/pkg/platform/kube/crd/client_test.go
Labels: approved, cla: yes, lgtm

#5956 Several enhancements to pilot cli debug tool
  pilot/tools/debug/pilot_cli.go
Labels: cla: yes, lgtm

#6052 Fix flag typo in README
  tests/e2e/README.md
Labels: cla: yes

#6088 Remove populating mtlsExcludeServices.
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#6111 Fixes #6108 Updated version checking statements in Ansible scripts
  install/ansible/istio/tasks/main.yml
Labels: approved, cla: yes, lgtm

#6115 Make pilot port configuration consistent
  bin/testEnvLocalK8S.sh
  install/consul/templates/istio.yaml.tmpl
  install/eureka/templates/istio.yaml.tmpl
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/monitoring.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/proxy/envoy/v1/discovery.go
  tests/local/cluster_registry_test.go
  tests/local/xds_local_test.go
  tests/util/pilot_server.go
  tools/hyperistio/hyperistio.go
Labels: approved, cla: yes, lgtm

#5931 Change span name to be virtual service/host : port + uri match string
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/route.go
  tests/e2e/tests/pilot/routing_test.go
Labels: approved, cla: yes, lgtm

#6035 enable server-side validation by default
  galley/cmd/gals/cmd/validator.go
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/charts/galley/templates/validatingwebhook.yaml
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
  install/kubernetes/helm/istio/values.yaml
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#6096 Fix upgrade TestMain since it is breaking post submit tests
  addons/grafana/dashboards/istio-http-grpc-service-dashboard.json
  addons/grafana/dashboards/istio-mesh-dashboard.json
  addons/grafana/dashboards/istio-tcp-service-dashboard.json
  prow/e2e-simpleTests.sh
  tests/e2e/tests/upgrade/upgrade_test.go
Labels: approved, cla: yes, lgtm

#5721 Fill MR with project metadata in stackdriver log adapter
  mixer/adapter/stackdriver/log/log.go
  mixer/adapter/stackdriver/log/log_test.go
Labels: approved, cla: yes, lgtm

#6017 Add e2e_simple for v2 and enable in circle
  .circleci/config.yml
  tests/e2e/tests/simple/a_simple_1_test.go
  tests/e2e/tests/simple/testdata/v1alpha3/routingrule1.yaml
  tests/e2e/tests/simple/testdata/v1alpha3/routingrule2.yaml
  tests/e2e/tests/simple/testdata/v1alpha3/routingruleNoPods.yaml
  tests/e2e/tests/simple/testdata/v1alpha3/servicesNotInjected.yaml
  tests/e2e/tests/simple/testdata/v1alpha3/servicesToBeInjected.yaml
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#6074 Add scripts for setting Minikube for Mac and improve Linux scripts
  tests/e2e/local/minikube/README.md
  tests/e2e/local/minikube/Troubleshooting.md
  tests/e2e/local/minikube/cleanup_host.sh
  tests/e2e/local/minikube/install_prereqs.sh
  tests/e2e/local/minikube/install_prereqs_debian.sh
  tests/e2e/local/minikube/install_prereqs_macos.sh
  tests/e2e/local/minikube/setup_host.sh
  tests/e2e/local/minikube/setup_minikube_env.sh
  tests/e2e/local/minikube/setup_test.sh
  tests/util/localregistry/localregistry.yaml
Labels: approved, cla: yes, lgtm

#6142 Remove security enablement flag
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#6110 Fixes #6105 - Updated version check regex in Ansible script
  install/ansible/istio/tasks/main.yml
Labels: cla: yes, lgtm

#6143 Proposing Gaung Ya Liu to OWNERS file of install
  install/OWNERS
Labels: approved, cla: yes, lgtm

#6138 fix one namespace issue for chart.
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#6104 Istioctl fixes to satisfy gometalinter
  istioctl/cmd/istioctl/inject.go
  istioctl/cmd/istioctl/metrics.go
Labels: approved, cla: yes, lgtm

#6129 pilot: make sure disabling access logging actually work with proxyv2
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes, lgtm

#6130 E2e Local Minikube Fixes
  tests/e2e/local/minikube/install_prereqs_macos.sh
  tests/e2e/local/minikube/setup_host.sh
Labels: approved, cla: yes, lgtm

#5918 quota and api-spec references should inherit the parent object's namespace if not specified
  pilot/pkg/model/config.go
Labels: approved, cla: yes, lgtm

#6093 Removed redundant if condition
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: approved, cla: yes, lgtm

#6098 Remove people that left the project
  OWNERS
  bin/OWNERS
  prow/OWNERS
  release/OWNERS
  release/pipeline/OWNERS
  tests/e2e/local/minikube/OWNERS
  tests/e2e/local/vagrant/OWNERS
Labels: approved, cla: yes, lgtm

#6122 mixerfilter: client telemetry settings
  pilot/pkg/networking/plugin/mixer/OWNERS
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes

#6126 Implement a fake backend for Mixer.
  Gopkg.lock
  Makefile
  mixer/docker/Dockerfile.test_policybackend
  mixer/test/policybackend/main.go
  pkg/test/fakes/policy/backend.go
  pkg/test/fakes/policy/controller.go
  pkg/test/fakes/policy/controller.pb.go
  pkg/test/fakes/policy/controller.proto
  pkg/test/fakes/policy/conversion.go
  pkg/test/fakes/policy/settings.go
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#6022 add in-memory secret cache for NodeAgent
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: approved, cla: yes, lgtm

#5999 Split cr to cr and crb for prometheus.
  install/kubernetes/helm/istio/charts/prometheus/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/clusterrolebindings.yaml
Labels: approved, cla: yes, lgtm

#6150 Create CRs for dynamic templates
  bin/mixer_codegen.sh
  mixer/adapter/kubernetesenv/template/template.yaml
  mixer/adapter/kubernetesenv/template/template_handler_service.descriptor_set
  mixer/adapter/servicecontrol/template/servicecontrolreport/template.yaml
  mixer/template/apikey/template.yaml
  mixer/template/authorization/template.yaml
  mixer/template/checknothing/template.yaml
  mixer/template/listentry/template.yaml
  mixer/template/logentry/template.yaml
  mixer/template/metric/template.yaml
  mixer/template/quota/template.yaml
  mixer/template/reportnothing/template.yaml
  mixer/template/sample/apa/Apa.yaml
  mixer/template/sample/check/CheckTesterTemplate.yaml
  mixer/template/sample/quota/QuotaTesterTemplate.yaml
  mixer/template/sample/report/ReportTesterTemplate.yaml
  mixer/template/tracespan/tracespan.yaml
  mixer/template/tracespan/tracespan_handler_service.descriptor_set
  mixer/test/spyAdapter/template/apa/tmpl.yaml
  mixer/test/spyAdapter/template/check/tmpl.yaml
  mixer/test/spyAdapter/template/report/reporttmpl.yaml
  mixer/tools/mixgen/cmd/adapter.go
  mixer/tools/mixgen/cmd/template.go
Labels: cla: yes

#6172 remove unused parameters for istio remote chart.
  install/kubernetes/helm/istio-remote/values.yaml
Labels: approved, cla: yes, lgtm

#5921 [Ansible Installer] Add Kiali as addon
  install/ansible/istio/tasks/delete_resources.yml
  install/ansible/istio/tasks/install_addons.yml
Labels: approved, cla: yes, lgtm

#5484 Add a rbac plugin in pilot to distribute rbac policies to proxy
  Gopkg.lock
  istioctl/cmd/istioctl/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/types.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/authz/rbac_test.go
  pilot/pkg/networking/plugin/authz/util.go
  pilot/pkg/networking/plugin/authz/util_test.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/test/mock/config.go
Labels: area/security/aaa, cla: yes

#6120 Migrate istioctl proxy-config to the envoy config_dump admin endpoint
  Gopkg.lock
  istioctl/cmd/istioctl/config.go
  pilot/cmd/pilot-agent/debug.go
  pilot/cmd/pilot-agent/debug_test.go
  pilot/cmd/pilot-agent/testdata/envoy-rev0.json
  pilot/pkg/proxy/envoy/configdump/jsonprinter.go
  pilot/pkg/proxy/envoy/configdump/jsonprinter_test.go
  pilot/pkg/proxy/envoy/configdump/testdata/bootstrapdump.json
  pilot/pkg/proxy/envoy/configdump/testdata/clusterdump.json
  pilot/pkg/proxy/envoy/configdump/testdata/configdump.json
  pilot/pkg/proxy/envoy/configdump/testdata/listenerdump.json
  pilot/pkg/proxy/envoy/configdump/testdata/routesdump.json
Labels: approved, cla: yes, lgtm

#6163 Introduce dynamic handler
  mixer/pkg/adapter/handler.go
  mixer/pkg/protobuf/descriptor/parser.go
  mixer/pkg/protobuf/yaml/dynamic/builder.go
  mixer/pkg/protobuf/yaml/dynamic/encoder.go
  mixer/pkg/protobuf/yaml/dynamic/encoder_test.go
  mixer/pkg/protobuf/yaml/dynamic/errors_test.go
  mixer/pkg/protobuf/yaml/dynamic/handler.go
  mixer/pkg/protobuf/yaml/dynamic/handler_test.go
  mixer/pkg/protobuf/yaml/dynamic/primitive.go
  mixer/pkg/protobuf/yaml/resolver.go
  mixer/test/spybackend/args.go
  mixer/test/spybackend/nosession.go
  mixer/test/spybackend/nosession_integration_test.go
  mixer/test/spybackend/session.go
  mixer/test/spybackend/session_integration_test.go
Labels: approved, cla: yes, lgtm

#6077 [test framework] Adding local pilot
  pkg/test/environment/environment.go
  pkg/test/local/environment.go
  pkg/test/local/pilot/args.go
  pkg/test/local/pilot/pilot.go
  pkg/test/local/pilot/pilot_test.go
Labels: approved, cla: yes, lgtm

#6183 replace user path with $GOPATH.
  bin/mixer_codegen.sh
  mixer/adapter/kubernetesenv/template/template.yaml
  mixer/adapter/servicecontrol/template/servicecontrolreport/template.yaml
  mixer/template/apikey/template.yaml
  mixer/template/authorization/template.yaml
  mixer/template/checknothing/template.yaml
  mixer/template/listentry/template.yaml
  mixer/template/logentry/template.yaml
  mixer/template/metric/template.yaml
  mixer/template/quota/template.yaml
  mixer/template/reportnothing/template.yaml
  mixer/template/sample/apa/Apa.yaml
  mixer/template/sample/check/CheckTesterTemplate.yaml
  mixer/template/sample/quota/QuotaTesterTemplate.yaml
  mixer/template/sample/report/ReportTesterTemplate.yaml
  mixer/template/tracespan/tracespan.yaml
  mixer/test/spyAdapter/template/apa/tmpl.yaml
  mixer/test/spyAdapter/template/check/tmpl.yaml
  mixer/test/spyAdapter/template/report/reporttmpl.yaml
  mixer/test/spybackend/nosession.go
  mixer/test/spybackend/nosession.yaml
  mixer/test/spybackend/session.go
  mixer/test/spybackend/session.yaml
  mixer/tools/mixgen/cmd/adapter.go
  mixer/tools/mixgen/cmd/adapter_test.go
  mixer/tools/mixgen/cmd/template.go
Labels: approved, cla: yes, lgtm

#6168 update api SHA
  Gopkg.lock
  vendor/istio.io/api/authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  vendor/istio.io/api/authentication/v1alpha1/policy.pb.go
  vendor/istio.io/api/authentication/v1alpha1/policy.proto
  vendor/istio.io/api/mixer/v1/global_dictionary.yaml
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/policy/v1beta1/fixed_cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/istio.policy.v1beta1.pb.html
  vendor/istio.io/api/python/istio_api/authentication/v1alpha1/policy_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  vendor/istio.io/api/python/istio_api/policy/v1beta1/cfg_pb2.py
  vendor/istio.io/api/rbac/v1alpha1/rbac.pb.go
  vendor/istio.io/api/rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#6197 Add e2e-pilot-noauth-v1alpha3-v2 to the presubmit test.
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#6166 thread SecretStore into SDS
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server.go
Labels: approved, cla: yes, lgtm

#6208 Bash completions for get and delete
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#6201 Update e2e minikube install scripts
  tests/e2e/local/minikube/README.md
  tests/e2e/local/minikube/install_prereqs_debian.sh
  tests/e2e/local/minikube/install_prereqs_macos.sh
  tests/e2e/local/minikube/setup_host.sh
Labels: approved, cla: yes, lgtm

#6211 Change accesslog entry to have global resource type
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/adapter/stackdriver/log/log.go
Labels: approved, cla: yes, lgtm

#6212 Fix mixgen to add extra space in template name ref
  mixer/test/spybackend/nosession.yaml
  mixer/test/spybackend/session.yaml
  mixer/tools/mixgen/cmd/adapter.go
  mixer/tools/mixgen/cmd/adapter_test.go
Labels: approved, cla: yes, lgtm

#6089 Add tool to check for TLS conflict between authentication policy and destination rule
  istioctl/cmd/istioctl/authn.go
  pilot/cmd/pilot-discovery/debug.go
  pilot/cmd/pilot-discovery/debug_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, cla: human-approved, cla: yes, lgtm

#6195 address Mandar's comments in the snapshot PR.
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/descriptorUtil.go
  mixer/pkg/runtime/config/ephemeral.go
Labels: approved, cla: yes, lgtm

#6215 Use jwt_auth config from istio/api
  Gopkg.lock
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: approved, cla: yes, lgtm

#6192 [Ansible Installer] Kiali Addon 0.3.1.Alpha and Fixing the curl commands to specific version
  install/ansible/istio/tasks/install_addons.yml
Labels: approved, cla: yes, lgtm

#6156 Fix a bug in rbac adapter to evaluate the properties correctly.
  mixer/adapter/rbac/rbacStore.go
  mixer/adapter/rbac/rbacStore_test.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#6188 Deprecation warning for deprecated types
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#6226 remove unused parameters for istio remote chart.
  install/kubernetes/helm/istio-remote/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio-remote/values.yaml
Labels: approved, cla: yes, lgtm

#6222 Upgrade kiali to 0.3.1.Alpha.
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#6147 Self nominating Baodong (Robert) Li to OWNERS file of tests
  tests/OWNERS
Labels: approved, cla: yes, lgtm

#6239 Ed Snible becomes approver for istioctl
  istioctl/OWNERS
Labels: approved, cla: yes, lgtm

#6243 Fix a couple doc issues in the tracespan proto.
  mixer/template/tracespan/traceSpan.pb.html
  mixer/template/tracespan/tracespan.proto
  mixer/template/tracespan/tracespan.yaml
  mixer/template/tracespan/tracespan_handler.gen.go
  mixer/template/tracespan/tracespan_handler_service.descriptor_set
  mixer/template/tracespan/tracespan_handler_service.pb.go
  mixer/template/tracespan/tracespan_handler_service.proto
  mixer/template/tracespan/tracespan_proto.descriptor_set
Labels: approved, cla: yes

#6220 Fix weighted routing with 0 weights
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: approved, cla: yes, lgtm

#6221 Use unique port names in Gateway servers
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/another-ingress.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/myservice-ingress.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/merged-gateway.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/myservice-gateway.yaml.golden
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/pkg/convert/ingress.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/monitor/copilot_snapshot_test.go
  pilot/pkg/config/monitor/file_snapshot_test.go
  pilot/pkg/config/monitor/monitor_test.go
  pilot/pkg/model/gateway_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/testdata/config/egressgateway.yaml
  tests/testdata/config/gateway-all.yaml
  tests/testdata/config/rule-route-via-egressgateway.yaml
  tests/testdata/config/virtual-service-all.yaml
Labels: approved, cla: yes

#6217 Wire mixer.runtime to dynamic.Handler
  mixer/pkg/adapter/handler.go
  mixer/pkg/adapter/test/integration.go
  mixer/pkg/protobuf/yaml/dynamic/handler.go
  mixer/pkg/protobuf/yaml/dynamic/handler_test.go
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/queries.go
  mixer/pkg/runtime/config/snapshot.go
  mixer/pkg/runtime/dispatcher/dispatchstate.go
  mixer/pkg/runtime/dispatcher/dispatchstate_test.go
  mixer/pkg/runtime/dispatcher/reporter_test.go
  mixer/pkg/runtime/dispatcher/session_test.go
  mixer/pkg/runtime/handler/signature.go
  mixer/pkg/runtime/handler/signature_test.go
  mixer/pkg/runtime/handler/table.go
  mixer/pkg/runtime/routing/builder.go
  mixer/pkg/runtime/routing/table.go
  mixer/test/spybackend/nosession_integration_test.go
Labels: approved, lgtm

#6228 Removed flag multicluster.enabled from values.yaml.
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/values-istio-auth-multicluster.yaml
  install/kubernetes/helm/istio/values-istio-multicluster.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes

#6185 Remove duplicated resources declaration for proxy
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#6133 Toggle proxy's --statsdUdpAddress arg by a global helm flag
  install/kubernetes/helm/istio/charts/egressgateway/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#6106 Added missing kubeconfig setting in Pilot tests
  tests/e2e/tests/pilot/egressgateway_test.go
  tests/e2e/tests/pilot/externalservice_test.go
  tests/e2e/tests/pilot/ingressgateway_test.go
Labels: approved, cla: yes

#5779 Fix xds_test on MacOS by configuring ...
  tests/util/pilot_server.go
Labels: cla: no

#6256 Revert "Fix xds_test on MacOS by configuring ..."
  tests/util/pilot_server.go
Labels: approved, cla: yes

#6251 Detect unknown quota responses
  mixer/pkg/protobuf/yaml/dynamic/handler.go
  mixer/pkg/protobuf/yaml/dynamic/handler_test.go
  mixer/test/spybackend/nosession_integration_test.go
Labels: approved, cla: yes

#6194 Update dash tests to use ingressgateway
  tests/e2e/tests/dashboard/dashboard_test.go
  tests/e2e/tests/dashboard/fortio-rules.yaml
Labels: approved, cla: yes

#6248 Delete protoc-3.3.0-osx-x86_64.zip
  mixer/protoc-3.3.0-osx-x86_64.zip
Labels: approved, cla: yes, lgtm

#6252 Return a cacheable OK result when a Check request doesn't hit an adapter at runtime.
  mixer/pkg/runtime/dispatcher/dispatcher.go
  mixer/pkg/runtime/dispatcher/dispatcher_test.go
  mixer/pkg/runtime/dispatcher/session.go
  mixer/pkg/runtime/testing/data/templates.go
Labels: approved, cla: yes, lgtm

#6260 owners files for pilot packages
  pilot/pkg/networking/OWNERS
  pilot/pkg/networking/plugin/authn/OWNERS
  pilot/pkg/networking/plugin/authz/OWNERS
Labels: approved, cla: yes, lgtm

#6250 log unexpected resp for debug
  tests/e2e/tests/pilot/authn_policy_test.go
Labels: approved, cla: yes, lgtm

#6263 deps: update go-control-plane
  Gopkg.lock
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/admin/v2alpha/config_dump.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/auth/cert.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/auth/cert.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/cds.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/cds.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/health_check.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/health_check.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/http_uri.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint/endpoint.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v2/als.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v2/als.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v2/file.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v2/file.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/bootstrap/v2/bootstrap.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/accesslog/v2/accesslog.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/accesslog/v2/accesslog.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/ext_authz/v2alpha/ext_authz.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/health_check/v2/health_check.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/rbac/v2/rbac.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/rbac/v2/rbac.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/router/v2/router.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/router/v2/router.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/ext_authz/v2/ext_authz.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/tcp_proxy/v2/tcp_proxy.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/grpc_credential/v2alpha/file_based_metadata.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/grpc_credential/v2alpha/file_based_metadata.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/rbac/v2alpha/rbac.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/transport_socket/capture/v2alpha/capture.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/data/accesslog/v2/accesslog.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/data/accesslog/v2/accesslog.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/data/tap/v2alpha/capture.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/data/tap/v2alpha/capture.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/service/accesslog/v2/als.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha/attribute_context.pb.go
  vendor/github.com/envoyproxy/go-control-plane/glide.lock
  vendor/github.com/envoyproxy/go-control-plane/glide.yaml
  vendor/github.com/envoyproxy/go-control-plane/pkg/test/accesslog.go
Labels: approved, cla: yes, lgtm

#5984 Update dump_kubernetes.sh
  bin/dump_kubernetes.sh
  tests/istio.mk
Labels: cla: yes

#6264 Adapter mixer e2e tests for grpc adapters
  mixer/pkg/adapter/test/integration.go
  mixer/test/spybackend/args.go
  mixer/test/spybackend/nosession.go
  mixer/test/spybackend/nosession_integration_test.go
  mixer/test/spybackend/session_integration_test.go
Labels: approved, cla: yes, lgtm

#6270 Remove pre-commit hooks
  bin/pre-commit
  broker/bin/pre-commit
Labels: approved, cla: yes, lgtm

#6262 telemetry: tuning mixerfilter
  istio.deps
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#6253 Patch MixerReportToMixer test to reflect source.service removal
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#6273 Remove default --skip_cleanup in test makefile.
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#6272 Remove auth exclusion test
  tests/e2e/tests/pilot/auth_exclusion_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/testdata/authn/destination-rule-exclude.yaml.tmpl
Labels: approved, cla: human-approved, cla: yes, lgtm

#6284 not pass adapter config when there is none.
  mixer/pkg/protobuf/yaml/dynamic/handler.go
  mixer/pkg/runtime/config/ephemeral.go
  mixer/pkg/runtime/handler/signature.go
  mixer/test/spybackend/nosession_integration_test.go
Labels: approved, cla: yes, lgtm

#6158 Use downstream protocol by default
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: cla: yes

#6277 Mock service registry refactored
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/context_test.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/memory/discovery_mock.go
  pilot/pkg/serviceregistry/memory/discovery_test.go
Labels: cla: yes

#6081 Use RDS for sidecars and gateways
  .circleci/config.yml
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/merged-gateway.yaml.golden
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/context.go
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/configgen.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
  tests/testdata/config/ingress.yaml
  tests/testdata/config/rule-ingressgateway.yaml
Labels: approved, cla: yes

#6289 disable e2e test case TestAuthNJwt/a->d[200] for now
  tests/e2e/tests/pilot/authn_policy_test.go
Labels: cla: yes

#6268 Update README.md
  tests/util/checker/testlinter/README.md
Labels: approved, cla: yes, lgtm

#6294 Update mixer_codegen.sh to generate proto_descriptors
  bin/mixer_codegen.sh
  mixer/adapter/bypass/config/config.proto_descriptor
  mixer/adapter/circonus/config/config.proto_descriptor
  mixer/adapter/cloudwatch/config/config.proto_descriptor
  mixer/adapter/denier/config/config.proto_descriptor
  mixer/adapter/dogstatsd/config/config.proto_descriptor
  mixer/adapter/fluentd/config/config.proto_descriptor
  mixer/adapter/kubernetesenv/config/config.proto_descriptor
  mixer/adapter/list/config/config.proto_descriptor
  mixer/adapter/memquota/config/config.proto_descriptor
  mixer/adapter/opa/config/config.proto_descriptor
  mixer/adapter/prometheus/config/config.proto_descriptor
  mixer/adapter/rbac/config/config.proto_descriptor
  mixer/adapter/redisquota/config/config.proto_descriptor
  mixer/adapter/servicecontrol/config/config.proto_descriptor
  mixer/adapter/solarwinds/config/config.proto_descriptor
  mixer/adapter/stackdriver/config/config.proto_descriptor
  mixer/adapter/statsd/config/config.proto_descriptor
  mixer/adapter/stdio/config/config.proto_descriptor
  mixer/pkg/protobuf/yaml/testdata/all/types.proto_descriptor
  security/proto/ca_service.proto_descriptor
  security/proto/nodeagent_service.proto_descriptor
  security/proto/workload_service.proto_descriptor
Labels: approved, cla: yes, lgtm

#6274 policy: enable policy on gateways and fix the test rules
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  pilot/pkg/networking/plugin/mixer/mixer.go
  samples/bookinfo/routing/mixer-rule-ingress-denial.yaml
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm
