Repository istio/istio, pull requests merged in 2018-08, with the labels that each got.

#7539 cloudfoundry performance improvements
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/cloudfoundry/controller.go
  pilot/pkg/config/cloudfoundry/controller_test.go
  pilot/pkg/config/cloudfoundry/fakes/copilot_client.go
  pilot/pkg/config/cloudfoundry/fakes/logger.go
  pilot/pkg/config/cloudfoundry/fakes/store.go
  pilot/pkg/config/monitor/README.md
  pilot/pkg/config/monitor/copilot_snapshot.go
  pilot/pkg/config/monitor/copilot_snapshot_test.go
  pilot/pkg/config/monitor/monitor.go
  pilot/pkg/config/monitor/monitor_test.go
  pilot/pkg/model/config.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/service.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/cached_routes.go
  pilot/pkg/serviceregistry/cloudfoundry/cached_routes_test.go
  pilot/pkg/serviceregistry/cloudfoundry/controller.go
  pilot/pkg/serviceregistry/cloudfoundry/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/fakes/copilot_client.go
  pilot/pkg/serviceregistry/cloudfoundry/fakes/logger.go
  pilot/pkg/serviceregistry/cloudfoundry/fakes/route_cacher.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery_test.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/memory/discovery.go
Labels: cla: yes

#7481 Atomically create and start a test mock server
  pilot/pkg/model/jwks_resolver_test.go
  pilot/pkg/model/test/mockopenidserver.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: cla: yes, lgtm

#7550 add SubjectAltNames to tls.validatecontext for sdsconfig
  pilot/pkg/model/authentication.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/plugin/authn/authentication.go
Labels: approved, cla: yes, lgtm

#7577 remove workaround to parse subjectID as CA put this field optional
  security/pkg/nodeagent/caClient/client.go
Labels: approved, cla: yes, lgtm

#7575 some refactoring on nodeagent
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/model/secret.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server.go
Labels: approved, cla: yes, lgtm

#7576 Fix race condition in ControlZ.
  pkg/ctrlz/ctrlz.go
Labels: approved, cla: yes, lgtm

#7433 Adding an MCP backend to Mixer [Galley Integration]
  codecov.requirement
  galley/pkg/mcp/client/client_test.go
  galley/pkg/runtime/processor.go
  mixer/pkg/config/inventory.go
  mixer/pkg/config/mcp/backend.go
  mixer/pkg/config/mcp/backend_test.go
  mixer/pkg/config/mcp/conversion.go
Labels: approved, cla: yes, do-not-merge/hold

#7566 call the gateway container of a gateway pod "istio-proxy"
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
Labels: cla: yes

#7568 Update codecov requirements
  codecov.requirement
Labels: approved, cla: yes

#7600 try to fix racetest in nodeagent cache
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: approved, cla: yes, lgtm

#7609 Update stale.yml
  .github/stale.yml
Labels: approved, cla: yes, lgtm

#7614 Update example stackdriver config to use CUMULATIVE
  mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml
Labels: approved, cla: yes, lgtm

#7373 Add ShellCheck job
  .circleci/config.yml
  tools/run_shellcheck.sh
Labels: approved, cla: yes, lgtm

#7376 Prow script for pilot-multicluster-e2e test
  prow/cluster_lib.sh
  prow/e2e-suite.sh
  prow/istio-pilot-multicluster-e2e.sh
  prow/mason_lib.sh
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#7633 Update ShellCheck excludes for new scripts from release-1.0
  tools/run_shellcheck.sh
Labels: approved, cla: yes, lgtm

#7628 [test-framework] Integrating test apps into framework
  pkg/test/framework/components/apps/api/apps.go
  pkg/test/framework/components/apps/components.go
  pkg/test/framework/components/apps/kube/app.go
  pkg/test/framework/components/apps/kube/app_test.go
  pkg/test/framework/components/apps/kube/apps.go
  pkg/test/framework/components/apps/local/app.go
  pkg/test/framework/components/apps/local/apps.go
  pkg/test/framework/components/apps/local/envoy/admin_util.go
  pkg/test/framework/components/apps/local/envoy/agent/agent.go
  pkg/test/framework/components/apps/local/envoy/agent/application.go
  pkg/test/framework/components/apps/local/envoy/agent/pilot/agent.go
  pkg/test/framework/components/apps/local/envoy/agent/pilot/agent_test.go
  pkg/test/framework/components/apps/local/envoy/agent/pilot/reserveport/api.go
  pkg/test/framework/components/apps/local/envoy/agent/pilot/reserveport/manager.go
  pkg/test/framework/components/apps/local/envoy/agent/pilot/reserveport/pool.go
  pkg/test/framework/components/apps/local/envoy/agent/pilot/reserveport/port.go
  pkg/test/framework/components/apps/local/envoy/discovery/filter.go
  pkg/test/framework/components/apps/local/envoy/envoy.go
  pkg/test/framework/components/components.go
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/components/pilot/pilot.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/environment.go
  pkg/test/framework/environment/environment.go
  pkg/test/service/echo/factory.go
  tests/e2e/tests/showcase/pilot_showcase_test.go
  tests/e2e/tests/showcase/showcase_test.go
  tests/integration2/examples/pilot/pilot_test.go
Labels: cla: yes, lgtm

#7632 ShellCheck: Enable and fix SC2006
  bin/init.sh
  bin/mixer_codegen.sh
  bin/perfcheck.sh
  bin/testEnvLocalK8S.sh
  release/create_tag_reference.sh
  release/pipeline/airflow_scripts.sh
  release/publish_release.sh
  samples/bookinfo/src/build-services.sh
  tests/e2e/local/minikube/cleanup_host.sh
  tests/e2e/local/minikube/setup_host.sh
  tests/e2e/local/minikube/setup_minikube_env.sh
  tests/e2e/local/vagrant/install_prereqs_debian.sh
  tools/run_shellcheck.sh
  tools/vagrant/provision-vagrant.sh
Labels: approved, cla: yes, lgtm

#7644 Properly format values.yaml for docification
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#7648 ShellCheck: Enable and fix syntax checking rules
  tests/e2e/local/minikube/install_prereqs_debian.sh
  tests/e2e/local/minikube/install_prereqs_macos.sh
  tools/run_shellcheck.sh
Labels: approved, cla: yes, lgtm

#7606 attach istio logging options to nodeagent cmd and add debug logs
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: approved, cla: yes, lgtm

#6679 Fix multicluster e2e test setup to use helm chart template
  tests/e2e/framework/app_manager.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/istioctl.go
  tests/e2e/framework/kubernetes.go
  tests/e2e/framework/multicluster.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/util/kube_utils.go
Labels: approved, area/environments, cla: yes, lgtm

#7649 ShellCheck: Enable and fix uncommon violations
  bin/codecov.sh
  bin/testEnvLocalK8S.sh
  bin/testEnvRootMinikube.sh
  galley/tools/gen-meta/gen-meta.sh
  install/updateVersion.sh
  prow/e2e-suite.sh
  release/create_release_archives.sh
  release/modify_values.sh
  release/pipeline/airflow_scripts.sh
  tests/helm/setup.sh
  tools/run_shellcheck.sh
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm

#7671 ShellCheck: Enable and fix SC2034
  bin/fmt.sh
  bin/get_workspace_status
  bin/init.sh
  bin/init_helm.sh
  bin/linters.sh
  bin/testEnvLocalK8S.sh
  bin/testEnvRootMinikube.sh
  install/tools/setupMeshEx.sh
  install/updateVersion.sh
  mixer/docker/extract.sh
  prow/e2e-suite-rbac-no_auth.sh
  prow/e2e-suite.sh
  prow/mason_lib.sh
  release/gcb_build_lib.sh
  release/store_artifacts.sh
  security/bin/e2e.sh
  tests/e2e_istio_preinstalled.sh
  tests/integration/example/integration.sh
  tools/deb/postinst.sh
  tools/run_shellcheck.sh
Labels: approved, cla: yes, lgtm

#7636 ShellCheck: Enable and fix SC2181
  bin/check_dashboards.sh
  bin/check_license.sh
  bin/envsetup.sh
  bin/get_workspace_status
  bin/testEnvRootMinikube.sh
  install/tools/setupIstioVM.sh
  install/tools/setupMeshEx.sh
  tests/e2e/local/minikube/install_prereqs_debian.sh
  tests/e2e/local/minikube/install_prereqs_macos.sh
  tests/e2e/local/minikube/setup_host.sh
  tests/e2e/local/minikube/setup_minikube_env.sh
  tests/e2e/local/vagrant/install_prereqs_debian.sh
  tests/e2e/local/vagrant/install_prereqs_macos.sh
  tests/e2e/local/vagrant/revert_kubectl_config_host.sh
  tests/e2e/local/vagrant/setup_dockerdaemon_linux.sh
  tests/e2e/local/vagrant/setup_kubectl_config_host.sh
  tools/deb/istio-iptables.sh
  tools/run_shellcheck.sh
  tools/vagrant/provision-vagrant.sh
Labels: approved, cla: yes, lgtm

#7682 [helm chart] quotes for service annotation values
  install/kubernetes/helm/istio/charts/gateways/templates/service.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/service.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/service.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/service.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/service.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/service-jaeger.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/service.yaml
Labels: approved, cla: yes, lgtm

#7681 ShellCheck: Fix remaining minor violations
  addons/grafana/fix_datasources.sh
  bin/check_dashboards.sh
  bin/check_license.sh
  bin/check_links.sh
  bin/codecov.sh
  bin/envsetup.sh
  bin/gobuild.sh
  bin/linters.sh
  bin/mixer_codegen.sh
  bin/perfcheck.sh
  bin/testEnvLocalK8S.sh
  downloadIstio.sh
  galley/pkg/crd/validation/testcerts/generate-certs.sh
  install/tools/setupMeshEx.sh
  prow/e2e-suite.sh
  prow/lib.sh
  release/create_github_release.sh
  release/downloadIstioCandidate.sh
  release/json_parse_shared.sh
  release/pipeline/airflow_scripts.sh
  release/publish_release.sh
  release/store_artifacts.sh
  samples/bookinfo/platform/consul/cleanup.sh
  samples/bookinfo/platform/kube/cleanup.sh
  security/pkg/pki/testdata/multilevelpki/certs.sh
  security/samples/plugin_ca_certs/gen_certs.sh
  tests/e2e/local/minikube/cleanup_host.sh
  tests/e2e/local/minikube/setup_minikube_env.sh
  tests/e2e/local/minikube/setup_test.sh
  tests/e2e/local/vagrant/setup_dockerdaemon_linux.sh
  tests/e2e/local/vagrant/setup_kubectl_config_host.sh
  tests/e2e/local/vagrant/setup_test.sh
  tests/e2e/local/vagrant/setup_vm.sh
  tests/helm/setup.sh
  tests/integration/component/proxy/start_envoy
  tests/integration/example/integration.sh
  tools/run_shellcheck.sh
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm

#7654 Add config volumes and containers to gateways
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
Labels: cla: yes

#7685 Add common labels and release name to deployments
  Makefile
  install/kubernetes/helm/istio-remote/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio-remote/templates/_labels.tpl
  install/kubernetes/helm/istio/charts/certmanager/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/_labels.tpl
Labels: cla: yes

#7678 inject sds uds volume mount in sidecar injection
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/mesh.go
Labels: approved, cla: yes, lgtm

#7670 ShellCheck: Enable and fix SC2155
  bin/codecov.sh
  bin/envsetup.sh
  bin/fmt.sh
  bin/init.sh
  bin/perfcheck.sh
  install/updateVersion.sh
  prow/lib.sh
  prow/mason_lib.sh
  release/cloud_builder.sh
  release/create_github_release.sh
  release/create_tag_reference.sh
  release/gcb_build_lib.sh
  release/json_parse_shared.sh
  samples/bookinfo/platform/consul/cleanup.sh
  samples/bookinfo/platform/kube/cleanup.sh
  tools/run_shellcheck.sh
Labels: approved, cla: yes, lgtm

#7680 ShellCheck: Enable and fix SC1117
  bin/check_license.sh
  bin/codecov.sh
  bin/perfcheck.sh
  install/updateVersion.sh
  mixer/pkg/il/interpreter/generate.sh
  prow/cluster_lib.sh
  release/downloadIstioCandidate.sh
  release/json_parse_shared.sh
  release/pipeline/airflow_scripts.sh
  tests/e2e/local/vagrant/setup_dockerdaemon_linux.sh
  tests/e2e/local/vagrant/setup_vm.sh
  tests/integration/example/integration.sh
  tools/run_shellcheck.sh
  tools/setup_perf_cluster.sh
  tools/vagrant/provision-vagrant.sh
Labels: approved, cla: yes, lgtm

#7613 use github.com/gogo/protobuf/proto for all Istio API resources
  Gopkg.lock
  Gopkg.toml
  galley/pkg/crd/validation/webhook_test.go
  galley/pkg/kube/converter/converter.go
  galley/pkg/kube/converter/converter_test.go
  galley/pkg/kube/converter/proto.go
  galley/pkg/kube/converter/proto_test.go
  galley/pkg/kube/source/source_test.go
  galley/pkg/mcp/client/client.go
  galley/pkg/mcp/configz/configz_test.go
  galley/pkg/metadata/types.go
  galley/pkg/metadata/types_test.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/runtime/resource/proto.go
  galley/pkg/runtime/resource/resource.go
  galley/pkg/runtime/resource/schema.go
  galley/pkg/runtime/resource/schema_test.go
  galley/pkg/runtime/state_test.go
  galley/tools/gen-meta/main.go
  galley/tools/gen-meta/metadata.yaml
  istioctl/pkg/util/proto/messageslice.go
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/model/config.go
  pilot/pkg/model/context.go
  pilot/pkg/model/conversion.go
  pilot/pkg/model/test/mock_config.pb.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/test/mock/config.go
  pkg/bootstrap/bootstrap_config.go
  pkg/bootstrap/bootstrap_config_test.go
  pkg/ctrlz/ctrlz.go
  pkg/ctrlz/ctrlz_test.go
  tests/local/cluster_registry_test.go
  tests/local/xds_local_test.go
  tests/util/pilot_server.go
  tools/hyperistio/hyperistio.go
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  vendor/istio.io/api/authentication/v1alpha1/policy.pb.go
  vendor/istio.io/api/authentication/v1alpha1/policy.proto
  vendor/istio.io/api/common/v1alpha1/istio.common.v1alpha1.pb.html
  vendor/istio.io/api/common/v1alpha1/string.pb.go
  vendor/istio.io/api/common/v1alpha1/string.proto
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/authentication/v1alpha1/policy_pb2.py
  vendor/istio.io/api/python/istio_api/common/v1alpha1/string_pb2.py
  vendor/istio.io/api/rbac/v1alpha1/rbac.pb.go
Labels: approved, cla: yes, lgtm

#6812 Add filter query parameters for servicegraph
  addons/servicegraph/README.md
  addons/servicegraph/force/forcegraph.js
  addons/servicegraph/promgen/promgen.go
Labels: approved, cla: yes, lgtm

#7560 [Helm] Apply imagePullSecrets to components that don't use serviceaccounts
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#7715 remove old code, move airflow scripts, fix build break
  release/airflow_scripts.sh
  release/cloud_build.template.json
  release/modify_values.sh
  release/pipeline/dags/istio_monthly_release_0_8.py
  release/pipeline/dags/istio_monthly_release_1_0.py
  release/publish_release.sh
Labels: approved, cla: yes, lgtm

#7708 [Ansible Installer] Including Missing SCC on change_scc file
  install/kubernetes/ansible/istio/tasks/change_scc.yml
Labels: approved, cla: yes, lgtm

#7697 Enable testlinter and fix violations of skip by issue rule.
  bin/linters.sh
  mixer/pkg/runtime/config/validator/validator_test.go
  pilot/pkg/serviceregistry/consul/monitor_test.go
  tests/e2e/tests/pilot/a_zipkin_test.go
  tests/e2e/tests/simple/a_simple_1_test.go
  tests/util/checker/testlinter/lint_rules_list.go
  tests/util/checker/testlinter/testdata/e2e/e2e_test.go
  tests/util/checker/testlinter/testdata/integration/integtest_test.go
  tests/util/checker/testlinter/testdata/integtest_integ_test.go
  tests/util/checker/testlinter/testdata/unit_test.go
  tests/util/checker/testlinter/testlinter.json
Labels: approved, cla: yes, lgtm

#7690 merge from master into release-1.0 changes for gateway deployment
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
Labels: cla: yes

#7553 Add grafana persist option to istio helm chart
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/pvc.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes

#7456 Remove usages of mesh auth_policy flag
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: cla: yes

#7732 (release-1.0) Use service name instead of cluster name for SNI w/ istio mtls
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes

#7434 servicecontrol: use instance whenever possible
  mixer/adapter/servicecontrol/handler.go
  mixer/adapter/servicecontrol/handler_test.go
  mixer/pkg/adapter/requestData.go
  mixer/pkg/adapter/requestData_test.go
  mixer/pkg/runtime/dispatcher/session.go
Labels: approved, cla: yes, lgtm

#7705 Change Control-Z startup/shutdown interface to eliminate race.
  galley/pkg/mcp/configz/configz_test.go
  galley/pkg/server/server.go
  mixer/pkg/server/server.go
  pilot/pkg/bootstrap/server.go
  pkg/ctrlz/ctrlz.go
  pkg/ctrlz/ctrlz_test.go
Labels: cla: yes, lgtm

#7714 bump dep to v0.5.0
  Gopkg.lock
  Makefile
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/go4.org/legal/legal.go
Labels: approved, cla: yes, lgtm

#7737 Adding helper functions to simplify injection templates
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/inject/auth.cert-dir.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/auth.non-default-service-account.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/auth.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/cronjob.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/enable-core-dump.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/format-duration.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-always.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-ignore.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-never.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-proxy-override.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-tproxy-debug.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-tproxy.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/job.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/list.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/pod.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-params-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-params.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
Labels: approved, cla: yes, lgtm

#7572 Log error for bad values of autoInject
  pilot/pkg/kube/inject/inject.go
Labels: approved, cla: yes, lgtm

#7744 Add support for loadBalancerSourceRanges in gateways
  install/kubernetes/helm/istio/charts/gateways/templates/service.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#7702 Fix problematic `if`s and `while`s in shell scripts
  bin/get_workspace_status
  install/tools/setupIstioVM.sh
  tests/e2e/local/minikube/setup_host.sh
  tests/e2e/local/minikube/setup_minikube_env.sh
Labels: approved, cla: yes, lgtm

#7692 Use service name instead of cluster name for SNI string w/ Istio MTLS
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes

#7725 remove deprecated flags
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  pkg/log/options.go
  pkg/log/options_test.go
Labels: approved, cla: yes, lgtm

#7635 Use per-push snapshot of configs for scalability
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/authentication.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_status.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/configgen.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_discovery.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/envoyfilter/envoyfilter.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery_test.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/memory/discovery.go
  tests/e2e/tests/pilot/listener_conflict_test.go
  tests/helm/templates/fortio-tls.yaml
  tests/helm/values-istio-test.yaml
Labels: cla: human-approved, cla: yes

#7748 ShellCheck: Enable and fix SC1090 and SC1091
  bin/envsetup.sh
  install/tools/setupIstioVM.sh
  prow/e2e-suite.sh
  prow/istio-postsubmit.sh
  prow/istio-presubmit.sh
  prow/istio-unit-tests.sh
  release/create_github_release.sh
  release/create_tag_reference.sh
  release/gcb_build_lib.sh
  release/start_gcb_build.sh
  release/start_gcb_publish.sh
  release/start_gcb_tag.sh
  samples/rawvm/demo.sh
  tests/e2e/local/minikube/setup_test.sh
  tools/deb/istio-ca.sh
  tools/deb/istio-iptables.sh
  tools/deb/istio-start.sh
  tools/run_canonical_perf_tests.sh
  tools/run_shellcheck.sh
Labels: approved, cla: yes, lgtm

#7774 Changed the bug/feature issue template description font to small font
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cla: yes, lgtm

#7343 Change mixer_codegen.sh to use protoc dockerfile
  bin/counterfeiter.sh
  bin/go-bindata.sh
  bin/mixer_codegen.sh
  bin/protoc.sh
  docker/Dockerfile.go_generate_dependency
  docker/build_and_push_go_generate_dependency.sh
Labels: approved, cla: yes, lgtm

#7779 Merge latest perf optimizations from release-1.0 into master
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/values-istio-gateways.yaml
  install/kubernetes/helm/istio/values.yaml
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/authentication.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_status.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/configgen.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_discovery.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/envoyfilter/envoyfilter.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery_test.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/memory/discovery.go
  tests/e2e/tests/pilot/listener_conflict_test.go
  tests/helm/templates/fortio-tls.yaml
  tests/helm/values-istio-test.yaml
Labels: cla: human-approved, cla: yes

#7761 move mcp packages under common `pkg` directory
  galley/pkg/runtime/distributor.go
  galley/pkg/runtime/distributor_test.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/runtime/state.go
  galley/pkg/server/server.go
  galley/tools/mcpc/main.go
  mixer/pkg/config/mcp/backend.go
  mixer/pkg/config/mcp/backend_test.go
  pkg/mcp/OWNERS
  pkg/mcp/client/client.go
  pkg/mcp/client/client_test.go
  pkg/mcp/configz/assets.gen.go
  pkg/mcp/configz/assets.go
  pkg/mcp/configz/assets/templates/config.html
  pkg/mcp/configz/configz.go
  pkg/mcp/configz/configz_test.go
  pkg/mcp/server/server.go
  pkg/mcp/server/server_test.go
  pkg/mcp/snapshot/inmemory.go
  pkg/mcp/snapshot/inmemory_test.go
  pkg/mcp/snapshot/snapshot.go
  pkg/mcp/snapshot/snapshot_test.go
  pkg/mcp/testing/server.go
Labels: approved, cla: yes, lgtm

#7565 always create istio-sidecar-injector configmap with default install
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values-istio-gateways.yaml
Labels: approved, cla: yes, lgtm

#7769 fixed: duplicated port in kiali service
  install/kubernetes/helm/istio/charts/kiali/templates/service.yaml
Labels: approved, cla: yes, lgtm

#6951 Include debug/authenticationz in pilot dump output
  tools/dump_kubernetes.sh
Labels: approved, cla: yes, lgtm

#7610 check cert/key not empty when applying tls setting.
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: cla: yes

#7784 Helm chart: Custom proxy image for ingress, gateways, pilot and mixer
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#7703 Speculative fix for flaky syncz tests
  pilot/pkg/proxy/envoy/v2/debug_test.go
Labels: approved, cla: yes, lgtm

#7797 fixes for broken daily build
  release/airflow_scripts.sh
  release/cloud_builder.sh
  release/publish_release.sh
  release/store_artifacts.sh
Labels: cla: yes

#7743 Defer self-registering validation webhook until endpoint is ready
  galley/pkg/crd/validation/config.go
  galley/pkg/crd/validation/webhook.go
  install/kubernetes/helm/istio/charts/galley/templates/clusterrole.yaml
  tests/e2e/framework/kubernetes.go
  tests/istio.mk
Labels: cla: yes, lgtm

#7816 Use debian-9 GCE image family.
  install/gcp/deployment_manager/istio-cluster.jinja
Labels: cla: yes, needs-ok-to-test

#7789 Fixes for mesh expansion
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
  security/pkg/pki/ca/controller/secret.go
  security/pkg/platform/aws.go
  security/pkg/platform/gcp.go
  security/pkg/platform/onprem.go
  tools/deb/istio-auth-node-agent.service
  tools/deb/istio-node-agent-start.sh
  tools/deb/istio-start.sh
  tools/deb/istio.mk
  tools/deb/postinst.sh
Labels: cla: yes

#7716 Gencert supports generating cert signed by citadel.
  security/tools/generate_cert/main.go
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#6612 Change to ALPN based filter chain selection.
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/envoyfilter/envoyfilter.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, cla: yes, lgtm

#7815 more build fixes related to shell check
  bin/fmt.sh
  release/airflow_scripts.sh
  release/cloud_builder.sh
Labels: approved, cla: yes, lgtm

#7796 Replace "MaxMsgSize" with "MaxRecvMsgSize" in grpc server
  mixer/pkg/api/grpcServer_test.go
  mixer/pkg/api/perf_test.go
  mixer/pkg/server/server.go
Labels: approved, cla: yes, lgtm

#7809 Remove blank excludes flag
  tools/run_shellcheck.sh
Labels: approved, cla: yes, lgtm

#7824 Change mixer_codegen.sh script to use gogoslick from dockerfile
  bin/fmt.sh
  bin/mixer_codegen.sh
  pilot/pkg/config/cloudfoundry/fakes/copilot_client.go
Labels: cla: yes

#7800 standard golang libs should be grouped together
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: approved, cla: yes, lgtm

#7741 [Ansible Installer] Adding Routes to Prometheus, Grafana, Istio-Ingress-Gateway
  install/kubernetes/ansible/istio/tasks/delete_resources.yml
  install/kubernetes/ansible/istio/tasks/install_on_cluster.yml
  install/kubernetes/ansible/istio/tasks/main.yml
  install/kubernetes/ansible/istio/tasks/set_istio_path.yml
Labels: approved, cla: yes, lgtm

#7825 Correct pilot autoscalemax to 5
  install/kubernetes/helm/istio/charts/gateways/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/autoscale.yaml
  install/kubernetes/helm/istio/values-istio-gateways.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#7870 update CA endpoint to prod instance
  security/cmd/node_agent_k8s/main.go
Labels: approved, cla: yes, lgtm

#7839 more fixes for broken daily build
  release/airflow_scripts.sh
  release/gcb_build_lib.sh
  release/start_gcb_build.sh
  release/start_gcb_publish.sh
  release/start_gcb_tag.sh
Labels: approved, cla: yes, lgtm

#7778 Add option to deployableConfig to remove existing resources
  tests/e2e/tests/pilot/pilot_test.go
  tests/util/kube_utils.go
Labels: approved, cla: yes, lgtm

#7786 Rename updater update to apply
  galley/tools/mcpc/main.go
  mixer/pkg/config/mcp/backend.go
  mixer/pkg/config/mcp/backend_test.go
  pkg/mcp/client/client.go
  pkg/mcp/client/client_test.go
  pkg/mcp/configz/configz_test.go
Labels: approved, cla: human-approved, cla: yes, lgtm

#7875 add helm charts for nodeagent
  install/kubernetes/helm/istio/charts/nodeagent/Chart.yaml
  install/kubernetes/helm/istio/charts/nodeagent/templates/daemonset.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#7443 /watch has been deprecated, use `?watch=true`
  pilot/pkg/config/kube/crd/controller.go
Labels: approved, cla: yes, lgtm

#7906 e2e guide docs typo fix
  tests/e2e/README.md
  tests/e2e/UsingGKE.md
Labels: cla: yes, needs-ok-to-test

#7898 Fix spelling error in file tests/util/checker/testlinter/README.md
  tests/util/checker/testlinter/README.md
Labels: cla: no, needs-ok-to-test

#7892 xds: fix invalid comments
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#7868 Cloudfoundry - Route weight
  Gopkg.lock
  pilot/pkg/config/cloudfoundry/controller.go
  pilot/pkg/config/cloudfoundry/controller_test.go
  vendor/code.cloudfoundry.org/copilot/api/cloud_controller.pb.go
  vendor/code.cloudfoundry.org/copilot/api/istio.pb.go
  vendor/github.com/onsi/ginkgo/config/config.go
Labels: approved, cla: human-approved, lgtm

#7853 fix typo in snapshot log/comments
  pkg/mcp/snapshot/snapshot.go
Labels: approved, cla: yes, lgtm

#7846 fix typo in command help message
  istioctl/cmd/istioctl/authn.go
Labels: approved, cla: yes, lgtm

#7845 lock protect read adsClients
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: cla: yes

#7833 Add RDS load timestamp to istioctl proxy-status
  istioctl/pkg/util/configdump/route.go
  istioctl/pkg/writer/compare/comparator.go
  istioctl/pkg/writer/compare/route.go
  istioctl/pkg/writer/compare/route_test.go
  istioctl/pkg/writer/compare/testdata/diffenvoyconfigdump.json
  istioctl/pkg/writer/compare/testdata/routediff.txt
Labels: cla: yes

#7832 More sidecar injector template cleanup
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/inject/auth.cert-dir.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/auth.non-default-service-account.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/auth.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/cronjob.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/enable-core-dump.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/format-duration.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-always.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-ignore.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-never.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-proxy-override.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-tproxy-debug.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-tproxy.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/job.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/list.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/pod.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-params-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-params.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_replace.yaml
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/job.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/webhook.go
  pilot/pkg/kube/inject/webhook_test.go
Labels: cla: yes, lgtm

#7842 optimize `edsClusters` `connectionNumber` to reduce access contention
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#7904 remove useless param
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
Labels: approved, cla: yes, lgtm

#7557 Helm chart: allow annotations on mixer pods
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#7801 fix pilot crash issue if there is zero listeners and err is nil
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: approved, cla: yes, lgtm

#7818 Merge recent changes from release-1.0
  galley/pkg/crd/validation/config.go
  galley/pkg/crd/validation/webhook.go
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/charts/galley/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values-istio-gateways.yaml
  install/kubernetes/helm/istio/values.yaml
  security/pkg/pki/ca/controller/secret.go
  security/pkg/platform/aws.go
  security/pkg/platform/gcp.go
  security/pkg/platform/onprem.go
  tests/e2e/framework/kubernetes.go
  tests/istio.mk
  tools/deb/istio-auth-node-agent.service
  tools/deb/istio-node-agent-start.sh
  tools/deb/istio-start.sh
  tools/deb/istio.mk
  tools/deb/postinst.sh
Labels: cla: yes

#7829 Bad default for Kaili - Updated install_addons.yml
  install/kubernetes/ansible/istio/tasks/install_addons.yml
Labels: approved, cla: yes, lgtm

#7718 remove unused post install hook for remote chart.
  install/kubernetes/helm/istio-remote/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/enable-mesh-mtls.yaml
  install/kubernetes/helm/istio-remote/templates/install-custom-resources.sh.tpl
Labels: approved, cla: yes, lgtm

#7895 Added nodeagent to requirements.yaml.
  install/kubernetes/helm/istio/requirements.yaml
Labels: cla: yes, lgtm

#7911 Mark agent_test tests skipped, as they are failing in CircleCI.
  pkg/test/framework/components/apps/local/envoy/agent/pilot/agent_test.go
Labels: approved, cla: yes, lgtm

#7704 Add ControlZ support to Citadel.
  security/cmd/istio_ca/main.go
Labels: approved, cla: yes

#7914 Revert "remove unused post install hook for remote chart. (#7718)"
  install/kubernetes/helm/istio-remote/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/enable-mesh-mtls.yaml
  install/kubernetes/helm/istio-remote/templates/install-custom-resources.sh.tpl
  install/kubernetes/helm/istio/charts/grafana/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/grafana-ports-mtls.yaml
  install/kubernetes/helm/istio/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/security/templates/enable-mesh-mtls.yaml
  install/kubernetes/helm/istio/templates/install-custom-resources.sh.tpl
Labels: approved, cla: yes

#7811 Unify reconnection and message processing in mcp client.
  pkg/mcp/client/client.go
  pkg/mcp/client/client_test.go
  pkg/mcp/configz/configz_test.go
  pkg/mcp/snapshot/snapshot.go
  pkg/mcp/snapshot/snapshot_test.go
Labels: approved, cla: yes, lgtm

#7750 Enable permissive mode for default deployment
  install/kubernetes/helm/istio-remote/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/enable-mesh-permissive.yaml
  install/kubernetes/helm/istio/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/security/templates/enable-mesh-permissive.yaml
  tests/e2e/tests/pilot/authn_policy_test.go
Labels: approved, cla: yes, lgtm

#7830 Implement mTLS functionality in MCP
  galley/pkg/crd/validation/config_test.go
  galley/pkg/crd/validation/webhook_test.go
  galley/pkg/server/server.go
  pilot/pkg/kube/inject/webhook_test.go
  pkg/mcp/creds/create.go
  pkg/mcp/creds/create_test.go
  pkg/mcp/creds/watcher.go
  pkg/mcp/server/listchecker.go
  pkg/mcp/server/listchecker_test.go
  pkg/mcp/server/server.go
  pkg/mcp/server/server_test.go
  pkg/mcp/testing/server.go
  pkg/mcp/testing/testcerts/generate-certs.sh
  pkg/mcp/testing/testcerts/testcerts.go
Labels: approved, cla: yes, lgtm

#7887 [test-framework] Remove use of Cobra flags.
  pkg/test/framework/settings/flags.go
Labels: approved, cla: yes, lgtm

#7881 Implement basic mTLS functionality in Galley
  galley/cmd/galley/cmd/server.go
  galley/pkg/server/args.go
  galley/pkg/server/args_test.go
  galley/pkg/server/configmap.go
  galley/pkg/server/configmap_test.go
  galley/pkg/server/server.go
  galley/pkg/server/server_test.go
  pkg/mcp/server/listchecker.go
Labels: approved, cla: yes, lgtm

#7929 lint tools complain about redundant newline in Println
  tools/license/get_dep_licenses.go
Labels: approved, cla: yes, lgtm

#7913 Fix RedisQuota not returning the first override match
  mixer/adapter/redisquota/redisquota.go
Labels: approved, cla: yes, lgtm

#7886 Re-enable "Check Scripts" as optional part of make lint
  .circleci/Makefile
  .circleci/config.yml
  .circleci/lint.dockerfile
  tools/run_shellcheck.sh
Labels: approved, cla: yes

#7882 Add Galley server mode to helm charts
  install/kubernetes/helm/istio/charts/galley/templates/accesslist.yaml.tpl
  install/kubernetes/helm/istio/charts/galley/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/galley/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/templates/service.yaml
Labels: approved, cla: yes, lgtm

#7939 Remove any duplicate clusters created by BuildClusters
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, area/networking, cla: yes, lgtm

#7951 allow pilot to run by itself
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: cla: yes

#7945 Update grafana to its latest version
  addons/grafana/Dockerfile.grafana
Labels: approved, cla: yes, lgtm

#7919 add rbac attributes to attributemanifest
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
Labels: approved, cla: yes, lgtm

#7011 Helm chart: allow mapping for statsd-prom-bridge
  install/kubernetes/helm/istio/charts/mixer/templates/configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#7849 Support configurable domain in Citadel identities
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
  security/README.md
  security/cmd/istio_ca/main.go
  security/pkg/pki/ca/controller/secret.go
  security/pkg/pki/ca/controller/secret_test.go
Labels: approved, cla: yes, lgtm

#7981 Revert "remove requestedServerName attribute (#7278)"
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/testdata/config/accesslog.yaml
  mixer/testdata/config/attributes.yaml
  mixer/testdata/config/tcp_accesslog.yaml
Labels: approved, cla: yes, lgtm

#7970 Updated Jaeger to 1.6
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#7924 Support Timestamp type for valueTypeEncoder
  mixer/pkg/protobuf/yaml/dynamic/valueTypeEncoder.go
  mixer/pkg/protobuf/yaml/dynamic/valueTypeEncoder_test.go
Labels: approved, cla: yes, lgtm

#7772 remove unused post install hook for remote chart.
  install/kubernetes/helm/istio-remote/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/enable-mesh-mtls.yaml
  install/kubernetes/helm/istio-remote/templates/install-custom-resources.sh.tpl
Labels: cla: yes

#7473 Added build-in annotation for cert manager.
  install/kubernetes/helm/istio/charts/certmanager/templates/deployment.yaml
Labels: approved, cla: yes

#7944 Add support for specifying sinkoptions when creating stackdriver sink
  Gopkg.lock
  mixer/adapter/stackdriver/config/adapter.stackdriver.config.pb.html
  mixer/adapter/stackdriver/config/config.pb.go
  mixer/adapter/stackdriver/config/config.proto
  mixer/adapter/stackdriver/config/config.proto_descriptor
  mixer/adapter/stackdriver/config/stackdriver.yaml
  mixer/adapter/stackdriver/log/log.go
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/logging/apiv2/config_client.go
  vendor/cloud.google.com/go/logging/apiv2/logging_client.go
  vendor/cloud.google.com/go/logging/apiv2/metrics_client.go
  vendor/cloud.google.com/go/logging/doc.go
  vendor/cloud.google.com/go/logging/internal/common.go
  vendor/cloud.google.com/go/logging/logadmin/logadmin.go
  vendor/cloud.google.com/go/logging/logadmin/metrics.go
  vendor/cloud.google.com/go/logging/logadmin/resources.go
  vendor/cloud.google.com/go/logging/logadmin/sinks.go
  vendor/cloud.google.com/go/logging/logging.go
  vendor/cloud.google.com/go/monitoring/apiv3/alert_policy_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/group_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/metric_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/notification_channel_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/uptime_check_client.go
  vendor/cloud.google.com/go/trace/apiv2/trace_client.go
Labels: approved, cla: yes, lgtm

#7956 Log error for bad values of autoInject (#7572)
  pilot/pkg/kube/inject/inject.go
Labels: approved, area/environments, cla: yes, lgtm

#7999 Update issue templates to make 'em look nicer for the submitter.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cla: yes, lgtm

#7960 mixer: non-blocking config store constructor, explicit wait for sync
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
  mixer/pkg/config/mcp/backend.go
  mixer/pkg/config/store/fsstore.go
  mixer/pkg/config/store/listener_test.go
  mixer/pkg/config/store/store.go
  mixer/pkg/config/store/store_test.go
  mixer/pkg/config/storetest/storetest.go
  mixer/pkg/runtime/runtime_test.go
  mixer/pkg/server/server.go
Labels: cla: yes

#7954 Update Envoy SHA to latest (release-1.0).
  bin/testEnvLocalK8S.sh
  istio.deps
  mixer/test/client/env/envoy.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/pkg/proxy/envoy/watcher_test.go
  pkg/bootstrap/bootstrap_config.go
  tests/e2e/tests/pilot/externalservice_test.go
  tools/deb/istio-start.sh
Labels: cla: yes

#6710 Start a document for continuous development with minikube
  tests/e2e/local/Tips.md
  tests/e2e/local/minikube/README.md
  tests/e2e/local/vagrant/README.md
Labels: approved, cla: yes, lgtm

#8007 mixer: remove destination.service deprecated attribute
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#7900 Let "pilot_grpc_address" take over param DiscoveryAddress in WriteBootstrap
  install/kubernetes/helm/istio-remote/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  pkg/bootstrap/bootstrap_config.go
  pkg/bootstrap/testdata/all.proto
  pkg/bootstrap/testdata/auth.proto
  pkg/bootstrap/testdata/default.proto
Labels: approved, cla: yes, lgtm

#7905 Replace MaxClusterNameLength with MeshConfig.StatNameLength
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/context.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/pkg/proxy/envoy/watcher_test.go
  pkg/bootstrap/bootstrap_config.go
  tools/hyperistio/hyperistio.go
Labels: approved, cla: yes, lgtm

#7948 Fix current ShellCheck violations
  bin/counterfeiter.sh
  bin/go-bindata.sh
  bin/mixer_codegen.sh
  bin/protoc.sh
  docker/build_and_push_go_generate_dependency.sh
  mixer/test/client/pilotplugin_mtls/testdata/generate.sh
  release/cloud_builder.sh
  tools/deb/istio-node-agent-start.sh
  tools/deb/istio-start.sh
Labels: approved, cla: yes, lgtm

#7973 cleanup: remove unused field "Client" in listener
  galley/pkg/kube/source/listener.go
Labels: approved, cla: yes, lgtm

#7988 Fix the API versions in Citadel yaml templates.
  install/kubernetes/citadel_extras/istio-citadel-plugin-certs.yaml.tmpl
  install/kubernetes/citadel_extras/istio-citadel-standalone.yaml.tmpl
  install/kubernetes/citadel_extras/istio-citadel-with-health-check.yaml.tmpl
Labels: approved, cla: yes, lgtm

#7983 Normalize clusters
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: area/networking, cla: yes

#7972 remove TPR since it has been deleted from k8s 1.8
  install/kubernetes/helm/istio/charts/gateways/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/clusterrole.yaml
Labels: approved, cla: yes, lgtm

#8021 fix nil pointer panic when ads request node is nil
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: approved, cla: yes, lgtm

#8012 Change issue template to use brackets instead of italics for readability
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#8010 Update Mixer dictionary to match proxy
  mixer/pkg/attribute/list.gen.go
  mixer/test/client/check_cache_hit/check_cache_hit_test.go
  mixer/test/client/check_report/check_report_test.go
  mixer/test/client/check_report_large_post_request/check_report_large_post_request_test.go
  mixer/test/client/disable_tcp_check_calls/disable_tcp_check_calls_test.go
  mixer/test/client/dynamic_attribute/dynamic_attribute_test.go
  mixer/test/client/dynamic_listener/dynamic_listener_test.go
  mixer/test/client/failed_request/failed_request_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  mixer/test/client/report_batch/report_batch_test.go
  mixer/test/client/tcp_filter/tcp_filter_test.go
  mixer/test/client/tcp_filter_periodical_report/tcp_filter_periodical_report_test.go
Labels: approved, cla: yes, lgtm

#7969 optimize pilot-discovery server
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pkg/cmd/cmd.go
  pkg/test/framework/components/apps/local/envoy/agent/pilot/agent_test.go
  pkg/test/framework/components/pilot/pilot.go
  tests/local/cluster_registry_test.go
  tests/local/xds_local_test.go
  tests/util/pilot_server.go
  tools/hyperistio/hyperistio.go
Labels: approved, cla: yes

#7840 `version` should be well protected
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: approved, cla: yes, lgtm

#8028 Add all supported value types to dynamic encoder
  mixer/pkg/protobuf/yaml/dynamic/encoder_test.go
  mixer/pkg/protobuf/yaml/dynamic/handler_test.go
  mixer/pkg/protobuf/yaml/dynamic/valueTypeEncoder.go
  mixer/pkg/protobuf/yaml/dynamic/valueTypeEncoder_test.go
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/ephemeral.go
  mixer/pkg/runtime/config/validator/validator_test.go
Labels: approved, cla: yes, lgtm

#7992 A few doc-related fixes.
  istioctl/cmd/istioctl/main.go
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
  pilot/cmd/sidecar-injector/main.go
  security/cmd/istio_ca/main.go
  security/cmd/node_agent/main.go
Labels: cla: yes

#7994 Add ports to VirtualService hosts in Envoy
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  tests/e2e/tests/pilot/ingressgateway_test.go
Labels: cla: yes

#8032 Change template text to be less condescending.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cla: yes, lgtm

#8000 telemetry: test for SNI reporting
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
Labels: approved, cla: yes, lgtm

#8055 update session cookie. (#8052)
  tests/e2e/tests/bookinfo/main_test.go
Labels: approved, cla: yes, lgtm

#8031 Allow multiple destination rules with different subsets for the same host
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/push_context.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/destination-rule-c-headersubset.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-content-route.yaml
Labels: cla: yes, lgtm

#7967 update secret management for kiali.
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/secrets.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#8037 Update istio.io/api to 214c759
  Gopkg.lock
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  vendor/istio.io/api/authentication/v1alpha1/policy.pb.go
  vendor/istio.io/api/authentication/v1alpha1/policy.proto
  vendor/istio.io/api/common/v1alpha1/istio.common.v1alpha1.pb.html
  vendor/istio.io/api/common/v1alpha1/string.pb.go
  vendor/istio.io/api/common/v1alpha1/string.proto
  vendor/istio.io/api/mcp/Readme.md
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mixer/adapter/model/v1beta1/infrastructure_backend.proto
  vendor/istio.io/api/mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
  vendor/istio.io/api/mixer/v1/config/client/api_spec.pb.go
  vendor/istio.io/api/mixer/v1/config/client/api_spec.proto
  vendor/istio.io/api/mixer/v1/config/client/client_config.proto
  vendor/istio.io/api/mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  vendor/istio.io/api/mixer/v1/global_dictionary.yaml
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/policy/v1beta1/fixed_cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/istio.policy.v1beta1.pb.html
  vendor/istio.io/api/rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  vendor/istio.io/api/rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#7923 remove deprecated ServiceDiscovery.Instances
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_accounts.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_discovery.go
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/serviceaccounts.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/memory/discovery_test.go
Labels: approved, cla: yes, lgtm
