Repository istio/istio, pull requests merged in 2018-09, with the labels that each got.

#8412 Cleanup env variable use in tests
  mixer/test/client/env/envoy.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pkg/bootstrap/bootstrap_config_test.go
  pkg/test/env/istio.go
  pkg/test/env/variable.go
  pkg/test/framework/components/apps/local/envoy/envoy.go
  pkg/test/framework/settings/env.go
  pkg/test/util/istio_env.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/mcp_test.go
  tests/util/pilot_server.go
  tools/hyperistio/hyperistio.go
Labels: approved, cla: yes, lgtm

#7768 fix todo rename file cache.go to pod.go
  pilot/pkg/serviceregistry/kube/pod.go
  pilot/pkg/serviceregistry/kube/pod_test.go
Labels: approved, cla: yes, lgtm

#8396 fix typos
  bin/diff_yaml.py
  galley/pkg/crd/validation/config.go
  galley/pkg/crd/validation/monitoring.go
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/values-istio-auth-galley.yaml
  install/kubernetes/helm/istio/values-istio-auth-multicluster.yaml
  install/kubernetes/helm/istio/values-istio-auth.yaml
  install/kubernetes/helm/istio/values-istio-galley.yaml
  install/kubernetes/helm/istio/values-istio-multicluster.yaml
  install/kubernetes/helm/istio/values-istio-one-namespace-auth.yaml
  install/kubernetes/helm/istio/values-istio-one-namespace.yaml
  install/kubernetes/helm/istio/values-istio.yaml
  install/kubernetes/helm/istio/values.yaml
  istioctl/pkg/kubernetes/client.go
  mixer/pkg/adapter/info.go
  mixer/pkg/attribute/mutableBag.go
  mixer/pkg/il/interpreter/extern_test.go
  mixer/pkg/il/interpreter/interpreter.go
  mixer/pkg/lang/ast/expr.go
  mixer/pkg/runtime/handler/env.go
  pilot/pkg/config/clusterregistry/conversion.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pkg/collateral/control.go
  pkg/mcp/testing/testcerts/generate-certs.sh
  pkg/test/framework/driver.go
  security/cmd/istio_ca/main.go
  security/pkg/nodeagent/secrets/server_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/verify_cert.go
  security/tools/generate_cert/main.go
  tools/license/get_dep_licenses.go
Labels: approved, cla: yes, lgtm

#8233 fix typo
  pilot/pkg/model/validation.go
Labels: approved, cla: yes, lgtm

#8375 enable running unit tests for particular dir
  Makefile
Labels: approved, cla: yes, lgtm

#8452 Disable ID token authentication for CSR
  security/pkg/platform/client.go
  security/pkg/platform/client_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: cla: yes

#8472 Fix codecov for in istio.io/istio/pilot/cmd/pilot-agent/status/*
  codecov.requirement
Labels: cla: yes, lgtm

#8484 remove duplicated service account for constructing sds config
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#8488 add sds uds volume mount for gateway
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#8445 Avoid copy lock by using reference
  pkg/mcp/client/client_test.go
  pkg/mcp/creds/watcher.go
  pkg/mcp/server/server.go
Labels: approved, cla: yes, lgtm

#8427 Use root:root as owner of ca-certificates files
  docker/ca-certificates.tgz
  docker/fetch_cacerts.sh
Labels: approved, cla: yes, lgtm

#8475 Add missing namespace into a rule
  samples/bookinfo/policy/mixer-rule-productpage-ratelimit.yaml
Labels: approved, cla: yes, lgtm

#8345 Validate virtual service sniHosts
  pilot/pkg/model/service.go
  pilot/pkg/model/validation.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/virtualservice-route-tcp-a.yaml
Labels: approved, cla: yes

#8491 Fix typos
  tests/e2e/local/minikube/setup_test.sh
  tests/e2e/local/vagrant/install_prereqs_macos.sh
  tests/e2e/local/vagrant/setup_dockerdaemon_linux.sh
  tests/e2e/local/vagrant/setup_kubectl_config_host.sh
  tests/e2e/local/vagrant/setup_test.sh
Labels: approved, cla: yes, lgtm

#8489 Fix security unit test error
  security/pkg/platform/client_test.go
Labels: approved, cla: yes, lgtm

#8474 update release for deployment manager to 1.0.2
  install/gcp/deployment_manager/istio-cluster.jinja.schema
  install/gcp/deployment_manager/istio-cluster.yaml
Labels: cla: yes

#8473 Add multiple host + TCP check to validation
  pilot/pkg/model/validation.go
Labels: approved, cla: yes, lgtm

#8450 Fix OR logic in telemetry-gateway template (#8381)
  install/kubernetes/helm/istio/charts/telemetry-gateway/templates/gateway.yaml
Labels: cla: yes

#8430 Add the namespace to the grafana secret
  install/kubernetes/helm/istio/charts/grafana/templates/secret.yaml
Labels: cla: yes

#8417 Add grafana persist option to istio helm chart (#7553)
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/pvc.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes, needs-ok-to-test

#8492 Reuse common codes in common_macos.sh
  tests/e2e/local/vagrant/install_prereqs_macos.sh
Labels: approved, cla: yes, lgtm

#8431 add unit tests for func ConvertAddressToCidr, isProxyVersion
  pilot/pkg/networking/util/util_test.go
Labels: approved, cla: yes, lgtm

#8455 use client-go abstraction function to create secret informer
  Gopkg.lock
  pilot/pkg/config/clusterregistry/secretcontroller.go
Labels: approved, cla: yes, lgtm

#8419 Add TLS inspector if needed
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes, lgtm

#8498 [test-framework] Various fixes for running with existing k8s environment
  pkg/test/framework/components/apiserver/apiserver.go
  pkg/test/framework/components/apps/kube/app.go
  pkg/test/framework/components/apps/kube/apps.go
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/components/pilot/pilot.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/driver.go
  pkg/test/framework/environments/kubernetes/flags.go
  pkg/test/framework/environments/kubernetes/implementation.go
  pkg/test/framework/environments/kubernetes/settings.go
  pkg/test/framework/errors/errors.go
  pkg/test/framework/settings/env.go
  pkg/test/framework/settings/flags.go
  pkg/test/framework/settings/settings.go
  pkg/test/kube/accessor.go
  tests/integration2/examples/pilot/pilot_test.go
Labels: approved, cla: yes, lgtm

#8025 refactor func createSecret() to BuildSecret()
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/controller/secret.go
  security/pkg/pki/ca/controller/secret_test.go
Labels: approved, cla: yes, lgtm

#8110 [Ansible Installer] Updating Kiali to v0.6
  install/kubernetes/ansible/istio/tasks/install_addons.yml
Labels: approved, cla: yes, lgtm

#6802 Update performance test with ingressgateway.
  tools/perf_istio_rules.yaml
  tools/perf_k8svcs.yaml
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm

#8384 Merge part of node agent work to master.
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/caclient/client.go
  security/pkg/nodeagent/caclient/client_test.go
  security/pkg/nodeagent/model/secret.go
Labels: approved, cla: yes, lgtm

#8371 refactor pilot-config-monitor
  pilot/pkg/config/monitor/monitor.go
Labels: approved, cla: yes, lgtm

#8399 fixtodo: Move secret to security/pkg/k8s/.
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/monitoring.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
  security/pkg/registry/kube/serviceaccount.go
  security/tests/integration/certificateRotationTest/certificate_rotation_test.go
  security/tests/integration/kubernetes_utils.go
Labels: approved, cla: yes, lgtm

#8512 Add endpoint subcommand for istioctl proxy-config
  istioctl/cmd/istioctl/proxyconfig.go
  istioctl/cmd/istioctl/proxyconfig_test.go
  istioctl/pkg/util/clusters/wrapper.go
  istioctl/pkg/writer/envoy/clusters/clusters.go
  istioctl/pkg/writer/envoy/clusters/clusters_test.go
  istioctl/pkg/writer/envoy/clusters/testdata/clusterfiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clusters.json
  istioctl/pkg/writer/envoy/clusters/testdata/clustersnofiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clustersummary.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clustersummaryfiltered.txt
Labels: approved, cla: yes, lgtm

#8507 remove dead code
  pkg/util/webhookclient.go
Labels: approved, cla: yes, lgtm

#8311 Fix Kiali installation with Ansible on MacOS
  install/kubernetes/ansible/istio/tasks/install_addons.yml
Labels: approved, cla: yes, lgtm

#8511 pass pilot-discovery stop channel to secret controller
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/secretcontroller.go
Labels: approved, cla: yes, lgtm

#8189 Use stock grafana images instead of custom docker build
  addons/README.md
  addons/grafana/Dockerfile.grafana
  addons/grafana/README.md
  addons/grafana/dashboards.yaml
  addons/grafana/datasources.yaml
  addons/grafana/default-docker-commandline
  addons/grafana/grafana.ini
  bin/check_dashboards.sh
  install/kubernetes/helm/istio/charts/grafana/dashboards/galley-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-mesh-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-service-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-workload-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/mixer-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/pilot-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/fix_datasources.sh
  install/kubernetes/helm/istio/charts/grafana/templates/configmap-custom-resources.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/configmap-dashboards.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/pvc.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/service.yaml
  install/kubernetes/helm/istio/charts/grafana/values.yaml
  install/kubernetes/helm/istio/values.yaml
  tests/e2e/tests/dashboard/dashboard_test.go
  tools/istio-docker.mk
Labels: approved, area/policies and telemetry, cla: yes, lgtm

#8324 Correct authn tls-check for permissive mode.
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, cla: yes, lgtm

#8528 [test-framework] Skip tests if requirements not met
  pkg/test/framework/dependency/dependencies.go
  pkg/test/framework/driver.go
  tests/integration2/examples/pilot/pilot_test.go
Labels: approved, cla: yes, lgtm

#8185 Updated the flags list in E2E readme
  tests/e2e/README.md
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#8435 add FatalLevel for package log
  pkg/log/config.go
  pkg/log/default.go
  pkg/log/default_test.go
  pkg/log/options.go
  pkg/log/scope.go
  pkg/log/scope_test.go
Labels: approved, cla: yes, lgtm

#8458 Bugfix: Use DeepEqual instead of len equal when pushRoute
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: approved, cla: yes, lgtm

#8517 pilot: clusterregistry cleanup and fix
  pilot/pkg/config/clusterregistry/conversion.go
  pilot/pkg/config/clusterregistry/conversion_test.go
  pilot/pkg/config/clusterregistry/secretcontroller.go
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#8104 servicecontrol adapter: handle Close errors
  mixer/adapter/servicecontrol/handler.go
Labels: approved, cla: yes, lgtm

#8267 replace Mutex with RWMutex in mixer mcp backend
  mixer/pkg/config/mcp/backend.go
Labels: approved, cla: yes, lgtm

#8519 fix shellcheck
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm

#8524 fix bug: must register prometheus collector
  pilot/pkg/config/kube/crd/controller.go
Labels: approved, cla: yes, lgtm

#8521 Check if package exists before installing minikube-required packages
  tests/e2e/local/common_linux.sh
  tests/e2e/local/minikube/install_prereqs_debian.sh
Labels: approved, cla: yes, lgtm

#8550 Add missing endpoints example in istioctl pc
  istioctl/cmd/istioctl/proxyconfig.go
Labels: approved, cla: yes, lgtm

#7928 refine runClients func for mixer performance
  mixer/pkg/perf/controller.go
  mixer/pkg/perf/controller_test.go
  mixer/pkg/perf/run.go
Labels: approved, cla: yes, lgtm

#8555 Fix some shell lint errors
  tests/e2e/local/common_linux.sh
Labels: approved, cla: yes, lgtm

#8432 Intruduce portforward lib into test-framework
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/components/pilot/pilot.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/kube/forwarder.go
  tests/e2e/tests/dashboard/dashboard_test.go
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#8446 fix todo: pass in kubeconfig
  tests/e2e/tests/simple/nginx_test.go
  tests/util/kube_utils.go
Labels: approved, cla: yes, lgtm

#8248 Add centos support for minikube install
  tests/e2e/local/minikube/install_prereqs.sh
  tests/e2e/local/minikube/install_prereqs_centos.sh
Labels: approved, cla: yes, lgtm

#8533 rbac: add e2e test for rbac tcp policies.
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-rbac-rules.yaml.tmpl
Labels: approved, area/security/aaa, cla: yes, lgtm

#8422 USE_LOCAL_PROXY=1 make docker.proxy_debug uses workspace envoy
  Makefile
Labels: approved, cla: yes, lgtm

#8564 add service account annotation
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: cla: yes, lgtm

#8485 Add envoy config to expose prom endpoint for scraping
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/dashboards/pilot-dashboard.json
  install/kubernetes/helm/istio/charts/mixer/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/statsdtoprom.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/job.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/webhook.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/default_golden.json
  tests/e2e/framework/istioctl.go
  tests/e2e/tests/mixer/mixer_test.go
  tools/deb/envoy_bootstrap_v2.json
Labels: approved, cla: yes, lgtm

#8559 Deprecate istioctl crud operations
  install/gcp/deployment_manager/istio-cluster.jinja
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
  istioctl/cmd/istioctl/proxyconfig_test.go
  samples/CONFIG-MIGRATION.md
  samples/bookinfo/networking/ROUTING_RULE_MIGRATION.md
  samples/bookinfo/platform/consul/README.md
  samples/bookinfo/platform/consul/cleanup.sh
  samples/bookinfo/platform/kube/cleanup.sh
  samples/websockets/README.md
  tests/e2e/framework/istioctl.go
  tests/e2e/tests/simple/a_simple_1_test.go
  tools/README.md
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm

#8569 Add STATUS column for pc endpoint Command
  istioctl/cmd/istioctl/proxyconfig.go
  istioctl/cmd/istioctl/proxyconfig_test.go
  istioctl/pkg/writer/envoy/clusters/clusters.go
  istioctl/pkg/writer/envoy/clusters/clusters_test.go
  istioctl/pkg/writer/envoy/clusters/testdata/clusterfiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clusters.json
  istioctl/pkg/writer/envoy/clusters/testdata/clustersnofiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clustersummary.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clustersummaryfiltered.txt
Labels: approved, cla: yes, lgtm

#8576 annotation placeholder for ingress/egress services
  install/kubernetes/helm/istio/charts/gateways/templates/service.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#8565 Make map encode deterministically for grpc adapter
  mixer/pkg/protobuf/yaml/encoder.go
  mixer/pkg/protobuf/yaml/encoder_test.go
Labels: approved, cla: yes, lgtm

#8401 remove wrong core group in PolicyRule
  security/tests/integration/kubernetes_utils.go
Labels: approved, cla: yes, lgtm

#8391 cleanup move constant to a center file
  security/cmd/istio_ca/main.go
  security/pkg/cmd/constants.go
Labels: approved, cla: yes, lgtm

#8544 Fix a bunch of typos in test/e2e/local
  tests/e2e/local/minikube/Troubleshooting.md
  tests/e2e/local/vagrant/cleanup_linux_host.sh
  tests/e2e/local/vagrant/setup_kubectl_config_host.sh
  tests/e2e/local/vagrant/setup_vm.sh
Labels: approved, cla: yes, lgtm

#7742 stalebot: add no stalebot label for wip issues
  .github/stale.yml
Labels: approved, cla: yes, lgtm

#8518 rate limit MCP auth check handler failures
  pkg/mcp/server/server.go
Labels: approved, cla: yes, lgtm

#8582 create kubernetes.Clientset use common pkg istio.io/istio/pkg/kube/
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes, lgtm

#8596 helper script to create/inject service account annotation
  tools/inject-sa.sh
Labels: cla: yes, lgtm

#8586 Bug fix: GetPrivateIP timeout does not take effect
  pilot/pkg/proxy/net.go
Labels: approved, cla: yes, lgtm

#8600 Updated MacOS proxy to v1.0.2
  bin/init.sh
Labels: cla: yes

#8571 refactor updateCluster
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#8456 replace "" with metav1.NamespaceAll
  pilot/cmd/pilot-discovery/main.go
Labels: approved, cla: yes, lgtm

#8433 galley exit when ListenAndServeTLS fails
  galley/pkg/crd/validation/webhook.go
Labels: approved, cla: yes, lgtm

#8604 update inject-sa to make it work in macOS
  tools/inject-sa.sh
Labels: approved, cla: yes, lgtm

#8460 add parse_test.go
  mixer/pkg/protobuf/descriptor/parser.go
  mixer/pkg/protobuf/descriptor/parser_test.go
Labels: approved, cla: yes, lgtm

#8607 refine mcp authCheck log
  pkg/mcp/server/server.go
Labels: approved, cla: yes, lgtm

#8464 Fix shell globbing in cleanup task
  bin/testEnvLocalK8S.sh
Labels: approved, cla: yes, lgtm

#8599 merge construct sdsconfig change into master
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
Labels: approved, cla: yes, lgtm

#8463 Fix local test failures due to a wrong $KUBECONFIG
  Makefile
Labels: approved, cla: yes, lgtm

#8626 pilot/OWNERS should be able to approve pilot e2e tests
  tests/e2e/tests/pilot/OWNERS
Labels: approved, cla: yes, lgtm

#8597 pilot mcp integration fixes
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  mixer/cmd/mixs/cmd/server.go
  mixer/pkg/config/mcp/backend.go
  mixer/pkg/server/args.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/coredatamodel/controller.go
  pilot/pkg/config/coredatamodel/controller_test.go
  pkg/mcp/testing/server.go
  tests/e2e/tests/pilot/mcp_test.go
Labels: approved, cla: yes, lgtm

#8618 Shellcheck fixes to make it pass again
  bin/check_spelling.sh
  tests/e2e/local/minikube/install_prereqs_centos.sh
  tests/e2e/local/minikube/install_prereqs_debian.sh
  tests/e2e/local/minikube/install_prereqs_macos.sh
  tests/e2e/local/vagrant/install_prereqs_debian.sh
  tests/e2e/local/vagrant/install_prereqs_macos.sh
Labels: approved, cla: yes, lgtm

#8580 Enable Citadel to serve the new API
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/error.go
  security/pkg/pki/ca/error_test.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/probe/controller.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: approved, cla: yes, lgtm

#8561 Removing Mixer-specific proto hack that converts Struct => interface{}
  Gopkg.lock
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/converter.go
  mixer/pkg/runtime/config/converter_test.go
  mixer/pkg/runtime/config/ephemeral.go
  mixer/template/apikey/template.yaml
  mixer/template/apikey/template_handler_service.descriptor_set
  mixer/template/apikey/template_proto.descriptor_set
  mixer/template/authorization/template.yaml
  mixer/template/authorization/template_handler_service.descriptor_set
  mixer/template/authorization/template_proto.descriptor_set
  mixer/template/checknothing/template.yaml
  mixer/template/checknothing/template_handler_service.descriptor_set
  mixer/template/checknothing/template_proto.descriptor_set
  mixer/template/edge/template.yaml
  mixer/template/edge/template_handler_service.descriptor_set
  mixer/template/edge/template_proto.descriptor_set
  mixer/template/listentry/template.yaml
  mixer/template/listentry/template_handler_service.descriptor_set
  mixer/template/listentry/template_proto.descriptor_set
  mixer/template/logentry/template.yaml
  mixer/template/logentry/template_handler_service.descriptor_set
  mixer/template/logentry/template_proto.descriptor_set
  mixer/template/metric/template.yaml
  mixer/template/metric/template_handler_service.descriptor_set
  mixer/template/metric/template_proto.descriptor_set
  mixer/template/quota/template.yaml
  mixer/template/quota/template_handler_service.descriptor_set
  mixer/template/quota/template_proto.descriptor_set
  mixer/template/reportnothing/template.yaml
  mixer/template/reportnothing/template_handler_service.descriptor_set
  mixer/template/reportnothing/template_proto.descriptor_set
  mixer/template/tracespan/tracespan.yaml
  mixer/template/tracespan/tracespan_handler_service.descriptor_set
  mixer/template/tracespan/tracespan_proto.descriptor_set
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/policy/v1beta1/cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/fixed_cfg.pb.go
Labels: approved, cla: yes, lgtm

#8633 Missing err assignment in multicluster e2e
  tests/e2e/framework/multicluster.go
Labels: approved, cla: yes, lgtm

#8575 Added istio version to deployment template labels
  install/kubernetes/helm/istio/charts/certmanager/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/_labels.tpl
Labels: approved, cla: yes, lgtm

#8632 Change istio-auth enabled or not to installation
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cla: yes, lgtm

#8531 Fix the minikube e2e test broken by Error: ImagePullBackOff.
  tests/e2e/local/minikube/README.md
  tests/e2e/local/minikube/setup_test.sh
Labels: approved, area/test and release, cla: yes, lgtm

#8621 Remove GKE version spec from DM quickstart
  install/gcp/deployment_manager/istio-cluster.jinja
Labels: approved, cla: yes, lgtm

#8425 fix race detector goroutine limit
  mixer/pkg/server/server.go
  mixer/pkg/server/server_test.go
Labels: approved, cla: yes, lgtm

#8495 fix vulnerability in istio proxy_init image.
  pilot/docker/Dockerfile.proxy_init
Labels: approved, cla: yes, lgtm

#7760 Prints server info on istioctl version
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
  istioctl/cmd/istioctl/proxyconfig_test.go
  istioctl/cmd/istioctl/version_test.go
  istioctl/pkg/kubernetes/client.go
  pkg/version/cobra.go
  pkg/version/cobra_test.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, cla: yes, lgtm

#8457 add support to connect to istio-policy backend to DeployedMixer instances
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/environment/environment.go
Labels: approved, cla: yes, lgtm

#8654 fix pilot log formats
  pilot/cmd/pilot-agent/status/server.go
  pilot/pkg/config/kube/crd/client.go
  pilot/pkg/config/monitor/monitor.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/serviceregistry/kube/deregister.go
  pilot/test/mock/config.go
Labels: approved, cla: yes, lgtm

#8612 remove ConfigStore.Get's bool return value
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
  pilot/pkg/config/aggregate/config.go
  pilot/pkg/config/aggregate/config_test.go
  pilot/pkg/config/aggregate/fakes/config_store_cache.go
  pilot/pkg/config/cloudfoundry/controller.go
  pilot/pkg/config/cloudfoundry/controller_test.go
  pilot/pkg/config/cloudfoundry/fakes/store.go
  pilot/pkg/config/coredatamodel/controller.go
  pilot/pkg/config/kube/crd/client.go
  pilot/pkg/config/kube/crd/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/memory/config.go
  pilot/pkg/config/memory/controller.go
  pilot/pkg/config/monitor/monitor.go
  pilot/pkg/model/config.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.go
  pilot/test/mock/config.go
Labels: approved, cla: yes, lgtm

#8648 Support customize --vm-driver for minikube
  tests/e2e/local/minikube/README.md
  tests/e2e/local/minikube/setup_host.sh
Labels: approved, cla: yes, lgtm

#8662 Enable prometheus metric scrape for Jaeger backend
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#8666 Disable istio-proxy readiness probes by default for release 1.0.3.
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes, lgtm

#8592 cleanup: remove unused "proxyType" param in buildOutboundClusters
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
Labels: approved, cla: yes, lgtm

#8627 Fixup and port the showcase Mixer report test as a real test
  tests/integration2/mixer/main_test.go
  tests/integration2/mixer/report_test.go
Labels: approved, cla: yes, lgtm

#8183 Support responseHeadersToRemove in virtualservices
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: approved, cla: yes, lgtm

#8629 merge sds change in authN listener change into master
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: approved, cla: yes, lgtm

#8665 Update codecov job to build on its own.
  .circleci/config.yml
  Makefile
  bin/codecov.sh
Labels: approved, cla: yes, lgtm

#8581 cleanup use kubectl instead istioctl CRUD
  samples/bookinfo/platform/consul/cleanup.sh
  samples/bookinfo/platform/kube/cleanup.sh
Labels: approved, cla: yes, lgtm

#8635 rbac: add sample yaml for tcp rbac with mongodb.
  samples/bookinfo/platform/kube/rbac/mongodb-policy.yaml
  samples/bookinfo/platform/kube/rbac/ratings-v2-add-serviceaccount.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-on-mongodb.yaml
Labels: approved, cla: yes, lgtm

#8671 Implement Mixer check functionality in the test framework & backend.
  pkg/test/fakes/policy/backend.go
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/environment/environment.go
  tests/integration2/mixer/check_test.go
Labels: approved, cla: yes, lgtm

#8634 Add Makefile and CircleCI support for the tests using the new test framework.
  .circleci/config.yml
  Makefile
  tests/integration2/README.md
  tests/integration2/tests.mk
Labels: approved, cla: yes, lgtm

#8653 fix error print format in injector
  pilot/cmd/sidecar-injector/main.go
Labels: approved, cla: yes, lgtm

#8614 export push context init errors to prometheus
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: approved, cla: yes, lgtm

#7315 Check go version before export GCFLAGS for debug.
  Makefile
Labels: approved, cla: yes, lgtm

#7337 Deprecate unused Pilot proxy flags
  pilot/cmd/pilot-agent/main.go
Labels: approved, cla: yes, lgtm

#8258 add sleep ServiceAccount to sleep sample
  samples/sleep/sleep.yaml
Labels: approved, cla: yes, lgtm

#8402 process err when json.Unmarshal fail to avoid panic
  security/tools/generate_cert/main.go
Labels: approved, cla: yes, lgtm

#7642 use edsCliet instead of adsClient building the StreamEndpoints
  pilot/tools/debug/pilot_cli.go
Labels: cla: yes, lgtm

#8549 Mixer kube adapter optimization
  Gopkg.lock
  mixer/adapter/kubernetesenv/cache.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
Labels: cla: yes, lgtm

#8567 fix the redundancy description of function
  pilot/pkg/model/service.go
Labels: cla: yes, lgtm

#8668 ci: fix shellcheck errors and warnings
  tests/e2e/local/minikube/setup_host.sh
  tools/setup_perf_cluster.sh
Labels: cla: yes, lgtm

#8681 remove redundant code
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/lds.go
Labels: approved, cla: yes, lgtm

#8678 Add resource annotations test for webhook inject
  pilot/pkg/kube/inject/testdata/webhook/resource_annotations.yaml
  pilot/pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
  pilot/pkg/kube/inject/webhook_test.go
Labels: cla: yes

#8608 checkout if go-get is successful
  bin/ci2gubernator.sh
  bin/codecov.sh
  bin/fmt.sh
  bin/linters.sh
Labels: cla: yes

#8591 Remove redundant constant.
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes

#8570 coverage improvement for istio.io/istio/pilot/pkg/model
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/service_test.go
  pilot/pkg/model/validation_test.go
Labels: cla: yes, lgtm

#8516 fix vulnerability in istio grafana image.
  addons/grafana/Dockerfile.grafana
Labels: approved, cla: yes, lgtm

#8679 fix vulnerability in istio proxy_init image for 1.0
  pilot/docker/Dockerfile.proxy_init
Labels: approved, cla: yes, lgtm

#8574 bug-fix: grpc.EnableTracing set before rpc sent or received
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes, lgtm

#8680 reused dead NewMemstore() function
  mixer/pkg/config/storetest/storetest.go
Labels: approved, cla: yes, lgtm

#8690 Fix build break.
  pkg/test/framework/components/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#8669 Fix wrong comment and rename GetSecret() to GenerateSecret()
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: approved, cla: yes, lgtm

#8646 Moved and renamed the shellcheck.sh script to fit other checkers
  .circleci/config.yml
  bin/check_shell_scripts.sh
Labels: approved, cla: yes, lgtm

#8674 CentOS support for local vagrant setup
  tests/e2e/local/common_linux.sh
  tests/e2e/local/minikube/install_prereqs_centos.sh
  tests/e2e/local/vagrant/install_prereqs.sh
  tests/e2e/local/vagrant/install_prereqs_centos.sh
Labels: approved, cla: yes, lgtm

#8636 Inject: Fix potential empty pod name and namespace
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/webhook.go
Labels: approved, cla: yes, lgtm

#8686 cleanup: remove proxyType parameter in GetMutualTLS
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, cla: yes, lgtm

#8695 Clean up owners a tad.
  OWNERS
  mixer/OWNERS
Labels: approved, cla: yes, lgtm

#8442 Fixing a context leak in pilot-agent
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/status/server.go
Labels: approved, cla: yes, lgtm

#8657 cherrypick SN service annotation PRs to master
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  security/cmd/istio_ca/main.go
  security/pkg/registry/kube/service.go
  security/pkg/registry/kube/service_test.go
Labels: approved, cla: yes, lgtm

#8708 add `hzxuzhonghu` into pilot owners
  pilot/OWNERS
Labels: cla: yes

#8712 Remove the duplicate cluster for endpoint
  istioctl/pkg/writer/envoy/clusters/clusters.go
  istioctl/pkg/writer/envoy/clusters/clusters_test.go
  istioctl/pkg/writer/envoy/clusters/testdata/clustermultihostsfiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clusters.json
  istioctl/pkg/writer/envoy/clusters/testdata/clustersnofiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clustersummary.txt
Labels: approved, cla: yes, lgtm

#8717 Add m1093782566 as test/e2e/local owner
  tests/e2e/local/OWNERS
Labels: approved, cla: yes, lgtm

#8704 [test-framework] fix port forwarder
  pkg/test/framework/components/mixer/mixer.go
  pkg/test/framework/components/pilot/pilot.go
  pkg/test/kube/forwarder.go
Labels: approved, cla: yes, lgtm

#8672 Expose envoy prom port for metrics scraping instead of using annotations
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/job.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/webhook.go
Labels: cla: yes, lgtm

#8256 add a log if proxy can not resolve StatsdUdpAddress
  pilot/cmd/pilot-agent/main.go
Labels: approved, cla: yes, lgtm

#8700 Moving test/integration to test/integration_old
  security/tests/integration/certificateRotationTest/certificate_rotation_test.go
  security/tests/integration/istio_ca_cert_rotation_env.go
  security/tests/integration/istio_ca_node_agent_env.go
  security/tests/integration/istio_ca_secret_env.go
  security/tests/integration/kubernetes_pod.go
  security/tests/integration/kubernetes_service.go
  security/tests/integration/nodeAgentTest/node_agent_test.go
  security/tests/integration/secretCreationTest/secret_creation_test.go
  tests/integration_old/README.md
  tests/integration_old/component/fortio_server/fortio_server_comp.go
  tests/integration_old/component/mixer/mixer_binary_comp.go
  tests/integration_old/component/proxy/README.md
  tests/integration_old/component/proxy/envoy.conf.template
  tests/integration_old/component/proxy/proxy_binary_comp.go
  tests/integration_old/component/proxy/start_envoy
  tests/integration_old/example/environment/appOnlyEnv/app_only_env.go
  tests/integration_old/example/environment/appOnlyEnv/cmd/main.go
  tests/integration_old/example/environment/mixerEnvoyEnv/cmd/main.go
  tests/integration_old/example/environment/mixerEnvoyEnv/mixer_envoy_env.go
  tests/integration_old/example/integration.sh
  tests/integration_old/example/tests/sample1/sample1_test.go
  tests/integration_old/example/tests/sample2/sample2_test.go
  tests/integration_old/framework/component.go
  tests/integration_old/framework/configuration.go
  tests/integration_old/framework/environment.go
  tests/integration_old/framework/status.go
  tests/integration_old/framework/testEnvManager.go
  tests/integration_old/framework/testProcess.go
  tests/integration_old/images/integration_framework_structure.jpg
Labels: approved, cla: yes, lgtm

#8711 fix codecov for missing istio.io/istio/security/pkg/k8s/controller
  codecov.requirement
Labels: approved, cla: yes, lgtm

#8724 move CA endpoint to nodeagent config file
  install/kubernetes/helm/istio/charts/nodeagent/templates/daemonset.yaml
  install/kubernetes/helm/istio/values.yaml
  security/cmd/node_agent_k8s/main.go
  security/cmd/node_agent_k8s/nodeagent.yaml
Labels: approved, cla: yes, lgtm

#8405 remove set -x
  bin/init.sh
  bin/init_helm.sh
Labels: approved, cla: yes, lgtm

#8577 Restore full dashboard e2e tests to working status
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-mesh-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-service-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/mixer-dashboard.json
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: approved, cla: yes, lgtm

#8142 Replacing hardcoded namespace in pilot helm template
  install/kubernetes/helm/istio/charts/pilot/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/meshexpansion.yaml
Labels: approved, cla: yes, lgtm

#8726 Fix post-submit failure
  pilot/pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
Labels: approved, cla: yes, lgtm

#6090 remove targetPort & containerPort from chart exposed list.
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/service.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/NOTES.txt
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/service.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/NOTES.txt
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/ingress-jaeger.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/service-jaeger.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/service.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#8334 add validation for LoadBalancer
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: approved, cla: yes, lgtm
