Repository istio/istio, pull requests merged in 2018-05, with the labels that each got.

#5268 Enable mTLS for pilot e2e tests
  Makefile
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  tests/e2e/tests/pilot/egressgateway_test.go
  tests/e2e/tests/pilot/testdata/app.yaml.tmpl
  tests/istio.mk
Labels: approved, cla: human-approved, cla: yes, lgtm

#4502 Fix config error when running with minikube
  .circleci/config
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#5297 Improve the script to generate jwt
  security/tools/jwt/README.md
Labels: approved, cla: yes

#5289 Make metrics command ready for web scale.
  istioctl/cmd/istioctl/metrics.go
Labels: approved, cla: yes, lgtm

#5326 prevent mixing istio-ingressgateway and istio-ingress in proxy config
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/config_test.go
Labels: cla: yes, lgtm

#5316 Quick fix for consistent upgrade e2e test failure
  tests/e2e/tests/upgrade/upgrade_test.go
Labels: cla: yes

#5184 Add all circle ci tests to testgrid
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#5336 use client-go's default client config loading rules (cherry-pick into 0.8)
  istioctl/cmd/istioctl/inject.go
Labels: approved, cla: yes, lgtm

#5333 Fix egressgateway e2e test when mTLS enable.
  tests/e2e/tests/pilot/egressgateway_test.go
  tests/e2e/tests/pilot/testdata/v1alpha3/disable-mtls-egressgateway.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/service-entry.yaml
Labels: cla: yes

#5362 bugfix: tracing operations for mixer sidecar
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
Labels: cla: yes

#5337 disable flakey controller cache tests in Pilot
  tests/e2e/tests/pilot/controller_test.go
Labels: cla: yes

#5366 Fix v1alpha3 abort rule not working in task
  samples/bookinfo/routing/route-rule-ratings-test-abort.yaml
Labels: cla: yes

#5374 Disable rbac e2e test.
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#5373 eds: Hold lock for iterating on EDS clusters for logging
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: cla: yes

#5312 Fix mesh expansion, add the v2 ports
  install/kubernetes/helm/istio/charts/pilot/templates/service.yaml
  install/kubernetes/mesh-expansion.yaml
  pilot/docker/envoy_pilot.yaml.tmpl
Labels: cla: yes, lgtm

#5339 re-add flags for consul and eureka
  pilot/cmd/pilot-discovery/main.go
Labels: approved, cla: yes, kind/blocking release, kind/customer issue, kind/fixit, lgtm

#5378 Revert 'enable auth on the noauth test'
  .circleci/config.yml
  Makefile
  tests/istio.mk
Labels: cla: yes

#5375 remove api section from istio.deps
  istio.deps
Labels: approved, cla: yes, lgtm

#5386 Attempt to capture periodic/postsubmit in testgrid
  bin/ci2gubernator.sh
  tests/istio.mk
Labels: cla: no

#5055 Per-port Destination rules and fault injection
  Gopkg.lock
  Makefile
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/egress-rule-tcp-wikipedia-cidr.yaml.golden
  istioctl/pkg/convert/egress.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/testdata/v1alpha3/serviceentry-tcp-wikipedia-cidr.yaml
  tests/istio.mk
Labels: approved, area/networking, cla: human-approved, kind/blocking release

#5363 Wildcard hostnames
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/authentication.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/proxy/envoy/v1/authentication.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/mock/discovery.go
  pilot/pkg/proxy/envoy/v1/policy.go
  pilot/pkg/proxy/envoy/v1/route.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/serviceaccounts.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/eureka/conversion.go
  pilot/pkg/serviceregistry/eureka/conversion_test.go
  pilot/pkg/serviceregistry/eureka/serviceaccounts.go
  pilot/pkg/serviceregistry/eureka/servicediscovery.go
  pilot/pkg/serviceregistry/eureka/servicediscovery_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/serviceaccounts.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
Labels: cla: yes, kind/blocking release

#5394 Correct authn flags for pilot v2 e2e test.
  Makefile
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
Labels: approved, cla: yes, lgtm

#5396 Second attempt to fix uploading test results from post-submit
  bin/ci2gubernator.sh
Labels: cla: yes

#5395 allow 'istioctl get gateway' etc
  istioctl/cmd/istioctl/main.go
Labels: approved, area/networking, cla: yes, kind/blocking release, lgtm

#5398 Test to see failure with latest fortio in 0.6, if any
  tests/e2e/tests/simple/simple1_test.go
Labels: cla: yes

#5385 Run e2e test for mTLS enable via authn policy in all Istio installation mode
  tests/e2e/tests/pilot/authn_policy_test.go
Labels: approved, cla: yes, lgtm

#5387 fix incorrect upstream tls context generation
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes

#5388 Update istio.io/api dependency.
  Gopkg.lock
  vendor/istio.io/api/mixer/adapter/model/v1beta1/check.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/info.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/info.proto
  vendor/istio.io/api/mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
  vendor/istio.io/api/mixer/adapter/model/v1beta1/template.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/template.proto
  vendor/istio.io/api/mixer/v1/global_dictionary.yaml
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/mixer/adapter/model/v1beta1/template_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: approved, cla: yes

#5368 add root CA bundle and use it for making https request in pilot
  pilot/docker/Dockerfile.pilot
  pilot/docker/certs/cacert.pem
  pilot/pkg/model/jwks_resolver.go
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#5317 add logging/increase retry times when mock server fails to start
  pilot/pkg/model/test/mockopenidserver.go
Labels: cla: yes

#5267 Add mixer tests for the Istio authn filter
  mixer/test/client/env/envoy.go
  mixer/test/client/env/envoy_conf.go
  mixer/test/client/env/ports.go
  mixer/test/client/env/setup.go
  mixer/test/client/fault_inject/fault_inject_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_origin_reject_no_jwt/authn_origin_reject_no_jwt_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_peer_reject_no_jwt/authn_peer_reject_no_jwt_test.go
  mixer/test/client/istio_authn_peer_reject_no_mtls/authn_peer_reject_no_mtls_test.go
  mixer/test/client/istio_authn_peer_reject_no_tls/authn_peer_reject_no_tls_test.go
Labels: approved, cla: yes, lgtm

#5402 re-enable the rbac e2e test in e2e_pilot and e2e_pilotv2 (no auth).
  tests/istio.mk
Labels: cla: yes

#5401 Use v2 in ingressgateway, pilot, mixer. Cleanup.
  install/kubernetes/helm/istio/charts/egressgateway/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/statsdtoprom.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/zipkin/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: cla: yes

#5399 Cleanup circle zombies
  .circleci/config.yml
  tests/istio.mk
Labels: cla: yes

#5369 Add example to simple showcase test
  pkg/test/cluster/fortioapp.go
  pkg/test/dependency/fortioapps.go
  pkg/test/environment.go
  tests/e2e/tests/showcase/simple_showcase_test.go
Labels: cla: yes, lgtm

#5411 istioctl convert-networking-config Ingress to Gateway
  istioctl/cmd/istioctl/convert/cmd.go
  istioctl/cmd/istioctl/convert/cmd_test.go
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/another-ingress.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/myservice-ingress.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/merged-gateway.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/myservice-gateway.yaml.golden
  istioctl/pkg/convert/ingress.go
  pilot/pkg/config/kube/ingress/conversion.go
Labels: cla: yes, lgtm

#5426 Revert "Add mixer tests for the Istio authn filter (#5267)"
  mixer/test/client/env/envoy.go
  mixer/test/client/env/envoy_conf.go
  mixer/test/client/env/ports.go
  mixer/test/client/env/setup.go
  mixer/test/client/fault_inject/fault_inject_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_origin_reject_no_jwt/authn_origin_reject_no_jwt_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_peer_reject_no_jwt/authn_peer_reject_no_jwt_test.go
  mixer/test/client/istio_authn_peer_reject_no_mtls/authn_peer_reject_no_mtls_test.go
  mixer/test/client/istio_authn_peer_reject_no_tls/authn_peer_reject_no_tls_test.go
Labels: approved, cla: yes, lgtm

#5318 Change Istio CA to Citadel in README.
  README.md
  security/README.md
  security/overview.svg
Labels: approved, cla: yes

#5452 [test-framework] Rationalize FortioApp model. (#1)
  pkg/test/cluster/fortioapp.go
  pkg/test/environment.go
  tests/e2e/tests/showcase/simple_showcase_test.go
Labels: cla: yes, lgtm

#5463 Update proxy sha for release-0.8 branch
  istio.deps
Labels: cla: yes, lgtm

#5460 Change GKE version from 1.9.6-gke.0 to 1.9.6-gke.1
  install/gcp/deployment_manager/istio-cluster.jinja
Labels: approved, cla: yes, lgtm

#5447 Add dns lookup family to the clusters
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: cla: yes

#5471 Fix fault rule versions
  samples/bookinfo/routing/route-rule-ratings-test-abort.yaml
  samples/bookinfo/routing/route-rule-ratings-test-delay.yaml
Labels: cla: yes

#5451 [test-framework] First pass cleanup of the model (#2)
  pkg/test/cluster/app.go
  pkg/test/dependency/cluster.go
  pkg/test/dependency/policybackend.go
  pkg/test/environment.go
  pkg/test/label/labels.go
  pkg/test/operations.go
  tests/e2e/tests/showcase/mixer_showcase_test.go
  tests/e2e/tests/showcase/showcase_test.go
Labels: cla: yes

#5474 [test-framework] Remove charts/DeployedIstioComponent and Environment cleanup
  pkg/test/charts/charts.go
  pkg/test/cluster/environment.go
  pkg/test/environment.go
  pkg/test/local/environment.go
  tests/e2e/tests/showcase/mixer_showcase_test.go
  tests/e2e/tests/showcase/showcase_test.go
Labels: cla: yes, lgtm

#5476 Revert incorrect change to fault rules
  samples/bookinfo/routing/route-rule-ratings-test-abort.yaml
  samples/bookinfo/routing/route-rule-ratings-test-delay.yaml
Labels: cla: yes

#5405 enable mtls for ingressgateway loadbalancer istio-auth.yaml
  Makefile
Labels: cla: yes

#5461 Remove expected error message check from jwks_resolver unit test.
  pilot/pkg/model/jwks_resolver_test.go
Labels: cla: yes, lgtm

#5468 Fix duplicate key on helm ingress/deployment.yaml template
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#5341 Fix IPv6 iptables.
  tools/deb/istio-iptables.sh
Labels: approved, cla: yes, lgtm

#5445 refactor secret controller
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/conversion.go
  pilot/pkg/config/clusterregistry/secretcontroller.go
Labels: approved, cla: yes, lgtm

#5487 Cleaning up App API to simplify URL construction
  pkg/test/cluster/app.go
  pkg/test/cluster/app_test.go
  pkg/test/cluster/fortioapp.go
  pkg/test/dependency/fortioapps.go
  pkg/test/environment/environment.go
  pkg/test/impl/driver/args.go
  tests/e2e/tests/showcase/mixer_showcase_test.go
  tests/e2e/tests/showcase/pilot_showcase_test.go
  tests/e2e/tests/showcase/showcase_test.go
Labels: cla: yes, lgtm

#5389 Race tests and more metrics around events from k8s
  pilot/pkg/config/kube/crd/controller.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/cache.go
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#5510 [test-framework] API and command-line cleanup.
  pkg/test/dependency/cluster.go
  pkg/test/flags.go
  pkg/test/impl/apiserver/instance.go
  pkg/test/impl/apiserver/instance_darwin.go
  pkg/test/impl/apiserver/instance_linux.go
  pkg/test/impl/driver/instance.go
  pkg/test/impl/driver/interface.go
  pkg/test/impl/helm/chart.go
  pkg/test/operations.go
Labels: approved, cla: yes, lgtm

#5482 Update proxy sha with stripped binary
  istio.deps
Labels: approved, cla: yes, lgtm

#5450 proxy/envoy image build fix
  bin/init.sh
Labels: approved, cla: yes, lgtm

#5520 Fix Cloud Foundry pilot test log dir
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#5501 Use template variable for access log
  mixer/test/client/env/envoy_conf.go
Labels: approved, cla: yes, lgtm

#5512 Create CA certs and make citadel run with designated certs in multi-c…
  install/kubernetes/helm/istio-remote/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  tests/e2e/framework/kubernetes.go
  tests/e2e/framework/multicluster.go
Labels: approved, cla: yes, lgtm

#5530 Update mixer service port names to use http/2
  Gopkg.lock
  install/kubernetes/helm/istio-remote/templates/endpoints.yaml
  install/kubernetes/helm/istio-remote/templates/service.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/service.yaml
  istio.deps
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: cla: yes, kind/blocking release

#5370 mixer: bind gRPC API locally to 9092 and use proxy on 9091
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  mixer/cmd/mixs/cmd/server.go
  mixer/pkg/server/args.go
  mixer/pkg/server/server.go
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
Labels: approved, cla: yes

#5506 ignore and remove git history file
  .gitignore
  .history_rewritten_20171102
Labels: cla: yes

#5467 Fix a DestinationRule for the bookinfo egress test
  samples/bookinfo/routing/egress-rule-google-apis.yaml
  tests/istio.mk
Labels: approved, lgtm

#5406 Add helm lint check
  bin/linters.sh
Labels: approved, cla: yes, needs-ok-to-test

#5465 Use the global image pull policy flag in the sidecar-injector ConfigMap
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
Labels: approved, cla: yes, lgtm

#5256 Make Kube Pod cache log line more helpful
  pilot/pkg/serviceregistry/kube/cache.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#4213 helloworld example does not include '-n istio-system' in commands for…
  samples/helloworld/README.md
Labels: approved, cla: no, lgtm, needs-ok-to-test, stale?

#5515 Separate debian linux distribution
  vagrant-kubernetes-istio/README.md
  vagrant-kubernetes-istio/install_prereqs.sh
  vagrant-kubernetes-istio/install_prereqs_debian.sh
Labels: approved, cla: yes, lgtm

#5544 enable rbac test for auth/e2e_pilotv2
  tests/istio.mk
Labels: cla: yes

#5553 Fix download path for kubectl on mac
  vagrant-kubernetes-istio/install_prereqs_macos.sh
Labels: approved, cla: yes, lgtm

#5494 Don't call DumpResponse when res is nil
  pilot/pkg/proxy/envoy/v2/xds_test.go
Labels: approved, cla: yes, lgtm

#5548 Correct container port of test app for dashboard e2e test
  tests/e2e/tests/dashboard/netcat-rules.yaml
Labels: cla: yes

#5551 [test-framework] Add health check to local envoy agent at startup
  pkg/test/local/proxy/envoy/agent/agent.go
  pkg/test/local/proxy/envoy/agent/agent_test.go
  pkg/test/local/proxy/envoy/agent/proxy_config.go
  pkg/test/local/proxy/envoy/envoy.go
  pkg/test/proxy/envoy/agent/agent_test.go
Labels: cla: yes

#5528 Make DNS names case-insensitive
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: cla: yes

#5558 Launch pilot locally failed for my kube config
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes

#5349 use namespace as chart name so it is unique
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#5562 Turn off logging for AZ as it is not in scope for 0.8
  pilot/pkg/proxy/envoy/v1/watcher.go
  pkg/bootstrap/bootstrap_config.go
Labels: approved, cla: yes, lgtm

#5563 Create client using mechanism of PR 5300
  istioctl/cmd/istioctl/deregister.go
  istioctl/cmd/istioctl/register.go
Labels: approved, cla: yes, lgtm

#5464 Update api sha to release0.8 latest.
  Gopkg.lock
  Gopkg.toml
  vendor/istio.io/api/mixer/adapter/model/v1beta1/check.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/info.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/info.proto
  vendor/istio.io/api/mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
  vendor/istio.io/api/mixer/adapter/model/v1beta1/template.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/template.proto
  vendor/istio.io/api/mixer/v1/global_dictionary.yaml
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/mixer/adapter/model/v1beta1/template_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: cla: yes, lgtm

#5543 Use port number instead of port name in CDS, EDS (for v2 only)
  .circleci/config.yml
  pilot/pkg/config/monitor/copilot_snapshot.go
  pilot/pkg/config/monitor/copilot_snapshot_test.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/mock/discovery.go
  pilot/pkg/proxy/envoy/v1/route.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery_test.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/eureka/servicediscovery.go
  pilot/pkg/serviceregistry/eureka/servicediscovery_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-update-virtualservice.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-virtualservice.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-gateway-a.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-ingressgateway.yaml
  tests/istio.mk
Labels: cla: no

#5570 set h2 max_concurrent_streams to 1073741824
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: cla: yes

#5533 Buid, packaging, script fixes.
  Makefile
  pilot/docker/Dockerfile.pilot
  pilot/docker/Dockerfile.proxyv2
  tools/deb/Dockerfile
  tools/deb/deb_test.sh
  tools/deb/istio-iptables.sh
  tools/deb/istio-start.sh
  tools/deb/istio.mk
  tools/hyperistio/hyperistio.go
  tools/istio-docker.mk
Labels: cla: yes, lgtm

#5572 V1 - set h2 max_concurrent_streams to 1073741824
  pilot/pkg/proxy/envoy/v1/authentication_test.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/resources.go
  pilot/pkg/proxy/envoy/v1/route.go
  pilot/pkg/proxy/envoy/v1/testdata/cds-authn-jwt.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-circuit-breaker.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ingress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-mixer-check-report-config.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-redirect-egress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context-optin.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context-optout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds.json.golden
Labels: cla: yes

#5560 Fix setting empty CA certificates field in gateway
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: cla: yes

#5561 Update proxy to have raw JWT claims.
  istio.deps
  mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go
Labels: cla: yes

#5566 attemp to fix 5564 - consistent way to create k8s client
  broker/pkg/platform/kube/crd/client.go
  istioctl/cmd/istioctl/inject.go
  istioctl/cmd/istioctl/main.go
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/sidecar-injector/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/client.go
  pilot/pkg/serviceregistry/kube/client.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/test/eurekamirror/eurekamirror.go
  security/cmd/istio_ca/main.go
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/controller/controller_test.go
Labels: approved, cla: yes, lgtm

#5575 Fix proxy config command for ingress, egressgateway and ingressgateway
  istioctl/cmd/istioctl/config.go
Labels: approved, cla: yes, lgtm

#5550 Define request.auth.claims
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/pkg/attribute/list.gen.go
  mixer/pkg/il/testing/tests.go
  mixer/pkg/protobuf/yaml/dynamic/encoder_test.go
  mixer/testdata/config/attributes.yaml
Labels: approved, cla: yes, lgtm

#5555 Fix minor issues with scripts
  vagrant-kubernetes-istio/README.md
  vagrant-kubernetes-istio/Troubleshooting.md
  vagrant-kubernetes-istio/install_prereqs_debian.sh
  vagrant-kubernetes-istio/install_prereqs_macos.sh
Labels: cla: yes, lgtm

#5593 Change default to 60 sec push
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: cla: yes

#5597 Change envoy to default to log level warn #5559
  pilot/cmd/pilot-agent/main.go
Labels: cla: yes

#5448 fix the bookinfo v1alpha3 test Makefile target name
  tests/istio.mk
Labels: cla: yes

#5541 Add starting watchers for dynamically added remote clusters
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/secretcontroller.go
  pilot/pkg/proxy/envoy/v1/discovery.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
Labels: cla: human-approved

#5556 Fix envoy binary used for tests on Mac
  bin/init.sh
Labels: cla: no

#5252 Add more info to accesslog.logentry instance for telemetry
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  install/kubernetes/templates/istio-mixer.yaml.tmpl
  mixer/adapter/stackdriver/config/adapter.stackdriver.config.pb.html
  mixer/adapter/stackdriver/config/config.pb.go
  mixer/adapter/stackdriver/config/config.proto
  mixer/adapter/stackdriver/log/log.go
  mixer/adapter/stackdriver/log/log_test.go
  mixer/testdata/config/stackdriver.yaml
Labels: cla: yes

#5601 Fix tee error resolving in false negative for some test jobs
  Makefile
  tests/istio.mk
Labels: cla: yes

#5627 Disable upgrade test since it is flaky and noisy.
  tests/e2e/tests/upgrade/upgrade_test.go
Labels: cla: yes, lgtm

#5610 allow users to use node port for istio ingress without producing another service for lb
  install/kubernetes/helm/istio/charts/ingress/templates/service.yaml
  install/kubernetes/helm/istio/charts/ingressgateway/templates/service.yaml
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#5585 fix pre-allocating slice capacity in pilot
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: area/networking, cla: no

#5602 remove generate_yaml-envoyv2_transition_auth Makefile target
  Makefile
  tests/istio.mk
Labels: cla: yes

#5584 Provide default requested resources for cpu/mem for sidecar
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/auth.cert-dir.yaml.injected
  pilot/pkg/kube/inject/testdata/auth.non-default-service-account.yaml.injected
  pilot/pkg/kube/inject/testdata/auth.yaml.injected
  pilot/pkg/kube/inject/testdata/cronjob.yaml.injected
  pilot/pkg/kube/inject/testdata/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/enable-core-dump.yaml.injected
  pilot/pkg/kube/inject/testdata/format-duration.yaml.injected
  pilot/pkg/kube/inject/testdata/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-always.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-ignore.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-never.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-proxy-override.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-tproxy-debug.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-tproxy.yaml.injected
  pilot/pkg/kube/inject/testdata/hello.yaml.injected
  pilot/pkg/kube/inject/testdata/job.yaml.injected
  pilot/pkg/kube/inject/testdata/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/list.yaml.injected
  pilot/pkg/kube/inject/testdata/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-params-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-params.yaml.injected
Labels: cla: human-approved

#5636 Security on flag fix
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/values.yaml
  tests/e2e/framework/kubernetes.go
Labels: cla: yes

#5596 skip listener when filters cannot be marshalled
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes, kind/blocking release

#5640 Examples should use current rule types
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#5625 Add ctrlz to Pilot
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
Labels: cla: yes

#5630 Dump pilot configuration from dump_kubernetes.sh
  Makefile
  bin/dump_kubernetes.sh
Labels: cla: yes

#5635 Upgrade from 0.7.1 to 0.8.0 fails
  install/kubernetes/helm/istio/charts/mixer/templates/clusterrole.yaml
Labels: cla: yes, do-not-merge/hold

#5567 Generate junit reports for all e2e jobs in Prow presubmit
  prow/e2e-suite.sh
Labels: cla: yes

#5637 Fix e2e egress httpbin.org tests
  tests/e2e/tests/pilot/routing_to_egress_test.go
Labels: cla: yes

#5649 Turn down k8senv adapter logging
  mixer/adapter/kubernetesenv/kubernetesenv.go
Labels: cla: yes

#5613 Add binding address support to ctrlz.
  pkg/ctrlz/ctrlz.go
  pkg/ctrlz/options.go
Labels: cla: yes

#5616 More pre-release fixes cleanup
  Makefile
  bin/dump_kubernetes.sh
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/lds.go
  tools/deb/Dockerfile
  tools/deb/deb_test.sh
  tools/deb/envoy_bootstrap_v2.json
  tools/deb/istio.mk
  tools/hyperistio/hyperistio.go
Labels: cla: yes

#5618 ALPN upgrade to http/2.0
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: cla: yes

#5656 Use jaeger for zipkin service
  install/kubernetes/helm/istio/charts/zipkin/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/zipkin/templates/service.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#5417 Add e2e_mixer tests for v1alpha3
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/util/util.go
  samples/bookinfo/routing/mixer-rule-additional-telemetry.yaml
  samples/bookinfo/routing/mixer-rule-deny-label.yaml
  samples/bookinfo/routing/mixer-rule-deny-serviceaccount.yaml
  samples/bookinfo/routing/mixer-rule-ingress-denial.yaml
  samples/bookinfo/routing/mixer-rule-ratings-denial.yaml
  samples/bookinfo/routing/mixer-rule-ratings-ratelimit.yaml
  tests/e2e/tests/bookinfo/main_test.go
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/istio.mk
Labels: cla: yes

#5634 Add a default secure ingress volume
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#5653 As discussed, generate an easy-to use for demo config
  .gitignore
  Makefile
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  install/kubernetes/helm/istio/values-istio-all.yaml
  install/kubernetes/helm/istio/values-istio-auth-multicluster.yaml
  install/kubernetes/helm/istio/values-istio-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
  install/kubernetes/helm/istio/values-istio-multicluster.yaml
  install/kubernetes/helm/istio/values-istio-one-namespace-auth.yaml
  install/kubernetes/helm/istio/values-istio-one-namespace.yaml
  install/kubernetes/helm/istio/values-istio.yaml
  install/kubernetes/helm/istio/values.yaml
  install/kubernetes/templates/addons/servicegraph.yaml.tmpl
  install/updateVersion.sh
  install/updateVersion_orig.sh
  release/create_release_archives.sh
Labels: cla: yes

#5655 Release-0.8: update api sha
  Gopkg.lock
  mixer/adapter/cloudwatch/config/adapter.cloudwatch.config.pb.html
  mixer/adapter/cloudwatch/config/config.pb.go
  mixer/adapter/kubernetesenv/template/adapter.template.kubernetes.pb.html
  mixer/adapter/kubernetesenv/template/template_proto.descriptor_set
  mixer/adapter/servicecontrol/template/servicecontrolreport/servicecontrolReport.pb.html
  mixer/adapter/servicecontrol/template/servicecontrolreport/template_proto.descriptor_set
  mixer/pkg/attribute/list.gen.go
  mixer/template/apikey/apiKey.pb.html
  mixer/template/apikey/template_proto.descriptor_set
  mixer/template/authorization/authorization.pb.html
  mixer/template/authorization/template_proto.descriptor_set
  mixer/template/logentry/logEntry.pb.html
  mixer/template/logentry/template_proto.descriptor_set
  mixer/template/metric/metric.pb.html
  mixer/template/metric/template_proto.descriptor_set
  mixer/template/quota/quota.pb.html
  mixer/template/quota/template_proto.descriptor_set
  mixer/template/sample/apa/Apa_proto.descriptor_set
  mixer/template/sample/apa/istio.mixer.adapter.sample.myApa.pb.html
  mixer/template/sample/check/CheckTesterTemplate_proto.descriptor_set
  mixer/template/sample/check/istio.mixer.adapter.sample.check.pb.html
  mixer/template/sample/quota/QuotaTesterTemplate_proto.descriptor_set
  mixer/template/sample/quota/istio.mixer.adapter.sample.quota.pb.html
  mixer/template/sample/report/ReportTesterTemplate_proto.descriptor_set
  mixer/template/sample/report/istio.mixer.adapter.sample.report.pb.html
  mixer/template/tracespan/traceSpan.pb.html
  mixer/template/tracespan/tracespan_proto.descriptor_set
  mixer/test/spyAdapter/template/report/SampleReport.pb.html
  mixer/test/spyAdapter/template/report/reporttmpl_proto.descriptor_set
  mixer/tools/codegen/pkg/bootstrapgen/testdata/apa/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/check/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/quota/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/report1/template.descriptor
  mixer/tools/codegen/pkg/bootstrapgen/testdata/report2/template.descriptor
  mixer/tools/codegen/pkg/interfacegen/testdata/apa/template.descriptor
  mixer/tools/codegen/pkg/interfacegen/testdata/check/template.descriptor
  mixer/tools/codegen/pkg/interfacegen/testdata/quota/template.descriptor
  mixer/tools/codegen/pkg/interfacegen/testdata/report/template.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/SimpleApaTemplate.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/SimpleTemplate.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedFieldTypeEnum.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedFieldTypeMessage.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedFieldTypePrimitive.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedMapKey.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedMapVal.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedTypeInAPAOutTemplate.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/UnsupportedValueTypeInAPA.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/multiFile.descriptor
  mixer/tools/codegen/pkg/modelgen/testdata/twoTemplatesError.descriptor
  vendor/istio.io/api/mixer/v1/global_dictionary.yaml
Labels: approved, cla: yes, lgtm

#5496 Use access log configuration in template and
  mixer/test/client/env/envoy_conf.go
  mixer/test/client/env/setup.go
  tests/testdata/bootstrap_tmpl.json
Labels: cla: human-approved, cla: yes

#5688 Fix missing kubeconfig issue in daily release
  tests/e2e/tests/controller/controller_test.go
Labels: approved, cla: yes, lgtm

#5697 R0.8
  mixer/test/client/disable_tcp_check_calls/disable_tcp_check_calls_test.go
  mixer/test/client/tcp_filter/tcp_filter_test.go
  mixer/test/client/tcp_filter_periodical_report/tcp_filter_periodical_report_test.go
  mixer/test/client/tcp_filter_v1_config/tcp_filter_v1_config_test.go
Labels: approved, cla: yes

#5658 Release-0.8: Update proxy sha
  istio.deps
Labels: approved, cla: yes

#5693 Close span when dispatch completes
  mixer/pkg/runtime/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm

#5695 Do not bypass MixerReportingToMixer e2e in V2
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#5663 Autoscaling doc update to match changes in istio-proxy container template
  samples/helloworld/README.md
Labels: cla: yes

#5708 Make istioctl get/delete case insensitive
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#5698 fix version for debian in dailies
  tools/deb/istio.mk
Labels: approved, cla: yes, lgtm

#5718 Temporarily disable mixer filter in gateway
  pilot/pkg/networking/plugin/mixer/mixer.go
  tests/e2e/tests/pilot/ingressgateway_test.go
Labels: approved, cla: yes, lgtm

#5545 ServiceEntry supports unix domain sockets
  pilot/pkg/model/service.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
Labels: cla: yes

#5670 Include helm chart option for installing jaeger specific services
  install/kubernetes/helm/istio/charts/tracing/.helmignore
  install/kubernetes/helm/istio/charts/tracing/Chart.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/NOTES.txt
  install/kubernetes/helm/istio/charts/tracing/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/ingress.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/service-jaeger.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/service.yaml
  install/kubernetes/helm/istio/charts/zipkin/templates/service.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#5707 Fix istioctl output format issue.
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#5675 Support Citatel helm toggle
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#5716 [test-framework] Switch from testing.T => testing.TB and uniformize *OrFail.
  pkg/test/cluster/app.go
  pkg/test/cluster/environment.go
  pkg/test/environment/environment.go
  pkg/test/local/environment.go
  pkg/test/operations.go
  tests/e2e/tests/showcase/mixer_showcase_test.go
  tests/e2e/tests/showcase/pilot_showcase_test.go
  tests/e2e/tests/showcase/showcase_test.go
  tests/e2e/tests/showcase/simple_showcase_test.go
Labels: cla: yes

#5738 Add request.raw_claims
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/testdata/config/attributes.yaml
Labels: approved, cla: yes

#5684 Revert "ALPN upgrade to http/2.0 (#5618)"
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#5717 Add prefixed based routing to Cloud Foundry
  Gopkg.lock
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/monitor/copilot_snapshot.go
  pilot/pkg/config/monitor/copilot_snapshot_test.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/serviceregistry/cloudfoundry/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery_test.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/cloudfoundry/mock/copilot.go
  vendor/code.cloudfoundry.org/copilot/api/cloud_controller.pb.go
  vendor/code.cloudfoundry.org/copilot/api/common.pb.go
  vendor/code.cloudfoundry.org/copilot/api/istio.pb.go
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
  vendor/github.com/golang/protobuf/proto/clone.go
  vendor/github.com/golang/protobuf/proto/decode.go
  vendor/github.com/golang/protobuf/proto/discard.go
  vendor/github.com/golang/protobuf/proto/encode.go
  vendor/github.com/golang/protobuf/proto/equal.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/message_set.go
  vendor/github.com/golang/protobuf/proto/pointer_reflect.go
  vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_merge.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/proto/text.go
  vendor/github.com/golang/protobuf/proto/text_parser.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/github.com/golang/protobuf/protoc-gen-go/plugin/plugin.pb.go
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
  vendor/github.com/golang/protobuf/ptypes/struct/struct.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
  vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
Labels: cla: no

#5690 Fix xDS failures calculation in pilot dashboard
  addons/grafana/dashboards/pilot-dashboard.json
Labels: approved, cla: yes

#5493 Remove unnecessary webhook script
  install/kubernetes/webhook-create-signed-cert.sh
Labels: approved, cla: yes, lgtm

#5722 Make injector-config-map top level - always installed
  install/kubernetes/helm/istio/Chart.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/service.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values-envoyv2-transition.yaml
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes

#5750 Added missing CRDs so that they can be managed by Helm
  install/kubernetes/helm/istio/charts/pilot/templates/crds.yaml
Labels: cla: yes

#5748 Fix tracing addon missing issue in release package.
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
Labels: cla: yes, lgtm

#5743 Enhance debug logging for Mixer grpc methods
  mixer/pkg/api/grpcServer.go
Labels: approved, cla: yes, lgtm

#5719 Dump CRDs explicitly
  bin/dump_kubernetes.sh
Labels: cla: yes

#5665 Call `set_download_command` unconditionally
  bin/init.sh
Labels: cla: yes

#5742 [test-framework] Further rationalize driver model.
  pkg/test/cluster/environment.go
  pkg/test/flags.go
  pkg/test/impl/driver/args.go
  pkg/test/impl/driver/instance.go
  pkg/test/impl/driver/interface.go
  pkg/test/impl/driver/tmp.go
  pkg/test/impl/logging/init.go
  pkg/test/impl/tmp/tmp.go
  pkg/test/internal/context.go
  pkg/test/local/environment.go
  pkg/test/operations.go
Labels: cla: yes

#5715 SNI header based forwarding for HTTPS ports
  pilot/pkg/model/service.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/eureka/conversion.go
  pilot/pkg/serviceregistry/eureka/conversion_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  tests/e2e/tests/pilot/egressgateway_test.go
  tests/e2e/tests/pilot/externalservice_test.go
  tests/e2e/tests/pilot/testdata/v1alpha3/egressgateway.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-route-via-egressgateway.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/service-entry.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/serviceentry-nghttp2.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/serviceentry-tcp-wikipedia-cidr.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/serviceentry-tcp-wikipedia-sni.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/serviceentry-wildcard-httpbin.yaml
Labels: approved, cla: human-approved, cla: no

#5754 Remove redundant default values descriptions
  istioctl/cmd/istioctl/inject.go
Labels: cla: yes

#5762 Fix proxy-config bug with multiple Pilots
  istioctl/cmd/istioctl/config.go
  pilot/cmd/pilot-discovery/debug.go
  pilot/cmd/pilot-discovery/debug_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: cla: yes

#5756 Adds new postsubmits for k8s 1.10
  prow/e2e-suite-rbac-auth-k8s-1.10.sh
  prow/istio-pilot-e2e-envoyv2-v1alpha3-k8s-1.10.sh
Labels: approved, cla: yes, lgtm

#5552 Upload circle presubmits to different GCS path so testgrid shows results in multiple panels
  bin/ci2gubernator.sh
Labels: approved, cla: yes, lgtm
