Repository istio/istio, pull requests merged in 2018-02, with the labels that each got.

#3275 Helm: Move ingress to a subchart
  install/kubernetes/helm/istio/charts/ingress/Chart.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/ingress/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/service.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/templates/helm/istio/values.yaml.tmpl
Labels: approved, cla: yes, lgtm

#3244 Add healthchecks to sidecar injector webhook
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/deployment.yaml
  install/kubernetes/templates/istio-sidecar-injector.yaml.tmpl
  pilot/cmd/sidecar-injector/main.go
  pilot/pkg/kube/inject/webhook.go
  pilot/test/integration/testdata/sidecar-injector.yaml.tmpl
Labels: cla: yes

#3353 Fix broken decorator verification in Pilot e2e
  pilot/test/integration/routing.go
Labels: approved, area/test and release, cla: yes, kind/bug, lgtm

#2846 Pilot data structure refactor for adopting Envoy v2 APIs
  pilot/pkg/proxy/envoy/v2/mesh.go
  pilot/pkg/proxy/envoy/v2/mesh_benchmark_test.go
  pilot/pkg/proxy/envoy/v2/mesh_test.go
Labels: approved, area/networking, cla: yes, lgtm

#3167 update makefile format doc
  DEV-GUIDE.md
Labels: approved, cla: yes, lgtm

#3276 Implement the core/glue part of runtime2.
  mixer/pkg/runtime2/listener.go
  mixer/pkg/runtime2/listener_test.go
  mixer/pkg/runtime2/runtime.go
  mixer/pkg/runtime2/runtime_test.go
  mixer/pkg/runtime2/testing/data/templates.go
Labels: approved, area/policies and telemetry, cla: yes, lgtm

#3360 Fix webhook tests for Pilot
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes, kind/test-failure, lgtm

#3358 Update reference docs.
  mixer/adapter/redisquota/config/adapter.redisquota.config.pb.html
  mixer/adapter/redisquota/config/config.pb.go
  mixer/adapter/redisquota/config/config.proto
  mixer/test/spyAdapter/template/check/SampleCheck.pb.html
  mixer/test/spyAdapter/template/template.gen.go
Labels: approved, cla: yes

#3240 Enable policy checks and telemetry on Egress
  bin/istio-proxy-cfg.py
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/egress_rules.go
  pilot/pkg/model/egress_rules_test.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/externalservice.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/testdata/lds-httpproxy.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-mixer-check-report-config.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-mixerclient-filter.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-tcp.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-multi-match-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optin.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted-external-service.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-tcp.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-multi-match-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-weighted-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-weighted.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-websocket.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-httpproxy.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-redirect-egress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-timeout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-http-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-http-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-http-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-weighted-external-service.json.golden
Labels: cla: yes, lgtm

#3366 Update proxy SHA to latest
  Gopkg.toml
  istio.VERSION
  istio.deps
  mixer/test/client/auth/auth_test.go
  mixer/test/client/check_report/check_report_test.go
  mixer/test/client/failed_request/failed_request_test.go
  mixer/test/client/report_batch/report_batch_test.go
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, lgtm

#3318 Add new Servicegraph visualization.
  Makefile
  addons/servicegraph/README.md
  addons/servicegraph/cmd/server/main.go
  addons/servicegraph/d3graph.go
  addons/servicegraph/docker/Dockerfile
  addons/servicegraph/docker/Dockerfile.debug
  addons/servicegraph/docker/gcloud_build.sh
  addons/servicegraph/force/forcegraph.css
  addons/servicegraph/force/forcegraph.html
  addons/servicegraph/force/forcegraph.js
  addons/servicegraph/js/cola/LICENSE
  addons/servicegraph/js/cola/cola.min.js
  addons/servicegraph/js/d3/LICENSE
  addons/servicegraph/js/d3/d3.v4.min.js
  addons/servicegraph/js/handlebars/handlebars.min.js
  addons/servicegraph/promgen/promgen.go
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3316 mixer lint / fmt fixes
  mixer/adapter/rbac/controller.go
  mixer/pkg/runtime2/dispatcher/session.go
  mixer/pkg/runtime2/testing/data/adapters.go
  mixer/template/sample/createinstance_test.go
  mixer/template/sample/template.gen_test.go
  mixer/test/client/env/attributes.go
Labels: approved, cla: yes, lgtm

#3374 Regenerate ref doc with latest generation tool.
  Gopkg.lock
  mixer/adapter/kubernetesenv/template/adapter.template.kubernetes.pb.html
  mixer/adapter/memquota/config/adapter.memquota.config.pb.html
  mixer/adapter/redisquota/config/adapter.redisquota.config.pb.html
  mixer/adapter/solarwinds/config/adapter.solarwinds.config.pb.html
  mixer/adapter/stackdriver/config/adapter.stackdriver.config.pb.html
  mixer/adapter/statsd/config/adapter.statsd.config.pb.html
  mixer/adapter/stdio/config/adapter.stdio.config.pb.html
  mixer/template/authorization/authorization.pb.html
  mixer/template/logentry/logEntry.pb.html
  mixer/template/metric/metric.pb.html
  mixer/template/quota/quota.pb.html
  mixer/template/sample/apa/istio.mixer.adapter.sample.myApa.pb.html
  mixer/template/sample/check/istio.mixer.adapter.sample.check.pb.html
  mixer/template/sample/quota/istio.mixer.adapter.sample.quota.pb.html
  mixer/template/sample/report/istio.mixer.adapter.sample.report.pb.html
  mixer/template/tracespan/traceSpan.pb.html
  mixer/test/spyAdapter/template/apa/SampleApa.pb.html
  mixer/test/spyAdapter/template/report/SampleReport.pb.html
Labels: approved, cla: yes, lgtm

#3280 perf setup scripts: add link to dailies and update for post 0.5.0
  tools/README.md
Labels: approved, cla: yes, lgtm

#3376 Fix docker tar generation for release builds
  release/cloud_builder.sh
  release/publish_release.sh
  release/store_artifacts.sh
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#3388 Add missing docs to the list and memquota adapters.
  mixer/adapter/list/config/adapter.list.config.pb.html
  mixer/adapter/list/config/config.pb.go
  mixer/adapter/list/config/config.proto
  mixer/adapter/memquota/config/adapter.memquota.config.pb.html
  mixer/adapter/memquota/config/config.pb.go
  mixer/adapter/memquota/config/config.proto
Labels: cla: yes

#3390 [DO NOT MERGE] Auto PR to update dependencies of istio
  Gopkg.toml
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3349 Various fixes for Istio Helm chart (makes it work 🎉)
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/crds.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/service.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/service.yaml
  install/kubernetes/helm/istio/charts/security/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/security/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/zipkin/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/templates/helm/istio/values.yaml.tmpl
Labels: cla: yes

#3379 Always copy envoy binary to avoid a stale dependency.
  bin/init.sh
Labels: approved, cla: yes, lgtm

#3393 Fixes RBAC issue with prometheus
  install/kubernetes/templates/addons/prometheus.yaml.tmpl
Labels: cla: yes, needs-ok-to-test

#3341 improve naming of some variables in pilot envoy config (v1)
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/discovery.go
  pilot/pkg/proxy/envoy/v1/externalservice.go
  pilot/pkg/proxy/envoy/v1/ingress.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/policy.go
  pilot/pkg/proxy/envoy/v1/route.go
Labels: cla: yes, lgtm

#3396 Fix logging bug and turn off zone aware routing for pilot/mixer
  pilot/pkg/model/context.go
  pilot/pkg/proxy/envoy/v1/watcher.go
  pilot/pkg/proxy/envoy/v1/watcher_test.go
Labels: cla: yes

#3356 Add cluster that is generated by the v1alpha2 route rule mirror
  pilot/pkg/proxy/envoy/v1/route.go
  pilot/test/integration/testdata/rule-default-route-mirrored.yaml.tmpl
Labels: area/networking, cla: yes

#3273 Wire runtime2 to the command-line flags in Mixer and add perf tests
  mixer/pkg/perf/config.go
  mixer/pkg/perf/server.go
  mixer/pkg/server/args.go
  mixer/pkg/server/server.go
  mixer/pkg/server/server_test.go
  mixer/test/e2e/e2e_apa_test.go
  mixer/test/perf/multimetric_test.go
  mixer/test/perf/norule_test.go
  mixer/test/perf/singlecheck_test.go
  mixer/test/perf/singlemetric_test.go
  mixer/test/perf/singlereport_test.go
Labels: approved, area/perf and scalability, area/policies and telemetry, cla: yes, lgtm

#3169 Add the liveness checker to the CA instance
  security/cmd/istio_ca/main.go
  security/pkg/cmd/probe.go
  security/pkg/pki/ca/ca.go
  security/pkg/probe/controller.go
  security/pkg/probe/controller_test.go
  security/pkg/probe/testdata/ca.crt
  security/pkg/probe/testdata/ca.key
  security/pkg/probe/testdata/root.crt
Labels: approved, cla: yes

#3406 Fault injection should use abort instead of timeout (#1279)
  samples/bookinfo/consul/route-rule-ratings-test-abort.yaml
  samples/bookinfo/eureka/route-rule-ratings-test-abort.yaml
  samples/bookinfo/kube/route-rule-ratings-test-abort.yaml
Labels: cla: yes

#3375 Add mixer client tests for per route config
  mixer/test/client/auth/auth_test.go
  mixer/test/client/check_report_disable/check_report_disable_test.go
  mixer/test/client/env/envoy_conf.go
  mixer/test/client/env/v2_config.go
  mixer/test/client/fault_inject/fault_inject_test.go
  mixer/test/client/quota/quota_test.go
  mixer/test/client/quota_cache/quota_cache_test.go
  mixer/test/client/stress/stress_test.go
Labels: approved, cla: yes, lgtm

#3397 update perf script to call `make pull` to deal with vendor
  tools/setup_perf_cluster.sh
Labels: cla: yes, lgtm

#3285 Removes setup_vm_firewall from run_tests in perf script
  tools/setup_perf_cluster.sh
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3408 Update readme for demo
  security/cmd/node_agent_k8s/README.md
Labels: approved, cla: yes

#3369 Istio OSS Release Process Doc
  release/README.md
Labels: area/test and release, automated-release, cla: yes, retest-not-required-docs-only

#3442 Fix mirror routing test
  pilot/test/integration/routing.go
Labels: area/test and release, cla: yes

#3417 Remove legacy config tests for mixer client
  mixer/test/client/auth/auth_test.go
  mixer/test/client/check_cache/check_cache_test.go
  mixer/test/client/check_report/check_report_test.go
  mixer/test/client/check_report_disable/check_report_disable_test.go
  mixer/test/client/disable_check_cache/disable_check_cache_test.go
  mixer/test/client/disable_tcp_check_calls/disable_tcp_check_calls_test.go
  mixer/test/client/env/envoy.go
  mixer/test/client/env/envoy_conf.go
  mixer/test/client/env/setup.go
  mixer/test/client/failed_request/failed_request_test.go
  mixer/test/client/fault_inject/fault_inject_test.go
  mixer/test/client/mixer_internal_fail/mixer_internal_fail_test.go
  mixer/test/client/network_policy/network_policy_test.go
  mixer/test/client/quota/quota_test.go
  mixer/test/client/quota_cache/quota_cache_test.go
  mixer/test/client/report_batch/report_batch_test.go
  mixer/test/client/stress/stress_test.go
  mixer/test/client/tcp_filter/tcp_filter_test.go
Labels: approved, cla: yes

#3422 Add v1alpha2 integration tests
  pilot/test/integration/driver.go
  pilot/test/integration/egress_rules.go
  pilot/test/integration/infra.go
  pilot/test/integration/ingress.go
  pilot/test/integration/kubernetes_external_name_services.go
  pilot/test/integration/routing.go
  pilot/test/integration/routingToEgress.go
  pilot/test/integration/testdata/v1alpha1/egress-rule-google.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/egress-rule-httpbin.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/egress-rule-nghttp2.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/egress-rule-tcp-wikipedia-cidr.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/egress-rule-wildcard-httpbin.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-content-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-default-route-append-headers.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-default-route-cors-policy.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-default-route-mirrored.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-default-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-fault-injection-to-egress.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-fault-injection.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-redirect-injection.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-redirect-to-egress.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-regex-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-rewrite-authority-externalbin.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-rewrite-to-egress.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-route-append-headers-httpbin.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-websocket-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha1/rule-weighted-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/destination-rule-c.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-content-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-default-route-append-headers.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-default-route-cors-policy.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-default-route-mirrored.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-default-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-fault-injection.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-redirect-injection.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-regex-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-websocket-route.yaml.tmpl
  pilot/test/integration/testdata/v1alpha2/rule-weighted-route.yaml.tmpl
Labels: cla: yes

#3416 Add missing copy code for copying quota args from session to state.
  mixer/pkg/runtime2/dispatcher/dispatcher.go
  mixer/pkg/runtime2/dispatcher/dispatcher_test.go
  mixer/pkg/runtime2/dispatcher/session.go
  mixer/pkg/runtime2/dispatcher/session_test.go
  mixer/pkg/runtime2/testing/data/templates.go
Labels: approved, cla: yes, lgtm

#3427 Improve Istio CA main function.
  security/cmd/istio_ca/main.go
Labels: approved, cla: yes

#3412 Gateway RDS response is sorted
  pilot/pkg/proxy/envoy/v1/gateway.go
  pilot/pkg/proxy/envoy/v1/testdata/rds-router-gateway-weighted-server1.json.golden
Labels: approved, area/networking, cla: yes

#3449 Add v1alpha1 routing tests to periodic pilot e2e
  .circleci/config.yml
Labels: area/test and release, cla: yes

#3411 Update the driver path
  security/cmd/node_agent_k8s/flexvolume/driver/driver.go
  security/cmd/node_agent_k8s/flexvolume/driver/driver_test.go
  security/cmd/node_agent_k8s/flexvolume/main.go
Labels: cla: human-approved, cla: yes

#3339 Enable basic security/mTLS for consul
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/consul/conversion_test.go
Labels: cla: yes

#3286 Mixer Runtime2 liveness
  mixer/pkg/runtime2/runtime.go
  mixer/pkg/server/server.go
Labels: approved, area/policies and telemetry, cla: yes, lgtm

#3432 cloudfoundry: No-op GetSidecarServiceInstances
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery_test.go
Labels: approved, cla: yes, lgtm

#3452 Fixed the probe check for self signed ca
  security/cmd/istio_ca/main.go
  security/pkg/probe/controller.go
  security/pkg/probe/controller_test.go
Labels: approved, area/security, cla: yes, lgtm

#3007 istioctl: use configmap for inject configuration, if present
  pilot/cmd/istioctl/inject.go
Labels: area/networking, cla: yes

#3434 Refactor Istio CA creation.
  security/cmd/istio_ca/main.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/testdata/ca-cert.cfg
  security/pkg/pki/ca/testdata/ca-cert.pem
  security/pkg/pki/ca/testdata/ca-key.pem
  security/pkg/pki/ca/testdata/cert-chain.pem
  security/pkg/pki/ca/testdata/certs.sh
  security/pkg/pki/ca/testdata/root-cert.pem
  security/pkg/pki/ca/testdata/root-key.pem
Labels: approved, cla: yes, lgtm

#3446 Add test to verify TCP filter periodical report.
  mixer/test/client/env/http_server.go
  mixer/test/client/env/ports.go
  mixer/test/client/env/v2_config.go
  mixer/test/client/tcp_filter_periodical_report/tcp_filter_periodical_report_test.go
Labels: approved, cla: yes, lgtm

#3438 Fix the node_agent Makefile target
  Makefile
Labels: cla: yes, needs-ok-to-test

#3439 Makefile: Suppress 'which' error messages
  Makefile
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3227 fix the mixer config used by pilot e2e
  tests/e2e/tests/pilot/testdata/mixer.yaml.tmpl
Labels: approved, cla: yes

#3454 Add command-line flags for controlling the use of the new runtime.
  mixer/cmd/mixs/cmd/server.go
Labels: approved, cla: yes, kind/important for release notes, lgtm

#3460 Use correct hub variable when building test install tars
  release/cloud_builder.sh
Labels: approved, cla: yes, lgtm

#3461 [DO NOT MERGE] Auto PR to update dependencies of istio
  Gopkg.toml
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3463 Few fixes for build/CI
  .circleci/config.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  bin/init.sh
Labels: approved, cla: yes, lgtm

#3402 Avoid that people end up using month' old stale tags from istio.VERSION
  istio.VERSION
Labels: approved, area/test and release, automated-release, cla: yes, lgtm

#3472 lint / format fixes
  mixer/pkg/runtime2/runtime.go
  mixer/pkg/server/args.go
  mixer/test/client/check_report_disable/check_report_disable_test.go
  pilot/pkg/kube/inject/webhook_test.go
  pilot/pkg/model/gateway.go
  pilot/pkg/proxy/envoy/v1/gateway.go
  pilot/pkg/proxy/envoy/v2/mesh.go
  pilot/pkg/proxy/envoy/v2/mesh_test.go
  security/cmd/istio_ca/main.go
  security/cmd/node_agent_k8s/workload/main.go
  security/pkg/probe/controller.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/routing_to_egress_test.go
  tests/e2e/tests/pilot/util/infra.go
  tests/e2e/tests/pilot/util/util.go
Labels: approved, cla: yes, lgtm

#3470 Disable authz check
  security/pkg/server/grpc/server.go
  security/pkg/server/grpc/server_test.go
Labels: approved, cla: yes, lgtm

#3431 update script to only publish istio-sidecar.deb
  release/create_github_release.sh
Labels: approved, cla: yes, lgtm

#3451 Go build: In verbose mode, also output commands in gobuild.sh
  Makefile
  bin/gobuild.sh
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3464 Pilot renames
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/discovery.go
  pilot/pkg/proxy/envoy/v1/discovery_test.go
  pilot/pkg/proxy/envoy/v1/externalservice.go
  pilot/pkg/proxy/envoy/v1/gateway.go
  pilot/pkg/proxy/envoy/v1/ingress.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/mock/discovery.go
  pilot/pkg/proxy/envoy/v1/policy.go
  pilot/pkg/proxy/envoy/v1/route.go
  pilot/pkg/proxy/envoy/v1/watcher.go
  pilot/pkg/proxy/envoy/v1/watcher_test.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery.go
  pilot/pkg/serviceregistry/cloudfoundry/servicediscovery_test.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/eureka/servicediscovery.go
  pilot/pkg/serviceregistry/eureka/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
Labels: area/networking, cla: yes, lgtm

#3450 Update Cobra.go to print version on stdout
  pkg/version/cobra.go
Labels: approved, cla: yes, needs-ok-to-test

#3473 Helm was breaking badly with a recent rename of service accounts
  install/kubernetes/helm/istio/charts/ingress/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio/charts/security/templates/clusterrolebinding.yaml
Labels: cla: yes

#3462 Add support for 0.5.1 to Istio on GKE template and default to the latest supported version.
  install/gcp/deployment_manager/istio-cluster.jinja
  install/gcp/deployment_manager/istio-cluster.jinja.schema
  install/gcp/deployment_manager/istio-cluster.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3478 Create prometheus service account in istio ns
  install/kubernetes/templates/addons/prometheus.yaml.tmpl
Labels: cla: yes

#3481 Remove files that remain after updateVersions.sh
  install/kubernetes/addons/servicegraph.yaml
  install/kubernetes/addons/zipkin-to-stackdriver.yaml
  install/kubernetes/addons/zipkin.yaml
Labels: approved, cla: yes, lgtm

#3475 Add build/push docker info
  DEV-GUIDE.md
Labels: approved, cla: yes, lgtm

#3391 Add Stringfy utility & StringEquals utility functions to pkg/adapter.
  mixer/adapter/memquota/memquota.go
  mixer/adapter/prometheus/prometheus.go
  mixer/adapter/redisquota/redisquota.go
  mixer/adapter/solarwinds/metrics_handler.go
  mixer/adapter/stackdriver/helper/common.go
  mixer/pkg/adapter/instanceUtil.go
  mixer/pkg/adapter/instanceUtil_test.go
Labels: approved, cla: yes

#3484 simplify prow test scripts, export KUBECONFIG
  prow/e2e-suite.sh
  prow/istio-pilot-e2e.sh
  prow/istio-postsubmit.sh
  prow/lib.sh
Labels: approved, cla: yes, lgtm

#3488 [DO NOT MERGE] Auto PR to update dependencies of istio
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3489 Fix broken link to image in README.md
  mixer/adapter/opa/README.md
Labels: cla: yes, needs-ok-to-test

#3389 Delete some old scripts and increase consistency for make
  Makefile
  addons/grafana/Dockerfile.grafana
  addons/servicegraph/docker/Dockerfile.servicegraph
  addons/servicegraph/docker/Dockerfile.servicegraph_debug
  bin/check_workspace.sh
  broker/bin/publish-docker-images.sh
  mixer/docker/Dockerfile.mixer
  mixer/docker/Dockerfile.mixer_debug
  mixer/docker/gcloud_build.sh
  pilot/docker/Dockerfile.app
  security/bin/gen-keys.sh
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#3493 Fixes cache buster doc bug
  tools/cache_buster.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3077 Reuse kubernetesenv client controllers per distinct kubeconfig
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
Labels: approved, cla: yes, lgtm

#3224 Fill project id in stackdriver adapter config if it is empty
  mixer/adapter/stackdriver/helper/common.go
  mixer/adapter/stackdriver/helper/common_test.go
  mixer/adapter/stackdriver/stackdriver.go
  mixer/adapter/stackdriver/stackdriver_test.go
  mixer/testdata/config/stackdriver.yaml
Labels: approved, cla: yes, lgtm

#3502 Workaround to fix prow.
  tests/e2e/tests/pilot/pilot_test.go
Labels: approved, cla: yes, lgtm

#3477 Experiment for improving pilot handling of large services
  pilot/pkg/proxy/envoy/v1/discovery.go
  pilot/pkg/serviceregistry/kube/queue.go
Labels: approved, cla: yes, lgtm

#3500 Add Mixerclient stats test
  istio.VERSION
  istio.deps
  mixer/test/client/check_cache/check_cache_test.go
  mixer/test/client/check_report/check_report_test.go
  mixer/test/client/check_report_disable/check_report_disable_test.go
  mixer/test/client/disable_check_cache/disable_check_cache_test.go
  mixer/test/client/disable_tcp_check_calls/disable_tcp_check_calls_test.go
  mixer/test/client/env/setup.go
  mixer/test/client/env/v2_config.go
  mixer/test/client/quota/quota_test.go
  mixer/test/client/quota_cache/quota_cache_test.go
  mixer/test/client/report_batch/report_batch_test.go
  mixer/test/client/stress/stress_test.go
  mixer/test/client/tcp_filter/tcp_filter_test.go
  mixer/test/client/tcp_filter_periodical_report/tcp_filter_periodical_report_test.go
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: cla: yes, lgtm

#3497 x509 error with certificate-authority-data: pin mergo dependency against kubernetes/client-go compatible version
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3466 Add ON-CALL playbook
  ON-CALL.md
Labels: approved, cla: yes, lgtm

#3503 Update dev guide file
  DEV-GUIDE.md
Labels: approved, cla: yes

#3370 [Istio/Security]: Flex volume driver
  Makefile
  security/cmd/flexvolume/driver/driver.go
  security/cmd/flexvolume/driver/driver_test.go
  security/cmd/flexvolume/main.go
Labels: cla: yes

#3512 [DO NOT MERGE] Auto PR to update dependencies of istio
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3492 Update .gitignore and make clean. Fix namespace in install template.
  .gitignore
  Makefile
  install/kubernetes/templates/addons/prometheus.yaml.tmpl
Labels: approved, cla: yes, lgtm

#3520 Move key/cert under security dir
  security/samples/plugin_ca_certs/ca-cert.pem
  security/samples/plugin_ca_certs/ca-key.pem
  security/samples/plugin_ca_certs/cert-chain.pem
  security/samples/plugin_ca_certs/root-cert.pem
Labels: cla: yes

#3521 Update cluster_lib.sh
  prow/cluster_lib.sh
Labels: approved, cla: yes, lgtm

#3525 Revise reeadme file
  security/cmd/node_agent_k8s/README.md
Labels: cla: yes

#3526 Add CA option to use upstream CA for provisioning cert.
  security/cmd/istio_ca/main.go
  security/pkg/pki/ca/ca.go
Labels: approved, cla: yes, lgtm

#3517 Correctly supporting auth modes in pilot e2e tests
  tests/e2e/tests/pilot/pilot_test.go
Labels: approved, cla: yes, lgtm

#3530 Only use output struct values when actually generated
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  install/kubernetes/templates/istio-mixer.yaml.tmpl
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
  mixer/adapter/kubernetesenv/template/template_handler.gen.go
  mixer/pkg/il/runtime/externs.go
  mixer/pkg/il/runtime/externs_test.go
  mixer/template/template.gen.go
  mixer/testdata/config/kubernetesenv.yaml
  mixer/tools/codegen/pkg/bootstrapgen/template/bootstrapTemplate.go
  mixer/tools/codegen/pkg/bootstrapgen/testdata/template.gen.go.golden
  mixer/tools/codegen/pkg/interfacegen/template/interface.go
  mixer/tools/codegen/pkg/interfacegen/testdata/apa/template_handler.gen.go.golden
  tests/e2e/tests/pilot/testdata/mixer.yaml.tmpl
Labels: approved, cla: yes, lgtm

#3535 Add option to install GCE VM
  install/tools/setupMeshEx.sh
Labels: cla: yes, lgtm

#3252 Make IsNetworkFilterConfig exported
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/resources.go
Labels: approved, cla: yes, lgtm

#3529 Adding simple e2e test to presubmit
  prow/e2e-bookInfoTests.sh
  prow/e2e-simpleTests.sh
Labels: approved, cla: yes, do-not-merge/hold, lgtm

#3546 Switch to istio org vendor
  .gitmodules
Labels: approved, cla: yes, lgtm

#3508 Add the tunning variable for throttle
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/templates/istio-pilot.yaml.tmpl
  pilot/pkg/serviceregistry/kube/queue.go
Labels: approved, cla: yes, lgtm

#3543 [DO NOT MERGE] Auto PR to update dependencies of istio
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3415 Remove obsolete mixer deployment files.
  addons/servicegraph/deploy/kube/servicegraph.yaml
  mixer/deploy/kube/README.md
  mixer/deploy/kube/conf/prometheus.yaml
  mixer/deploy/kube/grafana.yaml
  mixer/deploy/kube/localregistry.yaml
  mixer/deploy/kube/mixer.yaml
  mixer/deploy/kube/prometheus.yaml
Labels: approved, cla: yes, lgtm

#3524 Fix Grafana graphs by filtering the unknown service.
  addons/grafana/grafana-dashboard.json
Labels: approved, cla: yes, lgtm

#3468 add a method to stop the mixer Store explicitly
  mixer/adapter/rbac/rbac.go
  mixer/pkg/config/crd/init.go
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
  mixer/pkg/config/store/fsstore.go
  mixer/pkg/config/store/fsstore_test.go
  mixer/pkg/config/store/queue.go
  mixer/pkg/config/store/queue_test.go
  mixer/pkg/config/store/store.go
  mixer/pkg/config/store/store_test.go
  mixer/pkg/config/storetest/storetest.go
  mixer/pkg/config/storetest/storetest_test.go
  mixer/pkg/runtime/init.go
  mixer/pkg/runtime2/listener.go
  mixer/pkg/runtime2/listener_test.go
  mixer/pkg/runtime2/runtime.go
  mixer/pkg/runtime2/testing/util/snapshot.go
Labels: approved, cla: yes, lgtm

#3544 Need to use 1.9 which is the first index
  prow/cluster_lib.sh
Labels: cla: yes, lgtm

#3506 Squash clear cache calls
  pilot/pkg/proxy/envoy/v1/discovery.go
  pilot/pkg/proxy/envoy/v1/discovery_test.go
Labels: cla: yes

#3332 Upgrade istio-builder image to 0.4.6
  release/cloud_build.template.json
  release/cloud_builder.sh
Labels: approved, cla: yes, lgtm

#2444 Activate VM expansion test
  Makefile
  prow/e2e-suite-rbac-auth.sh
  tests/e2e/framework/rawVM.go
  tests/istio.mk
  tools/istio-docker.mk
Labels: approved, area/environments, automated-release, cla: human-approved, cla: yes, lgtm

#3536 IP Whitelist in Helm
  install/kubernetes/helm/README.md
  install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/templates/helm/istio/values.yaml.tmpl
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3560 cluster pre-provisioning for cluster-wide test
  prow/cluster_lib.sh
  prow/e2e-cluster_wide-auth.sh
  prow/lib.sh
  prow/mason_lib.sh
Labels: approved, cla: yes, lgtm

#3564 fix lint config and other lint errors
  lintconfig_base.json
  security/cmd/flexvolume/driver/driver.go
  security/cmd/flexvolume/driver/driver_test.go
  security/pkg/pki/ca/ca.go
Labels: approved, cla: yes, lgtm

#3558 Adds a diagram for the perf setup script
  tools/README.md
  tools/perf_setup.svg
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3516 Restoring TESTOPTS which was accidentally removed
  prow/istio-pilot-e2e.sh
  tests/e2e/tests/pilot/util/infra.go
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#3573 Fix compiler output when a function call is on the LHS non-logical OR
  mixer/pkg/il/compiler/compiler.go
  mixer/pkg/il/testing/tests.go
Labels: approved, cla: yes, lgtm

#3538 Test server port before sending SendCSR for probe check
  security/pkg/probe/controller.go
  security/pkg/probe/controller_test.go
Labels: approved, area/security, cla: yes, kind/enhancement, lgtm

#3591 Lint fixups in master
  mixer/adapter/dogstatsd/dogstatsd.go
  mixer/adapter/dogstatsd/dogstatsd_test.go
Labels: approved, ci/circleci, cla: yes, kind/test-failure, lgtm

#3592 [DO NOT MERGE] Auto PR to update dependencies of istio
  Gopkg.toml
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3539 Re-enable pprof for mixer with args consistent with Pilot
  mixer/cmd/mixs/cmd/server.go
  mixer/pkg/server/args.go
  mixer/pkg/server/monitoring.go
  mixer/pkg/server/server.go
  mixer/pkg/server/server_test.go
Labels: approved, cla: yes, lgtm

#3528 When installing via GCP/GKE, wait for initializer/injector to deploy before proceeding with bookinfo
  install/gcp/deployment_manager/istio-cluster.jinja
Labels: cla: yes, lgtm, needs-ok-to-test

#3522 Fix the grafana service account, missing namespace.
  install/kubernetes/templates/addons/grafana.yaml.tmpl
Labels: cla: yes, kind/blocking release

#3605 More permissive routing tests
  tests/e2e/tests/pilot/routing_test.go
Labels: approved, area/test and release, cla: yes, lgtm

#3507 use current time for running daily release
  prow/OWNERS
  release/OWNERS
  release/pipline/OWNERS
  release/pipline/dags/istio_common_dag.py
Labels: approved, cla: yes, lgtm

#3610 Fix CA main function format.
  security/cmd/istio_ca/main.go
Labels: approved, cla: yes, lgtm

#3611 Move certtuil file to pkg directory.
  security/cmd/node_agent/na/nafactory.go
  security/cmd/node_agent/na/nodeagent.go
  security/pkg/util/certutil.go
  security/pkg/util/certutil_test.go
  security/pkg/util/testdata/cert-util.pem
Labels: cla: yes

#3608 Change the name of NewIstioCAOptions
  security/cmd/istio_ca/main.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
Labels: cla: yes

#3614 [DO NOT MERGE] Auto PR to update dependencies of istio
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3612 Refine the node agent logic
  security/cmd/node_agent/main.go
  security/cmd/node_agent/na/nafactory.go
  security/cmd/node_agent/na/nafactory_test.go
Labels: approved, cla: yes, lgtm

#3494 Change mock services to use separate port object
  pilot/pkg/model/config_test.go
  pilot/pkg/proxy/envoy/v1/mock/discovery.go
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context-optin.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context-optout.json.golden
  pilot/pkg/serviceregistry/aggregate/controller_test.go
Labels: approved, cla: yes, lgtm

#3618 [DO NOT MERGE] Auto PR to update dependencies of istio
  istio.VERSION
  istio.deps
  pilot/docker/Dockerfile.proxy
  pilot/docker/Dockerfile.proxy_debug
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#3625 more lint fixes
  lintconfig_base.json
  mixer/adapter/redisquota/redisquota_test.go
  mixer/pkg/runtime2/dispatcher/dispatcher_test.go
  mixer/test/e2e/e2e_apa_test.go
  mixer/test/e2e/e2e_reftracking_test.go
  mixer/test/e2e/e2e_report_test.go
  pilot/pkg/config/clusterregistry/conversion_test.go
  pilot/pkg/model/gateway_test.go
  pkg/log/log_test.go
  pkg/tracing/config_test.go
  security/cmd/flexvolume/driver/driver_test.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/upgrade/upgrade_test.go
Labels: approved, cla: yes, lgtm

#3620 Added default probe settings for ca
  .gitignore
  install/kubernetes/templates/istio-ca-with-health-check.yaml.tmpl
  install/kubernetes/templates/istio.yaml.tmpl
  install/updateVersion.sh
Labels: area/security, cla: yes, kind/enhancement, lgtm

#3628 Clean up the platform config
  security/cmd/node_agent/main.go
  security/cmd/node_agent/na/config.go
  security/cmd/node_agent/na/nafactory.go
  security/cmd/node_agent/na/nodeagent_test.go
  security/pkg/platform/aws.go
  security/pkg/platform/aws_test.go
  security/pkg/platform/client.go
  security/pkg/platform/client_test.go
  security/pkg/platform/gcp.go
  security/pkg/platform/gcp_test.go
  security/pkg/platform/onprem.go
  security/pkg/platform/onprem_test.go
  security/pkg/probe/controller.go
Labels: approved, cla: yes, lgtm

#3613 Disable vm test in cluster wide
  prow/e2e-cluster_wide-auth.sh
Labels: approved, cla: yes, lgtm

#3615 Enabling cluster provisioning on no auth test
  prow/e2e-suite-rbac-no_auth.sh
Labels: approved, cla: yes, lgtm

#3559 Update APA field set tracking
  mixer/adapter/kubernetesenv/template/template_handler.gen.go
  mixer/pkg/il/testing/tests.go
  mixer/pkg/il/testing/util.go
  mixer/template/sample/apa/Apa_handler.gen.go
  mixer/template/sample/dispatch_test.go
  mixer/template/sample/template.gen.go
  mixer/template/sample/template.gen_test.go
  mixer/template/template.gen.go
  mixer/test/e2e/e2e_apa_test.go
  mixer/test/spyAdapter/template/apa/tmpl_handler.gen.go
  mixer/test/spyAdapter/template/template.gen.go
  mixer/tools/codegen/pkg/bootstrapgen/template/bootstrapTemplate.go
  mixer/tools/codegen/pkg/bootstrapgen/testdata/template.gen.go.golden
  mixer/tools/codegen/pkg/interfacegen/template/interface.go
  mixer/tools/codegen/pkg/interfacegen/testdata/apa/template_handler.gen.go.golden
Labels: cla: yes

#3630 Fix the isUds logic
  security/cmd/node_agent_k8s/nodeagent/main.go
  security/cmd/node_agent_k8s/nodeagentmgmt/nodeagentclient.go
  security/cmd/node_agent_k8s/nodeagentmgmt/nodeagentclient_test.go
  security/cmd/node_agent_k8s/nodeagentmgmt/nodeagentserver.go
Labels: approved, cla: yes

#3638 Update path for START_ENVOY
  tests/integration/example/integration.sh
Labels: approved, cla: yes, kind/test-failure

#3641 Use istio.deps to locate proxy version.
  tests/integration/example/integration.sh
Labels: approved, area/test and release, automated-release, cla: yes, kind/test-failure, lgtm

#3636 Make sure fortio is really the latest
  tools/README.md
  tools/perf_k8svcs.yaml
Labels: approved, cla: yes, lgtm

#3616 Remove previously deprecated mixerclient.v1 config
  pilot/pkg/model/service.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/externalservice.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/testdata/lds-httpproxy.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-ingress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-mixer-check-report-config.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-mixerclient-filter.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-router-with-gateway.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-tcp.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-multi-match-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optin.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted-external-service.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-tcp.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-multi-match-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-weighted-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-weighted.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-websocket.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-httpproxy.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-redirect-egress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-router-gateway-weighted-server1.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-timeout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-http-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-http-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-http-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/rds-v0-weighted-external-service.json.golden
Labels: approved, cla: yes, lgtm

#3599 CI/build adjustments
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
  .gitignore
  Makefile
  bin/init.sh
  pilot/test/util/kubernetes.go
  tests/e2e/tests/pilot/util/infra.go
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#3642 Remove unguarded log.Info from request path
  mixer/pkg/template/template.go
Labels: approved, area/perf and scalability, cla: yes, lgtm

#3540 Update Grafana to 5.0 beta.
  addons/grafana/Dockerfile.grafana
  addons/grafana/README.md
  addons/grafana/dashboards.yaml
  addons/grafana/dashboards/istio-dashboard.json
  addons/grafana/dashboards/mixer-dashboard.json
  addons/grafana/dashboards/pilot-dashboard.json
  addons/grafana/datasources.yaml
  addons/grafana/default-docker-commandline
  addons/grafana/fix_datasources.sh
  addons/grafana/grafana-dashboard.json
  addons/grafana/grafana.ini
  addons/grafana/import_dashboard.sh
  addons/grafana/mixer-dashboard.json
  addons/grafana/pilot-dashboard.json
  addons/grafana/start.sh
  install/kubernetes/templates/addons/grafana.yaml.tmpl
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#3654 Support unix:// paths for pilot xDS webhook
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/proxy/envoy/v1/discovery.go
  pkg/util/webhookclient.go
Labels: approved, cla: yes, lgtm

#3640 Update istio release alert email destination
  release/pipline/configs/environment_config.py
Labels: approved, cla: yes, lgtm

#3629 Show pkg name and url when installing istio on VM
  install/tools/setupIstioVM.sh
Labels: cla: yes

#3653 Bump up timeout for pilot e2e tests
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#3656 remove a flaky / incorrect test
  mixer/pkg/config/store/queue_test.go
Labels: approved, cla: yes, lgtm

#3666 update to istio-builder 5.0, no testonly tars
  release/cloud_build.template.json
  release/cloud_builder.sh
  release/cloud_publish.template.json
  release/cloud_tag.template.json
  release/create_github_release.sh
  release/publish_release.sh
Labels: cla: yes

#3663 Bump up cluster nodes for pilot e2e tests on prow
  prow/cluster_lib.sh
  prow/istio-pilot-e2e.sh
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#3448 [WIP] Mixer: Make runtime2 default
  mixer/cmd/mixs/cmd/server.go
  mixer/pkg/server/args.go
Labels: approved, area/policies and telemetry, cla: yes, lgtm

#3542 Generate JUnit Results for E2E Tests on Prow
  prow/e2e-suite.sh
  tests/e2e/framework/framework.go
  tests/e2e/framework/testInfo.go
  tests/istio.mk
Labels: cla: yes, do-not-merge/hold

#3670 Fix script to install GCE VM
  install/tools/setupMeshEx.sh
Labels: cla: yes

#3676 use proxy version from Dockerfile, don't prepend GCS_PATH
  release/cloud_builder.sh
  tests/integration/example/integration.sh
Labels: approved, cla: yes, lgtm

#3634 Gateway hosts may contain wildcards
  pilot/pkg/model/gateway_test.go
  pilot/pkg/proxy/envoy/v1/config_test.go
  pilot/pkg/proxy/envoy/v1/discovery_test.go
  pilot/pkg/proxy/envoy/v1/gateway.go
  pilot/pkg/proxy/envoy/v1/gateway_test.go
  pilot/pkg/proxy/envoy/v1/testdata/gateway-route-2.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway-wildcard-route.yaml
  pilot/pkg/proxy/envoy/v1/testdata/gateway-wildcard.yaml
  pilot/pkg/proxy/envoy/v1/testdata/rds-router-gateway-wildcard-server1.json.golden
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
Labels: approved, cla: yes, lgtm

#3671 Always use separate check and report clusters for mixer
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/testdata/cds-circuit-breaker-v1alpha2.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-circuit-breaker.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ingress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-mixerclient-filter.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-redirect-egress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-router.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context-optin.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context-optout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-v0-http-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-v0-http-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-v0-http-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-v0-tcp-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-v0-tcp-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-v0-tcp-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds-v0-weighted-external-service.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/cds.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-httpproxy.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-ingress.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-mixerclient-filter.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-router-with-gateway.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule-tcp.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-egress-rule.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-http-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-multi-match-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optin.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth-optout.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-dns.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-tcp-static.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted-external-service.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v0-weighted.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-tcp-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule-tcp.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-egress-rule.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-multi-match-fault-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-multi-match-fault.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-none-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-none.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-weighted-auth.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-v1-weighted.json.golden
  pilot/pkg/proxy/envoy/v1/testdata/lds-websocket.json.golden
Labels: area/perf and scalability, cla: yes

#3688 Create generic CA client.
  security/pkg/caclient/client.go
  security/pkg/caclient/client_test.go
  security/pkg/util/mock/fakecertutil.go
Labels: cla: yes
