Repository istio/istio, pull requests merged in 2018-07, with the labels that each got.

#6767 Switch from MessageName => TypeURL for type identification in Galley.
  galley/pkg/kube/converter/proto_test.go
  galley/pkg/kube/schema.go
  galley/pkg/kube/source.go
  galley/pkg/kube/source_test.go
  galley/pkg/kube/types.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/runtime/resource/resource.go
  galley/pkg/runtime/resource/resource_test.go
  galley/pkg/runtime/resource/schema.go
  galley/pkg/runtime/resource/schema_test.go
  galley/pkg/runtime/resource/types.go
  galley/pkg/runtime/resource/types_test.go
  galley/pkg/runtime/source_test.go
  galley/pkg/runtime/state.go
  galley/pkg/runtime/state_test.go
  galley/tools/gen-meta/main.go
Labels: approved, cla: yes, lgtm

#6739 Implement conditional function in Mixer expression language
  mixer/pkg/il/testing/tests.go
  mixer/pkg/lang/ast/expr_test.go
  mixer/pkg/lang/ast/func.go
  mixer/pkg/lang/compiler/compiler.go
Labels: approved, cla: yes, lgtm

#6746 mixer: rename reporter type to kind
  Gopkg.lock
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  istio.deps
  mixer/pkg/attribute/list.gen.go
  mixer/pkg/runtime/dispatcher/util.go
  mixer/pkg/runtime/dispatcher/util_test.go
  mixer/test/e2e/e2e_reftracking_test.go
  mixer/testdata/config/attributes.yaml
  mixer/testdata/config/metrics.yaml
  mixer/testdata/config/tcpmetrics.yaml
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pilot/pkg/networking/plugin/mixer/mixer.go
  vendor/istio.io/api/mixer/v1/global_dictionary.yaml
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#6366 Update istio-remote helm chart to support automatic sidecar injection
  install/kubernetes/helm/README.md
  install/kubernetes/helm/istio-remote/README.md
  install/kubernetes/helm/istio-remote/charts/security/templates/cleanup-old-ca.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/cleanup-secrets.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/clusterrole.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/enable-mesh-mtls.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/serviceaccount.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/OWNERS
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/_helpers.tpl
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/clusterrole.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/service.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/serviceaccount.yaml
  install/kubernetes/helm/istio-remote/requirements.yaml
  install/kubernetes/helm/istio-remote/templates/_helpers.tpl
  install/kubernetes/helm/istio-remote/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/templates/endpoints.yaml
  install/kubernetes/helm/istio-remote/templates/install-custom-resources.sh.tpl
  install/kubernetes/helm/istio-remote/templates/service.yaml
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
Labels: approved, area/environments, cla: yes, lgtm

#6764 Add proxy-status diff command and refactor
  Gopkg.lock
  istioctl/cmd/istioctl/proxystatus.go
  istioctl/pkg/util/configdump/bootstrap.go
  istioctl/pkg/util/configdump/bootstrap_test.go
  istioctl/pkg/util/configdump/cluster.go
  istioctl/pkg/util/configdump/cluster_test.go
  istioctl/pkg/util/configdump/listener.go
  istioctl/pkg/util/configdump/listener_test.go
  istioctl/pkg/util/configdump/route.go
  istioctl/pkg/util/configdump/route_test.go
  istioctl/pkg/util/configdump/testdata/configdump.json
  istioctl/pkg/util/configdump/wrapper.go
  istioctl/pkg/util/proto/messageslice.go
  istioctl/pkg/writer/compare/cluster.go
  istioctl/pkg/writer/compare/cluster_test.go
  istioctl/pkg/writer/compare/comparator.go
  istioctl/pkg/writer/compare/comparator_test.go
  istioctl/pkg/writer/compare/listener.go
  istioctl/pkg/writer/compare/listener_test.go
  istioctl/pkg/writer/compare/route.go
  istioctl/pkg/writer/compare/route_test.go
  istioctl/pkg/writer/compare/testdata/clusterdiff.txt
  istioctl/pkg/writer/compare/testdata/diffenvoyconfigdump.json
  istioctl/pkg/writer/compare/testdata/envoyconfigdump.json
  istioctl/pkg/writer/compare/testdata/listenerdiff.txt
  istioctl/pkg/writer/compare/testdata/pilotconfigdump.json
  istioctl/pkg/writer/compare/testdata/routediff.txt
  istioctl/pkg/writer/envoy/configdump/cluster.go
  istioctl/pkg/writer/envoy/configdump/configdump.go
  istioctl/pkg/writer/envoy/configdump/configdump_test.go
  istioctl/pkg/writer/envoy/configdump/listener.go
  istioctl/pkg/writer/envoy/configdump/route.go
  istioctl/pkg/writer/pilot/status.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/request/command.go
  pilot/pkg/request/command_test.go
  vendor/github.com/bradfitz/slice/COPYING
  vendor/github.com/bradfitz/slice/LICENSE
  vendor/github.com/bradfitz/slice/slice.go
  vendor/go4.org/AUTHORS
  vendor/go4.org/LICENSE
  vendor/go4.org/legal/legal.go
  vendor/go4.org/reflectutil/asm_b.s
  vendor/go4.org/reflectutil/asm_b_14.s
  vendor/go4.org/reflectutil/asm_jmp.s
  vendor/go4.org/reflectutil/asm_jmp_14.s
  vendor/go4.org/reflectutil/reflectutil.go
  vendor/go4.org/reflectutil/swapper.go
  vendor/go4.org/reflectutil/swapper_safe.go
  vendor/go4.org/reflectutil/swapper_unsafe.go
  vendor/go4.org/reflectutil/swapper_unsafe_14.go
  vendor/go4.org/reflectutil/swapper_unsafe_15.go
Labels: approved, cla: yes, lgtm

#6724 tests for aggregate config store
  pilot/pkg/config/aggregate/config_test.go
  pilot/pkg/config/aggregate/fakes/config_store_cache.go
  pilot/pkg/config/clusterregistry/conversion.go
Labels: approved, cla: yes, lgtm

#6683 Initial implementation of generic mcp client
  Gopkg.lock
  Gopkg.toml
  galley/pkg/kube/listener_test.go
  galley/pkg/mcp/client/client.go
  galley/pkg/mcp/client/client_test.go
  vendor/github.com/gogo/status/LICENSE
  vendor/github.com/gogo/status/status.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/go4.org/legal/legal.go
Labels: approved, area/config, cla: yes, lgtm

#6715 A Command line client for mcp protocol
  galley/tools/mcpc/main.go
Labels: approved, cla: yes, lgtm

#6229 Set default requests cpu resource to all deployments
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/statsdtoprom.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/auth.cert-dir.yaml.injected
  pilot/pkg/kube/inject/testdata/auth.non-default-service-account.yaml.injected
  pilot/pkg/kube/inject/testdata/auth.yaml.injected
  pilot/pkg/kube/inject/testdata/cronjob.yaml.injected
  pilot/pkg/kube/inject/testdata/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/enable-core-dump.yaml.injected
  pilot/pkg/kube/inject/testdata/format-duration.yaml.injected
  pilot/pkg/kube/inject/testdata/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-always.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-ignore.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-never.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-proxy-override.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-tproxy-debug.yaml.injected
  pilot/pkg/kube/inject/testdata/hello-tproxy.yaml.injected
  pilot/pkg/kube/inject/testdata/hello.yaml.injected
  pilot/pkg/kube/inject/testdata/job.yaml.injected
  pilot/pkg/kube/inject/testdata/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/list.yaml.injected
  pilot/pkg/kube/inject/testdata/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-params-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/traffic-params.yaml.injected
Labels: approved, cla: yes, lgtm

#6768 Fixes racetest failures in redisquota
  mixer/adapter/redisquota/redisquota_integration_test.go
Labels: approved, cla: yes, lgtm

#6792 Fix upgrade.
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#5416 Add configuration to allow transformation of durations to integers.
  mixer/adapter/fluentd/config/adapter.fluentd.config.pb.html
  mixer/adapter/fluentd/config/config.pb.go
  mixer/adapter/fluentd/config/config.proto
  mixer/adapter/fluentd/config/config.proto_descriptor
  mixer/adapter/fluentd/config/fluentd.yaml
  mixer/adapter/fluentd/fluentd.go
  mixer/adapter/fluentd/fluentd_test.go
  mixer/adapter/fluentd/operatorconfig/fluentd.yaml
Labels: approved, cla: yes, lgtm

#6789 Add workload and service dashboard
  addons/grafana/dashboards/istio-http-grpc-workload-dashboard.json
  addons/grafana/dashboards/istio-mesh-dashboard.json
  addons/grafana/dashboards/istio-service-dashboard.json
  addons/grafana/dashboards/istio-tcp-workload-dashboard.json
  addons/grafana/dashboards/istio-workload-dashboard.json
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/testdata/config/metrics.yaml
  mixer/testdata/config/tcpmetrics.yaml
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: approved, cla: yes, lgtm

#6798 simplify fmt script
  bin/fmt.sh
  broker/pkg/platform/kube/crd/client.go
  galley/pkg/kube/interfaces.go
  galley/pkg/runtime/resource/schema_test.go
  galley/tools/mcpc/main.go
  istioctl/cmd/istioctl/main.go
  mixer/adapter/circonus/circonus.go
  mixer/pkg/config/crd/init.go
  pilot/pkg/config/kube/crd/client.go
  pilot/pkg/config/monitor/fakes/copilot_client.go
  security/pkg/caclient/protocol/protocol.go
  security/tests/integration/kubernetes_utils.go
Labels: cla: no

#6742 support hash based routing for soft session affinity
  Gopkg.lock
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_accounts.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_discovery.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  tests/testdata/config/destination-rule-all.yaml
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.pb.go
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
  vendor/istio.io/api/routing/v1alpha1/dest_policy.pb.go
  vendor/istio.io/api/routing/v1alpha1/dest_policy.proto
  vendor/istio.io/api/routing/v1alpha1/istio.routing.v1alpha1.pb.html
Labels: approved, cla: yes, lgtm

#6799 unset sdsUdsPath in configmap
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: approved, cla: yes, lgtm

#6801 fix bug so that destination.service.** attributes are collected
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#6785 Avoid adding APA attributes into ingress check cache key
  mixer/template/sample/template.gen.go
  mixer/template/template.gen.go
  mixer/test/spyAdapter/template/template.gen.go
  mixer/tools/codegen/pkg/bootstrapgen/template/bootstrapTemplate.go
  mixer/tools/codegen/pkg/bootstrapgen/testdata/template.gen.go.golden
Labels: approved, cla: yes, lgtm

#6790 modify docker template files for proxyv2
  install/consul/templates/istio.yaml.tmpl
  install/eureka/templates/istio.yaml.tmpl
Labels: approved, cla: yes, lgtm

#6819 fix bug so that destination.service.** attributes are collected
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#6818 proxy-status diff of what Pilot has not what it has sent to Envoy
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: approved, cla: yes, lgtm

#6797 Add values for config map settings, including access log.
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes

#6402 SNI routing from sidecar to gateway with virtual services
  pilot/pkg/model/service.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/test/client/client.go
  tests/e2e/tests/pilot/authn_policy_test.go
  tests/e2e/tests/pilot/egressgateway_test.go
  tests/e2e/tests/pilot/externalservice_test.go
  tests/e2e/tests/pilot/ingressgateway_test.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/destination-rule-c.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/disable-mtls-egressgateway.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/egressgateway.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/envoyfilter-c.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/ingressgateway.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-503test-destinationrule-c-add-subset.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-503test-destinationrule-c-del-subset.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-503test-destinationrule-c.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-503test-update-virtualservice.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-503test-virtualservice.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-content-route.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-default-route-append-headers.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-default-route-cors-policy.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-default-route-mirrored.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-default-route.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-fault-injection.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-ingressgateway.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-redirect-injection.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-regex-route.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-route-via-egressgateway.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-websocket-route.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-weighted-route.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/service-entry-bookinfo.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/service-entry-google.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/serviceentry-httpbin.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/serviceentry-nghttp2.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/serviceentry-tcp-wikipedia-cidr.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/serviceentry-tcp-wikipedia-sni.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/serviceentry-wildcard-httpbin.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/virtualservice-route-tcp-a.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/gateway-tcp-a.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-503test-virtualservice.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-force-a-through-ingress-gateway.yaml
  tests/e2e/tests/pilot/testdata/v1alpha3/rule-gateway-a.yaml
Labels: approved, cla: no

#6830 Add myself back to OWNERS, sort the list alphabetically.
  OWNERS
Labels: cla: yes

#6829 Upload cloudfoundry test result to GCS
  .circleci/config.yml
Labels: cla: yes

#6848 Revert #6801 - breaks upgrade from 0.8
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#6705 503s: create DestinationRules before VirtualServices
  samples/bookinfo/routing/destination-rule-all-mtls.yaml
  samples/bookinfo/routing/destination-rule-all.yaml
  samples/bookinfo/routing/route-rule-all-v1.yaml
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/bookinfo/main_test.go
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes

#6835 Updates to accommodate move of api/config/mcp to api/mcp.
  Gopkg.lock
  Gopkg.toml
  galley/pkg/mcp/client/client.go
  galley/pkg/mcp/client/client_test.go
  galley/pkg/mcp/server/server.go
  galley/pkg/mcp/server/server_test.go
  galley/pkg/mcp/snapshot/inmemory.go
  galley/pkg/mcp/snapshot/inmemory_test.go
  galley/pkg/mcp/snapshot/snapshot.go
  galley/pkg/mcp/snapshot/snapshot_test.go
  galley/pkg/runtime/state.go
  galley/pkg/server/server.go
  galley/tools/mcpc/main.go
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/mcp/Readme.md
  vendor/istio.io/api/mcp/v1alpha1/envelope.pb.go
  vendor/istio.io/api/mcp/v1alpha1/envelope.proto
  vendor/istio.io/api/mcp/v1alpha1/istio.mcp.v1alpha1.pb.html
  vendor/istio.io/api/mcp/v1alpha1/mcp.pb.go
  vendor/istio.io/api/mcp/v1alpha1/mcp.proto
  vendor/istio.io/api/mcp/v1alpha1/metadata.pb.go
  vendor/istio.io/api/mcp/v1alpha1/metadata.proto
  vendor/istio.io/api/python/istio_api/mcp/v1alpha1/envelope_pb2.py
  vendor/istio.io/api/python/istio_api/mcp/v1alpha1/mcp_pb2.py
  vendor/istio.io/api/python/istio_api/mcp/v1alpha1/metadata_pb2.py
Labels: approved, cla: yes, lgtm

#6833 deps: update proxy
  istio.deps
Labels: approved, cla: yes, lgtm

#6862 racy access of quota args
  mixer/test/client/env/mixer_server.go
Labels: cla: yes

#6865 Remove the Envoy v1 implementation
  pilot/pkg/proxy/envoy/v1/authentication.go
  pilot/pkg/proxy/envoy/v1/config.go
  pilot/pkg/proxy/envoy/v1/fault.go
  pilot/pkg/proxy/envoy/v1/header.go
  pilot/pkg/proxy/envoy/v1/infra_auth.go
  pilot/pkg/proxy/envoy/v1/ingress.go
  pilot/pkg/proxy/envoy/v1/mixer.go
  pilot/pkg/proxy/envoy/v1/policy.go
  pilot/pkg/proxy/envoy/v1/resources.go
  pilot/pkg/proxy/envoy/v1/route.go
Labels: approved, cla: human-approved, do-not-merge/hold, lgtm

#6869 Remove AZ logic
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/service.go
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/pkg/proxy/envoy/watcher_test.go
  pkg/bootstrap/bootstrap_config.go
Labels: cla: yes

#6867 Rev Istio versions to 1.0.0 in helm charts
  install/kubernetes/helm/istio-remote/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/security/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio-remote/requirements.yaml
  install/kubernetes/helm/istio/Chart.yaml
  install/kubernetes/helm/istio/charts/galley/Chart.yaml
  install/kubernetes/helm/istio/charts/gateways/Chart.yaml
  install/kubernetes/helm/istio/charts/grafana/Chart.yaml
  install/kubernetes/helm/istio/charts/ingress/Chart.yaml
  install/kubernetes/helm/istio/charts/mixer/Chart.yaml
  install/kubernetes/helm/istio/charts/pilot/Chart.yaml
  install/kubernetes/helm/istio/charts/security/Chart.yaml
  install/kubernetes/helm/istio/charts/servicegraph/Chart.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio/requirements.yaml
Labels: approved, cla: yes

#6868 Fix problem where if mixer is disabled, 503 occurs
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: approved, cla: yes

#6743 [test-framework] Support local in-mesh traffic
  pkg/test/local/envoy/agent/agent.go
  pkg/test/local/envoy/agent/agent_test.go
  pkg/test/local/envoy/agent/application.go
  pkg/test/local/envoy/agent/application_proxy.go
  pkg/test/local/envoy/agent/pilot/agent.go
  pkg/test/local/envoy/agent/pilot/application_proxy.go
  pkg/test/local/envoy/agent/pilot/discovery_filter.go
  pkg/test/local/envoy/agent/pilot/reserveport/manager.go
  pkg/test/local/envoy/agent/pilot/reserveport/pool.go
  pkg/test/local/envoy/agent/stop.go
  pkg/test/protocol/client.go
  pkg/test/service/echo/application.go
  pkg/test/service/echo/client.go
  pkg/test/service/echo/factory.go
  pkg/test/service/echo/handler.go
  pkg/test/service/echo/server/main.go
Labels: approved, cla: yes, lgtm

#6740 initial check in for caclient
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/caClient/client.go
  security/pkg/nodeagent/caClient/client_test.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/secretmanager.go
Labels: approved, cla: yes, lgtm

#6827 Add galley config validation metrics and improved loggings
  Makefile
  galley/cmd/galley/cmd/validator.go
  galley/pkg/crd/validation/monitoring.go
  galley/pkg/crd/validation/webhook.go
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/templates/service.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml
Labels: cla: yes, lgtm

#6822 do not ignore subsets in soft sticky sessions
  Gopkg.lock
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  vendor/istio.io/api/config/mcp/Readme.md
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.pb.go
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  vendor/istio.io/api/routing/v1alpha1/ingress_rule.pb.go
  vendor/istio.io/api/routing/v1alpha1/ingress_rule.proto
  vendor/istio.io/api/routing/v1alpha1/istio.routing.v1alpha1.pb.html
  vendor/istio.io/api/routing/v1alpha1/route_rule.pb.go
  vendor/istio.io/api/routing/v1alpha1/route_rule.proto
Labels: cla: no

#6887 Mark gateway ports as H2 in k8s
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes

#6901 Remove v1alpha1 -> v1alpha3 conversion tool
  istioctl/cmd/istioctl/convert/cmd.go
  istioctl/cmd/istioctl/convert/cmd_test.go
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/another-ingress.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/destination-policy-helloworld.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/egress-rule-google.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/egress-rule-httpbin.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/egress-rule-tcp-wikipedia-cidr.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/egress-rule-wildcard-httpbin.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/myservice-ingress.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/nolabel-destination-policy.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/route-rule-80-20.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-content-route.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-default-route-append-headers.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-default-route-cors-policy.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-default-route-mirrored.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-default-route.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-fault-injection.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-redirect-injection.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-regex-route.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-websocket-route.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha1/rule-weighted-route.yaml
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/.gitignore
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/destination-rule-helloworld-with-80-20.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/destination-rule-helloworld.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/egress-rule-google.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/egress-rule-httpbin.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/egress-rule-tcp-wikipedia-cidr.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/egress-rule-wildcard-httpbin.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/merged-gateway.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/myservice-gateway.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/nolabel-destination-rule.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/route-rule-80-20-with-destpolicy.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/route-rule-80-20.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-content-route.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-default-route-append-headers.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-default-route-cors-policy.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-default-route-mirrored.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-default-route.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-fault-injection.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-redirect-injection.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-regex-route.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-websocket-route.yaml.golden
  istioctl/cmd/istioctl/convert/testdata/v1alpha3/rule-weighted-route.yaml.golden
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
  istioctl/pkg/convert/destination.go
  istioctl/pkg/convert/egress.go
  istioctl/pkg/convert/ingress.go
  istioctl/pkg/convert/route.go
Labels: approved, cla: yes, lgtm

#6897 Make the error message when Istio is checked out into the wrong place less confusing
  Makefile
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#6903 Added support for istioctl kube-inject into a Pod
  istioctl/cmd/istioctl/kubeinject.go
  pilot/pkg/kube/inject/initializer.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/testdata/pod.yaml
  pilot/pkg/kube/inject/testdata/pod.yaml.injected
Labels: cla: yes

#6914 Correcting duplication of annotations field in values.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#6911 Remove the post-install hooks when they were completed successfully
  install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
Labels: cla: yes

#6890 Remove broker related code, test, and build files
  Gopkg.lock
  Makefile
  README.md
  broker/OWNERS
  broker/README.md
  broker/bin/perftest.sh
  broker/cmd/brks/cmd/root.go
  broker/cmd/brks/cmd/server.go
  broker/cmd/brks/main.go
  broker/cmd/shared/print.go
  broker/example/crd.yaml
  broker/example/demo_catalog.json
  broker/example/demo_catalog.yaml
  broker/pkg/controller/controller.go
  broker/pkg/controller/controller_test.go
  broker/pkg/model/config/resource.go
  broker/pkg/model/config/schema.go
  broker/pkg/model/config/schema_test.go
  broker/pkg/model/config/store.go
  broker/pkg/model/config/store_test.go
  broker/pkg/model/osb/catalog.go
  broker/pkg/model/osb/catalog_test.go
  broker/pkg/model/osb/service.go
  broker/pkg/model/osb/serviceBinding.go
  broker/pkg/model/osb/serviceInstance.go
  broker/pkg/model/osb/servicePlan.go
  broker/pkg/model/osb/service_test.go
  broker/pkg/model/osb/serviceplan_test.go
  broker/pkg/platform/kube/crd/client.go
  broker/pkg/platform/kube/crd/client_test.go
  broker/pkg/platform/kube/crd/conversion.go
  broker/pkg/platform/kube/crd/conversion_test.go
  broker/pkg/platform/kube/crd/generate.sh
  broker/pkg/platform/kube/crd/template.go
  broker/pkg/platform/kube/crd/types.go
  broker/pkg/server/broker.go
  broker/pkg/testing/mock/config.go
  broker/pkg/testing/mock/proto/fake_config.pb.go
  broker/pkg/testing/mock/proto/fake_config.proto
  broker/pkg/testing/util/kubernetes.go
  codecov.requirement
  istioctl/cmd/istioctl/main.go
Labels: cla: yes

#6886 add tests for headless services and stateful sets
  tests/e2e/tests/pilot/grpc_test.go
  tests/e2e/tests/pilot/headless_test.go
  tests/e2e/tests/pilot/http_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/tcp_test.go
  tests/e2e/tests/pilot/testdata/app.yaml.tmpl
  tests/e2e/tests/pilot/testdata/headless.yaml
  tests/e2e/tests/pilot/testdata/statefulset.yaml.tmpl
Labels: approved, cla: yes

#6931 Remove vendored broker API dependencies
  Gopkg.lock
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/broker/dev/istio.broker.dev.pb.html
  vendor/istio.io/api/broker/dev/service_class.pb.go
  vendor/istio.io/api/broker/dev/service_class.proto
  vendor/istio.io/api/broker/dev/service_plan.pb.go
  vendor/istio.io/api/broker/dev/service_plan.proto
  vendor/istio.io/api/python/istio_api/broker/dev/service_class_pb2.py
  vendor/istio.io/api/python/istio_api/broker/dev/service_plan_pb2.py
Labels: approved, cla: yes, lgtm

#6896 Add mesh expansion gateway
  install/kubernetes/helm/istio-remote/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml
  install/kubernetes/helm/istio-remote/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/meshexpansion.yaml
  install/kubernetes/helm/istio/charts/security/templates/meshexpansion.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, area/environments, cla: yes

#6894 Use Shriram's env for better upgrade fix.
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes

#6940 Move mixer rules under policy and rename route-rule to virtual-service
  samples/bookinfo/networking/ROUTING_RULE_MIGRATION.md
  samples/bookinfo/networking/bookinfo-gateway.yaml
  samples/bookinfo/networking/destination-rule-all-mtls.yaml
  samples/bookinfo/networking/destination-rule-all.yaml
  samples/bookinfo/networking/destination-rule-reviews.yaml
  samples/bookinfo/networking/egress-rule-google-apis.yaml
  samples/bookinfo/networking/virtual-service-all-v1.yaml
  samples/bookinfo/networking/virtual-service-details-v2.yaml
  samples/bookinfo/networking/virtual-service-ratings-db.yaml
  samples/bookinfo/networking/virtual-service-ratings-mysql-vm.yaml
  samples/bookinfo/networking/virtual-service-ratings-mysql.yaml
  samples/bookinfo/networking/virtual-service-ratings-test-abort.yaml
  samples/bookinfo/networking/virtual-service-ratings-test-delay.yaml
  samples/bookinfo/networking/virtual-service-reviews-50-v3.yaml
  samples/bookinfo/networking/virtual-service-reviews-80-20.yaml
  samples/bookinfo/networking/virtual-service-reviews-90-10.yaml
  samples/bookinfo/networking/virtual-service-reviews-jason-v2-v3.yaml
  samples/bookinfo/networking/virtual-service-reviews-test-v2.yaml
  samples/bookinfo/networking/virtual-service-reviews-v2-v3.yaml
  samples/bookinfo/networking/virtual-service-reviews-v3.yaml
  samples/bookinfo/policy/mixer-rule-additional-telemetry.yaml
  samples/bookinfo/policy/mixer-rule-deny-label.yaml
  samples/bookinfo/policy/mixer-rule-deny-serviceaccount.yaml
  samples/bookinfo/policy/mixer-rule-ingress-denial.yaml
  samples/bookinfo/policy/mixer-rule-kubernetesenv-telemetry.yaml
  samples/bookinfo/policy/mixer-rule-ratings-denial.yaml
  samples/bookinfo/policy/mixer-rule-ratings-ratelimit.yaml
  samples/rawvm/README.md
  tests/e2e/tests/bookinfo/main_test.go
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/upgrade/upgrade_test.go
Labels: cla: yes

#6941 Follow up on upgrade bug
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#6938 Move dump_kubernetes.sh to tools/ (gets copied to istio-archive)
  Makefile
  tests/istio.mk
  tools/dump_kubernetes.sh
Labels: approved, cla: yes, lgtm

#6942 Updated the stress/load test cases.
  tests/helm/setup.sh
  tests/helm/templates/fortio-080.yaml
  tests/helm/templates/fortio-10rc1.yaml
  tests/helm/templates/fortio-cli.yaml
  tests/helm/templates/fortio-noistio.yaml
  tests/helm/templates/fortio-tls.yaml
  tests/helm/templates/fortio-tproxy.yaml
  tests/helm/templates/fortio.yaml
  tests/helm/templates/gateway.yaml
  tests/helm/values-istio-test.yaml
  tests/helm/values.yaml
Labels: approved, cla: no

#6959 Check for existence of localregistry.yaml file in setup_host script
  tests/e2e/local/minikube/setup_host.sh
Labels: approved, cla: yes, lgtm

#6965 Fix racetest following #6890
  .circleci/config.yml
Labels: cla: yes, lgtm

#6975 [test-framework] Remove tagging/label support.
  pkg/test/flags.go
  pkg/test/impl/driver/args.go
  pkg/test/impl/driver/instance.go
  pkg/test/impl/driver/interface.go
  pkg/test/label/label.go
  pkg/test/label/labels.go
  pkg/test/operations.go
  tests/e2e/tests/showcase/showcase_test.go
Labels: cla: yes

#6943 [BOT PR] to update dependencies of istio
  istio.deps
Labels: cla: yes, dependency-update, lgtm, release-note-none

#6952 fix type_url used to construct sds.DiscoveryResponse
  security/pkg/nodeagent/sds/sdsservice.go
Labels: approved, cla: yes, lgtm

#6954 add stat_prefix field in sdsconfig grpc setting
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
Labels: approved, cla: yes, lgtm

#6955 some cleanup on sdsservice
  security/pkg/nodeagent/sds/sdsservice.go
Labels: approved, cla: yes, lgtm

#6980 only set upstreamTsContext.AlpnProtocols to 'istio' in ISTIO_MUTUAL mode
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#6990 remove all dummy certs related code in nodeagent
  pilot/docker/Dockerfile.proxyv2
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  security/cmd/node_agent_k8s/main.go
  security/docker/Dockerfile.node-agent-k8s
  security/docker/nodeagent-sds-cert.pem
  security/docker/nodeagent-sds-key.pem
  security/pkg/nodeagent/sds/server.go
  security/tools/sds/sds_cli.go
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#6910 Create the grafana policy at post-install
  install/kubernetes/helm/istio/charts/grafana/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/grafana-ports-mtls.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/service.yaml
Labels: cla: yes, kind/blocking daily release

#6893 Remove old config
  galley/cmd/galley/cmd/validator.go
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/aggregate/config_test.go
  pilot/pkg/config/kube/crd/conversion_test.go
  pilot/pkg/config/kube/crd/types.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/conversion_test.go
  pilot/pkg/model/egress_rules.go
  pilot/pkg/model/egress_rules_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/test/mock/config.go
  tests/e2e/tests/galley/galley_test.go
  tests/e2e/tests/galley/testdata/config-v1alpha2-DestinationPolicy-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-DestinationPolicy-valid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-EgressRule-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-EgressRule-valid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-RouteRule-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-RouteRule-valid.yaml
  tests/e2e/tests/pilot/ingress/controller_test.go
Labels: cla: no

#6749 sample: add new sample yaml for local RBAC.
  samples/bookinfo/kube/rbac/details-reviews-policy.yaml
  samples/bookinfo/kube/rbac/namespace-policy.yaml
  samples/bookinfo/kube/rbac/productpage-policy.yaml
  samples/bookinfo/kube/rbac/ratings-policy.yaml
  samples/bookinfo/kube/rbac/rbac-config-ON.yaml
Labels: approved, area/security/aaa, cla: yes

#6953 Avoid returning empty strings from k8s env adapter
  mixer/template/sample/template.gen.go
  mixer/template/template.gen.go
  mixer/test/spyAdapter/template/template.gen.go
  mixer/tools/codegen/pkg/bootstrapgen/template/bootstrapTemplate.go
  mixer/tools/codegen/pkg/bootstrapgen/testdata/template.gen.go.golden
Labels: approved, cla: yes, lgtm

#6660 add certmanager integration
  install/kubernetes/helm/istio/charts/certmanager/Chart.yaml
  install/kubernetes/helm/istio/charts/certmanager/templates/NOTES.txt
  install/kubernetes/helm/istio/charts/certmanager/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/certmanager/templates/crds.yaml
  install/kubernetes/helm/istio/charts/certmanager/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/certmanager/templates/rbac.yaml
  install/kubernetes/helm/istio/charts/certmanager/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values.yaml
  samples/bookinfo/kube/bookinfo-certificate.yaml
  samples/bookinfo/routing/certmanager-egress-rules.yaml
  samples/bookinfo/routing/certmanager-gateway.yaml
Labels: cla: yes

#7012 makefile now pulls released dep
  Makefile
Labels: approved, cla: yes

#7017 remove MeshPolicy/DefaultDestRule CRD when mTLS isn't enabled
  install/kubernetes/helm/istio/charts/security/templates/configmap.yaml
Labels: cla: yes

#7016 Ensure destination weights total 100 percent
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: approved, cla: yes, lgtm

#6992 Generate listeners for endpoints not yet ready
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes

#6973 removed eureka adapter
  .gitignore
  Makefile
  README.md
  codecov.requirement
  install/eureka/README.md
  install/eureka/kubeconfig
  install/eureka/templates/istio.yaml.tmpl
  install/updateVersion.sh
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
  pilot/codecov.requirement
  pilot/docker/Dockerfile.eurekamirror
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/conversion.go
  pilot/pkg/serviceregistry/eureka/client.go
  pilot/pkg/serviceregistry/eureka/client_test.go
  pilot/pkg/serviceregistry/eureka/controller.go
  pilot/pkg/serviceregistry/eureka/controller_test.go
  pilot/pkg/serviceregistry/eureka/conversion.go
  pilot/pkg/serviceregistry/eureka/conversion_test.go
  pilot/pkg/serviceregistry/eureka/serviceaccounts.go
  pilot/pkg/serviceregistry/eureka/servicediscovery.go
  pilot/pkg/serviceregistry/eureka/servicediscovery_test.go
  pilot/pkg/serviceregistry/eureka/testdata/eureka-apps.json
  pilot/pkg/serviceregistry/eureka/testdata/eureka-no-apps.json
  pilot/pkg/serviceregistry/platform.go
  pilot/test/eurekamirror/eurekamirror.go
  samples/bookinfo/platform/eureka/README.md
  samples/bookinfo/platform/eureka/bookinfo.yaml
  samples/bookinfo/platform/eureka/cleanup.sh
  samples/bookinfo/platform/eureka/route-rule-all-v1.yaml
  samples/bookinfo/platform/eureka/route-rule-ratings-db.yaml
  samples/bookinfo/platform/eureka/route-rule-ratings-test-abort.yaml
  samples/bookinfo/platform/eureka/route-rule-ratings-test-delay.yaml
  samples/bookinfo/platform/eureka/route-rule-reviews-50-v3.yaml
  samples/bookinfo/platform/eureka/route-rule-reviews-test-v2.yaml
  samples/bookinfo/platform/eureka/route-rule-reviews-v2-v3.yaml
  samples/bookinfo/platform/eureka/route-rule-reviews-v3.yaml
  samples/bookinfo/platform/eureka/templates/bookinfo.sidecars.yaml.tmpl
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/simple/nginx_test.go
  tools/istio-docker.mk
Labels: cla: yes

#7020 move bookinfo/kube/* to bookinfo/platform/kube
  samples/bookinfo/platform/kube/bookinfo-certificate.yaml
  samples/bookinfo/platform/kube/rbac/details-reviews-policy.yaml
  samples/bookinfo/platform/kube/rbac/namespace-policy.yaml
  samples/bookinfo/platform/kube/rbac/productpage-policy.yaml
  samples/bookinfo/platform/kube/rbac/ratings-policy.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-ON.yaml
Labels: approved, cla: yes, lgtm

#6997 update the istio.io/api SHA (https://github.com/istio/api/pull/575) and istio.io/proxy SHA
  Gopkg.lock
Labels: approved, cla: yes, lgtm

#6995 Add the monitoring of the "alpha.istio.io/canonical-serviceaccounts" annotation
  security/cmd/istio_ca/main.go
  security/pkg/registry/kube/service.go
  security/pkg/registry/kube/service_test.go
Labels: approved, cla: yes, lgtm

#6967 Add requested server name attribute (SNI)
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  istio.deps
  mixer/testdata/config/accesslog.yaml
  mixer/testdata/config/attributes.yaml
  mixer/testdata/config/tcp_accesslog.yaml
Labels: approved, cla: yes, lgtm

#7027 Improve template query for workload variable in workload dashboard
  addons/grafana/dashboards/istio-workload-dashboard.json
Labels: approved, cla: yes, lgtm

#7024 move certmanager configs from bookinfo/routing to bookinfo/networking
  samples/bookinfo/networking/certmanager-gateway.yaml
  samples/bookinfo/routing/certmanager-egress-rules.yaml
Labels: approved, cla: yes

#7032 deps: update proxy
  istio.deps
Labels: approved, cla: human-approved, cla: no

#6888 Mocking and CLI test for proxy-status and proxy-config
  istioctl/cmd/istioctl/main.go
  istioctl/cmd/istioctl/proxyconfig.go
  istioctl/cmd/istioctl/proxyconfig_test.go
  istioctl/cmd/istioctl/proxystatus.go
  istioctl/cmd/istioctl/proxystatus_test.go
  istioctl/pkg/kubernetes/client.go
Labels: approved, cla: yes

#6936 Purge v1alpha1 routing from e2e
  tests/e2e/framework/test_flags.go
  tests/e2e/framework/test_flags_test.go
  tests/e2e/tests/bookinfo/demo_test.go
  tests/e2e/tests/bookinfo/main_test.go
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/pilot/ingress/controller_test.go
  tests/e2e/tests/pilot/ingress/main_test.go
  tests/e2e/tests/simple/a_simple_1_test.go
  tests/e2e/tests/simple/testdata/routingrule1.yaml
  tests/e2e/tests/simple/testdata/routingrule2.yaml
  tests/e2e/tests/simple/testdata/routingruleNoPods.yaml
  tests/e2e/tests/simple/testdata/servicesNotInjected.yaml
  tests/e2e/tests/simple/testdata/servicesToBeInjected.yaml
  tests/istio.mk
Labels: approved, cla: yes

#7046 Use nightly release-1.0 rather than master
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes

#6702 print failed envoy bootstrap config on start failure
  pilot/pkg/proxy/agent.go
  pilot/pkg/proxy/envoy/watcher.go
Labels: approved, area/networking, cla: yes

#6669 SignalFx TraceSpan Support
  Gopkg.lock
  mixer/adapter/signalfx/config/adapter.signalfx.config.pb.html
  mixer/adapter/signalfx/config/config.pb.go
  mixer/adapter/signalfx/config/config.proto
  mixer/adapter/signalfx/config/config.proto_descriptor
  mixer/adapter/signalfx/config/signalfx.yaml
  mixer/adapter/signalfx/metrics.go
  mixer/adapter/signalfx/metrics_integration_test.go
  mixer/adapter/signalfx/operatorconfig/signalfx.yaml
  mixer/adapter/signalfx/operatorconfig/tracing.yaml
  mixer/adapter/signalfx/signalfx.go
  mixer/adapter/signalfx/signalfx_test.go
  mixer/adapter/signalfx/tracing.go
  mixer/adapter/signalfx/tracing_integration_test.go
  mixer/adapter/stackdriver/trace/trace.go
  mixer/adapter/stackdriver/trace/trace_test.go
  mixer/pkg/adapter/traceutil.go
  mixer/pkg/adapter/traceutil_test.go
  vendor/github.com/signalfx/golib/sfxclient/cancel14.go
  vendor/github.com/signalfx/golib/sfxclient/cancel15.go
  vendor/github.com/signalfx/golib/sfxclient/httpsink.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#6891 Stackdriver Context Graph adapter: support regional GKE clusters
  mixer/adapter/stackdriver/contextgraph/workload.go
  mixer/adapter/stackdriver/contextgraph/workload_test.go
Labels: approved, cla: yes, lgtm

#7056 DO NOT MERGE TO MASTER: Revert "Restore pulling from master before testing, was lost by merge…
  .circleci/config.yml
  Makefile
Labels: cla: yes

#7048 Disable ingress in default Helm install
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes

#6994 Add batching to stackdriver adapter
  mixer/adapter/stackdriver/metric/bufferedClient.go
  mixer/adapter/stackdriver/metric/bufferedClient_test.go
  mixer/adapter/stackdriver/metric/merge_test.go
  mixer/adapter/stackdriver/metric/metric.go
Labels: approved, cla: yes, lgtm

#7044 Trim /32 subnet prefix from service entry addresses
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes

#7060 move ca root cert to different path in proxyv2 image
  pilot/docker/Dockerfile.proxyv2
  pilot/pkg/model/authentication.go
Labels: approved, cla: yes, lgtm

#7043 Add listeners by creation time and cleanup error reports for conflicts
  istioctl/cmd/istioctl/istioctl_test.go
  pilot/pkg/config/memory/config.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
Labels: approved, cla: no

#7028 mixerplugin: undo changes, add default outbound service config
  mixer/test/client/env/ports.go
  mixer/test/client/env/setup.go
  mixer/test/client/pilotplugin/pilotplugin_test.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#7071 remove crd registration for legacy routing APIs
  galley/pkg/kube/types.go
  galley/pkg/runtime/resource/types.go
  galley/tools/gen-meta/metadata.yaml
  install/kubernetes/helm/istio/charts/galley/templates/validatingwebhook.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/crds.yaml
  istioctl/cmd/istioctl/main.go
Labels: cla: yes

#7054 Add support in kubeenv adapter to generate missing pod uids
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
  mixer/adapter/kubernetesenv/template/adapter.template.kubernetes.pb.html
  mixer/adapter/kubernetesenv/template/template.proto
  mixer/adapter/kubernetesenv/template/template_handler.gen.go
  mixer/adapter/kubernetesenv/template/template_proto.descriptor_set
  mixer/template/template.gen.go
  mixer/testdata/config/kubernetesenv.yaml
Labels: approved, cla: yes, lgtm

#7062 Fix Helm upgrade error from 0.8.0 to 1.0
  install/kubernetes/helm/istio/charts/ingress/templates/clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm

#7035 remove gateway not used
  samples/bookinfo/networking/virtual-service-all-v1.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#7074 Fix the rbac sample files for Istio 1.0.
  samples/bookinfo/platform/kube/rbac/details-reviews-policy.yaml
  samples/bookinfo/platform/kube/rbac/ratings-policy.yaml
Labels: cla: yes

#7064 add categories to Istio's custom resource definitions
  install/kubernetes/helm/istio/charts/mixer/templates/crds.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/crds.yaml
  mixer/cmd/mixs/cmd/crd.go
  mixer/cmd/mixs/cmd/crd_test.go
Labels: approved, cla: yes, lgtm

#7019 Remove api.* attributes from accesslog as they are yet to be implemented
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
Labels: approved, cla: yes, lgtm

#7091 remove unused legacy v1alpha1 routing apis
  Gopkg.lock
  galley/pkg/runtime/resource/types.go
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  vendor/istio.io/api/mixer/v1/config/client/service.pb.go
  vendor/istio.io/api/mixer/v1/config/client/service.proto
  vendor/istio.io/api/mixer/v1/global_dictionary.yaml
  vendor/istio.io/api/python/istio_api/routing/v1alpha1/dest_policy_pb2.py
  vendor/istio.io/api/python/istio_api/routing/v1alpha1/egress_rule_pb2.py
  vendor/istio.io/api/python/istio_api/routing/v1alpha1/http_fault_pb2.py
  vendor/istio.io/api/python/istio_api/routing/v1alpha1/ingress_rule_pb2.py
  vendor/istio.io/api/python/istio_api/routing/v1alpha1/l4_fault_pb2.py
  vendor/istio.io/api/python/istio_api/routing/v1alpha1/route_rule_pb2.py
  vendor/istio.io/api/rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  vendor/istio.io/api/rbac/v1alpha1/rbac.pb.go
  vendor/istio.io/api/rbac/v1alpha1/rbac.proto
  vendor/istio.io/api/routing/v1alpha1/dest_policy.pb.go
  vendor/istio.io/api/routing/v1alpha1/dest_policy.proto
  vendor/istio.io/api/routing/v1alpha1/egress_rule.pb.go
  vendor/istio.io/api/routing/v1alpha1/egress_rule.proto
  vendor/istio.io/api/routing/v1alpha1/http_fault.pb.go
  vendor/istio.io/api/routing/v1alpha1/http_fault.proto
  vendor/istio.io/api/routing/v1alpha1/ingress_rule.pb.go
  vendor/istio.io/api/routing/v1alpha1/ingress_rule.proto
  vendor/istio.io/api/routing/v1alpha1/istio.routing.v1alpha1.pb.html
  vendor/istio.io/api/routing/v1alpha1/l4_fault.pb.go
  vendor/istio.io/api/routing/v1alpha1/l4_fault.proto
  vendor/istio.io/api/routing/v1alpha1/route_rule.pb.go
  vendor/istio.io/api/routing/v1alpha1/route_rule.proto
Labels: cla: yes

#7007 Updating Kiali to v0.5.0 in Helm Installer
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#7031 mixer logging: log decompressed attributes
  mixer/pkg/attribute/protoBag.go
Labels: approved, cla: yes

#7094 Istio-remote helm: allow setup pilot svc & endpoint for controlPlaneSecurity
  install/kubernetes/helm/istio-remote/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/templates/endpoints.yaml
  install/kubernetes/helm/istio-remote/templates/service.yaml
  install/kubernetes/helm/istio-remote/values.yaml
Labels: cla: yes

#7095 remove MeshPolicy/DefaultDestRule crd when mtls isn't enabled
  install/kubernetes/helm/istio-remote/charts/security/templates/configmap.yaml
Labels: cla: yes

#7092 Change mixer-post-install job name to indicate release version
  install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml
Labels: approved, cla: yes, lgtm

#7039 Fix for ingress conflict with tracing ingress
  install/kubernetes/helm/istio/charts/tracing/templates/ingress-jaeger.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: cla: yes

#7110 Mixer: delete unix socket before calling listen
  mixer/pkg/server/server.go
Labels: approved, cla: yes, lgtm

#7134 typo: connctionDuration -> connectionDuration
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
Labels: cla: yes

#7125 Avoid CRD leftover
  install/kubernetes/helm/istio/charts/mixer/templates/crds.yaml
Labels: cla: yes

#7119 Fix two data races
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: cla: yes

#7145 Update Release (Airflow) config to the current in-use version
  release/pipeline/configs/environment_config.py
  release/pipeline/dags/istio_common_dag.py
  release/pipeline/dags/istio_daily_master.py
  release/pipeline/dags/istio_daily_release_0_8.py
  release/pipeline/dags/istio_daily_release_1_0.py
  release/pipeline/dags/istio_monthly_flow.py
  release/pipeline/dags/istio_monthly_release_0_8.py
  release/pipeline/operators/gcs_to_gcs.py
Labels: approved, area/test and release, automated-release, cla: yes, lgtm

#7101 TCP routing cleanups/bug fixes: part 1
  Gopkg.lock
  pilot/pkg/model/push_status.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/util/util.go
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes

#7147 add reporterKind attribute to accesslog and tcpaccesslog
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
Labels: approved, cla: yes, lgtm

#7113 Improve outbound listener conflict messages
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes

#7158 Update accesslog config
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
Labels: approved, cla: yes, lgtm

#7156 mixer: allow configuring mixer ports
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: cla: yes

#7160 Adding unit test for TCP over TCP conflicts.
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: approved, cla: yes

#7123 Assorted small fixes for setup
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/service.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: approved, cla: yes

#7173 Adding e2e test for outbound listener conflicts
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/pilot/listener_conflict_test.go
Labels: cla: yes

#7175 remove static route generation. improve gateway validation
  pilot/pkg/config/monitor/monitor_test.go
  pilot/pkg/model/config.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes

#7042 Updating Kiali to v0.5.0 on Ansible Installer
  install/ansible/istio/tasks/install_addons.yml
Labels: approved, cla: yes, lgtm

#7085 Multicluster make zipkin conditional
  install/kubernetes/helm/istio-remote/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
Labels: approved, cla: yes, lgtm

#7177 Another place of the connctionDuration typo
  mixer/testdata/config/tcp_accesslog.yaml
Labels: cla: yes

#7178 Regenerate the Citadel templates
  install/kubernetes/citadel_extras/istio-citadel-plugin-certs.yaml.tmpl
  install/kubernetes/citadel_extras/istio-citadel-standalone.yaml.tmpl
  install/kubernetes/citadel_extras/istio-citadel-with-health-check.yaml.tmpl
  install/updateVersion.sh
Labels: cla: yes

#7152 make bookinfo sample build repeatable
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-add-serviceaccount.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/build-services.sh
  samples/bookinfo/src/productpage/requirements.txt
Labels: cla: yes

#7189 remove v1 registration from readiness probe and use debu/endpointz
  .gitignore
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: cla: yes

#7109 bookinfo fixes
  samples/CONFIG-MIGRATION.md
  samples/bookinfo/networking/virtual-service-ratings-test-abort.yaml
  samples/bookinfo/networking/virtual-service-ratings-test-delay.yaml
  samples/bookinfo/networking/virtual-service-reviews-jason-v2-v3.yaml
  samples/bookinfo/networking/virtual-service-reviews-test-v2.yaml
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/consul/route-rule-ratings-test-abort.yaml
  samples/bookinfo/platform/consul/route-rule-ratings-test-delay.yaml
  samples/bookinfo/platform/consul/route-rule-reviews-test-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-add-serviceaccount.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/build-services.sh
  samples/bookinfo/src/productpage/productpage.py
  samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
  tests/e2e/tests/bookinfo/demo_test.go
  tests/e2e/tests/bookinfo/main_test.go
  tests/e2e/tests/upgrade/upgrade_test.go
Labels: cla: yes

#7144 Fix broken ingress
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/push_status.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes

#7193 rbac: add e2e tests for envoy based rbac.
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/testdata/app.yaml.tmpl
  tests/e2e/tests/pilot/testdata/v1alpha2/istio-rbac-enable.yaml.tmpl
  tests/e2e/tests/pilot/testdata/v1alpha2/istio-rbac-rules.yaml.tmpl
Labels: cla: yes, lgtm

#7201 Update syntax used to configure xDS servers.
  mixer/test/client/dynamic_attribute/dynamic_attribute_test.go
  mixer/test/client/dynamic_listener/dynamic_listener_test.go
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  tests/testdata/bootstrap_tmpl.json
  tests/testdata/cf_bootstrap_tmpl.json
  tests/testdata/envoy_local.json
  tests/testdata/multicluster/envoy_local_v2.yaml
Labels: cla: yes

#7202 Update go-control-plane to 8cef83f9.
  Gopkg.lock
  pilot/pkg/proxy/envoy/v2/ads.go
  vendor/github.com/envoyproxy/go-control-plane/build/integration.sh
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/cds.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/health_check.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/health_check.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/discovery.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/discovery.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/rds.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/accesslog/v2/accesslog.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/accesslog/v2/accesslog.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/metrics/v2/metrics_service.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/metrics/v2/stats.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/config/metrics/v2/stats.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/type/string_match.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/type/string_match.pb.validate.go
  vendor/github.com/envoyproxy/go-control-plane/glide.lock
  vendor/github.com/envoyproxy/go-control-plane/glide.yaml
  vendor/github.com/envoyproxy/go-control-plane/pkg/server/server.go
  vendor/github.com/envoyproxy/go-control-plane/pkg/test/resource/resource.go
  vendor/github.com/envoyproxy/go-control-plane/sample/bootstrap-ads.yaml
  vendor/github.com/envoyproxy/go-control-plane/sample/bootstrap-xds.yaml
Labels: approved, cla: yes, lgtm

#7195 bump bookinfo version to 1.8.0
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-add-serviceaccount.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: cla: yes

#7194 Add contents of install/ansible to release script
  release/create_release_archives.sh
Labels: cla: yes

#7088 update for 1.0.0 path
  install/gcp/deployment_manager/istio-cluster.jinja
  install/gcp/deployment_manager/istio-cluster.jinja.display
  install/gcp/deployment_manager/istio-cluster.jinja.schema
  install/gcp/deployment_manager/istio-cluster.yaml
Labels: approved, cla: yes, do-not-merge/hold, lgtm

#7204 update api sha
  Gopkg.lock
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
Labels: cla: yes

#7051 Delete namespace after tests when using helm
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#6720 Add an e2e test for RedisQuota Adapter
  install/kubernetes/helm/istio/charts/mixer/templates/crds.yaml
  mixer/adapter/inventory.gen.go
  mixer/adapter/inventory.yaml
  mixer/adapter/redisquota/redisquota.go
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/mixer/testdata/mixer-rule-ratings-redis-quota.yaml
  tests/util/kube_utils.go
Labels: approved, cla: yes

#7207 Move Kubernetes Ansible to proper location
  install/kubernetes/ansible/README.md
  install/kubernetes/ansible/ansible.cfg
  install/kubernetes/ansible/istio/defaults/main.yml
  install/kubernetes/ansible/istio/meta/main.yml
  install/kubernetes/ansible/istio/tasks/add_to_path.yml
  install/kubernetes/ansible/istio/tasks/assert_oc_admin.yml
  install/kubernetes/ansible/istio/tasks/bookinfo_cmd.j2
  install/kubernetes/ansible/istio/tasks/change_scc.yml
  install/kubernetes/ansible/istio/tasks/create_namespace_free_definition_file.yml
  install/kubernetes/ansible/istio/tasks/delete_resources.yml
  install/kubernetes/ansible/istio/tasks/determine_latest_version.yml
  install/kubernetes/ansible/istio/tasks/determine_version.yml
  install/kubernetes/ansible/istio/tasks/get_istio_assets.yml
  install/kubernetes/ansible/istio/tasks/install.yml
  install/kubernetes/ansible/istio/tasks/install_addons.yml
  install/kubernetes/ansible/istio/tasks/install_distro.yml
  install/kubernetes/ansible/istio/tasks/install_on_cluster.yml
  install/kubernetes/ansible/istio/tasks/install_sample.yml
  install/kubernetes/ansible/istio/tasks/install_samples.yml
  install/kubernetes/ansible/istio/tasks/main.yml
  install/kubernetes/ansible/istio/tasks/safely_create_namespace.yml
  install/kubernetes/ansible/istio/tasks/set_appropriate_cmd_path.yml
  install/kubernetes/ansible/istio/tasks/set_istio_distro_vars.yml
  install/kubernetes/ansible/istio/tasks/simple_sample_cmd.j2
  install/kubernetes/ansible/istio/vars/main.yml
  install/kubernetes/ansible/main.yml
Labels: approved, cla: yes

#7206 Fixing a wrong Json key for the CreationTimestamp field
  pilot/pkg/model/config.go
Labels: cla: yes

#7209 rename key for istio-remote chart repository->hub
  install/kubernetes/helm/istio-remote/charts/security/templates/cleanup-secrets.yaml
  install/kubernetes/helm/istio-remote/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio-remote/values.yaml
Labels: approved, cla: yes, lgtm

#7187 Move "repository" to "hub" and hardcode image name
  install/kubernetes/helm/istio/charts/grafana/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/statsdtoprom.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/cleanup-secrets.yaml
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#7219 [test-framework] Expose get-or-create semantics of dependencies.
  pkg/test/impl/driver/instance.go
  pkg/test/internal/context.go
  pkg/test/internal/tracker.go
Labels: cla: yes

#6874 Moved RBAC CRDs to group rbac.istio.io from config.istio.io
  galley/pkg/kube/types.go
  galley/tools/gen-meta/metadata.yaml
  install/kubernetes/helm/istio/charts/galley/templates/validatingwebhook.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/crds.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/clusterrole.yaml
  mixer/adapter/rbac/operatorconfig/rbac.yaml
  mixer/adapter/rbac/rbac.go
  mixer/pkg/config/crd/init.go
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
  mixer/pkg/config/store/store.go
  mixer/pkg/config/store/store_test.go
  mixer/pkg/runtime/config/validator/validator_test.go
  mixer/pkg/server/server.go
  pilot/pkg/model/config.go
  samples/bookinfo/platform/kube/istio-rbac-details-reviews.yaml
  samples/bookinfo/platform/kube/istio-rbac-namespace.yaml
  samples/bookinfo/platform/kube/istio-rbac-productpage.yaml
  samples/bookinfo/platform/kube/istio-rbac-ratings.yaml
  samples/bookinfo/platform/kube/rbac/details-reviews-policy.yaml
  samples/bookinfo/platform/kube/rbac/namespace-policy.yaml
  samples/bookinfo/platform/kube/rbac/productpage-policy.yaml
  samples/bookinfo/platform/kube/rbac/ratings-policy.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-ON.yaml
  tests/e2e/tests/galley/galley_test.go
  tests/e2e/tests/galley/testdata/rbac-v1alpha1-ServiceRole-invalid.yaml
  tests/e2e/tests/galley/testdata/rbac-v1alpha1-ServiceRole-valid.yaml
  tests/e2e/tests/galley/testdata/rbac-v1alpha1-ServiceRoleBinding-invalid.yaml
  tests/e2e/tests/galley/testdata/rbac-v1alpha1-ServiceRoleBinding-valid.yaml
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-rbac-enable.yaml.tmpl
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-rbac-rules.yaml.tmpl
Labels: cla: yes, lgtm

#7226 Add useful warnings when quota specs do not match
  pilot/pkg/model/authentication.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/model/log.go
  pilot/pkg/model/push_status.go
  pilot/pkg/model/service.go
  pilot/pkg/model/trace.go
Labels: approved, cla: yes

#7232 update envoy sha - fix memory leak
  istio.deps
Labels: approved, cla: yes

#7227 More debug/troubleshooting
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/webhook.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: approved, cla: yes

#7245 Fix istio-remote sidecar-injector-configmap rendered yaml parse error
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
Labels: approved, cla: yes, lgtm

#6960 use read only stop channel
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/monitor/monitor.go
Labels: cla: yes

#7220 Tool to aggregate third party licenses
  tools/license/README.md
  tools/license/get_dep_licenses.go
Labels: approved, cla: yes, lgtm

#7246 add volumeMount for sds socket file in nodeagent
  security/cmd/node_agent_k8s/nodeagent.yaml
Labels: approved, cla: yes, lgtm
