Repository istio/istio, pull requests merged in 2018-12, with the labels that each got.

#10242 Add a user guide to run the demo of a prototype of Istio CA Vault integration
  security/demo/vault/user_guide/cert.pem
  security/demo/vault/user_guide/citadel/istio-citadel-vault-demo.yaml
  security/demo/vault/user_guide/client/node-agent-pod-1.yaml
  security/demo/vault/user_guide/config-environment.sh
  security/demo/vault/user_guide/example-pod-sa.yaml
  security/demo/vault/user_guide/push-citadel.sh
  security/demo/vault/user_guide/push-node-agent.sh
  security/demo/vault/user_guide/vault-cleanup.sh
  security/demo/vault/user_guide/vault-provision.sh
  security/demo/vault/user_guide/vault-start-server.sh
  security/docker/Dockerfile.citadel-vault-test-1
  security/tests/integration/vaultTest/testdata/example-workload-pod-sa.jwt
  security/tests/integration/vaultTest/testdata/reviewer-token.jwt
  tools/istio-docker.mk
Labels: cla: yes

#10241 ADS: remove never match case
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: approved, cla: yes, lgtm

#10149 Configurable format
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: approved, cla: yes

#10249 Remove k8s integration tests from release-1.1
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#10261 Update codecov.threshold and disable pull from master
  Makefile
  codecov.threshold
Labels: approved, cla: yes, lgtm

#10240 fix minProfile test failure and support multiple set values for helm installation
  prow/e2e-simpleTests-minProfile.sh
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#10271 codecov job: git clean before checking out
  bin/codecov_diff.sh
Labels: approved, cla: yes, lgtm

#9656 Permit port to domain validation.
  pilot/pkg/model/validation.go
Labels: approved, cla: yes, lgtm

#10250 Fix broken CNI SHA value
  istio.deps
Labels: cla: yes, lgtm

#10281 Alter Mixer tracing to only generate spans when service tracespan exi…
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pkg/tracing/config.go
  pkg/tracing/config_test.go
  pkg/tracing/options.go
  pkg/tracing/options_test.go
Labels: approved, cla: yes, lgtm

#10275 remove unused values var
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#10265 remove localkube refs from e2e minikube script
  tests/e2e/local/minikube/setup_host.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#10278 Revert "Permit port to domain validation."
  pilot/pkg/model/validation.go
Labels: approved, cla: yes, lgtm

#10306 Add telemetry-gateway subchart to helm requirements (#10178)
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/subcharts/telemetry-gateway/templates/gateway.yaml
Labels: approved, cla: yes, lgtm

#10301 Move EnvoyFilters into networking core
  pilot/pkg/networking/core/v1alpha3/envoyfilter.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/pkg/networking/plugin/registry/registry_test.go
Labels: approved, cla: yes, lgtm

#10257 add token volume mount to gateway
  install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#10325 Make e2e tests use the correct custom helm options when MCP is enabled
  Makefile
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, kind/test failure, lgtm

#9361 Initial code for NetworkScope - filter outbound listener/routes
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/pkg/proxy/envoy/watcher_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes, lgtm

#10158 Support grpc keepalive for pilot
  Gopkg.lock
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pkg/keepalive/options.go
  pkg/test/framework/components/apps/local/agent/pilot_agent_test.go
  pkg/test/framework/components/pilot/local.go
  tests/local/xds_local_test.go
  tests/util/pilot_server.go
  tools/hyperistio/hyperistio.go
Labels: approved, cla: yes, lgtm

#10291 populate complete Envoy bootstrap locality
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/deb/envoy_bootstrap_v2.json
Labels: approved, cla: yes, lgtm

#10090 Changes to make stackdriver e2e run on prow
  tests/e2e/tests/stackdriver/README.md
  tests/e2e/tests/stackdriver/stackdriver_test.go
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#10108 Handle envoy RDS protocol error response - 1.1
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
  pkg/adsc/adsc.go
Labels: approved, cla: yes, lgtm, ok-to-test

#10167 Bugfix: return an error instead of multierr.Prefix
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes, lgtm, ok-to-test

#10328 enable pilot/model linter test
  bin/linters.sh
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service_test.go
  pilot/pkg/model/test/mockopenidserver.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: approved, cla: yes, lgtm

#10321 Update to latest Prometheus to grab critical fix
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
Labels: approved, cla: yes, lgtm

#10343 enable global lint
  bin/linters.sh
  lintconfig_base.json
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/coredatamodel/controller_test.go
  pilot/pkg/config/kube/crd/client.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/config/memory/monitor_test.go
  pilot/pkg/config/monitor/monitor_test.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/webhook_test.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/mem.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/kube/pod.go
  pilot/tools/debug/pilot_cli.go
  pkg/adsc/adsc.go
  pkg/cache/cache_test.go
  pkg/cache/lruCache_test.go
  pkg/cache/ttlCache_test.go
  pkg/ctrlz/topics/collection.go
  pkg/keepalive/options.go
  pkg/mcp/creds/watcher_test.go
  pkg/mcp/server/server.go
  pkg/mcp/snapshot/snapshot.go
  pkg/mcp/snapshot/snapshot_test.go
  pkg/test/application/echo/echo.go
  pkg/test/deployment/util.go
  pkg/test/framework/components/apps/local/apps.go
  pkg/test/framework/components/citadel/kube.go
  pkg/test/framework/environments/kubernetes/implementation.go
Labels: approved, cla: yes, lgtm

#10237 add mixer route config only if mixer exists to improve efficiency
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#10345 update version in charts to 1.0.5
  install/kubernetes/helm/istio-remote/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/security/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio-remote/requirements.yaml
  install/kubernetes/helm/istio/Chart.yaml
  install/kubernetes/helm/istio/charts/certmanager/Chart.yaml
  install/kubernetes/helm/istio/charts/galley/Chart.yaml
  install/kubernetes/helm/istio/charts/gateways/Chart.yaml
  install/kubernetes/helm/istio/charts/grafana/Chart.yaml
  install/kubernetes/helm/istio/charts/ingress/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/mixer/Chart.yaml
  install/kubernetes/helm/istio/charts/pilot/Chart.yaml
  install/kubernetes/helm/istio/charts/prometheus/Chart.yaml
  install/kubernetes/helm/istio/charts/security/Chart.yaml
  install/kubernetes/helm/istio/charts/servicegraph/Chart.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio/charts/telemetry-gateway/Chart.yaml
  install/kubernetes/helm/istio/charts/tracing/Chart.yaml
  install/kubernetes/helm/istio/requirements.yaml
Labels: approved, cla: yes, lgtm

#8975 Add more values to recognized templates to mixer integration test
  mixer/pkg/adapter/test/integration.go
Labels: approved, cla: human-approved, cla: yes, lgtm

#10353 Restore e2e-dashboard test to CircleCI jobs
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#10352 Add stackdriver e2e test script
  prow/e2e-stackdriver.sh
Labels: approved, cla: yes, lgtm

#10355 Update README.md
  README.md
Labels: approved, cla: yes, lgtm

#9787 update consul docker image to 1.3.0
  install/consul/consul_config/agent-loglevel.json
  install/consul/consul_config/agent.json
  install/consul/consul_config/disable_update_check.json
  install/consul/consul_config/server.json
  install/consul/templates/istio.yaml.tmpl
Labels: approved, cla: yes, lgtm, ok-to-test

#10350 Update to prom client_golang to release tag instead of master
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm

#9059 Add flag trustDomain to pilot.
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml
  install/kubernetes/helm/subcharts/ingress/templates/deployment.yaml
  install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml
  install/kubernetes/helm/subcharts/pilot/templates/deployment.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/main_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/memory/discovery_mock.go
Labels: approved, cla: yes, lgtm

#10386 fix testPodCache flaky
  pilot/pkg/serviceregistry/kube/pod_test.go
Labels: approved, cla: yes, lgtm

#10324 Add TCP sentinel metrics to dashboard e2e test
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: approved, cla: yes, lgtm

#9475 Add timeout to remote handler
  mixer/pkg/protobuf/yaml/dynamic/handler.go
  mixer/pkg/protobuf/yaml/dynamic/handler_test.go
  mixer/test/spybackend/args.go
  mixer/test/spybackend/nosession.go
Labels: approved, cla: yes, lgtm

#10379 First round or mutex fixing
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/serviceregistry/kube/cache.go
Labels: approved, cla: yes

#10399 update Istio/API SHA
  Gopkg.lock
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/proto.lock
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#10255 [cherrypick]remove workaround of setting secure naming in node agent, instead set directly in pilot
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: approved, cla: yes, lgtm

#10259 allow envoy process to access token volume file in sidecar
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/mesh.go
Labels: approved, cla: yes, lgtm

#10419 move build trigger files to istio
  release/gcb/trigger_daily_build.sh
  release/gcb/trigger_release.sh
  release/gcb/trigger_test.sh
Labels: approved, cla: yes

#9698 Extend status pkg to expose all grpc status codes
  mixer/pkg/status/status.go
  mixer/pkg/status/status_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#10398 mixer: add toLower for header keys
  mixer/pkg/il/testing/tests.go
  mixer/pkg/lang/ast/expr.go
  mixer/pkg/lang/externs.go
Labels: approved, cla: yes, lgtm

#10418 Fix 1.1.0.snapshot.3 galley failure
  galley/pkg/crd/validation/validation.go
Labels: approved, cla: yes, lgtm

#10403 set meshconfig.sdsUseK8sSaJwt through sds helm value
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#10428 Ensure Docker test registry namespace exists
  tests/e2e/local/vagrant/install_prereqs_macos.sh
  tests/util/localregistry/README.md
  tests/util/localregistry/localregistry.yaml
Labels: approved, cla: yes, lgtm

#10431 add tests to coverage
  codecov.skip
Labels: approved, cla: yes, lgtm

#10439 Remove green sha logic from generate_manifest.sh
  release/gcb/generate_manifest.sh
Labels: approved, cla: yes, lgtm

#10027 Add pilot version string to prom metrics
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes, kind/enhancement, lgtm

#10443 update deployment manager
  install/gcp/deployment_manager/istio-cluster.jinja.schema
  install/gcp/deployment_manager/istio-cluster.yaml
Labels: cla: yes, lgtm

#10449 fix typo in release script
  release/gcb/generate_manifest.sh
Labels: approved, cla: yes

#10448 fix typo in release script
  release/gcb/generate_manifest.sh
Labels: approved, cla: yes

#10447 fix typo in release script
  release/gcb/generate_manifest.sh
Labels: approved, cla: yes, lgtm

#10344 Add helm flags to control the app probe rewrite beahvior.
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  istioctl/cmd/istioctl/kubeinject.go
  pilot/pkg/kube/inject/app_probe.go
  pilot/pkg/kube/inject/app_probe_test.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/inject/hello-probes.yaml.no-rewrite.injected
  pilot/pkg/kube/inject/webhook.go
Labels: approved, cla: yes, lgtm

#10451 get manifest from release tools path
  release/gcb/github_tag_release.sh
Labels: approved, cla: yes

#10452 get manifest from release tools path (#10451)
  release/gcb/github_publish_release.sh
  release/gcb/github_tag_release.sh
Labels: approved, cla: yes

#10308 e2e-mixer- make sure use generate_e2e_test_yaml for e2e-mixer*
  .circleci/config.yml
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#10445 Delete uneeded release files
  prow/upgrade-tests-1.0.1.sh
  prow/upgrade-tests-1.0.2.sh
  release/gcb/build.template.json
  release/gcb/daily_success.template.json
  release/gcb/get_commit.template.json
  release/gcb/github_publish.template.json
  release/gcb/github_tag.template.json
  release/gcb/helm_release.template.json
  release/gcb/release_qualification.template.json
  release/pipeline/OWNERS
  release/pipeline/airflow_scripts.sh
  release/pipeline/configs/environment_config.py
  release/pipeline/dags/istio_common_dag.py
  release/pipeline/dags/istio_common_daily.py
  release/pipeline/dags/istio_daily_master.py
  release/pipeline/dags/istio_daily_release_1_0.py
  release/pipeline/dags/istio_daily_release_1_1.py
  release/pipeline/dags/istio_monthly_dag.py
  release/pipeline/gcb_build_lib.sh
  release/pipeline/operators/gcs_copy_operator.py
  release/pipeline/operators/gcs_hook.py
  release/pipeline/operators/gcs_to_gcs.py
Labels: approved, cla: yes, lgtm

#10460 Optimize: stop informer after galley endpoint ready
  galley/pkg/crd/validation/endpoint.go
Labels: approved, cla: yes, lgtm

#9820 Bug fix: Fixes unmarshal error for expected error in integration test…
  mixer/pkg/adapter/test/integration.go
Labels: approved, cla: yes, lgtm, ok-to-test

#10472 Settings Cherrypick release changes from master to release-1.0
  prow/upgrade-tests-1.0.1.sh
  prow/upgrade-tests-1.0.2.sh
  release/gcb/build.template.json
  release/gcb/daily_success.template.json
  release/gcb/generate_manifest.sh
  release/gcb/get_commit.template.json
  release/gcb/github_publish.template.json
  release/gcb/github_tag.template.json
  release/gcb/modify_values.template.json
  release/gcb/release_qualification.template.json
  release/pipeline/OWNERS
  release/pipeline/airflow_scripts.sh
  release/pipeline/configs/environment_config.py
  release/pipeline/dags/istio_common_dag.py
  release/pipeline/dags/istio_daily_flow.py
  release/pipeline/dags/istio_monthly_flow.py
  release/pipeline/gcb_build_lib.sh
  release/pipeline/operators/gcs_copy_operator.py
  release/pipeline/operators/gcs_hook.py
Labels: approved, cla: yes

#10459 mixerplugin: deprecate attribute_for_mixer_proxy
  mixer/pkg/mockapi/server.go
  mixer/test/client/env/mixer_server.go
  mixer/test/client/env/setup.go
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#10440 Update isolation on config change
  pilot/pkg/model/push_context.go
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: approved, cla: yes, lgtm

#10303 Use in-memory pilot in cf/copilot_test
  Gopkg.lock
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/mcp_test.go
  tests/e2e/tests/pilot/mock/mcp/server.go
  vendor/github.com/onsi/gomega/gbytes/buffer.go
  vendor/github.com/onsi/gomega/gbytes/io_wrappers.go
  vendor/github.com/onsi/gomega/gbytes/say_matcher.go
  vendor/github.com/onsi/gomega/gexec/build.go
  vendor/github.com/onsi/gomega/gexec/exit_matcher.go
  vendor/github.com/onsi/gomega/gexec/prefixed_writer.go
  vendor/github.com/onsi/gomega/gexec/session.go
Labels: approved, cla: human-approved, cla: yes, lgtm

#10471 Cherrypick release changes from master to release-1.1
  prow/upgrade-tests-1.0.1.sh
  prow/upgrade-tests-1.0.2.sh
  release/gcb/build.template.json
  release/gcb/daily_success.template.json
  release/gcb/generate_manifest.sh
  release/gcb/get_commit.template.json
  release/gcb/github_publish.template.json
  release/gcb/github_tag.template.json
  release/gcb/helm_release.template.json
  release/gcb/release_qualification.template.json
  release/pipeline/OWNERS
  release/pipeline/airflow_scripts.sh
  release/pipeline/configs/environment_config.py
  release/pipeline/dags/istio_common_dag.py
  release/pipeline/dags/istio_common_daily.py
  release/pipeline/dags/istio_daily_master.py
  release/pipeline/dags/istio_daily_release_1_0.py
  release/pipeline/dags/istio_daily_release_1_1.py
  release/pipeline/dags/istio_monthly_dag.py
  release/pipeline/gcb_build_lib.sh
  release/pipeline/operators/gcs_copy_operator.py
  release/pipeline/operators/gcs_hook.py
  release/pipeline/operators/gcs_to_gcs.py
Labels: approved, cla: yes, lgtm

#10465 fix bug: return nil
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes, lgtm

#10292 add mixerRouteConfig cache
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#10436 Update codecov check to skip deleted files
  codecov.threshold
  tests/codecov/main.go
  tests/codecov/main_test.go
Labels: approved, cla: yes, lgtm

#10496 Revert "add mixerRouteConfig cache"
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#10421 fix TestCriticalCrdsAreReady race test
  mixer/pkg/config/crd/store_test.go
Labels: approved, cla: yes, lgtm

#10504 fix date race
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#10508 switch to new oauth token exchange interface
  security/pkg/nodeagent/plugin/plugin.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/test/mockserver.go
  security/pkg/nodeagent/sds/server.go
Labels: approved, cla: yes, lgtm

#10458 change fssourcetest to more declarative
  galley/pkg/fs/fssource_test.go
Labels: approved, cla: yes, lgtm

#10522 Don't pick up OS _kubectl_ for _kubectl:e2e_ Docker image
  .gitignore
  docker/Dockerfile.kubectl
Labels: approved, cla: yes, lgtm

#10476 Remove the explicit accesslist file from Galley.
  galley/pkg/server/configmap.go
  galley/pkg/server/configmap_test.go
  install/kubernetes/helm/subcharts/galley/templates/accesslist.yaml.tpl
  install/kubernetes/helm/subcharts/galley/templates/configmap.yaml
  pkg/filewatcher/filewatcher.go
  pkg/filewatcher/filewatcher_test.go
  pkg/mcp/server/listchecker.go
  pkg/mcp/server/listchecker_test.go
Labels: approved, cla: yes, lgtm

#10525 Add adapter tuning install options to helm
  install/kubernetes/helm/subcharts/mixer/templates/clusterrole.yaml
  install/kubernetes/helm/subcharts/mixer/templates/clusterrolebinding.yaml
  install/kubernetes/helm/subcharts/mixer/templates/config.yaml
  install/kubernetes/helm/subcharts/mixer/templates/serviceaccount.yaml
  install/kubernetes/helm/subcharts/mixer/values.yaml
Labels: approved, cla: yes, lgtm

#10526 Fix a broken link in a comment.
  mixer/template/edge/edge.pb.html
  mixer/template/edge/template.proto
  mixer/template/edge/template.yaml
  mixer/template/edge/template_handler.gen.go
  mixer/template/edge/template_handler_service.descriptor_set
  mixer/template/edge/template_handler_service.pb.go
  mixer/template/edge/template_handler_service.proto
  mixer/template/edge/template_proto.descriptor_set
Labels: approved, cla: yes

#10534 Remove permissions check test for fsstore (cherry-pick #9039)
  mixer/pkg/config/store/fsstore_test.go
Labels: approved, cla: yes, lgtm

#10531 mixer: add size function to EL
  mixer/pkg/il/builder.go
  mixer/pkg/il/interpreter/interpreterRun.go
  mixer/pkg/il/interpreter/interpreterRun.got
  mixer/pkg/il/opcode.go
  mixer/pkg/il/testing/tests.go
  mixer/pkg/lang/ast/func.go
  mixer/pkg/lang/compiler/compiler.go
Labels: approved, cla: yes, lgtm

#10527 move to newer urllib3
  samples/bookinfo/src/productpage/requirements.txt
Labels: approved, cla: yes

#10517 pilot-agent clean up
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/pkg/proxy/envoy/watcher_test.go
Labels: approved, cla: yes, lgtm

#10550 Disable galley server if useMCP is false
  install/kubernetes/helm/subcharts/galley/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#10546 remove e2e_simple_auth
  tests/istio.mk
Labels: cla: yes, lgtm

#10480 exclude livenessprobe request in rule,fix k8s livenessprobe is unknown in kiali
  install/kubernetes/helm/subcharts/mixer/templates/config.yaml
  mixer/testdata/config/prometheus.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#10551 move to newer requests and urllibs3
  samples/bookinfo/src/productpage/requirements.txt
Labels: approved, cla: yes, lgtm

#10542 Fixing typo in the Helm chart available parameters
  install/kubernetes/helm/istio/README.md
Labels: approved, cla: yes, lgtm, ok-to-test

#10559 Istio install script: manually set version when api call to get latest fails
  release/downloadIstioCandidate.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#10536 Push the istio-cni to gcr.io
  release/gcb/cloud_builder.sh
Labels: approved, cla: yes, lgtm

#10495 Fix data race during pilot shutdown
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes, lgtm

#10164 add requirements.lock to git ignore file.
  .gitignore
Labels: approved, cla: yes, lgtm

#10404 Add useAdapterCRDs switch
  install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml
  install/kubernetes/helm/subcharts/mixer/values.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#10270 Add build tag metric to pilot, galley, and mixer
  bin/get_workspace_status.sh
  galley/pkg/server/monitoring.go
  install/kubernetes/helm/subcharts/grafana/dashboards/galley-dashboard.json
  install/kubernetes/helm/subcharts/grafana/dashboards/istio-mesh-dashboard.json
  install/kubernetes/helm/subcharts/grafana/dashboards/istio-performance-dashboard.json
  install/kubernetes/helm/subcharts/grafana/dashboards/mixer-dashboard.json
  install/kubernetes/helm/subcharts/grafana/dashboards/pilot-dashboard.json
  install/kubernetes/helm/subcharts/grafana/templates/configmap-dashboards.yaml
  install/kubernetes/helm/subcharts/grafana/templates/deployment.yaml
  install/kubernetes/helm/subcharts/grafana/values.yaml
  istioctl/cmd/istioctl/version_test.go
  mixer/pkg/server/monitoring.go
  pilot/pkg/bootstrap/monitoring.go
  pkg/version/cobra_test.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, cla: yes, lgtm

#10553 Use ingressgateway public IP for K8s Ingress if no legacy ingress
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: approved, cla: yes, lgtm

#10579 increase code coverage of pkg/mcp/server/listchecker.go
  pkg/mcp/server/listchecker_test.go
Labels: approved, cla: yes, lgtm

#10532 Attempt #3 at fixing a bad link in a comment.
  mixer/template/edge/edge.pb.html
  mixer/template/edge/template.proto
  mixer/template/edge/template.yaml
  mixer/template/edge/template_handler.gen.go
  mixer/template/edge/template_handler_service.descriptor_set
  mixer/template/edge/template_handler_service.pb.go
  mixer/template/edge/template_handler_service.proto
  mixer/template/edge/template_proto.descriptor_set
Labels: approved, cla: yes, lgtm

#10363 configure add-ons with https in front
  install/kubernetes/helm/subcharts/gateways/values.yaml
  install/kubernetes/helm/subcharts/grafana/templates/gateway.yaml
  install/kubernetes/helm/subcharts/kiali/templates/gateway.yaml
  install/kubernetes/helm/subcharts/prometheus/templates/gateway.yaml
  install/kubernetes/helm/subcharts/tracing/templates/gateway.yaml
Labels: approved, cla: yes, lgtm

#10567 Enable Citadel to add signing cert to configmap.
  security/cmd/istio_ca/main.go
  security/pkg/k8s/configmap/configmap.go
  security/pkg/k8s/configmap/configmap_test.go
  security/pkg/nodeagent/caclient/client.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
Labels: approved, cla: yes, lgtm

#10590 update CA proto
  security/pkg/nodeagent/caclient/providers/google/client_test.go
  security/proto/providers/google/google.security.istioca.v1alpha1.pb.html
  security/proto/providers/google/istioca.pb.go
  security/proto/providers/google/istioca.proto
  security/proto/providers/google/istioca.proto_descriptor
Labels: approved, cla: yes, lgtm

#10593 update nodeagent google CA client to support new API
  security/pkg/nodeagent/caclient/providers/google/client.go
  security/pkg/nodeagent/caclient/providers/google/client_test.go
Labels: approved, cla: yes, lgtm

#10377 [Kiali][release-1.1] upgrade kiali
  install/kubernetes/helm/subcharts/kiali/Chart.yaml
  install/kubernetes/helm/subcharts/kiali/values.yaml
Labels: approved, cla: yes, lgtm

#10499 Introduce a poll-based cert watcher.
  codecov.threshold
  galley/pkg/server/server.go
  pkg/mcp/creds/create.go
  pkg/mcp/creds/create_test.go
  pkg/mcp/creds/load.go
  pkg/mcp/creds/notifyWatcher.go
  pkg/mcp/creds/notifyWatcher_test.go
  pkg/mcp/creds/options.go
  pkg/mcp/creds/pollingWatcher.go
  pkg/mcp/creds/pollingWatcher_test.go
  pkg/mcp/creds/watcher.go
Labels: approved, cla: yes, lgtm

#10602 CNI release tooling cherry pick
  Makefile
  istio.deps
  prow/e2e-simpleTests-cni.sh
  prow/lib.sh
  prow/release-test.sh
  release/gcb/cloud_builder.sh
  release/gcb/generate_manifest.sh
  release/gcb/github_tag_release.sh
  release/gcb/istio_checkout_code.sh
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#10608 Update codecov.threshold to ignore pkg/test drop
  codecov.threshold
Labels: approved, cla: yes, lgtm

#10609 fix flaky test
  security/pkg/nodeagent/caclient/providers/google/client_test.go
Labels: approved, cla: yes, lgtm

#10607 Enable Citadel to insert TLS root cert into configmap.
  install/kubernetes/helm/subcharts/security/templates/clusterrole.yaml
Labels: approved, cla: yes, lgtm

#10610 Update version to 1.0.6
  install/kubernetes/helm/istio-remote/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/security/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio-remote/requirements.yaml
  install/kubernetes/helm/istio/Chart.yaml
  install/kubernetes/helm/istio/charts/certmanager/Chart.yaml
  install/kubernetes/helm/istio/charts/galley/Chart.yaml
  install/kubernetes/helm/istio/charts/gateways/Chart.yaml
  install/kubernetes/helm/istio/charts/grafana/Chart.yaml
  install/kubernetes/helm/istio/charts/ingress/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/mixer/Chart.yaml
  install/kubernetes/helm/istio/charts/pilot/Chart.yaml
  install/kubernetes/helm/istio/charts/prometheus/Chart.yaml
  install/kubernetes/helm/istio/charts/security/Chart.yaml
  install/kubernetes/helm/istio/charts/servicegraph/Chart.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio/charts/telemetry-gateway/Chart.yaml
  install/kubernetes/helm/istio/charts/tracing/Chart.yaml
  install/kubernetes/helm/istio/requirements.yaml
Labels: approved, cla: yes, lgtm

#10613 add dedicated service account to run nodeagent
  install/kubernetes/helm/subcharts/nodeagent/templates/_helpers.tpl
  install/kubernetes/helm/subcharts/nodeagent/templates/clusterrole.yaml
  install/kubernetes/helm/subcharts/nodeagent/templates/clusterrolebinding.yaml
  install/kubernetes/helm/subcharts/nodeagent/templates/daemonset.yaml
  install/kubernetes/helm/subcharts/nodeagent/templates/serviceaccount.yaml
Labels: approved, cla: yes, lgtm

#10444 White/BlackListing: Change NOT_FOUND return code for a value not whit…
  mixer/adapter/list/list.go
  mixer/adapter/list/list_integration_test.go
  mixer/pkg/protobuf/yaml/dynamic/handler_test.go
  mixer/template/listentry/listEntry.pb.html
  mixer/template/listentry/template.proto
  mixer/template/listentry/template.yaml
  mixer/template/listentry/template_handler.gen.go
  mixer/template/listentry/template_handler_service.descriptor_set
  mixer/template/listentry/template_handler_service.pb.go
  mixer/template/listentry/template_handler_service.proto
  mixer/template/listentry/template_proto.descriptor_set
  mixer/template/template.gen.go
  mixer/test/spybackend/multiple-mix-calls.golden.json
  mixer/test/spybackend/nosession_integration_test.go
Labels: approved, cla: yes, lgtm

#10636 set podspec.securitycontext in auto-sidecar-injection webhook
  pilot/pkg/kube/inject/webhook.go
Labels: approved, cla: yes, lgtm

#10620 refactor pilot server to remove urgly Mutex
  pilot/pkg/bootstrap/server.go
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pkg/test/framework/runtime/components/apps/agent/pilot_agent_test.go
  pkg/test/framework/runtime/components/pilot/native.go
Labels: approved, cla: yes, lgtm

#10654 remove `envoyfilter` plugin name
  pilot/pkg/bootstrap/server.go
  pilot/pkg/networking/plugin/plugin.go
Labels: approved, cla: yes, lgtm

#10652 fix simpleTestsMinProfile
  install/kubernetes/helm/subcharts/pilot/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#10605 add a helm value file to enable sds
  install/kubernetes/helm/istio/values-istio-sds-auth.yaml
Labels: approved, cla: yes, lgtm

#10645 some clean up
  galley/pkg/kube/interfaces.go
  galley/pkg/kube/interfaces_test.go
  galley/pkg/kube/source/listener.go
  galley/pkg/kube/source/source.go
  galley/pkg/runtime/processor.go
  galley/pkg/testing/mock/kube.go
  pkg/mcp/snapshot/snapshot.go
Labels: approved, cla: yes, lgtm

#10574 Fix Galley Server Issues
  galley/pkg/server/server.go
  galley/pkg/server/server_test.go
  pkg/test/framework/runtime/components/galley/native.go
Labels: approved, cla: yes, lgtm

#10370 Correct EnableGrpcTracing value in logging message
  galley/pkg/server/args.go
Labels: approved, cla: yes, lgtm

#10672 Add util functions to authn k8s service account
  Gopkg.lock
  security/pkg/k8s/tokenreview/k8sauthn.go
  security/pkg/k8s/tokenreview/k8sauthn_test.go
Labels: approved, cla: yes, lgtm

#10427 Convert k8s services to Istio service entries in Galley
  galley/pkg/fs/fssource.go
  galley/pkg/fs/fssource_test.go
  galley/pkg/kube/converter/config.go
  galley/pkg/kube/converter/converter.go
  galley/pkg/kube/converter/converter_test.go
  galley/pkg/kube/source/source.go
  galley/pkg/kube/source/source_test.go
  galley/pkg/metadata/kube/types.go
  galley/pkg/metadata/types.go
  galley/pkg/server/server.go
  galley/pkg/server/server_test.go
  galley/tools/gen-meta/metadata.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#10081 feat: additional volumes for sidecar injection configuration
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/testdata/inject/deployment-user-volume.yaml
  pilot/pkg/kube/inject/testdata/webhook/user-volume.yaml
  pilot/pkg/kube/inject/testdata/webhook/user-volume.yaml.injected
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#10657 Enable K8s JWT authentication
  security/pkg/k8s/tokenreview/k8sauthn.go
  security/pkg/k8s/tokenreview/k8sauthn_test.go
  security/pkg/server/ca/authenticate/authenticator.go
  security/pkg/server/ca/authenticate/authenticator_test.go
  security/pkg/server/ca/authenticate/kube_jwt.go
  security/pkg/server/ca/authenticate/kube_jwt_test.go
  security/pkg/server/ca/authorizer.go
  security/pkg/server/ca/authorizer_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: approved, cla: yes, lgtm

#10598 Support define configscope for k8s service
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes, lgtm
