Repository istio/istio, pull requests merged in 2018-11, with the labels that each got.

#9650 Reduce run times of mixer e2e redis quota tests
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#9672 use DNS srv format for istio sni names in mTLS connections
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: approved, cla: yes, lgtm

#9624 Replace `ISTIO_NETWORK` with `NETWORK`
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
Labels: approved, cla: yes

#9681 update google.golang.org/genproto dep
  Gopkg.lock
  security/pkg/nodeagent/plugin/providers/google/iamclient.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/common.pb.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/iamcredentials.pb.go
Labels: approved, cla: yes, lgtm

#9687 Update daily release to copy file to stable location. (#9669)
  release/gcb/rel_daily_complete.sh
Labels: approved, cla: yes, lgtm

#9700 Use official httpbin image (kennethreitz/httpbin)
  samples/httpbin/README.md
  samples/httpbin/httpbin.yaml
Labels: approved, cla: yes, lgtm

#9619 Fix integration tests caused by recent helm change
  codecov.skip
  pkg/test/deployment/helm.go
  prow/istio-integ-k8s-tests.sh
  prow/istio-integ-local-tests.sh
  tests/integration2/tests.mk
Labels: approved, cla: yes, lgtm

#9699 use dns srv format for sni-dnat clusters
  install/kubernetes/helm/subcharts/gateways/values.yaml
  pilot/pkg/model/context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/pkg/networking/plugin/snidnat/snidnat.go
Labels: approved, cla: yes

#9670 filter hosts based on subset labels for ServiceEntry clusters
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: area/networking, cla: yes, lgtm

#9720 Nits on SNI-DNAT: fixing helm, etc.
  install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: cla: yes, lgtm

#9704 Use externalTrafficPolicy: Local for ingress (release-1.1).
  install/kubernetes/helm/subcharts/ingress/templates/service.yaml
  install/kubernetes/helm/subcharts/ingress/values.yaml
Labels: cla: yes

#9559 Rename identity-domain to trust-domain.
  install/kubernetes/helm/subcharts/security/templates/deployment.yaml
  install/kubernetes/helm/subcharts/security/values.yaml
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: approved, cla: yes, lgtm

#9721 Remove reference to helm chart repo on istio.io
  Makefile
  install/kubernetes/helm/istio-remote/requirements.yaml
  install/kubernetes/helm/istio/requirements.yaml
  pkg/test/deployment/helm.go
  release/gcb/helm_charts.sh
Labels: approved, cla: yes, lgtm

#9702 wait for supported resource types to be ready before starting galley
  Gopkg.lock
  galley/cmd/galley/cmd/root.go
  galley/pkg/kube/interfaces.go
  galley/pkg/kube/interfaces_test.go
  galley/pkg/kube/source/init.go
  galley/pkg/kube/source/init_test.go
  galley/pkg/kube/source/source.go
  galley/pkg/kube/source/source_test.go
  galley/pkg/server/args.go
  galley/pkg/server/server.go
  galley/pkg/server/server_test.go
  galley/pkg/testing/mock/kube.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake/clientset_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_customresourcedefinition.go
Labels: approved, cla: yes, lgtm

#9734 code cleanup
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: approved, cla: yes, lgtm

#9718 Add missing resources to kiali cluster role in helm chart (#9608)
  install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml
Labels: cla: yes

#9736 Support fs based MCP configuration
  pilot/pkg/bootstrap/server.go
Labels: approved, cla: yes

#9678 Inject: Encode labels as json similar to annotations (#9634)
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/webhook_test.go
  pkg/bootstrap/bootstrap_config_test.go
Labels: approved, cla: yes, lgtm

#9745 fix config corruption caused by mTLS conversion in dest rule
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#9719 exchange access token with iam service
  security/pkg/nodeagent/plugin/plugin.go
  security/pkg/nodeagent/plugin/providers/google/iamclient.go
  security/pkg/nodeagent/plugin/providers/google/iamclient_test.go
Labels: approved, cla: yes, lgtm

#9677 Re-add Service Graph build to istio-docker.mk
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#9747 sds service reads k8s sa jwt from request header if exists
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: approved, cla: yes, lgtm

#9615 Alter Mixer tracing to only generate spans when service tracespan exists
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/docker/envoy_telemetry.yaml.tmpl
  pkg/tracing/config.go
  pkg/tracing/config_test.go
  pkg/tracing/options.go
  pkg/tracing/options_test.go
Labels: approved, cla: yes, lgtm

#9751 add nodeagent to docker_targets
  tools/istio-docker.mk
Labels: approved, cla: yes, lgtm

#9757 thread authn provider specific plugins into nodeagent
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/plugin/plugin.go
  security/pkg/nodeagent/sds/server.go
Labels: approved, cla: yes, lgtm

#9759 Add a network value to the Istio charts
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9753 Added missing network support in multicluster controllers
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/multicluster.go
  pilot/pkg/config/clusterregistry/multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: approved, cla: yes, lgtm

#9722 enable to enable or disable policy or telemetry
  install/kubernetes/helm/istio/values.yaml
  install/kubernetes/helm/subcharts/mixer/templates/autoscale.yaml
  install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml
  install/kubernetes/helm/subcharts/mixer/templates/service.yaml
  install/kubernetes/helm/subcharts/mixer/templates/serviceaccount.yaml
  install/kubernetes/helm/subcharts/mixer/values.yaml
Labels: approved, cla: yes, lgtm

#9627 set endpoint.LocalityLbEndpoints LoadBalancingWeight
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
Labels: approved, cla: yes

#9766 extend secret TTL to 24hour, add grace period for secret refresh
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
Labels: approved, cla: yes, lgtm

#9772 Switch to pstauffer/curl image (#9637) (#9645)
  samples/sleep/sleep.yaml
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#9767 [release-1.0] Update helm chart version to 1.0.4
  install/kubernetes/helm/istio-remote/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/security/Chart.yaml
  install/kubernetes/helm/istio-remote/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio-remote/requirements.yaml
  install/kubernetes/helm/istio/Chart.yaml
  install/kubernetes/helm/istio/charts/certmanager/Chart.yaml
  install/kubernetes/helm/istio/charts/galley/Chart.yaml
  install/kubernetes/helm/istio/charts/gateways/Chart.yaml
  install/kubernetes/helm/istio/charts/grafana/Chart.yaml
  install/kubernetes/helm/istio/charts/ingress/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/mixer/Chart.yaml
  install/kubernetes/helm/istio/charts/pilot/Chart.yaml
  install/kubernetes/helm/istio/charts/prometheus/Chart.yaml
  install/kubernetes/helm/istio/charts/security/Chart.yaml
  install/kubernetes/helm/istio/charts/servicegraph/Chart.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/Chart.yaml
  install/kubernetes/helm/istio/charts/telemetry-gateway/Chart.yaml
  install/kubernetes/helm/istio/charts/tracing/Chart.yaml
  install/kubernetes/helm/istio/requirements.yaml
Labels: approved, cla: yes, lgtm

#9723 make pilot, mixer, and citadel deployment rollout strategy more robust
  install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml
  install/kubernetes/helm/subcharts/pilot/templates/deployment.yaml
  install/kubernetes/helm/subcharts/security/templates/deployment.yaml
  install/kubernetes/helm/subcharts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#9774 Update OWNERS
  prow/OWNERS
  release/OWNERS
  tests/OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test

#9780 fix typo
  mixer/bin/generate_word_list.py
Labels: cla: yes, lgtm, ok-to-test

#9321 Remove ConfigFetchIntervalSec from mixer args
  mixer/pkg/server/args.go
Labels: approved, cla: yes, lgtm

#9430 fix comments of mcp backend
  mixer/pkg/config/mcp/backend.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#9322 Enhance validation for mixer args
  mixer/pkg/server/args.go
  mixer/pkg/server/args_test.go
Labels: approved, cla: yes, lgtm

#9730 Set load_balancing_weight with a valid value
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  tests/e2e/tests/pilot/mcp_test.go
  tests/util/pilot_server.go
Labels: approved, cla: yes, lgtm

#9651 add token volume mount to sidecar injector
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/mesh.go
  security/pkg/nodeagent/plugin/providers/google/iamclient.go
  security/pkg/nodeagent/plugin/providers/google/iamclient_test.go
Labels: approved, cla: yes, lgtm

#9777 MemRegistry should copy labels from IstioEndpiont.
  pilot/pkg/proxy/envoy/v2/mem.go
Labels: approved, area/security, cla: yes, lgtm

#9795 hack?
  mixer/OWNERS
Labels: approved, cla: yes, lgtm

#9796 Omit security post install on istio-remote
  install/kubernetes/helm/istio-remote/values.yaml
  install/kubernetes/helm/subcharts/security/templates/create-custom-resources-job.yaml
Labels: approved, cla: yes, lgtm

#9775 config trust domain and plugin names for nodeagent
  install/kubernetes/helm/subcharts/nodeagent/templates/daemonset.yaml
  install/kubernetes/helm/subcharts/nodeagent/values.yaml
  security/cmd/node_agent_k8s/main.go
Labels: approved, cla: yes, lgtm

#9673 rework galley dashboard to include new metrics
  install/kubernetes/helm/subcharts/grafana/dashboards/galley-dashboard.json
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: approved, cla: yes, lgtm

#8878 Remove config options for envoy prometheus port
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml
  install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml
  install/kubernetes/helm/subcharts/prometheus/templates/configmap.yaml
  pilot/pkg/kube/inject/mesh.go
  pilot/pkg/kube/inject/testdata/inject/auth.cert-dir.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/auth.non-default-service-account.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/auth.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/cronjob.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/enable-core-dump.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/format-duration.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-always.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-ignore.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-namespace.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-never.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-proxy-override.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-tproxy-debug.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello-tproxy.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/hello.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/job.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/list.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/pod.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/status_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/status_params.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-params-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/traffic-params.yaml.injected
Labels: approved, cla: yes, lgtm

#9808 update istio/api SHA
  Gopkg.lock
  vendor/istio.io/api/.circleci/config.yml
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/README.md
  vendor/istio.io/api/envoy/config/filter/http/authn/v2alpha1/config.pb.go
  vendor/istio.io/api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  vendor/istio.io/api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/mixer/v1/attributes.pb.go
  vendor/istio.io/api/mixer/v1/mixer.pb.go
  vendor/istio.io/api/mixer/v1/mixer.proto
  vendor/istio.io/api/mixer/v1/report.pb.go
  vendor/istio.io/api/mixer/v1/report.proto
  vendor/istio.io/api/mixer/v1/service.pb.go
  vendor/istio.io/api/mixer/v1/service.proto
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/policy/v1beta1/cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/proto.lock
  vendor/istio.io/api/prototool.yaml
  vendor/istio.io/api/prow/api-presubmit.sh
  vendor/istio.io/api/python/istio_api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/mixer_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/report_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/service_pb2.py
  vendor/istio.io/api/python/istio_api/policy/v1beta1/cfg_pb2.py
  vendor/istio.io/api/scripts/pre-commit
  vendor/istio.io/api/tools/all/Dockerfile
  vendor/istio.io/api/tools/all/build-and-push.sh
  vendor/istio.io/api/tools/protoc/Dockerfile
  vendor/istio.io/api/tools/protoc/build-and-push.sh
  vendor/istio.io/api/tools/protolock/Dockerfile
  vendor/istio.io/api/tools/protolock/build-and-push.sh
Labels: approved, cla: yes, lgtm

#9711 fix bug: ConfigUpdate called too many times
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/mem.go
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#9216 define types.BoolValue var in pkg/proto/types.go
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/health/health_test.go
  pkg/proto/types.go
Labels: approved, cla: yes, lgtm

#9740 Cherry-pick #9559: Rename identity-domain to trust-domain.
  install/kubernetes/helm/subcharts/security/templates/deployment.yaml
  install/kubernetes/helm/subcharts/security/values.yaml
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#9807 Replace external link with a local one
  samples/tcp-echo/README.md
Labels: approved, cla: yes

#9584 Watch networks config file for changes
  install/kubernetes/helm/subcharts/pilot/templates/deployment.yaml
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
Labels: cla: yes

#9588 add base path for kiali and jaeger
  install/kubernetes/helm/subcharts/kiali/templates/deployment.yaml
  install/kubernetes/helm/subcharts/kiali/templates/ingress.yaml
  install/kubernetes/helm/subcharts/kiali/values.yaml
  install/kubernetes/helm/subcharts/tracing/templates/deployment.yaml
  install/kubernetes/helm/subcharts/tracing/templates/ingress-jaeger.yaml
  install/kubernetes/helm/subcharts/tracing/values.yaml
Labels: approved, cla: yes, lgtm

#9639 Make sure context is cancelled in various return paths
  pilot/pkg/bootstrap/server.go
Labels: cla: yes

#9727 Fix loadBalancerSourceRanges default value in the helm chart
  install/kubernetes/helm/subcharts/gateways/values.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#9768 remove global enabled flag for mixer
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/crds.yaml
  install/kubernetes/helm/istio/values.yaml
  install/kubernetes/helm/subcharts/gateways/templates/serviceaccount.yaml
  install/kubernetes/helm/subcharts/mixer/templates/autoscale.yaml
  install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml
  install/kubernetes/helm/subcharts/mixer/templates/service.yaml
  install/kubernetes/helm/subcharts/mixer/values.yaml
Labels: approved, cla: yes, lgtm

#9814 Fix the Envoy HTTP Log Format - Add a missing space
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes, lgtm

#9762 [Release 1.1] [Helm] Kiali - support different namespace
  install/kubernetes/helm/subcharts/kiali/templates/configmap.yaml
Labels: cla: yes

#9776 Helm template updates for multicluster with gateways
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/values-istio-multicluster-gateways.yaml
  install/kubernetes/helm/istio/values.yaml
  install/kubernetes/helm/subcharts/gateways/templates/preconfigured.yaml
  install/kubernetes/helm/subcharts/gateways/values.yaml
  install/kubernetes/helm/subcharts/istiocoredns/Chart.yaml
  install/kubernetes/helm/subcharts/istiocoredns/templates/_helpers.tpl
  install/kubernetes/helm/subcharts/istiocoredns/templates/clusterrole.yaml
  install/kubernetes/helm/subcharts/istiocoredns/templates/clusterrolebinding.yaml
  install/kubernetes/helm/subcharts/istiocoredns/templates/configmap.yaml
  install/kubernetes/helm/subcharts/istiocoredns/templates/deployment.yaml
  install/kubernetes/helm/subcharts/istiocoredns/templates/service.yaml
  install/kubernetes/helm/subcharts/istiocoredns/templates/serviceaccount.yaml
  install/kubernetes/helm/subcharts/istiocoredns/values.yaml
Labels: approved, cla: yes, lgtm

#9824 Use scratch base for tcp-echo sample
  samples/tcp-echo/src/Dockerfile
Labels: approved, cla: yes

#9828 add trust domain to config map
  install/kubernetes/helm/istio/templates/configmap.yaml
  pilot/pkg/model/context.go
Labels: approved, cla: yes, lgtm

#9835 adding additional things needed for new kiali features
  install/kubernetes/helm/subcharts/kiali/templates/clusterrole.yaml
Labels: approved, cla: yes, lgtm

#9833 helm: parameterize namespace in dest rule
  install/kubernetes/helm/subcharts/gateways/templates/preconfigured.yaml
Labels: approved, cla: yes, lgtm

#9176 Add support for healthy panic threshold (#4488)
  Gopkg.lock
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  vendor/istio.io/api/.circleci/config.yml
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/README.md
  vendor/istio.io/api/envoy/config/filter/http/authn/v2alpha1/config.pb.go
  vendor/istio.io/api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  vendor/istio.io/api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/mesh/v1alpha1/proxy.pb.go
  vendor/istio.io/api/mesh/v1alpha1/proxy.proto
  vendor/istio.io/api/mixer/v1/attributes.pb.go
  vendor/istio.io/api/mixer/v1/mixer.pb.go
  vendor/istio.io/api/mixer/v1/mixer.proto
  vendor/istio.io/api/mixer/v1/report.pb.go
  vendor/istio.io/api/mixer/v1/report.proto
  vendor/istio.io/api/mixer/v1/service.pb.go
  vendor/istio.io/api/mixer/v1/service.proto
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/policy/v1beta1/cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/policy/v1beta1/istio.policy.v1beta1.pb.html
  vendor/istio.io/api/proto.lock
  vendor/istio.io/api/prototool.yaml
  vendor/istio.io/api/prow/api-presubmit.sh
  vendor/istio.io/api/python/istio_api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/config_pb2.py
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/proxy_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/mixer_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/report_pb2.py
  vendor/istio.io/api/python/istio_api/mixer/v1/service_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/gateway_pb2.py
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/virtual_service_pb2.py
  vendor/istio.io/api/python/istio_api/policy/v1beta1/cfg_pb2.py
  vendor/istio.io/api/scripts/pre-commit
  vendor/istio.io/api/tools/all/Dockerfile
  vendor/istio.io/api/tools/all/build-and-push.sh
  vendor/istio.io/api/tools/protoc/Dockerfile
  vendor/istio.io/api/tools/protoc/build-and-push.sh
  vendor/istio.io/api/tools/protolock/Dockerfile
  vendor/istio.io/api/tools/protolock/build-and-push.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#9793 Update Proxy SHA to 65087d0e
  istio.deps
  mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go
  mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go
  mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go
  mixer/test/client/rbac_permissive_global/rbac_permissive_global_test.go
  mixer/test/client/rbac_permissive_policy/rbac_permissive_policy_test.go
Labels: approved, cla: yes, lgtm

#9841 remove debug info
  pilot/pkg/proxy/envoy/v2/eds_test.go
  tests/e2e/framework/app_manager.go
Labels: cla: yes

#9817 /debug/workloadz handler update
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, cla: yes

#9713 Use ServiceMeta to convey the protocol and other service properties
  Gopkg.lock
  Gopkg.toml
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/consul/conversion_test.go
  vendor/github.com/hashicorp/consul/NOTICE.md
  vendor/github.com/hashicorp/consul/api/acl.go
  vendor/github.com/hashicorp/consul/api/agent.go
  vendor/github.com/hashicorp/consul/api/api.go
  vendor/github.com/hashicorp/consul/api/catalog.go
  vendor/github.com/hashicorp/consul/api/connect.go
  vendor/github.com/hashicorp/consul/api/connect_ca.go
  vendor/github.com/hashicorp/consul/api/connect_intention.go
  vendor/github.com/hashicorp/consul/api/health.go
  vendor/github.com/hashicorp/consul/api/lock.go
  vendor/github.com/hashicorp/consul/api/operator_area.go
  vendor/github.com/hashicorp/consul/api/prepared_query.go
  vendor/github.com/hashicorp/consul/api/semaphore.go
  vendor/github.com/hashicorp/consul/ui-v2/app/styles/components/notice.scss
  vendor/github.com/hashicorp/consul/website/source/api/operator/license.html.md
  vendor/github.com/hashicorp/consul/website/source/docs/commands/license.html.markdown.erb
Labels: approved, cla: yes, lgtm

#9830 fix a typo
  pilot/pkg/model/authentication.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: approved, cla: yes, lgtm

#9832 some clean up and delete not used files
  install/kubernetes/helm/istio/values-istio-auth-mcp.yaml
  install/kubernetes/helm/istio/values-istio-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
  install/kubernetes/helm/istio/values-istio-mcp.yaml
  install/kubernetes/helm/istio/values-istio-multicluster.yaml
  install/kubernetes/helm/istio/values-istio-one-namespace-auth.yaml
  install/kubernetes/helm/istio/values-istio-one-namespace.yaml
  install/kubernetes/helm/istio/values-istio.yaml
  release/create_release_archives.sh
Labels: approved, cla: yes, lgtm

#9850 send ConfigUpdate signal
  pilot/pkg/bootstrap/server.go
Labels: approved, area/networking, cla: yes, lgtm

#9856 rbac: support custom attributes for network filter
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/authz/rbac_test.go
Labels: approved, cla: yes, lgtm

#9853 Fix for EDS delete bug
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/kube/controller.go
  tools/deb/istio-start.sh
Labels: approved, cla: yes, lgtm

#9839 Adding codecov diff between PR and its base.
  .circleci/accounts/istio-github.enc
  .circleci/config.yml
  bin/codecov.sh
  bin/codecov_diff.sh
Labels: approved, cla: yes, lgtm

#9870 Adding "kind/test failure" to stalebot exempt list
  .github/stale.yml
Labels: approved, cla: yes, lgtm

#9862 Fix MCP Legacy Mixer config conversion logic.
  galley/pkg/kube/converter/converter.go
  galley/pkg/kube/converter/converter_test.go
  galley/pkg/kube/source/source.go
  galley/pkg/kube/source/source_test.go
Labels: approved, cla: yes, lgtm

#9868 Adding integration tests to circle periodic
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#9873 Fix MCP Legacy Mixer config conversion logic. (#9862)
  galley/pkg/kube/converter/converter.go
  galley/pkg/kube/converter/converter_test.go
  galley/pkg/kube/source/source.go
  galley/pkg/kube/source/source_test.go
Labels: approved, cla: yes, lgtm

#9877 Additional config fix, for multicluster (crashing)
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/config/clusterregistry/secretcontroller.go
Labels: approved, cla: yes, lgtm

#9883 Fix deadlock: Simplify debounce, remove locking
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: approved, cla: yes, lgtm

#9879 Added envoy's server_name to gateway and ingress sidecar
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#9891 Fix TestAdsClusterUpdate/TestEds flake
  pilot/pkg/proxy/envoy/v2/xds_test.go
Labels: approved, cla: yes, lgtm

#9903 [test-framework] Extending deployment timeouts to match old framework
  pkg/test/deployment/instance.go
  pkg/test/framework/components/apps/kube/deployment.go
  pkg/test/framework/components/ingress/kube.go
  pkg/test/framework/components/mixer/kube.go
  pkg/test/framework/components/mixer/local.go
  pkg/test/framework/components/pilot/kube.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/framework/components/policybackend/local.go
  pkg/test/framework/components/policybackend/policybackend.go
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/environments/kubernetes/flags.go
  pkg/test/framework/environments/kubernetes/implementation.go
  pkg/test/framework/environments/kubernetes/settings.go
  pkg/test/kube/accessor.go
  pkg/test/util/retry.go
  pkg/test/util/retry/retry.go
Labels: approved, cla: yes, lgtm

#9792 relax requirement for unknown fields in json-to-proto decoding
  pilot/pkg/model/context.go
  pilot/pkg/model/conversion.go
  pilot/pkg/model/conversion_test.go
Labels: approved, cla: yes, lgtm

#9893 fix license check tool
  Makefile
  bin/linters.sh
  prow/release-test.sh
  release/gcb/cloud_builder.sh
  tools/license/get_dep_licenses.go
Labels: approved, cla: yes, lgtm

#9911 fix license check tool (#9893)
  Makefile
  bin/linters.sh
  prow/release-test.sh
  release/gcb/cloud_builder.sh
  tools/license/get_dep_licenses.go
Labels: approved, cla: yes, lgtm

#9539 Fix some issues in the Perf Dashboard
  install/kubernetes/helm/subcharts/grafana/dashboards/istio-performance-dashboard.json
Labels: approved, cla: yes, lgtm

#9501 Update README.md
  security/tools/jwt/samples/README.md
Labels: approved, cla: yes, lgtm, stale

#9890 HPA disabled for Telemetry and Policy due naming mismatches (#9881)
  install/kubernetes/README.md
  install/kubernetes/addons/zipkin.yaml.tmpl
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/subcharts/mixer/values.yaml
  install/updateVersion.sh
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/pilot/pilot_test.go
  tests/e2e/tests/pilot/routing_test.go
Labels: approved, cla: yes, lgtm

#9922 Fix excessive mixer cpu usage in release 1.0
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
Labels: approved, cla: yes, lgtm

#9946 Fix excessive mixer cpu usage in release 1.1
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
Labels: approved, cla: yes, lgtm

#9603 Use pool for protobags
  mixer/pkg/api/grpcServer.go
  mixer/pkg/attribute/bag_test.go
  mixer/pkg/attribute/protoBag.go
  mixer/pkg/mockapi/server.go
  mixer/pkg/mockapi/server_test.go
  mixer/pkg/perf/run.go
Labels: approved, cla: yes, lgtm

#9901 [Kiali] [release-1.1] bump up to next version
  install/kubernetes/helm/subcharts/kiali/Chart.yaml
  install/kubernetes/helm/subcharts/kiali/values.yaml
Labels: approved, cla: yes, lgtm

#9947 Adding istioctl and upgrade release qualification
  prow/e2e-suite.sh
  prow/istioctl-tests.sh
  prow/lib.sh
  prow/upgrade-tests.sh
Labels: approved, cla: yes, lgtm

#9896 Make the LB weight normalizer as a filter
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
Labels: approved, cla: yes, lgtm

#9952 Fix pilot panic: concurrent map read/write
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: approved, cla: yes, lgtm

#9953 Fix typo: falta -> fatal
  galley/pkg/crd/validation/validation.go
Labels: approved, cla: yes, lgtm, ok-to-test

#9920 Add istio.io repo
  install/kubernetes/helm/istio/README.md
Labels: approved, cla: yes, lgtm, ok-to-test

#9960 Add minimal istio profile
  install/kubernetes/helm/istio/charts/istio-cni-0.1.0.tgz
  install/kubernetes/helm/istio/values-istio-minimal.yaml
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#9910 Add zipkin deployment option to helm
  install/kubernetes/helm/subcharts/tracing/templates/deployment-jaeger.yaml
  install/kubernetes/helm/subcharts/tracing/templates/deployment-zipkin.yaml
  install/kubernetes/helm/subcharts/tracing/templates/ingress.yaml
  install/kubernetes/helm/subcharts/tracing/templates/service.yaml
  install/kubernetes/helm/subcharts/tracing/values.yaml
Labels: approved, cla: yes, lgtm

#9937 Fix service endpoint address validation
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: approved, cla: yes, lgtm

#9948 clean code
  pilot/pkg/model/push_context.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: approved, cla: yes, lgtm

#9834 helm: parameterize namespace in dest rule
  install/kubernetes/helm/subcharts/gateways/templates/preconfigured.yaml
Labels: approved, cla: yes, lgtm

#9967 Adding istioctl and upgrade release qualification (#9947)
  prow/e2e-suite.sh
  prow/istioctl-tests.sh
  prow/lib.sh
  prow/upgrade-tests.sh
Labels: approved, cla: yes, lgtm

#9969 Adding istioctl and upgrade release qualification (#9947)
  prow/cluster_lib.sh
  prow/e2e-suite.sh
  prow/istioctl-tests.sh
  prow/lib.sh
  prow/mason_lib.sh
  prow/upgrade-tests.sh
Labels: approved, cla: yes

#9977 Adding upgrade tests files to release-1.0 for testing.
  tests/upgrade/templates/fortio-cli.yaml
  tests/upgrade/templates/fortio.yaml
  tests/upgrade/templates/gateway.yaml
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes

#9941 Fix TestAdsClusterUpdate/TestEds flake (#9891)
  pilot/pkg/proxy/envoy/v2/xds_test.go
Labels: approved, cla: human-approved, cla: yes, lgtm

#9936 Dumps the logs from the remote cluster
  tests/e2e/framework/framework.go
Labels: approved, cla: yes, lgtm

#9955 Update dep istio.io/api to release-1.1
  Gopkg.lock
  Gopkg.toml
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/proto.lock
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/service_entry_pb2.py
Labels: approved, cla: yes, lgtm

#9895 Added the networks configuration to the Helm values
  install/kubernetes/helm/istio/templates/networks-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#9966 nominate yossi to install approver
  install/OWNERS
Labels: approved, cla: yes, lgtm

#9909 Enable Json logging configuration option
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: approved, cla: yes, lgtm

#9978 Add zone into stackdriver MR Auto Fill
  mixer/adapter/stackdriver/helper/common.go
Labels: approved, cla: yes, lgtm

#9945 Add response_flags to default metrics and logs
  install/kubernetes/helm/subcharts/mixer/templates/config.yaml
  mixer/testdata/config/attributes.yaml
Labels: approved, cla: yes, lgtm

#9989 Fix destination_service label expression for TCP metrics
  install/kubernetes/helm/subcharts/mixer/templates/config.yaml
Labels: approved, cla: yes, lgtm

#9971 use image tag in post-install job name
  install/kubernetes/helm/subcharts/grafana/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/subcharts/security/templates/cleanup-secrets.yaml
  install/kubernetes/helm/subcharts/security/templates/create-custom-resources-job.yaml
Labels: approved, cla: yes, lgtm

#9914 Add function to create kubeClient for istio CRDs by passing in a restconfig
  pilot/pkg/config/kube/crd/client.go
Labels: approved, cla: no, lgtm, ok-to-test

#9889 Added an istio-remote Helm flag to create the services and endpoints for the mixer
  install/kubernetes/helm/istio-remote/templates/configmap.yaml
  install/kubernetes/helm/istio-remote/templates/endpoints.yaml
  install/kubernetes/helm/istio-remote/templates/service.yaml
Labels: approved, cla: yes, lgtm

#9981 remove unneeded empty lines
  install/kubernetes/helm/istio-remote/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/templates/crds.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#9996 Remove unused helm commands
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#9997 Add upgrade threshold 1.0
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#9886 Split horizon EDS fixes and tests refactoring
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/multicluster.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#9999 remove redundant push
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#10000 Ceremonial PR
  mixer/OWNERS
Labels: approved, cla: yes, lgtm

#9810 Add newline into mixer debug information
  mixer/pkg/attribute/protoBag.go
Labels: approved, cla: yes, lgtm

#10002 fix TestNodeMetadata
  pkg/bootstrap/bootstrap_config_test.go
Labels: cla: yes

#10003 Improve ads test stablity
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pkg/adsc/adsc.go
  tests/util/pilot_server.go
Labels: cla: yes, lgtm

#10005 Resolve helm upgrade failure
  install/kubernetes/helm/istio/charts/galley/templates/validatingwehookconfiguration.yaml.tpl
  install/kubernetes/helm/istio/templates/crds.yaml
Labels: approved, cla: yes, lgtm

#9741 fixs typo: dont -> don't
  install/kubernetes/helm/subcharts/security/templates/enable-mesh-mtls.yaml
  mixer/adapter/solarwinds/internal/appoptics/client_test.go
  mixer/adapter/solarwinds/internal/appoptics/measurements_test.go
  mixer/adapter/solarwinds/internal/papertrail/papertrail_logger_test.go
  mixer/tools/adapterlinter/main_test.go
  release/gcb/generate_manifest.sh
Labels: cla: yes, ok-to-test

#10017 [test-framework] Fix linter errors in prep for 1.1 merge
  pkg/test/application/echo/batch.go
  pkg/test/application/echo/echo.go
  pkg/test/application/echo/protocols.go
  pkg/test/application/echo/server/main.go
  pkg/test/deployment/attrmanifest.go
  pkg/test/deployment/helm.go
  pkg/test/docker/registry/incluster.go
  pkg/test/envoy/envoy.go
  pkg/test/framework/operations.go
  pkg/test/framework/runtime/components/apps/agent/pilot_agent.go
  pkg/test/framework/runtime/components/apps/agent/pilot_agent_test.go
  pkg/test/framework/runtime/components/apps/native.go
  pkg/test/framework/runtime/dependency/manager.go
  pkg/test/framework/runtime/dependency/manager_test.go
  pkg/test/kube/kubectl.go
  pkg/test/util/reserveport/pool.go
Labels: approved, cla: yes, lgtm

#10018 Change floating point compare to integer to avoid bc
  tests/upgrade/test_crossgrade.sh
Labels: cla: yes

#10016 Adding codecov diff script (#9839)
  .circleci/accounts/istio-github.enc
  .circleci/config.yml
  bin/codecov.sh
  bin/codecov_diff.sh
Labels: approved, cla: yes, lgtm

#9907 Add size limits to dump_kubernetes
  tools/dump_kubernetes.sh
Labels: area/test and release, cla: yes, lgtm

#10021 fix unique job name generation with integer tags
  install/kubernetes/helm/subcharts/grafana/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/subcharts/security/templates/cleanup-secrets.yaml
  install/kubernetes/helm/subcharts/security/templates/create-custom-resources-job.yaml
Labels: approved, cla: yes, lgtm

#10028 Additional error checking
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#10031 Fix concurrent hashmap access
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: approved, cla: yes, lgtm

#10035 Completely disable endpoints networks filtering if not set
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#9715 Check config store in args validation
  mixer/pkg/server/args.go
  mixer/pkg/server/args_test.go
  mixer/pkg/server/server.go
Labels: approved, cla: yes, lgtm, ok-to-test

#10026 mixer: fix config corruption due to buffer re-use
  mixer/pkg/protobuf/yaml/encoder.go
  mixer/pkg/runtime/config/ephemeral_test.go
Labels: approved, cla: yes, lgtm

#10032 Update helm README - add gateway & security toggle
  install/kubernetes/helm/istio/README.md
Labels: approved, cla: yes, lgtm, ok-to-test

#9229 ensure closing server when return with error
  mixer/pkg/server/server.go
Labels: approved, cla: yes, lgtm

#10043 Fixes flaky secret controller unit tests
  pkg/kube/secretcontroller/secretcontroller_test.go
Labels: approved, cla: yes, lgtm

#10019 made http-monitoring port configurable for istio control plane
  install/kubernetes/helm/istio/values.yaml
  install/kubernetes/helm/subcharts/galley/templates/deployment.yaml
  install/kubernetes/helm/subcharts/galley/templates/service.yaml
  install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml
  install/kubernetes/helm/subcharts/mixer/templates/service.yaml
  install/kubernetes/helm/subcharts/pilot/templates/deployment.yaml
  install/kubernetes/helm/subcharts/pilot/templates/service.yaml
Labels: approved, cla: yes, lgtm

#10038 Always dump log from upgrade test.
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#10025 add resource usage to galley dashboard
  install/kubernetes/helm/subcharts/grafana/dashboards/galley-dashboard.json
Labels: approved, cla: yes, lgtm

#10052 Add retries to load command
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#10058 Fix upgrade tests in release-1.1.
  tests/upgrade/test_crossgrade.sh
Labels: approved, cla: yes, lgtm

#10060 Add helm charts build to release tarballs
  release/gcb/helm_charts.sh
  release/gcb/helm_release.template.json
  release/gcb/helm_values.sh
  release/pipeline/airflow_scripts.sh
Labels: approved, cla: yes, lgtm

#10009 add a simple test for min profile
  prow/e2e-simpleTests-minprofile.sh
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/mixer/mixer_test.go
  tests/util/helm_utils.go
Labels: approved, cla: yes, lgtm

#10061 mixer: reconcile nondet bug fix between 1.0 and 1.1
  mixer/pkg/protobuf/yaml/encoder.go
  mixer/pkg/runtime/config/ephemeral_test.go
Labels: approved, cla: yes, lgtm
