Repository istio/istio, pull requests merged in 2019-09, with the labels that each got.

#16704 Update istio.io/pkg version
  bin/get_workspace_status.sh
  go.mod
  go.sum
  istioctl/cmd/version_test.go
  tests/binary/binaries_test.go
Labels: cla: yes, size/S

#16691 Deduplicate hosts added to gateway listeners
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: area/networking, cla: yes, ok-to-test, size/L

#16742 Fix data race
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: area/test and release, cla: yes, size/L

#16753 fix flake
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: cla: yes, size/XS

#16744 add vendor in gitignore
  .gitignore
Labels: cla: yes, size/XS

#16675 Change method to determine if branch is dirty
  bin/get_workspace_status.sh
Labels: cla: yes, size/XS

#16752 Control panic, mock namespace
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/add-to-mesh_test.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/remove-from-mesh_test.go
Labels: cla: yes, size/M

#16757 Disply error on failed Dockerfile lint
  scripts/check_dockerfiles.sh
Labels: cla: yes, size/XS

#16759 Add go mod tidy to format
  Makefile
Labels: cla: yes, size/XS

#16679 Remove ENVOY_SHA and API_SHA from Dockerfiles
  bin/init.sh
  pilot/docker/Dockerfile.proxy_debug
  pilot/docker/Dockerfile.proxytproxy
  pilot/docker/Dockerfile.proxyv2
  tools/istio-docker.mk
Labels: cla: yes, size/M

#16766 Typo fix and code clean
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/push_context.go
Labels: area/networking, cla: yes, size/S

#16280 Add 'citadel_' prefix to controller monitoring package metrics
  security/pkg/k8s/controller/monitoring.go
Labels: area/policies and telemetry, area/security, cla: yes, size/S

#15784 Migrate Citadel ca package metrics from prometheus to open census
  security/pkg/server/ca/monitoring.go
  security/pkg/server/ca/server.go
  tests/e2e/tests/dashboard/dashboard_test.go
Labels: cla: yes, size/L

#16719 Fix data races in galley/pkg/config/source
  galley/pkg/config/source/kube/fs/source.go
  galley/pkg/config/testing/fixtures/expect.go
Labels: area/config, cla: yes, size/XS

#16769 Bug fix for initServiceAccount in push_context
  pilot/pkg/model/push_context.go
Labels: area/networking, cherrypick/release-1.2, cherrypick/release-1.3, cla: yes, size/XS

#16770 [release-1.3] Make nodeagent debug endpoint dump cert data in base64
  security/pkg/nodeagent/sds/sdsservice.go
Labels: cla: yes, size/S

#16741 Revert change which dumped node agent cert data in base64
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: area/security, cla: yes, size/S

#16772 [release-1.3] Bug fix for initServiceAccount in push_context
  pilot/pkg/model/push_context.go
Labels: cla: yes, size/XS

#16748 Stop support workload label update
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/mem.go
  pilot/pkg/proxy/envoy/v2/monitoring.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
Labels: area/networking, cla: yes, size/L

#16783 [release-1.3] Revert change which dumped node agent cert data in base64
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: cla: yes, size/S

#16788 [tracing e2e test] Avoid race between destination rule and trace span generation
  tests/integration/telemetry/tracing/clienttracing/client_tracing_test.go
  tests/integration/telemetry/tracing/tracing.go
Labels: cla: yes, size/S

#16789 Add owner for tests/integration/telemetry
  CODEOWNERS
Labels: cla: yes, size/XS

#16683 Bootstrap update for prom filter stats
  Makefile
  go.mod
  go.sum
  istio.deps
  istioctl/cmd/testdata/auth/productpage_config_dump.json
  istioctl/cmd/testdata/describe/ratings-v1-f745cf57b-vfwcv.json
  pkg/bootstrap/bootstrap_config_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/test/framework/components/echo/common/testdata/config_dump.json
  tests/e2e/tests/stackdriver/stackdriver_test.go
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/XXL

#16794 Sync to latest operator master version
  go.mod
  go.sum
Labels: cla: yes, size/XS

#16516 test: unknown destination_container should not fail
  tests/e2e/tests/mixer/mixer_test.go
Labels: area/policies and telemetry, cla: yes, size/XS

#16796 fix codecov for unknown import path
  bin/codecov.sh
Labels: area/test and release, cla: yes, size/XS

#16786 Pilot: only generate passthrough infra with ip versions provided by proxy
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
Labels: cherrypick/release-1.3, cla: yes, size/L

#16746 change istioctl archive directory structure
  release/create_release_archives.sh
Labels: area/test and release, cla: yes, size/XS

#16269 Allow unknown fields in Galley MeshConfig
  galley/pkg/meshconfig/cache.go
  galley/pkg/meshconfig/cache_test.go
  galley/pkg/meshconfig/testdata/meshconfig.json
Labels: area/config, cherrypick/release-1.3, cla: yes, size/M

#16762 generate sha for all istioctl archive
  release/gcb/gcb_lib.sh
Labels: area/test and release, cla: yes, size/S

#16801 Fix golang 1.13 flag parsing in tests
  tests/e2e/tests/kiali/kiali_test.go
  tests/e2e/tests/simple/a_simple_1_test.go
Labels: cla: yes, size/S

#16811 Correct Kiali Annotation in values.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: area/environments, cla: yes, size/XS

#16820 Fix trialing spaces in meshconfig to allow edits
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: cherrypick/release-1.3, cla: yes, size/S

#16822 [release-1.3] Fix trialing spaces in meshconfig to allow edits
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: cla: yes, size/S

#16821 Make sd adapter less verbose on server error
  mixer/adapter/stackdriver/metric/bufferedClient.go
Labels: cherrypick/release-1.2, cherrypick/release-1.3, cla: yes, size/S

#16792 Pilot: add tls_inspector if alpn is used
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: area/networking, cherrypick/release-1.3, cla: yes, size/M

#16804 backport #16786 and #16286
  istioctl/cmd/testdata/auth/productpage_config_dump.json
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pkg/test/framework/components/echo/common/testdata/config_dump.json
Labels: area/networking, cla: yes, size/XXL

#16809 Cherry pick 16691 to release 1.3
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: area/networking, cla: yes, size/L

#16825 Filter out environment variables & metrics in Galley, for collaterals.
  galley/cmd/galley/cmd/root.go
  galley/cmd/galley/cmd/root_test.go
  galley/pkg/envvar/envvars.go
  galley/pkg/server/components/configmap.go
  go.mod
  go.sum
Labels: area/config, cla: yes, size/L

#16803 [release-1.3] Allow unknown fields in Galley MeshConfig
  galley/pkg/meshconfig/cache.go
  galley/pkg/meshconfig/cache_test.go
  galley/pkg/meshconfig/testdata/meshconfig.json
Labels: cla: yes, size/M

#16798 expose the flag for skipping trust domain validation
  pilot/pkg/features/pilot.go
  pilot/pkg/security/authn/v1alpha1/policy_applier.go
  pilot/pkg/security/authn/v1alpha1/policy_applier_test.go
Labels: cherrypick/release-1.3, cla: yes, size/M

#16802 [release-1.3]cherry-pick into 1.3: Add/Remove service from mesh
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/add-to-mesh_test.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/remove-from-mesh.go
  istioctl/cmd/remove-from-mesh_test.go
  istioctl/cmd/root.go
  pilot/pkg/kube/inject/inject.go
Labels: area/user experience, cla: yes, size/XXL

#16829 [release-1.3] Pilot: add tls_inspector if alpn is used
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/M

#16805 zip docker tar after updating the image
  release/gcb/docker_tag_push_lib.sh
Labels: area/test and release, cla: yes, size/XS

#16824 [release-1.3] Make sd adapter less verbose on server error
  mixer/adapter/stackdriver/metric/bufferedClient.go
Labels: cla: yes, size/S

#16839 [release-1.3] expose the flag for skipping trust domain validation
  pilot/pkg/features/pilot.go
  pilot/pkg/security/authn/v1alpha1/policy_applier.go
  pilot/pkg/security/authn/v1alpha1/policy_applier_test.go
Labels: cla: yes, size/M

#16842 Trim trailing spaces in injection template
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
Labels: cherrypick/release-1.3, cla: yes, size/XS

#16841 [release-1.3]modify minimum k8s version for 1.3 release
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/pre-check_test.go
Labels: area/user experience, cla: yes, size/S

#16844 [release-1.3] Trim trailing spaces in injection template
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
Labels: cla: yes, size/XS

#16846 optimize InstancesByPort: not calling getPodByIP twice
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/config/labels/collection.go
  pkg/config/labels/collection_test.go
Labels: area/perf and scalability, cla: yes, size/M

#16392 add `istioctl x create-remote-secret`
  istioctl/cmd/root.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
  pilot/pkg/config/clusterregistry/multicluster_test.go
  pkg/kube/config.go
  pkg/kube/secretcontroller/secretcontroller.go
  pkg/kube/secretcontroller/secretcontroller_test.go
  tests/util/kube_utils.go
Labels: area/environments, area/user experience, cla: yes, size/XL

#16856 Update istio/proxy to include the java h2c upgrade fix.
  istio.deps
Labels: cla: yes, size/XS

#16852 Remove GODEBUG from pilot and mixer
  install/kubernetes/helm/istio/charts/mixer/values.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
Labels: cla: yes, size/XS

#16843 Fix a couple bugs in Galley's meshcfg package.
  galley/pkg/config/meshcfg/fs.go
  galley/pkg/config/meshcfg/fs_test.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#16864 Updated istio.deps with CNI head commit
  istio.deps
Labels: area/networking, cla: yes, size/XS

#16602 add initial authorization v1beta1 support
  pilot/pkg/model/authorization.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/security/authz/policy/helper.go
  pilot/pkg/security/authz/policy/v1alpha1/v1alpha1.go
  pilot/pkg/security/authz/policy/v1alpha1/v1alpha1_test.go
  pilot/pkg/security/authz/policy/v1beta1/v1beta1.go
  pilot/pkg/security/authz/policy/v1beta1/v1beta1_test.go
Labels: area/security, cla: yes, size/XL

#16861 Update proxy SHA
  istio.deps
Labels: cla: yes, size/XS

#16790 Refactor security reach-ability tests
  tests/integration/security/reachability/context.go
  tests/integration/security/reachability/manualmtls/main_test.go
  tests/integration/security/reachability/manualmtls/reachability_test.go
  tests/integration/security/reachability/reachability_test.go
Labels: area/security, area/test and release, cla: yes, size/XL

#16872 [release-1.3] optimize InstancesByPort: not calling getPodByIP twice
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/config/labels/collection.go
  pkg/config/labels/collection_test.go
Labels: cla: yes, size/M

#16840 add remote service certs to tls watches
  pilot/cmd/pilot-agent/main.go
Labels: area/networking, cla: yes, size/M

#16609 Fix mesh expansion
  tools/packaging/common/istio-node-agent-start.sh
  tools/packaging/common/istio-start.sh
Labels: cla: yes, size/M

#16865 Fix istioctl release binary corruption
  release/gcb/gcb_lib.sh
Labels: cla: yes, size/XS

#16847 Disable secureGrpc if sidecar is used for control plane mTLS
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: area/config, area/environments, cla: yes, ok-to-test, size/XS

#16875 [release-1.3] Fix istioctl release binary corruption
  release/gcb/gcb_lib.sh
Labels: cla: yes, size/XS

#16845 Fix headless service issues
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
Labels: cla: yes, size/L

#16605 Fix the deployment error of sleep-vault.yaml
  samples/sleep/sleep-vault.yaml
Labels: area/security, cherrypick/release-1.3, cla: yes, kind/docs, size/XS

#16816 Improve logging for Citadel and Citadel Agent.
  security/pkg/nodeagent/caclient/client.go
  security/pkg/pki/ca/ca.go
  security/pkg/registry/registry.go
Labels: area/security, cla: yes, size/XS

#16882 [release-1.3] add remote service certs to tls watches
  pilot/cmd/pilot-agent/main.go
Labels: cla: yes, size/M

#16812 Don't check hub in istioctl test
  prow/istioctl-tests.sh
Labels: cla: yes, size/XS

#16817 Remove version specific upgrade test
  prow/upgrade-tests-1.1.7.sh
  prow/upgrade-tests.sh
  tests/upgrade/test_crossgrade.sh
Labels: cla: yes, size/M

#16880 headless service feature flag cleanup
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: cla: yes, size/S

#16874 Disable flakey meshcfg tests until they can be rectified.
  galley/pkg/config/meshcfg/fs_test.go
Labels: cla: yes, size/S

#16881 [release-1.3] Disable secureGrpc if sidecar is used for control plane mTLS
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: cla: yes, size/XS

#16833 Combine snapshots for analysis in AnalyzingDistributor
  galley/pkg/config/processing/snapshotter/analyzingdistributor.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  galley/pkg/config/processing/snapshotter/statusupdater.go
  galley/pkg/config/processing/snapshotter/statusupdater_test.go
Labels: area/config, cla: yes, size/L

#16884 [release-1.3] Fix the deployment error of sleep-vault.yaml
  samples/sleep/sleep-vault.yaml
Labels: cla: yes, size/XS

#16859 Add milliseconds duration to dashboard
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-mesh-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-service-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-workload-dashboard.json
Labels: cherrypick/release-1.3, cla: yes, size/M

#16835 Pilot: set protocol detection timeout for inbound to 1s and outbound 100ms
  galley/testdata/conversion/dataset.gen.go
  galley/testdata/conversion/dataset/mesh.istio.io/v1alpha1/meshconfig_expected.json
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pkg/config/mesh/mesh.go
Labels: area/networking, cherrypick/release-1.3, cla: yes, size/S

#16893 [release-1.3] Add milliseconds duration to dashboard
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-mesh-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-service-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-workload-dashboard.json
Labels: cla: yes, size/M

#16894 [release-1.3] hide top-level namespace flags from manifest and profile commands
  istioctl/cmd/root.go
  istioctl/cmd/root_test.go
Labels: cla: yes, size/L

#16863 Configure mesh.sidecarToTelemetrySessionAffinity with existing helm option
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: cherrypick/release-1.2, cherrypick/release-1.3, cla: yes, size/XS

#16896 Pilot: set protocol detection timeout for inbound to 1s and outbound …
  galley/testdata/conversion/dataset.gen.go
  galley/testdata/conversion/dataset/mesh.istio.io/v1alpha1/meshconfig_expected.json
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pkg/config/mesh/mesh.go
Labels: cla: yes, size/S

#16876 Fix Envoy memory consumption when sniffing is enabled
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: area/networking, cla: yes, size/L

#16897 [release-1.3] Configure mesh.sidecarToTelemetrySessionAffinity with existing helm option
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: cla: yes, size/XS

#16888 Sets the svc resolution as it is needed in later processing
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: cla: yes, size/S

#16904 enable protocol sniffing by default in install
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
Labels: cherrypick/release-1.3, cla: yes, size/XS

#16898 [release-1.3] remove EnableHeadlessService env from Pilot.go
  pilot/pkg/features/pilot.go
Labels: cla: yes, size/XS

#16902 [release-1.3] Fix Envoy memory consumption when sniffing is enabled
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/L

#16868 add flag for protocol sniffing for virtual inbound
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
Labels: cla: yes, size/M

#16903 [1.3] Reduce Sprintf usage from route logic
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: cla: yes, size/S

#16823 [release-1.2] Make sd adapter less verbose on server error
  mixer/adapter/stackdriver/metric/bufferedClient.go
Labels: cla: yes, size/S

#16911 [release-1.3] clean up some tests
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
Labels: cla: yes, size/M

#16910 add flag for inbound listener protocol sniffing
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/util/util.go
Labels: cla: yes, size/S

#16908 [release-1.3] enable protocol sniffing by default in install
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
Labels: cla: yes, size/XS

#16906 Update istio/proxy SHA to HEAD of istio/proxy:release-1.3
  istio.deps
Labels: area/test and release, cla: yes, size/XS

#16857 Use galley's namespace as ownerref for the validation webhook config
  galley/pkg/crd/validation/config.go
  galley/pkg/crd/validation/config_test.go
  galley/pkg/crd/validation/webhook_test.go
Labels: area/config, area/environments, cla: yes, size/M

#16879 Fix a bug in eds debug interface
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: cla: yes, ok-to-test, size/XS

#16012 add support for install helm
  bin/init_helm.sh
Labels: cla: yes, ok-to-test, size/S

#16886 Added missing pod annotations parameter to istio charts.
  install/kubernetes/helm/istio/charts/certmanager/values.yaml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/values.yaml
  install/kubernetes/helm/istio/charts/istiocoredns/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/istiocoredns/values.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/values.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/values.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment-jaeger.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment-zipkin.yaml
  install/kubernetes/helm/istio/charts/tracing/values.yaml
Labels: area/environments, area/user experience, cla: yes, ok-to-test, size/M

#16900 Reduce Sprintf usage from route generation
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: cherrypick/release-1.3, cla: yes, size/S

#16927 Bump kubectl to 1.13
  docker/Dockerfile.kubectl
Labels: area/environments, area/user experience, cla: yes, size/XS

#16870 change minimum k8s version
  istioctl/cmd/remove-from-mesh.go
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/pre-check_test.go
Labels: cla: yes, size/S

#16934 [release-1.3] Bump kubectl to 1.13
  docker/Dockerfile.kubectl
Labels: cla: yes, size/XS

#16556 Update the base image versions for bookinfo sample apps
  samples/bookinfo/src/details/Dockerfile
  samples/bookinfo/src/mongodb/Dockerfile
  samples/bookinfo/src/mysql/Dockerfile
  samples/bookinfo/src/productpage/Dockerfile
  samples/bookinfo/src/productpage/requirements.txt
  samples/bookinfo/src/ratings/Dockerfile
  samples/bookinfo/src/reviews/reviews-wlpcfg/Dockerfile
Labels: cherrypick/release-1.3, cla: yes, size/S

#16925 add pdb for citadel.
  install/kubernetes/helm/istio/charts/security/templates/poddisruptionbudget.yaml
Labels: area/environments, cla: yes, size/S

#16938 [release-1.3] Update the base image versions for bookinfo sample apps
  samples/bookinfo/src/details/Dockerfile
  samples/bookinfo/src/mongodb/Dockerfile
  samples/bookinfo/src/mysql/Dockerfile
  samples/bookinfo/src/productpage/Dockerfile
  samples/bookinfo/src/productpage/requirements.txt
  samples/bookinfo/src/ratings/Dockerfile
  samples/bookinfo/src/reviews/reviews-wlpcfg/Dockerfile
Labels: cla: yes, size/S

#16932 Extend http route domains to include *.svc entries
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: area/networking, cla: yes, size/M

#16498 Add sds diagnostic tools to istioctl
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/proxystatus_test.go
  istioctl/cmd/root.go
  istioctl/pkg/kubernetes/sds_client.go
  istioctl/pkg/util/configdump/secret.go
  istioctl/pkg/util/configdump/secret_test.go
  istioctl/pkg/util/configdump/testdata/configdump.json
  istioctl/pkg/util/configdump/util.go
  istioctl/pkg/writer/compare/comparator.go
  istioctl/pkg/writer/compare/sds/sds_comparator.go
  istioctl/pkg/writer/compare/sds/sds_comparator_test.go
  istioctl/pkg/writer/compare/sds/testdata/envoyconfigdumpsds.json
  istioctl/pkg/writer/compare/sds/util.go
  istioctl/pkg/writer/compare/sds/util_test.go
  istioctl/pkg/writer/compare/sds/writer.go
  istioctl/pkg/writer/compare/sds/writer_test.go
  istioctl/pkg/writer/compare/testdata/envoyconfigdump.json
  istioctl/pkg/writer/envoy/configdump/configdump.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: area/security, area/user experience, cla: yes, size/XXL

#16913 Correct the context to use for callback
  tests/integration/security/reachability/context.go
Labels: area/security, area/test and release, cla: yes, size/XS

#16947 Revert "Extend http route domains to include *.svc entries"
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: cla: yes, size/M

#16892 Skip populating destination service host for passthrough and blackhole
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: cherrypick/release-1.3, cla: yes, size/S

#16891 Fix headless service issues (#16845)
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/serviceregistry/consul/conversion.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
Labels: cla: yes, size/L

#16760 Clean up legacy scripts in bin/ and Makefile
  Makefile
  bin/Dockerfile.goimports
  bin/check_links.sh
  bin/envsetup.sh
  bin/istio-proxy-cfg.py
  bin/perfcheck.sh
  bin/testEnvRootMinikube.sh
Labels: cla: yes, size/XXL

#16946 Fix aggregate workload labels response
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
Labels: cherrypick/release-1.3, cla: yes, size/S

#16952 [manual cherrypick] HTTP Sniffing: RDS Perf and bug fix
  pilot/pkg/networking/core/configgen.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: cla: yes, size/L

#16953 [release-1.3] Fix aggregate workload labels response
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
Labels: cla: yes, size/S

#16956 Fix flaky TestGetNodeAgentSecrets unit test
  istioctl/pkg/writer/compare/sds/util_test.go
Labels: cla: yes, size/S

#16951 Add telemetry session affinity
  install/kubernetes/helm/istio/templates/configmap.yaml
Labels: cla: yes, size/XS

#16771 [release-1.2] Bug fix for initServiceAccount in push_context
  pilot/pkg/model/push_context.go
Labels: cla: yes, size/XS

#16964 Stop building with verbose mode
  release/gcb/gcb_lib.sh
Labels: cla: yes, size/XS

#16712 [release-1.2] Fix the missing intermediate CA certs on Citadel TLS service.
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/platform/onprem.go
  security/pkg/probe/controller.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: cla: yes, size/L

#16980 Fix "go generate ..." issues.
  galley/pkg/config/source/kube/fs/source_test.go
  galley/pkg/config/source/kube/inmemory/kubesource_test.go
  galley/pkg/config/source/kube/rt/known_test.go
  galley/pkg/config/testing/data/builtin.gen.go
  galley/pkg/config/testing/data/builtin.go
  galley/pkg/config/testing/data/builtin/get.go
  mixer/adapter/kubernetesenv/config/config.proto_descriptor
  mixer/adapter/kubernetesenv/config/kubernetesenv.yaml
Labels: area/config, cla: yes, size/L

#16991 Disable kiali security
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: cherrypick/release-1.3, cla: yes, size/XS

#16957 Fixes to gateway template environment variables
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/files/injection-template.yaml
Labels: cla: yes, size/S

#16921 HTTP Sniffing: RDS perf & bug fix
  pilot/pkg/networking/core/configgen.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: cla: yes, size/L

#16992 [release-1.3] Disable kiali security
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: cla: yes, size/XS

#16993 Update kiali to v1.4.0
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: cherrypick/release-1.3, cla: yes, size/XS

#16988 Make metrics experimental again
  istioctl/cmd/describe.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/root.go
Labels: cherrypick/release-1.3, cla: yes, size/S

#17001 [release-1.3] Update kiali to v1.4.0
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: cla: yes, size/XS

#17003 Fix policy and telemetry group name in owner file
  CODEOWNERS
Labels: cla: yes, size/XS

#17006 Update istio/proxy SHA to HEAD of istio/proxy:release-1.3
  istio.deps
Labels: area/networking, area/test and release, cla: yes, size/XS

#17014 use kiali 1.4 instead
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: cla: yes, size/XS

#17016 Fix CODEOWNERS typo
  CODEOWNERS
Labels: cla: yes, size/XS

#17020 Make metrics experimental again (#16988)
  istioctl/cmd/describe.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/root.go
Labels: cla: yes, size/S

#17005 Handle empty files during Istio integration test install
  pkg/test/kube/kubectl.go
Labels: cla: yes, size/S

#17002 Pilot: add protocol sniffing flag for inbound listener
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/plugin_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
Labels: area/networking, cherrypick/release-1.3, cla: yes, size/L

#17025 [release-1.3] Pilot: add protocol sniffing flag for inbound listener
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/plugin_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
Labels: cla: yes, size/L

#17021 Capitalize env vars to align with the rest
  go.sum
  install/kubernetes/helm/istio/charts/nodeagent/templates/daemonset.yaml
  install/kubernetes/helm/istio/charts/nodeagent/values.yaml
  install/kubernetes/helm/istio/example-values/values-istio-googleca.yaml
  security/cmd/node_agent_k8s/main.go
Labels: cla: yes, size/S

#17026 fix galley webhook integration test
  tests/integration/galley/webhook/webhook_test.go
Labels: cla: yes, size/M

#16965 Upgrade golangci-lint to v1.18
  .golangci.yml
  galley/pkg/config/event/router.go
  galley/pkg/config/processing/session.go
  galley/pkg/runtime/distributor.go
  galley/pkg/runtime/publish/strategy_test.go
  galley/tools/gen-meta/main.go
  galley/tools/mcpc/main.go
  istioctl/pkg/util/handlers/handlers_test.go
  mixer/adapter/bypass/bypass.go
  mixer/pkg/protobuf/yaml/dynamic/handler_test.go
  mixer/pkg/runtime/lang/lang.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/monitor.go
  pkg/test/framework/components/mixer/native.go
  pkg/test/framework/components/policybackend/client.go
  scripts/run_golangci.sh
  tests/integration/pilot/locality/main_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/util/kube_utils.go
Labels: cla: yes, size/L

#17018 Fix race condition in controller test
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: cla: yes, size/S

#17024 Fix multicluster values name
  tests/e2e/framework/multicluster.go
Labels: cla: yes, size/XS

#17070 Build 1.1.15
  istio.deps
Labels: cla: yes, size/XS

#16994 Add RPS threshold for average latency load-shedding
  mixer/pkg/loadshedding/grpclatency.go
  mixer/pkg/loadshedding/grpclatency_test.go
  mixer/pkg/loadshedding/options.go
  mixer/pkg/loadshedding/options_test.go
  mixer/pkg/loadshedding/throttler.go
Labels: area/policies and telemetry, cla: yes, size/L

#17082 Replace references to 'NameSpace' with the correct 'Namespace'
  pkg/kube/secretcontroller/secretcontroller_test.go
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/tests/integration/certificateRotationTest/certificate_rotation_test.go
  security/tests/integration/istio_ca_cert_rotation_env.go
  security/tests/integration/istio_ca_node_agent_env.go
  security/tests/integration/istio_ca_secret_env.go
  security/tests/integration/secretCreationTest/secret_creation_test.go
Labels: area/security, cla: yes, size/M

#17022 Suppress unsupported port name and missing containerPort with 1.3 sidecar
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/testdata/describe/productpage-v1-7bbd79f8fd-k6j79.json
Labels: cherrypick/release-1.3, cla: yes, size/XXL

#16773 Fix deployment on liveness sample
  samples/health-check/liveness-http-same-port.yaml
  samples/health-check/liveness-http.yaml
Labels: cherrypick/release-1.3, cla: yes, kind/docs

#17073 cluster: use downstream protocol
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/util/util.go
Labels: area/networking, cla: yes, size/L

#17078 Fix spell mistake
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pkg/spiffe/spiffe.go
  pkg/spiffe/spiffe_test.go
Labels: area/security, cla: yes, ok-to-test, size/S

#17090 Mark stats_filter_test as custom setup
  tests/integration/telemetry/stats/prometheus/stats_filter_test.go
Labels: cla: yes, size/XS

#16427 test(mixer): add adapter bypass unit test
  mixer/adapter/bypass/util_test.go
Labels: cla: yes, ok-to-test, size/L
