Repository istio/istio, pull requests merged in 2019-11, with the labels that each got.

#17346 Disable circuit breaking by default
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cherrypick/release-1.4, cla: yes, ok-to-test, size/M

#18537 Add support for reset as a retryable policy
  pkg/config/validation/validation.go
Labels: cla: yes, size/XS

#18514 Test varying number of services for BenchmarkEDS
  pilot/pkg/proxy/envoy/v2/bench_test.go
Labels: cla: yes, size/M

#18164 fix readiness probe inconsistency
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/cmd/pilot-agent/status/ready/probe_test.go
  pilot/cmd/pilot-agent/status/util/server_info.go
  pilot/cmd/pilot-agent/status/util/stats.go
  pilot/cmd/pilot-agent/status/util/stats_test.go
  pilot/cmd/pilot-agent/status/util/util.go
Labels: area/networking, cla: yes, size/L

#18535 Fix sds info in control plane bootstrap
  pilot/cmd/pilot-agent/main.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#18545 [release-1.4] Fix sds info in control plane bootstrap
  pilot/cmd/pilot-agent/main.go
Labels: cla: yes, size/XS

#18543 eds: print resolution as string in log line
  pilot/pkg/model/service.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: area/networking, cla: yes, size/S

#18544 add additional info to timeout logs
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/cmd/pilot-agent/status/ready/probe_test.go
Labels: area/networking, cla: yes, size/XS

#18550 [release-1.4] Disable circuit breaking by default
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, needs-rebase, size/M

#18530 [release-1.4] Pass B3 context to opencensus
  install/gcp/bootstrap/gcp_envoy_bootstrap.json
  install/kubernetes/helm/istio/values.yaml
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/S

#18431 disable SNI-DNAT at ingress gateway by default
  install/kubernetes/helm/istio/charts/gateways/values.yaml
Labels: area/environments, area/perf and scalability, cla: yes, size/S

#18409 [release-1.4] add passthrough filter chain support for v1beta1 authorization policy
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/security/authz/builder/builder.go
  pkg/test/framework/components/echo/kube/deployment.go
  tests/integration/security/rbac_v1beta1_pass_through_test.go
  tests/integration/security/testdata/rbac/v1beta1-pass-through.yaml.tmpl
Labels: cla: yes, size/L

#18518 [release-1.4] GatewayAnalyzer should parse namespace from the gw info in VS first
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_gateways.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
  galley/pkg/config/resource/name.go
Labels: cla: yes, size/M

#17821 pilot: add alpn HTTP filter
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/plugin_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  security/proto/envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  security/proto/envoy/config/filter/http/alpn/v2alpha1/config.proto
  tests/integration/pilot/protocol_sniffing_test.go
  tests/integration/security/rbac_v1beta1_pass_through_test.go
Labels: cherrypick/release-1.4, cla: yes, size/XL

#18091 Sort filterchains for inbound virtual listeners
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
Labels: area/networking, cherrypick/release-1.4, cla: yes, size/XS

#18566 [release-1.4] Sort filterchains for inbound virtual listeners
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
Labels: cla: yes, size/XS

#18520 Support principals in source.principal.
  pilot/pkg/security/authz/builder/integration_test.go
  pilot/pkg/security/authz/builder/testdata/v1alpha1/td-aliases-source-principal-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/td-aliases-source-principal-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/td-aliases-source-principal-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/td-aliases-source-principal-out.yaml
  pilot/pkg/security/authz/model/model.go
  pilot/pkg/security/trustdomain/bundle.go
  pilot/pkg/security/trustdomain/bundle_test.go
  pilot/pkg/security/trustdomain/util.go
Labels: area/security, cherrypick/release-1.4, cla: yes, size/L

#18533 Integration tests for istioctl managing webhooks
  pkg/test/framework/components/istio/kube.go
  pkg/test/kube/accessor.go
  tests/integration/istioctl/versionanalyze/analyze_test.go
  tests/integration/istioctl/versionanalyze/istioctl_test.go
  tests/integration/istioctl/versionanalyze/testdata/reviews-svc.yaml
  tests/integration/istioctl/versionanalyze/testdata/reviews-vs-and-dr.yaml
  tests/integration/istioctl/versionanalyze/testdata/servicerole.yaml
  tests/integration/istioctl/versionanalyze/testdata/servicerolebinding.yaml
  tests/integration/istioctl/webhook/config/galley-webhook.yaml
  tests/integration/istioctl/webhook/config/sidecar-injector-webhook.yaml
  tests/integration/istioctl/webhook/webhook_test.go
Labels: cla: yes, size/L

#18570 update upgrade test script to have --force flag and proper testing versions
  prow/upgrade-tests.sh
  tests/upgrade/test_crossgrade.sh
Labels: cla: yes, size/S

#18571 Update istio/proxy sha
  istio.deps
Labels: cla: yes, size/XS

#18572 Run go format
  pilot/pkg/security/trustdomain/bundle_test.go
Labels: cla: yes, size/XS

#18573 [release-1.4] Update istio/proxy sha
  istio.deps
Labels: cla: yes, size/XS

#18455 Have update crd file be a part of presubmit tests
  Makefile
  Makefile.core.mk
  bin/update_crds.sh
  common/.commonfiles.sha
  install/kubernetes/helm/istio-init/files/crd-all.gen.yaml
Labels: cla: yes, size/M

#18512 Move golden output files to test_mode specific directories
  tests/scripts/istio-iptables-test.sh
  tests/scripts/testdata/golang/clean_golden.txt
  tests/scripts/testdata/golang/empty_parameter_golden.txt
  tests/scripts/testdata/golang/mode_redirect_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_golden.txt
  tests/scripts/testdata/golang/outbound_port_exclude_golden.txt
  tests/scripts/testdata/golang/wildcard_include_ip_range_golden.txt
  tests/scripts/testdata/golang_clean/clean_golden.txt
  tests/scripts/testdata/golang_clean/empty_parameter_golden.txt
  tests/scripts/testdata/golang_clean/mode_redirect_golden.txt
  tests/scripts/testdata/golang_clean/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/golang_clean/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/golang_clean/mode_tproxy_golden.txt
  tests/scripts/testdata/golang_clean/outbound_port_exclude_golden.txt
  tests/scripts/testdata/golang_clean/wildcard_include_ip_range_golden.txt
  tests/scripts/testdata/script/clean_golden.txt
  tests/scripts/testdata/script/empty_parameter_golden.txt
  tests/scripts/testdata/script/mode_redirect_golden.txt
  tests/scripts/testdata/script/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/script/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/script/mode_tproxy_golden.txt
  tests/scripts/testdata/script/outbound_port_exclude_golden.txt
  tests/scripts/testdata/script/wildcard_include_ip_range_golden.txt
  tests/scripts/testdata/script_clean/clean_golden.txt
  tests/scripts/testdata/script_clean/empty_parameter_golden.txt
  tests/scripts/testdata/script_clean/mode_redirect_golden.txt
  tests/scripts/testdata/script_clean/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/script_clean/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/script_clean/mode_tproxy_golden.txt
  tests/scripts/testdata/script_clean/outbound_port_exclude_golden.txt
  tests/scripts/testdata/script_clean/wildcard_include_ip_range_golden.txt
Labels: area/networking, area/test and release, cla: yes, ok-to-test, size/XXL

#18582 Unified style
  tests/local/xds_local_test.go
Labels: cla: yes, ok-to-test, size/XS

#18426 Improve ads request processing
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/util/sets/string.go
  pilot/pkg/util/sets/string_test.go
Labels: area/networking, cla: yes, size/L

#18497 Fix delete istio-operator namespace error
  tests/e2e/framework/kubernetes.go
Labels: cla: yes, size/XS

#18585 Update release-builder
  prow/release-commit.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#18559 [1.2] Backport changes to prevent proxy startup race condition
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pkg/features/pilot/pilot.go
Labels: cla: yes, size/S

#18407 Improve root cert rotation
  security/cmd/istio_ca/main.go
  security/pkg/k8s/configmap/configmap.go
  security/pkg/k8s/configmap/configmap_test.go
  security/pkg/k8s/controller/casecret.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
Labels: area/security, cherrypick/release-1.4, cla: yes, size/XL

#18602 release-1.4 trust domain migration cherry-picks
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/security/authz/builder/integration_test.go
  pilot/pkg/security/authz/builder/testdata/v1alpha1/all-fields-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/all-fields-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-td-aliases-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-td-aliases-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-*-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-*-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/td-aliases-source-principal-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/td-aliases-source-principal-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/all-fields-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/all-fields-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/allow-all-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/allow-all-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/deny-all-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/deny-all-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/multiple-policies-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/multiple-policies-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/not-override-v1alpha1-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/not-override-v1alpha1-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/override-v1alpha1-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/override-v1alpha1-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-multiple-td-aliases-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-multiple-td-aliases-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-principal-with-*-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-principal-with-*-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-td-aliases-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-td-aliases-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/single-policy-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/single-policy-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/td-aliases-source-principal-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/td-aliases-source-principal-out.yaml
  pilot/pkg/security/authz/converter/converter.go
  pilot/pkg/security/authz/model/model.go
  pilot/pkg/security/authz/model/model_test.go
  pilot/pkg/security/authz/model/util.go
  pilot/pkg/security/authz/model/util_test.go
  pilot/pkg/security/authz/policy/helper.go
  pilot/pkg/security/authz/policy/v1alpha1/v1alpha1.go
  pilot/pkg/security/authz/policy/v1alpha1/v1alpha1_test.go
  pilot/pkg/security/authz/policy/v1beta1/v1beta1.go
  pilot/pkg/security/authz/policy/v1beta1/v1beta1_test.go
  pilot/pkg/security/trustdomain/bundle.go
  pilot/pkg/security/trustdomain/bundle_test.go
  pilot/pkg/security/trustdomain/util.go
Labels: cla: yes, size/XXL

#18608 - Add new beta pattern to the exclusion list
  release/downloadIstioCandidate.sh
Labels: area/environments, area/test and release, cla: yes, size/XS

#18603 [release-1.4] Partial cherry pick of #18455 to pick up latest common-files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#18599 [release-1.4] Lightweight testing of operator cli
  tests/integration/tests.mk
Labels: cla: yes, size/S

#18604 rebuild docker image
  Makefile.core.mk
Labels: cla: yes, size/XS

#18541 Add fallthrough listener filer chain for BlackHoleCluster
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/L

#18617 Bump operator dependency
  go.mod
  go.sum
Labels: cla: yes, size/XS

#18492 Cherry pick root cert auto rotation
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/values.yaml
  security/cmd/istio_ca/main.go
  security/pkg/caclient/keycertbundlerotator.go
  security/pkg/cmd/constants.go
  security/pkg/k8s/configmap/configmap.go
  security/pkg/k8s/configmap/configmap_test.go
  security/pkg/k8s/controller/casecret.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
  security/pkg/k8s/secret/secret_util.go
  security/pkg/k8s/secret/secret_util_test.go
  security/pkg/nodeagent/vm/nodeagent.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
  security/pkg/pki/error/error.go
  security/pkg/pki/error/error_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/probe/controller.go
  security/pkg/probe/controller_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
  security/pkg/util/certutil.go
  security/pkg/util/certutil_test.go
  security/pkg/util/mock/fakecertutil.go
  tests/integration/security/file_mount_mtls_root_cert_auto_rotation/citadel_root_cert_auto_rotation_test.go
  tests/integration/security/file_mount_mtls_root_cert_auto_rotation/file_mount_mtls_test.go
  tests/integration/security/file_mount_mtls_root_cert_auto_rotation/main_test.go
Labels: area/security, cla: yes, size/XXL

#18616 Add retry to protoc.sh
  bin/protoc.sh
Labels: area/test and release, cla: yes, size/S

#18601 [release-1.4] Improve root cert rotation
  security/cmd/istio_ca/main.go
  security/pkg/k8s/configmap/configmap.go
  security/pkg/k8s/configmap/configmap_test.go
  security/pkg/k8s/controller/casecret.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
Labels: cla: yes, size/XL

#18579 Workaround nondeterministic linting
  Makefile.core.mk
Labels: cla: yes, size/XS

#18619 [release-1.4] Add fallthrough listener filer chain for BlackHoleCluster
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: cla: yes, size/L

#18595 [release-1.4] Update release-builder
  prow/release-commit.sh
Labels: cla: yes, size/XS

#18591 rename test file
  pilot/pkg/security/authz/builder/integration_test.go
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-wildcard-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-wildcard-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-principal-with-wildcard-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-principal-with-wildcard-out.yaml
Labels: cla: yes, size/XS

#18269 Remove normalization for LoadBalancingWeight
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
Labels: area/networking, cla: yes, size/M

#18626 Bump operator dependency
  go.mod
  go.sum
Labels: cla: yes, size/XS

#18589 eds: reduce locks while updating eds clusters
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: area/networking, cla: yes, size/M

#18568 fix create-remote-secret's default service account name
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/remote_secret.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#18581 move to drain listeners admin endpoint
  pilot/docker/Dockerfile.proxy_debug
  pilot/docker/Dockerfile.proxytproxy
  pilot/docker/Dockerfile.proxyv2
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pkg/envoy/admin.go
  pkg/envoy/agent.go
  pkg/envoy/agent_test.go
  pkg/envoy/instance.go
  pkg/envoy/proxy.go
  pkg/test/echo/docker/Dockerfile.app_sidecar
  tools/istio-docker.mk
  tools/packaging/common/envoy_bootstrap_drain.json
  tools/packaging/deb/istio.mk
  tools/packaging/rpm/proxy/istio-proxy.spec
Labels: area/networking, cla: yes, size/L

#18628 Remove repeated judgment condition in poddisruptionbudget template
  install/kubernetes/helm/istio/charts/certmanager/templates/poddisruptionbudget.yaml
  install/kubernetes/helm/istio/charts/galley/templates/poddisruptionbudget.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/poddisruptionbudget.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/poddisruptionbudget.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/poddisruptionbudget.yaml
  install/kubernetes/helm/istio/charts/security/templates/poddisruptionbudget.yaml
Labels: cla: yes, size/S

#18629 [release-1.4] fix create-remote-secret's default service account name
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/remote_secret.go
Labels: cla: yes, size/XS

#18635 fix waterch_test failed in windows
  pkg/test/env/istio.go
Labels: area/policies and telemetry, area/test and release, cla: yes, ok-to-test, size/XS

#18609 Fix minor type in pilot agent logs
  pilot/cmd/pilot-agent/status/util/stats.go
Labels: cla: yes, size/XS

#18600 Add analyzers for Sidecar workload selectors
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/sidecar/defaultselector.go
  galley/pkg/config/analysis/analyzers/sidecar/selector.go
  galley/pkg/config/analysis/analyzers/sidecar/util.go
  galley/pkg/config/analysis/analyzers/testdata/sidecar-default-selector.yaml
  galley/pkg/config/analysis/analyzers/testdata/sidecar-selector.yaml
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/config, cla: yes, size/L

#18606 Support multiple access rules
  istioctl/cmd/auth_test.go
  istioctl/cmd/testdata/auth/converter/multiple-access-rules-one-subject.golden.yaml
  istioctl/cmd/testdata/auth/converter/multiple-access-rules-two-subjects.golden.yaml
  istioctl/cmd/testdata/auth/converter/multiple-access-rules.yaml
  pilot/pkg/security/authz/converter/converter.go
Labels: cherrypick/release-1.4, cla: yes, size/L

#18627 Guard pilot debug api against indefinite locks
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: cla: yes, size/XS

#18474 Clean up legacy Discovery v1 server
  go.mod
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/proxy/envoy/discovery.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pkg/istiod/common.go
  pkg/istiod/pilotstart.go
  pkg/test/framework/components/pilot/native.go
  tests/local/xds_local_test.go
  tests/util/pilot_server.go
  tools/hyperistio/hyperistio.go
Labels: cla: yes, size/L

#18653 Updating common-files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#18669 Fix protoc.sh to output retry logging on stderr
  bin/protoc.sh
Labels: area/test and release, cla: yes, size/XS

#18673 Updating common-files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#18354 xDS push optimize
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_common.go
  pilot/pkg/proxy/envoy/v2/ads_common_test.go
Labels: area/networking, cla: yes, size/L

#18677 [release-1.4] Remove normalization for LoadBalancingWeight
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
Labels: cla: yes, size/M

#18574 eds: do not trigger continuous full pushes when a pod is in crash loop
  pilot/pkg/config/coredatamodel/syntheticserviceentrycontroller.go
  pilot/pkg/config/coredatamodel/syntheticserviceentrycontroller_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/mem.go
  pilot/pkg/proxy/envoy/v2/monitoring.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: area/networking, cla: yes, size/L

#18592 add collector endpoint version for zipkin
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: area/networking, cla: yes, size/S

#18682 [1.3] Disable yamllint
  bin/linters.sh
Labels: cla: yes, size/XS

#18679 fix readiness probe regression
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/cmd/pilot-agent/status/ready/probe_test.go
  pilot/cmd/pilot-agent/status/util/stats.go
Labels: area/networking, cla: yes, size/S

#18526 [release-1.3] disable protocol detection timeout for gateway (#18463)
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes, size/XS

#18587 Fix istio/operator tagging
  release/gcb/gcb_lib.sh
Labels: cla: yes, size/XS

#18353 [release-1.3] Donot gen outbound listener to the instance itself for tcp headless service
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/XS

#18691 [release-1.4] Switch istio/proxy to the release-1.4 branch.
  istio.deps
Labels: cla: yes, size/XS

#18686 [release-1.4] rename test file (cherry-pick #18591)
  pilot/pkg/security/authz/builder/integration_test.go
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-wildcard-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-wildcard-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-principal-with-wildcard-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/simple-policy-principal-with-wildcard-out.yaml
Labels: cla: yes, size/XS

#18687 envoy api update
  go.mod
  go.sum
Labels: cla: yes, size/XS

#18696 Bump operator dependency
  go.mod
  go.sum
Labels: cla: yes, size/XS

#18540 [1.3] Reject HTTP listeners on port 443 (#17515)
  pilot/pkg/features/pilot.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/M

#18659 [release-1.4] Support multiple access rules
  istioctl/cmd/auth_test.go
  istioctl/cmd/testdata/auth/converter/multiple-access-rules-one-subject.golden.yaml
  istioctl/cmd/testdata/auth/converter/multiple-access-rules-two-subjects.golden.yaml
  istioctl/cmd/testdata/auth/converter/multiple-access-rules.yaml
  pilot/pkg/security/authz/converter/converter.go
Labels: cla: yes, size/L

#18666 turn on protocol sniffing for inbound
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  pilot/pkg/features/pilot.go
Labels: area/networking, cla: yes, size/XS

#18400 [1.3] Fix stale endpoints on scale to zero
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: cla: yes, size/S

#18536 [1.3] Recover panics from patching envoyfilters (#17292)
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: cla: yes, size/L

#18674 Add analyzer rules for VirtualService destination ports
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/config, cla: yes, size/L

#18588 Cherry pick root cert auto rotation
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/values.yaml
  security/cmd/istio_ca/main.go
  security/pkg/caclient/keycertbundlerotator.go
  security/pkg/cmd/constants.go
  security/pkg/k8s/configmap/configmap.go
  security/pkg/k8s/configmap/configmap_test.go
  security/pkg/k8s/controller/casecret.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
  security/pkg/k8s/secret/secret_util.go
  security/pkg/k8s/secret/secret_util_test.go
  security/pkg/nodeagent/vm/nodeagent.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
  security/pkg/pki/error/error.go
  security/pkg/pki/error/error_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/generate_csr.go
  security/pkg/probe/controller.go
  security/pkg/probe/controller_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
  security/pkg/util/certutil.go
  security/pkg/util/certutil_test.go
  security/pkg/util/mock/fakecertutil.go
  tests/integration/security/file_mount_mtls_root_cert_auto_rotation/citadel_root_cert_auto_rotation_test.go
  tests/integration/security/file_mount_mtls_root_cert_auto_rotation/file_mount_mtls_test.go
  tests/integration/security/file_mount_mtls_root_cert_auto_rotation/main_test.go
  tests/integration/security/file_mount_mtls_root_cert_auto_rotation/multiple_citadel_root_rotation_test.go
Labels: area/security, cla: yes, size/XXL

#18703 Remove a log message from Citadel agent.
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
Labels: area/security, cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/XS

#18697 move grafana to latest
  install/kubernetes/helm/istio/charts/grafana/values.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#18706 [release-1.4] Remove a log message from Citadel agent.
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
Labels: cla: yes, size/XS

#18705 [release-1.3] Remove a log message from Citadel agent.
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
Labels: cla: yes, size/XS

#18620 Add fallthrough listener filer chain for BlackHoleCluster (#18541)
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: cla: yes, size/L

#18717 fix(mixer plugin): do not add HTTP filter when check and report disabled
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
Labels: area/policies and telemetry, cla: yes, size/L

#18719 [release-1.4] Allow user to specify threshold for exit code 79
  galley/pkg/config/analysis/diag/level.go
  istioctl/cmd/analyze.go
Labels: cla: yes, size/M

#18713 Skip syncing root cert if not in self signed CA mode
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: area/security, cherrypick/release-1.2, cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/M

#18725 Run make format
  security/pkg/k8s/controller/workloadsecret.go
Labels: cla: yes, size/S

#18723 [release-1.3] Skip syncing root cert if not in self signed CA mode
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: area/security, cla: yes, size/M

#18709 [release-1.4] move grafana to latest
  install/kubernetes/helm/istio/charts/grafana/values.yaml
Labels: cla: yes, size/XS

#18715 Fix gen-check flakes
  bin/protoc.sh
Labels: cla: yes, size/S

#18721 [release-1.4] fix(mixer plugin): do not add HTTP filter when check and report disabled
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
Labels: cla: yes, size/L

#18722 [release-1.4] Skip syncing root cert if not in self signed CA mode
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: cla: yes, size/M

#18716 Add new operator annotations to the analyze whitelist
  galley/pkg/config/analysis/analyzers/annotations/annotations.go
  go.mod
  go.sum
Labels: area/config, cherrypick/release-1.4, cla: yes, size/M

#18685 readiness revert to update status stats
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/cmd/pilot-agent/status/ready/probe_test.go
  pilot/cmd/pilot-agent/status/util/stats.go
Labels: area/networking, cla: yes, size/L

#18733 Update istio/proxy SHA to HEAD of istio/proxy:release-1.3
  istio.deps
Labels: area/networking, area/test and release, cla: yes, size/XS

#18738 Bump operator and proxy dependencies
  go.mod
  go.sum
  istio.deps
Labels: cla: yes, size/S

#18734 Use variables to render envoy telemetry template
  pilot/docker/envoy_telemetry.yaml.tmpl
Labels: area/config, area/policies and telemetry, cla: yes, size/S

#18710 Fix nil stackdriver environment variables
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/files/injection-template.yaml
Labels: area/policies and telemetry, cla: yes, size/S

#18667 rename istioctl auth to authz to focus on authorization
  istioctl/cmd/auth_test.go
  istioctl/cmd/authz.go
  istioctl/cmd/authz_test.go
  istioctl/cmd/root.go
  istioctl/cmd/testdata/auth/productpage.golden
  istioctl/cmd/testdata/authz/authz-policy.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-exclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-exclusion.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-inclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-inclusion.yaml
  istioctl/cmd/testdata/authz/converter/empty.yaml
  istioctl/cmd/testdata/authz/converter/group-in-subject.yaml
  istioctl/cmd/testdata/authz/converter/istio-configmap.yaml
  istioctl/cmd/testdata/authz/converter/multiple-access-rules-one-subject.golden.yaml
  istioctl/cmd/testdata/authz/converter/multiple-access-rules-two-subjects.golden.yaml
  istioctl/cmd/testdata/authz/converter/multiple-access-rules.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services-with-exclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services-with-inclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-multiple-services.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-multiple-services.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-one-service.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-one-service.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-two-services-prefix-suffix.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-two-services-prefix-suffix.yaml
  istioctl/cmd/testdata/authz/converter/one-subject.yaml
  istioctl/cmd/testdata/authz/converter/rbac-global-on.golden.yaml
  istioctl/cmd/testdata/authz/converter/rbac-global-on.yaml
  istioctl/cmd/testdata/authz/converter/svc-bookinfo.yaml
  istioctl/cmd/testdata/authz/converter/svc-other.yaml
  istioctl/cmd/testdata/authz/converter/svc-prefix-suffix.yaml
  istioctl/cmd/testdata/authz/converter/two-subjects.yaml
  istioctl/cmd/testdata/authz/notfound-role-in-binding.yaml
  istioctl/cmd/testdata/authz/productpage.golden
  istioctl/cmd/testdata/authz/productpage_config_dump.json
  istioctl/cmd/testdata/authz/unused-role.yaml
  istioctl/pkg/auth/cluster.go
  istioctl/pkg/auth/testdata/validator/notfound-role-in-binding.yaml
  istioctl/pkg/auth/testdata/validator/rbac-policies.yaml
  istioctl/pkg/auth/testdata/validator/service-entry.yaml
  istioctl/pkg/auth/testdata/validator/unused-role.yaml
  istioctl/pkg/auth/validator.go
  istioctl/pkg/auth/validator_test.go
  istioctl/pkg/authz/analyzer.go
  istioctl/pkg/authz/listener.go
  istioctl/pkg/authz/testdata/binding-ns-default-user-foo.yaml
  istioctl/pkg/authz/util.go
Labels: area/security, area/user experience, cherrypick/release-1.4, cla: yes, size/XXL

#18745 [release-1.4] Adding ServiceRoleServicesAnalyzer
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/auth/serviceroleservices.go
  galley/pkg/config/analysis/analyzers/testdata/serviceroleservices.yaml
  galley/pkg/config/analysis/analyzers/util/hosts.go
  galley/pkg/config/analysis/analyzers/util/hosts_test.go
Labels: cla: yes, size/L

#18701 Set exit code when analyze cannot parse files
  istioctl/cmd/analyze.go
  istioctl/cmd/sysexits.go
Labels: area/user experience, cherrypick/release-1.4, cla: yes, size/M

#18748 [release-1.4] Allow failures in kind cleanup and log
  prow/lib.sh
Labels: cla: yes, size/XS

#18753 [release-1.3] Add RPS threshold for average latency load-shedding
  mixer/pkg/loadshedding/grpclatency.go
  mixer/pkg/loadshedding/grpclatency_test.go
  mixer/pkg/loadshedding/options.go
  mixer/pkg/loadshedding/options_test.go
  mixer/pkg/loadshedding/throttler.go
Labels: cla: yes, size/L

#18652 improve wait io
  istioctl/cmd/wait.go
  istioctl/cmd/wait_test.go
Labels: area/user experience, cla: yes

#18751 [release-1.4] Check wildcards when trying to match VS to ServiceEntries, fixes #17976
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/auth/serviceroleservices.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
  galley/pkg/config/analysis/analyzers/util/hosts.go
  galley/pkg/config/analysis/analyzers/util/hosts_test.go
  galley/pkg/config/analysis/analyzers/virtualservice/conflictingmeshgatewayhosts.go
  galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
Labels: cla: yes, size/L

#18444 Add its own service account for httpbin
  samples/httpbin/httpbin.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#18744 [release-1.4] rename istioctl auth to authz to focus on authorization
  istioctl/cmd/auth_test.go
  istioctl/cmd/authz.go
  istioctl/cmd/authz_test.go
  istioctl/cmd/root.go
  istioctl/cmd/testdata/auth/productpage.golden
  istioctl/cmd/testdata/authz/authz-policy.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-exclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-exclusion.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-inclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/cluster-rbac-config-on-with-inclusion.yaml
  istioctl/cmd/testdata/authz/converter/empty.yaml
  istioctl/cmd/testdata/authz/converter/group-in-subject.yaml
  istioctl/cmd/testdata/authz/converter/istio-configmap.yaml
  istioctl/cmd/testdata/authz/converter/multiple-access-rules-one-subject.golden.yaml
  istioctl/cmd/testdata/authz/converter/multiple-access-rules-two-subjects.golden.yaml
  istioctl/cmd/testdata/authz/converter/multiple-access-rules.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services-with-exclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services-with-inclusion.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-all-services.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-multiple-services.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-multiple-services.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-one-service.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-one-service.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-two-services-prefix-suffix.golden.yaml
  istioctl/cmd/testdata/authz/converter/one-rule-two-services-prefix-suffix.yaml
  istioctl/cmd/testdata/authz/converter/one-subject.yaml
  istioctl/cmd/testdata/authz/converter/rbac-global-on.golden.yaml
  istioctl/cmd/testdata/authz/converter/rbac-global-on.yaml
  istioctl/cmd/testdata/authz/converter/svc-bookinfo.yaml
  istioctl/cmd/testdata/authz/converter/svc-other.yaml
  istioctl/cmd/testdata/authz/converter/svc-prefix-suffix.yaml
  istioctl/cmd/testdata/authz/converter/two-subjects.yaml
  istioctl/cmd/testdata/authz/notfound-role-in-binding.yaml
  istioctl/cmd/testdata/authz/productpage.golden
  istioctl/cmd/testdata/authz/productpage_config_dump.json
  istioctl/cmd/testdata/authz/unused-role.yaml
  istioctl/pkg/auth/cluster.go
  istioctl/pkg/auth/testdata/validator/notfound-role-in-binding.yaml
  istioctl/pkg/auth/testdata/validator/rbac-policies.yaml
  istioctl/pkg/auth/testdata/validator/service-entry.yaml
  istioctl/pkg/auth/testdata/validator/unused-role.yaml
  istioctl/pkg/auth/validator.go
  istioctl/pkg/auth/validator_test.go
  istioctl/pkg/authz/analyzer.go
  istioctl/pkg/authz/listener.go
  istioctl/pkg/authz/testdata/binding-ns-default-user-foo.yaml
  istioctl/pkg/authz/util.go
Labels: cla: yes, size/XXL

#18750 Add new operator annotations to the analyze whitelist
  galley/pkg/config/analysis/analyzers/annotations/annotations.go
  go.mod
  go.sum
  tests/integration/conformance/testdata/config/quotaspecbinding/basic/mcp.yaml
  tests/integration/conformance/testdata/networking/destinationRule/basic/mcp.yaml
  tests/integration/conformance/testdata/networking/envoyFilter/basic/mcp.yaml
  tests/integration/conformance/testdata/networking/serviceEntry/basic/mcp.yaml
  tests/integration/conformance/testdata/networking/sidecar/basic/mcp.yaml
  tests/integration/conformance/testdata/networking/syntheticServiceEntry/mcp.yaml
  tests/integration/conformance/testdata/policy/attributemanifests/basic/mcp.yaml
  tests/integration/conformance/testdata/policy/handlers/basic/mcp.yaml
  tests/integration/conformance/testdata/policy/httpapispecbindings/basic/mcp.yaml
  tests/integration/conformance/testdata/policy/httpapispecs/basic/mcp.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/mcp.yaml
  tests/integration/conformance/testdata/rbac/rbacConfig/basic/mcp.yaml
  tests/integration/conformance/testdata/security/authorizationPolicy/basic/mcp.yaml
  tests/integration/galley/conversion_test.go
Labels: area/config, cla: yes, size/L

#18761 [release-1.4] Add its own service account for httpbin
  samples/httpbin/httpbin.yaml
Labels: cla: yes, size/XS

#18655 fix(stackdriver): pull mesh uid from config
  mixer/adapter/stackdriver/config/adapter.stackdriver.config.pb.html
  mixer/adapter/stackdriver/config/config.pb.go
  mixer/adapter/stackdriver/config/config.proto
  mixer/adapter/stackdriver/config/config.proto_descriptor
  mixer/adapter/stackdriver/config/stackdriver.yaml
  mixer/adapter/stackdriver/contextgraph/contextgraph.go
  mixer/adapter/stackdriver/contextgraph/contextgraph_test.go
  mixer/adapter/stackdriver/helper/common.go
  mixer/adapter/stackdriver/helper/common_test.go
  mixer/adapter/stackdriver/log/log.go
  mixer/adapter/stackdriver/log/log_test.go
  mixer/adapter/stackdriver/metric/metric.go
  mixer/adapter/stackdriver/metric/metric_test.go
  mixer/adapter/stackdriver/stackdriver.go
  mixer/adapter/stackdriver/trace/trace_integration_test.go
  mixer/adapter/stackdriver/trace/trace_test.go
Labels: area/policies and telemetry, cherrypick/release-1.4, cla: yes, size/L

#18747 [release-1.4] Add --output-threshold flag to `istioctl analyze`
  istioctl/cmd/analyze.go
Labels: cla: yes, size/M

#18759 [release-1.4] Handle wildcards in vs destinationhost analyzer
  galley/pkg/config/analysis/analyzers/auth/serviceroleservices.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
  galley/pkg/config/analysis/analyzers/util/constants.go
  galley/pkg/config/analysis/analyzers/util/hosts.go
  galley/pkg/config/analysis/analyzers/util/hosts_test.go
  galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
Labels: cla: yes, size/M

#18769 [release-1.4] Include virtualservice mirror destinations in analysis
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_destinationrules.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/util.go
Labels: cla: yes, size/M

#18314 Istiod agent
  cmd/istiod/istiod.go
  pilot/cmd/pilot-agent/main.go
  pkg/istio-agent/sds-agent.go
  pkg/istiod/common.go
  pkg/istiod/istio_ca.go
  pkg/istiod/k8s/certs.go
  pkg/istiod/k8s/k8sstart.go
  pkg/istiod/pilotstart.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/pkg/server/ca/authenticate/authenticator.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/XXL

#18766 [release-1.4] Set exit code when analyze cannot parse files
  istioctl/cmd/analyze.go
  istioctl/cmd/sysexits.go
Labels: cla: yes, size/M

#18746 Bump dependencies
  Makefile
  common/.commonfiles.sha
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: cla: yes, size/S

#18775 Update SHA of installer 95cf731b8
  go.mod
  go.sum
Labels: cla: yes, size/XS

#18778 Sync to operator
  go.mod
  go.sum
Labels: cla: yes, size/XS

#18700 Add structured format options to istioctl analyze
  galley/pkg/config/analysis/diag/message.go
  galley/pkg/config/analysis/diag/message_test.go
  istioctl/cmd/analyze.go
Labels: area/user experience, cla: yes, size/M

#18732 sidecar: copy service port while copying matching ports to service
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
Labels: area/networking, cla: yes, size/M

#18742 Bump operator and release builder
  go.mod
  go.sum
  prow/release-commit.sh
Labels: cla: yes, size/XS

#18516 Drop dependency of controllers for DiscoveryService
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/coredatamodel/syntheticserviceentrycontroller.go
  pilot/pkg/proxy/envoy/v2/bench_test.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pkg/istiod/pilotstart.go
Labels: cla: yes, size/L

#18660 Remove reference to demo profile; add note about istioctl x analyze
  istioctl/pkg/install/verify.go
  istioctl/pkg/validate/validate.go
Labels: cla: yes, size/XS

#18782 [release-1.4] Add analyzers for Sidecar workload selectors
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/sidecar/defaultselector.go
  galley/pkg/config/analysis/analyzers/sidecar/selector.go
  galley/pkg/config/analysis/analyzers/sidecar/util.go
  galley/pkg/config/analysis/analyzers/testdata/sidecar-default-selector.yaml
  galley/pkg/config/analysis/analyzers/testdata/sidecar-selector.yaml
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: cla: yes, size/L

#18784 Update go to 1.13 in go.mod
  go.mod
Labels: cherrypick/release-1.4, cla: yes, size/XS

#18781 [release-1.4] minor cleanup & added more tests for resource.Name
  galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
  galley/pkg/config/resource/name.go
  galley/pkg/config/resource/name_test.go
Labels: cla: yes, size/M

#18724 cleanup remote secrets when the cluster's discovery is not registered
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/apply_test.go
  istioctl/pkg/multicluster/generate.go
  istioctl/pkg/multicluster/mesh.go
  istioctl/pkg/multicluster/remote_secret.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#18760 fix(mixer): remove signalfx adapter
  go.mod
  go.sum
  licenses/github.com/dropbox/godropbox/database/sqltypes/LICENSE
  licenses/github.com/dropbox/godropbox/io2/ioutil2/LICENSE
  licenses/github.com/dropbox/godropbox/license.txt
  licenses/github.com/facebookgo/stack/license
  licenses/github.com/facebookgo/stackerr/license
  licenses/github.com/gopherjs/gopherjs/LICENSE
  licenses/github.com/jtolds/gls/LICENSE
  licenses/github.com/juju/errors/LICENSE
  licenses/github.com/juju/loggo/LICENSE
  licenses/github.com/juju/testing/LICENCE
  licenses/github.com/signalfx/com_signalfx_metrics_protobuf/NONE
  licenses/github.com/signalfx/gohistogram/LICENSE
  licenses/github.com/signalfx/golib/LICENSE
  licenses/github.com/smartystreets/assertions/LICENSE.md
  licenses/github.com/smartystreets/assertions/internal/go-render/LICENSE
  licenses/github.com/smartystreets/assertions/internal/oglematchers/LICENSE
  licenses/github.com/smartystreets/goconvey/LICENSE.md
  licenses/github.com/smartystreets/goconvey/web/client/resources/fonts/Open_Sans/LICENSE.txt
  licenses/gopkg.in/logfmt.v0/LICENSE
  licenses/gopkg.in/stack.v1/LICENSE.md
  mixer/adapter/inventory.gen.go
  mixer/adapter/inventory.yaml
  mixer/adapter/metadata/inventory.go
  mixer/adapter/signalfx/config/adapter.signalfx.config.pb.html
  mixer/adapter/signalfx/config/config.pb.go
  mixer/adapter/signalfx/config/config.proto
  mixer/adapter/signalfx/config/config.proto_descriptor
  mixer/adapter/signalfx/config/signalfx.yaml
  mixer/adapter/signalfx/cumulative.go
  mixer/adapter/signalfx/metrics.go
  mixer/adapter/signalfx/metrics_integration_test.go
  mixer/adapter/signalfx/operatorconfig/signalfx.yaml
  mixer/adapter/signalfx/operatorconfig/tracing.yaml
  mixer/adapter/signalfx/registry.go
  mixer/adapter/signalfx/registry_test.go
  mixer/adapter/signalfx/signalfx.go
  mixer/adapter/signalfx/signalfx_test.go
  mixer/adapter/signalfx/tracing.go
  mixer/adapter/signalfx/tracing_integration_test.go
Labels: area/policies and telemetry, cherrypick/release-1.4, cla: yes, size/XXL

#18776 Skip flaky TestAuthorizationForHTTPServices
  tests/integration/istioio/security/authz_http_test.go
Labels: cla: yes, size/XS

#18787 [release-1.4] Update go to 1.13 in go.mod
  go.mod
Labels: cla: yes, size/XS

#18792 [release-1.4] cleanup remote secrets when the cluster's discovery is not registered
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/apply_test.go
  istioctl/pkg/multicluster/generate.go
  istioctl/pkg/multicluster/mesh.go
  istioctl/pkg/multicluster/remote_secret.go
Labels: cla: yes, size/S

#18783 fix namespaced name parsing in validation analyzer
  galley/pkg/config/analysis/analyzers/schema/validation.go
Labels: area/config, cherrypick/release-1.4, cla: yes, ok-to-test, size/XS

#18768 Update proxy SHA
  istio.deps
Labels: cla: yes, size/XS

#18791 [release-1.4] Add analyzer rules for VirtualService destination ports
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: cla: yes, size/L

#18794 Extra checks to avoid breaking ingress - which is not yet fully switched
  pilot/cmd/pilot-agent/main.go
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
Labels: area/networking, cla: yes, size/S

#18757 fix(galley dash): provide correct dimension to query for state type
  install/kubernetes/helm/istio/charts/grafana/dashboards/galley-dashboard.json
Labels: area/policies and telemetry, cherrypick/release-1.4, cla: yes

#18804 [release-1.4] fix(mixer): remove signalfx adapter (#18760)
  go.mod
  go.sum
  licenses/github.com/dropbox/godropbox/database/sqltypes/LICENSE
  licenses/github.com/dropbox/godropbox/io2/ioutil2/LICENSE
  licenses/github.com/dropbox/godropbox/license.txt
  licenses/github.com/facebookgo/stack/license
  licenses/github.com/facebookgo/stackerr/license
  licenses/github.com/gopherjs/gopherjs/LICENSE
  licenses/github.com/jtolds/gls/LICENSE
  licenses/github.com/juju/errors/LICENSE
  licenses/github.com/juju/loggo/LICENSE
  licenses/github.com/juju/testing/LICENCE
  licenses/github.com/signalfx/com_signalfx_metrics_protobuf/NONE
  licenses/github.com/signalfx/gohistogram/LICENSE
  licenses/github.com/signalfx/golib/LICENSE
  licenses/github.com/smartystreets/assertions/LICENSE.md
  licenses/github.com/smartystreets/assertions/internal/go-render/LICENSE
  licenses/github.com/smartystreets/assertions/internal/oglematchers/LICENSE
  licenses/github.com/smartystreets/goconvey/LICENSE.md
  licenses/github.com/smartystreets/goconvey/web/client/resources/fonts/Open_Sans/LICENSE.txt
  licenses/gopkg.in/logfmt.v0/LICENSE
  licenses/gopkg.in/stack.v1/LICENSE.md
  mixer/adapter/inventory.gen.go
  mixer/adapter/inventory.yaml
  mixer/adapter/metadata/inventory.go
  mixer/adapter/signalfx/config/adapter.signalfx.config.pb.html
  mixer/adapter/signalfx/config/config.pb.go
  mixer/adapter/signalfx/config/config.proto
  mixer/adapter/signalfx/config/config.proto_descriptor
  mixer/adapter/signalfx/config/signalfx.yaml
  mixer/adapter/signalfx/cumulative.go
  mixer/adapter/signalfx/metrics.go
  mixer/adapter/signalfx/metrics_integration_test.go
  mixer/adapter/signalfx/operatorconfig/signalfx.yaml
  mixer/adapter/signalfx/operatorconfig/tracing.yaml
  mixer/adapter/signalfx/registry.go
  mixer/adapter/signalfx/registry_test.go
  mixer/adapter/signalfx/signalfx.go
  mixer/adapter/signalfx/signalfx_test.go
  mixer/adapter/signalfx/tracing.go
  mixer/adapter/signalfx/tracing_integration_test.go
Labels: area/policies and telemetry, cla: yes, size/XXL

#18807 [release-1.4] fix(galley dash): provide correct dimension to query for state type
  install/kubernetes/helm/istio/charts/grafana/dashboards/galley-dashboard.json
Labels: cla: yes, size/XS

#18801 Add unit test for validation analyzer wrapper
  galley/pkg/config/analysis/analyzers/schema/validation_test.go
Labels: area/config, cla: yes, size/S

#18799 [kiali] helm update to move to kiali 1.9
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: area/environments/installer, cherrypick/release-1.4, cla: yes, size/L

#18800 [release-1.4] fix namespaced name parsing in validation analyzer
  galley/pkg/config/analysis/analyzers/schema/validation.go
Labels: cla: yes, size/XS

#18812 [release-1.4] Fix nil stackdriver environment variables
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/files/injection-template.yaml
Labels: cla: yes, size/S

#18808 Fix minor typo in analyzer messages
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/user experience, cla: yes, size/XS

#18814 [kiali] helm update to move to kiali 1.9 (#18799)
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: area/environments, cla: yes, size/L

#18797 Remove unused arg that somehow slipped through the linter
  galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
Labels: area/config, cla: yes, size/XS

#18811 Updating image to match prow.
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/S

#18610 istio-iptables: Fix golden files for golang implementation
  tests/scripts/testdata/golang/empty_parameter_golden.txt
  tests/scripts/testdata/golang/mode_redirect_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_golden.txt
  tests/scripts/testdata/golang/outbound_port_exclude_golden.txt
  tests/scripts/testdata/golang/wildcard_include_ip_range_golden.txt
Labels: cla: yes, ok-to-test, size/M

#18821 Don't set `request.host` as label for ingress
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
Labels: cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/XS
