Repository istio/istio, pull requests merged in 2019-05, with the labels that each got.

#13350 Lock down development of installer
  install/OWNERS
  install/kubernetes/helm/README.md
Labels: approved, cla: yes, lgtm

#13563 Fix isValidIP in iptable-start.sh and add unit test for it.
  Makefile
  tests/scripts/scripts_test.sh
  tools/packaging/common/istio-iptables.sh
Labels: approved, cla: yes, lgtm

#13741 fix broken links.
  pkg/test/framework/README.md
  tests/e2e/local/kind/README.md
  tests/e2e/local/kubeadm/README.md
  tests/e2e/local/minikube/README.md
  tests/e2e/local/vagrant/README.md
  tools/README.md
Labels: approved, cla: yes, lgtm

#13736 add samples validation linter
  .gitignore
  bin/check_samples.sh
  bin/linters.sh
  istioctl/pkg/validate/validate.go
  mixer/testdata/config/attributes.yaml
  samples/bookinfo/policy/mixer-rule-ratings-ratelimit.yaml
Labels: approved, cla: yes, lgtm

#13591 release: Update latest stable Istio CNI SHA
  istio.deps
Labels: cla: yes, lgtm

#13683 Fix unit tests of Vault CA integration
  security/pkg/nodeagent/caclient/providers/vault/client_test.go
  tests/integration/security/citadel_agent/vault/README.md
  tests/integration/security/citadel_agent/vault/client_test.go
Labels: approved, area/security, area/test and release, cla: yes, code mauve, lgtm

#13731 Reject overlapping Gateway HTTPS hosts
  pilot/pkg/model/gateway.go
  pilot/pkg/model/gateway_test.go
Labels: approved, cla: yes

#13750 Fix istioctl test
  prow/istioctl-tests.sh
Labels: approved, cla: yes, lgtm

#13738 Refactor Test Framework API Surface, and add complete Galley component methods.
  galley/pkg/testing/testdata/dataset.gen.go
  galley/pkg/testing/testdata/dataset/extensions/v1beta1/ingress_basic_expected.json
  galley/pkg/testing/testdata/dataset/extensions/v1beta1/ingress_merge_0_expected.json
  galley/pkg/testing/testdata/dataset/extensions/v1beta1/ingress_merge_1_expected.json
  galley/pkg/testing/testdata/testinfo.go
  pkg/test/framework/README.md
  pkg/test/framework/components/galley/galley.go
  pkg/test/framework/components/galley/kube.go
  pkg/test/framework/components/galley/native.go
  pkg/test/framework/components/galley/native_test.go
  pkg/test/framework/components/galley/snapshot.go
  pkg/test/framework/components/istio/istio.go
  pkg/test/framework/components/namespace/namespace.go
  pkg/test/framework/label/filter.go
  pkg/test/framework/operations.go
  pkg/test/framework/suite.go
  pkg/test/framework/suite_test.go
  pkg/test/framework/test.go
  pkg/test/kube/accessor.go
  pkg/test/util/yml/apply.go
  pkg/test/util/yml/cache.go
  pkg/test/util/yml/cache_test.go
  pkg/test/util/yml/parse.go
  pkg/test/util/yml/parts.go
  tests/integration/echo/echo_test.go
  tests/integration/examples/example_test.go
  tests/integration/framework/framework_test.go
  tests/integration/framework/galley_test.go
  tests/integration/framework/namespace_test.go
  tests/integration/galley/conversion/conversion_test.go
  tests/integration/galley/validation/validation_test.go
  tests/integration/mixer/main_test.go
  tests/integration/mixer/policy/ratelimiting_test.go
  tests/integration/mixer/telemetry/scenarios_test.go
  tests/integration/pilot/locality/failover/main_test.go
  tests/integration/pilot/locality/prioritized/main_test.go
  tests/integration/pilot/outboundtrafficpolicy/allowany/traffic_allow_any_test.go
  tests/integration/pilot/outboundtrafficpolicy/registryonly/traffic_registry_only_test.go
  tests/integration/qualification/main_test.go
  tests/integration/security/authn/authn_permissive_test.go
  tests/integration/security/citadel/secret_creation_test.go
  tests/integration/security/healthcheck/mtls_healthcheck_test.go
  tests/integration/security/rbac/v1/group/group_test.go
  tests/integration/security/rbac/v2/basic/basic_test.go
  tests/integration/security/rbac/v2/group/group_test.go
  tests/integration/security/reachability/main_test.go
  tests/integration/security/sds_citadel_flow/sds_citadel_flow_test.go
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
Labels: approved, cla: yes, lgtm

#13729 Extend fake policy backend for OOP adapter integration test
  pkg/test/fakes/policy/backend.go
  pkg/test/fakes/policy/config.pb.go
  pkg/test/fakes/policy/config.proto
  pkg/test/fakes/policy/config.proto_descriptor
  pkg/test/fakes/policy/controller.go
  pkg/test/fakes/policy/doc.go
  pkg/test/fakes/policy/policy.pb.html
  pkg/test/fakes/policy/policybackend.yaml
  pkg/test/fakes/policy/settings.go
  pkg/test/framework/components/policybackend/client.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/framework/components/policybackend/native.go
  pkg/test/framework/components/policybackend/policybackend.go
  tests/integration/mixer/check_test.go
  tests/integration/mixer/report_test.go
Labels: approved, cla: yes, lgtm

#13756 [Test Framework] Adding utility methods to Pilot
  pkg/test/framework/components/pilot/client.go
  pkg/test/framework/components/pilot/pilot.go
  tests/integration/pilot/sidecar_api_test.go
Labels: approved, cla: yes, lgtm

#13597 Cherrypick changes from master to release 1.1 for repease process
  release/gcb/run_build.sh
  release/gcb/run_daily_release.sh
  release/gcb/run_monthly_release.sh
Labels: cla: yes, lgtm

#13761 [Test Framework] Only wait for namespace if we have cleanup
  tests/integration/framework/namespace_test.go
Labels: approved, cla: yes, lgtm

#13768 Add temporary owners for collab-gce-identity branch.
  OWNERS
Labels: cla: yes

#13712 Fix the RPM proxy generation
  tools/packaging/rpm/Dockerfile.build
Labels: approved, cla: yes, lgtm

#13767 [Test Framework] Fix null yaml files generated
  pkg/test/util/yml/apply.go
Labels: approved, cla: yes, lgtm

#13410 GCE workload provisioning using Google CA
  security/cmd/node_agent/main.go
  security/pkg/caclient/config.go
  security/pkg/caclient/keycertbundlerotator.go
  security/pkg/caclient/keycertbundlerotator_test.go
  security/pkg/credential/token.go
  security/pkg/nodeagent/caclient/client.go
  security/pkg/nodeagent/caclient/providers/mock/fakecaclient.go
  security/pkg/nodeagent/envvar/envvar.go
  security/pkg/nodeagent/vm/citadelagent_v2.go
  security/pkg/nodeagent/vm/citadelagent_v2_test.go
  security/pkg/nodeagent/vm/config.go
  security/pkg/nodeagent/vm/nafactory.go
  security/pkg/nodeagent/vm/nafactory_test.go
  security/pkg/platform/aws.go
  security/pkg/platform/aws_test.go
  security/pkg/platform/client.go
  security/pkg/platform/client_test.go
  security/pkg/platform/gcp.go
  security/pkg/platform/gcp_test.go
  security/pkg/platform/onprem.go
  security/pkg/platform/onprem_test.go
Labels: approved, cla: yes, lgtm

#13632 rbac: introduce a general model to abstract the RBAC policy
  pilot/pkg/networking/plugin/authz/conversion.go
  pilot/pkg/networking/plugin/authz/model.go
  pilot/pkg/networking/plugin/authz/model_test.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/authz/rbac_test.go
  pilot/pkg/networking/plugin/authz/rbac_v2.go
  pilot/pkg/networking/plugin/authz/validate.go
  pilot/pkg/networking/plugin/authz/validate_test.go
Labels: approved, cla: yes, code mauve, lgtm

#13745 change endpoint logs to debug level
  pilot/pkg/proxy/envoy/v2/ep_filters.go
Labels: approved, cla: yes, lgtm

#13746 add access logs for passthrough listener
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: approved, cla: yes, lgtm

#13779 [Testing] Fix race in Galley file source
  galley/pkg/runtime/processor.go
  galley/pkg/source/fs/source.go
Labels: approved, cla: yes, lgtm

#13755 [Testing] Fix for Envoy baseID
  pkg/test/envoy/envoy.go
Labels: approved, cla: yes, lgtm

#13769 Create release-1.1-latest.txt with build version
  release/gcb/rel_daily_complete.sh
Labels: cla: yes, code mauve

#13784 [Test Framework] Capture cleanup settings from test
  tests/integration/framework/namespace_test.go
Labels: approved, cla: yes, lgtm

#13770 create master-latest.txt with build version
  release/gcb/rel_daily_complete.sh
Labels: approved, cla: yes, code mauve, lgtm

#13782 [Test Framework] Add custom setup label
  pkg/test/framework/label/labels.go
  tests/integration/pilot/locality/failover/main_test.go
  tests/integration/pilot/locality/prioritized/main_test.go
  tests/integration/pilot/outboundtrafficpolicy/allowany/traffic_allow_any_test.go
  tests/integration/pilot/outboundtrafficpolicy/registryonly/traffic_registry_only_test.go
  tests/integration/security/healthcheck/mtls_healthcheck_test.go
  tests/integration/security/rbac/v1/group/group_test.go
  tests/integration/security/rbac/v2/basic/basic_test.go
  tests/integration/security/rbac/v2/group/group_test.go
  tests/integration/security/sds_citadel_flow/sds_citadel_flow_test.go
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
Labels: approved, cla: yes, lgtm

#13757 [Test Framework] Various fixes for Echo component
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/common/envoy.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/sidecar.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/echo/native/instance.go
  pkg/test/framework/components/echo/native/sidecar.go
  tests/integration/echo/echo_test.go
Labels: approved, cla: yes, lgtm

#13117 add ipv6 parameter for rendering proxy config
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/main_test.go
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/util/listeners.go
  pilot/cmd/pilot-agent/status/util/stats.go
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pkg/bootstrap/bootstrap_config.go
  pkg/bootstrap/bootstrap_config_test.go
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: approved, cla: yes, lgtm

#13786 update nodeagent base image
  security/docker/Dockerfile.node-agent-k8s
Labels: approved, cla: yes, lgtm

#13783 Add individual owners files to each top-level test folder.
  tests/integration/echo/OWNERS
  tests/integration/examples/OWNERS
  tests/integration/framework/OWNERS
  tests/integration/galley/OWNERS
  tests/integration/mixer/OWNERS
  tests/integration/pilot/OWNERS
  tests/integration/qualification/OWNERS
  tests/integration/security/OWNERS
Labels: approved, cla: yes, lgtm

#13733 citadel: use chain cert if available otherwise use root cert
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
Labels: approved, cla: yes, lgtm

#13773 increase host selection retry max attempts
  pilot/pkg/networking/core/v1alpha3/route/retry/retry.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13796 [Testing] Add Flaky label.
  pkg/test/framework/label/labels.go
Labels: approved, cla: yes, lgtm

#13816 Add Yangmin as an owner for security integration test
  tests/integration/security/OWNERS
Labels: approved, cla: yes, lgtm

#13627 [istioctl] Upgrade rbac policy v1 to v2 locally.
  istioctl/cmd/istioctl/rbac.go
  istioctl/pkg/rbac/testdata/rbac-policies-v2.golden.yaml
  istioctl/pkg/rbac/testdata/rbac-policies-with-methods-and-paths-v2.golden.yaml
  istioctl/pkg/rbac/testdata/rbac-policies-with-methods-and-paths.yaml
  istioctl/pkg/rbac/testdata/rbac-policies.yaml
  istioctl/pkg/rbac/upgrade.go
  istioctl/pkg/rbac/upgrade_test.go
  pilot/pkg/model/validation.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#13094 fix(telemetry): remove configID from mixer self-monitoring metrics
  mixer/pkg/runtime/config/ephemeral.go
  mixer/pkg/runtime/config/snapshot.go
  mixer/pkg/runtime/handler/env.go
  mixer/pkg/runtime/handler/table.go
  mixer/pkg/runtime/monitoring/monitoring.go
  mixer/pkg/runtime/routing/builder.go
Labels: approved, area/policies and telemetry, cla: yes, code mauve, lgtm

#13792 Merge all Galley integration tests into a single test suite.
  tests/integration/galley/conversion_test.go
  tests/integration/galley/data.gen.go
  tests/integration/galley/data.gen_test.go
  tests/integration/galley/dialout/dialout_test.go
  tests/integration/galley/dialout_test.go
  tests/integration/galley/main_test.go
  tests/integration/galley/testdata/authentication-v1alpha1-Policy-invalid.yaml
  tests/integration/galley/testdata/authentication-v1alpha1-Policy-valid.yaml
  tests/integration/galley/testdata/config-v1alpha2-HTTPAPISpec-invalid.yaml
  tests/integration/galley/testdata/config-v1alpha2-HTTPAPISpec-valid.yaml
  tests/integration/galley/testdata/config-v1alpha2-HTTPAPISpecBinding-invalid.yaml
  tests/integration/galley/testdata/config-v1alpha2-HTTPAPISpecBinding-valid.yaml
  tests/integration/galley/testdata/config-v1alpha2-QuotaSpec-invalid.yaml
  tests/integration/galley/testdata/config-v1alpha2-QuotaSpec-valid.yaml
  tests/integration/galley/testdata/config-v1alpha2-QuotaSpecBinding-invalid.yaml
  tests/integration/galley/testdata/config-v1alpha2-QuotaSpecBinding-valid.yaml
  tests/integration/galley/testdata/config-v1alpha2-rule-invalid.yaml
  tests/integration/galley/testdata/config-v1alpha2-rule-valid.yaml
  tests/integration/galley/testdata/networking-v1alpha3-DestinationRule-invalid.yaml
  tests/integration/galley/testdata/networking-v1alpha3-DestinationRule-valid.yaml
  tests/integration/galley/testdata/networking-v1alpha3-Gateway-invalid.yaml
  tests/integration/galley/testdata/networking-v1alpha3-Gateway-valid.yaml
  tests/integration/galley/testdata/networking-v1alpha3-ServiceEntry-invalid-skipped.yaml
  tests/integration/galley/testdata/networking-v1alpha3-ServiceEntry-valid-skipped.yaml
  tests/integration/galley/testdata/networking-v1alpha3-VirtualService-invalid.yaml
  tests/integration/galley/testdata/networking-v1alpha3-VirtualService-valid.yaml
  tests/integration/galley/testdata/rbac-v1alpha1-ServiceRole-invalid.yaml
  tests/integration/galley/testdata/rbac-v1alpha1-ServiceRole-valid.yaml
  tests/integration/galley/testdata/rbac-v1alpha1-ServiceRoleBinding-invalid.yaml
  tests/integration/galley/testdata/rbac-v1alpha1-ServiceRoleBinding-valid.yaml
  tests/integration/galley/validation/data.gen.go
  tests/integration/galley/validation/validation_test.go
  tests/integration/galley/validation_test.go
Labels: approved, cla: yes, lgtm

#13316 bump the version of bookinfo images to 1.13.0
  samples/bookinfo/networking/egress-rule-google-apis.yaml
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-add-serviceaccount.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: approved, cla: yes, lgtm

#13809 Combine example and framework tests.
  tests/integration/framework/example_test.go
  tests/integration/framework/framework_test.go
  tests/integration/framework/mycomponent/kube.go
  tests/integration/framework/mycomponent/mycomponent.go
  tests/integration/framework/mycomponent/native.go
Labels: approved, cla: yes, lgtm

#13814 Mark tests flaking in post-submit as flaky.
  tests/integration/echo/echo_test.go
  tests/integration/mixer/check_test.go
  tests/integration/mixer/policy/ratelimiting_test.go
  tests/integration/mixer/report_test.go
  tests/integration/mixer/telemetry/scenarios_test.go
  tests/integration/pilot/locality/failover/failover_test.go
  tests/integration/pilot/outboundtrafficpolicy/helper.go
Labels: approved, cla: yes, lgtm

#13808 (hzxuzhonghu) Always allow unknown fields when apply json string
  pilot/pkg/config/kube/crd/conversion_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/conversion.go
  pilot/pkg/model/conversion_test.go
Labels: approved, cla: no, lgtm

#13654 Add a test for IP whitelisting
  pkg/test/framework/components/bookinfo/configs.go
  tests/integration/mixer/policy/white_black_listing_test.go
  tests/integration/mixer/util.go
Labels: approved, cla: yes, code mauve, lgtm

#13721 Remove too noisy log
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#13725 Change time.After to time.NewTimer
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: approved, area/networking, cla: yes, lgtm

#13833 Added correct link to Bookinfo docs
  samples/bookinfo/README.md
Labels: cla: yes, lgtm, ok-to-test

#12529 Adds a CNI option to the e2e tests
  tests/e2e/README.md
  tests/e2e/framework/kubernetes.go
  tests/istio.mk
  tests/util/helm_utils.go
Labels: approved, cla: yes, code mauve, lgtm

#13630 Cherry-pick from 1.0 to 1.1 - Fix deployment namespace #7446 (#7477)
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
Labels: approved, cla: no, lgtm

#13830 support isolated namespace for integration test
  pkg/test/framework/README.md
  pkg/test/framework/components/citadel/kube.go
  pkg/test/framework/components/galley/kube.go
  pkg/test/framework/components/ingress/kube.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  pkg/test/framework/components/mixer/kube.go
  pkg/test/framework/components/pilot/kube.go
  pkg/test/framework/components/prometheus/kube.go
Labels: approved, cla: yes, lgtm

#13747 Update Ruby version in the Dockerfile for bookinfo-details app
  samples/bookinfo/src/details/Dockerfile
Labels: cla: yes

#13727 Refactor commands out of 'main' package
  codecov.threshold
  istioctl/cmd/auth.go
  istioctl/cmd/auth_test.go
  istioctl/cmd/authn.go
  istioctl/cmd/authn_test.go
  istioctl/cmd/convert_ingress.go
  istioctl/cmd/convert_ingress_test.go
  istioctl/cmd/dashboard.go
  istioctl/cmd/dashboard_test.go
  istioctl/cmd/deprecated_cmd.go
  istioctl/cmd/deregister.go
  istioctl/cmd/handlers.go
  istioctl/cmd/handlers_test.go
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/main.go
  istioctl/cmd/istioctl/version.go
  istioctl/cmd/istioctl_test.go
  istioctl/cmd/kubeinject.go
  istioctl/cmd/metrics.go
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/proxystatus_test.go
  istioctl/cmd/rbac.go
  istioctl/cmd/register.go
  istioctl/cmd/root.go
  istioctl/cmd/testdata/auth/productpage.golden
  istioctl/cmd/testdata/auth/productpage_config_dump.json
  istioctl/cmd/testdata/deployment/hello.yaml
  istioctl/cmd/testdata/deployment/hello.yaml.injected
  istioctl/cmd/testdata/ingress/another-ingress.yaml
  istioctl/cmd/testdata/ingress/myservice-ingress.yaml
  istioctl/cmd/testdata/inject-config.yaml
  istioctl/cmd/testdata/inject-values.yaml
  istioctl/cmd/testdata/mesh-config.yaml
  istioctl/cmd/testdata/v1alpha3/merged-gateway.yaml
  istioctl/cmd/testdata/v1alpha3/merged-gateway.yaml.golden
  istioctl/cmd/testdata/v1alpha3/myservice-gateway.yaml
  istioctl/cmd/testdata/v1alpha3/myservice-gateway.yaml.golden
  istioctl/cmd/version.go
  istioctl/cmd/version_test.go
Labels: approved, cla: yes, lgtm

#13590 add istio-multicluster-split-horizon.yaml to gitignore
  .gitignore
Labels: cla: yes, lgtm, ok-to-test

#13797 [Testing] Removing unused flaky annotation
  pkg/test/annotation/flaky.go
  tools/checker/flaky_test_finder/flaky_test_finder.go
  tools/checker/flaky_test_finder/flaky_test_finder_test.go
  tools/checker/flaky_test_finder/rules/is_flaky.go
  tools/checker/flaky_test_finder/rules_matcher.go
  tools/checker/flaky_test_finder/testdata/flaky_rule_test.go
Labels: approved, cla: yes, lgtm

#13748 Update the version of NodeJS in Dockerfile of bookinfo-ratings app
  samples/bookinfo/src/ratings/Dockerfile
Labels: approved, cla: yes, lgtm

#13821 fix pilot-agent request url
  pilot/cmd/pilot-agent/request.go
Labels: approved, cla: yes, lgtm

#13689 updateServiceShards only for non k8s registry
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#13854 Adding helm init for perf tests
  prow/setup_perf_cluster_for_tests.sh
Labels: approved, cla: yes, lgtm

#13737 Remove CDS caching logic and related flag
  pilot/pkg/networking/core/configgen.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes, lgtm

#13835 Pass the original user agent to applications in app probes
  pilot/cmd/pilot-agent/status/server.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13865 update webhook http response error
  pilot/pkg/kube/inject/webhook.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13852 Make presubmit tests to exclude flaky and postsubmit tests.
  tests/integration/tests.mk
Labels: approved, cla: yes, lgtm

#13793 [Testing] Refactor locality integration tests
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/sidecar.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/istio/kube.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/kube/accessor.go
  tests/integration/pilot/locality/failover/failover_test.go
  tests/integration/pilot/locality/failover/main_test.go
  tests/integration/pilot/locality/failover_test.go
  tests/integration/pilot/locality/helpers.go
  tests/integration/pilot/locality/main_test.go
  tests/integration/pilot/locality/prioritized/main_test.go
  tests/integration/pilot/locality/prioritized/prioritized_test.go
  tests/integration/pilot/locality/prioritized_test.go
Labels: approved, cla: yes, lgtm

#13871 Add zsh completion file generation
  pkg/collateral/cobra.go
  pkg/collateral/control.go
Labels: approved, cla: yes, lgtm

#13774 Upgrade mysql version for bookinfo-mysqldb app to latest
  samples/bookinfo/src/mysql/Dockerfile
Labels: approved, cla: yes, lgtm

#13856 Further replace of 127.0.0.1 by hostname
  galley/cmd/galley/cmd/server.go
  galley/pkg/crd/validation/validation.go
  galley/tools/mcpc/main.go
  pilot/cmd/pilot-agent/status/server.go
  pkg/ctrlz/options.go
  tools/packaging/common/envoy_bootstrap_drain.json
Labels: cla: yes, lgtm

#13893 fix disabled policy checks for TCP
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#13568 Remove model.NodeType.Ingress
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pilot/pkg/serviceregistry/kube/controller_test.go
Labels: approved, cla: yes, lgtm

#13897 Add owners for RBAC tests
  tests/integration/security/rbac/OWNERS
Labels: approved, cla: yes, lgtm

#13889 Generate Zsh completion file and add to archive (tools/_istioctl)
  Makefile
Labels: approved, cla: yes, lgtm

#13896 fix a potential problem in RBAC test and refactor the test utility
  pkg/test/echo/common/response/response.go
  tests/integration/security/rbac/util/rbac_util.go
  tests/integration/security/rbac/v1/group/group_test.go
  tests/integration/security/rbac/v2/basic/basic_test.go
  tests/integration/security/rbac/v2/group/group_test.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#13917 Patch #11462 to master
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
Labels: approved, cla: yes, lgtm

#13922 Fix the galley integration shell script to use the right common script
  prow/integ-galley-local-presubmit-tests.sh
Labels: approved, cla: yes, lgtm

#13706 Add istio-env label when creating test namespaces.
  pkg/test/docker/registry/incluster.go
  pkg/test/framework/components/apps/kube.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/framework/core/image/flags.go
  pkg/test/framework/core/image/settings.go
  pkg/test/kube/accessor.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13928 Fix the RBAC group test
  tests/integration/security/rbac/v1/group/testdata/istio-group-list-rbac-rules.yaml.tmpl
  tests/integration/security/rbac/v2/group/testdata/istio-group-list-rbac-v2-rules.yaml.tmpl
Labels: approved, cla: yes, lgtm

#13930 [Test Framework] Remove apps component
  pkg/test/framework/components/apps/agent/bootstrap.go
  pkg/test/framework/components/apps/agent/config.go
  pkg/test/framework/components/apps/agent/instance.go
  pkg/test/framework/components/apps/agent/serviceentry.go
  pkg/test/framework/components/apps/apps.go
  pkg/test/framework/components/apps/kube.go
  pkg/test/framework/components/apps/native.go
  pkg/test/framework/components/apps/native_test.go
  tests/integration/pilot/outboundtrafficpolicy/helper.go
Labels: approved, cla: yes, lgtm

#13932 Fix istioctl flaky test
  istioctl/cmd/istioctl_test.go
Labels: approved, cla: yes, lgtm

#13905 fix pod antiaffinity issue.
  install/kubernetes/helm/istio/charts/certmanager/values.yaml
  install/kubernetes/helm/istio/charts/galley/values.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/_affinity.tpl
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  install/kubernetes/helm/istio/charts/grafana/values.yaml
  install/kubernetes/helm/istio/charts/istiocoredns/values.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
  install/kubernetes/helm/istio/charts/mixer/values.yaml
  install/kubernetes/helm/istio/charts/nodeagent/values.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  install/kubernetes/helm/istio/charts/prometheus/values.yaml
  install/kubernetes/helm/istio/charts/security/values.yaml
  install/kubernetes/helm/istio/charts/servicegraph/values.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/values.yaml
  install/kubernetes/helm/istio/charts/tracing/values.yaml
  install/kubernetes/helm/istio/templates/_affinity.tpl
Labels: approved, cla: yes

#13946 fix consul sidecar templates to update proxy_init image tag
  samples/bookinfo/platform/consul/templates/bookinfo.sidecars.yaml.tmpl
Labels: approved, area/networking, cla: yes, kind/customer issue, lgtm

#13949 Delete depupdate circleci job
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#13829 rbac: support reading service definition from a file for the upgrade command
  istioctl/cmd/auth.go
  istioctl/cmd/auth_test.go
  istioctl/cmd/rbac.go
  istioctl/cmd/root.go
  istioctl/cmd/testdata/auth/authz-policy.golden
  istioctl/cmd/testdata/auth/authz-policy.yaml
  istioctl/cmd/testdata/auth/svc-bookinfo.yaml
  istioctl/cmd/testdata/auth/svc-other.yaml
  istioctl/pkg/auth/testdata/rbac-policies-v2.golden.yaml
  istioctl/pkg/auth/testdata/rbac-policies-with-methods-and-paths-v2.golden.yaml
  istioctl/pkg/auth/testdata/rbac-policies-with-methods-and-paths.yaml
  istioctl/pkg/auth/testdata/rbac-policies.yaml
  istioctl/pkg/auth/upgrade.go
  istioctl/pkg/auth/upgrade_test.go
  istioctl/pkg/rbac/rbacStore.go
  istioctl/pkg/rbac/rbacStore_test.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#13918 Increase Golang version and memory requirement for Vagrant test env
  tools/vagrant/Vagrantfile
  tools/vagrant/provision-vagrant.sh
Labels: approved, cla: yes, lgtm

#13684 Fix unit tests of Vault CA integration [release 1.1 branch]
  install/kubernetes/helm/istio/example-values/values-istio-example-sds-vault.yaml
  security/pkg/nodeagent/caclient/providers/vault/client_test.go
  tests/integration2/security/citadel_agent/vault/README.md
  tests/integration2/security/citadel_agent/vault/client_test.go
Labels: approved, area/security, area/test and release, cla: yes, code mauve, lgtm

#13801 Fix bug(#13764). Support template in values config
  install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml
  install/kubernetes/helm/istio/files/injection-template.yaml
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/testdata/inject/hello-template-in-values.yaml.injected
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13941 Replace README content with a redirect to the wiki.
  pkg/test/framework/README.md
Labels: approved, cla: yes

#13827 Fix issue #12752. Add delay after applying configuration change
  pilot/pkg/proxy/agent_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13954 fix release script to use go.mod
  release/gcb/generate_manifest.sh
Labels: approved, cla: yes, lgtm

#13956 Fix a typo in the name of an environmental variable
  install/kubernetes/helm/istio/example-values/values-istio-example-sds-vault.yaml
Labels: approved, cla: yes, lgtm

#13776 add access logs for passthrough listener
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: approved, cla: yes, lgtm

#13846 (hzxuzhonghu) Always allow unknown fields when apply json string (#13…
  pilot/pkg/config/kube/crd/conversion_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/conversion.go
  pilot/pkg/model/conversion_test.go
Labels: approved, cla: yes, lgtm

#13952 add branch info to circle ci test logs
  bin/ci2gubernator.sh
Labels: approved, cla: yes, lgtm

#13924 Don't fail when server is missing for route request
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes

#13790 Add tracing integration test
  pkg/test/framework/components/zipkin/kube.go
  pkg/test/framework/components/zipkin/zipkin.go
  tests/integration/telemetry/tracing/tracing_test.go
Labels: approved, cla: yes, code mauve, lgtm

#13923 Support ingress gateway agent to use fallback secret
  security/docker/Dockerfile.node-agent-k8s
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/pkg/nodeagent/secretfetcher/secretfetcher_test.go
Labels: approved, cla: yes

#13975 Reuse function getPodKey in pilot
  pilot/pkg/serviceregistry/kube/pod.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13959 generate correct inbound clusters depending on ipv4 or ipv6 mode
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/proxy/envoy/proxy.go
  pilot/pkg/proxy/envoy/proxy_test.go
Labels: approved, area/networking, cla: yes, lgtm

#13987 [Test Framework] Fix ready timeout endpoints
  pkg/test/kube/accessor.go
Labels: approved, cla: yes, lgtm

#13927 drop unnecessary dependencies
  galley/pkg/runtime/projections/serviceentry/handler_bench_test.go
  galley/pkg/runtime/projections/serviceentry/handler_test.go
  galley/pkg/runtime/projections/serviceentry/integration/integration_bench_test.go
  galley/pkg/runtime/projections/serviceentry/pod/cache.go
  galley/pkg/runtime/projections/serviceentry/pod/cache_test.go
  go.mod
  go.sum
  pilot/pkg/kube/inject/webhook_test.go
  vendor/github.com/envoyproxy/protoc-gen-validate/validate/BUILD
  vendor/github.com/envoyproxy/protoc-gen-validate/validate/validate.h
  vendor/github.com/envoyproxy/protoc-gen-validate/validate/validate.pb.go
  vendor/github.com/envoyproxy/protoc-gen-validate/validate/validate.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/features/BUILD
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_annotations.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_annotations_windows.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_labels.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm

#13988 [Testing] Merge file utilities
  pkg/test/framework/components/bookinfo/configs.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/deployment.go
  pkg/test/util/file/file.go
  tests/integration/security/rbac/v1/group/group_test.go
  tests/integration/security/rbac/v2/basic/basic_test.go
  tests/integration/security/rbac/v2/basic/extended_test.go
  tests/integration/security/rbac/v2/group/group_test.go
  tests/integration/security/reachability/reachability_test.go
  tests/integration/security/sds_citadel_flow/sds_citadel_flow_test.go
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
Labels: approved, cla: yes, lgtm

#13849 Cleanup configs in policies test and fix flaky check and report tests
  tests/integration/mixer/check_test.go
  tests/integration/mixer/policy/ratelimiting_test.go
  tests/integration/mixer/policy/white_black_listing_test.go
  tests/integration/mixer/report_test.go
Labels: approved, cla: yes, lgtm

#13971 Remove CircleCI gates for aggregated integration tests.
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#13990 test framework: initialize only uninitialized instance
  pkg/test/framework/components/echo/kube/instance.go
Labels: approved, cla: yes, lgtm

#13992 Add grpc to reach-ability e2e test
  tests/integration/security/reachability/reachability_test.go
Labels: approved, cla: yes, code mauve, lgtm

#14016 Get filewatcher from common repo.
  galley/pkg/meshconfig/cache.go
  galley/pkg/server/configmap.go
  galley/pkg/server/configmap_test.go
  go.mod
  go.sum
  pilot/pkg/bootstrap/server.go
  pkg/filewatcher/fakefilewatcher_test.go
  pkg/filewatcher/filewatcher_test.go
  pkg/mcp/creds/notifyWatcher.go
  pkg/mcp/creds/notifyWatcher_test.go
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/Makefile
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/have_occurred_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_xml_matcher.go
  vendor/istio.io/common/pkg/appsignals/watcher.go
  vendor/istio.io/common/pkg/filewatcher/fakefilewatcher.go
  vendor/istio.io/common/pkg/filewatcher/filewatcher.go
  vendor/modules.txt
Labels: approved, cla: yes

#14021 Fix build break
  README.md
  galley/cmd/galley/cmd/server.go
  galley/pkg/crd/validation/validation.go
  galley/pkg/runtime/processor.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/server/server.go
  mixer/cmd/mixs/cmd/probe.go
  mixer/pkg/config/crd/init.go
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
  mixer/pkg/config/mcp/backend.go
  mixer/pkg/config/store/store.go
  mixer/pkg/runtime/runtime.go
  mixer/pkg/runtime/runtime_test.go
  mixer/pkg/server/args.go
  mixer/pkg/server/server.go
  pilot/cmd/sidecar-injector/main.go
  security/cmd/istio_ca/main.go
  security/pkg/cmd/probe.go
Labels: approved, cla: yes

#13955 Fix issue #13728. Create separate connectionManager for different filter chains
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#14015 [Test Framework] Refactor Echo API to hide waiting
  pkg/test/framework/components/echo/common/envoy_test.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/native/builder.go
  pkg/test/framework/components/echo/native/instance.go
  tests/integration/echo/echo_test.go
  tests/integration/pilot/locality/failover_test.go
  tests/integration/pilot/locality/main_test.go
  tests/integration/pilot/locality/prioritized_test.go
  tests/integration/pilot/outboundtrafficpolicy/helper.go
  tests/integration/security/authn/permissive_test.go
  tests/integration/security/healthcheck/mtls_healthcheck_test.go
  tests/integration/security/rbac/v1/group/group_test.go
  tests/integration/security/rbac/v2/basic/basic_test.go
  tests/integration/security/rbac/v2/basic/extended_test.go
  tests/integration/security/rbac/v2/group/group_test.go
  tests/integration/security/reachability/reachability_test.go
  tests/integration/security/sds_citadel_flow/sds_citadel_flow_test.go
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
Labels: approved, cla: yes, lgtm

#13961 [Test Framework] Galley: Allow nil namespace
  pkg/test/framework/components/galley/kube.go
Labels: approved, cla: yes, lgtm

#14023 [Testing] Merge YAML utilities
  pkg/test/config.go
  pkg/test/deployment/attrmanifest.go
  pkg/test/framework/components/istio/deployment.go
  pkg/test/framework/components/istio/deployment_test.go
  pkg/test/kube/kubectl.go
  pkg/test/util/yml/apply.go
  pkg/test/util/yml/parts.go
  pkg/test/util/yml/parts_test.go
  tests/integration/mixer/policy/ratelimiting_test.go
Labels: approved, cla: yes, lgtm

#13919 Fix ProcessStream error reporting on cancel
  pkg/mcp/source/source.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13945 [Test Framework] Support annotations in Echo component
  pkg/test/framework/components/echo/annotations.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/echo/native/workload.go
  tests/integration/echo/echo_test.go
  tests/integration/pilot/locality/main_test.go
  tests/integration/pilot/outboundtrafficpolicy/helper.go
  tests/integration/security/authn/permissive_test.go
  tests/integration/security/rbac/v1/group/group_test.go
  tests/integration/security/rbac/v2/basic/basic_test.go
  tests/integration/security/rbac/v2/basic/extended_test.go
  tests/integration/security/rbac/v2/group/group_test.go
  tests/integration/security/reachability/reachability_test.go
  tests/integration/security/sds_citadel_flow/sds_citadel_flow_test.go
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
Labels: approved, cla: yes, lgtm

#13997 Add Prow scripts for running Mixer integration tests.
  prow/integ-mixer-k8s-presubmit-tests.sh
  prow/integ-mixer-local-presubmit-tests.sh
Labels: approved, cla: yes, lgtm

#13985 fixing issue 13980
  tests/e2e/tests/simple/testdata/nginx/nginx.yaml.tmpl
  tools/packaging/common/istio-iptables.sh
Labels: approved, cla: yes, lgtm

#14056 [Test Framework] Fix call stack in TestContext
  pkg/test/framework/testcontext.go
Labels: approved, cla: yes, lgtm

#13763 consolidate ratelimit test samples
  bin/check_samples.sh
  pkg/test/framework/components/bookinfo/configs.go
  samples/bookinfo/policy/mixer-rule-productpage-redis-quota-fixed-window.yaml
  samples/bookinfo/policy/mixer-rule-ratings-redis-quota-fixed-window.yaml
  samples/bookinfo/policy/mixer-rule-ratings-redis-quota-rolling-window.yaml
  samples/bookinfo/policy/prometheus-adapter-deployment.yaml
  samples/bookinfo/policy/prometheus-oop-rule.yaml
  samples/fortio/stackdriver.yaml
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/stackdriver/adapter.yaml
  tests/e2e/tests/stackdriver/stackdriver_test.go
  tests/integration/mixer/policy/ratelimiting_test.go
Labels: approved, cla: yes, lgtm

#14078 Making simpleTest works in KinD
  prow/e2e-kind-simpleTests.sh
  prow/e2e-kind-suite.sh
  tests/e2e/local/kind/README.md
Labels: approved, cla: yes, lgtm

#14079 [Citadel Agent on VM] Fix typo and update comment
  security/pkg/nodeagent/envvar/envvar.go
Labels: approved, cla: yes, lgtm

#14044 Remove unused circle targets
  .circleci/config.yml
Labels: approved, area/test and release, cla: yes, lgtm

#14085 fix kind simpletest
  prow/e2e-kind-suite.sh
Labels: approved, cla: yes, lgtm

#14041 Merge release-1.1 into master
  install/kubernetes/helm/istio/charts/certmanager/values.yaml
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/galley/values.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/_affinity.tpl
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  install/kubernetes/helm/istio/charts/grafana/values.yaml
  install/kubernetes/helm/istio/charts/istiocoredns/values.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
  install/kubernetes/helm/istio/charts/mixer/values.yaml
  install/kubernetes/helm/istio/charts/nodeagent/values.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/values.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/values.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/values.yaml
  install/kubernetes/helm/istio/charts/tracing/values.yaml
  install/kubernetes/helm/istio/templates/_affinity.tpl
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/model.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/context.go
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/features/pilot/pilot.go
  release/gcb/run_monthly_release.sh
  samples/bookinfo/networking/egress-rule-google-apis.yaml
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/pkg/nodeagent/secretfetcher/secretfetcher_test.go
  tests/integration/pilot/locality/main_test.go
  tests/integration/security/citadel_agent/vault/README.md
  tests/integration/security/citadel_agent/vault/client_test.go
  tests/integration/security/healthcheck/main_test.go
  tests/integration/security/rbac/v1/group/main_test.go
  tests/integration/security/rbac/v2/basic/main_test.go
  tests/integration/security/rbac/v2/group/main_test.go
  tests/integration/security/reachability/main_test.go
  tests/integration/security/sds_citadel_flow/main_test.go
  tests/integration/security/sds_vault_flow/main_test.go
  tools/packaging/common/envoy_bootstrap_v2.json
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.go
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.html
  vendor/istio.io/api/networking/v1alpha3/sidecar.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
Labels: cla: yes, do-not-merge/hold

#14080 Sort Config in stable ordering
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/proxy/envoy/v2/rds.go
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes, lgtm

#14059 Add application port option for gateways
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/util/listeners.go
Labels: approved, cla: yes, lgtm

#13934 don't disconnect sds connection when receive empty resourcename
  security/pkg/nodeagent/sds/sdsservice.go
Labels: approved, cla: yes, lgtm

#13999 Add mysqlfilter feature flag
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes, lgtm

#14077 Update ingress requests and limits
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/job.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/user-volume.yaml.injected
Labels: approved, cla: yes, lgtm

#13894 backport of 13893
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
Labels: approved, cla: yes, lgtm

#13633 move verify-install from experiment
  istioctl/cmd/root.go
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/pre-check_test.go
  istioctl/pkg/install/verify.go
Labels: approved, cla: yes, lgtm

#13696 Show mcp client synced status in configz page
  pkg/mcp/configz/server/assets/assets.gen.go
  pkg/mcp/configz/server/assets/templates/config.html
  pkg/mcp/configz/server/configz_test.go
  pkg/mcp/snapshot/snapshot.go
  pkg/mcp/snapshot/snapshot_test.go
  pkg/mcp/source/source.go
  pkg/mcp/source/source_test.go
Labels: approved, cla: yes, lgtm

#13576 refactor eds building cluster LoadAssignment
  pilot/pkg/model/service.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#13966 bump k8s version when setup minikube
  tests/e2e/local/minikube/setup_host.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#14090 Fix Workdir calculation in the makefile.
  tests/integration/tests.mk
Labels: approved, cla: yes, lgtm

#14089 crd multiple versions
  galley/pkg/metadata/kube/types.go
  galley/pkg/source/kube/builtin/source_test.go
  galley/pkg/source/kube/dynamic/source.go
  galley/pkg/source/kube/schema/check/check.go
  galley/pkg/source/kube/schema/instance_test.go
  galley/pkg/source/kube/schema/resourcespec.go
  galley/pkg/source/kube/schema/resourcespec_test.go
  galley/tools/gen-meta/main.go
  galley/tools/gen-meta/metadata.yaml
Labels: approved, cla: yes, lgtm

#14050 Fix outbound traffic test
  tests/integration/pilot/outboundtrafficpolicy/helper.go
Labels: approved, cla: yes, lgtm

#14086 fix stackdriver config in post-submit test
  samples/fortio/stackdriver.yaml
  tests/e2e/tests/stackdriver/stackdriver_test.go
Labels: approved, cla: yes, lgtm

#13872 Initial istioctl integration test in new framework
  istioctl/cmd/istioctl/istioctl_test.go
  pkg/test/framework/components/istioctl/istioctl.go
  pkg/test/framework/components/istioctl/kube.go
  pkg/test/framework/components/istioctl/native.go
  tests/integration/istioctl/istioctl_test.go
Labels: approved, cla: yes, lgtm

#13734 Add version to Galley MCP dial out metadata.
  galley/pkg/server/callout.go
  galley/pkg/server/callout_test.go
Labels: approved, cla: yes, lgtm

#14093 Highlight the right avenues for community support.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: approved, cla: yes

#13732 Add Namespaces to list of resources Galley can serve over MCP.
  galley/pkg/metadata/kube/types.go
  galley/pkg/metadata/types.gen.go
  galley/pkg/source/kube/builtin/testdata/namespace.yaml
  galley/pkg/source/kube/builtin/types.go
  galley/pkg/source/kube/builtin/types_test.go
  galley/pkg/testing/mock/corev1.go
  galley/pkg/testing/mock/kube_interface.go
  galley/pkg/testing/mock/namespaces.go
  galley/pkg/testing/testdata/dataset.gen.go
  galley/pkg/testing/testdata/dataset/core/v1/namespace.yaml
  galley/pkg/testing/testdata/dataset/core/v1/namespace_expected.json
  galley/tools/gen-meta/metadata.yaml
Labels: approved, cla: yes, lgtm

#13807 fix: Update EDS only after ClusterDiscoveryType is known
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13772 cherry pick: #13745 change endpoint logs to debug level
  pilot/pkg/proxy/envoy/v2/ep_filters.go
Labels: cla: yes

#14107 Add ability for Galley to serve Mesh Config.
  galley/pkg/runtime/config.go
  galley/pkg/runtime/processor.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/runtime/state.go
  galley/pkg/runtime/state_test.go
  galley/pkg/server/server.go
  galley/pkg/source/fs/source_test.go
  galley/pkg/testing/testdata/dataset.gen.go
  galley/pkg/testing/testdata/dataset/mesh.istio.io/v1alpha1/meshconfig.yaml
  galley/pkg/testing/testdata/dataset/mesh.istio.io/v1alpha1/meshconfig_expected.json
Labels: approved, cla: yes, lgtm

#13909 Correctly handle pod deletion
  pilot/pkg/serviceregistry/kube/pod.go
Labels: approved, cla: yes, lgtm

#14149 [Test Framework] Fix panic in echo test
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/testcontext.go
Labels: approved, cla: yes, lgtm

#14166 [Test Framework] Fix outbound check for Echo
  pkg/test/framework/components/echo/common/envoy.go
Labels: approved, cla: yes, lgtm

#14076 [Test Framework] Support parallel tests
  pkg/test/framework/integration/component.go
  pkg/test/framework/integration/framework_test.go
  pkg/test/framework/integration/main_test.go
  pkg/test/framework/scope.go
  pkg/test/framework/test.go
  pkg/test/framework/testcontext.go
  tests/integration/README.md
  tests/integration/echo/echo_test.go
Labels: approved, cla: yes, lgtm

#14165 Update Vendor Files to match go.mod
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.go
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.html
  vendor/istio.io/api/networking/v1alpha3/sidecar.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/modules.txt
Labels: approved, cla: yes, lgtm

#14170 Refactor Galley test data set.
  galley/testdata/Readme.md
  galley/testdata/conversion/dataset.gen.go
  galley/testdata/conversion/dataset.go
  galley/testdata/conversion/dataset/config.istio.io/v1alpha2/circonus.yaml
  galley/testdata/conversion/dataset/config.istio.io/v1alpha2/circonus_expected.json
  galley/testdata/conversion/dataset/core/v1/namespace.yaml
  galley/testdata/conversion/dataset/core/v1/namespace_expected.json
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_basic.yaml
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_basic_expected.json
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_basic_meshconfig.yaml
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_merge_0.yaml
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_merge_0_expected.json
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_merge_0_meshconfig.yaml
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_merge_1.yaml
  galley/testdata/conversion/dataset/extensions/v1beta1/ingress_merge_1_expected.json
  galley/testdata/conversion/dataset/mesh.istio.io/v1alpha1/meshconfig.yaml
  galley/testdata/conversion/dataset/mesh.istio.io/v1alpha1/meshconfig_expected.json
  galley/testdata/conversion/dataset/networking.istio.io/v1alpha3/destinationRule.yaml
  galley/testdata/conversion/dataset/networking.istio.io/v1alpha3/destinationRule_expected.json
  galley/testdata/conversion/dataset/networking.istio.io/v1alpha3/gateway.yaml
  galley/testdata/conversion/dataset/networking.istio.io/v1alpha3/gateway_expected.json
  galley/testdata/conversion/dataset/networking.istio.io/v1alpha3/synthetic/serviceEntry.yaml
  galley/testdata/conversion/dataset/networking.istio.io/v1alpha3/synthetic/serviceEntry_expected.json
  galley/testdata/conversion/load.go
  galley/testdata/conversion/testinfo.go
  galley/testdata/validation/dataset.gen.go
  galley/testdata/validation/dataset.go
  galley/testdata/validation/dataset/authentication-v1alpha1-Policy-invalid.yaml
  galley/testdata/validation/dataset/authentication-v1alpha1-Policy-valid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-HTTPAPISpec-invalid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-HTTPAPISpec-valid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-HTTPAPISpecBinding-invalid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-HTTPAPISpecBinding-valid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-QuotaSpec-invalid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-QuotaSpec-valid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-QuotaSpecBinding-invalid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-QuotaSpecBinding-valid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-rule-invalid.yaml
  galley/testdata/validation/dataset/config-v1alpha2-rule-valid.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-DestinationRule-invalid.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-DestinationRule-valid.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-Gateway-invalid.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-Gateway-valid.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-ServiceEntry-invalid-skipped.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-ServiceEntry-valid-skipped.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-VirtualService-invalid.yaml
  galley/testdata/validation/dataset/networking-v1alpha3-VirtualService-valid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceRole-invalid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceRole-valid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceRoleBinding-invalid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceRoleBinding-valid.yaml
  tests/integration/galley/conversion_test.go
  tests/integration/galley/data.gen_test.go
  tests/integration/galley/validation_test.go
Labels: approved, cla: yes, lgtm

#13673 Integration test for traffic shifting
  tests/integration/pilot/trafficshifting/helper.go
  tests/integration/pilot/trafficshifting/testdata/traffic-shifting.yaml
  tests/integration/pilot/trafficshifting/traffic_shifting_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13948 Improve xDS logging consistency
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: approved, cla: yes, lgtm

#14181 attempt to fix flaky helm redis install
  pkg/test/env/istio.go
  pkg/test/framework/components/redis/kube.go
  pkg/test/framework/components/redis/redis.yaml
Labels: approved, cla: yes, lgtm

#14192 Dedupe Redis tests in e2e tests and new integration test framework
  tests/e2e/tests/mixer/mixer_test.go
Labels: approved, cla: yes, lgtm

#14209 Allow unknown flags in pilot-agent
  pilot/cmd/pilot-agent/main.go
Labels: approved, cla: yes, lgtm
