Repository istio/istio, pull requests merged in 2019-03, with the labels that each got.

#12076 Refactor e2e yaml value files
  .circleci/config.yml
  .gitignore
  Makefile
  install/kubernetes/helm/istio/example-values/README.md
  install/kubernetes/helm/istio/example-values/values-istio-example-sds-vault.yaml
  install/kubernetes/helm/istio/example-values/values-istio-gateways.yaml
  install/kubernetes/helm/istio/example-values/values-istio-googleca.yaml
  install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml
  install/kubernetes/helm/istio/test-values/README.md
  install/kubernetes/helm/istio/test-values/values-e2e.yaml
  install/kubernetes/helm/istio/test-values/values-istio-auth-mcp.yaml
  install/kubernetes/helm/istio/test-values/values-istio-auth-multicluster.yaml
  install/kubernetes/helm/istio/test-values/values-istio-auth-non-mcp.yaml
  install/kubernetes/helm/istio/test-values/values-istio-auth-sds.yaml
  install/kubernetes/helm/istio/test-values/values-istio-auth.yaml
  install/kubernetes/helm/istio/test-values/values-istio-mcp.yaml
  install/kubernetes/helm/istio/test-values/values-istio-multicluster.yaml
  install/kubernetes/helm/istio/test-values/values-istio-non-mcp.yaml
  install/kubernetes/helm/istio/test-values/values-istio-one-namespace-auth.yaml
  install/kubernetes/helm/istio/test-values/values-istio-one-namespace-trust-domain.yaml
  install/kubernetes/helm/istio/test-values/values-istio-one-namespace.yaml
  install/kubernetes/helm/istio/test-values/values-istio.yaml
  install/updateVersion.sh
  pkg/test/framework/runtime/components/environment/kube/settings.go
  release/create_release_archives.sh
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#12161 Do not setup SNI match if service has a VIP
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/tls.go
Labels: approved, cla: yes, lgtm

#12180 Doc fixes.
  mixer/adapter/kubernetesenv/config/adapter.kubernetesenv.config.pb.html
  mixer/adapter/kubernetesenv/config/config.pb.go
  mixer/adapter/kubernetesenv/config/config.proto
  mixer/adapter/kubernetesenv/config/config.proto_descriptor
  mixer/adapter/kubernetesenv/config/kubernetesenv.yaml
Labels: approved, cla: yes

#12177 fix mixer and pilot upgrade issues.
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
Labels: approved, cla: yes

#12104 add namespace parameter support
  istioctl/cmd/istioctl/proxystatus.go
  istioctl/cmd/istioctl/proxystatus_test.go
Labels: approved, cla: yes, lgtm

#11859 Move mixer check annotation to model with defaults
  pilot/pkg/model/context.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
Labels: approved, cla: yes, ok-to-test

#11773 Add an e2e test to validate fault injection telemetry.
  samples/bookinfo/networking/fault-injection-details-v1.yaml
  tests/e2e/tests/mixer/mixer_test.go
Labels: cla: yes, lgtm

#11877 Updates tests to match CNI install procedure
  Makefile
  prow/e2e-simpleTests-cni.sh
  prow/e2e-suite.sh
  prow/lib.sh
  tests/istio.mk
Labels: area/environments, area/test and release, cla: yes, lgtm

#12125 [Galley] Standardize worker thread lifecycles
  galley/pkg/runtime/processor.go
  galley/pkg/source/fs/source.go
  galley/pkg/source/kube/builtin/source.go
  galley/pkg/source/kube/builtin/source_test.go
  galley/pkg/source/kube/dynamic/source.go
  galley/pkg/source/kube/dynamic/source_test.go
  galley/pkg/util/worker.go
  galley/pkg/util/worker_test.go
Labels: approved, cla: yes, lgtm

#12050 Implement AuthorizationPolicy with workload selector.
  pilot/pkg/model/authorization.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/authz/rbac_v2.go
  pilot/pkg/networking/plugin/authz/rbac_v2_test.go
  pilot/pkg/networking/plugin/authz/test_helper.go
Labels: approved, cla: yes, lgtm

#12191 Update to grafana 6.0.0
  install/kubernetes/helm/istio/charts/grafana/values.yaml
Labels: approved, cla: yes, lgtm

#12114 Turn policy off by default
  Makefile
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/values.yaml
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/values.yaml
  install/kubernetes/helm/istio/test-values/values-e2e.yaml
  install/kubernetes/helm/istio/values-istio-demo-auth.yaml
  install/kubernetes/helm/istio/values-istio-demo-common.yaml
  install/kubernetes/helm/istio/values-istio-demo.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/kube/inject/testdata/inject/app_probe/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/app_probe/hello-readiness.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/app_probe/named_port.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/app_probe/one_container.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/app_probe/ready_only.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/app_probe/two_container.yaml.injected
Labels: cla: yes

#12213 Update deps for 1.1rc2
  Gopkg.lock
  istio.deps
  vendor/istio.io/api/Makefile
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/mesh/v1alpha1/network.pb.go
  vendor/istio.io/api/mesh/v1alpha1/network.proto
  vendor/istio.io/api/mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
  vendor/istio.io/api/mixer/adapter/model/v1beta1/template.pb.go
  vendor/istio.io/api/mixer/adapter/model/v1beta1/template.proto
  vendor/istio.io/api/mixer/v1/config/client/client_config.pb.go
  vendor/istio.io/api/mixer/v1/config/client/client_config.proto
  vendor/istio.io/api/mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.pb.go
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.proto
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/istio.networking.v1alpha3.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.go
  vendor/istio.io/api/networking/v1alpha3/sidecar.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/policy/v1beta1/cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/policy/v1beta1/istio.policy.v1beta1.pb.html
  vendor/istio.io/api/policy/v1beta1/type.pb.go
  vendor/istio.io/api/policy/v1beta1/type.proto
  vendor/istio.io/api/tools/all/Dockerfile
  vendor/istio.io/api/tools/all/build-and-push.sh
  vendor/istio.io/api/tools/protoc/build-and-push.sh
Labels: cla: yes, lgtm

#12214 pilot should wait for kubernetes cache sync before serving
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/clusterregistry/multicluster.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pkg/kube/secretcontroller/secretcontroller.go
Labels: cla: yes

#12206 Remove test mgmt ports
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/mem.go
  tests/integration2/pilot/sidecar_api_test.go
Labels: approved, cla: yes

#12225 guard mysql proxy with version check
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: approved, cla: yes

#11940 Various fixes for the Multicluster e2e test [release-1.1]
  install/kubernetes/helm/istio/test-values/values-istio-auth-multicluster.yaml
  install/kubernetes/helm/istio/test-values/values-istio-multicluster.yaml
  prow/istio-pilot-multicluster-e2e.sh
  tests/e2e/framework/kubernetes.go
  tests/e2e/framework/multicluster.go
  tests/e2e/tests/pilot/mesh_config_verify_test.go
Labels: cla: yes, lgtm

#12228 Fix pilot grpc failure in Consul
  install/consul/templates/istio.yaml.tmpl
Labels: cla: yes, lgtm

#12212 Handle command aliases correctly in generated docs.
  pkg/collateral/control.go
Labels: approved, cla: yes

#12188 Enable retries for specified status codes
  pilot/pkg/networking/core/v1alpha3/route/retry/retry.go
  pilot/pkg/proxy/envoy/v2/testdata/none_rds.json
Labels: approved, cla: yes, lgtm, ok-to-test

#12233 Adding sidecars to validating webhook configuration
  install/kubernetes/helm/istio/charts/galley/templates/validatingwebhookconfiguration.yaml.tpl
Labels: approved, cla: yes, lgtm

#12234 Fix destination rule selection issues
  install/kubernetes/helm/istio/templates/configmap.yaml
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  tests/e2e/tests/pilot/routing_test.go
Labels: approved, cla: yes, lgtm

#12173 fix istio chart upgrade issues.
  install/kubernetes/helm/istio/charts/security/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/security/templates/enable-mesh-mtls.yaml
  install/kubernetes/helm/istio/charts/security/templates/enable-mesh-permissive.yaml
  install/kubernetes/helm/istio/values-istio-remote.yaml
Labels: approved, cla: yes, lgtm

#12236 Disable the Redis network filter
  Gopkg.lock
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pkg/adsc/adsc.go
Labels: cla: yes

#11914 mixer: enable roundrobin client gRPC LB
  Gopkg.lock
  mixer/pkg/protobuf/yaml/dynamic/handler.go
Labels: cla: yes, lgtm

#12218 Support offline running productpage by packing js and css in image
  samples/bookinfo/src/productpage/Dockerfile
  samples/bookinfo/src/productpage/static/bootstrap-theme.min.css
  samples/bookinfo/src/productpage/static/bootstrap.min.css
  samples/bookinfo/src/productpage/static/bootstrap.min.js
  samples/bookinfo/src/productpage/static/jquery.min.js
  samples/bookinfo/src/productpage/templates/productpage.html
Labels: approved, cla: yes, lgtm, ok-to-test

#12110 Allow local loopback traffic not to be redirected
  tools/deb/istio-iptables.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#11897 Add pilot-agent support for configuring envoy to use the metrics service
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/context.go
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pkg/bootstrap/bootstrap_config.go
  pkg/bootstrap/testdata/all.proto
  pkg/bootstrap/testdata/all_golden.json
  tools/deb/envoy_bootstrap_v2.json
Labels: cla: yes, ok-to-test

#12263 Fix envoy filter matching logic
  pilot/pkg/networking/core/v1alpha3/envoyfilter.go
Labels: approved, cla: yes, lgtm

#12271 Add e2e tests for Authz v2
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/istio_rbac_v2_test.go
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-rbac-v2-rules.yaml.tmpl
Labels: approved, cla: yes, lgtm

#12241 Disable policy check, but still install policy
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#12288 fix gateway upgrade issue.
  install/kubernetes/helm/istio/charts/grafana/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/gateway.yaml
Labels: approved, cla: yes

#11916 Unblock ip6 tables to allow ipv6 traffic
  tools/deb/istio-iptables.sh
Labels: cla: yes

#11353 Make code more reusable in other contexts
  pkg/mcp/internal/size.go
  pkg/mcp/sink/client_sink.go
  pkg/mcp/sink/server_sink.go
  pkg/mcp/sink/sink.go
  pkg/mcp/sink/sink_test.go
  pkg/mcp/source/client_source.go
  pkg/mcp/source/client_source_test.go
  pkg/mcp/source/server_source.go
  pkg/mcp/source/server_source_test.go
  pkg/mcp/source/source.go
  pkg/mcp/source/source_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#11903 Adjust window for irate calculation to support large cluster envs
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-service-dashboard.json
  install/kubernetes/helm/istio/charts/grafana/dashboards/istio-workload-dashboard.json
Labels: approved, cla: yes, lgtm

#12278 wait for service and config cache sync before serving http and grpc
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/serviceregistry/kube/controller.go
  pkg/features/pilot/pilot.go
Labels: cla: yes

#12272 implement configurable dns refresh rate for strict dns clusters in envoy
  Gopkg.lock
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/values.yaml
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.go
  vendor/istio.io/api/networking/v1alpha3/sidecar.proto
  vendor/istio.io/api/proto.lock
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: area/networking, cla: yes

#12279 fix crash caused by unsure resource sequence
  pilot/pkg/serviceregistry/kube/controller.go
Labels: approved, cla: yes, lgtm

#12284 Remove legacy "ingress" component from Istio installer
  install/kubernetes/ansible/istio/tasks/change_scc.yml
  install/kubernetes/helm/istio/README.md
  install/kubernetes/helm/istio/charts/ingress/Chart.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/_helpers.tpl
  install/kubernetes/helm/istio/charts/ingress/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/clusterrolebinding.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/poddisruptionbudget.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/service.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/serviceaccount.yaml
  install/kubernetes/helm/istio/charts/ingress/values.yaml
  install/kubernetes/helm/istio/example-values/values-istio-gateways.yaml
  install/kubernetes/helm/istio/requirements.yaml
  install/kubernetes/helm/istio/templates/configmap.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#12309 Remove all add-on gateway configuration options
  install/kubernetes/helm/istio/charts/grafana/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/grafana/values.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/prometheus/values.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/gateway.yaml
  install/kubernetes/helm/istio/charts/tracing/values.yaml
Labels: approved, cla: yes, lgtm

#12280 merge the common content in demo values file
  install/kubernetes/helm/istio/values-istio-demo-common.yaml
  release/create_release_archives.sh
Labels: approved, cla: yes, lgtm

#12281 Correct TestAdmitPilot Case
  galley/pkg/crd/validation/webhook_test.go
Labels: approved, cla: yes, lgtm

#12273 Fix pilot grpc failure in Consul
  install/consul/templates/istio.yaml.tmpl
Labels: approved, cla: yes, lgtm

#12314 Create a new shard if none exists during service account mapping
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#12337 Proxy sha in istio. Api sha is already correct
  istio.deps
Labels: cla: yes, lgtm

#12347 fix wrong link for mixer
  mixer/README.md
Labels: cla: yes, ok-to-test

#12361 Update OWNERS
  mixer/OWNERS
Labels: cla: yes

#12346 fix regression causing 404s..
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
Labels: cla: no

#12363 Revert "fix DNs suffix extraction algorithm"
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
Labels: approved, cla: yes

#12365 Revert #11522: fix routing when DNS is resolved
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/main_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/serviceregistry/kube/controller_test.go
  pilot/pkg/serviceregistry/memory/discovery_mock.go
  tests/integration2/pilot/sidecar_api_test.go
Labels: approved, cla: yes, lgtm

#11740 Change IP addresses to show up as strings in accesslog
  mixer/adapter/stackdriver/log/log.go
  mixer/adapter/stackdriver/log/log_test.go
  mixer/pkg/adapter/instanceUtil.go
Labels: approved, cla: yes, lgtm

#12379 fix potential pilot panic and memory leak
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: approved, cla: yes, lgtm

#12378 Fix (rare) Pilot panic during config dump
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, cla: yes

#12345 fix reviews docker image build issue.
  samples/bookinfo/src/build-services.sh
Labels: cla: yes

#12250 fix bug: allow specify cpu/memory resource requests separately
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
Labels: approved, cla: yes, lgtm

#12189 Configuration: no longer hardcode mesh certs
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/main_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/pkg/proxy/envoy/watcher_test.go
Labels: approved, cla: yes, ok-to-test

#12393 Removing the hard-coded istio-system in endpoints.yaml
  install/kubernetes/helm/istio/templates/endpoints.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#12392 Helm customize sidecarInjectorWebhook & security & servicegraph image
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#12397 Don't fail sidecar validation on missing port name
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: approved, cla: yes

#12398 add the remote flag to the istioctl version command
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla: yes, needs-ok-to-test

#12304 Disable precomputation of CDS
  install/kubernetes/helm/istio/charts/pilot/values.yaml
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/configgen.go
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes, lgtm

#12167 [Galley] Introduce processing.Listener
  galley/pkg/runtime/processing/listener.go
  galley/pkg/runtime/processor.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/runtime/state.go
  galley/pkg/runtime/state_test.go
Labels: approved, cla: yes, lgtm

#12401 No longer build 0.8, but do 1.1
  .circleci/config.yml
Labels: approved, cla: yes

#12387 bump coredns plugin version
  install/kubernetes/helm/istio/charts/istiocoredns/values.yaml
Labels: approved, cla: yes, lgtm

#12364 Patch #11986 to master
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/customdnsname.go
  security/pkg/k8s/controller/customdnsname_test.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: approved, cla: human-approved, cla: yes, lgtm

#12366 remove deprecated service graph off demo profile
  install/kubernetes/helm/istio/values-istio-demo-common.yaml
Labels: approved, cla: yes, lgtm

#12202 Support using labels in authentication policy
  pilot/pkg/model/authentication.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#12340 fix EndpointShardsByService concurrent access
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#12330 Fix broken doc link
  mixer/adapter/kubernetesenv/config/adapter.kubernetesenv.config.pb.html
  mixer/adapter/kubernetesenv/config/config.pb.go
  mixer/adapter/kubernetesenv/config/config.proto
  mixer/adapter/kubernetesenv/config/config.proto_descriptor
  mixer/adapter/kubernetesenv/config/kubernetesenv.yaml
  mixer/adapter/kubernetesenv/template/template.yaml
  mixer/adapter/kubernetesenv/template/template_handler_service.descriptor_set
  mixer/adapter/kubernetesenv/template/template_proto.descriptor_set
Labels: approved, cla: yes, lgtm

#12353 Add Service to Fortio so that the sidecar can become ready.
  samples/httpbin/sample-client/fortio-deploy.yaml
Labels: approved, cla: yes, lgtm

#12384 Add permission to apps API group in security Helm job
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
Labels: approved, cla: yes, lgtm

#12377 fix panic caused by invalid multi-cluster secret
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
  pilot/pkg/config/clusterregistry/multicluster_test.go
  pkg/kube/secretcontroller/secretcontroller.go
  pkg/kube/secretcontroller/secretcontroller_test.go
Labels: cla: yes

#12425 locally running address resolution test can fail
  pilot/pkg/proxy/resolve.go
  pilot/pkg/proxy/resolve_test.go
Labels: approved, cla: yes, lgtm

#12428 Update istio/proxy for 1.1rc4
  istio.deps
Labels: approved, cla: yes

#12299 Add additional fields for ServiceRole, issue: #11516 (#11712)
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/authz/rbac_test.go
  pilot/pkg/networking/plugin/authz/test_helper.go
  pilot/pkg/networking/plugin/authz/util.go
  pilot/pkg/networking/plugin/authz/util_test.go
  pilot/pkg/networking/plugin/authz/validate.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#12433 Use syncmap to protect fileBasedMetadataConfigAnyMap from race conditions
  pilot/pkg/model/authentication.go
Labels: approved, cla: yes, lgtm

#12419 add missing .pb.go to list of generated files
  .gitattributes
Labels: approved, cla: yes, lgtm

#12416 Fix bad doc links.
  mixer/adapter/cloudwatch/config/adapter.cloudwatch.config.pb.html
  mixer/adapter/cloudwatch/config/cloudwatch.yaml
  mixer/adapter/cloudwatch/config/config.pb.go
  mixer/adapter/cloudwatch/config/config.proto
  mixer/adapter/cloudwatch/config/config.proto_descriptor
  mixer/adapter/zipkin/config/adapter.zipkin.config.pb.html
  mixer/adapter/zipkin/config/config.pb.go
  mixer/adapter/zipkin/config/config.proto
  mixer/adapter/zipkin/config/config.proto_descriptor
Labels: approved, cla: yes

#12169 update stackdriver example operator config
  mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml
Labels: approved, cla: yes, lgtm

#12462 use syncmap to avoid race conditions (#12433)
  pilot/pkg/model/authentication.go
Labels: approved, cla: yes, lgtm

#12412 Disable "xDS marshalling to Any" feature.
  pilot/pkg/networking/core/v1alpha3/envoyfilter.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/util/util.go
  pkg/features/pilot/pilot.go
Labels: cla: yes, lgtm

#12476 Do not reject entire batch of updates, if items get past validation.
  pilot/pkg/config/coredatamodel/controller.go
  pilot/pkg/config/coredatamodel/controller_test.go
Labels: approved, cla: yes, lgtm

#12468 Do not override certmanager CRDs
  install/kubernetes/helm/istio-init/templates/configmap-crd-certmanager-10.yaml
  install/kubernetes/helm/istio-init/templates/configmap-crd-certmanager-11.yaml
  install/kubernetes/helm/istio-init/templates/job-crd-certmanager-10.yaml
  install/kubernetes/helm/istio-init/templates/job-crd-certmanager-11.yaml
  install/kubernetes/helm/istio-init/values.yaml
Labels: approved, cla: yes, lgtm

#12484 Add helm resource-policy to CRDs to prevent deletion
  install/kubernetes/helm/istio-init/files/crd-10.yaml
  install/kubernetes/helm/istio-init/files/crd-11.yaml
  install/kubernetes/helm/istio-init/files/crd-certmanager-10.yaml
  install/kubernetes/helm/istio-init/files/crd-certmanager-11.yaml
Labels: approved, cla: yes

#12485 Pull in api and proxy for 1.1rc5
  Gopkg.lock
  istio.deps
  vendor/istio.io/api/authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  vendor/istio.io/api/authentication/v1alpha1/policy.pb.go
  vendor/istio.io/api/authentication/v1alpha1/policy.proto
  vendor/istio.io/api/dictionaries/custom.txt
  vendor/istio.io/api/envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  vendor/istio.io/api/envoy/config/filter/http/jwt_auth/v2alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/mesh/v1alpha1/network.pb.go
  vendor/istio.io/api/mesh/v1alpha1/network.proto
  vendor/istio.io/api/mesh/v1alpha1/proxy.pb.go
  vendor/istio.io/api/mesh/v1alpha1/proxy.proto
  vendor/istio.io/api/mixer/v1/attributes.pb.go
  vendor/istio.io/api/mixer/v1/attributes.proto
  vendor/istio.io/api/mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  vendor/istio.io/api/mixer/v1/config/client/service.proto
  vendor/istio.io/api/mixer/v1/istio.mixer.v1.pb.html
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.html
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.html
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.go
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.html
  vendor/istio.io/api/networking/v1alpha3/sidecar.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/policy/v1beta1/cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/policy/v1beta1/istio.policy.v1beta1.pb.html
  vendor/istio.io/api/rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  vendor/istio.io/api/rbac/v1alpha1/rbac.pb.go
  vendor/istio.io/api/rbac/v1alpha1/rbac.proto
Labels: cla: yes, lgtm

#12447 enable egressgateway in multicluster deployment.
  install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml
Labels: approved, cla: yes, lgtm

#12449 Validate Citadel certificate can be used for a CA
  security/pkg/pki/ca/ca.go
  security/pkg/pki/util/keycertbundle_test.go
Labels: approved, cla: yes, lgtm

#12375 remove gometalinter
  .gitignore
  Gopkg.lock
  Gopkg.toml
  bin/linters.sh
  codecov.skip
  mixer/tools/adapterlinter/gometalinter.json
  mixer/tools/adapterlinter/main.go
  mixer/tools/adapterlinter/main_test.go
  pilot/docker/Dockerfile.lint
  tests/util/checker/checker.go
  tests/util/checker/testlinter/gometalinter.json
  tests/util/checker/testlinter/testlinter.json
  tests/util/checker/testlinter/unittest_lint_test.go
  vendor/github.com/client9/misspell/.gitignore
  vendor/github.com/client9/misspell/.travis.yml
  vendor/github.com/client9/misspell/Dockerfile
  vendor/github.com/client9/misspell/Gopkg.lock
  vendor/github.com/client9/misspell/Gopkg.toml
  vendor/github.com/client9/misspell/LICENSE
  vendor/github.com/client9/misspell/Makefile
  vendor/github.com/client9/misspell/README.md
  vendor/github.com/client9/misspell/RELEASE-HOWTO.md
  vendor/github.com/client9/misspell/ascii.go
  vendor/github.com/client9/misspell/case.go
  vendor/github.com/client9/misspell/cmd/misspell/main.go
  vendor/github.com/client9/misspell/goreleaser.yml
  vendor/github.com/client9/misspell/ignore/glob.go
  vendor/github.com/client9/misspell/ignore/parse.go
  vendor/github.com/client9/misspell/install-misspell.sh
  vendor/github.com/client9/misspell/legal.go
  vendor/github.com/client9/misspell/mime.go
  vendor/github.com/client9/misspell/notwords.go
  vendor/github.com/client9/misspell/replace.go
  vendor/github.com/client9/misspell/scripts/build.sh
  vendor/github.com/client9/misspell/scripts/commit-msg.sh
  vendor/github.com/client9/misspell/scripts/goreleaser-dryrun.sh
  vendor/github.com/client9/misspell/scripts/pre-commit.sh
  vendor/github.com/client9/misspell/scripts/setup.sh
  vendor/github.com/client9/misspell/scripts/travis.sh
  vendor/github.com/client9/misspell/scripts/update-godownloader.sh
  vendor/github.com/client9/misspell/stringreplacer.go
  vendor/github.com/client9/misspell/stringreplacer_test.gox
  vendor/github.com/client9/misspell/url.go
  vendor/github.com/client9/misspell/words.go
Labels: approved, cla: yes, lgtm

#12318 Add CRD AuthorizationPolicy for authorization v2 API
  galley/pkg/metadata/kube/types.go
  galley/pkg/metadata/types.go
  galley/tools/gen-meta/metadata.yaml
  install/kubernetes/helm/istio-init/files/crd-12.yaml
  pilot/pkg/config/kube/crd/types.go
  pilot/pkg/model/authorization.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.go
  pilot/test/mock/config.go
  pkg/test/deployment/helm.go
  tests/e2e/framework/kubernetes.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#12498 Remove deprecated attributes from template comment
  mixer/template/apikey/template.yaml
  mixer/template/apikey/template_handler_service.descriptor_set
  mixer/template/apikey/template_proto.descriptor_set
  mixer/template/authorization/authorization.pb.html
  mixer/template/authorization/template.proto
  mixer/template/authorization/template.yaml
  mixer/template/authorization/template_handler.gen.go
  mixer/template/authorization/template_handler_service.descriptor_set
  mixer/template/authorization/template_handler_service.pb.go
  mixer/template/authorization/template_handler_service.proto
  mixer/template/authorization/template_proto.descriptor_set
  mixer/template/edge/template.yaml
  mixer/template/edge/template_handler_service.descriptor_set
  mixer/template/edge/template_proto.descriptor_set
  mixer/template/listentry/template.yaml
  mixer/template/listentry/template_handler_service.descriptor_set
  mixer/template/listentry/template_proto.descriptor_set
  mixer/template/logentry/logEntry.pb.html
  mixer/template/logentry/template.proto
  mixer/template/logentry/template.yaml
  mixer/template/logentry/template_handler.gen.go
  mixer/template/logentry/template_handler_service.descriptor_set
  mixer/template/logentry/template_handler_service.pb.go
  mixer/template/logentry/template_handler_service.proto
  mixer/template/logentry/template_proto.descriptor_set
  mixer/template/metric/metric.pb.html
  mixer/template/metric/template.proto
  mixer/template/metric/template.yaml
  mixer/template/metric/template_handler.gen.go
  mixer/template/metric/template_handler_service.descriptor_set
  mixer/template/metric/template_handler_service.pb.go
  mixer/template/metric/template_handler_service.proto
  mixer/template/metric/template_proto.descriptor_set
  mixer/template/quota/quota.pb.html
  mixer/template/quota/template.proto
  mixer/template/quota/template.yaml
  mixer/template/quota/template_handler.gen.go
  mixer/template/quota/template_handler_service.descriptor_set
  mixer/template/quota/template_handler_service.pb.go
  mixer/template/quota/template_handler_service.proto
  mixer/template/quota/template_proto.descriptor_set
  mixer/template/tracespan/traceSpan.pb.html
  mixer/template/tracespan/tracespan.proto
  mixer/template/tracespan/tracespan.yaml
  mixer/template/tracespan/tracespan_handler.gen.go
  mixer/template/tracespan/tracespan_handler_service.descriptor_set
  mixer/template/tracespan/tracespan_handler_service.pb.go
  mixer/template/tracespan/tracespan_handler_service.proto
  mixer/template/tracespan/tracespan_proto.descriptor_set
Labels: approved, cla: yes, lgtm

#12497 Allow no hosts in the ServiceEntry validation
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: approved, cla: yes, lgtm

#12418 merge top-level trafficPolicy should ignore null
  pilot/pkg/model/destination_rule.go
Labels: approved, cla: yes, lgtm, ok-to-test

#12430 Galley test component: support generic validation
  pkg/test/framework/api/components/galley.go
  pkg/test/framework/runtime/components/galley/client.go
  pkg/test/framework/runtime/components/galley/comparison.go
  pkg/test/framework/runtime/components/galley/native.go
  tests/integration2/galley/conversion/conversion_test.go
Labels: approved, cla: yes, lgtm

#12483 Support multiple root certs for multicluster self-signed Citadel
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/root-certs-for-testing.pem
Labels: approved, cla: yes, lgtm

#12524 docs: add samples for the route directive demo
  samples/httpbin/policy/keyval-template.yaml
  samples/httpbin/policy/keyval.yaml
Labels: approved, cla: yes, lgtm

#12526 spiffe: remove duplicate constant and some clean up
  pkg/spiffe/spiffe.go
  pkg/spiffe/spiffe_test.go
Labels: approved, cla: yes, lgtm

#12537 Disable the "xDS marshaling to Any" feature by default
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  pkg/features/pilot/pilot.go
Labels: approved, cla: yes, lgtm

#12516 Fix access log config when xds mashaling to any is disabled
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: approved, cla: yes, lgtm, ok-to-test

#12415 rbac: support authorization policy on gateway
  pilot/pkg/networking/plugin/authz/rbac.go
  tests/e2e/tests/pilot/istio_rbac_test.go
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-egressgateway.yaml
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-rbac-enable-gateway.yaml.tmpl
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-rbac-rules-gateway.yaml.tmpl
Labels: approved, area/security/aaa, cla: yes, lgtm

#12559 Revert "Allow no hosts in the ServiceEntry validation"
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: approved, cla: yes, lgtm

#12532 Fix bug in locality LB normalization
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
Labels: approved, cla: yes, lgtm

#12491 Improve certificate generation makefile
  samples/certs/Makefile
Labels: approved, cla: yes, lgtm

#12576 Revert "Fix bug in locality LB normalization (#12532)"
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
Labels: cla: yes

#12539 Testing: support retries in Structpath
  pkg/test/util/structpath/instance.go
  pkg/test/util/structpath/structpath.go
  tests/integration2/pilot/sidecar_api_test.go
Labels: approved, cla: yes, lgtm

#12242 Move Distributor interface back to runtime.
  galley/pkg/runtime/distributor.go
  galley/pkg/runtime/distributor_test.go
  galley/pkg/runtime/processor.go
  galley/pkg/runtime/processor_test.go
  galley/pkg/source/fs/source_test.go
Labels: approved, cla: yes, lgtm

#11823 [Kiali][master] things needed for next version of Kiali
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/demosecret.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: approved, cla: yes, lgtm

#12219 Canonicalize help strings for CLI
  security/cmd/istio_ca/main.go
Labels: approved, cla: yes, lgtm

#12383 Fix recently broken racetest on master
  mixer/pkg/lang/cel/builder_test.go
Labels: approved, cla: yes, lgtm

#12492 missing comment on exported function ConstructCustomDNSNames
  security/pkg/k8s/controller/customdnsname.go
Labels: approved, cla: yes, lgtm

#12604 Cherry-pick Galley/MCP changes from 1.1 => master
  galley/cmd/galley/cmd/root.go
  galley/cmd/galley/cmd/server.go
  galley/pkg/server/server.go
  galley/pkg/server/server_test.go
  galley/pkg/source/kube/schema/check/check.go
  galley/pkg/source/kube/schema/check/check_test.go
  galley/tools/mcpc/main.go
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  pilot/pkg/config/coredatamodel/controller.go
  pilot/pkg/config/coredatamodel/controller_test.go
Labels: approved, cla: yes, lgtm

#12608 Remove myself from OWNERS files
  install/OWNERS
  pilot/OWNERS
Labels: approved, cla: yes

#12577 Add an e2e test for out of process adapter
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/mixer/testdata/mixer-deployment-service.yaml
  tests/e2e/tests/mixer/testdata/mixer-oop-rule-handler-instance-deployment.yaml
Labels: approved, cla: yes, lgtm

#12611 Add a config package folder.
  pkg/config/doc.go
Labels: approved, cla: yes, lgtm

#12633 Hide most logging CLI options from istioctl
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#11904 Log descriptions of pods when tests break
  tests/util/kube_utils.go
Labels: approved, cla: yes, lgtm

#12542 add istio-init.yaml to .gitignore
  .gitignore
Labels: approved, cla: yes, lgtm

#12541 authz: add authorization policy CRD to helm-init
  install/kubernetes/helm/istio-init/templates/configmap-crd-12.yaml
  install/kubernetes/helm/istio-init/templates/job-crd-12.yaml
Labels: approved, area/security/aaa, cla: yes, lgtm

#12579 Fix bug in locality LB normalization (#12532)
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
Labels: cla: yes

#12588 Apply locality weighted lb config correctly
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: approved, cla: yes, lgtm

#12615 Fix bug causing empty endpoints per locality
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#12626 Fix the MCP Client ConfigZ page
  pkg/mcp/configz/assets.gen.go
  pkg/mcp/configz/assets/templates/config.html
  pkg/mcp/configz/configz_test.go
Labels: approved, cla: yes, lgtm

#12499 Add threshold for rds.go codecov
  codecov.threshold
Labels: cla: yes

#12239 Drop log level for missing service account for spiffe uri
  pkg/spiffe/spiffe.go
  pkg/spiffe/spiffe_test.go
Labels: cla: yes, lgtm

#12460 [Authz v2] Add additional fields for bindings and validation. (#11800)
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/plugin/authz/rbac.go
  pilot/pkg/networking/plugin/authz/rbac_test.go
  pilot/pkg/networking/plugin/authz/test_helper.go
Labels: approved, cla: yes, lgtm

#12174 enhance verify install command
  istioctl/cmd/istioctl/main.go
  istioctl/pkg/install/verify.go
Labels: approved, cla: yes, lgtm

#12175 configure prometheus to monitor citadel.
  install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml
Labels: approved, cla: yes, lgtm

#12556 Add namespace scoping to the Gateway 'port' names (#11509) (#12500)
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
Labels: cla: yes

#12649 Minimal changes to make locality lb not sigsegv
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
Labels: approved, cla: yes, lgtm

#12592 Locality label istio-locality in k8s should not contain `/`, use `.`
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
Labels: approved, cla: yes, lgtm

#12663 Only use gateways for servers being processed
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: approved, cla: yes, lgtm

#12569 Propagate Envoy Metrics Service Config
  pilot/cmd/pilot-agent/main.go
Labels: approved, cla: yes, ok-to-test

#12505 mixer: add directive demo adapter
  mixer/test/keyval/adapter.go
  mixer/test/keyval/config.pb.go
  mixer/test/keyval/config.proto
  mixer/test/keyval/config.proto_descriptor
  mixer/test/keyval/doc.go
  mixer/test/keyval/keyval.pb.html
  mixer/test/keyval/keyval.yaml
  mixer/test/keyval/main/main.go
  mixer/test/keyval/template.proto
  mixer/test/keyval/template.yaml
  mixer/test/keyval/template_handler.gen.go
  mixer/test/keyval/template_handler_service.descriptor_set
  mixer/test/keyval/template_handler_service.pb.go
  mixer/test/keyval/template_handler_service.proto
  mixer/test/keyval/template_proto.descriptor_set
  samples/httpbin/policy/keyval-template.yaml
  samples/httpbin/policy/keyval.yaml
Labels: approved, cla: yes, lgtm

#12643 Cherry-pick (#12233) from release-1.1 to master.
  install/kubernetes/helm/istio/charts/galley/templates/validatingwebhookconfiguration.yaml.tpl
Labels: approved, cla: yes, lgtm

#12581 Cleaning up Unit tests for RDS
  pilot/pkg/proxy/envoy/v2/rds_test.go
Labels: approved, cla: yes, lgtm

#10578 switching deployments to use apps/v1 api
  install/kubernetes/helm/istio/charts/certmanager/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/ingress/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/autoscale.yaml
  pilot/pkg/kube/inject/testdata/inject/statefulset.yaml
  pilot/pkg/kube/inject/testdata/inject/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pkg/test/framework/components/apps/kube.go
  samples/httpbin/sample-client/fortio-deploy.yaml
  samples/rawvm/k8cli.yaml.in
  samples/rawvm/k8services.yaml.in
  tests/e2e/tests/dashboard/fortio-rules.yaml
  tests/e2e/tests/dashboard/netcat-rules.yaml
  tests/e2e/tests/simple/testdata/v1alpha3/servicesNotInjected.yaml
  tests/e2e/tests/simple/testdata/v1alpha3/servicesToBeInjected.yaml
  tests/e2e/tests/stackdriver/fortio-rules.yaml
  tests/helm/templates/etcd.yaml
  tests/helm/templates/fortio-080.yaml
  tests/helm/templates/fortio-10rc1.yaml
  tests/helm/templates/fortio-cli.yaml
  tests/helm/templates/fortio-headless.yaml
  tests/helm/templates/fortio-master.yaml
  tests/helm/templates/fortio-noistio.yaml
  tests/helm/templates/fortio-tls.yaml
  tests/helm/templates/fortio-tproxy.yaml
  tests/helm/templates/fortio-ttls-small.yaml
  tests/helm/templates/fortio-ttls.yaml
  tests/helm/templates/fortio.yaml
  tests/upgrade/templates/fortio.yaml
  tools/perf_k8svcs.yaml
Labels: approved, cla: yes, lgtm

#12676 Cleanup Galley OWNERS file.
  galley/OWNERS
Labels: approved, cla: yes, lgtm

#12688 fix uds socket
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
Labels: cla: yes, lgtm

#12388 Add unit test to cover multiple different locality case
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: approved, cla: yes, lgtm

#12690 Build 1.1.1
  Gopkg.lock
  istio.deps
  vendor/istio.io/api/authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  vendor/istio.io/api/authentication/v1alpha1/policy.pb.go
  vendor/istio.io/api/authentication/v1alpha1/policy.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/mesh/v1alpha1/network.pb.go
  vendor/istio.io/api/mesh/v1alpha1/network.proto
  vendor/istio.io/api/mesh/v1alpha1/proxy.pb.go
  vendor/istio.io/api/mesh/v1alpha1/proxy.proto
  vendor/istio.io/api/mixer/v1/config/client/client_config.pb.go
  vendor/istio.io/api/mixer/v1/config/client/client_config.proto
  vendor/istio.io/api/mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.pb.go
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.pb.html
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.proto
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.html
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.go
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.html
  vendor/istio.io/api/networking/v1alpha3/sidecar.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/policy/v1beta1/cfg.pb.go
  vendor/istio.io/api/policy/v1beta1/cfg.proto
  vendor/istio.io/api/policy/v1beta1/istio.policy.v1beta1.pb.html
  vendor/istio.io/api/proto.lock
  vendor/istio.io/api/python/istio_api/mesh/v1alpha1/proxy_pb2.py
  vendor/istio.io/api/rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  vendor/istio.io/api/rbac/v1alpha1/rbac.pb.go
  vendor/istio.io/api/rbac/v1alpha1/rbac.proto
Labels: cla: yes

#12560 Fix LB weight setting for split horizon eds
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
Labels: approved, cla: yes

#12473 fix typo in default envoy JSON log format
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes, lgtm, ok-to-test

#12089 clarified mesh connect timeout fields based on code impl
  install/kubernetes/helm/istio/templates/configmap.yaml
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#12681 Testing: configurable ports for Echo
  pkg/test/application/echo/echo.go
  pkg/test/framework/components/echo/instance.go
  pkg/test/framework/components/echo/native.go
  tests/integration/echo/echo_test.go
Labels: approved, cla: yes

#12327 add image pull secrets for zipkin.
  install/kubernetes/helm/istio/charts/tracing/templates/deployment-zipkin.yaml
Labels: approved, cla: yes, lgtm

#12575 Refresh oop handler with connection config update
  mixer/pkg/runtime/config/ephemeral_test.go
  mixer/pkg/runtime/config/snapshot.go
  mixer/pkg/runtime/handler/signature.go
  mixer/pkg/runtime/handler/table_test.go
  mixer/pkg/runtime/testing/data/data.go
Labels: approved, cla: yes

#12585 Fixing coping of the data to the bucket during release
  release/gcb/run_daily_release.sh
  release/gcb/run_monthly_release.sh
Labels: approved, cla: yes, lgtm

#12458 'istioctl proxy-config clusters' output regression
  istioctl/cmd/istioctl/proxyconfig_test.go
  istioctl/pkg/writer/envoy/configdump/cluster.go
  istioctl/pkg/writer/envoy/configdump/testdata/clustersummary.txt
  istioctl/pkg/writer/envoy/configdump/testdata/clustersummaryfiltered.txt
Labels: approved, cla: human-approved, cla: yes, lgtm

#12675 Make error SNI subset validation message explicit
  pilot/pkg/model/validation.go
Labels: approved, cla: yes, lgtm

#11531 E2E test for health check under mtls using app prober rewrite.
  pkg/test/framework/README.md
  pkg/test/framework/components/apps/apps.go
  pkg/test/framework/components/apps/kube.go
  pkg/test/framework/components/istio/istio.go
  tests/integration/README.md
  tests/integration/security/healthcheck/mtls_healthcheck_test.go
Labels: approved, cla: yes, lgtm

#12702 Hide ServiceAccounts from PushContext log
  pilot/pkg/model/push_context.go
Labels: cla: yes
