Repository istio/istio, pull requests merged in 2019-04, with the labels that each got.

#12905 Istio does not use Cluster_LOGICAL_DNS, so remove it
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: approved, cla: yes, lgtm

#12914 Clean up Helm README
  install/kubernetes/helm/README.md
  install/kubernetes/helm/istio/README.md
Labels: approved, cla: yes, lgtm

#12627 'istioctl experimental dashboard' command to show add-ons and sidecars
  istioctl/cmd/istioctl/dashboard.go
  istioctl/cmd/istioctl/dashboard_test.go
  istioctl/cmd/istioctl/metrics.go
  istioctl/pkg/kubernetes/client.go
Labels: approved, cla: yes, lgtm

#12918 Validate new mixer CRDs
  install/kubernetes/helm/istio/charts/galley/templates/validatingwebhookconfiguration.yaml.tpl
  tests/e2e/tests/galley/testdata/config-v1alpha2-adapter-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-adapter-valid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-handler-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-handler-valid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-instance-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-instance-valid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-template-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-template-valid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-zipkin-invalid.yaml
  tests/e2e/tests/galley/testdata/config-v1alpha2-zipkin-valid.yaml
Labels: approved, cla: yes, lgtm

#12646 Add environment variables to allow configuring bookinfo hostnames
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-add-serviceaccount.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/productpage/productpage.py
  samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
  tests/apps/bookinfo/output/productpage-normal-user-v1.html
  tests/apps/bookinfo/output/productpage-normal-user-v2.html
  tests/apps/bookinfo/output/productpage-normal-user-v3.html
  tests/apps/bookinfo/output/productpage-test-user-v1-review-timeout.html
  tests/apps/bookinfo/output/productpage-test-user-v2.html
Labels: cla: yes, ok-to-test

#12942 Add edsClusters should be atomic
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: approved, cla: yes, lgtm

#12945 properly report errors on failure
  tests/e2e/framework/kubernetes.go
Labels: approved, area/test and release, cla: yes, kind/test failure, lgtm

#12902 Hoist exemptLabels to top-level, so that they can apply to prs as well.
  .github/stale.yml
Labels: approved, cla: yes, lgtm

#12680 [mixer-e2e-test] add retry to prometheus query in check cache test
  tests/e2e/tests/mixer/mixer_test.go
Labels: Code Mauve, approved, cla: yes, lgtm

#12661 Fixing typos in unit tests
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: approved, cla: yes, lgtm

#12714 respect locality weight set from ServiceEntry
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: approved, cla: yes, lgtm

#12831 sidecars with workload selector takes precedence over namespace wide one
  pilot/pkg/model/push_context.go
Labels: approved, cla: yes

#12847 Cleanup gateway vhost config gen
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: cla: yes

#12916 Add wildcard route fallthrough (Fixes ALLOW_ANY, 404s)
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pkg/features/pilot/pilot.go
Labels: cla: yes

#12972 Support PKCS#8 private keys.
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/generate_csr.go
Labels: approved, cla: yes, lgtm

#12159 Restore dump_kubernetes.sh function on OSX
  tools/dump_kubernetes.sh
Labels: cla: yes, lgtm

#12946 Remove Robert Li from tests OWNERS file
  tests/OWNERS
Labels: approved, cla: yes, lgtm

#12981 remove unnecessary namespace for webhook configuration
  install/kubernetes/helm/istio/charts/galley/templates/validatingwebhookconfiguration.yaml.tpl
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml
Labels: approved, cla: yes, lgtm

#12954 remove deprecated mcpServerAddrs flag
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pkg/test/framework/components/pilot/native.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/mcp_test.go
  tests/e2e/tests/pilot/performance/serviceentry_test.go
  tests/util/pilot_server.go
Labels: approved, cla: yes, lgtm

#12872 supprt proxy https app probe
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  pilot/cmd/pilot-agent/status/test-cert/cert.crt
  pilot/cmd/pilot-agent/status/test-cert/cert.key
  pilot/pkg/kube/inject/app_probe.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/testdata/inject/app_probe/https-probes.yaml
  pilot/pkg/kube/inject/testdata/inject/app_probe/https-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_https_probe_rewrite.patch
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_https_probe_rewrite.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_https_probe_rewrite_template.yaml
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes, lgtm

#12865 Allow some time for the configuration propagation
  tests/integration/pilot/security/authn_permissive_test.go
Labels: approved, cla: yes, lgtm

#12584 samples/bookinfo: easier access to logs
  samples/bookinfo/src/productpage/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test

#13001 Use shorter namespace prefixes in the test framework
  pkg/test/framework/components/namespace/kube.go
Labels: approved, cla: yes, lgtm

#12936 [Cherry-pick]Change Ip Address to readable format in accesslog from stdio/stackdri…
  mixer/adapter/stackdriver/log/log.go
  mixer/adapter/stackdriver/log/log_test.go
  mixer/adapter/stdio/stdio.go
  mixer/adapter/stdio/stdio_test.go
Labels: approved, cla: yes, lgtm

#12977 Update integration test env flag
  tests/integration/README.md
  tests/integration/tests.mk
Labels: approved, cla: yes, lgtm

#12849 Support inline role definition in AuthorizationPolicy
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/plugin/authz/rbac_v2.go
  pilot/pkg/networking/plugin/authz/rbac_v2_test.go
Labels: approved, cla: yes, lgtm

#12857 Don't fill test logs with "no provious log"
  tests/util/common_utils.go
  tests/util/kube_utils.go
Labels: Code Mauve, approved, cla: yes, lgtm

#11624 Add tests for the effect of mTLS setting to reachability
  pkg/test/framework/components/apps/kube.go
  pkg/test/framework/components/environment/kube/kube.go
  tests/integration/pilot/reachabiity/main_test.go
  tests/integration/pilot/reachabiity/mtls_test.go
  tests/integration/pilot/reachabiity/testdata/global-mtls-off.yaml
  tests/integration/pilot/reachabiity/testdata/global-mtls-on.yaml
  tests/integration/pilot/reachabiity/testdata/global-mtls-permissive.yaml
  tests/integration/pilot/reachabiity/testdata/single-port-mtls-on.yaml
Labels: approved, cla: yes, lgtm

#13005 remove deprecated code
  Gopkg.lock
  security/pkg/nodeagent/plugin/providers/google/iamclient.go
  security/pkg/nodeagent/plugin/providers/google/iamclient_test.go
Labels: approved, cla: yes, lgtm

#13000 Add examples/documentation for the test framework.
  tests/integration/README.md
  tests/integration/examples/example_test.go
  tests/integration/examples/mycomponent/mycomponent.go
  tests/integration/examples/mycomponent/native.go
Labels: approved, cla: yes, lgtm

#13003 Fix ticker and retry loop in mixer initialization CRD watch
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
Labels: approved, cla: yes, lgtm

#13015 first change to apps/v1 for Install
  install/kubernetes/citadel_extras/istio-citadel-plugin-certs.yaml.tmpl
  install/kubernetes/citadel_extras/istio-citadel-standalone.yaml.tmpl
  install/kubernetes/citadel_extras/istio-citadel-with-health-check.yaml.tmpl
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/istiocoredns/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/nodeagent/templates/daemonset.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/prometheus/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/servicegraph/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment-jaeger.yaml
  install/kubernetes/helm/istio/charts/tracing/templates/deployment-zipkin.yaml
Labels: approved, cla: yes, lgtm

#12997 use only ipv4 for pilot and zipkin
  pilot/docker/envoy_pilot.yaml.tmpl
  pilot/docker/envoy_policy.yaml.tmpl
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/deb/envoy_bootstrap_v2.json
Labels: approved, cla: yes, lgtm

#13013 small fix for imports
  galley/pkg/source/kube/dynamic/converter/converter_test.go
Labels: approved, cla: yes, lgtm

#12092 remove old mcp stack
  codecov.threshold
  galley/pkg/server/server.go
  galley/tools/mcpc/main.go
  mixer/pkg/config/mcp/backend.go
  pilot/pkg/bootstrap/server.go
  pkg/mcp/client/client.go
  pkg/mcp/client/client_test.go
  pkg/mcp/configz/configz_test.go
  pkg/mcp/server/listchecker.go
  pkg/mcp/server/server.go
  pkg/mcp/server/server_test.go
  pkg/mcp/sink/journal.go
  pkg/mcp/sink/journal_test.go
  pkg/mcp/testing/server.go
  pkg/test/framework/components/galley/client.go
Labels: approved, cla: yes, lgtm

#12251 Exclude Prometheus traffic in rule so that Kiali does not show it
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/testdata/config/prometheus.yaml
Labels: cla: yes, lgtm, ok-to-test

#13004 [Galley] Fix race in strategy shutdown.
  galley/pkg/runtime/publish/strategy.go
  galley/pkg/runtime/publish/strategy_test.go
Labels: approved, cla: yes, lgtm

#12641 Add instructions and scripts to facilitate running E2E tests locally using KinD
  prow/e2e-kind-simpleTests.sh
  prow/e2e-kind-suite.sh
  prow/lib.sh
  tests/e2e/local/kind/README.md
  tests/e2e/local/kind/install_prereqs.sh
  tests/e2e/local/kind/install_prereqs_debian.sh
  tests/e2e/local/kind/setup_kind_env.sh
  tests/e2e/local/kind/setup_test.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#13012 respect locality weight set from ServiceEntry
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: approved, cla: yes, lgtm

#13032 Add documentation about -p 1 for integration test framework.
  tests/integration/README.md
Labels: approved, cla: yes, lgtm

#13035 Reduce logs in security/pkg/nodeagent/sds/
  security/pkg/nodeagent/sds/server.go
Labels: approved, cla: yes, lgtm

#12982 move pkg/mcp/configz to pkg/mcp/configz/client
  mixer/pkg/config/mcp/backend.go
  pilot/pkg/bootstrap/server.go
  pkg/mcp/configz/client/assets.gen.go
  pkg/mcp/configz/client/assets.go
  pkg/mcp/configz/client/assets/templates/config.html
  pkg/mcp/configz/client/configz.go
  pkg/mcp/configz/client/configz_test.go
Labels: approved, cla: yes, lgtm

#12969 Restore TestMtlsHealthCheck in postsubmit, prow.
  tests/integration/security/healthcheck/mtls_healthcheck_test.go
Labels: approved, cla: yes, lgtm

#12707 Cherry pick cert file config from master to release-1.1
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/main_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authn/authentication_test.go
  pilot/pkg/proxy/envoy/watcher.go
  pilot/pkg/proxy/envoy/watcher_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#12289 Allow limiting Citadel to marked namespaces only
  security/cmd/istio_ca/main.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/k8s/controller/workloadsecret_test.go
Labels: approved, cla: yes, lgtm

#13047 appsv1 galley
  galley/pkg/crd/validation/config_test.go
  galley/pkg/crd/validation/webhook.go
  galley/pkg/crd/validation/webhook_test.go
Labels: approved, cla: yes, lgtm

#12829 add param to sidecar to ignore iptables changes
  tools/deb/istio-start.sh
  tools/deb/sidecar.env
Labels: approved, cla: yes, lgtm, ok-to-test

#13030 samples/bookinfo: migrate `apiVersion` of deployments to `apps/v1`
  samples/bookinfo/platform/kube/bookinfo-add-serviceaccount.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/platform/kube/rbac/ratings-v2-add-serviceaccount.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#13054 fix validation logic so that port.name is no longer a valid PortSelector
  pilot/pkg/model/validation.go
Labels: approved, area/networking, cla: yes, kind/customer issue, lgtm

#13037 [Test Framework]: Galley support for deleting config
  pkg/test/framework/components/galley/galley.go
  pkg/test/framework/components/galley/kube.go
  pkg/test/framework/components/galley/native.go
  pkg/test/framework/components/galley/native_test.go
  pkg/test/util/yml/apply.go
Labels: approved, cla: yes, lgtm

#12980 Support controlz for mcp server
  galley/pkg/server/server.go
  pkg/mcp/configz/server/assets.gen.go
  pkg/mcp/configz/server/assets.go
  pkg/mcp/configz/server/assets/templates/config.html
  pkg/mcp/configz/server/configz.go
  pkg/mcp/configz/server/configz_test.go
  pkg/mcp/snapshot/snapshot.go
Labels: approved, cla: yes, lgtm

#12203 generalize artifact injection into Docker images
  release/gcb/cloud_builder.sh
  release/gcb/docker_tag_push_lib.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#13060 Keep going when problem happens checking remote version
  istioctl/pkg/kubernetes/client.go
Labels: approved, cla: yes, lgtm

#13053 remove deprecated show-all flag
  tests/util/kube_utils.go
Labels: approved, cla: yes

#11801 Add x alias to experimental istioctl command
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#12693 Correct the app label for Gateway
  install/kubernetes/helm/istio/charts/gateways/templates/autoscale.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/clusterrole.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/clusterrolebindings.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/preconfigured.yaml
Labels: approved, cla: yes, lgtm

#13082 Fix tracing_datadog_golden.json for datadog tracer
  pkg/bootstrap/testdata/tracing_datadog_golden.json
Labels: approved, cla: yes, lgtm, ok-to-test

#13089 Fix small typo
  mixer/template/checknothing/checkNothing.pb.html
  mixer/template/checknothing/template.proto
  mixer/template/checknothing/template_handler.gen.go
  mixer/template/checknothing/template_handler_service.pb.go
  mixer/template/checknothing/template_handler_service.proto
  mixer/template/reportnothing/reportNothing.pb.html
  mixer/template/reportnothing/template.proto
  mixer/template/reportnothing/template_handler.gen.go
  mixer/template/reportnothing/template_handler_service.pb.go
  mixer/template/reportnothing/template_handler_service.proto
Labels: approved, cla: yes, lgtm, ok-to-test

#12805 Add jitter in CSR request
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: approved, cla: yes, lgtm

#12635 Allows cleanup.sh to run non-interactively in terminal
  samples/bookinfo/platform/kube/cleanup.sh
Labels: approved, cla: yes, lgtm, ok-to-test

#12730 Cherry-pick 'istioctl proxy-config clusters' cluster type column rendering (#12458)
  istioctl/cmd/istioctl/proxyconfig_test.go
  istioctl/pkg/writer/envoy/configdump/cluster.go
  istioctl/pkg/writer/envoy/configdump/testdata/clustersummary.txt
  istioctl/pkg/writer/envoy/configdump/testdata/clustersummaryfiltered.txt
Labels: approved, lgtm, ok-to-test

#12733 update sds secret mount.
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
Labels: approved, cla: yes, lgtm

#12762 Copy data from right place
  release/gcb/helm_values.sh
Labels: cla: yes, lgtm

#12766 Fix updateClusterInc for overlapping ports
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: approved, cla: yes, lgtm

#12832 enable default sidecarscope
  pilot/pkg/model/push_context.go
Labels: approved, cla: yes

#12890 [Galley] Fix for ServiceEntry event ordering
  galley/pkg/runtime/projections/serviceentry/convert/convert.go
  galley/pkg/runtime/projections/serviceentry/convert/convert_bench_test.go
  galley/pkg/runtime/projections/serviceentry/convert/convert_test.go
  galley/pkg/runtime/projections/serviceentry/handler.go
  galley/pkg/runtime/projections/serviceentry/handler_test.go
  galley/pkg/runtime/projections/serviceentry/node/cache.go
  galley/pkg/runtime/projections/serviceentry/node/cache_test.go
  galley/pkg/runtime/projections/serviceentry/pod/cache.go
  galley/pkg/runtime/projections/serviceentry/pod/cache_test.go
  tests/integration/galley/conversion/conversion_test.go
Labels: approved, cla: yes, lgtm

#11706 Adding sha for istio/tools to manifest.txt for future automation of p…
  release/gcb/generate_manifest.sh
Labels: approved, cla: yes, lgtm

#12808 Copy helm data from the right place
  release/gcb/helm_values.sh
Labels: approved, cla: yes, lgtm

#13027 Enable IPv6 Listeners
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: approved, cla: yes, lgtm

#13061 Enable more linters and fix warnings/errors
  .golangci.yml
  bin/linters.sh
  galley/pkg/runtime/projections/serviceentry/handler.go
  mixer/adapter/memquota/memquota_test.go
  mixer/pkg/config/mcp/backend_test.go
  mixer/pkg/perf/controller.go
  mixer/pkg/runtime/routing/string.go
  mixer/test/listbackend/list.go
  mixer/test/prometheus/nosession.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/tools/debug/pilot_cli.go
  pkg/mcp/tests/stress/stress_setup_test.go
  pkg/test/framework/components/pilot/native.go
  security/pkg/nodeagent/caclient/providers/vault/client_test.go
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/mcp_test.go
  tests/e2e/tests/pilot/performance/serviceentry_test.go
  tests/integration_old/component/mixer/mixer_binary_comp.go
Labels: approved, cla: yes, lgtm

#12852 Making tags requirement same as those in Kubernetes
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: approved, cla: yes, lgtm

#12953 Added certmanager flag into helm chart values.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#13141 controlPlaneMtls renamed to controlPlaneSecurityEnabled
  install/kubernetes/helm/istio/test-values/values-istio-auth-mcp.yaml
  install/kubernetes/helm/istio/test-values/values-istio-auth-multicluster.yaml
  install/kubernetes/helm/istio/test-values/values-istio-auth.yaml
  install/kubernetes/helm/istio/test-values/values-istio-mcp.yaml
  install/kubernetes/helm/istio/test-values/values-istio-multicluster.yaml
  install/kubernetes/helm/istio/test-values/values-istio-one-namespace-auth.yaml
  install/kubernetes/helm/istio/test-values/values-istio-one-namespace-trust-domain.yaml
  install/kubernetes/helm/istio/test-values/values-istio-one-namespace.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#13104 Patch #12805 to master
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: approved, cla: yes, lgtm

#12515 Fix HelmDelete command
  tests/e2e/framework/kubernetes.go
Labels: approved, cla: yes, lgtm

#13148 Right modification path
  release/gcb/helm_values.sh
Labels: approved, cla: yes, lgtm

#13077 Allow overriding of registry locality
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
Labels: approved, cla: yes, lgtm

#12815 mixer: add support for standard CRDs for compiled-in adapters
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/config/ephemeral.go
Labels: approved, cla: yes, lgtm

#13145 parse cert to get expire time
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/cache/testdata/cert-chain.pem
  security/pkg/nodeagent/model/secret.go
Labels: approved, cla: yes, lgtm

#13159 Installing istio for perf testing
  prow/setup_perf_cluster_for_tests.sh
Labels: approved, cla: yes, lgtm

#13112 added sidecar.istio.io/rewriteAppProbers annotation
  pilot/pkg/kube/inject/app_probe.go
  pilot/pkg/kube/inject/app_probe_test.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-set-in-annotation.yaml
  pilot/pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-set-in-annotation.yaml.injected
  pilot/pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-unset-in-annotation.yaml
  pilot/pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-unset-in-annotation.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_disabled_via_annotation.patch
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_disabled_via_annotation.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_disabled_via_annotation_template.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_enabled_via_annotation.patch
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_enabled_via_annotation.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_enabled_via_annotation_template.yaml
  pilot/pkg/kube/inject/webhook.go
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes, lgtm, ok-to-test

#12426 Export inject.injectionData()
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/webhook.go
Labels: approved, cla: yes, lgtm, ok-to-test

#13083 Registrator should use "master" version
  install/consul/templates/istio.yaml.tmpl
Labels: cla: yes, ok-to-test

#13186 Fixing copy for helm, one more time.
  release/gcb/helm_values.sh
Labels: approved, cla: yes, lgtm

#13195 Run goimports on generated file
  tests/integration/galley/validation/data.gen.go
  tests/integration/galley/validation/data.gen_test.go
Labels: approved, cla: yes, lgtm

#13151 Enable disabled mixer tests in New Test Framework
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/framework/components/policybackend/native.go
  tests/integration/mixer/check_test.go
  tests/integration/mixer/report_test.go
Labels: approved, cla: yes, lgtm

#12477 Reduce Pilot resource requests for demo
  install/kubernetes/helm/istio/values-istio-demo-common.yaml
Labels: approved, cla: yes

#13041 Added data source for Galley dashboard
  install/kubernetes/helm/istio/charts/grafana/dashboards/galley-dashboard.json
Labels: approved, cla: yes, lgtm, ok-to-test

#12798 fix values for pod anti-affinity.
  install/kubernetes/helm/istio/charts/gateways/templates/_affinity.tpl
  install/kubernetes/helm/istio/templates/_affinity.tpl
Labels: approved, cla: yes, lgtm

#12315 Align istio-gateways resource requests with sidecar
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  install/kubernetes/helm/istio/test-values/values-e2e.yaml
  install/kubernetes/helm/istio/values-istio-demo-common.yaml
Labels: approved, cla: yes, lgtm

#13165 report succeed after validation
  istioctl/pkg/validate/validate.go
Labels: approved, cla: yes, lgtm

#13170 Change exposed port of istio-pilot in consul
  install/consul/templates/istio.yaml.tmpl
Labels: cla: yes, ok-to-test

#12973 Cherrypick: Add wildcard route fallthrough (Fixes ALLOW_ANY, 404s) (#12916)
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pkg/features/pilot/pilot.go
Labels: cla: yes, lgtm

#13192 CEL checker mutex
  mixer/pkg/lang/cel/builder_test.go
Labels: approved, cla: yes, lgtm

#13084 Integration testing for Locality Load Balancing
  pilot/pkg/model/context.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pkg/test/application/echo/client.go
  pkg/test/framework/components/apps/apps.go
  pkg/test/framework/components/apps/kube.go
  pkg/test/framework/components/apps/native.go
  tests/integration/pilot/locality/main_test.go
  tests/integration/pilot/locality/prioritized_loadbalancing_test.go
Labels: approved, cla: yes, lgtm

#13127 [test-framework] Support helm values containing spaces
  pkg/test/helm/helm.go
  pkg/test/shell/shell.go
Labels: Code Mauve, approved, cla: yes, lgtm

#13190 Adding servicegraph testing to postsubmit
  prow/perf_service_graph_test.sh
Labels: approved, cla: yes, lgtm

#11448 Adding E2E Test for kiali
  install/kubernetes/helm/istio/test-values/values-e2e.yaml
  tests/e2e/tests/kiali/kiali_test.go
  tests/istio.mk
Labels: approved, cla: yes, lgtm

#13214 Remove unused mixer.enabled value
  install/kubernetes/helm/istio/charts/mixer/values.yaml
  install/kubernetes/helm/istio/values.yaml
Labels: approved, cla: yes, lgtm

#13194 Adding aliases for OWNERS
  OWNERS_ALIASES
  prow/OWNERS
Labels: approved, cla: yes, lgtm

#13217 fix(helm/sidecar-injector-configmap): run as root
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/job.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/list.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
  pilot/pkg/kube/inject/testdata/webhook/user-volume.yaml.injected
Labels: cla: yes, lgtm

#13222 Destination host cannot be *
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
Labels: cla: yes

#13224 Fixing helm order
  release/gcb/run_build.sh
Labels: approved, cla: yes, lgtm

#13146 Pilot [networking]: Add upstream idle_timeout to cluster definition
  Gopkg.lock
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.html
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/proto.lock
  vendor/istio.io/api/python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: approved, cla: yes, ok-to-test

#12988 Install pre check master
  Gopkg.lock
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/pre-check_test.go
  istioctl/pkg/install/verify.go
  istioctl/pkg/install/verify_test.go
Labels: approved, cla: yes, lgtm

#13233 update certificates with expiration time 100 years
  tests/testdata/certs/default/cert-chain.pem
  tests/testdata/certs/default/key.pem
  tests/testdata/certs/default/root-cert.pem
  tests/testdata/certs/pilot/cert-chain.pem
  tests/testdata/certs/pilot/key.pem
  tests/testdata/certs/pilot/root-cert.pem
  tests/testdata/local/etc/certs/cert-chain.pem
  tests/testdata/local/etc/certs/key.pem
  tests/testdata/local/etc/certs/root-cert.pem
Labels: approved, cla: yes, lgtm

#13234 Cherry pick #13233 to fix expired certificates
  tests/testdata/certs/default/cert-chain.pem
  tests/testdata/certs/default/key.pem
  tests/testdata/certs/default/root-cert.pem
  tests/testdata/certs/pilot/cert-chain.pem
  tests/testdata/certs/pilot/key.pem
  tests/testdata/certs/pilot/root-cert.pem
  tests/testdata/local/etc/certs/cert-chain.pem
  tests/testdata/local/etc/certs/key.pem
  tests/testdata/local/etc/certs/root-cert.pem
Labels: cla: yes, lgtm

#13011 fix original destination bug
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: approved, cla: yes

#13242 fix original destination bug
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: approved, cla: yes

#12666 Fix #11818 fix workloadSelector for Sidecars
  mixer/adapter/bypass/bypass.go
  mixer/test/client/env/ports.go
  mixer/test/client/gateway/gateway_test.go
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_accounts.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_discovery.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/mem.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/kube/controller.go
  pilot/pkg/serviceregistry/memory/discovery.go
  tests/testdata/networking/envoyfilter-without-service/configs.yaml
  tests/testdata/networking/envoyfilter-without-service/mesh.yaml
  tests/testdata/networking/sidecar-without-service/configs.yaml
  tests/testdata/networking/sidecar-without-service/mesh.yaml
Labels: approved, cla: yes, lgtm, ok-to-test

#13149 Right place to copy data from
  release/gcb/helm_values.sh
Labels: cla: yes

#13172 align init role label.
  install/kubernetes/helm/istio-init/templates/clusterrole.yaml
Labels: approved, cla: yes, lgtm

#13187 Remove istioctl "--platform <platform>" option
  istioctl/cmd/istioctl/main.go
Labels: approved, cla: yes, lgtm

#13163 push client the new root cert when it's changed
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: approved, cla: yes, lgtm

#13206 use port 80 for HTTP from details, for TLS origination
  samples/bookinfo/src/details/details.rb
Labels: approved, cla: yes, lgtm

#13181 Implement `role` field in AuthorizationPolicy
  pilot/pkg/model/validation.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/networking/plugin/authz/rbac_v2.go
  pilot/pkg/networking/plugin/authz/rbac_v2_test.go
Labels: approved, cla: yes, lgtm

#13199 Add integration tests for SDS-Vault mTLS flow and SDS-Citadel mTLS flow
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pkg/test/framework/components/apps/kube.go
  pkg/test/util/connection/connection.go
  security/pkg/nodeagent/sds/sdsservice.go
  tests/integration/security/sds_citadel_flow/sds_citadel_flow_test.go
  tests/integration/security/sds_citadel_flow/testdata/global-mtls.yaml
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
  tests/integration/security/sds_vault_flow/testdata/global-mtls.yaml
Labels: Code Mauve, approved, cla: yes, lgtm

#13225 Ignore missing resources on kubectl delete
  pkg/test/kube/kubectl.go
Labels: approved, cla: yes, lgtm

#13250 [Testing] Cleanup PortForwarder
  pkg/test/docker/registry/incluster.go
  pkg/test/framework/components/apps/kube.go
  pkg/test/framework/components/mixer/kube.go
  pkg/test/framework/components/pilot/kube.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/kube/accessor.go
  pkg/test/kube/port_forwarder.go
  tests/e2e/tests/dashboard/dashboard_test.go
  tests/e2e/tests/mixer/mixer_test.go
  tests/e2e/tests/pilot/pod_churn_test.go
Labels: approved, cla: yes, lgtm

#13209 Add generated LICENSES.txt to gitignore
  .gitignore
Labels: approved, cla: yes, lgtm

#13231 remove myself from owners for tests
  tests/e2e/tests/pilot/OWNERS
Labels: approved, cla: yes, lgtm

#13251 Fix ingress sds memory leak
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/pkg/nodeagent/secretfetcher/secretfetcher_test.go
Labels: approved, cla: yes, lgtm

#12734 add liveness probe for citadel.
  install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
Labels: approved, cla: yes, lgtm

#12668 Make 15020 first port in ingressgateway service
  install/kubernetes/helm/istio/charts/gateways/values.yaml
  tests/util/kube_utils.go
Labels: approved, cla: yes, ok-to-test

#12434 add upstream_transport_failure_reason to access log
  istio.deps
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes

#12965 Allow Locality Distribute without outlierDetection
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: cla: yes

#13253 Fix integration test errors and refactor security integration tests
  pkg/test/framework/runtime/testcontext.go
  pkg/test/util/policy/policy.go
  tests/integration/pilot/reachabiity/mtls_test.go
  tests/integration/security/authn/authn_permissive_test.go
  tests/integration/security/reachability/main_test.go
  tests/integration/security/reachability/mtls_test.go
  tests/integration/security/reachability/testdata/global-mtls-off.yaml
  tests/integration/security/reachability/testdata/global-mtls-on.yaml
  tests/integration/security/reachability/testdata/global-mtls-permissive.yaml
  tests/integration/security/reachability/testdata/single-port-mtls-on.yaml
  tests/integration/security/sds_citadel_flow/sds_citadel_flow_test.go
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
Labels: approved, cla: yes, lgtm

#13246 Fixes the multicluster e2e test
  tests/e2e/framework/kubernetes.go
  tests/e2e/tests/pilot/mesh_config_verify_test.go
  tests/util/kube_utils.go
Labels: approved, cla: yes, lgtm

#13278 pre-check: fix a logic error
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/pre-check_test.go
Labels: approved, cla: yes, lgtm

#13266 patch deprecated field
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: approved, cla: yes, lgtm

#13256 Remove kubectl from dockerfile prereqs since it pulls it
  tools/istio-docker.mk
Labels: approved, cla: yes

#12995 Fixing EDS unit tests
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: approved, cla: yes, lgtm

#13281 Skip validating non ingress gateway secret at secret fetcher.
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/pkg/nodeagent/secretfetcher/secretfetcher_test.go
Labels: approved, cla: yes, lgtm

#11788 Fix labels on manifests
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  install/kubernetes/helm/istio/templates/_helpers.tpl
Labels: approved, cla: yes, lgtm, ok-to-test

#13295 Disable xds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
Labels: cla: yes

#13296 Import istio/proxy for 1.1.3
  istio.deps
Labels: cla: yes

#13300 Update proxy version to 1.1.3
  pilot/docker/Dockerfile.proxy_debug
  pilot/docker/Dockerfile.proxytproxy
  pilot/docker/Dockerfile.proxyv2
  tools/deb/istio-start.sh
Labels: cla: yes

#13273 move to newer grafana
  install/kubernetes/helm/istio/charts/grafana/values.yaml
Labels: approved, cla: yes, lgtm

#13308 rbac: fix a data race in filter generation
  pilot/pkg/networking/plugin/authz/rbac.go
Labels: approved, area/security/aaa, cla: yes, lgtm

#12983 Include js/css files into static folder
  .codecov.yml
  bin/codecov.sh
  codecov.skip
  pkg/ctrlz/assets.gen.go
  pkg/ctrlz/assets/assets.gen.go
  pkg/ctrlz/assets/assets.go
  pkg/ctrlz/assets/static/css/bootstrap-4.0.0.min.css
  pkg/ctrlz/assets/static/css/dark_syntax-1.14.0.css
  pkg/ctrlz/assets/static/css/fontawesome-all-5.0.6.css
  pkg/ctrlz/assets/static/css/fonts.css
  pkg/ctrlz/assets/static/js/bootstrap-4.0.0.min.js
  pkg/ctrlz/assets/static/js/clipboard-1.7.1.min.js
  pkg/ctrlz/assets/static/js/jquery-3.2.1.slim.min.js
  pkg/ctrlz/assets/static/js/popper-1.12.9.min.js
  pkg/ctrlz/assets/static/js/prism-1.14.0.min.js
  pkg/ctrlz/assets/static/js/prism.js
  pkg/ctrlz/assets/templates/layouts/base.html
  pkg/ctrlz/ctrlz.go
  pkg/ctrlz/home.go
  pkg/ctrlz/topics/args.go
  pkg/ctrlz/topics/assets/assets.gen.go
  pkg/ctrlz/topics/assets/assets.go
  pkg/ctrlz/topics/collection.go
  pkg/ctrlz/topics/env.go
  pkg/ctrlz/topics/mem.go
  pkg/ctrlz/topics/metrics.go
  pkg/ctrlz/topics/proc.go
  pkg/ctrlz/topics/scopes.go
  pkg/ctrlz/topics/signals.go
  pkg/ctrlz/topics/version.go
  pkg/mcp/configz/client/assets/assets.gen.go
  pkg/mcp/configz/client/assets/assets.go
  pkg/mcp/configz/client/configz.go
  pkg/mcp/configz/server/assets/assets.gen.go
  pkg/mcp/configz/server/assets/assets.go
  pkg/mcp/configz/server/configz.go
Labels: approved, cla: yes, lgtm

#13303 Fix galley integration test race
  pkg/test/framework/components/galley/snapshot.go
Labels: approved, cla: yes, lgtm

#13337 Fix again helm copy, was reverted during merge from release 1.1
  release/gcb/helm_values.sh
Labels: approved, cla: yes, lgtm

#13160 Update OpenShift dependencies; Drop [deprecated] legacy schema
  Gopkg.lock
  Gopkg.toml
  pilot/pkg/kube/inject/initializer.go
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig.yaml
  pilot/pkg/kube/inject/testdata/inject/deploymentconfig.yaml.injected
  vendor/github.com/openshift/api/apps/v1/consts.go
  vendor/github.com/openshift/api/apps/v1/deprecated_consts.go
  vendor/github.com/openshift/api/apps/v1/legacy.go
  vendor/github.com/openshift/api/apps/v1/register.go
  vendor/github.com/openshift/api/apps/v1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm

#13118 Extend istioctl mocking library to allow mocking of authn etc
  istioctl/cmd/istioctl/authn.go
  istioctl/cmd/istioctl/authn_test.go
  istioctl/cmd/istioctl/dashboard.go
  istioctl/cmd/istioctl/dashboard_test.go
  istioctl/cmd/istioctl/metrics.go
  istioctl/cmd/istioctl/proxyconfig_test.go
  istioctl/cmd/istioctl/version_test.go
  istioctl/pkg/kubernetes/client.go
Labels: approved, cla: yes, lgtm

#13291 Fixing iptabes ranges
  tools/deb/istio-iptables.sh
Labels: approved, cla: yes, lgtm

#13297 Don't apply locality label unless provided
  pkg/test/framework/components/apps/kube.go
Labels: approved, cla: yes, lgtm

#13147 Single Template injection spec fully at runtime
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  install/kubernetes/helm/istio/files/injection-template.yaml
  install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml
  istioctl/cmd/istioctl/istioctl_test.go
  istioctl/cmd/istioctl/kubeinject.go
  istioctl/cmd/istioctl/testdata/deployment/hello.yaml.injected
  istioctl/cmd/istioctl/testdata/inject-config.yaml
  istioctl/cmd/istioctl/testdata/inject-values.yaml
  pilot/cmd/sidecar-injector/main.go
  pilot/pkg/kube/inject/inject.go
  pilot/pkg/kube/inject/inject_test.go
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_nosidecar_rewrite_template.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_disabled_via_annotation_template.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_enabled_via_annotation_template.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_template.yaml
  pilot/pkg/kube/inject/testdata/webhook/TestWebhookInject_template.yaml
  pilot/pkg/kube/inject/webhook.go
  pilot/pkg/kube/inject/webhook_test.go
Labels: approved, cla: yes, lgtm

#13340 Report circleci status to testgrid before k8s dump
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#13333 use syncmap in secretcache
  security/pkg/nodeagent/cache/secretcache.go
Labels: approved, cla: yes, lgtm

#13351 Gateway names cannot contain dot
  pilot/pkg/model/validation.go
Labels: cla: yes, lgtm
