Repository istio/istio, pull requests merged in 2020-04, with the labels that each got.

#22633 Update istio proxy SHA
  istio.deps
Labels: cla: yes, size/XS

#22535 Make use of metadata informer
  mixer/adapter/kubernetesenv/kubernetesenv.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/util.go
  pkg/kube/config.go
  pkg/kube/secretcontroller/secretcontroller.go
  pkg/kube/secretcontroller/secretcontroller_test.go
Labels: cla: yes, size/L

#22638 Move ISTIO_ENVOY_LINUX_VERSION to front in case unbounded
  bin/init.sh
Labels: area/test and release, cla: yes, ok-to-test, size/XS

#22639 Add wasm prefix and wasm_filter tag matching into bootstrap
  pkg/bootstrap/config.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/M

#22617 Fix the cert grace period calculation.
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: cla: yes, size/M

#22642 Fix spell miss: spiffee -> spiffe
  install/tools/setupMeshEx.sh
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, ok-to-test, size/S

#22631 [release-1.5] Remove extra space in grafana template
  manifests/istio-telemetry/grafana/templates/deployment.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#22603 Support K8s 1.18 IngressClass
  manifests/base/files/gen-istio-cluster.yaml
  manifests/base/templates/clusterrole.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/pkg/vfs/assets.gen.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  tests/integration/pilot/ingress/ingress_test.go
Labels: cla: yes, size/L

#22291 [1.5] Fix PDB selector for istiod (#22273)
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  manifests/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/component_hub_tag.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#22529 Fix prometheus operator for istiod
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/templates/service.yaml
  manifests/istio-telemetry/prometheusOperator/templates/servicemonitors.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/icp_input.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#22646 Automator: update common-files@master in istio/istio@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#22645 Fix IngressClass test on old kubenetes versions
  tests/integration/pilot/ingress/ingress_test.go
Labels: cla: yes, size/XS

#22647 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22649 [Test Framework] Allow both ControlPlaneValues and Values
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/operator.go
Labels: cla: yes, size/S

#22652 Default for ClusterLocalNamespaces
  galley/testdatasets/conversion/dataset.gen.go
  galley/testdatasets/conversion/dataset/mesh.istio.io/v1alpha1/meshconfig_expected.json
  pkg/config/mesh/mesh.go
  pkg/config/mesh/mesh_test.go
  pkg/kube/inject/inject.go
Labels: cla: yes, size/M

#22653 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22650 [Test Framework] Add Cluster to Echo
  pkg/test/echo/client/parsedresponse.go
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/response/response.go
  pkg/test/echo/server/endpoint/grpc.go
  pkg/test/echo/server/endpoint/http.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/docker/workload.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/testdata/basic.yaml
  pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
Labels: cla: yes, size/M

#22659 not to grab IstioOperatorSpec from empty IOPSYaml in upgrade
  operator/cmd/mesh/upgrade.go
Labels: area/environments, cla: yes, size/S

#22622 Support ca.crt secret key item
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/pkg/nodeagent/secretfetcher/secretfetcher_test.go
Labels: cla: yes, size/M

#22670 push context: minor optimization in merge
  pilot/pkg/model/push_context.go
Labels: area/networking, cla: yes, size/S

#22664 ads: remove validation calls for xds
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/monitoring.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: cla: yes, size/L

#22675 Fix test flakes for dashboard validation query
  tests/integration/telemetry/dashboard_test.go
Labels: cla: yes, size/XS

#22629 Applying cel upgrade to release 1.5
  go.mod
  go.sum
  mixer/pkg/il/testing/tests.go
  mixer/pkg/lang/cel/builder.go
  mixer/pkg/lang/cel/builder_test.go
  mixer/pkg/lang/cel/provider.go
  mixer/pkg/lang/cel/types.go
Labels: area/policies and telemetry, cla: yes, ok-to-test, size/XL

#22630 Pull in dependency updates
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: cla: yes, size/S

#22616 Add local SDS integration tests
  mixer/test/client/env/ports.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/test/README.md
  security/pkg/nodeagent/test/mock/caserver.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/nodeagent/test/success_sds/doc.go
  security/pkg/nodeagent/test/success_sds/sds_test.go
  security/pkg/nodeagent/test/testdata/bootstrap.yaml
Labels: cherrypick/release-1.5, cla: yes, size/XL

#22656 Support TLS on all protocols in echo
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/metrics.go
  pkg/test/echo/common/model.go
  pkg/test/echo/server/endpoint/grpc.go
  pkg/test/echo/server/endpoint/http.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/endpoint/tcp.go
  pkg/test/echo/server/endpoint/util.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  tests/integration/pilot/tls_test.go
Labels: cla: yes, size/L

#22686 clean up iptables: always redirect inbound traffic to 15006 port
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: cla: yes, size/M

#22688 Assorted startup chages, extracted from the DNS PR
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/validation.go
  pkg/istio-agent/sds-agent.go
Labels: cla: yes, size/M

#22583 make key cert rotation job works for VM
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
  security/pkg/nodeagent/sds/server.go
  tools/packaging/common/istio-start.sh
  tools/packaging/common/sidecar.env
Labels: cla: yes, size/M

#22567 ARM additions cleanup: removal of istioctl-linux
  Makefile.core.mk
Labels: area/config, cla: yes, ok-to-test, size/XS

#22694 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/base/files/crd-all.gen.yaml
  manifests/base/files/gen-istio-cluster.yaml
  operator/pkg/vfs/assets.gen.go
Labels: auto-merge, cla: yes, size/S

#22696 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22681 Add tests for selectors of templates
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  manifests/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#22679 Improvements to local agent run
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/sds/server.go
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/M

#22700 Fix PHONY recursion if target matches directory name
  Makefile.overrides.mk
Labels: cla: yes, size/XS

#22685 Make file watching code use signals instead of polling
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/monitor/monitor.go
  pilot/pkg/config/monitor/monitor_test.go
Labels: cla: yes, size/M

#22458 Remove mTLS analyzer
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/auth/mtls.go
  galley/pkg/config/analysis/analyzers/auth/mtls/destination_rule_checker.go
  galley/pkg/config/analysis/analyzers/auth/mtls/policy_checker.go
  galley/pkg/config/analysis/analyzers/auth/mtls/policy_checker_test.go
  galley/pkg/config/analysis/analyzers/policy/policy.go
  galley/pkg/config/analysis/analyzers/testdata/policy-with-peerauthentication-crd.yaml
  galley/pkg/config/analysis/analyzers/testdata/policy-without-peerauthentication-crd.yaml
Labels: area/security, area/user experience, cla: yes, size/XXL

#22568 Support cluster-local services
  pilot/pkg/bootstrap/mesh.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pkg/test/framework/components/galley/snapshot.go
  tests/integration/galley/conversion_test.go
  tests/integration/multicluster/cluster_local_test.go
  tests/integration/multicluster/main_test.go
  tests/integration/multicluster/reachability_test.go
  tests/integration/test/bob
Labels: cla: yes, size/L

#22711 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#22713 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22693 Fix blackhole and passthrough for telemetry v2
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/util/util.go
Labels: area/networking, cherrypick/release-1.5, cla: yes, size/S

#22632 Remove the galley deployment
  Makefile.core.mk
  galley/cmd/galley/cmd/probe.go
  galley/cmd/galley/cmd/root.go
  galley/cmd/galley/cmd/root_test.go
  galley/cmd/galley/cmd/server.go
  galley/cmd/galley/main.go
  galley/docker/Dockerfile.galley
  pkg/test/framework/components/galley/kube.go
  prow/lib.sh
  tests/integration/conformance/conformance_test.go
  tests/integration/conformance/main_test.go
  tests/integration/galley/galley_test.go
  tests/integration/galley/main_test.go
  tests/integration/galley/metrics_test.go
  tests/integration/galley/statusupdate/statusupdate_test.go
  tests/integration/pilot/analysis/analysis_test.go
  tests/integration/pilot/analysis/main_test.go
  tools/istio-docker.mk
Labels: cla: yes, size/XL

#22689 Add SDS integration tests
  mixer/test/client/env/ports.go
  mixer/test/client/env/setup.go
  security/pkg/nodeagent/test/cert_rotation/doc.go
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
  security/pkg/nodeagent/test/csr_failure/csr_test.go
  security/pkg/nodeagent/test/csr_failure/doc.go
  security/pkg/nodeagent/test/empty_certchain/doc.go
  security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
  security/pkg/nodeagent/test/mock/caserver.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/nodeagent/test/testdata/bootstrap.yaml
Labels: area/security, cla: yes, size/L

#22604 Support new Ingress pathType
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/testdata/simple.yaml
  pilot/pkg/config/kube/ingress/testdata/simple.yaml.golden
Labels: cla: yes, size/M

#22701 Set readOnlyRootFilesystem to true for istio-init with Istio CNI is enabled
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  operator/pkg/vfs/assets.gen.go
  pkg/kube/inject/testdata/inject/hello.yaml.cni.injected
Labels: area/networking, area/networking/cni, area/security, cherrypick/release-1.5, cla: yes, size/XS

#22731 Skip flaky TestCertRotation test
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
  security/pkg/nodeagent/test/csr_failure/csr_test.go
  security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
Labels: cla: yes, size/XS

#22692 use `CA_ADDR` to align with the env variable `CA_ADDR` used in sds_agent.go
  tools/packaging/common/istio-start.sh
  tools/packaging/common/sidecar.env
  tools/packaging/deb/deb_test.sh
Labels: cla: yes, size/XS

#22719 Remove ICP translation
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/manifest-migrate.go
  operator/cmd/mesh/manifest-migrate_test.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/testdata/manifest-generate/input/icp_input.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/icp_input.golden.yaml
  operator/cmd/mesh/testdata/manifest-migrate/input/default_icp_iop.yaml
  operator/cmd/mesh/testdata/manifest-migrate/output/default_icp_iop.golden.yaml
  operator/cmd/mesh/testdata/manifest-migrate/output/default_icp_iop.yaml
  operator/data/translateConfig/translate-ICP-IOP-1.5.yaml
  operator/data/translateConfig/translate-ICP-IOP-1.6.yaml
  operator/pkg/apis/istio/v1alpha1/common.go
  operator/pkg/apis/istio/v1alpha2/common.go
  operator/pkg/apis/istio/v1alpha2/deepcopy.go
  operator/pkg/apis/istio/v1alpha2/doc.go
  operator/pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  operator/pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  operator/pkg/apis/istio/v1alpha2/register.go
  operator/pkg/component/component.go
  operator/pkg/helmreconciler/dependencies.go
  operator/pkg/helmreconciler/interfaces.go
  operator/pkg/helmreconciler/patching.go
  operator/pkg/helmreconciler/reconciler.go
  operator/pkg/kubectlcmd/client.go
  operator/pkg/manifest/installer.go
  operator/pkg/name/name.go
  operator/pkg/object/objects.go
  operator/pkg/translate/icp_iop.go
  operator/pkg/translate/translate.go
  operator/pkg/translate/yaml_tree_test.go
  operator/pkg/util/annotation.go
  operator/pkg/util/common.go
  operator/pkg/util/label.go
  operator/pkg/util/reflect.go
  operator/pkg/validate/common.go
  operator/pkg/vfs/assets.gen.go
  operator/pkg/vfs/vfs.go
Labels: cla: yes, size/XXL

#22707 Remove HTTP on 443 hack, extend testing
  pilot/pkg/features/pilot.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pkg/test/echo/common/scheme/scheme.go
  pkg/test/echo/server/forwarder/protocol.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/docker/port.go
  pkg/test/framework/components/prometheus/kube.go
  tests/integration/mixer/outboundtrafficpolicy/helper.go
  tests/integration/mixer/outboundtrafficpolicy/traffic_allow_any_test.go
  tests/integration/mixer/outboundtrafficpolicy/traffic_registry_only_test.go
  tests/integration/mixer/outboundtrafficpolicy/v2/traffic_allow_any_test.go
  tests/integration/mixer/outboundtrafficpolicy/v2/traffic_registry_only_test.go
Labels: cla: yes, size/L

#22738 fix indentation issue for sidecar injector.
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  operator/pkg/vfs/assets.gen.go
Labels: area/environments, cla: yes, size/XS

#22682 Add --revision to CLI troubleshooting commands that consult Pilot
  istioctl/cmd/authz.go
  istioctl/cmd/dashboard.go
  istioctl/cmd/dashboard_test.go
  istioctl/cmd/describe.go
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/proxystatus_test.go
  istioctl/cmd/root.go
  istioctl/cmd/version.go
  istioctl/cmd/version_test.go
  istioctl/cmd/wait.go
  istioctl/cmd/wait_test.go
  istioctl/pkg/clioptions/control_plane.go
  istioctl/pkg/clioptions/doc.go
  istioctl/pkg/kubernetes/client.go
Labels: cla: yes, size/L

#22744 Add initial metadata into Opencensus sts option
  install/gcp/bootstrap/gcp_envoy_bootstrap.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/S

#22745 listener: minor improvements to listeners
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/L

#22369 Initial DNS support in Istiod
  go.mod
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  manifests/istio-control/istio-discovery/templates/configmap.yaml
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  manifests/istio-control/istio-discovery/templates/service.yaml
  manifests/istio-control/istio-discovery/values.yaml
  operator/pkg/vfs/assets.gen.go
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/bootstrap/server.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  tests/istio.mk
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: cla: yes, size/XXL

#22748 fix iptables null point panic
  tools/istio-iptables/pkg/cmd/run.go
Labels: area/networking, cla: yes, ok-to-test, size/XS

#22720 Clean up dead values.yaml fields
  istioctl/pkg/multicluster/generate.go
  manifests/istio-telemetry/prometheus/templates/deployment.yaml
  manifests/istio-telemetry/prometheus/values.yaml
  manifests/istio-telemetry/prometheusOperator/templates/servicemonitors.yaml
  manifests/istio-telemetry/prometheusOperator/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/files/crd-all.gen.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/files/gen-istio-cluster.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/prometheus/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/prometheusOperator/templates/servicemonitors.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/prometheusOperator/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/all_on.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-migrate/input/default_values.yaml
  operator/cmd/mesh/testdata/manifest-migrate/output/default_values.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/data/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/translate/translate_value_test.go
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#22754 Do not fail for old Kubernetes versions on ingressclass
  pilot/pkg/config/kube/ingress/controller.go
Labels: cla: yes, size/M

#22755 Analyzer for istio.io/rev revision label on namespaces
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/injection/injection.go
  galley/pkg/config/analysis/analyzers/testdata/injection.yaml
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: cla: yes, size/L

#22684 Pass revision through to webhook properly
  pkg/kube/inject/webhook.go
Labels: cla: yes, size/XS

#22736 [release-1.5] Set readOnlyRootFilesystem to true for istio-init with Istio CNI is enabled
  install/kubernetes/helm/istio/files/injection-template.yaml
  manifests/istio-control/istio-autoinject/files/injection-template.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  operator/pkg/vfs/assets.gen.go
  pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-set-in-annotation.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-unset-in-annotation.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/hello-probes.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/hello-readiness.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/https-probes.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/named_port.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/one_container.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/ready_live.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/ready_only.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/two_container.yaml.injected
  pkg/kube/inject/testdata/inject/hello.yaml.cni.injected
Labels: area/networking, area/networking/cni, cla: yes, size/M

#22761 Update proxy sha and enable blackholecluster integration tests
  istio.deps
  tests/integration/mixer/outboundtrafficpolicy/v2/traffic_registry_only_test.go
Labels: area/policies and telemetry, cla: yes, size/S

#21857 DestinationRule for specific host matches wildcards (fixes #19459)
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
Labels: cla: yes, ok-to-test, size/S

#22753 Optimize mgmt listener build
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
Labels: cla: yes, size/L

#21437 Apply ratelimiting to external services
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.gen.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
Labels: area/policies and telemetry, cherrypick/release-1.5, cla: yes, size/L

#22606 Add resync period to namespace controller
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/namespacecontroller.go
  pilot/pkg/bootstrap/namespacecontroller_test.go
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, size/S

#22757 Remove separate profile
  operator/data/profiles/separate.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#22712 Fix ServiceEntry incremental updates, extend testing
  pilot/pkg/config/memory/config.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/test/mock/config.go
Labels: cla: yes, size/XL

#22752 Remove reflect.DeepEqual from listener hot path
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/M

#22771 Added push type for PeerAuthentication and RequestAuthentication
  pilot/pkg/proxy/envoy/v2/ads_common.go
  pilot/pkg/proxy/envoy/v2/ads_common_test.go
Labels: area/networking, cla: yes, size/M

#22772 listener: use discovered ip version information
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: area/networking, cla: yes, size/M

#22774 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22773 [1.5] Add resync period to namespace controller (#22606)
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/namespacecontroller.go
  pilot/pkg/bootstrap/namespacecontroller_test.go
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, size/S

#22776 Remove some artifacts of the operator repository merge
  operator/CODEOWNERS
  operator/scripts/run_mandiff.sh
  operator/scripts/run_migrate_profile.sh
Labels: area/environments, cla: yes, size/L

#22671 Integration tests for plugging in the CA key and certificate
  pkg/test/framework/components/bookinfo/kube.go
  pkg/test/framework/components/istio/istio.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/components/namespace/namespace.go
  pkg/test/kube/accessor.go
  tests/integration/security/plugin_ca_key_cert/main_test.go
  tests/integration/security/plugin_ca_key_cert/plugin_ca_key_cert_test.go
Labels: area/security, cla: yes, size/L

#22778 Fix local `make clean init`
  Makefile.core.mk
Labels: cla: yes, size/XS

#22786 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22626 Add deprecation messages
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/templates/configmap.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/configmap.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/service.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/prometheus/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/component_hub_tag.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/install_package_path.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/data/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XL

#22787 Add annotations for setting cpu/memory limits on sidecar
  manifests/istio-control/istio-autoinject/files/injection-template.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  operator/pkg/vfs/assets.gen.go
  pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-set-in-annotation.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/hello-probes-with-flag-unset-in-annotation.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/hello-probes.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/hello-readiness.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/https-probes.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/named_port.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/one_container.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/ready_live.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/ready_only.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/two_container.yaml.injected
  pkg/kube/inject/testdata/webhook/resource_annotations.yaml
  pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
Labels: area/config, cla: yes, ok-to-test, size/M

#22793 Align envoy log format with Istio
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: cla: yes, size/XS

#22790 Don't error on missing configs in aggregate store
  pilot/pkg/config/aggregate/config.go
Labels: cla: yes, size/XS

#22791 Select new labels in istioctl
  istioctl/pkg/kubernetes/client.go
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#22797 get/set correct namespace from iop instance.
  operator/pkg/apis/istio/v1alpha1/common.go
Labels: cla: yes, size/XS

#22810 operator: remove files that are no longer used
  operator/hack/sdk
  operator/prow/e2e_install.sh
  operator/prow/k8s/mtls_permissive.yaml
  operator/prow/k8s/mtls_strict.yaml
  operator/prow/k8s/sidecar-local.yaml
  operator/tests/codecov/main.go
  operator/tests/codecov/main_test.go
  operator/tests/e2e/e2e.sh
  operator/tests/profiles/helm/values-istio-default.yaml
  operator/tests/profiles/helm/values-istio-demo.yaml
  operator/tests/profiles/helm/values-istio-minimal.yaml
Labels: cla: yes, size/XL

#22722 Manual cherry pick of fix blackhole and passthrough for telemetry v2 …
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/util/util.go
Labels: area/networking, area/policies and telemetry, cla: yes, size/S

#22809 Add REVISION column to 'kubectl get istiooperator'
  manifests/base/files/crd-operator.yaml
  manifests/base/files/gen-istio-cluster.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#22691 [release-1.5] fix operator validation of slice
  operator/pkg/validate/validate.go
  operator/pkg/validate/validate_test.go
Labels: cla: yes, size/S

#22709 Fix immutable field change, add regression test
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#22758 Disable DNS feature by default
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  manifests/istio-control/istio-discovery/values.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#22788 Remove inbound listeners
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  tests/integration/pilot/envoyfilter/main_test.go
  tests/integration/pilot/sidecarscope/scope_serviceentry_static_test.go
  tests/integration/security/mtls_permissive_test.go
Labels: cla: yes, size/L

#22820 feat(gcp): add additional metadata for gce managed instance groups
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
Labels: area/policies and telemetry, cla: yes, size/L

#22819 Fix race condition in test
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: area/security, cla: yes, size/XS

#22823 Stop using deprecated filters naming/config
  pilot/pkg/networking/core/v1alpha3/filters.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/L

#22737 fix gateway name and labels.
  manifests/gateways/istio-ingress/templates/gateway.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#22828 render the mutatingwebhook name correctly for other namespaces
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  operator/pkg/vfs/assets.gen.go
Labels: area/config, area/environments, cla: yes, size/XS

#22829 [release-1.5] Fix broken link in istio operator schema validation
  operator/pkg/validate/validate_values.go
Labels: cla: yes, size/XS

#22832 unit test fix for TestEds
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: area/test and release, cla: yes, ok-to-test, size/S

#22822 Migrate SAN verification off deprecated option
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  pkg/bootstrap/option/convert.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/XL

#22817 Generate separate test files for each SDS and STS test.
  mixer/test/client/env/setup.go
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
  security/pkg/nodeagent/test/csr_failure/csr_test.go
  security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/nodeagent/test/testdata/bootstrap.yaml
  security/pkg/stsservice/test/setup.go
  security/pkg/stsservice/test/testdata/bootstrap.yaml
  security/pkg/stsservice/test/testdata/trustworthy-jwt.jwt
Labels: area/security, cla: yes, size/M

#22792 Update gopher-lua library
  go.mod
  go.sum
  licenses/github.com/chzyer/logex/LICENSE
  licenses/github.com/chzyer/readline/LICENSE
  licenses/github.com/chzyer/test/LICENSE
Labels: cla: yes, size/M

#22836 remove legacy TODO
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
Labels: cla: yes, size/S

#22706 Remove jwt analyzer
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/auth/jwt.go
  galley/pkg/config/analysis/analyzers/deprecation/deprecation.go
  galley/pkg/config/analysis/analyzers/testdata/deprecation.yaml
  galley/pkg/config/analysis/analyzers/testdata/jwt-invalid-service-port-name.yaml
  galley/pkg/config/analysis/analyzers/testdata/jwt-valid-service-port-name.yaml
Labels: area/security, area/user experience, cla: yes, size/XL

#22818 Fix lint errors for golangci-lint 1.24
  galley/pkg/config/processor/transforms/ingress/virtualService.go
  galley/pkg/config/source/kube/apiserver/status/controller_test.go
  galley/pkg/testing/mock/configmaps.go
  galley/pkg/testing/mock/selfsubjectaccessreviews.go
  istioctl/cmd/add-to-mesh_test.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/remove-from-mesh_test.go
  istioctl/cmd/version.go
  istioctl/pkg/writer/compare/route.go
  mixer/adapter/bypass/bypass_test.go
  mixer/pkg/il/testing/tests.go
  mixer/pkg/lang/ast/expr_test.go
  mixer/pkg/lang/checker/checker_test.go
  mixer/pkg/protobuf/yaml/dynamic/auth_test.go
  mixer/pkg/runtime/config/config_test.go
  mixer/pkg/runtime/runtime_test.go
  mixer/template/sample/createinstance_test.go
  mixer/template/sample/template.gen_test.go
  mixer/test/client/env/mixer_filter_config.go
  operator/cmd/mesh/manifest-generate_test.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/serviceregistry/consul/controller_test.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pkg/config/mesh/mesh_test.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/webhook_test.go
  pkg/mcp/sink/journal_test.go
  pkg/test/cert/ca/root.go
  pkg/test/fakes/policy/backend.go
  pkg/test/framework/components/bookinfo/kube.go
  pkg/test/kube/kubectl.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
  security/pkg/nodeagent/test/csr_failure/csr_test.go
  security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
  security/pkg/nodeagent/test/success_sds/sds_test.go
  security/pkg/pki/util/generate_csr_test.go
  security/pkg/stsservice/test/success_sts/proxy_sts_test.go
  tests/integration/mixer/telemetry/metrics/scenarios_test.go
  tests/integration/pilot/meshnetwork/main_test.go
  tests/integration/telemetry/dashboard_test.go
  tests/integration/telemetry/stats/prometheus/tcp/stats_tcp_filter_test.go
  tests/integration/telemetry/tracing/tracing.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: cla: yes, size/XL

#22838 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#22843 Skip flaky test
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
Labels: area/security, cla: yes, size/XS

#22816 Update proxy sha to point to blackhole telemetry fix in 1.5
  istio.deps
Labels: area/policies and telemetry, cla: yes, size/XS

#22794 Refactor tests not to use compiled in charts
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/manifest-migrate_test.go
  operator/cmd/mesh/manifest-versions_test.go
  operator/cmd/mesh/manifest_shared_test.go
  operator/cmd/mesh/operator-common.go
  operator/cmd/mesh/operator_test.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/profile-dump_test.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/shared_test.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/files/crd-operator.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/files/gen-istio-cluster.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/separate.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/component_hub_tag.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/install_package_path.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
  operator/pkg/controller/istiocontrolplane/rendering_test.go
  operator/pkg/helm/helm.go
  operator/pkg/helm/helm_test.go
  operator/pkg/helm/vfs_renderer.go
  operator/pkg/helmreconciler/rendering.go
  operator/pkg/name/name.go
  operator/pkg/validate/validate_test.go
  operator/scripts/run_update_golden_snapshots.sh
  pkg/kube/inject/webhook_test.go
Labels: cla: yes, size/XL

#22531 Initial support for WorkloadEntry
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/external/controller_test.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
Labels: cla: yes, size/XXL

#22839 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22807 Remove legacy autorest replacements
  go.mod
  go.sum
Labels: cla: yes, size/S

#22824 Add source file line number to analyze messages
  galley/pkg/config/analysis/analyzers/analyzers_bench_test.go
  galley/pkg/config/analysis/analyzers/schema/validation_test.go
  galley/pkg/config/analysis/diag/helper_test.go
  galley/pkg/config/analysis/diag/message.go
  galley/pkg/config/analysis/diag/message_test.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  galley/pkg/config/source/kube/apiserver/watcher.go
  galley/pkg/config/source/kube/inmemory/kubesource.go
  galley/pkg/config/source/kube/rt/adapter.go
  galley/pkg/config/source/kube/rt/extract.go
  galley/pkg/config/source/kube/rt/origin.go
  galley/pkg/config/source/kube/rt/origin_test.go
  galley/pkg/config/source/mcp/origin.go
  galley/pkg/config/util/kubeyaml/kubeyaml.go
  galley/pkg/config/util/kubeyaml/kubeyaml_test.go
  go.sum
  istioctl/cmd/analyze.go
  pkg/config/resource/origin.go
Labels: cla: yes, size/L

#22847 [release-1.5] Updating deps for release-1.5 branch
  go.mod
  go.sum
  install/kubernetes/helm/istio-init/files/crd-all.gen.yaml
  istio.deps
  manifests/base/files/crd-all.gen.yaml
  operator/pkg/vfs/assets.gen.go
  prow/release-commit.sh
Labels: cla: yes, size/S

#22853 Remove AllowOrigin from route since it is deprecated in istio API
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
Labels: area/networking, cla: yes, size/M

#22826 check annotation validity in analyzer
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/annotations/annotations.go
  galley/pkg/config/analysis/analyzers/testdata/misannotated.yaml
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  pkg/kube/inject/inject.go
Labels: cla: yes, size/M

#22854 Use jsonpb for validation
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_merge_meshconfig.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/pkg/validate/common.go
Labels: cla: yes, size/S

#22118 Implement virtualService delegate
  go.mod
  pilot/pkg/features/pilot.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
  pilot/pkg/util/sets/string.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/config/validation/virtualservice.go
  pkg/config/validation/virtualservice_test.go
Labels: area/networking, area/user experience, cla: yes, size/XXL

#22862 perf: remove some more sprintf calls in hot path
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/conversion.go
Labels: area/networking, cla: yes, size/M

#22865 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#22866 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22869 Revert CoreDNS sidecar.
  manifests/base/files/crd-operator.yaml
  manifests/base/files/gen-istio-cluster.yaml
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/templates/configmap.yaml
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  operator/pkg/vfs/assets.gen.go
  tests/istio.mk
Labels: cla: yes, size/M

#22831 Fixes #22830. Don't mutate proxy IPAddresses while building listeners
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: area/networking, cla: yes, ok-to-test, size/XS

#22844 Mark mtls.enabled as deprecated
  operator/README.md
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/data/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/translate/translate_value_test.go
  operator/pkg/vfs/assets.gen.go
  pkg/test/framework/components/istio/config.go
Labels: cla: yes, size/S

#22821 Disable using host header in gateway stats filter
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/templates/telemetryv2_1.4.yaml
  manifests/istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
  manifests/istio-control/istio-discovery/templates/telemetryv2_1.6.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#22858 only allow vs delegation on gateways
  pilot/pkg/model/virtualservice.go
  pkg/config/validation/validation.go
  pkg/config/validation/virtualservice_test.go
Labels: cla: yes, size/S

#22886 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/S

#22033 Implementation of incremental MCP
  galley/pkg/envvar/envvars.go
  galley/pkg/server/components/processing.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/mcp/controller.go
  pilot/pkg/serviceregistry/mcp/controller_test.go
  pkg/mcp/source/source.go
  pkg/mcp/source/source_test.go
Labels: area/perf and scalability, cla: yes, lifecycle/stale, ok-to-test, size/L

#22116 add link to zenhub extension download
  README.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#22892 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22890 Increase error level of not ready log
  pilot/cmd/pilot-agent/status/server.go
Labels: cla: yes, size/XS

#22846 'istioctl verify-install' consume IstioOperator
  istioctl/pkg/install/verify.go
  istioctl/pkg/validate/validate.go
Labels: cla: yes, size/L

#22864 support port-level traffic policy on inbound cluster
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, ok-to-test, size/L

#22898 route: optimize virtual service route generation
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pkg/config/host/name.go
Labels: cla: yes, size/M

#22859 listener: simplify and optimize mergeTCPFilterChains implementation
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: area/networking, cla: yes, size/L

#22833 Integration test for certificate issued by CA to sidecar and mTLS
  tests/integration/security/cert_mtls/cert_mtls_test.go
  tests/integration/security/cert_mtls/main_test.go
  tests/integration/security/plugin_ca_key_cert/main_test.go
  tests/integration/security/plugin_ca_key_cert/plugin_ca_key_cert_test.go
  tests/integration/security/util/cert/cert.go
  tests/integration/security/util/dir/util.go
Labels: area/security, cla: yes, size/XL

#22827 enable PROV_CERT in sidecar.env by default
  tools/packaging/common/istio-start.sh
  tools/packaging/common/sidecar.env
Labels: cla: yes, size/XS

#22881 add resource status check after process manifests
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
  operator/pkg/helmreconciler/reconciler.go
Labels: cla: yes, size/M

#22789 Improve the Istio-agent secret cache.
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/cache/mock/secretcache_mock.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/cache/testdata/cert-chain.pem
  security/pkg/nodeagent/cache/testdata/key.pem
  security/pkg/nodeagent/cache/testdata/privatekey.pem
  security/pkg/nodeagent/cache/testdata/root-cert.pem
  security/pkg/util/jwtutil.go
  security/pkg/util/jwtutil_test.go
Labels: area/security, cla: yes, size/XL

#22877 Do not install older telemetry v2 config when revision is set
  manifests/istio-control/istio-discovery/templates/telemetryv2_1.4.yaml
  manifests/istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#22906 fix typo in error logs of security/
  security/tools/generate_cert/main.go
Labels: area/security, cla: yes, size/XS

#22891 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#22917 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22662 support for setting k8s overlay from values
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_override_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-migrate/output/default_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-migrate/output/overlay_values.golden.yaml
  operator/pkg/helmreconciler/rendering.go
  operator/pkg/translate/translate_value.go
  operator/pkg/translate/translate_value_test.go
Labels: cla: yes, size/L

#22876 Fix revision CR scoping
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/serviceregistry/mcp/controller.go
Labels: cherrypick/release-1.5, cla: yes, size/M

#22921 crd client cleanup
  pilot/pkg/config/kube/crd/controller/client.go
Labels: area/config, cla: yes, size/L

#22924 add container status check
  operator/pkg/helmreconciler/reconciler.go
Labels: cla: yes, size/S

#22867 Improve validation for selector on SE
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: cla: yes, size/M

#22922 [release-1.5] Fix revision CR scoping
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/serviceregistry/mcp/controller.go
Labels: cla: yes, size/M

#22932 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#22923 Fix debug handler /debug/inject
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, size/S

#22933 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#22937 Fix trailing spaces in manifest
  manifests/gateways/istio-ingress/templates/poddisruptionbudget.yaml
  manifests/gateways/istio-ingress/templates/serviceaccount.yaml
  manifests/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  manifests/istio-control/istio-discovery/templates/configmap.yaml
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/object/objects.go
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/M
