Repository istio/istio, pull requests merged in 2020-08, with the labels that each got.

#25986 Expand endpoints before pod test to check pod
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: cherrypick/release-1.6, cherrypick/release-1.7, cla: yes, release-notes-none, size/M

#26028 Move meshExpansion to ControlPlaneValues in tests
  pkg/test/framework/components/istio/operator.go
  tests/integration/multicluster/base/main_test.go
  tests/integration/multicluster/centralistio/main_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#25990 fix NodePort services for meshNetworks gateway
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/xds/xds_test.go
  releasenotes/notes/fix-nodeport-meshnetwork.yaml
Labels: area/networking, cla: yes, size/L

#26025 Don't log panic in unit test
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
  pilot/pkg/util/runtime/runtime.go
  pilot/pkg/util/runtime/runtime_test.go
Labels: cla: yes, release-notes-none, size/S

#26033 [release-1.7] Expand endpoints before pod test to check pod
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: cla: yes, release-notes-none, size/M

#26023 Adopt new label changes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes, release-notes-none, size/XS

#25964 fixing dns resolution issues
  docker/Dockerfile.base
  istioctl/pkg/util/configdump/listener.go
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  pilot/pkg/networking/core/v1alpha3/dns_listener.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  releasenotes/notes/dns-capture.yaml
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/routing_test.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: cla: yes, release-notes-none, size/L

#25966 update go control plane
  go.mod
  go.sum
  istioctl/pkg/authz/listener.go
  istioctl/pkg/writer/envoy/configdump/listener.go
  istioctl/pkg/writer/envoy/configdump/listener_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/xds/lds_test.go
  pilot/pkg/xds/xds_test.go
  pkg/adsc/adsc.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/config/xds/filter_types.gen.go
  releasenotes/notes/envoy-filter.yaml
Labels: cla: yes, size/L

#26005 properly drain gateway listeners
  pilot/cmd/pilot-agent/main.go
  pkg/envoy/admin.go
  pkg/envoy/instance.go
  pkg/envoy/proxy.go
Labels: cla: yes, release-notes-none, size/S

#26039 move v2 registration out of main path
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/simple.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#26058 Fix networking.HTTPMatchRequest.WithoutHeaders conflict detect
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
  pkg/config/validation/virtualservice.go
Labels: cherrypick/release-1.6, cherrypick/release-1.7, cla: yes, release-notes-none, size/S

#26057 gateway: optimize http route generation for gateways
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/xds/testdata/benchmarks/gateways.yaml
Labels: cla: yes, release-notes-none, size/L

#26044 [manual cherry-pick] fixing dns resolution issues (#25964)
  docker/Dockerfile.base
  istioctl/pkg/util/configdump/listener.go
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  pilot/pkg/networking/core/v1alpha3/dns_listener.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  releasenotes/notes/dns-capture.yaml
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: cla: yes, size/L

#26047 [manual cherry-pick] Add credential fetcher in istio agent (#25614)
  pilot/cmd/pilot-agent/main.go
  pkg/istio-agent/sds-agent.go
  pkg/security/security.go
  security/pkg/credentialfetcher/fetcher.go
  security/pkg/credentialfetcher/fetcher_test.go
  security/pkg/credentialfetcher/plugin/gce.go
  security/pkg/credentialfetcher/plugin/mock.go
  security/pkg/nodeagent/cache/mock/secretcache_mock.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/stsservice/test/setup.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin_test.go
  security/pkg/stsservice/tokenmanager/sts_test.go
  security/pkg/stsservice/tokenmanager/tokenmanager.go
Labels: cla: yes, release-notes-none, size/XL

#26065 [release-1.7] Fix networking.HTTPMatchRequest.WithoutHeaders conflict detect
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
  pkg/config/validation/virtualservice.go
Labels: cla: yes, release-notes-none, size/S

#26029 Support TCP server first protocol in echo
  pkg/test/echo/cmd/client/main.go
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/model.go
  pkg/test/echo/proto/echo.pb.go
  pkg/test/echo/proto/echo.proto
  pkg/test/echo/server/endpoint/tcp.go
  pkg/test/echo/server/forwarder/instance.go
  pkg/test/echo/server/forwarder/protocol.go
  pkg/test/echo/server/forwarder/tcp.go
Labels: cla: yes, release-notes-none, size/L

#26071 revert benchmark gateway config
  pilot/pkg/xds/testdata/benchmarks/gateways.yaml
Labels: area/networking, cla: yes, release-notes-none, size/M

#26067 Automator: update common-files@release-1.7 in istio/istio@release-1.7
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26069 Automator: update istio/api@release-1.7 dependency in istio/istio@release-1.7
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26016 Pilot unit test improvements
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/cds_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/debug_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/discovery_test.go
  pilot/pkg/xds/eds_sh_test.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/init_test.go
  pilot/pkg/xds/lds_test.go
  pilot/pkg/xds/rds_test.go
  pkg/adsc/adsc.go
Labels: cla: yes, release-notes-none, size/XXL

#26054 [release-1.7] properly drain gateway listeners
  pilot/cmd/pilot-agent/main.go
  pkg/envoy/admin.go
  pkg/envoy/instance.go
  pkg/envoy/proxy.go
Labels: cla: yes, release-notes-none, size/S

#26076 Automator: update proxy@release-1.7 in istio/istio@release-1.7
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26046 Disable compiled wasm
  manifests/profiles/default.yaml
  manifests/profiles/preview.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/preview.yaml
Labels: cla: yes, release-notes-none, size/S

#26078 Skip TestMeshNetworking test
  pilot/pkg/xds/xds_test.go
Labels: cla: yes, release-notes-none, size/XS

#25624 [release-1.7] Update Mixer server to enable Ext-Authz and Access Log Service
  mixer/pkg/api/envoyGrpcServer.go
  mixer/pkg/attribute/envoyProtoBag.go
  mixer/pkg/attribute/envoyProtoBag_test.go
  mixer/pkg/attribute/responeFlagParser.go
  mixer/pkg/server/server.go
Labels: cla: yes, ok-to-test, release-notes-none, size/XXL

#26077 Fix pilot race errors
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/internalgen.go
Labels: cla: yes, release-notes-none, size/S

#25755 DestinationRule Analyzer against no caCertificates
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/destinationrule/ca-certificates.go
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-compound-mutual-simple.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-compound-simple-mutual.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-mutual-destination.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-mutual-port.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-simple-port.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-with-ca.yaml
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/dr-analyzer.yaml
Labels: cherrypick/release-1.5, cherrypick/release-1.6, cherrypick/release-1.7, cla: yes, size/L

#26088 [release-1.7] DestinationRule Analyzer against no caCertificates
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/destinationrule/ca-certificates.go
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-compound-mutual-simple.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-compound-simple-mutual.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-mutual-destination.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-mutual-port.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-simple-port.yaml
  galley/pkg/config/analysis/analyzers/testdata/destinationrule-with-ca.yaml
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/dr-analyzer.yaml
Labels: cla: yes, release-notes-none, size/L

#26072 Namespace all addons
  samples/addons/extras/prometheus-operator.yaml
  samples/addons/extras/zipkin.yaml
  samples/addons/jaeger.yaml
Labels: cherrypick/release-1.7, cla: yes, release-notes-none, size/XS

#26074 Add ParseToken flag
  pilot/cmd/pilot-agent/main.go
  pkg/security/security.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: area/security, cherrypick/release-1.7, cla: yes, release-notes-none, size/L

#26093 [release-1.7] Namespace all addons
  samples/addons/extras/prometheus-operator.yaml
  samples/addons/extras/zipkin.yaml
  samples/addons/jaeger.yaml
Labels: cla: yes, release-notes-none, size/XS

#26011 Revert "refactor: convert IstioOperator from Unstructured more efficiently"
  istioctl/pkg/install/verify.go
  istioctl/pkg/install/verify_test.go
Labels: cla: yes, release-notes-none, size/M

#26061 Increase grpc connection timeout
  pilot/pkg/model/config_test.go
  pkg/test/echo/client/client.go
  pkg/test/echo/common/util.go
Labels: cla: yes, release-notes-none, size/XS

#26096 [release-1.7] Add ParseToken flag
  pilot/cmd/pilot-agent/main.go
  pkg/security/security.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: cla: yes, release-notes-none, size/L

#26105 fix nil pointer issue of logger during validation test
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
Labels: cla: yes, release-notes-none, size/XS

#26106 Update installation guide URL for download Istio candidate
  release/downloadIstioCandidate.sh
Labels: area/test and release, cherrypick/release-1.7, cla: yes, community/testing days, release-notes-none, size/XS

#26082 Don't claim 'istioctl validate' is deprecated
  istioctl/pkg/validate/validate.go
Labels: cherrypick/release-1.7, cla: yes, release-notes-none, size/XS

#25835 Remove dead code for codecov and bookinfo output
  .codecov.yml
  bin/codecov.sh
  bin/codecov_diff.sh
  codecov.skip
  codecov.threshold
  go.mod
  operator/.codecov.yml
  operator/codecov.skip
  operator/codecov.threshold
  tests/apps/bookinfo/output/productpage-normal-user-v1.html
  tests/apps/bookinfo/output/productpage-normal-user-v2.html
  tests/apps/bookinfo/output/productpage-normal-user-v3.html
  tests/apps/bookinfo/output/productpage-test-user-v1-review-timeout.html
  tests/apps/bookinfo/output/productpage-test-user-v2.html
  tests/codecov/main.go
  tests/codecov/main_test.go
Labels: cla: yes, release-notes-none, size/XXL

#26008 Remove endpoints when the new labels do not match the selector
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  releasenotes/notes/25678.yaml
Labels: area/networking, cla: yes, ok-to-test, size/L

#26040 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#26114 [release-1.7] Update deps
  go.mod
  go.sum
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/XS

#26073 Disable Ingress for kiali
  manifests/addons/values-kiali.yaml
  samples/addons/kiali.yaml
Labels: cla: yes, release-notes-none, size/XS

#26092 Fix EDS tests
  pilot/pkg/xds/eds_test.go
Labels: cla: yes, size/S

#26108 rename EnvoyXdsServer to XDSServer
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/multicluster.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/xds/lds_test.go
  pilot/pkg/xds/simple_test.go
Labels: cla: yes, release-notes-none, size/M

#26113 [release-1.7] Update installation guide URL for download Istio candidate
  release/downloadIstioCandidate.sh
Labels: cla: yes, release-notes-none, size/XS

#26085 fix mesh network flakes
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/xds_test.go
Labels: area/networking, area/test and release, cla: yes, release-notes-none, size/M

#26121 Add more context to error log on test framework init
  pkg/test/framework/components/echo/kube/builder.go
Labels: cla: yes, size/XS

#26087 ApplyMeshConfig allow overriding with default value
  pilot/cmd/pilot-agent/config_test.go
  pkg/config/mesh/mesh.go
Labels: cherrypick/release-1.7, cla: yes, release-notes-none, size/M

#26120 [release-1.7] Fix pilot race errors (#26077)
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/internalgen.go
Labels: cla: yes, release-notes-none, size/S

#26124 [release-1.7] Fix issues in manifests
  Makefile.core.mk
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
Labels: cla: yes, release-notes-none, size/S

#26117 [release-1.7] Don't claim 'istioctl validate' is deprecated
  istioctl/pkg/validate/validate.go
Labels: cla: yes, release-notes-none, size/XS

#26129 [release-1.7] ApplyMeshConfig allow overriding with default value
  pilot/cmd/pilot-agent/config_test.go
  pkg/config/mesh/mesh.go
Labels: cla: yes, release-notes-none, size/M

#26001 Remove SDS Timeout
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/convert_test.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  releasenotes/notes/26001.yaml
Labels: cla: yes, size/M

#26022 add an example of using holdApplicationUntilProxyStarts
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/24737.yaml
Labels: area/environments, cla: yes, size/XS

#26132 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26137 [Release 1.7] Manual cherrypick of #25818
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/networking.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/security/authn/factory/factory.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  releasenotes/notes/25818.yaml
  tests/integration/security/authorization_test.go
  tests/integration/security/testdata/authz/v1beta1-egress-gateway.yaml.tmpl
Labels: cla: yes, size/L

#26127 Misc pilot unit test improvements
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/pushqueue_test.go
  pilot/pkg/xds/simple.go
  pkg/adsc/adsc.go
  pkg/istio-agent/sds-agent.go
  pkg/istio-agent/xds-agent.go
  pkg/test/env/http_client.go
Labels: cla: yes, release-notes-none, size/M

#25934 Reject invalid jwks and add integration test for jwt rules
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/testdata/requestauthn/a-authn.yaml.tmpl
  tests/integration/security/testdata/requestauthn/b-authn-authz.yaml.tmpl
  tests/integration/security/testdata/requestauthn/c-authn.yaml.tmpl
  tests/integration/security/testdata/requestauthn/e-authn.yaml.tmpl
  tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl
Labels: cla: yes, release-notes-none, size/M

#26118 Add pure in-memory analyzer source
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
Labels: cla: yes, release-notes-none, size/M

#26091 Create code sample for exposing istiod through ingress and use it in tests
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/operator.go
  samples/istiod-gateway/istiod-gateway.yaml
  tests/integration/multicluster/base/main_test.go
  tests/integration/multicluster/centralistio/main_test.go
  tests/integration/pilot/main_test.go
  tests/integration/security/main_test.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
Labels: area/test and release, cla: yes, kind/docs, release-notes-none, size/L

#26030 Update Proxy SHA
  istio.deps
  pkg/test/framework/components/stackdriver/kube.go
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/vm/testdata/server_access_log.json.tmpl
Labels: cla: yes, size/S

#26143 Cleanup unused node metadata
  pilot/pkg/model/context.go
Labels: cla: yes, size/S

#26149 [release-1.7] manual add an example of using holdApplicationUntilProxyStarts #26022
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/24737.yaml
Labels: area/environments, cla: yes, size/S

#26144 values: labels is a map, not a struct
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: cla: yes, size/S

#26110 Fix incorrect lb endpoints for DNS ServiceEntry with workload selector
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Labels: cla: yes, release-notes-none, size/M

#26147 fix operator remove
  operator/pkg/helmreconciler/prune.go
  tests/integration/operator/switch_cr_test.go
Labels: cherrypick/release-1.7, cla: yes, size/M

#26156 [release-1.7] fix operator remove
  operator/pkg/helmreconciler/prune.go
  tests/integration/operator/switch_cr_test.go
Labels: cla: yes, release-notes-none, size/M

#26159 Rename manifest apply to install
  operator/ARCHITECTURE.md
  operator/cmd/mesh/install.go
Labels: cla: yes, release-notes-none, size/XS

#26165 Automator: update proxy@release-1.7 in istio/istio@release-1.7
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26166 Automator: update istio/api@release-1.7 dependency in istio/istio@release-1.7
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26163 [kiali] use the new kiali server helm chart
  manifests/addons/gen.sh
  manifests/addons/values-kiali.yaml
  samples/addons/kiali.yaml
Labels: area/environments, cherrypick/release-1.7, cla: yes, release-notes-none, size/XXL

#26170 [release-1.7][kiali] use the new kiali server helm chart (#26163)
  manifests/addons/gen.sh
  manifests/addons/values-kiali.yaml
  samples/addons/kiali.yaml
Labels: cla: yes, release-notes-none, size/XXL

#26172 Fix: VM post-submit test should be deployed with each image
  tests/integration/pilot/vm_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#26175 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#25996 Refactor istioctl analyze and analysis messages
  galley/pkg/config/analysis/diag/helper.go
  galley/pkg/config/analysis/diag/message.go
  galley/pkg/config/analysis/diag/messages.go
  galley/pkg/config/analysis/diag/messages_test.go
  istioctl/cmd/analyze.go
  istioctl/pkg/util/formatting/formatter.go
  istioctl/pkg/util/formatting/formatter_test.go
  istioctl/pkg/util/formatting/msg_threshold.go
Labels: area/user experience, cla: yes, release-notes-none, size/XL

#26167 [release-1.7] Rename manifest apply to install
  operator/ARCHITECTURE.md
  operator/cmd/mesh/install.go
Labels: cla: yes, release-notes-none, size/XS

#26180 Fix release notes to match schema
  releasenotes/notes/24471.yaml
  releasenotes/notes/24554.yaml
  releasenotes/notes/25280.yaml
  releasenotes/notes/25669.yaml
  releasenotes/notes/25818.yaml
  releasenotes/notes/26001.yaml
  releasenotes/notes/crd-webhook-v1.yaml
  releasenotes/notes/dr-analyzer.yaml
  releasenotes/notes/envoy-filter.yaml
Labels: area/test and release, cherrypick/release-1.7, cla: yes, release-notes-none

#26151 remove istio-validation container when running istioctl rm
  istioctl/cmd/kubeuninject.go
Labels: area/environments, area/user experience, cherrypick/release-1.6, cherrypick/release-1.7, cherrypick/release-1.8, cla: yes, release-notes-none, size/XS

#26187 add mwc v1beta1 api to runtime scheme
  pkg/kube/inject/webhook.go
Labels: area/environments, cherrypick/release-1.7, cla: yes, release-notes-none, size/XS

#26153 add max program size back
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#26193 [release-1.7] add mwc v1beta1 api to runtime scheme
  pkg/kube/inject/webhook.go
Labels: cla: yes, release-notes-none, size/XS

#26179 Automator: update proxy@release-1.7 in istio/istio@release-1.7
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26196 [release-1.7] add max program size back
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: cla: yes, release-notes-none, size/S

#26201 cleanup kube Controller.Run
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#26192 add namespace flag to istioctl dashboard
  istioctl/cmd/dashboard.go
Labels: cla: yes, size/S

#26194 Remove SDS Timeout for default and root case
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/convert_test.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  releasenotes/notes/26001.yaml
Labels: area/networking, cla: yes, size/M

#26197 [release-1.7] Extra Envoy Access Log Attribute and Bag Preprocess Fix
  mixer/pkg/attribute/envoyProtoBag.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-policy/templates/config.yaml
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#26217 Move common HelpStr into root for istioctl commands
  operator/cmd/mesh/install.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/operator-dump.go
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/operator-remove.go
  operator/cmd/mesh/root.go
  operator/cmd/mesh/uninstall.go
  operator/cmd/mesh/upgrade.go
Labels: cla: yes, release-notes-none, size/M

#26202 fix feature labels in pilot and allowlist
  pkg/test/framework/features/allowlist.txt
  pkg/test/framework/features/features.go
  pkg/test/framework/features/features.yaml
  pkg/test/framework/test.go
  tests/integration/pilot/locality_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/routing_test.go
  tests/integration/tests.mk
Labels: area/test and release, cla: yes, release-notes-none, size/L

#25646 Enable TCP Telemetry v2 export via Stackdriver filter
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.8.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.8.yaml
  pkg/test/framework/components/stackdriver/kube.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/client_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
Labels: cherrypick/release-1.7, cla: yes, size/XL

#26190 [release-1.7] remove istio-validation container when running istioctl rm
  istioctl/cmd/kubeuninject.go
Labels: cla: yes, release-notes-none, size/XS

#26221 Fix pointer in for loop leading to incorrect tests
  tests/integration/pilot/routing_test.go
Labels: cla: yes, size/XS

#26226 label stackdriver tcp filter test
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#26207 Automator: update proxy@release-1.7 in istio/istio@release-1.7
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26173 Add Java related annotations in meshca.proto for using in generated Java code
  security/proto/providers/google/meshca.proto
Labels: area/security, cla: yes, ok-to-test, release-notes-none, size/XS

#26146 Deprecate meshExpansion and add ingress Service port 15012 by default
  manifests/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  pkg/test/framework/components/istio/operator.go
  releasenotes/notes/mesh-expansion.yaml
  tests/integration/multicluster/centralistio/main_test.go
Labels: area/environments, cla: yes, size/L

#26236 reload services and endpoints when networks change
  pilot/pkg/serviceregistry/kube/controller/network.go
Labels: area/networking, cla: yes, size/XS

#26227 Fix duplicate SDS resource
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tests/integration/pilot/istioctl_test.go
  tools/packaging/common/envoy_bootstrap.json
Labels: cherrypick/release-1.7, cla: yes, release-notes-none, size/L

#26238 Add sample for cross-network-gateway
  samples/cross-network-gateway/cross-network-gateway.yaml
Labels: cla: yes, release-notes-none, size/S

#26195 Remove DNS capture from install, tests
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/values.yaml
  pkg/test/framework/components/echo/kube/deployment.go
  releasenotes/notes/dns-capture.yaml
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/routing_test.go
  tests/istio.mk
Labels: cla: yes, release-notes-none, size/M

#26031 benchmark: keep benchmark specific logs
  pilot/pkg/xds/bench_test.go
Labels: cla: yes, release-notes-none, size/XS

#26228 update version of prune list
  operator/pkg/helmreconciler/prune.go
Labels: cherrypick/release-1.7, cla: yes, size/XS

#26241 [release-1.7] Fix duplicate SDS resource
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tests/integration/pilot/istioctl_test.go
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/L

#26244 Refresh token periodically through credential fetcher
  security/pkg/nodeagent/cache/secretcache.go
Labels: area/security, cherrypick/release-1.7, cla: yes, release-notes-none, size/M

#26245 [release-1.7] update version of prune list
  operator/pkg/helmreconciler/prune.go
Labels: cla: yes, release-notes-none, size/XS

#26251 [release-1.7] Refresh token periodically through credential fetcher
  security/pkg/nodeagent/cache/secretcache.go
Labels: cla: yes, release-notes-none, size/M

#26112 Fix cluster's lb endpoints not updated when workloadentry changes
  pilot/pkg/model/push_context.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/mcp/controller_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/eds.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#26250 Use common namespace value
  operator/cmd/mesh/operator-dump.go
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/operator-remove.go
  operator/cmd/mesh/root.go
  operator/cmd/mesh/shared.go
Labels: area/environments, cla: yes, release-notes-none, size/S

#26257 TestSendPushes go routine leak
  pilot/pkg/xds/discovery_test.go
Labels: cla: yes, size/M

#26247 Automator: update istio/api@release-1.7 dependency in istio/istio@release-1.7
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26260 Fix connection lock
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/debug.go
Labels: cla: yes, release-notes-none, size/S

#26254 Fix pushqueue test goroutine leak
  pilot/pkg/xds/pushqueue_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#26268 [Release-1.7] Enable TCP Telemetry v2 export via Stackdriver filter (#25646)
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
  pkg/test/framework/components/stackdriver/kube.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/client_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
Labels: cla: yes, release-notes-none, size/L

#26252 Clean up 1.4 telemetry v2 file
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.4.yaml
Labels: cla: yes, release-notes-none, size/XS

#26249 cleanup networks resync and add tests
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/xds_test.go
  pkg/config/mesh/networks_watcher.go
Labels: area/networking, cla: yes, size/L

#26270 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26081 Do not automatically add UID 0 to proxy
  tools/istio-iptables/pkg/cmd/root.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#26272 Automator: update common-files@release-1.7 in istio/istio@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26278 Automator: update common-files@release-1.7 in istio/istio@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26274 [release-1.7] added grpc keepalive params to envoy bootstrap template for gcp
  install/gcp/bootstrap/gcp_envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/S

#26279 Automator: update istio/api@release-1.7 dependency in istio/istio@release-1.7
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26284 [release-1.5] Update base image
  Makefile.core.mk
Labels: cla: yes, size/XS

#26269 [Release-1.7] Update Proxy SHA (#26030)
  istio.deps
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/vm/testdata/server_access_log.json.tmpl
Labels: cla: yes, release-notes-none, size/S

#26291 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#26253 change the PARSE_TOKEN to skipParseTokenEnv and fix the isTokenExpired logic issue
  pilot/cmd/pilot-agent/main.go
  pkg/security/security.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: area/security, cla: yes, release-notes-none, size/M

#26285 Revert "update MutatingWebhook apiVersion to v1 and other minor fixes"
  istioctl/cmd/testdata/webhook/example-mutating-webhook-config.yaml
  istioctl/cmd/testdata/webhook/example-validating-webhook-config.yaml
  istioctl/cmd/webhook.go
  istioctl/cmd/webhook_test.go
  istioctl/pkg/install/pre-check.go
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/validatingwebhookconfiguration.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.6.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.6.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/files/gen-istio-cluster.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/validatingwebhookconfiguration.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/telemetryv2_1.4.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/telemetryv2_1.6.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/mutatingwebhook.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/telemetryv2_1.6.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/prune.go
  pilot/pkg/bootstrap/certcontroller.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
  pkg/webhooks/validation/server/monitoring.go
  pkg/webhooks/validation/server/server.go
  pkg/webhooks/validation/server/server_test.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/k8s/chiron/controller_test.go
  security/pkg/k8s/chiron/utils_test.go
  tests/integration/operator/switch_cr_test.go
  tests/integration/pilot/webhook_test.go
  tests/integration/security/webhook/config/galley-webhook.yaml
  tests/integration/security/webhook/config/sidecar-injector-webhook.yaml
Labels: area/environments, area/networking, area/security, area/user experience, cherrypick/release-1.7, cla: yes, release-notes-none, size/XL

#26295 [release-1.7] change the PARSE_TOKEN to skipParseTokenEnv and fix the isTokenExpired logic issue
  pilot/cmd/pilot-agent/main.go
  pkg/security/security.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: cla: yes, release-notes-none, size/M

#26258 add jaeger collector service.
  samples/addons/jaeger.yaml
Labels: cla: yes, size/S

#26290 fix race when reloading kube controller networks
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/fake.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#26301 remove unnecessary logs in tests
  pilot/pkg/serviceregistry/kube/deregister_test.go
Labels: cla: yes, release-notes-none, size/XS

#26283 Don't specify remote profile in test framework deploy
  pkg/test/framework/components/istio/operator.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#26209 Operator/tpath refactor & Unit test additions
  operator/pkg/tpath/struct_test.go
  operator/pkg/tpath/tree_test.go
  operator/pkg/tpath/util_test.go
Labels: cla: yes, release-notes-none, size/L

#26304 Don't parse null IstioOperator overlays
  operator/pkg/util/yaml.go
  operator/pkg/validate/common.go
Labels: cherrypick/release-1.7, cla: yes, release-notes-none, size/S

#26288 Automator: update proxy@release-1.7 in istio/istio@release-1.7
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#26310 Revert "update MutatingWebhook apiVersion to v1 and other minor fixes…
  istioctl/cmd/testdata/webhook/example-mutating-webhook-config.yaml
  istioctl/cmd/testdata/webhook/example-validating-webhook-config.yaml
  istioctl/cmd/webhook.go
  istioctl/cmd/webhook_test.go
  istioctl/pkg/install/pre-check.go
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/validatingwebhookconfiguration.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/files/gen-istio-cluster.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/validatingwebhookconfiguration.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/telemetryv2_1.4.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/telemetryv2_1.6.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/mutatingwebhook.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/prune.go
  pilot/pkg/bootstrap/certcontroller.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
  pkg/webhooks/validation/server/monitoring.go
  pkg/webhooks/validation/server/server.go
  pkg/webhooks/validation/server/server_test.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/k8s/chiron/controller_test.go
  security/pkg/k8s/chiron/utils_test.go
  tests/integration/galley/webhook_test.go
  tests/integration/operator/switch_cr_test.go
  tests/integration/security/webhook/config/galley-webhook.yaml
  tests/integration/security/webhook/config/sidecar-injector-webhook.yaml
Labels: area/environments, cla: yes, release-notes-none, size/XL

#26305 [release-1.7] Don't parse null IstioOperator overlays
  operator/pkg/util/yaml.go
  operator/pkg/validate/common.go
Labels: cla: yes, release-notes-none, size/S

#26315 ads: move mutex to proxy
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/cds.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/discovery_test.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/ep_filters_test.go
  pilot/pkg/xds/gen2.go
  pilot/pkg/xds/internalgen.go
  pilot/pkg/xds/lds.go
  pilot/pkg/xds/rds.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#26319 [release-1.7] add namespace flag to istioctl dashboard
  istioctl/cmd/dashboard.go
Labels: cla: yes, release-notes-none, size/S

#26322 [release-1.7] Update dependencies
  go.mod
  go.sum
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/S

#26326 [release-1.7] Update kiali in profiles
  manifests/charts/istio-telemetry/kiali/values.yaml
  manifests/profiles/default.yaml
  operator/cmd/mesh/manifest-generate_test.go
Labels: cla: yes, release-notes-none, size/XS

#25302 Add feature to show exact error line number when using `istioctl analyze`
  galley/pkg/config/analysis/README.md
  galley/pkg/config/analysis/analyzers/analyzers_bench_test.go
  galley/pkg/config/analysis/analyzers/annotations/annotations.go
  galley/pkg/config/analysis/analyzers/authz/authorizationpolicies.go
  galley/pkg/config/analysis/analyzers/deployment/services.go
  galley/pkg/config/analysis/analyzers/gateway/gateway.go
  galley/pkg/config/analysis/analyzers/gateway/secret.go
  galley/pkg/config/analysis/analyzers/injection/injection-image.go
  galley/pkg/config/analysis/analyzers/injection/injection.go
  galley/pkg/config/analysis/analyzers/multicluster/meshnetworks.go
  galley/pkg/config/analysis/analyzers/schema/validation_test.go
  galley/pkg/config/analysis/analyzers/service/portname.go
  galley/pkg/config/analysis/analyzers/sidecar/selector.go
  galley/pkg/config/analysis/analyzers/util/find_errorline_utils.go
  galley/pkg/config/analysis/analyzers/util/find_errorline_utils_test.go
  galley/pkg/config/analysis/analyzers/virtualservice/conflictingmeshgatewayhosts.go
  galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
  galley/pkg/config/analysis/analyzers/virtualservice/destinationrules.go
  galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
  galley/pkg/config/analysis/analyzers/virtualservice/regexes.go
  galley/pkg/config/analysis/analyzers/virtualservice/util.go
  galley/pkg/config/analysis/diag/helper.go
  galley/pkg/config/analysis/diag/message.go
  galley/pkg/config/analysis/diag/message_test.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  galley/pkg/config/source/kube/apiserver/watcher.go
  galley/pkg/config/source/kube/inmemory/kubesource.go
  galley/pkg/config/source/kube/inmemory/kubesource_test.go
  galley/pkg/config/source/kube/rt/adapter.go
  galley/pkg/config/source/kube/rt/extract.go
  galley/pkg/config/source/kube/rt/origin.go
  galley/pkg/config/source/mcp/origin.go
  go.mod
  go.sum
  pkg/config/resource/origin.go
  pkg/test/framework/features/features.yaml
  releasenotes/notes/25302.yaml
  tests/integration/pilot/analyze_test.go
Labels: cla: yes, size/XL

#26296 Update Proxy SHA
  istio.deps
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
Labels: cla: yes, release-notes-none, size/XS

#26286 Add filter configuration override to telemetry v2
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.6.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.8.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.6.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.8.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: cla: yes, size/L

#26331 dont test reloading meshNetworks in xds_test
  pilot/pkg/xds/xds_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#25960 Update dependency istio/{client-go,api} and remove mixer reference.
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/misannotated.yaml
  galley/pkg/config/analysis/diag/level.go
  galley/pkg/config/analysis/diag/message.go
  galley/pkg/config/source/kube/apiserver/status/controller_test.go
  galley/pkg/config/source/kube/apiserver/status/util.go
  go.mod
  go.sum
  istioctl/cmd/testdata/mesh-config.yaml
  istioctl/pkg/util/formatting/formatter_test.go
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/profiles/demo.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/demo.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_merge_meshconfig.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  pilot/pkg/status/state.go
  pilot/pkg/status/state_test.go
  pilot/pkg/status/status.go
  pkg/config/mesh/mesh.go
  pkg/config/schema/fuzz_test.go
  tests/integration/pilot/analysis/analysis_test.go
Labels: cla: yes, release-notes-none, size/XXL

#26327 Test XDS invariants in pilot unit tests
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/filters/filters.go
  pilot/pkg/xds/xds_test.go
  pilot/test/xdstest/extract.go
  pilot/test/xdstest/validate.go
Labels: cla: yes, release-notes-none, size/XXL

#26084 Remove unneeded constructCSRHostName
  security/pkg/nodeagent/cache/helper.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: cla: yes, release-notes-none, size/L

#26339 Remove duplicate CNI test
  cni/deployments/kubernetes/install/test/install_cni_test.go
Labels: cla: yes, release-notes-none, size/M

#26342 [release-1.7] Fix release notes to match schema. Cherrypick failed.
  releasenotes/README.md
  releasenotes/notes/24471.yaml
  releasenotes/notes/24554.yaml
  releasenotes/notes/24737.yaml
  releasenotes/notes/25280.yaml
  releasenotes/notes/25519.yaml
  releasenotes/notes/25737.yaml
  releasenotes/notes/25818.yaml
  releasenotes/notes/26001.yaml
  releasenotes/notes/add-release-notes-generation.yaml
  releasenotes/notes/add-sni-host.yaml
  releasenotes/notes/addon-remove.yaml
  releasenotes/notes/agent-metrics.yaml
  releasenotes/notes/auto-mtls-headless.yaml
  releasenotes/notes/crd-webhook-v1.yaml
  releasenotes/notes/delay-app-start.yaml
  releasenotes/notes/dns-capture.yaml
  releasenotes/notes/dr-analyzer.yaml
  releasenotes/notes/dr-sds.yaml
  releasenotes/notes/ecc-csr.yaml
  releasenotes/notes/endpoint-before-pod.yaml
  releasenotes/notes/ingress-named-port.yaml
  releasenotes/notes/istioctl-uninstall.yaml
  releasenotes/notes/nonroot-gateway.yaml
  releasenotes/notes/operator_revision.yaml
  releasenotes/notes/prom-rewrite.yaml
  releasenotes/notes/psfile.yaml
  releasenotes/notes/rpm-builds.yaml
  releasenotes/notes/service-select-workload-entry.yaml
  releasenotes/notes/validate-unknown.yaml
  releasenotes/notes/xds-v3.yaml
Labels: cla: yes, size/L

#26320 Move EndpointBuilder out and do some other cleanups
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/util.go
Labels: cla: yes, release-notes-none, size/XL
