Repository istio/istio, pull requests merged in 2020-07, with the labels that each got.

#25134 fix: get resource from scope traverses parents
  pkg/test/framework/resource/context.go
  pkg/test/framework/scope.go
  pkg/test/framework/scope_test.go
  pkg/test/framework/testcontext.go
Labels: area/test and release, cla: yes, size/L

#25140 Automator: update istio/api@release-1.6 dependency in istio/istio@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#25118 Don't initialize multiple default sidecars for ns
  pilot/pkg/model/push_context.go
Labels: cla: yes, size/S

#25124 Move init connection to receive thread
  mixer/adapter/stackdriver/internal/cloud.google.com/go/contextgraph/apiv1alpha1/mock_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
Labels: cla: yes, size/L

#25042 Send envoy.config.core.v3.ControlPlane proto with experimental XDS
  pilot/pkg/xds/adapter.go
  pilot/pkg/xds/gen2.go
Labels: cla: yes, size/M

#24780 Fix Ingress that is missing secretName
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  pilot/pkg/config/kube/ingress/testdata/tls-no-secret.yaml
  pilot/pkg/config/kube/ingress/testdata/tls-no-secret.yaml.golden
Labels: cla: yes, size/M

#25150 fix incorrect comment
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, size/XS

#25152 fix xds updater interface docs
  pilot/pkg/model/push_context.go
Labels: area/networking, cla: yes, size/S

#25117 Improvements to XDS benchmarks
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/testdata/benchmarks/empty.yaml
  pilot/pkg/xds/testdata/benchmarks/gateways-shared.yaml
  pilot/pkg/xds/testdata/benchmarks/gateways.yaml
  pilot/pkg/xds/testdata/benchmarks/telemetry.yaml
  pilot/pkg/xds/testdata/benchmarks/virtualservice.yaml
Labels: cla: yes, size/XL

#25151 xds: move pilot cli to v3
  pilot/tools/debug/pilot_cli.go
Labels: area/networking, cla: yes

#25087 Initial XDS-based (experimental) version subcommand
  istioctl/cmd/root.go
  istioctl/cmd/version.go
  istioctl/pkg/clioptions/central.go
  istioctl/pkg/multixds/gather.go
  istioctl/pkg/xds/client.go
Labels: cla: yes, size/L

#25127 Move istio CRD reader to shared informers
  istioctl/cmd/deprecated_cmd.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
  pkg/kube/client.go
  pkg/test/kube/mock_client.go
Labels: cla: yes, size/L

#25142 fix test issues that cause analyze to fail
  pkg/test/framework/analyzer.go
  pkg/test/framework/features/features.yaml
  tests/integration/qualification/loadbalancing_test.go
  tests/integration/qualification/main_test.go
Labels: cla: yes, size/L

#24859 Add prometheus parsing to metric merge test
  pilot/cmd/pilot-agent/status/server_test.go
Labels: cla: yes, size/M

#25162 Fix ingress crash on shutdown
  pilot/pkg/config/kube/ingress/controller.go
Labels: cla: yes, size/XS

#25167 kube controller: remove metadata informer
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
Labels: cla: yes, size/M

#25168 [release-1.6] Update proxyv2 sha
  istio.deps
Labels: cla: yes, size/XS

#25187 istio-cni chart should not depend on manifests/charts/global.yaml
  manifests/charts/istio-cni/values.yaml
Labels: area/environments, cla: yes, size/S

#25159 Update proxy sha
  istio.deps
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/envoy/instance_test.go
  pkg/envoy/options.go
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tools/packaging/common/envoy_bootstrap.json
  tools/packaging/common/istio-start.sh
Labels: cla: yes, size/XL

#24958 gateway: ignore virtual services when https redirect is set
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: cla: yes, size/M

#25197 Log XDS client rejections due to SPIFFE
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, size/S

#25207 Fix Istioctl upgrade with dry-run options
  operator/cmd/mesh/upgrade.go
Labels: area/environments, area/user experience, cla: yes, ok-to-test, size/S

#25136 pilot: fix n^2 scaling behavior with gateways
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/model/virtualservice.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: cla: yes, size/L

#25164 kube: remove legacy client in Istiod
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/bootstrap/validation.go
Labels: cla: yes, size/M

#24919 Resolve DNS in sidecar envoy
  pilot/pkg/model/config.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/dns_listener.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  pilot/pkg/xds/filters/filters.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/traffic_shifting_test.go
  tests/integration/pilot/vm/testdata/traffic-shifting.yaml
  tests/integration/pilot/vm/vm_test.go
  tests/istio.mk
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: cla: yes, size/XL

#25228 Fix typo in EDS log
  pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
Labels: cla: yes, size/XS

#25224 Do not trigger push to Gateways when Sidecar object changes
  pilot/pkg/xds/ads_common.go
Labels: cla: yes, size/XS

#25203 Fix agent starting when using ECC_SIGNATURE_ALGORITHM
  pkg/istio-agent/sds-agent.go
Labels: area/security, cla: yes, size/XS

#25238 Split xds authentication
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/authentication.go
Labels: cla: yes, size/L

#25201 Add HPA and PDB for Istiocoredns manifests
  manifests/charts/istiocoredns/templates/autoscale.yaml
  manifests/charts/istiocoredns/templates/deployment.yaml
  manifests/charts/istiocoredns/templates/poddisruptionbudget.yaml
  manifests/charts/istiocoredns/values.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: area/config, area/environments, cla: yes, ok-to-test, size/M

#25234 cluster: move more functions to cluster builder
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, size/XL

#25210 update fortio to 1.4.1
  go.mod
  go.sum
Labels: area/perf and scalability, area/test and release, cla: yes, size/S

#25227 Fix non k8s registry check
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/eds.go
Labels: cla: yes, size/XS

#25200 ADSC: improve test coverage
  pkg/adsc/adsc_test.go
Labels: area/networking, cla: yes, size/L

#25243 Sort manifests during generate, similar to apply
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/testdata/manifest-generate/output/all_off.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways_override_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/telemetry_default.golden.yaml
Labels: cla: yes, size/XXL

#25248 Move istioctl to using client-go
  istioctl/cmd/deprecated_cmd.go
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/istioctl_test.go
  istioctl/cmd/kubeinject_test.go
  istioctl/cmd/kubeuninject_test.go
  istioctl/cmd/root.go
  istioctl/cmd/sidecar-bootstrap.go
  istioctl/cmd/sidecar-bootstrap_test.go
  istioctl/cmd/version_test.go
Labels: cla: yes, size/L

#25256 Cleanup test targets on makefile
  Makefile.core.mk
Labels: cla: yes, size/L

#25034 Add unit test of CSR request to server unit test to test cliencertauthenticator works correctly
  security/pkg/server/ca/server_test.go
Labels: area/security, cla: yes, ok-to-test, size/L

#25258 Move UpstreamTLSContext Generation to separate function and extend test coverage
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, size/XL

#25249 dns: Deadlock fix and performance improvements.
  pkg/dns/dns.go
Labels: area/networking, area/perf and scalability, cla: yes, ok-to-test, size/XS

#25137 add unit test to authz
  pilot/pkg/security/authz/matcher/string_test.go
Labels: area/security, cla: yes, ok-to-test, size/M

#24398 Add an XDS proxy in agent, tests for TLS communication.
  pilot/pkg/model/context.go
  pilot/pkg/networking/apigen/apigen.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/gen2.go
  pilot/pkg/xds/internalgen.go
  pilot/pkg/xds/simple.go
  pkg/adsc/adsc.go
  pkg/istio-agent/sds-agent.go
  pkg/istio-agent/xds-agent.go
  tests/util/pilot_server.go
Labels: cla: yes, size/XL

#25195 istioctl --xds-san and --insecure options for testing XDS
  istioctl/pkg/clioptions/central.go
  istioctl/pkg/multixds/gather.go
  istioctl/pkg/xds/client.go
  pkg/adsc/adsc.go
Labels: cla: yes, size/S

#25225 Handle namespace deletion race condition in cm controller
  security/pkg/util/configutil.go
Labels: cla: yes, size/XS

#25259 security tests: remove super slow waits in test
  security/pkg/cmd/constants.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/k8s/chiron/controller_test.go
  security/pkg/k8s/chiron/utils.go
  security/pkg/k8s/chiron/utils_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
Labels: cla: yes, size/M

#25265 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#25255 Cache configs in benchmark tests
  pilot/pkg/xds/bench_test.go
Labels: cla: yes, size/S

#25266 eds: compare service accounts for existing endpoint shards only
  pilot/pkg/xds/eds.go
Labels: area/networking, cla: yes, size/S

#25186 istio-discovery chart should not depend on manifests/charts/global.yaml
  manifests/charts/README-helm3.md
  manifests/charts/istio-control/istio-discovery/Chart.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
Labels: area/environments, cla: yes, size/L

#25192 ads: unify ads protocol handling across type urls
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/debug_test.go
  pilot/pkg/xds/gen2.go
  pilot/pkg/xds/init_test.go
  pilot/pkg/xds/internalgen.go
  pilot/pkg/xds/monitoring.go
  pilot/pkg/xds/rds_test.go
  pilot/pkg/xds/v3/model.go
Labels: area/networking, cla: yes, size/L

#25260 gateway charts should not depend on manifests/charts/global.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
Labels: area/environments, cla: yes, size/L

#25273 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#25278 Add version label to `pilot_xds` metric
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/monitoring.go
Labels: area/networking, area/policies and telemetry, cla: yes, size/S

#25236 [release-1.6] Fix agent starting when using ECC_SIGNATURE_ALGORITHM
  pkg/istio-agent/sds-agent.go
Labels: cla: yes, size/XS

#25211 Add Unit test TestRenderTemplate to test operator/pkg/util/util.go RenderTempla…
  operator/pkg/util/util_test.go
Labels: cla: yes, ok-to-test, size/M

#25281 [Istioctl] Removing use of kube context in remote secret creation
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/apply_test.go
  istioctl/pkg/multicluster/options.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
Labels: cla: yes, size/L

#25283 [release-1.6] Update base image
  Makefile.core.mk
Labels: area/test and release, cla: yes, size/XS

#25221 [release-1.5] Update istio/proxy sha for release-1.5 branch
  Makefile.core.mk
  istio.deps
Labels: cla: yes, size/XS

#24912 [release-1.6] fix hpa scaleTargetRef
  operator/cmd/mesh/testdata/manifest-migrate/output/default_values.golden.yaml
  operator/pkg/translate/translate_value.go
  operator/pkg/translate/translate_value_test.go
Labels: cla: yes, size/S

#25282 Update base image
  Makefile.core.mk
Labels: area/test and release, cla: yes, size/XS

#25292 [release-1.5] Update base image for release-1.5
  Makefile.core.mk
Labels: cla: yes, size/XS

#25262 Update stackdriver bootstrap test
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: area/policies and telemetry, cla: yes, size/L

#25277 Log CRD client messages under a scope
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/metrics.go
Labels: cla: yes, size/S

#25270 use common util for json marshal
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/verify.go
  istioctl/pkg/validate/validate.go
  operator/pkg/validate/common.go
Labels: cla: yes, size/M

#25096 Extend security test for VMs
  tests/integration/pilot/cni/cni_test.go
  tests/integration/security/main_test.go
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, size/M

#25294 Optimize performance for large numbers of services
  pilot/pkg/model/push_context.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/util/util.go
Labels: cla: yes, size/S

#25318 Automator: update istio/api@release-1.6 dependency in istio/istio@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#25304 ads: use watched resourcenames instead of clusters and routes
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/eds_sh_test.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/rds.go
Labels: area/networking, cla: yes, size/L

#25305 update deployment requirements url for istioctl validate
  istioctl/pkg/validate/validate.go
Labels: cla: yes, size/S

#25321 Update proxy to pull in https://github.com/envoyproxy/envoy/pull/11921
  istio.deps
Labels: cla: yes, size/XS

#25121 Drop excessive RBAC permissions
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/clusterrole.yaml
  manifests/charts/base/templates/clusterrolebinding.yaml
Labels: cla: yes, size/L

#25230 Add MCP-over-XDS to bootstrap
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pkg/istio-agent/sds-agent.go
Labels: cla: yes, size/L

#25295 Remove duplicate BuildConfigInfoMetadata function
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/util/util.go
Labels: cla: yes, size/S

#25300 Fix missing CRDs in client
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: cla: yes, size/S

#25313 update pilot to istiod for istioctl proxy-status
  istioctl/cmd/proxystatus.go
  istioctl/cmd/proxystatus_test.go
  istioctl/pkg/writer/compare/cluster.go
  istioctl/pkg/writer/compare/comparator.go
  istioctl/pkg/writer/compare/listener.go
  istioctl/pkg/writer/compare/route.go
  istioctl/pkg/writer/pilot/status.go
  istioctl/pkg/writer/pilot/status_test.go
  istioctl/pkg/writer/pilot/testdata/multiStatusMultiPilot.txt
  istioctl/pkg/writer/pilot/testdata/multiStatusSinglePilot.txt
  istioctl/pkg/writer/pilot/testdata/singleStatus.txt
  istioctl/pkg/writer/pilot/testdata/singleStatusFallback.txt
Labels: cla: yes, size/L

#25322 Update proxy to pull in https://github.com/envoyproxy/envoy/pull/11921
  istio.deps
Labels: cla: yes, size/XS

#25049 cherry-pick: istio iptables filters empty values
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: area/networking, cla: yes, size/S

#25323 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#25334 tests: centralistiod patch happens in errgroup
  pkg/test/framework/components/istio/operator.go
Labels: area/test and release, cla: yes, size/S

#25131 Stop writing root to istio-security configmap
  pilot/pkg/bootstrap/istio_ca.go
  security/pkg/k8s/configmap/configmap.go
  security/pkg/k8s/configmap/configmap_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
  security/pkg/server/ca/server_test.go
Labels: cla: yes, size/XL

#25326 Reduce length of envoy logs
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: cla: yes, size/XS

#25107 set istiod secure grpc port
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
Labels: cla: yes, size/S

#25287 feat(testing): Add GCE Metadata Server component
  pkg/test/env/istio.go
  pkg/test/framework/components/gcemetadata/gce_metadata_server.yaml
  pkg/test/framework/components/gcemetadata/gcemetadata.go
  pkg/test/framework/components/gcemetadata/kube.go
Labels: area/test and release, cla: yes, size/L

#25336 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#25317 Fix VM test flakes
  pkg/test/framework/components/echo/kube/instance.go
Labels: cla: yes, size/XS

#25342 Add method to enable subject token refresh in sts token source
  security/pkg/stsservice/tokenmanager/sts_test.go
  security/pkg/stsservice/tokenmanager/tokensource.go
Labels: cla: yes, size/M

#25158 Fix: workload TTL is changed based on the intermediate cert TTL
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
Labels: area/security, cla: yes, ok-to-test, size/L

#25346 Fix deprecation enable ALS message
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
Labels: cla: yes, ok-to-test, size/XS

#25360 Better handle vendored trees
  Makefile.core.mk
  bin/protoc.sh
  mixer/pkg/attribute/generate_word_list.sh
Labels: cherrypick/release-1.6, cla: yes, size/XS

#25264 (test): add fake for GCE Metadata Server
  pkg/test/fakes/gce_metadata_server/Dockerfile
  pkg/test/fakes/gce_metadata_server/Makefile
  pkg/test/fakes/gce_metadata_server/main.go
Labels: area/policies and telemetry, area/test and release, cla: yes, size/L

#25356 eds: fix endpoint port in service entry eds update
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Labels: area/networking, cla: yes, size/XS

#25337 De-dup send traffic and decouple traffic shifting
  pkg/test/framework/features/features.yaml
  tests/integration/pilot/traffic_shifting_test.go
  tests/integration/pilot/vm/util.go
  tests/integration/pilot/vm/vm_test.go
  tests/integration/pilot/vm/vm_traffic_shifting_test.go
Labels: area/test and release, cla: yes, size/L

#25355 ads: derive watch status from active watches
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
  pkg/adsc/adsc.go
Labels: area/networking, cla: yes, size/S

#25361 removed secret dumps and deprecated --export from dump_kubernetes.sh
  tools/dump_kubernetes.sh
Labels: area/user experience, cla: yes, ok-to-test, size/S

#25341 Add MultiVM to VM tests
  tests/integration/pilot/vm/vm_test.go
Labels: area/test and release, cla: yes, size/M

#25343 Expose istioctl multicluster as a library
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/apply_test.go
  istioctl/pkg/multicluster/clientfactory.go
  istioctl/pkg/multicluster/clientfactory_test.go
  istioctl/pkg/multicluster/cluster.go
  istioctl/pkg/multicluster/cluster_test.go
  istioctl/pkg/multicluster/desc.go
  istioctl/pkg/multicluster/describe.go
  istioctl/pkg/multicluster/env.go
  istioctl/pkg/multicluster/env_test.go
  istioctl/pkg/multicluster/generate.go
  istioctl/pkg/multicluster/mesh.go
  istioctl/pkg/multicluster/poller.go
  istioctl/pkg/multicluster/poller_test.go
  istioctl/pkg/multicluster/printer.go
  istioctl/pkg/multicluster/printer_test.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  istioctl/pkg/multicluster/util.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/kube/mock_client.go
Labels: cla: yes, size/XXL

#25345 Fix default builtin profile path when chartsDir is empty
  operator/pkg/helm/helm.go
  operator/pkg/helm/vfs_renderer.go
Labels: cla: yes, size/XS

#25202 SDS Secret Provisioning for Egress Gateway using Destination Rule API
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/templates/role.yaml
  manifests/charts/gateways/istio-egress/templates/rolebindings.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/gateways/istio-ingress/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways_override_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ingressgateway_k8s_settings.golden.yaml
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/xds/ads_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sds_stream_test.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/sds/server_test.go
  security/pkg/nodeagent/secretfetcher/secretfetcher.go
  security/pkg/nodeagent/secretfetcher/secretfetcher_test.go
Labels: cla: yes, ok-to-test, size/XL

#25380 Partial revert of Drop excessive RBAC permissions (#25121)
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/clusterrole.yaml
Labels: cla: yes, size/S

#25385 Automator: update common-files@release-1.6 in istio/istio@release-1.6
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#25386 istiocoredns chart should not depend on global.yaml
  manifests/charts/istiocoredns/values.yaml
Labels: area/environments, cla: yes, size/M

#25388 [release-1.6] Better handle vendored trees
  Makefile.core.mk
  bin/protoc.sh
  mixer/pkg/attribute/generate_word_list.sh
Labels: cla: yes, size/XS

#25370 Remove prometheus chart dependency on global.yaml
  manifests/charts/istio-telemetry/prometheus/values.yaml
Labels: area/environments, cla: yes, size/L

#25392 networking: add better transport security iptables rules
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: cla: yes, size/M

#25257 Add targets for running/reporting/comparing benchmarks as part of CI
  Makefile.core.mk
  prow/benchtest.sh
Labels: cla: yes, size/M

#25405 Refactor some more tests away from using goldens
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/test-util.go
  operator/cmd/mesh/testdata/manifest-generate/input/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/empty.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/gateways.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/gateways_override_default.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/minimal.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways_override_default.golden.yaml
Labels: cla: yes, size/XXL

#25372 Allow users to enable validation webhook or not
  manifests/charts/base/templates/validatingwebhookconfiguration.yaml
  manifests/charts/base/values.yaml
Labels: area/environments, cla: yes, size/XS

#25407 Update helm v3 dependency
  go.mod
  go.sum
Labels: cla: yes, size/XS

#25354 remove version check for tcp metadata filter
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/security/authn/utils/utils.go
Labels: area/networking, cla: yes, size/S

#25376 Fix crd client metrics
  pilot/pkg/config/kube/crdclient/metrics.go
Labels: cla: yes, size/XS

#25409 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#25377 Handle tombstone in ledger updates
  pilot/pkg/config/kube/crdclient/ledger.go
Labels: cla: yes, size/M

#25358 Fix tombstone recovery bug in Galley
  galley/pkg/config/source/kube/apiserver/watcher.go
Labels: area/user experience, cherrypick/release-1.6, cla: yes, ok-to-test, size/S

#25314 ADSC: Check for cert expiration locally before contacting XDS server
  pkg/adsc/adsc.go
Labels: cla: yes, size/S

#25146 Make proxyv2 image building operations universal
  Makefile.core.mk
  bin/init.sh
  pilot/docker/Dockerfile.proxyv2
  tools/istio-docker.mk
Labels: area/test and release, cla: yes, ok-to-test, size/M

#25275 Fix broken benchmark test
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
Labels: cla: yes, size/M

#25403 sidecar scopes pushes to namespace
  pilot/pkg/model/push_context.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/xds/ads_common.go
  pilot/pkg/xds/ads_common_test.go
Labels: area/networking, area/perf and scalability, cla: yes, size/M

#25284 [release-1.6] Add version label to `pilot_xds` metric
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/monitoring.go
Labels: cla: yes, size/S

#25378 optimize CombineVHostRoutes
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: area/perf and scalability, cla: yes, size/M

#25390 Bump service-apis dependency
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/conversion.go
  tests/integration/pilot/ingress/testdata/crd.yaml
Labels: cla: yes, size/XXL

#25421 Revert "Add MultiVM to VM tests "
  tests/integration/pilot/vm/vm_test.go
Labels: cla: yes, size/M

#25422 Fix SHA reference
  prow/benchtest.sh
Labels: cla: yes, size/XS

#25426 Automator: update istio/api@release-1.6 dependency in istio/istio@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#25290 Add roundtrip fuzzing tests for our CRDs
  pilot/pkg/config/kube/crd/config_test.go
  pilot/pkg/config/kube/crd/roundtrip/roundtrip.go
Labels: cla: yes, size/L

#25316 Add initial RPM build and test
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8
  pkg/test/framework/components/echo/kube/deployment.go
  prow/lib.sh
  tests/integration/pilot/vm/util.go
  tools/istio-docker.mk
  tools/packaging/deb/istio.mk
Labels: cla: yes, size/M

#25365 Update grafana and prometheus
  manifests/addons/gen.sh
  manifests/addons/values-grafana.yaml
  manifests/addons/values-prometheus.yaml
  manifests/charts/istio-telemetry/grafana/values.yaml
  manifests/charts/istio-telemetry/prometheus/values.yaml
  manifests/profiles/default.yaml
  samples/addons/grafana.yaml
  samples/addons/prometheus.yaml
Labels: cla: yes, size/M

#25306 Add unit test for mode/authentication to cover ConstructSdsSecretConfigWithCustomUds, ConstructValidationContext, ApplyCustomSDSToCommonTLSContext
  pilot/pkg/security/model/authentication_test.go
Labels: area/security, cla: yes, ok-to-test, size/L

#25431 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#25429 Moving security envoy filters to pkg/envoy
  istioctl/pkg/authz/listener.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/xds/filters/filters.go
  pkg/config/xds/filter_types.gen.go
  pkg/config/xds/filter_types.go
  pkg/envoy/config/authentication/v1alpha1/policy.pb.go
  pkg/envoy/config/authentication/v1alpha1/policy.proto
  pkg/envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  pkg/envoy/config/filter/http/alpn/v2alpha1/config.proto
  pkg/envoy/config/filter/http/authn/v2alpha1/config.pb.go
  pkg/envoy/config/filter/http/authn/v2alpha1/config.proto
  pkg/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  pkg/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.proto
  pkg/test/framework/components/echo/common/envoy.go
  pkg/test/framework/components/echo/kube/sidecar.go
Labels: cla: yes, size/M

#25368 Added template for release notes
  CODEOWNERS
  releasenotes/template.yaml
Labels: cla: yes, size/M

#25425 [release-1.6] Fix Istioctl upgrade with dry-run options
  operator/cmd/mesh/upgrade.go
Labels: area/environments, cla: yes, size/S

#25435 Add memory to benchmark test
  prow/benchtest.sh
Labels: cla: yes, size/XS

#25433 [Bug Fix] Empty ResouceName results in ill configured UpstreamTLSContext
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, ok-to-test, size/L

#25384 Expose more of istioctl as library
  operator/cmd/mesh/manifest-apply.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/operator-remove.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/upgrade.go
  pkg/kube/client.go
  pkg/test/framework/components/environment/kube/settings.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/kube/mock_client.go
Labels: cla: yes, size/L

#24923 record reverseStatus as hashset, due to high cpu utilization
  pilot/pkg/status/reporter.go
  pilot/pkg/status/reporter_test.go
Labels: area/user experience, cla: yes, size/M

#25444 fix(pilot): apply header manipulations in redirect action
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: cla: yes, size/M

#25451 Fix breakage in istioctl manifest apply
  operator/cmd/mesh/manifest-apply.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/upgrade.go
  pkg/test/framework/components/istio/operator.go
Labels: cla: yes, size/L

#25455 refactor(pilot): extract method to get header operations
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: cla: yes, size/L

#25452 Don't complain about unknown keys on in-cluster IOP
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/verify.go
  istioctl/pkg/validate/validate.go
  operator/pkg/apis/istio/common.go
  operator/pkg/helm/vfs_renderer.go
Labels: cla: yes, size/S

#25414 update endpoint shards when doing a full push for service entries
  pilot/pkg/config/memory/config.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  pilot/pkg/xds/discovery.go
Labels: area/networking, cla: yes, size/M

#25459 gateway: do not compute snihosts for service repeatedly
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: cla: yes, size/M

#25469 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#25473 Revert "gateway: do not compute snihosts for service repeatedly"
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: cla: yes, size/M

#25471 Revert "Expose more of istioctl as library (#25384)"
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/apply_test.go
  istioctl/pkg/multicluster/clientfactory.go
  istioctl/pkg/multicluster/clientfactory_test.go
  istioctl/pkg/multicluster/cluster.go
  istioctl/pkg/multicluster/cluster_test.go
  istioctl/pkg/multicluster/desc.go
  istioctl/pkg/multicluster/describe.go
  istioctl/pkg/multicluster/env.go
  istioctl/pkg/multicluster/env_test.go
  istioctl/pkg/multicluster/generate.go
  istioctl/pkg/multicluster/mesh.go
  istioctl/pkg/multicluster/poller.go
  istioctl/pkg/multicluster/poller_test.go
  istioctl/pkg/multicluster/printer.go
  istioctl/pkg/multicluster/printer_test.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  istioctl/pkg/multicluster/util.go
  operator/cmd/mesh/manifest-apply.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/operator-remove.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/upgrade.go
  pkg/kube/client.go
  pkg/test/framework/components/environment/kube/settings.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/kube/mock_client.go
Labels: cla: yes, size/XXL

#25475 cleanup ingress test component
  pkg/test/framework/components/ingress/kube.go
Labels: area/test and release, cla: yes, size/M

#25335 Use XDS v3 for SDS
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  pkg/bootstrap/option/convert.go
  pkg/bootstrap/option/convert_test.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, size/L

#25466 Add api version to release notes schema
  releasenotes/template.yaml
Labels: cla: yes, size/XS

#25404 add config map and envoy filter into istiod-remote
  Makefile.core.mk
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/configmap.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.6.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
  manifests/charts/istiod-remote/values.yaml
Labels: cla: yes, size/XXL

#25446 test(security): deflake TestCreatePluggedCertCA
  security/pkg/pki/ca/ca_test.go
Labels: area/test and release, cla: yes, size/XS

#25472 Tune benchmark test
  pilot/pkg/xds/bench_test.go
  prow/benchtest.sh
Labels: cla: yes, size/XS
