Repository istio/istio, pull requests merged in 2020-11, with the labels that each got.

#28232 set network label when istioctl creates namespace
  operator/cmd/mesh/install.go
  operator/cmd/mesh/manifest_shared_test.go
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/shared.go
Labels: cla: yes, release-notes-none, size/S

#28467 Update release builder
  prow/release-commit.sh
Labels: area/environments, cla: yes, release-notes-none, size/XS

#28468 add test for conversion.go
  pkg/util/gogo/conversion_test.go
Labels: area/test and release, cla: yes, ok-to-test, release-notes-none, size/M

#28438 Dynamically set trust domain on mesh config update
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
Labels: cherrypick/release-1.8, cla: yes, release-notes-none, size/S

#28461 samples/addons/README.md: add missing protocol
  samples/addons/README.md
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#28460 tests/integration: update README
  tests/integration/README.md
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#28464 operator: update ARCHITECTURE
  operator/ARCHITECTURE.md
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#28253 improve install req message.
  operator/cmd/mesh/install.go
Labels: cla: yes, release-notes-none, size/M

#28474 pilot, discovery: move grpc logging to PersistentPreRun
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
Labels: cla: yes, release-notes-none, size/XS

#28469 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28396 istio-discovery: validate keepaliveMaxServerConnectionAge duration
  pilot/cmd/pilot-discovery/main.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: cla: yes, release-notes-none, size/M

#28481 prow: overwrite existing node annotations
  prow/lib.sh
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#28471 [release-1.8] Dynamically set trust domain on mesh config update
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, release-notes-none, size/S

#28459 tests/integration/pilot: update README
  tests/integration/pilot/README.md
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#28443 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28487 Automator: update istio/api@release-1.8 dependency in istio/istio@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28444 Convert jwt test into multicluster supported
  pkg/test/framework/components/echo/instances.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/util/authn/authn_util.go
  tests/integration/security/util/framework.go
Labels: area/security, cla: yes, release-notes-none, size/XL

#28484 Automator: update common-files@release-1.8 in istio/istio@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28494 Add customization for helloworld sample
  samples/helloworld/README.md
  samples/helloworld/gen-helloworld.sh
Labels: cla: yes, release-notes-none, size/L

#28495 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28496 [release-1.8] update proxy sha
  istio.deps
  pkg/test/framework/components/stackdriver/kube.go
Labels: cla: yes, release-notes-none, size/XS

#28499 Use registry image from GCR
  prow/lib.sh
Labels: cla: yes, release-notes-none, size/XS

#27915 Convert Stackdriver and Stats telemetry tests to use Multicluster
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/components/prometheus/prometheus.go
  pkg/test/framework/components/stackdriver/kube.go
  pkg/test/framework/components/stackdriver/stackdriver.yaml
  tests/integration/telemetry/dashboard_test.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/client_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/client_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/traffic_assertion.json.tmpl
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
  tests/integration/telemetry/stats/prometheus/http/stats.go
  tests/integration/telemetry/stats/prometheus/istioctl/istioctl_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/stats_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/stats/prometheus/tcp/stats_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/tcp/testdata/cleanup.yaml
  tests/integration/telemetry/stats/prometheus/util_prometheus.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_tcp_filter_test.go
  tests/integration/telemetry/util.go
Labels: cherrypick/release-1.8, cla: yes, release-notes-none, size/XXL

#28450 Disable strict_1xx_and_204_reponse_headers in envoy bootstrap config
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: area/networking, cherrypick/release-1.7, cherrypick/release-1.8, cla: yes, release-notes-none, size/S

#28498 Do not switch TLS version on 1.6 -> 1.7 upgrade
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/security/model/authentication.go
  releasenotes/notes/tls-version.yaml
Labels: cla: yes, size/M

#28505 [release-1.8] Disable strict_1xx_and_204_reponse_headers in envoy bootstrap config
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/S

#28508 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28488 Fully flag protect service-apis
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: cherrypick/release-1.8, cla: yes, release-notes-none, size/XS

#28470 update release sha for 1.8
  prow/release-commit.sh
Labels: area/environments, cla: yes, release-notes-none, size/XS

#28454 Fix dead link
  operator/scripts/run_update_golden_snapshots.sh
Labels: cla: yes, kind/docs, needs-ok-to-test, release-notes-none, size/XS

#28463 samples/bookinfo: update README
  samples/bookinfo/README.md
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#28462 samples/helloworld: update README
  samples/helloworld/README.md
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#28509 Update service-apis to RC2
  go.mod
  go.sum
  licenses/sigs.k8s.io/service-apis/LICENSE
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.yaml
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.yaml
  pilot/pkg/config/kube/gateway/testdata/tcp.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
  pkg/config/model_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/testdata/service-apis-crd.yaml
Labels: cherrypick/release-1.8, cla: yes, release-notes-none, size/XL

#28529 Fix typo in istioctl upgrade.go
  operator/cmd/mesh/upgrade.go
Labels: area/environments, cla: yes, release-notes-none, size/XS

#28535 Add missing subcommands to proxy-config help synopsis
  istioctl/cmd/proxyconfig.go
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#28526 [release-1.8] Update service-apis to RC2
  go.mod
  go.sum
  licenses/sigs.k8s.io/service-apis/LICENSE
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.yaml
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.yaml
  pilot/pkg/config/kube/gateway/testdata/tcp.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
  pkg/config/model_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/testdata/service-apis-crd.yaml
Labels: cla: yes, release-notes-none, size/XL

#28530 Fix grafana workload dashboard mismatched quantiles query
  manifests/addons/dashboards/istio-workload-dashboard.json
  samples/addons/grafana.yaml
Labels: cherrypick/release-1.8, cla: yes, ok-to-test, release-notes-none, size/XS

#28449 autoregister flag for workload entry command
  istioctl/cmd/workload.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
Labels: cla: yes, release-notes-none, size/XS

#28515 [release-1.8] Fully flag protect service-apis
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: cla: yes, release-notes-none, size/XS

#28532 fix duplicated warning message for operator install command.
  operator/cmd/mesh/install.go
Labels: area/environments, cla: yes, release-notes-none, size/S

#28485 Stop skipping lint/format in integration tests
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  tests/integration/helm/install_test.go
  tests/integration/multicluster/helper.go
  tests/integration/pilot/analysis/analysis_test.go
  tests/integration/pilot/cni/cni_test.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/main_test.go
  tests/integration/security/mtls_first_party_jwt/main_test.go
  tests/integration/security/mtlsk8sca/main_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/sds_egress/main_test.go
  tests/integration/security/util/authn/authn_util.go
  tests/integration/security/util/connection/checker.go
  tests/integration/telemetry/dashboard_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/vm/vm_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/stats_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/util_prometheus.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_tcp_filter_test.go
  tests/integration/telemetry/util.go
Labels: cla: yes, release-notes-none, size/L

#28522 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28516 Manual cherry-pick of https://github.com/istio/istio/pull/28450
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: area/networking, cla: yes, release-notes-none, size/M

#28539 add delay feature to echo
  pkg/test/echo/server/endpoint/http.go
Labels: area/test and release, cla: yes, release-notes-none, size/S

#28501 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28442 Adjust inbound and outbound filter chains
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/simulation/traffic.go
  pilot/pkg/xds/xds_test.go
  pilot/test/xdstest/validate.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: cherrypick/release-1.6, cherrypick/release-1.7, cherrypick/release-1.8, cla: yes, release-notes-none, size/L

#28537 Avoid duplicate HTTP headers for istio-proxy probe requests
  pilot/cmd/pilot-agent/status/server.go
Labels: cla: yes, release-notes-none, size/XS

#28543 [release-1.8] autoregister flag for workload entry command
  istioctl/cmd/workload.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
Labels: cla: yes, release-notes-none, size/XS

#28552 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28389 set validationwebhookconfig as Fail close by default for remote clusters
  pkg/webhooks/validation/controller/controller.go
Labels: cla: yes, release-notes-none, size/XS

#28554 [1.6] Adjust inbound and outbound filter chains (#28442)
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  tests/integration/pilot/routing_test.go
  tests/integration/pilot/sidecar_api_test.go
Labels: cla: yes, size/L

#28557 Automator: update istio/api@release-1.8 dependency in istio/istio@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28427 Improved performance of MostSpecificHostMatch
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/destination_rule.go
  pilot/pkg/model/push_context.go
Labels: area/perf and scalability, area/test and release, cla: yes, ok-to-test, release-notes-none, size/L

#28429 bookinfo build: update readme to describe build process
  samples/bookinfo/README.md
Labels: area/test and release, area/user experience, cla: yes, release-notes-none, size/M

#28486 add analyzer for incompatible host between VirtualService and Gateway
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_host_not_found_gateway.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/config, cla: yes, ok-to-test, release-notes-none, size/L

#28517 Pull base image from GCR instead of dockerhub
  cni/deployments/kubernetes/Dockerfile.install-cni
  istioctl/docker/Dockerfile.istioctl
  operator/docker/Dockerfile.operator
  pilot/docker/Dockerfile.pilot
  pilot/docker/Dockerfile.proxyv2
  pkg/test/echo/docker/Dockerfile.app
Labels: cla: yes, release-notes-none, size/S

#28569 Increase upgrade support for 1.9
  operator/cmd/mesh/upgrade.go
Labels: area/environments/operator, cla: yes, release-notes-none, size/XS

#28273 cherry-pick: do not update root certs for destination rule certs (#27268)
  security/pkg/nodeagent/cache/secretcache.go
Labels: cla: yes, ok-to-test, release-notes-none, size/S

#28446 workload entry configure command allows specifying ingress service name
  istioctl/cmd/workload.go
  istioctl/pkg/multicluster/cluster.go
Labels: cla: yes, release-notes-none, size/S

#28580 Fix issue with any marshal of nil
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: cla: yes, release-notes-none, size/S

#28579 Make grafana dashboard refId ordered
  manifests/addons/dashboards/istio-mesh-dashboard.json
  manifests/addons/dashboards/istio-service-dashboard.json
  manifests/addons/dashboards/istio-workload-dashboard.json
  samples/addons/grafana.yaml
Labels: area/user experience, cla: yes, release-notes-none, size/L

#28512 add sample ext_authz server
  samples/extauthz/README.md
  samples/extauthz/ext-authz.yaml
  samples/extauthz/src/Dockerfile
  samples/extauthz/src/Makefile
  samples/extauthz/src/go.mod
  samples/extauthz/src/go.sum
  samples/extauthz/src/main.go
  samples/extauthz/src/main_test.go
Labels: area/security, cla: yes, release-notes-none, size/XL

#28588 [release-1.8] Add customization for helloworld sample
  samples/helloworld/README.md
  samples/helloworld/gen-helloworld.sh
Labels: cla: yes, release-notes-none, size/L

#28354 Improve wle reg/unreg robustness
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/workloadentry.go
Labels: cla: yes, release-notes-none, size/M

#28584 [release-1.8] workload entry configure command allows specifying ingress service name
  istioctl/cmd/workload.go
  istioctl/pkg/multicluster/cluster.go
Labels: cla: yes, release-notes-none, size/S

#28586 [release-1.8] tests/integration/pilot: update README
  tests/integration/pilot/README.md
Labels: cla: yes, release-notes-none, size/XS

#28560 operator/cmd/mesh/testdata: remove docs
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/README-helm3.md
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/README.md
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/UPDATING-CHARTS.md
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/PROFILES.md
Labels: cla: yes, kind/docs, release-notes-none, size/L

#28561 tests/integration/pilot/README.md: update file path
  tests/integration/pilot/README.md
Labels: cla: yes, kind/docs, release-notes-none, size/XS

#28571 istioctl upgrade: IOPS unchanged warning if upgrade is run on the same version
  operator/cmd/mesh/upgrade.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#28619 echo: allow binding to INSTANCE_IP
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/server/endpoint/grpc.go
  pkg/test/echo/server/endpoint/http.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/endpoint/tcp.go
  pkg/test/echo/server/endpoint/util.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/testdata/basic.yaml
  pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
Labels: cla: yes, release-notes-none, size/L

#28625 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28551 [1.8] Adjust inbound and outbound filter chains (#28442)
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/simulation/traffic.go
  pilot/pkg/xds/xds_test.go
  pilot/test/xdstest/validate.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: cla: yes, release-notes-none, size/L

#28626 [kiali] update to kiali 1.26
  manifests/addons/gen.sh
  manifests/addons/values-kiali.yaml
  releasenotes/notes/kiali-update.yaml
  samples/addons/kiali.yaml
Labels: area/environments, cherrypick/release-1.8, cla: yes, size/L

#28627 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28628 [release-1.8] [kiali] update to kiali 1.26
  manifests/addons/gen.sh
  manifests/addons/values-kiali.yaml
  releasenotes/notes/kiali-update.yaml
  samples/addons/kiali.yaml
Labels: cla: yes, release-notes-none, size/L

#28633 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28593 [Test Framework] Cleanup logic for cluster types
  pkg/test/framework/components/environment/kube/cluster.go
  pkg/test/framework/components/environment/kube/kube.go
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/istio/util.go
  pkg/test/framework/components/istioctl/kube.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/resource/cluster.go
  pkg/test/kube/dump.go
  tests/integration/helm/install_test.go
  tests/integration/operator/switch_cr_test.go
  tests/integration/pilot/cni/cni_test.go
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/revisions/uninstall_test.go
  tests/integration/pilot/webhook_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/chiron/dns_cert_test.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/sds_tls_origination/util/util.go
  tests/integration/security/util/cert/cert.go
  tests/integration/telemetry/dashboard_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#28638 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28642 [release-1.7] Infer headless tlsmode
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  tests/integration/security/reachability_test.go
Labels: cla: yes, release-notes-none, size/L

#28630 Automator: update istio/api@release-1.8 dependency in istio/istio@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28283 chore(manifests): update config to typed config (#27264)
  manifests/charts/gateways/istio-ingress/templates/preconfigured.yaml
  releasenotes/notes/fix-multicluster-envoyfilter.yaml
Labels: cla: yes, size/M

#28553 [1.7] Adjust inbound and outbound filter chains (#28442)
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/xds/xds_test.go
  tests/integration/pilot/routing_test.go
Labels: cla: yes, release-notes-none, size/M

#28590 [Release-1.8] Convert Stackdriver and Stats telemetry tests to use Multicluster (#…
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/components/prometheus/prometheus.go
  pkg/test/framework/components/stackdriver/kube.go
  pkg/test/framework/components/stackdriver/stackdriver.yaml
  tests/integration/telemetry/dashboard_test.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/client_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/client_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/traffic_assertion.json.tmpl
  tests/integration/telemetry/stats/prometheus/http/stats.go
  tests/integration/telemetry/stats/prometheus/istioctl/istioctl_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/stats_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/stats/prometheus/tcp/stats_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/tcp/testdata/cleanup.yaml
  tests/integration/telemetry/stats/prometheus/util_prometheus.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_tcp_filter_test.go
  tests/integration/telemetry/util.go
Labels: cla: yes, release-notes-none, size/XXL

#28650 add update permission for istio-reader
  manifests/charts/base/templates/clusterrole.yaml
Labels: cla: yes, release-notes-none, size/XS

#28274 cherry-pick: pilot: GlobalUnicastIP of a model.Proxy should be set to the 1st applicable IP address in the list (#28260)
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  releasenotes/notes/28269.yaml
Labels: cla: yes, ok-to-test, size/M

#28632 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#28658 [release-1.8] refactor eastwest script to use args
  pkg/test/framework/components/istio/eastwest.go
  samples/multicluster/gen-eastwest-gateway.sh
Labels: cla: yes, release-notes-none, size/M

#28629 Treat JSON values as string for translation
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_merge_meshconfig.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/pkg/tpath/tree.go
Labels: cherrypick/release-1.8, cla: yes, release-notes-none, size/S

#28660 [release-1.8] Treat JSON values as string for translation
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_merge_meshconfig.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/pkg/tpath/tree.go
Labels: cla: yes, release-notes-none, size/S

#28636 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28661 Add explicit check for IP addresses when resolving VirtualService host shortname
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#28665 [release-1.7] Treat JSON values as string for translation
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_merge_meshconfig.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/pkg/tpath/tree.go
Labels: cla: yes, release-notes-none, size/S

#28657 gen-eastwest supports revision
  pkg/test/framework/components/istio/eastwest.go
  pkg/test/framework/components/istio/operator.go
  samples/multicluster/gen-eastwest-gateway.sh
Labels: cla: yes, release-notes-none, size/M

#28669 bump base image
  Makefile.core.mk
Labels: cla: yes, release-notes-none, size/XS

#28451 add initial implementation of CUSTOM action in AuthorizationPolicy
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/authorization.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/security/authz/builder/extauthz.go
  pilot/pkg/security/authz/builder/testdata/action-custom-HTTP-for-TCP-filter-in.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-HTTP-for-TCP-filter-out1.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-HTTP-for-TCP-filter-out2.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-bad-multiple-providers-in.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-bad-out.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-grpc-provider-out1.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-grpc-provider-out2.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-http-provider-out1.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-http-provider-out2.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-in.yaml
  pilot/pkg/xds/fake.go
  pkg/config/validation/extensionprovider.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: area/security, cla: yes, release-notes-none, size/XXL

#28667 Add ca-certs to VM base images and rebuild
  Makefile.core.mk
  pkg/test/echo/docker/Dockerfile.app_sidecar_base
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Labels: cla: yes, release-notes-none, size/XS

#28640 Max workload cert lifetime should not apply to istiod's server cert
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/xds/ads_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
Labels: area/security, cla: yes, release-notes-none, size/L

#28656 Add a release note for external istiod
  releasenotes/notes/external-istiod.yaml
  releasenotes/template.yaml
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S

#28559 samples/custom-bootstrap/README.md: use relative file path
  samples/custom-bootstrap/README.md
Labels: cla: yes, kind/docs, release-notes-none, size/XS

#28676 [release-1.8] Add a release note for external istiod
  releasenotes/notes/external-istiod.yaml
  releasenotes/template.yaml
Labels: cla: yes, release-notes-none, size/S

#28565 fix custom sni in bootstrap clusters properly
  pkg/bootstrap/option/convert.go
  pkg/bootstrap/option/convert_test.go
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
Labels: area/networking, cla: yes, release-notes-none, size/S

#28128 Remove old Istiod DNS code
  pkg/dns/dns.go
  pkg/dns/dns_test.go
Labels: cla: yes, release-notes-none, size/XL

#28602 release/downloadIstioCandidate.sh: check tarball url before download
  release/downloadIstioCandidate.sh
Labels: cla: yes, release-notes-none, size/S

#28677 Fix typo
  operator/README.md
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#28608 istioctl upgrade: display warning when skipping past minor versions
  operator/cmd/mesh/upgrade.go
Labels: area/user experience, cla: yes, release-notes-none, size/S

#27932 istioctl proxy-config log: add label selector to filter logs
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  releasenotes/notes/27490.yaml
Labels: area/user experience, cla: yes, size/M

#28694 Add retry to curl downloads
  bin/init.sh
Labels: cla: yes, release-notes-none, size/XS

#28405 Add validator to perform offline CRD validation in tests
  go.mod
  go.sum
  licenses/github.com/asaskevich/govalidator/LICENSE
  licenses/github.com/go-openapi/analysis/LICENSE
  licenses/github.com/go-openapi/errors/LICENSE
  licenses/github.com/go-openapi/loads/LICENSE
  licenses/github.com/go-openapi/runtime/LICENSE
  licenses/github.com/go-openapi/runtime/middleware/denco/LICENSE
  licenses/github.com/go-openapi/strfmt/LICENSE
  licenses/github.com/go-openapi/validate/LICENSE
  licenses/github.com/go-stack/stack/LICENSE.md
  licenses/go.mongodb.org/mongo-driver/LICENSE
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/mismatch.yaml
  pkg/config/crd/validator.go
  pkg/config/crd/validator_test.go
  pkg/config/model.go
  pkg/config/schema/gvk/resources.go
Labels: cla: yes, release-notes-none, size/XXL

#28655 Fix trust domain RM
  releasenotes/notes/trust-domain-validation.yaml
Labels: cherrypick/release-1.8, cla: yes, size/XS

#28670 Trim agent binary by 14mb by conditionally compiled XDS filters
  Makefile.core.mk
  pilot/pkg/xds/v2/model.go
  pkg/config/xds/filter_types.gen.go
  pkg/config/xds/filter_types.go
Labels: cherrypick/release-1.7, cherrypick/release-1.8, cla: yes, release-notes-none, size/M

#28692 Remove staticinit gen
  galley/pkg/config/testing/basicmeta/generate.go
  galley/pkg/config/testing/basicmeta/staticinit.gen.go
  galley/pkg/config/testing/k8smeta/generate.go
  galley/pkg/config/testing/k8smeta/staticinit.gen.go
  pkg/config/schema/codegen/staticinit.go
  pkg/config/schema/codegen/staticinit_test.go
  pkg/config/schema/codegen/tools/staticinit.main.go
  pkg/config/schema/collections/staticinit.gen.go
  pkg/config/schema/generate.go
  pkg/config/schema/snapshots/staticinit.gen.go
  pkg/config/schema/staticinit.gen.go
Labels: cla: yes, release-notes-none, size/L

#28702 Add 'Upgrade' product area to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#28704 [release-1.8] Fix trust domain RM
  releasenotes/notes/trust-domain-validation.yaml
Labels: cla: yes, release-notes-none, size/XS

#28507 Fix port level mTLS when Sidecar is defined
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/xds/lds_test.go
Labels: cla: yes, release-notes-none, size/L

#28600 Remove unused ca certs bundle
  docker/ca-certificates.tgz
Labels: cla: yes, release-notes-none, size/XS

#28674 Drop dependency on the operator from the agent
  pilot/pkg/bootstrap/server.go
  pilot/pkg/xds/debug.go
Labels: cla: yes, release-notes-none, size/S

#28678 allow passing unset map to MostSpecificHostMatch
  pilot/pkg/model/config.go
  pilot/pkg/model/push_context.go
Labels: area/perf and scalability, cla: yes, ok-to-test, release-notes-none, size/S

#28690 Add test for binary size
  tests/binary/binaries_test.go
Labels: cla: yes, release-notes-none, size/L

#28181 make istiod-less as default remote for integration test
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istiod-remote/templates/configmap.yaml
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/eastwest.go
  pkg/test/framework/components/istio/flags.go
  pkg/test/framework/components/istio/operator.go
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/iop-remote-integration-test-defaults.yaml
Labels: cla: yes, release-notes-none, size/L

#28525 Remove dead test
  tests/integration/security/sds_vault_flow/main_test.go
  tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
  tests/integration/security/sds_vault_flow/testdata/config.yaml
Labels: cla: yes, release-notes-none, size/L

#28544 Add hpa test
  istioctl/cmd/remove-from-mesh.go
  istioctl/cmd/remove-from-mesh_test.go
  operator/cmd/mesh/manifest-generate_test.go
  samples/bookinfo/platform/kube/cleanup.sh
Labels: area/test and release, cla: yes, ok-to-test, release-notes-none, size/S

#28604 pilot: allow enabling gRPC logging with --log_output_level
  go.mod
  go.sum
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
  releasenotes/notes/28604.yaml
Labels: area/test and release, area/user experience, cla: yes, size/S

#28634 Remove Istiod MCP sink
  galley/pkg/config/source/mcp/cache.go
  galley/pkg/config/source/mcp/cache_test.go
  galley/pkg/config/source/mcp/source.go
  galley/pkg/config/source/mcp/source_test.go
  galley/pkg/server/components/patchtable.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/components/processing_test.go
  galley/tools/mcpc/main.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/mcp/controller.go
  pilot/pkg/serviceregistry/mcp/controller_test.go
  pkg/mcp/configz/client/assets/assets.gen.go
  pkg/mcp/configz/client/assets/assets.go
  pkg/mcp/configz/client/assets/templates/config.html
  pkg/mcp/configz/client/configz.go
  pkg/mcp/configz/client/configz_test.go
  pkg/mcp/creds/create.go
  pkg/mcp/creds/create_test.go
  pkg/mcp/creds/load.go
  pkg/mcp/creds/notifyWatcher.go
  pkg/mcp/creds/notifyWatcher_test.go
  pkg/mcp/creds/options.go
  pkg/mcp/creds/watcher.go
  pkg/mcp/internal/test/rate_limiter.go
  pkg/mcp/monitoring/monitoring.go
  pkg/mcp/rate/ratelimiter.go
  pkg/mcp/server/listchecker.go
  pkg/mcp/server/listchecker_test.go
  pkg/mcp/sink/client_sink.go
  pkg/mcp/sink/client_sink_test.go
  pkg/mcp/sink/journal.go
  pkg/mcp/sink/journal_test.go
  pkg/mcp/sink/server_sink.go
  pkg/mcp/sink/server_sink_test.go
  pkg/mcp/sink/sink.go
  pkg/mcp/sink/sink_test.go
  pkg/mcp/snapshot/snapshot.go
  pkg/mcp/source/client_source.go
  pkg/mcp/source/client_source_test.go
  pkg/mcp/source/server_source.go
  pkg/mcp/source/server_source_test.go
  pkg/mcp/source/source.go
  pkg/mcp/source/source_test.go
  pkg/mcp/testing/monitoring/reporter.go
  pkg/mcp/testing/server.go
  pkg/mcp/tests/stress/README.md
  pkg/mcp/tests/stress/stress_setup_test.go
  pkg/mcp/tests/stress/stress_test.go
  releasenotes/notes/mcp-removal.yaml
  tests/util/pilot_server.go
Labels: cla: yes, size/XXL

#28648 add runAsUser to bookinfo samples to run as non-root
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: area/environments, area/user experience, cla: yes, ok-to-test, release-notes-none, size/S

#28718 [1.8] Trim agent binary by 14mb by conditionally compiled XDS filters (#28670)
  Makefile.core.mk
  pilot/pkg/xds/v2/model.go
  pkg/config/xds/filter_types.gen.go
  pkg/config/xds/filter_types.go
Labels: cla: yes, release-notes-none, size/M

#28617 EDS: Ignore pods in deleting status
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: cla: yes, release-notes-none, size/M

#28679 Modify TestMostSpecificHostmatch to construct map in test loop
  pilot/pkg/model/config_test.go
Labels: area/test and release, cla: yes, ok-to-test, release-notes-none, size/M

#28329 GetProxyServiceInstances cleanup
  pilot/pkg/model/context.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/config/constants/constants.go
  pkg/test/framework/components/echo/kube/builder.go
Labels: cherrypick/release-1.8, cla: yes, release-notes-none, size/M

#28472 Display schema validation warnings in istioctl analyze
  galley/pkg/config/analysis/analyzers/schema/validation.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/user experience, cla: yes, release-notes-none, size/S

#28722 [release-1.8] GetProxyServiceInstances cleanup
  pilot/pkg/model/context.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/config/constants/constants.go
  pkg/test/framework/components/echo/kube/builder.go
Labels: cla: yes, release-notes-none, size/M

#28717 [1.7] Trim agent binary by 14mb by conditionally compiled XDS filters (#28670)
  Makefile.core.mk
  pilot/pkg/xds/v2/model.go
  pkg/config/xds/filter_types.gen.go
  pkg/config/xds/filter_types.go
Labels: cla: yes, release-notes-none, size/M

#28725 Automator: update istio/api@release-1.8 dependency in istio/istio@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28500 Update proxy sha
  istio.deps
  pkg/test/framework/components/stackdriver/kube.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_registry_only_test.go
Labels: cla: yes, release-notes-none, size/S

#28703 [1.7] Remove dependency on google.golang.org/api (#26242)
  pkg/bootstrap/platform/gcp.go
Labels: cla: yes, release-notes-none, size/M

#28729 Skip VM related parts for TestTraffic
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  tests/integration/README.md
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: cla: yes, release-notes-none, size/M

#28733 remove unused old centralIstiod tests since we have made istiod-less …
  pkg/test/framework/features/features.yaml
  tests/integration/multicluster/centralistio/main_test.go
Labels: cla: yes, release-notes-none, size/M

#28732 Fix inject validata
  pkg/kube/inject/inject.go
Labels: area/user experience, cherrypick/release-1.7, cherrypick/release-1.8, cla: yes, ok-to-test, size/XS

#28726 test framework: deploy gateways for remote clusters
  pkg/test/framework/components/istio/operator.go
  tests/integration/iop-remote-integration-test-defaults.yaml
Labels: cla: yes, release-notes-none, size/M

#28735 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28603 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#28739 minor fix for pre-check
  istioctl/pkg/install/pre-check.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#28671 Stop using deprecated log functions
  cni/pkg/install-cni/cmd/root.go
  galley/pkg/config/processing/snapshotter/snapshotter.go
  galley/pkg/config/source/inmemory/collection.go
  galley/pkg/config/source/kube/apiserver/source.go
  galley/pkg/config/source/kube/inmemory/kubesource.go
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/mesh.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/webhook.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/apigen/apigen.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/grpcgen/grpcgen.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pilot/pkg/serviceregistry/kube/deregister.go
  pilot/pkg/serviceregistry/kube/register.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/authentication.go
  pilot/pkg/xds/internalgen.go
  pilot/pkg/xds/simple.go
  pkg/adsc/adsc.go
  pkg/config/event/router.go
  pkg/envoy/proxy.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/local_xds_generator.go
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/server/endpoint/http.go
  pkg/webhooks/webhookpatch.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/stsservice/server/server.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
  tests/util/pilot_server.go
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/cluster/cluster.go
  tools/bug-report/pkg/content/content.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/root.go
Labels: cla: yes, release-notes-none, size/L

#28745 Fix bad revision in IOP
  operator/pkg/validate/validate.go
Labels: area/environments/operator, cla: yes, release-notes-none, size/S

#28594 Convert more reachability tests into multicluster support
  tests/integration/security/reachability_test.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#28502 Convert TestPassThroughFilterChain into multicluster support
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/util/framework.go
Labels: area/security, cla: yes, release-notes-none, size/L

#28751 Fix dashboard duplicate datasource issue
  manifests/addons/dashboards/istio-service-dashboard.json
  manifests/addons/dashboards/istio-workload-dashboard.json
  samples/addons/grafana.yaml
Labels: area/user experience, cla: yes, release-notes-none, size/L

#28757 [release-1.8] Avoid duplicate grafana URL when absolute linkUrl is set
  manifests/addons/dashboards/istio-mesh-dashboard.json
  samples/addons/grafana.yaml
Labels: cla: yes, release-notes-none, size/S

#28598 Add /debug/mesh endpoint
  pilot/pkg/xds/debug.go
Labels: cla: yes, release-notes-none, size/XS

#28760 Fix observed generation release note
  releasenotes/notes/28003.yaml
Labels: cherrypick/release-1.8, cla: yes, size/XS

#28759 Add terminationGracePeriodSeconds=0 to sleep sample
  samples/sleep/sleep.yaml
Labels: cla: yes, release-notes-none, size/XS
