Repository istio/istio, pull requests merged in 2020-05, with the labels that each got.

#23275 Preserve source ip in TPROXY mode
  pilot/pkg/networking/core/v1alpha3/filters.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  tools/istio-iptables/pkg/cmd/run.go
Labels: area/environments, area/networking, cla: yes, ok-to-test, size/M

#23445 Add Kiali fix to Helm
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: cla: yes, size/XS

#23432 Send gateway readiness probe through envoy
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/profiles/default.yaml
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/XL

#23448 Update RDS on DestinationRule change
  pilot/pkg/proxy/envoy/v2/ads_common.go
Labels: cherrypick/release-1.5, cherrypick/release-1.6, cla: yes, size/XS

#23459 Update to latest common files and update redigo
  common/.commonfiles.sha
  common/config/license-lint.yml
  go.mod
  go.sum
  licenses/github.com/gomodule/redigo/LICENSE
Labels: cla: yes, size/S

#23460 Bypass iptables for port 15021
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
Labels: cla: yes, size/XS

#23361 [release-1.6] unit tests for ServiceEntry update fix
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
Labels: cla: yes, size/M

#23393 Use labels and annotations from istio/api repo
  galley/pkg/config/analysis/analyzers/injection/injection.go
  istioctl/pkg/kubernetes/client.go
  operator/pkg/helmreconciler/reconciler.go
  pilot/cmd/pilot-agent/config.go
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/model/config.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
  pilot/pkg/serviceregistry/external/servicediscovery_test.go
  pilot/pkg/serviceregistry/mcp/controller.go
  pkg/kube/inject/inject.go
  pkg/kube/inject/testdata/inject/traffic-annotations.yaml
  pkg/kube/inject/testdata/inject/traffic-annotations.yaml.injected
  pkg/kube/inject/webhook.go
  pkg/test/framework/components/namespace/kube.go
Labels: cherrypick/release-1.6, cla: yes, size/L

#23449 [release-1.6] Send gateway readiness probe through envoy
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/profiles/default.yaml
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/XL

#23451 [release-1.6] Update RDS on DestinationRule change
  pilot/pkg/proxy/envoy/v2/ads_common.go
Labels: cla: yes, size/XS

#23467 [release-1.6] Bypass iptables for port 15021
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
Labels: cla: yes, size/XS

#23468 test framework: dump envoy proxy configs
  pkg/test/framework/components/namespace/kube.go
Labels: area/test and release, cla: yes, size/S

#23437 Remove node_agent binary
  Makefile.core.mk
  pkg/test/echo/docker/echo-start.sh
  security/cmd/node_agent/main.go
  tools/packaging/deb/istio.mk
  tools/packaging/deb/postinst.sh
Labels: cla: yes, size/L

#23478 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#23282 fix operator resources prune issue.
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
Labels: area/environments, cherrypick/release-1.6, cla: yes, size/M

#23454 create dns certs only if custom certs are not provided
  pilot/pkg/bootstrap/server.go
Labels: area/networking, cla: yes, size/S

#23474 Bump test kind image
  prow/lib.sh
Labels: cla: yes, size/XS

#23444 Update Kiali for Istio 1.15
  install/kubernetes/helm/istio/charts/kiali/Chart.yaml
  install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml
  install/kubernetes/helm/istio/charts/kiali/values.yaml
Labels: cla: yes, flag/needs-release-note, size/XS

#23450 [release-1.5] Update RDS on DestinationRule change
  pilot/pkg/proxy/envoy/v2/ads_common.go
Labels: cla: yes, size/XS

#23458 Let --force really work in 'manifest apply'
  operator/cmd/mesh/manifest-apply.go
  operator/pkg/helmreconciler/reconciler.go
  operator/pkg/helmreconciler/render.go
  operator/pkg/validate/common.go
Labels: cla: yes, size/S

#23440 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#20689 BUGFIX: Fall back to InClusterConfig
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: area/security, cla: yes, size/L

#23500 [release-1.6] BUGFIX: Fall back to InClusterConfig
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: cla: yes, size/L

#23472 Avoid accidental dynamic concurrency
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/testdata/inject/traffic-annotations.yaml
  pkg/kube/inject/testdata/inject/traffic-annotations.yaml.injected
Labels: cherrypick/release-1.6, cla: yes, size/M

#23430 Fix integration local test races
  pilot/pkg/config/memory/monitor.go
  pilot/pkg/config/memory/monitor_test.go
  pilot/pkg/config/monitor/monitor.go
  pilot/pkg/config/monitor/monitor_test.go
  pkg/test/docker/container.go
  pkg/test/framework/components/galley/native.go
  tests/integration/pilot/sidecar_api_test.go
Labels: cla: yes, size/L

#23466 Update kind to 0.8.0
  prow/lib.sh
Labels: cla: yes, size/S

#23514 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#23446 [release-1.6] Preserve source ip in TPROXY mode
  pilot/pkg/networking/core/v1alpha3/filters.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  tools/istio-iptables/pkg/cmd/run.go
Labels: cla: yes, size/M

#23516 Update istio/pkg library
  go.mod
  go.sum
Labels: cla: yes, size/XS

#23518 [release-1.6] Avoid accidental dynamic concurrency (#23472)
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/testdata/inject/traffic-annotations.yaml
  pkg/kube/inject/testdata/inject/traffic-annotations.yaml.injected
Labels: cla: yes, size/M

#23417 sds: add file watcher support
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: cla: yes, size/L

#23506 [release-1.5] Update CNI dep to include fix for openshift 4.3.5 install issue
  istio.deps
Labels: area/environments, area/test and release, cla: yes, size/XS

#23517 Remove temporary kind workaround
  prow/lib.sh
Labels: cla: yes, size/XS

#23465 Remove tcp mx alpn from http filter chains in downstreamtlscontext
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: area/policies and telemetry, area/security, cherrypick/release-1.5, cherrypick/release-1.6, cla: yes, size/L

#23522 Update tcp stats configuration to use different vm id
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.6.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
Labels: cla: yes, size/M

#23533 Add some missed deprecation warnings
  bin/nomodify.md5
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/configmap.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/cmd/mesh/testdata/profile-dump/output/config_path.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.6, cla: yes

#23535 [release-1.6] Update tcp stats configuration to use different vm id
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.6.yaml
Labels: cla: yes, size/S

#23540 Update operator for istio/operator#777
  go.mod
  go.sum
Labels: cla: yes, size/XS

#23520 Fully support installPackagePath
  bin/nomodify.md5
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/profile-diff.go
  operator/cmd/mesh/profile-dump_test.go
  operator/cmd/mesh/profile-list.go
  operator/cmd/mesh/profile.go
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/cmd/mesh/testdata/profile-dump/output/config_path.yaml
  operator/pkg/helm/helm.go
  operator/pkg/helm/vfs_renderer.go
  operator/pkg/validate/validate_values_test.go
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#23545 Automator: update common-files@release-1.6 in istio/istio@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#23311 Add validation and analysis for meshnetworks
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/multicluster/meshnetworks.go
  galley/pkg/config/analysis/analyzers/testdata/common/meshnetworks.yaml
  galley/pkg/config/analysis/analyzers/testdata/multicluster-unknown-serviceregistry.yaml
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  galley/pkg/config/mesh/const.go
  galley/pkg/config/mesh/defaults.go
  galley/pkg/config/mesh/defaults_test.go
  galley/pkg/config/mesh/fs.go
  galley/pkg/config/mesh/fs_test.go
  galley/pkg/config/mesh/inmemory.go
  galley/pkg/config/mesh/inmemory_test.go
  galley/pkg/config/mesh/metadata_test.go
  galley/pkg/config/processing/runtime_test.go
  galley/pkg/config/processing/session.go
  galley/pkg/config/processor/build_test.go
  galley/pkg/config/processor/transforms/ingress/dataset_test.go
  galley/pkg/config/processor/transforms/ingress/gateway_test.go
  galley/pkg/config/processor/transforms/ingress/virtualService_test.go
  galley/pkg/server/components/patchtable.go
  galley/pkg/server/components/processing_test.go
  pkg/config/mesh/mesh.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: area/networking, cla: yes, size/XL

#23543 Replace kubectl exec for contacting Pilot in istioctl
  istioctl/cmd/metrics_test.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/version.go
  istioctl/cmd/version_test.go
  istioctl/cmd/wait.go
  istioctl/pkg/kubernetes/client.go
Labels: cla: yes, size/M

#23546 Cherrypick #23533
  bin/nomodify.md5
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/configmap.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/cmd/mesh/testdata/profile-dump/output/config_path.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#23552 [Release-1.6] Remove tcp mx alpn from http filter chains in downstreamtlscontext
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: area/policies and telemetry, cla: yes, size/L

#23498 Rebuild bookinfo
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/productpage/Dockerfile
Labels: cla: yes, size/M

#23549 [release-1.6] Add validation and analysis for meshnetworks
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/multicluster/meshnetworks.go
  galley/pkg/config/analysis/analyzers/testdata/common/meshnetworks.yaml
  galley/pkg/config/analysis/analyzers/testdata/multicluster-unknown-serviceregistry.yaml
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  galley/pkg/config/mesh/const.go
  galley/pkg/config/mesh/defaults.go
  galley/pkg/config/mesh/defaults_test.go
  galley/pkg/config/mesh/fs.go
  galley/pkg/config/mesh/fs_test.go
  galley/pkg/config/mesh/inmemory.go
  galley/pkg/config/mesh/inmemory_test.go
  galley/pkg/config/mesh/metadata_test.go
  galley/pkg/config/processing/runtime_test.go
  galley/pkg/config/processing/session.go
  galley/pkg/config/processor/build_test.go
  galley/pkg/config/processor/transforms/ingress/dataset_test.go
  galley/pkg/config/processor/transforms/ingress/gateway_test.go
  galley/pkg/config/processor/transforms/ingress/virtualService_test.go
  galley/pkg/server/components/patchtable.go
  galley/pkg/server/components/processing_test.go
  pkg/config/mesh/mesh.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: cla: yes, size/XL

#23542 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#23555 Improvements to operator pruning (#23314)
  istioctl/pkg/kubernetes/client.go
  operator/cmd/mesh/manifest-apply.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
  operator/pkg/util/progress.go
  operator/pkg/util/progress_test.go
Labels: cla: yes, size/L

#23547 Add --revision flag alias
  operator/cmd/mesh/manifest-apply.go
  operator/cmd/mesh/manifest-common.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/root.go
  operator/cmd/mesh/upgrade.go
Labels: cherrypick/release-1.6, cla: yes, size/M

#23102 SDS agent bring clusterID meta when send csr request
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/istio-agent/sds-agent.go
  security/pkg/k8s/tokenreview/k8sauthn.go
  security/pkg/k8s/tokenreview/k8sauthn_test.go
  security/pkg/k8s/tokenreview/testdata/legacy-jwt.jwt
  security/pkg/k8s/tokenreview/testdata/trustworthy-jwt.jwt
  security/pkg/nodeagent/caclient/client.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
  security/pkg/nodeagent/caclient/providers/citadel/client_test.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/server/ca/authenticate/authenticator.go
  security/pkg/server/ca/authenticate/kube_jwt.go
  security/pkg/server/ca/authenticate/kube_jwt_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: cla: yes, size/XXL

#23551 [Release-1.5] Remove tcp mx alpn from http filter chains in downstreamtlscontext
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1alpha1/policy_applier.go
  pilot/pkg/security/authn/v1alpha1/policy_applier_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: cla: yes, size/L

#23539 [release-1.5] update tcp stats configuration to use different vm id
  manifests/istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#23566 update operator doc.
  operator/README.md
Labels: area/environments, cla: yes, kind/docs, size/S

#23491 add wait options for operator.
  manifests/charts/istio-operator/templates/deployment.yaml
  manifests/charts/istio-operator/values.yaml
  operator/deploy/operator.yaml
  operator/pkg/helmreconciler/reconciler.go
  operator/pkg/helmreconciler/wait.go
Labels: area/environments, cla: yes, size/S

#23406 Use derived ProxyConfig for tracing tls settings
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
Labels: cherrypick/release-1.6, cla: yes, size/S

#23492 istiod: unify cert handling logic and remove unused code from webhooks
  galley/pkg/server/components/validation.go
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/bootstrap/validation.go
  pilot/pkg/bootstrap/webhook.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  pkg/webhooks/validation/server/monitoring.go
  pkg/webhooks/validation/server/server.go
  pkg/webhooks/validation/server/server_test.go
Labels: cla: yes, size/XL

#23532 [release-1.6] Add command args to configure Isitod with externally managed certificates
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/bootstrap/validation.go
  pilot/pkg/bootstrap/webhook.go
Labels: cla: yes, size/M

#23556 Drop kubectl exec in favor of port-forward for envoy commands
  istioctl/pkg/kubernetes/client.go
Labels: cla: yes, size/M

#23568 fix configMap name of istio-sidecar-injector mounted to istiod (#23567)
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#23574 [release-1.6] Fix errors for in-place upgrade 1.6.0
  operator/cmd/mesh/upgrade.go
  operator/pkg/version/version.go
  operator/version/version.go
Labels: cla: yes, size/S

#23126 initial sidecar-bootstrap command
  go.mod
  istioctl/cmd/root.go
  istioctl/cmd/sidecar-bootstrap.go
  istioctl/cmd/sidecar-bootstrap_test.go
Labels: area/config, area/security, area/user experience, cla: yes, feature/Virtual-machine, ok-to-test, size/XL

#23571 Use derived ProxyConfig for tracing tls settings (#23406)
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
Labels: cla: yes, size/S

#23572 Fix portmanager race
  pkg/test/docker/container.go
  pkg/test/framework/components/echo/docker/port.go
  pkg/test/framework/components/echo/docker/workload.go
  pkg/test/framework/components/environment/native/native.go
Labels: cla: yes, size/M

#23573 Long description and better examples for add-to-mesh/remove-from-mesh
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/remove-from-mesh.go
Labels: cla: yes, size/L

#23579 Update istio.io/api
  go.mod
  go.sum
Labels: area/test and release, cla: yes, size/XS

#23097 istioctl: check for v1alpha1 security CRDs in upgrade
  operator/cmd/mesh/upgrade.go
Labels: area/environments, area/security, cherrypick/release-1.6, cla: yes, size/M

#23585 [release-1.6] istioctl: check for v1alpha1 security CRDs in upgrade
  operator/cmd/mesh/upgrade.go
Labels: cla: yes, size/M

#23584 fix(canonical service): add env vars for canonical service
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
Labels: area/policies and telemetry, cla: yes, size/M

#23588 [release-1.6] fix(canonical service): add env vars for canonical service
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
Labels: cla: yes, size/M

#23512 Remove builtin versioned yaml-as-code files from operator assets.gen.go
  bin/nomodify.md5
  istioctl/pkg/install/verify.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-versions.go
  operator/cmd/mesh/manifest-versions_test.go
  operator/cmd/mesh/manifest.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/upgrade.go
  operator/data/translateConfig/names-1.5.yaml
  operator/data/translateConfig/names-1.6.yaml
  operator/data/translateConfig/names-1.7.yaml
  operator/data/translateConfig/reverseTranslateConfig-1.4.yaml
  operator/data/translateConfig/reverseTranslateConfig-1.5.yaml
  operator/data/translateConfig/reverseTranslateConfig-1.6.yaml
  operator/data/translateConfig/reverseTranslateConfig-1.7.yaml
  operator/data/translateConfig/translateConfig-1.3.yaml
  operator/data/translateConfig/translateConfig-1.4.yaml
  operator/data/translateConfig/translateConfig-1.5.yaml
  operator/data/translateConfig/translateConfig-1.6.yaml
  operator/data/translateConfig/translateConfig-1.7.yaml
  operator/data/versions.yaml
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/render.go
  operator/pkg/name/name.go
  operator/pkg/translate/translate.go
  operator/pkg/translate/translate_common.go
  operator/pkg/translate/translate_test.go
  operator/pkg/translate/translate_value.go
  operator/pkg/translate/translate_value_test.go
  operator/pkg/version/version.go
  operator/pkg/version/version_test.go
  operator/pkg/vfs/assets.gen.go
  operator/scripts/create_release_charts.sh
  operator/version/version_test.go
Labels: cla: yes, size/XXL

#23587 Fix panic when some operator values are null during "manifest generate" or apply
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/bare_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/bogus_cps.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/tpath/tpath.go
Labels: cla: yes, size/M

#23593 change pod event log level to debug
  pilot/pkg/serviceregistry/kube/controller/pod.go
Labels: area/networking, cla: yes, size/XS

#23592 cherrypick 23282.
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
Labels: area/environments, cla: yes, size/M

#23563 [release-1.6] SDS agent bring clusterID meta when send csr request
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/istio-agent/sds-agent.go
  security/pkg/k8s/tokenreview/k8sauthn.go
  security/pkg/k8s/tokenreview/k8sauthn_test.go
  security/pkg/k8s/tokenreview/testdata/legacy-jwt.jwt
  security/pkg/k8s/tokenreview/testdata/trustworthy-jwt.jwt
  security/pkg/nodeagent/caclient/client.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
  security/pkg/nodeagent/caclient/providers/citadel/client_test.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/server/ca/authenticate/authenticator.go
  security/pkg/server/ca/authenticate/kube_jwt.go
  security/pkg/server/ca/authenticate/kube_jwt_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: cla: yes, size/XXL

#23598 [release-1.6] Serve DestinationRule file mounts over SDS
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: cla: yes, size/L

#23597 [release-1.6] change pod event log level to debug
  pilot/pkg/serviceregistry/kube/controller/pod.go
Labels: cla: no, cla: yes, size/XS

#23462 Update links in Istio Operator README.md
  operator/README.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#23570 Handle custom resource name in Gateways
  manifests/charts/gateways/istio-egress/templates/serviceaccount.yaml
  manifests/charts/gateways/istio-ingress/templates/role.yaml
  manifests/charts/gateways/istio-ingress/templates/rolebindings.yaml
  manifests/charts/gateways/istio-ingress/templates/serviceaccount.yaml
  operator/cmd/mesh/manifest-generate_test.go
Labels: area/environments, cla: yes, size/S

#23612 Use CA bundle if provided via command args.
  pilot/pkg/bootstrap/sidecarinjector.go
Labels: area/networking, cla: yes, ok-to-test, size/S

#23613 Guard against null bool in "manifest generate"
  operator/cmd/mesh/testdata/manifest-generate/input/bogus_cps.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
Labels: cla: yes, size/XS

#23586 [Test Framework] Remove unnecessary components
  pkg/test/deployment/util.go
  pkg/test/deployment/yaml.go
  pkg/test/framework/components/bookinfo/bookinfo.go
  pkg/test/framework/components/bookinfo/kube.go
  pkg/test/framework/components/chiron/chiron.go
  pkg/test/framework/components/chiron/kube.go
  pkg/test/framework/components/citadel/citadel.go
  pkg/test/framework/components/citadel/kube.go
  pkg/test/framework/components/deployment/deployment.go
  pkg/test/framework/components/deployment/kube.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/framework/initstatics.go
  pkg/test/kube/accessor.go
  pkg/test/kube/deployment.go
  tests/integration/mixer/telemetry/metrics/scenarios_test.go
  tests/integration/qualification/loadbalancing_test.go
  tests/integration/security/chiron/dns_cert_test.go
Labels: cla: yes, size/XL

#23596 Tpath cleanup
  operator/cmd/mesh/test-util.go
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/pkg/compare/compare.go
  operator/pkg/name/name_test.go
  operator/pkg/tpath/struct.go
  operator/pkg/tpath/tpath_test.go
  operator/pkg/tpath/tree.go
  operator/pkg/tpath/util.go
  operator/pkg/translate/translate_common.go
  operator/pkg/translate/translate_value.go
  operator/pkg/translate/yaml_tree.go
  operator/pkg/util/reflect.go
  operator/pkg/util/yaml.go
Labels: cla: yes, size/XL

#23611 istiod: add tests for istiod cert rotation
  galley/pkg/server/components/processing_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
  pkg/mcp/creds/notifyWatcher_test.go
  pkg/mcp/creds/pollingWatcher_test.go
  pkg/testcerts/generate-certs.sh
  pkg/testcerts/testcerts.go
  pkg/webhooks/validation/controller/controller_test.go
  pkg/webhooks/validation/server/server_test.go
Labels: cla: yes, size/L

#23076 New metric for cert chain expiry timestamp
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
  security/pkg/pki/util/mock/fakekeycertbundle.go
  security/pkg/server/ca/monitoring.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: area/policies and telemetry, area/security, cla: yes, ok-to-test, size/L

#23594 test framework: centralize pod dump and include envoy configs
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/kube/accessor.go
  pkg/test/kube/dump.go
Labels: area/test and release, cla: yes, size/L

#23505 Add memberlist secret for metallb
  prow/lib.sh
Labels: cla: yes, size/XS

#23606 remove deprecated fields
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/UPDATING-CHARTS.md
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
Labels: cla: yes, ok-to-test, size/M

#23554 Fix Test_SecretController flake
  mixer/adapter/kubernetesenv/kubernetesenv.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/kube/secretcontroller/secretcontroller.go
  pkg/kube/secretcontroller/secretcontroller_test.go
Labels: cla: yes, size/S

#23548 Add an Istiod-remote chart
  Makefile.core.mk
  manifests/charts/README-helm3.md
  manifests/charts/istiod-remote/Chart.yaml
  manifests/charts/istiod-remote/NOTES.txt
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  manifests/charts/istiod-remote/kustomization.yaml
  manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/values.yaml
Labels: area/environments, cla: yes, size/XXL

#23641 fix test istiod cert reload flake
  pilot/pkg/bootstrap/server.go
Labels: area/networking, cla: yes, size/XS

#23602 rename package external to serviceentry
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/proxy/envoy/v2/bench_test.go
  pilot/pkg/proxy/envoy/xds/xds.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
Labels: cla: yes, size/M

#23634 Fix broken cluster-local domain override
  galley/pkg/config/analysis/analyzers/util/constants.go
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/server/settings/args.go
  galley/pkg/server/settings/args_test.go
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/describe.go
  istioctl/pkg/convert/ingress.go
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/model/context.go
  pilot/pkg/security/trustdomain/bundle.go
  pkg/config/constants/constants.go
  pkg/dns/dns.go
  pkg/spiffe/spiffe.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/environment/native/native.go
Labels: cla: yes, size/L

#23636 [release-1.6] sds: add file watcher support
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: cla: yes, size/L

#23608 Add a feature flag for se selecting pods
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/features/pilot.go
Labels: area/networking, cla: yes, size/XS

#23654 1.5 bump base
  Makefile.core.mk
Labels: cla: yes, size/XS

#23624 use istiod flag to create istiod or Istiod-remote service
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
Labels: area/environments, cla: yes, size/M

#23657 [release-1.6] Fix panic when some operator values are null during "manifest generate" or apply
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/bare_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/bogus_cps.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/tpath/tpath.go
Labels: cla: yes, size/M

#22762 Simplified addons implementation
  manifests/addons/gen.sh
  manifests/addons/values-grafana.yaml
  manifests/addons/values-prometheus.yaml
  samples/addons/README.md
  samples/addons/extras/zipkin.yaml
  samples/addons/grafana.yaml
  samples/addons/jaeger.yaml
  samples/addons/kiali.yaml
  samples/addons/prometheus.yaml
Labels: cherrypick/release-1.6, cla: yes, size/XXL

#23659 check for Values.pilot instead of Values.global.pilot
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
Labels: area/environments, cla: yes, size/XS

#23660 [release-1.6] Simplified addons implementation
  manifests/addons/gen.sh
  manifests/addons/values-grafana.yaml
  manifests/addons/values-prometheus.yaml
  samples/addons/README.md
  samples/addons/extras/zipkin.yaml
  samples/addons/grafana.yaml
  samples/addons/jaeger.yaml
  samples/addons/kiali.yaml
  samples/addons/prometheus.yaml
Labels: cla: yes, size/XXL

#23625 set discoveryAddress to be cluster-local by default
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
Labels: area/networking, cla: yes, size/S

#23662 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#23208 test framework: allow configuring remote (non-control plane) clusters
  pkg/test/framework/components/environment/kube/kube.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/istio/util.go
  prow/lib.sh
  tests/integration/multicluster/cluster_local.go
  tests/integration/multicluster/helper.go
  tests/integration/multicluster/multimaster/main_test.go
  tests/integration/multicluster/reachability.go
  tests/integration/multicluster/remote/main_test.go
Labels: area/networking, area/test and release, cla: yes, size/L

#23099 fix hub and tag override for operator test
  pkg/test/kube/accessor.go
  tests/integration/operator/main_test.go
  tests/integration/operator/switch_cr_test.go
Labels: cla: yes, size/M

#23665 [release-1.6] Update proxy SHA
  istio.deps
Labels: cla: yes, size/XS

#23667 Manually cherry-pick #23608 back to release-1.6
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/features/pilot.go
Labels: cla: yes, size/XS

#23226 Support creation of CSRs using ECC based on root CA certs using ECC
  pilot/pkg/bootstrap/server.go
  pkg/istio-agent/sds-agent.go
  security/pkg/caclient/client_test.go
  security/pkg/caclient/protocol/protocol_test.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/vm/nodeagent_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
  security/pkg/pki/testdata/ec-root-cert.pem
  security/pkg/pki/testdata/ec-root-key.pem
  security/pkg/pki/testdata/ec-workload-cert.pem
  security/pkg/pki/testdata/ec-workload-key.pem
  security/pkg/pki/testdata/multilevelpki/ecc-certs.sh
  security/pkg/pki/testdata/multilevelpki/ecc-int-cert-chain.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int-cert.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int-key.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int2-cert-chain.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int2-cert.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int2-key.pem
  security/pkg/pki/testdata/multilevelpki/ecc-root-cert.pem
  security/pkg/pki/testdata/multilevelpki/ecc-root-key.pem
  security/pkg/pki/util/crypto.go
  security/pkg/pki/util/crypto_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/generate_csr.go
  security/pkg/pki/util/generate_csr_test.go
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
  security/pkg/pki/util/verify_cert.go
  security/pkg/pki/util/verify_cert_test.go
  security/pkg/probe/controller.go
  security/pkg/probe/controller_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
  security/tools/generate_cert/main.go
  security/tools/generate_csr/main.go
Labels: area/security, cla: yes, size/XXL

#23607 Make xxxHandler as a method of ServiceEntryStore
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
Labels: cla: yes, size/L

#23645 [release-1.6] Use CA bundle if provided via command args.
  pilot/pkg/bootstrap/sidecarinjector.go
Labels: area/networking, cla: yes, ok-to-test, size/S

#23663 Override rather than merge on manifest update
  operator/cmd/mesh/manifest-apply.go
  operator/pkg/helmreconciler/apply.go
  operator/pkg/helmreconciler/apply_test.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/testdata/configmap-changed.yaml
  operator/pkg/helmreconciler/testdata/configmap.yaml
Labels: cla: yes, size/L

#23577 [kiali] move to v1.18 to address compatibility fixes for istio 1.6
  manifests/charts/istio-telemetry/kiali/Chart.yaml
  manifests/charts/istio-telemetry/kiali/values.yaml
  manifests/profiles/default.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/kiali/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/helm_values_enablement.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
Labels: area/environments, cherrypick/release-1.6, cla: yes, size/S

#23678 [kiali] pilot version endpoint is gone, use the new istiod replacement
  manifests/charts/istio-telemetry/kiali/templates/configmap.yaml
Labels: area/environments, cherrypick/release-1.6, cla: yes, size/XS

#23679 [release-1.6] [kiali] pilot version endpoint is gone, use the new istiod replacement
  manifests/charts/istio-telemetry/kiali/templates/configmap.yaml
Labels: cla: yes, size/XS

#23581 [release-1.6]fix controller test and add back resource status check
  pkg/test/kube/accessor.go
  tests/integration/operator/main_test.go
  tests/integration/operator/switch_cr_test.go
Labels: cla: yes, size/M

#23684 server: move init certs out of secure gRPC listener
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
Labels: cla: yes, size/L

#22919 Move Cluster and Endpoints to xds V3
  pilot/pkg/model/context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/configgen.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/plugin.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/bench_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pkg/adsc/adsc.go
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/platform/aws.go
  pkg/bootstrap/platform/aws_test.go
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/platform.go
  pkg/config/validation/validation_test.go
  pkg/config/xds/xds.go
  tests/integration/pilot/sidecarscope/scope_serviceentry_dns_test.go
  tests/integration/pilot/sidecarscope/scope_serviceentry_static_test.go
  tests/testdata/bootstrap_tmpl.json
Labels: cla: yes, size/XXL

#23693 [release-1.6] cherry pick use istiod flag to create istiod or Istiod-remote service and #23659
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
Labels: area/environments, cla: yes, size/M

#23604 fix incorrect labels for watching resources.
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
Labels: cla: yes, size/M

#23682 [kiali] move to v1.18 to address compatibility fixes for istio 1.6
  manifests/charts/istio-telemetry/kiali/Chart.yaml
  manifests/charts/istio-telemetry/kiali/values.yaml
  manifests/profiles/default.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/kiali/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/helm_values_enablement.golden.yaml
Labels: area/environments, cla: yes, size/S

#23699 Update proxy sha to latest rel-1.6 branch
  istio.deps
Labels: cla: yes, size/XS

#23700 server: cleanup istiod feature flag
  pilot/pkg/bootstrap/mesh.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/validation.go
  pilot/pkg/bootstrap/webhook.go
  pilot/pkg/features/pilot.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pkg/test/framework/components/pilot/native.go
Labels: cla: yes, size/M

#23698 server: add some todos for future cleanup
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, size/S

#23707 rename JWT policy constants as per go conventions
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pkg/jwt/jwt.go
  security/pkg/k8s/tokenreview/k8sauthn.go
  security/pkg/server/ca/authenticate/kube_jwt_test.go
  security/pkg/server/ca/server_test.go
Labels: area/networking, area/security, cla: yes, size/M

#23671 Support creation of CSRs using ECC based on root CA certs using ECC (…
  pilot/pkg/bootstrap/server.go
  pkg/istio-agent/sds-agent.go
  security/pkg/caclient/client_test.go
  security/pkg/caclient/protocol/protocol_test.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/vm/nodeagent_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/mock/fakeca.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
  security/pkg/pki/testdata/ec-root-cert.pem
  security/pkg/pki/testdata/ec-root-key.pem
  security/pkg/pki/testdata/ec-workload-cert.pem
  security/pkg/pki/testdata/ec-workload-key.pem
  security/pkg/pki/testdata/multilevelpki/ecc-certs.sh
  security/pkg/pki/testdata/multilevelpki/ecc-int-cert-chain.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int-cert.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int-key.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int2-cert-chain.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int2-cert.pem
  security/pkg/pki/testdata/multilevelpki/ecc-int2-key.pem
  security/pkg/pki/testdata/multilevelpki/ecc-root-cert.pem
  security/pkg/pki/testdata/multilevelpki/ecc-root-key.pem
  security/pkg/pki/util/crypto.go
  security/pkg/pki/util/crypto_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/generate_csr.go
  security/pkg/pki/util/generate_csr_test.go
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
  security/pkg/pki/util/verify_cert.go
  security/pkg/pki/util/verify_cert_test.go
  security/pkg/probe/controller.go
  security/pkg/probe/controller_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
  security/tools/generate_cert/main.go
  security/tools/generate_csr/main.go
Labels: area/networking, cla: yes, size/XXL

#23649 update webhook config for remote webhook url
  manifests/charts/base/templates/validatingwebhookconfiguration.yaml
  manifests/charts/base/values.yaml
  manifests/charts/gateways/istio-ingress/templates/meshexpansion.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/values.yaml
  manifests/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
Labels: cla: yes, size/M

#23666 Add client cert back to XDS connection
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/S

#23728 Automator: update common-files@release-1.6 in istio/istio@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#23729 Fix operator proto gen
  operator/operator.mk
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: cla: yes, size/XS

#23650 Fix flaky cert expiry tests
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
  security/pkg/server/ca/monitoring.go
Labels: cla: yes, size/L

#23704 support generate workload certs using the generated intermediate ca
  samples/certs/Makefile
  samples/certs/README.md
Labels: area/environments/multicluster, area/user experience, cherrypick/release-1.6, cla: yes, feature/Virtual-machine, size/M

#23708 Make addons owned by environments and P&T
  CODEOWNERS
Labels: cla: yes, size/XS

#23701 [kiali] update the simplified addon gen.sh script to use the new kiali v1.18
  manifests/addons/gen.sh
  samples/addons/kiali.yaml
Labels: cherrypick/release-1.6, cla: yes, size/M

#23724 Handle query parameters in Istiod debug client
  istioctl/pkg/kubernetes/client.go
Labels: cla: yes, size/S

#23733 [release-1.6] support generate workload certs using the generated intermediate ca
  samples/certs/Makefile
  samples/certs/README.md
Labels: cla: yes, size/M

#23739 [release-1.6] cherry-pick Add an Istiod-remote chart (#23548)
  Makefile.core.mk
  manifests/charts/README-helm3.md
  manifests/charts/istiod-remote/Chart.yaml
  manifests/charts/istiod-remote/NOTES.txt
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  manifests/charts/istiod-remote/kustomization.yaml
  manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/values.yaml
Labels: area/environments, cla: yes, size/XXL

#23519 [release-1.6] Fail with exit code in check-no-modify (#23425)
  bin/check_no_modify.sh
  bin/update_no_modify.sh
Labels: cla: yes, size/XS

#23734 [release-1.6] initial sidecar-bootstrap command
  go.mod
  istioctl/cmd/root.go
  istioctl/cmd/sidecar-bootstrap.go
  istioctl/cmd/sidecar-bootstrap_test.go
Labels: cla: yes, size/XL

#23736 [release-1.6] [kiali] update the simplified addon gen.sh script to use the new kiali v1.18
  manifests/addons/gen.sh
  samples/addons/kiali.yaml
Labels: cla: yes, size/M

#23747 Update proxy sha in istio
  istio.deps
Labels: cla: yes, size/XS

#23721 Show RBAC rules when they live under the VirtualInboundListener
  istioctl/cmd/describe.go
  tests/integration/istioctl/testdata/a.yaml
  tests/integration/pilot/istioctl_test.go
Labels: cherrypick/release-1.6, cla: yes, size/M

#23730 Remove Envoy config_dumps from istioctl unit tests
  istioctl/cmd/authz_test.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus_test.go
  istioctl/cmd/testdata/authz/productpage_config_dump.json
  istioctl/cmd/testdata/describe/istio-ingressgateway-5bf6c9887-vvvmj.json
  istioctl/cmd/testdata/describe/productpage-v1-7bbd79f8fd-k6j79.json
  istioctl/cmd/testdata/describe/productpage-v1-c7765c886-v99jb.json
  istioctl/cmd/testdata/describe/ratings-v1-f745cf57b-vfwcv.json
  istioctl/pkg/util/configdump/bootstrap_test.go
  istioctl/pkg/util/configdump/cluster_test.go
  istioctl/pkg/util/configdump/listener_test.go
  istioctl/pkg/util/configdump/route_test.go
  istioctl/pkg/util/configdump/secret_test.go
  istioctl/pkg/util/configdump/testdata/configdump.json
  istioctl/pkg/writer/compare/cluster_test.go
  istioctl/pkg/writer/compare/comparator_test.go
  istioctl/pkg/writer/compare/listener_test.go
  istioctl/pkg/writer/compare/route_test.go
  istioctl/pkg/writer/compare/sds/sds_comparator_test.go
  istioctl/pkg/writer/compare/sds/testdata/envoyconfigdumpsds.json
  istioctl/pkg/writer/compare/sds/util_test.go
  istioctl/pkg/writer/compare/testdata/diffenvoyconfigdump.json
  istioctl/pkg/writer/compare/testdata/envoyconfigdump.json
  istioctl/pkg/writer/compare/testdata/envoyconfigdump2020.json
  istioctl/pkg/writer/compare/testdata/listenerdiff.txt
  istioctl/pkg/writer/compare/testdata/pilotconfigdump.json
  istioctl/pkg/writer/compare/testdata/pilotconfigdump2020.json
  istioctl/pkg/writer/compare/testdata/routediff.txt
  istioctl/pkg/writer/envoy/clusters/clusters_test.go
  istioctl/pkg/writer/envoy/clusters/testdata/clustermultihostsfiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clusters.json
  istioctl/pkg/writer/envoy/clusters/testdata/clustersnofiltered.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clustersummary.txt
  istioctl/pkg/writer/envoy/clusters/testdata/clustersummaryfiltered.txt
  istioctl/pkg/writer/envoy/configdump/cluster_test.go
  istioctl/pkg/writer/envoy/configdump/configdump_test.go
  istioctl/pkg/writer/envoy/configdump/listener_test.go
  istioctl/pkg/writer/envoy/configdump/route_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/bootstrapdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/clusterdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/clusterdumpfiltered.json
  istioctl/pkg/writer/envoy/configdump/testdata/configdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/listenerdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/listenerdumpfiltered.json
  istioctl/pkg/writer/envoy/configdump/testdata/listenersummary.txt
  istioctl/pkg/writer/envoy/configdump/testdata/listenersummaryfiltered.txt
  istioctl/pkg/writer/envoy/configdump/testdata/routedump.json
  istioctl/pkg/writer/envoy/configdump/testdata/routedumpfiltered.json
  istioctl/pkg/writer/envoy/configdump/testdata/routesummary.txt
  istioctl/pkg/writer/envoy/configdump/testdata/routesummaryfiltered.txt
Labels: cla: yes, size/XXL

#23670 Apply --set flags using tpath instead of building tree
  operator/cmd/mesh/manifest-apply.go
  operator/cmd/mesh/manifest-common.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/testdata/manifest-generate/output/gateways.golden.yaml
  operator/cmd/mesh/upgrade.go
  operator/pkg/tpath/tree.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-template-in-values-iop.yaml
  pkg/kube/inject/webhook_test.go
Labels: cherrypick/release-1.6, cla: yes, size/L

#23748 Ignore useless node event
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: cla: yes, size/S

#23743 [release-1.6] cherry pick update webhook config for remote webhook url #23649
  manifests/charts/base/templates/validatingwebhookconfiguration.yaml
  manifests/charts/base/values.yaml
  manifests/charts/gateways/istio-ingress/templates/meshexpansion.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/values.yaml
  manifests/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: area/environments, cla: yes, size/M

#23502 Integration test for ProxyStatus and Experimental AuthZ Check
  istioctl/pkg/util/configdump/cluster.go
  tests/integration/istioctl/testdata/authz-a.yaml
  tests/integration/pilot/istioctl_test.go
Labels: cherrypick/release-1.6, cla: yes, size/M

#23507 Document feature coverage process
  pkg/test/framework/features/README.md
Labels: cla: yes, size/M

#23744 cache service lister to prevent initiating everywhere
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointsdiscovery.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
Labels: area/networking, cla: yes, size/M

#23741 [release-1.6] Make istioctl install output more user friendly (#23424)
  operator/cmd/mesh/manifest-apply.go
  operator/pkg/helmreconciler/apply.go
  operator/pkg/helmreconciler/reconciler.go
  operator/pkg/helmreconciler/wait.go
  operator/pkg/name/name.go
  operator/pkg/util/progress/progress.go
  operator/pkg/util/progress/progress_test.go
Labels: cla: yes, size/L

#23761 Don't listen on 0.0.0.0 doing proxy-status
  istioctl/pkg/kubernetes/client.go
Labels: cla: yes, size/S

#23722 Revert #23663
  operator/pkg/helmreconciler/apply.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/testdata/configmap-changed.yaml
  operator/pkg/helmreconciler/testdata/configmap.yaml
Labels: cla: yes, size/M
