Repository istio/istio, pull requests merged in 2020-10, with the labels that each got.

#27655 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27646 Remove obsolete DNS ports
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/service.yaml
  samples/multicluster/gen-eastwest-gateway.sh
Labels: cla: yes, release-notes-none, size/S

#27652 Fix log format for xdsproxy logs
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/XS

#27529 Fix excessive logs in istioctl operations
  istioctl/cmd/root.go
Labels: cla: yes, release-notes-none, size/XS

#27659 Remove Makefile.vm as it is no longer referenced
  tools/certs/Makefile.vm
Labels: cla: yes, release-notes-none, size/L

#27460 1.7 patch for issue #27427
  manifests/charts/gateways/istio-ingress/templates/preconfigured.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/global.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/examples/multicluster/values-istio-multicluster-gateways.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/27300.yaml
Labels: cla: yes, size/M

#27672 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27642 minor cleanup on remote secret creation
  istioctl/pkg/multicluster/apply.go
  istioctl/pkg/multicluster/cluster.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
Labels: cla: yes, release-notes-none, size/M

#27656 Add traffic passthrough testing with simulation
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/simulation/traffic.go
  pilot/test/xdstest/validate.go
Labels: cla: yes, release-notes-none, size/L

#27679 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27651 xds: push cds on vs update
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/cds.go
  releasenotes/notes/push-cds-and-eds-on-virtualservice-update.yaml
Labels: cla: yes, size/M

#27613 [release-1.7] default min TLS version and configure cipher suites
  pilot/pkg/features/pilot.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  releasenotes/notes/tls-min-version.yaml
Labels: cla: yes, size/L

#27598 Update Helm 3 doc to improve usability
  manifests/charts/README-helm3.md
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/M

#27681 Speed up JWKS tests (15s -> 0.5s)
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/model/jwks_resolver_test.go
  pilot/pkg/model/test/mockopenidserver.go
Labels: cla: yes, release-notes-none, size/L

#27684 Add Update test to Client Go
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: cla: yes, release-notes-none, size/S

#27663 authz: clean namespaceMatch
  galley/pkg/config/analysis/analyzers/authz/authorizationpolicies.go
Labels: cla: yes, ok-to-test, release-notes-none, size/S

#27697 Automator: update istio/api@release-1.7 dependency in istio/istio@release-1.7
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#27470 1.6 patch for issue #27427
  manifests/charts/gateways/istio-ingress/templates/preconfigured.yaml
  manifests/charts/global.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/data/examples/multicluster/values-istio-multicluster-gateways.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/27300.yaml
Labels: cla: yes, size/M

#27463 [release-1.7] fix error service name in Cleanup
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#27528 [1.6] Stop creating invalid double wildcard domains (#27362)
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: cla: yes, size/M

#27699 [Test Framework] Fixes, cleanup, and logging for kubeconfig logic
  pkg/test/framework/components/environment/kube/flags.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#27436 [release-1.7] Manual cherry-pick of "istioctl fallback to 'exec'"
  pkg/kube/client.go
  releasenotes/notes/27421.yaml
Labels: cla: yes, size/M

#27683 Optimize docker building
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_7
  pkg/test/framework/components/echo/kube/deployment.go
  prow/lib.sh
  tools/build-base-images.sh
  tools/buildx-gen.sh
  tools/istio-docker.mk
  tools/skip-image.sh
Labels: cla: yes, release-notes-none, size/M

#27522 [release-1.7] Stop creating invalid double wildcard domains
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/double-wildcard.yaml
Labels: cla: yes, release-notes-none, size/M

#27702 [Test Framework] Correct logging for the kubeconfig being used.
  pkg/test/framework/components/environment/kube/flags.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#27536 cherrypick 27502
  manifests/charts/istio-operator/templates/clusterrole.yaml
Labels: area/environments, cla: yes, release-notes-none, size/XS

#27640 Add multicluster support for Gateway SDS
  pilot/pkg/bootstrap/server.go
  pilot/pkg/secrets/kube/multicluster.go
  pilot/pkg/secrets/kube/secrets.go
  pilot/pkg/secrets/kube/secrets_test.go
  pilot/pkg/secrets/model.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
Labels: cla: yes, release-notes-none, size/L

#27537 cherrypick 26456 to release-1.7
  operator/ARCHITECTURE.md
  operator/README.md
  operator/cmd/mesh/testdata/manifest-generate/input/ingressgateway_k8s_settings.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ingressgateway_k8s_settings.golden.yaml
  operator/pkg/translate/translate.go
  releasenotes/notes/add-pod-securitycontext.yaml
Labels: area/environments, cla: yes, size/S

#27705 Speed up unit tests dramatically by better waiting
  pkg/kube/client.go
Labels: cla: yes, release-notes-none, size/XS

#27596 [release-1.7] Update istio logo for grafana istio-mesh-dashboard
  manifests/charts/istio-telemetry/grafana/dashboards/istio-mesh-dashboard.json
  samples/addons/grafana.yaml
Labels: cla: yes, release-notes-none, size/XS

#27708 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27703 remove the old version of token verification
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: area/security, cla: yes, release-notes-none, size/M

#27710 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27687 make xds send timeout configurable
  pilot/pkg/features/pilot.go
  pilot/pkg/xds/ads.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#27714 Speed up registry tests
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: cla: yes, release-notes-none, size/M

#27715 slow down retries to allow for delayed_close_timeout
  tests/integration/pilot/common/traffic.go
Labels: cla: yes, release-notes-none, size/XS

#27658 Properly update instancesByPort and test
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
Labels: cla: yes, release-notes-none, size/L

#27722 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27588 Fix benchmark leak
  pilot/pkg/xds/fake.go
Labels: cla: yes, release-notes-none, size/XS

#27667 Always treat Envoy routes as v3, even if Envoy doesn't
  istioctl/pkg/util/configdump/listener.go
  istioctl/pkg/util/configdump/route.go
Labels: cla: yes, release-notes-none, size/S

#27733 Automator: update common-files@release-1.6 in istio/istio@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#27736 Automator: update istio/api@release-1.6 dependency in istio/istio@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#27721 reset the metrics value before the test
  security/pkg/nodeagent/sds/monitoring.go
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#27627 Add dedicated section to issue templates for crashes
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla: yes, release-notes-none, size/XS

#27739 long log on shifting test failure
  tests/integration/pilot/common/routing.go
Labels: cla: yes, release-notes-none, size/XS

#27742 Automator: update proxy@release-1.7 in istio/istio@release-1.7
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27717 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27604 Add some additional validations
  pilot/test/xdstest/validate.go
Labels: cla: yes, release-notes-none, size/S

#27712 Controller for watching a ConfigMap
  pkg/kube/configmapwatcher/configmapwatcher.go
  pkg/kube/configmapwatcher/configmapwatcher_test.go
Labels: cla: yes, release-notes-none, size/L

#27747 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27748 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27657 remove cacert.pem and use x509.SystemCertPool()
  pilot/docker/Dockerfile.pilot
  pilot/pkg/model/jwks_resolver.go
  pkg/test/echo/client/client.go
  pkg/test/echo/common/model.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/testdata/certs/cacert.pem
  tools/istio-docker.mk
Labels: area/security, auto-merge, cherrypick/release-1.6, cherrypick/release-1.7, cherrypick/release-1.8, cla: yes, release-notes-none, size/XXL

#27731 Fix kube controller test flakes.
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
Labels: cla: yes, release-notes-none, size/L

#27752 List watched resources in adsz
  pilot/pkg/xds/debug.go
Labels: cla: yes, release-notes-none, size/S

#27754 Update SHAs to pick up Envoy CVE and spanKind
  istio.deps
Labels: cla: yes, size/XS

#27724 Setup ConfigStore in xDS
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/clusterrole.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/xds/internalgen.go
Labels: cla: yes, release-notes-none, size/S

#27763 [release-1.7] Use istiod label selector
  pilot/tools/debug/pilot_cli.go
  pkg/kube/client.go
  pkg/test/framework/components/istio/operator.go
  releasenotes/notes/fix-istioctl-version-revisioned-istiod.yaml
Labels: cla: yes, size/S

#27750 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27572 remove deprecated outboundTrafficPolicy from global values.
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/translate/testdata/icp-iop/input/default.yaml
  operator/pkg/translate/testdata/icp-iop/output/default.yaml
  releasenotes/notes/27494.yaml
Labels: cla: yes, size/S

#27503 Update description for istioctl main commands
  operator/cmd/mesh/install.go
  operator/cmd/mesh/manifest.go
  operator/cmd/mesh/operator.go
  operator/cmd/mesh/profile.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#27118 Add instruction for local build if the compiled in charts are not found
  operator/cmd/mesh/operator-dump.go
  operator/cmd/mesh/operator-init.go
  operator/pkg/helm/vfs_renderer.go
Labels: area/environments/operator, area/user experience, cla: yes, kind/istioctl, release-notes-none, size/M

#27778 Add validation warnings to webhook
  pkg/kube/adapter.go
  pkg/webhooks/validation/server/server.go
  releasenotes/notes/validation-warning.yaml
Labels: cla: yes, size/M

#27264 Update deprecated config to typed config in istio-multicluster-ingressgateway EnvoyFilter template
  manifests/charts/gateways/istio-ingress/templates/preconfigured.yaml
Labels: area/environments, cla: yes, ok-to-test, release-notes-none, size/XS

#27762 [release-1.7] Remove release label in PodDisruptionBudget for egress gateway
  manifests/charts/gateways/istio-egress/templates/poddisruptionbudget.yaml
  releasenotes/notes/27730.yaml
Labels: cla: yes, size/S

#27305 security: Fix comment about PKCS version.
  security/pkg/pki/util/crypto.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#27497 Add label test
  operator/pkg/util/label_test.go
Labels: cla: yes, ok-to-test, release-notes-none, size/M

#27602 Test Kubernetes 1.15 in CI
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/kube/mock_client.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/main_test.go
  tests/integration/pilot/testdata/authz-b.yaml
Labels: cla: yes, release-notes-none, size/M

#27774 eastwest sample script generates operator yaml
  pkg/test/framework/components/istio/eastwest.go
  pkg/test/framework/components/istio/operator.go
  samples/multicluster/gen-eastwest-gateway.sh
Labels: cla: yes, release-notes-none, size/M

#27760 Add NewConfigMapWatcher for mesh config
  pkg/config/mesh/watcher.go
  pkg/config/mesh/watcher_test.go
  pkg/kube/configmapwatcher/configmapwatcher.go
  pkg/kube/configmapwatcher/configmapwatcher_test.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#27812 Bump 1.6 base image
  Makefile.core.mk
Labels: cla: yes, size/XS

#27798 make sure concatenated certs are separated by new lines
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: area/security, cla: yes, ok-to-test, release-notes-none, size/M

#27785 Add label to samples Service to allow deploying separately
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-discovery.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/health-check/liveness-command.yaml
  samples/health-check/liveness-http-same-port.yaml
  samples/helloworld/helloworld.yaml
  samples/httpbin/httpbin-nodeport.yaml
  samples/httpbin/httpbin-vault.yaml
  samples/httpbin/httpbin.yaml
  samples/httpbin/sample-client/fortio-deploy.yaml
  samples/https/nginx-app.yaml
  samples/kubernetes-blog/bookinfo-ratings.yaml
  samples/kubernetes-blog/bookinfo-v1.yaml
  samples/sleep/sleep-vault.yaml
  samples/sleep/sleep.yaml
  samples/tcp-echo/tcp-echo-services.yaml
  samples/tcp-echo/tcp-echo.yaml
  samples/websockets/app.yaml
Labels: cla: yes, kind/docs, release-notes-none, size/S

#27775 Disable SNI-DNAT (AUTO_PASSTHROUGH) clusters by default
  manifests/profiles/default.yaml
  releasenotes/notes/sni-dnat-default.yaml
  samples/multicluster/gen-eastwest-gateway.sh
Labels: cla: yes, size/M

#27789 Fix SDS connection metrics
  security/pkg/nodeagent/sds/sdsservice.go
Labels: cla: yes, release-notes-none, size/XS

#27766 [release-1.6]Cherry-pick: remove cacert.pem and use x509.SystemCertPool()
  pilot/docker/Dockerfile.pilot
  pilot/pkg/model/jwks_resolver.go
  pkg/test/echo/client/client.go
  pkg/test/echo/common/model.go
  releasenotes/notes/27574.yaml
  tests/integration/mixer/outboundtrafficpolicy/helper.go
  tests/testdata/certs/cacert.pem
  tools/istio-docker.mk
Labels: area/security, cla: yes, size/XXL

#27816 helm: sort crd files by name
  operator/pkg/helm/helm.go
Labels: cla: yes, release-notes-none, size/XS

#27813 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27767 [release-1.7] cherry pick: remove cacert.pem and use x509.SystemCertPool() (#27657)
  pilot/docker/Dockerfile.pilot
  pilot/pkg/model/jwks_resolver.go
  pkg/test/echo/client/client.go
  pkg/test/echo/common/model.go
  releasenotes/notes/27574.yaml
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/testdata/certs/cacert.pem
  tools/istio-docker.mk
Labels: area/security, cla: yes, size/XXL

#27817 [Test] Remove unnecessary custom settings
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/filebased_tls_origination/main_test.go
  tests/integration/security/sds_tls_origination/main_test.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/S

#27820 Add istio-coredns-plugin deprecation
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  releasenotes/notes/agent-dns-capture.yaml
Labels: cla: yes, size/S

#27814 Cleanup pilot metrics
  manifests/addons/dashboards/pilot-dashboard.json
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/monitoring.go
  pilot/pkg/xds/v3/model.go
Labels: cla: yes, release-notes-none, size/M

#27694 Remove extraneous logs in test
  pilot/pkg/model/jwks_resolver_test.go
Labels: cla: yes, release-notes-none, size/XS

#27805 Cleanup some legacy flags in istio-agent
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/main_test.go
Labels: cla: yes, release-notes-none, size/M

#27794 Exclude kube system namespaces for istioctl analyze
  galley/pkg/config/analysis/analyzers/util/config.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#27746 Add NR response flag for Gateway 404s
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/gateway-404-nr.yaml
  tests/integration/pilot/common/routing.go
Labels: cla: yes, size/M

#27793 Use Info instead of Warn for istioctl analyzer istio injection
  galley/pkg/config/analysis/analyzers/injection/injection.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/user experience, cla: yes, release-notes-none, size/S

#27753 Fix updates to -cacert Secrets for Istiod SDS
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
Labels: cla: yes, release-notes-none, size/L

#27781 Add warnings to `istioctl validate`
  istioctl/pkg/validate/validate.go
  istioctl/pkg/validate/validate_test.go
Labels: cla: yes, release-notes-none, size/L

#27716 Add revision and version info to bug-report
  go.sum
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/common/common.go
Labels: cla: yes, release-notes-none, size/M

#27833 [Testing] Enable egress for all tests.
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/multicluster/centralremotekubeconfig/main_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/main_test.go
  tests/integration/security/sds_tls_origination/main_test.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#27821 Add support for custom headers in the agent proxy
  pilot/cmd/pilot-agent/main.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/M

#27843 fix broken links in operator doc.
  operator/README.md
Labels: area/environments, cla: yes, kind/docs, release-notes-none, size/S

#27603 Handle EndpointSlice duplications
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/fake.go
Labels: cla: yes, release-notes-none, size/L

#27846 istioctl analyze: do not error if the threshold is warning
  istioctl/cmd/analyze.go
  istioctl/cmd/analyze_test.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#27852 [Testing] Enable all ports on ingress by default
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/multicluster/centralistio/main_test.go
  tests/integration/pilot/main_test.go
  tests/integration/telemetry/main_test.go
Labels: cla: yes, release-notes-none, size/L

#27049 configure cross-network gateway with labels
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/mesh_network_test.go
  pilot/pkg/xds/xds_test.go
  pkg/test/framework/components/istio/operator.go
  releasenotes/notes/27049.yaml
  samples/multicluster/gen-eastwest-gateway.sh
Labels: cla: yes, size/XXL

#27854 [Testing] Add retry support to echo component
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/kube/instance.go
  tests/integration/multicluster/helper.go
  tests/integration/multicluster/loadbalancing.go
  tests/integration/multicluster/telemetry.go
  tests/integration/operator/switch_cr_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#27856 [Testing] Add flags to control default echo call retry
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/flags.go
  pkg/test/framework/initstatics.go
  tests/integration/multicluster/helper.go
  tests/integration/operator/switch_cr_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#27860 [Testing] Cleanup echo retry
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/common/envoy_test.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/flags.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/ingress/interface.go
  tests/integration/multicluster/helper.go
  tests/integration/operator/switch_cr_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#27866 Fix broken link in README.md
  README.md
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#27883 fix virtual service delegate validation
  pkg/config/validation/validation.go
  pkg/config/validation/virtualservice_test.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#27880 remove unused path param from istiod-remote
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/mutatingwebhook.yaml
Labels: cla: yes, release-notes-none, size/S

#27864 Cache the http client in order to reuse the connection
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  releasenotes/notes/27726.yaml
Labels: area/networking, cla: yes, release-notes-none, size/M

#27882 record xds send time
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/monitoring.go
  releasenotes/notes/send-stat.yaml
Labels: cla: yes, size/S

#27885 Move configure logs to PersistentPreRun
  istioctl/cmd/root.go
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
Labels: area/user experience, cla: yes, release-notes-none, size/M

#27878 Added missing default values to enable Helm3
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
Labels: cla: yes, release-notes-none, size/S

#27891 Update depedency for release builder
  prow/release-commit.sh
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#27890 Automator: update common-files@release-1.7 in istio/istio@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27159 Add IO shortname for istio operator
  manifests/charts/base/crds/crd-operator.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  releasenotes/notes/27159.yaml
Labels: cla: yes, size/S

#27836 support PATCH in crdclient
  go.mod
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
  pilot/pkg/config/kube/crdclient/gen/types.go.tmpl
  pilot/pkg/config/kube/crdclient/types.gen.go
Labels: cla: yes, release-notes-none, size/M

#27825 Watch mesh configuration ConfigMap
  pilot/pkg/bootstrap/mesh.go
  pilot/pkg/bootstrap/server.go
  pkg/config/mesh/watcher.go
  pkg/config/mesh/watcher_test.go
  pkg/kube/configmapwatcher/configmapwatcher.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#27898 [release-1.7] Do not spam logs/requests when webhook config is missing
  pkg/webhooks/validation/controller/controller.go
Labels: cla: yes, release-notes-none, size/XS

#27115 rename `centralIstiod` flag
  manifests/charts/base/templates/clusterrole.yaml
  manifests/charts/global.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/configmap.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/clusterrole.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/global.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/istiod_remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/install_package_path.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  releasenotes/notes/27115.yaml
  tests/integration/multicluster/centralistio/main_test.go
Labels: cla: yes, size/L

#27894 locks around extractGatewaysFromService calls
  pilot/pkg/serviceregistry/kube/controller/network.go
Labels: cla: yes, release-notes-none, size/S

#27802 Enable ADS proxy by default
  manifests/profiles/preview.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/model/context.go
  pkg/test/framework/components/echo/kube/deployment.go
  releasenotes/notes/agent-xds-proxy.yaml
  tests/integration/iop-integration-test-defaults.yaml
Labels: cla: yes, size/S

#27881 Reuse the upstream connection
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/M

#27902 Fix format on test log statement
  pkg/test/framework/components/istio/eastwest.go
Labels: cla: yes, release-notes-none, size/XS

#27614 specify default service account for create-remote-secret for config type
  istioctl/pkg/multicluster/apply_test.go
  istioctl/pkg/multicluster/cluster.go
  istioctl/pkg/multicluster/cluster_test.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  pkg/config/constants/constants.go
  pkg/test/framework/components/istio/operator.go
Labels: cla: yes, release-notes-none, size/M

#27895 Allow localhost XDS address
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/XS

#27876 Regen addons
  manifests/addons/dashboards/istio-performance-dashboard.json
  manifests/addons/dashboards/pilot-dashboard.json
  manifests/addons/gen.sh
  samples/addons/grafana.yaml
  tests/integration/telemetry/dashboard_test.go
Labels: cla: yes, release-notes-none, size/XXL

#27871 [Testing] Refactor pilot traffic tests
  pkg/test/echo/client/parsedresponse.go
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/ingress/interface.go
  pkg/test/framework/components/istio/operator.go
  tests/integration/multicluster/cluster_local.go
  tests/integration/multicluster/helper.go
  tests/integration/multicluster/loadbalancing.go
  tests/integration/multicluster/reachability.go
  tests/integration/multicluster/telemetry.go
  tests/integration/operator/switch_cr_test.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/endpointslice/endpointslice_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/locality_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/routing_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/sds_ingress/ingress_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/sds_tls_origination/util/util.go
  tests/integration/security/util/authn/authn_util.go
  tests/integration/telemetry/dashboard_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XXL

#27744 Enable istiod SDS by default
  pilot/pkg/features/pilot.go
  releasenotes/notes/istiod-sds.yaml
  tests/integration/security/sds_ingress_gateway/ingress_test.go
Labels: cla: yes, release-notes-none, size/S

#27892 Automator: update istio/api@release-1.7 dependency in istio/istio@release-1.7
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#27858 Require approval from Environments leads for any values.yaml changes
  CODEOWNERS
Labels: cla: yes, release-notes-none, size/XS

#27920 xdsproxy: add tests for reconnect
  pilot/pkg/xds/fake.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_test.go
Labels: cla: yes, release-notes-none, size/L

#27905 Add tests for health probers
  pkg/istio-agent/health/health_probers_test.go
Labels: area/test and release, cla: yes, ok-to-test, release-notes-none, size/L

#27897 xds proxy: support plaintext communications
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/S

#27937 [Testing] Remove a few more custom configurations
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/analysis/main_test.go
  tests/integration/pilot/analysis_test.go
  tests/integration/security/sds_egress/main_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#27823 Add cluster metadata for telemetry
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: cla: yes, release-notes-none, size/XL

#27952 [Testing] Reverting move of pilot analysis_test.go
  tests/integration/pilot/analysis/analysis_test.go
  tests/integration/pilot/analysis/main_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#27949 Update readme for east-west gateway.
  samples/multicluster/README.md
Labels: cla: yes, kind/docs, release-notes-none, size/XS

#27926 Refactor file watching for injection
  pkg/kube/inject/watcher.go
  pkg/kube/inject/webhook.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#27961 Dump previous pod logs for crash in test
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/S

#27806 Deprecate values.yaml trustDomain setting
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istiod-remote/templates/configmap.yaml
  manifests/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
Labels: cla: yes, release-notes-none, size/XS

#27955 [Testing] Removing more custom settings
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/main_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#27780 Add metrics for istio-agent startup time
  pilot/cmd/pilot-agent/metrics/metrics.go
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/cmd/pilot-agent/status/server.go
  releasenotes/notes/agent-startup.yaml
Labels: cla: yes, size/M

#27964 Fix crash on bad NACK
  pilot/pkg/xds/internalgen.go
Labels: cla: yes, release-notes-none, size/XS

#27965 Add timeout for dial
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/XS

#27972 move gatewayPort annotation to networking.istio.io
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: cla: yes, release-notes-none, size/XS

#27963 Remove unused/wrong expiry on token
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/XS

#27962 bump istio api
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  pkg/config/schema/fuzz_test.go
Labels: cla: yes, release-notes-none, size/M

#27936 Merge validate httproute
  pkg/config/validation/validation.go
  pkg/config/validation/virtualservice.go
  pkg/config/validation/virtualservice_test.go
Labels: cla: yes, release-notes-none, size/L

#27975 align mutatingwebhook.yaml in istiod-remote with istiod-discovery
  Makefile.core.mk
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
Labels: cla: yes, release-notes-none, size/S

#27815 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#27408 rework on ads client
  istioctl/pkg/xds/client.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/networking/apigen/apigen_test.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/lds_test.go
  pkg/adsc/adsc.go
  pkg/adsc/adsc_test.go
  pkg/istio-agent/local_xds_generator.go
Labels: cla: yes, release-notes-none, size/L

#27933 [release-1.7] Fix logging in operator
  operator/cmd/mesh/manifest-generate.go
Labels: cla: yes, release-notes-none, size/XS

#27966 Add injection ConfigMap watcher
  pkg/kube/inject/watcher.go
  pkg/kube/inject/watcher_test.go
  pkg/kube/inject/webhook.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#28002 Add reflection server to echo
  pkg/test/echo/server/endpoint/grpc.go
Labels: cla: yes, release-notes-none, size/XS

#27857 Add missing metrics (vs,dr,gw) into Mesh Dashboard
  manifests/addons/dashboards/istio-mesh-dashboard.json
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/addons/dashboards/istio-mesh-dashboard.json
  samples/addons/grafana.yaml
Labels: cla: yes, release-notes-none, size/S

#27998 Revert enabling analysis by default
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/analysis/main_test.go
Labels: cla: yes, release-notes-none, size/S
