Repository istio/istio, pull requests merged in 2020-06, with the labels that each got.

#24248 [release-1.6] sds: handle file mounted certs use case in sds agent
  pkg/istio-agent/sds-agent.go
  pkg/istio-agent/sds-agent_test.go
Labels: area/security, cla: yes, size/M

#24237 CORS Policy TestData: Change to allowOrigins block
  tests/testdata/config/rule-default-route-cors-policy.yaml
Labels: area/networking, area/security, area/test and release, cla: yes, ok-to-test, size/XS

#24240 eds: only call functions when needed
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: area/networking, cla: yes, size/S

#24253 [release-1.6] sds: skip reading jwt token for file mounted certs
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server.go
Labels: cla: yes, size/M

#24254 [release-1.6] sds: skip waiting for ingress gateway secret for file mounted certs
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server.go
Labels: cla: yes, size/M

#24261 Modify CODEOWNERS with micro review optimizations
  CODEOWNERS
Labels: cla: yes, size/XS

#24268 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24247 [release-1.6] Fix incorrect ServiceAccount used in custom IngressGateway Deployment
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
Labels: cla: yes, size/XS

#24205 Clean up Make for deprecated files to remove
  .gitignore
  Makefile.core.mk
Labels: cla: yes, size/M

#24267 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#24274 Fix TCP over HTTP conflicts causing invalid configs (#24131)
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/M

#24124 Support v2 and v3 XDS transport protocols
  pilot/pkg/proxy/envoy/v2/adapter.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/discovery_test.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/gen2.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/proxy/envoy/v2/internalgen.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: cla: yes, size/L

#24256 ads: remove file writes in tests
  pilot/pkg/proxy/envoy/v2/ads_test.go
Labels: cla: yes, size/S

#24184 Document TestSingleTlsGateway_SecretRotation function in the SDS Ingress Test Suite
  tests/integration/security/sds_ingress/ingress_test.go
Labels: area/security, cla: yes, kind/docs, ok-to-test, size/XS

#24273 [release-1.6] cherry pick use external name when remote pilot addr is hostname #24219
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/endpoints.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/services.yaml
Labels: area/environments, cla: yes, size/S

#24211 Fix cleanup and change readiness check for tests
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/kube/accessor.go
Labels: cla: yes, size/M

#23355 Cleanup dead and deprecated options
  manifests/charts/base/templates/services.yaml
  manifests/charts/global.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istio-telemetry/mixer-telemetry/values.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/profiles/default.yaml
  manifests/profiles/minimal.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/UPDATING-CHARTS.md
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/clusterrole.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/services.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/global.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-cni/templates/daemonset.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/configmap.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/mixer-telemetry/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/minimal.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/bogus_cps.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_merge_meshconfig.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/cmd/mesh/testdata/profile-dump/output/config_path.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/helm/helm.go
  operator/pkg/translate/testdata/icp-iop/input/default.yaml
  operator/pkg/validate/validate_values_test.go
  pkg/test/framework/components/bookinfo/configs.go
  pkg/test/framework/components/istio/config.go
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/mixer/main_test.go
  tests/integration/mixer/policy/ratelimiting_test.go
  tests/integration/mixer/telemetry/logs/accesslog_test.go
  tests/integration/mixer/telemetry/metrics/scenarios_test.go
  tests/integration/pilot/analysis/main_test.go
  tests/integration/security/chiron/main_test.go
  tests/integration/security/mtls_first_party_jwt/main_test.go
  tests/integration/security/mtlsk8sca/main_test.go
  tests/integration/security/webhook/webhook_test.go
  tests/integration/telemetry/main_test.go
  tests/integration/telemetry/tracing/clienttracing/client_tracing_test.go
  tests/integration/telemetry/tracing/servertracing/tracing_test.go
Labels: cla: yes, size/XXL

#24121 Remove chiron binary
  security/cmd/chiron/main.go
Labels: cla: yes, size/L

#24279 Cleanup duplicate namespace metadata
  manifests/profiles/demo.yaml
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/networking_test.go
  pilot/pkg/proxy/envoy/v2/bench_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pkg/bootstrap/config.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  tests/integration/pilot/meshnetwork/main_test.go
Labels: cla: yes, size/M

#24272 Improve referential integrity tests for manifests
  operator/cmd/mesh/manifest-generate_test.go
Labels: cherrypick/release-1.6, cla: yes, size/L

#24218 [release-1.5] Update cni sha for release-1.5 branch
  istio.deps
Labels: cla: yes, size/XS

#24252 Backport #24242 to release-1.5 - Fix incorrect ServiceAccount used in custom IngressGateway Deployment
  manifests/gateways/istio-egress/templates/deployment.yaml
  manifests/gateways/istio-ingress/templates/deployment.yaml
  operator/pkg/vfs/assets.gen.go
Labels: area/environments, cla: yes, flag/needs-release-note, size/XS

#24326 xds: second round of import consistency
  pilot/pkg/networking/core/v1alpha3/filters.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/thriftroute.go
Labels: area/networking, cla: yes, size/L

#24298 Allow nodeport discovery address
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/istio/util.go
Labels: cla: yes, size/M

#24312 Update validation webhook package to use monitoring package
  pkg/webhooks/validation/server/monitoring.go
Labels: cla: yes, size/L

#23504 Respect HTTPHeader in app prober
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
Labels: cla: yes, size/L

#24334 Backfill feature tag to all telemetry tests
  pkg/test/framework/features/features.yaml
  tests/integration/telemetry/dashboard_test.go
  tests/integration/telemetry/requestclassification/requestclassification_test.go
  tests/integration/telemetry/stats/prometheus/http/nullvm/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/http/rewrite/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/http/stats.go
  tests/integration/telemetry/stats/prometheus/http/wasm/stats_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/tcp/stats_tcp_filter_test.go
  tests/integration/telemetry/tracing/clienttracing/client_tracing_test.go
  tests/integration/telemetry/tracing/servertracing/tracing_test.go
Labels: cla: yes, size/M

#24314 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24342 minor doc fixes in sidecar injection metrics
  pkg/kube/inject/inject.go
  pkg/kube/inject/monitoring.go
Labels: area/policies and telemetry, cla: yes, size/S

#24347 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24225 Initial client auth for XDS
  pilot/pkg/features/pilot.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: area/networking, area/security, cla: yes, size/M

#24277 Fix QuotaSpecBinding Crash
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
  pkg/test/env/istio.go
  pkg/test/framework/components/redis/service_account.yaml
  tests/integration/mixer/policy/ratelimiting_test.go
Labels: area/policies and telemetry, cherrypick/release-1.6, cla: yes, size/L

#24141 fix typo
  README.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#24343 Move cert generation tooling to /tools
  tools/certs/Makefile
  tools/certs/README.md
Labels: area/security, cherrypick/release-1.6, cla: yes, size/XS

#24362 [release-1.6] Move cert generation tooling to /tools
  tools/certs/Makefile
  tools/certs/README.md
Labels: cla: yes, size/XS

#24352 Skip using gateways with hostnames in split horizon
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
Labels: cla: yes, size/L

#24355 Use v3 filters in bootstrap
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/L

#24341 Fix race condition in adsc
  pkg/adsc/adsc.go
Labels: cla: yes, size/XS

#24378 Skip whitelist test
  tests/integration/mixer/policy/white_black_listing_test.go
Labels: cla: yes, size/XS

#24304 Update jquery and nodejs
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/productpage/static/jquery.min.js
  samples/bookinfo/src/ratings/Dockerfile
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cherrypick/release-1.6, cla: yes, size/M

#24389 Cleanup legacy USER_SDS metadata config
  manifests/charts/istio-policy/templates/deployment.yaml
  manifests/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-policy/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/telemetry_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.golden.yaml
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: area/networking, area/security, cla: yes, size/S

#24340 Cleanup envoy download code
  pkg/test/deps/istio.go
  pkg/test/envoy/download.go
  pkg/test/framework/components/echo/docker/workload.go
Labels: cla: yes, size/L

#24297 Allow XDS v2/v3 for status distribution
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eventhandler.go
  pilot/pkg/status/reporter.go
  pilot/pkg/status/reporter_test.go
Labels: cla: yes, size/L

#24384 Remove dead probe code
  security/pkg/cmd/probe.go
  security/pkg/cmd/probe_test.go
Labels: cla: yes, size/M

#24402 Update jquery and nodejs
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/productpage/static/jquery.min.js
  samples/bookinfo/src/ratings/Dockerfile
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, size/M

#24151 Use new prometheus deployment in test framework
  manifests/addons/values-prometheus.yaml
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/components/prometheus/prometheus.go
  samples/addons/kiali.yaml
  samples/addons/prometheus.yaml
  tests/integration/mixer/main_test.go
  tests/integration/mixer/outboundtrafficpolicy/traffic_test.go
  tests/integration/mixer/outboundtrafficpolicy/v2/traffic_test.go
  tests/integration/mixer/policy/ratelimiting_test.go
  tests/integration/mixer/telemetry/metrics/scenarios_test.go
  tests/integration/security/cert_provision_prometheus/cert_provision_prometheus_test.go
  tests/integration/security/sds_egress/main_test.go
  tests/integration/telemetry/main_test.go
  tests/integration/telemetry/stats/prometheus/http/nullvm/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/http/rewrite/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/http/stats.go
  tests/integration/telemetry/stats/prometheus/http/wasm/stats_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/tcp/stats_tcp_filter_test.go
Labels: cla: yes, size/L

#24386 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24407 [release-1.4] Update jquery and nodejs
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/productpage/static/jquery.min.js
  samples/bookinfo/src/ratings/Dockerfile
Labels: cla: yes, size/M

#24404 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#24408 [1.5] update proxy SHA
  istio.deps
Labels: cla: yes, size/XS

#24412 Probe rewrite fails if path does not start with "/"
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
Labels: area/config, cla: yes, ok-to-test, size/M

#24417 Fix ratelimit test
  tests/integration/mixer/policy/ratelimiting_test.go
Labels: area/policies and telemetry, cla: yes, size/XS

#24409 Remove whitelist test
  tests/integration/mixer/policy/white_black_listing_test.go
Labels: area/policies and telemetry, cla: yes, size/M

#24418 Galley: remove callout code
  galley/pkg/authplugin/authplugin.go
  galley/pkg/authplugins/README.md
  galley/pkg/authplugins/google/google.go
  galley/pkg/authplugins/google/google_test.go
  galley/pkg/authplugins/inventory.go
  galley/pkg/authplugins/inventory_test.go
  galley/pkg/authplugins/none/none.go
  galley/pkg/authplugins/none/none_test.go
  galley/pkg/server/components/callout.go
  galley/pkg/server/components/callout_test.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/components/processing_test.go
  galley/pkg/server/settings/args.go
Labels: cla: yes, size/XL

#24406 [release-1.5] Update jquery and nodejs
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/productpage/static/jquery.min.js
  samples/bookinfo/src/ratings/Dockerfile
Labels: cla: yes, size/M

#24428 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#24427 Fix some minor issues related to leader election
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/leaderelection/leaderelection.go
  pkg/webhooks/validation/controller/controller.go
Labels: area/networking, cla: yes, size/M

#24166 Test VM workloads in integration tests
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/test/echo/docker/Dockerfile.app_sidecar
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/kube/accessor.go
  prow/lib.sh
  tests/integration/pilot/vm/vm_test.go
  tools/packaging/common/istio-start.sh
  tools/packaging/common/sidecar.env
Labels: cla: yes, size/L

#24321 Fix metrics error rps stats incorrect
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
Labels: cla: yes, size/XS

#24361 Remove health plugin and management cluster
  mixer/test/client/gateway/gateway_test.go
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_service_discovery.gen.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/plugin/health/health.go
  pilot/pkg/networking/plugin/health/health_test.go
  pilot/pkg/networking/plugin/registry/registry.go
  pilot/pkg/networking/plugin/registry/registry_test.go
  pilot/pkg/proxy/envoy/v2/ads_common.go
  pilot/pkg/proxy/envoy/v2/ads_common_test.go
  pilot/pkg/proxy/envoy/v2/mem.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/consul/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Labels: cla: yes, size/XXL

#24372 create-remote-secret silently fails for integration tests
  istioctl/pkg/multicluster/remote_secret.go
Labels: area/test and release, cla: yes, size/XS

#24399 Bump Kubernetes client libraries
  go.mod
  go.sum
  pilot/pkg/leaderelection/leaderelection.go
Labels: cla: yes, size/M

#24400 Remove references to galley for ApplyConfigOrFail
  tests/integration/README.md
Labels: area/test and release, cla: yes, size/S

#24415 Apply proxyMetadata to Prometheus sidecar.
  manifests/charts/global.yaml
  manifests/charts/istio-telemetry/prometheus/templates/deployment.yaml
  manifests/profiles/default.yaml
Labels: area/environments, area/policies and telemetry, cherrypick/release-1.6, cla: yes, size/XS

#24431 Cleanup dead galley code
  galley/pkg/config/processor/transforms/ingress/common.go
  galley/pkg/config/processor/transforms/ingress/create.go
  galley/pkg/config/processor/transforms/ingress/dataset_test.go
  galley/pkg/config/processor/transforms/ingress/gateway.go
  galley/pkg/config/processor/transforms/ingress/gateway_test.go
  galley/pkg/config/processor/transforms/ingress/syntheticVirtualService.go
  galley/pkg/config/processor/transforms/ingress/virtualService.go
  galley/pkg/config/processor/transforms/ingress/virtualService_test.go
  galley/pkg/config/processor/transforms/transforms.go
  galley/pkg/config/source/kube/fs/source.go
  galley/pkg/config/source/kube/fs/source_test.go
  galley/pkg/config/synthesize/version.go
  galley/pkg/config/synthesize/version_test.go
  galley/pkg/envvar/envvars.go
  galley/pkg/meshconfig/cache.go
  galley/pkg/meshconfig/cache_test.go
  galley/pkg/meshconfig/testdata/meshconfig.json
  galley/pkg/server/components/configmap.go
  galley/pkg/server/components/configmap_test.go
  galley/pkg/server/components/patchtable.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/components/processing_test.go
  galley/pkg/server/components/scope.go
  galley/pkg/server/settings/args.go
  galley/pkg/server/settings/args_test.go
  pilot/pkg/bootstrap/configcontroller.go
Labels: cla: yes, size/XXL

#24365 add imagePullSecrets to sidecar injection template
  manifests/charts/global.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-image-pull-secret.yaml
  pkg/kube/inject/testdata/inject/hello-image-secrets-in-values-iop.yaml
  pkg/kube/inject/testdata/inject/hello-image-secrets-in-values.yaml.injected
  pkg/kube/inject/testdata/inject/hello-multiple-image-secrets.yaml.injected
Labels: area/config, area/environments, area/user experience, cherrypick/release-1.6, cla: yes, size/XL

#24395 Stop creating inbound filter chain per IP
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
Labels: cla: yes, size/M

#24435 TLS Context Tests
  pkg/bootstrap/option/convert_test.go
Labels: area/networking, area/security, cla: yes, size/L

#24414 Fix XDS client authentication
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: cla: yes, size/M

#24313 skip unit tests and fix flaky test issues for nodeagent(sds) service
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
  security/pkg/nodeagent/test/csr_failure/csr_test.go
  security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
Labels: area/security, cla: yes, ok-to-test, size/S

#24025 Cleanup dead code in metadata
  pilot/pkg/model/context.go
  pilot/pkg/security/model/authentication.go
  pkg/bootstrap/config.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
Labels: cla: yes, size/M

#24311 Add help message to makefile
  Makefile.core.mk
Labels: cla: yes, size/S

#24288 Switch to actually request/use XDS v3
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/rds.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/L

#24446 add imagePullSecrets to sidecar injection template
  manifests/charts/global.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-image-pull-secret.yaml
  pkg/kube/inject/testdata/inject/hello-image-secrets-in-values-iop.yaml
  pkg/kube/inject/testdata/inject/hello-image-secrets-in-values.yaml.injected
  pkg/kube/inject/testdata/inject/hello-multiple-image-secrets.yaml.injected
Labels: area/config, area/environments, area/user experience, cla: yes, size/XL

#24448 Fix #24291
  operator/pkg/util/path.go
  operator/pkg/util/path_test.go
Labels: area/config, cla: yes, size/M

#24317 [release-1.6] Improve referential integrity tests for manifests
  operator/cmd/mesh/manifest-generate_test.go
Labels: cla: yes, size/L

#24380 [cherrypick] Skip using gateways with hostnames in split horizon (#24352)
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/proxy/envoy/v2/ep_filters_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
Labels: cla: yes, size/L

#24359 [release-1.6] Fix QuotaSpecBinding Crash
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/plugin/mixer/mixer.go
  pilot/pkg/networking/plugin/mixer/mixer_test.go
  pkg/test/env/istio.go
  pkg/test/framework/components/redis/service_account.yaml
  tests/integration/mixer/policy/ratelimiting_test.go
Labels: cla: yes, size/L

#24397 Bump grafana and prometheus versions
  manifests/addons/gen.sh
  manifests/addons/values-grafana.yaml
  manifests/charts/istio-telemetry/grafana/values.yaml
  manifests/charts/istio-telemetry/prometheus/values.yaml
  manifests/profiles/default.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/component_hub_tag.yaml
  samples/addons/grafana.yaml
  samples/addons/kiali.yaml
  samples/addons/prometheus.yaml
Labels: cla: yes, size/M

#24429 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24451 [release-1.6] Fix metrics error rps stats incorrect
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
Labels: cla: yes, size/XS

#24367 enhance fetch-root-ca and do not rely PID as serial number
  tools/certs/Makefile
Labels: cla: yes, size/S

#24468 Manual cherrypick of 23898 to master
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: area/networking, cla: yes, kind/test failure, lifecycle/needs-escalation, size/XS

#24456 cluster: fix comment
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: area/networking, cla: yes, size/XS

#24366 update object cache for watched resources.
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
Labels: area/environments, cherrypick/release-1.6, cla: yes, size/M

#24344 Adsc tests
  pkg/adsc/adsc.go
  pkg/adsc/adsc_test.go
Labels: area/networking, cla: yes, size/L

#24426 Add support for k8s.v1.cni.cncf.io/networks annotation
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-cncf-networks.yaml.injected
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks.yaml
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks.yaml.injected
Labels: area/networking, cla: yes, size/XL

#24454 Fix: Pilot crash when set illegal host in sidecar resource
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
Labels: area/networking, cla: yes, ok-to-test, size/M

#24486 cleanup more imports
  pilot/pkg/model/context.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/platform/aws.go
  pkg/bootstrap/platform/aws_test.go
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/platform.go
Labels: cla: yes, size/M

#24440 Adding support for startup probe.
  pilot/cmd/pilot-agent/status/server.go
  pkg/kube/inject/app_probe.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/app_probe/startup_live.yaml
  pkg/kube/inject/testdata/inject/app_probe/startup_live.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/startup_only.yaml
  pkg/kube/inject/testdata/inject/app_probe/startup_only.yaml.injected
  pkg/kube/inject/testdata/inject/app_probe/startup_ready_live.yaml
  pkg/kube/inject/testdata/inject/app_probe/startup_ready_live.yaml.injected
Labels: area/config, cla: yes, ok-to-test, size/XL

#24487 eds: do not update service shards for service entries
  pilot/pkg/proxy/envoy/v2/discovery.go
  pilot/pkg/proxy/envoy/v2/eds.go
Labels: area/networking, cla: yes, size/M

#24492 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#24482 Operator Tests (path)
  operator/pkg/util/path.go
  operator/pkg/util/path_test.go
Labels: area/config, cla: yes, size/L

#24494 eds: move split horizon test to v3
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
Labels: area/networking, cla: yes, size/M

#24495 remove reflect deep equal in endpoint comparison
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: area/networking, cla: yes, size/M

#24493 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24481 [release-1.6] fix incorrect labels for watching resources.
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
Labels: cla: yes, size/M

#24510 [release-1.6] Apply proxyMetadata to Prometheus sidecar
  manifests/charts/global.yaml
  manifests/charts/istio-telemetry/prometheus/templates/deployment.yaml
  manifests/profiles/default.yaml
Labels: area/environments, cla: yes, size/XS

#24403 --output=flags option for 'istioctl profile dump'
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/profile-dump_test.go
  operator/cmd/mesh/testdata/profile-dump/output/all_off.txt
  operator/cmd/mesh/testdata/profile-dump/output/config_path.txt
  operator/pkg/util/path.go
Labels: cla: yes, size/XL

#24506 manifests: fix PodSecurityContext for gateways
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
Labels: cla: yes, size/M

#24509 Deprecate istioctl manifest apply
  operator/cmd/mesh/manifest-apply.go
Labels: cla: yes, size/XS

#24507 remove optional istio-sidecar-injector config map volume in istiod de…
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/install_package_path.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
Labels: area/environments, cla: yes, ok-to-test, size/S

#24518 update istio-operator chart to use helm 3 crds installation method
  manifests/charts/istio-operator/crds/crd-operator.yaml
  manifests/charts/istio-operator/templates/crds.yaml
  manifests/charts/istio-operator/values.yaml
Labels: cla: yes, ok-to-test, size/XS

#24530 Remove extraneous Send failure logs
  pilot/pkg/proxy/envoy/v2/cds.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/gen2.go
  pilot/pkg/proxy/envoy/v2/lds.go
  pilot/pkg/proxy/envoy/v2/monitoring.go
  pilot/pkg/proxy/envoy/v2/rds.go
Labels: cla: yes, size/S

#24529 Fix ledger capacity size
  pilot/pkg/status/reporter.go
Labels: cla: yes, size/XS

#24528 auth: log client for failed authentication
  security/pkg/server/ca/server.go
Labels: cla: yes, size/S

#24536 [release-1.6]update object cache for watched resources.
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
Labels: area/environments, cla: yes, size/M

#24537 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24455 router: dedupe domains across virtual hosts
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: area/networking, cla: yes, size/L

#24346 add feature label for security integration test
  pkg/test/framework/features/features.yaml
  tests/integration/security/chiron/dns_cert_test.go
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlscert_pluginca_securenaming/mtlscert_pluginca_securenaming_test.go
  tests/integration/security/sds_ingress/ingress_test.go
  tests/integration/security/sds_ingress_k8sca/main_test.go
  tests/integration/security/webhook/webhook_test.go
Labels: cla: yes, ok-to-test, size/S

#24550 Allow running Ingress locally
  pilot/pkg/security/model/authentication.go
  pkg/kube/util.go
Labels: cla: yes, size/XS

#24516 More detailed output and sorted output for "istioctl pc listeners"
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/writer/envoy/configdump/listener.go
Labels: cla: yes, size/L

#24556 Derive suite name for test framework
  pkg/test/framework/suite.go
Labels: cla: yes, size/S

#24558 Switch test framework over to samples zipkin
  pkg/test/framework/components/zipkin/kube.go
  tests/integration/telemetry/tracing/clienttracing/client_tracing_test.go
  tests/integration/telemetry/tracing/servertracing/tracing_test.go
Labels: cla: yes, size/M

#24569 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24570 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#24443 support exportTo specific namespaces
  pilot/pkg/model/destination_rule.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/config/visibility/visibility.go
Labels: cla: yes, size/XL

#24293 Support v2 or v3 for SDS
  pilot/pkg/proxy/envoy/v2/adapter.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  security/pkg/nodeagent/sds/adapter.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server_test.go
  security/pkg/testing/sdsc/sdsclient.go
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: cla: yes, size/L

#24566 Cleanup demo profile
  manifests/profiles/demo.yaml
Labels: cla: yes, size/M

#24574 respect targetPort in gateway.meshExpansionPorts.
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/gateways/istio-ingress/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways_override_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ingressgateway_k8s_settings.golden.yaml
Labels: area/config, cla: yes, ok-to-test, size/S

#24560 fix kiali issue on canary upgrade
  manifests/charts/istio-telemetry/kiali/templates/configmap.yaml
  manifests/charts/istio-telemetry/kiali/values.yaml
Labels: cla: yes, ok-to-test, size/XS

#24587 [Test Framework] Accessor cleanup
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/environment/kube/cluster.go
  pkg/test/framework/components/environment/kube/settings.go
  pkg/test/framework/components/ingress/kube.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/istio/util.go
  pkg/test/framework/components/mixer/kube.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/components/pilot/kube.go
  pkg/test/framework/components/policybackend/kube.go
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/components/redis/kube.go
  pkg/test/framework/components/stackdriver/kube.go
  pkg/test/framework/components/zipkin/kube.go
  pkg/test/kube/accessor.go
  pkg/test/kube/deployment.go
  pkg/test/kube/dump.go
  pkg/test/kube/pods.go
  pkg/test/kube/port_forwarder.go
  pkg/test/kube/spdy.go
  tests/integration/galley/namespace_test.go
  tests/integration/galley/webhook_test.go
  tests/integration/operator/switch_cr_test.go
  tests/integration/pilot/cni/cni_test.go
  tests/integration/security/chiron/dns_cert_test.go
  tests/integration/security/mtlscert_pluginca_securenaming/mtlscert_pluginca_securenaming_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/util/cert/cert.go
  tests/integration/telemetry/dashboard_test.go
Labels: cla: yes, size/XL

#24568 Removes panic, and a minor cleanup
  pilot/pkg/config/kube/gateway/conversion.go
Labels: area/networking, cla: yes, size/S

#24533 refactor: move pilot/security test dep out of mixer
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
  pkg/test/env/envoy.go
  pkg/test/env/envoy_conf.go
  pkg/test/env/http_client.go
  pkg/test/env/http_server.go
  pkg/test/env/ports.go
  pkg/test/env/setup.go
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
  security/pkg/nodeagent/test/csr_failure/csr_test.go
  security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/nodeagent/test/success_sds/sds_test.go
  security/pkg/nodeagent/test/testdata/bootstrap.yaml
  security/pkg/stsservice/test/failure_sts_token_fetch/token_failure_test.go
  security/pkg/stsservice/test/proxy_cached_sts_token/proxy_cached_token_test.go
  security/pkg/stsservice/test/renew_sts_token/renew_token_test.go
  security/pkg/stsservice/test/server_cached_short_lived_sts_token/short_lived_cached_token_test.go
  security/pkg/stsservice/test/server_cached_sts_token/server_cached_token_test.go
  security/pkg/stsservice/test/setup.go
  security/pkg/stsservice/test/sts_fetch_timeout/sts_timeout_test.go
  security/pkg/stsservice/test/success_sts/proxy_sts_test.go
  tests/testdata/bootstrap_tmpl.json
Labels: cla: yes, size/XXL

#24593 Add tests & lint
  pilot/pkg/security/trustdomain/util_test.go
Labels: area/security, cla: yes, size/M

#24607 [release-1.6] Sort output formats - unsorted causes churn in html and istio.io PRs
  istioctl/cmd/analyze.go
Labels: cla: yes, size/XS

#24606 xds: rename tests
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
  pilot/pkg/proxy/envoy/v2/rds_test.go
Labels: area/networking, cla: yes, size/L

#24534 [release-1.6] Manual recreated cherrypick of 24477
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-cncf-networks.yaml.injected
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks.yaml
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks.yaml.injected
Labels: cla: yes, size/XL

#24542 [release-1.6] manifests: fix PodSecurityContext for gateways
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
Labels: cla: yes, size/M

#24588 Use xds v3 in more places
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/proxy/envoy/filters/filters.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pkg/test/framework/components/pilot/client.go
  pkg/test/framework/components/pilot/pilot.go
  pkg/test/util/structpath/instance_test.go
  tests/integration/mixer/outboundtrafficpolicy/traffic_allow_any_egressproxy_test.go
  tests/integration/pilot/meshnetwork/main_test.go
  tests/integration/pilot/scope_serviceentry_dns_test.go
  tests/integration/pilot/scope_serviceentry_static_test.go
  tests/integration/pilot/sidecar_api_test.go
Labels: cla: yes, size/L

#24564 Use debian-10 distroless base image
  mixer/docker/Dockerfile.mixer
  mixer/docker/Dockerfile.mixer_codegen
  mixer/docker/Dockerfile.test_policybackend
  mixer/test/listbackend/cmd/Dockerfile
  mixer/test/prometheus/cmd/Dockerfile
  operator/docker/Dockerfile.operator
  pilot/docker/Dockerfile.pilot
  samples/tcp-echo/src/Dockerfile
Labels: area/environments, cla: yes, ok-to-test, size/S

#24608 docs: Update README to reflect current project realities
  README.md
Labels: cla: yes, kind/docs, size/M

#24590 Use proxyMetadata in gateway env (#24381)
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
Labels: cla: yes, size/XS

#24551 add RemoteClusterValues to integ test framework
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/operator.go
Labels: area/test and release, cla: yes, size/M

#24001 Update service-apis dependency
  go.mod
  go.sum
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/clusterrole.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/files/gen-istio-cluster.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/clusterrole.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/mismatch.yaml
  pilot/pkg/config/kube/gateway/testdata/simple.yaml
  pilot/pkg/config/kube/gateway/testdata/simple.yaml.golden
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  tests/integration/galley/validation_test.go
  tests/integration/pilot/ingress/ingress_test.go
  tests/integration/pilot/ingress/testdata/crd.yaml
Labels: cla: yes, size/XXL

#24444 Remove legacy citadel protos
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
  security/proto/ca_service.pb.go
  security/proto/ca_service.proto
  security/proto/ca_service.proto_descriptor
  security/proto/generate.go
  security/proto/workload_service.pb.go
  security/proto/workload_service.proto
  security/proto/workload_service.proto_descriptor
Labels: cla: yes, size/L

#24623 Update istio.deps
  istio.deps
  prow/release-commit.sh
Labels: cla: yes, size/XS

#24567 Deprecate istioctl addons install
  manifests/profiles/default.yaml
  manifests/profiles/demo.yaml
  operator/cmd/mesh/profile-common.go
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
  operator/pkg/tpath/struct.go
Labels: cla: yes, size/L

#24627 xds: move eds tests to v3
  pilot/pkg/proxy/envoy/v2/ads_test.go
  pilot/pkg/proxy/envoy/v2/cds_test.go
  pilot/pkg/proxy/envoy/v2/debug_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/init_test.go
Labels: cla: yes, size/M

#24615 Bump BASE_VERSION
  Makefile.core.mk
Labels: area/test and release, cla: yes, size/XS

#24613 refactor(tests): move telemetry integration tests out of mixer package
  pkg/test/framework/features/features.yaml
  tests/integration/mixer/outboundtrafficpolicy/traffic_allow_any_test.go
  tests/integration/mixer/outboundtrafficpolicy/traffic_registry_only_test.go
  tests/integration/mixer/outboundtrafficpolicy/traffic_test.go
  tests/integration/mixer/telemetry/metrics/istioctl_metrics_test.go
  tests/integration/mixer/telemetry/metrics/scenarios_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_allow_any_test.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_registry_only_test.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go
  tests/integration/telemetry/stats/prometheus/http/stats.go
  tests/integration/telemetry/stats/prometheus/istioctl/istioctl_metrics_test.go
  tests/integration/telemetry/stats/prometheus/util_prometheus.go
Labels: area/policies and telemetry, area/test and release, cla: yes, size/L

#24635 [release-1.6] Bump base
  Makefile.core.mk
Labels: cla: yes, size/XS

#24434 Add token source based on sts token exchange
  security/pkg/stsservice/tokenmanager/google/mock/mockserver.go
  security/pkg/stsservice/tokenmanager/sts_test.go
  security/pkg/stsservice/tokenmanager/tokensource.go
Labels: cla: yes, size/L

#24573 Add gate for feature labels
  pkg/test/framework/features/features.go
  pkg/test/framework/features/whitelist.txt
  pkg/test/framework/test.go
Labels: cla: yes, size/XXL

#24612 add deprecated message for mixer
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
Labels: cla: yes, size/M

#24641 Add test to gateway controller
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/controller_test.go
Labels: area/networking, cla: yes, size/L

#24634 [release-1.5] Bump base
  Makefile.core.mk
Labels: cla: yes, size/XS

#24650 Make istioctl kube client common
  istioctl/cmd/authz.go
  istioctl/cmd/dashboard.go
  istioctl/cmd/dashboard_test.go
  istioctl/cmd/deprecated_cmd.go
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/istioctl_test.go
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/root.go
  istioctl/cmd/sidecar-bootstrap.go
  istioctl/cmd/sidecar-bootstrap_test.go
  istioctl/cmd/version.go
  istioctl/cmd/version_test.go
  istioctl/cmd/wait.go
  istioctl/pkg/kubernetes/client.go
  pkg/kube/client.go
  pkg/kube/portforwarder.go
  pkg/kube/spdy.go
  pkg/kube/util.go
  pkg/test/kube/mock_client.go
Labels: cla: yes, size/XXL

#24656 resolve test that made it in without label
  pkg/test/framework/features/whitelist.txt
Labels: cla: yes, size/XS

#24231 Fix #22804
  operator/cmd/mesh/profile-common_test.go
  operator/cmd/mesh/testdata/profile-dump/input/pilot_plugin_invalid.yaml
  operator/cmd/mesh/testdata/profile-dump/input/pilot_plugin_valid.yaml
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: cla: yes, size/M
