Repository istio/istio, pull requests merged in 2020-01, with the labels that each got.

#19869 change service registry to external for service entries
  pilot/pkg/serviceregistry/external/conversion.go
  pilot/pkg/serviceregistry/external/conversion_test.go
Labels: area/networking, cla: yes, size/XS

#19871 deep clone service instance when sidecar has ingress listeners
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: area/networking, cla: yes, size/L

#19862 Assign /pkg sub-dirs to specific owners
  CODEOWNERS
Labels: cla: yes, size/XS

#19856 remove redundant field sseDiscoveryOptions incrementalSSEDiscoveryOpt…
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/mcp/controller.go
Labels: cla: yes, size/M

#19878 Don't use spew for pilot logs
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/mesh.go
  pkg/config/mesh/networks_watcher.go
Labels: cla: yes, size/S

#19870 Add make target for pushing with buildkit
  tools/buildx-gen.sh
  tools/istio-docker.mk
Labels: cla: yes, size/S

#19752 Add token manager to do token exchange and enable STS server at Pilot-agent
  pilot/cmd/pilot-agent/main.go
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/mockserver.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go
  security/pkg/stsservice/tokenmanager/google/mock/mockserver.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin_test.go
  security/pkg/stsservice/tokenmanager/tokenmanager.go
Labels: area/security, cla: yes, size/XXL

#19760 Update analysis readme to match #19729
  galley/pkg/config/analysis/README.md
Labels: area/config, cla: yes, size/XS

#19888 skip port name check for system ns
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/auth/mtls.go
  galley/pkg/config/analysis/analyzers/service/portname.go
  galley/pkg/config/analysis/analyzers/testdata/service-no-port-name-system-namespace.yaml
  galley/pkg/config/analysis/analyzers/util/config.go
Labels: cla: yes, size/M

#19892 [release-1.4] Keep service instances sorted by creation/hostname
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/M

#19859 make SSE controller share a connection with common mcp controller
  pilot/pkg/bootstrap/configcontroller.go
Labels: cla: yes, size/XS

#19821 Use TransportSocket in filter chains
  istioctl/pkg/authz/listener.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/util/util.go
  tests/integration/security/mtls_permissive_test.go
Labels: cla: yes, size/L

#19882 Stop logging client disconnect as a pilot error
  pilot/pkg/proxy/envoy/v2/ads.go
Labels: cla: yes, size/S

#19899 xds: use typedstruct
  pilot/pkg/model/config.go
  pilot/pkg/proxy/envoy/v2/discovery.go
  tests/integration/telemetry/stats/prometheus/testdata/metadata_exchange_filter.yaml
  tests/integration/telemetry/stats/prometheus/testdata/stats_filter.yaml
Labels: cla: yes, size/L

#19812 Minor clean code for listener build
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, size/L

#19881 Fix performance regression for EnvoyFilter w/o MCP
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/deprecated.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  tests/testdata/networking/envoyfilter-without-service/configs.yaml
Labels: cla: yes, size/M

#19840 Rebuild base image
  Makefile.core.mk
Labels: cla: yes, size/XS

#19864 Disable route timeout for passthrough cluster
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: area/networking, cla: yes, ok-to-test, size/M

#19897 Add test for STS flow
  security/pkg/stsservice/server/server.go
  security/pkg/stsservice/server/server_test.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
  security/pkg/stsservice/tokenmanager/sts_test.go
  security/pkg/stsservice/tokenmanager/tokenmanager.go
Labels: area/security, cla: yes, size/L

#19905 Don't validate credentialName in gateway secrets analyzer if it isn't specified
  galley/pkg/config/analysis/analyzers/gateway/secret.go
  galley/pkg/config/analysis/analyzers/testdata/gateway-secrets.yaml
Labels: area/config, cla: yes, size/S

#19906 Update analyzer IsIstioControlPlane filter to also look for release=istio
  galley/pkg/config/analysis/analyzers/testdata/service-no-port-name-system-namespace.yaml
  galley/pkg/config/analysis/analyzers/util/config.go
Labels: area/config, cla: yes, size/M

#19907 [release-1.4] Do not inject a sidecar into post-install jobs
  install/kubernetes/helm/istio/charts/grafana/templates/create-custom-resources-job.yaml
  install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml
Labels: cla: yes, size/XS

#19876 Disable multiple metrics exporters with Istiod
  pilot/pkg/bootstrap/sidecarinjector.go
  pkg/kube/inject/webhook.go
Labels: cla: yes, size/S

#19762 Sync api
  go.mod
  go.sum
  install/kubernetes/helm/istio-init/files/crd-all.gen.yaml
  install/kubernetes/helm/istio-init/files/crd-mixer.yaml
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  mixer/testdata/config/kubernetesenv.yaml
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: cla: yes, size/L

#19818 Add support for pkcs8 private key
  pkg/istio-agent/sds-agent.go
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/pki/util/generate_csr_test.go
Labels: area/security, cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/M

#19912 [release-1.4] Update dependency for 1.4.3
  go.mod
  go.sum
  istio.deps
  istioctl/pkg/multicluster/generate.go
  prow/release-commit.sh
Labels: cla: yes, size/S

#19769 Do not configure ip6tables at all if IPv6 is disabled
  Makefile.core.mk
  tests/scripts/istio-iptables-test.sh
  tests/scripts/testdata/golang/empty_parameter_golden.txt
  tests/scripts/testdata/golang/mode_redirect_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_golden.txt
  tests/scripts/testdata/golang/outbound_port_exclude_golden.txt
  tests/scripts/testdata/golang/wildcard_include_ip_range_golden.txt
  tests/scripts/testdata/golang_clean/empty_parameter_golden.txt
  tests/scripts/testdata/golang_clean/mode_redirect_golden.txt
  tests/scripts/testdata/golang_clean/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/golang_clean/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/golang_clean/mode_tproxy_golden.txt
  tests/scripts/testdata/golang_clean/outbound_port_exclude_golden.txt
  tests/scripts/testdata/golang_clean/wildcard_include_ip_range_golden.txt
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-iptables/pkg/builder/iptables_builder_impl.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: area/networking, cla: yes, size/XL

#19895 Update operator
  go.mod
  go.sum
Labels: cla: yes, size/XS

#19713 refactor endpoints code
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointsdiscovery.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: cla: yes, size/L

#19917 Fix invalid mixer CRD
  mixer/pkg/runtime/testing/data/data.go
Labels: cla: yes, size/XS

#19920 remove unnecessary fmt printlns in tests
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: area/networking, cla: yes, size/XS

#19866 Reduce spammy logs from sidecar-injector
  pkg/kube/inject/webhook.go
Labels: cla: yes, size/XS

#19308 Disable redirect calls to app itself via envoy
  tests/scripts/testdata/golang/empty_parameter_golden.txt
  tests/scripts/testdata/golang/mode_redirect_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_ipv6_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_and_wildcard_port_golden.txt
  tests/scripts/testdata/golang/mode_tproxy_golden.txt
  tests/scripts/testdata/golang/outbound_port_exclude_golden.txt
  tests/scripts/testdata/golang/wildcard_include_ip_range_golden.txt
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: area/networking, cla: yes, size/L

#19496 Enable headless service reachability test
  tests/integration/security/mtls/strict_test.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, size/S

#19929 Fix TestConformance
  tests/integration/conformance/testdata/policy/instance/basic/input.yaml
Labels: cla: yes, size/XS

#19919 handle http proxy while generating routes
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: area/networking, cla: yes, size/L

#19938 fix http access log
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes, size/XS

#19936 service entry: recompute indexes only when services have changed
  pilot/pkg/serviceregistry/external/servicediscovery.go
Labels: cla: yes, size/L

#19913 [release-1.4] Manually cherry-pick #19818
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/pki/util/generate_csr_test.go
Labels: area/security, cla: yes, size/M

#19914 [release-1.3] Add support for pkcs8 private key #19818
  security/cmd/node_agent_k8s/main.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/pki/util/generate_csr_test.go
Labels: area/security, cla: yes, size/M

#19723 fix webhook integration test
  pkg/test/kube/accessor.go
  tests/integration/galley/webhook/webhook_test.go
Labels: cla: yes, size/S

#19808 Add default resource definition support for analyzers
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/gateway/gateway.go
  galley/pkg/config/analysis/analyzers/gateway/secret.go
  galley/pkg/config/analysis/analyzers/testdata/gateway-custom-ingressgateway-badport.yaml
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/analysis/local/defaults.go
  istioctl/cmd/analyze.go
Labels: area/config, cla: yes, size/L

#19954 Update stats filter test to use operator
  tests/integration/telemetry/stats/prometheus/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/testdata/metadata_exchange_filter.yaml
  tests/integration/telemetry/stats/prometheus/testdata/stats_filter.yaml
Labels: cla: yes, size/L

#19957 Add msg.All() which returns all analyzer message types
  galley/pkg/config/analysis/msg/generate.main.go
  galley/pkg/config/analysis/msg/messages.gen.go
Labels: cla: yes, size/XS

#19771 istio: add consecutive 5xx and gateway errors for outlier detection
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: area/networking, cla: yes, ok-to-test, size/L

#19962 Fix race in pilot controller tests
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: cla: yes, size/XS

#19960 Fix logs without spaces
  pkg/istio-agent/sds-agent.go
Labels: cla: yes, size/S

#18979 support dualstack in bookinfo sample
  samples/bookinfo/src/details/details.rb
  samples/bookinfo/src/productpage/productpage.py
Labels: cla: yes, ok-to-test, size/XS

#19863 SSE remove event should trigger a xDS push
  pilot/pkg/serviceregistry/synthetic/serviceentry/syntheticserviceentrycontroller.go
  pilot/pkg/serviceregistry/synthetic/serviceentry/syntheticserviceentrycontroller_test.go
Labels: area/networking, cla: yes, size/M

#19955 Make `istioctl upgrade` graduate from experimental
  istioctl/cmd/root.go
Labels: area/environments, cherrypick/release-1.4, cla: yes, size/XS

#19974 Galley: schema updates
  galley/pkg/config/analysis/analyzer.go
  galley/pkg/config/analysis/analyzer_test.go
  galley/pkg/config/analysis/analyzers/schema/validation.go
  galley/pkg/config/analysis/analyzers/schema/validation_test.go
  galley/pkg/config/collection/set.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  galley/pkg/config/processing/snapshotter/snapshotter.go
  galley/pkg/config/processing/transformer/provider.go
  galley/pkg/config/schema/codegen/collections.go
  galley/pkg/config/schema/codegen/collections_test.go
  galley/pkg/config/schema/collection/schema.go
  galley/pkg/config/schema/collection/schema_test.go
  galley/pkg/config/schema/collection/schemas.go
  galley/pkg/config/schema/collection/schemas_test.go
  galley/pkg/config/schema/collections/collections.gen.go
  galley/pkg/config/schema/resource/schema.go
  galley/pkg/config/schema/resource/schema_test.go
  galley/pkg/config/schema/schema.go
  galley/pkg/config/schema/schema_test.go
  galley/pkg/config/source/kube/apiserver/source.go
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/config/source/mcp/cache_test.go
  galley/pkg/config/testing/basicmeta/collections.gen.go
  galley/pkg/config/testing/data/collections.go
  galley/pkg/config/testing/k8smeta/collections.gen.go
Labels: cla: yes, size/XL

#19890 Add timeout for `istioctl analyze` getting resources
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/processing/snapshotter/statusupdater.go
  galley/pkg/config/processing/snapshotter/statusupdater_test.go
  galley/pkg/config/source/kube/apiserver/watcher.go
  istioctl/cmd/analyze.go
Labels: area/config, area/user experience, cla: yes, size/L

#19805 Add e2e test for jwt+authz on ingress
  pkg/test/framework/components/ingress/ingress.go
  pkg/test/framework/components/ingress/kube.go
  tests/integration/security/jwt_test.go
  tests/integration/security/testdata/requestauthn/global-jwt.yaml.tmpl
  tests/integration/security/testdata/requestauthn/ingress.yaml.tmpl
Labels: area/security, cla: yes, size/L

#19951 Write Citadel CA cert to a ConfigMap in each namespace
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/namespacecontroller.go
  pilot/pkg/bootstrap/server.go
  security/pkg/util/configutil.go
  security/pkg/util/configutil_test.go
Labels: area/networking, area/security, cla: yes, size/L

#19969 Update operator dependency
  go.mod
  go.sum
Labels: cla: yes, size/XS

#19963 correctly pass service host name in eds update for service entries
  pilot/pkg/serviceregistry/external/controller_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
Labels: area/networking, cla: yes, size/L

#20002 Fix names of istio-iptables scripts called in Debian package
  tools/packaging/common/istio-start.sh
Labels: area/environments, area/networking, cla: yes, size/XS

#19971 fix(bootstrap): add time-bounded platform detection logic with fail-fast
  pkg/bootstrap/config.go
  pkg/bootstrap/platform/aws.go
  pkg/bootstrap/platform/discovery.go
Labels: area/policies and telemetry, cla: yes, size/L

#19978 Removes Cloudfoundry Copilot integration test
  tests/e2e/tests/pilot/cloudfoundry/copilot_test.go
  tests/e2e/tests/pilot/mcp_test.go
  tests/istio.mk
  tests/testdata/mcp_bootstrap_tmpl.json
Labels: area/networking, cla: yes, size/L

#19988 Citadel generates the istiod certificate
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pkg/test/framework/components/pilot/native.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  tests/util/pilot_server.go
Labels: area/networking, area/security, cla: yes, size/L

#20007 Galley: Remove references to Pilot schemas.
  galley/pkg/config/schema/collections/mock.go
  galley/pkg/config/util/pb/proto.go
  galley/pkg/crd/validation/validation.go
  galley/pkg/crd/validation/webhook.go
  galley/pkg/crd/validation/webhook_test.go
Labels: cla: yes, size/L

#20016 Improve the SDS tests and fix error logs.
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server.go
Labels: area/security, cla: yes, size/S

#20008 update istio api
  go.mod
  go.sum
  install/kubernetes/helm/istio-init/files/crd-all.gen.yaml
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/model/jwks_resolver_test.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/security/authn/v1alpha1/policy_applier.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: area/security, cla: yes, size/M

#19991 Fix merging filter chains with matching all conditions
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: area/networking, cherrypick/release-1.4, cla: yes, size/L

#19965 handle serviceentry delete
  pilot/pkg/serviceregistry/external/controller_test.go
  pilot/pkg/serviceregistry/external/servicediscovery.go
Labels: area/networking, cla: yes, size/M

#20018 CHERRY-PICK #19991: Fix merging filter chains with matching all conditions
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: area/networking, cla: yes, size/L

#20024 Stop using deprecated fields in virtualservice
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  samples/bookinfo/networking/fault-injection-details-v1.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-default-route-append-headers.yaml
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-route-via-egressgateway.yaml
  tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-egressgateway.yaml
  tests/testdata/config/rule-default-route-append-headers.yaml
Labels: cla: yes, size/L

#20035 Migrate istio.io test for SDS to istioctl instead of helm template
  tests/integration/istioio/trafficmanagement/ingress/scripts/cleanup.txt
  tests/integration/istioio/trafficmanagement/ingress/scripts/enable_sds.txt
  tests/integration/istioio/trafficmanagement/ingress/secure_ingress_sds_test.go
Labels: area/test and release, cla: yes, size/M

#19983 add standalone webhook validation controller and server packages (1 of 3)
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
  pkg/webhooks/validation/controller/monitoring.go
  pkg/webhooks/validation/server/monitoring.go
  pkg/webhooks/validation/server/server.go
  pkg/webhooks/validation/server/server_test.go
Labels: cla: yes, size/XXL

#20006 Refactor messages to track resource rather than origin
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/schema/validation_test.go
  galley/pkg/config/analysis/diag/message.go
  galley/pkg/config/analysis/diag/message_test.go
  galley/pkg/config/analysis/diag/messages.go
  galley/pkg/config/analysis/diag/messages_test.go
  galley/pkg/config/analysis/msg/generate.main.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  galley/pkg/config/source/kube/apiserver/status/controller.go
  galley/pkg/config/source/kube/apiserver/status/controller_test.go
  istioctl/cmd/analyze.go
Labels: area/config, cla: yes, size/L

#20030 fix TestKubeOnly flake
  galley/pkg/config/processing/snapshotter/statusupdater.go
Labels: cla: yes, size/XS

#20010 Add permissions check for `istioctl analyze`
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/testing/mock/authorizationv1.go
  galley/pkg/testing/mock/kube_interface.go
  galley/pkg/testing/mock/selfsubjectaccessreviews.go
Labels: area/config, cla: yes, size/L

#20012 Apply forward token and payload based on API spec
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: area/security, cla: yes, size/L

#20013 Update istio/proxy to 01/08
  istio.deps
  pilot/pkg/security/authn/v1alpha1/policy_applier.go
  pilot/pkg/security/authn/v1alpha1/policy_applier_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: cla: yes, size/L

#20042 Revert "Migrate istio.io test for SDS to istioctl instead of helm template"
  tests/integration/istioio/trafficmanagement/ingress/scripts/cleanup.txt
  tests/integration/istioio/trafficmanagement/ingress/scripts/enable_sds.txt
  tests/integration/istioio/trafficmanagement/ingress/secure_ingress_sds_test.go
Labels: cla: yes, size/M

#19743 Deflake TestQuotaCache
  mixer/test/client/quota_cache/quota_cache_test.go
Labels: cla: yes, size/XS

#20040 Allow setting the template file for pilot-agent
  pilot/cmd/pilot-agent/main.go
Labels: cla: yes, size/XS

#20019 Update istioctl webhook injector service name
  istioctl/cmd/webhook.go
Labels: cla: yes, size/XS

#20049 Skip Ingress 503 test for multicluster only
  tests/e2e/tests/pilot/ingressgateway_test.go
Labels: cla: yes, size/XS

#20037 Istioctl: Migrate to galley schemas
  galley/pkg/config/schema/collection/schemas.go
  galley/pkg/config/schema/collection/schemas_test.go
  galley/pkg/config/schema/resource/schema.go
  galley/pkg/config/util/pilotadapter/convert.go
  galley/pkg/crd/validation/webhook.go
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/add-to-mesh_test.go
  istioctl/cmd/authz.go
  istioctl/cmd/convert_ingress.go
  istioctl/cmd/deprecated_cmd.go
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/istioctl_test.go
  istioctl/cmd/remove-from-mesh.go
  istioctl/cmd/remove-from-mesh_test.go
  istioctl/cmd/wait.go
  istioctl/cmd/wait_test.go
  istioctl/pkg/validate/validate.go
  istioctl/pkg/validate/validate_test.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/config/kube/crd/conversion.go
  pilot/pkg/config/memory/config.go
  pkg/config/schema/set.go
Labels: cla: yes, size/XL

#20048 Add chmod for iptables command
  tools/istio-docker.mk
Labels: cla: yes, size/XS

#19673 Allow istioctl analyze to suppress messages via cmd line
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  go.mod
  istioctl/cmd/analyze.go
Labels: area/user experience, cla: yes, size/L

#20041 Fix istiod Citadel CA starting flow
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  pkg/test/framework/components/pilot/native.go
  tests/util/pilot_server.go
Labels: area/networking, area/security, cla: yes, size/M

#20053 Add link for how to set HUB and TAG
  tests/integration/istioio/README.md
Labels: area/environments, area/test and release, area/user experience, cla: yes, ok-to-test, size/XS

#20063 istio.io SDS tests: deploy control plane using test framework
  tests/integration/istioio/trafficmanagement/ingress/main_test.go
  tests/integration/istioio/trafficmanagement/ingress/scripts/cleanup.txt
  tests/integration/istioio/trafficmanagement/ingress/scripts/enable_sds.txt
  tests/integration/istioio/trafficmanagement/ingress/secure_ingress_sds_test.go
Labels: area/test and release, cla: yes, size/M

#20056 Update envoyproxy api to 0.9.2
  go.mod
  go.sum
  mixer/test/client/dynamic_attribute/dynamic_attribute_test.go
  mixer/test/client/dynamic_listener/dynamic_listener_test.go
  mixer/test/client/gateway/gateway_test.go
  mixer/test/client/pilotplugin/pilotplugin_test.go
  mixer/test/client/pilotplugin_mtls/pilotplugin_mtls_test.go
  mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
Labels: cla: yes, size/L

#20052 Randomize CSR names to avoid race conditions from running multiple istiod instances
  security/pkg/k8s/chiron/utils.go
  security/pkg/k8s/chiron/utils_test.go
Labels: area/networking, area/security, cherrypick/release-1.4, cla: yes, size/M

#20079 [release-1.4] Randomize CSR names to avoid race conditions from running multiple istiod instances
  security/pkg/k8s/chiron/utils.go
  security/pkg/k8s/chiron/utils_test.go
Labels: cla: yes, size/M

#20083 Set Metrics in kube controller
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: cla: yes, size/XS

#19595 Fix segfaults: unaligned atomics on 32bit architectures
  galley/pkg/config/processing/snapshotter/snapshotter.go
  pkg/mcp/source/source.go
Labels: cla: yes, ok-to-test, size/S

#20026 Fix a group of mixer attributes generated from k8s when pod name contains dot
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
Labels: area/policies and telemetry, cherrypick/release-1.4, cla: yes, size/M

#19534 add a iptables failure detector, default off
  go.mod
  go.sum
  tests/scripts/istio-iptables-self-call-setup.sh
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/validation/linux.go
  tools/istio-iptables/pkg/validation/linux_test.go
  tools/istio-iptables/pkg/validation/validator.go
Labels: area/networking, cla: yes, size/L

#19606 Added test for Traffic Shifting task
  tests/integration/istioio/trafficmanagement/scripts/traffic_shifting.txt
  tests/integration/istioio/trafficmanagement/traffic_shifting_test.go
Labels: area/test and release, cla: yes, ok-to-test, size/L

#20050 Add e2e tests to verify JWT and JWT payload are output/prune as set correctly
  tests/integration/security/jwt_test.go
  tests/integration/security/testdata/requestauthn/e-authn.yaml.tmpl
  tests/integration/security/util/authn/authn_util.go
Labels: area/security, area/test and release, cla: yes, size/M

#19984 Make galley use the new webhook controller and server packages (2 of 3)
  CODEOWNERS
  galley/cmd/galley/cmd/server.go
  galley/pkg/crd/validation/config.go
  galley/pkg/crd/validation/config_test.go
  galley/pkg/crd/validation/endpoint.go
  galley/pkg/crd/validation/monitoring.go
  galley/pkg/crd/validation/validation.go
  galley/pkg/crd/validation/validation_test.go
  galley/pkg/crd/validation/webhook.go
  galley/pkg/crd/validation/webhook_test.go
  galley/pkg/server/components/validation.go
  galley/pkg/server/server.go
  galley/pkg/server/server_test.go
  galley/pkg/server/settings/args.go
  install/kubernetes/helm/istio/charts/galley/templates/clusterrole.yaml
  pkg/test/framework/components/galley/native.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
  pkg/webhooks/validation/server/server.go
  pkg/webhooks/validation/server/server_test.go
  tests/integration/galley/webhook/webhook_test.go
Labels: cla: yes, size/XXL

#20020 eds: remove inefficient get service calls while updating service shards
  pilot/pkg/proxy/envoy/v2/debug.go
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_sh_test.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/mem.go
  tests/util/pilot_server.go
Labels: cla: yes, size/M

#20104 eds: remove sleep in initLocalPilotTestEnv
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
Labels: cla: yes, size/S

#20109 [release-1.4] Send partial update on scale to zero endpoints
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: cla: yes, size/S

#20096 Add annotation for enableCoreDump
  install/kubernetes/helm/istio/files/injection-template.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/enable-core-dump-annotation.yaml
  pkg/kube/inject/testdata/inject/enable-core-dump-annotation.yaml.injected
  pkg/test/framework/components/echo/annotations.go
Labels: area/config, area/user experience, cla: yes, ok-to-test, size/L

#20071 Make samples/ directory accessible from istio.io tests through symlink
  pkg/test/istioio/builder.go
Labels: area/test and release, cla: yes, size/S

#20118 istio.io tests: don't set WorkDir to env.IstioSrc
  tests/integration/istioio/README.md
  tests/integration/istioio/examples/bookinfo_test.go
  tests/integration/istioio/security/authz_http_test.go
  tests/integration/istioio/security/mtls_migration_test.go
  tests/integration/istioio/trafficmanagement/traffic_shifting_test.go
Labels: area/test and release, cla: yes, size/S

#20017 Configure Istio Agent to connect to different CA providers
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/cache/secretcache.go
Labels: area/networking, area/security, cla: yes, size/M

#20088 update istio api
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/deprecation/deprecation.go
  galley/pkg/config/analysis/analyzers/testdata/deprecation.yaml
  go.mod
  go.sum
  install/kubernetes/helm/istio-init/files/crd-all.gen.yaml
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  tests/e2e/tests/pilot/routing_test.go
  tests/e2e/tests/pilot/testdata/networking/v1alpha3/rule-default-route-append-headers.yaml
Labels: cla: yes, size/L

#20136 Fixing race conditions in Analyzing Distributor tests
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
Labels: area/config, cla: yes, ok-to-test, size/M

#20132 Revert "Add timeout for `istioctl analyze` getting resources (#19890)"
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/processing/snapshotter/statusupdater.go
  galley/pkg/config/processing/snapshotter/statusupdater_test.go
  galley/pkg/config/source/kube/apiserver/watcher.go
  istioctl/cmd/analyze.go
Labels: area/config, cla: yes, size/L

#20054 Switch JWT validation to allow_missing instead of allow_missing_or_failed
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/testdata/requestauthn/c-authn.yaml.tmpl
Labels: cla: yes, size/L

#20140 Fix race in TestEds
  pilot/pkg/proxy/envoy/v2/eds_test.go
  pilot/pkg/proxy/envoy/v2/xds_test.go
Labels: cla: yes, size/S

#20022 Remove legacy searching endpoints in other namesapces
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointsdiscovery.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: cla: yes, size/M

#20138 Use external service controller for Synthetic Service Entries
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/serviceregistry/synthetic/serviceentry/discovery.go
  pilot/pkg/serviceregistry/synthetic/serviceentry/discovery_test.go
  pilot/pkg/serviceregistry/synthetic/serviceentry/syntheticserviceentrycontroller.go
  pilot/pkg/serviceregistry/synthetic/serviceentry/syntheticserviceentrycontroller_test.go
  pkg/config/schemas/schemagen/main.go
  pkg/config/schemas/schemagen/schemas.yaml
  pkg/config/schemas/schemas.gen.go
  tests/integration/pilot/mcp/main_test.go
Labels: cla: yes, size/XXL

#20094 Fix locality load balancing
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/proxy/envoy/v2/eds.go
  tests/integration/pilot/locality/distribute_test.go
  tests/integration/pilot/locality/failover_test.go
  tests/integration/pilot/locality/main_test.go
  tests/integration/pilot/locality/prioritized_test.go
Labels: cla: yes, size/L

#20095 Configure Envoy TLS validation for istiod
  manifests/global.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/features/pilot.go
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/option/instances_test.go
  pkg/envoy/proxy.go
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: area/networking, area/security, cla: yes, size/M

#20141 Disable TestQuotaCache
  mixer/test/client/quota_cache/quota_cache_test.go
Labels: cla: yes, size/XS

#20146 Make environments owners of manifests/ operator/
  CODEOWNERS
Labels: cla: yes, size/XS

#20155 Fix GetProxyServiceInstances
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: area/networking, cla: yes, size/S

#19992 Make headless service passthrough resolution optional
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: area/config, area/networking, cla: yes, ok-to-test, size/S

#20156 Add Envoy filter types so typed_config can be used when configuring EnvoyFilters
  pkg/config/validation/validation_test.go
  pkg/config/xds/filter_types.go
Labels: area/config, area/networking, cla: yes, ok-to-test, size/L

#20172 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: cla: yes, size/XS

#20134 Enable k8s CA signing through an environmental variable
  pilot/cmd/pilot-agent/main.go
  pkg/istio-agent/sds-agent.go
  security/pkg/nodeagent/sds/server.go
Labels: area/networking, area/security, cla: yes, size/M

#20194 Update proxy sha
  istio.deps
Labels: cla: yes, size/XS

#20193 Add PILOT_CERT_PROVIDER env variable for Pilot discovery container
  manifests/istio-control/istio-discovery/templates/deployment.yaml
  pilot/pkg/bootstrap/namespacecontroller.go
  pkg/istio-agent/sds-agent.go
Labels: area/networking, area/security, cla: yes, size/S

#20182 Package for translating IstioControlPlane to IstioOperator schemas
  operator/data/translateConfig/translate-ICP-IOP-1.5.yaml
  operator/pkg/name/name_test.go
  operator/pkg/patch/patch.go
  operator/pkg/tpath/tpath.go
  operator/pkg/tpath/tpath_test.go
  operator/pkg/translate/icp_iop.go
  operator/pkg/translate/testdata/icp-iop/input/addons.yaml
  operator/pkg/translate/testdata/icp-iop/input/default.yaml
  operator/pkg/translate/testdata/icp-iop/input/gateways.yaml
  operator/pkg/translate/testdata/icp-iop/output/addons.yaml
  operator/pkg/translate/testdata/icp-iop/output/default.yaml
  operator/pkg/translate/testdata/icp-iop/output/gateways.yaml
  operator/pkg/translate/yaml_tree.go
  operator/pkg/translate/yaml_tree_test.go
  operator/pkg/util/reflect.go
  operator/pkg/util/yaml.go
Labels: cla: yes, size/XXL

#20197 Bump kubernetes api to 1.17.1
  go.mod
  go.sum
Labels: cla: yes, size/M

#20206 Add short --skip-confirmation flag
  operator/cmd/mesh/manifest-apply.go
  operator/cmd/mesh/upgrade.go
  operator/pkg/manifest/installer.go
Labels: cla: yes, size/XS

#20145 Fix chart copying and generation for operator build
  Makefile.core.mk
  operator/Makefile.core.mk
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/gateways_override_default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  operator/data/profiles/default.yaml
  operator/installer.sha
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/component/controlplane/control_plane.go
  operator/pkg/vfs/assets.gen.go
  operator/pkg/vfs/vfs.go
  operator/python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
  operator/release/create_release_charts.sh
  operator/scripts/run_update_charts.sh
Labels: cla: yes, size/XL

#20121 simplify version check and add more tests
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
Labels: area/networking, cla: yes, size/M

#20127 Add basic bench testing for analyzers
  galley/pkg/config/analysis/analyzers/analyzers_bench_test.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/local/analyze.go
Labels: area/config, area/test and release, cla: yes, size/L

#20159 Fix listeners when proxy capture mode is none
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/proxy/envoy/v2/lds_test.go
Labels: cla: yes, size/S

#20174 Check resources for analyze suppression codes
  galley/pkg/config/processing/snapshotter/analyzingdistributor.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
Labels: area/user experience, cla: yes, size/L

#20187 Add various of tag format support in version check of istioctl upgrade
  operator/cmd/mesh/upgrade.go
  operator/pkg/manifest/client.go
  operator/pkg/version/version.go
  operator/pkg/version/version_test.go
  operator/version/version.go
Labels: area/environments, cla: yes, size/L

#20210 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  install/kubernetes/helm/istio-init/files/crd-all.gen.yaml
Labels: cla: yes, size/XS

#20180 Add operator init/remove commands
  istioctl/cmd/root.go
Labels: cla: yes, size/XS

#20181 Update README for operator
  operator/README.md
Labels: cla: yes, size/L

#20222 Clean up makefile
  operator/Makefile.core.mk
  operator/cmd/mesh/manifest_shared_test.go
Labels: cla: yes, size/M

#20221 Remove option for unsafe regex in Pilot
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pkg/config/validation/validation_test.go
Labels: cla: yes, size/M

#20224 Fix catchall route detection with safe regex
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: cla: yes, size/XS

#20229 Fix validation cert rotation
  pkg/webhooks/validation/server/server.go
Labels: cla: yes, size/S

#19896 Remove retry of individual time series
  mixer/adapter/stackdriver/metric/bufferedClient.go
  mixer/adapter/stackdriver/metric/bufferedClient_test.go
Labels: cla: yes, size/L

#20190 Allow multiple ICPS's as istioctl manifest/upgrade/profile input
  operator/cmd/mesh/manifest-apply.go
  operator/cmd/mesh/manifest-common.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/root.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/shared_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/telemetry_override_only.yaml
  operator/cmd/mesh/upgrade.go
  operator/pkg/util/testdata/yaml/input/yaml_layer1.yaml
  operator/pkg/util/testdata/yaml/input/yaml_layer2.yaml
  operator/pkg/util/testdata/yaml/input/yaml_layer3.yaml
  operator/pkg/util/testdata/yaml/output/layer1.yaml
  operator/pkg/util/testdata/yaml/output/layer1_2.yaml
  operator/pkg/util/testdata/yaml/output/layer1_2_3.yaml
  operator/pkg/util/yaml.go
Labels: area/environments, cla: yes, size/L

#20130 Add istio-validation container in when cni is enabled
  install/kubernetes/helm/istio/files/injection-template.yaml
  manifests/istio-control/istio-autoinject/files/injection-template.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  operator/pkg/vfs/assets.gen.go
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello.yaml.cni.injected
Labels: cla: yes, size/XL

#20091 [release-1.4] Fix a group of mixer attributes generated from k8s when pod name contains dot
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/adapter/kubernetesenv/kubernetesenv_test.go
Labels: cla: yes, size/M

#20124 Skip unused services while generate clusters for the gateways
  pilot/pkg/features/pilot.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: area/config, area/networking, area/perf and scalability, cla: yes, ok-to-test, size/M

#20211 Operator post-merge: update the data/versions.yaml
  operator/cmd/mesh/manifest-versions.go
  operator/cmd/mesh/upgrade.go
  operator/data/versions.yaml
  operator/pkg/vfs/assets.gen.go
Labels: area/environments, cla: yes, size/S

#20139 support deny action in authorization policy
  pilot/pkg/model/authorization.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/security/authz/builder/integration_test.go
  pilot/pkg/security/authz/builder/testdata/v1beta1/action-allow-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/action-deny-out.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/action-in.yaml
  pilot/pkg/security/authz/policy/helper.go
  pilot/pkg/security/authz/policy/policy.go
  pilot/pkg/security/authz/policy/v1alpha1/v1alpha1.go
  pilot/pkg/security/authz/policy/v1alpha1/v1alpha1_test.go
  pilot/pkg/security/authz/policy/v1beta1/v1beta1.go
  pilot/pkg/security/authz/policy/v1beta1/v1beta1_test.go
  tests/integration/security/rbac_v1beta1_test.go
  tests/integration/security/testdata/rbac/v1beta1-deny-ns-root.yaml.tmpl
  tests/integration/security/testdata/rbac/v1beta1-deny.yaml.tmpl
Labels: cla: yes, size/XL

#20237 eds: fix eds test codecov flaky ness
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: cla: yes, size/S

#20220 Stop using deprecated CORS policy
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
Labels: cla: yes, size/L

#20240 Fix bootstrap override
  manifests/istio-control/istio-autoinject/files/injection-template.yaml
  manifests/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#20245 Updating CNI SHA so we build the new CNI image.
  istio.deps
Labels: area/networking, area/test and release, cla: yes, size/XS

#20218 Schema tests
  operator/pkg/apis/istio/fixup_structs/main.go
  operator/pkg/apis/istio/v1alpha1/common.go
  operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/util/util.go
  operator/pkg/util/yaml.go
  operator/pkg/validate/validate_values_test.go
  operator/python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/L

#20243 Update operator CRD file to sync with generated file
  bin/update_crds.sh
  manifests/base/files/crd-all.gen.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  operator/pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#20249 iptables: Add override for iptables validation timeout
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/validation/validator.go
Labels: area/networking, cla: yes, size/M
