Repository istio/istio, pull requests merged in 2021-06, with the labels that each got.

#33196 update doc file path
  tests/integration/pilot/README.md
Labels: cla: yes, release-notes-none, size/XS

#33195 check if in.Rewrite is nil
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: area/networking, area/perf and scalability, cla: yes, ok-to-test, release-notes-none, size/XS

#33200 feat:check the k8s version before installing istio by operator
  operator/cmd/mesh/operator-init.go
Labels: area/environments/operator, cla: yes, kind/istioctl, release-notes-none, size/XS

#33201 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33173 wait for some time to give chance to both key and cert are written
  security/pkg/nodeagent/cache/secretcache.go
Labels: area/security, cla: yes, release-notes-none, size/S

#32982 Bump k8s test version to v1.21.1
  prow/integ-suite-kind.sh
Labels: cla: yes, release-notes-none, size/XS

#33190 Dedup Pushcontext with ServiceDiscovery and IstioConfigStore
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/apigen/apigen.go
  pilot/pkg/networking/apigen/apigen_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/discovery.go
Labels: cla: yes, release-notes-none, size/M

#33131 authz: add more e2e tests for dry-run policy
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/authorization_policy.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/policy_allow.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/policy_deny.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_allow_no_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_allow_with_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_deny_no_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_deny_with_policy.json.tmpl
Labels: area/security, cla: yes, release-notes-none, size/L

#33211 [release-1.10] Move from IstioVersions to Revisions in test framework (#32518)
  pkg/test/framework/components/echo/cmd/echogen/echogen.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  pkg/test/framework/resource/version.go
  pkg/test/framework/resource/version_test.go
  pkg/test/framework/test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#32878 honour subject alt names from service entry
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  releasenotes/notes/32539.yaml
Labels: area/networking, cla: yes, size/L

#33204 Filter out some redundant domains in istioctl
  istioctl/pkg/writer/envoy/configdump/route.go
Labels: cla: yes, release-notes-none, size/S

#33107 fixed istioctl wait bug for integ-distroless-k8s-tests
  istioctl/cmd/wait.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#33145 add crash recover to CNI plugin
  cni/cmd/istio-cni/main.go
  cni/cmd/istio-cni/main_test.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#32951 Optimize route generation by collapsing overlapping routes
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  releasenotes/notes/route-collapse.yaml
Labels: cla: yes, release-notes-none, size/L

#33044 Add per-revision validating webhook configuration
  manifests/charts/base/templates/validatingwebhookconfiguration.yaml
  manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  operator/cmd/mesh/install.go
  operator/cmd/mesh/uninstall.go
  pilot/pkg/bootstrap/validation.go
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/url/url.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
  pkg/webhooks/webhookpatch.go
  tests/integration/pilot/webhook_test.go
Labels: area/environments, cla: yes, release-notes-none, size/XL

#33240 avoid recursively dumping sibling test contexts
  pkg/test/framework/runtime.go
  pkg/test/framework/scope.go
  pkg/test/framework/testcontext.go
Labels: cla: yes, release-notes-none, size/S

#33231 Update to focal/debian10
  Makefile.core.mk
  docker/Dockerfile.base
  docker/Dockerfile.distroless
  manifests/charts/istio-operator/files/gen-operator.yaml
  pilot/docker/Dockerfile.proxyv2
  releasenotes/notes/focal-debian10.yaml
  tools/istio-iptables/pkg/dependencies/implementation.go
Labels: cla: yes, release-notes-none, size/M

#33140 fixed issue#33095 for status reporter panic error
  pilot/pkg/bootstrap/configcontroller.go
Labels: area/networking, area/user experience, cla: yes, release-notes-none, size/XS

#33242 Add label.CustomSetup and RequireIstioVersion to assorted pilot tests
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/piggyback_test.go
  tests/integration/pilot/revisioncmd/main_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/pilot/revisions/revisions_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/S

#33233 Fix regression preventing Host header set in vs destination section
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/config/validation/validation.go
  releasenotes/notes/host-in-route-destination.yaml
  tests/integration/pilot/common/routing.go
  tools/packaging/common/envoy_bootstrap.json
Labels: cherrypick/release-1.10, cla: yes, size/L

#33262 Revert "check if virtual service destinations has matching ports"
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
Labels: cla: yes, release-notes-none, size/L

#33265 ndsz: handle empty cluster id for headless svc
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/name_table.go
  pilot/pkg/xds/ep_filters.go
Labels: cla: yes, release-notes-none, size/S

#33264 [1.10] Fix regression preventing Host header set in vs destination section (…
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/config/validation/validation.go
  releasenotes/notes/host-in-route-destination.yaml
  tests/integration/pilot/common/routing.go
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, size/L

#32966 Fix overlapping service ordering
  pilot/pkg/model/sidecar.go
  releasenotes/notes/service-ordering.yaml
Labels: cla: yes, size/S

#33077 Remove istiod-remote charts
  Makefile.core.mk
  istioctl/cmd/revision.go
  istioctl/cmd/revision_test.go
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
  manifests/charts/istio-control/istio-discovery/Chart.yaml
  manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrolebinding.yaml
  manifests/charts/istio-control/istio-discovery/templates/configmap-jwks.yaml
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
  manifests/charts/istio-control/istio-discovery/templates/revision-tags.yaml
  manifests/charts/istio-control/istio-discovery/templates/role.yaml
  manifests/charts/istio-control/istio-discovery/templates/rolebinding.yaml
  manifests/charts/istio-control/istio-discovery/templates/service.yaml
  manifests/charts/istio-control/istio-discovery/templates/serviceaccount.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/Chart.yaml
  manifests/charts/istiod-remote/NOTES.txt
  manifests/charts/istiod-remote/files/gateway-injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  manifests/charts/istiod-remote/kustomization.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
  manifests/charts/istiod-remote/templates/clusterrolebinding.yaml
  manifests/charts/istiod-remote/templates/configmap.yaml
  manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/templates/role.yaml
  manifests/charts/istiod-remote/templates/rolebinding.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.10.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.11.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.9.yaml
  manifests/charts/istiod-remote/values.yaml
  manifests/profiles/default.yaml
  manifests/profiles/external.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/istiod_remote.yaml
  operator/pkg/component/component.go
  operator/pkg/controlplane/control_plane_test.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/name/name.go
  operator/pkg/translate/translate.go
  operator/pkg/translate/translate_value.go
  operator/pkg/util/merge_iop.go
  releasenotes/notes/32949.yaml
  tests/integration/iop-istiodless-remote-integration-test-defaults.yaml
  tests/integration/multicluster/centralremotekubeconfig/main_test.go
Labels: cla: yes, size/XXL

#33267 Fix double logging in agent SDS
  security/pkg/nodeagent/sds/sdsservice.go
Labels: cla: yes, release-notes-none, size/S

#33278 fix a misspelling bug in istio/samples/bookinfo #33277
  samples/bookinfo/README.md
Labels: cla: yes, needs-ok-to-test, release-notes-none, size/XS

#33217 code cleanup: use cobra.Args to check command line arguments
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/admin.go
  istioctl/cmd/dashboard.go
  istioctl/cmd/describe.go
  istioctl/cmd/injector-list.go
  istioctl/cmd/remove-from-mesh.go
Labels: cla: yes, ok-to-test, release-notes-none, size/M

#33216 add more common patterns to path normalization test
  pkg/test/echo/client/parsedresponse.go
  pkg/test/framework/features/features.yaml
  tests/integration/security/normalization_test.go
Labels: area/security, cla: yes, release-notes-none, size/L

#33247 Fix sync during bootstrap
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingressv1/controller.go
Labels: cla: yes, release-notes-none, size/L

#33276 change struct name from 'configstoreMonitor' to 'configStoreMonitor'
  pilot/pkg/config/memory/monitor.go
Labels: area/user experience, cla: yes, ok-to-test, release-notes-none, size/S

#33234 Expose DNS config from agent
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/options/statusserver.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/pkg/dns/dns.go
  pkg/istio-agent/agent.go
Labels: cla: yes, release-notes-none, size/M

#33272 Fix TestWebhook to work under non-default revisions
  tests/integration/pilot/webhook_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#33192 Added deterministic push order test per connection
  pilot/pkg/xds/pushqueue_test.go
Labels: cla: yes, release-notes-none, size/M

#33289 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33248 Close the used file
  istioctl/pkg/validate/validate.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#33266 Consolidate componentLogLevel into one field
  pilot/cmd/pilot-agent/main.go
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: cla: yes, release-notes-none, size/M

#33273 after istio upgraded to 1.10,the community page url has changed to ht…
  SUPPORT.md
  cni/README.md
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#33255 virtualservice set default delegate namespace to root's
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
Labels: area/networking, cla: yes, ok-to-test, release-notes-none, size/L

#33219 add additional logging for cache sync
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pkg/kube/secretcontroller/secretcontroller.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#33304 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33305 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33286 dump ndsz via agent
  pilot/cmd/pilot-agent/request.go
  pkg/test/framework/components/echo/cmd/echogen/echogen.go
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/M

#33303 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33214 gateway-api: set more status fields
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mismatch.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
  pilot/pkg/model/kstatus/helper.go
Labels: cla: yes, release-notes-none, size/XXL

#33302 remove make of out
  pilot/pkg/serviceregistry/serviceentry/conversion.go
Labels: area/networking, area/perf and scalability, cla: yes, ok-to-test, release-notes-none, size/XS

#33311 Update helm integration test to use 1.9.0 and 1.10.0
  tests/integration/helm/testdata/1.10.0/base.tar.gz
  tests/integration/helm/testdata/1.10.0/gateways/istio-egress.tar.gz
  tests/integration/helm/testdata/1.10.0/gateways/istio-ingress.tar.gz
  tests/integration/helm/testdata/1.10.0/istio-control/istio-discovery.tar.gz
  tests/integration/helm/upgrade/helm_upgrade_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#33325 Automator: update common-files@master in istio/istio@master
  SUPPORT.md
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33327 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/S

#33328 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33292 do not build auto MTLS settings for SIMPLE
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#33244 Double the timeout to fix the authz dry-run test flaky
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#33290 [tf] Add validation to IstioVersion when parsing revisions
  pkg/test/framework/resource/version.go
  pkg/test/framework/resource/version_test.go
  tests/integration/pilot/common/traffic.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#33329 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33306 Take into account service registry state in gateway controller
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.yaml
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.yaml
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.yaml
  pilot/pkg/config/kube/gateway/testdata/tcp.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
Labels: area/networking, cla: yes, release-notes-none, size/XL

#32924 add uptime metric for istiod server
  pilot/pkg/bootstrap/monitoring.go
  releasenotes/notes/add-istiod-uptime-metric.yaml
Labels: cla: yes, size/S

#33309 add documentation url to analysis messages
  galley/pkg/config/analysis/msg/generate.main.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/test and release, cla: yes, release-notes-none, size/M

#33319 envoy filter metrics does not have name populated correctly
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/envoyfilter_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#33344 remove name tag from envoy filter error metrics
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#33257 Prevent meaningless enqueue before SyncAll
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/sync.go
Labels: cla: yes, release-notes-none, size/M

#33274 add fuzz test for authorization policy
  pkg/test/framework/features/features.yaml
  tests/integration/security/fuzz/README.md
  tests/integration/security/fuzz/backends/apache/apache.yaml
  tests/integration/security/fuzz/backends/nginx/nginx.yaml
  tests/integration/security/fuzz/fuzz_test.go
  tests/integration/security/fuzz/fuzzers/dotdotpwn/Dockerfile
  tests/integration/security/fuzz/fuzzers/dotdotpwn/Makefile
  tests/integration/security/fuzz/fuzzers/dotdotpwn/dotdotpwn.yaml
  tests/integration/security/fuzz/fuzzers/dotdotpwn/run.sh
  tests/integration/security/fuzz/main_test.go
  tests/integration/security/fuzz/overview.jpg
Labels: area/security, cla: yes, release-notes-none, size/L

#32697 test proxyless gRPC with echo
  pilot/pkg/util/sets/string.go
  pilot/pkg/util/sets/string_test.go
  pkg/test/echo/cmd/client/main.go
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/scheme/scheme.go
  pkg/test/echo/server/forwarder/protocol.go
  pkg/test/framework/components/echo/annotations.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/echotest/filters.go
  pkg/test/framework/components/echo/instances.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/util.go
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: cla: yes, release-notes-none, size/L

#33348 Fix using new Gateway api with legacy gw annotation
  pilot/pkg/model/gateway.go
Labels: cla: yes, release-notes-none, size/XS

#33357 Cleanup istiod-remote checks in charts
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrolebinding.yaml
  manifests/charts/istio-control/istio-discovery/templates/role.yaml
  manifests/charts/istio-control/istio-discovery/templates/rolebinding.yaml
  manifests/charts/istio-control/istio-discovery/templates/serviceaccount.yaml
Labels: area/environments, cla: yes, release-notes-none, size/M

#33362 fix minor tf log
  pkg/test/framework/components/echo/echoboot/echoboot.go
Labels: cla: yes, release-notes-none, size/XS

#33373 agent: use non blocking select
  pkg/istio-agent/agent.go
Labels: cla: yes, release-notes-none, size/XS

#33221 Fixes #30868. Added the missing IPv6 rule.
  releasenotes/notes/30868.yaml
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: area/networking, area/user experience, cla: yes, ok-to-test, size/M

#33120 Add Istio user agent to kube-client used in istioctl and other binaries
  cni/cmd/istio-cni-repair/main.go
  cni/cmd/istio-cni-taint/main.go
  cni/cmd/istio-cni/kubernetes.go
  go.mod
  istioctl/cmd/analyze.go
  istioctl/cmd/istioctl/main.go
  istioctl/cmd/root.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/upgrade.go
  pkg/kube/util.go
  releasenotes/notes/set-user-agent.yaml
  tools/bug-report/pkg/kubeclient/kubeclient.go
Labels: cla: yes, size/L

#33341 Drop support for 1.9 proxies
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  pkg/bootstrap/option/convert.go
Labels: cla: yes, release-notes-none, size/L

#33364 cleanups for k8s controller
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: cla: yes, release-notes-none, size/M

#33384 Add debug endpoint to show size of XDS caches
  pilot/pkg/model/xds_cache.go
  pilot/pkg/xds/debug.go
Labels: cla: yes, release-notes-none, size/M

#33321 [release-1.10] remove debounce logic from secret watcher
  security/pkg/nodeagent/cache/secretcache.go
Labels: cla: yes, release-notes-none, size/M

#33320 [release-1.10] wait for some time to give chance to both key and cert are written
  security/pkg/nodeagent/cache/secretcache.go
Labels: cla: yes, release-notes-none, size/S

#33381 Fix delta test to match Envoy
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/deltaadstest.go
Labels: cla: yes, release-notes-none, size/XS

#33316 downgrade quic-go
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/XS

#33172 fix: script parameter error under macos
  bin/retry.sh
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#33263 Trim down dependencies
  go.mod
  go.sum
  licenses/github.com/andybalholm/brotli/LICENSE
  licenses/github.com/dsnet/compress/LICENSE.md
  licenses/github.com/golang/snappy/LICENSE
  licenses/github.com/klauspost/compress/LICENSE
  licenses/github.com/klauspost/compress/s2/LICENSE
  licenses/github.com/klauspost/compress/s2/cmd/internal/readahead/LICENSE
  licenses/github.com/klauspost/compress/snappy/LICENSE
  licenses/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt
  licenses/github.com/klauspost/pgzip/LICENSE
  licenses/github.com/mholt/archiver/v3/LICENSE
  licenses/github.com/nwaples/rardecode/LICENSE
  licenses/github.com/pierrec/lz4/v4/LICENSE
  licenses/github.com/ulikunitz/xz/LICENSE
  licenses/github.com/xi2/xz/LICENSE
  operator/pkg/helm/urlfetcher.go
  operator/pkg/util/tgz/tgz.go
Labels: cla: yes, release-notes-none, size/L

#33393 check if virtual service destinations has matching ports (take 2)
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#33386 Fix regression when using custom transport_socket envoyfilter
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/ef-tls-regression.yaml
Labels: cherrypick/release-1.10, cherrypick/release-1.9, cla: yes, size/L

#33413 handle remove files in secret watcher
  releasenotes/notes/33293.yaml
  security/pkg/nodeagent/cache/secretcache.go
Labels: cherrypick/release-1.10, cla: yes, size/S

#33415 Update api dep
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot.tar.gz
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_values_enable_egressgateway.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/helm_values_enablement.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ingressgateway_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/install_package_path.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml
  operator/cmd/mesh/testdata/operator/output/operator-dump.yaml
  operator/cmd/mesh/testdata/operator/output/operator-init.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.txt
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/cmd/mesh/testdata/profile-dump/output/config_path.txt
  operator/cmd/mesh/testdata/profile-dump/output/config_path.yaml
Labels: cla: yes, release-notes-none, size/XXL

#33419 [release-1.10] handle remove files in secret watcher
  releasenotes/notes/33293.yaml
  security/pkg/nodeagent/cache/secretcache.go
Labels: cla: yes, release-notes-none, size/S

#33406 Consistently early resolve environment variables
  pilot/cmd/pilot-agent/options/security.go
  pilot/cmd/pilot-discovery/app/cmd.go
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/plugin/authn/util.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/status/state.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/deltaadstest.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/pcds.go
  pkg/bootstrap/config.go
Labels: cla: yes, release-notes-none, size/L

#33427 envoy: add mongo filter feature
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
Labels: cla: yes, release-notes-none, size/S

#33215 Update dependencies
  go.mod
  go.sum
  tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go
Labels: cla: yes, release-notes-none, size/XS

#32701 fixed issues of overlapping matches for virtualservice. Issue#24707
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_overlappingmatches.yaml
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  pkg/config/validation/validation.go
Labels: area/user experience, cla: yes, release-notes-none, size/L

#33428 Fix leaky informer run and wait
  pkg/kube/client.go
Labels: cla: yes, release-notes-none, size/M

#33383 No need to apply istio-root-ca-cert configmap to special kubernetes system namespaces.
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pkg/kube/inject/initializer.go
  pkg/kube/inject/inject.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: cla: yes, release-notes-none, size/M

#33369 make sure daemonset has at least one pod ready
  operator/pkg/helmreconciler/wait.go
Labels: area/networking, cla: yes, ok-to-test, release-notes-none, size/S

#33359 Add version summary option to istioctl proxy-config bootstrap
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/writer/envoy/configdump/configdump.go
  istioctl/pkg/writer/envoy/configdump/configdump_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/configdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/versionsummary.txt
  releasenotes/notes/33359.yaml
Labels: area/user experience, cla: yes, ok-to-test, size/L

#33436 add test for cert delete and add
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: cla: yes, release-notes-none, size/S

#33439 [release-1.9] Fixes #30868. Added the missing IPv6 rule.
  releasenotes/notes/30868.yaml
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: cla: yes, release-notes-none, size/M

#33423 pilot: cleanup server to only store kubeClient
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/status/state.go
Labels: cla: yes, release-notes-none, size/S

#33445 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/S

#33395 Bump base images
  Makefile.core.mk
  pilot/docker/Dockerfile.proxyv2
Labels: cla: yes, release-notes-none, size/XS

#33438 Fix dump for TestCustomGateway
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/XS

#33442 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33400 [tf] Consolidate --istio.test.revision and --istio.test.revisions flags
  pkg/test/framework/components/echo/cmd/echogen/echogen.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/istio/util.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/components/namespace/namespace.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/flags_test.go
  pkg/test/framework/resource/settings.go
  pkg/test/framework/resource/version.go
  pkg/test/framework/resource/version_test.go
  pkg/test/kube/dump.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/webhook_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#33446 [tf] Avoid erroring out when injection template missing
  pkg/test/framework/components/echo/echoboot/echoboot.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#33448 Some improvements to GCP metadata
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
Labels: cla: yes, release-notes-none, size/S

#33452 [1.10] Fix regression when using custom transport_socket envoyfilter (#33386)
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/ef-tls-regression.yaml
Labels: cla: yes, size/L

#33449 Export XDS_AUTH_PLAINTEXT variable
  pilot/pkg/xds/authentication.go
Labels: cla: yes, release-notes-none, size/XS

#33363 Merge gateway topology test into common suite
  pkg/test/kube/util.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/gateway_topology/gw_topology_test.go
  tests/integration/pilot/gw_topology_test.go
Labels: cla: yes, release-notes-none, size/L

#33457 Add minIstioVersion for instance IP tests
  tests/integration/pilot/common/routing.go
Labels: area/test and release, cla: yes, release-notes-none, size/S

#33458 Fix cert generation test for go 1.17 support
  security/pkg/pki/util/generate_cert_test.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/S

#33453 [1.9] Fix regression when using custom transport_socket envoyfilter (#33386)
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/ef-tls-regression.yaml
Labels: cla: yes, size/XXL

#33433 istioctl crashed at retrieveListenerAddress
  istioctl/pkg/writer/envoy/configdump/listener.go
  istioctl/pkg/writer/envoy/configdump/listener_test.go
Labels: area/user experience, cla: yes, ok-to-test, release-notes-none, size/S

#33296 add ut for sysexit.go
  istioctl/cmd/sysexits_test.go
  releasenotes/notes/revision-tag-command.yaml
Labels: cla: yes, release-notes-none, size/S

#33451 User proper name in gateway status
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
Labels: cla: yes, release-notes-none, size/L

#33444 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33471 fix normalizeClusters typo in comment
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#33473 Update proxy sha.
  istio.deps
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/M

#33465 modify parameters in helm_upgrade
  tests/integration/helm/upgrade/util.go
Labels: area/test and release, cla: yes, ok-to-test, release-notes-none, size/XS

#33459 [release-1.10] Fix cert generation test for go 1.17 support
  security/pkg/pki/util/generate_cert_test.go
Labels: cla: yes, release-notes-none, size/S

#33482 code style, keep CamelCase: change variable name from `podcontroller` to `podController`
  cni/pkg/taint/taintcontroller.go
Labels: area/user experience, cla: yes, needs-ok-to-test, release-notes-none, size/XS

#33484 fix typo from DefaultWasmModulePurgeInteval to DefaultWasmModulePurgeInterval
  pkg/istio-agent/xds_proxy.go
  pkg/wasm/cache.go
  pkg/wasm/cache_test.go
Labels: cla: yes, release-notes-none, size/S

#33367 istioctl proxy-config command support pod-name auto-completion
  istioctl/cmd/proxyconfig.go
Labels: cla: yes, ok-to-test, release-notes-none, size/M

#33440 [release-1.10] Fixes #30868. Added the missing IPv6 rule.
  releasenotes/notes/30868.yaml
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: cla: yes, release-notes-none, size/M

#33403 Fix istioctl auth errors
  istioctl/cmd/authz.go
  istioctl/cmd/describe.go
  istioctl/cmd/precheck.go
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxystatus.go
  pkg/kube/client.go
  pkg/kube/mock_client.go
  tests/integration/pilot/istioctl_test.go
  tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
Labels: area/user experience, cla: yes, release-notes-none, size/M

#33493 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33496 Re-run failed automator to update common-files
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none, size/XS

#32628 [release-1.10] allow specifying additional echo workloads
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/echoboot/flags.go
Labels: cla: yes, release-notes-none, size/L

#33501 Automator: update common-files@release-1.10 in istio/istio@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33503 run UPDATE_BRANCH=release-1.9 ./bin/update_deps.sh; make gen
  go.mod
  go.sum
  pilot/docker/Dockerfile.proxyv2
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/S

#33502 Automator: update istio/api@release-1.10 dependency in istio/istio@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33504 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33508 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33505 Fix token exchange error message
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#33509 run UPDATE_BRANCH=release-1.10 ./bin/update_deps.sh; make gen
  go.mod
  go.sum
  pilot/docker/Dockerfile.proxyv2
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/S

#33479 Skip tests broken in 1.22
  tests/integration/helm/upgrade/main_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/security/chiron/main_test.go
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/mtlsk8sca/main_test.go
  tests/integration/security/sds_ingress_k8sca/main_test.go
Labels: cla: yes, release-notes-none, size/M

#33507 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33510 fix consistent hashing test for multicluster
  tests/integration/pilot/common/routing.go
Labels: cla: yes, release-notes-none, size/M

#33456 bootstrap: add patching and an integration test
  pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go
  pilot/pkg/xds/bootstrapds.go
  pkg/config/xds/xds.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
Labels: cla: yes, release-notes-none, size/M

#33500 [tf] Pass context to namespace when creating with stableNamespaces
  pkg/test/framework/components/namespace/kube.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#33518 Make consistent hash test only run in single network
  tests/integration/pilot/common/traffic.go
Labels: cla: yes, release-notes-none, size/XS

#33521 Fix ingress test on old and new kubernetes versions
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/S

#33524 Bump quic-go for go 1.17 support
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/S

#32863 Adding MCS service discovery
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/clusterrole.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
  pilot/pkg/serviceregistry/kube/controller/util.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/xds/endpoint_builder.go
  pkg/kube/client.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/environment/kube/flags.go
  pkg/test/framework/features/features.yaml
  releasenotes/notes/mcs-service-discovery.yaml
  tests/integration/pilot/mcs/autoexport/autoexport_test.go
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
Labels: area/networking, cla: yes, size/XXL

#33522 Improve merging of proxy config proxyMetadata
  pilot/cmd/pilot-agent/config/config_test.go
  pkg/config/mesh/mesh.go
  pkg/config/mesh/mesh_test.go
  releasenotes/notes/pc-merge-metadata.yaml
Labels: cherrypick/release-1.10, cla: yes, size/M

#33331 Fixes for validation webhook controller
  manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  pilot/pkg/bootstrap/validation.go
  pilot/pkg/features/pilot.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
  tests/integration/pilot/webhook_test.go
Labels: area/environments, cla: yes, release-notes-none, size/M

#33499 Manual update of gogo-genproto.
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/XS

#32581 sort envoy filters by priority
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
Labels: cla: yes, release-notes-none, size/L

#33467 followup the PR#32701 and fixed issues based on comments left by @hzx…
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: cla: yes, release-notes-none, size/M

#33515 short path check for SubsetOf
  pkg/config/labels/collection.go
  pkg/config/labels/instance.go
  pkg/config/labels/instance_test.go
Labels: area/perf and scalability, cla: yes, release-notes-none, size/S

#33529 [release-1.10] Improve merging of proxy config proxyMetadata
  pilot/cmd/pilot-agent/config/config_test.go
  pkg/config/mesh/mesh.go
  pkg/config/mesh/mesh_test.go
  releasenotes/notes/pc-merge-metadata.yaml
Labels: cla: yes, release-notes-none, size/M

#33548 pick up missing repo updates (failed automator jobs)
  go.mod
  go.sum
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/S

#33552 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33541 Add integfuzz tag to lint and format configs
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  tests/integration/security/fuzz/main_test.go
Labels: cla: yes, release-notes-none, size/XS

#33494 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#33556 improve Equals func performance
  pilot/pkg/model/config_test.go
  pkg/config/labels/instance.go
Labels: cla: yes, release-notes-none, size/S
