Repository istio/istio, pull requests merged in 2021-04, with the labels that each got.

#31838 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31605 support xds address for kube-inject
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/kubeinject.go
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
Labels: cla: yes, release-notes-none, size/L

#31842 Remove unreachable code in internal-debug
  istioctl/cmd/internal-debug.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#31828 Fix bad formatting in log
  istioctl/cmd/workload.go
Labels: cla: yes, release-notes-none, size/XS

#31841 Clean up pilot-agent start up error message.
  pilot/cmd/pilot-agent/main.go
  pkg/istio-agent/agent.go
Labels: cla: yes, release-notes-none, size/XS

#31840 Fix bug-report target cluster context error
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/content/content.go
Labels: area/user experience, cla: yes, release-notes-none, size/S

#31846 add one integration test and release notes for kube-inject
  pkg/test/framework/features/features.yaml
  releasenotes/notes/29270.yaml
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/testdata/hello.yaml
Labels: cla: yes, size/M

#31756 Revert "add ratelimit configmap (#31734)"
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/src/ratings/ratings.js
  samples/ratelimit/rate-limit-service.yaml
Labels: cla: yes, kind/docs, release-notes-none, size/S

#31839 Add pilot_sds_certificate_errors_total metric for sds
  pilot/pkg/xds/monitoring.go
  pilot/pkg/xds/sds.go
  releasenotes/notes/31779.yaml
Labels: cla: yes, size/S

#31823 backport xds cache changes
  pilot/pkg/features/pilot.go
  pilot/pkg/model/xds_cache.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/xds_cache_test.go
  pkg/test/kube/dump.go
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/XL

#31709 Integration test for 'istioctl experimental version'
  tests/integration/pilot/istioctl_test.go
Labels: cla: yes, release-notes-none, size/S

#31832 Support XDS proxy for delta xds
  pilot/pkg/xds/delta.go
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
  pkg/wasm/convert.go
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/L

#31836 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31825 Avoid proxy being marked ready prematurely when fetch times out
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/security/model/authentication.go
  pkg/bootstrap/instance.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  security/pkg/nodeagent/util/util.go
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/M

#31565 echotest: RunToN for tests with multiple destinations
  pkg/test/framework/components/echo/echotest/echotest.go
  pkg/test/framework/components/echo/echotest/filters.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/echotest/run.go
  pkg/test/framework/components/echo/echotest/setup.go
  pkg/test/framework/components/echo/instances.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/security/pass_through_filter_chain_test.go
  tools/bug-report/pkg/config/config.go
Labels: cla: yes, release-notes-none, size/XL

#31847 Refactor DetectSupportedJWTPolicy to use kubernetes.Interface
  istioctl/cmd/workload.go
  istioctl/cmd/workload_test.go
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/manifest/shared.go
  operator/pkg/util/k8s.go
  operator/pkg/util/k8s_test.go
Labels: area/environments, cla: yes, release-notes-none, size/M

#31753 add delimit for status report of distribution
  pilot/pkg/status/reporter.go
  pilot/pkg/status/reporter_test.go
Labels: cla: yes, release-notes-none, size/S

#31459 Fix the body is not closed when the response failure
  operator/pkg/httprequest/httprequest.go
Labels: cla: yes, release-notes-none, size/XS

#31845 do not set h2 alpn when downstream config is set
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31863 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31868 minor optimization in model
  pkg/config/model.go
Labels: cla: yes, release-notes-none, size/XS

#31857 Clean up two unused stats tag from default bootstrap tag list.
  pkg/bootstrap/config.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
Labels: cla: yes, release-notes-none, size/L

#31858 Remove unnecessary root cert config from Stackdriver tracer config.
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  tools/packaging/common/envoy_bootstrap.json
  tools/packaging/common/gcp_envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/M

#31869 refactor test server in to common code for agent
  pilot/cmd/pilot-agent/status/ready/probe_test.go
  pilot/cmd/pilot-agent/status/server_test.go
  pilot/cmd/pilot-agent/status/testserver/server.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#31870 change passthrough clusters to use new protocol options
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#31849 Webhook Warn on ineffective virtual service matches
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/schema/validation.go
  galley/pkg/config/analysis/analyzers/virtualservice/matches.go
  pkg/config/validation/validation.go
  releasenotes/notes/vs-ineffective-warning.yaml
Labels: cla: yes, size/L

#31878 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31859 Fix sts token exchange request retry logic.
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: cla: yes, release-notes-none, size/S

#31884 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31890 Add example of add to list by overlays patches
  operator/README.md
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#31813 Fix analyzer IST137 description
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#31827 Disable inbound iptables capture on standard ports for VMs
  istioctl/cmd/testdata/vmconfig/simple/cluster.env.golden
  istioctl/cmd/workload.go
  pkg/test/framework/components/echo/kube/deployment.go
  releasenotes/notes/vm-iptables-inbound.yaml
Labels: cherrypick/release-1.9, cla: yes, size/S

#31895 [release-1.9] Disable inbound iptables capture on standard ports for VMs
  istioctl/cmd/testdata/vmconfig/simple/cluster.env.golden
  istioctl/cmd/workload.go
  pkg/test/framework/components/echo/kube/deployment.go
  releasenotes/notes/vm-iptables-inbound.yaml
Labels: cla: yes, release-notes-none, size/S

#31778 Fix for Issue 31695 - supporting '-o yaml' in istioctl proxy-config to output in yaml
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/writer/envoy/clusters/clusters.go
  istioctl/pkg/writer/envoy/configdump/cluster.go
  istioctl/pkg/writer/envoy/configdump/configdump.go
  istioctl/pkg/writer/envoy/configdump/configdump_test.go
  istioctl/pkg/writer/envoy/configdump/listener.go
  istioctl/pkg/writer/envoy/configdump/route.go
  releasenotes/notes/31695-releasenote.yaml
Labels: area/user experience, cla: yes, ok-to-test, size/L

#31887 remove downstream protocol usages
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#31892 Fix BoolValueForPB may be nil
  istioctl/cmd/revision.go
  operator/cmd/mesh/install.go
  operator/pkg/component/component.go
  operator/pkg/util/util.go
  operator/pkg/util/util_test.go
Labels: area/environments, cla: yes, release-notes-none, size/M

#31852 Properly validate header operations and allow host header modification
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/config/validation/virtualservice.go
  tests/integration/pilot/common/routing.go
Labels: cla: yes, release-notes-none, size/L

#31894 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31886 refactor listener code to use cluster model
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31901 change test server to use dynamic port
  pilot/cmd/pilot-agent/status/ready/probe_test.go
  pilot/cmd/pilot-agent/status/server_test.go
  pilot/cmd/pilot-agent/status/testserver/server.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31896 Fix err always nil (unreachable code)
  tools/bug-report/pkg/config/config.go
Labels: area/user experience, cla: yes, release-notes-none, size/S

#31902 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31903 Manually update istio/api
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#31879 update dry-run metric prefix and also add e2e tests
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/testdata/http/allow-empty-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/allow-nil-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/allow-path-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/audit-full-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/deny-and-allow-out1.yaml
  pilot/pkg/security/authz/builder/testdata/http/deny-and-allow-out2.yaml
  pilot/pkg/security/authz/builder/testdata/http/deny-empty-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/dry-run-allow-and-deny-out1.yaml
  pilot/pkg/security/authz/builder/testdata/http/dry-run-allow-and-deny-out2.yaml
  pilot/pkg/security/authz/builder/testdata/http/dry-run-allow-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/dry-run-mix-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/multiple-policies-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/simple-policy-multiple-td-aliases-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/simple-policy-principal-with-wildcard-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/simple-policy-td-aliases-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/single-policy-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/td-aliases-source-principal-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/allow-both-http-tcp-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/allow-only-http-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/audit-both-http-tcp-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/deny-both-http-tcp-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/dry-run-mix-out.yaml
  pilot/pkg/security/authz/model/model.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/authorization_policy.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_authorization_policy.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log.json.tmpl
Labels: area/security, cla: yes, release-notes-none, size/L

#31906 Copy cni repair and taint binary to local bin folder.
  cni/deployments/kubernetes/Dockerfile.install-cni
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: cla: yes, release-notes-none, size/XS

#31907 Add more logs to install-cni.
  cni/pkg/install-cni/cmd/root.go
  cni/pkg/install-cni/pkg/config/config.go
  cni/pkg/install-cni/pkg/install/kubeconfig.go
Labels: cla: yes, release-notes-none, size/M

#31831 Move `istioctl tag` command group to `istioctl revision tag` subcommand
  istioctl/cmd/revision.go
  istioctl/cmd/root.go
  istioctl/cmd/tag.go
  releasenotes/notes/revision-tag-command.yaml
  tests/integration/pilot/revisions/revision_tag_test.go
Labels: area/user experience, cla: yes, size/S

#31911 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31875 Add vm to authz integration tests
  tests/integration/security/authorization_test.go
  tests/integration/security/testdata/authz/v1beta1-jwt.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-mtls.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-workload-ns-root.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-workload-ns1.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-workload-ns2.yaml.tmpl
Labels: area/security, cherrypick/release-1.9, cla: yes, release-notes-none, size/XL

#31866 Fix allows repeated headers
  pkg/kube/apimirror/probe.go
Labels: cla: yes, release-notes-none, size/XS

#31921 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31897 refactor filter chain match options
  pilot/pkg/networking/core/v1alpha3/filterchain_options.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#31922 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31932 Automated branching step 1
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/S

#31864 Fix backoff max limit
  pilot/pkg/model/jwks_resolver.go
Labels: cla: yes, release-notes-none, size/XS

#31919 kube-inject improvements
  istioctl/cmd/kubeinject.go
  tests/integration/pilot/istioctl_test.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/M

#31933 Log discovery requests when logging at debug level
  istioctl/cmd/proxystatus.go
  istioctl/cmd/version.go
  pkg/adsc/adsc.go
Labels: cla: yes, size/S

#31937 shifting test: use 2 pods when vms are disabled
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/S

#31940 [release-1.10] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/M

#31912 mtls checker handles dr explicitly setting ISTIO_MUTUAL
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters_test.go
Labels: cla: yes, release-notes-none, size/L

#31947 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31877 Add vm to TestAuthorization_Deny and TestAuthorization_NegativeMatch
  tests/integration/security/authorization_test.go
  tests/integration/security/testdata/authz/v1beta1-deny.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-negative-match.yaml.tmpl
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/L

#31942 Include EDS in configdump
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/XS

#31952 Automator: update common-files@release-1.10 in istio/istio@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31949 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31608 add envoy filter stats
  pilot/pkg/features/pilot.go
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#31960 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31958 Automator: update common-files@release-1.8 in istio/istio@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31944 Automator: update istio/api@release-1.10 dependency in istio/istio@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31959 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31950 Add Traffic Verification to Helm Install Test
  tests/integration/helm/install_test.go
Labels: cla: yes, ok-to-test, size/XS

#31953 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31968 fix ext-authz flaky test
  pilot/pkg/security/authz/builder/extauthz.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#31881 filter out non mTLS cross network endpoints (#30705)
  pilot/pkg/model/authentication.go
  pilot/pkg/model/xds_cache.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/xds/eds_sh_test.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/ep_filters_test.go
  pilot/pkg/xds/mesh_network_test.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/xds_cache_test.go
  pkg/test/framework/config.go
  releasenotes/notes/30705.yaml
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, size/XXL

#31975 [1.8] Improve Ingress support in test framework (#31798)
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/ingress/interface.go
  pkg/test/framework/components/istio/util.go
Labels: cla: yes, release-notes-none, size/M

#31951 Enhance istio pre-check to use analyzer format, add additional checks
  galley/pkg/config/analysis/diag/messages.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  istioctl/cmd/precheck.go
  istioctl/cmd/root.go
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/pre-check_test.go
  istioctl/pkg/install/verify.go
  releasenotes/notes/28915.yaml
Labels: area/user experience, cla: yes, size/XXL

#31924 doc: exist -> exists copy in helmreconciler prune
  operator/pkg/helmreconciler/prune.go
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#31962 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31954 Bump 1.10 to 1.11 in master
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.11.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.11.yaml
  operator/version/version.go
  pilot/pkg/xds/bench_test.go
  prow/release-commit.sh
  tools/packaging/common/istio-start.sh
Labels: area/test and release, cla: yes, release-notes-none, size/XXL

#31978 add release notes for `istioctl x internal-debug`
  releasenotes/notes/31338.yaml
Labels: cla: yes, size/XS

#31972 [1.9 backport] Allow setting SNI explicitly in echo (#31625)
  pkg/test/echo/cmd/client/main.go
  pkg/test/echo/proto/echo.pb.go
  pkg/test/echo/proto/echo.proto
  pkg/test/echo/server/forwarder/http.go
  pkg/test/echo/server/forwarder/protocol.go
Labels: cla: yes, release-notes-none, size/S

#31460 Fix URLFetch does not support folders
  operator/pkg/helm/urlfetcher.go
  operator/pkg/helm/urlfetcher_test.go
Labels: cla: yes, release-notes-none, size/M

#31986 Move setUpstreamProtocol to buildDefaultCluster
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: cla: yes, release-notes-none

#31983 Make `CGO_ENABLED` configurable for gobuild script
  Makefile.core.mk
  common/scripts/gobuild.sh
Labels: cla: yes, release-notes-none, size/XS

#31996 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31917 [CNI] Add repair type label to repaired pod stats.
  cni/pkg/repair/monitoring.go
  cni/pkg/repair/repair.go
  cni/pkg/repair/repair_test.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/L

#31973 [release-1.9] Improve Ingress support in test framework
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/ingress/interface.go
  pkg/test/framework/components/istio/util.go
Labels: cla: yes, release-notes-none, size/M

#31999 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32000 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31961 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31998 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31969 [release-1.9] Add Traffic Verification to Helm Install Test
  tests/integration/helm/install_test.go
Labels: cla: yes, release-notes-none, size/XS

#31970 [release-1.10] Add Traffic Verification to Helm Install Test
  tests/integration/helm/install_test.go
Labels: cla: yes, release-notes-none, size/XS

#31899 clean up connections always
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31963 Automator: update istio/api@release-1.8 dependency in istio/istio@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32001 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31956 [release-1.10] shifting test: use 2 pods when vms are disabled
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: cla: yes, release-notes-none, size/S

#32013 Bump grpc dep
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/XS

#32016 refactor authorization e2e test for better readability
  tests/integration/security/authorization_test.go
  tests/integration/security/testdata/authz/v1beta1-deny.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-negative-match.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-workload-ns-root.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-workload-ns1.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-workload-ns2.yaml.tmpl
Labels: cla: yes, release-notes-none, size/L

#32019 shifting test: use only available splits
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/vm_test.go
Labels: cla: yes, release-notes-none, size/M

#32010 [release-1.8] filter out non mTLS cross network endpoints (#30705)
  pilot/pkg/model/authentication.go
  pilot/pkg/model/xds_cache.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/xds/eds_sh_test.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/ep_filters_test.go
  pilot/pkg/xds/mesh_network_test.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/xds_cache_test.go
  pkg/test/framework/resource/cluster.go
  releasenotes/notes/30705.yaml
  tests/integration/security/authorization_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, size/XXL

#31974 [1.8] Cherrypick improvements to echo client app
  pkg/test/echo/cmd/client/main.go
  pkg/test/echo/proto/echo.pb.go
  pkg/test/echo/proto/echo.proto
  pkg/test/echo/server/forwarder/http.go
  pkg/test/echo/server/forwarder/protocol.go
Labels: cla: yes, release-notes-none, size/M

#31048 Integration testing: support 1.9.0 -> latest and 1.8.1 -> latest upgrades using helm
  tests/integration/helm/install_test.go
  tests/integration/helm/testdata/1.9.0/base.tar.gz
  tests/integration/helm/testdata/1.9.0/gateways/istio-egress.tar.gz
  tests/integration/helm/testdata/1.9.0/gateways/istio-ingress.tar.gz
  tests/integration/helm/testdata/1.9.0/istio-control/istio-discovery.tar.gz
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
  tests/integration/operator/switch_cr_test.go
  tests/integration/operator/verify_test.go
  tests/integration/pilot/ingress_test.go
  tests/util/sanitycheck/sanity_check.go
Labels: area/environments, area/test and release, cla: yes, release-notes-none, size/L

#32029 match delta with ads
  pilot/pkg/xds/delta.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#32028 Improve analyzer msg
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/XS

#31843 Donot honor tls certificate specified in istio mtls mode
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, release-notes-none, size/L

#31977 [release-1.10] Enhance istio pre-check to use analyzer format, add additional checks
  galley/pkg/config/analysis/diag/messages.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  istioctl/cmd/precheck.go
  istioctl/cmd/root.go
  istioctl/pkg/install/pre-check.go
  istioctl/pkg/install/pre-check_test.go
  istioctl/pkg/install/verify.go
  releasenotes/notes/28915.yaml
Labels: cla: yes, release-notes-none, size/XXL

#32018 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31784 Bind localhost to virtualOutbound listener
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/xds/xds_test.go
Labels: cla: yes, release-notes-none, size/XS

#32036 Pick a free unbinded port
  pilot/pkg/bootstrap/server_test.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/M

#32046 [release-1.10] Integration testing: support 1.9.0 -> latest and 1.8.1 -> latest upgrades using helm
  tests/integration/helm/install_test.go
  tests/integration/helm/testdata/1.9.0/base.tar.gz
  tests/integration/helm/testdata/1.9.0/gateways/istio-egress.tar.gz
  tests/integration/helm/testdata/1.9.0/gateways/istio-ingress.tar.gz
  tests/integration/helm/testdata/1.9.0/istio-control/istio-discovery.tar.gz
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
  tests/integration/operator/switch_cr_test.go
  tests/integration/operator/verify_test.go
  tests/integration/pilot/ingress_test.go
  tests/util/sanitycheck/sanity_check.go
Labels: cla: yes, release-notes-none, size/L

#31797 Allow slash characters in env variable values passed to injector #31732
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  releasenotes/notes/31797.yaml
Labels: cherrypick/release-1.10, cla: yes, ok-to-test, size/M

#31981 Fix probe header
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  pkg/kube/apimirror/probe.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#32043 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32042 [release-1.10] Improve analyzer msg
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: cla: yes, release-notes-none, size/XS

#32052 Do not write namespace configmap for k8s cert provider
  pilot/pkg/bootstrap/server.go
Labels: cherrypick/release-1.10, cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#31853 emit metrics for informer watch errors
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/config/aggregate/config.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingressv1/controller.go
  pilot/pkg/config/memory/controller.go
  pilot/pkg/model/config.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/util/informermetric/informerutil.go
  releasenotes/notes/31853.yaml
Labels: cherrypick/release-1.10, cherrypick/release-1.9, cla: yes, size/L

#31980 vm prober send probe to right ip
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/status/server.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/health/health_check.go
  pkg/istio-agent/health/health_check_test.go
  pkg/istio-agent/health/health_probers.go
  pkg/istio-agent/health/health_probers_test.go
  pkg/istio-agent/xds_proxy.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/M

#31885 cleanup inbound listener conflicts
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: cla: yes, release-notes-none, size/S

#32061 [release-1.10] vm prober send probe to right ip
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/status/server.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/health/health_check.go
  pkg/istio-agent/health/health_check_test.go
  pkg/istio-agent/health/health_probers.go
  pkg/istio-agent/health/health_probers_test.go
  pkg/istio-agent/xds_proxy.go
Labels: cla: yes, release-notes-none, size/M

#32062 use test framework imagepullsecret in testcustomgateway
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/image/settings.go
  tests/integration/pilot/ingress_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/M

#32006 Skip first party jwt on k8s 1.21+
  pkg/kube/mock_client.go
  pkg/kube/version.go
  pkg/kube/version_test.go
  pkg/test/framework/analyzer.go
  pkg/test/framework/components/cluster/cluster.go
  pkg/test/framework/components/cluster/topology.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/suite.go
  tests/integration/helm/install_test.go
  tests/integration/pilot/endpointslice/endpointslice_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/main_test.go
  tests/integration/pilot/mcs/serviceexport_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/revisioncmd/revision_view_test.go
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/filebased_tls_origination/main_test.go
  tests/integration/security/mtls_first_party_jwt/main_test.go
  tests/integration/security/sds_egress/main_test.go
  tests/integration/security/sds_tls_origination/main_test.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/L

#32066 [release-1.10] Skip first party jwt on k8s 1.21+
  pkg/kube/mock_client.go
  pkg/kube/version.go
  pkg/kube/version_test.go
  pkg/test/framework/analyzer.go
  pkg/test/framework/components/cluster/cluster.go
  pkg/test/framework/components/cluster/topology.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/suite.go
  tests/integration/helm/install_test.go
  tests/integration/pilot/endpointslice/endpointslice_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/main_test.go
  tests/integration/pilot/mcs/serviceexport_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/revisioncmd/revision_view_test.go
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/filebased_tls_origination/main_test.go
  tests/integration/security/mtls_first_party_jwt/main_test.go
  tests/integration/security/sds_egress/main_test.go
  tests/integration/security/sds_tls_origination/main_test.go
Labels: cla: yes, release-notes-none, size/L

#31718 Add operator options flag into integration test framework.
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  pkg/test/framework/components/istio/operator.go
Labels: cla: yes, release-notes-none, size/M

#31880 Add vm to TestAuthorization_IngressGateway and TestAuthorization_EgressGateway
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/testdata/authz/v1beta1-egress-gateway.yaml.tmpl
  tests/integration/security/testdata/authz/v1beta1-ingress-gateway.yaml.tmpl
  tests/integration/security/testdata/requestauthn/ingress.yaml.tmpl
  tests/integration/security/util/framework.go
Labels: cherrypick/release-1.10, cherrypick/release-1.9, cla: yes, release-notes-none, size/XL

#31905 Fix race condition in mesh config update
  pkg/config/mesh/watcher.go
Labels: cherrypick/release-1.10, cherrypick/release-1.9, cla: yes, release-notes-none, size/S

#32074 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31893 add integration test for use client protocol
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#32083 Add ROOT env var
  tools/build-base-images.sh
Labels: cherrypick/release-1.10, cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#32086 [release-1.8] Add ROOT env var
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/XS

#32087 [release-1.9] Add ROOT env var
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/XS

#32085 [release-1.10] Add ROOT env var
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/XS

#32090 [release-1.10] Update to new base image
  Makefile.core.mk
Labels: cla: yes, release-notes-none, size/XS

#32022 staticvm: allow specifying instance ip
  pkg/test/framework/components/cluster/staticvm/staticvm.go
  pkg/test/framework/components/cluster/staticvm/staticvm_test.go
  pkg/test/framework/components/echo/staticvm/workload.go
Labels: cla: yes, release-notes-none, size/M

#31945 Add vm to TestAuthorization_TCP
  tests/integration/security/authorization_test.go
  tests/integration/security/testdata/authz/v1beta1-tcp.yaml.tmpl
  tests/integration/security/util/framework.go
Labels: cherrypick/release-1.10, cherrypick/release-1.9, cla: yes, release-notes-none, size/L

#32091 Switch warning to error per TOC feedback
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/XS

#31923 Fix read and write confilicts
  pkg/kube/client.go
  pkg/kube/rpc_creds.go
  pkg/kube/rpc_creds_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#32053 Revert "Bind localhost to virtualOutbound listener "
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/xds/xds_test.go
Labels: cla: yes, release-notes-none, size/XS

#32093 [release-1.10] Switch warning to error per TOC feedback
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
Labels: cla: yes, release-notes-none, size/XS

#32089 [release-1.10] use test framework imagepullsecret in testcustomgateway
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/image/settings.go
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/M

#31749 Ability to tap into istio-agent to route debug messages to istiod
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/gen.go
  pkg/istio-agent/README.md
  pkg/istio-agent/agent.go
  pkg/istio-agent/agent_test.go
  pkg/istio-agent/xds_proxy.go
  releasenotes/notes/agent-xds-piggyback.yaml
  tests/integration/pilot/piggyback_test.go
Labels: area/user experience, cla: yes, size/L

#32077 Remove unused stats
  samples/httpbin/sample-client/fortio-deploy.yaml
Labels: cla: yes, release-notes-none, size/S

#32097 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32094 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32078 [release-1.10] shifting test: use only available splits
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/vm_test.go
Labels: cla: yes, release-notes-none, size/M

#32099 Use GetValue instead of util.BoolValue
  istioctl/cmd/revision.go
  operator/cmd/mesh/install.go
  operator/pkg/component/component.go
  operator/pkg/util/util.go
  operator/pkg/util/util_test.go
Labels: area/environments, cla: yes, release-notes-none, size/M

#32103 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32107 [release-1.8] Fix probe header
  pilot/cmd/pilot-agent/status/server.go
Labels: cla: yes, release-notes-none, size/S

#30750 Allow setting concurrency in ProxyConfig for gateway
  pilot/cmd/pilot-agent/config/config.go
  pilot/cmd/pilot-agent/config/config_test.go
Labels: cla: yes, release-notes-none, size/S

#32104 [release-1.10] Fix probe header
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  pkg/kube/apimirror/probe.go
Labels: cla: yes, release-notes-none, size/L
