Repository istio/istio, pull requests merged in 2021-11, with the labels that each got.

#35810 [release-1.12] Update deps
  docker/Dockerfile.distroless
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: size/S, cla: yes, release-notes-none

#35685 Add istio rev support to adsc & xds config controller
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/model/context.go
  pkg/adsc/adsc.go
  pkg/adsc/adsc_test.go
  pkg/config/model.go
Labels: ok-to-test, size/M, cla: yes, release-notes-none

#35817 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35806 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35819 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35818 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35823 Force gzip to overwrite existing archives in docker.save target
  tools/istio-docker.mk
Labels: area/test and release, size/XS, cla: yes, release-notes-none

#35822 clean up codes, reduce unnecessary logic
  pilot/pkg/request/command.go
Labels: area/user experience, size/XS, cla: yes, release-notes-none

#35820 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35746 Enable TestKubeInject in istiodremote topology
  istioctl/cmd/kubeinject.go
  tests/integration/pilot/istioctl_test.go
Labels: size/M, cla: yes, release-notes-none

#35836 Fix filterchain match's incorrect early match
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
Labels: area/networking, size/L, cla: yes, release-notes-none

#35834 Expose canonical-name and canonical-revision to grpc-agent container
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
  pkg/kube/inject/testdata/inject/grpc-agent.yaml.injected
Labels: area/networking, ok-to-test, size/XS, cla: yes, release-notes-none

#35674 multicluster: run a single remote secrets controller
  galley/pkg/config/analysis/analyzers/multicluster/meshnetworks.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/credentials/kube/leak_test.go
  pilot/pkg/credentials/kube/multicluster.go
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/credentials/kube/secrets_test.go
  pilot/pkg/credentials/model.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  pkg/kube/multicluster/secretcontroller.go
  pkg/kube/multicluster/secretcontroller_test.go
  pkg/test/framework/components/istio/operator.go
Labels: size/XL, cla: yes, release-notes-none, cherrypick/release-1.12

#35854 add release note for ext-authz changes in Envoy
  releasenotes/notes/35480-ext-authz.yaml
Labels: area/security, size/S, cla: yes

#35708 added code for jwt https server
  samples/jwt-server/src/main.go
  samples/jwt-server/src/main_test.go
  samples/jwt-server/testdata/README.MD
  samples/jwt-server/testdata/server.crt
  samples/jwt-server/testdata/server.key
Labels: area/security, ok-to-test, size/L, cla: yes, release-notes-none

#35848 Add DeepCopy to echo CallOptions
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/istio/ingress.go
Labels: size/S, cla: yes, release-notes-none

#35849 echo: support dualstack --bind-localhost
  pkg/test/echo/server/instance.go
Labels: size/M, cla: yes, release-notes-none

#35857 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35832 Wait for pods to be deleted when cleaning up operators
  tests/integration/operator/switch_cr_test.go
Labels: area/test and release, ok-to-test, size/S, cla: yes, release-notes-none

#35825 `Instance.SubsetOf` should check if key exists
  pkg/config/labels/instance.go
  pkg/config/labels/instance_test.go
Labels: area/networking, ok-to-test, size/M, cla: yes, release-notes-none

#35841 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35852 mcs test: backoff more aggresively
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
Labels: size/S, cla: yes, release-notes-none

#35875 Automator: update proxy@release-1.12 in istio/istio@release-1.12
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35853 tf: fix backoff
  pkg/test/util/retry/retry.go
Labels: size/XS, cla: yes, release-notes-none

#35873 Use targetPort for gateway tests
  tests/integration/pilot/gw_topology_test.go
  tests/integration/pilot/ingress_test.go
Labels: size/XS, cla: yes, release-notes-none

#35877 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35878 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35881 Automator: update proxy@release-1.12 in istio/istio@release-1.12
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35884 enable multicluster workload entry by default
  pilot/pkg/features/pilot.go
  releasenotes/notes/35883.yaml
  tests/integration/iop-integration-test-defaults-with-quic.yaml
  tests/integration/iop-integration-test-defaults.yaml
Labels: size/S, cla: yes, cherrypick/release-1.12

#35879 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35851 ipv6: fix VM healthcheck ipv6 detection
  pilot/cmd/pilot-agent/options/agent.go
Labels: size/XS, cla: yes, release-notes-none

#35890 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35883 enable multicluster headless by default
  pilot/pkg/features/pilot.go
  releasenotes/notes/35883.yaml
  releasenotes/notes/35884.yaml
  tests/integration/iop-integration-test-defaults-with-quic.yaml
  tests/integration/iop-integration-test-defaults.yaml
Labels: size/S, cla: yes, cherrypick/release-1.12

#35874 Cleanup duplicate pilot SAN log
  pkg/istio-agent/agent.go
Labels: size/XS, cla: yes, release-notes-none

#35882 docker: rewrite make+bash with a simple golang tool
  pkg/test/env/istio.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tools/docker
  tools/docker-builder/main.go
  tools/docker-builder/types.go
  tools/docker-copy.sh
  tools/istio-docker.mk
Labels: size/XL, cla: yes, release-notes-none

#35886 [release-1.12] enable multicluster workload entry by default
  pilot/pkg/features/pilot.go
  releasenotes/notes/35883.yaml
  tests/integration/iop-integration-test-defaults-with-quic.yaml
  tests/integration/iop-integration-test-defaults.yaml
Labels: size/S, cla: yes, release-notes-none

#35847 Support WE for IPv6
  pilot/pkg/controller/workloadentry/workloadentry_controller.go
Labels: size/XS, cla: yes, release-notes-none

#35814 [release-1.12] Make port forwarder resilient to broken connection.
  pkg/kube/portforwarder.go
Labels: size/M, cla: yes, release-notes-none

#35903 Bump buildkit version
  prow/lib.sh
  tools/docker-builder/main.go
Labels: size/XS, cla: yes, release-notes-none

#35904 Skip flaky mcs test
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
Labels: size/XS, cla: yes, release-notes-none

#35908 Automator: update proxy@release-1.12 in istio/istio@release-1.12
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35909 do not allow priv escalation in istiod
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: size/XS, cla: yes, release-notes-none

#35762 update JWT claim routing implementation
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_jwtclaimroute.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/jwtclaimroute.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/util/constant/constant.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  tests/integration/pilot/common/routing.go
Labels: area/security, size/L, cla: yes, release-notes-none, cherrypick/release-1.12

#35911 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35912 Fix echo dualstack
  pkg/test/echo/server/instance.go
Labels: size/XS, cla: yes, release-notes-none

#35914 Bump jwt-server to 0.6
  samples/jwt-server/jwt-server.yaml
  samples/jwt-server/src/Makefile
Labels: size/XS, cla: yes, release-notes-none

#35889 Update to fix hadolint warning
  samples/bookinfo/src/productpage/Dockerfile
Labels: size/XS, cla: yes, release-notes-none

#35913 optimize codes, the logic that apply pilot default args should be placed together
  pilot/pkg/bootstrap/options.go
Labels: area/user experience, size/XS, cla: yes, release-notes-none

#35910 [release-1.12] update JWT claim routing implementation
  galley/pkg/config/analysis/analyzers/all.go
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_jwtclaimroute.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/jwtclaimroute.go
  galley/pkg/config/analysis/msg/messages.gen.go
  galley/pkg/config/analysis/msg/messages.yaml
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/util/constant/constant.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  tests/integration/pilot/common/routing.go
Labels: size/L, cla: yes, release-notes-none

#35838 [release-1.12] Fix filterchain match's incorrect early match
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
Labels: size/L, cla: yes, release-notes-none

#35850 Use v6 DNS resolution when we are on a ipv6 *only* proxy
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: size/S, cla: yes, release-notes-none

#35842 [release-1.12] multicluster: run a single remote secrets controller
  galley/pkg/config/analysis/analyzers/multicluster/meshnetworks.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/credentials/kube/leak_test.go
  pilot/pkg/credentials/kube/multicluster.go
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/credentials/kube/secrets_test.go
  pilot/pkg/credentials/model.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  pkg/kube/multicluster/secretcontroller.go
  pkg/kube/multicluster/secretcontroller_test.go
  pkg/test/framework/components/istio/operator.go
Labels: size/XL, cla: yes, release-notes-none

#35863 Send healthcheck after lds request has been sent
  pilot/pkg/xds/ads.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_test.go
Labels: area/networking, size/L, cla: yes, release-notes-none

#35813 [release-1.12] Fix label injection enabled with policy=disabled
  pkg/kube/inject/inject.go
  pkg/kube/inject/webhook_test.go
  releasenotes/notes/inject-disabled.yaml
Labels: size/M, cla: yes, release-notes-none

#35816 [release-1.12] change iptables probe port to string
  pilot/cmd/pilot-agent/status/grpcready/probe.go
  pilot/cmd/pilot-agent/status/ready/probe.go
  pilot/pkg/features/pilot.go
  pkg/bootstrap/config.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: size/S, cla: yes, release-notes-none

#35922 [release-1.12] Skip flaky mcs test
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
Labels: size/XS, cla: yes, release-notes-none

#35844 Bump gRPC to v1.42.0
  go.mod
  go.sum
  pilot/pkg/networking/grpcgen/grpcecho_test.go
  pilot/pkg/networking/grpcgen/lds.go
Labels: size/M, cla: yes, release-notes-none, cherrypick/release-1.12

#35532 Implement ProxyConfig CR
  pilot/pkg/model/proxy_config.go
  pilot/pkg/model/proxy_config_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/xds/pcds.go
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  tests/integration/pilot/proxyconfig/proxyconfig_test.go
Labels: size/XL, cla: yes, release-notes-none

#35927 add release note for jwt claim routing
  releasenotes/notes/jwt-route.yaml
Labels: area/security, size/XS, cla: yes, cherrypick/release-1.12

#35933 Fix wrong ctx usage leading to panic on failure
  tests/integration/security/sds_ingress/util/util.go
Labels: size/S, cla: yes, release-notes-none

#35929 [release-1.12] add release note for jwt claim routing
  releasenotes/notes/jwt-route.yaml
Labels: size/XS, cla: yes, release-notes-none

#35919 Fix service and cluster update missing reason
  pilot/pkg/model/push_context.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/xds/monitoring.go
Labels: area/networking, size/XS, cla: yes, release-notes-none

#35458 fix istioctl precheck unused code logic
  istioctl/cmd/precheck.go
Labels: size/XS, cla: yes, release-notes-none

#35897 Config translate returns value type
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/gen/types.go.tmpl
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/schema/fuzz_test.go
  tests/fuzz/config_validation_fuzzer.go
Labels: size/M, cla: yes, release-notes-none

#35946 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35931 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35938 [release-1.12] Fix service and cluster update missing reason
  pilot/pkg/model/push_context.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/xds/monitoring.go
Labels: size/XS, cla: yes, release-notes-none

#35795 configure request without query access log formatter
  pilot/pkg/networking/core/v1alpha3/accesslog.go
Labels: size/S, cla: yes, release-notes-none

#35872 Support distroless in piggyback test
  tests/integration/pilot/piggyback_test.go
Labels: size/S, cla: yes, release-notes-none, cherrypick/release-1.12

#35950 enable multicluster headless by default (#35883)
  pilot/pkg/features/pilot.go
  releasenotes/notes/35883.yaml
  releasenotes/notes/35884.yaml
  tests/integration/iop-integration-test-defaults-with-quic.yaml
  tests/integration/iop-integration-test-defaults.yaml
Labels: size/S, cla: yes

#35667 Add default resources to coreDump container
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  pkg/kube/inject/testdata/inject/enable-core-dump-annotation.yaml.injected
  pkg/kube/inject/testdata/inject/enable-core-dump.yaml.injected
Labels: size/L, cla: yes, release-notes-none

#35691 Fix alt-host generation when hostname has a partial overlap with cluster domain
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  releasenotes/notes/vhost-name-generation.yaml
Labels: size/L, cla: yes

#35947 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35888 [release-1.12] mcs test: backoff more aggresively
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
Labels: size/S, cla: yes, release-notes-none

#35926 [release-1.12] Bump gRPC to v1.42.0
  go.mod
  go.sum
  pilot/pkg/networking/grpcgen/grpcecho_test.go
  pilot/pkg/networking/grpcgen/lds.go
Labels: size/M, cla: yes, release-notes-none

#35668 Add WasmPlugin integration test
  pilot/pkg/model/extensions.go
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
Labels: size/M, cla: yes, release-notes-none, cherrypick/release-1.12

#35957 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35954 [release-1.12] Add WasmPlugin integration test
  pilot/pkg/model/extensions.go
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
Labels: size/M, cla: yes, release-notes-none

#35961 Automator: update istio/client-go@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35963 Automator: update istio/client-go@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35918 Delete GetValidatingWebhooksWithRevision func
  istioctl/pkg/tag/util.go
Labels: ok-to-test, size/S, cla: yes, release-notes-none

#35960 Automator: update common-files@release-1.12 in istio/istio@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35956 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35976 [release-1.12] Switch port naming for generated Service
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
Labels: size/S, cla: yes, release-notes-none

#35975 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35952 [release-1.12] Support distroless in piggyback test
  tests/integration/pilot/piggyback_test.go
Labels: size/S, cla: yes, release-notes-none

#35934 Fix DefaultHTTPRetryPolicy for gateways
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: size/XS, cla: yes, release-notes-none, cherrypick/release-1.12

#35965 Enable/Fix multi-arch build for DOCKER_V2_BUILDER
  tools/docker
Labels: ok-to-test, size/S, cla: yes, release-notes-none

#35962 Automator: update istio/api@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35974 Fix race when registry added after all the previous existing ones hav…
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
Labels: area/networking, size/M, cla: yes, release-notes-none, cherrypick/release-1.12

#35945 Delete redundant service handler
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
Labels: area/networking, ok-to-test, size/S, cla: yes, release-notes-none

#35982 [release-1.12] Revert "Scaffolding for ProxyConfig implementation (#35602)"
  galley/testdatasets/validation/dataset/networking-v1beta1-ProxyConfig-invalid.yaml
  galley/testdatasets/validation/dataset/networking-v1beta1-ProxyConfig-valid.yaml
  pilot/cmd/pilot-agent/config/config.go
  pilot/pkg/config/kube/crdclient/gen/main.go
  pilot/pkg/config/kube/crdclient/gen/types.go.tmpl
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/mesh/mesh_test.go
  pkg/config/schema/collections/collections.agent.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/kube/inject/validate.go
  pkg/webhooks/validation/server/server.go
Labels: size/L, cla: yes, release-notes-none

#35983 Replace openssl with echo client
  pkg/test/echo/common/scheme/scheme.go
  pkg/test/echo/server/forwarder/protocol.go
  pkg/test/echo/server/forwarder/tls.go
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/common/call.go
  tests/integration/pilot/common/routing.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/util/cert/cert.go
Labels: size/L, cla: yes, release-notes-none

#35978 [release-1.12] Fix DefaultHTTPRetryPolicy for gateways
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: size/XS, cla: yes, release-notes-none

#35984 Allow empty env var at CNI Daemonset.
  cni/pkg/cmd/root.go
Labels: size/XS, cla: yes, release-notes-none

#35979 [release-1.12] Fix race when registry added after all the previous existing ones hav…
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
Labels: size/M, cla: yes, release-notes-none

#35782 Fix TestGateway for TCP services
  tests/integration/pilot/ingress_test.go
Labels: size/XS, cla: yes, release-notes-none

#35977 Automator: update istio/client-go@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/M, cla: yes, auto-merge, release-notes-none

#35988 [release-1.12] Update deps
  go.mod
  go.sum
  istio.deps
  pilot/docker/Dockerfile.proxyv2
  prow/release-commit.sh
Labels: size/S, cla: yes, release-notes-none

#35985 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35987 Ensure cert order is deterministic
  pkg/test/echo/client/parsedresponse.go
  tests/integration/pilot/common/routing.go
  tests/integration/security/util/cert/cert.go
Labels: size/M, cla: yes, release-notes-none

#35763 Add support for recursive file watch to pilot
  pilot/pkg/config/monitor/file_snapshot.go
  pilot/pkg/config/monitor/monitor.go
Labels: size/M, cla: yes, release-notes-none

#35998 test cluster-local config using service subsets
  tests/integration/pilot/multicluster_test.go
Labels: size/M, cla: yes, release-notes-none

#35990 ignore FQDN endpointslice
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/M, cla: yes, release-notes-none

#36006 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, cla: yes, auto-merge, release-notes-none

#35930 Set sysctls for gateway ports
  manifests/charts/gateway/README.md
  manifests/charts/gateway/templates/deployment.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
Labels: size/L, cla: yes, release-notes-none, cherrypick/release-1.12

#36007 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36008 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#36012 [release-1.12] Set sysctls for gateway ports
  manifests/charts/gateway/README.md
  manifests/charts/gateway/templates/deployment.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
Labels: size/L, cla: yes, release-notes-none

#36009 tf: do not cleanup external ServiceEntry
  tests/integration/pilot/common/apps.go
Labels: size/XS, cla: yes, release-notes-none

#35986 Add securityContext to CNI DaemonSet to run as root.
  cni/pkg/cmd/root.go
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: size/S, cla: yes, release-notes-none

#35876 Document supported address values
  pilot/pkg/config/kube/gateway/conversion.go
Labels: size/S, cla: yes, release-notes-none

#36020 make log more readable
  pilot/pkg/xds/discovery.go
Labels: cla: yes, release-notes-none

#36004 echo: return errors in dns
  pkg/test/echo/server/forwarder/dns.go
  tests/integration/pilot/common/routing.go
Labels: size/M, cla: yes, release-notes-none

#36010 Start using metallb for IPv6
  prow/integ-suite-kind.sh
Labels: size/XS, cla: yes, release-notes-none

#36013 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35994 Enable building for base images
  tools/docker-builder/main.go
Labels: ok-to-test, size/XS, cla: yes, release-notes-none

#36017 Fix cdsz endpoint not found
  tools/bug-report/pkg/common/common.go
Labels: size/XS, cla: yes, release-notes-none

#36003 Update proxyv2 distroless image to reduce surface
  pilot/docker/Dockerfile.proxyv2
Labels: size/XS, cla: yes, release-notes-none

#36015 Fix panic in discoverynamespaces.go
  pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
Labels: ok-to-test, size/S, cla: yes, release-notes-none

#36023 Automator: update common-files@master in istio/istio@master
  Makefile
  common/.commonfiles.sha
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36025 pilot-agent request: add allowlist for debug ports
  pilot/cmd/pilot-agent/request.go
Labels: size/S, cla: yes, release-notes-none

#36026 Automator: update istio/gogo-genproto@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36028 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36024 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36030 Fix bug in telemetry causing multiple duplicate filters
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
Labels: size/M, cla: yes, release-notes-none, cherrypick/release-1.12

#36033 fix proxyless gRPC mTLS
  pilot/pkg/networking/grpcgen/grpcecho_test.go
  pilot/pkg/networking/grpcgen/grpcgen.go
  pilot/pkg/networking/grpcgen/lds.go
  pkg/istio-agent/grpcxds/grpc_bootstrap.go
  pkg/istio-agent/testdata/grpc-bootstrap.json
Labels: size/M, cla: yes, release-notes-none, cherrypick/release-1.12

#36029 [release-1.12] ignore FQDN endpointslice
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/M, cla: yes, release-notes-none

#36005 Tweaks to test code to support IPv6
  pkg/kube/portforwarder.go
  pkg/test/framework/components/echo/staticvm/workload.go
  pkg/test/framework/components/gcemetadata/kube.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/opentelemetry/kube.go
  pkg/test/framework/components/stackdriver/kube.go
  pkg/test/framework/components/zipkin/kube.go
  pkg/test/framework/label/labels.go
  samples/ratelimit/rate-limit-service.yaml
  tests/integration/pilot/common/traffic.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/jwt_test.go
  tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
  tests/integration/telemetry/stats/prometheus/api/stats_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/stats_filter_test.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go
Labels: size/M, cla: yes, release-notes-none

#36027 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36038 Revert /host prefix from CNI log volume mount path.
  cni/pkg/cmd/root.go
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: size/XS, cla: yes, release-notes-none

#36035 [release-1.12] Fix bug in telemetry causing multiple duplicate filters
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
Labels: size/M, cla: yes, release-notes-none

#36036 [release-1.12] fix proxyless gRPC mTLS
  pilot/pkg/networking/grpcgen/grpcecho_test.go
  pilot/pkg/networking/grpcgen/grpcgen.go
  pilot/pkg/networking/grpcgen/lds.go
  pkg/istio-agent/grpcxds/grpc_bootstrap.go
  pkg/istio-agent/testdata/grpc-bootstrap.json
Labels: size/M, cla: yes, release-notes-none

#36034 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36039 Automator: update proxy@release-1.12 in istio/istio@release-1.12
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36043 do not generate debug output for ndsz if dns is not enabled
  pilot/pkg/xds/debug.go
Labels: area/networking, size/XS, cla: yes, release-notes-none

#36042 Rebuilding docker-builder if code changed
  tools/docker
Labels: ok-to-test, size/XS, cla: yes, release-notes-none

#36041 Fix docker.save tar targets
  tools/istio-docker.mk
Labels: area/test and release, size/XS, cla: yes, release-notes-none

#36057 Automator: update istio/pkg@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#34971 use EndpointSlices by default in 1.21
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/test/framework/components/istio/operator.go
  releasenotes/notes/endpoint-slice.yaml
  tests/integration/pilot/endpointslice/endpointslice_test.go
Labels: size/M, cla: yes

#36047 Add time flag validation to bug-report
  tools/bug-report/pkg/bugreport/flags.go
Labels: area/test and release, area/user experience, size/XS, cla: yes, release-notes-none

#36031 [release-1.12] pilot-agent request: add allowlist for debug ports
  pilot/cmd/pilot-agent/request.go
Labels: size/S, cla: yes, release-notes-none

#36058 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
  licenses/github.com/ghodss/yaml/LICENSE
Labels: size/M, cla: yes, auto-merge, release-notes-none

#36060 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36064 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36001 add more e2e tests for authz dry-run with TCP traffic
  tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_allow_matched.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_both_matched.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_deny_matched.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_allow_matched.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_both_matched.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_deny_matched.json.tmpl
Labels: area/security, size/L, cla: yes, release-notes-none

#35706 Address branch cutting expectations
  RELEASE_BRANCHES.md
Labels: area/test and release, size/M, cla: yes, release-notes-none

#36070 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#36032 [release-1.11] pilot-agent request: add allowlist for debug ports
  pilot/cmd/pilot-agent/request.go
Labels: size/S, cla: yes, release-notes-none

#36065 [echo] Make readiness check timeout configurable.
  pkg/test/framework/components/echo/common/config.go
  pkg/test/framework/components/echo/flags.go
Labels: cla: yes, release-notes-none
