Repository istio/istio, pull requests merged in 2021-09, with the labels that each got.

#34085 Fix crash in tpath
  operator/pkg/tpath/tree.go
  tests/fuzz/testdata/FuzzTranslateFromValueToSpec/5041840540745728
Labels: size/XS, cla: yes, release-notes-none

#34958 Delete the duplicated definition method RegisterService
  pkg/test/echo/server/endpoint/grpc.go
Labels: size/XS, cla: yes, release-notes-none

#34976 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#34977 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#34948 Enable ratelimit config reload automatically when the configMap has been updated
  samples/ratelimit/rate-limit-service.yaml
Labels: size/XS, cla: yes, release-notes-none

#34961 Fix Deployment namespace bug in image: auto analyzer
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/injection/image-auto.go
  galley/pkg/config/analysis/analyzers/testdata/image-auto.yaml
Labels: cla: yes, release-notes-none, cherrypick/release-1.10, cherrypick/release-1.11

#34996 [release-1.10] Fix Deployment namespace bug in image: auto analyzer
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/injection/image-auto.go
  galley/pkg/config/analysis/analyzers/testdata/image-auto.yaml
Labels: size/XS, cla: yes, release-notes-none

#34991 [release-1.9] Backport destination rule does not trigger LDS 1.9
  pilot/pkg/xds/lds.go
  releasenotes/notes/34944.yaml
Labels: ok-to-test, size/M, cla: yes, release-notes-none

#34998 Fix quic test on old k8s versions
  tests/integration/security/sds_ingress/quic/ingress_test.go
Labels: size/S, cla: yes, release-notes-none

#34993 Bump up default grpc transport settings for adsc.
  pkg/adsc/adsc.go
Labels: size/S, cla: yes, release-notes-none

#34800 add echo-grpc sample for doc
  samples/grpc-echo/grpc-echo.yaml
Labels: size/L, cla: yes, release-notes-none, cherrypick/release-1.11

#34923 remove pushVersion from route cache key
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache.go
Labels: size/XS, cla: yes, release-notes-none

#34978 rm PILOT_USE_TARGET_PORT_FOR_GATEWAY_ROUTES
  pilot/pkg/features/pilot.go
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: size/M, cla: yes, release-notes-none

#34928 set gateway sidecarscope from getSidecarScope
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
Labels: area/networking, size/M, cla: yes, release-notes-none

#35006 Require Istio 1.11 for MCS test
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
Labels: area/test and release, size/XS, cla: yes, release-notes-none

#35003 iptables: fix OUTPUT chain for exclude nic
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/testdata/basic-exclude-nic.golden
  tools/istio-iptables/pkg/cmd/testdata/tproxy.golden
  tools/istio-iptables/pkg/config/config.go
Labels: area/networking, size/S, cla: yes, release-notes-none

#34834 Fuzzing: Bring back FuzzValidateClusters
  tests/fuzz/oss_fuzz_build.sh
Labels: area/test and release, area/perf and scalability, ok-to-test, size/XS, cla: yes, release-notes-none

#35007 1.10: clean up connections always (#31899)
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
Labels: size/M, cla: yes, release-notes-none

#34774 Allow http proxy to be enabled per workload instead of global.
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: size/M, cla: yes, release-notes-none

#34878 [release-1.10] fix `istioctl analyze` deployment analyzer ignoring service namespaces
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/deployment/services.go
  galley/pkg/config/analysis/analyzers/testdata/deployment-multi-service-different-ns.yaml
  releasenotes/notes/34847.yaml
Labels: size/M, cla: yes, release-notes-none

#35000 Allow specifying an IP:port for istiod address.
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pilot/cmd/pilot-agent/options/security.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
  pkg/security/security.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
Labels: size/S, cla: yes, release-notes-none

#34808 [release-1.10] Improve injection performance
  pkg/kube/inject/template.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: size/XS, cla: yes, release-notes-none

#34946 fix envoy agent exit bug
  pkg/envoy/agent.go
Labels: area/networking, size/XS, cla: yes, release-notes-none

#35008 Keep adsz output in deterministic order
  pilot/pkg/xds/debug.go
Labels: size/XS, cla: yes, release-notes-none

#34982 revise admin log to be more formatted like other commands
  istioctl/cmd/istiodconfig.go
  istioctl/cmd/istiodconfig_test.go
  releasenotes/notes/34982.yaml
Labels: size/S, cla: yes, release-notes-none

#35009 Add release note for gateway v1alpha2
  releasenotes/notes/gateway-v1alpha2.yaml
Labels: size/XS, cla: yes

#34986 add flag to control cluster telemetry metadata
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/util/util.go
Labels: area/networking, size/S, cla: yes, release-notes-none

#34951 [Release 1.11] Fix misue service's pointer address in map
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  releasenotes/notes/34900.yaml
Labels: size/M, cla: yes

#35018 avoid using vm[0] in locality test
  tests/integration/pilot/locality_test.go
Labels: size/M, cla: yes, release-notes-none, cherrypick/release-1.11

#34999 remote poc: configure client + setup script
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/xds/filters/filters.go
  poc/.gitignore
  poc/client-l7.yaml
  poc/client.yaml
  poc/config.yaml
  poc/up.sh
Labels: size/L, cla: yes

#35005 [release-1.11] add echo-grpc sample for doc
  samples/grpc-echo/grpc-echo.yaml
Labels: size/L, cla: yes, release-notes-none

#35020 clean up connections always (#31899) (#35007)
  pilot/pkg/xds/ads.go
Labels: size/M, cla: yes, release-notes-none

#34997 [release-1.11] Fix Deployment namespace bug in image: auto analyzer
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/injection/image-auto.go
  galley/pkg/config/analysis/analyzers/testdata/image-auto.yaml
  releasenotes/notes/34961.yaml
Labels: size/S, cla: yes

#35026 Return NOT_FOUND when WorkloadEntry cannot be found
  pilot/pkg/controller/workloadentry/workloadentry_controller.go
Labels: area/networking, ok-to-test, size/XS, cla: yes, release-notes-none

#35025 Cleanup eastwest gateway install
  samples/multicluster/gen-eastwest-gateway.sh
Labels: size/S, cla: yes, release-notes-none

#34924 remove pushVersion from cluster cache key
  pilot/pkg/model/authentication.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/xds/endpoint_builder.go
Labels: size/M, cla: yes, release-notes-none

#35028 Change workload not found error to FAILED_PRECONDITION
  pilot/pkg/controller/workloadentry/workloadentry_controller.go
Labels: area/networking, ok-to-test, size/XS, cla: yes, release-notes-none

#35037 Remove the corresponding file when remove deleted resources from cache
  pkg/adsc/adsc.go
Labels: size/XS, cla: yes, release-notes-none

#34611 Fuzzing: Add kube fuzzer
  tests/fuzz/kube_fuzzer.go
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/regression_test.go
Labels: ok-to-test, size/M, cla: yes, release-notes-none

#35040 Add name and namespace to adsc client.
  pilot/pkg/bootstrap/configcontroller.go
Labels: cla: yes, release-notes-none

#34003 Add labels section on pod level for operator and pilot components
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istio-operator/templates/deployment.yaml
  manifests/charts/istio-operator/values.yaml
  manifests/charts/istiod-remote/values.yaml
  manifests/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/33879.yaml
Labels: area/environments, ok-to-test, size/M, cla: yes

#35044 Fixed Unable to add an item to a list using overlays in IstioOperator
  operator/pkg/patch/patch.go
Labels: area/environments, size/S, cla: yes, release-notes-none

#35045 Add more details to Send Failure logs
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/monitoring.go
  pilot/pkg/xds/xdsgen.go
Labels: size/M, cla: yes, release-notes-none

#35065 flag name uses public constants
  istioctl/cmd/root.go
Labels: area/test and release, size/M, cla: yes, release-notes-none

#35046 Add a rate limit to incoming XDS requests
  pilot/pkg/features/pilot.go
  pilot/pkg/grpc/grpc.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/discovery.go
Labels: size/M, cla: yes, release-notes-none

#35049 Share complete scheme in all usages
  pkg/config/crd/validator.go
  pkg/config/schema/fuzz_test.go
  pkg/kube/client.go
  pkg/kube/util.go
  tests/fuzz/config_validation_fuzzer.go
Labels: size/M, cla: yes, release-notes-none

#35069 fix no permission for serviceexport discovery.
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/reader-clusterrole.yaml
  manifests/charts/istiod-remote/templates/reader-clusterrole.yaml
  releasenotes/notes/35068.yaml
Labels: size/S, cla: yes

#34580 Fuzzing: Add security fuzzer
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/regression_test.go
  tests/fuzz/security_fuzzer.go
Labels: area/test and release, area/perf and scalability, ok-to-test, size/L, cla: yes, release-notes-none

#34913 change envoy filter metrics from counter to gauge
  pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go
  pilot/pkg/xds/discovery.go
Labels: area/networking, size/M, cla: yes, release-notes-none

#34983 Optimize: reduce calling mtlsChecker.mtlsDisabledByPeerAuthentication
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
Labels: area/networking, size/M, cla: yes, release-notes-none

#35071 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35072 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35073 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35076 Automator: update proxy@release-1.11 in istio/istio@release-1.11
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35075 Add a rate limit to incoming XDS requests (#35046)
  pilot/pkg/features/pilot.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/discovery.go
Labels: size/M, cla: yes, release-notes-none

#35052 Add MCS ClusterSet IPs to Service
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/templates/reader-clusterrole.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
  manifests/charts/istiod-remote/templates/reader-clusterrole.yaml
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/serviceregistry/mock/discovery_mock.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/xds/debug.go
  pkg/cluster/addressmap.go
  pkg/config/constants/constants.go
  tests/integration/pilot/mcs/autoexport/autoexport_test.go
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
  tests/integration/pilot/testdata/mcs-serviceimport-crd.yaml
Labels: area/networking, size/XXL, cla: yes, release-notes-none

#35083 clean up duplicate error logs
  pilot/cmd/pilot-agent/main.go
Labels: area/test and release, size/XS, cla: yes, release-notes-none

#35070 Drop --bootstrap-version flag
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
  security/pkg/nodeagent/test/setup.go
Labels: area/environments, size/XS, cla: yes, release-notes-none

#35087 remove port double check
  pilot/pkg/networking/util/util.go
Labels: area/test and release, size/XS, cla: yes, release-notes-none

#35014 add support for sourceip hashing in tcp proxy
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  releasenotes/notes/35014.yaml
  tests/integration/pilot/common/routing.go
Labels: area/networking, size/L, cla: yes

#34254 Switch our direct dependency from docker/distribution to v3
  go.mod
  go.sum
  licenses/github.com/distribution/distribution/v3/LICENSE
  operator/cmd/mesh/upgrade.go
Labels: size/L, cla: yes, release-notes-none

#35081 fix comment in certutil.go
  security/pkg/util/certutil.go
Labels: size/XS, cla: yes, release-notes-none

#35105 Clean up for simple server
  pilot/pkg/xds/simple.go
Labels: size/XS, cla: yes, release-notes-none

#35109 Fuzzing: Improve inject fuzzer
  tests/fuzz/testdata/inject/fuzz_into_resource_file.dict
Labels: area/test and release, area/perf and scalability, ok-to-test, size/S, cla: yes, release-notes-none

#35078 Rename charts we will publish to help repo
  manifests/charts/istio-cni/Chart.yaml
  manifests/charts/istio-control/istio-discovery/Chart.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
Labels: size/M, cla: yes, release-notes-none

#35112 Automator: update common-files@release-1.10 in istio/istio@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35098 Print CLI version in bug-report/versions
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: ok-to-test, area/user experience, size/S, cla: yes, release-notes-none

#35116 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35103 Fuzzing: Add missing `-i` in sed command in oss-fuzz build script
  tests/fuzz/oss_fuzz_build.sh
Labels: area/test and release, area/perf and scalability, ok-to-test, size/XS, cla: yes, release-notes-none

#34969 [release-1.10] feat: annotations on gateway serviceaccount
  manifests/charts/gateways/istio-egress/templates/serviceaccount.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/templates/serviceaccount.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/helm_chart_gateway_serviceaccount_annotations.yaml
Labels: ok-to-test, size/M, cla: yes

#35113 Automator: update istio/api@release-1.10 dependency in istio/istio@release-1.10
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#34874 Simple Gateway chart for Helm
  manifests/charts/gateway/Chart.yaml
  manifests/charts/gateway/README.md
  manifests/charts/gateway/templates/NOTES.txt
  manifests/charts/gateway/templates/_helpers.tpl
  manifests/charts/gateway/templates/deployment.yaml
  manifests/charts/gateway/templates/hpa.yaml
  manifests/charts/gateway/templates/role.yaml
  manifests/charts/gateway/templates/service.yaml
  manifests/charts/gateway/templates/serviceaccount.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
  tests/integration/pilot/ingress_test.go
Labels: size/XL, cla: yes, release-notes-none

#35118 Ignore EndpointSlices generated by MCS
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
Labels: area/networking, size/L, cla: yes, release-notes-none

#35019 Do not panic in `istioctl analyze` with types without protos
  galley/pkg/config/source/kube/inmemory/kubesource.go
Labels: size/S, cla: yes, release-notes-none

#35119 Fixing data race in aggregate controller
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: area/networking, size/XS, cla: yes, release-notes-none

#35085 fix nil error return
  security/pkg/pki/util/verify_cert.go
Labels: size/XS, cla: yes, release-notes-none

#35094 prevent multiple memory allocations
  pilot/pkg/networking/plugin/authn/util.go
Labels: area/test and release, size/XS, cla: yes, release-notes-none

#35125 Update BASE_VERSION to 1.12-dev.1
  Makefile.core.mk
Labels: size/XS, cla: yes, release-notes-none

#35131 redundant memory allocation
  pkg/adsc/adsc.go
Labels: area/test and release, size/XS, cla: yes, release-notes-none

#34990 [release-1.10] Backport destination rule does not trigger LDS 1.10
  pilot/pkg/xds/lds.go
  releasenotes/notes/34944.yaml
Labels: ok-to-test, size/M, cla: yes, release-notes-none

#35133 Fix minor logging issue
  pilot/pkg/trustbundle/trustbundle.go
Labels: size/XS, cla: yes, release-notes-none

#34864 [master] August 2021 security patches
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/allow-host-before-111-in.yaml
  pilot/pkg/security/authz/builder/testdata/http/allow-host-before-111-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/multiple-policies-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/single-policy-out.yaml
  pilot/pkg/security/authz/matcher/header.go
  pilot/pkg/security/authz/matcher/header_test.go
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
  pilot/pkg/security/authz/model/model.go
  pilot/pkg/security/authz/model/model_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/testdata/authz/v1beta1-ingress-gateway.yaml.tmpl
Labels: size/XL, cla: yes, lifecycle/staleproof, release-notes-none

#34947 fix envoy process leak when systemd stop istio
  tools/packaging/common/istio-start.sh
  tools/packaging/common/istio.service
  tools/packaging/packaging.mk
Labels: size/XS, cla: yes, release-notes-none

#35135 Add README to all charts
  manifests/charts/base/NOTES.txt
  manifests/charts/base/README.md
  manifests/charts/base/templates/NOTES.txt
  manifests/charts/istio-cni/README.md
  manifests/charts/istio-cni/templates/NOTES.txt
  manifests/charts/istio-control/istio-discovery/NOTES.txt
  manifests/charts/istio-control/istio-discovery/README.md
  manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
Labels: size/L, cla: yes, release-notes-none

#35141 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#33472 Env Var allowing proxies to utilize OS CA Cert
  pilot/cmd/pilot-agent/options/security.go
  pilot/pkg/features/pilot.go
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/security/model/authentication.go
  pkg/bootstrap/option/convert.go
  pkg/istio-agent/agent_test.go
  pkg/security/security.go
  pkg/security/security_test.go
  releasenotes/notes/33472.yaml
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/cafile/cafile.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: area/networking, size/XL, cla: yes, lifecycle/staleproof

#35155 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35156 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35158 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35128 Remove useless code and define the errUnknownType.
  pilot/pkg/config/memory/store.go
Labels: size/S, cla: yes, release-notes-none

#35160 Update confusing comment regarding envoy filter patch
  pilot/pkg/model/envoyfilter.go
Labels: size/XS, cla: yes, release-notes-none

#35166 Fix pushqueue memory leak
  pilot/pkg/xds/pushqueue.go
  pilot/pkg/xds/pushqueue_test.go
  pkg/queue/instance.go
  releasenotes/notes/pq-memory-leak.yaml
  tests/util/leak/check.go
Labels: size/M, cla: yes, cherrypick/release-1.9, cherrypick/release-1.10, cherrypick/release-1.11

#35091 Fix the adsc may be blocked by the errChan
  pkg/adsc/adsc.go
Labels: size/XS, cla: yes, release-notes-none

#35140 Fix regression with same-named virtual services
  pilot/pkg/model/sidecar.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  releasenotes/notes/same-name-vs.yaml
Labels: size/L, cla: yes, release-notes-none

#35164 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35074 Add a rate limit to incoming XDS requests (#35046)
  pilot/pkg/features/pilot.go
  pilot/pkg/grpc/grpc.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/discovery.go
Labels: size/M, cla: yes, release-notes-none

#35168 [release-1.10] Fix pushqueue memory leak
  pilot/pkg/xds/pushqueue.go
  pilot/pkg/xds/pushqueue_test.go
  pkg/queue/instance.go
  releasenotes/notes/pq-memory-leak.yaml
  tests/util/leak/check.go
Labels: size/M, cla: yes, release-notes-none

#35170 update dep go-control-plane
  go.mod
  go.sum
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, cla: yes, release-notes-none

#35167 [release-1.9] Fix pushqueue memory leak
  pilot/pkg/xds/pushqueue.go
  pilot/pkg/xds/pushqueue_test.go
  pkg/queue/instance.go
  releasenotes/notes/pq-memory-leak.yaml
  tests/util/leak/check.go
Labels: size/M, cla: yes, release-notes-none

#35173 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35174 Add security related info to helm installs
  manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
Labels: area/environments, size/XS, cla: yes, release-notes-none

#34962 [release-1.11] feat: annotations on gateway serviceaccount
  manifests/charts/gateways/istio-egress/templates/serviceaccount.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/templates/serviceaccount.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/helm_chart_gateway_serviceaccount_annotations.yaml
Labels: area/security, ok-to-test, size/M, cla: yes, release-notes-none

#35169 [release-1.11] Fix pushqueue memory leak
  pilot/pkg/xds/pushqueue.go
  pilot/pkg/xds/pushqueue_test.go
  pkg/queue/instance.go
  releasenotes/notes/pq-memory-leak.yaml
  tests/util/leak/check.go
Labels: size/M, cla: yes, release-notes-none

#35095 fix analyzer test and conflicting gateway analyzer
  galley/pkg/config/analysis/analyzers/deprecation/deprecation.go
  galley/pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  galley/pkg/config/analysis/analyzers/util/find_errorline_utils.go
Labels: area/user experience, size/S, cla: yes, release-notes-none

#34814 fix `istioctl analyze` has the unexpected [IST0132] msg when analyzing the virtual service
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_host_not_found_gateway_with_ns_prefix.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
  releasenotes/notes/34814.yaml
Labels: area/user experience, size/L, cla: yes, cherrypick/release-1.10, cherrypick/release-1.11

#35030 make use of new CommonHttpProtocolOptions.MaxRequestsPerConnection
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/util/util.go
Labels: size/M, cla: yes, release-notes-none

#35048 istioctl workload sets discovery address for revision
  istioctl/cmd/testdata/vmconfig/simple/mesh.yaml.golden
  istioctl/cmd/workload.go
  istioctl/cmd/workload_test.go
  tests/integration/pilot/revisions/revisions_test.go
Labels: size/S, cla: yes, release-notes-none

#35153 avoid slice multiple memory allocations
  istioctl/cmd/kubeinject.go
Labels: size/XS, cla: yes, release-notes-none

#34939 Remove previous default tag on non-revisioned installation
  istioctl/cmd/tag.go
  istioctl/pkg/tag/util.go
  operator/cmd/mesh/install.go
Labels: area/environments, size/S, cla: yes, release-notes-none

#35180 [release-1.11] fix `istioctl analyze` has the unexpected [IST0132] msg when analyzing the virtual service
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_host_not_found_gateway_with_ns_prefix.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
  releasenotes/notes/34814.yaml
Labels: size/L, cla: yes, release-notes-none

#35184 Fix TestStrictMTLS test to work in istiodremote topology
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/util/cert/cert.go
  tests/integration/security/util/dir/util.go
Labels: size/S, cla: yes, release-notes-none

#35179 [release-1.10] fix `istioctl analyze` has the unexpected [IST0132] msg when analyzing the virtual service
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/testdata/virtualservice_host_not_found_gateway_with_ns_prefix.yaml
  galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
  releasenotes/notes/34814.yaml
Labels: size/L, cla: yes, release-notes-none

#35190 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/L, cla: yes, auto-merge, release-notes-none

#35187 Skip security tests that fail in multicluter and external-controlplane topologies
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
Labels: size/XS, cla: yes, release-notes-none

#35146 Implement scheme/port redirect
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pkg/config/schema/fuzz_test.go
  pkg/config/validation/validation.go
  tests/integration/pilot/common/routing.go
Labels: size/L, cla: yes, release-notes-none

#35144 Lazy-ily compute sidecar scope for namespaces without Sidecar
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
Labels: size/L, cla: yes, release-notes-none

#35189 Benchmark and optimize PushRequest
  pilot/pkg/model/push_context.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/monitoring.go
Labels: size/M, cla: yes, release-notes-none

#35183 make use of new Listener.bind_to_port
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
Labels: size/S, cla: yes, release-notes-none

#35198 [release-1.11] fix analyzer test and conflicting gateway analyzer
  galley/pkg/config/analysis/analyzers/deprecation/deprecation.go
  galley/pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  galley/pkg/config/analysis/analyzers/util/find_errorline_utils.go
  releasenotes/notes/35095.yaml
Labels: size/S, cla: yes

#35205 Automator: update common-files@release-1.11 in istio/istio@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35207 Automator: update istio/client-go@release-1.11 dependency in istio/istio@release-1.11
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35196 Bump addon versions
  manifests/addons/gen.sh
  samples/addons/grafana.yaml
  samples/addons/kiali.yaml
  samples/addons/prometheus.yaml
Labels: size/L, cla: yes, release-notes-none

#35208 Fixed Istio Operator does not uninstall components
  manifests/charts/istio-operator/files/gen-operator.yaml
  manifests/charts/istio-operator/templates/clusterrole.yaml
Labels: area/environments, size/XS, cla: yes, release-notes-none

#35194 [release-1.10] istioctl workload sets discovery address for revision
  istioctl/cmd/testdata/vmconfig/simple/mesh.yaml.golden
  istioctl/cmd/workload.go
  istioctl/cmd/workload_test.go
  tests/integration/pilot/revisions/revisions_test.go
Labels: size/S, cla: yes, release-notes-none

#35195 [release-1.11] istioctl workload sets discovery address for revision
  istioctl/cmd/testdata/vmconfig/simple/mesh.yaml.golden
  istioctl/cmd/workload.go
  istioctl/cmd/workload_test.go
  releasenotes/notes/35048.yaml
  tests/integration/pilot/revisions/revisions_test.go
Labels: size/S, cla: yes, release-notes-none

#35215 ignore istio.test.revision set to default
  pkg/test/framework/resource/version.go
Labels: size/XS, cla: yes, release-notes-none

#35193 perf: reuse PushRequest object during Merge
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/pushqueue.go
Labels: size/M, cla: yes, release-notes-none

#35209 Fix gateway chart external traffic policy
  manifests/charts/gateway/templates/service.yaml
Labels: size/XS, cla: yes, release-notes-none

#35218 Enable more pilot-istiodremote integration tests
  pkg/test/framework/analyzer.go
  pkg/test/framework/suite.go
  pkg/test/framework/test.go
  tests/integration/pilot/analysis/analysis_test.go
  tests/integration/pilot/cross_revision_test.go
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/piggyback_test.go
  tests/integration/pilot/revisioncmd/main_test.go
  tests/integration/pilot/revisioncmd/revision_view_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/pilot/revisions/revision_tag_test.go
  tests/integration/pilot/revisions/revisions_test.go
Labels: size/M, cla: yes, release-notes-none

#35225 Automator: update common-files@release-1.10 in istio/istio@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35222 [release-1.11] ignore istio.test.revision set to default
  pkg/test/framework/resource/version.go
Labels: size/XS, cla: yes, release-notes-none

#35211 Improve the error handling of STS token manager
  pilot/cmd/pilot-agent/options/security.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go
  security/pkg/stsservice/test/setup.go
  security/pkg/stsservice/tokenmanager/sts_test.go
  security/pkg/stsservice/tokenmanager/tokenmanager.go
  security/pkg/stsservice/tokenmanager/tokensource.go
Labels: area/networking, area/security, size/M, cla: yes, release-notes-none

#35227 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35233 Add flag to skip TProxy related parts in test.
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  tests/integration/pilot/original_src_addr_test.go
Labels: size/S, cla: yes, release-notes-none

#35234 Cleanup deadcode in tokensource
  security/pkg/stsservice/tokenmanager/sts_test.go
  security/pkg/stsservice/tokenmanager/tokensource.go
Labels: size/L, cla: yes, release-notes-none

#35230 Remove unused function in push context
  pilot/pkg/model/push_context.go
Labels: size/S, cla: yes, release-notes-none

#35252 Manual update of istio/client-go (includes api)
  go.mod
  go.sum
Labels: size/S, cla: yes, release-notes-none

#35236 Filter secrets for TLS cert watcher
  pilot/pkg/secrets/kube/secrets.go
  releasenotes/notes/secret-watch.yaml
Labels: size/M, cla: yes

#34843 [release-1.11] add retriable status codes to retry policy
  pilot/pkg/networking/core/v1alpha3/route/retry/retry.go
  pilot/pkg/networking/core/v1alpha3/route/retry/retry_test.go
Labels: size/M, cla: yes, release-notes-none

#35235 flag to skip arbitrary types of workloads
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/echotypes/types.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
Labels: size/L, cla: yes, release-notes-none

#35256 Rename Service.Address to Service.DefaultAddress
  pilot/pkg/model/service.go
  pilot/pkg/model/validation_test.go
  pilot/pkg/model/virtualservice_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/eds_sh_test.go
  pkg/dns/server/name_table.go
  pkg/dns/server/name_table_test.go
Labels: area/networking, size/L, cla: yes, release-notes-none

#35258 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35257 Consistency in Chart.yaml version section
  manifests/charts/base/Chart.yaml
  manifests/charts/default/Chart.yaml
  manifests/charts/gateways/istio-egress/Chart.yaml
  manifests/charts/gateways/istio-ingress/Chart.yaml
  manifests/charts/istio-cni/Chart.yaml
  manifests/charts/istio-control/istio-discovery/Chart.yaml
  manifests/charts/istio-operator/Chart.yaml
  manifests/charts/istiod-remote/Chart.yaml
Labels: size/M, cla: yes, release-notes-none

#35202 Adding Pilot service annotation capabilities
  manifests/charts/istio-control/istio-discovery/templates/service.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/35229.yaml
Labels: area/environments, ok-to-test, size/S, cla: yes

#35266 Refactor retry_test.go to table driven tests
  pilot/pkg/networking/core/v1alpha3/route/retry/retry_test.go
Labels: ok-to-test, size/L, cla: yes, release-notes-none

#35253 SetupMonitoring should return immediately when error occurred
  cni/pkg/monitoring/monitoring.go
Labels: area/networking, size/XS, cla: yes, release-notes-none

#35212 Add metadata exchange as native code
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.10.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.11.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.12.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/networking.go
  pilot/pkg/xds/filters/filters.go
  pkg/adsc/adsc.go
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: size/XXL, cla: yes, release-notes-none

#35273 Remove unused error from GetService method
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
Labels: area/networking, size/L, cla: yes, release-notes-none

#35002 Add the error of validateExtensionProvider to errors when validate MeshConfig.
  pilot/pkg/security/authz/builder/extauthz.go
  pkg/config/validation/extensionprovider.go
Labels: size/S, cla: yes, release-notes-none

#35268 remove delayed close timeout feature flag
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: size/S, cla: yes, release-notes-none
