Repository istio/istio, pull requests merged in 2021-02, with the labels that each got.

#30549 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/S

#30551 Add missing issue number for 1.9 release notes
  releasenotes/notes/28346.yaml
  releasenotes/notes/cluster-labels-prometheus.yaml
  releasenotes/notes/default-access-log.yaml
  releasenotes/notes/default-container.yaml
  releasenotes/notes/injector-selectors.yaml
  releasenotes/notes/kiali-update-v1.29.yaml
  releasenotes/notes/mcp-removal.yaml
  releasenotes/notes/pod-ip-listener.yaml
  releasenotes/notes/redirect-dns-iptables.yaml
  releasenotes/notes/tracing-canonical-service.yaml
Labels: cherrypick/release-1.9, cla: yes, size/S

#30544 Fix istioctl analyze docs url version error
  pkg/url/url.go
Labels: cla: yes, release-notes-none, size/XS

#30546 update grpc go and remove v2 workarounds
  common/config/.golangci-format.yml
  go.mod
  go.sum
  pilot/pkg/networking/grpcgen/grpcgen.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/networking/grpcgen/testdata/xds_bootstrap.json
  pilot/test/grpcgen/grpcinit.go
Labels: cla: yes, release-notes-none, size/L

#30556 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30558 [1.8] Partial cherrypick: Fix various races in push context initialization …
  pilot/pkg/xds/discovery.go
Labels: cla: yes, release-notes-none, size/XS

#30560 [release-1.8] [cherry-pick] ingress status fixes
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
  releasenotes/notes/ingress-status-fixes.yaml
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, size/L

#30532 add metrics for auto registrations
  pilot/pkg/controller/workloadentry/workloadentry_controller.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#30563 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30564 Fix DNS search namespaces with existing trailing dot
  pilot/pkg/dns/dns.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#30569 [release-1.9] Fix DNS search namespaces with existing trailing dot
  pilot/pkg/dns/dns.go
Labels: cla: yes, release-notes-none, size/XS

#30555 Fix namespace creation in operator
  operator/cmd/mesh/shared.go
  operator/pkg/helmreconciler/reconciler.go
Labels: cla: yes, release-notes-none, size/M

#30543 documentation_url -> documentationUrl everywhere
  galley/pkg/config/analysis/diag/message.go
  galley/pkg/config/analysis/diag/message_test.go
  galley/pkg/config/analysis/diag/messages_test.go
  istioctl/pkg/util/formatting/formatter_test.go
Labels: cla: yes, release-notes-none, size/S

#30554 Revision tag integration test
  istioctl/cmd/tag.go
  pkg/test/framework/features/features.yaml
  tests/integration/pilot/revisions/revision_tag_test.go
Labels: cla: yes, release-notes-none, size/L

#30557 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#29216 Fix to enable choice of TLS parameters within Envoy Filters
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
Labels: area/networking, area/security, cla: yes, lifecycle/automatically-closed, ok-to-test, release-notes-none, size/L

#30582 remove xds proxy periodic disconnect warning logs
  pkg/istio-agent/xds_proxy.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#30584 Fix condition to make revision test skip on k8s <1.16
  pkg/test/framework/components/cluster/cluster.go
  tests/integration/pilot/multi_version_revision_test.go
Labels: cla: yes, release-notes-none, size/XS

#30591 Add initial fetch timeout to metric customization remote fetch test.
  tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
Labels: cla: yes, release-notes-none, size/XS

#30568 enable previously disabled VM tests
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/vm_test.go
Labels: cla: yes, release-notes-none, size/S

#30599 fix defaulting remote cluster values
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/operator.go
  tests/integration/security/ecc_signature_algorithm/main_test.go
Labels: cla: yes, release-notes-none, size/XS

#30597 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30565 Introduce remote secret name parameter for "istioctl x create-remote-secret"
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
Labels: area/environments, area/security, area/test and release, cla: yes, feature/Multi-cluster, ok-to-test, size/M

#30590 Fix inbound TLS v2 settings
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  releasenotes/notes/tls-inbound-all-protocols.yaml
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, size/M

#30622 [release-1.8] Fix inbound TLS v2 settings
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  releasenotes/notes/tls-inbound-all-protocols.yaml
Labels: cla: yes, release-notes-none, size/M

#30630 dont attempt vm deployments in skipVM mode
  pkg/test/framework/components/echo/echoboot/echoboot.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none

#30633 [release-1.8] use correct yaml package to read image pull secret
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/testdata/basic.yaml
  pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/secret.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
Labels: cla: yes, release-notes-none, size/S

#30634 [release-1.9] use correct yaml package to read image pull secret
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/testdata/basic.yaml
  pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/secret.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
Labels: cla: yes, release-notes-none, size/S

#30636 [release-1.9] dont attempt vm deployments in skipVM mode
  pkg/test/framework/components/echo/echoboot/echoboot.go
Labels: cla: yes, release-notes-none, size/XS

#30639 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30640 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30604 Control XDS auth header type by XDS_TOKEN_TYPE
  pilot/pkg/bootstrap/server.go
  pkg/security/security.go
Labels: area/networking, area/security, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#30269 Remove deprecated gateway ports
  manifests/charts/gateways/istio-egress/templates/preconfigured.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  releasenotes/notes/mc-gateway-ports.yaml
Labels: cla: yes, size/L

#30644 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30602 set MaxEjectionTime to BaseEjectionTime if it is greater than 300s
  pilot/pkg/networking/core/v1alpha3/cluster.go
  releasenotes/notes/30181.yaml
  tests/integration/pilot/locality_test.go
Labels: area/networking, cherrypick/release-1.9, cla: yes, size/M

#30613 istioctl verify-install: fix empty revision
  istioctl/pkg/verifier/verifier.go
Labels: cla: yes, release-notes-none, size/XS

#30607 detect jwt policy and support first-party jwt token for VM
  istioctl/cmd/workload.go
Labels: cla: yes, release-notes-none, size/M

#30066 Consolidate HTTP and TCP Client Settings with global DestinationRule
  pilot/pkg/features/pilot.go
  pilot/pkg/model/destination_rule.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/merge-dr.yaml
Labels: area/networking, cherrypick/release-1.9, cla: yes, size/L

#30617 [istioctl] use admit v1beta1 rather than admit v1 in revision tag command
  istioctl/cmd/tag.go
  istioctl/cmd/tag_test.go
Labels: cla: yes, release-notes-none, size/S

#30650 [release-1.9] set MaxEjectionTime to BaseEjectionTime if it is greater than 300s
  pilot/pkg/networking/core/v1alpha3/cluster.go
  releasenotes/notes/30181.yaml
  tests/integration/pilot/locality_test.go
Labels: cla: yes, size/S

#30659 Fix missing skip validation
  pilot/pkg/config/memory/config.go
Labels: cla: yes, ok-to-test, release-notes-none, size/S

#30668 [release-1.9] fix defaulting remote cluster values
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/operator.go
  tests/integration/security/ecc_signature_algorithm/main_test.go
Labels: cla: yes, release-notes-none, size/XS

#30670 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30672 make ingress work with staticvm
  pkg/test/framework/components/istio/operator.go
Labels: cla: yes, release-notes-none, size/S

#30673 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30671 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30605 invert if condition revision check for readability
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
  manifests/charts/istio-control/istio-discovery/templates/service.yaml
Labels: area/environments, cla: yes, release-notes-none, size/S

#30151 cherrypick 29752 for the istio operator permissions.
  manifests/charts/istio-operator/files/gen-operator.yaml
  manifests/charts/istio-operator/templates/clusterrole.yaml
Labels: cla: yes, release-notes-none, size/S

#30669 Properly quote injection template labels
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/M

#30677 [release-1.9] Properly quote injection template labels
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
Labels: cla: yes, release-notes-none, size/M

#30578 Remove defunct VM sample
  samples/rawvm/.gitignore
  samples/rawvm/Makefile
  samples/rawvm/README.md
  samples/rawvm/demo.sh
  samples/rawvm/k8cli.yaml.in
  samples/rawvm/k8services.yaml.in
Labels: cla: yes, release-notes-none, size/L

#30687 [release-1.8] Update base image to 1.8-dev.7
  Makefile.core.mk
Labels: cla: yes, release-notes-none, size/XS

#30684 Fix unnecessary full push in serviceentry store.
  pilot/pkg/config/monitor/monitor.go
  releasenotes/notes/30683.yaml
Labels: cla: yes, ok-to-test, size/S

#30690 Automator: update istio/api@release-1.8 dependency in istio/istio@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30689 run UPDATE_BRANCH=release-1.9 ./bin/update_deps.sh; make gen
  Makefile.core.mk
  go.mod
  go.sum
  prow/release-commit.sh
Labels: area/test and release, cla: yes, release-notes-none, size/S

#30688 Automator: update common-files@release-1.8 in istio/istio@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30628 Fix concurrent sort of SNI hosts and CIDR
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/M

#30575 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30697 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30647 Fix DNS loop when there is a local DNS proxy
  pilot/pkg/dns/dns.go
  releasenotes/notes/dns-localhost-loop.yaml
  tests/integration/pilot/common/routing.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
  tools/istio-iptables/pkg/config/config.go
Labels: cherrypick/release-1.9, cla: yes, size/L

#30695 [release-1.8] Fix concurrent sort of SNI hosts and CIDR
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, release-notes-none, size/M

#30702 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30700 [release-1.9] Fix DNS loop when there is a local DNS proxy (#30647)
  pilot/pkg/dns/dns.go
  releasenotes/notes/dns-localhost-loop.yaml
  tests/integration/pilot/common/routing.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
  tools/istio-iptables/pkg/config/config.go
Labels: cla: yes, size/L

#30693 allow security tests to run against real VMs
  pkg/test/framework/components/echo/common/config.go
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/instance.go
  tests/integration/security/util/reachability/context.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/M

#30698 use a deterministic cluster name for subtests
  pkg/test/framework/components/cluster/cluster.go
  pkg/test/framework/components/cluster/clusterboot/factory_test.go
  pkg/test/framework/components/cluster/topology.go
  tests/integration/multicluster/cluster_local.go
  tests/integration/multicluster/helper.go
  tests/integration/multicluster/loadbalancing.go
  tests/integration/multicluster/telemetry.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/mirror_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/external_ca/basic_reachability.go
  tests/integration/security/jwt_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/util/reachability/context.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/tracing/opencensusagent/tracing_test.go
  tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/M

#30713 Fix manifest-generate_test tests flake
  operator/cmd/mesh/manifest-generate_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#30712 Improve operator/pkg/object code coverage
  operator/pkg/object/objects_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#30710 tools/istio-iptables: allow `dry-run` flag to be used across commands
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/root.go
Labels: area/networking, cla: yes, ok-to-test, release-notes-none, size/S

#30290 reduce cost of sorting k8s analysis messages
  galley/pkg/config/analysis/analyzers/analyzers_bench_test.go
  galley/pkg/config/analysis/analyzers/schema/validation_test.go
  galley/pkg/config/analysis/diag/helper.go
  galley/pkg/config/analysis/diag/messages.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  galley/pkg/config/source/kube/rt/origin.go
  galley/pkg/config/source/mcp/origin.go
  pkg/config/resource/origin.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/S

#30666 Security e2e: Ensuring External CA tests are run
  tests/integration/security/external_ca/reachability_test.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#30722 Fix envoy dashboard with custom namespace
  istioctl/cmd/dashboard.go
  istioctl/cmd/dashboard_test.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/S

#30711 Integration test for revision command
  tests/integration/pilot/revisioncmd/main_test.go
  tests/integration/pilot/revisioncmd/revision_view_test.go
Labels: area/user experience, cla: yes, release-notes-none, size/L

#30643 Fix typo
  pilot/cmd/pilot-agent/main.go
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#30676 AuthorizationPolicy and PeerAuthentication Benchmarks
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/testdata/benchmarks/authorizationpolicy.yaml
  pilot/pkg/xds/testdata/benchmarks/peerauthentication.yaml
Labels: cla: yes, size/M

#30745 Fix ctx.Clusters().Default()
  pkg/test/framework/components/cluster/clusterboot/factory.go
  pkg/test/framework/components/cluster/config.go
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/S

#30746 [release-1.9] Fix ctx.Clusters().Default()
  pkg/test/framework/components/cluster/clusterboot/factory.go
  pkg/test/framework/components/cluster/config.go
Labels: cla: yes, release-notes-none, size/S

#30748 fix ctx.Clusters().Default()
  pkg/test/framework/components/cluster/aggregate/factory.go
Labels: cla: yes, release-notes-none, size/XS

#30589 Adding PilotcertProvider validation check prior to installing IstioOperatorSpec
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/manifest/shared.go
  operator/pkg/util/k8s.go
  operator/pkg/util/k8s_test.go
  pkg/errdict/errdict.go
  releasenotes/notes/22161.yaml
Labels: area/environments, area/user experience, cla: yes, size/L

#30726 init Labels map
  operator/pkg/helmreconciler/reconciler.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#30721 Remove sdsUdsPath
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
Labels: cla: yes, release-notes-none, size/L

#30738 Properly pass proxy to inbound sidecar creation
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
Labels: cla: yes, release-notes-none, size/M

#30759 fixed a typo
  operator/cmd/mesh/upgrade.go
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#30739 Add option to enable legacy cluster name
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/networking/util/util.go
Labels: cla: yes, release-notes-none, size/L

#30752 add one integration case to check nil label map for iop
  tests/integration/operator/install_test.go
Labels: cla: yes, release-notes-none, size/XS

#30758 istioctl bug-report: fix typo in help text
  tools/bug-report/pkg/bugreport/flags.go
Labels: cla: yes, release-notes-none, size/S

#30757 fix missing stat secret failures stat increment
  security/pkg/nodeagent/cache/secretcache.go
Labels: cla: yes, release-notes-none, size/XS

#30766 fix operator/README.md
  operator/README.md
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/S

#29802 Pilot scoped namespaces
  go.mod
  go.sum
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
  pilot/pkg/serviceregistry/kube/controller/filter/informer.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/ads.go
  pkg/config/mesh/watcher_test_utils.go
  releasenotes/notes/pilot-discovery-scoped-namespaces.yaml
Labels: cla: yes, ok-to-test, size/XXL

#30770 Fix Wasm reliable remote load release notes.
  releasenotes/README.md
  releasenotes/notes/reliable-wasm-remote-load.yaml
Labels: cla: yes, release-notes-none, size/XS

#30764 Trim dependencys of pkg/test/framework
  pkg/test/envoy/envoy.go
  pkg/test/envoy/envoy_conf.go
  pkg/test/envoy/ports.go
  pkg/test/envoy/setup.go
  pkg/test/framework/initstatics.go
  security/pkg/nodeagent/test/cert_rotation/rotation_test.go
  security/pkg/nodeagent/test/csr_failure/csr_test.go
  security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
  security/pkg/nodeagent/test/setup.go
  security/pkg/nodeagent/test/success_sds/sds_test.go
  security/pkg/stsservice/test/failure_sts_token_fetch/token_failure_test.go
  security/pkg/stsservice/test/proxy_cached_sts_token/proxy_cached_token_test.go
  security/pkg/stsservice/test/renew_sts_token/renew_token_test.go
  security/pkg/stsservice/test/server_cached_short_lived_sts_token/short_lived_cached_token_test.go
  security/pkg/stsservice/test/server_cached_sts_token/server_cached_token_test.go
  security/pkg/stsservice/test/setup.go
  security/pkg/stsservice/test/sts_fetch_timeout/sts_timeout_test.go
  security/pkg/stsservice/test/success_sts/proxy_sts_test.go
Labels: cla: yes, release-notes-none, size/L

#30623 [release-1.9] Fix inbound TLS v2 settings
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  releasenotes/notes/tls-inbound-all-protocols.yaml
Labels: cla: yes, release-notes-none, size/M

#30663 Manual cherry-pick global DestinationRule …
  pilot/pkg/features/pilot.go
  pilot/pkg/model/destination_rule.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/merge-dr.yaml
Labels: cla: yes, size/L

#30704 [release-1.9] allow security tests to run against real VMs
  pkg/test/framework/components/echo/common/config.go
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/instance.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, release-notes-none, size/M

#30724 [release-1.9] reduce cost of sorting k8s analysis messages
  galley/pkg/config/analysis/analyzers/analyzers_bench_test.go
  galley/pkg/config/analysis/analyzers/schema/validation_test.go
  galley/pkg/config/analysis/diag/helper.go
  galley/pkg/config/analysis/diag/messages.go
  galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go
  galley/pkg/config/source/kube/rt/origin.go
  galley/pkg/config/source/mcp/origin.go
  pkg/config/resource/origin.go
Labels: cla: yes, release-notes-none, size/S

#30732 [release-1.9] Fix envoy dashboard with custom namespace
  istioctl/cmd/dashboard.go
  istioctl/cmd/dashboard_test.go
Labels: cla: yes, release-notes-none, size/S

#30696 [release-1.9] Fix concurrent sort of SNI hosts and CIDR
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, release-notes-none, size/M

#30714 tools/istio-clean-iptables: clean up all DNS UDP rules
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-clean-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#30553 [release-1.9] Add missing issue number for 1.9 release notes
  releasenotes/notes/28346.yaml
  releasenotes/notes/cluster-labels-prometheus.yaml
  releasenotes/notes/default-access-log.yaml
  releasenotes/notes/default-container.yaml
  releasenotes/notes/injector-selectors.yaml
  releasenotes/notes/kiali-update-v1.29.yaml
  releasenotes/notes/mcp-removal.yaml
  releasenotes/notes/pod-ip-listener.yaml
  releasenotes/notes/redirect-dns-iptables.yaml
  releasenotes/notes/tracing-canonical-service.yaml
Labels: cla: yes, release-notes-none, size/S

#30772 [istioctl] handle default revision in workload command
  istioctl/cmd/workload.go
Labels: cla: yes, release-notes-none, size/XS

#30775 [istioctl] fix panic in revision command without args
  istioctl/cmd/revision.go
Labels: area/user experience, cla: yes, release-notes-none, size/XS

#30777 fix LocalityToString comment
  pilot/pkg/networking/util/util.go
Labels: cla: yes, kind/docs, ok-to-test, release-notes-none, size/XS

#30783 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30743 Improve retry timeouts
  pkg/test/util/retry/retry.go
Labels: cla: yes, release-notes-none, size/S

#30727 fix envoy filter service match for inbound clusters
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  releasenotes/notes/inbound-patch.yaml
Labels: area/networking, cla: yes, size/L

#30788 fix stats filter test: shadow var for goroutine
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: cherrypick/release-1.5, cherrypick/release-1.8, cla: yes, release-notes-none, size/XS

#30790 [release-1.8] fix stats filter test: shadow var for goroutine
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: cla: yes, release-notes-none, size/XS

#30794 [1.8] Pass JSON log encoding to envoy logs (#29159)
  pilot/cmd/pilot-agent/main.go
  pkg/envoy/proxy.go
Labels: cla: yes, release-notes-none, size/S

#30778 Add updating of distroless image to update_deps.sh
  bin/update_deps.sh
  docker/Dockerfile.distroless
  pilot/docker/Dockerfile.proxyv2
  prow/release-commit.sh
Labels: area/test and release, cla: yes, release-notes-none, size/S

#30795 ext-authz: fix to set the proper timeout for gRPC case
  pilot/pkg/security/authz/builder/extauthz.go
  pilot/pkg/security/authz/builder/testdata/action-custom-HTTP-for-TCP-filter-out2.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-grpc-provider-out2.yaml
Labels: area/security, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#30791 [release-1.9] fix stats filter test: shadow var for goroutine
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: cla: yes, release-notes-none, size/XS

#30800 [release-1.9] ext-authz: fix to set the proper timeout for gRPC case
  pilot/pkg/security/authz/builder/extauthz.go
  pilot/pkg/security/authz/builder/testdata/action-custom-HTTP-for-TCP-filter-out2.yaml
  pilot/pkg/security/authz/builder/testdata/action-custom-grpc-provider-out2.yaml
Labels: cla: yes, release-notes-none, size/XS

#30793 Use consistent scope name in envoy json logs
  pkg/envoy/proxy.go
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#30803 [release-1.9] Use consistent scope name in envoy json logs
  pkg/envoy/proxy.go
Labels: cla: yes, release-notes-none, size/XS

#30749 Add http3 client to echo
  go.mod
  go.sum
  licenses/github.com/cheekybits/genny/LICENSE
  licenses/github.com/lucas-clemente/quic-go/LICENSE
  licenses/github.com/marten-seemann/qpack/LICENSE.md
  licenses/github.com/marten-seemann/qtls-go1-15/LICENSE
  pkg/test/echo/cmd/client/main.go
  pkg/test/echo/proto/echo.pb.go
  pkg/test/echo/proto/echo.proto
  pkg/test/echo/server/forwarder/http.go
  pkg/test/echo/server/forwarder/protocol.go
Labels: cla: yes, release-notes-none, size/L

#30801 [release-1.9] istioctl verify-install: fix empty revision
  istioctl/pkg/verifier/verifier.go
Labels: cla: yes, release-notes-none, size/XS

#30802 [release-1.8] Use consistent scope name in envoy json logs
  pkg/envoy/proxy.go
Labels: cla: yes, release-notes-none, size/XS

#30799 broken tracing test checks networks instead of hardcoded name
  tests/integration/telemetry/tracing/opencensusagent/tracing_test.go
  tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
Labels: cla: yes, release-notes-none, size/L

#30813 Fix bugs in go-stress-test
  tools/go-stress-test
Labels: cla: yes, release-notes-none, size/XS

#30816 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30817 telemetry tests: fix more loop vars in goroutines
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#29704 add support for remote_jwks in jwt validation for mesh clusters
  pilot/pkg/features/pilot.go
  pilot/pkg/security/authn/factory/factory.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/security/authz/builder/extauthz.go
  pilot/pkg/security/utils.go
  releasenotes/notes/28742.yaml
  samples/jwt-server/jwt-server.yaml
  samples/jwt-server/src/Dockerfile
  samples/jwt-server/src/Makefile
  samples/jwt-server/src/main.go
  samples/jwt-server/src/main_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/main_test.go
  tests/integration/security/testdata/requestauthn/g-authn.yaml.tmpl
  tests/integration/security/util/framework.go
Labels: cla: yes, size/XL

#30786 Fix bad wasm remote load test flaky.
  tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
Labels: cla: yes, release-notes-none, size/XS

#30815 Expand testing of application bind and sidecar
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/model.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
Labels: cla: yes, release-notes-none, size/L

#30842 Allow multiple istio.test.skips
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/matcher.go
  pkg/test/framework/resource/matcher_test.go
  pkg/test/framework/resource/settings.go
Labels: cla: yes, release-notes-none, size/M

#30847 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30839 [release-1.9] Expand testing of application bind and sidecar
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/model.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/instance.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
Labels: cla: yes, release-notes-none, size/L

#30841 Dump entire wait respones from pilot when verbose is set
  istioctl/cmd/wait.go
Labels: cla: yes, release-notes-none, size/XS

#30858 istioctl bug-report: use .tar.gz
  tools/bug-report/pkg/archive/archive.go
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: cla: yes, release-notes-none, size/XS

#30849 Properly chown certs in docker build
  tools/istio-docker.mk
Labels: cla: yes, release-notes-none, size/XS

#30497 [release-1.7] Fix dashboard controlz could not port forward to istiod pod (#30467)
  istioctl/cmd/dashboard.go
  istioctl/pkg/util/handlers/handlers.go
  pkg/kube/client.go
  pkg/test/kube/mock_client.go
  releasenotes/notes/30208.yaml
Labels: cla: yes, size/L

#30559 Partial cherrypick: Fix various races in push context initialization …
  pilot/pkg/xds/discovery.go
Labels: cla: yes, release-notes-none, size/XS

#30468 [release-1.7] Fix namespace isn't resolved correctly in VirtualService delegation
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/30387.yaml
Labels: cla: yes, size/L

#30567 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30860 Automator: update proxy@release-1.7 in istio/istio@release-1.7
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30861 pilot-discovery: remove superfluous response.WriteHeader call in debug
  pilot/pkg/xds/debug.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#30846 Fix HoldApplicationUntilProxyStarts
  pkg/kube/inject/webhook.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#30844 Avoid spurious error log on unset JSON access log format
  pilot/pkg/networking/core/v1alpha3/accesslog.go
Labels: cla: yes, release-notes-none, size/S

#30875 Fix ADS stream hanging on errors
  pilot/pkg/xds/ads.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/S

#30675 [Test Framework] Support dynamic echo workloads
  pkg/config/constants/constants.go
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/pod_controller.go
  pkg/test/framework/components/echo/kube/util.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/echo/kube/workload_manager.go
Labels: area/test and release, cla: yes, release-notes-none, size/XXL

#30014 Add env for jwks refresh interval configuration
  pilot/pkg/features/pilot.go
  pilot/pkg/model/jwks_resolver.go
  releasenotes/notes/30014.yaml
Labels: area/security, cla: yes, size/S

#30881 Fix races in ServiceEntry refreshIndexes
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Labels: cla: yes, release-notes-none, size/S

#30882 Fix typo in validation message
  pkg/config/validation/validation.go
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#30883 [release-1.9] Fix typo in validation message
  pkg/config/validation/validation.go
Labels: cla: yes, release-notes-none, size/XS

#30830 refactor MergeGateway to cleanup Servers field
  pilot/pkg/model/gateway.go
  pilot/pkg/model/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#30855 [istioctl/cmd]: trim trailing whitespace
  istioctl/cmd/revision.go
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#30876 [release-1.9] Fix ADS stream hanging on errors
  pilot/pkg/xds/ads.go
Labels: cla: yes, release-notes-none, size/S

#30887 telemetry tests: fix more loop vars in goroutines
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: cla: yes, ok-to-test, size/XS

#30870 Fix HoldApplicationUntilProxyStarts (#30846)
  pkg/kube/inject/webhook.go
Labels: cla: yes, release-notes-none, size/XS

#30853 add debounce for secret watcher
  security/pkg/nodeagent/cache/secretcache.go
Labels: area/security, cla: yes, release-notes-none, size/M

#30901 allow stable namespaces to be created/claimed in parallel
  pkg/test/framework/components/namespace/kube.go
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS
