Repository istio/istio, pull requests merged in 2021-10, with the labels that each got.

#35434 Apply full informer wait to all client types
  pkg/kube/client.go
Labels: size/S, cla: yes, release-notes-none

#35351 Allow publishing explicit `-debug` tagged images
  cni/deployments/kubernetes/Dockerfile.install-cni
  operator/docker/Dockerfile.operator
  pilot/docker/Dockerfile.pilot
  pilot/docker/Dockerfile.proxyv2
  prow/release-commit.sh
  samples/tcp-echo/src/Dockerfile
  tools/buildx-gen.sh
  tools/istio-docker.mk
Labels: size/L, cla: yes, release-notes-none

#35439 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35432 Regenerate with new protoc
  pilot/pkg/xds/nds_test.go
  pkg/dns/client/dns.go
  pkg/dns/proto/nds.pb.go
  pkg/dns/proto/nds.proto
  pkg/dns/server/name_table_test.go
Labels: size/S, cla: yes, release-notes-none

#35443 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35442 Reduce delay on tf call, and introduce backoff
  pkg/test/framework/components/echo/common/envoy.go
  pkg/test/framework/components/echo/flags.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/kube/util.go
  pkg/test/util/retry/retry.go
  tests/integration/pilot/common/traffic.go
Labels: size/M, cla: yes, release-notes-none

#35446 Bump release-builder to fix postsubmit
  prow/release-commit.sh
Labels: size/XS, cla: yes, release-notes-none

#35440 Revert "[release-1.11] Try random iptables command to fix jwt test (#35399)"
  prow/integ-suite-kind.sh
Labels: size/XS, cla: yes, release-notes-none

#35461 Handle empty ratings collection when using Mongo
  samples/bookinfo/src/ratings/ratings.js
Labels: kind/docs, ok-to-test, size/XS, cla: yes, release-notes-none

#35362 Bump distroless image
  pilot/docker/Dockerfile.proxyv2
Labels: size/XS, cla: yes, release-notes-none

#35447 Allow turning off ALPN in echo server
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/model.go
  pkg/test/echo/server/endpoint/http.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/kube/deployment.go
  tests/integration/security/ca_custom_root/main_test.go
Labels: size/M, cla: yes, release-notes-none

#35361 Update to grpc 1.41
  go.mod
  go.sum
  pilot/pkg/networking/grpcgen/lds.go
Labels: size/S, cla: yes, release-notes-none

#35444 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35318 fix canonical revision label for workload groups
  istioctl/cmd/testdata/vmconfig-nil-proxy-metadata/cluster.env.golden
  istioctl/cmd/testdata/vmconfig-nil-proxy-metadata/mesh.yaml.golden
  istioctl/cmd/testdata/vmconfig/simple/cluster.env.golden
  istioctl/cmd/testdata/vmconfig/simple/mesh.yaml.golden
  istioctl/cmd/workload.go
  releasenotes/notes/fix-workload-group-labels.yaml
Labels: size/S, cla: yes

#35468 Update update_deps.sh to use debian11 instead of debian10
  bin/update_deps.sh
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: area/test and release, size/S, cla: yes, release-notes-none

#35466 [release-1.11] run UPDATE_BRANCH=release-1.11 ./bin/update_deps.sh; make gen
  docker/Dockerfile.distroless
  go.mod
  go.sum
  pilot/docker/Dockerfile.proxyv2
  prow/release-commit.sh
Labels: area/test and release, size/S, cla: yes, release-notes-none

#35472 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35473 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  licenses/github.com/marten-seemann/qtls-go1-17/LICENSE
  pkg/config/schema/collections/collections.agent.gen.go
  pkg/config/schema/collections/collections.gen.go
  tests/integration/security/sds_ingress/quic/ingress_test.go
Labels: size/S, cla: yes, auto-merge, release-notes-none

#35463 [release-1.9] Update 1.9 base image and run UPDATE_BRANCH=release-1.9 ./bin/update_deps.sh; make gen
  Makefile.core.mk
  docker/Dockerfile.distroless
  go.mod
  go.sum
  pilot/docker/Dockerfile.proxyv2
  prow/release-commit.sh
Labels: size/S, cla: yes, release-notes-none

#35479 clean up unused code
  pilot/test/xdstest/extract.go
Labels: size/XS, cla: yes, release-notes-none

#35474 Fix default DOCKER_BUILD_VARIANTS
  tools/istio-docker.mk
Labels: size/XS, cla: yes, release-notes-none

#35382 Integrate with GKE workload certificates
  pilot/cmd/pilot-agent/options/security.go
  pilot/cmd/pilot-agent/options/security_test.go
  pkg/istio-agent/agent_test.go
  pkg/istio-agent/xds_proxy.go
  pkg/security/security.go
  releasenotes/notes/35385.yaml
  security/pkg/nodeagent/cache/secretcache.go
Labels: area/security, size/L, cla: yes

#35464 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35453 Add watchedNamespaces for istioctl operator dump
  operator/cmd/mesh/operator-dump.go
  operator/cmd/mesh/operator_test.go
  operator/cmd/mesh/testdata/operator/output/operator-dump.yaml
  releasenotes/notes/35485.yaml
Labels: ok-to-test, size/S, cla: yes

#35488 Skip TestClusterLocal on pre-1.11 versions
  tests/integration/pilot/multicluster_test.go
Labels: size/XS, cla: yes, release-notes-none

#35483 Add Annotation Maturity to Upgrade Check
  galley/pkg/config/analysis/analyzers/analyzers_test.go
  galley/pkg/config/analysis/analyzers/maturity/maturity.go
  istioctl/cmd/precheck.go
  releasenotes/notes/35483.yaml
Labels: size/L, cla: yes

#35417 proxyless grpc: support fault injection
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/grpcgen/grpcecho_test.go
  pilot/pkg/networking/grpcgen/lds.go
Labels: size/M, cla: yes, release-notes-none

#35499 Update BASE_VERSION to 2021-10-06T19-01-15
  Makefile.core.mk
Labels: size/XS, cla: yes, release-notes-none

#35729 Fix label injection enabled with policy=disabled
  pkg/kube/inject/inject.go
  pkg/kube/inject/webhook_test.go
  releasenotes/notes/inject-disabled.yaml
Labels: size/M, cla: yes

#35802 [release-1.12] Fixup common-files
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#35803 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#35768 Wait for cache sync before proceeding with leader election
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/leaderelection/leaderelection_test.go
  pkg/revisions/default_watcher.go
  pkg/revisions/default_watcher_test.go
Labels: size/L, cla: yes, release-notes-none

#35658 Make port forwarder resilient to broken connection.
  pkg/kube/portforwarder.go
Labels: size/M, cla: yes, release-notes-none
