Repository istio/istio, pull requests merged in 2021-03, with the labels that each got.

#30985 Scope full push raised by Sidecar config changes
  pilot/pkg/model/context.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/xds/ads_common.go
  pilot/pkg/xds/ads_common_test.go
  pilot/pkg/xds/ads_test.go
  releasenotes/notes/scope-push-by-sidecar-changes.yaml
Labels: cla: yes, ok-to-test, size/L

#31133 revert base ejection time fix
  pilot/pkg/networking/core/v1alpha3/cluster.go
  tests/integration/pilot/locality_test.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31074 istioctl verify-install: add revision shortcut
  istioctl/pkg/clioptions/control_plane.go
  istioctl/pkg/install/verify.go
Labels: cla: yes, release-notes-none, size/XS

#30934 Add istioctl proxy-config all
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/writer/envoy/configdump/configdump.go
  istioctl/pkg/writer/envoy/configdump/route.go
  releasenotes/notes/istioctl-pc-all.yaml
Labels: cla: yes, size/L

#31114 Default namespace before 'istioctl validate'
  istioctl/cmd/root.go
  istioctl/pkg/validate/validate.go
  istioctl/pkg/validate/validate_test.go
Labels: cla: yes, release-notes-none, size/M

#31120 Fix data race in analysis status update
  pilot/pkg/status/state.go
Labels: cla: yes, release-notes-none, size/XS

#31135 Clean up 1.8 telemetry filter.
  Makefile.core.mk
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.8.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.8.yaml
Labels: cla: yes, release-notes-none, size/XXL

#31142 Fix typo.
  pkg/config/constants/constants.go
Labels: cla: yes, release-notes-none, size/XS

#31144 fix dns name table comments
  pilot/pkg/networking/core/v1alpha3/name_table.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#31149 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31105 remove unnecessary setting for original dst
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#31152 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31151 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31125 Move admission configs to v1
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/validatingwebhookconfiguration.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/templates/revision-tags.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
Labels: cla: yes, release-notes-none, size/S

#31161 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31162 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31163 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31154 Fix validation
  galley/testdatasets/validation/dataset.gen.go
  galley/testdatasets/validation/dataset/networking-v1alpha3-EnvoyFilter-invalid.yaml
  tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit.yaml
  tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit_per_route.yaml
Labels: cla: yes, release-notes-none, size/S

#31164 Remove dup line in .gitignore
  .gitignore
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#31121 Match inbound cluster logic in prober
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/status/server.go
Labels: cla: yes, release-notes-none, size/M

#31153 Fix spacing on ADS request log
  pilot/pkg/model/push_context.go
Labels: cla: yes, release-notes-none, size/XS

#31171 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31175 fix health check logic when initial check is failure
  pkg/istio-agent/health/health_check.go
  pkg/istio-agent/health/health_check_test.go
Labels: cla: yes, release-notes-none, size/S

#31170 remove tlsv2 env var
  pilot/pkg/features/pilot.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
Labels: cla: yes, release-notes-none, size/M

#31143 istioctl pc all: remove duplicate alias
  istioctl/cmd/proxyconfig.go
Labels: cla: yes, release-notes-none, size/XS

#30679 merge the ResolveJwksURI into refresh() function
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/model/jwks_resolver_test.go
  pilot/pkg/model/test/mockopenidserver.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  releasenotes/notes/30261.yaml
Labels: cla: yes, ok-to-test, size/XL

#30469 Fixed wildcard hosts fail to match when port is included in host header
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/25350.yaml
Labels: area/networking, cla: yes, size/L

#30805 istioctl analyze: skip if namespace does not exists
  istioctl/cmd/analyze.go
Labels: cla: yes, release-notes-none, size/S

#30866 istioctl analyze: display dir or file name when it is provided
  istioctl/cmd/analyze.go
Labels: cla: yes, release-notes-none, size/S

#31160 Fix custom domain with gateway-api
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/backendpolicy.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
Labels: cla: yes, release-notes-none, size/M

#31189 [Test Framework] Fix panic if echo creation fails
  pkg/test/framework/components/echo/kube/instance.go
Labels: cla: yes, release-notes-none, size/XS

#31188 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XXL

#31191 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31093 Warn service entry which has more than one host specified simultaneously with address and https port
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: cla: yes, release-notes-none, size/L

#31132 Cleanup serviceIndex's ClusterVIPs
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/name_table.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: cla: yes, release-notes-none, size/M

#31195 Donot set StripPortMode if not enabled
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: cla: yes, release-notes-none, size/S

#31201 diff_yaml.py: unify function name style
  bin/diff_yaml.py
Labels: area/test and release, cla: yes, ok-to-test, release-notes-none, size/XS

#31200 Remove .PHONY target non-existent prerequisites
  Makefile.core.mk
Labels: area/test and release, cla: yes, ok-to-test, release-notes-none, size/XS

#31204 optimize cluster vip mutex in service
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/serviceregistry/mock/discovery_mock.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31213 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31215 Support comma seperated list of HUBS for build-base-images.sh
  tools/build-base-images.sh
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#31209 fix(azure bootstrap): handle tags with semicolons or without values
  pkg/bootstrap/platform/azure.go
  pkg/bootstrap/platform/azure_test.go
  releasenotes/notes/azureTags.yaml
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, size/M

#31219 Fix build failure on Macs
  bin/init.sh
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#31222 [release-1.8] fix(azure bootstrap): handle tags with semicolons or without values
  pkg/bootstrap/platform/azure.go
  pkg/bootstrap/platform/azure_test.go
  releasenotes/notes/azureTags.yaml
Labels: cla: yes, size/M

#31223 [release-1.8] Fix build failure on Macs
  bin/init.sh
Labels: cla: yes, release-notes-none, size/XS

#31225 [release-1.9] fix(azure bootstrap): handle tags with semicolons or without values
  pkg/bootstrap/platform/azure.go
  pkg/bootstrap/platform/azure_test.go
  releasenotes/notes/azureTags.yaml
Labels: cla: yes, size/M

#31181 Add experimental support for mesh traffic to gateway api
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/L

#31168 Add filter chain name match support to envoyfilter
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  releasenotes/notes/31168.yaml
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, ok-to-test, size/M

#31217 [release-1.9] Support comma seperated list of HUBS for build-base-images.sh
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/XS

#31178 [istioctl] Add generate subcommand and webhookName option to revision tag command
  istioctl/cmd/tag.go
  istioctl/cmd/tag_test.go
Labels: area/user experience, cla: yes, release-notes-none, size/L

#31224 [release-1.9] Fix build failure on Macs
  bin/init.sh
Labels: cla: yes, release-notes-none, size/XS

#31232 cleanup enable crd validation feature flag
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/metrics.go
  pilot/pkg/features/pilot.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31214 Add cluster into endpoint workload metadata.
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  releasenotes/notes/destination-cluster-stats-label.yaml
Labels: cla: yes, size/M

#30944 minor improvements to istio cni
  cni/pkg/taint/taintcontroller.go
  cni/pkg/taint/taintcontroller_test.go
  manifests/charts/istio-cni/templates/clusterrole.yaml
  manifests/charts/istio-cni/templates/clusterrolebinding.yaml
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: cla: yes, release-notes-none, size/M

#31045 Add runtime assertions to Pilot
  pilot/pkg/features/pilot.go
  pilot/pkg/model/xds_cache.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/xds_cache_test.go
  pkg/test/kube/dump.go
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/L

#31239 Update build_base_images to only build one image, tag push others,
  Makefile.core.mk
  tools/build-base-images.sh
  tools/buildx-gen.sh
  tools/istio-docker.mk
Labels: cherrypick/release-1.9, cla: yes, release-notes-none, size/S

#31127 Bump golang dependencies
  go.mod
  go.sum
  licenses/github.com/decred/dcrd/dcrec/secp256k1/v3/LICENSE
  licenses/github.com/evanphx/json-patch/v5/LICENSE
  licenses/github.com/lestrrat-go/backoff/v2/LICENSE
  licenses/github.com/lestrrat-go/httpcc/LICENSE
  licenses/github.com/lestrrat-go/option/LICENSE
  tests/common/jwt/jwt_token_test.go
Labels: cla: yes, release-notes-none, size/L

#31236 minor refactor in service entry conversion
  pilot/pkg/serviceregistry/serviceentry/conversion.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#29911 Adding metrics to CNI repair controller
  cni/cmd/istio-cni-repair/main.go
  cni/pkg/repair/repair.go
  cni/pkg/repair/repair_test.go
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/19300.yaml
Labels: cla: yes, size/L

#31243 [release-1.9] wait for pod deletion before echo is ready
  pkg/kube/util.go
  pkg/test/kube/util.go
Labels: cla: yes, release-notes-none, size/XS

#31249 [release-1.9] Update build_base_images to only build one image, tag push others,
  Makefile.core.mk
  tools/build-base-images.sh
  tools/buildx-gen.sh
  tools/istio-docker.mk
Labels: cla: yes, release-notes-none, size/S

#31251 dns: fix various issues with dns proxy
  pilot/pkg/dns/dns.go
  pilot/pkg/dns/dns_test.go
Labels: cla: yes, release-notes-none, size/L

#31226 Remove cluster label stats plugin customization
  istio.deps
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.10.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.10.yaml
  tests/integration/telemetry/stackdriver/vm/testdata/trace.prototext.tmpl
Labels: cla: yes, release-notes-none, size/L

#31255 Fix custom gateway test when using revision tag
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/XS

#31237 istioctl operator init: create watchedNamespaces or default namespace
  operator/cmd/mesh/operator-init.go
Labels: cla: yes, release-notes-none, size/S

#31258 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31263 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31265 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31257 Backport DNS fixes to 1.9
  pilot/pkg/dns/dns.go
  pilot/pkg/dns/dns_test.go
  pilot/pkg/networking/core/v1alpha3/name_table.go
  releasenotes/notes/dns-round-robin.yaml
Labels: cla: yes, size/L

#31254 fix race cluster vip mutex in service (#31204)"
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
Labels: cla: yes, release-notes-none, size/S

#31261 No need to store jwtPath in Server struct
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, release-notes-none, size/M

#31272 istioctl manifest: migrate is redundant
  operator/README.md
Labels: cla: yes, release-notes-none, size/S

#31260 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31012 MultiRoot Certificate support: e2e tests
  pkg/test/framework/features/features.yaml
  samples/certs/README.md
  samples/certs/ca-cert-alt.pem
  samples/certs/ca-key-alt.pem
  samples/certs/cert-chain-alt.pem
  samples/certs/generate-workload.sh
  samples/certs/root-cert-alt.pem
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/ca_custom_root/multi_root_test.go
Labels: area/security, cla: yes, release-notes-none, size/L

#31253 Sync ingress and egress templates
  Makefile.core.mk
  manifests/charts/gateways/istio-egress/templates/_helpers.tpl
  manifests/charts/gateways/istio-egress/templates/autoscale.yaml
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/templates/poddisruptionbudget.yaml
  manifests/charts/gateways/istio-egress/templates/role.yaml
  manifests/charts/gateways/istio-egress/templates/rolebindings.yaml
  manifests/charts/gateways/istio-egress/templates/service.yaml
  manifests/charts/gateways/istio-egress/templates/serviceaccount.yaml
  manifests/charts/gateways/istio-ingress/templates/autoscale.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/poddisruptionbudget.yaml
  manifests/charts/gateways/istio-ingress/templates/preconfigured.yaml
  manifests/charts/gateways/istio-ingress/templates/role.yaml
  manifests/charts/gateways/istio-ingress/templates/rolebindings.yaml
  manifests/charts/gateways/istio-ingress/templates/service.yaml
  manifests/charts/gateways/istio-ingress/templates/serviceaccount.yaml
  manifests/manifest.go
Labels: cla: yes, release-notes-none, size/L

#31286 Consistently only dump in CIMode
  pkg/test/framework/testcontext.go
Labels: cla: yes, release-notes-none, size/XS

#31091 lds: cidr equality only checks significant bits
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: cla: yes, release-notes-none, size/M

#31290 warn when using localhost in remote secret command
  istioctl/pkg/multicluster/remote_secret.go
Labels: cla: yes, release-notes-none, size/XS

#31292 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31264 Set peerCertVerifier in initSecureDiscoveryService
  pilot/pkg/bootstrap/server.go
  pilot/pkg/xds/ads.go
Labels: cla: yes, release-notes-none, size/M

#31293 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31281 Use gRPC error for unauthenticated
  pilot/pkg/xds/ads.go
Labels: cla: yes, release-notes-none, size/XS

#31311 Remove admitPilot
  pkg/webhooks/validation/server/server.go
  pkg/webhooks/validation/server/server_test.go
Labels: cla: yes, release-notes-none, size/M

#31256 Fix invalid JSON log format
  pkg/envoy/proxy.go
Labels: cla: yes, release-notes-none, size/XS

#31307 move functions to cluster builder
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: cla: yes, release-notes-none, size/XXL

#31302 cleanup few more env vars
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
Labels: cla: yes, release-notes-none, size/M

#31318 [release-1.8] Bump 1.8 base image
  Makefile.core.mk
Labels: cla: yes, release-notes-none, size/XS

#31291 Add a simple minimal deployment for gateway injection
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/templates/injected-deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/injected-deployment.yaml
  pkg/test/framework/components/istio/operator.go
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/util.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/testdata/gateway-values.yaml
Labels: cla: yes, release-notes-none, size/L

#31323 Update build-base-images.sh to verify if images may already exist
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/S

#31331 Allow DOCKER_TARGETS as existing env var for build-base-images.sh
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/XS

#31329 Avoid putting temporary file in source tree
  tests/integration/pilot/istioctl_test.go
Labels: cla: yes, release-notes-none, size/XS

#31310 Fix missing server name for create-remote-secret warning
  istioctl/pkg/multicluster/remote_secret.go
Labels: cla: yes, release-notes-none, size/XS

#31300 Cleanup iptables when systemd service stops
  releasenotes/notes/vm-cleanup-iptables.yaml
  tools/packaging/common/istio-start.sh
  tools/packaging/common/istio.service
Labels: cla: yes, size/S

#31339 fix xds cache race
  pilot/pkg/model/xds_cache.go
  pilot/pkg/xds/xds_cache_test.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#31150 Make test framework version-aware
  pkg/test/framework/analyzer.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  pkg/test/framework/resource/version.go
  pkg/test/framework/resource/version_test.go
  pkg/test/framework/test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#31347 Make kubernetes.default.svc cluster-local by default.
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/api-server-cluster-local.yaml
Labels: area/networking, cla: yes, size/M

#31321 Disable envoy hot restart
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: cla: yes, release-notes-none, size/XS

#31285 TestReachability: assert we actually send mtls when expected
  pkg/test/echo/client/client.go
  pkg/test/echo/client/parsedresponse.go
  pkg/test/framework/components/echo/common/call.go
  tests/integration/pilot/cni/cni_test.go
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/util/connection/checker.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, release-notes-none, size/L

#31350 Add .run/ to gitignore
  .gitignore
Labels: cla: yes, release-notes-none, size/XS

#31298 fix flaky jwks resolver tests
  pilot/pkg/model/jwks_resolver_test.go
Labels: area/security, area/test and release, cla: yes, ok-to-test, release-notes-none, size/XS

#31355 use v3 secret type
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/testing/sdsc/sdsclient.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#31370 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31365 tf: shadow t var to avoid using wrong one
  pkg/test/failer.go
  pkg/test/framework/components/istioctl/istioctl.go
  pkg/test/framework/components/istioctl/kube.go
  tests/integration/pilot/analysis/analysis_test.go
  tests/integration/pilot/analyze_test.go
  tests/integration/pilot/cni/cni_test.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/endpointslice/endpointslice_test.go
  tests/integration/pilot/gateway_topology/gw_topology_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/locality_test.go
  tests/integration/pilot/main_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/original_src_addr_test.go
  tests/integration/pilot/revisioncmd/revision_view_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/pilot/revisions/revision_tag_test.go
  tests/integration/pilot/revisions/revisions_test.go
  tests/integration/pilot/revisions/uninstall_test.go
  tests/integration/pilot/routing_test.go
  tests/integration/pilot/validation_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/pilot/webhook_test.go
Labels: cla: yes, release-notes-none, size/XL

#31376 Test sds tls origination with default cluster
  tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/sds_tls_origination/main_test.go
  tests/integration/security/sds_tls_origination/util/util.go
Labels: area/security, cla: yes, release-notes-none, size/S

#31378 Make kubernetes.default.svc cluster-local by default. (#31347)
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/api-server-cluster-local.yaml
Labels: area/networking, cla: yes, size/M

#31385 Clean up TERMINATION_DRAIN_DURATION_SECONDS env var operator test data.
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_merge_meshconfig.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
Labels: cla: yes, release-notes-none, size/XS

#31382 Fix listener filter predicate
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/simulation/traffic.go
  pilot/test/xdstest/test.go
Labels: cla: yes, release-notes-none, size/S

#31356 Remove VALIDATION_ENABLED env
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/validation.go
  pilot/pkg/config/memory/store.go
  pilot/pkg/config/memory/store_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, release-notes-none, size/S

#31357 workloadentry handler is registered separately in serviceentry store
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, release-notes-none, size/S

#31390 Moving trustbundle library after CA initializaton
  pilot/pkg/bootstrap/server.go
Labels: area/networking, area/security, cla: yes, release-notes-none, size/XS

#31399 [release-1.8] Manual cherrypicks of build-base-images.sh PRs
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/S

#31358 Cherry pick release 1.9 fix envoyfilter
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  releasenotes/notes/28996.yaml
Labels: area/networking, cla: yes, ok-to-test, size/L

#31377 Make kubernetes.default.svc cluster-local by default. (#31347)
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/api-server-cluster-local.yaml
Labels: area/networking, cla: yes, size/M

#31402 [release-1.9] Support dynamic echo backport
  pkg/config/constants/constants.go
  pkg/kube/util.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/kube/pod_controller.go
  pkg/test/framework/components/echo/kube/util.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/echo/kube/workload_manager.go
  pkg/test/framework/components/echo/staticvm/instance.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/kube/util.go
  tests/integration/pilot/revisioned_upgrade_test.go
Labels: area/test and release, cla: yes, release-notes-none, size/XXL

#31388 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30950 pilot: Make JwtKeyResolver non global
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/model/jwks_resolver_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/fake.go
  tests/util/leak/check.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#31273 remove deprecated uses of http protocol options
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/xds/v3/model.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#31406 Clean up sidecar injector monitoring port
  pilot/pkg/bootstrap/sidecarinjector.go
  pkg/kube/inject/monitoring.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: cla: yes, release-notes-none, size/L

#31405 Refactor cluster local logic
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/cluster_local.go
  pilot/pkg/model/cluster_local_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/xds/ep_filters_test.go
  pilot/pkg/xds/simple.go
Labels: area/networking, cla: yes, release-notes-none, size/XL

#30976 authn: default peer authn to a PERMISSIVE is none effective exists
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/testdata/no-peer-authn.yaml
Labels: area/security, cla: yes, release-notes-none, size/M

#31408 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#30914 authn: skip filter peer config when mtls is disabled
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: cla: yes, release-notes-none, size/S

#31409 Clean up health check file param from injector.
  pilot/pkg/bootstrap/sidecarinjector.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: cla: yes, release-notes-none, size/M

#30521 Change the drain strategy to immediate
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
  releasenotes/notes/31403.yaml
Labels: cla: yes, size/S

#31392 Fix vs/gateway/dr event handler been registered twice
  pilot/pkg/config/kube/gateway/controller.go
Labels: cla: yes, release-notes-none, size/XS

#30812 [istioctl] add version check to tag set command
  istioctl/cmd/tag.go
  istioctl/cmd/tag_test.go
  tests/integration/pilot/revisions/revision_tag_test.go
Labels: area/user experience, cla: yes, release-notes-none, size/M

#31415 do not set max stream duration
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#31407 Drop echo default timeout
  pkg/test/echo/common/util.go
  pkg/test/framework/components/echo/call.go
Labels: cla: yes, release-notes-none, size/XS

#31429 Make istio.io/rev=default inject for default revision
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  releasenotes/notes/add-default-revision-webhook.yaml
Labels: area/environments, cla: yes, size/L

#31432 Cache Kubernetes version
  pilot/pkg/config/kube/ingress/controller.go
  pkg/kube/client.go
Labels: cla: yes, release-notes-none, size/M

#31437 [release-1.9] Make test framework version-aware (#31150)
  pkg/test/framework/analyzer.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  pkg/test/framework/resource/version.go
  pkg/test/framework/resource/version_test.go
  pkg/test/framework/test.go
Labels: area/test and release, cla: yes, release-notes-none, size/L

#31288 Fix auto mtls for PASSTHROUGH load balancer mode
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  releasenotes/notes/auto-mtls-passthrough.yaml
  tests/integration/security/reachability_test.go
  tests/integration/security/testdata/automtls-passthrough.yaml
Labels: cla: yes, size/M

#31428 Adding kube client for MCS API
  go.mod
  go.sum
  licenses/sigs.k8s.io/mcs-api/LICENSE
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/clusterrole.yaml
  pkg/kube/client.go
  pkg/kube/mock_client.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#31435 Fixups for updating golang-ci
  tests/integration/pilot/revisioncmd/revision_view_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
Labels: cla: yes, release-notes-none, size/S

#30753 Dynamically get trust domain from the cluster for telemetry test.
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/client_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/client_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_audit/server_audit_all_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_audit/server_audit_bar_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_audit/server_audit_foo_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/vm/main_test.go
  tests/integration/telemetry/stackdriver/vm/testdata/client_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/vm/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/vm/testdata/server_request_count.json.tmpl
  tests/integration/telemetry/util.go
Labels: cla: yes, release-notes-none, size/L

#30755 Add more log to sd integration test.
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/vm/vm_test.go
Labels: cla: yes, release-notes-none, size/S

#31326 Remove 4 echo instances from security tests
  tests/integration/security/authorization_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/testdata/pass-through-filter-chain.yaml.tmpl
  tests/integration/security/testdata/requestauthn/aud.yaml.tmpl
  tests/integration/security/testdata/requestauthn/authn-authz.yaml.tmpl
  tests/integration/security/testdata/requestauthn/authn-only.yaml.tmpl
  tests/integration/security/testdata/requestauthn/forward.yaml.tmpl
  tests/integration/security/testdata/requestauthn/global-jwt.yaml.tmpl
  tests/integration/security/testdata/requestauthn/invalid-jwks.yaml.tmpl
  tests/integration/security/testdata/requestauthn/remote.yaml.tmpl
  tests/integration/security/util/authn/authn_util.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, release-notes-none, size/XL

#31430 Add wait for custom gateway
  tests/integration/pilot/ingress_test.go
Labels: cla: yes, release-notes-none, size/S

#31441 Cleanup domain suffix handling
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/model/cluster_local.go
  pilot/pkg/model/context.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#31446 Add more info to STS error log
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: area/security, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#31445 Add more info to STS error log
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#31448 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31447 [release-1.9] Add more info to STS error log
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: cla: yes, release-notes-none, size/XS

#31420 rename IstioCluster to MutableCluster
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: area/networking, cla: yes, release-notes-none, size/L

#31398 [release-1.9] Manual cherrypick of #31323 #31331 #31343
  tools/build-base-images.sh
Labels: cla: yes, release-notes-none, size/S

#31457 fix typo
  istioctl/pkg/xds/client.go
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#31470 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31471 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#31391 do not add validation context for SIMPLE
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
Labels: area/networking, area/security, cla: yes, release-notes-none, size/L

#31469 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
