Repository istio/istio, pull requests merged in 2021-05, with the labels that each got.

#32576 [release-1.10] Fix spelling error
  releasenotes/notes/inbound-passthrough.yaml
Labels: cla: yes, release-notes-none, size/M

#32578 [release-1.10] embed on Windows uses forward slash
  operator/pkg/helm/helm.go
  operator/pkg/helm/renderer.go
Labels: cla: yes, release-notes-none, size/S

#32584 fix typo
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/virtualservice_test.go
Labels: cla: yes, ok-to-test, size/XS

#32589 Make the Key identifier of a Config object unique
  istioctl/cmd/wait.go
  istioctl/cmd/wait_test.go
  pilot/pkg/model/config_test.go
  pilot/pkg/status/ledger.go
  pilot/pkg/status/report.go
  pkg/config/model.go
Labels: cla: yes, release-notes-none, size/S

#32591 kube-inject: use Istio sidecar
  istioctl/cmd/kubeinject.go
Labels: cla: yes, release-notes-none, size/S

#32599 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32583 ca: merge tests for SignCSR
  security/pkg/pki/ca/ca_test.go
Labels: cla: yes, release-notes-none, size/L

#32572 handle unset network
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/name_table.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
Labels: cla: yes, release-notes-none, size/M

#32486 echogen: util for manual testing with echo
  pkg/test/framework/components/cluster/fake.go
  pkg/test/framework/components/cluster/staticvm/namespace.go
  pkg/test/framework/components/cluster/staticvm/staticvm.go
  pkg/test/framework/components/cluster/staticvm/staticvm_test.go
  pkg/test/framework/components/echo/cmd/echogen/README.md
  pkg/test/framework/components/echo/cmd/echogen/echogen.go
  pkg/test/framework/components/echo/cmd/echogen/echogen_test.go
  pkg/test/framework/components/echo/cmd/echogen/testdata/config.yaml
  pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
  pkg/test/framework/components/echo/common/defaults.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/config_test.go
  pkg/test/framework/components/echo/echotest/fake.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/namespace/static.go
  pkg/test/util/yml/apply_test.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/cross_revision_test.go
  tests/integration/pilot/mcs/serviceexport_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/jwt_test.go
Labels: cla: yes, release-notes-none, size/XL

#32604 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32606 test framework: dump yaml and include deployment state
  pkg/test/framework/components/namespace/kube.go
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/M

#32605 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32607 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32561 Add --dry-run flag supported for uninstall command
  operator/cmd/mesh/uninstall.go
  releasenotes/notes/32513.yaml
Labels: area/environments, cla: yes, size/XS

#32613 Automator: update common-files@master in istio/istio@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32586 minor listener refactor
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/filterchain_options.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_address.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/util/util.go
Labels: cla: yes, release-notes-none, size/L

#32608 remove unused istioctl/pkg/convert/lister-wrapper.go
  istioctl/pkg/convert/lister-wrapper.go
Labels: cla: yes, ok-to-test, release-notes-none, size/M

#32579 Bump year in license.
  LICENSE
Labels: cla: yes, release-notes-none, size/XS

#32614 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32618 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32257 allow configuring delayed closed timeout
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: cla: yes, release-notes-none, size/L

#32624 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32416 Add DNS capture into CNI.
  cni/cmd/istio-cni/iptables.go
  cni/cmd/istio-cni/kubernetes.go
  cni/cmd/istio-cni/main.go
  cni/cmd/istio-cni/main_test.go
  cni/cmd/istio-cni/redirect.go
  cni/pkg/install-cni/pkg/config/config.go
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  pkg/test/framework/components/istio/operator.go
  releasenotes/notes/cni-dns-capture.yaml
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/endpointslice/endpointslice_test.go
  tests/integration/pilot/routing_test.go
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-clean-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: cla: yes, size/L

#32625 allow specifying additional echo workloads
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/echoboot/flags.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/L

#32626 Handle the error of failing to marshal a token request
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: area/security, cla: yes, release-notes-none, size/S

#32621 Change STS logging statements from Debugf to Errorf
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#32635 support embedding topolgoy in istio.test.config
  pkg/test/framework/components/echo/echoboot/flags.go
  pkg/test/framework/components/environment/kube/flags.go
  pkg/test/framework/components/environment/kube/settings.go
  pkg/test/framework/config/config.go
  pkg/test/framework/config/map.go
  pkg/test/framework/resource/version.go
Labels: cla: yes, release-notes-none, size/L

#32577 Dump istio-cni daemonset in integ test.
  pkg/test/framework/components/istio/helm.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/S

#32629 [1.9] Stop creating namespace when --dry-run is set
  operator/pkg/helmreconciler/reconciler.go
Labels: cla: yes, release-notes-none, size/XS

#32627 Stop requiring configmap for `kube-inject`
  istioctl/cmd/kubeinject.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/S

#32615 Remove deprecated resources from operator
  operator/pkg/helmreconciler/prune.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/S

#32617 Various improvements to istio-agent logging
  pilot/cmd/pilot-agent/options/security.go
  pkg/istio-agent/agent.go
  pkg/security/security.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/M

#32587 refactor ads and delta
  pilot/pkg/model/context.go
  pilot/pkg/networking/apigen/apigen.go
  pilot/pkg/networking/grpcgen/grpcgen.go
  pilot/pkg/xds/cds.go
  pilot/pkg/xds/debuggen.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/ecds.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/lds.go
  pilot/pkg/xds/nds.go
  pilot/pkg/xds/pcds.go
  pilot/pkg/xds/proxy_dependencies.go
  pilot/pkg/xds/proxy_dependencies_test.go
  pilot/pkg/xds/rds.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/statusgen.go
  pilot/pkg/xds/xdsgen.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: cla: yes, release-notes-none, size/M

#32641 [release-1.10] Stop requiring configmap for `kube-inject`
  istioctl/cmd/kubeinject.go
Labels: cla: yes, release-notes-none, size/S

#32616 Remote istio-reader needs more cluster permissions
  istioctl/pkg/multicluster/remote_secret.go
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/XS

#32654 Consolidate peer authn and authn policy MTLS mode conversion func
  pilot/pkg/model/authentication.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
Labels: area/security, cla: yes, release-notes-none, size/M

#32609 Fix: istioctl dashboard envoy does not default namespace
  istioctl/cmd/dashboard.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/XS

#32631 [release-1.10] echogen: util for manual testing with echo
  pkg/test/framework/components/cluster/fake.go
  pkg/test/framework/components/cluster/staticvm/namespace.go
  pkg/test/framework/components/cluster/staticvm/staticvm.go
  pkg/test/framework/components/cluster/staticvm/staticvm_test.go
  pkg/test/framework/components/echo/cmd/echogen/README.md
  pkg/test/framework/components/echo/cmd/echogen/echogen.go
  pkg/test/framework/components/echo/cmd/echogen/echogen_test.go
  pkg/test/framework/components/echo/cmd/echogen/testdata/config.yaml
  pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
  pkg/test/framework/components/echo/common/defaults.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/config_test.go
  pkg/test/framework/components/echo/echotest/fake.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/namespace/static.go
  pkg/test/util/yml/apply_test.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/cross_revision_test.go
  tests/integration/pilot/mcs/serviceexport_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/jwt_test.go
Labels: cla: yes, release-notes-none, size/XXL

#32660 [release-1.10] Fix: istioctl dashboard envoy does not default namespace
  istioctl/cmd/dashboard.go
Labels: cla: yes, release-notes-none, size/XS

#32663 [release-1.10] Deprecate first party jwt option
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
Labels: cla: yes, release-notes-none, size/XS

#32651 [release-1.10] Remote istio-reader needs more cluster permissions
  istioctl/pkg/multicluster/remote_secret.go
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: cla: yes, release-notes-none, size/XS

#32647 minor renaming and refactoring in envoy filters
  istioctl/cmd/describe.go
  pilot/pkg/model/listener.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/simulation/traffic.go
Labels: area/networking, cla: yes, release-notes-none, size/XL

#32658 Fix panic on invalid mesh config
  pkg/config/mesh/kubemesh/watcher_test.go
  pkg/config/mesh/watcher.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/S

#32679 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32661 Skip test dump if no pods found.
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/XS

#32682 Automator: update common-files@release-1.10 in istio/istio@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32666 Add helm-based revision upgrade test
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
  tests/util/sanitycheck/sanity_check.go
Labels: area/environments, area/test and release, cherrypick/release-1.10, cla: yes, release-notes-none, size/L

#32683 Automator: update istio/api@release-1.10 dependency in istio/istio@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32688 Adjust the order of authenticators
  pilot/pkg/bootstrap/server.go
Labels: area/security, cla: yes, release-notes-none, size/XS

#32685 [release-1.10] Add helm-based revision upgrade test
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
  tests/util/sanitycheck/sanity_check.go
Labels: cla: yes, release-notes-none, size/L

#32690 use k8s yaml library for ci dump
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/XS

#32686 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32593 istio-agent: add checks for XDS root CA existence
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#32676 [release-1.10] Fix panic on invalid mesh config
  pkg/config/mesh/kubemesh/watcher_test.go
  pkg/config/mesh/watcher.go
Labels: cla: yes, release-notes-none, size/S

#32671 trustbundle: return error when replacing td in principal fails
  pilot/pkg/security/trustdomain/bundle.go
  pilot/pkg/security/trustdomain/bundle_test.go
Labels: area/security, cla: yes, release-notes-none, size/M

#32693 [release-1.10] Adjust the order of authenticators
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, release-notes-none, size/XS

#32692 Use credential fetcher to fetch token for XDS
  security/pkg/nodeagent/caclient/credentials.go
  security/pkg/nodeagent/caclient/credentials_test.go
Labels: area/security, cherrypick/release-1.10, cla: yes, release-notes-none, size/M

#32694 [release-1.10] Use credential fetcher to fetch token for XDS
  security/pkg/nodeagent/caclient/credentials.go
  security/pkg/nodeagent/caclient/credentials_test.go
Labels: cla: yes, release-notes-none, size/M

#32684 wait for secrets cache sync
  pilot/pkg/bootstrap/server.go
  pilot/pkg/secrets/kube/multicluster.go
Labels: cla: yes, release-notes-none, size/M

#32632 [release-1.10] Handle the error of failing to marshal a token request
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: cla: yes, release-notes-none, size/S

#32633 [release-1.10] Change STS logging statements from Debugf to Errorf
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Labels: cla: yes, release-notes-none, size/XS

#32674 istioctl dashboard: improve port-forward error message to mention namespace
  istioctl/pkg/util/handlers/handlers.go
  pkg/kube/portforwarder.go
Labels: cla: yes, release-notes-none, size/XS

#32515 allow resolving same-network cross-cluster headless services
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/name_table.go
  pkg/test/framework/components/echo/echotest/filters.go
  pkg/test/framework/components/echo/instances.go
  releasenotes/notes/27342.yaml
  samples/helloworld/helloworld.yaml
  tests/integration/iop-integration-test-defaults.yaml
  tests/integration/pilot/cni/cni_test.go
  tests/integration/pilot/common/routing.go
  tests/integration/security/util/connection/checker.go
  tests/integration/security/util/reachability/context.go
Labels: cla: yes, size/M

#32699 [release-1.9] wait for secrets cache sync
  pilot/pkg/bootstrap/server.go
  pilot/pkg/secrets/kube/multicluster.go
Labels: cla: yes, release-notes-none, size/M

#32706 kubejwt-authenticator: use dynamically updated trust domain
  pilot/pkg/bootstrap/server.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
Labels: area/security, cla: yes, release-notes-none, size/M

#32707 Remove redundant open files
  operator/pkg/helm/urlfetcher.go
Labels: area/environments, cla: yes, release-notes-none, size/XS

#32710 Fix usage
  pilot/tools/debug/pilot_cli.go
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#32715 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32718 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32712 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32473 Make installer create istiod service if none detected for revisioned install
  operator/cmd/mesh/install.go
  operator/cmd/mesh/uninstall.go
  pkg/url/url.go
  releasenotes/notes/revision-install-create-istiod-service.yaml
Labels: area/environments, cherrypick/release-1.10, cla: yes, size/L

#32700 tf: Improvements to traffic generator
  pkg/test/framework/components/echo/util/traffic/generator.go
  pkg/test/framework/components/echo/util/traffic/result.go
  tests/integration/pilot/revisioned_upgrade_test.go
Labels: cla: yes, release-notes-none, size/M

#32721 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32720 [release-1.10] Make installer create istiod service if none detected for revisioned install
  operator/cmd/mesh/install.go
  operator/cmd/mesh/uninstall.go
  pkg/url/url.go
  releasenotes/notes/revision-install-create-istiod-service.yaml
Labels: cla: yes, release-notes-none, size/L

#32496 xds: add bootstrap discovery service
  manifests/profiles/preview.yaml
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pilot/docker/Dockerfile.pilot
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bootstrapds.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/v3/model.go
  pkg/bootstrap/config.go
  pkg/bootstrap/config_test.go
  pkg/bootstrap/instance.go
  pkg/envoy/agent.go
  pkg/envoy/agent_test.go
  pkg/envoy/proxy.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
  tools/istio-docker.mk
Labels: cla: yes, release-notes-none, size/L

#32713 Preserve tty when running under `bin/retry.sh`
  bin/retry.sh
Labels: cla: yes, release-notes-none, size/S

#32705 Fix comments for inbound cluster building
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: cla: yes, release-notes-none

#32717 Do not bind ports until we are ready
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/M

#32636 Add upgrade survey to install command
  operator/cmd/mesh/install.go
Labels: cla: yes, release-notes-none, size/XS

#32744 ca: separate self-signed debug mode without K8s from plugged cert mode
  pilot/pkg/bootstrap/istio_ca.go
  security/pkg/pki/ca/ca.go
Labels: cla: yes, release-notes-none, size/L

#32736 [release-1.10] Do not bind ports until we are ready
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
Labels: cla: yes, release-notes-none, size/M

#32698 [release-1.10] wait for secrets cache sync
  pilot/pkg/bootstrap/server.go
  pilot/pkg/secrets/kube/multicluster.go
Labels: cla: yes, release-notes-none, size/M

#32750 Deflake pilot mc tests by sending single requests
  tests/integration/pilot/common/routing.go
Labels: cla: yes, release-notes-none, size/M

#32758 [release-1.10] Support SHARED_MESH_CONFIG with FileWatcher
  pilot/pkg/bootstrap/mesh.go
  pkg/config/mesh/kubemesh/watcher.go
  pkg/config/mesh/kubemesh/watcher_test.go
  pkg/config/mesh/mesh.go
  pkg/config/mesh/watcher.go
  pkg/config/mesh/watcher_test.go
Labels: cla: yes, release-notes-none, size/M

#32753 Make revision tags work against older versions
  istioctl/cmd/tag.go
  istioctl/cmd/tag_test.go
Labels: area/environments, cherrypick/release-1.10, cla: yes, release-notes-none, size/L

#32759 Don't watch debug URLs
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
Labels: cla: yes, release-notes-none, size/S

#32783 xds: abort bootstrap discovery on ctrl-c
  pkg/istio-agent/agent.go
Labels: cla: yes, release-notes-none, size/XS

#32767 Backport mutating webhook port in yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
Labels: cla: yes, release-notes-none, size/XS

#32748 ca: reuse consts instead of hardcode where applicable
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/istio_ca_test.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/k8s/chiron/controller_test.go
  security/pkg/k8s/controller/casecret.go
  security/pkg/k8s/secret/secret_util.go
  security/pkg/k8s/secret/secret_util_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
  security/tools/generate_cert/main.go
  tests/integration/security/chiron/dns_cert_test.go
  tests/integration/security/util/cert/cert.go
  tests/integration/security/util/secret/secret.go
Labels: area/security, cla: yes, release-notes-none, size/L

#32793 Update go-control-plane go.mod replace
  go.mod
  go.sum
Labels: cla: yes, size/S

#31957 [release-1.10] mtls checker handles dr explicitly setting ISTIO_MUTUAL
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters_test.go
Labels: cla: yes, release-notes-none, size/L

#32754 [kiali] bump to v1.34
  manifests/addons/gen.sh
  manifests/addons/values-kiali.yaml
  releasenotes/notes/kiali-update-v1.34.yaml
  samples/addons/kiali.yaml
Labels: area/environments, cherrypick/release-1.10, cla: yes, size/L

#32643 [release-1.10] Remove deprecated resources from operator
  operator/pkg/helmreconciler/prune.go
Labels: cla: yes, release-notes-none, size/S

#32804 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32799 Automator: update common-files@release-1.10 in istio/istio@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32805 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32797 Automator: update proxy@release-1.10 in istio/istio@release-1.10
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32812 Automator: update istio/api@release-1.10 dependency in istio/istio@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32580 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32724 Switch handling of missing routes to send no response instead of empty
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: cla: yes, release-notes-none, size/S

#32811 do not read empty file on retry.sh error
  bin/retry.sh
Labels: cla: yes, release-notes-none, size/XS

#32824 Cleanup stale env after removal of Gateway SDS from the agent
  pilot/pkg/features/pilot.go
Labels: area/networking, cla: yes, release-notes-none, size/XS

#32358 Fix PDB maxUnavailable field cannot be set in Istio operator
  operator/pkg/object/objects.go
  operator/pkg/object/objects_test.go
  operator/pkg/translate/translate.go
  releasenotes/notes/31910.yaml
Labels: area/environments, cherrypick/release-1.10, cla: yes, size/L

#32815 Update go-control-plane; needed for cve
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: cherrypick/release-1.10, cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#32836 Automator: update common-files@release-1.9 in istio/istio@release-1.9
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32829 Automator: update proxy@release-1.8 in istio/istio@release-1.8
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32830 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32837 Automator: update istio/api@release-1.9 dependency in istio/istio@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32818 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32808 Fix pilot/TestTproxy for multiversion tests
  tests/integration/pilot/original_src_addr_test.go
Labels: cla: yes, release-notes-none, size/S

#32826 cleanup: re-remove canonical service/revision and service cluster
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istiod-remote/files/gateway-injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  pilot/cmd/pilot-agent/main.go
Labels: cla: yes, release-notes-none, size/M

#32810 Port 1.9.5 to release-1.9
  Makefile.core.mk
  go.mod
  go.sum
  istio.deps
  licenses/github.com/cncf/xds/go/LICENSE
  licenses/go.opentelemetry.io/proto/otlp/LICENSE
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/networking/grpcgen/testdata/xds_bootstrap.json
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pilot/test/grpcgen/grpcinit.go
  pkg/adsc/adsc_test.go
  pkg/config/validation/validation.go
  pkg/config/xds/filter_types.gen.go
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/common/call.go
  security/pkg/stsservice/mock/xdsserver.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/normalization_test.go
Labels: cla: yes, release-notes-none, size/XXL

#32839 Cherrypick 5/11 security release
  Makefile.core.mk
  go.mod
  go.sum
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pkg/config/xds/filter_types.gen.go
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/istio/util.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/multicluster_test.go
  tests/integration/security/normalization_test.go
Labels: cla: yes, release-notes-none, size/XL

#32844 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32840 Cherrypick 5/11 security fixes to master
  Makefile.core.mk
  go.mod
  go.sum
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pkg/test/framework/components/echo/call.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/istio/util.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/multicluster_test.go
  tests/integration/security/normalization_test.go
Labels: cla: yes, release-notes-none, size/XL

#32823 pilot-agent: remove unnecessary error and checks in SDS server
  pkg/istio-agent/agent.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/sdsservice_test.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/test/setup.go
Labels: area/networking, cla: yes, release-notes-none, size/S

#32845 Log listener termination in echo server
  pkg/test/echo/server/endpoint/grpc.go
  pkg/test/echo/server/endpoint/http.go
Labels: cla: yes, release-notes-none, size/XS

#32854 Get proxy workload label from specified cluster
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: cla: yes, release-notes-none, size/S

#32851 Fix Comments
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Labels: cla: yes, release-notes-none, size/XS

#32861 [release-1.10] Run UPDATE_BRANCH=release-1.10 ./bin/update_deps.sh
  go.mod
  go.sum
  prow/release-commit.sh
Labels: cla: yes, release-notes-none, size/S

#32857 remove redudant ResyncPeriod, actually not used
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
Labels: cla: yes, release-notes-none, size/XS

#32849 Log which container crashed
  pkg/test/kube/dump.go
Labels: cla: yes, release-notes-none, size/XS

#32549 dashboard: switch sent/received for outbound TCP connections
  manifests/addons/dashboards/istio-workload-dashboard.json
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/S

#32866 [release-1.10] dashboard: switch sent/received for outbound TCP connections
  manifests/addons/dashboards/istio-workload-dashboard.json
Labels: cla: yes, release-notes-none, size/S

#32869 Fix name of TestPassThroughFilterChain
  tests/integration/security/pass_through_filter_chain_test.go
Labels: cla: yes, release-notes-none, size/L

#32872 Fix broken release notes in 1.10 only
  releasenotes/notes/19300.yaml
  releasenotes/notes/30067.yaml
  releasenotes/notes/30683.yaml
  releasenotes/notes/31075.yaml
  releasenotes/notes/31186.yaml
  releasenotes/notes/31403.yaml
  releasenotes/notes/31573.yaml
  releasenotes/notes/31779.yaml
  releasenotes/notes/31797.yaml
  releasenotes/notes/31853.yaml
  releasenotes/notes/auto-mtls-passthrough.yaml
  releasenotes/notes/inbound-passthrough.yaml
  releasenotes/notes/inbound-patch.yaml
  releasenotes/notes/pilot-discovery-scoped-namespaces.yaml
  releasenotes/notes/revision-tag-command.yaml
  releasenotes/notes/scope-push-by-sidecar-changes.yaml
  releasenotes/notes/vm-cleanup-iptables.yaml
  releasenotes/notes/vs-ineffective-warning.yaml
Labels: cla: yes, size/M

#32870 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32871 Fix broken release notes
  releasenotes/notes/27342.yaml
  releasenotes/notes/31095.yaml
  releasenotes/notes/31910.yaml
  releasenotes/notes/32201.yaml
  releasenotes/notes/agent-xds-piggyback.yaml
  releasenotes/notes/cni-dns-capture.yaml
  releasenotes/notes/inbound-passthrough.yaml
  releasenotes/notes/istiod-config-size-bytes.yaml
  releasenotes/notes/strict_1xx_204_fix.yaml
  releasenotes/template.yaml
Labels: cla: yes, size/S

#32777 fixed issue#32567
  pilot/pkg/config/kube/crdclient/client.go
Labels: area/networking, area/user experience, cla: yes, release-notes-none, size/XS

#32864 Fix log in pilot gateway
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: cla: yes, release-notes-none, size/XS

#32867 Fix local address for ipv6 probes
  pilot/cmd/pilot-agent/status/server.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/XS

#32739 minor refactor to dns proxy
  pilot/pkg/dns/dns.go
  pilot/pkg/dns/proxy.go
Labels: area/networking, cla: yes, release-notes-none, size/M

#32877 [release-1.10] Fix local address for ipv6 probes
  pilot/cmd/pilot-agent/status/server.go
Labels: cla: yes, release-notes-none, size/XS

#32681 Sample Jaeger version 1.20 -> 1.22
  releasenotes/notes/update-jaeger-v1.22.yaml
  samples/addons/jaeger.yaml
Labels: cla: yes, size/S

#32652 Istiod CA: Ensure Istiod certs initialized when Pilot Cert Provider i…
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
Labels: cla: yes, size/L

#32889 Add log before busy waiting for CNI network config.
  cni/pkg/install-cni/pkg/install/cniconfig.go
Labels: cla: yes, release-notes-none, size/XS

#32890 increase dns timeouts
  pilot/pkg/dns/proxy.go
Labels: cla: yes, release-notes-none, size/XS

#32893 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32723 [Cherry-pick] Adjust the order of authenticators
  pilot/pkg/bootstrap/server.go
Labels: cla: yes, release-notes-none, size/XS

#32838 Automator: update proxy@release-1.9 in istio/istio@release-1.9
  istio.deps
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#32675 Support setting namespaces on gateway charts
  manifests/charts/gateways/istio-egress/templates/_affinity.tpl
  manifests/charts/gateways/istio-ingress/templates/_affinity.tpl
Labels: cla: yes, release-notes-none, size/S

#32847 Fix flakes in TestMultiWatcherShouldNotifyHandlers
  pkg/config/mesh/watcher.go
  pkg/config/mesh/watcher_test.go
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/S

#32814 Remove watchedNamespace
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
Labels: cla: yes, release-notes-none, size/S

#32876 Fix the upgrade and downgrade message of the control plane
  operator/cmd/mesh/install.go
  releasenotes/notes/32749.yaml
  security/pkg/k8s/controller/casecret.go
  security/pkg/stsservice/server/server_test.go
  security/pkg/stsservice/tokenmanager/sts_test.go
Labels: cla: yes, ok-to-test, size/S

#32882 pilot: unify pilot cert provider for agent and discovery
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pilot/cmd/pilot-agent/options/options.go
  pilot/cmd/pilot-agent/options/security.go
  pilot/pkg/bootstrap/certcontroller.go
  pkg/config/constants/constants.go
  pkg/istio-agent/agent.go
  pkg/security/security.go
Labels: area/networking, area/security, cla: yes, release-notes-none, size/M

#32850 bootstrap: cleanup status ports and config dir
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/pkg/model/context.go
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/envoy/agent.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/agent_test.go
  tools/packaging/common/envoy_bootstrap.json
Labels: cla: yes, release-notes-none, size/L

#32873 Fix TTL log
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
Labels: cla: yes, release-notes-none, size/XS

#32433 Remove dprecated field useLegacySelector
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: cla: yes, release-notes-none, size/L

#32910 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/M

#32913 Check result of cache.WaitForCacheSync()
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingressv1/controller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcontroller.go
  pkg/config/mesh/kubemesh/watcher.go
  security/pkg/k8s/chiron/controller.go
Labels: cla: yes, release-notes-none, size/M
