Repository istio/istio, pull requests merged in 2022-12, with the labels that each got.

#42216 Reduce unnecessary workload handler calls on pod updates
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
Labels: area/networking, size/M, release-notes-none

#42233 Add min version required to 20 for tests using k8sca
  releasenotes/notes/deprecate-k8sca-upto-v1.20.yaml
  tests/integration/security/mtlsk8sca/main_test.go
  tests/integration/security/sds_ingress_k8sca/main_test.go
Labels: area/test and release, area/security, ok-to-test, size/S

#42231 Automator: update proxy@release-1.14 in istio/istio@release-1.14
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42242 rust tests in CI
  istio.deps
  manifests/charts/ztunnel/values.yaml
  pkg/test/framework/resource/settings.go
  tests/integration/ambient/main_test.go
Labels: size/S

#42245 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42244 gateway-api bump to v0.6.0-rc1
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/alias.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/delegated.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mcs.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-service.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/XL, release-notes-none

#42241 [release-1.14] Update go modules (#40597)
  go.mod
  go.sum
  istioctl/cmd/metrics_test.go
  licenses/cloud.google.com/go/compute/metadata/LICENSE
  licenses/github.com/googleapis/enterprise-certificate-proxy/LICENSE
  pilot/pkg/networking/core/v1alpha3/envoyfilter/extension_configuration_patch_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/status/distribution/state_test.go
  pkg/config/schema/resource/schema_test.go
  pkg/test/echo/cmd/client/main.go
Labels: size/XL, release-notes-none

#42239 [release-1.15] Update go modules (#40597)
  go.mod
  go.sum
  istioctl/cmd/metrics_test.go
  licenses/cloud.google.com/go/compute/metadata/LICENSE
  pilot/pkg/networking/core/v1alpha3/envoyfilter/extension_configuration_patch_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/status/distribution/state_test.go
  pkg/config/schema/resource/schema_test.go
  pkg/test/echo/cmd/client/main.go
Labels: size/L, release-notes-none

#42254 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42258 [release-1.16] validate opentelemetry tracing extension provider
  pkg/config/validation/extensionprovider.go
  pkg/config/validation/extensionprovider_test.go
Labels: size/M, release-notes-none

#42255 Make pod/node unused fields removed.
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: size/L, release-notes-none

#42259 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42264 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42250 add waypoint integration tests for authz coverage
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none, area/ambient

#42293 Update BASE_VERSION to master-2022-12-05T19-01-23
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#42292 Update BASE_VERSION to 1.16-2022-12-05T19-01-28
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#42291 Update BASE_VERSION to 1.15-2022-12-05T19-01-24
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#42294 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42248 pilot: ensure initialization of secure grpc server also when serving …
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
  releasenotes/notes/42248.yaml
Labels: area/environments, ok-to-test, size/M

#42286 [UT] improve test for operator/pkg/istio/v1alpha1
  operator/pkg/apis/istio/v1alpha1/deepcopy_test.go
  operator/pkg/apis/istio/v1alpha1/testdata/quantity.yaml
Labels: size/XS, release-notes-none

#42295 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42301 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42300 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42252 Fix remote cluster sync timeout issue
  pilot/pkg/serviceregistry/kube/controller/controller.go
  releasenotes/notes/42252.yaml
Labels: size/S

#42188 Fix ENABLE_ENHANCED_RESOURCE_SCOPING bug
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/serviceentry/namespace_handler.go
  releasenotes/notes/42173.yaml
Labels: size/L

#42324 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42345 Revert "[release-1.16] Fix ENABLE_ENHANCED_RESOURCE_SCOPING bug (#42188)"
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/serviceentry/namespace_handler.go
  releasenotes/notes/42173.yaml
Labels: size/L, release-notes-none

#42329 ignore non tcp port and figure out named port
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/S

#42352 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42353 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42355 Automator: update istio/client-go@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42358 Automator: update proxy@release-1.14 in istio/istio@release-1.14
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42356 Fix TestControllerEnableResourceScoping data race
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
Labels: size/M, release-notes-none

#42230 Ignore events from other revisions in cache handler
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/config/kube/crdclient/cache_handler_test.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
  releasenotes/notes/42212.yaml
Labels: area/networking, ok-to-test, size/L

#42302 migrate to protojson
  istioctl/pkg/writer/envoy/configdump/configdump.go
Labels: size/S, release-notes-none

#42282 remove redundant config check in ecds
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/xds/ecds.go
  pilot/pkg/xds/ecds_test.go
  pilot/pkg/xds/sds.go
Labels: size/L, release-notes-none

#42362 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42363 update go-control-plane
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, release-notes-none

#42361 Automator: update common-files@release-1.16 in istio/istio@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42237 Handling Istiod DNS cert rotation for k8s CA
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/server_test.go
  pkg/testcerts/testcerts.go
Labels: area/security, ok-to-test, size/L, release-notes-none

#42348 Make TestResolveAddr err check less strict
  pilot/pkg/util/network/ip_test.go
Labels: size/XS, release-notes-none

#42367 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41618 Add extra source addresses for Inbound cluster via upstream bindconfig to support dual stack in Istio
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_address.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/util/util.go
  releasenotes/notes/40394.yaml
  tests/integration/security/main_test.go
  tests/integration/security/reachability_test.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/root_test.go
Labels: size/L

#42370 Update BASE_VERSION to 1.14-2022-12-08T19-00-42
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#42119 add partial wildcard checks to Gateway and Sidecar
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/42119.yaml
Labels: ok-to-test, size/M

#42375 Fix nil pointer check on ambient controller
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/XS, release-notes-none

#42378 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42381 Add excludeInterfaces support to istio cni plugin
  cni/pkg/plugin/plugin_test.go
  cni/pkg/plugin/redirect.go
  releasenotes/notes/42381.yaml
Labels: size/M

#42346 xds: fix reconnect on-demand XDS in ambient and Service subscriptions
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/workload.go
  pilot/pkg/xds/workload_test.go
Labels: size/L, release-notes-none

#42379 fix dns round robin discovery
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/serviceregistry/serviceentry/store.go
  pilot/pkg/serviceregistry/serviceentry/store_test.go
Labels: size/M, release-notes-none

#42383 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42351 Cleanup Envoy ztunnel implementation and code
  istio.deps
  istioctl/pkg/util/configdump/workload.go
  manifests/charts/ztunnel/templates/daemonset.yaml
  pilot/pkg/networking/ambientgen/waypointgen.go
  pilot/pkg/networking/ambientgen/ztunnelgen.go
  pilot/pkg/networking/ambientgen/ztunnelgen_test.go
  pilot/pkg/xds/discovery.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  tests/integration/ambient/baseline_test.go
Labels: size/XXL

#42391 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42386 move to struct and handle delete
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/store.go
  pilot/pkg/serviceregistry/serviceentry/store_test.go
Labels: release-notes-none

#42394 fix deprecate apiversion for ingress in testdata
  pkg/config/analysis/analyzers/testdata/misannotated.yaml
Labels: ok-to-test, size/XS, release-notes-none

#42404 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42406 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42397 Bump k8s dependencies to v0.26
  go.mod
  go.sum
  licenses/cloud.google.com/go/iam/LICENSE
  licenses/github.com/Azure/go-autorest/autorest/LICENSE
  licenses/github.com/Azure/go-autorest/autorest/adal/LICENSE
  licenses/github.com/Azure/go-autorest/autorest/date/LICENSE
  licenses/github.com/Azure/go-autorest/logger/LICENSE
  licenses/github.com/Azure/go-autorest/tracing/LICENSE
  licenses/github.com/PuerkitoBio/purell/LICENSE
  licenses/github.com/PuerkitoBio/urlesc/LICENSE
  licenses/github.com/golang-jwt/jwt/v4/LICENSE
  licenses/github.com/russross/blackfriday/LICENSE.txt
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/gatewayclass.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingressv1/status.go
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/kube/controller/autoserviceexportcontroller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pilot/pkg/status/distribution/state.go
  pkg/config/xds/filter_types.gen.go
  pkg/kube/client.go
  pkg/kube/configmapwatcher/configmapwatcher.go
  pkg/kube/fakemirror.go
  pkg/kube/informer/filter.go
  pkg/kube/mock_client.go
  pkg/kube/multicluster/secretcontroller.go
  pkg/revisions/default_watcher.go
  pkg/test/framework/components/stackdriver/google.go
  pkg/test/framework/components/stackdriver/kube.go
  pkg/test/framework/components/stackdriver/stackdriver.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/webhookpatch.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
  tests/integration/telemetry/stackdriver/vm/vm_test.go
Labels: size/XXL, release-notes-none

#42365 istioctl: support `pc ecds` command
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/util/configdump/ecds.go
  istioctl/pkg/util/configdump/util.go
  istioctl/pkg/writer/envoy/configdump/ecds.go
  istioctl/pkg/writer/envoy/configdump/ecds_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/ecds/configdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.json
  istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.txt
  istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.yaml
  releasenotes/notes/42365.yaml
Labels: area/user experience, size/L

#42407 Add two more tips for Mac OS users
  CONTRIBUTING.md
Labels: size/XS

#42385 fix ds post submit integration test issues
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_address.go
  pilot/pkg/networking/util/util.go
Labels: size/M, release-notes-none

#42415 go on to fix the integ-ds_istio_postsubmit job failed
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/util/util.go
Labels: size/M, release-notes-none

#42416 fix namepace controller leader election event handler leak
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
Labels: size/XS, release-notes-none

#42384 Cleanup CNI and iptables binaries
  Makefile.core.mk
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/redirect.go
  tools/docker.yaml
  tools/istio-clean-iptables/main.go
  tools/istio-clean-iptables/main_test.go
  tools/istio-iptables/.gitignore
  tools/istio-iptables/main.go
  tools/istio-iptables/main_test.go
  tools/istio-iptables/pkg/config/validation_test.go
  tools/istio-iptables/pkg/testing/data/data.go
  tools/istio-iptables/pkg/testing/maintest/testing.go
Labels: size/L, release-notes-none

#42420 fix gateway deployment controller leader election event handler leak
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
Labels: size/S, release-notes-none

#42418 Revise some injection annotations to labels in samples
  samples/addons/extras/prometheus_vm.yaml
  samples/addons/extras/prometheus_vm_tls.yaml
  samples/addons/extras/skywalking.yaml
  samples/addons/extras/zipkin.yaml
  samples/addons/jaeger.yaml
Labels: size/XS, release-notes-none

#42422 Fix gateway service dependencies
  pilot/pkg/model/sidecar.go
  pilot/pkg/xds/proxy_dependencies.go
  pilot/pkg/xds/proxy_dependencies_test.go
  releasenotes/notes/42400.yaml
Labels: size/L

#41912 Fix verify-install inconsistent behavior
  istioctl/pkg/verifier/verifier.go
  operator/cmd/mesh/shared.go
  releasenotes/notes/41912.yaml
Labels: size/S, release-notes-none

#42433 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42431 Minor CONTRIBUTING update
  CONTRIBUTING.md
Labels: size/XS, release-notes-none

#42436 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42440 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42445 Automator: update common-files@master in istio/istio@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#42160 istioctl: fix `istioctl operator remove` fail when not specify reversion
  operator/cmd/mesh/operator-common.go
  operator/cmd/mesh/operator-init.go
  releasenotes/notes/42160.yaml
  tests/integration/operator/switch_cr_test.go
Labels: area/environments, size/M

#42446 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#42447 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42430 Fix gateway deployment
  istio.deps
  manifests/charts/base/crds/gateway-api-crds.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/S

#42442 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42113 gateway-api: support InvalidTLSConfiguration
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml
  pilot/pkg/credentials/kube/multicluster.go
  pilot/pkg/credentials/model.go
  pilot/pkg/model/context.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/ecds.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/simple.go
  tests/integration/pilot/gateway_conformance_test.go
Labels: area/networking, size/L, release-notes-none

#42455 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42456 Auto-name the VS routes in HTTPRoute auto-generated
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/alias.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/delegated.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-service.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-binding.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
Labels: size/L, release-notes-none

#42458 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42287 improve metav1 package import statement
  istioctl/cmd/analyze.go
  operator/pkg/apis/istio/v1alpha1/types.go
  pkg/test/framework/components/istio/eastwest.go
Labels: size/S, release-notes-none

#42461 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42412 Fix locality label missing
  pilot/pkg/xds/ads.go
  pkg/bootstrap/config.go
  pkg/bootstrap/config_test.go
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  releasenotes/notes/42414.yaml
Labels: size/S

#42468 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42471 Automator: update common-files@release-1.16 in istio/istio@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42472 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42469 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42466 Update go-control-plane
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: area/test and release, size/XS, release-notes-none

#42475 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42473 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#42438 fix incorrect code style
  samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
Labels: ok-to-test, size/XS, release-notes-none

#42470 Automator: update common-files@master in istio/istio@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#42477 ep builder: check invidual proxy has hbone
  pilot/pkg/model/context.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/endpoint_builder.go
Labels: size/M

#42491 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42492 Dependabot specified updates
  go.mod
  go.sum
Labels: area/test and release, size/M, release-notes-none

#42493 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42500 Revert PR #42160
  operator/cmd/mesh/operator-common.go
  operator/cmd/mesh/operator-init.go
  releasenotes/notes/42160.yaml
  tests/integration/operator/switch_cr_test.go
Labels: size/M, release-notes-none

#42503 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42504 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42505 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42501 [release-1.15] Let the double-layer loop deep copy object of large array change to once
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go
Labels: size/L, release-notes-none

#42489 close all servers of agent properly
  pilot/cmd/pilot-agent/app/cmd.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/agent_test.go
  pkg/istio-agent/xds_proxy_test.go
Labels: area/networking, size/XS, release-notes-none

#42494 agent: fail fast on first error
  pilot/cmd/pilot-agent/status/server.go
Labels: size/XS, release-notes-none

#42506 Fixes for shellcheck 0.9.0
  samples/bookinfo/platform/kube/cleanup.sh
  tools/packaging/common/istio-start.sh
Labels: area/test and release, size/S, release-notes-none

#42464 Convert base image registry to ARG
  Makefile.core.mk
  cni/deployments/kubernetes/Dockerfile.install-cni
  istioctl/docker/Dockerfile.istioctl
  operator/docker/Dockerfile.operator
  pilot/docker/Dockerfile.pilot
  pilot/docker/Dockerfile.proxyv2
  pkg/test/echo/docker/Dockerfile.app
  pkg/test/echo/docker/Dockerfile.app_sidecar
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_7
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8
  samples/extauthz/docker/Dockerfile
  tools/docker-builder/common.go
  tools/docker-builder/main.go
  tools/docker-builder/types.go
Labels: size/M, release-notes-none

#42387 improve retry backoff for web hook patching during conflict
  pkg/kube/controllers/queue.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
Labels: size/M, release-notes-none

#42512 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42514 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42515 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42509 gateway-api: get parent routes as VS dependencies
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache.go
Labels: area/networking, size/L, release-notes-none

#42521 Update go-control-plane
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: area/test and release, size/M, release-notes-none

#42526 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42530 Fix for shellcheck 0.9.0 (#42506)
  samples/bookinfo/platform/kube/cleanup.sh
  tools/packaging/common/istio-start.sh
Labels: size/S, area/ambient

#42495 TestSidecarRoutes: re-enable for Gateway API
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/xds/fake.go
  pkg/kube/client.go
  pkg/kube/util.go
Labels: size/L, release-notes-none

#42534 Fix merge map losing source content
  pkg/proto/merge/merge.go
  releasenotes/notes/fix-42533.yaml
Labels: area/networking, size/M, cherrypick/release-1.15, cherrypick/release-1.16

#42541 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42543 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42544 Revert "Fix merge map losing source content"
  pkg/proto/merge/merge.go
  releasenotes/notes/fix-42533.yaml
Labels: size/M, release-notes-none

#42538 [gw-api] support experimental path redirect
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: ok-to-test, size/L, release-notes-none

#42546 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42527 set AMBIENT_TYPE env var for ztunnel
  manifests/charts/ztunnel/templates/daemonset.yaml
Labels: size/XS, area/ambient

#42548 fix typo in useGatewaySemantics
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: ok-to-test, size/XS, release-notes-none

#42437 Drop consumer waypoint
  istio.deps
  pilot/pkg/networking/ambientgen/waypointgen.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/xds/endpoint_builder.go
  pkg/test/framework/components/ambient/waypoint.go
  tests/integration/ambient/baseline_test.go
Labels: size/L

#42435 istioctl analyze revision
  istioctl/cmd/analyze.go
  releasenotes/notes/istioctl-analyze-revision.yaml
Labels: size/S

#42554 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#42496 add cookie path support to config via label istio.io/persistent-session
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/networking/grpcgen/lds.go
Labels: area/networking, ok-to-test, size/S, release-notes-none

#42557 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42513 feat(operator): override default k8s version from helm default capabilities
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/pkg/helm/helm.go
  releasenotes/notes/42513.yaml
Labels: area/environments, size/S

#42562 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42556 ToPrettyJSON: ident even for protobuf
  pkg/config/model.go
Labels: size/S, release-notes-none

#42567 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42568 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42536 rename IsNonHTTPTLSServer to IsTLSServer
  pilot/pkg/model/gateway.go
  pkg/config/gateway/gateway.go
  pkg/config/gateway/gateway_test.go
Labels: size/S, release-notes-none

#42577 add test for nds generate
  pilot/pkg/xds/nds_test.go
Labels: area/networking, size/M, release-notes-none

#42559 Update helm integration tests
  tests/integration/helm/install_test.go
  tests/integration/helm/testdata/1.10.0/base.tar.gz
  tests/integration/helm/testdata/1.10.0/gateways/istio-egress.tar.gz
  tests/integration/helm/testdata/1.10.0/gateways/istio-ingress.tar.gz
  tests/integration/helm/testdata/1.10.0/istio-control/istio-discovery.tar.gz
  tests/integration/helm/testdata/1.11.3/base.tar.gz
  tests/integration/helm/testdata/1.11.3/gateways/istio-egress.tar.gz
  tests/integration/helm/testdata/1.11.3/gateways/istio-ingress.tar.gz
  tests/integration/helm/testdata/1.11.3/istio-control/istio-discovery.tar.gz
  tests/integration/helm/testdata/1.15.0/base.tar.gz
  tests/integration/helm/testdata/1.15.0/gateway.tar.gz
  tests/integration/helm/testdata/1.15.0/istio-control/istio-discovery.tar.gz
  tests/integration/helm/testdata/1.16.0/base.tar.gz
  tests/integration/helm/testdata/1.16.0/gateway.tar.gz
  tests/integration/helm/testdata/1.16.0/istio-control/istio-discovery.tar.gz
  tests/integration/helm/testdata/1.8.1/base.tar.gz
  tests/integration/helm/testdata/1.8.1/gateways/istio-egress.tar.gz
  tests/integration/helm/testdata/1.8.1/gateways/istio-ingress.tar.gz
  tests/integration/helm/testdata/1.8.1/istio-control/istio-discovery.tar.gz
  tests/integration/helm/testdata/1.9.0/base.tar.gz
  tests/integration/helm/testdata/1.9.0/gateways/istio-egress.tar.gz
  tests/integration/helm/testdata/1.9.0/gateways/istio-ingress.tar.gz
  tests/integration/helm/testdata/1.9.0/istio-control/istio-discovery.tar.gz
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/main_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: area/test and release, size/L, release-notes-none

#42576 Update grpc.go
  pkg/test/echo/server/endpoint/grpc.go
  releasenotes/notes/42576.yaml
Labels: ok-to-test, size/S

#42578 make fsnotify event more readable.
  pilot/pkg/bootstrap/istio_ca.go
  pkg/kube/inject/watcher.go
  security/pkg/nodeagent/cache/secretcache.go
Labels: ok-to-test, size/S, release-notes-none

#42595 Automator: update istio/client-go@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41923 Add support for allowing cert-manager signers
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.values.gen.yaml
  pkg/kube/inject/testdata/inputs/default.values.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.38.values.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml
  releasenotes/notes/41923.yaml
Labels: area/environments, ok-to-test, size/M

#42590 Repair value override
  pkg/test/framework/components/echo/kube/instance.go
Labels: ok-to-test, size/XS, release-notes-none

#42589 change the library from net to netip for proxy instance's interfaces handling in pilot agent
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/validation/validator.go
Labels: release-notes-none

#42597 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42599 Fix trafficPolicyTLSModeForPort() func cause pilot push XDS panic
  pilot/pkg/xds/endpoint_builder.go
  releasenotes/notes/fix-42598.yaml
Labels: size/M

#42591 close file fd
  pkg/bootstrap/config.go
Labels: ok-to-test, size/XS, release-notes-none

#42018 Update istio-cni to use logAsJson Flag
  manifests/charts/UPDATING-CHARTS.md
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
Labels: area/environments, ok-to-test, size/XS, release-notes-none

#42545 Drop `http.DefaultClient`
  istioctl/cmd/clusters.go
  istioctl/cmd/proxystatus.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  pkg/kube/client.go
  pkg/proxy/proxyinfo.go
  pkg/test/kube/dump.go
Labels: size/S, release-notes-none

#42611 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#42609 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none
