Repository istio/istio, pull requests merged in 2022-08, with the labels that each got.

#40197 Prevent calling json.MarshalIndent and handle err, instead using writ…
  pilot/pkg/xds/debug.go
Labels: size/XS, release-notes-none

#40189 [release-1.14] manual cherry pick 39729
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/testdata/virtualservice_conflictingmeshgatewayhosts.yaml
  pkg/config/analysis/analyzers/testdata/virtualservice_conflictingmeshgatewayhosts_with_exportto.yaml
  pkg/config/analysis/analyzers/util/exportto.go
  pkg/config/analysis/analyzers/util/exportto_test.go
  pkg/config/analysis/analyzers/virtualservice/conflictingmeshgatewayhosts.go
  releasenotes/notes/39729.yaml
Labels: size/L

#40200 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40196 [release-1.14] Fix bug blocking JSON marshal of endpointShardz
  pilot/pkg/model/endpointshards.go
Labels: size/XS, release-notes-none

#40203 fuzz: attempt to fix build by working around fuzzing limitation
  CODEOWNERS
  pkg/fuzz/util.go
Labels: size/XS, release-notes-none

#40202 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40206 Automated branching step 1
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: size/S, release-notes-none

#40208 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40210 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40212 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40211 Automator: update istio/client-go@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40214 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40215 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40072 pilot: fix issue with TLS and TCP order dependency
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/test/xdstest/validate.go
  releasenotes/notes/tls-tcp-conflict.yaml
Labels: size/L, cherrypick/release-1.13, cherrypick/release-1.14

#40218 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40222 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40224 [release-1.15] pilot: fix issue with TLS and TCP order dependency
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/test/xdstest/validate.go
  releasenotes/notes/tls-tcp-conflict.yaml
Labels: size/L, release-notes-none

#40225 Automator: update istio/client-go@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40109 optimize handleStats temporary big byte slice
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
Labels: ok-to-test, size/L, release-notes-none

#40137 Use absolute path when adding file watcher
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/cache/testdata/file-to-watch.txt
Labels: area/security, ok-to-test, size/M, release-notes-none

#40227 [release-1.15] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  prow/release-commit.sh
Labels: size/M, release-notes-none

#40228 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40230 Automator: update istio/api@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40229 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40231 Automator: update istio/pkg@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40204 Fix new linter version
  istioctl/cmd/analyze.go
  istioctl/pkg/writer/compare/comparator.go
  pilot/cmd/pilot-agent/status/server_test.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/proxy_dependencies_test.go
  pkg/kube/multicluster/secretcontroller_test.go
Labels: size/L, release-notes-none

#40234 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40232 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40233 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
Labels: size/S, auto-merge, release-notes-none

#40226 cleanup tunneling code
  pilot/pkg/networking/networking.go
  pilot/pkg/networking/networking_test.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
Labels: area/networking, size/L, release-notes-none

#40235 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40237 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40244 Fix export to logic lead to not found logic
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
  pkg/config/analysis/analyzers/util/service_lookup.go
  pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
  releasenotes/notes/40244.yaml
Labels: area/user experience, size/L

#40242 fix eds comments
  pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
  pilot/pkg/xds/eds.go
Labels: size/XS, release-notes-none

#40248 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40247 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40251 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40254 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40257 [Experimental dual-stack] Run make gen
  cni/pkg/plugin/testdata/basic.txt.golden
  cni/pkg/plugin/testdata/dns.txt.golden
  cni/pkg/plugin/testdata/include-exclude-ip.txt.golden
  cni/pkg/plugin/testdata/include-exclude-ports.txt.golden
  cni/pkg/plugin/testdata/invalid-drop.txt.golden
  cni/pkg/plugin/testdata/tproxy.txt.golden
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/xds/eds.go
  pkg/bootstrap/config.go
Labels: size/M

#40252 Cleanup makefile env vars
  Makefile.core.mk
  bin/init.sh
  tools/packaging/packaging.mk
Labels: size/L, release-notes-none

#40253 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40249 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40261 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40258 Documentation updates for comments in #40255
  cni/pkg/repair/repair_test.go
  operator/pkg/patch/patch.go
  pkg/dns/client/dns_test.go
  pkg/istio-agent/health/health_probers.go
  pkg/kube/inject/initializer.go
  pkg/test/framework/components/echo/echotest/filters.go
  pkg/test/framework/components/echo/echotest/run.go
  pkg/test/framework/components/echo/echotest/setup.go
  pkg/test/framework/components/istio/kube.go
  tools/bug-report/pkg/config/config.go
Labels: size/L, release-notes-none

#39483 Support pulling multi-arch envoy binaries
  Makefile.core.mk
  bin/init.sh
  pkg/test/echo/docker/Dockerfile.app_sidecar
  prow/integ-suite-kind.sh
  prow/lib.sh
  prow/release-commit.sh
  samples/jwt-server/jwt-server.yaml
  samples/jwt-server/src/Dockerfile
  samples/jwt-server/src/Makefile
  tools/docker-builder/builder/crane.go
  tools/docker-builder/common.go
  tools/docker-builder/crane.go
  tools/docker-builder/docker.go
  tools/docker-builder/main.go
  tools/docker-builder/types.go
  tools/docker-copy.sh
  tools/docker.yaml
  tools/packaging/packaging.mk
Labels: size/L, release-notes-none

#40240 Fix fake v1beta1 conversion in validate
  istioctl/pkg/validate/validate.go
Labels: area/user experience, size/XS, release-notes-none

#40262 Remove unused fields of Agent
  pkg/envoy/agent.go
Labels: area/networking, size/XS, release-notes-none

#40263 Bump master to 1.16
  Makefile.core.mk
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.16.yaml
  manifests/charts/istio-operator/files/gen-operator.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.16.yaml
  operator/version/version.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/xds/bench_test.go
  pkg/test/framework/resource/version_test.go
  prow/release-commit.sh
  tools/packaging/common/istio-start.sh
Labels: size/XXL, release-notes-none

#40271 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40272 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40278 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#40279 Add qemulation to release builder
  prow/release-commit.sh
  tools/docker-builder/types.go
Labels: size/M, release-notes-none

#40282 Update BASE_VERSION to 1.13-2022-08-04T19-00-46
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#40285 Automator: update istio/api@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40286 [release-1.14] fix accessLogFormat with req_without_query and JSON encoding
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  releasenotes/notes/39272.yaml
Labels: size/S, release-notes-none

#40287 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40184 change log level
  pkg/config/analysis/local/context.go
  releasenotes/notes/40184.yaml
Labels: size/XS, cherrypick/release-1.13, cherrypick/release-1.14

#40292 [release-1.14] change log level
  pkg/config/analysis/local/context.go
  releasenotes/notes/40184.yaml
Labels: size/XS, release-notes-none

#40291 [release-1.13] change log level
  pkg/config/analysis/local/context.go
  releasenotes/notes/40184.yaml
Labels: size/XS, release-notes-none

#40293 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40269 Add SkyWalking configuration samples
  samples/addons/extras/skywalking.yaml
Labels: kind/docs, ok-to-test, size/L, release-notes-none

#40288 [release-1.15] Change update_deps.sh with release-1.15
  bin/update_deps.sh
Labels: size/XS, release-notes-none

#40089 do not repeat trust id in logs
  pkg/spiffe/spiffe.go
Labels: size/XS, release-notes-none

#40300 remove restart epoch from envoy
  pkg/bootstrap/instance.go
  pkg/bootstrap/instance_test.go
  pkg/envoy/agent.go
  pkg/envoy/agent_test.go
  pkg/envoy/instance.go
  pkg/envoy/instance_test.go
  pkg/envoy/options.go
  pkg/envoy/options_test.go
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
  pkg/istio-agent/agent.go
Labels: area/networking, size/L, release-notes-none

#40280 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40302 Automator: update proxy@release-1.14 in istio/istio@release-1.14
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40283 [release-1.15] Documentation updates for comments in #40255
  cni/pkg/repair/repair_test.go
  operator/pkg/patch/patch.go
  pkg/dns/client/dns_test.go
  pkg/istio-agent/health/health_probers.go
  pkg/kube/inject/initializer.go
  pkg/test/framework/components/echo/echotest/filters.go
  pkg/test/framework/components/echo/echotest/run.go
  pkg/test/framework/components/echo/echotest/setup.go
  pkg/test/framework/components/istio/kube.go
  tools/bug-report/pkg/config/config.go
Labels: size/L, release-notes-none

#40151 start admin interface earlier
  pilot/pkg/bootstrap/server.go
  pilot/pkg/xds/debug.go
Labels: size/M, release-notes-none

#40289 Support debug building mode
  Makefile.core.mk
  tools/docker-builder/main.go
  tools/docker.yaml
Labels: size/XS, release-notes-none

#40305 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40306 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40310 Update BASE_VERSION to 1.14-2022-08-05T19-00-50
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#40309 Update BASE_VERSION to master-2022-08-05T19-00-57
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#40308 Update BASE_VERSION to master-2022-08-05T19-00-49
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#40209 security tests refactor
  pkg/test/framework/components/echo/common/deployment/echos.go
  pkg/test/framework/components/echo/common/deployment/namespace.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/eastwest.go
  pkg/test/framework/components/istio/kube.go
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/ecc_signature_algorithm/main_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
Labels: area/test and release, area/security, size/XL, release-notes-none

#40243 fix empty endpoints weight for AUTO_PASSTHROUGH gateway
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/ep_filters_test.go
Labels: area/networking, ok-to-test, size/XL, release-notes-none

#40312 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40319 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40294 Fix TestInsertDataToConfigMap flake
  security/pkg/k8s/configutil_test.go
Labels: size/S, release-notes-none

#40265 Fix bug for for Sidecar's defaultEndpoint is IPv6 format
  pilot/pkg/model/validation.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/L, release-notes-none

#40220 Fix 0103 warning for non-injected pods on the host network
  pkg/config/analysis/analyzers/injection/injection.go
  pkg/config/analysis/analyzers/testdata/injection.yaml
  releasenotes/notes/40220.yaml
Labels: area/user experience, size/S

#40314 [release-1.14] fix empty endpoints weight for AUTO_PASSTHROUGH gateway
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/ep_filters_test.go
Labels: area/networking, ok-to-test, size/XL, release-notes-none

#40328 improve sleep-spire.yaml
  samples/security/spire/sleep-spire.yaml
Labels: area/test and release, release-notes-none

#40330 Cherrypick 40220
  pkg/config/analysis/analyzers/injection/injection.go
  pkg/config/analysis/analyzers/testdata/injection.yaml
  releasenotes/notes/40220.yaml
Labels: size/M

#40334 1.15: cherrypick arm64 support
  Makefile.core.mk
  bin/init.sh
  pkg/test/echo/docker/Dockerfile.app_sidecar
  prow/integ-suite-kind.sh
  prow/lib.sh
  prow/release-commit.sh
  releasenotes/notes/arm64-support.yaml
  samples/jwt-server/jwt-server.yaml
  samples/jwt-server/src/Dockerfile
  samples/jwt-server/src/Makefile
  tools/docker-builder/builder/crane.go
  tools/docker-builder/common.go
  tools/docker-builder/crane.go
  tools/docker-builder/docker.go
  tools/docker-builder/main.go
  tools/docker-builder/types.go
  tools/docker-copy.sh
  tools/docker.yaml
  tools/packaging/packaging.mk
Labels: size/L

#40315 fuzzing: fix oss-fuzz build
  tests/fuzz/oss_fuzz_build.sh
Labels: size/XS, release-notes-none

#40275 fix gateway with different bind to have same host
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/40268.yaml
Labels: area/networking, ok-to-test, size/L

#40297 improve CheckAutoScaleAndReplicaCount
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
  releasenotes/notes/40297.yaml
Labels: size/S

#40304 Don't gen default webhooks if operatorManageWebhooks is true
  operator/cmd/mesh/install.go
Labels: size/S, release-notes-none

#40307 Respect ALPN negotiation in agent prober
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  pkg/test/echo/server/endpoint/http.go
  releasenotes/notes/http2-probes.yaml
Labels: size/L, cherrypick/release-1.15

#40320 unify timeout logic across service and virtual service
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/40299.yaml
Labels: area/networking, size/M

#40313 [release-1.15] fix empty endpoints weight for AUTO_PASSTHROUGH gateway
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/ep_filters_test.go
Labels: area/networking, ok-to-test, size/XL, release-notes-none

#40332 [release-1.15] Fix release-commit to use 1.15 instead of master
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#40337 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40335 [release-1.15] Fix 0103 warning for non-injected pods on the host network
  pkg/config/analysis/analyzers/injection/injection.go
  pkg/config/analysis/analyzers/testdata/injection.yaml
  releasenotes/notes/40220.yaml
Labels: size/S, release-notes-none

#40336 [release-1.15] Run update_deps.sh before build
  istio.deps
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#40331 [release-1.15] improve sleep-spire.yaml
  samples/security/spire/sleep-spire.yaml
Labels: size/XS, release-notes-none

#40341 [release-1.15] Don't gen default webhooks if operatorManageWebhooks is true
  operator/cmd/mesh/install.go
Labels: size/S, release-notes-none

#40338 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40340 [release-1.15] Respect ALPN negotiation in agent prober
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  pkg/test/echo/server/endpoint/http.go
  releasenotes/notes/http2-probes.yaml
Labels: size/L, release-notes-none

#40345 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40354 [release-1.15] improve CheckAutoScaleAndReplicaCount
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
  releasenotes/notes/40297.yaml
Labels: size/S, release-notes-none

#40301 Remove old Envoy runtime flag
  pkg/bootstrap/config.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
Labels: area/environments, ok-to-test, size/M, release-notes-none

#40361 chore: add missing templating list for datasource
  manifests/addons/dashboards/istio-extension-dashboard.json
  manifests/addons/dashboards/istio-performance-dashboard.json
  samples/addons/grafana.yaml
Labels: area/user experience, size/M, release-notes-none

#40353 [release-1.14] improve CheckAutoScaleAndReplicaCount
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
  releasenotes/notes/40297.yaml
Labels: size/S, release-notes-none

#40366 Automator: update istio/api@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40216 [release-1.13] pilot: fix issue with TLS and TCP order dependency
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/test/xdstest/validate.go
  releasenotes/notes/tls-tcp-conflict.yaml
Labels: size/M, release-notes-none

#40217 [release-1.14] pilot: fix issue with TLS and TCP order dependency
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/test/xdstest/validate.go
  releasenotes/notes/tls-tcp-conflict.yaml
Labels: size/M, release-notes-none

#40367 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40371 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40136 Set ISTIO_META_GENERATOR only fro grpc
  pkg/istio-agent/agent.go
  pkg/istio-agent/testdata/grpc-bootstrap.json
Labels: size/XS, release-notes-none

#40327 add identifier to crd client logs
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/config/analysis/incluster/controller.go
  pkg/config/analysis/local/istiod_analyze.go
Labels: area/networking, size/M, release-notes-none

#40374 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40296 Propagate SkyWalking tracing header in sample application
  samples/bookinfo/src/details/details.rb
  samples/bookinfo/src/productpage/productpage.py
  samples/bookinfo/src/productpage/tests/unit/test_productpage.py
  samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
Labels: ok-to-test, size/S, release-notes-none

#40388 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40387 fix the bug when istio ingressgateway cannot be matched to a node
  manifests/charts/gateways/istio-egress/templates/_affinity.tpl
  manifests/charts/gateways/istio-ingress/templates/_affinity.tpl
  releasenotes/notes/bug-fix-for-arch-helm-templates.yaml
Labels: area/environments, size/S, cherrypick/release-1.14, cherrypick/release-1.15

#40390 [release-1.14] fix the bug when istio ingressgateway cannot be matched to a node
  manifests/charts/gateways/istio-egress/templates/_affinity.tpl
  manifests/charts/gateways/istio-ingress/templates/_affinity.tpl
  releasenotes/notes/bug-fix-for-arch-helm-templates.yaml
Labels: size/S, release-notes-none

#40389 Automator: update proxy@release-1.14 in istio/istio@release-1.14
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40393 debug interface: fix crash regression
  pilot/pkg/bootstrap/server.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/debuggen.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/simple.go
Labels: size/M, release-notes-none

#40391 [release-1.15] fix the bug when istio ingressgateway cannot be matched to a node
  manifests/charts/gateways/istio-egress/templates/_affinity.tpl
  manifests/charts/gateways/istio-ingress/templates/_affinity.tpl
  releasenotes/notes/bug-fix-for-arch-helm-templates.yaml
Labels: size/S, release-notes-none

#40186 Rework proxy labels update
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/fake.go
  pkg/bootstrap/config.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/instance.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/match/matchers_test.go
  pkg/test/framework/components/echo/staticvm/instance.go
  tests/integration/security/authz_test.go
Labels: area/networking, size/L, release-notes-none

#40404 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40399 [release-1.14] unify timeout logic across service and virtual service
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/40299.yaml
Labels: size/M

#40400 [release-1.13] unify timeout logic across service and virtual service
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/40299.yaml
Labels: size/M

#39521 fix multi accesslogging not working
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  releasenotes/notes/39521.yaml
Labels: area/extensions and telemetry, size/XXL

#40221 Add failover priorities to eds cache key
  pilot/pkg/networking/util/util.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/endpoint_builder_test.go
  releasenotes/notes/40198.yaml
Labels: area/networking, size/L

#40402 [release-1.15] unify timeout logic across service and virtual service
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/40299.yaml
Labels: size/M, release-notes-none

#40414 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40415 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#40411 telemetry logging: insert newlines in format, per spec
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
Labels: size/XS, release-notes-none, cherrypick/release-1.15

#40362 Promoted istioctl x uninstall to istioctl uninstall
  istioctl/cmd/root.go
  operator/cmd/mesh/uninstall.go
  releasenotes/notes/40339.yaml
  tests/integration/operator/switch_cr_test.go
  tests/integration/pilot/revisions/uninstall_test.go
Labels: size/M

#40417 [release-1.15] fix multi accesslogging not working
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  releasenotes/notes/39521.yaml
Labels: size/XXL, release-notes-none

#40420 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40418 [release-1.15] Rework proxy labels update
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/fake.go
  pkg/bootstrap/config.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/instance.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/match/matchers_test.go
  pkg/test/framework/components/echo/staticvm/instance.go
  tests/integration/security/authz_test.go
Labels: size/L, release-notes-none

#40428 Automator: update proxy@release-1.14 in istio/istio@release-1.14
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40274 tf: Fix Istioctl XDS flakes
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/piggyback_test.go
Labels: size/M, release-notes-none

#40432 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#40410 Merge changes from istio template (#38837)
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
  pkg/kube/inject/testdata/inject/grpc-agent.yaml.injected
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: ok-to-test, area/user experience, size/L, release-notes-none

#40433 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#40434 Automator: update istio/client-go@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40435 added few more test scenarios in authz builder
  pilot/pkg/security/authz/builder/testdata/tcp/allow-both-http-tcp-in.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/allow-both-http-tcp-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/deny-both-http-tcp-in.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/deny-both-http-tcp-out.yaml
Labels: area/security, size/M, release-notes-none

#40438 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40406 Add benchmarks for queue
  pkg/queue/instance_test.go
Labels: size/S, release-notes-none

#40440 Automator: update proxy@release-1.14 in istio/istio@release-1.14
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40439 [release-1.15] telemetry logging: insert newlines in format, per spec
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
Labels: size/XS, release-notes-none

#40442 telemetry logging: refactor fileAccessLogFormat
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: size/L, release-notes-none

#40447 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#40448 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#40322 Refactor proxy labels: add labels fields to Proxy
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/autoregistration/controller_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/peer_authentication_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/security/authz/builder/fuzz_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/mesh_network_test.go
  pkg/bootstrap/config.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
  pkg/istio-agent/xds_proxy_test.go
Labels: size/L, release-notes-none

#40449 move maxstream duration creation inside condition
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: size/S, release-notes-none
