Repository istio/istio, pull requests merged in 2022-07, with the labels that each got.

#39647 [tf] Storing deployment templates in files
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/flags.go
  pkg/test/framework/components/echo/kube/templates/deployment.yaml
  pkg/test/framework/components/echo/kube/templates/service.yaml
  pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
  pkg/test/framework/components/environment/kube/flags.go
  pkg/test/util/tmpl/parse.go
Labels: area/test and release, ok-to-test, size/XL, release-notes-none

#39709 minor renaming of methods to avoid confusion in cluster patcher
  pilot/pkg/networking/core/v1alpha3/cluster.go
Labels: area/networking, size/S, release-notes-none

#39733 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39704 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#39721 Revert changes to always notify XdsUpdater in mem discovery
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
Labels: size/L, release-notes-none

#39725 added imagePullSecret in extauthz and jwt server deployment
  pkg/test/framework/components/authz/kube.go
  pkg/test/framework/components/jwt/kube.go
  pkg/test/util/yml/apply.go
  samples/jwt-server/jwt-server.yaml
Labels: area/security, size/M, release-notes-none

#39737 tf: enable core dumps even if the pod has restarted
  pkg/test/kube/dump.go
Labels: size/XS, release-notes-none

#39717 Minor fixes on echo app
  pkg/test/echo/server/forwarder/util.go
  pkg/test/echo/server/instance.go
Labels: size/S, release-notes-none

#39723 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#39715 Allow running TestSDS concurrently
  security/pkg/nodeagent/sds/sdsservice_test.go
Labels: size/XS, release-notes-none

#39735 echo: avoid filling defaults twice
  pkg/test/echo/server/forwarder/util.go
Labels: size/XS, release-notes-none

#39742 tf: prevent blocking eastwest gateway with test policies
  tests/integration/security/testdata/beta-mtls-on.yaml
  tests/integration/security/testdata/beta-mtls-permissive.yaml
  tests/integration/security/testdata/no-peer-authn.yaml
Labels: size/M, release-notes-none

#39746 xds: respond to requests previously miscategorized as ACKs
  pilot/pkg/features/pilot.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/discovery_test.go
  releasenotes/notes/double-ack.yaml
  tests/integration/base.yaml
Labels: size/M

#39744 mod: bump quic-go dependency
  go.mod
  go.sum
Labels: size/S, release-notes-none

#39749 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39750 updated the pullsecret logic
  pkg/test/framework/components/authz/kube.go
Labels: area/security, size/XS, release-notes-none

#39748 Improve tests and logs around meshconfig update
  pkg/config/mesh/kubemesh/watcher_test.go
  pkg/test/framework/components/istio/configmap.go
Labels: size/M, release-notes-none

#39606 use mesh config defaults when log formatter is not specified
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Labels: area/networking, size/M, release-notes-none

#39722 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#39688 do not cache dependent configs in xds cache store
  pilot/pkg/model/xds_cache.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/xds_cache_test.go
Labels: size/L, release-notes-none

#39755 add metrics for dependent config size
  pilot/pkg/model/xds_cache.go
Labels: area/networking, size/S, release-notes-none

#39753 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/M, auto-merge, release-notes-none

#39756 upgrade go control plane
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, release-notes-none

#39764 Not really evict a key that is added later after LRU evict bt before the evict handler run by istio
  pilot/pkg/model/xds_cache.go
  pilot/pkg/xds/xds_cache_test.go
Labels: release-notes-none

#39665 use config hash for dependent configs
  pilot/pkg/model/config.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/xds_cache.go
  pilot/pkg/networking/core/v1alpha3/cluster_cache.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache_test.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/proxy_dependencies_test.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/xds_cache_test.go
Labels: area/networking, size/L, release-notes-none

#39783 [Dual Stack] Fix the bug for installing Istio in IPv4 only k8s cluster with dual stack feature is enabled
  pkg/bootstrap/config.go
Labels: size/XS

#39782 Revert "do not cache dependent configs in xds cache store (#39688)"
  pilot/pkg/model/xds_cache.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/xds_cache_test.go
Labels: area/networking, size/L, release-notes-none

#39781 clean telemetryv2 files
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.11.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.12.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.11.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.12.yaml
Labels: area/environments, area/perf and scalability, size/XXL, release-notes-none

#39784 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#39785 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#39796 Update BASE_VERSION to 1.13-2022-07-05T19-02-50
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#39757 minor refactor in cluster builder
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: area/networking, size/M, release-notes-none

#39803 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
Labels: size/XS, auto-merge, release-notes-none

#39805 Automator: update istio/api@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#39806 Automator: update istio/client-go@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#39818 Update BASE_VERSION to master-2022-07-06T19-01-15
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#39769 minor comment changes in xds
  pilot/pkg/xds/ads.go
Labels: area/networking, size/S, release-notes-none

#39765 implement max connection duration
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/39765.yaml
Labels: size/M

#39821 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39730 Add split DRs to rds/cds/eds dependent configs
  pilot/pkg/model/config.go
  pilot/pkg/model/destination_rule.go
  pilot/pkg/model/destination_rule_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_cache.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/grpcgen/cds.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/xds_cache_test.go
  releasenotes/notes/39726.yaml
Labels: area/networking, size/L

#39824 Agent: Unified use of NewSecretManager func
  pkg/istio-agent/agent.go
Labels: area/environments, area/perf and scalability, size/XS, release-notes-none

#39760 Fix a multierr usage
  istioctl/pkg/tag/util.go
Labels: area/environments, size/XS, release-notes-none

#39523 Fix injection check in x injector list
  istioctl/cmd/injector-list.go
Labels: area/user experience, size/XS, release-notes-none

#39569 Filter system namespaces for injector list
  istioctl/cmd/injector-list.go
Labels: size/S, release-notes-none

#39817 cherrypicked from master tls secrets format
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/istio_ca_test.go
  releasenotes/notes/k8s-tls-secret-cacerts.yaml
  security/pkg/nodeagent/caclient/providers/mock/mockcaclient.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
  tests/fuzz/pki_fuzzer.go
Labels: area/networking, size/L

#39338 [tf] flag to only deploy specific apps istio.test.onlyWorkloads
  pkg/test/framework/components/echo/deployment/builder.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  prow/integ-suite-kind.sh
Labels: size/M, release-notes-none

#39801 Fix bug(#38077) that causes a stale SA token is being used in istio-cni
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  cni/pkg/install/testdata/token-bar
  cni/pkg/install/testdata/token-foo
  releasenotes/notes/38077.yaml
Labels: area/networking, ok-to-test, size/L

#39832 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39553 Add description to admin log, and reformat the display
  istioctl/cmd/istiodconfig.go
  istioctl/cmd/istiodconfig_test.go
  releasenotes/notes/desc-to-admin-log-scope.yaml
Labels: area/user experience, size/M

#39823 Respect GA topology label first
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/util.go
  pilot/pkg/serviceregistry/kube/controller/util_test.go
Labels: size/S, release-notes-none

#39729 Fix analyze conflicting mesh gateway with exportTo
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/testdata/virtualservice_conflictingmeshgatewayhosts.yaml
  pkg/config/analysis/analyzers/testdata/virtualservice_conflictingmeshgatewayhosts_with_exportto.yaml
  pkg/config/analysis/analyzers/util/exportto.go
  pkg/config/analysis/analyzers/util/exportto_test.go
  pkg/config/analysis/analyzers/virtualservice/conflictingmeshgatewayhosts.go
  releasenotes/notes/39729.yaml
Labels: size/L, cherrypick/release-1.14

#39831 Manual update of istio/api including update for StatPrefix
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
Labels: size/M, release-notes-none

#39840 [tf] load templates outside of init func
  pkg/test/framework/components/echo/kube/deployment.go
Labels: area/test and release, ok-to-test, size/M, release-notes-none

#39804 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#39846 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39850 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39645 hbone: initial echo server/client implementation
  pkg/config/protocol/instance.go
  pkg/config/protocol/instance_test.go
  pkg/hbone/README.md
  pkg/hbone/dialer.go
  pkg/hbone/dialer_test.go
  pkg/hbone/server.go
  pkg/hbone/util.go
  pkg/test/echo/cmd/client/main.go
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/proto/echo.pb.go
  pkg/test/echo/proto/echo.proto
  pkg/test/echo/server/endpoint/hbone.go
  pkg/test/echo/server/endpoint/http.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/endpoint/tcp.go
  pkg/test/echo/server/forwarder/config.go
  pkg/test/echo/server/forwarder/grpc.go
  pkg/test/echo/server/forwarder/http.go
  pkg/test/echo/server/forwarder/tcp.go
  pkg/test/echo/server/forwarder/tls.go
  pkg/test/echo/server/forwarder/util.go
  pkg/test/echo/server/forwarder/websocket.go
  pkg/test/echo/server/instance.go
Labels: size/XL, release-notes-none

#39674 Fix: allow enableNamespacesByDefault when revision tag is set
  operator/cmd/mesh/install.go
  releasenotes/notes/39674.yaml
Labels: size/M

#39768 fix: update the typo for pkg spiffe
  pkg/spiffe/spiffe.go
Labels: size/S, release-notes-none

#39853 add type to xds cache evictions stat
  pilot/pkg/model/xds_cache.go
Labels: size/M, release-notes-none

#39859 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#39862 gateway-api: bump dependency to fix flakes
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#39648 Refactoring Security Tests
  pkg/test/framework/components/echo/common/deployment/echos.go
  pkg/test/framework/components/echo/common/deployment/namespace.go
  pkg/test/framework/components/echo/config.go
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/ca_custom_root/multi_root_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/external_ca/reachability_test.go
  tests/integration/security/https_jwt/main_test.go
  tests/integration/security/util/cert/cert.go
Labels: area/security, size/XL, release-notes-none

#39861 Fix KubernetesResources builder for fuzzer
  tests/fuzz/kube_gateway_controller_fuzzer.go
Labels: size/XS, release-notes-none

#39847 Add testcases for mockclient_PodsForSelector
  pkg/kube/client_test.go
  pkg/kube/mock_client_test.go
Labels: area/test and release, ok-to-test, size/L, release-notes-none

#39767 fix: update the typo code comment for pkg istioctl/cmd
  istioctl/cmd/analyze.go
  istioctl/cmd/root.go
  istioctl/cmd/workload.go
Labels: size/S, release-notes-none

#39849 fix istioctl pc eds
  istioctl/pkg/writer/envoy/configdump/endpoint.go
  istioctl/pkg/writer/envoy/configdump/endpoint_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/configdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/emptyfilter_output.json
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/emptyfilter_output.txt
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/emptyfilter_output.yaml
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/portfilter_output.json
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/portfilter_output.txt
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/portfilter_output.yaml
Labels: area/user experience, size/XXL, release-notes-none

#39854 possible dependent config leak
  pilot/pkg/model/xds_cache.go
Labels: area/networking, size/XS, release-notes-none

#39834 disable sending unhealthy endpoints by default
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/xds/eds_test.go
  releasenotes/notes/39825.yaml
Labels: area/networking, size/M, cherrypick/release-1.14

#39867 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39525 Fix x injector ns pod info not accurate when use default
  istioctl/cmd/injector-list.go
  istioctl/cmd/injector-list_test.go
  releasenotes/notes/39525.yaml
Labels: area/user experience, size/M

#39872 [release-1.14] disable sending unhealthy endpoints by default #39871
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/xds/eds_test.go
  releasenotes/notes/39825.yaml
Labels: area/networking, size/M

#39495 Add protocol check for empty address in Service Entry
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/27990.yaml
Labels: ok-to-test, size/M

#39860 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#39883 Fix operator test on 1.25
  tests/integration/operator/switch_cr_test.go
Labels: size/S, release-notes-none

#39865 Create topology flag to proxy only kubectl traffic through HTTPProxy
  pkg/test/framework/components/cluster/cluster.go
  pkg/test/framework/components/cluster/config.go
  pkg/test/framework/components/cluster/topology.go
  pkg/test/framework/components/istio/ingress.go
Labels: area/test and release, size/M, release-notes-none

#39881 validation: do not warn about ECDS types
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/S, release-notes-none

#39357 [release-1.13] pilot: fix a bug when merge >2 Services together
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  releasenotes/notes/multi-service-merge.yaml
Labels: size/M, release-notes-none

#39889 xds: improve incremental logging
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/xdsgen.go
Labels: size/XS, release-notes-none

#39878 tf: fast mesh config update for Istiodless
  pkg/test/framework/components/istio/configmap.go
Labels: size/M, release-notes-none, cherrypick/release-1.14

#39891 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#39866 fix: update the typo code comment
  cni/pkg/taint/taint.go
  istioctl/pkg/authz/analyzer.go
  istioctl/pkg/clioptions/doc.go
  istioctl/pkg/tag/generate.go
  istioctl/pkg/util/handlers/handlers.go
  operator/pkg/helm/renderer.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pkg/config/protocol/instance.go
  pkg/test/framework/components/cluster/topology.go
  pkg/test/framework/components/echo/echotest/setup.go
  security/pkg/server/ca/server_test.go
  tools/bug-report/pkg/config/config.go
Labels: size/M, release-notes-none

#39894 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#39877 initialize commonLbConfig in default cluster
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
Labels: area/networking, size/S, release-notes-none

#39774 Enable TestTunnelingOutboundTraffic and configure access log in forward proxy
  pkg/test/echo/server/endpoint/http.go
  tests/integration/pilot/forwardproxy/envoy_config_generator.go
  tests/integration/pilot/tunneling_test.go
Labels: area/test and release, area/networking, size/M, release-notes-none

#39893 Fix bug blocking JSON marshal of endpointShardz
  pilot/pkg/model/endpointshards.go
Labels: size/XS, release-notes-none

#39875 fix bug for the istio-agent wait command to make sure that it is really timeout
  pilot/cmd/pilot-agent/app/wait.go
Labels: size/S, release-notes-none

#39899 improve telemetry bench test
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/testdata/benchmarks/telemetry-api.yaml
Labels: area/networking, area/perf and scalability, size/S, release-notes-none

#39913 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#39776 Virtual service direct response
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/config/validation/virtualservice.go
Labels: area/networking, ok-to-test, size/L, release-notes-none

#39892 xds: improve req log consistency
  pilot/pkg/xds/ads.go
Labels: size/XS, release-notes-none

#39909 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#39918 Prevent illegal logs in goroutines in hbone test
  pkg/hbone/dialer_test.go
Labels: size/XS, release-notes-none

#39890 tf: add explicit loggs when stuck in warming state
  pkg/test/kube/dump.go
Labels: size/S, release-notes-none

#39902 Fix typo of InsertDataToConfigMap func description
  security/pkg/k8s/configutil.go
Labels: ok-to-test, size/XS, release-notes-none

#39907 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#39920 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39923 tf: drop unused feature in external_ca
  tests/integration/security/external_ca/main_test.go
Labels: size/XS, release-notes-none

#39924 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39904 remove relative operation error for envoy filter MERGE operation
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go
  pkg/config/analysis/analyzers/testdata/envoy-filter-merge-operation.yaml
Labels: size/L, release-notes-none

#39900 remove year from copyright
  pkg/queue/delay.go
  pkg/queue/delay_test.go
  pkg/queue/util.go
  security/pkg/server/ca/authenticate/cert_authenticator.go
  security/pkg/server/ca/server_test.go
Labels: release-notes-none

#39928 Revert "[Dual Stack] Add dual stack README"
  DualStackREADME.md
Labels: size/M

#39929 [Dual Stack] Add dual stack README
  DUAL_STACK.md
Labels: size/M

#39916 xds: fix issue when skipping first request
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/xdsgen.go
Labels: size/M, release-notes-none

#39405 add xfcc authenticator
  go.mod
  go.sum
  licenses/github.com/alecholmes/xfccparser/LICENSE
  licenses/github.com/alecthomas/participle/COPYING
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pilot/pkg/xds/auth.go
  pkg/security/security.go
  security/pkg/nodeagent/caclient/providers/citadel/client_test.go
  security/pkg/nodeagent/test/mock/caserver.go
  security/pkg/server/ca/authenticate/cert_authenticator.go
  security/pkg/server/ca/authenticate/xfcc_authenticator.go
  security/pkg/server/ca/authenticate/xfcc_authenticator_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: area/networking, area/security, size/L, release-notes-none

#39915 tf: improve dumping
  pkg/kube/client.go
  pkg/kube/mock_client.go
  pkg/kube/portforwarder.go
  pkg/test/framework/components/cluster/kube/factory.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/components/namespace/namespace.go
  pkg/test/framework/resource/context.go
  pkg/test/framework/scope.go
  pkg/test/framework/suitecontext.go
  pkg/test/framework/testcontext.go
  pkg/test/kube/dump.go
Labels: size/L, release-notes-none

#39936 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39937 xds: always respond to EDS request after CDS requests
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/discovery_test.go
Labels: size/M, release-notes-none

#39857 dns: added DNSForwardParallel to support sending parallel queries to all name servers
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
  pkg/istio-agent/agent.go
  releasenotes/notes/agent-dns-forward-parallel.yaml
Labels: area/networking, ok-to-test, size/L

#39699 Make istio-cni compatible with Talos Linux (go netns implementation + added ca cert path)
  cni/cmd/istio-cni/main.go
  cni/pkg/config/config.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/redirect.go
  pkg/security/security.go
  releasenotes/notes/39699.yaml
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
Labels: area/networking, ok-to-test, size/L, release-notes-none

#39948 tf: loosen restrictions on 'real stackdriver' testing
  pkg/test/framework/components/stackdriver/stackdriver.go
Labels: area/test and release, size/XS, release-notes-none

#39751 add cache for accesslog
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  pilot/pkg/util/protoconv/protoconv.go
Labels: size/XXL, release-notes-none

#39941 Convert mockprom to metrics endpoint test to a subtest
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: ok-to-test, size/M, release-notes-none

#39949 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39954 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39959 Fix resiliience port-forward
  pkg/kube/portforwarder.go
Labels: size/XS, release-notes-none

#39967 [release-1.14] Updated kind image needed for kind update (part of #38885)
  prow/integ-suite-kind.sh
Labels: size/XS, release-notes-none

#39968 Bump distroless base
  docker/Dockerfile.distroless
Labels: size/XS, release-notes-none, cherrypick/release-1.14

#39965 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#39975 Run update_deps on the Istio 1.14 branch
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: area/test and release, size/S, release-notes-none

#39980 Automator: update common-files@release-1.13 in istio/istio@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#39981 Automator: update istio/client-go@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#39690 Refact authenticator
  pilot/pkg/xds/debug.go
  pkg/security/mock.go
  pkg/security/security.go
  security/pkg/server/ca/authenticate/cert_authenticator.go
  security/pkg/server/ca/authenticate/cert_authenticator_test.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
  security/pkg/server/ca/authenticate/oidc.go
  security/pkg/server/ca/authenticate/oidc_test.go
  security/pkg/server/ca/authenticate/xfcc_authenticator.go
  security/pkg/server/ca/authenticate/xfcc_authenticator_test.go
  security/pkg/server/ca/server_test.go
Labels: size/L, release-notes-none

#39971 Mitigate TestDNS flakes
  pkg/dns/client/dns_test.go
  pkg/dns/client/proxy.go
Labels: size/M, release-notes-none

#39996 [release-1.13] Update branch for update_deps
  bin/update_deps.sh
Labels: size/XS, release-notes-none

#39978 Run update_deps on the release-1.13 branch
  docker/Dockerfile.distroless
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: area/test and release, size/S, release-notes-none

#39956 Skip forward when the proxy connection is closed
  pkg/istio-agent/xds_proxy.go
Labels: size/S, release-notes-none

#39960 handle non wildcard resources during reconnect
  pilot/pkg/features/pilot.go
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/discovery_test.go
Labels: area/networking, size/L, release-notes-none

#39922 Add test for unfixed SNI overlapping bug
  pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
Labels: size/M, release-notes-none

#39964 lint: fix usages of legacy proto package
  istioctl/pkg/util/configdump/wrapper.go
  operator/pkg/util/yaml.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/proxy_config_test.go
  pkg/istio-agent/agent.go
  pkg/util/protomarshal/protomarshal.go
  tests/fuzz/crd_roundtrip_fuzzer.go
Labels: size/S, release-notes-none

#39888 tf: export external service to same namespace only
  pkg/test/framework/components/echo/common/deployment/namespace.go
  tests/integration/telemetry/stats/prometheus/stats.go
Labels: size/S, release-notes-none

#40002 Various test framework improvements
  pkg/test/framework/components/authz/kube.go
  pkg/test/framework/components/istio/cleanup.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/scope.go
  pkg/test/kube/dump.go
  pkg/test/util/retry/retry.go
  pkg/test/util/retry/retry_test.go
  tests/integration/operator/operator_dumper.go
Labels: size/L, release-notes-none

#39972 test reachability: make protocol on outer loop
  tests/integration/security/reachability_test.go
Labels: size/L, release-notes-none

#40004 Automator: update proxy@release-1.12 in istio/istio@release-1.12
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40003 Add AlwaysRespond logic to Delta XDS as well
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/delta.go
Labels: size/M, release-notes-none

#40013 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40000 Bump api
  go.mod
  go.sum
  pkg/config/analysis/analyzers/testdata/misannotated.yaml
Labels: size/S, release-notes-none

#40020 added imagePullSecret in custom jwt-server
  pkg/test/framework/components/jwt/kube.go
Labels: area/security, size/XS, release-notes-none

#39976 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#40021 Change the warning message to debug message
  operator/pkg/helmreconciler/prune.go
Labels: area/environments, size/XS, release-notes-none, cherrypick/release-1.13, cherrypick/release-1.14

#40026 [release-1.14] Change the warning message to debug message
  operator/pkg/helmreconciler/prune.go
Labels: size/XS, release-notes-none

#40016 tf: wait for CRDs to be established before Gateway tests
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/ingress_test.go
Labels: size/M, release-notes-none

#40024 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#39457 [e2e test]add telemetry e2e test with default provider
  tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go
Labels: area/extensions and telemetry, size/M, release-notes-none

#40009 remove max concurrent streams default
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: area/networking, size/XS, release-notes-none

#40014 Check AllowAny mode in RDS cache key
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache.go
  releasenotes/notes/rds-cache-allow-any.yaml
Labels: size/S

#39833 clean proxy_init.resources
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
Labels: area/environments, size/M, release-notes-none

#39988 improve cni logging
  cni/pkg/cmd/root.go
  cni/pkg/log/uds.go
  cni/pkg/log/uds_test.go
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
Labels: area/environments, size/M, release-notes-none

#40033 Change the warning message to debug message
  operator/pkg/helmreconciler/prune.go
Labels: size/XS, release-notes-none

#40039 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
