Repository istio/istio, pull requests merged in 2022-02, with the labels that each got.

#37090 Workaround Centos 8 death
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Labels: release-notes-none

#37093 Fix the Centos 8 workaround to not mess with Centos 7
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Labels: size/XS, release-notes-none

#37097 add 1.13 survey
  manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
  operator/cmd/mesh/install.go
Labels: size/XS, release-notes-none

#37098 Update BASE_VERSION to 1.11-dev.11
  Makefile.core.mk
Labels: size/XS, release-notes-none

#37052 Fix and skip istiodless istioctl tests
  tests/integration/pilot/istioctl_test.go
Labels: size/S, release-notes-none, cherrypick/release-1.13

#37105 [release-1.13] add proxyconfig control of service-cluster naming scheme (#36809)
  go.mod
  go.sum
  istioctl/cmd/add-to-mesh.go
  istioctl/cmd/workload.go
  operator/pkg/util/merge_iop.go
  pilot/cmd/pilot-agent/config/config.go
  pkg/bootstrap/config.go
  pkg/bootstrap/config_test.go
  pkg/config/mesh/mesh.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/envoy/proxy_test.go
  pkg/kube/inject/template.go
  pkg/kube/inject/webhook.go
  pkg/kube/labels/labels.go
  releasenotes/notes/36809.yaml
Labels: size/L

#37099 Run bin/update_deps.sh
  docker/Dockerfile.distroless
  prow/release-commit.sh
Labels: area/test and release, size/XS, release-notes-none

#37101 [release-1.13] run UPDATE_BRANCH=release-1.13 ./bin/update_deps.sh
  docker/Dockerfile.distroless
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#37102 fix flake: queue.TestClosed
  pkg/queue/instance_test.go
Labels: size/S, release-notes-none, cherrypick/release-1.13

#37106 Fix installation on OpenShift
  manifests/profiles/openshift.yaml
Labels: size/XS, release-notes-none

#37103 [release-1.13] add open-telemetry sample
  samples/open-telemetry/README.md
  samples/open-telemetry/otel.yaml
Labels: size/L, release-notes-none

#37111 Break instead of return on empty resources at xds proxy.
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
Labels: size/XS, release-notes-none, cherrypick/release-1.11, cherrypick/release-1.12, cherrypick/release-1.13

#37108 [release-1.13] fix flake: queue.TestClosed
  pkg/queue/instance_test.go
Labels: size/S, release-notes-none

#37115 [release-1.13] Break instead of return on empty resources at xds proxy.
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
Labels: size/XS, release-notes-none

#37094 Change default `PILOT_MAX_REQUESTS_PER_SECOND` to 25
  pilot/pkg/features/pilot.go
  releasenotes/notes/max-rps-xds.yaml
Labels: size/S

#37109 Remove minikube flag from testing infrastructure
  pkg/test/framework/components/environment/kube/flags.go
  pkg/test/framework/components/environment/kube/settings.go
  tests/integration/tests.mk
Labels: size/S, release-notes-none

#37080 remove feature flag for virtual service delegates
  pilot/pkg/features/pilot.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/virtualservice.go
  pkg/config/validation/validation.go
  pkg/config/validation/virtualservice.go
Labels: area/networking, size/M, release-notes-none

#37104 [release-1.13] Fix and skip istiodless istioctl tests
  tests/integration/pilot/istioctl_test.go
Labels: size/S, release-notes-none

#37113 [release-1.11] Break instead of return on empty resources at xds proxy.
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
Labels: size/XS, release-notes-none

#37100 [release-1.12] run UPDATE_BRANCH=release-1.12 ./bin/update_deps.sh
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: size/S, release-notes-none

#37045 istioctl: fix order dependant tests
  cni/pkg/plugin/plugin_test.go
  istioctl/cmd/tag_test.go
  istioctl/cmd/workload.go
  pkg/kube/client.go
Labels: size/S, release-notes-none, cherrypick/release-1.13

#37114 [release-1.12] Break instead of return on empty resources at xds proxy.
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
Labels: size/XS, release-notes-none

#37127 TestGatewayHostnames: use non-priv port
  pilot/pkg/model/network_test.go
Labels: size/XS, release-notes-none

#37121 add release note for PR 36806
  releasenotes/notes/36806.yaml
Labels: ok-to-test, size/XS, cherrypick/release-1.12, cherrypick/release-1.13

#36851 [release-1.12] Ignoring duplicated cipher suites
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/M, release-notes-none

#37135 [release-1.12] validation: do not exit early on gateway TLS warnings
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/S, release-notes-none

#37131 [release-1.12] add release note for PR 36806
  releasenotes/notes/36806.yaml
Labels: size/XS, release-notes-none

#37112 Fix test ordering for tls origination
  pkg/test/framework/analyzer.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
  pkg/test/framework/test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/sds_tls_origination/util/util.go
  tests/integration/security/util/framework.go
Labels: size/XXL, release-notes-none

#37019 refactor: merge JWTPath and credential fetcher
  pilot/cmd/pilot-agent/options/options.go
  pilot/cmd/pilot-agent/options/security.go
  pkg/istio-agent/agent_test.go
  pkg/security/security.go
  security/pkg/credentialfetcher/fetcher.go
  security/pkg/credentialfetcher/plugin/gce.go
  security/pkg/credentialfetcher/plugin/mock.go
  security/pkg/credentialfetcher/plugin/token.go
  security/pkg/nodeagent/caclient/credentials.go
  security/pkg/nodeagent/caclient/credentials_test.go
  security/pkg/nodeagent/caclient/providers/citadel/client_test.go
  security/pkg/nodeagent/test/setup.go
Labels: size/L, release-notes-none

#37058 Added setupkind.sh script
  samples/kind-lb/README.md
  samples/kind-lb/setupkind.sh
Labels: kind/docs, size/L, release-notes-none

#37142 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37143 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37145 Various fixes/cleanup to the loadbalancer simulation
  pkg/test/loadbalancersim/lb_test.go
  pkg/test/loadbalancersim/loadbalancer/roundrobin.go
  pkg/test/loadbalancersim/loadbalancer/weight.go
  pkg/test/loadbalancersim/mesh/client.go
  pkg/test/loadbalancersim/mesh/node.go
  pkg/test/loadbalancersim/network/connection.go
  pkg/test/loadbalancersim/network/helper.go
  pkg/test/loadbalancersim/timeseries/data.go
  pkg/test/loadbalancersim/timeseries/instance.go
Labels: area/test and release, size/L, release-notes-none

#37147 fix request without query access log formatter
  pilot/pkg/networking/core/v1alpha3/accesslog.go
Labels: area/networking, size/XS, release-notes-none

#37144 [release-1.13] TestGatewayHostnames: use non-priv port
  pilot/pkg/model/network_test.go
Labels: size/XS, release-notes-none

#37141 [release-1.13] Added setupkind.sh script
  samples/kind-lb/README.md
  samples/kind-lb/setupkind.sh
Labels: size/L, release-notes-none

#37153 Output message with explanation when using --save
  tools/docker-builder/main.go
Labels: area/test and release, size/M, release-notes-none

#37154 [release-1.13] fix request without query access log formatter
  pilot/pkg/networking/core/v1alpha3/accesslog.go
Labels: size/XS, release-notes-none

#37116 Various test framework improvements
  istioctl/cmd/wait.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/kube/sidecar.go
  pkg/test/framework/components/echo/kube/workload.go
  pkg/test/framework/components/istioctl/kube.go
  pkg/test/framework/testcontext.go
  tests/integration/pilot/istioctl_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/util/framework.go
Labels: size/L, release-notes-none

#37132 [release-1.13] add release note for PR 36806
  releasenotes/notes/36806.yaml
Labels: size/XS, release-notes-none

#37149 Bump go modules
  go.mod
  go.sum
  istioctl/cmd/metrics_test.go
  licenses/github.com/BurntSushi/toml/internal/toml-test/COPYING
Labels: size/L, release-notes-none

#37157 Make grpc tests runnable in parallel and improve logging
  pilot/pkg/networking/apigen/apigen_test.go
  pilot/pkg/networking/grpcgen/grpcecho_test.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/xds/simple.go
Labels: size/L, release-notes-none

#37162 Minor clean up to use sets pkg.
  pilot/pkg/networking/core/v1alpha3/envoyfilter/extension_configuration_patch.go
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
Labels: size/S, release-notes-none

#37171 Add more robust calls to ecc_signature test
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
Labels: size/S, release-notes-none

#37170 Turn off autoscaling on externalistiod
  tests/integration/iop-externalistiod-primary-integration-test-defaults.yaml
Labels: size/XS, release-notes-none

#37177 Fix go test tools
  tools/go-ordered-test
  tools/go-stress-test
Labels: size/XS, release-notes-none

#37178 Fix race conditions with bootstrap unit test
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
Labels: size/M, release-notes-none

#37182 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#36948 fix istioctl x metrics
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
Labels: area/extensions and telemetry, area/user experience, size/M, release-notes-none, cherrypick/release-1.13

#37179 Update release-builder dep + others (-proxy)
  go.mod
  go.sum
  prow/release-commit.sh
Labels: area/test and release, size/S, release-notes-none

#36959 respect prometheus annotations
  pkg/kube/inject/inject.go
  pkg/kube/inject/testdata/inject/prometheus-scrape.yaml
  pkg/kube/inject/testdata/inject/prometheus-scrape.yaml.injected
  pkg/kube/inject/testdata/inject/prometheus-scrape2.yaml
  pkg/kube/inject/testdata/inject/prometheus-scrape2.yaml.injected
  pkg/kube/inject/webhook.go
  releasenotes/notes/36959.yaml
Labels: area/extensions and telemetry, size/XL, cherrypick/release-1.13

#37188 [release-1.13] respect prometheus annotations
  pkg/kube/inject/inject.go
  pkg/kube/inject/testdata/inject/prometheus-scrape.yaml
  pkg/kube/inject/testdata/inject/prometheus-scrape.yaml.injected
  pkg/kube/inject/testdata/inject/prometheus-scrape2.yaml
  pkg/kube/inject/testdata/inject/prometheus-scrape2.yaml.injected
  pkg/kube/inject/webhook.go
  releasenotes/notes/36959.yaml
Labels: size/XL, release-notes-none

#37158 tf: speed up telemetry tests
  pkg/test/echo/cmd/client/main.go
  pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/testdata/basic.yaml
  pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
  pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
  pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/components/prometheus/prometheus.go
  pkg/test/framework/resource/context.go
  pkg/test/framework/telemetry.go
  tests/integration/pilot/analyze_test.go
  tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/stats/prometheus/util_prometheus.go
  tests/integration/telemetry/util.go
Labels: size/XL, release-notes-none

#37187 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37193 Automator: update common-files@release-1.12 in istio/istio@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37191 Fix IOP merge for ingressgategateway label field
  operator/pkg/util/merge_iop.go
  operator/pkg/util/merge_iop_test.go
  operator/pkg/util/testdata/yaml/input/yaml_layer1.yaml
  operator/pkg/util/testdata/yaml/input/yaml_layer2.yaml
  operator/pkg/util/testdata/yaml/output/layer1.yaml
  operator/pkg/util/testdata/yaml/output/layer1_2.yaml
  operator/pkg/util/testdata/yaml/output/layer1_2_3.yaml
  operator/pkg/util/testdata/yaml/output/layer1_stdin.yaml
Labels: area/environments, ok-to-test, size/M, release-notes-none

#37194 Automator: update istio/client-go@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37195 [release-1.13] istioctl x metrice support custom duration
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/root.go
Labels: size/M, release-notes-none

#37200 Automator: update istio/api@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#36548 Fix ValidatingWebhookConfiguration naming in precheck
  istioctl/cmd/precheck.go
Labels: size/XS, release-notes-none

#36550 Remove useless rootca-compare alias
  istioctl/cmd/proxyconfig.go
Labels: size/XS, release-notes-none

#37018 Remove liveness prober from CNI Daemonset.
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: size/XS, release-notes-none

#37201 Automator: update istio/client-go@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37206 vm support: fix incorrect behaviour of the `hydrateWorkloadInstance()`
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/util.go
Labels: area/networking, size/L, release-notes-none

#36714 allow node selection parameters in operator chart
  manifests/charts/istio-operator/templates/deployment.yaml
  manifests/charts/istio-operator/values.yaml
Labels: area/environments, ok-to-test, size/S, release-notes-none

#37075 Credential controller: make use of generic event handler wrapper
  pilot/pkg/bootstrap/server.go
  pilot/pkg/credentials/kube/multicluster.go
  pilot/pkg/credentials/kube/secrets.go
Labels: size/M, release-notes-none

#37164 Fix IPv6 detection for EKS
  pilot/pkg/util/network/ip.go
  releasenotes/notes/fix-eks-ipv6.yaml
  tools/istio-iptables/pkg/cmd/root.go
Labels: area/networking, ok-to-test, size/S

#37212 Treat NaN as equal for fuzzer
  tests/fuzz/crd_roundtrip_fuzzer.go
  tests/fuzz/testdata/FuzzCRDRoundtrip/6428395234263040
Labels: size/XS, release-notes-none

#37213 Manually updating istio/api
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
  pilot/pkg/model/conversion_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/grpcgen/cds.go
Labels: area/networking, size/M, release-notes-none

#37211 [release-1.13] allow node selection parameters in operator chart
  manifests/charts/istio-operator/templates/deployment.yaml
  manifests/charts/istio-operator/values.yaml
Labels: size/S, release-notes-none

#37219 Only setup the credentials if there is one
  prow/lib.sh
Labels: area/test and release, size/XS, release-notes-none

#37222 Revert "Only setup the credentials if there is one"
  prow/lib.sh
Labels: size/XS, release-notes-none

#37204 [release-1.13] Fix ValidatingWebhookConfiguration naming in precheck
  istioctl/cmd/precheck.go
Labels: size/XS, release-notes-none

#37061 added tests for fromHeader and fromParams in request authentication
  tests/integration/security/jwt_test.go
  tests/integration/security/testdata/requestauthn/headers-params.yaml.tmpl
Labels: size/L, release-notes-none

#37208 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37214 Drop invalid filters instead of panic
  pilot/test/xdstest/extract.go
  tests/fuzz/testdata/FuzzValidateClusters/5567080949219328
Labels: size/XS, release-notes-none

#37224 Make helloworld app listen both ipv6 and ipv4 addresses
  samples/helloworld/src/app.py
Labels: size/XS, release-notes-none

#37122 send unhealthy endpoints to Envoy (take 2)
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/endpoint_builder.go
  releasenotes/notes/36274.yaml
Labels: area/networking, size/L

#37068 Fix x authz check example
  istioctl/cmd/authz.go
Labels: area/user experience, size/XS, release-notes-none, cherrypick/release-1.13

#37230 minor refactor `util/sets`
  pkg/kube/inject/webhook.go
Labels: area/networking, size/XS, release-notes-none

#37047 fix typo and do some refactoring work
  cni/pkg/taint/taint.go
  istioctl/pkg/validate/validate.go
  pilot/pkg/controller/workloadentry/workloadentry_controller.go
Labels: ok-to-test, size/XS, release-notes-none

#37180 break down NewStatusVerifier
  istioctl/pkg/install/verify.go
  istioctl/pkg/verifier/verifier.go
  operator/cmd/mesh/install.go
  tests/integration/operator/verify_test.go
Labels: ok-to-test, size/M, release-notes-none

#37128 [release-1.13] istioctl: fix order dependant tests
  cni/pkg/plugin/plugin_test.go
  istioctl/cmd/tag_test.go
  istioctl/cmd/workload.go
  pkg/kube/client.go
Labels: size/S, release-notes-none

#37210 Skip flaky TestWait
  tests/integration/pilot/istioctl_test.go
Labels: size/XS, release-notes-none

#37233 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37234 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37237 Use stable name for dumping
  pkg/test/kube/dump.go
Labels: size/XS, release-notes-none

#37238 Workaround centos repo removal
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Labels: size/XS, release-notes-none, cherrypick/release-1.12, cherrypick/release-1.13

#37220 Switch default LB algorithm to LEAST_REQUEST
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pkg/test/framework/features/features.gen.go
  pkg/test/framework/tools/featuresgen/cmd/root.go
  releasenotes/notes/new_lb_algorithm_default.yaml
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
  tests/integration/pilot/multicluster_test.go
  tests/integration/telemetry/constants.go
Labels: area/networking, size/M

#37241 [release-1.13] Workaround centos repo removal
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Labels: size/XS, release-notes-none

#37228 [release-1.13] Fix x authz check example
  istioctl/cmd/authz.go
Labels: size/XS, release-notes-none

#37242 Update BASE_VERSION to master-2022-02-09T20-27-12
  Makefile.core.mk
Labels: size/XS, release-notes-none

#37252 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#36903 add insecure oci support
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
  pkg/wasm/cache.go
  pkg/wasm/cache_test.go
  pkg/wasm/imagefetcher.go
Labels: size/M, release-notes-none

#37248 Update BASE_VERSION to master-2022-02-09T22-12-56
  Makefile.core.mk
Labels: size/XS, release-notes-none

#37255 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/M, auto-merge, release-notes-none

#37129 vm support: support multiple WorkloadEntry(s) with the same IP
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/util/workloadinstances/index.go
  pilot/pkg/serviceregistry/util/workloadinstances/index_test.go
  pilot/pkg/serviceregistry/util/workloadinstances/map.go
  pilot/pkg/serviceregistry/util/workloadinstances/util.go
  pilot/pkg/util/slices/string.go
Labels: area/networking, size/XL, release-notes-none

#37259 fix missing customService in EgressGatewayConfig
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/37259.yaml
Labels: area/environments, ok-to-test, size/S

#37236 Implement `runtimeValues` in proxy config
  pkg/bootstrap/config.go
  pkg/bootstrap/option/convert.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  releasenotes/notes/runtime-values.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L

#37275 [release-1.13] Fix linting issues with golangci-lint 1.44
  istioctl/cmd/add-to-mesh.go
  operator/pkg/util/yaml.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/testserver/server.go
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/config/file/util/kubeyaml/kubeyaml.go
  pilot/pkg/keycertbundle/watcher_test.go
  pilot/pkg/leaderelection/k8sleaderelection/k8sresourcelock/interface.go
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/authorization.go
  pilot/pkg/model/config.go
  pilot/pkg/model/proxy_config.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/virtualservice_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/trustbundle/trustbundle_test.go
  pkg/bootstrap/config.go
  pkg/bootstrap/platform/gcp_test.go
  pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  pkg/config/model_test.go
  pkg/config/resource/origin.go
  pkg/config/schema/collection/name.go
  pkg/config/schema/resource/schema.go
  pkg/envoy/agent.go
  pkg/istio-agent/xds_proxy_test.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/istio/istio.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/label/filter.go
  pkg/test/framework/resource/environment.go
  pkg/wasm/cache_test.go
  pkg/wasm/imagefetcher_test.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/k8s/chiron/utils.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/caclient/providers/google-cas/client.go
  security/pkg/pki/ra/k8s_ra.go
  security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin_test.go
  security/pkg/stsservice/tokenmanager/sts_test.go
  tools/docker-builder/main.go
  tools/istio-iptables/pkg/validation/vld_unix.go
Labels: size/L, release-notes-none

#37273 Automator: update common-files@release-1.13 in istio/istio@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37282 Automator: update istio/api@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37227 support Wasmplugin vmconfig
  pilot/pkg/model/extensions.go
  pilot/pkg/model/extensions_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/37227.yaml
Labels: area/extensions and telemetry, size/L

#37279 Automator: update istio/pkg@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#36551 Fix rootca-compare cmd validate logic error
  istioctl/cmd/proxyconfig.go
Labels: size/XS, release-notes-none

#36803 Fix describe pod PeerAuthentication info
  istioctl/cmd/describe.go
Labels: area/user experience, size/XS, release-notes-none

#37281 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37274 Automator: update istio/client-go@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37285 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37240 [release-1.12] Workaround centos repo removal
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Labels: size/XS, release-notes-none

#37246 istioctl: fix order dependant tests (#37045)
  cni/pkg/plugin/plugin_test.go
  istioctl/cmd/tag_test.go
  istioctl/cmd/workload.go
Labels: size/XS, release-notes-none

#37295 refactoring: remove code duplication in `serviceregistry/serviceentry`
  pilot/pkg/serviceregistry/serviceentry/store.go
Labels: area/networking, size/S, release-notes-none

#37256 set imagePullSecrets with values.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
Labels: ok-to-test, size/S, release-notes-none

#37280 Change Kiali's signing key
  manifests/addons/values-kiali.yaml
  samples/addons/kiali.yaml
Labels: area/environments, ok-to-test, size/XS, release-notes-none

#37284 Make use of Listener.EnableReusePort to replace deprecated ReusePort
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: area/networking, size/XS, release-notes-none

#37287 remove thrift protocol references
  pilot/pkg/networking/networking.go
  pkg/config/protocol/instance.go
  tests/fuzz/pilot_model_fuzzer.go
Labels: area/networking, size/S, release-notes-none

#37298 [release-1.13] set imagePullSecrets with values.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
Labels: size/S, release-notes-none

#37296 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/M, auto-merge, release-notes-none

#37300 Deprecate some test skip options for multicluster
  pkg/test/framework/suite.go
  tests/integration/helm/main_test.go
  tests/integration/helm/upgrade/main_test.go
  tests/integration/operator/main_test.go
  tests/integration/pilot/cni/cniversionskew_test.go
  tests/integration/pilot/endpointslice/endpointslice_test.go
  tests/integration/pilot/mcs/autoexport/autoexport_test.go
  tests/integration/pilot/revisioncmd/main_test.go
  tests/integration/pilot/revisions/revisions_test.go
  tests/integration/security/chiron/main_test.go
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/filebased_tls_origination/main_test.go
  tests/integration/security/mtlsk8sca/main_test.go
  tests/integration/security/sds_egress/main_test.go
  tests/integration/security/sds_ingress/quic/ingress_test.go
  tests/integration/security/sds_ingress_k8sca/main_test.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
Labels: area/test and release, size/S, release-notes-none

#37304 Automator: update common-files@release-1.13 in istio/istio@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37306 Automator: update istio/client-go@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37309 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37297 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37310 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37283 [release-1.13] Fix istioctl x describe not evaluating `appProtocol` properly
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  releasenotes/notes/37223.yaml
Labels: size/M, release-notes-none

#37313 log consistency in delta
  pilot/pkg/xds/delta.go
Labels: area/networking, size/S, release-notes-none

#37288 tests: covers pkg/config/kube/conversion.
  pkg/config/kube/conversion_test.go
Labels: area/test and release, ok-to-test, size/M, release-notes-none

#37312 reduce lock duration in delta
  pilot/pkg/xds/delta.go
Labels: area/networking, size/XS, release-notes-none

#37318 `remote.Image` respect `fetchOpts`
  pkg/wasm/imagefetcher.go
Labels: area/extensions and telemetry, size/XS, release-notes-none

#36820 Get all the VIPs of a service entry through MCP over xDS
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
Labels: size/S, release-notes-none

#37316 fix type assertion
  pilot/pkg/config/file/store.go
Labels: area/perf and scalability, ok-to-test, size/XS, release-notes-none

#37317 [release-1.13] Run update_deps
  go.mod
  go.sum
  prow/release-commit.sh
Labels: size/S, release-notes-none

#37299 Update BASE_VERSION to 1.12-2022-02-11T19-01-16
  Makefile.core.mk
Labels: size/XS, release-notes-none

#37327 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37328 [TF] Create common WaitForConfig implementation
  pkg/test/framework/components/istioctl/istioctl.go
  pkg/test/framework/components/istioctl/kube.go
  pkg/test/framework/config.go
  pkg/test/framework/resource/context.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/reachability/context.go
  tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
Labels: area/test and release, size/L, release-notes-none

#37333 Automator: update common-files@release-1.12 in istio/istio@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37339 remove CheckProxyVerionForMX in 1.14
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/util/util.go
Labels: size/M, release-notes-none

#37334 Automator: update istio/client-go@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37350 Fix rendering of injectedAnnotations in Helm charts
  manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
Labels: area/environments, ok-to-test, size/XS, release-notes-none

#37351 Automator: update istio/client-go@release-1.11 dependency in istio/istio@release-1.11
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37040 Validate certificate before sending back to proxy
  pilot/pkg/features/pilot.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  pilot/pkg/xds/testdata/benchmarks/secrets.yaml
Labels: size/L, release-notes-none

#37349 Automator: update common-files@release-1.11 in istio/istio@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37353 Fix invalid flag definition in echo
  pkg/test/echo/cmd/client/main.go
Labels: size/XS, release-notes-none

#37352 Drop unneeded `replace` directives
  go.mod
  go.sum
  licenses/github.com/containerd/continuity/LICENSE
  licenses/github.com/docker/docker/contrib/busybox/LICENSE
  licenses/github.com/docker/docker/contrib/syntax/vim/LICENSE
  licenses/github.com/docker/go-units/LICENSE
  licenses/github.com/opencontainers/runc/LICENSE
Labels: size/XL, release-notes-none

#37271 Add warning when setting certs with PASSTHROUGH mode
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/S, release-notes-none, cherrypick/release-1.12, cherrypick/release-1.13

#37332 [TF] Install Istio with istioctl library
  operator/cmd/mesh/install.go
  operator/cmd/mesh/manifest-diff.go
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest.go
  operator/cmd/mesh/operator-common.go
  operator/cmd/mesh/operator-dump.go
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/operator-remove.go
  operator/cmd/mesh/operator.go
  operator/cmd/mesh/operator_test.go
  operator/cmd/mesh/profile-diff.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/profile-list.go
  operator/cmd/mesh/profile.go
  operator/cmd/mesh/root.go
  operator/cmd/mesh/shared.go
  operator/cmd/mesh/uninstall.go
  operator/cmd/mesh/upgrade.go
  pkg/test/framework/components/istio/eastwest.go
  pkg/test/framework/components/istio/operator.go
Labels: area/test and release, size/XL, release-notes-none

#37325 [TF] Prevent concurrent istioctl invoke
  pkg/test/framework/components/istioctl/kube.go
Labels: area/test and release, size/S, release-notes-none

#37360 [release-1.13] Add warning when setting certs with PASSTHROUGH mode
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/S, release-notes-none

#37363 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37301 client protocol jobs: expand coverage to more port names
  pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
  pkg/test/framework/components/echo/common/defaults.go
  tests/integration/pilot/common/routing.go
Labels: size/L, release-notes-none
