Repository istio/istio, pull requests merged in 2022-11, with the labels that each got.

#41548 add `--purge` flags to operator remove
  operator/cmd/mesh/operator-remove.go
  operator/cmd/mesh/root.go
  releasenotes/notes/41548.yaml
  tests/integration/operator/switch_cr_test.go
Labels: area/user experience, size/M, release-notes-none

#41624 Replace of net.IP by netip.Addr in adsc
  pilot/pkg/util/network/ip.go
  pkg/adsc/adsc.go
Labels: size/M, release-notes-none

#41711 remove thrift config references
  operator/pkg/util/merge_iop.go
  pkg/config/mesh/mesh.go
Labels: area/networking, size/XS, release-notes-none

#41686 refactor and move hbone cluster code
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/util/util.go
Labels: area/networking, size/L, release-notes-none

#41714 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41610 Optimize MostSpecificHostMatch
  pilot/pkg/model/cluster_local.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/destination_rule.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pkg/config/host/names.go
  releasenotes/notes/optimize-most-specific-host-match.yaml
Labels: area/perf and scalability, ok-to-test, size/L

#41707 [release-1.15] fix pilotExists regression
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/prune_test.go
  pkg/kube/mock_client.go
  pkg/test/framework/features/features.yaml
  releasenotes/notes/41644.yaml
  tests/integration/operator/uninstall_test.go
Labels: size/L

#41717 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41720 Automator: update common-files@release-1.16 in istio/istio@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41721 Dump helm failures
  tests/integration/helm/install_test.go
Labels: size/XS, release-notes-none

#41722 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41723 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41725 Update BASE_VERSION to 1.15-2022-11-02T00-18-32
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41724 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41726 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41719 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41733 Update BASE_VERSION to 1.16-2022-11-02T13-31-52
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41732 Update BASE_VERSION to master-2022-11-02T13-32-04
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41712 operator: deprecation announcement of fetching charts
  operator/pkg/manifest/shared.go
  releasenotes/notes/deprecate-operator-httpfetch.yaml
Labels: area/environments, size/XS, cherrypick/release-1.16

#41736 [release-1.16] operator: deprecation announcement of fetching charts
  operator/pkg/manifest/shared.go
  releasenotes/notes/deprecate-operator-httpfetch.yaml
Labels: size/XS, release-notes-none

#41635 [bug fix] Skip the pod inaccessible for `istioctl ps --xds-via-agent`
  istioctl/pkg/multixds/gather.go
Labels: size/XS, release-notes-none, cherrypick/release-1.14, cherrypick/release-1.15, cherrypick/release-1.16

#41743 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41744 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41740 [release-1.16] [bug fix] Skip the pod inaccessible for `istioctl ps --xds-via-agent`
  istioctl/pkg/multixds/gather.go
Labels: size/XS, release-notes-none

#41739 [release-1.15] [bug fix] Skip the pod inaccessible for `istioctl ps --xds-via-agent`
  istioctl/pkg/multixds/gather.go
Labels: size/XS, release-notes-none

#41416 wasm: enhance fallback logic for the Wasm module download failure
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
  pkg/config/xds/filters.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/wasm/convert.go
  pkg/wasm/convert_test.go
  releasenotes/notes/wasm-download-fallback.yaml
  tests/integration/telemetry/api/testdata/bad-wasm-envoy-filter-fail-open.yaml
  tests/integration/telemetry/api/wasmplugin_test.go
Labels: size/L, cherrypick/release-1.13, cherrypick/release-1.14, cherrypick/release-1.15, cherrypick/release-1.16

#41752 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41745 loadbalancer: add fuzzer
  pilot/pkg/networking/core/v1alpha3/loadbalancer/fuzz_test.go
Labels: area/test and release, area/networking, area/security, size/M, release-notes-none

#41770 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41766 refactor hbone listener code
  pilot/pkg/model/listener.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/filters/filters.go
Labels: size/M, release-notes-none

#41765 remove unnecessary type from set initialization
  pkg/config/security/security.go
  pkg/envoy/agent.go
Labels: size/XS, release-notes-none

#41764 Add endpoint check for ServiceEntry.
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: release-notes-none

#41777 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41780 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41633 ambient: integrate ztunnel builds
  CONTRIBUTING.md
  Makefile.core.mk
  README.md
  bin/build_ztunnel.sh
  bin/init.sh
  istio.deps
  manifests/charts/ztunnel/templates/daemonset.yaml
  pilot/docker/Dockerfile.ztunnel
  prow/lib.sh
  tools/docker.yaml
Labels: size/L

#41737 Limit webhook patcher to patch owned webhooks
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/webhooks/util/util.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
  releasenotes/notes/scope-webhook-cert-patching.yaml
Labels: size/M, cherrypick/release-1.16

#41742 gateway-api: implement gep-1426
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  tests/integration/pilot/ingress_test.go
Labels: size/L, release-notes-none

#41778 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41783 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41776 [bugfix] Fix restarting logic of deployment in the test framework
  pkg/test/framework/components/echo/kube/deployment.go
Labels: size/M, release-notes-none

#41781 [release-1.16] Limit webhook patcher to patch owned webhooks
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/webhooks/util/util.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
  releasenotes/notes/scope-webhook-cert-patching.yaml
Labels: size/M, release-notes-none

#41782 Move ConfigKey to a `Set` instead of map
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/xds_cache.go
  pilot/pkg/model/xds_cache_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/route/route_cache_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/ecds_test.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/proxy_dependencies_test.go
  pilot/pkg/xds/pushqueue_test.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  pilot/pkg/xds/xds_cache_test.go
  security/pkg/nodeagent/sds/server.go
Labels: size/XL, release-notes-none

#41483 Add support for multi-arch releaseTar URL
  pkg/url/url.go
  pkg/url/url_test.go
  releasenotes/notes/41483.yaml
Labels: area/test and release, area/user experience, size/S

#41785 add telemetry analyzer
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/telemetry/providers.go
  pkg/config/analysis/analyzers/testdata/telemetry-invalid-provider.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/41785.yaml
Labels: area/extensions and telemetry, area/user experience, size/L

#41727 strip pod unused fields
  pilot/pkg/security/model/authentication.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/M, release-notes-none

#41786 operator: clean code
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/util/tgz/tgz.go
Labels: area/environments, size/L, release-notes-none

#41795 [fix] Increase the timeout for restarting to 60s
  pkg/test/framework/components/echo/kube/deployment.go
Labels: size/XS, release-notes-none

#41797 gateway-api: enable mesh ingress tests
  pilot/pkg/config/kube/gateway/conversion.go
  tests/integration/pilot/ingress_test.go
Labels: size/S, release-notes-none

#41761 Fix PrivateKeyProvider's problem with proxy-config
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  releasenotes/notes/41761.yaml
Labels: area/security, ok-to-test, size/M

#41798 [release-1.16] gateway-api: implement gep-1426
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  tests/integration/pilot/ingress_test.go
Labels: size/L, release-notes-none

#41801 Verify signature from CSRs
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ra/common.go
Labels: area/security, size/XS, release-notes-none

#41803 A few small ztunnel fixes
  bin/build_ztunnel.sh
  manifests/charts/ztunnel/templates/daemonset.yaml
  tools/docker.yaml
Labels: size/S

#41804 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41805 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41807 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41775 original_dst: set idle timeout to 5min
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: size/S, release-notes-none, cherrypick/release-1.16

#41809 Fix config key hashcode collision issue.
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
Labels: release-notes-none

#41812 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41806 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41815 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41816 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41817 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41810 [release-1.16] original_dst: set idle timeout to 5min
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: size/S, release-notes-none

#41728 No need to cache when the token is equal to the cached one
  pilot/pkg/model/xds_cache.go
  pilot/pkg/model/xds_cache_test.go
Labels: size/XS, release-notes-none

#41820 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41819 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41811 do not push dns round robin cluster with incorrect lb endpoints
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: area/networking, size/S, release-notes-none, cherrypick/release-1.16

#41828 Broken links corrections
  pkg/config/analysis/README.md
Labels: kind/docs, size/XS, release-notes-none

#41799 [release-1.16] gateway-api: enable mesh ingress tests
  pilot/pkg/config/kube/gateway/conversion.go
  tests/integration/pilot/ingress_test.go
Labels: size/S, release-notes-none

#41821 [release-1.16] No need to cache when the token is equal to the cached one
  pilot/pkg/model/xds_cache.go
  pilot/pkg/model/xds_cache_test.go
Labels: size/XS, release-notes-none

#41832 Update go-control-plane
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: area/test and release, size/XS, release-notes-none

#41833 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41834 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41835 Automator: update common-files@release-1.16 in istio/istio@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41836 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41796 ambient: Refactor workload discovery to be more efficient and support on-demand
  pilot/pkg/model/config.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
  pilot/pkg/serviceregistry/kube/controller/filter/informer.go
  pilot/pkg/serviceregistry/kube/controller/util.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/deltaadstest.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/workload.go
  pilot/pkg/xds/workload_test.go
  pkg/config/schema/codegen/collections.go
  pkg/config/schema/kind/resources.gen.go
  pkg/kube/controllers/common.go
  pkg/kube/controllers/index.go
Labels: size/XXL, release-notes-none

#41822 Fix GetKubernetesVersion
  pkg/kube/client.go
Labels: size/XS, release-notes-none

#41738 [release-1.14] [bug fix] Skip the pod inaccessible for `istioctl ps --xds-via-agent`
  istioctl/pkg/multixds/gather.go
Labels: size/XS, release-notes-none

#41837 Update BASE_VERSION to 1.13-2022-11-07T19-02-24
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41842 [release-1.14] chiron: amend cert watch timeout for DNS certificates
  security/pkg/k8s/chiron/controller.go
Labels: size/XS, release-notes-none

#41843 [release-1.15] chiron: amend cert watch timeout for DNS certificates
  security/pkg/k8s/chiron/controller.go
Labels: size/XS, release-notes-none

#41841 [release-1.16] chiron: amend cert watch timeout for DNS certificates
  security/pkg/k8s/chiron/controller.go
Labels: size/XS, release-notes-none

#41845 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41844 [release-1.16] Run update_deps.sh
  docker/Dockerfile.distroless
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: size/S, release-notes-none

#41853 Automator: update proxy@release-1.14 in istio/istio@release-1.14
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41846 Update to make prow/release-commit.sh executable after sed
  bin/update_deps.sh
Labels: area/test and release, size/XS, release-notes-none, cherrypick/release-1.14, cherrypick/release-1.15, cherrypick/release-1.16

#41866 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#41865 [release-1.16] Update to make prow/release-commit.sh executable after sed
  bin/update_deps.sh
Labels: size/XS, release-notes-none

#41870 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41872 Deny h2c upgrade traffic around the code base
  common/config/.golangci.yml
  pilot/pkg/bootstrap/server.go
  pkg/h2c/wrapper.go
  pkg/hbone/server.go
  pkg/istio-agent/xds_proxy.go
  pkg/test/echo/server/endpoint/http.go
Labels: size/M, release-notes-none

#41867 Add Install/Upgrade Survey for 1.16
  manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
  operator/cmd/mesh/install.go
Labels: ok-to-test, size/XS, release-notes-none

#41873 Update BASE_VERSION to 1.14-2022-11-08T20-17-22
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41875 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41877 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41879 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40329 Add skywalking extension provider to demo profile
  manifests/profiles/demo.yaml
Labels: ok-to-test, size/XS, lifecycle/automatically-closed, release-notes-none

#41878 rename to denyH2cUpgrade
  pkg/h2c/wrapper.go
Labels: size/XS, release-notes-none

#41886 Revert "do not push dns round robin cluster with incorrect lb endpoints"
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: size/S, release-notes-none, cherrypick/release-1.16

#41887 Revert "[release-1.16] Limit webhook patcher to patch owned webhooks"
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/webhooks/util/util.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
  releasenotes/notes/scope-webhook-cert-patching.yaml
Labels: size/M, release-notes-none

#41890 [release-1.15] run UPDATE_BRANCH=release-1.15 ./bin/update_deps.sh
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: area/test and release, size/S, release-notes-none

#41885 [release-1.16] Deny h2c upgrade traffic around the code base
  common/config/.golangci.yml
  pilot/pkg/bootstrap/server.go
  pkg/h2c/wrapper.go
  pkg/hbone/server.go
  pkg/istio-agent/xds_proxy.go
  pkg/test/echo/server/endpoint/http.go
Labels: size/M, release-notes-none

#41889 [release-1.14] run UPDATE_BRANCH=release-1.14 ./bin/update_deps.sh
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: area/test and release, size/S, release-notes-none

#41897 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41757 [release-1.15] wasm: enhance fallback logic for the Wasm module download failure (#41416)
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
  pkg/config/xds/filters.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/wasm/convert.go
  pkg/wasm/convert_test.go
  releasenotes/notes/wasm-download-fallback.yaml
  tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/wasm/testdata/bad-wasm-envoy-filter-fail-open.yaml
Labels: size/L

#41893 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41517 Fix validate ignore service port appProtocol
  istioctl/pkg/validate/validate.go
  istioctl/pkg/validate/validate_test.go
  pkg/url/url.go
  pkg/url/url_test.go
  releasenotes/notes/validate-appprotocol.yaml
Labels: area/environments, area/user experience, size/M

#41898 Fixed kind issue
  samples/kind-lb/setupkind.sh
Labels: size/XS, release-notes-none

#41894 add a size check on wasm module
  pkg/wasm/httpfetcher.go
  pkg/wasm/imagefetcher.go
Labels: area/networking, size/S, release-notes-none

#41895 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41900 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41901 add validation for dns round robin endpoints
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/M, release-notes-none

#41831 filter service instances based on service creation for round robin
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/serviceregistry/serviceentry/store.go
  pilot/pkg/serviceregistry/serviceentry/store_test.go
Labels: area/networking, size/L, release-notes-none

#41907 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41863 [release-1.14] Update to make prow/release-commit.sh executable after sed
  bin/update_deps.sh
Labels: size/XS, release-notes-none

#41919 fix istio crashes with memory nil pointer
  pilot/pkg/model/push_context.go
Labels: area/perf and scalability, ok-to-test, size/XS, release-notes-none, cherrypick/release-1.16

#41905 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41906 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41904 Allow skipping tests not yet working on Rust ztunnel
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  tests/integration/ambient/baseline_test.go
Labels: size/S

#41926 [release-1.16] fix istio crashes with memory nil pointer
  pilot/pkg/model/push_context.go
Labels: size/XS, release-notes-none

#41932 [release-1.15] Manual cherry-pick of #40578
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/prune_test.go
  operator/pkg/helmreconciler/testdata/iop-test-gw-1.yaml
  operator/pkg/helmreconciler/testdata/iop-test-gw-2.yaml
  releasenotes/notes/40578.yaml
Labels: size/L

#41931 [release-1.16] Manual cherry-pick of #40578
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/prune_test.go
  operator/pkg/helmreconciler/testdata/iop-test-gw-1.yaml
  operator/pkg/helmreconciler/testdata/iop-test-gw-2.yaml
  releasenotes/notes/40578.yaml
Labels: size/L

#41934 gateway-api: more bookinfo config yamls
  samples/bookinfo/gateway-api/route-reviews-50-v3.yaml
  samples/bookinfo/gateway-api/route-reviews-v1.yaml
  samples/bookinfo/gateway-api/route-reviews-v3.yaml
Labels: size/M, release-notes-none, cherrypick/release-1.16

#41431 feat:clean-iptables consider InboundInterceptionMode
  releasenotes/notes/41431.yaml
  tools/istio-clean-iptables/main_test.go
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-clean-iptables/pkg/cmd/testdata/inbound-interception-mode.golden
  tools/istio-clean-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: area/networking, ok-to-test, size/L

#41922 Bump Gateway-API dependency
  go.mod
  go.sum
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/L, release-notes-none

#41936 [release-1.16] gateway-api: more bookinfo config yamls
  samples/bookinfo/gateway-api/route-reviews-50-v3.yaml
  samples/bookinfo/gateway-api/route-reviews-v1.yaml
  samples/bookinfo/gateway-api/route-reviews-v3.yaml
Labels: size/M, release-notes-none

#41941 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41908 telemetry: fix datadog hostname
  go.mod
  go.sum
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
  releasenotes/notes/41908.yaml
Labels: size/M

#41161 operator: add resourcequotas in clusterrole
  manifests/charts/istio-operator/files/gen-operator.yaml
  manifests/charts/istio-operator/templates/clusterrole.yaml
  releasenotes/notes/41161.yaml
Labels: area/environments, size/S, cherrypick/release-1.14, cherrypick/release-1.15, cherrypick/release-1.16

#41947 [release-1.15] operator: add resourcequotas in clusterrole
  manifests/charts/istio-operator/files/gen-operator.yaml
  manifests/charts/istio-operator/templates/clusterrole.yaml
  releasenotes/notes/41161.yaml
Labels: size/S, release-notes-none

#41945 [release-1.16] operator: add resourcequotas in clusterrole
  manifests/charts/istio-operator/files/gen-operator.yaml
  manifests/charts/istio-operator/templates/clusterrole.yaml
  releasenotes/notes/41161.yaml
Labels: size/S, release-notes-none

#41950 [release-1.16] add validation for dns round robin endpoints
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/M, release-notes-none

#41951 [release-1.16] add a size check on wasm module
  pkg/wasm/httpfetcher.go
  pkg/wasm/imagefetcher.go
Labels: size/S, release-notes-none

#41952 More bookinfo yamls
  samples/bookinfo/gateway-api/route-all-v1.yaml
  samples/bookinfo/platform/kube/bookinfo-versions.yaml
Labels: size/M, release-notes-none, cherrypick/release-1.16

#41953 [release-1.16] More bookinfo yamls
  samples/bookinfo/gateway-api/route-all-v1.yaml
  samples/bookinfo/platform/kube/bookinfo-versions.yaml
Labels: size/M, release-notes-none

#41851 [release-1.14] Fix GetKubernetesVersion
  pkg/kube/client.go
Labels: size/XS, release-notes-none

#41960 Manual cherrypick: "Check if metadata endpoint is available and trigger GCP requests concurrently" 40105
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
Labels: area/environments, size/L, release-notes-none, cherrypick/release-1.15

#41961 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41963 [release-1.15] Manual cherrypick: "Check if metadata endpoint is available and trigger GCP requests concurrently" 40105
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
Labels: size/L, release-notes-none

#41962 limit memory in sts debug mode
  security/pkg/stsservice/server/server.go
Labels: size/S, release-notes-none

#41802 L7 deny rule check in authz validation
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/25832.yaml
Labels: area/security, size/L

#41966 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41967 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41969 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41971 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41972 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#41973 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41974 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41982 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41985 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41981 Revert "Limit webhook patcher to patch owned webhooks"
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/webhooks/util/util.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
  releasenotes/notes/scope-webhook-cert-patching.yaml
Labels: size/M, release-notes-none
