Repository istio/istio, pull requests merged in 2022-10, with the labels that each got.

#41240 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41242 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41251 Remove log line
  pilot/pkg/config/kube/crdclient/client.go
Labels: size/XS, release-notes-none

#41252 gateway-api: update samples v1alpha2 -> v1beta1
  samples/bookinfo/gateway-api/bookinfo-gateway.yaml
  samples/helloworld/gateway-api/helloworld-gateway.yaml
  samples/helloworld/gateway-api/helloworld-route.yaml
Labels: size/S, release-notes-none

#41253 [1.13] Fix PushContext.sidecarIndex.rootConfig flipping issue (#40575)
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/sidecar-flipflop.yaml
Labels: size/S

#41254 [1.14] Fix PushContext.sidecarIndex.rootConfig flipping issue (#40575)
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/sidecar-flipflop.yaml
Labels: size/S

#41265 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41266 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41269 Automator: update istio/client-go@release-1.14 dependency in istio/istio@release-1.14
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41267 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41268 Automator: update common-files@release-1.14 in istio/istio@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41270 1.13 branch fix for CVE-2022-41715
  go.mod
  go.sum
  istioctl/cmd/config_test.go
  istioctl/cmd/dashboard_test.go
  istioctl/cmd/describe.go
  istioctl/cmd/istioctl_test.go
  istioctl/cmd/istiodconfig.go
  istioctl/cmd/kubeinject_test.go
  istioctl/cmd/kubeuninject.go
  istioctl/cmd/kubeuninject_test.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/options_test.go
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/authz/listener.go
  istioctl/pkg/validate/validate_test.go
  licenses/rsc.io/xstd/go1.19.2/LICENSE
  operator/cmd/mesh/profile-dump_test.go
  operator/cmd/mesh/test-util.go
  operator/pkg/compare/compare.go
  operator/pkg/tpath/tree.go
  operator/pkg/util/path.go
  operator/pkg/validate/common.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingressv1/conversion.go
  pilot/pkg/model/context.go
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/security/authz/matcher/header.go
  pilot/pkg/security/authz/matcher/header_test.go
  pilot/pkg/simulation/traffic.go
  pilot/test/util/diff.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/platform/gcp.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/injection/injection-image.go
  pkg/config/analysis/analyzers/util/constants.go
  pkg/config/analysis/analyzers/virtualservice/regexes.go
  pkg/config/analysis/msg/generate.main.go
  pkg/config/labels/instance.go
  pkg/config/validation/validation.go
  pkg/kube/util.go
  pkg/test/echo/client/parsedresponse.go
  pkg/test/envoy/binary.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/label/filter.go
  pkg/test/framework/resource/matcher.go
  pkg/test/framework/suite.go
  pkg/test/framework/tools/featuresgen/cmd/root.go
  pkg/test/util/structpath/instance.go
  pkg/test/util/yml/parts.go
  releasenotes/notes/41270.yaml
  security/pkg/nodeagent/caclient/providers/google/client.go
  tests/fuzz/regression_test.go
  tests/integration/pilot/istioctl_test.go
  tools/bug-report/pkg/cluster/cluster.go
Labels: size/L

#41274 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41277 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41279 Automator: update common-files@master in istio/istio@master
  LICENSE
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#41278 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41283 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41286 [release-1.14] Only expand vhost domains for local services
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  releasenotes/notes/38678.yaml
Labels: size/M, release-notes-none

#41288 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  licenses/istio.io/api/LICENSE
  licenses/istio.io/client-go/LICENSE
Labels: size/S, auto-merge, release-notes-none

#41294 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41295 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41297 [1.15] gateway-api: fix an issue causing Informers to fail
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-simple.yaml
  pkg/kube/controllers/common.go
  releasenotes/notes/gateway-v1beta1.yaml
Labels: size/L

#41296 [1.14] gateway-api: fix an issue causing Informers to fail
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-simple.yaml
  pkg/kube/controllers/common.go
  releasenotes/notes/gateway-v1beta1.yaml
Labels: size/L, release-notes-none

#41298 [1.13] gateway-api: fix an issue causing Informers to fail
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/alpha-simple.yaml
  pkg/kube/controllers/common.go
  releasenotes/notes/gateway-v1beta1.yaml
Labels: size/L

#41299 gateway-api: add Istio option for MUTUAL TLS mode
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
Labels: size/M, release-notes-none

#41285 Remove my 15 minutes of fame in gcp_bootstrap
  tools/packaging/common/gcp_envoy_bootstrap.json
Labels: size/XS, release-notes-none, cherrypick/release-1.14, cherrypick/release-1.15

#41106 Add support for custom proxy config to waypoints
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/ambient/controller/waypoint_controller.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: size/S, release-notes-none, area/ambient

#41300 [release-1.14] Remove my 15 minutes of fame in gcp_bootstrap
  tools/packaging/common/gcp_envoy_bootstrap.json
Labels: size/XS, release-notes-none

#41255 [1.15] Fix PushContext.sidecarIndex.rootConfig flipping issue (#40575)
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/sidecar-flipflop.yaml
Labels: size/S

#41302 Fix issue with GVK in event handlers
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: size/S, release-notes-none

#41301 [release-1.15] Remove my 15 minutes of fame in gcp_bootstrap
  tools/packaging/common/gcp_envoy_bootstrap.json
Labels: size/XS, release-notes-none

#41303 Fix issue with GVK in event handlers
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: size/S, release-notes-none

#41304 Fix issue with GVK in event handlers
  pilot/pkg/config/kube/crdclient/cache_handler.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: size/S, release-notes-none

#41245 istioctl: add confirmation for istioctl operator remove
  operator/cmd/mesh/operator-remove.go
  releasenotes/notes/41245.yaml
  tests/integration/operator/switch_cr_test.go
Labels: area/user experience, size/S, release-notes-none

#41310 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#40660 session affinity support for proxyless gRPC, EDS draining
  pilot/pkg/features/pilot.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/xds/endpoint_builder.go
  pkg/istio-agent/xds_proxy.go
  security/pkg/credentialfetcher/fetcher.go
Labels: area/networking, size/L, release-notes-none

#41261 Place `istio.metadata_exchange` before RBAC filters for network and HTTP filters
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  releasenotes/notes/41066.yaml
Labels: area/networking, ok-to-test, size/L, release-notes-none

#40382 Add check-inject feature to describe pod injection
  istioctl/cmd/checkinject.go
  istioctl/cmd/checkinject_test.go
  istioctl/cmd/root.go
  istioctl/cmd/testdata/check-inject/default-injector.yaml
  istioctl/cmd/testdata/check-inject/rev-16-injector.yaml
  istioctl/pkg/writer/table/writer.go
  istioctl/pkg/writer/table/writer_test.go
  releasenotes/notes/x-check-inject.yaml
Labels: area/user experience, size/XXL

#41323 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41324 Fix exportTo field validation
  pkg/config/visibility/visibility.go
Labels: area/networking, size/XS, release-notes-none

#41231 [release-1.15] Fix proxyconfig annotation lead to kube-inject panic
  istioctl/cmd/kubeinject.go
  istioctl/cmd/kubeinject_test.go
  istioctl/cmd/testdata/deployment/hello-with-proxyconfig-anno.yaml
  istioctl/cmd/testdata/deployment/hello-with-proxyconfig-anno.yaml.injected
  releasenotes/notes/40778.yaml
Labels: size/L, release-notes-none

#41317 Add revision validation to operator dump
  operator/cmd/mesh/operator-dump.go
Labels: area/environments, size/XS, release-notes-none

#41338 Remove metrics that do nothing
  pilot/pkg/xds/monitoring.go
Labels: size/S, release-notes-none

#41340 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#41322 operator: fix schema cluster scoped
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.yaml
  releasenotes/notes/41322.yaml
Labels: area/environments, size/S, cherrypick/release-1.13, cherrypick/release-1.14, cherrypick/release-1.15

#41332 replace the net.ParseCIDR for pkg/capture
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_test.go
Labels: size/M, release-notes-none

#41334 replace the net.ParseCIDR for pkg/server/ca/authenticate
  security/pkg/server/ca/authenticate/xfcc_authenticator.go
Labels: size/S, release-notes-none

#41344 [release-1.13] Manual cherry-pick of #40165
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  releasenotes/notes/serviceentry-ip-auto-allocation.yaml
Labels: area/networking, size/M

#41345 [release-1.14] operator: fix schema cluster scoped
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.yaml
  releasenotes/notes/41322.yaml
Labels: size/S, release-notes-none

#41348 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41352 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41347 [release-1.13] operator: fix schema cluster scoped
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.yaml
  releasenotes/notes/41322.yaml
Labels: size/S, release-notes-none

#41212 tracing: set datadog ServiceName
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
  releasenotes/notes/41212.yaml
Labels: area/extensions and telemetry, size/L, cherrypick/release-1.14, cherrypick/release-1.15

#41329 Fix data race in multicluster case.
  pilot/pkg/credentials/kube/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
Labels: release-notes-none

#41343 Drop unneeded `gogo` imports and add lint
  common/config/.golangci.yml
  pilot/pkg/bootstrap/config_compare.go
  pilot/pkg/model/virtualservice.go
  pkg/config/analysis/local/helpers_test.go
  pkg/config/model.go
  pkg/config/resource/instance_test.go
  pkg/config/schema/collection/schema_test.go
  pkg/config/schema/collection/schemas_test.go
  pkg/kube/fakemirror.go
  pkg/util/gogoprotomarshal/protomarshal.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
Labels: size/M, release-notes-none

#41357 [release-1.15] tracing: set datadog ServiceName
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
  releasenotes/notes/41212.yaml
Labels: area/extensions and telemetry, size/L

#41346 [release-1.15] operator: fix schema cluster scoped
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.yaml
  releasenotes/notes/41322.yaml
Labels: size/S, release-notes-none

#41213 do not apply rate limits for sds server
  pilot/pkg/xds/discovery.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: size/S, release-notes-none

#41365 Add missing unit test for #40165
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
Labels: area/test and release, size/M, release-notes-none, cherrypick/release-1.13, cherrypick/release-1.14, cherrypick/release-1.15

#41372 [release-1.13] Add missing unit test for #40165
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
Labels: size/M, release-notes-none

#41374 [release-1.15] Add missing unit test for #40165
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
Labels: size/M, release-notes-none

#41368 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#41358 [release-1.14] tracing: set datadog ServiceName
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
  releasenotes/notes/41212.yaml
Labels: area/extensions and telemetry, size/L

#41378 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41367 all: fix a few function names on comments
  istioctl/cmd/describe.go
  istioctl/cmd/precheck.go
  operator/cmd/mesh/operator-dump.go
Labels: ok-to-test, size/S, release-notes-none

#41311 Fix Sidecar egress TCP listener doesn't use auto allocated address
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: area/networking, size/L, release-notes-none

#41385 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41384 Add CODEOWNERS for ambient
  CODEOWNERS
Labels: size/M, release-notes-none

#41390 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41394 Automator: update istio/client-go@release-1.15 dependency in istio/istio@release-1.15
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41399 fix istio-cni link
  manifests/charts/istio-cni/Chart.yaml
Labels: area/environments, size/XS, release-notes-none

#41272 Failover validation
  pkg/config/mesh/mesh.go
  pkg/config/mesh/mesh_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/failover-validation.yaml
Labels: area/networking, size/L

#41400 partially replace the net by the netip for ip validate
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingressv1/status.go
  pilot/pkg/model/config.go
  pilot/pkg/model/context.go
  pilot/pkg/model/network.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/xds/debug.go
  pkg/config/validation/validation.go
  pkg/util/net/ip.go
Labels: size/L, release-notes-none

#40799 telemetry e2e: move most of code out of `stats/prometheus`
  tests/integration/telemetry/api/accesslogs_test.go
  tests/integration/telemetry/api/stats_wasm_filter_test.go
  tests/integration/telemetry/api/stats_wasm_tcp_filter_test.go
  tests/integration/telemetry/common/stats.go
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/envoyfilter/customizemetrics/testdata/attributegen_envoy_filter.yaml
  tests/integration/telemetry/envoyfilter/nullvm/dashboard_test.go
  tests/integration/telemetry/envoyfilter/nullvm/istioctl_metrics_test.go
  tests/integration/telemetry/envoyfilter/nullvm/stats_filter_test.go
  tests/integration/telemetry/envoyfilter/nullvm/stats_tcp_filter_test.go
  tests/integration/telemetry/envoyfilter/wasm/bad_wasm_filter_test.go
  tests/integration/telemetry/envoyfilter/wasm/imagepullpolicy_test.go
  tests/integration/telemetry/envoyfilter/wasm/stats_wasm_filter_test.go
  tests/integration/telemetry/envoyfilter/wasm/stats_wasm_tcp_filter_test.go
  tests/integration/telemetry/envoyfilter/wasm/testdata/bad-filter.yaml
  tests/integration/telemetry/envoyfilter/wasm/testdata/registry-secret.yaml
  tests/integration/telemetry/envoyfilter/wasm/testdata/wasm-filter.yaml
  tests/integration/telemetry/envoyfilter/wasm/testsetup.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/stats/prometheus/util_prometheus.go
  tests/integration/telemetry/testdata/istio-mtls-dest-rule.yaml
  tests/integration/telemetry/testdata/istio-mtls-gateway.yaml
  tests/integration/telemetry/testdata/istio-mtls-vs.yaml
  tests/integration/telemetry/util.go
Labels: area/extensions and telemetry, size/L, release-notes-none

#41395 partially replace the net by the netip for the pilot/pkg/serviceregistry
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
Labels: size/S, release-notes-none

#41404 [release-1.15] Pilot: Add a guard against empty TRUSTED_GATEWAY_CIDR feature
  pilot/pkg/features/pilot.go
  releasenotes/notes/41171.yaml
Labels: size/S, release-notes-none

#41387 echo: add UDP support
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/scheme/scheme.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/endpoint/udp.go
  pkg/test/echo/server/endpoint/util.go
  pkg/test/echo/server/forwarder/instance.go
  pkg/test/echo/server/forwarder/udp.go
  pkg/test/echo/server/instance.go
Labels: size/L, release-notes-none

#41379 ambient: ca: Implement node authorization
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/features/pilot.go
  pkg/security/security.go
  pkg/test/util/assert/assert.go
  security/pkg/k8s/tokenreview/k8sauthn.go
  security/pkg/k8s/tokenreview/k8sauthn_test.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
  security/pkg/server/ca/node_auth.go
  security/pkg/server/ca/node_auth_test.go
  security/pkg/server/ca/server.go
  tests/fuzz/security_fuzzer.go
Labels: size/XL, release-notes-none

#41410 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#41412 Update BASE_VERSION to 1.13-2022-10-13T19-01-05
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41413 Update BASE_VERSION to 1.14-2022-10-13T19-02-21
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41409 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41411 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41186 Make endpointslice fuzzing work
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/fuzz_test.go
Labels: size/S, release-notes-none

#41392 tf: cache open api schema fetch
  pkg/kube/client.go
Labels: size/XS, release-notes-none, cherrypick/release-1.15

#41164 Overwrite default tag instead of remove in non-revisioned installation
  operator/cmd/mesh/install.go
Labels: area/environments, size/XS, release-notes-none

#41371 sets: allow unordered types
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pilot/cmd/pilot-discovery/app/options.go
  pilot/pkg/config/kube/gateway/context.go
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/proxy_view.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/telemetry.go
  pilot/pkg/networking/core/v1alpha3/listenertest/match.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/serviceregistry/util/workloadinstances/index.go
  pilot/pkg/xds/cds_test.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/deltatest.go
  pilot/pkg/xds/eds_test.go
  pkg/config/mesh/mesh.go
  pkg/config/validation/validation.go
  pkg/kube/namespace/filter.go
  pkg/test/framework/components/echo/config/builder.go
  pkg/test/framework/components/echo/namespacedname.go
  pkg/util/sets/set.go
  pkg/util/sets/set_test.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/caclient/providers/google-cas/client.go
  tests/integration/pilot/common/routing.go
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/filter/filter.go
  tools/docker-builder/crane.go
  tools/docker-builder/docker.go
  tools/docker-builder/main.go
  tools/docker-builder/types.go
Labels: size/L, release-notes-none

#41419 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41359 change the library from net to netip for integration framework components
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/ingress/interface.go
  pkg/test/framework/components/istio/istio.go
  pkg/test/framework/components/istio/kube.go
  pkg/test/framework/components/istio/util.go
Labels: size/M, release-notes-none

#41398 partially replace the net by the netip for istioctl san istio-iptables
  istioctl/cmd/precheck.go
  istioctl/cmd/workload.go
  pilot/cmd/pilot-agent/app/cmd.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pkg/config/validation/validation.go
  security/pkg/pki/util/san.go
  security/pkg/pki/util/san_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/cmd/root_test.go
Labels: size/M, release-notes-none

#41429 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41428 Scope envoy filters for CDS/RDS
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/envoyfilter_test.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: size/L, release-notes-none

#41422 refactor: replace the net.IP by the netip.Addr for the pkg/dns
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
  pkg/dns/server/name_table.go
  pkg/istio-agent/agent.go
  pkg/util/net/ip.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/cmd/root.go
Labels: size/L, release-notes-none

#41418 validate tls ciphersuite below 1.2 version
  pkg/config/validation/validation.go
Labels: size/XS, release-notes-none

#41420 rm legacy readmes
  pilot/pkg/xds/README.md
Labels: release-notes-none

#40729 stats: correct response_code regex
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  releasenotes/notes/40729.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: area/extensions and telemetry, size/L

#41435 Failover validation (#41272)
  pkg/config/mesh/mesh.go
  pkg/config/mesh/mesh_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/failover-validation.yaml
Labels: size/L

#41438 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#41433 [release-1.15] validate tls ciphersuite below 1.2 version
  pkg/config/validation/validation.go
Labels: size/XS, release-notes-none

#41436 Failover validation (#41272)
  pkg/config/mesh/mesh.go
  pkg/config/mesh/mesh_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/failover-validation.yaml
Labels: size/L

#41439 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41442 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41444 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41426 ambient: no checkAmbient if pod is in excluded namespaces
  cni/pkg/plugin/plugin.go
Labels: ok-to-test, size/XS, release-notes-none, area/ambient

#41448 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41451 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41327 refactor: use netip.ParsePrefix replace the net.ParseCIDR
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/security/authz/matcher/cidr.go
  pilot/pkg/security/authz/matcher/cidr_test.go
  pilot/pkg/security/authz/model/generator.go
  tests/fuzz/pilot_security_fuzzer.go
Labels: size/L, release-notes-none

#40995 `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`: don't push xds when unrelated services are updated
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/xds/proxy_dependencies.go
  pilot/pkg/xds/proxy_dependencies_test.go
Labels: area/networking, size/L, release-notes-none

#41456 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41461 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41018 Create inbound listener from both sidecar and service
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  releasenotes/notes/41018.yaml
Labels: area/networking, ok-to-test, size/L

#41425 fixed bug for port forward to support ipv4 and ipv6
  pkg/kube/client.go
  pkg/test/kube/dump.go
  pkg/wasm/cache_test.go
  releasenotes/notes/41425.yaml
Labels: size/S, release-notes-none

#41373 [release-1.14] Add missing unit test for #40165
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
Labels: size/M, release-notes-none

#41198 create istio-ca-root-cert cm in namespaces selected by discoverySelectors
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pkg/kube/namespace/filter.go
  releasenotes/notes/scope-root-ca-configmap.yaml
Labels: area/networking, size/L

#41330 istioctl: check revision exists before uninstalling
  istioctl/cmd/injector-list.go
  istioctl/cmd/revision.go
  istioctl/pkg/tag/revision.go
  operator/cmd/mesh/uninstall.go
  releasenotes/notes/41330.yaml
  tests/integration/pilot/revisioncmd/revision_view_test.go
  tests/integration/pilot/revisions/uninstall_test.go
Labels: area/environments, area/user experience, size/L

#41463 Remove unused secret creation step in egress gateway tls test
  tests/integration/security/egress_gateway_origination_test.go
Labels: area/test and release, size/XS, release-notes-none

#41361 Fix `istioctl proxy-config endpoint` command failed for ztunnel pods
  istioctl/pkg/writer/envoy/clusters/clusters.go
Labels: size/XS, release-notes-none

#41446 Added dual stack support for setting up kind cluster
  samples/kind-lb/README.md
  samples/kind-lb/setupkind.sh
Labels: area/test and release, size/L, release-notes-none

#41467 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#41468 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#41421 ambient: split ztunnel daemonset to its own chart
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  manifests/charts/ztunnel/.helmignore
  manifests/charts/ztunnel/Chart.yaml
  manifests/charts/ztunnel/templates/daemonset.yaml
  manifests/charts/ztunnel/templates/rbac.yaml
  manifests/charts/ztunnel/values.yaml
  manifests/profiles/ambient.yaml
  manifests/profiles/default.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot.tar.gz
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/helm_values_enablement.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ingressgateway_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/install_package_path.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_disable_tracing.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.txt
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/cmd/mesh/testdata/profile-dump/output/config_path.txt
  operator/cmd/mesh/testdata/profile-dump/output/config_path.yaml
  operator/pkg/component/component.go
  operator/pkg/component/ztunnel.go
  operator/pkg/controlplane/control_plane_test.go
  operator/pkg/name/name.go
  operator/pkg/translate/translate.go
  operator/pkg/translate/translate_value.go
  operator/pkg/util/merge_iop.go
Labels: size/XXL, area/ambient

#41466 Automated branching step 1
  docker/Dockerfile.distroless
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#41472 pilot: return the 'InvalidArgument' error code when parsing the node metadata fail
  pilot/pkg/xds/ads.go
Labels: release-notes-none

#41478 [release-1.13] pilot: return the 'InvalidArgument' error code when parsing the node metadata fail
  pilot/pkg/xds/ads.go
Labels: size/XS, release-notes-none

#41480 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41476 [release-1.15] pilot: return the 'InvalidArgument' error code when parsing the node metadata fail
  pilot/pkg/xds/ads.go
Labels: size/XS, release-notes-none

#41477 [release-1.14] pilot: return the 'InvalidArgument' error code when parsing the node metadata fail
  pilot/pkg/xds/ads.go
Labels: size/XS, release-notes-none

#41484 istioctl experimental: change the short of the precheck subcommand to start with uppercase
  istioctl/cmd/precheck.go
Labels: ok-to-test, size/XS, release-notes-none

#41485 Make use of rev label in some files
  tests/integration/helm/upgrade/util.go
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: size/XS, release-notes-none

#41464 [release-1.15] fixed bug for port forward to support ipv4 and ipv6
  pkg/kube/client.go
  pkg/test/kube/dump.go
  pkg/wasm/cache_test.go
  releasenotes/notes/41425.yaml
Labels: size/S, release-notes-none

#41492 pilot: avoid spam from unset CIDR
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/util/util.go
Labels: size/S, release-notes-none

#41474 telemetry: reorg e2e tests
  pkg/test/framework/features/allowlist.txt
  tests/integration/telemetry/api/registry_setup_test.go
  tests/integration/telemetry/api/setup_test.go
  tests/integration/telemetry/api/stats_test.go
  tests/integration/telemetry/api/stats_wasm_filter_test.go
  tests/integration/telemetry/api/testdata/bad-filter.yaml
  tests/integration/telemetry/api/testdata/registry-secret.yaml
  tests/integration/telemetry/api/testdata/wasm-filter.yaml
  tests/integration/telemetry/api/wasmplugin_test.go
  tests/integration/telemetry/envoyfilter/wasm/bad_wasm_filter_test.go
  tests/integration/telemetry/envoyfilter/wasm/stats_wasm_filter_test.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/policy/helper_test.go
  tests/integration/telemetry/policy/traffic_allow_any_test.go
  tests/integration/telemetry/policy/traffic_registry_only_test.go
Labels: area/extensions and telemetry, size/L, release-notes-none

#41502 Update BASE_VERSION to 1.14-2022-10-18T19-02-23
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41500 Update BASE_VERSION to 1.15-2022-10-18T19-01-15
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41498 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41391 Initial HBONE for sidecars and ingress (for master)
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  manifests/profiles/ambient.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/model/context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/util/protoconv/protoconv.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/filters/filters.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/XL, release-notes-none

#41497 envoy: use standard logging format
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: size/XS, release-notes-none

#41488 Use contants string instead of string literals as cacerts secrect name
  pilot/pkg/bootstrap/istio_ca.go
  security/pkg/pki/ca/ca.go
Labels: ok-to-test, size/XS, release-notes-none

#41496 delta: ensure proper resource handling on reconnect
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/fake.go
  pilot/test/xdstest/extract.go
Labels: size/L, release-notes-none

#41505 telemetry: add e2e tests for accesslogging filter
  tests/integration/telemetry/api/accesslogs_test.go
  tests/integration/telemetry/api/setup_test.go
  tests/integration/telemetry/api/testdata/accesslog-filter.yaml
Labels: size/M, release-notes-none

#41501 Update BASE_VERSION to 1.13-2022-10-18T19-02-31
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41499 Update BASE_VERSION to master-2022-10-18T19-01-10
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#41511 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41487 istioctl experimental: modify the example display format of 'istioctl x check-inject -h'
  istioctl/cmd/checkinject.go
Labels: ok-to-test, size/S, release-notes-none

#41513 Prevent hardcoding filter name from HBONE
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
Labels: size/S, release-notes-none

#41518 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#41459 handle http context in xfcc authenticator
  pkg/security/security.go
  security/pkg/server/ca/authenticate/xfcc_authenticator.go
  security/pkg/server/ca/authenticate/xfcc_authenticator_test.go
Labels: size/L, release-notes-none

#41509 minor comment improvements
  pilot/pkg/xds/delta.go
Labels: size/XS, release-notes-none

#41520 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#41506 update commenst for cacerts secret
  security/pkg/pki/ca/ca.go
Labels: size/XS, release-notes-none
