Repository istio/istio, pull requests merged in 2022-03, with the labels that each got.

#37598 Disable Envoy retries in tests
  tests/integration/base.yaml
Labels: size/XS, release-notes-none

#37599 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37549 [TF] Removing RBAC test utiities
  pkg/http/headers/builder.go
  pkg/http/headers/wellknown.go
  pkg/test/echo/check/checkers.go
  pkg/test/echo/common/util.go
  pkg/test/echo/response.go
  pkg/test/util/file/file.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/ingress_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/normalization_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/util/authn/authn_util.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/rbac_util/util.go
  tests/integration/security/util/scheck/checkers.go
Labels: area/test and release, size/XXL, release-notes-none

#36582 Support REPLACE for virtual host in envoy filter
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go
  releasenotes/notes/replace-virtualhost.yaml
Labels: area/networking, size/L

#37540 Set upstream max tls version to TLS 1.3
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  releasenotes/notes/upstream-tls-version.yaml
Labels: area/networking, size/M, release-notes-none

#37612 Clone catch all vhost to prevent it from being mutated
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: size/XS, release-notes-none, cherrypick/release-1.12, cherrypick/release-1.13

#37614 [release-1.13] Clone catch all vhost to prevent it from being mutated
  pilot/pkg/networking/core/v1alpha3/httproute.go
Labels: size/XS, release-notes-none

#37578 fix a bug that cache entries were never updated
  pkg/wasm/cache.go
  pkg/wasm/cache_test.go
Labels: ok-to-test, size/S, release-notes-none

#37603 Pilot debounce: log reason when there is no config
  pilot/pkg/xds/discovery.go
Labels: size/S, release-notes-none

#37597 Reduce test duration for google mock CA
  security/pkg/nodeagent/caclient/providers/google-cas/mock/ca_mock.go
  security/pkg/nodeagent/caclient/providers/google/mock/ca_mock.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#37615 increase test timeout for ads push scoping
  pilot/pkg/xds/ads_test.go
Labels: area/networking, size/XS, release-notes-none

#37618 [release-1.12] deepcopy before merging port (#37536)
  pilot/pkg/model/sidecar.go
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: area/networking, size/S, release-notes-none

#37627 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37632 [release-1.13] fix a bug that cache entries were never updated
  pkg/wasm/cache.go
  pkg/wasm/cache_test.go
Labels: size/S, release-notes-none

#37628 [TF] Refactoring ConfigManager interface
  pkg/test/framework/components/echo/echoboot/echoboot.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/istio/eastwest.go
  pkg/test/framework/components/istio/operator.go
  pkg/test/framework/components/istio/util.go
  pkg/test/framework/components/opentelemetry/kube.go
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/components/zipkin/kube.go
  pkg/test/framework/config.go
  pkg/test/framework/resource/context.go
  pkg/test/util/tmpl/evaluate.go
  tests/integration/helm/util.go
  tests/integration/pilot/analysis/analysis_test.go
  tests/integration/pilot/cni/cniversionskew_test.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/cross_revision_test.go
  tests/integration/pilot/grpc_probe_test.go
  tests/integration/pilot/gw_topology_test.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/locality_test.go
  tests/integration/pilot/mcs/common/common.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/multicluster_test.go
  tests/integration/pilot/proxyconfig/proxyconfig_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/multi_root_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/fuzz/fuzz_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/mtls_healthcheck_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/util/reachability/context.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
  tests/integration/telemetry/stackdriver/vm/vm_test.go
  tests/integration/telemetry/stats/prometheus/api/stats_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
Labels: area/test and release, size/XL, release-notes-none

#37636 [TF] Fixing telemetry test nesting
  tests/integration/telemetry/constants.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_allow_any_test.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_registry_only_test.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/vm/vm_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/istioctl_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/stats_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/stats/prometheus/util_prometheus.go
  tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_tcp_filter_test.go
  tests/integration/telemetry/tracing/opencensusagent/tracing_test.go
  tests/integration/telemetry/tracing/tracing.go
  tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
Labels: size/L, release-notes-none

#37639 Make include outbound port work with CNI.
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin_test.go
  cni/pkg/plugin/redirect.go
  releasenotes/notes/37637.yaml
Labels: size/M, cherrypick/release-1.12, cherrypick/release-1.13

#37640 Speed up TestK8sSignWithMeshConfig
  security/pkg/k8s/chiron/utils.go
  security/pkg/pki/ra/k8s_ra_test.go
  security/pkg/pki/ra/leak_test.go
Labels: size/L, release-notes-none

#37644 [release-1.13] Make include outbound port work with CNI.
  cni/pkg/plugin/iptables.go
  cni/pkg/plugin/plugin_test.go
  cni/pkg/plugin/redirect.go
  releasenotes/notes/37637.yaml
Labels: size/M, release-notes-none

#37591 Restrict another hub to prevent accidents
  tools/docker-builder/main.go
Labels: size/XS, release-notes-none

#37650 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37566 Use image's digest instead of binary's checksum
  pkg/wasm/cache.go
  pkg/wasm/cache_test.go
  pkg/wasm/imagefetcher.go
  pkg/wasm/imagefetcher_test.go
Labels: ok-to-test, size/L, release-notes-none

#37619 [release-1.13] Remove cluster handlers from aggregate controller when cluster delete…
  pilot/pkg/model/controller.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/mock/discovery.go
Labels: size/L, release-notes-none, cherrypick/release-1.13

#37643 [release-1.12] Make include outbound port work with CNI.
  cni/pkg/plugin/iptables.go
  cni/pkg/plugin/plugin_test.go
  cni/pkg/plugin/redirect.go
  releasenotes/notes/37637.yaml
Labels: size/M, release-notes-none

#37624 Fix: mcs incorrectly deleted
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
Labels: size/M, release-notes-none

#37559 skip active connections check when downstream cx stats are not available
  pkg/envoy/agent.go
  pkg/envoy/agent_test.go
Labels: size/S, release-notes-none

#37616 optimize: auto allocate addresses only when services updated
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/store.go
  pilot/pkg/serviceregistry/serviceentry/store_test.go
Labels: area/networking, size/M, release-notes-none

#37653 update DerivedGauge
  go.mod
  go.sum
  pilot/pkg/bootstrap/monitoring.go
Labels: area/extensions and telemetry, size/S, release-notes-none

#37658 Update BASE_VERSION to 1.12-2022-03-02T14-52-36
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#37662 Log remaining names in operator test
  tests/integration/operator/switch_cr_test.go
Labels: size/XS, release-notes-none

#37655 Remove default caBundle value from Chart to allow GitOps
  manifests/charts/default/templates/mutatingwebhook.yaml
  manifests/charts/default/templates/validatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/templates/revision-tags.yaml
  manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/templates/validatingwebhookconfiguration.yaml
  operator/cmd/mesh/manifest-generate_test.go
  releasenotes/notes/37737.yaml
Labels: area/environments, ok-to-test, size/S

#37641 [release-1.12] fix a bug that cache entries were never updated (#37578)
  pkg/wasm/cache.go
  pkg/wasm/cache_test.go
Labels: release-notes-none

#37670 gateway: avoid recreating Deployment on each kubectl apply
  pilot/pkg/config/kube/gateway/templates.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/templates/service.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.13

#37358 [TF] Remove security Checker
  pkg/http/headers/wellknown.go
  pkg/test/echo/check/checkers.go
  tests/integration/security/ca_custom_root/multi_root_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/external_ca/reachability_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/util/authn/authn_util.go
  tests/integration/security/util/connection/checker.go
  tests/integration/security/util/reachability/context.go
  tests/integration/security/util/scheck/checkers.go
Labels: size/XXL, release-notes-none

#37668 Remove duplicate test case
  tests/integration/security/util/reachability/context.go
Labels: size/XS, release-notes-none

#37673 [release-1.13] gateway: avoid recreating Deployment on each kubectl apply
  pilot/pkg/config/kube/gateway/templates.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/templates/service.yaml
Labels: size/S, release-notes-none

#37669 Update --no-clobber to not check existence of tag `latest`
  tools/docker-builder/main.go
Labels: area/test and release, size/XS, release-notes-none

#37620 [release-1.13] Revert #36697 auto allocate ip while getting services from the store
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  pilot/pkg/serviceregistry/serviceentry/store.go
Labels: area/networking, size/M, release-notes-none

#37676 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37372 pilot-agent add cert expiry metric
  security/pkg/nodeagent/cache/monitoring.go
  security/pkg/nodeagent/cache/secretcache.go
Labels: area/extensions and telemetry, size/S, release-notes-none

#37646 retry: fix default backoff
  pkg/test/util/retry/retry.go
Labels: size/XS, release-notes-none

#37514 Make all telemetry tests support multiple clusters
  pkg/test/framework/components/echo/kube/deployment.go
  tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
Labels: area/test and release, size/XS, release-notes-none

#37678 build default transport socketmatch each time instead of using shared
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: area/networking, size/S, release-notes-none

#37683 update metric description
  security/pkg/nodeagent/cache/monitoring.go
Labels: size/XS, release-notes-none

#37604 Pilot: store latest push instead of global
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/discovery.go
Labels: size/M, release-notes-none

#37672 mitigate flaky tests temporarily
  tests/integration/security/util/reachability/context.go
Labels: size/XS, release-notes-none

#37694 Automator: update istio/api@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37698 [release-1.12] gateway: avoid recreating Deployment on each kubectl apply
  pilot/pkg/config/kube/gateway/templates.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/templates/service.yaml
Labels: size/S, release-notes-none

#37699 debuggen: check verified identity presence explicitly
  pilot/pkg/xds/debuggen.go
Labels: size/XS, release-notes-none, cherrypick/release-1.11, cherrypick/release-1.12

#37697 Fix --no-clobber ignoring of `latest` images
  tools/docker-builder/main.go
Labels: area/test and release, size/XS, release-notes-none

#37706 Automator: update istio/api@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37688 Add script to build kind node image
  tools/build-kind-image.sh
Labels: size/M, release-notes-none

#37695 Automator: update istio/client-go@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#37690 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#37659 Improve gateway chart docs
  manifests/charts/gateway/README.md
  manifests/charts/gateway/templates/deployment.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.13

#37713 Automator: update common-files@release-1.13 in istio/istio@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37692 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37715 Automator: update common-files@release-1.12 in istio/istio@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37558 [release-1.13] [Bug Fix] no mutating service when merging port
  pilot/pkg/model/sidecar.go
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: size/S, release-notes-none

#37712 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37718 Automator: update common-files@release-1.11 in istio/istio@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37716 Automator: update istio/client-go@release-1.12 dependency in istio/istio@release-1.12
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37707 [TF] Move retry options to CallOptions
  pkg/test/framework/components/echo/calloptions.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/echotest/fake.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/staticvm/instance.go
  pkg/test/framework/components/istio/ingress.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/locality_test.go
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/multicluster_test.go
  tests/integration/pilot/original_src_addr_test.go
  tests/integration/pilot/revisions/revisions_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/multi_root_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/external_ca/reachability_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/normalization_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/util/cert/cert.go
  tests/integration/security/util/reachability/context.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/vm/vm_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/tracing/tracing.go
  tests/util/sanitycheck/sanity_check.go
Labels: area/test and release, size/L, release-notes-none

#37717 Automator: update istio/client-go@release-1.13 dependency in istio/istio@release-1.13
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37720 Automator: update istio/client-go@release-1.11 dependency in istio/istio@release-1.11
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37714 [release-1.13] Improve gateway chart docs
  manifests/charts/gateway/README.md
  manifests/charts/gateway/templates/deployment.yaml
Labels: size/S, release-notes-none

#37703 [release-1.11] Bump base image
  Makefile.core.mk
Labels: size/XS, release-notes-none

#37704 [release-1.11] debuggen: check verified identity presence explicitly
  pilot/pkg/xds/debuggen.go
Labels: size/XS, release-notes-none

#37719 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#36713 Fix describe po not finding vs when protocol is https
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/testdata/describe/http_config.json
  istioctl/cmd/testdata/describe/tls_config.json
  releasenotes/notes/36713.yaml
Labels: area/user experience, size/L

#37727 [TF] Rename echoboot to deployment.
  pkg/test/framework/components/echo/caller.go
  pkg/test/framework/components/echo/deployment/builder.go
  pkg/test/framework/components/echo/deployment/flags.go
  pkg/test/framework/components/echo/echo.go
  pkg/test/framework/components/echo/echotest/fake.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  tests/integration/pilot/cni_race_test.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/cross_revision_test.go
  tests/integration/pilot/grpc_probe_test.go
  tests/integration/pilot/istioctl_test.go
  tests/integration/pilot/mcs/common/common.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/proxyconfig/proxyconfig_test.go
  tests/integration/pilot/revisioncmd/revision_view_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/pilot/revisions/revision_tag_test.go
  tests/integration/pilot/revisions/revisions_test.go
  tests/integration/pilot/tcp_probe_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/ecc_signature_algorithm/main_test.go
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/mtls_healthcheck_test.go
  tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/util/framework.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/tracing/tracing.go
  tests/util/sanitycheck/sanity_check.go
Labels: area/test and release, size/L, release-notes-none

#37708 TelemetryAPI: Disable Stackdriver logging if not configured (by default, or otherwise)
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  releasenotes/notes/37708.yaml
Labels: area/user experience, size/S, cherrypick/release-1.12, cherrypick/release-1.13

#37735 [release-1.12] UPDATE_BRANCH=release-1.12 ./bin/update_deps.sh
  go.mod
  go.sum
  istio.deps
Labels: size/S, release-notes-none

#37736 [release-1.13] UPDATE_BRANCH=release-1.13 ./bin/update_deps.sh
  go.mod
  go.sum
  istio.deps
Labels: size/S, release-notes-none

#37734 [release-1.11] UPDATE_BRANCH=release-1.11 ./bin/update_deps.sh
  go.mod
  go.sum
  istio.deps
Labels: size/S, release-notes-none

#37737 UPDATE_BRANCH=master ./bin/update_deps.sh
  go.mod
  go.sum
  istio.deps
Labels: size/S, release-notes-none

#37742 [release-1.13] TelemetryAPI: Disable Stackdriver logging if not configured (by default, or otherwise)
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  releasenotes/notes/37708.yaml
Labels: size/S, release-notes-none

#37743 Bump 1.11 base image
  Makefile.core.mk
Labels: size/XS, release-notes-none

#37745 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37746 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#37740 Fix issue with helm tags rendering
  manifests/charts/istio-control/istio-discovery/templates/revision-tags.yaml
Labels: size/M, release-notes-none

#37750 Automator: update proxy@release-1.11 in istio/istio@release-1.11
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37752 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37722 check key and cert are valid before sending to Envoy
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: size/S, release-notes-none

#37730 gateway: fix error log when deleting a Gateway
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
Labels: area/networking, ok-to-test, size/XS, release-notes-none

#37760 Update BASE_VERSION to master-2022-03-05T19-01-04
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#37738 Switch protobuf compiling to `buf`
  Makefile.core.mk
  buf.gen.yaml
  operator/operator.mk
  pkg/dns/proto/nds.mk
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/test/echo/proto/echo_grpc.pb.go
  tools/proto/buf.gogo.yaml
  tools/proto/buf.golang.yaml
  tools/proto/buf.yaml
  tools/proto/proto.mk
Labels: size/M, release-notes-none

#37747 Add tests for virtual services
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pilot/test/xdstest/extract.go
Labels: size/L, release-notes-none

#37759 Revert "Pilot: store latest push instead of global (#37604)"
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/discovery.go
  tests/integration/pilot/multicluster_test.go
Labels: size/M, release-notes-none

#37761 Standardize run commands for integ tests
  tests/integration/tests.mk
Labels: size/S, release-notes-none

#37763 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37755 Automator: update proxy@release-1.12 in istio/istio@release-1.12
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37749 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37768 remove unused functions
  pkg/istio-agent/xds_proxy.go
Labels: size/M, release-notes-none

#37774 Improve config store error return
  pilot/pkg/config/file/store.go
Labels: area/networking, size/XS, release-notes-none

#37733 telemetry api: allow default json format for envoy file logger
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  releasenotes/notes/default-json-logging-envoy-telemetry-api.yaml
Labels: size/M, cherrypick/release-1.13

#37754 [release-1.13] Fix describe po not finding vs when protocol is https
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/testdata/describe/http_config.json
  istioctl/cmd/testdata/describe/tls_config.json
  releasenotes/notes/36713.yaml
Labels: size/L, release-notes-none

#37782 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37775 Clean up unused code
  pkg/bootstrap/platform/platform.go
Labels: size/XS, release-notes-none

#37777 Make AuthorizationPolicy parsing more robust
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
Labels: size/S, release-notes-none, cherrypick/release-1.12, cherrypick/release-1.13

#37784 go dependencies: bump protobuf library
  go.mod
  go.sum
Labels: size/XS, release-notes-none, cherrypick/release-1.11, cherrypick/release-1.12, cherrypick/release-1.13

#37787 [release-1.13] Make AuthorizationPolicy parsing more robust
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
Labels: size/S, release-notes-none

#37785 pilot: limit reads from untrusted inputs
  pkg/kube/inject/webhook.go
  pkg/kube/util.go
  pkg/webhooks/validation/server/server.go
Labels: size/M, release-notes-none, cherrypick/release-1.12, cherrypick/release-1.13

#37783 Cleanup stale file
  prof
Labels: size/XS, release-notes-none

#37792 [release-1.13] pilot: limit reads from untrusted inputs
  pkg/kube/inject/webhook.go
  pkg/kube/util.go
  pkg/webhooks/validation/server/server.go
Labels: size/M, release-notes-none

#37799 go dependencies: bump protobuf library
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#37780 Add new `go-compile-verbose` tool to help debug build times
  tools/go-compile-verbose
Labels: size/M, release-notes-none

#37804 [release-1.11] pilot: limit reads from untrusted inputs
  pkg/kube/inject/webhook.go
  pkg/kube/util.go
  pkg/webhooks/validation/server/server.go
Labels: size/M, release-notes-none

#37796 go dependencies: bump protobuf library
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#37807 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37791 [release-1.12] pilot: limit reads from untrusted inputs
  pkg/kube/inject/webhook.go
  pkg/kube/util.go
  pkg/webhooks/validation/server/server.go
Labels: size/M, release-notes-none

#37808 [TF] Cleanup echo Port
  pkg/config/protocol/instance.go
  pkg/test/framework/components/echo/calloptions.go
  pkg/test/framework/components/echo/common/call.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/istio/ingress.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/locality_test.go
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/multicluster_test.go
  tests/integration/pilot/original_src_addr_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/pilot/revisions/revisions_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/ca_custom_root/multi_root_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/external_ca/reachability_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/normalization_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/util/cert/cert.go
  tests/integration/security/util/reachability/context.go
  tests/integration/security/util/scheck/checkers.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/policy/envoy_ratelimit_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/vm/vm_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/tracing/tracing.go
  tests/util/sanitycheck/sanity_check.go
Labels: area/test and release, size/XXL, release-notes-none

#37705 [release-1.12] debuggen: check verified identity presence explicitly
  pilot/pkg/xds/debuggen.go
Labels: size/XS, release-notes-none

#37786 [release-1.12] Make AuthorizationPolicy parsing more robust
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
Labels: size/S, release-notes-none

#37076 add RBAC support to proxyless gRPC
  pilot/pkg/networking/grpcgen/grpcecho_test.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/grpcgen/testdata/xds_bootstrap.json
  pilot/pkg/serviceregistry/memory/discovery.go
  pkg/test/echo/server/endpoint/grpc.go
Labels: size/XL, release-notes-none, cherrypick/release-1.13

#37675 Enable serviceentry wles cross clusters
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
Labels: area/networking, size/XS, release-notes-none

#37797 [release-1.12] go dependencies: bump protobuf library
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#37778 [release-1.13] telemetry api: allow default json format for envoy file logger
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  releasenotes/notes/default-json-logging-envoy-telemetry-api.yaml
Labels: size/M, release-notes-none

#37811 Do not waste time compressing VM packages in tests
  prow/integ-suite-kind.sh
  tools/packaging/packaging.mk
Labels: size/S, release-notes-none

#37810 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#37781 [TF] Flexible echo CallOptions.To
  pkg/test/framework/components/cluster/cluster.go
  pkg/test/framework/components/echo/calloptions.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/echotest/run.go
  pkg/test/framework/components/echo/echotest/setup.go
  pkg/test/framework/components/echo/instance.go
  pkg/test/framework/components/echo/instances.go
  pkg/test/framework/components/echo/kube/instance.go
  pkg/test/framework/components/echo/services.go
  pkg/test/framework/components/echo/staticvm/instance.go
  pkg/test/framework/components/echo/workload.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/ingress_test.go
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
  tests/integration/pilot/mirror_test.go
  tests/integration/pilot/multi_version_revision_test.go
  tests/integration/pilot/multicluster_test.go
  tests/integration/pilot/original_src_addr_test.go
  tests/integration/pilot/revisioned_upgrade_test.go
  tests/integration/pilot/revisions/revisions_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/multi_root_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/external_ca/reachability_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/normalization_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/sds_ingress/ingress_test.go
  tests/integration/security/sds_ingress/util/util.go
  tests/integration/security/testdata/authz/v1beta1-conditions.yaml.tmpl
  tests/integration/security/util/cert/cert.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/reachability/context.go
  tests/integration/security/util/scheck/checkers.go
  tests/integration/telemetry/outboundtrafficpolicy/helper.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/tracing/tracing.go
Labels: area/test and release, size/XXL, release-notes-none

#37820 Automator: update proxy@release-1.11 in istio/istio@release-1.11
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37800 Pilot: store latest push instead of global
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/xds_cache.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/discovery.go
  tests/integration/pilot/multicluster_test.go
Labels: size/M, release-notes-none

#37819 add otel provider in demo profile
  manifests/profiles/demo.yaml
  samples/open-telemetry/README.md
Labels: kind/docs, size/M, release-notes-none

#37827 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37823 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37833 minor dns fix and additional tests
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
Labels: area/networking, size/S, release-notes-none

#37302 [TF] Removing some multi-cluster specific logic
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/ingress_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/external_ca/reachability_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/util/reachability/context.go
Labels: area/test and release, size/L, release-notes-none

#37826 fix test file secrets flake
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: area/security, size/S, release-notes-none

#37817 add dual stack support for echo server [TF]
  pkg/test/echo/server/endpoint/util.go
  pkg/test/echo/server/instance.go
Labels: area/test and release, area/networking, ok-to-test, size/M, release-notes-none

#37839 Synchronize MCS even handling
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
Labels: size/M, release-notes-none

#37837 Move managed gateway our of loop
  tests/integration/pilot/ingress_test.go
Labels: size/M, release-notes-none

#37843 Automator: update proxy@release-1.13 in istio/istio@release-1.13
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37842 Automator: update proxy@release-1.12 in istio/istio@release-1.12
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#37845 fix nit
  samples/open-telemetry/README.md
Labels: kind/docs, size/XS, release-notes-none

#37846 [release-1.13] add otel provider in demo profile
  manifests/profiles/demo.yaml
  samples/open-telemetry/README.md
Labels: size/M, release-notes-none

#37849 Fixed metallb master branch issue
  samples/kind-lb/setupkind.sh
Labels: area/user experience, size/XS, release-notes-none

#37852 fix data race in dns
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
Labels: area/networking, size/S, release-notes-none

#37851 [release-1.13] fix nit
  samples/open-telemetry/README.md
Labels: size/XS, release-notes-none

#37863 vm support: make default file paths in `istio-start.sh` relative
  tools/packaging/common/istio-start.sh
Labels: area/environments, size/S, release-notes-none

#37866 bootstrap: fix outdated config in `gcp_envoy_bootstrap.json`
  tools/packaging/common/gcp_envoy_bootstrap.json
Labels: area/environments, size/S, release-notes-none

#37869 bootstrap: make file path `/var/run/secrets/tokens/istio-token` relative
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  tools/packaging/common/envoy_bootstrap.json
  tools/packaging/common/gcp_envoy_bootstrap.json
Labels: area/environments, size/S, release-notes-none

#37840 Bump to grpc v1.45
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#37818 Speed up some of the slowest pilot tests
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/model/network_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
  pilot/pkg/trustbundle/trustbundle.go
  pilot/pkg/trustbundle/trustbundle_test.go
  pkg/wasm/cache_test.go
  pkg/wasm/httpfetcher.go
  pkg/wasm/httpfetcher_test.go
  security/pkg/k8s/chiron/utils.go
  security/pkg/k8s/chiron/utils_test.go
  security/pkg/pki/ra/k8s_ra.go
Labels: size/L, release-notes-none

#37870 [TF] Cleanup echo matchers
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/echotest/echotest.go
  pkg/test/framework/components/echo/echotest/filters.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/instances.go
  pkg/test/framework/components/echo/match/matcher.go
  pkg/test/framework/components/echo/match/matchers.go
  pkg/test/framework/components/echo/matcher.go
  tests/integration/pilot/common/apps.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
  tests/integration/pilot/mcs/autoexport/autoexport_test.go
  tests/integration/pilot/mcs/discoverability/discoverability_test.go
  tests/integration/pilot/revisions/revisions_test.go
  tests/integration/pilot/vm_test.go
  tests/integration/security/authorization_test.go
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/ca_custom_root/multi_root_test.go
  tests/integration/security/ca_custom_root/secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
  tests/integration/security/ca_custom_root/trust_domain_validation_test.go
  tests/integration/security/ecc_signature_algorithm/main_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/external_ca/reachability_test.go
  tests/integration/security/https_jwt/https_jwt_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/mtls_first_party_jwt/strict_test.go
  tests/integration/security/mtlsk8sca/strict_test.go
  tests/integration/security/pass_through_filter_chain_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/util/framework.go
  tests/integration/security/util/reachability/context.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/stats/prometheus/stats.go
  tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
  tests/integration/telemetry/tracing/tracing.go
Labels: area/test and release, size/XL, release-notes-none

#37586 Add Warning for IPs in SNI Hosts in TLSRoute.Match criteria
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/ip-sni-hosts.yaml
Labels: area/networking, size/M

#37824 Fix TestEdsCache flake
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Labels: area/networking, size/M, release-notes-none

#37873 get aws information from link local address
  go.mod
  go.sum
  licenses/github.com/aws/aws-sdk-go/LICENSE.txt
  licenses/github.com/aws/aws-sdk-go/internal/sync/singleflight/LICENSE
  licenses/github.com/jmespath/go-jmespath/LICENSE
  pkg/bootstrap/platform/aws.go
  pkg/bootstrap/platform/aws_test.go
Labels: area/networking, size/L, release-notes-none

#37874 support ipv6 for getting aws information
  pilot/cmd/pilot-agent/options/agent.go
  pkg/bootstrap/platform/aws.go
  pkg/bootstrap/platform/aws_test.go
  pkg/bootstrap/platform/discovery.go
Labels: area/networking, size/M, release-notes-none

#37861 Cleanup stale protobuf gen stuff
  buf.gen.yaml
  operator/operator.mk
Labels: size/M, release-notes-none
