Repository istio/istio, pull requests merged in 2023-12, with the labels that each got.

#48100 ambient: fix a regression in pod update handler
  cni/pkg/ambient/informers.go
Labels: size/XS, release-notes-none, area/ambient

#48106 istioctl: prune IOP
  operator/pkg/helmreconciler/prune.go
Labels: size/S, release-notes-none

#48123 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#48118 Prometheus addon updates
  manifests/addons/gen.sh
  manifests/addons/values-prometheus.yaml
  samples/addons/extras/prometheus_vm.yaml
  samples/addons/extras/prometheus_vm_tls.yaml
  samples/addons/prometheus.yaml
Labels: size/XXL, release-notes-none

#48101 Cleanup authn v1beta1 policyApplier
  istioctl/pkg/describe/describe.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/security/authn/factory.go
  pilot/pkg/security/authn/factory/factory.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/policy_applier_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/xds/endpoints/mtls_checker.go
Labels: size/XXL, release-notes-none

#48111 Revert "Fix internal-debug syncz not working with agent, and add support for debug type `config_dump `"
  istioctl/pkg/internaldebug/internal-debug.go
  tests/integration/pilot/piggyback_test.go
Labels: size/S, release-notes-none

#48129 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48131 operator: bump golden chart tests
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/manifest_shared_test.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot.tar.gz
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/helm_values_enablement.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ingressgateway_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/install_package_path.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_disable_tracing.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_merge_meshconfig.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ztunnel.golden.yaml
  operator/cmd/mesh/testdata/operator/output/operator-dump.yaml
  operator/cmd/mesh/testdata/operator/output/operator-init.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.txt
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
Labels: size/XXL, release-notes-none

#48119 Update openshift instructions for new variables needed
  manifests/charts/install-OpenShift.md
Labels: area/environments, size/XS, release-notes-none, cherrypick/release-1.20

#48134 [release-1.20] Update openshift instructions for new variables needed
  manifests/charts/install-OpenShift.md
Labels: size/XS, release-notes-none

#48093 Remove spurious log message from istioctl output
  pkg/kube/portforwarder.go
Labels: area/environments, size/XS, release-notes-none

#47302 Fix ecds config not correct for delta response
  pkg/istio-agent/xds_proxy_delta.go
  releasenotes/notes/47302.yaml
Labels: area/networking, size/S

#48137 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48139 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#48142 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48143 [release-1.20] Complete root ca cert rotation
  samples/certs/README.md
  samples/certs/root-cert-combined-2.pem
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
  tests/integration/security/cacert_rotation/main_test.go
Labels: size/L, release-notes-none

#48125 Fix TestSyncAllWorkloadsFromAmbient flake
  pilot/pkg/serviceregistry/kube/controller/network_test.go
Labels: area/networking, size/M, release-notes-none

#46821 [WIP] remove privileges from waypoint
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/46592.yaml
Labels: area/security, ok-to-test, size/M, area/ambient

#48072 ambient: fix veth lookup for ztunnel pod on OpenShift
  cni/pkg/ambient/constants/constants.go
  cni/pkg/ambient/net_linux.go
  cni/pkg/ebpf/server/redirectionServer_linux.go
  releasenotes/notes/fix-peer-veth-lookup-on-openshift.yaml
Labels: size/M, area/ambient

#48158 cni: full repair in repair controller
  cni/pkg/ambient/podutil.go
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/plugin_dryrun_test.go
  cni/pkg/plugin/redirect.go
  cni/pkg/repair/monitoring.go
  cni/pkg/repair/netns.go
  cni/pkg/repair/repaircontroller.go
  go.mod
  manifests/charts/istio-cni/templates/clusterrole.yaml
  manifests/charts/istio-cni/templates/clusterrolebinding.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/flag/flag.go
  pkg/flag/flag_test.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-clean-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/config/config_test.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
  tools/istio-iptables/pkg/validation/validator.go
Labels: size/XXL, release-notes-none

#48159 cni: full repair in repair controller
  cni/pkg/ambient/podutil.go
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/plugin_dryrun_test.go
  cni/pkg/plugin/redirect.go
  cni/pkg/repair/monitoring.go
  cni/pkg/repair/netns.go
  cni/pkg/repair/repaircontroller.go
  go.mod
  manifests/charts/istio-cni/templates/clusterrole.yaml
  manifests/charts/istio-cni/templates/clusterrolebinding.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/flag/flag.go
  pkg/flag/flag_test.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-clean-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/config/config_test.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
  tools/istio-iptables/pkg/validation/validator.go
Labels: size/XXL, release-notes-none

#48152 refactor append metadata exchange filter
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
Labels: size/M, release-notes-none

#48155 fix comment nit
  pilot/pkg/model/telemetry_logging.go
Labels: size/XS, release-notes-none

#48145 Implement delta response for internal request and debug API
  pilot/pkg/xds/debuggen.go
  pilot/pkg/xds/statusgen.go
Labels: area/networking, size/L, release-notes-none

#48132 telemetry: update tests to not use EnvoyFilter
  pilot/pkg/features/pilot.go
  pilot/pkg/model/telemetry.go
  pkg/test/fakes/gce_metadata_server/Makefile
  pkg/test/fakes/gce_metadata_server/main.go
  pkg/test/framework/components/gcemetadata/gce_metadata_server.yaml
  pkg/test/framework/components/gcemetadata/gcemetadata.go
  pkg/test/framework/components/gcemetadata/kube.go
  pkg/test/framework/components/registryredirector/kube.go
  pkg/test/framework/components/registryredirector/registry_redirector_server.yaml
  pkg/test/framework/components/stackdriver/google.go
  pkg/test/framework/components/stackdriver/kube.go
  pkg/test/framework/components/stackdriver/stackdriver.yaml
  pkg/test/kube/util.go
  tests/integration/telemetry/api/accesslogs_test.go
  tests/integration/telemetry/api/customize_metrics_test.go
  tests/integration/telemetry/api/dashboard_test.go
  tests/integration/telemetry/api/istioctl_metrics_test.go
  tests/integration/telemetry/api/registry_setup_test.go
  tests/integration/telemetry/api/setup_test.go
  tests/integration/telemetry/api/stats_test.go
  tests/integration/telemetry/api/testdata/attributegen.yaml
  tests/integration/telemetry/api/wasmplugin_test.go
  tests/integration/telemetry/common/stats.go
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/envoyfilter/customizemetrics/testdata/setup_config.yaml
  tests/integration/telemetry/envoyfilter/nullvm/stats_filter_test.go
  tests/integration/telemetry/envoyfilter/nullvm/stats_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_allow_no_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_allow_with_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_deny_no_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_deny_with_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/vm/main_test.go
Labels: size/XXL, release-notes-none

#48076 fix(limit): use the KubernetesAPIQPS parameter to override the remote cluster kubeconfig
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pkg/kube/multicluster/secretcontroller.go
  pkg/kube/multicluster/secretcontroller_test.go
  pkg/kube/util.go
  pkg/kube/util_test.go
Labels: area/perf and scalability, ok-to-test, size/L, release-notes-none

#48089 autoregistration: fix marking entries as connected after disconnect
  pilot/pkg/autoregistration/controller.go
  releasenotes/notes/48089.yaml
Labels: size/M

#48162 Analyzer warning for internal gateway ref
  pilot/pkg/config/kube/gateway/conversion.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/testdata/virtualservice_internal_gateway_ref.yaml
  pkg/config/analysis/analyzers/virtualservice/gateways.go
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  pkg/config/gateway/kube/gatewayapi.go
Labels: size/M, release-notes-none

#48133 Skip graceful termination if Envoy ended prematurely
  pkg/envoy/agent.go
  releasenotes/notes/skip-graceful-termination.yaml
Labels: ok-to-test, area/user experience, size/M

#48146 Improve network tests
  pilot/pkg/serviceregistry/kube/controller/network_test.go
Labels: area/test and release, size/M, release-notes-none

#48167 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48157 remove checking ztunnel
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
Labels: size/XS, release-notes-none

#48165 proto: use vtprotobuf optimized functions when available
  pilot/pkg/util/protoconv/protoconv.go
Labels: size/S, release-notes-none

#48179 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#48178 bug-report: sort events by creation date
  releasenotes/notes/istioctl-sort-events-by-creation.yaml
  tools/bug-report/pkg/content/content.go
Labels: ok-to-test, size/XS

#48176 [release-1.19] Cherrypick #47643 - dependabot docker/docker update
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#48154 cleanup envoy endpoint building for tunnel
  pilot/pkg/networking/util/util.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
Labels: size/M, release-notes-none

#48171 Fix test flake TestNetworkUpdateTriggers
  pilot/pkg/serviceregistry/kube/controller/network_test.go
Labels: size/XS, release-notes-none

#48181 add DaemonSets and StatefulSets to known types
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kind/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
Labels: size/S, release-notes-none

#48182 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#48183 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#48184 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48163 Optimize model.ParseSubsetKey
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
  pilot/pkg/xds/eds.go
Labels: size/M, release-notes-none

#48185 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47686 Add memory targetAverageUtilization config
  manifests/charts/gateway/templates/hpa.yaml
  manifests/charts/gateway/values.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot.tar.gz
  operator/cmd/mesh/testdata/manifest-generate/input/autoscaling_ingress_v2.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/autoscaling_v2.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/autoscaling_v2beta1_k8s_and_values.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/deprecated_autoscaling_k8s_spec.yaml
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_k8s_settings.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/autoscaling_ingress_v2.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/autoscaling_v2.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/autoscaling_v2beta1_k8s_and_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/deprecated_autoscaling_k8s_spec.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.golden.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/translate/translate_test.go
  operator/pkg/translate/translate_value_test.go
  operator/pkg/util/merge_iop.go
  pkg/config/analysis/analyzers/testdata/common/sidecar-injector-enabled-nsbydefault.yaml
  pkg/config/analysis/analyzers/testdata/sidecar-injector-configmap-with-revision-canary.yaml
Labels: area/environments, ok-to-test, area/user experience, size/L, release-notes-none

#48187 Automator: update common-files@release-1.20 in istio/istio@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#48194 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48170 Make EnableDistributionTracking really disable things
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
Labels: size/M, release-notes-none

#48191 Automator: update istio/client-go@release-1.18 dependency in istio/istio@release-1.18
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#48186 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#48190 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#48193 reduce redudant cal for autoAllocateIPs
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
Labels: size/S, release-notes-none

#48192 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48195 [release-1.20] istioctl bug-report: Speed improvement from concurrency limiting
  releasenotes/notes/bug-report-speedup.yaml
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/bugreport/flags.go
  tools/bug-report/pkg/config/config.go
  tools/bug-report/pkg/kubeclient/kubeclient.go
  tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
Labels: size/M, release-notes-none

#48199 cni: fix typo at root.go
  cni/pkg/cmd/root.go
Labels: size/XS, release-notes-none

#48189 Automator: update ztunnel@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48196 remove retry in TestNetworkUpdateTriggers
  pilot/pkg/serviceregistry/kube/controller/network_test.go
Labels: size/S, release-notes-none

#48200 [release-1.20 ]Update deps
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#48205 Small refactor to crdclient test
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: size/M, release-notes-none

#48206 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48209 Fix deadlink for istio logo in dashboard
  manifests/addons/dashboards/istio-mesh-dashboard.json
  samples/addons/grafana.yaml
Labels: size/XS, release-notes-none

#48210 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48213 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48216 [release-1.20] tools/bug-report: Reduce k8s API calls via "get" not "describe"
  releasenotes/notes/bug-report-perf.yaml
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/content/content.go
Labels: size/M, release-notes-none

#48215 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48226 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#48227 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48232 Update BASE_VERSION to 1.19-2023-12-07T19-03-18
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48231 Update BASE_VERSION to master-2023-12-07T19-01-55
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48234 Update BASE_VERSION to 1.18-2023-12-07T19-03-08
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48233 Update BASE_VERSION to 1.20-2023-12-07T19-03-32
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48175 refactor: use sets to simplify code logic
  pilot/cmd/pilot-agent/app/cmd.go
  pilot/cmd/pilot-agent/app/request.go
Labels: area/networking, size/M, release-notes-none

#48236 `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`: build JWKS clusters
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/xds/cds.go
  pilot/pkg/xds/proxy_dependencies_test.go
  releasenotes/notes/jwks-cluster.yaml
Labels: area/security, size/L

#48240 Automator: update ztunnel@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48245 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48251 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#48230 Fix TestHostNetworkPod flake
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
  pkg/test/util/assert/tracker.go
Labels: size/M, release-notes-none

#48250 ambient: cleanup profile
  manifests/profiles/ambient.yaml
Labels: size/S, release-notes-none

#48246 e2e: increase accesslog retry timeout
  tests/integration/telemetry/api/accesslogs_test.go
Labels: size/XS, release-notes-none

#48071 Dedupe wildcard routes based on the virtualservice with the most specific match
  pilot/pkg/features/pilot.go
  pilot/pkg/model/config.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pkg/config/model.go
  releasenotes/notes/45415-overlapping-wildcards.yaml
Labels: area/networking, size/L, cherrypick/release-1.19, cherrypick/release-1.20

#48248 Minor cleanup of cluster inbound code
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
Labels: size/S, release-notes-none

#48260 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#48261 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48255 fix some comment
  pilot/pkg/model/extensions.go
  pkg/wasm/convert.go
  pkg/wasm/imagefetcher.go
  tests/integration/telemetry/api/stats_test.go
Labels: size/S, release-notes-none

#48264 Cleanup for ambient helm installation
  manifests/charts/istio-control/istio-discovery/ambient-values.yaml
Labels: area/environments, size/XS, release-notes-none

#48252 envoy: always use json as as Envoy custom bootstrap config
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
  pkg/envoy/testdata/bootstrap.yaml
Labels: area/user experience, size/M, release-notes-none

#48268 Fix merge traffic policy
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: size/S, release-notes-none

#48281 Update BASE_VERSION to 1.19-2023-12-11T19-02-16
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48280 Update BASE_VERSION to 1.20-2023-12-11T19-02-36
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48282 Update BASE_VERSION to 1.18-2023-12-11T19-04-01
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48279 Update BASE_VERSION to master-2023-12-11T19-01-39
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#48287 gateway: set_current_client_cert_details only if valid
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: area/networking, area/user experience, size/M, release-notes-none

#48288 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48289 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48237 Implement upstream proxy protocol
  pilot/pkg/networking/core/v1alpha3/cluster_tls.go
  pilot/pkg/networking/core/v1alpha3/cluster_traffic_policy.go
  pilot/pkg/networking/core/v1alpha3/cluster_traffic_policy_test.go
  pkg/config/validation/validation.go
  releasenotes/notes/destination-rule-proxyprotocol
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/gw_topology_test.go
Labels: size/L

#48221 Svc network update on network change, and handle required resources when the namespace is selected
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/network_test.go
Labels: area/networking, size/M, release-notes-none, area/ambient

#48297 use discovery v1 labels
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: size/XS, release-notes-none

#48266 Fix dry-run deactivating default webhook
  istioctl/pkg/tag/generate_test.go
  operator/pkg/helmreconciler/reconciler.go
  releasenotes/notes/48266.yaml
Labels: area/environments, size/M

#48298 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47862 istioctl: only support SSA
  operator/cmd/mesh/manifest_shared_test.go
  operator/cmd/mesh/shared.go
  operator/pkg/helmreconciler/apply.go
  operator/pkg/helmreconciler/apply_test.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/common_test.go
  operator/pkg/helmreconciler/prune_test.go
  operator/pkg/helmreconciler/reconciler.go
  operator/pkg/util/path.go
  tests/fuzz/helm_reconciler_fuzzer.go
Labels: size/L, release-notes-none

#48299 code cleanup, remove duplicated checks
  pilot/pkg/model/gateway.go
  pkg/config/gateway/gateway.go
Labels: size/XS, release-notes-none

#48303 update zt daemonset to use ISTIO_META_CLUSTER_ID
  manifests/charts/ztunnel/templates/daemonset.yaml
Labels: size/XS, release-notes-none, area/ambient

#48283 [release-1.20] Dedupe wildcard routes based on the virtualservice with the most specific match (#48071)
  pilot/pkg/features/pilot.go
  pilot/pkg/model/config.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pkg/config/model.go
  releasenotes/notes/45415-overlapping-wildcards.yaml
Labels: size/L

#48277 [release-1.19] Dedupe wildcard routes based on the virtualservice with the most specific match (#48071)
  pilot/pkg/features/pilot.go
  pilot/pkg/model/config.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pkg/config/model.go
  releasenotes/notes/45415-overlapping-wildcards.yaml
Labels: size/XL

#48235 limit full pushes when pure http headless service endpoints add/delete
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  releasenotes/notes/48207.yaml
Labels: area/networking, size/M

#48285 [release-1.20] make the auto scale behave in gateway configurable
  manifests/charts/gateway/templates/hpa.yaml
  manifests/charts/gateway/values.yaml
  releasenotes/notes/47318.yaml
Labels: size/S, release-notes-none

#47892 install: drop legacy telemetry install
  Makefile.core.mk
  manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
  manifests/charts/istio-control/istio-discovery/templates/_helpers.tpl
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.18.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.19.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.20.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.21.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/templates/_helpers.tpl
  manifests/charts/istiod-remote/templates/telemetryv2_1.18.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.19.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.20.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.21.yaml
  manifests/charts/istiod-remote/values.yaml
  manifests/profiles/default.yaml
  manifests/profiles/preview.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot.tar.gz
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml
  operator/cmd/mesh/testdata/profile-dump/output/all_off.txt
  operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/util/merge_iop.go
  releasenotes/notes/drop-telemetry-envoyfilter.yaml
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/accesslogpolicy.yaml
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
Labels: size/XXL, release-notes-none

#48307 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#48310 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48291 Try to fix flake TestServerReconcilePod
  cni/pkg/ambient/informers_test.go
Labels: ok-to-test, size/L, release-notes-none

#48320 [release-1.20] Fix dry-run deactivating default webhook
  istioctl/pkg/tag/generate_test.go
  operator/pkg/helmreconciler/reconciler.go
  releasenotes/notes/48266.yaml
Labels: size/M, release-notes-none

#48319 [release-1.19] Fix dry-run deactivating default webhook
  istioctl/pkg/tag/generate_test.go
  operator/pkg/helmreconciler/reconciler.go
  releasenotes/notes/48266.yaml
Labels: size/M, release-notes-none

#48324 Replace a deprecated go-jose repo with active one
  go.mod
  go.sum
  licenses/gopkg.in/square/go-jose.v2/LICENSE
  licenses/gopkg.in/square/go-jose.v2/json/LICENSE
  pkg/spiffe/spiffe.go
  security/pkg/server/ca/authenticate/oidc_test.go
  tests/integration/pilot/validation_test.go
Labels: area/test and release, size/L, release-notes-none

#48327 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#48328 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#48329 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48333 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#48330 Make sure we still take the oldest VS when we have actual duplicate hosts
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
Labels: area/networking, size/M, release-notes-none, cherrypick/release-1.19, cherrypick/release-1.20

#48335 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#48338 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48340 Move default tests to k8s 1.29
  prow/integ-suite-kind.sh
Labels: size/XS, release-notes-none

#48337 [release-1.20] Manual Cherrypick 48235
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  releasenotes/notes/48207.yaml
Labels: size/L

#48342 [release-1.20] Make sure we still take the oldest VS when we have actual duplicate hosts
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
Labels: size/M, release-notes-none

#48339 tests: test standard remote profile, which doesn't have mesh config
  pkg/test/framework/components/istio/configmap.go
  tests/integration/iop-remote-integration-test-defaults.yaml
Labels: size/S, release-notes-none

#48341 [release-1.19] Make sure we still take the oldest VS when we have actual duplicate hosts
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
Labels: size/M, release-notes-none

#48313 Fix typos that do not affect logical with crate-ci/typos.
  Makefile.core.mk
  cni/pkg/ebpf/app/ambient_redirect.bpf.c
  cni/pkg/ebpf/server/redirectionServer_linux.go
  istioctl/pkg/checkinject/checkinject.go
  istioctl/pkg/multixds/gather.go
  istioctl/pkg/writer/pilot/status.go
  operator/pkg/name/name.go
  pilot/pkg/features/pilot.go
  pilot/pkg/model/context.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/filters/filters.go
  pkg/config/validation/validation.go
  pkg/dns/client/dns.go
  pkg/errdict/errdict.go
  pkg/workloadapi/workload.pb.go
  pkg/workloadapi/workload.proto
  tools/bug-report/pkg/cluster/cluster.go
Labels: kind/docs, ok-to-test, size/L, release-notes-none

#48347 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48351 Fix missing push nds for headless pure http svc
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/serviceregistry/util/xdsfake/updater.go
Labels: size/M, release-notes-none

#48355 [release-1.20] Fix missing push nds for headless pure http svc
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/serviceregistry/util/xdsfake/updater.go
Labels: size/M, release-notes-none

#48345 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48357 Tighter query for L4 metrics in the Ambient integeration test
  tests/integration/ambient/baseline_test.go
Labels: size/XS, release-notes-none, area/ambient

#48363 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48334 Fix wrong socket type for extra addresses in QUIC listeners
  pilot/pkg/networking/core/v1alpha3/listener.go
  releasenotes/notes/48334.yaml
  tests/integration/security/sds_ingress/quic/ingress_test.go
Labels: size/S, area/dual-stack

#48332 operator: cleanup default profile
  manifests/profiles/default.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.values.gen.yaml
  pkg/kube/inject/testdata/inputs/default.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/default.values.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.values.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml
Labels: size/L, release-notes-none

#48369 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#48304 gcp: drop reliance on metadata server entirely when GCP_METADATA is set
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
Labels: size/S, release-notes-none

#48370 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#48318 Add selector analyzer to k8s gateway
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/k8sgateway/workloadselector.go
  pkg/config/analysis/analyzers/testdata/k8sgateway-selector.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/48318.yaml
Labels: area/user experience, size/L

#48371 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48372 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48375 [release-1.19] Fix wrong socket type for extra addresses in QUIC listeners
  pilot/pkg/networking/core/v1alpha3/listener.go
  releasenotes/notes/48334.yaml
Labels: area/networking, size/S, area/dual-stack

#48376 [release-1.20] Fix wrong socket type for extra addresses in QUIC listeners
  pilot/pkg/networking/core/v1alpha3/listener.go
  releasenotes/notes/48334.yaml
  tests/integration/security/sds_ingress/quic/ingress_test.go
Labels: area/networking, size/S, area/dual-stack

#47961 Fix uninstall with files doesn't prune things correctly
  operator/cmd/mesh/uninstall.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/prune_test.go
  pkg/test/framework/features/features.yaml
  releasenotes/notes/47961.yaml
  tests/integration/pilot/revisions/uninstall_test.go
Labels: area/environments, size/L

#48378 Add separator to two CRD files
  manifests/charts/base/templates/crds.yaml
Labels: area/environments, size/XS, release-notes-none, cherrypick/release-1.20

#48382 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48391 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48344 Update dependencies to k8s 1.29
  go.mod
  go.sum
  licenses/github.com/felixge/httpsnoop/LICENSE.txt
  licenses/github.com/mxk/go-flowrate/LICENSE
  licenses/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/LICENSE
  licenses/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/LICENSE
  pkg/kube/client_factory.go
  pkg/kube/spdy.go
Labels: size/XL, release-notes-none

#48396 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48389 [release-1.20] Add separator to two CRD files
  manifests/charts/base/templates/crds.yaml
Labels: size/XS, release-notes-none

#48397 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none
