Repository istio/istio, pull requests merged in 2023-08, with the labels that each got.

#46217 Flags: remove protocol sniffing flags
  manifests/addons/dashboards/pilot-dashboard.json
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  manifests/profiles/default.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pilot/pkg/features/pilot.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_cache.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/networking.go
  pilot/pkg/networking/networking_test.go
  pilot/pkg/networking/util/util.go
  pkg/config/protocol/instance.go
  releasenotes/notes/flagprotocol-sniffing.yaml
  samples/addons/grafana.yaml
Labels: size/XL

#46245 tf: make dashboard test not send errors
  tests/integration/telemetry/envoyfilter/nullvm/dashboard_test.go
Labels: size/XS, release-notes-none

#46255 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46256 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#46235 Always enable listener.ContinueOnListenerFiltersTimeout
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: size/M, release-notes-none

#46241 Fix revisioned default resources being filtered during analysis
  pilot/pkg/config/kube/crdclient/client_test.go
  pkg/config/analysis/local/analyze_test.go
  pkg/config/analysis/local/istiod_analyze.go
  pkg/config/model.go
  pkg/config/schema/collection/schemas.go
  releasenotes/notes/46241.yaml
Labels: area/user experience, size/L

#46261 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46265 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46260 Fix test flake TestFuzzMergeHttpRoute
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
Labels: size/XS, release-notes-none

#46266 Automated branching step 1
  go.mod
  go.sum
  prow/release-commit.sh
Labels: area/test and release, size/S, release-notes-none

#46268 Fix ambient `WorkloadEntry` update xds events
  pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
  releasenotes/notes/46267.yaml
Labels: size/S, area/ambient

#46072 Add output format option to precheck
  istioctl/pkg/precheck/precheck.go
  releasenotes/notes/46072.yaml
Labels: size/S

#46133 Revise create remote secret logic
  istioctl/cmd/root.go
  istioctl/pkg/cli/context.go
  istioctl/pkg/multicluster/env.go
  istioctl/pkg/multicluster/env_test.go
  istioctl/pkg/multicluster/options.go
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  pkg/kube/client.go
Labels: area/user experience, size/XL, release-notes-none

#46104 Fix incorrect verify-install deployment count
  istioctl/pkg/verifier/verifier.go
  releasenotes/notes/46104.yaml
Labels: area/user experience, size/S

#46272 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46254 cleanup app probe test
  pilot/cmd/pilot-agent/status/server_test.go
Labels: size/XS, release-notes-none

#46271 Fix two text typos
  cni/pkg/cmd/root.go
  pilot/pkg/bootstrap/istio_ca.go
Labels: kind/docs, size/XS, release-notes-none

#46278 fix incorrect stat increments in webhook patching
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
Labels: size/S, release-notes-none

#46276 fix: typo
  pilot/pkg/features/pilot.go
  pkg/config/schema/kubetypes/common.go
  security/pkg/pki/ra/k8s_ra.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_csr.go
Labels: ok-to-test, area/user experience, size/S, release-notes-none

#46282 Automator: update common-files@release-1.17 in istio/istio@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46283 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46284 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46286 Automator: update common-files@release-1.18 in istio/istio@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46288 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46287 Automator: update istio/client-go@release-1.18 dependency in istio/istio@release-1.18
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46292 Automator: update ztunnel@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46299 [release-1.19] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  prow/release-commit.sh
Labels: size/M, release-notes-none

#46300 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46285 add release notes for #46277
  releasenotes/notes/46277.yaml
Labels: size/XS, cherrypick/release-1.18, cherrypick/release-1.19

#46179 Add validation of workload entry identity (#117)
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/autoregistration/controller_test.go
  pilot/pkg/features/pilot.go
  pilot/pkg/xds/vm_test.go
  pkg/adsc/adsc.go
  pkg/istio-agent/xds_proxy_test.go
Labels: size/L, release-notes-none, cherrypick/release-1.19

#46304 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46301 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46302 [release-1.18] add release notes for #46277
  releasenotes/notes/46277.yaml
Labels: size/XS, release-notes-none

#46303 [release-1.19] add release notes for #46277
  releasenotes/notes/46277.yaml
Labels: size/XS, release-notes-none

#46305 [release-1.19] Add validation of workload entry identity (#117)
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/autoregistration/controller_test.go
  pilot/pkg/features/pilot.go
  pilot/pkg/xds/vm_test.go
  pkg/adsc/adsc.go
  pkg/istio-agent/xds_proxy_test.go
Labels: size/L, release-notes-none

#46306 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46308 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46310 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46206 Mark validate referential flag as hidden because of no usage
  istioctl/pkg/validate/validate.go
Labels: area/user experience, size/XS, release-notes-none

#46236 Update min k8sversion to 1.25
  istioctl/pkg/install/k8sversion/version.go
  istioctl/pkg/install/k8sversion/version_test.go
Labels: area/user experience, size/S, release-notes-none, cherrypick/release-1.19

#46161 Fix describe with injected gateway not working
  istioctl/pkg/describe/describe.go
  istioctl/pkg/describe/describe_test.go
  releasenotes/notes/46161.yaml
Labels: area/user experience, size/L

#46184 Revise deprecated FromInt to FromInt32
  istioctl/pkg/describe/describe_test.go
  operator/pkg/apis/istio/v1alpha1/value_types_json.go
  operator/pkg/object/objects.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pkg/kube/inject/app_probe.go
  pkg/kube/inject/app_probe_test.go
  tests/integration/pilot/tunneling_test.go
Labels: size/S, release-notes-none

#46257 Remove experimental revision tag command
  istioctl/pkg/revision/revision.go
  releasenotes/notes/46257.yaml
Labels: area/user experience, size/XS

#46316 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46317 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46314 operator/pkg/name: remove unused unexported global map
  operator/pkg/name/name.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#46319 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46313 fix: cross namespace gateway test cases
  tests/integration/pilot/gateway_test.go
Labels: area/test and release, ok-to-test, size/M, release-notes-none

#46320 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46323 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46322 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46324 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46291 Temporarily skip version test that is broken
  tests/integration/pilot/multi_version_revision_test.go
Labels: size/XS, release-notes-none, cherrypick/release-1.19

#46330 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46331 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46318 [release-1.19] Update min k8sversion to 1.25
  istioctl/pkg/install/k8sversion/version.go
  istioctl/pkg/install/k8sversion/version_test.go
Labels: size/S, release-notes-none

#46328 [release-1.19] Temporarily skip version test that is broken
  tests/integration/pilot/multi_version_revision_test.go
Labels: size/XS, release-notes-none

#46325 [release-1.19] fix: typo
  pilot/pkg/features/pilot.go
  pkg/config/schema/kubetypes/common.go
  security/pkg/pki/ra/k8s_ra.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_csr.go
Labels: size/S, release-notes-none

#46337 [release-1.19] Support namespace filtering for experimental proxy status
  istioctl/pkg/proxystatus/proxystatus.go
  istioctl/pkg/writer/pilot/status.go
  pilot/pkg/xds/statusgen.go
  tests/integration/pilot/istioctl_test.go
Labels: size/S, release-notes-none

#46338 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46341 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46343 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46340 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#46344 [release-1.19] Replace master with release-1.19
  bin/update_deps.sh
  bin/update_ztunnel.sh
  prow/release-commit.sh
Labels: size/S, release-notes-none

#46333 Cleanup legacy EDS tests
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/xds/eds_sh_test.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
Labels: size/L, release-notes-none

#46347 Fix uninstall dry-run has confirmation
  operator/cmd/mesh/uninstall.go
Labels: size/XS, release-notes-none

#46351 Add service account completion to waypoint command
  istioctl/pkg/completion/completion.go
  istioctl/pkg/waypoint/waypoint.go
Labels: area/user experience, size/M, release-notes-none, area/ambient

#46289 Set extAuth authority to hostname
  pilot/pkg/security/authz/builder/extauthz.go
  pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out2.yaml
  pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out2.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/custom-both-http-tcp-out2.yaml
Labels: size/S, release-notes-none

#46355 add test for gateway route merge preferences
  pilot/pkg/config/kube/gateway/conversion_test.go
Labels: size/L, release-notes-none

#46362 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46364 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46363 Fix EDS test flakes
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/instance.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/mock/discovery.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/eds_sh_test.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/simple.go
  tests/fuzz/aggregate_controller_fuzzer.go
Labels: size/L, release-notes-none

#46357 Temporarily skip version test that is broken (again)
  tests/integration/pilot/revisioned_upgrade_test.go
Labels: size/XS, release-notes-none

#46371 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46372 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46375 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46326 locality: refactor and drop Service dependency
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/eds_test.go
  pkg/bootstrap/config.go
  pkg/test/util/assert/assert.go
  releasenotes/notes/locality-service.yaml
Labels: size/L

#46373 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46376 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46377 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46379 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46358 [release-1.19] accesslog: disable builtin resource labels
  go.mod
  go.sum
  pilot/pkg/features/pilot.go
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  releasenotes/notes/46339.yaml
Labels: size/S, release-notes-none

#46381 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45291 Add istio-generated key to cacerts and create self-signed cacerts secret
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/selfsignedcarootcertrotator.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
Labels: size/L, release-notes-none

#46369 make CRD validator support CEL validation
  pkg/config/crd/validator.go
Labels: size/S, release-notes-none

#46334 Cleanup obsolete parts of simple istio-agent xds server
  pilot/pkg/bootstrap/server.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/simple.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: size/L, release-notes-none

#46359 Use go-control-plane from last 1.27 cut
  go.mod
  go.sum
Labels: area/test and release, size/XS, release-notes-none

#46374 Move EndpointIndex logic to common area, use in ConfigGenTest
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/endpointshards_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
Labels: size/XL, release-notes-none

#46391 [kiali] update to kiali 1.72.0
  manifests/addons/gen.sh
  releasenotes/notes/kiali-update-v1.72.yaml
  samples/addons/kiali.yaml
Labels: area/environments, size/M, cherrypick/release-1.19

#46132 pkg: fix typos in comments and tests
  pkg/bootstrap/option/convert.go
  pkg/collateral/predicate.go
  pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go
  pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  pkg/config/analysis/local/istiod_analyze.go
  pkg/config/resource/origin.go
  pkg/config/validation/validation.go
  pkg/dns/client/dns.go
  pkg/env/var_test.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_test.go
  pkg/kube/controllers/queue.go
  pkg/kube/inject/webhook.go
  pkg/kube/kclient/clienttest/direct.go
  pkg/ledger/smt.go
  pkg/ledger/smt_test.go
  pkg/slices/slices.go
  pkg/test/framework/components/environment/kube/flags.go
  pkg/test/framework/features/features.yaml
  pkg/test/util/retry/retry.go
  pkg/version/cobra.go
Labels: kind/docs, area/test and release, ok-to-test, size/M, release-notes-none

#46393 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46295 Remove usage of service instances for proxy
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/proxy_dependencies.go
  tests/fuzz/pilot_model_fuzzer.go
Labels: size/XXL, release-notes-none

#46395 tf: properly assign available port for port-forward
  pkg/kube/client.go
  pkg/kube/portforwarder.go
  pkg/test/framework/components/cluster/kube/factory.go
Labels: size/M, release-notes-none

#46397 1.17: bump k8s.io/client-go dep
  go.mod
  go.sum
Labels: ok-to-test, size/M, release-notes-none

#46402 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46394 [release-1.19] [kiali] update to kiali 1.72.0
  manifests/addons/gen.sh
  releasenotes/notes/kiali-update-v1.72.yaml
  samples/addons/kiali.yaml
Labels: size/M, release-notes-none

#46312 support aws IMDSv2
  pkg/bootstrap/platform/aws.go
  pkg/http/get.go
  releasenotes/notes/46312.yaml
Labels: size/L

#46399 sds: remove TODO that is already done
  pilot/pkg/xds/sds.go
Labels: size/XS, release-notes-none

#46405 [release-1.19] support aws IMDSv2
  pkg/bootstrap/platform/aws.go
  pkg/http/get.go
  releasenotes/notes/46312.yaml
Labels: size/L, release-notes-none

#46392 [release-1.19] Temporarily skip version test that is broken (again)
  tests/integration/pilot/revisioned_upgrade_test.go
Labels: size/XS, release-notes-none

#46403 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46415 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46401 Fix flake in new TestLocality test
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/S, release-notes-none

#46404 [Test Framework] Fix incorrect duration in log
  pkg/test/framework/components/echo/common/call.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#46406 Fix some time measurement for istioctl bug-report command
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: area/test and release, ok-to-test, size/S, release-notes-none

#46408 normalize metric name
  pkg/webhooks/validation/server/monitoring.go
Labels: size/XS, release-notes-none

#46412 Replace os.MkdirTemp with T.TempDir in tests
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/test-util_test.go
  pkg/filewatcher/filewatcher_test.go
  pkg/kube/util_test.go
Labels: area/test and release, ok-to-test, size/L, release-notes-none

#46423 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46424 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46432 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46426 [release-1.19] Update to latest quic-go for Go 1.21.0
  go.mod
  go.sum
Labels: size/S, release-notes-none

#46420 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46378 Create architecture directory and add file for Ambient peerauthentication
  CODEOWNERS
  architecture/ambient/peer-authentication.md
  architecture/environments/operator.md
  architecture/networking/pilot.md
Labels: size/M, release-notes-none

#46433 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46439 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46442 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46444 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46446 [release-1.19] Run update_deps
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#46441 Avoid mutating object in `istioctl pc all` to avoid duplicate prefix
  istioctl/pkg/writer/envoy/configdump/listener.go
Labels: size/XS, release-notes-none

#46384 Fix pc workload not working
  istioctl/pkg/util/configdump/workload.go
  istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
  istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary.txt
  istioctl/pkg/writer/ztunnel/configdump/workload.go
Labels: size/XXL, release-notes-none

#46434 Fix flake in TestEDSUnhealthyEndpoints
  pilot/pkg/xds/eds_test.go
Labels: size/XS, release-notes-none

#46448 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46450 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46425 validation: fix edge case in new mirror validation
  pkg/config/validation/validation.go
Labels: size/XS, release-notes-none

#46456 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46460 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#46455 operator: fix typos in comments and tests
  operator/cmd/mesh/install.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/test-util_test.go
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/component/component.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/wait.go
  operator/pkg/metrics/monitoring.go
  operator/pkg/object/objects.go
  operator/pkg/patch/patch.go
  operator/pkg/translate/translate.go
  operator/pkg/translate/translate_test.go
  operator/pkg/validate/common.go
Labels: kind/docs, area/test and release, ok-to-test, size/M, release-notes-none

#46453 correct flaky test comment
  tests/integration/telemetry/envoyfilter/nullvm/dashboard_test.go
Labels: size/XS, release-notes-none

#46440 testing: better cmp opts
  pilot/pkg/model/fuzz_test.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/util/workloadinstances/index_test.go
  pkg/test/util/assert/assert.go
Labels: size/L, release-notes-none

#46462 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#46465 Fix MustParse crash if ingress doesn't have an IP
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
  releasenotes/notes/46465.yaml
Labels: area/networking, size/M, area/ambient, cherrypick/release-1.19

#46464 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46468 [release-1.19] Fix MustParse crash if ingress doesn't have an IP
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
  releasenotes/notes/46465.yaml
Labels: size/M, release-notes-none

#46366 Smarter watch on files in shared node CNI directory
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  cni/pkg/install/kubeconfig.go
  cni/pkg/install/kubeconfig_test.go
  cni/pkg/install/testdata/kubeconfig-newhost
Labels: size/L, release-notes-none

#46474 [release-1.19] Fix pc workload not working
  istioctl/pkg/util/configdump/workload.go
  istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
  istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary.txt
  istioctl/pkg/writer/ztunnel/configdump/workload.go
Labels: size/XXL, release-notes-none

#46458 fix: TestHelmReconciler flake
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/manifest_shared_test.go
Labels: area/test and release, ok-to-test, size/M, release-notes-none

#46466 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46476 [release-1.19] Fix uninstall dry-run has confirmation
  operator/cmd/mesh/uninstall.go
Labels: size/XS, release-notes-none

#46478 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46479 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46475 [release-1.19] Warn muiltple istio namespace labels in analyze, include ambient
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/injection/injection.go
  pkg/config/analysis/analyzers/testdata/injection.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/46348.yaml
Labels: size/M, release-notes-none

#46487 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46485 fix port conflict
  pilot/pkg/bootstrap/server_test.go
Labels: area/networking, size/XS, release-notes-none, cherrypick/release-1.18, cherrypick/release-1.19

#46491 Reduce flakiness of TestNewServer
  pilot/pkg/bootstrap/server_test.go
Labels: size/M, release-notes-none

#46489 [release-1.18] fix port conflict
  pilot/pkg/bootstrap/server_test.go
Labels: size/XS, release-notes-none

#46490 [release-1.19] fix port conflict
  pilot/pkg/bootstrap/server_test.go
Labels: size/XS, auto-merge, release-notes-none

#46483 install: fix dry-run prunes resources
  operator/pkg/helmreconciler/reconciler.go
  releasenotes/notes/46483.yaml
Labels: area/environments, size/XS

#46492 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46067 metadata exchange: switch to native implementation
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/xds/filters/filters.go
  releasenotes/notes/http-metadata-exchange.yaml
  tests/integration/telemetry/envoyfilter/nullvm/dashboard_test.go
Labels: size/M

#46496 pilot: set `istio.alpn_override: false` in subset clusters
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  releasenotes/notes/40680.yaml
Labels: area/networking, size/L, cherrypick/release-1.19
