Repository istio/istio, pull requests merged in 2023-09, with the labels that each got.

#46792 Update deps for 1.19.0
  docker/Dockerfile.distroless
Labels: area/test and release, size/XS, release-notes-none

#46802 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46808 [release-1.17] support aws IMDSv2
  pkg/bootstrap/platform/aws.go
  pkg/http/get.go
  releasenotes/notes/46312.yaml
Labels: size/L, release-notes-none

#46806 [release-1.18] support aws IMDSv2
  pkg/bootstrap/platform/aws.go
  pkg/http/get.go
  releasenotes/notes/46312.yaml
Labels: size/L, release-notes-none

#46801 Remove conditional cleanup from traffic test
  tests/integration/pilot/common/traffic.go
Labels: area/test and release, size/XS, release-notes-none

#46803 Fix ingressgateway being enabled in ambient profile
  manifests/profiles/ambient.yaml
Labels: size/XS, release-notes-none, area/ambient

#46811 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46812 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46815 gateway api: Fix the status address type
  pilot/pkg/config/kube/gateway/conversion.go
Labels: size/XS, release-notes-none

#46817 gateway api: use the new reason AddressNotAssigned
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/eastwest-labelport.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest-tlsoption.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/waypoint.status.yaml.golden
Labels: size/S, release-notes-none

#46816 Temporarily add xenial and bionic base images
  tools/docker.yaml
Labels: size/XS, release-notes-none

#46822 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46824 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46818 [release-1.18] Remove conditional cleanup from traffic test
  tests/integration/pilot/common/traffic.go
Labels: size/XS, release-notes-none

#46831 Clean up some unused code
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
Labels: area/networking, size/S, release-notes-none

#46828 fix TestXdsProxyStatus flake: race condition in connection
  pilot/pkg/xds/statusgen.go
Labels: area/test and release, area/user experience, size/XS, release-notes-none

#46838 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46762 More fix: only select wles from config cluster
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/authorization.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
Labels: size/M, release-notes-none

#46540 adding waypoints should be non-disruptive
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  releasenotes/notes/46540.yaml
Labels: size/L, area/ambient

#46840 Update BASE_VERSION to master-2023-09-05T17-00-27
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#46841 Report networkpolicies in bug-report
  tools/bug-report/pkg/content/content.go
Labels: size/XS, release-notes-none, cherrypick/release-1.18, cherrypick/release-1.19

#46851 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#46842 [release-1.18] Report networkpolicies in bug-report
  tools/bug-report/pkg/content/content.go
Labels: size/XS, release-notes-none

#46843 [release-1.19] Report networkpolicies in bug-report
  tools/bug-report/pkg/content/content.go
Labels: size/XS, release-notes-none

#46850 Remove unused env var
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: size/XS, release-notes-none

#46735 [release-1.19] respect meshConfig.defaultConfig.sampling
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
  releasenotes/notes/46711.yaml
Labels: size/L

#46819 [release-1.19] Remove conditional cleanup from traffic test
  tests/integration/pilot/common/traffic.go
Labels: size/XS, release-notes-none

#46683 [release-1.19] Add ability to install gateway helm chart with dual-stack service def…
  manifests/charts/gateway/templates/service.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
  releasenotes/notes/gateway-dual-stack.yaml
Labels: size/S, release-notes-none

#46715 [release-1.19] Ambient: fix incorrect updates when ambient namespace label is changed
  pilot/pkg/serviceregistry/kube/controller/controller.go
  releasenotes/notes/46614.yaml
Labels: size/S, release-notes-none

#46739 [release-1.19] install: fix warning with wrong control plane
  istioctl/pkg/version/version.go
  operator/cmd/mesh/install.go
  operator/pkg/version/version.go
  pkg/kube/client.go
  pkg/version/cobra_test.go
  pkg/version/version.go
  releasenotes/notes/46511.yaml
Labels: size/M, release-notes-none

#46853 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#46784 [release-1.19] Cherrypick 46429
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/filterchain_options.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/networking.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/xds/filters/context.go
  pilot/pkg/xds/filters/filters.go
  pilot/pkg/xds/filters/filters_test.go
  pilot/pkg/xds/testdata/benchmarks/empty.yaml
  pkg/config/mesh/mesh.go
  pkg/config/mesh/mesh_test.go
  pkg/ptr/pointer.go
  releasenotes/notes/proxy-headers.yaml
  tests/integration/pilot/headers_test.go
Labels: size/XXL

#46814 Raise minimum OS in VM tests
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
  prow/lib.sh
  tools/docker.yaml
Labels: size/S, release-notes-none

#46795 Add IPv6 wildcard for dualstack proxies and correct ipv6 wildcard
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pkg/config/constants/constants.go
Labels: area/networking, size/M, release-notes-none

#46854 If an error occurs, the value of svc will be overwritten and the print error message will be empty
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: ok-to-test, size/XS, release-notes-none

#46861 guarantee we don't end up with empty address endpoints
  pilot/pkg/xds/endpoints/endpoint_builder.go
Labels: size/XS, release-notes-none

#46864 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46866 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46865 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46869 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46862 Fix mesh config sync
  pkg/kube/watcher/configmapwatcher/configmapwatcher.go
  releasenotes/notes/mesh-sync.yaml
Labels: size/S, release-notes-none

#46871 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46872 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46873 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46875 return http plugin type for default
  pilot/pkg/model/extensions.go
Labels: size/XS, release-notes-none

#46876 Automator: update common-files@release-1.18 in istio/istio@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46878 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46877 Automator: update istio/client-go@release-1.18 dependency in istio/istio@release-1.18
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46874 fix: close the file fd when it indeed
  pkg/test/util/yml/file.go
Labels: ok-to-test, size/XS, release-notes-none

#46677 [release-1.19] Update sigs.k8s.io/gateway-api to 0.8.0
  go.mod
  go.sum
  operator/cmd/operator/server.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: area/networking, size/XL, release-notes-none

#45695 Add proxy command to dashboard
  istioctl/pkg/dashboard/dashboard.go
  releasenotes/notes/45695.yaml
Labels: area/user experience, size/M

#46886 Automator: update ztunnel@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46888 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46887 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46860 Enable DUAL_STACK flags at test framework level
  pkg/test/framework/components/istio/kube.go
  tests/integration/pilot/main_test.go
  tests/integration/security/main_test.go
Labels: area/test and release, size/M, release-notes-none

#46870 Fix some install flags not taking effect
  operator/cmd/mesh/operator-init.go
  operator/cmd/mesh/operator-remove.go
  operator/cmd/mesh/root.go
  operator/cmd/mesh/uninstall.go
Labels: area/environments, size/M, release-notes-none

#46896 Cherrypick 46579
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/xds/filters/filters.go
  pkg/test/framework/components/echo/common/deployment/namespace.go
  releasenotes/notes/skip-mx-headers.yaml
  tests/integration/pilot/headers_test.go
Labels: size/L

#46897 Revert "Enable DUAL_STACK flags at test framework level"
  pkg/test/framework/components/istio/kube.go
  tests/integration/pilot/main_test.go
  tests/integration/security/main_test.go
Labels: size/M, release-notes-none

#46900 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46890 [release-1.18] Bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#46889 [release-1.19] Bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#46894 Add endpoints to proxy-config all output
  istioctl/pkg/proxyconfig/proxyconfig.go
  releasenotes/notes/fix-proxyconfig-endpoints-json.yaml
  tests/integration/pilot/istioctl_test.go
Labels: area/user experience, size/M

#46902 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46893 [release-1.17] Manual cherrypick of #46883 - Bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#46903 Automator: update common-files@release-1.17 in istio/istio@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46905 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46906 send initial unready endpoints when SendUnhealthyEndpoints is enabled
  pilot/pkg/model/endpointshards.go
  pilot/pkg/xds/eds_test.go
Labels: size/M, release-notes-none

#46912 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46907 Enable DUAL_STACK flags at test framework level
  pkg/test/framework/components/istio/kube.go
  tests/integration/pilot/main_test.go
  tests/integration/security/main_test.go
  tests/integration/security/sds_ingress/quic/ingress_test.go
Labels: size/M, release-notes-none

#46917 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46913 [cherry-pick 1.18] Add E2E option to patch SHARED_MESH_CONFIG (#46074)
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/configmap.go
  pkg/test/framework/components/istio/flags.go
Labels: area/test and release, size/M, release-notes-none

#46927 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46918 use pkg/wellknown
  go.mod
  go.sum
  istioctl/pkg/authz/listener.go
  istioctl/pkg/describe/describe.go
  istioctl/pkg/writer/envoy/configdump/listener.go
  istioctl/pkg/writer/envoy/configdump/listener_test.go
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_tls.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/extauthz.go
  pilot/pkg/xds/filters/filters.go
  pilot/pkg/xds/filters/filters_test.go
  pilot/pkg/xds/lds_test.go
  pilot/pkg/xds/xds_test.go
  pilot/test/xdstest/extract.go
  pkg/adsc/adsc.go
  pkg/bootstrap/option/convert.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/config/xds/deprecated.go
  pkg/config/xds/filter_types.gen.go
  pkg/config/xds/filters.go
  pkg/wellknown/wellknown.go
Labels: area/test and release, size/L, release-notes-none

#46920 telemetry: add test for TestTelemetryFilters
  pilot/pkg/model/telemetry_test.go
Labels: size/L, release-notes-none

#46924 dedup addressInfo
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
Labels: size/M, release-notes-none

#46901 Fix applying resource error lead to undefined behavior during installation
  operator/pkg/helmreconciler/apply.go
  releasenotes/notes/46901.yaml
Labels: area/environments, size/S

#46934 Remove unused external CA type ISTIOD_RA_ISTIO_API
  pilot/pkg/bootstrap/istio_ca.go
  security/pkg/pki/ra/common.go
Labels: area/security, size/XS, release-notes-none

#46621 Add validation logic for PolicyTargetReference selector
  pilot/pkg/serviceregistry/kube/controller/authorization.go
  pkg/config/analysis/analyzers/authz/authorizationpolicies.go
  pkg/config/analysis/analyzers/telemetry/selector.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/XL, release-notes-none

#46936 Ambient/CNI: be more selective about hostIP skips
  cni/pkg/ambient/net_linux.go
Labels: size/S, release-notes-none, area/ambient

#46941 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#46943 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46880 Fix verify install kinds for kind NetworkAttachmentDefinition
  istioctl/pkg/verifier/verifier.go
  releasenotes/notes/46880.yaml
Labels: area/user experience, size/M, cherrypick/release-1.19

#46942 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46825 Fix analyze keep watching resources when api server cannot be connected
  istioctl/pkg/analyze/analyze.go
Labels: area/user experience, size/XS, release-notes-none

#46944 [release-1.19] Fix verify install kinds for kind NetworkAttachmentDefinition
  istioctl/pkg/verifier/verifier.go
  releasenotes/notes/46880.yaml
Labels: size/M, release-notes-none

#46938 [release-1.19] Gateway API cherrypicks
  pilot/pkg/config/kube/gateway/context.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/testdata/eastwest-labelport.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest-tlsoption.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/waypoint.status.yaml.golden
Labels: size/M, release-notes-none

#46940 [release-1.19] Add endpoints to proxy-config all output
  istioctl/pkg/proxyconfig/proxyconfig.go
  releasenotes/notes/fix-proxyconfig-endpoints-json.yaml
  tests/integration/pilot/istioctl_test.go
Labels: size/M, release-notes-none

#46949 [release-1.19] dedup addressInfo
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
Labels: size/M, release-notes-none

#46931 [cherry-pick 1.18] Update egress e2es
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  tests/integration/pilot/tunneling_test.go
  tests/integration/security/authz_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/testdata/authz/egress-gateway.yaml.tmpl
Labels: area/test and release, size/M, release-notes-none

#46948 possible duplicate ut test items
  operator/pkg/object/objects_test.go
Labels: ok-to-test, size/XS, release-notes-none

#46952 Remove github.com/stretchr/testify dependency
  go.mod
  pkg/adsc/adsc_test.go
Labels: ok-to-test, size/XS, release-notes-none

#46955 Update deps and simplify update_deps.sh getSha()
  bin/update_deps.sh
  docker/Dockerfile.distroless
  istio.deps
  prow/release-commit.sh
Labels: size/S, release-notes-none

#46939 [release-1.17] Pass rules to iptables-restore via stdin instead of a file
  cni/pkg/plugin/iptables.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin_dryrun_test.go
  releasenotes/notes/43945.yaml
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: size/L, release-notes-none

#46957 unskip some sidecar integ tests in the ambient suite
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none, area/ambient

#46898 Fix proxy UID/GID in Gateway templates
  manifests/charts/gateway/README.md
  manifests/charts/gateway/openshift-values.yaml
  manifests/charts/gateway/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istiod-remote/files/gateway-injection-template.yaml
  pkg/kube/inject/testdata/inject/gateway.yaml.injected
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: size/M, release-notes-none

#46954 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, release-notes-none

#46472 architecture: add ztunnel.md
  architecture/ambient/ztunnel.md
Labels: size/L, release-notes-none

#46963 fix DNSNoEndpointClusters metric
  pilot/pkg/model/push_context.go
  releasenotes/notes/46963.yaml
Labels: size/XS, cherrypick/release-1.17, cherrypick/release-1.18, cherrypick/release-1.19

#46966 [release-1.19] fix DNSNoEndpointClusters metric
  pilot/pkg/model/push_context.go
  releasenotes/notes/46963.yaml
Labels: size/XS, release-notes-none

#46962 Run bin/update_bin.sh on release-1.17
  docker/Dockerfile.distroless
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: size/S, release-notes-none

#46965 [release-1.18] fix DNSNoEndpointClusters metric
  pilot/pkg/model/push_context.go
  releasenotes/notes/46963.yaml
Labels: size/XS, release-notes-none

#46969 move missing endpoints log to buildCluster
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Labels: size/XS, release-notes-none

#46978 Fix issue with emiting uninitialized Guage metrics
  pkg/monitoring/gauge.go
  pkg/monitoring/monitoring_test.go
  pkg/monitoring/monitortest/test.go
  releasenotes/notes/gauge-empty-metrics.yaml
Labels: size/M, release-notes-none, cherrypick/release-1.19

#46979 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46981 gateway-api: update dependency for timeouts API
  go.mod
  go.sum
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
Labels: area/networking, size/M, release-notes-none

#46980 [release-1.19] Fix issue with emiting uninitialized Guage metrics
  pkg/monitoring/gauge.go
  pkg/monitoring/monitoring_test.go
  pkg/monitoring/monitortest/test.go
  releasenotes/notes/gauge-empty-metrics.yaml
Labels: size/M, release-notes-none

#46718 move filter before to prevent unneeded processing
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
Labels: size/M, release-notes-none

#46975 e2e: improve operator test
  tests/integration/operator/switch_cr_test.go
  tests/integration/operator/uninstall_test.go
Labels: area/test and release, size/S, release-notes-none

#46973 relax ttl validation to allow passive cookies
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/S, release-notes-none

#46984 Fix typo at name.go
  pkg/config/resource/name.go
Labels: size/XS, release-notes-none

#46992 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46997 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47003 Cleanup viper flag definitions
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/root.go
Labels: size/L, release-notes-none

#46945 Add ports to Workload data structure
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pkg/workloadapi/workload.pb.go
  pkg/workloadapi/workload.proto
Labels: size/XS, release-notes-none

#46989 add http cookie test case
  tests/integration/pilot/common/routing.go
Labels: size/M, release-notes-none

#46968 Fix ext authz deny all traffic if encountering error with the provider
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/extauthz.go
  pilot/pkg/security/authz/builder/testdata/http/custom-bad-out.yaml
  releasenotes/notes/46968.yaml
Labels: area/security, size/M

#47006 remove min istio version
  tests/integration/pilot/common/routing.go
Labels: size/M, release-notes-none

#45243 fix: istioctl remove all revisions of istio operator when not specify revision
  operator/cmd/mesh/operator-remove.go
  releasenotes/notes/45243.yaml
  tests/integration/operator/switch_cr_test.go
Labels: area/user experience, size/M, release-notes-none

#46258 Support default system namespace filtering for analyze
  istioctl/pkg/injector/injector-list.go
  pilot/pkg/config/file/store.go
  pkg/config/analysis/analyzers/injection/injection.go
  pkg/config/analysis/analyzers/service/portname.go
  pkg/config/analysis/analyzers/util/config.go
  pkg/config/analysis/local/istiod_analyze.go
  tools/bug-report/pkg/cluster/cluster.go
Labels: area/user experience, size/M, release-notes-none

#46863 move ambient install into framework
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/installer.go
  pkg/test/framework/components/namespace/kube.go
  tests/integration/ambient/main_test.go
  tests/integration/iop-ambient-test-defaults.yaml
Labels: size/M, release-notes-none

#47015 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47007 Clean up some install codes
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/pkg/name/name.go
  operator/pkg/object/objects.go
  pkg/config/analysis/analyzers/testdata/mtls-exports.yaml
  pkg/config/analysis/analyzers/testdata/mtls-global-dr-no-meshpolicy.yaml
  pkg/config/analysis/analyzers/testdata/mtls-ignores-istio-control-plane.yaml
  pkg/config/analysis/analyzers/testdata/mtls-ignores-system-namespaces.yaml
  pkg/config/analysis/analyzers/testdata/mtls-meshpolicy-permissive.yaml
  pkg/config/analysis/analyzers/testdata/mtls-meshpolicy.yaml
  pkg/config/analysis/analyzers/testdata/mtls-no-dr.yaml
  pkg/config/analysis/analyzers/testdata/mtls-no-policy.yaml
  pkg/config/analysis/analyzers/testdata/mtls-no-sidecar.yaml
  pkg/config/analysis/analyzers/testdata/mtls-with-port.yaml
Labels: size/XXL, release-notes-none

#47017 gateway-api: add support for HTTPRoute timeouts
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
Labels: area/networking, size/L, release-notes-none

#46899 Fix filter ordering and WASM NETWORK implementation
  pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/core/v1alpha3/tls.go
  releasenotes/notes/filter-order.yaml
Labels: size/XL

#47018 min k8s version for ambient suite
  pkg/test/framework/suite.go
  tests/integration/ambient/main_test.go
Labels: size/XS, release-notes-none

#47014 gateway-api: re-enable multi-mirrors conformance tests
  go.mod
  go.sum
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
Labels: area/test and release, area/networking, size/S, release-notes-none

#47020 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47021 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46994 Add values files for users to install ambient when using helm
  manifests/charts/istio-cni/ambient-values.yaml
  manifests/charts/istio-control/istio-discovery/ambient-values.yaml
  releasenotes/notes/helm-ambient.yaml
Labels: area/test and release, area/environments, size/M, area/ambient

#47023 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47024 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47026 Update Architecture Direct link
  operator/README.md
Labels: kind/docs, ok-to-test, size/XS, release-notes-none

#47019 Revert "add http cookie test case (#46989)"
  tests/integration/pilot/common/routing.go
Labels: size/M, release-notes-none

#47030 Revert "unskip some sidecar integ tests in the ambient suite"
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none

#46970 Push back invalid secret to prevent sds fetching timeout
  pilot/pkg/xds/sds.go
  releasenotes/notes/46868.yaml
Labels: size/S

#47029 fix shardKey comment
  pilot/pkg/model/endpointshards.go
Labels: size/XS, release-notes-none

#47031 Fix injected deployment gateway template for OpenShift
  manifests/charts/gateways/istio-egress/templates/injected-deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/injected-deployment.yaml
Labels: size/S, release-notes-none

#46964 [release-1.17] fix DNSNoEndpointClusters metric
  pilot/pkg/model/push_context.go
  releasenotes/notes/46963.yaml
Labels: size/XS, release-notes-none

#47032 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47033 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47034 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#46882 Fix delta workload bugs
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/workload.go
Labels: size/L, release-notes-none

#47035 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47028 Fix TestMeshNetworking flake
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/S, release-notes-none

#47022 Dual-stack: /healthz/ready should have both v4/v6 wildcard listeners
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
  pkg/test/framework/components/istio/istio.go
  pkg/test/framework/components/istio/kube.go
  tests/integration/pilot/gateway_test.go
  tools/packaging/common/envoy_bootstrap.json
Labels: area/networking, size/M, release-notes-none, area/dual-stack

#47038 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47040 Dual-stack: /stats/prometheus should have both v4/v6 listeners
  tests/integration/pilot/gateway_test.go
  tools/packaging/common/envoy_bootstrap.json
Labels: area/networking, ok-to-test, size/M, release-notes-none, area/dual-stack

#46915 targetRef implementation for RequestAuthentication
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/features/pilot.go
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/policyattachment.go
  pilot/pkg/model/policyattachment_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/security/authn/factory/factory.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  pilot/pkg/xds/endpoints/mtls_checker.go
  pkg/config/constants/constants.go
  pkg/test/framework/components/echo/echotest/run.go
  releasenotes/notes/46846.yaml
  tests/common/jwt/jwt_token.go
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/testdata/requestauthn/waypoint-jwt.yaml.tmpl
  tests/integration/security/jwt_test.go
  tests/integration/security/policy_attachment_only/jwt_gateway_test.go
  tests/integration/security/policy_attachment_only/main_test.go
  tests/integration/security/policy_attachment_only/testdata/requestauthn/gateway-api.yaml.tmpl
  tests/integration/security/policy_attachment_only/testdata/requestauthn/gateway-jwt.yaml.tmpl
  tests/integration/security/testdata/requestauthn/gateway-api.yaml.tmpl
  tests/integration/security/testdata/requestauthn/gateway-jwt.yaml.tmpl
Labels: area/environments, size/XXL, area/ambient

#44709 auto-register connected proxies at WorkloadGroup creation
  pilot/pkg/autoregistration/connections.go
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/autoregistration/controller_test.go
  pilot/pkg/autoregistration/internal/health/controller.go
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
  releasenotes/notes/45329.yaml
  tests/fuzz/autoregistration_controller_fuzzer.go
Labels: size/L

#47043 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none
