Repository istio/istio, pull requests merged in 2023-04, with the labels that each got.

#44203 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44064 controllers: modernize validating webhook controller
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kind/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/controller/controller_test.go
Labels: size/XL, release-notes-none

#44066 controllers: use kclient for MWC controller
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
Labels: size/M, release-notes-none

#44206 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#44210 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44171 [1.17] gateway deployment controller: handle backwards compatibility
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pkg/test/util/assert/assert.go
  releasenotes/notes/gateway-futureproof.yaml
Labels: size/L

#44187 Disable istio-ingressgateway in ambient profile
  manifests/profiles/ambient.yaml
  tests/integration/ambient/main_test.go
Labels: release-notes-none

#44217 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44221 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44202 add release-notes for grpc stats
  releasenotes/notes/grpc-stats.yaml
Labels: size/XS, cherrypick/release-1.17

#44220 gateway: remove internal annotation from propogating
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.38.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.17

#43837 GetProxyWorkloadLabels: check namespace properly
  pilot/pkg/serviceregistry/serviceentry/controller.go
Labels: size/S, release-notes-none

#44209 Refactor component struct for simplicity and extensibility
  operator/pkg/component/component.go
  operator/pkg/component/ztunnel.go
  operator/pkg/controlplane/control_plane_test.go
Labels: size/L, release-notes-none

#44222 [release-1.17] add release-notes for grpc stats
  releasenotes/notes/grpc-stats.yaml
Labels: size/XS, release-notes-none

#43993 Add Tag and Revision support to waypoints, gateway API.
  istioctl/cmd/waypoint.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pkg/revisions/tag_watcher.go
  tests/integration/ambient/bookinfo_test.go
Labels: size/L, release-notes-none

#44224 Fix ztunnel secret state in configdump
  istioctl/pkg/writer/ztunnel/configdump/configdump.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
  istioctl/pkg/writer/ztunnel/configdump/testdata/secretsummary.txt
Labels: area/user experience, size/S, release-notes-none, area/ambient

#44204 reject partial wildcard hosts in service entry for HTTPS protocol
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/44195.yaml
Labels: size/S

#44154 clean DefaultStatTags
  pkg/bootstrap/config.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: size/XXL, release-notes-none

#44241 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44216 [1.16] gateway deployment controller: handle backwards compatibility …
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/templates/service.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pkg/test/util/assert/assert.go
  releasenotes/notes/gateway-futureproof.yaml
Labels: size/L

#44226 Reuse defined const in BuildSecret function.
  security/pkg/k8s/secret/secret_util.go
  security/pkg/k8s/secret/secret_util_test.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
Labels: size/L, release-notes-none

#43878 Add ztunnel configdump and log to bugreport
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/util/ambient/util.go
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/cluster/cluster.go
  tools/bug-report/pkg/cluster/cluster_test.go
  tools/bug-report/pkg/common/common.go
  tools/bug-report/pkg/config/config.go
  tools/bug-report/pkg/content/content.go
  tools/bug-report/pkg/processlog/processlog.go
  tools/bug-report/pkg/processlog/processlog_test.go
Labels: area/test and release, size/L, release-notes-none, area/ambient

#44235 add release note for gateway deployment changes
  releasenotes/notes/gateway-api118.yaml
Labels: size/M

#44211 test: increase ut covrage for pkg/name
  operator/pkg/name/name_test.go
Labels: area/test and release, size/L, release-notes-none

#44243 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44250 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#44229 [1.17] gateway: remove internal annotation from propogating (#44220)
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/templates/service.yaml
Labels: size/XS, release-notes-none

#44251 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44253 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#44254 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#44258 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44255 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44261 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44262 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44257 gateway-api: future proof for 0.7.0
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/gateway_conformance_test.go
Labels: size/L, release-notes-none

#44270 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44271 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44238 kclient: refactor for easier usage
  pilot/pkg/bootstrap/istio_ca_test.go
  pilot/pkg/config/kube/crdclient/client_test.go
  pilot/pkg/config/kube/gateway/gatewayclass_test.go
  pilot/pkg/config/kube/ingress/controller_test.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/autoserviceexportcontroller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/network_test.go
  pilot/pkg/xds/workload_test.go
  pkg/config/schema/codegen/collections.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/kube/kclient/client.go
  pkg/kube/kclient/clienttest/direct.go
  pkg/kube/kclient/clienttest/test_helpers.go
  pkg/kube/kclient/helpers.go
  pkg/kube/kclient/index.go
  pkg/kube/kclient/interfaces.go
  pkg/kube/kclient/untyped.go
  pkg/kube/kubetypes/types.go
Labels: size/XL, release-notes-none

#44268 Speed up autoregistration lifecycle test
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/autoregistration/controller_test.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#44277 Manual update of common-files
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: area/test and release, size/XS, release-notes-none

#44278 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44027 docs: work with loki
  manifests/addons/gen.sh
  manifests/addons/values-grafana.yaml
  manifests/addons/values-loki.yaml
  samples/addons/grafana.yaml
  samples/addons/loki.yaml
  samples/open-telemetry/loki/REAME.md
  samples/open-telemetry/loki/iop.yaml
  samples/open-telemetry/loki/otel.yaml
  samples/open-telemetry/loki/telemetry.yaml
Labels: size/XL, release-notes-none

#44275 Bump ztunnel to hyper 1.0.0
  istio.deps
Labels: size/XS, release-notes-none

#44281 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44282 Automator: update common-files@release-1.17 in istio/istio@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#44283 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44284 fix(networking): support large direct response on gateways
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/test/xdstest/validate.go
Labels: area/networking, ok-to-test, size/M, release-notes-none

#44231 Integration Test for Istio custom GRPC count metrics
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
Labels: area/test and release, size/M, release-notes-none, cherrypick/release-1.16, cherrypick/release-1.17

#44260 bump go.mod before 1.18
  cni/pkg/taint/taintcontroller.go
  go.mod
  go.sum
  istioctl/pkg/multicluster/env.go
  istioctl/pkg/multicluster/env_test.go
  istioctl/pkg/multicluster/remote_secret.go
  licenses/github.com/antlr/antlr4/runtime/Go/antlr/v4/LICENSE
  licenses/github.com/klauspost/compress/internal/lz4ref/LICENSE
  licenses/github.com/stretchr/testify/LICENSE
  operator/pkg/helmreconciler/wait.go
  pilot/pkg/autoregistration/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
  pkg/kube/client.go
  pkg/kube/client_factory.go
  tests/binary/binaries_test.go
Labels: size/L, release-notes-none

#44159 Fixes selector logic of service and endpoint
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/util.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/util.go
  pilot/pkg/serviceregistry/util/workloadinstances/selector.go
  pkg/config/labels/instance.go
  pkg/config/labels/instance_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/44159.yaml
Labels: area/networking, ok-to-test, size/L

#44279 gateway: fix replacefullpath when request is to /
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: size/XS, release-notes-none

#44272 resolve test flake in CABundleWatcher
  pkg/webhooks/validation/controller/controller_test.go
Labels: size/S, release-notes-none

#44192 Retry when east-west gateway hostname resolution fails
  pilot/pkg/model/network.go
  pilot/pkg/model/network_test.go
  releasenotes/notes/gw-hostname-resolution.yaml
Labels: area/networking, size/L

#44295 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43541 gateway: skip un-managed types in deploymentcontroller
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
Labels: size/M, release-notes-none

#44298 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44296 Add nil-check for WASM validation
  pkg/config/validation/validation.go
Labels: size/XS, release-notes-none

#44297 kube-probe: avoid duplicate probe headers
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
Labels: size/M, release-notes-none

#44190 Refactor multi network manage
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/model/network.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/xds/debug.go
  pkg/config/mesh/networks_watcher.go
Labels: size/L, release-notes-none

#44301 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#44302 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44305 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#44306 Skip gateway.istio.io/controller-version annotation message in analyzer
  pkg/config/analysis/analyzers/maturity/maturity.go
  pkg/config/analysis/analyzers/testdata/misannotated.yaml
Labels: area/user experience, size/S, release-notes-none

#44312 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44303 Fix the metric and log reports for the dryrun gateway config
  pkg/kube/adapter.go
  pkg/webhooks/validation/server/monitoring.go
  pkg/webhooks/validation/server/server.go
  releasenotes/notes/44303.yaml
Labels: area/environments, size/M

#44314 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#44307 e2e: refactor grpc stats test
  pkg/test/framework/features/features.yaml
  tests/integration/telemetry/api/stats_test.go
  tests/integration/telemetry/common/stats.go
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/envoyfilter/nullvm/stats_filter_test.go
Labels: area/test and release, size/L, release-notes-none

#44320 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44330 update istio.io/api
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#44326 Fix type at shared.go
  operator/cmd/mesh/shared.go
Labels: ok-to-test, size/XS, release-notes-none

#44111 remove sync all
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/model/addressmap.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/serviceregistry/kube/controller/sync.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/xds/ep_filters_test.go
Labels: size/L, release-notes-none

#44246 Integration tests for ENABLE_ENHANCED_RESOURCE_SCOPING feature
  pkg/test/framework/components/echo/common/deployment/namespace.go
  pkg/test/framework/components/istio/eastwest.go
  pkg/test/framework/features/features.yaml
  pkg/test/framework/resource/settings.go
  tests/integration/pilot/multiplecontrolplanes/main_test.go
Labels: size/L, release-notes-none

#44319 Update deps 2023 04 10
  go.mod
  go.sum
  prow/release-commit.sh
Labels: area/test and release, size/XS, release-notes-none

#44339 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#44340 Use official 0.27.0 release
  go.mod
  go.sum
Labels: size/M, release-notes-none

#44338 reduced tokenWaitBackoff from 1 second to 10 millis
  istioctl/pkg/multicluster/remote_secret_test.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#44322 Fix the ztunnel iop specification for resources leads to a patch error.
  manifests/charts/ztunnel/templates/daemonset.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/ztunnel.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/ztunnel.golden.yaml
  operator/pkg/translate/translate.go
Labels: area/environments, size/L, release-notes-none, area/ambient

#44344 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44343 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44346 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#42922 Fix ServiceEntry WorkloadInstanceHandler for label change in Pods
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  releasenotes/notes/bug-fix-serviceentry-workloadselector.yaml
Labels: area/networking, ok-to-test, size/L, release-notes-none

#44359 Update BASE_VERSION to 1.17-2023-04-12T19-03-40
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#44358 Update BASE_VERSION to 1.16-2023-04-12T19-03-05
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#44357 Update BASE_VERSION to master-2023-04-12T19-02-00
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#44259 Add docs for Calico, set the annotation by default.
  manifests/charts/istio-cni/README.md
  manifests/charts/ztunnel/templates/daemonset.yaml
Labels: size/S, release-notes-none

#44373 update_deps.sh prior to release-1.18 branch cut
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#44365 gateway-api: fix naming override
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
Labels: area/networking, size/L, release-notes-none

#44380 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44381 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44360 validation: add small nil check
  pkg/config/validation/validation.go
Labels: size/XS, release-notes-none

#44287 [release-1.16] Integration Test for Istio custom GRPC count metrics
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
Labels: size/M, release-notes-none

#44389 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44292 Add a better check for ztunnel pod guess
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/pkg/util/ambient/util.go
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: area/user experience, size/M, release-notes-none, area/ambient

#44377 cni: drop experimental taint controller
  Makefile.core.mk
  cni/README.md
  cni/cmd/istio-cni-taint/README.md
  cni/cmd/istio-cni-taint/main.go
  cni/deployments/kubernetes/Dockerfile.install-cni
  cni/pkg/taint/README.md
  cni/pkg/taint/taint.go
  cni/pkg/taint/taint_test.go
  cni/pkg/taint/taint_test_helper.go
  cni/pkg/taint/taintcontroller.go
  cni/pkg/taint/taintcontroller_test.go
  manifests/charts/istio-cni/templates/clusterrole.yaml
  manifests/charts/istio-cni/templates/clusterrolebinding.yaml
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
  releasenotes/notes/drop-taint.yaml
  tools/docker.yaml
Labels: size/XXL

#44390 Automator: update common-files@release-1.16 in istio/istio@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#44379 kube: use protobuf in client
  pilot/pkg/features/pilot.go
  pkg/kube/client.go
  pkg/kube/util.go
Labels: size/S, release-notes-none

#44382 [release-1.17] gateway-api: fix naming override
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
Labels: area/networking, size/L, release-notes-none

#44393 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44395 Remove release note approval by release-managers
  CODEOWNERS
Labels: area/test and release, size/XS, release-notes-none

#44388 gateway: prevent duplicate `istio_authn` network filter in the filter chain
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/44388.yaml
Labels: area/networking, size/L, cherrypick/release-1.17

#44394 Add response headers for grpc
  pkg/test/echo/server/forwarder/grpc.go
Labels: area/networking, size/XS, release-notes-none

#44396 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44398 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#44400 Use k8s 1.27.0 as the default node image for integration testing
  prow/integ-suite-kind.sh
Labels: area/test and release, size/XS, release-notes-none

#44403 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44399 [release-1.17] gateway: prevent duplicate `istio_authn` network filter in the filter chain
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/44388.yaml
Labels: size/L, release-notes-none

#44397 remove deadcode from operator proto
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: size/XS, release-notes-none

#44288 [release-1.17] Integration Test for Istio custom GRPC count metrics
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
Labels: size/M, release-notes-none

#44405 fix:productpage build fail
  samples/bookinfo/src/productpage/requirements.txt
Labels: size/XS, release-notes-none

#44404 Run update_deps.sh
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: area/test and release, size/S, release-notes-none

#44406 chore: Fix function name in a comment
  operator/pkg/helmreconciler/prune.go
Labels: kind/docs, ok-to-test, size/XS, release-notes-none

#44407 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#44408 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44409 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44410 Remove hard coded Istio namespace
  istioctl/cmd/tag.go
  istioctl/pkg/tag/generate.go
  operator/cmd/mesh/install.go
Labels: area/environments, size/XS, release-notes-none

#44411 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43921 Analyze: add cert check for gateway credential
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/xds/sds.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/gateway/secret.go
  pkg/config/analysis/analyzers/testdata/gateway-secrets-validation.yaml
  pkg/config/analysis/analyzers/testdata/gateway-secrets.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/43921.yaml
Labels: size/L

#44419 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44345 Fix webhook issues in installation process
  operator/cmd/mesh/install.go
  releasenotes/notes/44345.yaml
Labels: area/environments, area/user experience, size/S

#44420 Set the WorkloadSelector of ServiceEntry only if the label is not empty
  pilot/pkg/serviceregistry/serviceentry/conversion.go
Labels: area/networking, size/XS, release-notes-none

#44417 Lazy evaluation of `controlPlane` to allow the lazy POD_NAME env var setting
  pilot/pkg/xds/xdsgen.go
Labels: size/S, release-notes-none

#44431 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44414 "istioctl pc route" output add "VHOST NAME"
  istioctl/pkg/writer/envoy/configdump/route.go
  releasenotes/notes/44414.yaml
Labels: ok-to-test, area/user experience, size/S

#44416 Temper severity of extraneous errors
  cni/pkg/ambient/iptables.go
Labels: area/user experience, size/XS, release-notes-none, area/ambient

#44421 Cleanup message.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
Labels: size/M, release-notes-none

#44440 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44436 update_deps for 1.18 branch cut
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
  prow/release-commit.sh
Labels: release-notes-none

#44441 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44442 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44438 fix wrong example for admin log
  istioctl/cmd/istiodconfig.go
Labels: size/XS, release-notes-none

#44428 add validation for empty prefix header match
  pkg/config/validation/validation_test.go
  pkg/config/validation/virtualservice.go
  pkg/config/validation/virtualservice_test.go
  releasenotes/notes/44424.yaml
Labels: area/networking, area/user experience, size/M

#44321 >fix `istioctl analyze` to panic when the server port in gateway is nil.
  pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  releasenotes/notes/fix-44318.yaml
Labels: area/user experience, size/S, release-notes-none

#44443 Fix missing gateway services
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/44439.yaml
Labels: area/networking, size/L, cherrypick/release-1.16, cherrypick/release-1.17

#44425 Add configurable scaling behavior for Istiod's HPA in helm chart
  manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/helm-configurable-scaling-behavior.yaml
Labels: ok-to-test, size/S

#44433 bug report: fix dry-run logic
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: area/user experience, size/M, release-notes-none

#44453 update admin log Use
  istioctl/cmd/istiodconfig.go
Labels: area/user experience, size/XS, release-notes-none

#44464 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44465 Fix error render type in bug-report issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: size/XS, release-notes-none

#44449 disable automount SA token only on tests with min istio revisions >= 1.16
  pkg/test/framework/components/echo/common/deployment/echos.go
Labels: area/test and release, size/XS, release-notes-none

#44450 Check expected http error
  cni/pkg/log/uds.go
  cni/pkg/monitoring/monitoring.go
  pilot/pkg/bootstrap/server.go
  pkg/istio-agent/xds_proxy.go
  pkg/network/error.go
  security/pkg/stsservice/server/server.go
Labels: size/M, release-notes-none

#43821 istioctl: Improve proxy-config all usability
  istioctl/cmd/proxyconfig.go
  istioctl/pkg/writer/compare/sds/writer.go
  istioctl/pkg/writer/envoy/configdump/cluster.go
  istioctl/pkg/writer/envoy/configdump/configdump.go
  istioctl/pkg/writer/envoy/configdump/endpoint.go
  istioctl/pkg/writer/envoy/configdump/listener.go
  istioctl/pkg/writer/envoy/configdump/route.go
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/emptyfilter_output.txt
  istioctl/pkg/writer/envoy/configdump/testdata/endpoint/portfilter_output.txt
  releasenotes/notes/43821.yaml
Labels: area/user experience, size/L

#44472 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44474 improve check-inject example output
  istioctl/cmd/checkinject.go
Labels: size/XS, release-notes-none

#43326 Fix `pc log -h` listed active loggers out of date
  istioctl/cmd/proxyconfig.go
Labels: area/user experience, size/M, release-notes-none

#44478 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#44476 fix confilict gateway analysis and add ut
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  pkg/config/analysis/analyzers/testdata/conflicting-gateways-invalid-port.yaml
Labels: area/user experience, size/M, release-notes-none

#44479 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#44482 operator: cleanup unused consts
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
  operator/pkg/helm/helm.go
Labels: size/S, release-notes-none

#44483 improve istioctl workload example
  istioctl/cmd/workload.go
Labels: area/user experience, size/S, release-notes-none

#44487 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none
