Repository istio/istio, pull requests merged in 2023-11, with the labels that each got.

#47415 [release-1.18] Add IPv6 wildcard for dualstack proxies and correct ipv6 wildcard
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pkg/config/constants/constants.go
  releasenotes/notes/serviceentry-dualstack.yaml
Labels: size/M

#47440 Sidecar resources using defaultEndpoint can use ::1 in all cases
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  releasenotes/notes/47412.yaml
Labels: area/networking, size/L, cherrypick/release-1.18, cherrypick/release-1.19, area/dual-stack, cherrypick/release-1.20

#47644 iptables: refactor to avoid global variables
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin_dryrun_test.go
  cni/pkg/plugin/redirect.go
  pkg/flag/flag.go
  pkg/flag/flag_test.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-clean-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/config/config_test.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/validation/validator.go
Labels: size/XL, release-notes-none

#47677 [release-1.20] Sidecar resources using defaultEndpoint can use ::1 in all cases
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  releasenotes/notes/47412.yaml
Labels: size/L, release-notes-none

#47688 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47689 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47690 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47691 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47675 [release-1.18] Sidecar resources using defaultEndpoint can use ::1 in all cases
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  releasenotes/notes/47412.yaml
Labels: size/L, release-notes-none

#47676 [release-1.19] Sidecar resources using defaultEndpoint can use ::1 in all cases
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  releasenotes/notes/47412.yaml
Labels: size/L, release-notes-none

#47673 use static fake JWKS
  go.mod
  go.sum
  licenses/github.com/lestrrat-go/httprc/LICENSE
  licenses/github.com/lestrrat-go/jwx/v2/LICENSE
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: area/security, size/L, release-notes-none

#47683 remove legacy exclude
  go.mod
Labels: size/XS, release-notes-none

#47699 [release-1.20] bump gateway api version to 1.0.0 and cherry-pick 47469
  cni/pkg/repair/repair_test.go
  common/config/.golangci.yml
  go.mod
  go.sum
  istioctl/pkg/waypoint/testdata/waypoint/combined-gateway
  istioctl/pkg/waypoint/waypoint.go
  licenses/github.com/klauspost/compress/snappy/xerial/LICENSE
  licenses/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  licenses/google.golang.org/appengine/LICENSE
  licenses/sigs.k8s.io/yaml/LICENSE
  licenses/sigs.k8s.io/yaml/goyaml.v2/LICENSE
  licenses/sigs.k8s.io/yaml/goyaml.v3/LICENSE
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/model/network.go
  pilot/pkg/model/push_context.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pkg/kube/kclient/client_test.go
  pkg/maps/maps.go
  pkg/monitoring/monitoring.go
  pkg/slices/slices.go
  pkg/slices/slices_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
  tools/golangci-override.yaml
Labels: size/XXL, release-notes-none

#47678 [add] tolerations field to istiod
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  releasenotes/notes/add-tolerations-field-to-istiod.yaml
Labels: ok-to-test, size/S

#47685 Remove meaningless profile condition in ParseYAMLFiles
  operator/pkg/manifest/shared.go
Labels: ok-to-test, size/XS, release-notes-none

#47679 [release-1.20] Update deps
  LICENSE
  prow/release-commit.sh
Labels: size/L, release-notes-none

#47424 Trigger workload cert signing immediately after root cert changed
  pkg/security/security.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: size/M, release-notes-none, cherrypick/release-1.20

#47701 [release-1.20] Trigger workload cert signing immediately after root cert changed
  pkg/security/security.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
Labels: size/M, release-notes-none

#47702 Support sidecarContainers for bug-report
  tools/bug-report/pkg/cluster/cluster.go
Labels: area/user experience, size/S, release-notes-none

#47703 Fix istiod and proxy versions are incorrect in bug report
  releasenotes/notes/47703.yaml
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: area/user experience, size/S

#47664 pilot: enable external name alias on-by-default
  pilot/pkg/features/pilot.go
  releasenotes/notes/external-name-on.yaml
Labels: size/M, release-notes-none

#47628 service entry: warn on ignored targetPort
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/S, release-notes-none

#47504 Drop unsafe usage in mesh config
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pkg/config/mesh/watcher.go
  pkg/config/mesh/watcher_test_utils.go
Labels: size/M, release-notes-none

#47710 [release-1.19] Fix tag list output command not working
  istioctl/pkg/tag/tag.go
  releasenotes/notes/47705.yaml
Labels: size/S, release-notes-none

#47704 Fix header present match
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/header-present.yaml
Labels: size/M

#47714 Fix typo 'proxywhen'
  pilot/cmd/pilot-agent/options/options.go
Labels: ok-to-test, size/XS, release-notes-none, cherrypick/release-1.20

#47722 gateway-api: attached routes conformance test fix
  go.mod
  go.sum
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.20

#47729 iptables: stop panicing in leaf functions
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: size/M, release-notes-none

#47726 add argo ambient ref arch to samples
  CODEOWNERS
  bin/check_samples.sh
  samples/ambient-argo/README.md
  samples/ambient-argo/application/application.yaml
  samples/ambient-argo/application/bookinfo-versions.yaml
  samples/ambient-argo/application/details-waypoint.yaml
  samples/ambient-argo/application/details.yaml
  samples/ambient-argo/application/ingress-gateway.yaml
  samples/ambient-argo/application/namespace.yaml
  samples/ambient-argo/application/productpage.yaml
  samples/ambient-argo/application/ratings.yaml
  samples/ambient-argo/application/reviews-waypoint.yaml
  samples/ambient-argo/application/reviews.yaml
  samples/ambient-argo/application/route-reviews-90-10.yaml
  samples/ambient-argo/documentation/Ambient Upgrade - Strategies.png
  samples/ambient-argo/documentation/argo-reference-arch.dot
  samples/ambient-argo/documentation/argo-reference-arch.svg
  samples/ambient-argo/istio/cni.yaml
  samples/ambient-argo/istio/control-plane-appset.yaml
  samples/ambient-argo/istio/extras.yaml
  samples/ambient-argo/istio/tags.yaml
  samples/ambient-argo/istio/ztunnel.yaml
  samples/ambient-argo/meta-application.yaml
  samples/ambient-argo/tag-chart/Chart.yaml
  samples/ambient-argo/tag-chart/templates/mutatingwebhooks.yaml
  samples/ambient-argo/tag-chart/templates/shimservice.yaml
  samples/ambient-argo/tag-chart/templates/validatingwebhook.yaml
  samples/ambient-argo/tag-chart/values.yaml
Labels: size/XXL, release-notes-none

#47712 istioctl bug-report: Speed improvement from concurrency limiting
  releasenotes/notes/bug-report-speedup.yaml
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/bugreport/flags.go
  tools/bug-report/pkg/config/config.go
  tools/bug-report/pkg/kubeclient/kubeclient.go
  tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
Labels: ok-to-test, size/M

#47694 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47730 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#47731 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47733 update dependency gorilla
  go.mod
  go.sum
  licenses/github.com/gorilla/mux/LICENSE
  licenses/github.com/gorilla/websocket/LICENSE
Labels: area/security, ok-to-test, size/M, release-notes-none

#47736 [release-1.19] Fix header present match (#47704)
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/header-present.yaml
Labels: size/M

#47737 Fix header present match (#47704)
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/header-present.yaml
Labels: size/M

#47749 prioritize using istio-ca-secret even if USE_CACERTS_FOR_SELF_SIGNED_…
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/generate_csr.go
Labels: size/L, release-notes-none

#47765 Update BASE_VERSION to 1.19-2023-11-06T19-02-47
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47766 Update BASE_VERSION to 1.17-2023-11-06T19-02-26
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47764 Update BASE_VERSION to 1.18-2023-11-06T19-01-12
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47767 Update BASE_VERSION to 1.20-2023-11-06T19-03-14
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47768 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47770 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47758 1.18: Handle null values in istio-discovery template (#45955)
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istiod-remote/templates/configmap.yaml
  releasenotes/notes/helm_chart_istiodiscovery_defaultvalues.yaml
Labels: ok-to-test, size/M

#47772 Fix TestAmbientIndex_ServiceEntry_DisableK8SServiceSelectWorkloadEntries flake
  pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
Labels: area/test and release, area/networking, size/XS, release-notes-none

#47776 remove never enetered code
  pilot/pkg/networking/core/v1alpha3/listener.go
Labels: size/XS, release-notes-none

#47780 fix dns failure comment
  pkg/dns/client/monitoring.go
Labels: size/XS, release-notes-none

#47778 add more logs to consistent hash tests
  tests/integration/pilot/common/routing.go
Labels: size/M, release-notes-none

#47318 make the auto scale behave in gateway configurable
  manifests/charts/gateway/templates/hpa.yaml
  manifests/charts/gateway/values.yaml
  releasenotes/notes/47318.yaml
Labels: area/environments, size/S

#47762 Drop redundant test case in `TestServicesDiff`
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
Labels: area/test and release, size/S, release-notes-none

#47787 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47782 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47788 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47790 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47795 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47793 Fix RBAC permissions for status reporter
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
Labels: size/S, release-notes-none

#47796 Update deps for 1.19.4
  docker/Dockerfile.distroless
  istio.deps
  prow/release-commit.sh
Labels: area/test and release, size/XS, release-notes-none

#47789 Fix TestAmbientIndex_WorkloadEntries_DisableK8SServiceSelectWorkloadEntries flake
  pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
Labels: area/networking, size/XS, release-notes-none

#47799 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47775 Refactor a little in HelmReconciler.ApplyManifest
  operator/cmd/mesh/manifest_shared_test.go
  operator/cmd/mesh/shared.go
  operator/pkg/helmreconciler/apply.go
  operator/pkg/helmreconciler/reconciler.go
  tests/fuzz/helm_reconciler_fuzzer.go
Labels: area/environments, ok-to-test, size/M, release-notes-none

#47800 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47805 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47806 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47807 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47808 remove error message in istioctl operator
  operator/cmd/operator/main.go
Labels: area/environments, size/XS, release-notes-none

#47798 Honor test flags in eastwest gateway deployment
  pkg/test/framework/components/istio/eastwest.go
Labels: size/XS, release-notes-none

#47809 gateway-api: enable static addresses conformance test
  pilot/pkg/config/kube/gateway/context.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/eastwest-labelport.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest-tlsoption.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/waypoint.status.yaml.golden
  tests/integration/pilot/gateway_conformance_test.go
Labels: size/M, release-notes-none

#47812 remove duplicate calls to needsPortMatch func
  pilot/pkg/model/sidecar.go
Labels: area/networking, size/S, release-notes-none

#47811 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47815 Add logging for service difference across clusters
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: size/XS, release-notes-none

#47615 istioctl: add waypoint integration test
  tests/integration/ambient/bookinfo_test.go
  tests/integration/ambient/waypoint_test.go
Labels: area/test and release, area/user experience, size/L, release-notes-none

#47641 add e2e test for cacert rotation
  pkg/test/framework/features/features.yaml
  samples/certs/README.md
  samples/certs/root-cert-combined.pem
  tests/integration/security/cacert_rotation/main_test.go
  tests/integration/security/util/cert/cert.go
Labels: area/test and release, area/security, size/L, release-notes-none

#47819 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47538 Fix user created tag webhook being deleted by installer
  istioctl/pkg/tag/generate.go
  istioctl/pkg/tag/generate_test.go
  istioctl/pkg/tag/tag.go
  releasenotes/notes/47538.yaml
Labels: size/M, cherrypick/release-1.19, cherrypick/release-1.20

#47826 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47823 [release-1.19] Fix user created tag webhook being deleted by installer
  istioctl/pkg/tag/generate.go
  istioctl/pkg/tag/generate_test.go
  istioctl/pkg/tag/tag.go
  releasenotes/notes/47538.yaml
Labels: size/M, release-notes-none

#47801 Fix internal-debug syncz not working with agent, and add support for debug type `config_dump `
  istioctl/pkg/internaldebug/internal-debug.go
  tests/integration/pilot/piggyback_test.go
Labels: area/networking, area/user experience, size/S, release-notes-none

#47825 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#47813 Fix some delta xds proxy logics
  pkg/istio-agent/xds_proxy_delta.go
Labels: area/networking, size/L, release-notes-none

#47837 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47831 Improve validate error message
  istioctl/pkg/validate/validate.go
Labels: area/user experience, size/XS, release-notes-none

#47840 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47771 [release-1.20] Update deps
  go.mod
  go.sum
  prow/release-commit.sh
Labels: size/S, release-notes-none

#47839 fix cacert_rotation TestReachability flake
  tests/integration/security/cacert_rotation/main_test.go
Labels: area/test and release, size/XS, release-notes-none

#47817 Improve initServiceaccount by calculating once per service and reducing the lock time
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_cache.go
  pilot/pkg/networking/grpcgen/cds.go
  pkg/spiffe/spiffe.go
Labels: size/L, release-notes-none

#47845 reduce fallback scope
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/virtualservice.go
Labels: area/networking, area/perf and scalability, size/S, release-notes-none

#47711 [release-1.20] Fix tag list output command not working
  istioctl/pkg/tag/tag.go
  releasenotes/notes/47705.yaml
Labels: size/S, release-notes-none

#47728 [release-1.20] gateway-api: attached routes conformance test fix
  go.mod
  go.sum
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/S, release-notes-none

#47735 [release-1.20] Fix header present match (#47704)
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/header-present.yaml
Labels: size/M

#47769 [release-1.20] prioritize using istio-ca-secret even if USE_CACERTS_FOR_SELF_SIGNED_…
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/util/generate_cert_test.go
  security/pkg/pki/util/generate_csr.go
Labels: size/L, release-notes-none

#47824 [release-1.20] Fix user created tag webhook being deleted by installer
  istioctl/pkg/tag/generate.go
  istioctl/pkg/tag/generate_test.go
  istioctl/pkg/tag/tag.go
  releasenotes/notes/47538.yaml
Labels: size/M, release-notes-none

#47851 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47854 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47855 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47818 istioctl: add a flag to delete all waypoints in a namespace
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/47818.yaml
  tests/integration/ambient/waypoint_test.go
Labels: area/user experience, size/L

#47859 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47861 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47852 waypoint support ProxyMetadata
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: size/XS, release-notes-none

#47865 Update BASE_VERSION to 1.20-2023-11-15T19-06-47
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47864 Update BASE_VERSION to 1.18-2023-11-15T19-03-21
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47866 Update BASE_VERSION to 1.17-2023-11-15T19-04-49
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47863 Update BASE_VERSION to master-2023-11-15T19-01-44
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47868 Reuse a variable, don't call a function several times
  pkg/test/framework/components/echo/kube/deployment.go
Labels: size/XS, release-notes-none

#47869 Update BASE_VERSION to 1.19-2023-11-15T22-11-23
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47870 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47841 Use sets.String replace sets.Set[string]
  cni/pkg/ambient/informers.go
  cni/pkg/ambient/net.go
  cni/pkg/ambient/net_linux.go
  cni/pkg/ambient/server.go
  cni/pkg/ebpf/server/redirectionServer_linux.go
  cni/pkg/install/binaries.go
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/model/network_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pkg/revisions/tag_watcher.go
  pkg/revisions/tag_watcher_test.go
  pkg/util/sets/set.go
  pkg/util/sets/set_test.go
  tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
Labels: ok-to-test, size/M, release-notes-none

#47681 Add topology.istio.io/network label to waypoint if exists
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
  pkg/kube/inject/template.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/47681.yaml
Labels: area/networking, size/L

#47872 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47874 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47875 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47376 move stateful set filter to per route filter
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: size/L, release-notes-none

#47848 leader election: fix lease locks stealing each other
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/leaderelection/leaderelection_test.go
Labels: size/M, release-notes-none, cherrypick/release-1.18, cherrypick/release-1.19, cherrypick/release-1.20

#47888 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47887 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47896 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47884 [release-1.20] leader election: fix lease locks stealing each other
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/leaderelection/leaderelection_test.go
Labels: size/M, release-notes-none

#47877 istioctl: fix dashboard namespace flag usage
  istioctl/pkg/dashboard/dashboard.go
  istioctl/pkg/dashboard/dashboard_test.go
  releasenotes/notes/47877.yaml
Labels: area/user experience, size/M

#47879 istioctl: support displaying network info in workload configdump summary
  istioctl/pkg/util/configdump/workload.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
  istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary.txt
  istioctl/pkg/writer/ztunnel/configdump/workload.go
Labels: area/user experience, size/M, release-notes-none

#47883 [release-1.19] leader election: fix lease locks stealing each other
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/leaderelection/leaderelection_test.go
Labels: size/M, release-notes-none

#47894 Fix telemetry templates
  manifests/charts/istio-control/istio-discovery/templates/_helpers.tpl
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.18.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.19.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.20.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.21.yaml
  manifests/charts/istiod-remote/templates/_helpers.tpl
  manifests/charts/istiod-remote/templates/configmap.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.18.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.19.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.20.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.21.yaml
  releasenotes/notes/fix-stackdriver-install.yaml
Labels: ok-to-test, size/L

#47850 Remove runAs from test deployment files
  pkg/test/echo/docker/Dockerfile.app
  pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
  pkg/test/framework/components/echo/kube/templates/deployment.yaml
  pkg/test/framework/components/echo/kube/testdata/basic.yaml
  pkg/test/framework/components/echo/kube/testdata/disable-automount-sa.yaml
  pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
  pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
  pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/proxyless-custom-image.yaml
  pkg/test/framework/components/echo/kube/testdata/proxyless.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
  samples/grpc-echo/grpc-echo.yaml
Labels: size/M, release-notes-none

#47873 fix multicluster leader election regression
  pilot/pkg/leaderelection/leaderelection.go
  releasenotes/notes/multicluster-leader-election.yaml
Labels: size/XS

#47897 Fix netns path invoking from cni plugin
  cni/pkg/ambient/net_linux.go
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: size/S, release-notes-none, area/ambient

#47908 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47909 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47900 Wrap IsPodEnrolledInDp for iptables and ebpf mode
  cni/pkg/ambient/informers.go
  cni/pkg/ambient/net_linux.go
  cni/pkg/ebpf/server/redirectionServer_linux.go
Labels: size/M, release-notes-none, area/ambient

#47907 Update multicluster-leader-election.yaml
  releasenotes/notes/multicluster-leader-election.yaml
Labels: size/XS, release-notes-none

#47913 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47898 Fix the custom injection on OpenShift
  pkg/kube/inject/testdata/inject/proxy-override.yaml
  pkg/kube/inject/testdata/inject/proxy-override.yaml.injected
  pkg/kube/inject/webhook.go
  releasenotes/notes/fix-custom-injection-openshift.yaml
Labels: size/M, cherrypick/release-1.20

#47860 Drop `installed-state` from installation
  Makefile.core.mk
  istioctl/cmd/root.go
  istioctl/pkg/revision/revision.go
  istioctl/pkg/revision/revision_test.go
  istioctl/pkg/tag/tag.go
  istioctl/pkg/tag/tag_test.go
  istioctl/pkg/tag/util.go
  manifests/charts/base/crds/crd-operator.yaml
  manifests/charts/istiod-remote/templates/crd-operator.yaml
  operator/cmd/mesh/install.go
  operator/cmd/mesh/manifest_shared_test.go
  operator/cmd/mesh/shared.go
  operator/pkg/helmreconciler/common.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/name/name.go
  releasenotes/notes/drop-iop.yaml
  tests/integration/operator/verify_test.go
  tests/integration/pilot/revisioncmd/main_test.go
  tests/integration/pilot/revisioncmd/revision_view_test.go
Labels: size/XXL

#47914 [release-1.20] Fix the custom injection on OpenShift
  pkg/kube/inject/testdata/inject/proxy-override.yaml
  pkg/kube/inject/testdata/inject/proxy-override.yaml.injected
  pkg/kube/inject/webhook.go
  releasenotes/notes/fix-custom-injection-openshift.yaml
Labels: size/M, release-notes-none

#47920 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47923 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47929 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47930 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#47931 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47902 [release-1.19] fix multicluster leader election regression
  pilot/pkg/leaderelection/leaderelection.go
  releasenotes/notes/multicluster-leader-election.yaml
Labels: size/S, release-notes-none

#47903 [release-1.18] fix multicluster leader election regression
  pilot/pkg/leaderelection/leaderelection.go
  releasenotes/notes/multicluster-leader-election.yaml
Labels: size/S, release-notes-none

#47935 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47904 [release-1.20] fix multicluster leader election regression
  pilot/pkg/leaderelection/leaderelection.go
  releasenotes/notes/multicluster-leader-election.yaml
Labels: size/S, release-notes-none

#47937 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47936 Automator: update common-files@release-1.20 in istio/istio@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47938 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47944 Install ztunnel after istio-cni
  operator/pkg/helmreconciler/common.go
Labels: area/environments, size/XS, release-notes-none, area/ambient

#47945 [release-1.18] Adjust DNS Proxy CNAME wildcard response to be compatible with glibc and musl
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
  releasenotes/notes/47290.yaml
Labels: size/M

#47922 Make httpbin samples work on OpenShift
  releasenotes/notes/make-httpbin-work-ocp.yaml
  samples/extauthz/local-ext-authz.yaml
  samples/httpbin/httpbin-nodeport.yaml
  samples/httpbin/httpbin-vault.yaml
  samples/httpbin/httpbin.yaml
Labels: size/M

#47407 envoy: use upstream JWT filter instead of the custom Istio extension
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/matcher/metadata.go
  pilot/pkg/security/authz/matcher/metadata_test.go
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
  pilot/pkg/security/authz/model/model.go
  pilot/pkg/security/authz/model/model_test.go
  pilot/pkg/security/authz/model/util.go
  pilot/pkg/xds/filters/filters.go
  releasenotes/notes/extended-jwt.yaml
  tests/fuzz/pilot_security_fuzzer.go
Labels: size/XL

#47950 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47843 optimize ambient server event response
  cni/pkg/ambient/informers.go
  cni/pkg/ambient/informers_test.go
  cni/pkg/ambient/net.go
  cni/pkg/ambient/server.go
Labels: ok-to-test, size/L, release-notes-none

#47899 istioctl: fix dashboard namespace
  istioctl/pkg/dashboard/dashboard.go
  istioctl/pkg/dashboard/dashboard_test.go
Labels: area/user experience, size/M, release-notes-none
