Repository istio/istio, pull requests merged in 2023-10, with the labels that each got.

#47169 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47147 add gateway mirrors test
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
Labels: size/M, release-notes-none

#47168 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#47171 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47114 Change operator api to support dual-stack enablement of Istio components
  manifests/charts/base/templates/services.yaml
  manifests/charts/base/values.yaml
  manifests/charts/gateway/templates/service.yaml
  manifests/charts/gateways/istio-egress/templates/service.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/templates/service.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/templates/service.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/templates/services.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/44017.yaml
Labels: area/test and release, area/environments, area/networking, size/L, area/dual-stack

#47170 EnableK8SServiceSelectWorkloadEntries in Ambient
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
Labels: size/M, release-notes-none, area/ambient

#47165 Add more options for setting up kind clusters
  samples/kind-lb/README.md
  samples/kind-lb/setupkind.sh
Labels: area/test and release, size/L, release-notes-none

#47173 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#46800 Gated feature flag to add a secondary outbound bind for IPv6-only clusters
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  releasenotes/notes/46719.yaml
Labels: area/networking, ok-to-test, size/M

#47175 minor update to allow stronger assertion about sidecar to waypoint
  tests/integration/ambient/baseline_test.go
Labels: size/XS, release-notes-none, area/ambient

#47179 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#47178 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none

#47182 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47181 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47183 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47184 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47185 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#47186 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47188 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47191 Update BASE_VERSION to master-2023-10-04T19-01-17
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47190 Update BASE_VERSION to 1.17-2023-10-04T19-01-18
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47192 Update BASE_VERSION to 1.18-2023-10-04T19-04-08
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47194 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47196 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47189 Improve various validations
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/M, release-notes-none

#47197 optimize: select virtual services
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/config/aggregate/config.go
  pilot/pkg/model/destination_rule.go
  pilot/pkg/model/virtualservice.go
  pilot/pkg/networking/apigen/apigen.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceentry/store_test.go
  pilot/pkg/serviceregistry/serviceentry/util.go
  pkg/config/model.go
Labels: area/perf and scalability, size/M, needs-ok-to-test, release-notes-none

#46983 Targetref Implementation for WASMPlugin
  pilot/pkg/model/authentication.go
  pilot/pkg/model/extensions.go
  pilot/pkg/model/extensions_test.go
  pilot/pkg/model/policyattachment.go
  pilot/pkg/model/policyattachment_test.go
  pilot/pkg/model/push_context.go
  releasenotes/notes/46845.yaml
  tests/integration/telemetry/api/setup_test.go
  tests/integration/telemetry/api/testdata/gateway-api.yaml
  tests/integration/telemetry/api/testdata/gateway-wasm-filter.yaml
  tests/integration/telemetry/api/wasmplugin_test.go
Labels: size/L, area/ambient

#47203 bump some test timeouts
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pkg/config/mesh/kubemesh/watcher_test.go
Labels: size/XS, release-notes-none

#47204 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47206 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47208 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47210 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47200 [release-1.18] Support additional address in listeners output (#44648)
  istioctl/pkg/writer/envoy/configdump/listener.go
  istioctl/pkg/writer/envoy/configdump/listener_test.go
  releasenotes/notes/istioctl-additional-address.yaml
Labels: area/test and release, area/user experience, size/M

#47212 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47209 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47220 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47217 Fix istioctl build failed
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
Labels: area/test and release, size/S, release-notes-none

#47223 Automator: update common-files@release-1.17 in istio/istio@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47224 Automator: update istio/client-go@release-1.18 dependency in istio/istio@release-1.18
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47225 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47222 Automator: update common-files@release-1.18 in istio/istio@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47228 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47231 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47233 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47232 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47145 fix: typo
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: ok-to-test, size/XS, release-notes-none

#47239 Automator: update ztunnel@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47240 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47241 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47243 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47244 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47045 Support auto-detecting pilot monitoring port in istioctl commands
  pkg/kube/client.go
  pkg/kube/client_test.go
  releasenotes/notes/47045.yaml
Labels: area/user experience, size/M

#47237 minor optimize: replace with set
  pilot/pkg/status/resourcelock.go
Labels: area/environments, size/S, release-notes-none

#47048 add http cookie test case
  pkg/test/echo/server/forwarder/config.go
  pkg/test/echo/server/forwarder/http.go
  pkg/test/echo/server/forwarder/util.go
  pkg/test/framework/components/echo/calloptions.go
  pkg/test/framework/components/echo/common/call.go
  tests/integration/pilot/common/routing.go
Labels: size/L, release-notes-none

#47242 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47245 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47251 fix insecureRegistries set
  pilot/cmd/pilot-agent/options/agent.go
Labels: size/XS, release-notes-none

#47235 add test for empty customHost
  pilot/pkg/bootstrap/server_test.go
Labels: size/S, release-notes-none

#47250 Fix client get istio version logic
  pkg/kube/client.go
Labels: area/user experience, size/M, release-notes-none

#47215 fix multiple header matches in root vs
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
  releasenotes/notes/47148.yaml
Labels: size/M

#47258 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47262 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47152 Allow setting priorityClassName in Istio gateway helm chart
  manifests/charts/gateway/templates/deployment.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
Labels: area/environments, ok-to-test, size/S, release-notes-none

#47246 Fix istioctl using crd watcher logging issue
  istioctl/pkg/root/root.go
Labels: area/user experience, size/XS, release-notes-none

#47267 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47271 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47081 fix auto allocate invalid ip allocation
  pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/xds/nds_test.go
  releasenotes/notes/47081.yaml
Labels: size/L

#47276 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47277 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47279 Update golang.org/x/net
  go.mod
  go.sum
Labels: area/test and release, size/M, release-notes-none

#47281 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47282 Update grpc-go
  go.mod
  go.sum
Labels: area/test and release, size/M, release-notes-none

#47289 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47284 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47288 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47291 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47292 Automator: update common-files@release-1.17 in istio/istio@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47286 [release-1.18] Update golang.org/x/net and grpc-go
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
  tests/integration/pilot/forwardproxy/envoy_config_generator.go
Labels: area/test and release, size/M, release-notes-none

#47247 Fix the problem of creating temp files but not deleting them by directly applying yaml string
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/tag/generate.go
  pkg/kube/client.go
Labels: size/M, release-notes-none

#47287 [release-1.19] Update golang.org/x/net and grpc-go
  go.mod
  go.sum
Labels: size/M, release-notes-none

#47297 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47294 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47293 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47285 [release-1.17] Update golang.org/x/net and grpc-go
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
  tests/integration/pilot/forwardproxy/envoy_config_generator.go
Labels: area/test and release, size/L, release-notes-none

#47299 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47296 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47295 Automator: update common-files@release-1.18 in istio/istio@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#47298 Automator: update istio/client-go@release-1.18 dependency in istio/istio@release-1.18
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#47099 regional failover to work with failover priority
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  pilot/pkg/serviceregistry/util/label/label.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/47099.yaml
Labels: area/networking, ok-to-test, size/L

#47300 Waypoint support global proxy image value
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/47300.yaml
Labels: area/environments, size/S

#47304 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47252 Improve proxy-config log command with envoy all loggers format
  istioctl/pkg/proxyconfig/proxyconfig.go
  releasenotes/notes/47252.yaml
Labels: area/user experience, size/S

#47311 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47314 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47257 Revert "Temporarily remove eBPF impl pending CNCF guidance (#45162)"
  cni/pkg/ebpf/app/ambient_redirect.bpf.c
  cni/pkg/ebpf/app/vmlinux.h
  cni/pkg/ebpf/server/ambient_redirect_bpf.go
  cni/pkg/ebpf/server/ambient_redirect_bpf.o
  cni/pkg/ebpf/server/redirectionServer_linux.go
  releasenotes/notes/cncf-ebpf-enable.yaml
Labels: size/XL, area/ambient

#47172 Add feature flag for merged cacerts secret
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/features/pilot.go
  security/pkg/pki/ca/ca.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
Labels: size/L, release-notes-none

#47317 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47316 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47319 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47290 Adjust DNS Proxy CNAME wildcard response to be compatible with glibc and musl
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
  releasenotes/notes/47290.yaml
Labels: area/networking, ok-to-test, size/M

#47323 [release-1.19] Adjust DNS Proxy CNAME wildcard response to be compatible with glibc and musl
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
  releasenotes/notes/47290.yaml
Labels: size/M, release-notes-none

#47327 improve auto allocation comments
  pilot/pkg/serviceregistry/serviceentry/controller.go
Labels: size/XS, release-notes-none

#47218 Lazy load default namespace for istioctl
  istioctl/cmd/root.go
  istioctl/pkg/analyze/analyze.go
  istioctl/pkg/cli/context.go
  istioctl/pkg/cli/option.go
  istioctl/pkg/dashboard/dashboard.go
  releasenotes/notes/47218.yaml
Labels: area/user experience, size/M

#47325 Update spire-agent image to match spire-server
  samples/security/spire/spire-quickstart.yaml
Labels: kind/docs, size/XS, release-notes-none

#47330 Update BASE_VERSION to master-2023-10-12T19-01-47
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47331 Update BASE_VERSION to 1.18-2023-10-12T19-01-45
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47332 Update BASE_VERSION to 1.17-2023-10-12T19-03-57
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47201 Bump api manually to fix build issues
  go.mod
  go.sum
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/L, release-notes-none

#47205 tcp MX: enable WDS fallback
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pilot/pkg/features/pilot.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster_tls.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/xds/filters/filters.go
  pkg/bootstrap/config.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/installer.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  releasenotes/notes/wds.yaml
  tests/integration/iop-wds.yaml
  tests/integration/telemetry/common/stats.go
Labels: size/M

#47337 envoy: replace connect_authority with set_filter_state
  go.mod
  go.sum
  istio.deps
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/xds/filters/filters.go
  pkg/config/xds/filter_types.gen.go
Labels: size/M, release-notes-none

#47339 Bump iptables image to fix glibc
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/XS, release-notes-none

#47010 clean up delta xds
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/workload.go
Labels: size/M, release-notes-none

#47343 Update BASE_VERSION to 1.19-2023-10-13T03-27-30
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#47344 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47345 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47349 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47350 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47353 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47161 Clarify telemetry deployment namespace
  samples/open-telemetry/tracing/README.md
Labels: kind/docs, ok-to-test, size/S, release-notes-none

#47199 Fix ambient CNI
  manifests/profiles/ambient.yaml
  operator/pkg/util/merge_iop.go
  tests/integration/base.yaml
Labels: size/XS, release-notes-none

#47358 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47361 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47360 [release-1.19] Clarify telemetry deployment namespace
  samples/open-telemetry/tracing/README.md
Labels: size/S, release-notes-none

#47356 manifest generate: respect cluster-specific flag
  operator/cmd/mesh/manifest-generate.go
Labels: size/S, release-notes-none

#47363 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47365 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47367 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47369 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#47368 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47370 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47347 move cors policy to typed per filter config
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
Labels: area/networking, size/M, release-notes-none

#47009 don't trigger full push for none visibility K8s service
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: area/networking, size/M, release-notes-none

#47382 fix telemetry discovery test
  tests/integration/iop-wds.yaml
Labels: size/XS, release-notes-none

#47385 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47374 Skip invalid authz tests
  pilot/pkg/security/authz/builder/fuzz_test.go
Labels: size/S, release-notes-none

#47380 Drop new verbose log to debug level
  pilot/pkg/config/kube/gateway/context.go
Labels: size/XS, release-notes-none

#47387 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47388 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47392 cni: 1.19 cherrypicks
  cni/cmd/istio-cni/main.go
  cni/pkg/config/config.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/redirect.go
  releasenotes/notes/iptables-lock.yaml
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
  tools/istio-iptables/pkg/dependencies/implementation_test.go
Labels: area/networking, size/XL

#47393 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#47377 webhook: move tests to use always-invalid annotation
  pkg/config/constants/constants.go
  pkg/config/validation/validation.go
  pkg/test/datasets/validation/dataset/extensions-v1alpha1-WasmPlugin-invalid.yaml
  pkg/test/datasets/validation/dataset/extensions-v1alpha1-WasmPlugin.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-DestinationRule-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-DestinationRule.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-EnvoyFilter-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-EnvoyFilter.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-Gateway-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-Gateway.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-ServiceEntry-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-ServiceEntry.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-Sidecar-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-Sidecar.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-VirtualService-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-VirtualService-regexp-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-VirtualService.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-WorkloadEntry-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-WorkloadEntry.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-WorkloadGroup-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1alpha3-WorkloadGroup.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-DestinationRule-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-DestinationRule.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-Gateway-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-Gateway.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-Sidecar-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-Sidecar.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-WorkloadEntry-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta-WorkloadEntry.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-ProxyConfig-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-ProxyConfig.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-ServiceEntry-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-ServiceEntry.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-WorkloadGroup-invalid.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-WorkloadGroup.yaml
  pkg/test/datasets/validation/dataset/security-v1-AuthorizationPolicy-invalid.yaml
  pkg/test/datasets/validation/dataset/security-v1-AuthorizationPolicy.yaml
  pkg/test/datasets/validation/dataset/security-v1-RequestAuthentication-invalid.yaml
  pkg/test/datasets/validation/dataset/security-v1-RequestAuthentication.yaml
  pkg/test/datasets/validation/dataset/security-v1beta1-AuthorizationPolicy-invalid.yaml
  pkg/test/datasets/validation/dataset/security-v1beta1-AuthorizationPolicy.yaml
  pkg/test/datasets/validation/dataset/security-v1beta1-PeerAuthentication-invalid.yaml
  pkg/test/datasets/validation/dataset/security-v1beta1-PeerAuthentication.yaml
  pkg/test/datasets/validation/dataset/security-v1beta1-RequestAuthentication-invalid.yaml
  pkg/test/datasets/validation/dataset/security-v1beta1-RequestAuthentication.yaml
  pkg/test/datasets/validation/dataset/telemetry-v1alpha1-Telemetry-invalid.yaml
  pkg/test/datasets/validation/dataset/telemetry-v1alpha1-Telemetry.yaml
  pkg/test/util/yml/apply.go
  pkg/webhooks/validation/controller/controller.go
  tests/integration/pilot/validation_test.go
Labels: size/L, release-notes-none

#47063 Support plugged root cert rotation
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  releasenotes/notes/47063.yaml
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/server.go
  security/pkg/nodeagent/util/util.go
Labels: size/M

#47354 access logs: add support for CEL formatter
  pilot/pkg/model/telemetry_logging.go
Labels: size/S, release-notes-none

#47270 Add `istioctl` Analyzer for External Control Plane Installations
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/externalcontrolplane/externalcontrolplane.go
  pkg/config/analysis/analyzers/testdata/externalcontrolplane-missing-urls.yaml
  pkg/config/analysis/analyzers/testdata/externalcontrolplane-using-ip-addr.yaml
  pkg/config/analysis/analyzers/testdata/externalcontrolplane-valid-urls.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/47269.yaml
Labels: area/user experience, size/L

#47400 Add validationIgnorer to crd validator to ignore resources
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
  pilot/pkg/config/kube/gateway/conversion_test.go
  pkg/config/crd/validator.go
  pkg/config/crd/validator_test.go
Labels: area/networking, size/L, release-notes-none

#47389 Fix DNS resolution flakes
  pilot/pkg/model/network_test.go
Labels: size/L, release-notes-none

#47395 envoy: revert to authenticated principal in rbac for sidecars
  istio.deps
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/deny-and-allow-out1.yaml
  pilot/pkg/security/authz/builder/testdata/http/deny-and-allow-out2.yaml
  pilot/pkg/security/authz/builder/testdata/http/multiple-policies-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/simple-policy-multiple-td-aliases-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/simple-policy-principal-with-wildcard-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/simple-policy-td-aliases-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/single-policy-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/td-aliases-source-principal-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/allow-both-http-tcp-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/audit-both-http-tcp-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/deny-both-http-tcp-out.yaml
  pilot/pkg/xds/filters/filters.go
Labels: size/XL, release-notes-none

#47381 Add gateway integration tests for dual-stack services
  tests/integration/pilot/gateway_test.go
Labels: area/test and release, area/networking, size/L, release-notes-none, area/dual-stack

#47391 cni: 1.18 cherrypicks
  cni/cmd/istio-cni/main.go
  cni/pkg/config/config.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/redirect.go
  releasenotes/notes/iptables-lock.yaml
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
  tools/istio-iptables/pkg/dependencies/implementation_test.go
Labels: area/networking, size/XL

#47396 [release-1.20] Automation step 1
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: size/S, release-notes-none
