Repository istio/istio, pull requests merged in 2023-06, with the labels that each got.

#45231 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45151 update istioctl pc workload command for latest ambient wds
  istioctl/pkg/util/configdump/workload.go
  istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
  istioctl/pkg/writer/ztunnel/configdump/workload.go
Labels: size/XL, release-notes-none, area/ambient

#45221 injection: correctly exit early on error
  pkg/kube/inject/webhook.go
Labels: size/XS, release-notes-none

#43580 BugFix: #42068: Support Field Removals for IstioOperator
  operator/pkg/helmreconciler/apply.go
  operator/pkg/helmreconciler/apply_test.go
  operator/pkg/helmreconciler/testdata/iop-changed.yaml
  releasenotes/notes/43580.yaml
Labels: area/environments, ok-to-test, size/M, lifecycle/automatically-closed, release-notes-none, cherrypick/release-1.15, cherrypick/release-1.16, cherrypick/release-1.17

#45239 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45238 remove unuse file
  pkg/istio-agent/agent_test.go
  pkg/test/env/http_client.go
  pkg/test/env/http_server.go
Labels: ok-to-test, size/L, release-notes-none

#45240 Bump go modules
  go.mod
  go.sum
  licenses/google.golang.org/genproto/googleapis/api/LICENSE
  licenses/google.golang.org/genproto/googleapis/rpc/LICENSE
Labels: size/XL, release-notes-none

#45249 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45230 eds: simplify and optimize mTLS checker
  istioctl/cmd/describe.go
  pilot/pkg/model/authentication.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/ep_filters_test.go
  pilot/pkg/xds/mtls_checker.go
  pkg/slices/slices.go
Labels: size/XL, release-notes-none

#45245 use rwmutex replace mutex and use RLock when get
  cni/pkg/ambient/server.go
  pilot/pkg/model/cluster_local.go
  pkg/adsc/adsc.go
  pkg/kube/inject/webhook.go
Labels: ok-to-test, size/M, release-notes-none

#45248 Fix and test cluster metrics
  cni/pkg/repair/repair_test.go
  pilot/pkg/util/informermetric/informerutil.go
  pkg/kube/client.go
  pkg/kube/kclient/client_test.go
  pkg/monitoring/monitoring_test.go
  pkg/monitoring/monitortest/test.go
Labels: size/XL, release-notes-none

#45253 return error info if read file have error
  pkg/adsc/adsc.go
Labels: ok-to-test, size/XS, release-notes-none

#45237 Integration tests for CRL support at Ingress Gateway
  tests/integration/security/sds_ingress/ingress_test.go
  tests/integration/security/sds_ingress/util/generate_certs.sh
  tests/integration/security/sds_ingress/util/test_certs.go
  tests/integration/security/sds_ingress/util/util.go
Labels: size/L, release-notes-none

#45257 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#45058 GAMMA: remove requirement for ReferenceGrant for cross namespace backends
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conditions_test.go
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.yaml
  pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
  pkg/slices/slices.go
Labels: size/XXL, release-notes-none

#45258 wasm: implement fail_open
  pilot/pkg/model/extensions.go
  pilot/pkg/model/extensions_test.go
  releasenotes/notes/wasm-fail-open.yaml
  tests/integration/telemetry/api/testdata/bad-wasm-envoy-filter-fail-open.yaml
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/envoyfilter/customizemetrics/testdata/attributegen_envoy_filter.yaml
  tests/integration/telemetry/envoyfilter/customizemetrics/testdata/bootstrap_patch.yaml
Labels: size/L

#45260 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45263 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45266 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45267 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45244 pilot: refactor version to avoid globals
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/eds_test.go
Labels: size/M, release-notes-none

#45264 Avoid memory allocation within address map
  pilot/pkg/model/addressmap.go
  pilot/pkg/model/addressmap_test.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: size/M, release-notes-none

#45270 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45272 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45216 fix envoyFilter order
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  releasenotes/notes/45216.yaml
Labels: ok-to-test, size/L

#45065 Gamma: fix consumer overrides
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
Labels: size/M, release-notes-none

#45265 increase ut coverage for pkg/slices
  pkg/slices/slices_test.go
Labels: ok-to-test, size/L, release-notes-none

#45281 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45284 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#45287 Update BASE_VERSION to 1.17-2023-06-05T19-02-58
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45288 Update BASE_VERSION to 1.16-2023-06-05T19-02-55
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45289 Update BASE_VERSION to release-1.18-2023-06-05T19-04-11
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45285 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45286 Update BASE_VERSION to master-2023-06-05T19-01-58
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45294 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45282 linter: consolidate on common helper libraries
  common/config/.golangci.yml
  pilot/cmd/pilot-agent/status/server.go
  pkg/test/echo/server/endpoint/grpc.go
  tools/docker-builder/types.go
  tools/golangci-override.yaml
Labels: size/S, release-notes-none

#45290 gateway: cleanup wildcard port matcher
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: size/S, release-notes-none

#45297 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45293 Fix Telemetry disablement matching
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  releasenotes/notes/telemetry-implicit-match-all.yaml
Labels: size/M, cherrypick/release-1.16, cherrypick/release-1.17, cherrypick/release-1.18

#45295 use istio pkg.slices
  pilot/pkg/config/kube/gateway/controller.go
Labels: size/S, release-notes-none

#45298 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45305 remove isempty function in address map
  pilot/pkg/config/kube/gateway/context.go
  pilot/pkg/model/addressmap.go
  pilot/pkg/model/addressmap_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/M, release-notes-none

#45309 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45170 Wds evolution v2
  istio.deps
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/v3/model.go
  pilot/pkg/xds/workload.go
  pilot/pkg/xds/workload_test.go
  pkg/workloadapi/workload.pb.go
  pkg/workloadapi/workload.proto
Labels: size/L, release-notes-none, area/ambient

#45316 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45318 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45310 [release-1.18][step 0] Update deps prior to 1.18.0 GA
  go.mod
  go.sum
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#45312 docs: add controllers documentation to ARCHITECTURE
  pilot/ARCHITECTURE.md
Labels: size/L, release-notes-none

#45319 ambient: fix TestWorkloadReconnect flake
  pilot/pkg/xds/workload_test.go
Labels: size/S, release-notes-none

#45325 Automator: update common-files@release-1.18 in istio/istio@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#45326 Automator: update istio/client-go@release-1.18 dependency in istio/istio@release-1.18
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45035 Don't hardcode versions in upgrade test
  go.mod
  pkg/test/env/istio.go
  pkg/util/image/registry.go
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/main_test.go
  tools/docker-builder/docker.go
Labels: size/L, release-notes-none

#45313 multicluster: minor refactoring
  pkg/kube/multicluster/clusterstore.go
  pkg/kube/multicluster/secretcontroller.go
Labels: size/M, release-notes-none

#45211 Fix validatingwebhookconfiguration installation error
  istioctl/pkg/tag/generate.go
  istioctl/pkg/tag/generate_test.go
  operator/pkg/helmreconciler/reconciler.go
Labels: area/environments, size/M, release-notes-none

#45300 golangci-lint: add depguard/v2 settings
  tools/golangci-override.yaml
Labels: area/test and release, size/M, release-notes-none

#45163 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45283 ambient: refactor controller implementation a bit
  pilot/pkg/model/config.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/authorization.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/workload.go
  pkg/slices/slices.go
Labels: size/XL, release-notes-none

#45322 use file.AtomicWrite to chmod auth
  cni/pkg/ambient/server.go
Labels: ok-to-test, size/S, release-notes-none

#45320 Cleanup: improve the use of maps
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/ep_filters.go
Labels: ok-to-test, size/M, release-notes-none

#45336 monitoring: drop raw usage of OC library
  cni/pkg/repair/repair_test.go
  pkg/version/stats_linux.go
  pkg/version/version_linux_test.go
  pkg/webhooks/validation/controller/monitoring.go
Labels: size/L, release-notes-none

#45105 Revert "clean and fix string split"
  pilot/pkg/model/context.go
  pilot/pkg/model/virtualservice.go
Labels: size/S, release-notes-none

#45308 Allow lookup of GVK from client-go types
  pkg/config/schema/codegen/templates/types.go.tmpl
  pkg/config/schema/kubetypes/resources.gen.go
Labels: size/XS, release-notes-none

#45164 [release-1.18] Return a specific status code in debuggen
  pilot/pkg/xds/debuggen.go
Labels: size/S, release-notes-none

#45195 globally protect env.PushContext to prevent race
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
  pilot/pkg/networking/core/v1alpha3/fake.go
  pilot/pkg/networking/core/v1alpha3/fuzz_test.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/cds_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/fake.go
  pilot/pkg/xds/simple.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/webhook_test.go
Labels: size/L, release-notes-none

#45081 [release-1.18]Manual cherry-pick of 44481 and 44775
  manifests/charts/gateway/templates/poddisruptionbudget.yaml
  manifests/charts/gateway/values.schema.json
  manifests/charts/gateway/values.yaml
  releasenotes/notes/44481.yaml
Labels: size/M

#45130 [release-1.18] Certificate Revocation List support
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/credentials/kube/multicluster.go
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/credentials/kube/secrets_test.go
  pilot/pkg/credentials/model.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  pkg/config/analysis/analyzers/gateway/secret.go
  releasenotes/notes/crl_support.yaml
Labels: size/L

#45165 [release-1.18] Add an option to enable LoadReportingSerivce client in Envoy
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/lrs.proxycfg
  pkg/bootstrap/testdata/lrs_golden.json
  releasenotes/notes/lrs.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L, release-notes-none

#45168 [release-1.18] Fix invalid XDS configuration for wildcard Ingress HTTP path (#44898)
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  pilot/pkg/config/kube/ingress/testdata/overlay.yaml.golden
  pilot/pkg/config/kube/ingress/testdata/tls-no-secret.yaml.golden
  pilot/pkg/config/kube/ingress/testdata/tls.yaml.golden
Labels: area/networking, size/M, release-notes-none

#45303 [release-1.18] Fix Telemetry disablement matching
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  releasenotes/notes/telemetry-implicit-match-all.yaml
Labels: size/M, release-notes-none

#44934 Add rolling update max unavailable to CNI chart to speed up deploys (cherry pick to release-1.18)
  manifests/charts/UPDATING-CHARTS.md
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/cni-rolling-max-available.yaml
Labels: area/environments, ok-to-test, size/S

#45343 [release-1.18] Fix istioctl pc secret cert validity not accurate
  istioctl/pkg/writer/compare/sds/util.go
  istioctl/pkg/writer/envoy/configdump/secret_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/secret/config_dump.json
  istioctl/pkg/writer/envoy/configdump/testdata/secret/output
  releasenotes/notes/44929.yaml
Labels: size/L, release-notes-none

#45334 Add missing outputformat usage for istioctl envoy-stats
  istioctl/cmd/proxyconfig.go
Labels: area/user experience, size/XS, release-notes-none

#45337 monitoring: make benchmark more robust
  pkg/monitoring/monitoring_test.go
Labels: size/S, release-notes-none

#45350 change CODEOWNERS of pkg/monitoring
  CODEOWNERS
Labels: size/XS, release-notes-none

#45357 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45359 [release-1.18] Change to use Node instead of RawMetadata in LoadStatsConfigJSONStr
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
Labels: size/XS, release-notes-none

#45331 use defer to unlock
  releasenotes/notes/45331.yaml
  security/pkg/nodeagent/cache/secretcache.go
Labels: ok-to-test, size/XS

#45360 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45363 Automator: update common-files@release-1.16 in istio/istio@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#45192 Add resource settings to gateway-api deployment templates
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.33.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.36.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: area/environments, area/perf and scalability, ok-to-test, area/user experience, size/XS, release-notes-none

#45364 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45366 Check the disabled status when adding a log provider
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  releasenotes/notes/check-disabled-status.yaml
Labels: size/M, cherrypick/release-1.16, cherrypick/release-1.17, cherrypick/release-1.18

#45375 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45373 [release-1.18] Check the disabled status when adding a log provider
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  releasenotes/notes/check-disabled-status.yaml
Labels: size/M, release-notes-none

#45362 rm depguard v1 settings
  common/config/.golangci.yml
  tools/golangci-override.yaml
Labels: area/test and release, size/M, release-notes-none

#45367 Cleanup deadcode in tf Stats
  go.mod
  pkg/test/framework/components/echo/kube/sidecar.go
  pkg/test/framework/components/echo/sidecar.go
Labels: size/M, release-notes-none

#45380 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45381 Automator: update istio/client-go@release-1.18 dependency in istio/istio@release-1.18
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45377 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45361 monitoring: cleanup more direct open census usage
  cni/pkg/monitoring/monitoring.go
  operator/cmd/operator/server.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/pkg/bootstrap/monitoring.go
  pilot/pkg/model/jwks_resolver_test.go
  pkg/kube/inject/webhook_test.go
  pkg/monitoring/monitoring.go
  pkg/monitoring/monitoring_test.go
  pkg/monitoring/monitortest/test.go
  pkg/test/echo/server/instance.go
  security/pkg/monitoring/monitoring.go
  security/pkg/nodeagent/caclient/providers/citadel/client_test.go
  security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go
  security/pkg/nodeagent/util/util.go
Labels: size/L, release-notes-none

#45391 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45274 Refactor istioctl package global variables, and fix some client usages
  istioctl/cmd/admin.go
  istioctl/cmd/analyze.go
  istioctl/cmd/authz.go
  istioctl/cmd/checkinject.go
  istioctl/cmd/clusters.go
  istioctl/cmd/completion.go
  istioctl/cmd/dashboard.go
  istioctl/cmd/dashboard_test.go
  istioctl/cmd/deprecated_cmd.go
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/injector-list.go
  istioctl/cmd/internal-debug.go
  istioctl/cmd/istioctl_test.go
  istioctl/cmd/istiodconfig.go
  istioctl/cmd/kubeinject.go
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/mock_test.go
  istioctl/cmd/precheck.go
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/revision.go
  istioctl/cmd/root.go
  istioctl/cmd/tag.go
  istioctl/cmd/version.go
  istioctl/cmd/wait.go
  istioctl/cmd/waypoint.go
  istioctl/cmd/waypoint_test.go
  istioctl/cmd/workload.go
  istioctl/cmd/workload_test.go
  istioctl/pkg/cli/context.go
  istioctl/pkg/cli/context_test.go
  istioctl/pkg/cli/kubectl_factory.go
  istioctl/pkg/cli/option.go
  istioctl/pkg/util/ambient/util.go
  istioctl/pkg/util/handlers/handlers.go
  istioctl/pkg/util/handlers/handlers_test.go
  istioctl/pkg/validate/validate.go
  istioctl/pkg/validate/validate_test.go
Labels: area/user experience, size/XXL, release-notes-none

#45395 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45399 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45175 #42938 add topologySpreadConstraints config for istiod helm chart
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/helm_chart_pilot_topologyspreadconstraints.yaml
Labels: ok-to-test, size/S

#45397 simplify and optimize servicesDiff
  pilot/pkg/serviceregistry/serviceentry/controller.go
Labels: ok-to-test, size/S, release-notes-none

#45379 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#45398 Implement support for Regex Rewrite for URI's
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/httpregexrewrite.yaml
Labels: area/networking, ok-to-test, size/L

#45345 [release-1.16] Fix istioctl pc secret cert validity not accurate
  istioctl/pkg/writer/compare/sds/util.go
  istioctl/pkg/writer/envoy/configdump/secret_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/secret/config_dump.json
  istioctl/pkg/writer/envoy/configdump/testdata/secret/output
  releasenotes/notes/44929.yaml
Labels: size/L, release-notes-none

#45402 Return ealier when the key contains hostname
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
Labels: size/XS, release-notes-none

#45396 add ut for pkg/util/net/ip_test.go
  pkg/util/net/ip_test.go
Labels: ok-to-test, size/L, release-notes-none

#45416 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#45417 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45422 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45327 Update workload.Uid
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
  pilot/pkg/xds/workload_test.go
Labels: size/L, release-notes-none

#45385 Fix getGatewayClasses has waypoint after Ambient is disabled
  pilot/pkg/config/kube/gateway/conversion.go
Labels: size/XS, release-notes-none

#45421 memory controller: propogate correct error
  pilot/pkg/config/memory/controller.go
Labels: size/S, release-notes-none

#45374 [release-1.16] Check the disabled status when adding a log provider
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  releasenotes/notes/check-disabled-status.yaml
Labels: size/M

#45386 depguard: add guard for OpenCensus
  common/config/.golangci.yml
  tools/golangci-override.yaml
Labels: area/test and release, size/S, release-notes-none

#45419 Validation webhook should ensure in UriRegexRewrite both match and rewrite fields present
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: area/networking, ok-to-test, size/M, release-notes-none

#45438 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45428 generate-certs: Remove unnecessary cleanup step
  tests/testdata/certs/generate.sh
Labels: size/XS, release-notes-none

#45275 Update min supported k8s version to 1.24
  istioctl/pkg/install/k8sversion/version.go
  istioctl/pkg/install/k8sversion/version_test.go
  releasenotes/notes/45275.yaml
Labels: area/user experience, size/S, cherrypick/release-1.18

#45427 istioctl: fix client usages and drop newKubeClientWithRevision
  istioctl/cmd/admin.go
  istioctl/cmd/analyze.go
  istioctl/cmd/analyze_test.go
  istioctl/cmd/authz.go
  istioctl/cmd/checkinject.go
  istioctl/cmd/clusters.go
  istioctl/cmd/completion.go
  istioctl/cmd/config_test.go
  istioctl/cmd/dashboard.go
  istioctl/cmd/dashboard_test.go
  istioctl/cmd/deprecated_cmd.go
  istioctl/cmd/describe.go
  istioctl/cmd/describe_test.go
  istioctl/cmd/injector-list.go
  istioctl/cmd/internal-debug.go
  istioctl/cmd/istioctl_test.go
  istioctl/cmd/istiodconfig.go
  istioctl/cmd/istiodconfig_test.go
  istioctl/cmd/kubeinject.go
  istioctl/cmd/kubeinject_test.go
  istioctl/cmd/metrics.go
  istioctl/cmd/metrics_test.go
  istioctl/cmd/mock_test.go
  istioctl/cmd/precheck.go
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
  istioctl/cmd/proxystatus.go
  istioctl/cmd/proxystatus_test.go
  istioctl/cmd/revision.go
  istioctl/cmd/root.go
  istioctl/cmd/tag.go
  istioctl/cmd/version.go
  istioctl/cmd/wait.go
  istioctl/cmd/wait_test.go
  istioctl/cmd/waypoint.go
  istioctl/cmd/waypoint_test.go
  istioctl/cmd/workload.go
  istioctl/cmd/workload_test.go
  istioctl/pkg/cli/context.go
  istioctl/pkg/cli/mock_client.go
  istioctl/pkg/validate/validate.go
  istioctl/pkg/validate/validate_test.go
Labels: area/test and release, area/user experience, size/XXL, release-notes-none

#45446 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#45368 bootstrap: implement custom buckets
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/test/framework/components/echo/annotations.go
  releasenotes/notes/bootstrap-histogram-buckets.yaml
  tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
  tests/integration/telemetry/envoyfilter/customizemetrics/testdata/bootstrap_patch.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/M

#45450 Automator: update proxy@release-1.18 in istio/istio@release-1.18
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45451 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45444 [release-1.18] Update min supported k8s version to 1.24
  istioctl/pkg/install/k8sversion/version.go
  istioctl/pkg/install/k8sversion/version_test.go
  releasenotes/notes/45275.yaml
Labels: size/S, release-notes-none

#45407 istioctl workload configure: accept ingress IPv6
  istioctl/cmd/testdata/vmconfig/ipv4/.gitignore
  istioctl/cmd/testdata/vmconfig/ipv4/cluster.env.golden
  istioctl/cmd/testdata/vmconfig/ipv4/hosts.golden
  istioctl/cmd/testdata/vmconfig/ipv4/istio-token.golden
  istioctl/cmd/testdata/vmconfig/ipv4/mesh.yaml.golden
  istioctl/cmd/testdata/vmconfig/ipv4/meshconfig.yaml
  istioctl/cmd/testdata/vmconfig/ipv4/root-cert.pem.golden
  istioctl/cmd/testdata/vmconfig/ipv4/workloadgroup.yaml
  istioctl/cmd/testdata/vmconfig/ipv6/.gitignore
  istioctl/cmd/testdata/vmconfig/ipv6/cluster.env.golden
  istioctl/cmd/testdata/vmconfig/ipv6/hosts.golden
  istioctl/cmd/testdata/vmconfig/ipv6/istio-token.golden
  istioctl/cmd/testdata/vmconfig/ipv6/mesh.yaml.golden
  istioctl/cmd/testdata/vmconfig/ipv6/meshconfig.yaml
  istioctl/cmd/testdata/vmconfig/ipv6/root-cert.pem.golden
  istioctl/cmd/testdata/vmconfig/ipv6/workloadgroup.yaml
  istioctl/cmd/workload.go
  istioctl/cmd/workload_test.go
  releasenotes/notes/45407.yaml
Labels: area/networking, size/M

#45420 ambient: use correct FQDN for hostname
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
Labels: size/S, release-notes-none

#45435 Add more log for istio ca for trouble shooting
  security/pkg/server/ca/server.go
Labels: size/S, release-notes-none

#45423 Use UriRegexRewrite to implement full path rewrite in Gateway API
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
Labels: area/networking, ok-to-test, size/M, release-notes-none

#45344 [release-1.17] Fix istioctl pc secret cert validity not accurate
  istioctl/pkg/writer/compare/sds/util.go
  istioctl/pkg/writer/envoy/configdump/secret_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/secret/config_dump.json
  istioctl/pkg/writer/envoy/configdump/testdata/secret/output
  releasenotes/notes/44929.yaml
Labels: size/L, release-notes-none

#45452 xds: replace map with set
  pilot/pkg/xds/ads.go
Labels: ok-to-test, size/XS, release-notes-none

#45194 [release-1.18] cherry-pick: add debug info when generating certs for workloads
  security/pkg/server/ca/server.go
Labels: area/user experience, size/XS, release-notes-none

#45459 Remove unused test data
  istioctl/cmd/testdata/uninject/cronjob-with-app.yaml
  istioctl/cmd/testdata/uninject/cronjob-with-app.yaml.injected
  istioctl/cmd/testdata/uninject/cronjob.yaml
  istioctl/cmd/testdata/uninject/cronjob.yaml.injected
  istioctl/cmd/testdata/uninject/daemonset.yaml
  istioctl/cmd/testdata/uninject/daemonset.yaml.injected
  istioctl/cmd/testdata/uninject/deploymentconfig-app-probe.yaml
  istioctl/cmd/testdata/uninject/deploymentconfig-app-probe.yaml.injected
  istioctl/cmd/testdata/uninject/deploymentconfig-multi.yaml
  istioctl/cmd/testdata/uninject/deploymentconfig-multi.yaml.injected
  istioctl/cmd/testdata/uninject/deploymentconfig.yaml
  istioctl/cmd/testdata/uninject/deploymentconfig.yaml.injected
  istioctl/cmd/testdata/uninject/enable-core-dump.yaml
  istioctl/cmd/testdata/uninject/enable-core-dump.yaml.injected
  istioctl/cmd/testdata/uninject/hello.yaml
  istioctl/cmd/testdata/uninject/job.yaml
  istioctl/cmd/testdata/uninject/job.yaml.injected
  istioctl/cmd/testdata/uninject/list.yaml
  istioctl/cmd/testdata/uninject/list.yaml.injected
  istioctl/cmd/testdata/uninject/pod.yaml
  istioctl/cmd/testdata/uninject/pod.yaml.injected
  istioctl/cmd/testdata/uninject/replicaset.yaml
  istioctl/cmd/testdata/uninject/replicaset.yaml.injected
  istioctl/cmd/testdata/uninject/replicationcontroller.yaml
  istioctl/cmd/testdata/uninject/replicationcontroller.yaml.injected
  istioctl/cmd/testdata/uninject/statefulset.yaml
  istioctl/cmd/testdata/uninject/statefulset.yaml.injected
  istioctl/cmd/testdata/v1alpha3/.gitignore
  istioctl/cmd/testdata/v1alpha3/merged-gateway.yaml.golden
  istioctl/cmd/testdata/v1alpha3/myservice-gateway.yaml.golden
  istioctl/cmd/testdata/v1alpha3/named-port-gateway.yaml.golden
Labels: area/user experience, size/XXL, release-notes-none

#45460 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45440 Add platform
  manifests/charts/base/values.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/profiles/openshift.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/platform/platform.go
Labels: size/M, release-notes-none

#45470 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45473 use set replace map
  pilot/pkg/model/sidecar.go
Labels: ok-to-test, size/S, release-notes-none

#45355 helloworld sample update
  samples/helloworld/helloworld-dual-stack.yaml
  samples/helloworld/src/Dockerfile
  samples/helloworld/src/app.py
  samples/helloworld/src/requirements.txt
Labels: kind/docs, size/M, release-notes-none

#45469 Fix bug-report was hanging during analysis.
  tools/bug-report/pkg/content/content.go
Labels: area/test and release, area/user experience, size/XS, release-notes-none

#45475 Analyze: exclude useless secrets to reduce execution time
  pilot/pkg/config/kube/crdclient/client.go
  pkg/config/analysis/local/istiod_analyze.go
Labels: size/M, release-notes-none

#45479 use insert on set
  pilot/pkg/model/config.go
Labels: size/XS, release-notes-none

#45478 Fix workload test do not cleanup
  istioctl/pkg/workload/testdata/vmconfig-nil-proxy-metadata/.gitignore
  istioctl/pkg/workload/testdata/vmconfig/.gitignore
  istioctl/pkg/workload/testdata/vmconfig/ipv4/.gitignore
  istioctl/pkg/workload/testdata/vmconfig/ipv6/.gitignore
  istioctl/pkg/workload/workload_test.go
Labels: size/M, release-notes-none

#45474 Fix admin log default namespace
  istioctl/pkg/admin/istiodconfig.go
Labels: size/XS, release-notes-none

#45485 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#45484 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#45492 Update BASE_VERSION to master-2023-06-15T19-01-36
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45493 Update BASE_VERSION to 1.16-2023-06-15T19-02-27
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45494 Update BASE_VERSION to 1.17-2023-06-15T19-03-18
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45495 Update BASE_VERSION to 1.18-2023-06-15T19-02-54
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#45483 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#45498 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#44944 cni: cleanup exclusion logic
  cni/pkg/plugin/ambient.go
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/plugin_dryrun_test.go
  cni/pkg/plugin/plugin_test.go
Labels: size/L, release-notes-none

#45497 CRL: integration tests sidecar egress tls origination
  tests/integration/security/egress_sidecar_tls_origination_test.go
Labels: size/L, release-notes-none

#45150 make WorkloadEntry address optional
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/store.go
  pilot/pkg/serviceregistry/util/workloadinstances/index.go
  pilot/pkg/xds/endpoint_builder.go
  pilot/pkg/xds/ep_filters.go
  pilot/pkg/xds/ep_filters_test.go
  pilot/pkg/xds/mesh_network_test.go
  pilot/test/xdstest/extract.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/dns/server/name_table.go
  releasenotes/notes/45150.yaml
  tests/integration/pilot/workloadentry_test.go
Labels: size/XL

#45152 Optimize labels.String()
  pkg/config/labels/instance.go
  pkg/config/labels/instance_test.go
Labels: size/M, release-notes-none

#45476 Fix auto register WLE with invalid istio-locality label
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/autoregistration/controller_test.go
  releasenotes/notes/45413.yaml
Labels: size/S
