Repository istio/istio, pull requests merged in 2023-03, with the labels that each got.

#43626 Fix analyzer generates no service associated messages for waypoint deploy
  pkg/config/analysis/analyzers/deployment/services.go
  pkg/config/analysis/analyzers/testdata/deployment-multi-service.yaml
Labels: area/user experience, size/M, release-notes-none, area/ambient

#43675 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43652 Fix analyzing not caught some messages in default namespace
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/deployment/services.go
  pkg/config/analysis/analyzers/testdata/deployment-service-no-selector.yaml
  releasenotes/notes/43652.yaml
Labels: size/M, cherrypick/release-1.16, cherrypick/release-1.17

#43680 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43679 remove get with request and unnecessary type args
  pilot/pkg/model/typed_xds_cache.go
  pilot/pkg/model/typed_xds_cache_test.go
  pilot/pkg/model/xds_cache.go
Labels: size/L, release-notes-none

#43678 [release-1.17] Fix analyzing not caught some messages in default namespace
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/deployment/services.go
  pkg/config/analysis/analyzers/testdata/deployment-service-no-selector.yaml
  releasenotes/notes/43652.yaml
Labels: size/M, release-notes-none

#43670 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43697 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43701 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43699 add integ test for testing waypoint changes in ingress gateway
  tests/integration/ambient/bookinfo_test.go
Labels: size/M, release-notes-none

#43704 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43707 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43703 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43702 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43686 remove redundant types conversion
  pilot/pkg/model/context_test.go
Labels: ok-to-test, size/XS, release-notes-none

#43685 move cache eviction loop to xds cache impl
  pilot/pkg/model/typed_xds_cache.go
  pilot/pkg/model/typed_xds_cache_test.go
  pilot/pkg/model/xds_cache.go
Labels: size/L, release-notes-none

#43491 Server Side Apply: Enabled without detection logic when k8s version > v1.22
  operator/pkg/helmreconciler/reconciler.go
  releasenotes/notes/37946.yaml
Labels: ok-to-test, size/S

#43674 connect: consolidate HCM configs
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  pilot/pkg/xds/endpoint_builder.go
Labels: size/L, release-notes-none

#43719 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43724 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43676 ambient: properly opt-out sidecar pods
  cni/pkg/ambient/ambientpod/podutil.go
  cni/pkg/ambient/informers.go
  cni/pkg/ambient/options.go
  cni/pkg/ambient/util.go
  cni/pkg/plugin/ambient.go
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/profiles/ambient.yaml
Labels: size/L, release-notes-none

#43732 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43734 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43649 ambient handle pod cleanups
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
Labels: size/M, release-notes-none, area/ambient

#43723 connect: delete and consolidate more code
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/util/internal_upstream.go
Labels: size/L, release-notes-none

#43660 fix: istioctl operator remove fail when not specify reversion
  operator/cmd/mesh/operator-remove.go
  releasenotes/notes/fix-remove-iop-not-work.yaml
Labels: area/environments, size/XS, release-notes-none

#43726 Attempt 2 at fixing Grafana variable query
  manifests/addons/dashboards/istio-service-dashboard.json
  samples/addons/grafana.yaml
Labels: size/XS, release-notes-none

#43727 Automator: update common-files@master in istio/istio@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#43729 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#43737 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43706 add two telemetry analyzers
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/telemetry/defaultselector.go
  pkg/config/analysis/analyzers/telemetry/selector.go
  pkg/config/analysis/analyzers/telemetry/util.go
  pkg/config/analysis/analyzers/testdata/telemetry-default-selector.yaml
  pkg/config/analysis/analyzers/testdata/telemetry-selector.yaml
  pkg/config/analysis/analyzers/util/find_errorline_utils.go
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  releasenotes/notes/43706.yaml
Labels: ok-to-test, size/L

#43672 Allow for dual stack services to use when enabling experimental dual …
  samples/tcp-echo/tcp-echo-dual-stack.yaml
  samples/tcp-echo/tcp-echo-ipv4.yaml
  samples/tcp-echo/tcp-echo-ipv6.yaml
Labels: area/test and release, size/L, release-notes-none

#43744 cleanups for hbone and ambient
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_builder.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
Labels: size/M, release-notes-none

#43740 Automator: update proxy@release-1.15 in istio/istio@release-1.15
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43739 Automator: update proxy@release-1.16 in istio/istio@release-1.16
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43746 Support DirectResponse for waypoints
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
Labels: area/networking, size/S, release-notes-none, area/ambient

#43661 ServiceEntry-created clusters are not matched in IPv6-only cluster
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
  pkg/config/constants/constants.go
  pkg/test/framework/components/echo/check/checkers.go
  tests/integration/README.md
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: ok-to-test, size/L, release-notes-none

#43690 fix gateway bind with same port and different protocol
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/43688.yaml
Labels: area/networking, ok-to-test, size/L

#43693 Fix for #43689 - Fix local macOS devbuilds
  Makefile.core.mk
  cni/pkg/ebpf/server/redirectionServer_linux.go
Labels: area/test and release, size/S, release-notes-none

#43728 Automator: update istio/pkg@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#43748 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43736 Add prefix matching on query parameter
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  releasenotes/notes/43710.yaml
Labels: size/L

#43749 ambient: fix wrong namespace usage
  cni/pkg/ambient/informers.go
Labels: size/XS, release-notes-none

#43753 gateway-api: add gateway for httpbin sample
  samples/httpbin/gateway-api/httpbin-gateway.yaml
Labels: size/S, release-notes-none

#43755 Update BASE_VERSION to 1.16-2023-03-03T19-01-17
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43758 Update BASE_VERSION to master-2023-03-03T19-17-03
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43756 Update BASE_VERSION to 1.15-2023-03-03T19-02-34
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43759 samples: use multiarch httpbin image
  samples/httpbin/README.md
  samples/httpbin/httpbin.yaml
Labels: kind/docs, area/test and release, area/user experience, size/XS, release-notes-none

#43757 Update BASE_VERSION to 1.17-2023-03-03T19-02-38
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43761 Fix: Initialize iptables helpers for both ambient CNI modes
  cni/pkg/ambient/server.go
Labels: area/networking, size/XS, release-notes-none, area/ambient

#43750 queue: do not expose spammy logs
  pkg/kube/controllers/queue.go
Labels: size/S, release-notes-none

#43762 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43768 Automator: update go dependencies@ in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#43766 Modify the reminder log of istio removal
  operator/cmd/mesh/operator-remove.go
Labels: area/environments, size/XS, release-notes-none

#43773 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43743 Speed up unit tests
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pkg/webhooks/validation/controller/controller_test.go
  samples/tcp-echo/src/main_test.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#43760 store: make List infallible
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/autoregistration/controller_test.go
  pilot/pkg/config/aggregate/config.go
  pilot/pkg/config/aggregate/config_test.go
  pilot/pkg/config/file/store.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/memory/controller.go
  pilot/pkg/config/memory/store.go
  pilot/pkg/config/monitor/monitor_test.go
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/authorization.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/config.go
  pilot/pkg/model/fake_store.go
  pilot/pkg/model/proxy_config.go
  pilot/pkg/model/proxy_config_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/apigen/apigen.go
  pilot/pkg/networking/apigen/apigen_test.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/namespace_handler.go
  pilot/pkg/xds/debug.go
  pilot/test/mock/config.go
  pkg/adsc/adsc.go
  pkg/adsc/adsc_test.go
  pkg/config/analysis/local/context.go
  pkg/kube/inject/webhook_test.go
Labels: size/XL, release-notes-none

#43781 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43605 Allow adding pod labels to gateway manifest
  manifests/charts/gateway/templates/_helpers.tpl
  manifests/charts/gateway/templates/deployment.yaml
  releasenotes/notes/gw-allow-labels.yaml
Labels: area/environments, area/user experience, size/S

#43767 refactor waypoint logic
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/waypoint.go
  pilot/pkg/networking/util/internal_upstream.go
Labels: size/L, release-notes-none, area/ambient

#43770 AccessLogging: fix the issue where disable accesslogging does not take effect
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Labels: size/L, release-notes-none, cherrypick/release-1.16, cherrypick/release-1.17

#43774 Minimize vmlinux.h for ebpf redirection
  cni/pkg/ebpf/app/vmlinux.h
Labels: area/networking, size/XXL, release-notes-none, area/ambient

#43776 fix gateway with TCP and different bind listeners are not generated c…
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  releasenotes/notes/43775.yaml
Labels: ok-to-test, size/L

#43777 Fix ip rule/route flush for ebpf redirection
  cni/pkg/ambient/net_linux.go
Labels: size/S, release-notes-none, area/ambient

#43771 Download and install istioctl without path change
  release/downloadIstioCtl.sh
  releasenotes/notes/43771.yaml
Labels: area/user experience, size/S

#43790 fix a typo in the SPIFFE_BUNDLE_ENDPOINTS description
  pilot/pkg/features/pilot.go
Labels: kind/docs, size/XS, release-notes-none

#43791 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43764 analyzer: cleanup unused params
  istioctl/cmd/analyze.go
  istioctl/cmd/precheck.go
  istioctl/cmd/tag.go
  operator/pkg/helmreconciler/reconciler.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/incluster/controller.go
  pkg/config/analysis/local/analyze_test.go
  pkg/config/analysis/local/istiod_analyze.go
  pkg/config/legacy/util/kuberesource/resources.go
  tests/fuzz/analyzer_fuzzer.go
  tools/bug-report/pkg/content/content.go
Labels: size/M, release-notes-none

#43793 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43782 copyBinaries: use struct{} and isDir
  cni/pkg/install/binaries.go
Labels: area/perf and scalability, ok-to-test, size/S, release-notes-none

#43683 [release-1.16] Manual cherry-pick of https://github.com/istio/istio/pull/43652
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/deployment/services.go
  pkg/config/analysis/analyzers/testdata/deployment-service-no-selector.yaml
  releasenotes/notes/43652.yaml
Labels: size/M

#43769 fix some comments
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/kube/inject/watcher.go
Labels: ok-to-test, size/XS, release-notes-none

#43796 Replace `reflect.DeepEqual` with `service.Equals`
  pilot/pkg/serviceregistry/serviceentry/controller.go
Labels: area/networking, size/XS, release-notes-none

#43752 Fix MaybeApplyTLSModeLabel function
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: area/networking, ok-to-test, size/L, release-notes-none

#43624 Fix `istioctl pc log` ztunnel pod not working
  istioctl/cmd/proxyconfig.go
  istioctl/cmd/proxyconfig_test.go
Labels: area/user experience, size/M, release-notes-none, area/ambient

#43798 [release-1.17] AccessLogging: fix the issue where disable accesslogging does not take effect
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Labels: size/L, release-notes-none

#43795 [release-1.17] Include trustDomains from CaCertificates in SAN Validation
  pilot/pkg/networking/plugin/authn/util.go
  pilot/pkg/networking/plugin/authn/util_test.go
  releasenotes/notes/add_trust_domans_san_validator.yaml
Labels: size/M, release-notes-none

#43789 crdclient: consolidate generation logic
  go.mod
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/gen/main.go
  pilot/pkg/config/kube/crdclient/gen/types.go.tmpl
  pilot/pkg/config/kube/crdclient/generate.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/schema/ast/ast.go
  pkg/config/schema/codegen/collections.go
  pkg/config/schema/codegen/common.go
  pkg/config/schema/collections/collections.agent.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kind/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/config/schema/resource/schema.go
Labels: size/XL, release-notes-none

#43804 Manually update latest client-go and api
  go.mod
  go.sum
Labels: size/S, release-notes-none

#43808 [release-1.17] rbac: honor useAuthenticated
  pilot/pkg/security/authz/model/model.go
  pilot/pkg/security/authz/model/model_test.go
  releasenotes/notes/invalid-rbac-filter.yaml
Labels: size/L, release-notes-none

#43786 pilot: improve xds event testing
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
Labels: size/L, release-notes-none

#43811 Update BASE_VERSION to master-2023-03-07T19-01-19
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43813 Update BASE_VERSION to 1.15-2023-03-07T19-02-22
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43812 Update BASE_VERSION to 1.17-2023-03-07T19-01-20
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43810 Update BASE_VERSION to 1.16-2023-03-07T19-01-19
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#43806 fuzzing: flag parameters in instrumentation utility
  tests/fuzz/oss_fuzz_build.sh
Labels: area/test and release, area/security, size/XS, release-notes-none

#43787 pilot: wait for queue to complete in test
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
  pilot/pkg/xds/fake.go
  pkg/kube/client.go
Labels: size/S, release-notes-none

#43814 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43207 Ecdh curves support for non ISTIO_MUTUAL traffic
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pilot/pkg/security/authn/utils/utils.go
  pkg/config/security/security.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/ecdh_support.yaml
Labels: area/networking, area/security, size/L

#43801 Print waypoint name in istioctl pc workloads
  istioctl/pkg/writer/ztunnel/configdump/workload.go
Labels: area/user experience, size/S, release-notes-none, area/ambient

#43788 controller: minor refactor of function to method
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/M, release-notes-none

#43742 [release-1.16] Manual cherry-pick to fix #43590 and #43783
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/networking/core/v1alpha3/accesslog.go
  pilot/pkg/networking/core/v1alpha3/accesslog_test.go
  releasenotes/notes/43372.yaml
Labels: size/L

#43709 Fix name resolution in istioctl command
  istioctl/pkg/util/handlers/handlers.go
  istioctl/pkg/util/handlers/handlers_test.go
  releasenotes/notes/43709.yaml
Labels: area/user experience, size/L, cherrypick/release-1.17

#43819 [release-1.17] Fix name resolution in istioctl command
  istioctl/pkg/util/handlers/handlers.go
  istioctl/pkg/util/handlers/handlers_test.go
  releasenotes/notes/43709.yaml
Labels: size/L, release-notes-none

#43822 Fix analyzing ambient mode authorizationpolicy has no matching workload message error
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/authz/authorizationpolicies.go
  pkg/config/analysis/analyzers/testdata/authorizationpolicies.yaml
  pkg/config/analysis/analyzers/util/in_mesh.go
Labels: area/user experience, size/M, release-notes-none, area/ambient

#43041 Add otel tracing example
  manifests/profiles/demo.yaml
  samples/open-telemetry/als/README.md
  samples/open-telemetry/otel.yaml
  samples/open-telemetry/tracing/README.md
  samples/open-telemetry/tracing/telemetry.yaml
Labels: kind/docs, size/L, release-notes-none

#43834 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43815 pkg/queue: add HasSynced
  pkg/queue/delay.go
  pkg/queue/instance.go
  pkg/queue/instance_test.go
Labels: size/M, release-notes-none

#43839 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43840 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43844 Automator: update common-files@release-1.16 in istio/istio@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43845 Automator: update common-files@release-1.15 in istio/istio@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43846 Automator: update istio/client-go@release-1.16 dependency in istio/istio@release-1.16
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43832 endpointslice: remove support for serving v1beta1
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pkg/kube/client.go
  pkg/kube/fakemirror.go
  releasenotes/notes/es-drop-beta.yaml
Labels: size/L

#43847 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43828 change the cert serial number output to hex
  istioctl/pkg/writer/compare/sds/util.go
  releasenotes/notes/43765.yaml
Labels: area/user experience, size/S

#43820 refactor: move cb(handleService/handlePod) as method of ambient index
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
Labels: size/L, release-notes-none

#43854 Automator: update common-files@release-1.17 in istio/istio@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43856 Automator: update proxy@release-1.17 in istio/istio@release-1.17
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#43855 Automator: update istio/client-go@release-1.17 dependency in istio/istio@release-1.17
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43851 [release-1.17] Bump x/net to 0.7.0 in release-1.17 to fix CVE-2022-41723
  go.mod
  go.sum
Labels: area/security, size/S, release-notes-none

#43860 Bump Helm to 3.11.1
  go.mod
  go.sum
Labels: area/security, size/XS, release-notes-none

#43809 Break system namespace and ingressgateway assumptions
  pkg/test/framework/components/istio/cleanup.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  pkg/test/framework/components/istio/kube.go
  pkg/test/kube/dump.go
  pkg/test/kube/util.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: area/test and release, size/L, release-notes-none, cherrypick/release-1.17

#43831 kube: wrapper around informer PART 1: codegen
  pkg/config/schema/codegen/collections.go
  pkg/config/schema/codegen/common.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/kube/kubetypes/types.go
Labels: size/L, release-notes-none

#43867 ServiceEntry IP allocation: Stable IP when used in multiple namespaces
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  releasenotes/notes/43858.yaml
Labels: area/networking, ok-to-test, size/L, release-notes-none, cherrypick/release-1.17

#43850 Add output dir option to bug-report
  releasenotes/notes/43850.yaml
  tools/bug-report/pkg/bugreport/bugreport.go
  tools/bug-report/pkg/bugreport/flags.go
Labels: area/test and release, area/user experience, size/S

#43823 refactor mesh tls settings
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/security/authn/v1beta1/policy_applier.go
Labels: size/M, release-notes-none

#43873 [bugfix] Use ReadHeaderTimeout instead of ReadTimeout when gRPC is multiplexed
  pilot/pkg/bootstrap/server.go
Labels: size/XS, release-notes-none

#43879 [release-1.17] ServiceEntry IP allocation: Stable IP when used in multiple namespaces
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  releasenotes/notes/43858.yaml
Labels: size/L, release-notes-none

#43869 [release-1.17] Run update_deps.sh
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: size/S, release-notes-none

#43866 [release-1.17] Break system namespace and ingressgateway assumptions
  pkg/test/framework/components/istio/cleanup.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  pkg/test/framework/components/istio/kube.go
  pkg/test/kube/dump.go
  pkg/test/kube/util.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/common/traffic.go
Labels: size/L, release-notes-none

#43885 [release-1.17] [bugfix] Use ReadHeaderTimeout instead of ReadTimeout when gRPC is multiplexed
  pilot/pkg/bootstrap/server.go
Labels: size/XS, release-notes-none

#43876 make inbound port configurable
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  pilot/pkg/model/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_inbound.go
  pkg/config/mesh/mesh.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.38.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/43876.yaml
Labels: area/environments, size/S

#43884 [release-1.16] [bugfix] Use ReadHeaderTimeout instead of ReadTimeout when gRPC is multiplexed
  pilot/pkg/bootstrap/server.go
Labels: size/XS, release-notes-none

#43794 [release-1.16] Include trustDomains from CaCertificates in SAN Validation
  pilot/pkg/networking/plugin/authn/util.go
  pilot/pkg/networking/plugin/authn/util_test.go
  releasenotes/notes/add_trust_domans_san_validator.yaml
Labels: size/M, release-notes-none

#43887 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43396 fix: `istioctl install --set` and `istioctl manifest generate --set` boolean var failed
  operator/cmd/mesh/install.go
  operator/cmd/mesh/manifest-generate.go
  operator/pkg/manifest/shared.go
  operator/pkg/manifest/shared_test.go
  operator/pkg/util/testdata/yaml/input/convention_boolean.yaml
  operator/pkg/util/testdata/yaml/input/convention_float.yaml
  operator/pkg/util/testdata/yaml/input/convention_integer.yaml
  operator/pkg/util/testdata/yaml/output/convention_boolean.yaml
  operator/pkg/util/testdata/yaml/output/convention_float.yaml
  operator/pkg/util/testdata/yaml/output/convention_integer.yaml
  releasenotes/notes/43355.yaml
Labels: area/user experience, size/L

#43863 Drop EndpointSlice test on 1.20
  tests/integration/pilot/endpointsmode/endpointslice_test.go
Labels: size/XS, release-notes-none

#43895 cni: conditionally mount bpf fs
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: area/environments, size/XS, release-notes-none, area/ambient

#43535 Provision to provide overridden/explicit value for failoverPriority label
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
  releasenotes/notes/43535.yaml
Labels: area/networking, ok-to-test, size/L

#43852 ServiceEntry deletion - trigger endpoint shard update when some endpoints are remaining
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  releasenotes/notes/43853.yaml
Labels: ok-to-test, size/M

#43899 Update go-control-plane
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: area/test and release, size/XS, release-notes-none

#43894 [TF] add retry to default service account patch command
  pkg/test/framework/components/namespace/kube.go
Labels: size/S, release-notes-none

#43903 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43904 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#43905 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/authorization.pb.go
  pkg/workloadapi/workload.pb.go
Labels: size/S, auto-merge, release-notes-none

#43452 disable EnvoyFilter by default for telemetry
  Makefile.core.mk
  manifests/charts/istio-control/istio-discovery/templates/_helpers.tpl
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.16.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.17.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.18.yaml
  manifests/charts/istiod-remote/templates/_helpers.tpl
  manifests/charts/istiod-remote/templates/configmap.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.16.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.17.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.18.yaml
  releasenotes/notes/telemetry-native.yaml
Labels: size/L

#43872 [release-1.16] Manual cherry-pick to fix #43194
  samples/certs/README.md
  samples/certs/generate-workload.sh
  samples/certs/leaf-workload-bar-cert.pem
  samples/certs/leaf-workload-foo-cert.pem
  samples/certs/workload-bar-cert.pem
  samples/certs/workload-bar-key.pem
  samples/certs/workload-bar-root-certs.pem
  samples/certs/workload-foo-cert.pem
  samples/certs/workload-foo-key.pem
  samples/certs/workload-foo-root-certs.pem
  security/pkg/pki/ra/k8s_ra.go
  security/pkg/pki/ra/k8s_ra_test.go
Labels: area/security, size/L, release-notes-none

#43901 Simplify logic and add test
  istioctl/cmd/kubeuninject.go
  istioctl/cmd/kubeuninject_test.go
Labels: area/perf and scalability, ok-to-test, size/M, release-notes-none

#43926 port forward return error if status code is not 200
  pkg/kube/client.go
Labels: area/user experience, size/XS, release-notes-none

#43898 Optimize AmbientIndex pod handler
  pilot/pkg/serviceregistry/kube/controller/ambientindex.go
Labels: area/networking, size/S, release-notes-none, area/ambient

#43922 Map istio Health status value to envoy to simpify code
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/xds/endpoint_builder.go
Labels: size/M, release-notes-none

#43830 go.mod: bump 03-08
  cni/pkg/ebpf/server/ambient_redirect_bpf.go
  go.mod
  go.sum
  licenses/github.com/miekg/dns/LICENSE
Labels: size/L, release-notes-none

#43929 Properly embed all files
  manifests/manifest.go
Labels: size/XS, release-notes-none

#43931 Set GOMEMLIMIT on Istiod
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  releasenotes/notes/gomemlimit.yaml
Labels: size/S

#43940 Fix demo profile doc test
  manifests/profiles/demo.yaml
  samples/open-telemetry/tracing/README.md
  samples/open-telemetry/tracing/telemetry.yaml
Labels: area/test and release, size/XS, release-notes-none

#43945 Pass rules to iptables-restore via stdin instead of a file
  cni/pkg/plugin/iptables.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin_dryrun_test.go
  releasenotes/notes/43945.yaml
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: area/networking, ok-to-test, size/L

#42874 Updating the sample helloworld python base image
  samples/helloworld/src/Dockerfile
Labels: area/test and release, size/XS, release-notes-none

#43149 fix(sec): upgrade tornado to 5.1
  samples/bookinfo/src/productpage/requirements.txt
Labels: ok-to-test, size/XS, release-notes-none

#43731 fix env vars since they collide with kubernetes
  samples/bookinfo/src/productpage/productpage.py
  samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
Labels: size/XS, release-notes-none
