Repository istio/istio, pull requests merged in 2024-11, with the labels that each got.

#53747 Minor fixes for niche cases of ambient controller
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
Labels: size/L, release-notes-none

#53748 fix integration-test TestBadWasmRemoteLoad for default deny-all policy
  tests/integration/telemetry/api/stats_test.go
  tests/integration/telemetry/api/wasmplugin_test.go
Labels: area/test and release, ok-to-test, size/S, release-notes-none

#53702 prevent double lock
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/network.go
Labels: size/S, release-notes-none

#53746 Update path template validation for AuthzPolicy
  pkg/config/security/security.go
  pkg/config/security/security_test.go
  tests/integration/security/authz_test.go
Labels: size/L, release-notes-none

#53751 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#53756 Automator: update common-files@release-1.24 in istio/istio@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53757 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53758 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53754 Clarify description of ISTIO_DELTA_XDS env variable in pilot-discovery docs
  pilot/pkg/features/experimental.go
Labels: kind/docs, area/networking, size/XS, release-notes-none

#53762 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53763 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53764 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53766 addon: bump prometheus version
  manifests/addons/gen.sh
  samples/addons/prometheus.yaml
Labels: size/M, release-notes-none

#53773 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53772 cleanup deprecated function wait.PollImmediateUntil
  pilot/pkg/leaderelection/k8sleaderelection/leaderelection.go
Labels: size/XS, release-notes-none

#53259 control service and policy tracing tags based on api
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/tracing.go
  pilot/pkg/networking/core/tracing_test.go
Labels: size/L, release-notes-none

#53760 Disable DNS jitter to 0
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
  releasenotes/notes/52877.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.24

#53776 [release-1.24] Undo DNS jitter
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
  releasenotes/notes/52877.yaml
Labels: size/S, release-notes-none

#53783 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53629 [release-1.23] Manual backport of #53624
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  releasenotes/notes/53624.yaml
Labels: area/environments, size/S

#53785 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53784 ambient: fix a bug preventing rewrite from working
  pilot/pkg/networking/core/listener_waypoint.go
Labels: size/M, release-notes-none, cherrypick/release-1.24

#53789 [release-1.24] ambient: fix a bug preventing rewrite from working
  pilot/pkg/networking/core/listener_waypoint.go
Labels: size/M, release-notes-none

#53597 krt: initial debug interface
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/meshconfig.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/xds/debug.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/core.go
  pkg/kube/krt/debug.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/recomputetrigger.go
  pkg/kube/krt/singleton.go
  pkg/kube/krt/static.go
  pkg/kube/krt/testing.go
  pkg/workloadapi/security/authorization_json.gen.go
  pkg/workloadapi/workload_json.gen.go
  tools/proto/buf.golang-json.yaml
  tools/proto/proto.mk
Labels: size/L, release-notes-none

#53787 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53788 [release-1.24] fix filterStateObjectsToLog
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/networking/core/accesslog.go
  releasenotes/notes/53778.yaml
Labels: size/L, release-notes-none

#53792 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53661 Enable PILOT_ENABLE_IP_AUTOALLOCATE by default for Istio 1.25
  manifests/charts/base/files/profile-compatibility-version-1.24.yaml
  manifests/charts/default/files/profile-compatibility-version-1.24.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.24.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.24.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.24.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.24.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.24.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.24.yaml
  manifests/helm-profiles/compatibility-version-1.24.yaml
  pilot/pkg/controllers/ipallocate/ipallocate_test.go
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/serviceentry_simulation_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/xds/nds_test.go
  releasenotes/notes/ip-allocation-v2-default.yaml
  tests/integration/iop-ambient-test-defaults.yaml
  tests/integration/pilot/common/routing.go
Labels: size/M, release-notes-none

#53794 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53796 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53795 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53703 Remove duplicate ambient index sync all
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/serviceregistry/kube/controller/network_test.go
Labels: size/M, release-notes-none

#53793 Replace min/max helpers with built-in min/max
  istioctl/pkg/writer/table/writer.go
  pilot/pkg/networking/core/httproute.go
Labels: ok-to-test, size/S, release-notes-none

#53804 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53798 add e2e for FILTER_STATE accesslog command
  tests/integration/telemetry/api/accesslogs_test.go
  tests/integration/telemetry/api/setup_test.go
  tests/integration/telemetry/api/testdata/accesslog/enable-filter-state-log.yaml
Labels: size/M, release-notes-none

#52978 helm: dynamic naming of ztunnel chart
  manifests/charts/ztunnel/templates/_helpers.tpl
  manifests/charts/ztunnel/templates/daemonset.yaml
  manifests/charts/ztunnel/templates/rbac.yaml
  manifests/charts/ztunnel/values.yaml
  manifests/profiles/default.yaml
  manifests/sample-charts/ambient/values.yaml
  releasenotes/notes/ztunnel-helm-chart.yaml
Labels: size/M

#53807 Fix bug where invalid redirect codes in VirtualService caused proto marshal errors
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
Labels: area/networking, size/M, release-notes-none, cherrypick/release-1.22, cherrypick/release-1.23, cherrypick/release-1.24

#53808 [release-1.23] Fix bug where invalid redirect codes in VirtualService caused proto marshal errors
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
Labels: size/M, release-notes-none

#53811 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53810 [release-1.22] Fix bug where invalid redirect codes in VirtualService caused proto marshal errors
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
Labels: size/M, release-notes-none

#53801 Fix merging duration influence dst duration
  pilot/pkg/networking/core/cluster_builder.go
  pkg/proto/merge/merge.go
  pkg/proto/merge/merge_test.go
  releasenotes/notes/53801.yaml
Labels: size/M

#53818 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53819 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53820 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53813 fix TestFilterStateAccessLog not working as expected
  tests/integration/telemetry/api/accesslogs_test.go
  tests/integration/telemetry/api/setup_test.go
Labels: size/S, release-notes-none

#53822 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53824 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53814 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53830 Drop core dump annotation
  pkg/kube/inject/validate.go
Labels: size/XS, release-notes-none

#53833 [release-1.24] Fix merging duration influence dst duration
  pilot/pkg/networking/core/cluster_builder.go
  pkg/proto/merge/merge.go
  pkg/proto/merge/merge_test.go
  releasenotes/notes/53801.yaml
Labels: size/M, release-notes-none

#53835 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53826 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53841 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53821 Use the zone from the metadata for creating locality
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
Labels: size/L, release-notes-none

#53842 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53848 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53852 fix path join on windows
  operator/pkg/helm/helm.go
  operator/pkg/helm/path.go
  operator/pkg/helm/path_windows.go
  releasenotes/notes/53852.yaml
Labels: area/environments, size/M

#53850 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53856 [release-1.24] fix path join on windows
  operator/pkg/helm/helm.go
  operator/pkg/helm/path.go
  operator/pkg/helm/path_windows.go
  releasenotes/notes/53852.yaml
Labels: size/M, release-notes-none

#53861 Istio CNI in hostnet should have corresponding dnsPolicy
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/53861.yaml
Labels: size/S, area/ambient

#53869 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53871 [release-1.24] Istio CNI in hostnet should have corresponding dnsPolicy
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/53861.yaml
Labels: size/S, release-notes-none

#53876 [fix]: do not h2upgrade when useClientProtocol is set in DR
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
Labels: area/networking, ok-to-test, size/S, release-notes-none

#53339 istioctl: add revision shortcode for analyze
  istioctl/pkg/analyze/analyze.go
  releasenotes/notes/53339.yaml
Labels: size/S, release-notes-none

#53881 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53882 cleanup deadcode
  cni/pkg/util/executil.go
Labels: area/networking, ok-to-test, size/M, release-notes-none

#53895 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53900 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53897 optimize performance and minor refactor
  pilot/pkg/model/sidecar.go
Labels: area/networking, area/perf and scalability, ok-to-test, size/S, release-notes-none

#53910 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53896 ambient: remove legacy tproxy redirction mode
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/iptables/iptables.go
  cni/pkg/iptables/iptables_test.go
  cni/pkg/iptables/testdata/tproxy.golden
  cni/pkg/iptables/testdata/tproxy_ipv6.golden
  cni/pkg/nodeagent/options.go
  cni/pkg/nodeagent/server.go
Labels: size/L, release-notes-none

#53898 bump envoy go control plane
  go.mod
  go.sum
  pilot/pkg/model/extensions.go
  pilot/pkg/model/extensions_test.go
  pkg/config/xds/filter_types.gen.go
  pkg/wasm/convert.go
Labels: size/S, release-notes-none

#53912 dns jitter (again)
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
  releasenotes/notes/52877.yaml
Labels: size/S

#53925 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53927 Sample: bump jaeger version
  samples/addons/jaeger.yaml
Labels: size/XS, release-notes-none

#53557 Fixed incorrect No data in Grafana dashboard panels
  manifests/addons/dashboards/istio-extension-dashboard.json
  manifests/addons/dashboards/istio-performance-dashboard.json
  manifests/addons/dashboards/istio-service-dashboard.json
  manifests/addons/dashboards/istio-workload-dashboard.json
  releasenotes/notes/grafana-rate-interval.yaml
  samples/addons/grafana.yaml
Labels: area/extensions and telemetry, ok-to-test, area/user experience, size/L

#53880 group manifestSet contents by component type
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/render/manifest.go
  releasenotes/notes/53880.yaml
Labels: area/environments, size/M, cherrypick/release-1.24

#53708 return error instead of just logging it and add detailed error messages
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: size/M, release-notes-none

#53929 Remove misleading platform value
  manifests/charts/base/values.yaml
Labels: size/XS, release-notes-none

#53862 Explicitly specifiying ipset revision seems to fix some ipset creation/insertion corner cases
  cni/pkg/ipset/nldeps_linux.go
  releasenotes/notes/53862.yaml
Labels: area/networking, size/S, area/ambient

#53930 [release-1.24] group manifestSet contents by component type
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/render/manifest.go
  releasenotes/notes/53880.yaml
Labels: size/M, release-notes-none

#53892 update envoyproxy ratelimit version
  samples/ratelimit/rate-limit-service.yaml
Labels: size/XS, release-notes-none

#53936 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53937 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53932 Bump go mod dependencies
  go.mod
  go.sum
  licenses/github.com/planetscale/vtprotobuf/LICENSE
  licenses/github.com/planetscale/vtprotobuf/generator/pattern/LICENSE
Labels: size/L, release-notes-none

#53809 [release-1.24] Fix bug where invalid redirect codes in VirtualService caused proto marshal errors
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
Labels: size/M, release-notes-none

#53939 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53943 fix authorization APIs are not consistent in istio and ztunnel
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/security/authorization.proto
Labels: size/XS, release-notes-none

#53945 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53888 Set appArmor profile for istio-cni to unconfined
  cni/pkg/nodeagent/ztunnelserver.go
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/53829.yaml
Labels: area/security, size/S, area/ambient, cherrypick/release-1.24

#53946 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53954 Fix nil pointer when processing invalid waypoint backendrefs
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/route/route.go
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none, area/ambient, cherrypick/release-1.22, cherrypick/release-1.23, cherrypick/release-1.24

#53955 [release-1.24] Fix nil pointer when processing invalid waypoint backendrefs
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/route/route.go
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none

#53935 ambient: fully support Gateway's with IP address in status
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  releasenotes/notes/waypoint-revision.yaml
Labels: size/L, cherrypick/release-1.24

#53962 Update BASE_VERSION to 1.23-2024-11-19T19-02-51
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#53958 Fix flake in TestQueue
  pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go
Labels: size/XS, release-notes-none

#53959 Update BASE_VERSION to 1.24-2024-11-19T19-01-56
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#53960 Update BASE_VERSION to master-2024-11-19T19-02-33
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#53951 Ignore delete cmds errors from optional iptables rules
  cni/pkg/iptables/iptables.go
  releasenotes/notes/53951.yaml
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
Labels: area/networking, size/S, cherrypick/release-1.24

#53965 Remove istio-clean-iptables utility
  CODEOWNERS
  pilot/cmd/pilot-agent/app/cmd.go
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-clean-iptables/pkg/cmd/root.go
  tools/istio-clean-iptables/pkg/cmd/testdata/dns-uid-gid.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/dns.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/empty.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/inbound-interception-mode.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/ipnets-with-kube-virt-interfaces.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/kube-virt-interfaces.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups-exclude.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups.golden
  tools/istio-clean-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/e2e/e2e_test.go
Labels: area/environments, area/networking, size/XXL, release-notes-none

#53966 [release-1.24] Ignore delete cmds errors from optional iptables rules
  cni/pkg/iptables/iptables.go
  releasenotes/notes/53951.yaml
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
Labels: size/S, release-notes-none

#53963 [release-1.24] ambient: fully support Gateway's with IP address in status
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  releasenotes/notes/waypoint-revision.yaml
Labels: size/L, release-notes-none

#53953 Set AppArmor annotation instead of appArmorProfile
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/53829.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.24

#53706 log: fix the wrong error message
  pkg/log/options.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#53894 feat(istioctl): add support for custom authz
  istioctl/pkg/authz/authz_test.go
  istioctl/pkg/authz/listener.go
  istioctl/pkg/authz/testdata/configdump.yaml
  releasenotes/notes/53894.yaml
Labels: ok-to-test, area/user experience, size/XXL

#53970 [release 1.24] Set AppArmor annotation to unconfined on istio-cni-node (#53953)
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/53829.yaml
Labels: size/S

#53975 addons: bump addons version
  manifests/addons/gen.sh
  samples/addons/kiali.yaml
  samples/addons/prometheus.yaml
Labels: size/L, release-notes-none

#53976 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53978 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53982 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53983 [release-1.23] return error instead of just logging it and add detailed error messages
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: size/M, release-notes-none

#53984 [release-1.24] return error instead of just logging it and add detailed error messages
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: size/M, release-notes-none

#53985 Add release note that was missed for PR 53708
  releasenotes/notes/propagate-injection-config-errors.yaml
Labels: size/S, cherrypick/release-1.23, cherrypick/release-1.24

#53988 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53987 [release-1.24] Add release note that was missed for PR 53708
  releasenotes/notes/propagate-injection-config-errors.yaml
Labels: size/S, release-notes-none

#53997 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53995 pilot: fix `types=wds` not working in `/debug/config_dump`
  pilot/pkg/xds/debug.go
Labels: size/XS, release-notes-none

#53993 1.24: pick up fix for gateway API breaking change
  go.mod
  go.sum
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/XS, release-notes-none

#53969 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53999 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54011 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53981 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54013 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54014 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54015 Make all inpod delete rules optional
  cni/pkg/iptables/iptables.go
Labels: area/networking, size/S, release-notes-none

#54021 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54026 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54010 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54028 fix authz pol waypoint status
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
Labels: size/L, release-notes-none, area/ambient, cherrypick/release-1.24

#54030 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54031 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53980 Fix telemetry tracing tests on Openshift
  pkg/test/framework/components/zipkin/kube.go
  pkg/test/framework/components/zipkin/zipkin.go
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
  tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
Labels: area/extensions and telemetry, ok-to-test, size/L, release-notes-none

#54032 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54029 Run make gen with latest image
  operator/pkg/apis/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/kube/namespace/filter.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/workload.pb.go
  pkg/zdsapi/zds.pb.go
Labels: area/test and release, size/XS, release-notes-none

#54035 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54039 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54040 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54041 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#54044 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54049 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54038 [release-1.24] fix authz pol waypoint status
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
Labels: size/L, release-notes-none

#54052 adsc: close connection when we reconnect
  pkg/adsc/delta.go
Labels: size/XS, release-notes-none

#54054 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54055 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53974 istioctl: fix pc secret performance issue
  istioctl/pkg/proxyconfig/proxyconfig.go
  releasenotes/notes/53974.yaml
Labels: size/M

#54064 fix istioctl waypoint delete deletes things which are not waypoints
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/54064.yaml
Labels: area/user experience, size/S, release-notes-none

#54066 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54067 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54069 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54072 Update BASE_VERSION to 1.22-2024-11-26T19-01-41
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none
