Repository istio/istio, pull requests merged in 2024-08, with the labels that each got.

#52453 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52451 Drop legacy log rotation
  go.mod
  go.sum
  licenses/gopkg.in/natefinch/lumberjack.v2/LICENSE
  pkg/log/config.go
  pkg/log/config_test.go
  pkg/log/options.go
  pkg/log/options_test.go
  releasenotes/notes/drop-log-rotate.yaml
Labels: size/L, release-notes-none

#52316 Refactor keycertbundle
  releasenotes/notes/52193.yaml
  security/pkg/pki/ca/ca.go
  security/pkg/pki/util/keycertbundle.go
  security/pkg/pki/util/keycertbundle_test.go
  security/pkg/server/ca/monitoring.go
  security/pkg/server/ca/server.go
Labels: area/test and release, area/extensions and telemetry, size/L

#52445 Consolidate on YAML library usage
  common/config/.golangci.yml
  istioctl/pkg/precheck/precheck.go
  istioctl/pkg/validate/validate.go
  operator/pkg/patch/patch.go
  operator/pkg/tpath/tree.go
  operator/pkg/tpath/util.go
  operator/pkg/translate/yaml_tree.go
  operator/pkg/version/version.go
  operator/pkg/version/version_test.go
  pilot/pkg/config/file/store.go
  pilot/pkg/config/kube/crd/conversion.go
  pkg/test/framework/components/cluster/config.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/deployment/flags.go
  pkg/test/framework/components/environment/kube/flags.go
  pkg/test/framework/config/config.go
  pkg/test/framework/resource/settings.go
  pkg/test/framework/tools/featuresgen/cmd/root.go
  pkg/test/framework/tools/featuresgen/cmd/root_test.go
  pkg/test/framework/tools/featuresgen/main.go
  tools/golangci-override.yaml
Labels: size/XL, release-notes-none

#52441 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52462 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52464 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52465 Wrong expiration times
  security/pkg/server/ca/server.go
Labels: size/XS, release-notes-none

#52461 Add container ports to istio-cni daemonset
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: ok-to-test, size/XS, release-notes-none, area/ambient

#52460 [release-1.23] fix auto_allocate validation message to account for v2 ip auto allocation
  pilot/pkg/controllers/ipallocate/ipallocate.go
  pilot/pkg/controllers/ipallocate/ipallocate_test.go
  pilot/pkg/networking/serviceentry/ip_autoallocation.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pkg/config/validation/validation.go
  releasenotes/notes/52422.yaml
Labels: size/S, release-notes-none

#52323 `istio-cni` - stop writing `kubeconfig` to shared CNI netdir
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/cniconfig.go
  cni/pkg/install/cniconfig_test.go
  cni/pkg/install/install.go
  cni/pkg/install/kubeconfig.go
  cni/pkg/install/kubeconfig_test.go
  cni/pkg/install/testdata/bridge.conf.golden
  cni/pkg/install/testdata/istio-cni.conf
  cni/pkg/install/testdata/list-with-istio.conflist.golden
  cni/pkg/install/testdata/list.conflist.golden
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/plugin_dryrun_test.go
  cni/pkg/plugin/plugin_test.go
  cni/test/install_cni.go
  cni/test/testdata/expected/10-calico.conflist-istioconfig
  cni/test/testdata/expected/YYY-istio-cni.conf
  cni/test/testdata/expected/minikube_cni.conflist.expected
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  releasenotes/notes/52323.yaml
Labels: size/L, cherrypick/release-1.23

#52454 install: Cleanup validation
  manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
  operator/pkg/manifest/shared.go
  tests/fuzz/misc_fuzzers.go
Labels: size/L, release-notes-none

#52475 Update BASE_VERSION to 1.23-2024-08-01T19-01-15
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52474 Update BASE_VERSION to 1.22-2024-08-01T19-02-54
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52473 Update BASE_VERSION to 1.21-2024-08-01T19-02-13
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52398 ambient: support clients sending TLS
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/networking/core/cluster_tls_test.go
  pilot/pkg/networking/core/cluster_waypoint.go
  releasenotes/notes/backend-tls.yaml
  tests/integration/ambient/baseline_test.go
Labels: size/L, release-notes-none, cherrypick/release-1.23

#52365 Update GetXXAddressForProxy
  pilot/pkg/config/kube/gateway/context.go
  pilot/pkg/features/experimental.go
  pilot/pkg/model/context.go
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
  pilot/pkg/networking/core/httproute_test.go
  pilot/pkg/networking/core/serviceentry_simulation_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pkg/dns/server/name_table_test.go
  tests/integration/pilot/common/routing.go
Labels: size/L, release-notes-none

#52416 respect cluster statname pattern if provided
  pilot/pkg/features/telemetry.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/cluster_waypoint.go
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/listener.go
  pilot/pkg/networking/core/listener_inbound.go
  pilot/pkg/networking/grpcgen/cds.go
  pilot/pkg/networking/util/util.go
Labels: size/L, release-notes-none, cherrypick/release-1.23

#52476 Update BASE_VERSION to master-2024-08-01T19-01-15
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52478 [release-1.23] ambient: support clients sending TLS
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/networking/core/cluster_tls_test.go
  pilot/pkg/networking/core/cluster_waypoint.go
  releasenotes/notes/backend-tls.yaml
  tests/integration/ambient/baseline_test.go
Labels: size/L, release-notes-none

#52329 [release-1.23] Do not add pod to ipset if we have a "partial failure" adding to the dataplane.
  cni/pkg/nodeagent/cni-watcher_test.go
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/net_test.go
  cni/pkg/nodeagent/server.go
  cni/pkg/nodeagent/server_test.go
  releasenotes/notes/52320.yaml
Labels: size/XXL, release-notes-none

#52319 implement addressing per-hosts for autoallocate
  pilot/pkg/controllers/ipallocate/ipallocate.go
  pilot/pkg/controllers/ipallocate/ipallocate_test.go
  pilot/pkg/networking/serviceentry/ip_autoallocation.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  releasenotes/notes/52319.yaml
Labels: area/networking, size/XL, cherrypick/release-1.23

#52483 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52415 rm redudant instance param
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/cluster_builder.go
Labels: size/S, release-notes-none

#52480 ambient: do not allow service waypoint to have a waypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#52467 operator: misc code cleanup
  operator/cmd/mesh/uninstall.go
  operator/pkg/translate/translate.go
  operator/pkg/util/yaml.go
Labels: size/M, release-notes-none

#52484 [release-1.23] ambient: do not allow service waypoint to have a waypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
Labels: size/XS, release-notes-none

#52488 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52489 remove unneeded func isAllowedKubernetesAudience
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
Labels: ok-to-test, size/M, release-notes-none

#52472 operator: move proto from api to this repo
  istioctl/pkg/validate/validate_test.go
  operator/cmd/mesh/uninstall.go
  operator/pkg/apis/istio/common.go
  operator/pkg/apis/istio/v1alpha1/common.go
  operator/pkg/apis/istio/v1alpha1/deepcopy_test.go
  operator/pkg/apis/istio/v1alpha1/operator.pb.go
  operator/pkg/apis/istio/v1alpha1/operator.proto
  operator/pkg/apis/istio/v1alpha1/operator_json.go
  operator/pkg/apis/istio/v1alpha1/testdata/quantity.yaml
  operator/pkg/apis/istio/v1alpha1/types.go
  operator/pkg/apis/istio/v1alpha1/validation/validation.go
  operator/pkg/apis/istio/v1alpha1/validation/validation_test.go
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  operator/pkg/apis/istio/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/component/component.go
  operator/pkg/controlplane/control_plane.go
  operator/pkg/controlplane/control_plane_test.go
  operator/pkg/helmreconciler/apply_test.go
  operator/pkg/helmreconciler/reconciler.go
  operator/pkg/manifest/shared.go
  operator/pkg/name/name.go
  operator/pkg/name/name_test.go
  operator/pkg/patch/patch.go
  operator/pkg/patch/patch_test.go
  operator/pkg/translate/translate.go
  operator/pkg/translate/translate_common.go
  operator/pkg/translate/translate_common_test.go
  operator/pkg/translate/translate_test.go
  operator/pkg/translate/translate_value.go
  operator/pkg/util/merge_iop.go
  operator/pkg/util/merge_iop_test.go
  operator/pkg/validate/validate.go
  operator/pkg/validate/validate_test.go
  operator/pkg/validate/validate_values_test.go
  pkg/test/framework/components/istio/kube.go
  tests/fuzz/misc_fuzzers.go
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/regression_test.go
Labels: size/XXL, release-notes-none

#52495 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52496 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52466 Bug/stale cert expiration logs
  pilot/pkg/bootstrap/istio_ca.go
  pkg/monitoring/monitortest/test.go
  releasenotes/notes/stale-cert-expiration-metrics.yaml
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: area/security, size/L

#52498 Automator: update ztunnel@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52408 [release-1.23] manifest: Ensure profile is a string
  manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
  releasenotes/notes/52017.yaml
Labels: size/S, release-notes-none

#52499 [release-1.23] Fix 52273: add CNI_NET_DIR back. It's used.
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  releasenotes/notes/52127.yaml
Labels: size/XS, release-notes-none

#52482 Fix stale GVK in benchmark test
  pilot/pkg/config/memory/store_test.go
Labels: size/M, release-notes-none

#52491 Fix typo of InsertDataToConfigMap func description
  security/pkg/k8s/configutil.go
Labels: ok-to-test, size/XS, release-notes-none

#52502 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52504 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52505 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52506 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52468 operator: remove `profile` commands
  istioctl/cmd/root.go
  operator/cmd/mesh/profile-dump.go
  operator/cmd/mesh/profile-dump_test.go
  operator/cmd/mesh/profile-list.go
  operator/cmd/mesh/profile-list_test.go
  operator/cmd/mesh/profile.go
  operator/cmd/mesh/shared.go
  releasenotes/notes/operator-drop-dump.yaml
Labels: size/XL, release-notes-none

#52500 [release-1.23] respect cluster statname pattern if provided
  pilot/pkg/features/telemetry.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/cluster_waypoint.go
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/listener.go
  pilot/pkg/networking/core/listener_inbound.go
  pilot/pkg/networking/grpcgen/cds.go
  pilot/pkg/networking/util/util.go
Labels: size/L, release-notes-none

#52485 hand written IstioEndpoint deepcopy
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
Labels: area/networking, area/perf and scalability, size/M, release-notes-none

#52494 [release-1.23] cherry-pick: implement addressing per-hosts for autoallocate (#52319)
  pilot/pkg/controllers/ipallocate/ipallocate.go
  pilot/pkg/controllers/ipallocate/ipallocate_test.go
  pilot/pkg/networking/serviceentry/ip_autoallocation.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  releasenotes/notes/52319.yaml
Labels: area/networking, size/XL

#52459 Fix replacements errors in helm charts and templates
  manifests/charts/base/files/profile-openshift.yaml
  manifests/charts/default/files/profile-openshift.yaml
  manifests/charts/gateway/files/profile-openshift.yaml
  manifests/charts/gateways/istio-egress/files/profile-openshift.yaml
  manifests/charts/gateways/istio-ingress/files/profile-openshift.yaml
  manifests/charts/istio-cni/files/profile-openshift.yaml
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/templates/network-attachment-definition.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-openshift.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  manifests/charts/istiod-remote/files/profile-openshift.yaml
  manifests/charts/ztunnel/files/profile-openshift.yaml
  manifests/helm-profiles/openshift.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: ok-to-test, size/M, release-notes-none

#52514 Allow setting resources to null in gateway chart
  manifests/charts/gateway/values.schema.json
Labels: size/XS, release-notes-none, cherrypick/release-1.22, cherrypick/release-1.23

#52501 add names to static listeners
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
  pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: release-notes-none

#52515 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52518 [release-1.23] Allow setting resources to null in gateway chart
  manifests/charts/gateway/values.schema.json
Labels: size/XS, release-notes-none

#52517 [release-1.22] Allow setting resources to null in gateway chart
  manifests/charts/gateway/values.schema.json
Labels: size/XS, release-notes-none

#52524 Add release notes for dual-stack support promotion
  releasenotes/notes/dual-stack-alpha.yaml
Labels: size/S, release-notes-none

#52533 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51966 Strict CSR validation in k8s CSR workflow
  releasenotes/notes/51966.yaml
  security/pkg/pki/ra/common.go
  security/pkg/pki/ra/common_test.go
  security/pkg/pki/ra/k8s_ra_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_csr.go
  security/pkg/pki/util/san.go
  security/pkg/pki/util/san_test.go
Labels: area/security, area/user experience, size/L

#52431 add gateway.istio.io/managed: istio.io-gateway-controller to managed gateway
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/custom-class.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/infrastructure-labels-annotations.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect-infra.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/proxy-config-crd.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: size/S, release-notes-none

#52539 Update BASE_VERSION to 1.23-2024-08-06T19-01-26
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52537 Update BASE_VERSION to 1.21-2024-08-06T19-01-21
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52538 Update BASE_VERSION to 1.22-2024-08-06T19-01-22
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52526 [release-1.23] pin go-control-plane
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#52543 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52302 filter destinations using sourceNamespace
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  releasenotes/notes/51936.yaml
Labels: ok-to-test, size/XL

#52550 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#52540 Be explicit to work around K8S capability validation bug
  manifests/charts/ztunnel/templates/daemonset.yaml
  releasenotes/notes/52540.yaml
Labels: area/security, size/S, area/ambient

#52560 Fix flake in TestCreateSidecarScope
  pilot/pkg/model/sidecar_test.go
Labels: size/S, release-notes-none

#52555 Bind waypoint HBONE listener to dual stack
  pilot/pkg/networking/core/listener_waypoint.go
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#52563 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#52565 Automator: update ztunnel@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52556 [release-1.23] Strict CSR validation in k8s CSR workflow
  releasenotes/notes/51966.yaml
  security/pkg/pki/ra/common.go
  security/pkg/pki/ra/common_test.go
  security/pkg/pki/ra/k8s_ra_test.go
  security/pkg/pki/util/generate_cert.go
  security/pkg/pki/util/generate_csr.go
  security/pkg/pki/util/san.go
  security/pkg/pki/util/san_test.go
Labels: size/L, release-notes-none

#52562 [release-1.23] Bind waypoint HBONE listener to dual stack
  pilot/pkg/networking/core/listener_waypoint.go
Labels: size/XS, release-notes-none

#52535 Add MutateStruct function for fuzz test
  pilot/pkg/model/fuzz_test.go
  pkg/fuzz/util.go
  pkg/fuzz/util_test.go
Labels: area/test and release, size/L, release-notes-none

#52568 Automator: update common-files@release-1.22 in istio/istio@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#52569 Automator: update istio/client-go@release-1.22 dependency in istio/istio@release-1.22
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#52570 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52552 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52549 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52575 fix mutate circular data structure and improve test case
  pilot/pkg/model/fuzz_test.go
  pkg/fuzz/util.go
  pkg/fuzz/util_test.go
Labels: area/test and release, size/L, release-notes-none

#52580 Automator: update common-files@release-1.23 in istio/istio@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#52581 Automator: update istio/client-go@release-1.23 dependency in istio/istio@release-1.23
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#52582 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52577 Bump docker go dep
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#52587 Update BASE_VERSION to master-2024-08-08T19-01-18
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52584 Update BASE_VERSION to 1.22-2024-08-08T19-01-18
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52585 Update BASE_VERSION to 1.21-2024-08-08T19-02-34
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52586 Update BASE_VERSION to 1.23-2024-08-08T19-01-38
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#52579 1.21: bump docker go dep
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#52591 istioctl: support parsing out v1 CRDs
  istioctl/pkg/writer/envoy/configdump/route.go
  istioctl/pkg/writer/envoy/configdump/testdata/routes/istio-gateway-http-route-prefix/configdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/routes/k8s-gateway-http-route-path-prefix/configdump.json
Labels: size/XS, release-notes-none

#52578 1.22: bump docker go dep
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#52593 Automator: update ztunnel@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52594 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52542 fix istioctl analyze report IST0145 error with wildcard host and specific subdomain
  pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  releasenotes/notes/52413.yaml
Labels: area/user experience, size/M, release-notes-none

#52566 Attempt to support SE status in analysis
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/generation_adapter.go
  pilot/pkg/status/manager.go
  pilot/pkg/status/resource.go
  pilot/pkg/status/resourcelock.go
  pilot/pkg/status/resourcelock_test.go
  pkg/config/analysis/incluster/controller.go
Labels: size/L, release-notes-none

#52596 Remove global.autoscalingv2API field from helm API
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.values.gen.yaml
  pkg/kube/inject/testdata/inputs/default.values.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.values.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.values.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml
Labels: area/environments, size/S, release-notes-none

#52604 Do not expose `testing` package beyond where its needed
  pkg/test/failer.go
  pkg/test/failer_test.go
Labels: size/S, release-notes-none

#52598 Remove comments about virtual service host matching flag
  pilot/pkg/model/sidecar.go
  pilot/pkg/networking/core/route/route.go
Labels: kind/docs, size/XS, release-notes-none

#52606 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52608 Return nil if the upstream error is io.EOF in istio-agent
  pkg/istio-agent/xds_proxy.go
Labels: release-notes-none, cherrypick/release-1.21, cherrypick/release-1.22, cherrypick/release-1.23

#52611 Drop test dep from agent
  pkg/istio-agent/health/health_probers.go
Labels: size/XS, release-notes-none

#52618 fix deepcopy lost copy field
  pilot/pkg/model/service.go
Labels: area/networking, size/S, release-notes-none

#52551 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#52621 Revert "Return nil if the upstream error is io.EOF in istio-agent"
  pkg/istio-agent/xds_proxy.go
Labels: size/XS, release-notes-none

#52623 Auto detect cilium incompatibility during cni loop
  cni/pkg/install/install.go
Labels: size/M, release-notes-none

#52625 Fix regression in CORS header validation
  pkg/config/validation/validation.go
Labels: size/S, release-notes-none, cherrypick/release-1.23

#52628 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52629 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52632 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52626 [release-1.23] Fix regression in CORS header validation
  pkg/config/validation/validation.go
Labels: size/S, release-notes-none

#52633 ztunnel: add logAsJson value to helm chart
  manifests/charts/ztunnel/templates/daemonset.yaml
  manifests/charts/ztunnel/values.yaml
  releasenotes/notes/52631.yaml
Labels: area/environments, ok-to-test, size/S, area/ambient

#52400 Fix istiod helm chart for remote
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: area/environments, size/XS, release-notes-none, cherrypick/release-1.23

#52534 ensure we finalize lines during success messages
  operator/pkg/util/progress/progress.go
  releasenotes/notes/52534.yaml
Labels: area/environments, ok-to-test, size/M

#52641 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52634 replace pkg exp/constraints with cmp
  go.mod
  pkg/slices/slices.go
  pkg/util/sets/set.go
  pkg/util/smallset/smallset.go
Labels: area/test and release, ok-to-test, size/S, release-notes-none

#52644 Fix typo and file naming
  releasenotes/notes/refactor-keycertbundle.yaml
Labels: kind/docs, release-notes-none

#52588 Fix Handling of Deletions in EDS Cache and Update Functions
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/L, release-notes-none

#52648 [release-1.22] Fix Handling of Deletions in EDS Cache and Update Functions
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/L, release-notes-none

#52649 [release-1.21] Fix Handling of Deletions in EDS Cache and Update Functions
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/L, release-notes-none

#52635 cleanup HostMatcherWithRegex deadcode
  pilot/pkg/security/authz/matcher/header.go
  pilot/pkg/security/authz/matcher/header_test.go
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/pilot_security_fuzzer.go
  tests/fuzz/regression_test.go
Labels: area/security, size/L, release-notes-none

#52643 Cleanup misc deadcode only used in tests
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pilot/pkg/networking/core/route/route_cache.go
  pilot/pkg/networking/core/route/route_cache_test.go
  pilot/pkg/status/resource.go
  pkg/collateral/control.go
  pkg/collateral/control_test.go
  pkg/config/resource/name.go
  pkg/config/resource/name_test.go
  pkg/config/resource/serialization.go
  pkg/ctrlz/topics/collection.go
  pkg/structured/structured.go
  pkg/test/util/yml/cache.go
  pkg/test/util/yml/cache_test.go
  pkg/util/strcase/camelcase.go
  pkg/util/strcase/camelcase_test.go
  security/pkg/k8s/chiron/utils.go
  security/pkg/k8s/chiron/utils_test.go
  tools/bug-report/pkg/util/path/path.go
  tools/docker-builder/builder/crane.go
  tools/docker-builder/builder/tar.go
  tools/istio-iptables/pkg/capture/format.go
Labels: size/XXL, release-notes-none

#52638 ensure there is always jitter in cert renwals
  releasenotes/notes/grace-ratio-jitter.yaml
  security/pkg/nodeagent/cache/secretcache.go
Labels: area/security, area/perf and scalability, ok-to-test, size/XS

#52655 fix compatibility version for stat regex
  manifests/charts/base/files/profile-compatibility-version-1.21.yaml
  manifests/charts/base/files/profile-compatibility-version-1.22.yaml
  manifests/charts/default/files/profile-compatibility-version-1.21.yaml
  manifests/charts/default/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.22.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.22.yaml
  manifests/helm-profiles/compatibility-version-1.21.yaml
  manifests/helm-profiles/compatibility-version-1.22.yaml
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#52657 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52613 Fix custom sidecar injection in an OpenShift deployment
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-openshift-custom-injection.yaml
  pkg/kube/inject/testdata/inject/hello-openshift-custom-injection.yaml.injected
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.values.gen.yaml
  pkg/kube/inject/webhook.go
Labels: size/L, release-notes-none

#52658 Add support for proxy (based on env vars) to echo
  pkg/test/echo/server/forwarder/util.go
Labels: size/XS, release-notes-none

#52650 fuzz: fix build
  tests/fuzz/oss_fuzz_build.sh
Labels: area/test and release, size/S, release-notes-none

#52660 Move presubmit to k8s 1.31
  prow/integ-suite-kind.sh
Labels: size/XS, release-notes-none

#52567 testing: create dependency deny/allow list
  Makefile.core.mk
  tests/binary/dependencies_test.go
Labels: size/L, release-notes-none

#52597 honour destination rule TLS settings for mesh external
  manifests/charts/base/files/profile-compatibility-version-1.21.yaml
  manifests/charts/base/files/profile-compatibility-version-1.22.yaml
  manifests/charts/base/files/profile-compatibility-version-1.23.yaml
  manifests/charts/default/files/profile-compatibility-version-1.21.yaml
  manifests/charts/default/files/profile-compatibility-version-1.22.yaml
  manifests/charts/default/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.23.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.22.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.23.yaml
  manifests/helm-profiles/compatibility-version-1.21.yaml
  manifests/helm-profiles/compatibility-version-1.22.yaml
  manifests/helm-profiles/compatibility-version-1.23.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/networking/core/cluster_tls_test.go
  pkg/istio-agent/agent_test.go
  releasenotes/notes/52597.yaml
Labels: size/M, release-notes-none

#52599 Remove code paths for VERIFY_CERTIFICATE_AT_CLIENT
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/networking/core/cluster_tls_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
Labels: area/networking, size/L, release-notes-none

#52662 ipautoallocator: do not watch SE if they do not exist
  pilot/pkg/controllers/ipallocate/ipallocate.go
  pilot/pkg/controllers/ipallocate/ipallocate_test.go
Labels: size/S, release-notes-none

#52654 add support for deferred stats creation
  manifests/charts/base/files/profile-compatibility-version-1.21.yaml
  manifests/charts/base/files/profile-compatibility-version-1.22.yaml
  manifests/charts/base/files/profile-compatibility-version-1.23.yaml
  manifests/charts/default/files/profile-compatibility-version-1.21.yaml
  manifests/charts/default/files/profile-compatibility-version-1.22.yaml
  manifests/charts/default/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.23.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.22.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.23.yaml
  manifests/helm-profiles/compatibility-version-1.21.yaml
  manifests/helm-profiles/compatibility-version-1.22.yaml
  manifests/helm-profiles/compatibility-version-1.23.yaml
  pilot/pkg/features/experimental.go
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
  pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  releasenotes/notes/deferred_stats_creation.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L

#52669 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52513 fix: istio-cni uses hostPort only when ambient enabled
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: ok-to-test, size/XS, release-notes-none, area/ambient

#52612 respect DNS capture for proxy with auto-assigned addresses
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/serviceregistry/serviceentry/store_test.go
  releasenotes/notes/52612.yaml
  tests/integration/ambient/main_test.go
Labels: area/networking, size/L, area/ambient, cherrypick/release-1.23

#52672 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52666 [cherry-pick][release-1.23] Fix istiod helm chart for remote
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: area/environments, size/XS, feature/Multi-cluster, release-notes-none

#52679 revert change to stop manual allocation of se address
  tests/integration/ambient/main_test.go
Labels: size/XS, release-notes-none, area/ambient

#52681 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52684 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52687 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52686 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#52680 adding ds support for autoallocated IP in getAllAddressesForProxy
  pilot/pkg/model/service.go
  tests/integration/ambient/main_test.go
Labels: area/networking, size/S, release-notes-none, area/ambient

#52711 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52685 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#52712 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#52661 Update Go dependencies to 1.31
  cni/pkg/nodeagent/server_test.go
  go.mod
  go.sum
  istioctl/pkg/multicluster/remote_secret_test.go
  istioctl/pkg/tag/tag_test.go
  licenses/github.com/antlr/antlr4/runtime/Go/antlr/v4/LICENSE
  licenses/github.com/antlr4-go/antlr/v4/LICENSE
  licenses/github.com/fxamacker/cbor/v2/LICENSE
  licenses/github.com/x448/float16/LICENSE
  licenses/gopkg.in/evanphx/json-patch.v4/LICENSE
  pilot/pkg/leaderelection/leaderelection_test.go
  pkg/kube/client.go
  pkg/kube/controllers/queue.go
  pkg/kube/kclient/clienttest/direct.go
  pkg/test/framework/components/echo/kube/pod_controller.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/webhookpatch.go
  security/pkg/k8s/chiron/utils_test.go
  security/pkg/pki/ca/ca_test.go
  security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
  tests/binary/binaries_test.go
  tests/binary/dependencies_test.go
Labels: size/L, release-notes-none

#52721 Fix lint issues
  operator/pkg/install/wait.go
Labels: size/XS, release-notes-none

#52624 Autodetect vendor-specific CNI incompatibilities during install
  istioctl/pkg/validate/validate.go
  operator/pkg/apis/validation/validation.go
  operator/pkg/apis/validation/validation_test.go
  operator/pkg/render/manifest.go
Labels: size/M, release-notes-none

#52720 Workaround calico issue in integration test
  tests/integration/ambient/baseline_test.go
Labels: size/XS, release-notes-none

#52717 installer: fix missing labels on uninstall
  operator/cmd/mesh/uninstall.go
Labels: size/S, release-notes-none

#52723 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none
