Repository istio/istio, pull requests merged in 2024-12, with the labels that each got.

#54113 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#54114 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54117 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54121 [release-1.22] [fix]: do not h2upgrade when useClientProtocol is set in DR
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
Labels: size/S, release-notes-none

#54123 [release-1.24] [fix]: do not h2upgrade when useClientProtocol is set in DR
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
Labels: size/S, release-notes-none

#54122 [release-1.23] [fix]: do not h2upgrade when useClientProtocol is set in DR
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
Labels: size/S, release-notes-none

#54133 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54135 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54089 install: fix PDB overrides
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/pkg/render/postprocess.go
  releasenotes/notes/pdb-resolve.yaml
Labels: size/M, cherrypick/release-1.24

#54138 [release-1.24] install: fix PDB overrides
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/pkg/render/postprocess.go
  releasenotes/notes/pdb-resolve.yaml
Labels: size/M, release-notes-none

#54112 fix: fix k3s cniBinDir to static path
  manifests/charts/base/files/profile-platform-k3s.yaml
  manifests/charts/default/files/profile-platform-k3s.yaml
  manifests/charts/gateway/files/profile-platform-k3s.yaml
  manifests/charts/gateways/istio-egress/files/profile-platform-k3s.yaml
  manifests/charts/gateways/istio-ingress/files/profile-platform-k3s.yaml
  manifests/charts/istio-cni/files/profile-platform-k3s.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-platform-k3s.yaml
  manifests/charts/ztunnel/files/profile-platform-k3s.yaml
  manifests/helm-profiles/platform-k3s.yaml
Labels: area/environments, ok-to-test, size/XS, release-notes-none

#54071 Fix: Cross-namespace RequestAuthentication
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/xds/waypoint_test.go
  releasenotes/notes/54071.yaml
Labels: size/L, area/ambient, cherrypick/release-1.24

#54143 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54076 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54136 leader election: default revision properly
  pilot/pkg/leaderelection/leaderelection.go
Labels: size/XS, release-notes-none

#54153 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54154 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54155 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53834 [release-1.23] Fix merging duration influence dst duration
  pilot/pkg/networking/core/cluster_builder.go
  pkg/proto/merge/merge.go
  pkg/proto/merge/merge_test.go
  releasenotes/notes/53801.yaml
Labels: size/M

#54141 Use platform profile for GKE as well, and drop the K8S version detect
  manifests/charts/base/files/profile-platform-gke.yaml
  manifests/charts/default/files/profile-platform-gke.yaml
  manifests/charts/gateway/files/profile-platform-gke.yaml
  manifests/charts/gateways/istio-egress/files/profile-platform-gke.yaml
  manifests/charts/gateways/istio-ingress/files/profile-platform-gke.yaml
  manifests/charts/istio-cni/files/profile-platform-gke.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-platform-gke.yaml
  manifests/charts/ztunnel/files/profile-platform-gke.yaml
  manifests/helm-profiles/platform-gke.yaml
  releasenotes/notes/54141.yaml
Labels: size/M, area/ambient

#54162 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54164 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#54158 Fix TestNetworkUpdateTriggers flake
  pilot/pkg/serviceregistry/kube/controller/network_test.go
Labels: size/S, release-notes-none

#54167 Update install script to link guides for ambient
  release/downloadIstioCandidate.sh
Labels: size/S, release-notes-none

#54175 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54178 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#54176 Update validations to check for incompatible Calico CNI fields
  operator/pkg/apis/validation/validation.go
  operator/pkg/apis/validation/validation_test.go
Labels: area/environments, ok-to-test, area/user experience, size/L, release-notes-none

#54179 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54181 NewDelayedInformer allows using clients from Register
  pkg/config/schema/kubeclient/common.go
  pkg/config/schema/kubeclient/common_test.go
  pkg/config/schema/metadata.yaml
  pkg/kube/kclient/client.go
Labels: size/S, release-notes-none

#53994 krt: move event processing to queue
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/meshconfig.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pkg/kube/kclient/client.go
  pkg/kube/kclient/delayed.go
  pkg/kube/kclient/interfaces.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/collection_test.go
  pkg/kube/krt/conformance_test.go
  pkg/kube/krt/core.go
  pkg/kube/krt/fetch.go
  pkg/kube/krt/index_test.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/informer_test.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join_test.go
  pkg/kube/krt/processor.go
  pkg/kube/krt/recomputetrigger_test.go
  pkg/kube/krt/singleton_test.go
  pkg/kube/krt/static.go
  pkg/kube/krt/static_test.go
  pkg/kube/krt/sync.go
  pkg/kube/krt/testing.go
  pkg/queue/instance.go
Labels: size/XXL, release-notes-none

#54185 [release-1.23] fix(helm): render service account properly when adding annotations (#…
  manifests/charts/istio-control/istio-discovery/templates/serviceaccount.yaml
  manifests/charts/istiod-remote/templates/serviceaccount.yaml
  releasenotes/notes/53989.yaml
Labels: size/S

#54190 tiny typo in multiple controlplane integration tests
  tests/integration/pilot/multiplecontrolplanes/main_test.go
Labels: kind/docs, size/XS, release-notes-none

#54180 ambient CNI agent upgrade handling
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/server.go
  cni/pkg/nodeagent/server_test.go
  manifests/charts/istio-cni/templates/clusterrole.yaml
  releasenotes/notes/54180.yaml
  tests/integration/ambient/cniupgrade/main_test.go
Labels: area/environments, size/XL, area/ambient

#54192 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54183 [release-1.24] fix(helm): render service account properly when adding annotations
  manifests/charts/istio-control/istio-discovery/templates/serviceaccount.yaml
  releasenotes/notes/53989.yaml
Labels: size/S, release-notes-none

#54195 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54197 make NewDelayedInformer call registered type codepath and add tests
  pkg/kube/kclient/client.go
  pkg/kube/kclient/client_test.go
Labels: size/M, release-notes-none

#54198 Automator: update common-files@release-1.22 in istio/istio@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54200 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54199 Automator: update istio/client-go@release-1.22 dependency in istio/istio@release-1.22
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54092 Add DAC_OVERRIDE to istio-cni-node
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/53829-2.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.24

#54182 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54206 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54177 Automator: update common-files@release-1.24 in istio/istio@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54211 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#54214 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54212 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54215 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54222 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54210 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54221 Remove some duplicated test fns, and explicitly wait for DS pods to ready up
  tests/integration/ambient/cni/main_test.go
  tests/integration/ambient/cniupgrade/main_test.go
  tests/integration/ambient/util.go
  tests/integration/pilot/cni_race_test.go
Labels: area/test and release, size/L, release-notes-none, area/ambient

#54224 use upstream_cluster_raw for json access log
  pilot/pkg/model/telemetry_logging.go
Labels: size/XS, release-notes-none

#54228 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54226 [release-1.22] use upstream_cluster_raw for json access log
  pilot/pkg/model/telemetry_logging.go
Labels: size/XS, release-notes-none

#54223 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54229 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54230 addons: Bump addons version
  manifests/addons/gen.sh
  samples/addons/kiali.yaml
  samples/addons/loki.yaml
Labels: size/L, release-notes-none

#54233 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54231 Revert "[release-1.22] use upstream_cluster_raw for json access log"
  pilot/pkg/model/telemetry_logging.go
Labels: size/XS, release-notes-none

#54236 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#54213 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54241 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54225 [release-1.23] use upstream_cluster_raw for json access log
  pilot/pkg/model/telemetry_logging.go
Labels: size/XS, release-notes-none

#54227 [release-1.24] use upstream_cluster_raw for json access log
  pilot/pkg/model/telemetry_logging.go
Labels: size/XS, release-notes-none

#54242 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54247 [integ tests] ensure *all* pods are healthy before continuing CNI test
  tests/integration/ambient/cniupgrade/main_test.go
Labels: size/XS, release-notes-none

#54249 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54193 Monitoring: fix early gauge recording
  pilot/pkg/bootstrap/monitoring.go
  pilot/pkg/bootstrap/server.go
Labels: size/S, release-notes-none, cherrypick/release-1.24

#54252 [release-1.23] Monitoring: fix early gauge recording
  pilot/pkg/bootstrap/monitoring.go
  pilot/pkg/bootstrap/server.go
Labels: size/S, release-notes-none

#54254 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54074 krt: introduce a reverse index for dependencies, dramatically reducing CPU usage
  pkg/kube/krt/collection.go
  pkg/kube/krt/fetch.go
  pkg/kube/krt/filter.go
  pkg/kube/krt/index.go
  pkg/kube/krt/internal.go
Labels: size/L, release-notes-none

#54258 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54259 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54260 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54251 [release-1.24] Monitoring: fix early gauge recording
  pilot/pkg/bootstrap/monitoring.go
  pilot/pkg/bootstrap/server.go
Labels: size/S, release-notes-none

#54201 Support grpc probes for workload group health checks
  pkg/istio-agent/health/health_check.go
  pkg/istio-agent/health/health_probers.go
  pkg/istio-agent/health/health_probers_test.go
Labels: area/networking, area/user experience, size/L, release-notes-none

#54264 `profile` and `platform` should mirror each other in terms of scoping
  manifests/charts/base/templates/zzz_profile.yaml
  manifests/charts/default/templates/zzz_profile.yaml
  manifests/charts/gateway/templates/zzz_profile.yaml
  manifests/charts/gateways/istio-egress/templates/zzz_profile.yaml
  manifests/charts/gateways/istio-ingress/templates/zzz_profile.yaml
  manifests/charts/istio-cni/templates/zzz_profile.yaml
  manifests/charts/istio-control/istio-discovery/templates/zzz_profile.yaml
  manifests/charts/ztunnel/templates/zzz_profile.yaml
  manifests/zzz_profile.yaml
  releasenotes/notes/54264.yaml
Labels: area/environments, size/L

#54203 cni: propogate log context further
  cni/pkg/iptables/iptables.go
  cni/pkg/iptables/iptables_e2e_test.go
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/server.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
  tools/istio-iptables/pkg/dependencies/implementation_unspecified.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: size/L, release-notes-none

#54250 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54262 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54207 Fix NACKS when service addresses partially overlap
  pilot/pkg/networking/core/serviceentry_simulation_test.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller_test.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/test/xdstest/extract.go
  pilot/test/xdstest/validate.go
  pkg/dns/server/name_table.go
  pkg/dns/server/name_table_test.go
  releasenotes/notes/fix-overlapping-se.yaml
  tests/integration/pilot/common/routing.go
Labels: size/L, cherrypick/release-1.24

#54217 Prep for iptables idempotency by making ipset ops (safely) idempotent by doubling-down on comments
  cni/pkg/ipset/ipset.go
  cni/pkg/ipset/nldeps_linux.go
  cni/pkg/ipset/nldeps_mock.go
  cni/pkg/nodeagent/server.go
  cni/pkg/nodeagent/server_test.go
Labels: size/L, release-notes-none, area/ambient

#54218 Handle ignoring plugin events in the informer more intelligently
  cni/pkg/nodeagent/cni-watcher.go
  cni/pkg/nodeagent/cni-watcher_test.go
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/nodeagent/server.go
  cni/pkg/util/podutil.go
  pkg/kube/util.go
Labels: size/L, release-notes-none, area/ambient

#54287 ambient: fix case of incorrect equals leading to excessive load
  pilot/pkg/model/service.go
Labels: size/XS, release-notes-none, cherrypick/release-1.24

#54291 [release-1.24] ambient: fix DNS resolution of ExternalName services with DNS proxy
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
  releasenotes/notes/externalname-ambient.yaml
Labels: size/M, release-notes-none

#54294 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54276 Gateway: better handling of invalid protocols
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml
  pilot/pkg/features/experimental.go
Labels: size/L, release-notes-none

#54292 fix istioctl proxyconfig performance issue
  istioctl/pkg/proxyconfig/proxyconfig.go
  releasenotes/notes/54292.yaml
Labels: area/user experience, size/S, release-notes-none

#54173 add comments to endpoint slice and remove additional loop
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: size/M, release-notes-none

#54283 enable configuration of global.proxy.outlierLogPath for waypoints
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.44.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.52.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.51.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/reroute-virtual-interfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
Labels: ok-to-test, size/XS, release-notes-none, area/ambient

#54286 Add tcp port to peer authn test
  tests/integration/ambient/baseline_test.go
Labels: size/XS, release-notes-none

#54293 remove 1.23 version checks
  pilot/pkg/model/context.go
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_internal_test.go
  pilot/pkg/networking/util/util.go
Labels: size/M, release-notes-none

#54202 Always wait for `iptables-legacy` lock, even if using sandboxing. Also, rename var.
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/options.go
  cni/pkg/nodeagent/server.go
  tools/istio-iptables/pkg/capture/run_test.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
Labels: area/networking, size/M, release-notes-none, area/ambient

#54290 [release-1.24] ambient: fix case of incorrect equals leading to excessive load
  pilot/pkg/model/service.go
Labels: size/XS, release-notes-none

#54299 fix tagwatcher with revisions
  pkg/kube/kclient/index.go
  pkg/revisions/tag_watcher.go
  pkg/revisions/tag_watcher_test.go
  releasenotes/notes/54280.yaml
Labels: size/S, area/upgrade, cherrypick/release-1.23, cherrypick/release-1.24

#54298 [ambient] Fix some unit test flakes for ambient informer
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/util/podutil.go
Labels: area/test and release, size/M, release-notes-none, area/ambient

#54305 [release-1.24] fix tagwatcher with revisions
  pkg/kube/kclient/index.go
  pkg/revisions/tag_watcher.go
  pkg/revisions/tag_watcher_test.go
  releasenotes/notes/54280.yaml
Labels: size/S, release-notes-none

#54313 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54314 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54304 [release-1.23] fix tagwatcher with revisions
  pkg/kube/kclient/index.go
  pkg/revisions/tag_watcher.go
  pkg/revisions/tag_watcher_test.go
  releasenotes/notes/54280.yaml
Labels: size/S, release-notes-none

#54296 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#54315 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54317 Automator: update common-files@release-1.24 in istio/istio@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54318 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54319 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54320 Event counts stil not exact for this test
  cni/pkg/nodeagent/informers_test.go
Labels: area/test and release, size/M, release-notes-none, area/ambient

#54321 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54324 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54325 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54327 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#54328 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54330 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54170 Fix patching deployment when upgrade to istio 1.24
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/istio-upgrade-to-1.24.yaml
  releasenotes/notes/54145.yaml
Labels: size/L

#54312 fix: clear tmp files from previous run if exist before copy cni binaries again
  cni/pkg/install/binaries.go
  cni/pkg/install/binaries_test.go
  releasenotes/notes/54311.yaml
Labels: area/environments, ok-to-test, size/M, release-notes-none

#54337 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54333 fix mixed case host with tls redirect
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/gateway_test.go
  releasenotes/notes/49638.yaml
Labels: size/S

#54343 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54347 Still some racy tests - there are more initial update events to wait on
  cni/pkg/nodeagent/informers_test.go
Labels: area/test and release, size/S, release-notes-none, area/ambient

#54342 update dependencies
  go.mod
  go.sum
  licenses/github.com/BurntSushi/toml/internal/toml-test/COPYING
  licenses/github.com/golang/groupcache/LICENSE
  licenses/github.com/imdario/mergo/LICENSE
  licenses/go.opentelemetry.io/auto/sdk/LICENSE
  licenses/go.starlark.net/LICENSE
  licenses/k8s.io/kube-openapi/pkg/internal/third_party/govalidator/LICENSE
  tests/binary/binaries_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: area/test and release, size/XL, release-notes-none

#54345 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54348 Adapt telemetry api "registry-redirector" tests to Openshift
  tests/integration/telemetry/api/customize_metrics_test.go
  tests/integration/telemetry/api/registry_setup_test.go
  tests/integration/telemetry/api/setup_test.go
Labels: area/extensions and telemetry, ok-to-test, size/M, release-notes-none

#54349 use k8s 1.32.0 as base to run tests against
  prow/integ-suite-kind.sh
Labels: area/test and release, size/XS, release-notes-none

#54341 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54346 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#54350 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#54352 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54366 debug: align ConfigDump behavior with Envoy Admin API
  pilot/pkg/xds/debug.go
Labels: area/test and release, ok-to-test, size/XS, release-notes-none

#54284 ambient: add extension points into proto API
  pkg/workloadapi/workload.pb.go
  pkg/workloadapi/workload.proto
  pkg/workloadapi/workload_json.gen.go
Labels: size/S, release-notes-none

#54353 Fix patching deployment when upgrade to istio 1.24 (#54170)
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/istio-upgrade-to-1.24.yaml
  releasenotes/notes/54145.yaml
Labels: size/L

#54232 fix empty imagePullSecret for service scope wasmplugin in ambient
  pilot/pkg/model/authentication.go
  pilot/pkg/model/authentication_test.go
  pilot/pkg/model/authorization.go
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/extensions.go
  pilot/pkg/model/policyattachment.go
  pilot/pkg/model/policyattachment_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/networkfilter.go
  pkg/slices/slices.go
  tests/integration/ambient/wasm_test.go
Labels: area/extensions and telemetry, size/L, release-notes-none, area/ambient

#54322 Skip test/try to diagnose test flakes
  pkg/test/framework/components/istio/cleanup.go
  pkg/test/framework/components/istio/installer.go
  tests/integration/ambient/cni/main_test.go
  tests/integration/ambient/util.go
Labels: size/S, release-notes-none

#54368 [release-1.24] clarify status wording for authz policy for ztunnel with L7 rules
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  releasenotes/notes/54334.yaml
Labels: size/S, release-notes-none

#54369 Partial backport: krt: move event processing to queue (#53994)
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/meshconfig.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/kube/kclient/client.go
  pkg/kube/kclient/delayed.go
  pkg/kube/kclient/interfaces.go
  pkg/kube/krt/collection_test.go
  pkg/kube/krt/index_test.go
  pkg/kube/krt/informer_test.go
  pkg/kube/krt/join_test.go
  pkg/kube/krt/recomputetrigger_test.go
  pkg/kube/krt/singleton_test.go
  pkg/kube/krt/sync.go
Labels: size/L, release-notes-none

#54370 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#54371 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54373 Update BASE_VERSION to 1.24-2024-12-17T19-00-41
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#54375 Update BASE_VERSION to 1.23-2024-12-17T19-01-56
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#54372 Update BASE_VERSION to 1.22-2024-12-17T19-01-34
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#54358 Commit to monitor event implicit sync and use it for all tests
  cni/pkg/nodeagent/informers_test.go
Labels: area/test and release, size/L, release-notes-none, area/ambient

#54374 Update BASE_VERSION to master-2024-12-17T19-00-43
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#54378 Automator: update ztunnel@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54384 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54379 ambient: avoid slow lookup for network
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
Labels: size/M, release-notes-none

#54385 fix mirror percentage calculation in gateway apis
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  releasenotes/notes/54357.yaml
Labels: size/S

#54388 [release-1.23] validation: future proof unknown versions
  pkg/config/schema/collection/schemas.go
  pkg/webhooks/validation/server/server.go
  releasenotes/notes/futureproof-version.yaml
Labels: size/S, release-notes-none

#54387 minor optimization in gateways
  pilot/pkg/networking/core/gateway.go
Labels: size/XS, release-notes-none

#54351 krt: remove dead code that doesn't work right
  pilot/pkg/controllers/untaint/nodeuntainter.go
  pkg/kube/krt/helpers.go
  pkg/kube/krt/internal.go
Labels: size/M, release-notes-none

#54395 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54380 xds: do not attempt to push resources to Ztunnel
  pilot/pkg/xds/cds.go
  pilot/pkg/xds/ecds.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/lds.go
  pilot/pkg/xds/nds.go
  pilot/pkg/xds/rds.go
Labels: size/M, release-notes-none

#54397 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none
