Repository istio/istio, pull requests merged in 2024-06, with the labels that each got.

#51341 [release-1.22] Fix bug with initial snapshot create
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/pod_cache.go
  cni/pkg/nodeagent/server.go
  cni/pkg/util/podutil.go
Labels: size/L, release-notes-none

#51323 [release-1.22] Change pod repair getPodNetNs logic to not rely on /32 route in host ns.
  cni/pkg/repair/netns.go
Labels: size/M, release-notes-none

#51345 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51344 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51346 Update BASE_VERSION to 1.20-2024-06-01T19-02-45
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#51350 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#51351 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51357 Update BASE_VERSION to 1.21-2024-06-02T19-03-50
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#51358 Update BASE_VERSION to master-2024-06-02T19-03-25
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#51234 manifests: add `gateways.securityContext` option to custom gateway securityContext
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/files/gateway-injection-template.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/securitycontext-condition.yaml
Labels: area/environments, size/M, release-notes-none

#51339 Bump API and client-go deps
  common/config/.golangci.yml
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/M, release-notes-none

#51364 Fix race
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
Labels: size/M, release-notes-none

#51372 Attempt to fix fuzzing build
  tests/fuzz/oss_fuzz_build.sh
Labels: size/XS, release-notes-none

#51379 `istio-cni` - fix a TODO around removal
  cni/pkg/nodeagent/informers.go
Labels: size/S, release-notes-none, area/ambient

#51373 add the id to the svg element in productpage
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-psa.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/productpage/templates/productpage.html
Labels: area/test and release, size/M, release-notes-none

#51286 Wasm integration tests for Ambient Mode
  tests/integration/ambient/main_test.go
  tests/integration/ambient/registry_setup_test.go
  tests/integration/ambient/testdata/gateway-api.yaml
  tests/integration/ambient/testdata/registry-secret.yaml
  tests/integration/ambient/testdata/wasm-filter.yaml
  tests/integration/ambient/wasm_test.go
Labels: size/L, release-notes-none

#51366 [release-1.20] manifests: add gateways.securityContext option to custom gateway securityContext
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/files/gateway-injection-template.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/securitycontext-condition.yaml
Labels: area/environments, size/M, release-notes-none

#51381 Certificate chain trim spaces
  releasenotes/notes/trim-certificate-chain.yaml
  security/pkg/pki/testdata/cert-chain-trailing-line.pem
  security/pkg/pki/util/crypto.go
  security/pkg/pki/util/crypto_test.go
Labels: size/L, cherrypick/release-1.22

#51371 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51378 istioctl: add overwrite flag for enroll-namespace
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/add-overwrite-flag.yaml
Labels: area/user experience, size/M, area/ambient

#51335 Add initial Ztunnel Grafana dashboard
  manifests/addons/dashboards/README.md
  manifests/addons/dashboards/jsonnetfile.json
  manifests/addons/dashboards/jsonnetfile.lock.json
  manifests/addons/dashboards/lib/g.libsonnet
  manifests/addons/dashboards/lib/lib-grid.libsonnet
  manifests/addons/dashboards/lib/output.json
  manifests/addons/dashboards/lib/panels.libsonnet
  manifests/addons/dashboards/lib/queries.libsonnet
  manifests/addons/dashboards/lib/variables.libsonnet
  manifests/addons/dashboards/ztunnel-dashboard.gen.json
  manifests/addons/dashboards/ztunnel.libsonnet
  manifests/addons/gen.sh
  operator/cmd/mesh/manifest-generate_test.go
  prow/release-commit.sh
  samples/addons/grafana.yaml
Labels: size/XXL, release-notes-none

#51393 update deps for 1.21.3
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/XS, release-notes-none

#51349 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#51401 Add ENABLE_ENHANCED_RESOURCE_SCOPING to compatibility profiles
  manifests/charts/base/files/profile-compatibility-version-1.20.yaml
  manifests/charts/base/files/profile-compatibility-version-1.21.yaml
  manifests/charts/default/files/profile-compatibility-version-1.20.yaml
  manifests/charts/default/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.20.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.20.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.20.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-operator/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istio-operator/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.21.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.20.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  manifests/helm-profiles/compatibility-version-1.20.yaml
  manifests/helm-profiles/compatibility-version-1.21.yaml
  releasenotes/notes/51399.yaml
Labels: area/environments, area/user experience, size/S

#51367 [release-1.21] manifests: add gateways.securityContext option to custom gateway securityContext
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/files/gateway-injection-template.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/securitycontext-condition.yaml
Labels: area/environments, size/M, release-notes-none

#51316 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#51404 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#51402 [release-1.22] Add ENABLE_ENHANCED_RESOURCE_SCOPING to compatibility profiles
  manifests/charts/base/files/profile-compatibility-version-1.20.yaml
  manifests/charts/base/files/profile-compatibility-version-1.21.yaml
  manifests/charts/default/files/profile-compatibility-version-1.20.yaml
  manifests/charts/default/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.20.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.20.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.20.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istio-operator/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istio-operator/files/profile-compatibility-version-1.21.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.20.yaml
  manifests/charts/istiod-remote/files/profile-compatibility-version-1.21.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.20.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  manifests/helm-profiles/compatibility-version-1.20.yaml
  manifests/helm-profiles/compatibility-version-1.21.yaml
  releasenotes/notes/51399.yaml
Labels: size/S, release-notes-none

#51405 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#51411 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51412 remove unused dual option in agent
  pilot/cmd/pilot-agent/options/agent.go
  pkg/envoy/proxy.go
  pkg/istio-agent/agent.go
Labels: size/S, release-notes-none

#51415 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51419 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#51423 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51422 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#51424 optimize: sidecar service selection and merge
  pilot/pkg/model/sidecar.go
Labels: area/perf and scalability, size/S, release-notes-none

#51426 Add XDS address to ztunnel
  manifests/charts/ztunnel/templates/daemonset.yaml
  manifests/charts/ztunnel/values.yaml
Labels: size/S, release-notes-none

#51353 Fix:Service Account Annotation Formatting Error
  manifests/charts/istio-control/istio-discovery/templates/serviceaccount.yaml
  manifests/charts/istiod-remote/templates/serviceaccount.yaml
  releasenotes/notes/51289.yaml
Labels: area/environments, ok-to-test, size/S

#51416 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51421 Optimize ParseGatewayRDSRouteName
  pilot/pkg/model/gateway.go
  pilot/pkg/model/gateway_test.go
Labels: size/M, release-notes-none

#51417 Automator: update ztunnel@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51352 iptables - fix redirection for UDP calls
  cni/pkg/plugin/testdata/include-exclude-ip.txt.golden
  releasenotes/notes/51377.yaml
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/testdata/ip-range.golden
  tools/istio-iptables/pkg/capture/testdata/ipnets-with-kube-virt-interfaces.golden
  tools/istio-iptables/pkg/capture/testdata/ipnets.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-ipnets.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-uid-gid.golden
  tools/istio-iptables/pkg/capture/testdata/loopback-outbound-iprange.golden
  tools/istio-iptables/pkg/capture/testdata/tproxy.golden
Labels: size/S

#51429 Ambient CNI informer: K8S job pods must be handled uniquely
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/net_test.go
  pkg/kube/util.go
  releasenotes/notes/51429.yaml
Labels: area/networking, size/L, area/ambient

#51435 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51418 istioctl: promote `istioctl x waypoint`
  istioctl/cmd/root.go
  istioctl/pkg/waypoint/waypoint.go
  pkg/test/framework/components/ambient/waypoint.go
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/waypoint_test.go
Labels: size/M, release-notes-none

#51439 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51440 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51441 istio-cni: cosmetic + comment fixups (no logical changes)
  cni/pkg/nodeagent/informers.go
Labels: size/S, release-notes-none, area/ambient

#51380 istioctl: remove --verbose flag since it should be the default column output anyway
  istioctl/pkg/writer/ztunnel/configdump/configdump.go
  istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
  istioctl/pkg/writer/ztunnel/configdump/workload.go
  istioctl/pkg/ztunnelconfig/ztunnelconfig.go
Labels: area/user experience, size/S, release-notes-none, area/ambient

#50878 ambient: fix nil pointer when pod cache is stale
  cni/pkg/nodeagent/cni-watcher.go
  cni/pkg/nodeagent/cni-watcher_test.go
  cni/pkg/nodeagent/informers.go
Labels: size/L, release-notes-none, cherrypick/release-1.22

#51442 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#51036 Test framework: remove "Static VM" concept
  pkg/test/framework/components/ambient/waypoint.go
  pkg/test/framework/components/cluster/cluster.go
  pkg/test/framework/components/cluster/clusterboot/factory.go
  pkg/test/framework/components/cluster/clusterboot/factory_test.go
  pkg/test/framework/components/cluster/clusters.go
  pkg/test/framework/components/cluster/config.go
  pkg/test/framework/components/cluster/factory.go
  pkg/test/framework/components/cluster/fake.go
  pkg/test/framework/components/cluster/kube/factory.go
  pkg/test/framework/components/cluster/staticvm/staticvm.go
  pkg/test/framework/components/cluster/staticvm/staticvm_test.go
  pkg/test/framework/components/cluster/topology.go
  pkg/test/framework/components/echo/cmd/echogen/README.md
  pkg/test/framework/components/echo/cmd/echogen/echogen.go
  pkg/test/framework/components/echo/cmd/echogen/echogen_test.go
  pkg/test/framework/components/echo/cmd/echogen/testdata/config.yaml
  pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
  pkg/test/framework/components/echo/deployment/builder.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/factory.go
  pkg/test/framework/components/echo/kube/builder.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/match/matchers_test.go
  pkg/test/framework/components/echo/staticvm/instance.go
  pkg/test/framework/components/echo/staticvm/workload.go
  pkg/test/framework/components/environment/kube/fake.go
  pkg/test/framework/components/environment/kube/kube.go
  pkg/test/framework/components/environment/kube/settings.go
  pkg/test/framework/components/istio/cleanup.go
  pkg/test/framework/components/istio/configmap.go
  pkg/test/framework/components/istio/kube.go
  pkg/test/framework/components/namespace/kube.go
  pkg/test/framework/components/prometheus/kube.go
  pkg/test/framework/config.go
  pkg/test/framework/suite.go
  pkg/test/framework/suite_test.go
  pkg/test/framework/test.go
  pkg/test/kube/dump.go
  tests/integration/ambient/main_test.go
  tests/integration/ambient/waypoint_test.go
  tests/integration/pilot/gateway_test.go
  tests/integration/pilot/ingress_test.go
Labels: size/XXL, release-notes-none

#51443 [release-1.22] ambient: fix nil pointer when pod cache is stale
  cni/pkg/nodeagent/cni-watcher.go
  cni/pkg/nodeagent/cni-watcher_test.go
  cni/pkg/nodeagent/informers.go
Labels: size/L, release-notes-none

#51432 [release-1.22] optimize: sidecar service selection and merge
  pilot/pkg/model/sidecar.go
Labels: size/S, release-notes-none

#51436 [release-1.22] Workaround weird cluster versions
  pkg/kube/version.go
  pkg/kube/version_test.go
Labels: size/M, release-notes-none

#51444 istioctl: add missing field into ztunnel configdump
  istioctl/pkg/writer/ztunnel/configdump/api.go
Labels: size/S, release-notes-none

#51448 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50662 doc: update the doc of the --log_rotate_max_age
  pkg/log/options.go
Labels: kind/docs, ok-to-test, size/XS, release-notes-none

#51449 dependabot: add release-notes-none label
  .github/dependabot.yml
Labels: size/XS, release-notes-none

#51410 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#51280 update supported groups for TLS
  pkg/config/security/security.go
Labels: area/security, ok-to-test, size/XS, release-notes-none

#51450 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51451 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51453 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51454 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51457 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51461 Fix null value in gateway chart values that leads to user values being overridden
  manifests/charts/gateway/values.yaml
Labels: area/environments, ok-to-test, size/XS, release-notes-none, cherrypick/release-1.21, cherrypick/release-1.22

#51356 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51452 Minor improvement to sds init logging
  security/pkg/nodeagent/sds/server.go
Labels: area/networking, area/user experience, size/XS, release-notes-none

#51476 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51477 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51481 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51465 ambient: cleanup sidecar tests
  tests/integration/ambient/cnirepair/main_test.go
  tests/integration/ambient/main_test.go
Labels: size/M, release-notes-none

#51485 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51484 cleanup unused flags
  pilot/pkg/features/telemetry.go
Labels: size/XS, release-notes-none

#51473 krt: add informer dump
  pkg/kube/krt/informer.go
Labels: size/XS, release-notes-none

#51487 [release-1.21] Minor improvement to sds init logging
  security/pkg/nodeagent/sds/server.go
Labels: size/XS, release-notes-none

#51488 [release-1.22] Minor improvement to sds init logging
  security/pkg/nodeagent/sds/server.go
Labels: size/XS, release-notes-none

#51428 Make bookinfo not really slow
  samples/bookinfo/src/details/details.rb
  samples/bookinfo/src/productpage/Dockerfile
  samples/bookinfo/src/productpage/productpage.py
  samples/bookinfo/src/productpage/requirements.in
  samples/bookinfo/src/productpage/requirements.txt
Labels: size/L, release-notes-none

#51483 remove ENABLE_OTEL_BUILTIN_RESOURCE_LABELS
  pilot/pkg/features/telemetry.go
  pilot/pkg/model/telemetry_logging.go
  releasenotes/notes/otel-builtin-labels.yaml
Labels: size/S

#51474 ambient tests: add all CRDs for unit tests
  pilot/test/xds/fake.go
Labels: size/XS, release-notes-none

#51446 Improve ambient e2e coverage
  pkg/kube/namespace/filter.go
  releasenotes/notes/ns-filter.yaml
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/main_test.go
  tests/integration/iop-ambient-test-defaults.yaml
Labels: size/L, release-notes-none

#51499 [release-1.22] Fix null value in gateway chart values that leads to user values being overridden
  manifests/charts/gateway/values.yaml
Labels: size/XS, release-notes-none

#51500 [release-1.21] Fix null value in gateway chart values that leads to user values being overridden
  manifests/charts/gateway/values.yaml
Labels: size/XS, release-notes-none

#51497 [release-1.22] Fix discovery selectors and GC bug
  pilot/pkg/config/kube/crdclient/client.go
  pkg/kube/kclient/client_test.go
  pkg/kube/namespace/filter.go
  releasenotes/notes/ns-filter.yaml
Labels: size/M, release-notes-none

#51495 ztunnel: log backtraces for debugging
  manifests/charts/ztunnel/templates/daemonset.yaml
Labels: size/XS, release-notes-none

#51493 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51504 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51492 Add consistent table order in iptables-restore input and expand builder test coverage
  tools/istio-iptables/pkg/builder/iptables_builder_impl.go
  tools/istio-iptables/pkg/builder/iptables_builder_test.go
  tools/istio-iptables/pkg/builder/testdata/append-insert-multi-restore.golden
  tools/istio-iptables/pkg/builder/testdata/append-insert-multi.golden
  tools/istio-iptables/pkg/builder/testdata/append-multi-restore.golden
  tools/istio-iptables/pkg/builder/testdata/append-multi.golden
  tools/istio-iptables/pkg/builder/testdata/append-single-restore.golden
  tools/istio-iptables/pkg/builder/testdata/append-single.golden
  tools/istio-iptables/pkg/builder/testdata/insert-multi-restore.golden
  tools/istio-iptables/pkg/builder/testdata/insert-multi.golden
  tools/istio-iptables/pkg/builder/testdata/insert-single-restore.golden
  tools/istio-iptables/pkg/builder/testdata/insert-single.golden
  tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v4-restore.golden
  tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v4.golden
  tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v6-restore.golden
  tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v6.golden
Labels: area/test and release, size/XL, release-notes-none

#51511 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51512 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51506 Enable remote readiness checks over https
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/bootstrap/webhook.go
  releasenotes/notes/51506.yaml
Labels: area/networking, area/security, ok-to-test, size/M

#51516 cni: fix running profile
  pkg/ctrlz/ctrlz.go
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#51520 [release-1.22] cni: fix running profile
  pkg/ctrlz/ctrlz.go
Labels: size/XS, release-notes-none

#51521 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#51524 Automator: update common-files@release-1.21 in istio/istio@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#51526 Automator: update common-files@release-1.22 in istio/istio@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#51530 Ambient: fix two broken tests
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/main_test.go
Labels: size/S, release-notes-none

#51529 Automator: update istio/client-go@release-1.22 dependency in istio/istio@release-1.22
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#51531 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51532 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51528 Automator: update istio/client-go@release-1.21 dependency in istio/istio@release-1.21
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#51486 OpenTelemetry access log support formatter
  go.mod
  go.sum
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  releasenotes/notes/otel-accesslog-formatter.yaml
Labels: size/L

#51523 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#51408 Automator: update common-files@release-1.20 in istio/istio@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#51343 validation: improve header validation
  pkg/config/validation/validation.go
  pkg/config/validation/virtualservice.go
Labels: size/S, release-notes-none

#51527 validation: avoid double validation of labels
  pkg/config/validation/validation.go
Labels: size/XS, release-notes-none

#51533 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51538 envoyfilter build error log add flag
  pilot/pkg/model/envoyfilter.go
Labels: area/networking, size/XS, release-notes-none

#51540 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#51543 Automator: update ztunnel@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51542 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#51544 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51546 cni: fix k/v pairs in UDS logging from plugin
  cni/pkg/log/uds.go
  cni/pkg/log/uds_test.go
Labels: size/L, release-notes-none, cherrypick/release-1.22

#51547 Fix plugin debug logging
  cni/cmd/istio-cni/main.go
  cni/pkg/cmd/root.go
  cni/pkg/plugin/plugin.go
Labels: size/S, release-notes-none

#51510 Allow setting bind mode at Gateway level instead of just class level
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
Labels: size/S, release-notes-none

#51550 ambient: deprecate hbone_single_tls_port field
  pkg/workloadapi/workload.pb.go
  pkg/workloadapi/workload.proto
Labels: size/XS, release-notes-none

#51552 Update ztunnel dashboard with real ID
  prow/release-commit.sh
Labels: size/XS, release-notes-none

#51553 samples: bump addon versions
  manifests/addons/gen.sh
  samples/addons/extras/zipkin.yaml
  samples/addons/grafana.yaml
  samples/addons/jaeger.yaml
  samples/addons/kiali.yaml
  samples/addons/loki.yaml
  samples/addons/prometheus.yaml
Labels: size/L, release-notes-none

#51549 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51554 dashboards: migrate pilot dashboard over to modern jsonnet dashboard-as-code
  manifests/addons/dashboards/lib/dashboard.libsonnet
  manifests/addons/dashboards/lib/panels.libsonnet
  manifests/addons/dashboards/lib/queries.libsonnet
  manifests/addons/dashboards/lib/variables.libsonnet
  manifests/addons/dashboards/pilot-dashboard.gen.json
  manifests/addons/dashboards/pilot-dashboard.json
  manifests/addons/dashboards/pilot.libsonnet
  manifests/addons/dashboards/ztunnel-dashboard.gen.json
  manifests/addons/dashboards/ztunnel.libsonnet
  manifests/addons/gen.sh
  manifests/addons/values-grafana.yaml
  samples/addons/grafana.yaml
  tests/integration/telemetry/api/dashboard_test.go
Labels: size/XXL, release-notes-none

#51503 pilot: collapse to single inbound passthrough
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/listener_builder_test.go
  pilot/pkg/networking/core/listener_inbound.go
  pilot/pkg/networking/core/listener_test.go
  pilot/pkg/networking/core/listenertest/match.go
  pilot/pkg/networking/core/peer_authentication_simulation_test.go
  pilot/pkg/networking/core/sidecar_simulation_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/simulation/traffic.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/deltatest.go
Labels: size/L, release-notes-none

#51561 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51563 Remove duplicate resolve host name in destination rule
  pilot/pkg/model/destination_rule.go
Labels: size/XS, release-notes-none

#51498 Remove dead and confusing code, chiron rejects empty signers
  pilot/pkg/bootstrap/certcontroller.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/features/pilot.go
  pkg/config/constants/constants.go
  pkg/security/security.go
Labels: size/L, release-notes-none

#51571 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50540 add "app.kubernetes.io/name" to gateway.podlabels
  manifests/charts/gateway/templates/_helpers.tpl
  manifests/charts/gateway/templates/deployment.yaml
Labels: area/environments, ok-to-test, size/M, release-notes-none

#51580 fix type assertion panic for controllers.Object
  pilot/pkg/config/kube/crdclient/client.go
  pkg/revisions/tag_watcher.go
Labels: ok-to-test, size/S, release-notes-none

#51535 disable sorting of JSON logging by default due to float serialization in envoy
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  pilot/pkg/model/telemetry_test.go
  pilot/pkg/networking/core/accesslog_test.go
  releasenotes/notes/48882.yaml
Labels: ok-to-test, size/S

#51566 minor performance improvements
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/gateway.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/xds/delta.go
Labels: size/S, release-notes-none

#51577 ambient: filter cross-namespace authz policies (#51557)
  istioctl/pkg/writer/ztunnel/configdump/api.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  releasenotes/notes/ambient-ns-policy.yaml
Labels: size/L, release-notes-none

#51568 Fix false positives for IST0128 and IST0129
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/destinationrule/ca-certificates.go
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname-selector.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname-selector.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname.yaml
  releasenotes/notes/51568.yaml
Labels: area/user experience, size/L

#51585 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51584 [release-1.22] Fix false positives for IST0128 and IST0129
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/destinationrule/ca-certificates.go
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname-selector.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname-selector.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname.yaml
  releasenotes/notes/51568.yaml
Labels: size/L, release-notes-none

#51583 [release-1.21] Fix false positives for IST0128 and IST0129
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/destinationrule/ca-certificates.go
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname-selector.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname-selector.yaml
  pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname.yaml
  releasenotes/notes/51568.yaml
Labels: size/L, release-notes-none

#51589 webhooks: move to v1
  manifests/charts/base/templates/default.yaml
  manifests/charts/default/templates/mutatingwebhook.yaml
  manifests/charts/default/templates/validatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/templates/revision-tags.yaml
  manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  manifests/charts/istiod-remote/templates/default.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  manifests/charts/istiod-remote/templates/validatingwebhookconfiguration.yaml
  operator/cmd/mesh/manifest-generate_test.go
  samples/ambient-argo/tag-chart/templates/mutatingwebhooks.yaml
  samples/ambient-argo/tag-chart/templates/validatingwebhook.yaml
Labels: size/S, release-notes-none

#51594 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51598 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#51599 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51587 logging: drop excessive warning
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/XS, release-notes-none

#51602 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51596 Use Helm global.externalIstiod for pilot env variable
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  releasenotes/notes/51595.yaml
Labels: area/environments, area/networking, size/S

#51559 istioctl: add subcommand for retrieving waypoint status
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/51559.yaml
Labels: area/user experience, size/L, area/ambient

#51605 Bump Kiali to 1.86
  manifests/addons/gen.sh
  samples/addons/kiali.yaml
Labels: size/M, release-notes-none

#51555 [release-1.22] cni: fix k/v pairs in UDS logging from plugin
  cni/pkg/log/uds.go
  cni/pkg/log/uds_test.go
Labels: size/L, release-notes-none

#51590 Do not import v1beta1 API just for a label
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: size/XS, release-notes-none

#51621 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51574 Add test to ensure `istio-cni` disruption does not impact established ambient pod dataplane
  tests/integration/ambient/cni/main_test.go
Labels: area/test and release, size/L, release-notes-none, area/ambient

#51617 echo server: bind to multiple pod IPs
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/kube/templates/deployment.yaml
Labels: size/M, release-notes-none

#51618 Bump Kiali to 1.86
  manifests/addons/gen.sh
  samples/addons/kiali.yaml
Labels: size/L, release-notes-none
