Repository istio/istio, pull requests merged in 2024-05, with the labels that each got.

#50711 Fix service entry merge
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/xds/cds_test.go
  releasenotes/notes/se-conflict.yaml
Labels: size/L, release-notes-none, cherrypick/release-1.20, cherrypick/release-1.21, cherrypick/release-1.22

#50773 [release-1.22] Fix service entry merge
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/xds/cds_test.go
  releasenotes/notes/se-conflict.yaml
Labels: size/L, release-notes-none

#50770 [release-1.22] fix jwt-claim-route flake
  tests/integration/pilot/common/routing.go
Labels: size/M, release-notes-none

#50788 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50728 support for disabling metrics endpoint from outside of pod
  pilot/cmd/pilot-agent/status/server.go
  pilot/pkg/bootstrap/monitoring.go
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/features/telemetry.go
  pkg/util/net/ip.go
  pkg/util/net/ip_test.go
  releasenotes/notes/50728.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L

#50761 Optimize service sorting
  pilot/pkg/model/push_context.go
  pkg/slices/slices.go
  pkg/slices/slices_test.go
Labels: area/networking, size/M, release-notes-none

#50763 fix inappropriate func name
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
Labels: area/networking, size/XS, release-notes-none

#50771 Update gateway-api version for conformance
  go.mod
  go.sum
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/M, release-notes-none, cherrypick/release-1.22

#50789 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50791 Add --for to waypoint generate to allow preview of yaml
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/50791.yaml
Labels: area/user experience, size/S, area/ambient, cherrypick/release-1.22

#50794 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50798 clean up remaining references to use-waypoint being an annotation
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
Labels: size/XS, release-notes-none, area/ambient

#50796 Add a couple of missing labels in CNI helm charts
  manifests/charts/istio-cni/templates/clusterrolebinding.yaml
Labels: size/XS, release-notes-none

#50800 helm tests: Simplify the implementation of `NamespaceConfig`
  tests/integration/helm/util.go
Labels: size/M, release-notes-none

#50778 [release-1.22] fix ambient telemetry test
  istio.deps
  tests/integration/ambient/baseline_test.go
Labels: size/XS, release-notes-none

#50802 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50797 [release-1.22] Add --for to waypoint generate to allow preview of yaml
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/50791.yaml
Labels: size/S, release-notes-none

#50810 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50803 [release-1.21] Fix gateway deployment on OpenShift
  manifests/charts/base/files/profile-openshift.yaml
  manifests/charts/default/files/profile-openshift.yaml
  manifests/charts/gateway/README.md
  manifests/charts/gateway/files/profile-openshift.yaml
  manifests/charts/gateway/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/files/profile-openshift.yaml
  manifests/charts/gateways/istio-ingress/files/profile-openshift.yaml
  manifests/charts/istio-cni/files/profile-openshift.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-openshift.yaml
  manifests/charts/istio-operator/files/profile-openshift.yaml
  manifests/charts/istiod-remote/files/profile-openshift.yaml
  manifests/charts/ztunnel/files/profile-openshift.yaml
  manifests/helm-profiles/openshift.yaml
Labels: size/M, release-notes-none

#50812 [release-1.22] support for disabling metrics endpoint from outside of pod
  pilot/cmd/pilot-agent/status/server.go
  pilot/pkg/bootstrap/monitoring.go
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/features/telemetry.go
  pkg/util/net/ip.go
  pkg/util/net/ip_test.go
  releasenotes/notes/50728.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L, release-notes-none

#50815 [release-1.22] bump deps
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: size/S, release-notes-none

#50696 Generalize default webhook message
  operator/cmd/mesh/install.go
  tests/integration/operator/install_test.go
Labels: area/environments, area/user experience, size/XS, release-notes-none

#50818 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50819 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#50820 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50821 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50822 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50776 [release-1.20] Fix service entry merge
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/xds/cds_test.go
  releasenotes/notes/se-conflict.yaml
Labels: size/L

#50795 [release-1.22] Update gateway-api version for conformance
  go.mod
  go.sum
  operator/pkg/controller/istiocontrolplane/errdict.go
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/L, release-notes-none

#50824 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50777 [release-1.21] Fix service entry merge
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pilot/pkg/xds/cds_test.go
  releasenotes/notes/se-conflict.yaml
Labels: size/L

#50799 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50826 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50827 helm upgrade tests: Upgrade from latest patch release
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: size/M, release-notes-none

#50653 Push some local test cleanups
  cni/pkg/nodeagent/cni-watcher_test.go
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/plugin/plugin_test.go
  cni/pkg/util/podutil.go
  cni/pkg/util/podutil_test.go
  istioctl/pkg/injector/injector-list_test.go
  istioctl/pkg/util/ambient/util.go
  istioctl/pkg/waypoint/waypoint.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pkg/config/analysis/analyzers/injection/injection.go
  pkg/config/analysis/analyzers/maturity/maturity.go
  pkg/config/analysis/analyzers/util/in_mesh.go
  pkg/config/constants/constants.go
  pkg/test/framework/components/ambient/waypoint.go
  pkg/test/framework/components/echo/annotations.go
  pkg/test/framework/components/echo/common/deployment/echos.go
  pkg/test/framework/components/echo/common/deployment/external.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/deployment/builder.go
  pkg/test/framework/components/echo/echotest/filters_test.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/deployment_test.go
  pkg/test/framework/components/echo/kube/templates/deployment.yaml
  pkg/test/framework/components/echo/kube/templates/service.yaml
  pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
  pkg/test/framework/components/echo/match/matchers.go
  pkg/test/framework/components/echo/match/matchers_test.go
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/cnirepair/main_test.go
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/ambient/main_test.go
  tests/integration/ambient/waypoint_test.go
  tests/integration/pilot/grpc_probe_test.go
  tests/integration/pilot/headers_test.go
  tests/integration/pilot/proxyconfig/proxyconfig_test.go
  tests/integration/pilot/tcp_probe_test.go
  tests/integration/security/ca_custom_root/main_test.go
  tests/integration/security/file_mounted_certs/main_test.go
  tests/integration/security/filebased_tls_origination/main_test.go
  tests/integration/security/mtls_healthcheck_test.go
  tests/integration/security/reachability_test.go
  tests/integration/security/util/framework.go
  tests/integration/telemetry/api/setup_test.go
  tests/integration/telemetry/policy/helper_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/vm/main_test.go
Labels: area/test and release, size/XL, release-notes-none

#50825 [release-1.22] Ambient: individual pods can enroll using label `istio.io/dataplane-mode=ambient`
  cni/pkg/util/podutil.go
  cni/pkg/util/podutil_test.go
  releasenotes/notes/50355.yaml
Labels: size/L, release-notes-none

#50817 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50830 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50832 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50835 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50838 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50843 jwt: fix list audience claim matching
  pilot/pkg/security/authz/builder/testdata/http/extended-allow-full-rule-out.yaml
  pilot/pkg/security/authz/model/generator.go
  releasenotes/notes/jwt-aud.yaml
Labels: size/M, cherrypick/release-1.21, cherrypick/release-1.22

#50847 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50804 Use label istio.io/dataplane-mode=disabled for pod-level ambient opt-out
  cni/README.md
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/plugin/plugin_test.go
  cni/pkg/util/podutil.go
  cni/pkg/util/podutil_test.go
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/ztunnel/templates/daemonset.yaml
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/custom-class.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect-infra.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/proxy-config-crd.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
  pkg/config/constants/constants.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.44.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  pkg/test/framework/components/echo/common/deployment/echos.go
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
  releasenotes/notes/50804.yaml
  tests/integration/ambient/cnirepair/main_test.go
  tests/integration/ambient/main_test.go
  tests/integration/ambient/waypoint_test.go
Labels: area/user experience, size/L, area/ambient, cherrypick/release-1.22

#50844 [release-1.21] jwt: fix list audience claim matching
  pilot/pkg/security/authz/builder/testdata/http/extended-allow-full-rule-out.yaml
  pilot/pkg/security/authz/model/generator.go
  releasenotes/notes/jwt-aud.yaml
Labels: size/M, release-notes-none

#50846 [release-1.22] jwt: fix list audience claim matching
  pilot/pkg/security/authz/builder/testdata/http/extended-allow-full-rule-out.yaml
  pilot/pkg/security/authz/model/generator.go
  releasenotes/notes/jwt-aud.yaml
Labels: size/M, release-notes-none

#50853 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50854 Fix ztunnel deployment on OpenShift
  manifests/charts/base/files/profile-openshift-ambient.yaml
  manifests/charts/default/files/profile-openshift-ambient.yaml
  manifests/charts/gateway/files/profile-openshift-ambient.yaml
  manifests/charts/gateways/istio-egress/files/profile-openshift-ambient.yaml
  manifests/charts/gateways/istio-ingress/files/profile-openshift-ambient.yaml
  manifests/charts/istio-cni/files/profile-openshift-ambient.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-openshift-ambient.yaml
  manifests/charts/istio-operator/files/profile-openshift-ambient.yaml
  manifests/charts/istiod-remote/files/profile-openshift-ambient.yaml
  manifests/charts/ztunnel/files/profile-openshift-ambient.yaml
  manifests/charts/ztunnel/templates/rbac.yaml
  manifests/helm-profiles/openshift-ambient.yaml
Labels: size/M, release-notes-none

#50839 Fix CNI installation in namespaces other than kube-system in OpenShift
  manifests/charts/istio-cni/templates/clusterrole.yaml
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#50855 [release-1.22] Fix CNI installation in namespaces other than kube-system in OpenShift
  manifests/charts/istio-cni/templates/clusterrole.yaml
Labels: size/XS, release-notes-none

#50852 webhooks: clean up noisy misleading logs
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/validation/server/server.go
Labels: size/XS, release-notes-none

#50857 [release-1.22] Fix ztunnel deployment on OpenShift
  manifests/charts/base/files/profile-openshift-ambient.yaml
  manifests/charts/default/files/profile-openshift-ambient.yaml
  manifests/charts/gateway/files/profile-openshift-ambient.yaml
  manifests/charts/gateways/istio-egress/files/profile-openshift-ambient.yaml
  manifests/charts/gateways/istio-ingress/files/profile-openshift-ambient.yaml
  manifests/charts/istio-cni/files/profile-openshift-ambient.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-openshift-ambient.yaml
  manifests/charts/istio-operator/files/profile-openshift-ambient.yaml
  manifests/charts/istiod-remote/files/profile-openshift-ambient.yaml
  manifests/charts/ztunnel/files/profile-openshift-ambient.yaml
  manifests/charts/ztunnel/templates/rbac.yaml
  manifests/helm-profiles/openshift-ambient.yaml
Labels: size/M, release-notes-none

#50833 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50858 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50859 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50845 turn off default allow waypoint by default
  pilot/pkg/features/ambient.go
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none, cherrypick/release-1.22

#50862 [release-1.22] turn off default allow waypoint by default
  pilot/pkg/features/ambient.go
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none

#50863 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#50755 istioctl: make analyze params in result message stable
  pkg/config/analysis/analyzers/deployment/services.go
  pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  pkg/config/analysis/analyzers/injection/injection-image.go
  pkg/config/analysis/analyzers/sidecar/selector.go
  pkg/config/analysis/analyzers/sidecar/util.go
  pkg/config/analysis/analyzers/telemetry/selector.go
  pkg/config/analysis/analyzers/telemetry/util.go
  pkg/config/analysis/analyzers/virtualservice/conflictingmeshgatewayhosts.go
  pkg/config/analysis/analyzers/webhook/webhook.go
Labels: area/user experience, size/M, release-notes-none

#50864 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50861 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50377 remove misleading constants
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_tls_test.go
  pilot/pkg/networking/core/cluster_traffic_policy_test.go
  pkg/config/constants/constants.go
Labels: size/M, release-notes-none

#50782 add support for proxying 100 continue headers
  pilot/pkg/features/experimental.go
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/gateway_test.go
  pilot/pkg/networking/core/listener.go
  pilot/pkg/networking/core/listener_builder.go
  pilot/pkg/networking/core/listener_inbound.go
  releasenotes/notes/36278.yaml
Labels: size/S

#50874 [release-1.21] Fix CNI installation in namespaces other than kube-system in OpenShift
  manifests/charts/istio-cni/templates/clusterrole.yaml
Labels: size/XS, release-notes-none

#50877 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50880 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50884 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50883 [release-1.22] bump proxy and ambient test
  istio.deps
  tests/integration/ambient/baseline_test.go
Labels: size/XS, release-notes-none

#50882 bump proxy and ambient test
  istio.deps
  tests/integration/ambient/baseline_test.go
Labels: size/XS, release-notes-none

#50840 fix port merge of kubernetes services in sidecar
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  releasenotes/notes/sidecar-port-merge.yaml
Labels: size/L, cherrypick/release-1.22

#50887 [release-1.22] fix port merge of kubernetes services in sidecar
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  releasenotes/notes/sidecar-port-merge.yaml
Labels: size/L, release-notes-none

#50888 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50866 Update integration README by adding a missing command-line flag and fixing typos
  tests/integration/README.md
Labels: kind/docs, ok-to-test, size/M, release-notes-none

#50889 stop default for istio.io/waypoint-for in istioctl
  istioctl/pkg/waypoint/waypoint.go
Labels: area/user experience, size/S, release-notes-none, area/ambient

#50890 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50891 Add some more useful logging around iptables selection in ambient CNI
  cni/pkg/iptables/iptables.go
  tools/istio-iptables/pkg/dependencies/implementation.go
Labels: area/networking, size/S, release-notes-none, area/ambient

#50897 Update BASE_VERSION to master-2024-05-07T22-48-43
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#50898 Update iptables image SHA
  cni/deployments/kubernetes/Dockerfile.install-cni
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: area/test and release, ok-to-test, size/XS, release-notes-none, cherrypick/release-1.20, cherrypick/release-1.21, cherrypick/release-1.22

#50899 Automator: update ztunnel@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50842 change #none to none for use-waypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  releasenotes/notes/49700.yaml
Labels: size/S, Ambient Beta, cherrypick/release-1.22

#50902 [release-1.22] Update iptables image SHA
  cni/deployments/kubernetes/Dockerfile.install-cni
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/XS, release-notes-none

#50905 [release-1.20] Update iptables image SHA
  cni/deployments/kubernetes/Dockerfile.install-cni
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/S, release-notes-none

#50901 [release-1.21] Update iptables image SHA
  cni/deployments/kubernetes/Dockerfile.install-cni
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/XS, release-notes-none

#50896 discovery fake: allow kube-client override
  pilot/test/xds/fake.go
Labels: size/S, release-notes-none

#50904 [release-1.22] change #none to none for use-waypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  releasenotes/notes/49700.yaml
Labels: size/S, release-notes-none

#50906 fix release-notes kind
  releasenotes/notes/no-1p-jwt.yaml
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#50909 [release-1.22] fix release-notes kind
  releasenotes/notes/no-1p-jwt.yaml
Labels: size/XS, release-notes-none

#50910 cleanup rename p to wle
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
Labels: size/M, release-notes-none

#50916 Fix ambient cni on OpenShift
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/plugin_test.go
Labels: size/S, release-notes-none, cherrypick/release-1.21, cherrypick/release-1.22

#50926 docker: use `ubuntu:noble`
  docker/Dockerfile.base
  docker/Dockerfile.distroless
  releasenotes/notes/noble-base.yaml
Labels: size/S, release-notes-none

#50920 [release-1.22] Fix ambient cni on OpenShift
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/plugin_test.go
Labels: size/S, release-notes-none

#50519 ambient: implement service.trafficDistribution field in Service
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
Labels: size/S, release-notes-none

#50922 validation of waypoint name for istioctl
  istioctl/pkg/waypoint/waypoint.go
Labels: size/XS, release-notes-none, area/ambient

#50831 Pick up gateway rc2
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/isolation.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/isolation.yaml
  pilot/pkg/config/kube/gateway/testdata/isolation.yaml.golden
  pkg/config/validation/validation.go
  pkg/config/validation/virtualservice.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/XL, release-notes-none, cherrypick/release-1.22

#50918 krt: optimize FilterKey
  pkg/kube/krt/fetch.go
Labels: size/M, release-notes-none, cherrypick/release-1.22

#50929 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#50930 Update BASE_VERSION to master-2024-05-08T18-51-53
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#50928 exp: add more logs
  tests/integration/pilot/common/routing.go
Labels: size/XS, release-notes-none

#50932 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50936 VM tests: bump base images
  pkg/test/echo/docker/Dockerfile.app_sidecar_base
  pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8
  tools/docker.yaml
Labels: size/S, release-notes-none

#50938 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#50935 [release-1.22] krt: optimize FilterKey
  pkg/kube/krt/fetch.go
Labels: size/M, release-notes-none

#50903 Add Authz test for JWT aud claim
  tests/common/jwt/jwt_token.go
  tests/integration/security/authz_test.go
  tests/integration/security/testdata/authz/jwt.yaml.tmpl
Labels: area/security, size/M, release-notes-none

#50931 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50939 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50934 [release-1.22] Pick up gateway rc2
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/isolation.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/isolation.yaml
  pilot/pkg/config/kube/gateway/testdata/isolation.yaml.golden
  pkg/config/validation/validation.go
  pkg/config/validation/virtualservice.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/XL, release-notes-none

#50925 distroless: move to apko/wolfi images
  bin/update_deps.sh
  cni/deployments/kubernetes/Dockerfile.install-cni
  docker/Dockerfile.distroless
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
  releasenotes/notes/apko-distroless.yaml
Labels: size/M

#50945 gateway: 1.1.0
  go.mod
  go.sum
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.22

#50948 [release-1.22] gateway: 1.1.0
  go.mod
  go.sum
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/S, release-notes-none

#50951 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50895 bootstrap: interpolate HOST_IP like we do for native traces
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: size/S, release-notes-none

#50921 performance: optimize metrics in kube controller
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/S, release-notes-none

#50927 Update VM base images
  Makefile.core.mk
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
  prow/lib.sh
  tools/docker.yaml
Labels: size/M, release-notes-none

#50933 add support for istio.io/waypoint-for on gatewayClasses
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  releasenotes/notes/50933.yaml
Labels: size/M, area/ambient

#50667 tests: drop hardcoded kube-system CNI
  pkg/test/framework/components/istio/kube.go
  tests/integration/pilot/cni_race_test.go
  tests/integration/pilot/multiplecontrolplanes/main_test.go
Labels: size/S, release-notes-none

#50757 xds: push CDS on AUTO_PASSTHROUGH Gateway change
  pilot/pkg/model/context.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/gateway_test.go
  pilot/pkg/xds/cds.go
  releasenotes/notes/push-cds-on-auto-passthrough-gateway-change.yaml
Labels: area/networking, size/L

#50959 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50961 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50957 Add an openshift flag to integration tests
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  tests/integration/README.md
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: size/M, release-notes-none

#50960 [release-1.22] bootstrap: interpolate HOST_IP like we do for native traces
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: size/S, release-notes-none

#50963 xds: avoid computation when not needed for CDS
  pilot/pkg/xds/cds.go
Labels: size/S, release-notes-none

#50970 [release-1.22] bump deps
  istio.deps
Labels: size/XS, release-notes-none

#50962 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50964 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50974 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50973 Add a test to ensure we can handle alt client-go versions
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: size/S, release-notes-none

#50975 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50976 fix TestBinarySizes
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
  tests/binary/binaries_test.go
Labels: size/S, release-notes-none

#50987 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50781 add outlier log path configuration in mesh proxy config
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pkg/envoy/proxy.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.values.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.values.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.44.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.44.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.values.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml
  releasenotes/notes/56781.yaml
Labels: ok-to-test, area/user experience, size/M

#50924 krt: various micro-optimizations
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/core.go
  pkg/kube/krt/fetch.go
  pkg/kube/krt/filter.go
  pkg/kube/krt/helpers.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/singleton.go
  pkg/kube/krt/static.go
  pkg/kube/krt/testing.go
  pkg/slices/slices.go
  pkg/slices/slices_test.go
  pkg/util/smallset/smallset.go
  pkg/util/smallset/smallset_test.go
Labels: size/XL, release-notes-none

#50452 cors: do not forwarded preflight request if the origin is not allowed
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_internal_test.go
  releasenotes/notes/50452.yaml
Labels: size/M

#50994 Automator: update istio/client-go@release-1.22 dependency in istio/istio@release-1.22
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#50989 sds: remove Google CA clients
  go.mod
  go.sum
  licenses/cloud.google.com/go/iam/LICENSE
  licenses/cloud.google.com/go/security/LICENSE
  licenses/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/LICENSE
  pkg/istio-agent/agent.go
  pkg/istio-agent/plugins.go
  security/pkg/nodeagent/caclient/providers/google-cas/client.go
  security/pkg/nodeagent/caclient/providers/google-cas/client_test.go
  security/pkg/nodeagent/caclient/providers/google-cas/mock/ca_mock.go
  security/pkg/nodeagent/caclient/providers/google/client.go
  security/pkg/nodeagent/caclient/providers/google/client_test.go
  security/pkg/nodeagent/caclient/providers/google/mock/ca_mock.go
  security/proto/providers/google/meshca.pb.go
  security/proto/providers/google/meshca.proto
  security/proto/providers/google/meshca_grpc.pb.go
Labels: size/XXL, release-notes-none

#50999 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#51000 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#50995 Fix warning
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  pkg/config/validation/validation.go
Labels: size/XS, release-notes-none

#51006 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50915 iptables: use `ISTIO_OUTPUT` chain for DNS UDP rules
  cni/pkg/plugin/testdata/dns.txt.golden
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/testdata/dns-uid-gid.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/dns.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/empty.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/inbound-interception-mode.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups-exclude.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups.golden
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/testdata/dns-uid-gid.golden
  tools/istio-iptables/pkg/capture/testdata/ip-range.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups-exclude.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-dns-uid-gid.golden
  tools/istio-iptables/pkg/capture/testdata/loopback-outbound-iprange.golden
  tools/istio-iptables/pkg/capture/testdata/tproxy.golden
Labels: area/networking, ok-to-test, size/L, release-notes-none, area/dual-stack

#51007 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50969 test: fix CNI Version Skew test
  tests/integration/pilot/cni/cniversionskew_test.go
Labels: size/XS, release-notes-none

#51011 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50828 sds: simplify implementation to reduce dependencies
  Makefile.core.mk
  pilot/pkg/model/context.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/sds_test.go
  pilot/pkg/xds/xdsgen.go
  pkg/xds/server.go
  security/pkg/nodeagent/sds/sdsservice.go
  security/pkg/nodeagent/sds/server.go
  tests/binary/binaries_test.go
  tests/integration/pilot/piggyback_test.go
Labels: size/L, release-notes-none

#51013 Fix usage of infrastructure labels/annotations on gateway
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/infrastructure-labels-annotations.yaml
Labels: size/L, release-notes-none, cherrypick/release-1.22

#50993 remove stackdriver e2e tests
  istio.deps
  tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/common.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
  tests/integration/telemetry/stackdriver/testdata/accesslogpolicy.yaml
  tests/integration/telemetry/stackdriver/testdata/client_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/client_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/custom_bootstrap.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_audit/server_audit_all_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_audit/server_audit_bar_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_audit/server_audit_foo_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_audit/v1beta1-audit-authorization-policy.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/policy_allow.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/policy_deny.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_allow_no_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_allow_with_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_deny_no_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/server_access_log_deny_with_policy.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_allow_matched.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_both_matched.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_deny_matched.yaml.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_allow_matched.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_both_matched.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_deny_matched.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/server_tcp_connection_count.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/testdata/unsampled_server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/vm/main_test.go
  tests/integration/telemetry/stackdriver/vm/testdata/client_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/vm/testdata/server_access_log.json.tmpl
  tests/integration/telemetry/stackdriver/vm/testdata/server_request_count.json.tmpl
  tests/integration/telemetry/stackdriver/vm/testdata/trace.prototext.tmpl
  tests/integration/telemetry/stackdriver/vm/vm_test.go
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
Labels: size/XXL, release-notes-none

#51019 Fix TestCNIVersionSkew 2.0
  tests/integration/pilot/cni/cniversionskew_test.go
Labels: size/XS, release-notes-none

#50746 pilot: fix bug in endpoint updates
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/L, release-notes-none, cherrypick/release-1.21, cherrypick/release-1.22

#51017 krt: fix minor comment/noisy log
  pkg/kube/krt/index.go
Labels: size/XS, release-notes-none

#51025 [release-1.22] pilot: fix bug in endpoint updates
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
Labels: size/L, release-notes-none

#50981 [release-1.22] xds: push CDS on AUTO_PASSTHROUGH Gateway change
  pilot/pkg/model/context.go
  pilot/pkg/model/gateway.go
  pilot/pkg/model/gateway_test.go
  pilot/pkg/xds/cds.go
  releasenotes/notes/push-cds-on-auto-passthrough-gateway-change.yaml
Labels: size/L, release-notes-none
