Repository istio/istio, pull requests merged in 2024-04, with the labels that each got.

#50157 Fix high CPU consumption on pilot when in-cluster analysis is enabled
  pkg/util/concurrent/debouncer.go
  releasenotes/notes/50157.yaml
Labels: area/networking, area/user experience, size/S, cherrypick/release-1.20, cherrypick/release-1.21

#50178 [release-1.20] Fix high CPU consumption on pilot when in-cluster analysis is enabled
  pkg/util/concurrent/debouncer.go
  releasenotes/notes/50157.yaml
Labels: size/S, release-notes-none

#50171 Recognize networking v1 APIs
  pkg/config/schema/collections/collections.agent.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/test/datasets/validation/dataset/networking-v1-DestinationRule.yaml
  pkg/test/datasets/validation/dataset/networking-v1-Gateway.yaml
  pkg/test/datasets/validation/dataset/networking-v1-ServiceEntry.yaml
  pkg/test/datasets/validation/dataset/networking-v1-Sidecar.yaml
  pkg/test/datasets/validation/dataset/networking-v1-VirtualService.yaml
  pkg/test/datasets/validation/dataset/networking-v1-WorkloadEntry.yaml
  pkg/test/datasets/validation/dataset/networking-v1-WorkloadGroup.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-DestinationRule.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-Gateway.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-Sidecar.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-VirtualService.yaml
  pkg/test/datasets/validation/dataset/networking-v1beta1-WorkloadEntry.yaml
Labels: area/networking, size/L, release-notes-none

#50172 Recognize peerauthentication v1
  pkg/config/schema/collections/collections.agent.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/test/datasets/validation/dataset/security-v1-PeerAuthentication.yaml
Labels: area/security, size/S, release-notes-none

#50179 [release-1.21] Fix high CPU consumption on pilot when in-cluster analysis is enabled
  pkg/util/concurrent/debouncer.go
  releasenotes/notes/50157.yaml
Labels: size/S, release-notes-none

#50190 proxy: eliminate most xDS
  Makefile.core.mk
  pilot/cmd/pilot-agent/status/ready/probe.go
  pkg/bootstrap/option/convert.go
Labels: size/M, release-notes-none

#50194 proxy: remove unnecessary rbac and route imports
  Makefile.core.mk
  pkg/wasm/convert.go
Labels: size/S, release-notes-none

#50191 Move most gateway-api imports to v1
  pilot/pkg/config/kube/gateway/conversion.go
Labels: size/L, release-notes-none

#44123 istioctl: add a service analyzer for inconsistencies across multiple clusters
  istioctl/pkg/analyze/analyze.go
  istioctl/pkg/cli/context.go
  istioctl/pkg/precheck/precheck.go
  istioctl/pkg/tag/tag.go
  manifests/charts/istio-control/istio-discovery/templates/reader-clusterrole.yaml
  manifests/charts/istio-operator/templates/clusterrole.yaml
  manifests/charts/istiod-remote/templates/reader-clusterrole.yaml
  operator/pkg/helmreconciler/prune.go
  pkg/config/analysis/README.md
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/analyzers/analyzers_bench_test.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/multicluster/service.go
  pkg/config/analysis/analyzers/multicluster_analyzers_test.go
  pkg/config/analysis/analyzers/schema/validation_test.go
  pkg/config/analysis/analyzers/testdata/multicluster/inconsistent-service-1.yaml
  pkg/config/analysis/analyzers/testdata/multicluster/inconsistent-service-2.yaml
  pkg/config/analysis/diag/helper.go
  pkg/config/analysis/legacy/source/kube/origin.go
  pkg/config/analysis/legacy/util/kuberesource/resources.go
  pkg/config/analysis/local/context.go
  pkg/config/analysis/local/istiod_analyze.go
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  pkg/config/resource/origin.go
  pkg/kube/client.go
  pkg/test/framework/components/cluster/kube/factory.go
  pkg/test/framework/components/istio/installer.go
  pkg/test/framework/features/features.yaml
  releasenotes/notes/44123.yaml
  tests/integration/pilot/analyze_test.go
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: area/user experience, size/XL

#50199 Document additional krt exported identifiers
  pkg/kube/krt/core.go
  pkg/kube/krt/helpers.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/join.go
Labels: kind/docs, ok-to-test, size/S, release-notes-none

#50204 Move a few more gateway API resources to v1
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
Labels: size/L, release-notes-none

#50042 Fix gateway deployment on OpenShift
  manifests/charts/base/files/profile-openshift.yaml
  manifests/charts/default/files/profile-openshift.yaml
  manifests/charts/gateway/README.md
  manifests/charts/gateway/files/profile-openshift.yaml
  manifests/charts/gateway/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/files/profile-openshift.yaml
  manifests/charts/gateways/istio-ingress/files/profile-openshift.yaml
  manifests/charts/istio-cni/files/profile-openshift.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-openshift.yaml
  manifests/charts/istio-operator/files/profile-openshift.yaml
  manifests/charts/istiod-remote/files/profile-openshift.yaml
  manifests/charts/ztunnel/files/profile-openshift.yaml
  manifests/helm-profiles/openshift.yaml
Labels: size/XS, release-notes-none

#50202 Add Dynatrace sampler to OpenTelemetry Tracing Provider
  pilot/pkg/networking/core/tracing.go
  pilot/pkg/networking/core/tracing_test.go
  releasenotes/notes/dynatrace-sampler.yaml
Labels: size/L

#50206 assert all events in TestAmbientIndex_Policy to reduce flakiness
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
Labels: size/M, release-notes-none, area/ambient

#49932 Default EgressListener services should also be merged
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/sidecar_test.go
  pilot/pkg/networking/core/serviceentry_simulation_test.go
Labels: size/M, release-notes-none

#50187 Implement a CombinedAnalyzer interface
  pkg/config/analysis/analyzer.go
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/local/istiod_analyze.go
Labels: ok-to-test, size/M, release-notes-none

#50208 ztunnel: allow building custom target
  bin/build_ztunnel.sh
Labels: size/XS, release-notes-none

#50207 istioctl: move waypoints command to `v1`
  istioctl/pkg/waypoint/waypoint.go
  istioctl/pkg/waypoint/waypoint_test.go
Labels: size/M, release-notes-none

#50216 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50218 Remove external profile in the profile list
  manifests/profiles/external.yaml
  operator/cmd/mesh/profile-list_test.go
  operator/pkg/manifest/shared.go
  releasenotes/notes/50218.yaml
Labels: size/M

#50213 ambient: fix flake on waypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/sync.go
Labels: size/M, release-notes-none

#49970 Implement waypointfor annotation
  go.mod
  go.sum
  istioctl/pkg/waypoint/waypoint.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pkg/config/analysis/analyzers/maturity/maturity.go
  pkg/config/constants/constants.go
  pkg/test/framework/components/ambient/waypoint.go
  releasenotes/notes/49851.yaml
Labels: size/L, area/ambient

#50226 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50224 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#50227 Make Service a full test client in ambientTestServer and update annotateService
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
Labels: size/S, release-notes-none

#50233 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50221 Remove istio.io/for-service-account
  istioctl/pkg/waypoint/testdata/waypoint/all-gateway
  istioctl/pkg/waypoint/testdata/waypoint/combined-gateway
  istioctl/pkg/waypoint/testdata/waypoint/default-gateway
  istioctl/pkg/waypoint/waypoint.go
  istioctl/pkg/waypoint/waypoint_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pkg/config/analysis/analyzers/maturity/maturity.go
  pkg/config/analysis/analyzers/testdata/misannotated.yaml
  pkg/config/analysis/analyzers/testdata/service-port-name.yaml
  pkg/config/constants/constants.go
  pkg/test/framework/components/ambient/waypoint.go
  releasenotes/notes/50221.yaml
  samples/ambient-argo/application/details-waypoint.yaml
  samples/ambient-argo/application/reviews-waypoint.yaml
  tests/integration/ambient/bookinfo_test.go
  tests/integration/ambient/waypoint_test.go
Labels: ok-to-test, size/L, area/ambient

#50234 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50223 [release-1.21] cni: use iptables distroless variant
  cni/deployments/kubernetes/Dockerfile.install-cni
Labels: size/XS, release-notes-none

#50236 Bump grpc-go and x/net
  go.mod
  go.sum
Labels: size/S, release-notes-none

#50229 [release-1.20] Implement CombinedAnalyzer interface
  pkg/config/analysis/analyzer.go
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/local/istiod_analyze.go
Labels: ok-to-test, size/M, release-notes-none

#50241 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49916 istioctl: add default name for waypoint and remove leftover service-account code
  istioctl/pkg/waypoint/testdata/waypoint/all-gateway
  istioctl/pkg/waypoint/testdata/waypoint/combined-gateway
  istioctl/pkg/waypoint/testdata/waypoint/default-gateway
  istioctl/pkg/waypoint/waypoint.go
  istioctl/pkg/waypoint/waypoint_test.go
  pkg/config/constants/constants.go
Labels: size/M, release-notes-none, area/ambient

#50256 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50240 Enable kube.Client to create informers for registered types
  pkg/config/schema/kubeclient/common.go
  pkg/config/schema/kubeclient/common_test.go
  pkg/config/schema/kubetypes/common.go
  pkg/kube/kclient/client.go
  pkg/kube/krt/informer_test.go
Labels: ok-to-test, size/L, release-notes-none

#50239 Test the Telemetry API Access logging match feature
  pilot/pkg/model/telemetry_test.go
Labels: area/test and release, size/S, release-notes-none

#50212 proxy: slim Istio agent dependencies
  Makefile.core.mk
  istioctl/pkg/writer/compare/listener.go
  pilot/cmd/pilot-agent/options/agent.go
  pilot/pkg/xds/v3/model.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/agent_test.go
  pkg/istio-agent/tap_proxy.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
  pkg/model/wasm.go
  pkg/model/xds.go
Labels: size/L, release-notes-none

#50260 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#50263 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/M, auto-merge, release-notes-none

#50266 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50222 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50264 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50259 Backport: Bump grpc-go and x/net #50236
  go.mod
  go.sum
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pilot/pkg/util/protoconv/protoconv.go
  pkg/config/xds/filter_types.gen.go
  tests/binary/binaries_test.go
Labels: size/L, release-notes-none

#50268 [release-1.20] Bump grpc-go and x/net
  go.mod
  go.sum
Labels: size/L, release-notes-none

#50281 Automator: update istio/client-go@release-1.20 dependency in istio/istio@release-1.20
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50282 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50283 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50284 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50285 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/M, auto-merge, release-notes-none

#50280 Automator: update istio/client-go@release-1.21 dependency in istio/istio@release-1.21
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50286 Automator: update ztunnel@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50277 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50278 Automator: update common-files@release-1.21 in istio/istio@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50279 Automator: update common-files@release-1.20 in istio/istio@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50287 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50290 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50291 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50292 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#50270 ca: remove legacy-unknown signer, removed in k8s 1.22
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
  security/pkg/k8s/chiron/utils.go
Labels: size/XS, release-notes-none

#50273 [release-1.19] Bump grpc-go and x/net
  go.mod
  go.sum
  licenses/google.golang.org/appengine/LICENSE
  pilot/pkg/networking/grpcgen/grpcgen_test.go
  pkg/test/echo/server/endpoint/grpc.go
Labels: size/L, release-notes-none

#50262 Recognize Telemetry v1
  pkg/config/schema/collections/collections.agent.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/test/datasets/validation/dataset/telemetry-v1-Telemetry.yaml
Labels: size/XS, release-notes-none

#50293 Automator: update common-files@release-1.19 in istio/istio@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50294 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50154 ambient: shutdown client in test to prevent races
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
Labels: size/XS, release-notes-none

#50235 specify inbound protocol for sandwiched waypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pkg/config/constants/constants.go
  pkg/workloadapi/workload.pb.go
  pkg/workloadapi/workload.proto
Labels: size/L, release-notes-none

#50295 ambient: fix flake in new TestAmbientIndex_WaypointForWorkloadTraffic test
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
Labels: size/M, release-notes-none

#50297 bug-report: ignore expected errors on distroless
  tools/bug-report/pkg/bugreport/bugreport.go
Labels: size/S, release-notes-none

#50276 tf: allow dumping resources from container tests
  pkg/test/framework/analyzer.go
  pkg/test/framework/scope.go
  pkg/test/framework/suitecontext.go
  pkg/test/framework/test.go
  pkg/test/framework/testcontext.go
  tests/integration/ambient/traffic_test.go
Labels: size/M, release-notes-none

#50302 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50299 ambient: fix flake in TestWorkloadsForWaypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
Labels: size/XS, release-notes-none

#50300 docs: add note about custom bootstrap off-k8s
  samples/custom-bootstrap/README.md
Labels: size/XS, release-notes-none

#50303 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50304 proxy: slim pilot-agent cmd
  Makefile.core.mk
  pilot/cmd/pilot-agent/app/cmd.go
  pilot/cmd/pilot-agent/app/cmd_test.go
  pilot/cmd/pilot-agent/main.go
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/agent_proxy.go
  pilot/cmd/pilot-agent/options/statusserver.go
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  pkg/envoy/proxy_test.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/agent_test.go
  pkg/model/proxy.go
Labels: size/L, release-notes-none

#50305 Automator: update ztunnel@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50296 injection: use values default as base
  pkg/kube/inject/inject.go
Labels: size/XS, release-notes-none

#50309 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50310 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#50257 ambient: enable locality LB for waypoint
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pkg/ptr/pointer.go
  pkg/workloadapi/workload.pb.go
  pkg/workloadapi/workload.proto
Labels: size/L, release-notes-none

#50311 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50275 ambient: use distroless for cni as well
  manifests/charts/base/files/profile-ambient.yaml
  manifests/charts/default/files/profile-ambient.yaml
  manifests/charts/gateway/files/profile-ambient.yaml
  manifests/charts/gateways/istio-egress/files/profile-ambient.yaml
  manifests/charts/gateways/istio-ingress/files/profile-ambient.yaml
  manifests/charts/istio-cni/files/profile-ambient.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-ambient.yaml
  manifests/charts/istio-operator/files/profile-ambient.yaml
  manifests/charts/istiod-remote/files/profile-ambient.yaml
  manifests/charts/ztunnel/files/profile-ambient.yaml
  manifests/helm-profiles/ambient.yaml
  tests/integration/base.yaml
Labels: size/XS, release-notes-none

#50317 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50269 Bump go.mod deps
  go.mod
  go.sum
  licenses/cel.dev/expr/LICENSE
  licenses/cel.dev/expr/proto/test/v1/LICENSE
  licenses/github.com/alecthomas/participle/v2/COPYING
  licenses/github.com/go-jose/go-jose/v4/LICENSE
  licenses/github.com/go-jose/go-jose/v4/json/LICENSE
  pilot/cmd/pilot-agent/status/server_test.go
  security/pkg/server/ca/authenticate/xfcc_authenticator.go
  security/pkg/server/ca/authenticate/xfcc_authenticator_test.go
Labels: size/XL, release-notes-none

#50318 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#50307 use SpawnUpstreamSpan instead of startChildSpan
  pilot/pkg/networking/core/listener_builder.go
  pilot/pkg/networking/core/tracing.go
  pilot/pkg/networking/core/tracing_test.go
Labels: area/networking, size/L, release-notes-none

#50319 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#50267 istioctl: add enrolled namespace flag for users to enroll waypoints for a namespace
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/50221.yaml
  releasenotes/notes/50267.yaml
  tests/integration/ambient/waypoint_test.go
Labels: size/M, area/ambient

#50320 ambient: fix node filter
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
Labels: size/XS, release-notes-none

#50330 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50331 Enable vtprotobuf by default
  Makefile.core.mk
  go.mod
  go.sum
  pilot/pkg/features/pilot.go
Labels: size/S, release-notes-none

#50334 ambient: add test that we can access the api-server
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none

#50324 krt: allow lookup by Index, replace Namespace logic with Index
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/meshconfig.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pkg/kube/krt/bench_test.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/collection_test.go
  pkg/kube/krt/core.go
  pkg/kube/krt/fetch.go
  pkg/kube/krt/filter.go
  pkg/kube/krt/index.go
  pkg/kube/krt/index_test.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/informer_test.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/join_test.go
  pkg/kube/krt/singleton.go
  pkg/kube/krt/static.go
Labels: size/L, release-notes-none

#50329 samples: bump all addon versions for 1.22
  manifests/addons/gen.sh
  manifests/addons/values-kiali.yaml
  manifests/addons/values-loki.yaml
  samples/addons/extras/skywalking.yaml
  samples/addons/extras/zipkin.yaml
  samples/addons/grafana.yaml
  samples/addons/jaeger.yaml
  samples/addons/kiali.yaml
  samples/addons/loki.yaml
  samples/addons/prometheus.yaml
Labels: size/L, release-notes-none

#50338 helm: document openshift profile usage
  manifests/charts/install-OpenShift.md
Labels: size/S, release-notes-none

#50337 CNI: enable sidecars in istio-system
  manifests/charts/base/files/profile-ambient.yaml
  manifests/charts/base/files/profile-openshift-ambient.yaml
  manifests/charts/base/files/profile-openshift.yaml
  manifests/charts/default/files/profile-ambient.yaml
  manifests/charts/default/files/profile-openshift-ambient.yaml
  manifests/charts/default/files/profile-openshift.yaml
  manifests/charts/gateway/files/profile-ambient.yaml
  manifests/charts/gateway/files/profile-openshift-ambient.yaml
  manifests/charts/gateway/files/profile-openshift.yaml
  manifests/charts/gateways/istio-egress/files/profile-ambient.yaml
  manifests/charts/gateways/istio-egress/files/profile-openshift-ambient.yaml
  manifests/charts/gateways/istio-egress/files/profile-openshift.yaml
  manifests/charts/gateways/istio-ingress/files/profile-ambient.yaml
  manifests/charts/gateways/istio-ingress/files/profile-openshift-ambient.yaml
  manifests/charts/gateways/istio-ingress/files/profile-openshift.yaml
  manifests/charts/istio-cni/files/profile-ambient.yaml
  manifests/charts/istio-cni/files/profile-openshift-ambient.yaml
  manifests/charts/istio-cni/files/profile-openshift.yaml
  manifests/charts/istio-cni/values.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-ambient.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-openshift-ambient.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-openshift.yaml
  manifests/charts/istio-operator/files/profile-ambient.yaml
  manifests/charts/istio-operator/files/profile-openshift-ambient.yaml
  manifests/charts/istio-operator/files/profile-openshift.yaml
  manifests/charts/istiod-remote/files/profile-ambient.yaml
  manifests/charts/istiod-remote/files/profile-openshift-ambient.yaml
  manifests/charts/istiod-remote/files/profile-openshift.yaml
  manifests/charts/ztunnel/files/profile-ambient.yaml
  manifests/charts/ztunnel/files/profile-openshift-ambient.yaml
  manifests/charts/ztunnel/files/profile-openshift.yaml
  manifests/helm-profiles/ambient.yaml
  manifests/helm-profiles/openshift-ambient.yaml
  manifests/helm-profiles/openshift.yaml
  tests/integration/helm/util.go
Labels: size/S, release-notes-none

#50354 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50183 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50333 test changes to support revised ztunnel logic
  istio.deps
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none, area/ambient

#50343 Fix bug when virtual services overwrites routes
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/gateway_simulation_test.go
  releasenotes/notes/vs-overwrite-fix.yaml
Labels: area/networking, ok-to-test, size/L

#50336 tf: properly configure variant instead of hacking 'tag'
  Makefile.core.mk
  pkg/test/env/istio.go
  pkg/test/framework/components/authz/kube.go
  pkg/test/framework/components/echo/cmd/echogen/echogen_test.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/kube.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  prow/integ-suite-kind.sh
  tests/integration/ambient/main_test.go
  tests/integration/base.yaml
  tests/integration/helm/util.go
  tests/integration/iop-ambient-test-defaults.yaml
  tests/integration/operator/switch_cr_test.go
  tests/integration/operator/uninstall_test.go
  tests/integration/operator/verify_test.go
  tests/integration/pilot/gateway_test.go
  tests/integration/tests.mk
Labels: size/L, release-notes-none

#50357 revised tests to account for removal of hairpin
  istio.deps
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none, area/ambient

#50347 Split istioctl pc ztunnel info into zc
  istioctl/cmd/root.go
  istioctl/pkg/proxyconfig/proxyconfig.go
  istioctl/pkg/proxyconfig/proxyconfig_test.go
  istioctl/pkg/ztunnelconfig/ztunnelconfig.go
  istioctl/pkg/ztunnelconfig/ztunnelconfig_test.go
  releasenotes/notes/50347.yaml
Labels: size/XL, area/ambient

#50332 Move helm tests to use --profile=ambient
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: size/M, release-notes-none

#50230 [release-1.21] Implement CombinedAnalyzer interface
  pkg/config/analysis/analyzer.go
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/local/istiod_analyze.go
Labels: ok-to-test, size/M, release-notes-none

#50367 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50368 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49843 krt: fix register and sync race cause double events
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pkg/kube/controllers/common.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/core.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/singleton.go
  pkg/kube/krt/singleton_test.go
  pkg/kube/krt/static.go
  pkg/kube/krt/util.go
Labels: size/L, release-notes-none

#50340 download script should fail early when the download failed
  release/downloadIstioCtl.sh
Labels: area/environments, ok-to-test, size/XS, release-notes-none

#50374 remove legacy mock server
  pilot/pkg/model/push_context_test.go
  pilot/test/xdstest/mock_discovery.go
Labels: size/M, release-notes-none

#50388 Fix ambient helm test
  tests/integration/helm/upgrade/util.go
Labels: size/XS, release-notes-none

#50390 hbone listener: allow pods with no service
  pilot/pkg/networking/core/listener_inbound.go
Labels: size/XS, release-notes-none

#50391 validation: increase max connection timeout
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/XS, release-notes-none

#50392 prow: update metrics server
  prow/config/metrics/metrics.yaml
Labels: size/M, release-notes-none

#50393 cni: enable pprof, stop memory spikes
  cni/pkg/cmd/root.go
  pkg/ctrlz/ctrlz.go
  pkg/ctrlz/options.go
  pkg/file/file.go
  releasenotes/notes/cni-pprof.yaml
Labels: size/M, release-notes-none, cherrypick/release-1.20, cherrypick/release-1.21

#50394 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#50405 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50400 [release-1.21] cni: enable pprof, stop memory spikes
  cni/pkg/cmd/root.go
  pkg/ctrlz/ctrlz.go
  pkg/ctrlz/options.go
  pkg/file/file.go
  releasenotes/notes/cni-pprof.yaml
Labels: size/M, release-notes-none

#50407 cni: enable pprof, stop memory spikes (#50393)
  cni/pkg/cmd/root.go
  pkg/ctrlz/ctrlz.go
  pkg/ctrlz/options.go
  pkg/file/file.go
  releasenotes/notes/cni-pprof.yaml
Labels: size/M, release-notes-none

#50376 Cleanup some unused constants
  cni/pkg/constants/constants.go
  cni/pkg/iptables/iptables.go
  cni/pkg/nodeagent/constants/constants.go
  cni/pkg/nodeagent/server.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: size/M, release-notes-none

#50254 istioctl: handle DISABLE in TLS types for precheck
  istioctl/pkg/precheck/precheck.go
Labels: size/S, release-notes-none, cherrypick/release-1.21

#50411 [release-1.21] istioctl: handle DISABLE in TLS types for precheck
  istioctl/pkg/precheck/precheck.go
Labels: size/S, release-notes-none

#50421 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50427 Update install-OpenShift.md
  manifests/charts/install-OpenShift.md
Labels: size/XS, release-notes-none

#50426 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48818 Untaint controller
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  pilot/cmd/pilot-discovery/app/cmd.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/controllers/untaint/nodeuntainter.go
  pilot/pkg/controllers/untaint/nodeuntainter_test.go
  pilot/pkg/features/pilot.go
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pkg/test/framework/resource/setup.go
  pkg/test/framework/suite.go
  releasenotes/notes/48818.yaml
  tests/integration/ambient/untaint/main_test.go
  tests/integration/ambient/untaint/untaint_test.go
Labels: size/XL, area/ambient

#50424 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50409 Initial update to Gateway API 1.1
  go.mod
  go.sum
  pilot/pkg/config/kube/crdclient/types.gen.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/grpc.status.yaml.golden
  pkg/config/model_test.go
  pkg/config/schema/codegen/templates/collections.go.tmpl
  pkg/config/schema/collections/collections.agent.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/XXL, release-notes-none

#50425 ambient: fix targetRef for Authz, move all tests over
  pilot/pkg/networking/plugin/authz/authorization.go
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/testdata/requestauthn/waypoint-jwt.yaml.tmpl
Labels: size/M, release-notes-none

#50433 ambient: drop conformance test skip
  tests/integration/ambient/gateway_conformance_test.go
Labels: size/XS, release-notes-none

#50359 Ambient CNI: propagate Kubernetes pod info to ztunnel
  cni/pkg/nodeagent/fakes_test.go
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/net_test.go
  cni/pkg/nodeagent/pod_cache.go
  cni/pkg/nodeagent/pod_cache_test.go
  cni/pkg/nodeagent/podcgroupns.go
  cni/pkg/nodeagent/podcgroupns_test.go
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/nodeagent/ztunnelserver_test.go
  cni/pkg/util/podutil.go
  pkg/zdsapi/zds.pb.go
  pkg/zdsapi/zds.proto
Labels: size/L, release-notes-none

#50435 mod: bump to k8s 1.30 pre-release
  go.mod
  go.sum
  tests/binary/binaries_test.go
Labels: size/M, release-notes-none

#50363 ambient: implement workload and service waypoints for EDS
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  tests/integration/ambient/baseline_test.go
Labels: size/L, release-notes-none

#50441 tests: make security timeout test more resiliant
  tests/integration/security/testdata/requestauthn/timeout.yaml.tmpl
Labels: size/XS, release-notes-none

#50443 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50446 node tainter: fix test flakes
  pilot/pkg/controllers/untaint/nodeuntainter.go
  pilot/pkg/controllers/untaint/nodeuntainter_test.go
Labels: size/S, release-notes-none

#50449 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50450 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50439 api: implement targetRefs support
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
  pilot/pkg/model/policyattachment.go
  pilot/pkg/model/policyattachment_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/L, release-notes-none

#50442 istioctl: cleanup ValidArgsFunction
  istioctl/pkg/admin/istiodconfig.go
  istioctl/pkg/authz/authz.go
  istioctl/pkg/checkinject/checkinject.go
  istioctl/pkg/completion/completion.go
  istioctl/pkg/describe/describe.go
  istioctl/pkg/metrics/metrics.go
  istioctl/pkg/proxyconfig/proxyconfig.go
  istioctl/pkg/proxystatus/proxystatus.go
  istioctl/pkg/ztunnelconfig/ztunnelconfig.go
Labels: size/M, release-notes-none

#50453 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50454 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#50455 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#50456 chore: fix some comments
  cni/pkg/nodeagent/healthServer.go
  istioctl/pkg/dashboard/dashboard.go
  operator/pkg/compare/compare.go
Labels: ok-to-test, size/XS, release-notes-none

#50434 ambient: include extra services to allow extensions to work
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/waypoint.go
Labels: size/S, release-notes-none

#50451 remove VERIFY_SDS_CERTIFICATE feature flag
  pilot/pkg/features/experimental.go
  pilot/pkg/xds/sds.go
Labels: size/S, release-notes-none

#50461 Sort values for validTrafficType
  istioctl/pkg/waypoint/waypoint.go
Labels: size/XS, release-notes-none

#50463 ambient: test `targetRefs` instead of singular
  pilot/pkg/model/policyattachment.go
  pilot/pkg/model/policyattachment_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/testdata/requestauthn/waypoint-jwt.yaml.tmpl
Labels: size/M, release-notes-none

#50288 Helm install tests for ambient multi-namespace deployment scenarios
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: area/environments, area/user experience, size/L, release-notes-none, area/ambient

#50467 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#50395 istioctl: we should warn when namespace is not labeled ambient
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/50395.yaml
Labels: size/M, area/ambient

#50468 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none
