Repository istio/istio, pull requests merged in 2024-10, with the labels that each got.

#53356 Minor optimization around SupportsTunnel
  pilot/pkg/model/service.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
Labels: size/S, release-notes-none

#53360 Partial revert of #53348 to fix race
  pilot/pkg/model/addressmap.go
Labels: size/XS, release-notes-none

#53351 Added metrics port to kube-gateway.yaml manifest
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/custom-class.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/infrastructure-labels-annotations.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect-infra.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/proxy-config-crd.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/53351.yaml
Labels: ok-to-test, size/M, area/ambient

#53374 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53377 1.23: bump to docker 26.1.5
  go.mod
  go.sum
Labels: size/S, release-notes-none

#53376 cleanup invalid yaml in test
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none

#53091 AuthorizationPolicy status for waypoint attachment
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
  pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/conversion.go
  pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go
  releasenotes/notes/53091.yaml
Labels: size/XL, area/ambient

#53380 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53336 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53362 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53372 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53378 Fix postsubmit fails caused by #53318
  releasenotes/notes/53318.yaml
  tests/integration/helm/main_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: size/M, release-notes-none

#53298 [release-1.22] Fix httpbin sample's command
  samples/httpbin/httpbin-vault.yaml
  samples/httpbin/httpbin.yaml
Labels: size/XS, release-notes-none

#53394 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53398 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
  pkg/config/validation/testdata/crds/serviceentry-invalid.yaml
  pkg/config/validation/testdata/crds/serviceentry-valid.yaml
  pkg/config/validation/testdata/crds/workloadgroup-invalid.yaml
  pkg/config/validation/testdata/crds/workloadgroup-valid.yaml
Labels: size/L, auto-merge, release-notes-none

#53403 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53412 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53373 Add metrics port to waypoint
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: size/XS, release-notes-none

#53381 Add curl sample to replace sleep
  releasenotes/notes/curl-sample.yaml
  samples/curl/README.md
  samples/curl/curl.yaml
  samples/security/spire/curl-spire.yaml
  samples/sleep/README.md
Labels: size/L

#53416 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53417 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53418 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53420 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53410 docs: Add Makefile.k8s.mk Usage
  tools/certs/README.md
Labels: ok-to-test, size/S, release-notes-none

#53367 Allow extra spaces between namespaces in networking.istio.io/exportTo annotation
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/kube/conversion_test.go
  pkg/config/analysis/analyzers/util/service_lookup.go
  pkg/config/analysis/analyzers/util/service_lookup_test.go
  releasenotes/notes/53429.yaml
Labels: ok-to-test, size/L

#53329 Bump gateway to 1.2.0
  go.mod
  go.sum
  licenses/github.com/cyphar/filepath-securejoin/LICENSE
  pilot/pkg/config/kube/gateway/testdata/grpc.yaml
  tests/integration/pilot/gateway_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/XXL, release-notes-none

#53432 Make direct test client compatible with Istio-isms
  pkg/kube/kclient/clienttest/direct.go
  pkg/kube/kclient/clienttest/direct_test.go
Labels: size/M, release-notes-none

#53446 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53447 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53449 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53436 bikeshed yaml manifest ordering
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Labels: size/XS, release-notes-none

#53444 Fix a few issues in chart rendering
  manifests/charts/base/templates/zzz_profile.yaml
  manifests/charts/default/templates/zzz_profile.yaml
  manifests/charts/gateway/templates/zzz_profile.yaml
  manifests/charts/gateways/istio-egress/templates/zzz_profile.yaml
  manifests/charts/gateways/istio-ingress/templates/zzz_profile.yaml
  manifests/charts/istio-cni/templates/zzz_profile.yaml
  manifests/charts/istio-control/istio-discovery/templates/zzz_profile.yaml
  manifests/charts/ztunnel/templates/zzz_profile.yaml
  manifests/zzz_profile.yaml
  operator/pkg/values/map.go
Labels: size/M, release-notes-none

#53442 [release-1.22] Support clusterLocal host exclusions for multi-cluster
  pilot/pkg/model/cluster_local.go
  pilot/pkg/model/cluster_local_test.go
  releasenotes/notes/52367.yaml
Labels: ok-to-test, size/L

#53448 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#53445 Add debug logs for full push
  pilot/pkg/xds/discovery.go
Labels: size/XS, release-notes-none

#53451 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53453 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53454 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53456 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53457 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53458 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53460 Automator: update istio/client-go@release-1.23 dependency in istio/istio@release-1.23
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53461 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53465 Automator: update ztunnel@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53383 [release-1.23] Added metrics port to kube gateway.yaml manifest
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/custom-class.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/infrastructure-labels-annotations.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect-infra.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/kube-gateway-ambient-redirect.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/proxy-config-crd.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/53351.yaml
Labels: ok-to-test, size/M, area/ambient

#53474 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53477 gateway: report status for istio-remote gateway
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/eastwest-remote.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/eastwest-remote.yaml
Labels: size/M, release-notes-none

#53466 Make tf deployment a bit more flexible
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/kube.go
Labels: size/S, release-notes-none

#53480 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53467 docs: add architectural documentation describing integration test setup
  architecture/tests/integration.md
Labels: kind/docs, size/L, release-notes-none

#53450 istioctl: support filter resource by namespace for injector list
  istioctl/pkg/injector/injector-list.go
  releasenotes/notes/53450.yaml
Labels: area/user experience, size/S, release-notes-none

#53468 adsc: improve backoff for delta mode
  pkg/adsc/adsc.go
  pkg/adsc/delta.go
  pkg/adsc/delta_test.go
Labels: size/M, release-notes-none

#53435 Add abilility to use traffic distribution on old k8s clusters
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.39.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.46.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.42.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
Labels: size/M, release-notes-none

#53337 add cert to xfcc header for sidecar
  pilot/pkg/networking/core/httproute.go
  pilot/pkg/networking/core/listener_inbound.go
  releasenotes/notes/53337.yaml
  tests/integration/pilot/headers_test.go
Labels: size/L

#53486 Respect --namespace flag in `istioctl ztunnelconfig`
  istioctl/pkg/ztunnelconfig/ztunnelconfig.go
  tests/integration/ambient/istioctl_test.go
Labels: size/XS, release-notes-none

#53484 Fix kube-virt-related rules cleanup in legacy istio-clean-iptables
  releasenotes/notes/48368.yaml
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-clean-iptables/pkg/cmd/testdata/ipnets-with-kube-virt-interfaces.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/kube-virt-interfaces.golden
  tools/istio-clean-iptables/pkg/config/config.go
Labels: area/networking, size/L, cherrypick/release-1.22, cherrypick/release-1.23

#53485 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53049 [release-1.23] Fix TestTunnelingOutboundTraffic failure on OCP
  tests/integration/pilot/testdata/external-forward-proxy-deployment.yaml
  tests/integration/pilot/tunneling_test.go
Labels: size/XS, release-notes-none

#53498 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53479 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53488 don't process status queue while ambient index is not synched
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
Labels: size/XS, release-notes-none, area/ambient

#53501 regen proto with new version
  operator/pkg/apis/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/workload.pb.go
  pkg/zdsapi/zds.pb.go
Labels: size/XS, release-notes-none

#53506 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53500 bookinfo: bump details lock and actually use it
  samples/bookinfo/src/details/Dockerfile
  samples/bookinfo/src/details/Gemfile.lock
Labels: size/XS, release-notes-none, cherrypick/release-1.22, cherrypick/release-1.23

#53513 cni: optimize memory footprint
  pkg/file/fadvise_linux.go
  pkg/file/fadvise_unspecified.go
  pkg/file/file.go
  releasenotes/notes/cni-memory.yaml
Labels: size/M, release-notes-none

#53478 Explicitly set privileged istio-cni to false
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/52558.yaml
Labels: area/security, size/S

#53514 [release-1.23] bookinfo: bump details lock and actually use it
  samples/bookinfo/src/details/Dockerfile
  samples/bookinfo/src/details/Gemfile.lock
Labels: size/XS, release-notes-none

#53511 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53518 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53519 add x-envoy-attempt-count to proxy headers
  tests/integration/pilot/headers_test.go
Labels: size/XS, release-notes-none

#53520 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53523 [release-1.22] Fix kube-virt-related rules cleanup in legacy istio-clean-iptables
  releasenotes/notes/48368.yaml
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-clean-iptables/pkg/cmd/testdata/ipnets-with-kube-virt-interfaces.golden
  tools/istio-clean-iptables/pkg/cmd/testdata/kube-virt-interfaces.golden
  tools/istio-clean-iptables/pkg/config/config.go
Labels: area/networking, size/L

#53528 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53529 Include .Values.seLinuxOptions in istio-cni-node DaemonSet
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: area/networking, ok-to-test, size/XS, release-notes-none

#53535 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53541 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53490 native-sidecars: add per-pod opt-in/out annotation
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/native-sidecar-opt-in.yaml
  pkg/kube/inject/testdata/inject/native-sidecar-opt-in.yaml.injected
  pkg/kube/inject/testdata/inject/native-sidecar-opt-out.yaml
  pkg/kube/inject/testdata/inject/native-sidecar-opt-out.yaml.injected
  pkg/kube/inject/testdata/inputs/custom-template.yaml.43.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.43.values.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.values.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
  releasenotes/notes/native-sidecar-annotation.yaml
Labels: area/environments, ok-to-test, size/XL, area/upgrade

#52564 [release-1.23] allow sni hosts with outbound_ in vs, when bound to gw
  pkg/config/validation/agent/validation.go
  pkg/config/validation/agent/validation_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
Labels: size/L, release-notes-none

#53534 cleanup: remove istio_authn generator
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_internal_test.go
  pilot/pkg/networking/core/route/route_test.go
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/networking/plugin/authn/authentication.go
  pilot/pkg/networking/plugin/authz/authorization.go
  pilot/pkg/security/authn/factory.go
  pilot/pkg/security/authn/policy_applier.go
  pilot/pkg/security/authn/policy_applier_test.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/builder_test.go
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/multiple-policies-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/single-policy-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/audit-both-http-tcp-out.yaml
  pilot/pkg/security/authz/builder/testdata/tcp/deny-both-http-tcp-out.yaml
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
  pilot/pkg/security/authz/model/model.go
  pilot/pkg/security/authz/model/model_test.go
  pilot/pkg/security/authz/model/util.go
  pilot/pkg/xds/filters/filters.go
Labels: size/XXL, release-notes-none

#53544 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53540 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53545 Run make gen
  pkg/test/echo/proto/echo_grpc.pb.go
Labels: area/test and release, size/XS, release-notes-none

#53547 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53499 Add initial ztunnel cross-version test
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
  tests/util/sanitycheck/sanity_check.go
Labels: size/L, release-notes-none, area/ambient

#53552 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53489 validation: future proof unknown versions
  pkg/config/schema/collection/schemas.go
  pkg/webhooks/validation/server/server.go
  releasenotes/notes/futureproof-version.yaml
Labels: size/S

#53463 Fix mirroring from waypoints
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/route/route.go
  releasenotes/notes/waypoint-mirror.yaml
Labels: size/M

#53542 Fix remote profile
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  manifests/charts/istio-control/istio-discovery/templates/reader-clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/templates/remote-istiod-endpoints.yaml
  manifests/charts/istio-control/istio-discovery/templates/remote-istiod-service.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  operator/cmd/mesh/manifest-generate_test.go
Labels: ok-to-test, size/S, feature/Multi-cluster, release-notes-none

#53546 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53533 manifests: fix gateway waypoint template on OpenShift
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
Labels: ok-to-test, size/XS, release-notes-none

#53568 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53472 feat(destinationRule): :rocket: Adding warmup configuration
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
  pkg/config/validation/testdata/crds/destinationrule-invalid.yaml
  pkg/config/validation/testdata/crds/destinationrule-valid.yaml
  pkg/config/validation/testdata/crds/serviceentry-valid.yaml
  pkg/config/validation/validation.go
  releasenotes/notes/3215.yaml
Labels: ok-to-test, size/L

#53443 [release-1.23] Support clusterLocal host exclusions for multi-cluster (#52367)
  pilot/pkg/model/cluster_local.go
  pilot/pkg/model/cluster_local_test.go
  releasenotes/notes/52367.yaml
Labels: ok-to-test, size/L

#53565 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53570 Bring deferred_stat_options out of the cluster_manager's condition
  tools/packaging/common/envoy_bootstrap.json
Labels: ok-to-test, size/XS, release-notes-none

#53571 istioctl: fix injector list prints webhooks not related to istio
  istioctl/pkg/injector/injector-list.go
  releasenotes/notes/53571.yaml
Labels: size/S, release-notes-none

#53574 Fix openshift and openshift-ambient profiles
  manifests/profiles/openshift-ambient.yaml
  manifests/profiles/openshift.yaml
Labels: area/environments, size/XS, release-notes-none

#53575 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53576 Always set type to spc_t for istio-cni if seLinux is configured
  manifests/charts/istio-cni/templates/daemonset.yaml
Labels: area/environments, size/XS, release-notes-none

#53470 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53584 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53585 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53586 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53591 bump Kiali to v2.0.0
  manifests/addons/gen.sh
  manifests/addons/values-kiali.yaml
  releasenotes/notes/kiali-update-v2.0.yaml
  samples/addons/kiali.yaml
Labels: area/environments, area/extensions and telemetry, size/L

#53572 do not send unhealthy endpoints in nds for headless
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pkg/dns/server/name_table.go
  releasenotes/notes/53572.yaml
Labels: size/S

#53587 minor optimize FilterInPlace
  pkg/slices/slices.go
  pkg/slices/slices_test.go
Labels: area/networking, area/perf and scalability, size/M, release-notes-none

#53487 traffic distribution: move to API repo
  cni/pkg/nodeagent/net.go
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
Labels: size/S, release-notes-none

#53595 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53057 Use cluster contexts in kubeconfig instead of remote secrets in multi-cluster service analyzer.
  istioctl/pkg/analyze/analyze.go
  istioctl/pkg/cli/context.go
  pkg/kube/util.go
  pkg/test/framework/components/istioctl/kube.go
  releasenotes/notes/51934.yaml
  tests/integration/pilot/analyze_test.go
Labels: ok-to-test, area/user experience, size/L, feature/Multi-cluster

#53599 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53592 addons: bump versions, ~including Kiali 2.0~
  manifests/addons/gen.sh
  samples/addons/grafana.yaml
  samples/addons/loki.yaml
  samples/addons/prometheus.yaml
Labels: size/L, release-notes-none

#53600 Fix helm value in external Istiod chart
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: area/environments, size/XS, feature/Multi-cluster, release-notes-none

#53606 chore: less noise
  pilot/pkg/networking/core/extension_config_builder.go
Labels: size/XS, release-notes-none

#52281 Add manifest translate command
  operator/cmd/mesh/manifest-generate.go
  operator/cmd/mesh/manifest-translate.go
  operator/cmd/mesh/manifest.go
  operator/cmd/mesh/readme.tpl
  operator/pkg/component/component.go
  operator/pkg/render/manifest.go
Labels: size/L, lifecycle/automatically-closed, release-notes-none

#53598 Cherry-pick security fixes to master
  pilot/pkg/features/xds.go
  pilot/pkg/networking/core/listener_builder.go
  pilot/pkg/networking/core/listener_builder_test.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/testdata/explicit_internal_address.proxycfg
  pkg/bootstrap/testdata/explicit_internal_address_golden.json
Labels: area/security, size/XL, release-notes-none

#53602 Update Gateway API version in samples to v1
  samples/ambient-argo/application/details-waypoint.yaml
  samples/ambient-argo/application/ingress-gateway.yaml
  samples/ambient-argo/application/reviews-waypoint.yaml
  samples/ambient-argo/application/route-reviews-90-10.yaml
  samples/bookinfo/gateway-api/bookinfo-gateway.yaml
  samples/bookinfo/gateway-api/route-all-v1.yaml
  samples/bookinfo/gateway-api/route-reviews-50-v3.yaml
  samples/bookinfo/gateway-api/route-reviews-90-10.yaml
  samples/bookinfo/gateway-api/route-reviews-v1.yaml
  samples/bookinfo/gateway-api/route-reviews-v3.yaml
  samples/helloworld/gateway-api/helloworld-gateway.yaml
  samples/helloworld/gateway-api/helloworld-route.yaml
  samples/httpbin/gateway-api/httpbin-gateway.yaml
  samples/tcp-echo/gateway-api/tcp-echo-all-v1.yaml
Labels: kind/docs, size/M, release-notes-none

#52985 Support sending from ingress -> service waypoint
  pilot/pkg/features/ambient.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  pilot/test/xdstest/extract.go
  pkg/kube/krt/core.go
  pkg/kube/krt/util.go
  tests/integration/ambient/waypoint_test.go
Labels: size/XL, release-notes-none

#53608 Update envoy go-control-plane
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/XS, release-notes-none

#53588 waypoint: enable TLS inspector if TLS service is enrolled
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/xds/waypoint_test.go
  releasenotes/notes/53588.yaml
Labels: area/networking, size/M, area/ambient

#53619 release-1.24 Automation step 1
  docker/Dockerfile.distroless
  go.mod
  go.sum
  prow/release-commit.sh
Labels: size/S, release-notes-none

#53622 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53621 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53594 Fix crash due to shared mutable state in EnvoyFilter
  pilot/pkg/model/authorization_test.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
  pilot/pkg/networking/core/cluster_waypoint.go
  pilot/pkg/networking/core/envoyfilter/rc_patch.go
  pilot/pkg/networking/core/envoyfilter/rc_patch_test.go
  pilot/pkg/security/authn/policy_applier_test.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/endpoints/ep_filters.go
  pkg/config/mesh/mesh.go
  pkg/config/model.go
  pkg/config/validation/agent/validation_test.go
  pkg/config/validation/validation.go
  pkg/dns/client/dns_test.go
  pkg/istio-agent/agent.go
  pkg/kube/inject/template.go
  pkg/util/protomarshal/protomarshal.go
Labels: size/L, release-notes-none

#53624 Add user-overridable env to `istio-cni` chart, since we have it for everything else already
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/values.yaml
  releasenotes/notes/53624.yaml
Labels: area/environments, size/S, area/ambient, cherrypick/release-1.23

#53625 Change istioctl analyze --remote-cluster-context flag to --remote-contexts
  istioctl/pkg/analyze/analyze.go
  istioctl/pkg/cli/context.go
  releasenotes/notes/51934.yaml
  tests/integration/pilot/analyze_test.go
Labels: ok-to-test, area/user experience, size/M, feature/Multi-cluster

#53623 DNS jitter
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
  releasenotes/notes/52877.yaml
Labels: area/perf and scalability, size/S

#53632 I think this might be all we need to OCI-publish dev build charts
  prow/release-commit.sh
Labels: area/test and release, area/environments, size/XS, release-notes-none

#53610 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53618 fix precheck output
  istioctl/pkg/precheck/precheck.go
Labels: size/XS, release-notes-none

#53626 pilot: minor deduplication of code
  pilot/pkg/model/config.go
  pilot/pkg/xds/workload.go
Labels: size/S, release-notes-none

#53640 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53635 improve the code format for istioctl x es output
  istioctl/pkg/proxyconfig/proxyconfig.go
Labels: size/S, release-notes-none

#53638 improve istioctl analyze output
  istioctl/pkg/analyze/analyze.go
Labels: size/XS, release-notes-none

#53642 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53630 Updated tests and docs for jitter
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_builder_test.go
Labels: size/XS, release-notes-none

#53646 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53647 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53648 Automator: update proxy@release-1.22 in istio/istio@release-1.22
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53582 Remove --recursive flags for istioctl analyze
  istioctl/pkg/analyze/analyze.go
  releasenotes/notes/53582.yaml
  tests/integration/pilot/analyze_test.go
Labels: size/M

#53651 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53652 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53656 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53675 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53677 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#53679 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53681 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#53682 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#53650 istioctl: add support for trust bundles to `proxy-config secret`
  istioctl/pkg/writer/compare/sds/util.go
  istioctl/pkg/writer/compare/sds/writer.go
  istioctl/pkg/writer/envoy/configdump/secret_test.go
  istioctl/pkg/writer/envoy/configdump/testdata/secret/istio/config_dump.json
  istioctl/pkg/writer/envoy/configdump/testdata/secret/istio/output
  istioctl/pkg/writer/envoy/configdump/testdata/secret/spire/config_dump.json
  istioctl/pkg/writer/envoy/configdump/testdata/secret/spire/output
  releasenotes/notes/53650.yaml
Labels: area/user experience, size/L

#53643 krt: allow changing the state of the static collection
  pkg/kube/krt/static.go
  pkg/kube/krt/static_test.go
Labels: size/L, release-notes-none

#53687 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none
