Repository istio/istio, pull requests merged in 2024-02, with the labels that each got.

#49123 [release-1.20] Bump distroless iptables image
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/XS, release-notes-none

#49133 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49125 [release-1.21] Bump distroless iptables image
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/XS, release-notes-none

#49122 [release-1.19] Bump distroless iptables image
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.ztunnel
Labels: size/XS, release-notes-none

#49136 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49132 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49142 correct CODEOWNER for /pkg/adsc
  CODEOWNERS
Labels: size/XS, release-notes-none

#49146 [release-1.21] Run update_deps.sh
  common/config/.golangci.yml
  prow/release-commit.sh
  tests/integration/pilot/gateway_conformance_test.go
Labels: size/XS, release-notes-none

#49137 lint depguard
  common/config/.golangci.yml
  tests/integration/pilot/gateway_conformance_test.go
Labels: size/XS, release-notes-none

#49138 ambient: remove irrational code block for ns scan
  cni/pkg/nodeagent/net.go
Labels: size/S, release-notes-none, area/ambient

#49155 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#49153 [release-1.20] Manual cherry-pick of 49127
  go.mod
  go.sum
Labels: size/S, release-notes-none

#49131 Ambient PeerAuthentication should use AND semantics instead of OR
  pilot/pkg/serviceregistry/kube/controller/authorization.go
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-disable-port-mtls.yaml
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-permissive-port-mtls.yaml
  releasenotes/notes/49098.yaml
Labels: size/M, area/ambient, Ambient Beta, cherrypick/release-1.19, cherrypick/release-1.20, cherrypick/release-1.21

#49158 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49157 Add peerauth test to cover port-level PERMISSIVE.
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none

#49159 [release-1.19] Ambient PeerAuthentication should use AND semantics instead of OR
  pilot/pkg/serviceregistry/kube/controller/authorization.go
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-disable-port-mtls.yaml
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-permissive-port-mtls.yaml
  releasenotes/notes/49098.yaml
Labels: size/M, release-notes-none

#49160 [release-1.20] Ambient PeerAuthentication should use AND semantics instead of OR
  pilot/pkg/serviceregistry/kube/controller/authorization.go
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-disable-port-mtls.yaml
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-permissive-port-mtls.yaml
  releasenotes/notes/49098.yaml
Labels: size/M, release-notes-none

#49161 [release-1.21] Ambient PeerAuthentication should use AND semantics instead of OR
  pilot/pkg/serviceregistry/kube/controller/authorization.go
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-disable-port-mtls.yaml
  pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-permissive-port-mtls.yaml
  releasenotes/notes/49098.yaml
Labels: size/M, release-notes-none

#49152 [release-1.19] Manual cherry-pick of 49127
  go.mod
  go.sum
  licenses/github.com/klauspost/compress/snappy/xerial/LICENSE
Labels: size/M, release-notes-none

#44802 Add ownerReferences in waypoint SA
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/custom-class.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/infrastructure-labels-annotations.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/proxy-config-crd.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  pkg/kube/version.go
  pkg/kube/version_test.go
Labels: size/L, release-notes-none, area/ambient

#48841 Bump go-control-plane
  go.mod
  go.sum
  pilot/pkg/features/pilot.go
  pilot/pkg/util/protoconv/protoconv.go
  pkg/config/xds/filter_types.gen.go
  tests/binary/binaries_test.go
Labels: size/S, release-notes-none

#49094 Ambient CNI: Fix informer reconciliation logs
  cni/pkg/nodeagent/cni-watcher.go
  cni/pkg/nodeagent/cni-watcher_test.go
Labels: size/L, release-notes-none, area/ambient, cherrypick/release-1.21

#49139 Fix delta ADS client
  pkg/adsc/delta.go
  pkg/adsc/delta_test.go
  releasenotes/notes/49139.yaml
Labels: area/networking, size/L

#49165 [release-1.21] Ambient CNI: Fix informer reconciliation logs
  cni/pkg/nodeagent/cni-watcher.go
  cni/pkg/nodeagent/cni-watcher_test.go
Labels: size/L, release-notes-none

#49166 Fix network label exists on waypoint when no network config is set
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
Labels: area/networking, size/XS, release-notes-none

#49163 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49168 [release-1.21] Manual cherry-pick of 49127
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#49170 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#48942 fix: revision value should be respected for remote cluster svc/endpoint
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
  manifests/charts/istiod-remote/templates/endpoints.yaml
  manifests/charts/istiod-remote/templates/services.yaml
  releasenotes/notes/remote-cluster-respect-revision.yaml
Labels: area/environments, ok-to-test, size/S, cherrypick/release-1.19, cherrypick/release-1.20, cherrypick/release-1.21

#49017 Cleanup analysis legacy package
  istioctl/pkg/precheck/precheck.go
  pilot/pkg/config/aggregate/config_test.go
  pilot/pkg/config/file/store.go
  pkg/config/analysis/analyzers/util/find_errorline_utils_test.go
  pkg/config/analysis/incluster/controller.go
  pkg/config/analysis/legacy/source/kube/origin.go
  pkg/config/analysis/legacy/util/kuberesource/resources.go
  pkg/config/analysis/local/context.go
  pkg/config/analysis/local/helpers_test.go
  pkg/config/analysis/local/istiod_analyze.go
  pkg/config/legacy/mesh/const.go
  pkg/config/legacy/testing/fixtures/expect.go
Labels: area/user experience, size/L, release-notes-none

#49035 add support for inbound traffic policy
  manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/pkg/util/merge_iop.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  pkg/config/mesh/mesh.go
  pkg/kube/inject/inject.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.37.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/drop-legacy-inbound-passthrough.yaml
Labels: size/L

#49049 istioctl: add namespace filtering to workload configdump
  istioctl/pkg/proxyconfig/proxyconfig.go
  istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary_default.txt
  istioctl/pkg/writer/ztunnel/configdump/workload.go
  releasenotes/notes/49049.yaml
Labels: area/user experience, size/M

#49134 add off/in ambient test for bookinfo
  tests/integration/ambient/bookinfo_test.go
Labels: size/XS, release-notes-none

#49173 Remove unused flag NATIVE_METADATA_EXCHANGE
  pilot/pkg/features/experimental.go
Labels: size/XS, release-notes-none

#49176 xds: Fix test that hangs for 10s
  pilot/pkg/xds/eds_test.go
Labels: size/S, release-notes-none

#49178 [release-1.21] fix: revision value should be respected for remote cluster svc/endpoint
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
  manifests/charts/istiod-remote/templates/endpoints.yaml
  manifests/charts/istiod-remote/templates/services.yaml
  releasenotes/notes/remote-cluster-respect-revision.yaml
Labels: size/S, release-notes-none

#49190 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49191 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#49185 context: utilize new AfterFunc to avoid unneeded goroutines
  cni/pkg/nodeagent/cni-watcher.go
  cni/pkg/nodeagent/ztunnelserver.go
  pilot/pkg/status/resourcelock.go
  pilot/pkg/xds/adstest.go
  pilot/pkg/xds/deltaadstest.go
Labels: size/M, release-notes-none

#49192 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49189 ambient: fix: use lastest pod status to determine the action
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
Labels: size/L, release-notes-none, area/ambient

#49193 refactor: extract VSMatches function
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/virtualservice.go
Labels: area/networking, size/M, release-notes-none

#49199 ambient: cleanup dup logs while del/opt-out Pods
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/server.go
Labels: size/S, release-notes-none, area/ambient

#49011 A multi-cluster node authorizer to support multi-cluster scenario in ambient mesh
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  releasenotes/notes/49011.yaml
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
  security/pkg/server/ca/node_auth.go
  security/pkg/server/ca/node_auth_test.go
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: area/security, ok-to-test, size/XL, area/ambient

#49211 Revert "add off/in ambient test for bookinfo"
  tests/integration/ambient/bookinfo_test.go
Labels: size/XS, release-notes-none

#49196 Extract method
  pilot/pkg/model/sidecar.go
Labels: area/networking, size/M, release-notes-none

#49200 Update adsc.go
  pkg/adsc/adsc.go
Labels: ok-to-test, size/S, release-notes-none

#49143 move demo providers into namespace observability
  manifests/charts/base/files/profile-demo.yaml
  manifests/charts/default/files/profile-demo.yaml
  manifests/charts/gateway/files/profile-demo.yaml
  manifests/charts/gateways/istio-egress/files/profile-demo.yaml
  manifests/charts/gateways/istio-ingress/files/profile-demo.yaml
  manifests/charts/istio-cni/files/profile-demo.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-demo.yaml
  manifests/charts/istio-operator/files/profile-demo.yaml
  manifests/charts/istiod-remote/files/profile-demo.yaml
  manifests/charts/ztunnel/files/profile-demo.yaml
  manifests/helm-profiles/demo.yaml
Labels: area/test and release, size/XS, release-notes-none

#49164 gateway-api: fix a race condition when updating status
  pilot/pkg/config/kube/gateway/controller.go
Labels: area/networking, size/S, release-notes-none

#49206 Improve envoyfilter patch implementation
  pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/util.go
  pilot/pkg/networking/core/v1alpha3/envoyfilter/util_test.go
Labels: area/networking, size/L, release-notes-none

#49217 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#49218 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49175 istioctl: avoid 30s Istioctl test
  istioctl/pkg/wait/wait_test.go
Labels: size/S, release-notes-none

#49183 istioctl: support v1 Gateway API
  istioctl/pkg/util/handlers/handlers.go
Labels: size/XS, release-notes-none

#49216 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49227 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49207 cni-plugin: fix plugin execution broken by ambient
  cni/pkg/plugin/plugin.go
Labels: area/networking, size/XS, release-notes-none, area/ambient, cherrypick/release-1.21

#49233 Update BASE_VERSION to 1.19-2024-02-06T19-03-20
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#49232 Update BASE_VERSION to 1.21-2024-02-06T19-00-52
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#49234 Update BASE_VERSION to 1.20-2024-02-06T19-04-57
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#49235 Update BASE_VERSION to master-2024-02-06T19-29-28
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#49197 refactor collectImportedServices func
  pilot/pkg/model/sidecar.go
Labels: area/networking, size/M, release-notes-none

#49230 [release-1.21] cni-plugin: fix plugin execution broken by ambient
  cni/pkg/plugin/plugin.go
Labels: size/XS, release-notes-none

#49180 kclient: support patch operation
  pkg/kube/kclient/client.go
  pkg/kube/kclient/interfaces.go
Labels: size/XS, release-notes-none

#49213 Use session cookies instead of 2-min hardcoded persistent cookies
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: size/S, release-notes-none

#49240 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49187 krt: add new recompute trigger
  pkg/kube/krt/recomputetrigger.go
  pkg/kube/krt/recomputetrigger_test.go
Labels: size/M, release-notes-none

#49243 remove deepequals in tests
  pilot/pkg/networking/core/v1alpha3/envoyfilter/util_test.go
Labels: size/S, release-notes-none

#49209 Improves further on PR #49189
  cni/pkg/nodeagent/informers.go
Labels: size/XS, release-notes-none

#49237 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49245 remove appsnals
  pkg/appsignals/watcher.go
  pkg/appsignals/watcher_test.go
  pkg/ctrlz/ctrlz_test.go
  pkg/ctrlz/topics/signals.go
Labels: size/L, release-notes-none

#49250 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49248 Сommas have been fixed
  architecture/networking/pilot.md
  manifests/charts/README.md
Labels: ok-to-test, size/XS, release-notes-none

#49249 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49251 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#49179 Ambient Helm Install/Upgrade Integration Tests
  pkg/test/framework/features/features.yaml
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: area/test and release, size/L, release-notes-none

#49252 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#48770 [gw-api] publish supported features in gateway class
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/gatewayclass.go
  pilot/pkg/config/kube/gateway/supported_features.go
  pilot/pkg/config/kube/gateway/testdata/alias.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/delegated.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/grpc.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mismatch.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden
  releasenotes/notes/gateway-gwc-publish-supportedfeatures.yaml
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: area/networking, ok-to-test, size/XXL

#49259 cni: use iptables distroless variant
  cni/deployments/kubernetes/Dockerfile.install-cni
Labels: size/XS, release-notes-none

#49238 ambient: more strict UT check for event handler
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
Labels: size/S, release-notes-none, area/ambient

#49254 lint: adopt gofumpt 0.6.0 rules
  cni/pkg/install/kubeconfig_test.go
  operator/pkg/translate/translate_value.go
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server.go
  security/pkg/nodeagent/caclient/providers/google-cas/client.go
  tests/integration/pilot/analysis/analysis_test.go
  tools/istio-iptables/pkg/validation/vld_unix.go
Labels: size/XS, release-notes-none

#49184 kclient: do not panic on handlers after stopped
  pkg/kube/kclient/client.go
Labels: size/XS, release-notes-none

#49265 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49266 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49269 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49268 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49271 debug: include config cluster in clusterz
  pkg/kube/multicluster/secretcontroller.go
Labels: size/XS, release-notes-none

#49264 istio-cni: err loging for plugin listener exit
  cni/pkg/install/install.go
  cni/pkg/nodeagent/cni-watcher.go
Labels: area/networking, size/M, release-notes-none, area/ambient

#49274 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49275 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49261 pilot: do not skip creating istio-ca-root-cert in kube-system namespace
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  releasenotes/notes/istio-ca-root-cert-kube-system.yaml
  security/pkg/k8s/configutil.go
  security/pkg/k8s/configutil_test.go
Labels: area/environments, size/M

#49281 cni: use dedicated test tmpdir
  cni/pkg/pluginlistener/listener_test.go
Labels: size/XS, release-notes-none

#49286 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49287 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49204 OpenTelemetryTracingProvider: Allow to configure resource detectors
  pilot/pkg/networking/core/v1alpha3/tracing.go
  pilot/pkg/networking/core/v1alpha3/tracing_test.go
  pilot/pkg/xds/filters/filters.go
  releasenotes/notes/otel-tracing-provider-resource-detectors.yaml
  tests/integration/telemetry/tracing/otelcollector/testdata/otel-tracing-res-detectors.yaml
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
Labels: size/L

#49291 [release-1.20] fix: revision value should be respected for remote cluster svc/endpoint
  manifests/charts/base/templates/endpoints.yaml
  manifests/charts/base/templates/services.yaml
  manifests/charts/istiod-remote/templates/endpoints.yaml
  manifests/charts/istiod-remote/templates/services.yaml
  releasenotes/notes/remote-cluster-respect-revision.yaml
Labels: size/S, release-notes-none

#49292 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49283 architecture: add new document for controllers
  architecture/networking/controllers.md
Labels: size/M, release-notes-none

#49295 Automator: update istio/client-go@release-1.19 dependency in istio/istio@release-1.19
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49293 Fix empty ECDS with Delta XDS
  pkg/istio-agent/xds_proxy_delta.go
  pkg/istio-agent/xds_proxy_delta_test.go
Labels: size/L, release-notes-none

#49299 Automator: update ztunnel@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49303 agent: treat GOAWAY as expected
  pilot/pkg/grpc/grpc.go
Labels: size/XS, release-notes-none

#49288 Clean up old plugin tests
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/plugin.go
  cni/pkg/plugin/plugin_cni_conformance.go
  cni/pkg/plugin/plugin_dryrun_test.go
  cni/pkg/plugin/plugin_test.go
  cni/pkg/plugin/sidecar_intercept_rule_mgr.go
  cni/pkg/repair/repaircontroller.go
Labels: area/test and release, size/XXL, release-notes-none

#49304 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49305 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49306 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49258 [release-1.21] Ambient Helm Install/Upgrade Integration Tests
  pkg/test/framework/features/features.yaml
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tests/integration/helm/upgrade/util.go
  tests/integration/helm/util.go
Labels: size/L, release-notes-none

#49309 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49310 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#49311 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49312 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49314 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49308 Fix dual-stack TestIngress/status postsubmit test failure
  tests/integration/pilot/ingress_test.go
Labels: area/networking, size/S, release-notes-none, area/dual-stack

#49316 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49321 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#49255 Prepare for a Calico platform integ environment
  common/scripts/kind_provisioner.sh
  prow/config/calico.md
  prow/config/calico.yaml
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/testdata/only-hbone.yaml
Labels: size/XXL, release-notes-none, area/ambient

#49330 Fix lint errors updating linter to 1.56
  pilot/pkg/config/monitor/file_snapshot.go
  pilot/pkg/config/monitor/monitor.go
  security/pkg/pki/util/san_test.go
Labels: size/S, release-notes-none

#49325 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49329 Automator: update common-files@master in istio/istio@master
  SUPPORT.md
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#49319 Separate CNIConfig and CNIUsageConfig (see #49290)
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: area/environments, size/S, release-notes-none

#49322 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49323 Replace discuss link in FR template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/XS, release-notes-none

#49326 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49328 injection: mark cronjob as v1, as v1beta1 is removed
  pkg/kube/util.go
  pkg/kube/util_test.go
Labels: size/XS, release-notes-none

#49332 manifests: remove HPA backwards compatibility
  manifests/charts/gateways/istio-egress/templates/autoscale.yaml
  manifests/charts/gateways/istio-ingress/templates/autoscale.yaml
  manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/testdata/manifest-generate/output/autoscaling_v2beta1_k8s_and_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/deprecated_autoscaling_k8s_spec.golden.yaml
  operator/pkg/translate/translate.go
  operator/pkg/translate/translate_test.go
Labels: size/L, release-notes-none

#49337 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#49338 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49339 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49347 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49354 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49360 Automator: update proxy@release-1.19 in istio/istio@release-1.19
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49361 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49365 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#49327 [release-1.19] Run UPDATE_BRANCH=release-1.19 make update-common and fix lint
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
  tests/integration/pilot/gateway_conformance_test.go
Labels: size/XS, release-notes-none

#49307 istioctl: improve admin log flag description
  istioctl/pkg/admin/istiodconfig.go
Labels: area/user experience, size/XS, release-notes-none

#49368 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49357 Add missing descriptions to fields in values_types.proto
  manifests/charts/istio-cni/templates/daemonset.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
Labels: area/environments, ok-to-test, area/user experience, size/L, release-notes-none

#49366 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49367 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#49374 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49256 inject: detect deployment metadata for ArgoCD Rollout
  pkg/kube/util.go
  pkg/kube/util_test.go
Labels: size/M, release-notes-none

#49280 ctrlz: bind to port 0 in tests to avoid conflicts
  pkg/ctrlz/ctrlz_test.go
Labels: size/XS, release-notes-none

#49377 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#49380 Automator: update common-files@release-1.21 in istio/istio@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#49376 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#49378 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49382 Automator: update proxy@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49386 Automator: update ztunnel@release-1.21 in istio/istio@release-1.21
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49389 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#49390 Automator: update proxy@release-1.20 in istio/istio@release-1.20
  istio.deps
Labels: size/XS, auto-merge, release-notes-none
