Repository istio/istio, pull requests merged in 2025-06, with the labels that each got.

#56480 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56481 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56482 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56466 support displaying stack-trace-level for admin log
  istioctl/pkg/admin/istiodconfig.go
  releasenotes/notes/56500.yaml
Labels: area/user experience, size/S

#56485 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56486 implement merge option for LISTENER_FILTER in EnvoyFilter
  pilot/pkg/networking/core/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/envoyfilter/listener_patch_test.go
  releasenotes/notes/envoyfilter-listenerfilter-merge.yaml
Labels: area/networking, size/L

#56491 base image builder: fix script
  tools/build-base-images.sh
Labels: size/XS, release-notes-none, cherrypick/release-1.26

#56493 [release-1.26] base image builder: fix script
  tools/build-base-images.sh
Labels: size/XS, release-notes-none

#56495 Update BASE_VERSION to 1.26-2025-06-03T19-01-54
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56507 pilot-agent: no more need to raise soft limits
  pilot/cmd/pilot-agent/app/cmd.go
  pilot/cmd/pilot-agent/app/fds.go
  pilot/cmd/pilot-agent/app/fds_unix.go
Labels: size/M, release-notes-none

#56509 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56508 pilot: cleanup deadcode in features
  pilot/pkg/features/tuning.go
Labels: size/S, release-notes-none

#56510 krt: add assertions
  pkg/kube/krt/collection.go
  pkg/kube/krt/collection_test.go
  pkg/kube/krt/map.go
Labels: size/M, release-notes-none, cherrypick/release-1.26

#56499 Fix crash in merging http routes
  pilot/pkg/config/kube/gateway/route_collections.go
  pilot/pkg/config/kube/gateway/testdata/delegated.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/grpc.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/isolation.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-service.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-binding.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
  pkg/config/model.go
  pkg/kube/krt/index.go
Labels: ok-to-test, size/XL, release-notes-none, cherrypick/release-1.26

#56518 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56517 [release-1.26] Fix crash in merging http routes
  pilot/pkg/config/kube/gateway/route_collections.go
  pilot/pkg/config/kube/gateway/testdata/delegated.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/grpc.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/isolation.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-service.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-binding.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
  pkg/config/model.go
  pkg/kube/krt/index.go
Labels: size/XL, release-notes-none

#56525 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56528 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56502 remove finding of pods by IP
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/kube/controller/util.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  releasenotes/notes/pod-controller-avoid-ip-search.yaml
Labels: size/M

#55986 feat: enable support for proxy protocol on status port
  pilot/pkg/features/experimental.go
  pkg/bootstrap/config.go
  pkg/bootstrap/option/instances.go
  releasenotes/notes/envoy-status-port-proxy-protocol.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: area/networking, ok-to-test, size/M

#56537 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56539 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56540 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56543 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#56544 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56545 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56246 [release-1.24] istioctl: fix panic when there're multiple gateways
  operator/cmd/mesh/manifest-translate.go
  releasenotes/notes/56240.yaml
Labels: size/S, release-notes-none

#56551 fix gen
  samples/addons/loki.yaml
Labels: size/XS, release-notes-none

#56541 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56553 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56476 fix EnvoyFilter targetRefs match
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  releasenotes/notes/56476.yaml
  tests/integration/ambient/baseline_test.go
Labels: size/L

#56554 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56561 Automator: update istio/client-go@release-1.26 dependency in istio/istio@release-1.26
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56463 fix: The Gateway Inference Extension doesn't receive response bodies
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
  pkg/workloadapi/security/authorization_vtproto.pb.go
  pkg/workloadapi/workload_vtproto.pb.go
Labels: area/networking, ok-to-test, size/XS, release-notes-none

#56563 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56199 Fix Ambient TestWasmPluginConfigurations test for Openshift
  tests/integration/ambient/registry_setup_test.go
Labels: size/S, release-notes-none, area/ambient

#56566 Update BASE_VERSION to 1.23-2025-06-10T19-02-04
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56580 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56581 Update BASE_VERSION to master-2025-06-11T19-01-21
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56582 Update BASE_VERSION to 1.24-2025-06-11T19-02-54
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56589 [release-1.26] injection: fix sidecar template for TPROXY mode on OpenShift
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-openshift-tproxy.yaml
  pkg/kube/inject/testdata/inject/hello-openshift-tproxy.yaml.injected
  releasenotes/notes/56577.yaml
Labels: size/L

#56593 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56596 Control Gateway API deploy in integration tests
  pkg/test/framework/components/crd/gateway.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  tests/integration/README.md
Labels: area/test and release, size/S, release-notes-none

#56625 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56606 [release-1.26] Control Gateway API deploy in integration tests
  pkg/test/framework/components/crd/gateway.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  tests/integration/README.md
Labels: size/S, release-notes-none

#56599 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56631 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56634 fix: fixes flaky 'invalid crl' test case
  security/pkg/pki/util/keycertbundle_test.go
Labels: area/security, size/XS, release-notes-none

#56646 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56635 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56649 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56643 Update istioctl x describe examples and remove dead code.
  istioctl/pkg/describe/describe.go
Labels: kind/docs, ok-to-test, size/S, release-notes-none

#56627 Use __rate_interval in grafana dashboards instead of hardcoded 1m and 5m intervals
  manifests/addons/dashboards/istio-service-dashboard.json
  manifests/addons/dashboards/istio-workload-dashboard.json
  manifests/addons/dashboards/lib/queries.libsonnet
  manifests/addons/dashboards/pilot-dashboard.gen.json
  samples/addons/grafana.yaml
Labels: area/extensions and telemetry, ok-to-test, size/XL, release-notes-none

#56623 gw-inference: support new envoy override_host lb policy
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  pkg/wellknown/wellknown.go
Labels: area/networking, size/L

#56629 126/krt assert
  pkg/kube/krt/collection.go
Labels: size/S, release-notes-none

#56653 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56655 cleanup and tests for inference-lb-policy
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
Labels: area/networking, size/L

#56498 Removes unnecessary interaction with compartments
  cni/pkg/iptables/iptables.go
  cni/pkg/iptables/iptables_e2e_linux_test.go
  cni/pkg/iptables/iptables_linux.go
  cni/pkg/iptables/iptables_test.go
  cni/pkg/iptables/iptables_windows.go
  cni/pkg/nodeagent/net_linux.go
  cni/pkg/nodeagent/net_windows.go
  cni/pkg/nodeagent/pod_cache_windows.go
Labels: size/M, area/ambient, windows/ambient

#56666 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56668 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56669 Automator: update common-files@release-1.25 in istio/istio@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56677 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56676 fix injection template for ClusterTrustBundle
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
Labels: area/environments, size/S, release-notes-none

#56645 Enhance `genHTMLFragment` to Include Anchor Tags in Environment Variable Table Output
  pkg/collateral/control.go
Labels: kind/docs, size/S, release-notes-none

#56683 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56684 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56689 [release-1.26] Ambient: In ambient index, filter configs by revision (#56477)
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
  releasenotes/notes/56477.yaml
Labels: size/L

#56693 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56694 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#56699 Update BASE_VERSION to master-2025-06-19T19-00-49
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56700 Update BASE_VERSION to 1.25-2025-06-19T19-01-37
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56702 Update BASE_VERSION to 1.26-2025-06-19T19-01-24
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56701 Update BASE_VERSION to 1.24-2025-06-19T19-02-14
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#56708 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56696 [release-1.26] Improve ingress address resolution in integration tests flow
  pkg/test/framework/components/istio/ingress.go
Labels: size/M, release-notes-none

#56713 [release-1.25] Ambient: In ambient index, filter configs by revision (#56477) (#56689)
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
  pkg/kube/kubetypes/types.go
  releasenotes/notes/56477.yaml
Labels: size/L

#56685 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56718 Automator: update istio/client-go@release-1.26 dependency in istio/istio@release-1.26
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56722 Automator: update ztunnel@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56717 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56725 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56727 support ClusterTrustBundle to v1beta1 API
  pilot/pkg/config/kube/clustertrustbundle/controller.go
  pilot/pkg/config/kube/clustertrustbundle/controller_test.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  releasenotes/notes/56306.yaml
Labels: area/security, size/M

#55604 wasmplugin: Allow configuration of fail reload strategy
  pilot/pkg/model/extensions.go
  pilot/pkg/model/extensions_test.go
  releasenotes/notes/wasm-fail-reload.yaml
Labels: area/extensions and telemetry, ok-to-test, size/S

#56695 Fix prepetual out of sync status within argocd
  manifests/charts/istio-cni/templates/daemonset.yaml
  releasenotes/notes/56695.yaml
Labels: area/environments, ok-to-test, size/XS, area/ambient

#56656 Refactor inference extension support to krt
  istio.deps
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/gateway_collection.go
  pilot/pkg/config/kube/gateway/inferencepool.go
  pilot/pkg/config/kube/gateway/inferencepool_collection.go
  pilot/pkg/config/kube/gateway/inferencepool_test.go
  pilot/pkg/config/kube/gateway/route_collections.go
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/status/collections.go
  pilot/pkg/status/manager.go
  pkg/config/model.go
  pkg/kube/client.go
Labels: size/XXL, release-notes-none

#56736 Remove unused multiCluster values
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  releasenotes/notes/remove-extra-multicluster-helm-values.yaml
Labels: size/M

#56737 ensure consistency in inject label validation
  pkg/kube/inject/inject.go
  pkg/kube/inject/webhook_test.go
Labels: area/test and release, size/M, release-notes-none

#56738 CNI Pod delete edge case
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/net_linux.go
  releasenotes/notes/56738.yaml
Labels: area/networking, size/S, area/ambient, cherrypick/release-1.25, cherrypick/release-1.26

#56742 Add support for OPTIONAL_MUTUAL to Gateway API
  pilot/pkg/config/kube/gateway/conversion.go
Labels: area/networking, area/security, ok-to-test, size/XS, release-notes-none

#56395 Multicluster AmbientIndex
  pilot/pkg/bootstrap/server.go
  pilot/pkg/grpc/tls.go
  pilot/pkg/networking/core/fake.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/collectioncache.go
  pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
  pilot/pkg/serviceregistry/kube/controller/ambient/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go
  pilot/pkg/serviceregistry/kube/controller/ambient/multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/networks.go
  pilot/pkg/serviceregistry/kube/controller/ambient/nodes.go
  pilot/pkg/serviceregistry/kube/controller/ambient/remotesecrets.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/network_test.go
  pilot/pkg/serviceregistry/util/xdsfake/updater.go
  pkg/config/model.go
  pkg/kube/client.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/core.go
  pkg/kube/krt/debug.go
  pkg/kube/krt/dynamic.go
  pkg/kube/krt/helpers.go
  pkg/kube/krt/informer_test.go
  pkg/kube/krt/join.go
  pkg/kube/krt/join_test.go
  pkg/kube/krt/map.go
  pkg/kube/krt/nestedjoin.go
  pkg/kube/krt/nestedjoin_test.go
  pkg/kube/krt/options.go
  pkg/kube/krt/processor.go
  pkg/kube/krt/singleton.go
  pkg/kube/multicluster/secretcontroller.go
  pkg/kube/multicluster/secretcontroller_test.go
  tests/binary/binaries_test.go
  tests/integration/README.md
  tests/integration/ambient/baseline_test.go
Labels: size/XXL, release-notes-none, area/ambient

#56141 feat: represent revision tags using services
  istioctl/pkg/tag/generate.go
  istioctl/pkg/tag/generate_test.go
  istioctl/pkg/tag/tag.go
  istioctl/pkg/tag/tag_test.go
  istioctl/pkg/tag/util.go
  manifests/charts/istio-control/istio-discovery/templates/revision-tags-mwc.yaml
  manifests/charts/istio-control/istio-discovery/templates/revision-tags-svc.yaml
  operator/pkg/install/install.go
  operator/pkg/webhook/webhook.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pkg/revisions/tag_watcher.go
  pkg/revisions/tag_watcher_test.go
  releasenotes/notes/revision-tags-as-svc.yaml
  tests/integration/helm/util.go
Labels: area/environments, ok-to-test, area/user experience, size/XXL, area/ambient

#56746 [release-1.26] fix clustertrustbundles rbac
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: size/XS, release-notes-none

#56747 [release-1.26] fix clusterTrustBundle template
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
Labels: size/S, release-notes-none

#56748 add release notes for ClusterTrustBundle
  releasenotes/notes/cluster-trust-bundle.yaml
Labels: size/XS, cherrypick/release-1.26

#56785 [release-1.26] add release notes for ClusterTrustBundle
  releasenotes/notes/cluster-trust-bundle.yaml
Labels: size/XS, release-notes-none

#56784 Add domain resolve to Ambient TestServiceEntryInlinedWorkloadEntry test
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none, area/ambient

#56788 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56789 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56637 Do not transitively import net/trace
  Makefile.core.mk
  go.mod
  go.sum
  licenses/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE
  pkg/security/retry.go
Labels: size/L, release-notes-none

#56687 do not use discovery filter for system namespace network
  pilot/pkg/serviceregistry/kube/controller/controller.go
  releasenotes/notes/56687.yaml
Labels: area/networking, size/S, area/ambient, cherrypick/release-1.25, cherrypick/release-1.26

#56798 status: fix busyloop
  pilot/pkg/status/resourcelock.go
  pilot/pkg/status/resourcelock_test.go
Labels: size/M, release-notes-none, cherrypick/release-1.26

#56809 manifests: refactor conditions for tproxy and capNetBindService
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
Labels: area/environments, size/XS, release-notes-none

#56812 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56806 fix dns althost name generation
  pkg/dns/client/dns.go
  pkg/dns/client/dns_test.go
Labels: size/XS, release-notes-none

#56813 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56787 Add annotation support to deployment object in istio discovery chart
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  releasenotes/notes/istiod-chart-deployment-annotations-support.yaml
Labels: ok-to-test, size/S

#56821 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56822 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56823 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56832 feat(gw-inference): Add support for InferencePool reference grants
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/references_collection.go
  pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.yaml
  pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.yaml.golden
Labels: ok-to-test, size/L

#56792 Inference pool Status handling and cross namespace references
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/inferencepool_collection.go
  pilot/pkg/config/kube/gateway/inferencepool_status_test.go
Labels: ok-to-test, size/XL

#56835 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none
