Repository istio/istio, pull requests merged in 2025-01, with the labels that each got.

#54508 ambient: optimize for single registry case
  pilot/pkg/serviceregistry/aggregate/controller.go
Labels: size/M, release-notes-none

#54510 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54511 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54504 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54517 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54523 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54519 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54527 Increase timeout on benchmark test
  prow/benchtest.sh
Labels: size/XS, release-notes-none

#54532 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54531 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54520 Replace Eric with keithmattix for top level ownership
  CODEOWNERS
Labels: size/XS, release-notes-none

#54534 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54501 Use vtproto to encode gRPC messages
  pilot/pkg/xds/delta.go
  pkg/util/protomarshal/grpc.go
Labels: size/M, release-notes-none

#54500 More WDS to use vtprotobuf
  go.mod
  pilot/pkg/model/service.go
  pilot/pkg/util/protoconv/protoconv.go
  pkg/workloadapi/fuzz_test.go
  pkg/workloadapi/security/authorization_vtproto.pb.go
  pkg/workloadapi/workload_vtproto.pb.go
  tools/proto/buf.golang-json.yaml
Labels: size/M, release-notes-none

#54484 istioctl: remove long experimental flag --xds-via-agents
  istioctl/pkg/multixds/gather.go
  istioctl/pkg/proxystatus/proxystatus.go
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/agent_test.go
  pkg/istio-agent/tap_proxy.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
  releasenotes/notes/istioctl-xds-piggyback.yaml
  tests/integration/pilot/piggyback_test.go
Labels: size/XL, release-notes-none

#54512 adopt envoy.extensions.wasm.v3.PluginConfig.fail_policy
  pilot/pkg/model/extensions.go
  pilot/pkg/model/extensions_test.go
  pilot/pkg/networking/core/extension/wasmplugin.go
  pilot/pkg/networking/core/extension/wasmplugin_test.go
  pilot/pkg/networking/core/extension_config_builder.go
  pkg/wasm/convert.go
Labels: size/L, release-notes-none

#54542 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54541 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54464 xds: move ResourceNames to a set
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/grpcgen/grpcgen.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/debuggen.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/deltatest.go
  pilot/pkg/xds/ecds.go
  pilot/pkg/xds/ecds_test.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/nds_test.go
  pilot/pkg/xds/rds.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  pilot/pkg/xds/statusgen.go
  pilot/pkg/xds/workload.go
  pilot/pkg/xds/workload_test.go
  pilot/pkg/xds/xdsgen.go
  pkg/util/sets/set.go
  pkg/xds/server.go
  pkg/xds/server_test.go
  security/pkg/nodeagent/sds/sdsservice.go
Labels: size/L, release-notes-none

#54547 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54546 [release-1.24] Update path template validation for AuthzPolicy
  pkg/config/security/security.go
  pkg/config/security/security_test.go
  tests/integration/security/authz_test.go
Labels: size/L, release-notes-none

#54462 [release-1.22] PeerAuthentication Merging for Ambient (#54073)
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-strict-namespace-permissive-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-strict-namespace-permissive-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-namespace-strict-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-namespace-strict-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-unset-port-mtls-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-unset-port-mtls-permissive.yaml
  releasenotes/notes/53884.yaml
  tests/integration/ambient/baseline_test.go
Labels: size/L

#54461 [release-1.23] PeerAuthentication Merging for Ambient (#54073)
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-strict-namespace-permissive-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-strict-namespace-permissive-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-namespace-strict-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-namespace-strict-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-workload-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-permissive-workload.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-unset-port-mtls-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-unset-port-mtls-permissive.yaml
  releasenotes/notes/53884.yaml
  tests/integration/README.md
  tests/integration/ambient/baseline_test.go
Labels: size/XL

#54552 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54550 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
  operator/pkg/apis/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/workload.pb.go
  pkg/zdsapi/zds.pb.go
Labels: size/XS, auto-merge, release-notes-none

#54549 Benchmark WDS
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/testdata/benchmarks/serviceentry-workloadentry.yaml
Labels: size/M, release-notes-none

#54554 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54558 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54559 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54555 remove expensive sprintf in configs updated
  pilot/pkg/xds/discovery.go
Labels: size/XS, release-notes-none

#54556 fix test flake
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: size/XS, release-notes-none

#54451 unify xds push needed checks
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/xds/cds.go
  pilot/pkg/xds/ecds.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/lds.go
  pilot/pkg/xds/nds.go
  pilot/pkg/xds/nds_test.go
  pilot/pkg/xds/rds.go
  pilot/pkg/xds/xdsgen.go
Labels: size/L, release-notes-none

#54521 Ambient: Add pre-marshalling of xds
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/xds/workload.go
Labels: size/L, release-notes-none

#54560 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54563 delta xds: fix regression in pushing on unsubscribe
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/util_test.go
  pkg/util/sets/set.go
Labels: size/L, release-notes-none

#54507 Refactor Telemetry tests "IsKindCluster" function
  pkg/test/framework/components/cluster/clusters.go
  tests/integration/telemetry/api/customize_metrics_test.go
  tests/integration/telemetry/api/registry_setup_test.go
  tests/integration/telemetry/api/setup_test.go
Labels: area/extensions and telemetry, ok-to-test, size/M, release-notes-none

#54565 Handle out-of-order ztunnel connection removals correctly.
  cni/pkg/nodeagent/server.go
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/nodeagent/ztunnelserver_test.go
  releasenotes/notes/54565.yaml
Labels: size/L, area/upgrade, area/ambient

#54566 Fix Ambient Peer Authn flake
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive.yaml
  releasenotes/notes/54146.yaml
  tests/integration/ambient/baseline_test.go
Labels: size/L, area/ambient, cherrypick/release-1.22, cherrypick/release-1.23, cherrypick/release-1.24

#54569 [release-1.24] Handle out-of-order ztunnel connection removals correctly.
  cni/pkg/nodeagent/server.go
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/nodeagent/ztunnelserver_test.go
  releasenotes/notes/54565.yaml
Labels: size/L, release-notes-none

#54577 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#54579 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54567 [release-1.23] Update path template validation for AuthzPolicy
  pkg/config/security/security.go
  pkg/config/security/security_test.go
  tests/integration/security/authz_test.go
Labels: size/L, release-notes-none

#54118 Resolve JWKS Resolver TOCTOU Race Conditions
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/model/jwks_resolver_test.go
  releasenotes/notes/54118.yaml
Labels: ok-to-test, size/L

#54513 proxy network label should be set based on pod labels, system namespa…
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder_test.go
  pilot/pkg/serviceregistry/util/label/label.go
Labels: size/L, release-notes-none

#54583 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#54584 Sort portlevel mtls before converting
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pkg/maps/maps.go
Labels: size/S, release-notes-none, area/ambient

#54585 Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: area/networking, area/security, ok-to-test, size/XS, release-notes-none

#54573 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54578 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54564 ambient: drop dedupe of workloads
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/L, release-notes-none

#54600 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54594 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#54603 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54605 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54606 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54612 (fix): align gateway condition key usage
  pilot/pkg/config/kube/gateway/conversion.go
Labels: ok-to-test, size/XS, release-notes-none

#54604 Fix shared state access causing test flakes
  tests/integration/ambient/baseline_test.go
Labels: area/test and release, size/S, release-notes-none

#54628 tests: fix flake in TestNewServerCertInit
  pilot/pkg/bootstrap/server_test.go
Labels: size/XS, release-notes-none

#54616 [release-1.24] Fix Ambient Peer Authn flake (#54566)
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive.yaml
  releasenotes/notes/54146.yaml
  tests/integration/ambient/baseline_test.go
Labels: size/L

#54439 Mostly cosmetic tidies split out from #53906
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/server.go
  cni/pkg/util/podutil.go
Labels: size/L, release-notes-none, area/ambient

#54617 [release-1.23] Fix Ambient Peer Authn flake (#54566)
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive.yaml
  releasenotes/notes/54146.yaml
  tests/integration/ambient/baseline_test.go
Labels: size/L

#54632 Automator: update common-files@release-1.24 in istio/istio@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54624 [release-1.24] Fix shared state access causing test flakes
  tests/integration/ambient/baseline_test.go
Labels: size/S, release-notes-none

#54633 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54634 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54505 return early in ip allocator controller when service entry status is updated
  pilot/pkg/controllers/ipallocate/ipallocate.go
Labels: size/S, release-notes-none

#54610 Prevent iptables GetStateFromSave from processing lines related to non-built-in tables
  releasenotes/notes/fix-iptables-state-custom-table.yaml
  tools/istio-iptables/pkg/builder/iptables_builder_impl.go
  tools/istio-iptables/pkg/builder/iptables_builder_test.go
Labels: area/networking, size/L, cherrypick/release-1.24

#54639 [release-1.24] Prevent iptables GetStateFromSave from processing lines related to non-built-in tables
  releasenotes/notes/fix-iptables-state-custom-table.yaml
  tools/istio-iptables/pkg/builder/iptables_builder_impl.go
  tools/istio-iptables/pkg/builder/iptables_builder_test.go
Labels: size/L, release-notes-none

#54642 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54638 Promote ambient DNS capture
  manifests/charts/base/files/profile-compatibility-version-1.24.yaml
  manifests/charts/default/files/profile-compatibility-version-1.24.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.24.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.24.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.24.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.24.yaml
  manifests/charts/istio-cni/values.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.24.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.24.yaml
  manifests/helm-profiles/compatibility-version-1.24.yaml
  releasenotes/notes/ambient-dns-on.yaml
Labels: size/S

#54646 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54557 telemetry: support additional labels in metadata exchange
  pilot/pkg/features/telemetry.go
  pilot/pkg/networking/core/gateway_test.go
  pilot/pkg/xds/filters/filters.go
  pilot/pkg/xds/filters/filters_test.go
  releasenotes/notes/54000.yaml
  tests/integration/telemetry/api/setup_test.go
  tests/integration/telemetry/api/stats_test.go
  tests/integration/telemetry/api/testdata/additional-labels.yaml
Labels: area/extensions and telemetry, size/XL

#54653 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54658 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54651 Check equality of ports in Gateway conflict check
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/gateway/conflictinggateway.go
  pkg/config/analysis/analyzers/testdata/conflicting-gateways-multiple-ports.yaml
  pkg/config/analysis/analyzers/testdata/gateway-different-port.yaml
  releasenotes/notes/54643.yaml
Labels: ok-to-test, size/L, release-notes-none, area/upgrade

#54660 Remove unused iptable restore constants
  tools/istio-iptables/pkg/dependencies/implementation.go
Labels: size/S, release-notes-none

#53887 Preserve HTTP 1 Header Case
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_cache.go
  pilot/pkg/networking/core/listener_builder.go
  releasenotes/notes/preserve-http1-header-case.yaml
  tests/integration/pilot/preserve_http_header_case_test.go
Labels: area/networking, size/L

#54670 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54307 Allow waypoints servers to support hostnames in routing
  pilot/pkg/features/ambient.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/match/match.go
  pilot/pkg/xds/filters/filters.go
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/main_test.go
Labels: size/L, release-notes-none, area/ambient

#54673 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54680 make accesslog order stable
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  releasenotes/notes/54680.yaml
Labels: area/extensions and telemetry, size/S, cherrypick/release-1.22, cherrypick/release-1.23, cherrypick/release-1.24

#54681 [release-1.22] make accesslog order stable
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  releasenotes/notes/54680.yaml
Labels: size/S, release-notes-none

#54682 [release-1.23] make accesslog order stable
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  releasenotes/notes/54680.yaml
Labels: size/S, release-notes-none

#54683 [release-1.24] make accesslog order stable
  pilot/pkg/model/telemetry.go
  pilot/pkg/model/telemetry_logging_test.go
  releasenotes/notes/54680.yaml
Labels: size/S, release-notes-none

#54686 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54688 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54691 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54692 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54551 krt: optimize lookups in Join
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
Labels: size/L, release-notes-none

#54601 ambient: do not full push for WDS when we don't need to
  pilot/pkg/model/push_context.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/workload.go
Labels: size/L, release-notes-none

#54695 Switch this back so we don't create it unless remotePilotAddress is set
  manifests/charts/istio-control/istio-discovery/templates/remote-istiod-service.yaml
Labels: area/environments, size/XS, feature/Multi-cluster, release-notes-none

#54421 [Dual-stack] Introduce IP_FAMILIES for integration tests
  common/scripts/kind_provisioner.sh
  pkg/test/framework/components/echo/common/deployment/echos.go
  pkg/test/framework/components/echo/common/deployment/external.go
  pkg/test/framework/components/echo/common/deployment/namespace.go
  pkg/test/framework/components/echo/deployment/builder.go
  pkg/test/framework/components/istio/kube.go
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  pkg/test/framework/suite.go
  pkg/test/framework/test.go
  prow/integ-suite-kind.sh
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/gateway_test.go
  tests/integration/security/policy_attachment_only/main_test.go
  tests/integration/security/reachability_test.go
  tests/integration/tests.mk
Labels: area/networking, size/L, release-notes-none, area/dual-stack

#54698 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#53998 Sidecar iptables cruft removal, handle DNS chains better.
  cni/pkg/iptables/iptables.go
  cni/pkg/plugin/testdata/basic.txt.golden
  cni/pkg/plugin/testdata/custom-uid-tproxy.txt.golden
  cni/pkg/plugin/testdata/custom-uid.txt.golden
  cni/pkg/plugin/testdata/dns.txt.golden
  cni/pkg/plugin/testdata/include-exclude-ip.txt.golden
  cni/pkg/plugin/testdata/include-exclude-ports.txt.golden
  cni/pkg/plugin/testdata/invalid-drop.txt.golden
  cni/pkg/plugin/testdata/tproxy.txt.golden
  pkg/kube/inject/webhook.go
  releasenotes/notes/53998.yaml
  tools/istio-iptables/pkg/builder/iptables_builder_impl.go
  tools/istio-iptables/pkg/builder/iptables_builder_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/capture/run_test.go
  tools/istio-iptables/pkg/capture/testdata/basic-exclude-nic.golden
  tools/istio-iptables/pkg/capture/testdata/dns-uid-gid.golden
  tools/istio-iptables/pkg/capture/testdata/drop-invalid.golden
  tools/istio-iptables/pkg/capture/testdata/empty.golden
  tools/istio-iptables/pkg/capture/testdata/host-ipv4-loopback-cidr.golden
  tools/istio-iptables/pkg/capture/testdata/inbound-ports-include.golden
  tools/istio-iptables/pkg/capture/testdata/inbound-ports-tproxy.golden
  tools/istio-iptables/pkg/capture/testdata/inbound-ports-wildcard-tproxy.golden
  tools/istio-iptables/pkg/capture/testdata/inbound-ports-wildcard.golden
  tools/istio-iptables/pkg/capture/testdata/ip-range.golden
  tools/istio-iptables/pkg/capture/testdata/ipnets-with-kube-virt-interfaces.golden
  tools/istio-iptables/pkg/capture/testdata/ipnets.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups-exclude.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-dns-uid-gid.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-empty-inbound-ports.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-inbound-ports.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-ipnets.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-outbound-ports.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-uid-gid.golden
  tools/istio-iptables/pkg/capture/testdata/ipv6-virt-interfaces.golden
  tools/istio-iptables/pkg/capture/testdata/kube-virt-interfaces.golden
  tools/istio-iptables/pkg/capture/testdata/logging.golden
  tools/istio-iptables/pkg/capture/testdata/loopback-outbound-iprange.golden
  tools/istio-iptables/pkg/capture/testdata/outbound-owner-groups-exclude.golden
  tools/istio-iptables/pkg/capture/testdata/outbound-owner-groups.golden
  tools/istio-iptables/pkg/capture/testdata/outbound-ports-include.golden
  tools/istio-iptables/pkg/capture/testdata/tproxy.golden
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/log/command.go
  tools/istio-iptables/pkg/log/nflog.go
Labels: area/networking, size/XXL

#54699 [release-1.23] Backport release note for missed behavior change #54699
  releasenotes/notes/retroactive-note-for-53949.yaml
Labels: size/S

#54678 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54701 spire: fixup sample
  samples/security/spire/istio-spire-config.yaml
Labels: size/XS, release-notes-none

#54667 Do not impersonate empty group
  istioctl/pkg/cli/option.go
  istioctl/pkg/cli/option_test.go
  releasenotes/notes/54667.yaml
Labels: ok-to-test, area/user experience, size/M

#54709 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54714 Gateway also needs global flattening
  Makefile.core.mk
  manifests/charts/gateway/templates/zzz_profile.yaml
  releasenotes/notes/54714.yamml
Labels: size/S, cherrypick/release-1.24

#54717 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54713 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54711 PILOT_SEND_UNHEALTHY_ENDPOINTS: exclude terminating endpoints
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  pkg/dns/server/name_table.go
  pkg/dns/server/name_table_test.go
  releasenotes/notes/endpoint-termination.yaml
Labels: size/M

#54697 Be more explicit about how Helm value deprecations should manifest in relnotes
  manifests/charts/UPDATING-CHARTS.md
Labels: area/user experience, size/XS, release-notes-none, area/upgrade

#54716 [release-1.24] Gateway also needs global flattening
  Makefile.core.mk
  manifests/charts/gateway/templates/zzz_profile.yaml
  releasenotes/notes/54714.yamml
Labels: size/S, release-notes-none

#54728 run make gen
  operator/pkg/apis/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/workload.pb.go
  pkg/zdsapi/zds.pb.go
Labels: size/XS, release-notes-none

#54733 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54483 ambient: support `istio.io/ingress-use-waypoint` at the namespace level
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  releasenotes/notes/ingress-use-waypoint-namespace.yaml
Labels: size/M, release-notes-none

#54727 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54742 Enable modifying the prow cluster name
  prow/integ-suite-kind.sh
Labels: size/XS, release-notes-none

#54749 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54753 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54754 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54744 istioctl: support SA RBAC rule parsing
  istioctl/pkg/writer/ztunnel/configdump/api.go
  istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
  istioctl/pkg/writer/ztunnel/configdump/testdata/policies.txt
Labels: size/L, release-notes-none

#54755 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54758 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54767 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54768 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54677 ambient: move networks logic to native krt
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
  pilot/pkg/serviceregistry/kube/controller/ambient/networks.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/network_test.go
  tests/binary/binaries_test.go
Labels: size/L, release-notes-none

#54772 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54773 Clean up forked ingress config controller comments
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ingress/conversion.go
Labels: area/networking, size/S, release-notes-none

#54774 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54738 add support for a new Envoy command-line option to skip deprecated logs
  pilot/cmd/pilot-agent/app/cmd.go
  pilot/cmd/pilot-agent/options/agent.go
  pilot/cmd/pilot-agent/options/options.go
  pkg/bootstrap/config.go
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
  pkg/istio-agent/agent.go
  pkg/model/proxy.go
  releasenotes/notes/54738.yaml
Labels: ok-to-test, size/M

#54751 minor optimization in service entry controller
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/serviceregistry/serviceentry/store.go
Labels: size/S, release-notes-none

#54778 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54732 Allow SIMPLE TLS origination without secret read acces
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
Labels: size/M, release-notes-none

#54769 Include krtz in bug-report
  tools/bug-report/pkg/common/common.go
Labels: size/XS, release-notes-none

#54787 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54788 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54795 Fix accesslog format incompatibility between 1.23 istiod and <1.23 proxies
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/networking/core/accesslog.go
  releasenotes/notes/54795.yaml
Labels: area/networking, area/extensions and telemetry, size/M

#54796 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54465 Add tagged gateways to status and XDS
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/model/push_context.go
  pkg/config/model.go
  pkg/revisions/leak_test.go
  pkg/revisions/tag_watcher.go
  releasenotes/notes/54458.yaml
  tests/integration/pilot/gateway_test.go
Labels: area/user experience, size/L, area/ambient

#54316 kclient: apply client side filter to index result
  pkg/kube/kclient/client.go
  pkg/kube/kclient/index.go
  pkg/kube/kclient/index_test.go
Labels: size/L, release-notes-none

#54745 AuthorizationPolicy serviceAccount: allow same namespace
  pilot/pkg/networking/grpcgen/lds.go
  pilot/pkg/security/authz/builder/builder.go
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-in.yaml
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
  pilot/pkg/security/authz/builder/testdata/http/extended-allow-full-rule-out.yaml
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
  pilot/pkg/security/authz/model/model.go
  pilot/pkg/security/authz/model/model_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/allow-full-in.yaml
  pilot/pkg/serviceregistry/kube/controller/ambient/testdata/allow-full.yaml
  pkg/config/security/security.go
  pkg/config/security/security_test.go
Labels: size/L, release-notes-none

#54807 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54806 Use preserveHeaderCase when calculating cache key
  pilot/pkg/networking/core/cluster_cache.go
Labels: area/networking, size/XS, release-notes-none

#54729 ambient: Properly support add/remove retries
  cni/pkg/cmd/root.go
  cni/pkg/nodeagent/error.go
  cni/pkg/nodeagent/informers.go
  cni/pkg/nodeagent/informers_test.go
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/net_test.go
  cni/pkg/nodeagent/server.go
  cni/pkg/nodeagent/server_test.go
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/util/podutil.go
  pkg/config/constants/constants.go
Labels: size/XL, release-notes-none, area/ambient, cherrypick/release-1.25

#54786 Use resolv.conf for getting the zone
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
Labels: size/L, release-notes-none, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#54798 Use the commmon label 'pod' instead of 'pod_name' as label in PodMonitor
  samples/addons/extras/prometheus-operator.yaml
Labels: kind/docs, area/environments, ok-to-test, area/user experience, size/XS, release-notes-none

#54715 Support TrafficDistribution for Envoy
  pilot/pkg/features/experimental.go
  pilot/pkg/model/endpointshards.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
  pilot/pkg/networking/core/cluster_waypoint.go
  pilot/pkg/networking/core/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/loadbalancer/loadbalancer_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  releasenotes/notes/traffic-distribution.yaml
  tests/integration/pilot/locality_test.go
Labels: size/L

#54765 ambient: fix ingress-use-waypoint with ServiceEntry
  pilot/pkg/model/service.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  pilot/pkg/xds/waypoint_test.go
Labels: size/M, release-notes-none, cherrypick/release-1.24

#54785 ambient: refactor internal transports
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/networking/core/cluster_waypoint.go
  pilot/pkg/networking/util/internal_upstream.go
Labels: size/M, release-notes-none

#54803 Drop go-control-plane and rely on subpackages
  common/config/.golangci.yml
  go.mod
  go.sum
  licenses/github.com/envoyproxy/go-control-plane/contrib/LICENSE
  licenses/github.com/envoyproxy/go-control-plane/envoy/LICENSE
  manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/convert.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent.proxycfg
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/config/xds/filter_types.gen.go
  pkg/config/xds/filter_types.go
  tools/packaging/common/envoy_bootstrap.json
Labels: size/XL, release-notes-none

#54823 Fix unit test flake
  cni/pkg/nodeagent/informers_test.go
Labels: size/S, release-notes-none, area/ambient

#54825 By default, exclude gateways from ambient mesh enrollment
  manifests/charts/gateway/values.yaml
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  releasenotes/notes/54825.yaml
Labels: size/M, area/ambient

#54826 ambient: fix caching of HBONE access log filter
  pilot/pkg/networking/core/accesslog.go
Labels: size/XS, release-notes-none

#54671 Refactor RunX cmds for istio-iptables into a single API
  cni/pkg/iptables/iptables.go
  releasenotes/notes/54644.yaml
  tools/istio-iptables/pkg/capture/helper.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_test.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
  tools/istio-iptables/pkg/dependencies/implementation_unspecified.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: area/networking, area/user experience, size/L, cherrypick/release-1.25

#54804 go-control-plane: only depend on protos
  go.mod
  licenses/github.com/envoyproxy/go-control-plane/LICENSE
  pilot/pkg/networking/core/accesslog_test.go
  pilot/pkg/networking/core/listener_test.go
  pilot/test/xdstest/extract.go
  pkg/adsc/adsc.go
  pkg/adsc/delta.go
  pkg/adsc/delta_test.go
  pkg/bootstrap/option/convert.go
  pkg/config/xds/filter_types.go
  pkg/config/xds/filters.go
  pkg/util/protomarshal/protomarshal.go
  pkg/wasm/convert.go
  pkg/wasm/convert_test.go
  tests/binary/dependencies_test.go
Labels: size/L, release-notes-none

#54829 Add release note from #54803
  releasenotes/notes/opencensus-removal.yaml
Labels: size/S

#54830 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none
