Repository istio/istio, pull requests merged in 2025-03, with the labels that each got.

#55315 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55320 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55319 addons: Bump addons version
  manifests/addons/gen.sh
  samples/addons/kiali.yaml
  samples/addons/prometheus.yaml
Labels: size/M, release-notes-none

#55322 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55321 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55317 istioctl: fix bug for internl-debug
  istioctl/pkg/internaldebug/internal-debug.go
  istioctl/pkg/multixds/gather.go
Labels: area/user experience, size/S, release-notes-none

#55327 improve istioctl waypoint status example format
  istioctl/pkg/waypoint/waypoint.go
Labels: size/XS, release-notes-none

#55183 krt/kclient: Allow removing handlers
  pkg/config/mesh/meshwatcher/mesh.go
  pkg/config/mesh/meshwatcher/mesh_test.go
  pkg/config/mesh/meshwatcher/networks.go
  pkg/kube/kclient/client.go
  pkg/kube/kclient/client_test.go
  pkg/kube/kclient/delayed.go
  pkg/kube/kclient/interfaces.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/conformance_test.go
  pkg/kube/krt/core.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/processor.go
  pkg/kube/krt/singleton.go
  pkg/kube/krt/static.go
Labels: size/L, release-notes-none

#55325 Fix Telemetry Tracint flaky tests failures
  pkg/test/framework/components/zipkin/kube.go
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
  tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
Labels: area/extensions and telemetry, ok-to-test, size/S, release-notes-none

#55312 gateway: add a new missed test cases for missing references
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
Labels: size/L, release-notes-none

#55332 Drop obsolete alias-for Gateway
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/model.go
  pilot/pkg/config/kube/gateway/testdata/alias.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/alias.yaml
  pilot/pkg/config/kube/gateway/testdata/alias.yaml.golden
Labels: size/L, release-notes-none

#55335 bump min k8s version to 1.29
  istioctl/pkg/install/k8sversion/version.go
  istioctl/pkg/install/k8sversion/version_test.go
Labels: size/S, release-notes-none, cherrypick/release-1.25

#55304 If k8s credentials expired, do not block our own `istio-cni` pod
  .gitignore
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/cniconfig.go
  cni/pkg/install/cniconfig_test.go
  cni/pkg/install/testdata/bridge.conf.golden
  cni/pkg/install/testdata/istio-cni.conf
  cni/pkg/install/testdata/list-with-istio.conflist.golden
  cni/pkg/install/testdata/list.conflist.golden
  cni/pkg/plugin/plugin.go
  cni/test/testdata/expected/10-calico.conflist-istioconfig
  cni/test/testdata/expected/YYY-istio-cni.conf
  cni/test/testdata/expected/minikube_cni.conflist.expected
  go.mod
  go.sum
  licenses/gopkg.in/natefinch/lumberjack.v2/LICENSE
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  pkg/log/options.go
  pkg/log/uds.go
  releasenotes/notes/55304.yaml
Labels: size/L, area/ambient

#55229 Expand Cilium detection to handle kube-proxy-replacement and socket LB checks
  operator/pkg/apis/validation/validation.go
  operator/pkg/apis/validation/validation_test.go
Labels: ok-to-test, size/M, feature/Multi-cluster, release-notes-none

#55338 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55340 controllers: pass name through to kubernetes queue
  pkg/kube/controllers/queue.go
Labels: size/S, release-notes-none

#55000 multus: fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array
  pkg/kube/inject/template.go
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml.injected
Labels: area/networking, size/S, release-notes-none, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#55353 [release-1.24] multus: fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array
  pkg/kube/inject/template.go
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml.injected
Labels: size/S, release-notes-none

#55354 [release-1.25] multus: fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array
  pkg/kube/inject/template.go
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml.injected
Labels: size/S, release-notes-none

#55357 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55360 Fix ztunnel service account name
  manifests/charts/ztunnel/templates/daemonset.yaml
Labels: area/environments, area/networking, ok-to-test, size/XS, release-notes-none, area/ambient

#55362 Update BASE_VERSION to 1.25-2025-03-04T19-01-37
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55361 Update BASE_VERSION to 1.24-2025-03-04T19-01-29
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55351 bump go-jose to 4.0.5
  go.mod
  go.sum
  licenses/github.com/go-jose/go-jose/v3/LICENSE
  licenses/github.com/go-jose/go-jose/v3/json/LICENSE
  pkg/spiffe/spiffe.go
  security/pkg/server/ca/authenticate/oidc_test.go
  tests/integration/pilot/validation_test.go
Labels: size/L, release-notes-none

#55364 [release-1.25] Fix ztunnel service account name
  manifests/charts/ztunnel/templates/daemonset.yaml
Labels: size/XS, release-notes-none

#55365 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55339 Turn no-hostnet `istio-cni` back on by default + lost some bits in #55314 churn
  cni/pkg/nodeagent/meshdataplane_linux.go
  manifests/charts/istio-cni/values.yaml
Labels: size/L, release-notes-none, area/ambient

#55377 node untaint: plumb krt debugger to krt collections
  pilot/pkg/bootstrap/server.go
  pilot/pkg/controllers/untaint/nodeuntainter.go
  pilot/pkg/controllers/untaint/nodeuntainter_test.go
  pkg/kube/krt/options.go
Labels: size/S, release-notes-none, area/ambient

#55373 [release-1.24] bump go-jose to 4.0.5
  go.mod
  go.sum
  licenses/github.com/go-jose/go-jose/v3/LICENSE
  licenses/github.com/go-jose/go-jose/v3/json/LICENSE
  pkg/spiffe/spiffe.go
  security/pkg/server/ca/authenticate/oidc_test.go
  tests/integration/pilot/validation_test.go
Labels: size/L, release-notes-none

#55378 krt: use stop and debugger everywhere
  pilot/pkg/controllers/untaint/nodeuntainter_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pilot/pkg/serviceregistry/kube/controller/fake.go
  pkg/kube/krt/conformance_test.go
  pkg/kube/krt/join_test.go
  pkg/kube/krt/krttest/helpers.go
  pkg/kube/krt/recomputetrigger_test.go
  pkg/kube/krt/singleton_test.go
  pkg/kube/krt/static_test.go
Labels: size/M, release-notes-none

#55379 analyzer: stop unconditionally watching secrets/services/xyz
  pkg/config/analysis/local/istiod_analyze.go
Labels: size/XS, release-notes-none

#55382 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55384 [release-1.25] serverca: expand signed cert and cert chain PEMs with multiple cert blocks inside
  releasenotes/notes/serverca-expand-certs.yaml
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: size/L, release-notes-none

#55386 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#55291 accesslog: support `omit_empty_values`
  pilot/pkg/model/telemetry_logging.go
  pilot/pkg/model/telemetry_logging_test.go
  releasenotes/notes/54930.yaml
Labels: area/extensions and telemetry, size/M

#55393 Automator: update common-files@release-1.24 in istio/istio@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55394 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55402 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54285 Add double HBONE support to echo client and server
  go.mod
  go.sum
  licenses/github.com/cbeuw/connutil/LICENSE
  pkg/config/protocol/instance.go
  pkg/hbone/dialer.go
  pkg/hbone/doubledialer.go
  pkg/hbone/server.go
  pkg/test/echo/cmd/client/main.go
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/proto/echo.pb.go
  pkg/test/echo/proto/echo.proto
  pkg/test/echo/server/endpoint/doublehbone.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/forwarder/config.go
  pkg/test/echo/server/forwarder/util.go
  pkg/test/echo/server/instance.go
  pkg/test/framework/components/echo/calloptions.go
  pkg/test/framework/components/echo/common/call.go
Labels: area/test and release, size/XL, release-notes-none

#55385 Include the underlay error in the mesh dataplane initialization error
  cni/pkg/nodeagent/server.go
Labels: ok-to-test, size/XS, release-notes-none, area/ambient

#55403 Fix TLS from ratings sample
  samples/bookinfo/src/ratings/Dockerfile
Labels: size/XS, release-notes-none, cherrypick/release-1.25

#55383 [release-1.24] serverca: expand signed cert and cert chain PEMs with multiple cert blocks inside
  releasenotes/notes/serverca-expand-certs.yaml
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: size/L, release-notes-none

#55331 istioctl: internel-debug should return response if it's last one
  istioctl/pkg/internaldebug/internal-debug_test.go
  istioctl/pkg/multixds/gather.go
Labels: area/environments, size/L, release-notes-none

#55405 [release-1.25] Fix TLS from ratings sample
  samples/bookinfo/src/ratings/Dockerfile
Labels: size/XS, release-notes-none

#55399 gateway: do not drop entire route if mirror is invalid
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
Labels: size/M, release-notes-none

#55400 optimization: do not copy when we do not need to
  pilot/pkg/model/push_context.go
  pilot/pkg/model/virtualservice.go
Labels: size/S, release-notes-none

#55387 Dump state of helm upgrade tests in case of failure
  tests/integration/helm/upgrade/util.go
Labels: area/test and release, size/M, release-notes-none

#55411 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55412 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55280 waypoint: unify XDS for waypoint routes
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
Labels: size/L, release-notes-none

#55410 Fix validation for 0s connectionPool.tcp.IdleTimeout
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55409.yaml
Labels: area/networking, size/S, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#55415 [release-1.25] Fix validation for 0s connectionPool.tcp.IdleTimeout
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55409.yaml
Labels: size/S, release-notes-none

#55149 ambient: disable accidental EnvoyFilter implementation
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/httproute.go
  pilot/pkg/networking/core/listener_builder.go
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none

#54478 feat: add code coverage
  .gitignore
  Makefile.overrides.mk
  prow/coverage.sh
Labels: ok-to-test, size/M, release-notes-none

#55422 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55423 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55426 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55430 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55431 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55447 Automator: update common-files@master in istio/istio@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#55417 [release-1.24] Fix validation for 0s connectionPool.tcp.IdleTimeout
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55409.yaml
Labels: size/S, release-notes-none

#55416 [release-1.23] Fix validation for 0s connectionPool.tcp.IdleTimeout
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55409.yaml
Labels: size/S, release-notes-none

#55448 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#55450 Automator: update istio/client-go@release-1.25 dependency in istio/istio@release-1.25
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#55445 [release 1.24] telemetry tests fixes for Openshift
  pkg/test/framework/components/cluster/clusters.go
  tests/integration/telemetry/api/customize_metrics_test.go
  tests/integration/telemetry/api/registry_setup_test.go
Labels: area/extensions and telemetry, ok-to-test, size/M, release-notes-none

#55452 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#55348 fix typo for WasmPluginResourceNamePrefix
  pilot/pkg/model/extensions.go
  pilot/pkg/networking/core/gateway_test.go
  pilot/pkg/networking/core/listener_test.go
  pilot/pkg/xds/ecds_test.go
Labels: size/L, release-notes-none

#55424 disable draining when quitquitquit is called
  pilot/cmd/pilot-agent/options/statusserver.go
  pilot/cmd/pilot-agent/status/server.go
  pilot/cmd/pilot-agent/status/server_test.go
  pkg/istio-agent/agent.go
Labels: size/S, release-notes-none

#55455 Automator: update istio/client-go@release-1.23 dependency in istio/istio@release-1.23
  go.mod
  go.sum
  manifests/charts/base/crds/crd-all.gen.yaml
  manifests/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#55198 Implement TCPRoute for waypoints
  pilot/pkg/networking/core/listener_waypoint.go
  releasenotes/notes/waypoint-tcproute.yaml
  tests/integration/ambient/waypoint_test.go
Labels: size/L

#55267 krt: support using indexes as collections
  pkg/kube/krt/index.go
  pkg/kube/krt/index_test.go
Labels: size/L, release-notes-none

#55381 Improve `HTTPRoute` status conditions for `Service` and `ServiceEntry` parentRef types
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conditions_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.yaml
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.yaml.golden
  releasenotes/notes/httproute-status-for-svc-svcentry.yaml
Labels: ok-to-test, area/user experience, size/L, area/ambient

#55456 Drop spammy env var
  Makefile.overrides.mk
Labels: size/XS, release-notes-none

#55460 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55457 krt: add debug to index collection
  pkg/kube/krt/index.go
Labels: size/M, release-notes-none

#55474 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55468 Fix TestCNIRaceRepair test for Openshift (#54581)
  tests/integration/ambient/util.go
  tests/integration/pilot/cni_race_test.go
Labels: area/test and release, ok-to-test, size/M, release-notes-none

#55476 optimize: avoid updating service targets when it's not really necessary
  pilot/pkg/model/context.go
  pilot/pkg/xds/ads.go
Labels: area/perf and scalability, size/S, release-notes-none

#55469 Check for reachable ingress in TestGatewayAPI security test (#55028)
  pkg/test/framework/components/istio/ingress.go
  pkg/test/kube/util.go
Labels: area/test and release, ok-to-test, size/M, release-notes-none

#55465 fix waypoint-for and rev labels cannot be generated simultaneously by istioctl waypoint
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/55465.yaml
Labels: size/S

#55480 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55482 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55483 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55485 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55443 [release 1.24] fix telemetry tracing tests on openshift
  pkg/test/framework/components/zipkin/kube.go
  pkg/test/framework/components/zipkin/zipkin.go
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
  tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
Labels: area/extensions and telemetry, ok-to-test, size/L, release-notes-none

#55470 Fix Telemetry Tracint flaky tests failures (#55325)
  pkg/test/framework/components/zipkin/kube.go
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
  tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
Labels: area/extensions and telemetry, ok-to-test, size/S, release-notes-none

#55454 krt: various improvements split out
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue.go
  pkg/config/mesh/meshwatcher/mesh.go
  pkg/config/mesh/meshwatcher/networks.go
  pkg/kube/krt/collection.go
  pkg/kube/krt/collection_test.go
  pkg/kube/krt/conformance_test.go
  pkg/kube/krt/core.go
  pkg/kube/krt/fetch.go
  pkg/kube/krt/helpers.go
  pkg/kube/krt/index.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/krttest/helpers.go
  pkg/kube/krt/processor.go
  pkg/kube/krt/processor_test.go
  pkg/kube/krt/recomputetrigger.go
  pkg/kube/krt/singleton.go
  pkg/kube/krt/singleton_test.go
  pkg/kube/krt/static.go
  pkg/kube/krt/static_test.go
  pkg/kube/krt/status.go
  pkg/kube/krt/util.go
Labels: size/XL, release-notes-none

#55497 optimize: add missing cluster scoped known config types for sidecar
  pilot/pkg/model/sidecar.go
Labels: area/perf and scalability, size/XS, release-notes-none

#54914 HBONE: properly use HBONE when ISTIO_MUTUAL is explicitly set
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none, cherrypick/release-1.25

#55494 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55488 Template ztunnel name for CA_TRUSTED_NODE_ACCOUNTS environment.
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
Labels: area/networking, ok-to-test, size/XS, release-notes-none, area/ambient

#55508 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55498 Do not assign namespace to cluster scoped resources
  pilot/pkg/config/kube/crd/conversion.go
  pilot/pkg/config/kube/gateway/testdata/delegated.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/grpc.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mismatch.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden
Labels: size/S, release-notes-none

#55517 [release-1.25] upgrade golang.org/x/oauth2
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#55513 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55459 conradhanson/bug fix route status parentref reporting
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.status.yaml.golden
  releasenotes/notes/fix-httproute-status-parentref-single-result.yaml
Labels: area/networking, ok-to-test, area/user experience, size/L

#55499 [1.25] waypoints: fix HTTP auto-protocol detection (#55421)
  pilot/pkg/networking/core/cluster_builder.go
  pkg/test/echo/server/forwarder/grpc.go
  releasenotes/notes/waypoint-auto-http2.yaml
  tests/integration/ambient/baseline_test.go
  tests/integration/ambient/waypoint_test.go
Labels: size/L, release-notes-none

#55536 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55539 cherry-pick route status updates into release-1.25
  pilot/pkg/config/kube/gateway/conditions.go
  pilot/pkg/config/kube/gateway/conditions_test.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.yaml
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.yaml
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.yaml.golden
  releasenotes/notes/fix-httproute-status-parentref-single-result.yaml
  releasenotes/notes/httproute-status-for-svc-svcentry.yaml
Labels: area/networking, area/user experience, size/XL, area/ambient

#55547 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55549 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55531 samples: make setupkind work on mac
  samples/kind-lb/setupkind.sh
Labels: size/S, release-notes-none

#55553 addons: Bump addons version
  manifests/addons/gen.sh
  samples/addons/jaeger.yaml
  samples/addons/loki.yaml
Labels: size/S, release-notes-none

#55550 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55540 cni: give hint when platform is not set appropriately
  cni/pkg/install/install.go
Labels: size/XS, release-notes-none

#55500 Remove deadcode in test framework
  pkg/test/framework/features/README.md
  pkg/test/framework/features/allowlist.txt
Labels: size/XXL, release-notes-none

#55541 istioctl zc: avoid accidentally selecting random pod
  istioctl/pkg/ztunnelconfig/ztunnelconfig.go
Labels: size/M, release-notes-none

#55559 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55560 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55561 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55505 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55565 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55566 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55568 Remove ENABLE_AUTO_SNI and related codepaths
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/networking/core/cluster_tls_test.go
  releasenotes/notes/55568.yaml
Labels: area/environments, area/networking, size/L

#55544 tls: do not modify shared objects
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/networking/core/cluster_tls_test.go
  pilot/pkg/networking/core/cluster_traffic_policy.go
Labels: size/L, release-notes-none

#55572 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55501 [release-1.25] HBONE: properly use HBONE when ISTIO_MUTUAL is explicitly set
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none

#55573 optimize: avoid unnecessary slice copying
  pilot/pkg/serviceregistry/serviceentry/controller.go
Labels: area/perf and scalability, size/XS, release-notes-none

#55496 optimize: proxy updated config filtering
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/gateway/controller_test.go
  pilot/pkg/model/network.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/network.go
  pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
  pilot/pkg/serviceregistry/serviceentry/controller.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/ads_test.go
  pilot/pkg/xds/bench_test.go
  pilot/pkg/xds/cds.go
  pilot/pkg/xds/debug.go
  pilot/pkg/xds/delta.go
  pilot/pkg/xds/delta_test.go
  pilot/pkg/xds/discovery.go
  pilot/pkg/xds/discovery_test.go
  pilot/pkg/xds/ecds_test.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/eds_sh_test.go
  pilot/pkg/xds/eds_test.go
  pilot/pkg/xds/nds_test.go
  pilot/pkg/xds/pcds.go
  pilot/pkg/xds/proxy_dependencies.go
  pilot/pkg/xds/proxy_dependencies_test.go
  pilot/pkg/xds/sds.go
  pilot/pkg/xds/sds_test.go
  pilot/pkg/xds/workload.go
  pilot/pkg/xds/xdsgen.go
  pilot/test/xds/fake.go
Labels: area/perf and scalability, size/XL, release-notes-none

#55425 Document reconciliation and idempotency logic for iptables wrapper
  tools/istio-iptables/pkg/README.md
Labels: kind/docs, size/M, release-notes-none

#55567 don't warning when se is set workloadSelector with resolution DNS
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55567.yaml
Labels: size/S, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#55581 Fix a minor issue in releasenote
  releasenotes/notes/55567.yaml
Labels: size/XS, release-notes-none

#55576 1.25 golang CVE
  go.mod
  go.sum
Labels: area/security, size/M, release-notes-none

#55580 [release-1.25] don't warning when se is set workloadSelector with resolution DNS
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55567.yaml
Labels: size/S, release-notes-none

#55590 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55594 Golang CVE Fixes
  go.mod
  go.sum
Labels: area/security, size/M, release-notes-none

#55589 update supported groups for TLS
  pkg/config/security/security.go
Labels: ok-to-test, size/XS, release-notes-none

#55578 [release-1.23] don't warning when se is set workloadSelector with resolution DNS
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55567.yaml
Labels: size/S, release-notes-none

#55569 ambient: support fqdn in workloadentry
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/istio/ingress/interface.go
  releasenotes/notes/55569.yaml
  tests/integration/ambient/baseline_test.go
Labels: area/networking, size/L, area/ambient

#55603 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55613 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55618 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55619 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55620 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55624 Automator: update istio/client-go@release-1.25 dependency in istio/istio@release-1.25
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55628 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55625 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55630 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55631 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55548 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/S, auto-merge, release-notes-none

#55634 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55626 Minor cleanup on istioctl waypoint command
  istioctl/pkg/waypoint/waypoint.go
Labels: size/S, release-notes-none

#55600 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#55643 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55436 gateway-api-inference-extenstion support
  bin/update_crds.sh
  go.mod
  go.sum
  licenses/sigs.k8s.io/gateway-api-inference-extension/LICENSE
  manifests/charts/base/files/crd-all.gen.yaml
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/inferencepool.go
  pilot/pkg/config/kube/gateway/inferencepool_test.go
  pilot/pkg/config/kube/gateway/testdata/deployment/gateway-with-infrerencepool-extproc-infra-label.yaml
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/features/experimental.go
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/listener_builder.go
  pilot/pkg/networking/core/listener_builder_test.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  pilot/pkg/xds/filters/filters.go
  pkg/config/constants/constants.go
  pkg/config/schema/codegen/collections.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kind/resources.gen.go
  pkg/config/schema/kubeclient/common.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/kube/client.go
  pkg/wellknown/wellknown.go
  tests/binary/dependencies_test.go
Labels: ok-to-test, size/XXL

#55645 Automator: update common-files@release-1.23 in istio/istio@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55644 Clusterrole and auto gen
  bin/update_crds.sh
  istio.deps
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  tests/integration/pilot/testdata/gateway-api-inference-extension-crd.yaml
Labels: ok-to-test, size/XL

#55646 Automator: update istio/client-go@release-1.23 dependency in istio/istio@release-1.23
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55647 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55642 Release 1.24 fix test services reachability and flackiness
  pkg/test/framework/components/istio/ingress.go
  pkg/test/framework/components/zipkin/kube.go
  pkg/test/kube/util.go
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
  tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
  tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
Labels: area/test and release, ok-to-test, size/M, release-notes-none
