Repository istio/istio, pull requests merged in 2025-08, with the labels that each got.

#57216 Add counters in the nftable rules
  tools/istio-nftables/pkg/capture/run.go
  tools/istio-nftables/pkg/capture/testdata/basic-exclude-nic.golden
  tools/istio-nftables/pkg/capture/testdata/dns-uid-gid.golden
  tools/istio-nftables/pkg/capture/testdata/drop-invalid.golden
  tools/istio-nftables/pkg/capture/testdata/empty.golden
  tools/istio-nftables/pkg/capture/testdata/host-ipv4-loopback-cidr.golden
  tools/istio-nftables/pkg/capture/testdata/inbound-ports-include.golden
  tools/istio-nftables/pkg/capture/testdata/inbound-ports-tproxy.golden
  tools/istio-nftables/pkg/capture/testdata/inbound-ports-wildcard-tproxy.golden
  tools/istio-nftables/pkg/capture/testdata/inbound-ports-wildcard.golden
  tools/istio-nftables/pkg/capture/testdata/ip-range.golden
  tools/istio-nftables/pkg/capture/testdata/ipnets-with-kube-virt-interfaces.golden
  tools/istio-nftables/pkg/capture/testdata/ipnets.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups-exclude.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-dns-uid-gid.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-empty-inbound-ports.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-inbound-ports.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-ipnets.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-outbound-ports.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-uid-gid.golden
  tools/istio-nftables/pkg/capture/testdata/ipv6-virt-interfaces.golden
  tools/istio-nftables/pkg/capture/testdata/kube-virt-interfaces.golden
  tools/istio-nftables/pkg/capture/testdata/loopback-outbound-iprange.golden
  tools/istio-nftables/pkg/capture/testdata/outbound-owner-groups-exclude.golden
  tools/istio-nftables/pkg/capture/testdata/outbound-owner-groups.golden
  tools/istio-nftables/pkg/capture/testdata/outbound-ports-include.golden
  tools/istio-nftables/pkg/capture/testdata/tproxy.golden
  tools/istio-nftables/pkg/constants/constants.go
Labels: size/XXL, release-notes-none

#57233 Automator: update proxy@release-1.27 in istio/istio@release-1.27
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57231 UPDATING-CHARTS.md: be more explicit in about protobuf updates
  manifests/charts/UPDATING-CHARTS.md
Labels: area/environments, size/XS, release-notes-none

#56549 feat: support cacert in configMaps
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  releasenotes/notes/56549.yaml
Labels: ok-to-test, size/M

#57157 krt: Nested Join Rewrite
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/ambient/networks.go
  pilot/pkg/serviceregistry/kube/controller/ambient/nodes.go
  pilot/pkg/serviceregistry/kube/controller/ambient/remotesecrets_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pkg/config/model.go
  pkg/kube/krt/collection_test.go
  pkg/kube/krt/dynamic.go
  pkg/kube/krt/helpers.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/join_test.go
  pkg/kube/krt/map.go
  pkg/kube/krt/map_test.go
  pkg/kube/krt/mergejoin.go
  pkg/kube/krt/nestedjoin.go
  pkg/kube/krt/nestedjoin_test.go
  pkg/kube/krt/nestedjoinmerge.go
  pkg/kube/krt/nestedjoinmerge_test.go
Labels: size/XXL, release-notes-none, cherrypick/release-1.27

#57235 [release-1.27] krt: Nested Join Rewrite
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/ambient/networks.go
  pilot/pkg/serviceregistry/kube/controller/ambient/nodes.go
  pilot/pkg/serviceregistry/kube/controller/ambient/remotesecrets_test.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pkg/config/model.go
  pkg/kube/krt/collection_test.go
  pkg/kube/krt/dynamic.go
  pkg/kube/krt/helpers.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/join_test.go
  pkg/kube/krt/map.go
  pkg/kube/krt/map_test.go
  pkg/kube/krt/mergejoin.go
  pkg/kube/krt/nestedjoin.go
  pkg/kube/krt/nestedjoin_test.go
  pkg/kube/krt/nestedjoinmerge.go
  pkg/kube/krt/nestedjoinmerge_test.go
Labels: size/XXL, release-notes-none

#57234 nftables: remove the helm TestNativeNftablesInstall test
  tests/integration/helm/install_test.go
Labels: area/test and release, size/XS, release-notes-none, cherrypick/release-1.27

#57238 [release-1.27] nftables: remove the helm TestNativeNftablesInstall test
  tests/integration/helm/install_test.go
Labels: size/XS, release-notes-none

#57239 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57241 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57242 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57244 Automator: update proxy@release-1.27 in istio/istio@release-1.27
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57246 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57252 [release-1.26] Fix VerifyIptablesState ignoring IPv4 state in favor of the IPv6 one
  releasenotes/notes/56626.yaml
  tools/istio-iptables/pkg/capture/helper.go
  tools/istio-iptables/pkg/capture/run_linux_test.go
Labels: size/L, release-notes-none

#57255 [release-1.25] Fix VerifyIptablesState ignoring IPv4 state in favor of the IPv6 one
  releasenotes/notes/56626.yaml
  tools/istio-iptables/pkg/capture/helper.go
  tools/istio-iptables/pkg/capture/run_test.go
Labels: area/networking, size/L

#57260 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57258 [release-1.25] fix binary_test size for envoy, manual cp #57160
  istio.deps
  tests/binary/binaries_test.go
Labels: size/XS, release-notes-none

#57272 [release-1.27] cacerts file watcher bug
  pilot/pkg/bootstrap/istio_ca.go
  pilot/pkg/bootstrap/server_test.go
  releasenotes/notes/cacerts-file-watcher-bug.yaml
Labels: size/M, release-notes-none

#57290 [release-1.27] Check all workloads when deciding whether to send to EW gateway
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
Labels: size/S, release-notes-none

#57286 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#57289 Fix gen-eastwest-gateway.sh for ambient multi-cluster
  samples/multicluster/gen-eastwest-gateway.sh
Labels: size/XS, feature/Multi-cluster, release-notes-none, area/ambient

#56972 Handle deadlock between CNI startup and plugin
  cni/pkg/install/cniconfig.go
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  cni/pkg/plugin/plugin.go
  operator/pkg/apis/values_types.pb.go
  operator/pkg/apis/values_types.proto
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  tests/integration/ambient/cni/main_test.go
  tests/integration/ambient/main_test.go
Labels: area/networking, size/L, release-notes-none, area/upgrade, area/ambient, cherrypick/release-1.27

#57292 [release-1.27] Fix gen-eastwest-gateway.sh for ambient multi-cluster
  samples/multicluster/gen-eastwest-gateway.sh
Labels: size/XS, release-notes-none

#57296 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57304 remove unused arg
  pilot/pkg/serviceregistry/kube/controller/ambient/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/ambient/nodes.go
Labels: size/XS, release-notes-none

#57301 Automator: update proxy@release-1.27 in istio/istio@release-1.27
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57307 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57308 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57309 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57310 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57314 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56830 Filter out invalid certs.
  releasenotes/notes/certificate-parsing-graceful-failures.yaml
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/cache/secretcache_test.go
  security/pkg/nodeagent/cache/testdata/emptyfile.pem
  security/pkg/nodeagent/cache/testdata/invalidpem.pem
  security/pkg/nodeagent/cache/testdata/root-ca-bundle-with-graceful-failures.pem
  security/pkg/pki/util/crypto.go
Labels: area/security, size/L

#57284 improve istioctl x internal-debug syncz --all output format
  istioctl/pkg/internaldebug/internal-debug.go
  istioctl/pkg/internaldebug/internal-debug_test.go
Labels: area/networking, area/user experience, size/L, release-notes-none

#57323 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57322 fix retry budget validation when only retry budget is set
  pkg/config/validation/validation.go
  releasenotes/notes/retry-budget-validation.yaml
Labels: size/XS, cherrypick/release-1.27

#57253 [release-1.27] Fix VerifyIptablesState ignoring IPv4 state in favor of the IPv6 one
  releasenotes/notes/56626.yaml
  tools/istio-iptables/pkg/capture/helper.go
  tools/istio-iptables/pkg/capture/run_linux_test.go
Labels: size/L, release-notes-none

#57330 Add seccompProfile configuration
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  releasenotes/notes/57004.yaml
Labels: ok-to-test, size/M

#57340 fix the behavior change of istio ps will breaks foreign tooling calling
  istioctl/pkg/proxystatus/proxystatus_test.go
  istioctl/pkg/writer/pilot/status.go
  releasenotes/notes/57340.yaml
Labels: area/networking, area/user experience, size/S

#57334 add metrics when servicetarget's is empty
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: size/S, release-notes-none

#57353 Add test for Service bound waypoints with MultiNetwork
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
Labels: ok-to-test, size/L, feature/Multi-cluster, release-notes-none, area/ambient, cherrypick/release-1.27

#57359 Automator: update proxy@release-1.27 in istio/istio@release-1.27
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57365 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57377 run make gen
  operator/pkg/apis/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/workload.pb.go
  pkg/zdsapi/zds.pb.go
Labels: size/XS, release-notes-none

#57382 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#57366 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57387 Improve waypoint interop testing
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
Labels: size/S, feature/Multi-cluster, release-notes-none, area/ambient, cherrypick/release-1.27

#57390 Automator: update proxy@release-1.27 in istio/istio@release-1.27
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57381 allow null requests and limits for gateway deployment
  manifests/charts/gateway/values.schema.json
  releasenotes/notes/57381.yaml
Labels: ok-to-test, size/S

#57398 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#57065 Add GitHub Copilot configuration and domain knowledge
  .github/.copilot/domain_knowledge/integration_test_framework.md
  .github/.copilot/domain_knowledge/istio_analysis_messages.md
  .github/.copilot/domain_knowledge/istio_tags_and_revisions.md
  .github/.copilot/domain_knowledge/istioctl_commands.md
  .github/.copilot/domain_knowledge/krt_package.md
  .github/.copilot/domain_knowledge/pilot_push_context.md
  .github/copilot-instructions.md
  .github/prompts/create_domain_knowledge.prompt.md
  .gitignore
Labels: size/XL, release-notes-none

#57391 [release-1.27] Improve waypoint interop testing
  pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
Labels: size/S, release-notes-none

#57367 preserve header case for passthrough clusters
  pilot/pkg/networking/core/cluster_builder.go
  pilot/pkg/networking/core/cluster_cache.go
  pilot/pkg/networking/core/listener_builder.go
  tests/integration/pilot/preserve_http_header_case_test.go
Labels: area/networking, size/M, release-notes-none

#57401 Automator: update common-files@release-1.25 in istio/istio@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#57402 Automator: update istio/client-go@release-1.25 dependency in istio/istio@release-1.25
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#57405 Automator: update common-files@release-1.26 in istio/istio@release-1.26
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#57406 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#57408 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57410 Automator: update istio/client-go@release-1.27 dependency in istio/istio@release-1.27
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#57411 [release-1.27] Fix iptables detection logic
  releasenotes/notes/57385.yaml
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
Labels: size/S, release-notes-none

#57421 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57436 Automator: update ztunnel@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57439 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57441 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57423 add new mTLS echo capability to our testing
  pkg/test/echo/parse.go
  pkg/test/echo/response.go
  pkg/test/framework/components/echo/common/deployment/external.go
  pkg/test/framework/components/echo/common/ports/ports.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/templates/deployment.yaml
  pkg/test/framework/components/echo/port.go
  tests/integration/security/egress_gateway_origination_test.go
Labels: area/test and release, size/L, release-notes-none, cherrypick/release-1.27

#57447 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57444 [release-1.27] mtls-echo and sample
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/common/model.go
  pkg/test/echo/fields.go
  pkg/test/echo/server/endpoint/http.go
  pkg/test/echo/server/endpoint/instance.go
  pkg/test/echo/server/instance.go
  samples/mtls-echo/README.md
  samples/mtls-echo/mtls-echo.yaml
Labels: size/L, release-notes-none

#57200 iptables: gracefully handle missing IPv6 support
  cni/pkg/iptables/iptables.go
  cni/pkg/iptables/iptables_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux_test.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: area/networking, ok-to-test, size/L, release-notes-none

#57430 Run nftable tests even with distroless images
  tests/integration/helm/install_test.go
  tests/integration/pilot/nftables/main_test.go
Labels: size/S, release-notes-none

#57443 [release-1.27] add new mTLS echo capability to our testing
  pkg/test/echo/parse.go
  pkg/test/echo/response.go
  pkg/test/framework/components/echo/common/deployment/external.go
  pkg/test/framework/components/echo/common/ports/ports.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/templates/deployment.yaml
  pkg/test/framework/components/echo/port.go
  tests/integration/security/egress_gateway_origination_test.go
Labels: size/L, release-notes-none

#57459 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#57435 pkg/typemap: refactor to use reflect.TypeFor
  pkg/typemap/map.go
Labels: ok-to-test, size/XS, release-notes-none

#57434 support display connections info for ztunnel-config all
  istioctl/pkg/writer/ztunnel/configdump/configdump.go
  releasenotes/notes/57434.yaml
Labels: area/networking, area/user experience, size/S

#57463 [release-1.27] do not add the new --ca flag during custome grpc template
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/templates/deployment.yaml
Labels: size/XS, release-notes-none

#57461 add UT for ztunnel-config connections and all
  istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
  istioctl/pkg/writer/ztunnel/configdump/testdata/allsummary.txt
  istioctl/pkg/writer/ztunnel/configdump/testdata/connectionsummary.txt
  istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
Labels: area/networking, area/user experience, size/L, release-notes-none

#57469 Fixes panic due to uninitialized pointer when ClusterID is misconfigured
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
Labels: ok-to-test, size/XS, feature/Multi-cluster, release-notes-none

#57295 feat(gw-inference): Adds Initial Support for InferencePool v1
  go.mod
  go.sum
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  pilot/pkg/config/kube/crdclient/types.gen.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/inferencepool_collection.go
  pilot/pkg/config/kube/gateway/inferencepool_status_test.go
  pilot/pkg/config/kube/gateway/inferencepool_test.go
  pilot/pkg/config/kube/gateway/route_collections.go
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.yaml
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/kube/client.go
  releasenotes/notes/57219.yaml
  tests/integration/pilot/testdata/gateway-api-inference-extension-crd.yaml
Labels: area/networking, size/XXL

#57484 Remove unnessary package wolfi-baselayout
  docker/iptables.yaml
Labels: area/test and release, size/XS, release-notes-none, cherrypick/release-1.25, cherrypick/release-1.26

#57489 [release-1.27] Remove unnessary package wolfi-baselayout
  docker/iptables.yaml
Labels: size/XS, release-notes-none

#57487 [release-1.25] Remove unnessary package wolfi-baselayout
  docker/iptables.yaml
Labels: size/XS, release-notes-none

#57488 [release-1.26] Remove unnessary package wolfi-baselayout
  docker/iptables.yaml
Labels: size/XS, release-notes-none

#57492 update helm to resolve security issues
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#57442 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#57493 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#57502 [release-1.25] default revision tagwatcher
  pkg/revisions/tag_watcher.go
  releasenotes/notes/56767.yaml
  tests/integration/helm/install_test.go
Labels: size/L

#57503 run make gen
  operator/pkg/apis/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/workload.pb.go
  pkg/zdsapi/zds.pb.go
  prow/integ-suite-kind.sh
  samples/addons/grafana.yaml
Labels: size/XS, release-notes-none

#57500 [release-1.27] Add defaultRevision logic to tagWatcher (#57467)
  pkg/revisions/tag_watcher.go
  releasenotes/notes/56767.yaml
  tests/integration/helm/install_test.go
Labels: size/L

#57517 [release-1.25] schema validation
  .go-version
  manifests/charts/gateway/values.schema.json
  releasenotes/notes/57354.yaml
Labels: size/M, release-notes-none
