Repository istio/istio, pull requests merged in 2025-04, with the labels that each got.

#55762 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55764 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55313 Upgrade gateway-api to v1.3.0
  bin/update_crds.sh
  go.mod
  go.sum
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
  pilot/pkg/serviceregistry/kube/controller/network_test.go
  pkg/config/validation/validation.go
  tests/integration/ambient/gateway_conformance_test.go
  tests/integration/pilot/gateway_conformance_test.go
  tests/integration/pilot/testdata/gateway-api-crd.yaml
Labels: size/XXL, release-notes-none

#55765 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55761 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55759 echo: fallback to IPv4 if there are no address
  pkg/test/echo/cmd/server/main.go
  pkg/test/echo/server/instance.go
Labels: size/XS, release-notes-none

#55730 istioctl: warn if using legacy Gateway API versions
  istioctl/pkg/precheck/precheck.go
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
Labels: size/M, release-notes-none

#55770 Fix goroutine leak when sync fails
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pkg/kube/controllers/queue.go
  pkg/kube/multicluster/secretcontroller.go
  pkg/kube/watcher/configmapwatcher/configmapwatcher.go
  pkg/revisions/tag_watcher.go
Labels: size/S, release-notes-none

#55772 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55652 update golang CVE packages
  go.mod
  go.sum
  licenses/golang.org/x/exp/LICENSE
  licenses/golang.org/x/oauth2/LICENSE
  licenses/golang.org/x/time/LICENSE
Labels: area/security, size/M, release-notes-none

#55735 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55771 Update BASE_VERSION to 1.23-2025-04-01T19-02-37
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55725 Automator: update ztunnel@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55736 [release-1.23] Fix broken IstioCNI config for enabling repair mode (#55665)
  manifests/charts/istio-cni/templates/configmap-cni.yaml
Labels: size/XS, release-notes-none

#55783 Automator: update istio/client-go@release-1.23 dependency in istio/istio@release-1.23
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#55236 fix istioctl waypoint delete gateway which is not waypoint
  istioctl/pkg/waypoint/waypoint.go
  releasenotes/notes/55236.yaml
Labels: size/M

#55744 [istioctl manifests]: support reconcilePodRulesOnStartup in operator specs
  operator/pkg/apis/validation/validation_test.go
  operator/pkg/apis/values_types.pb.go
  operator/pkg/apis/values_types.proto
  releasenotes/notes/55744.yaml
Labels: ok-to-test, size/S

#55352 [release-1.23] multus: fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array
  pkg/kube/inject/template.go
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml.injected
Labels: size/S, release-notes-none

#55721 Automator: update common-files@release-1.23 in istio/istio@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55784 Automator: update istio/client-go@release-1.23 dependency in istio/istio@release-1.23
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55777 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55797 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55720 istioctl: include protocol in connection dump
  istioctl/pkg/writer/ztunnel/configdump/api.go
  istioctl/pkg/writer/ztunnel/configdump/connections.go
Labels: size/XS, release-notes-none

#55796 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55808 Update BASE_VERSION to 1.25-2025-04-04T19-01-15
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55810 Update BASE_VERSION to 1.23-2025-04-04T19-03-04
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55809 Update BASE_VERSION to 1.24-2025-04-04T19-02-09
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55813 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55811 pilot: fix bug in Alias type RDS cache
  pilot/pkg/networking/core/route/route_cache.go
  releasenotes/notes/rds-cache-alias.yaml
Labels: size/S, release-notes-none, cherrypick/release-1.24, cherrypick/release-1.25

#55769 Add option to customize updateStrategy in istio-cni/ztunnel daemonsets helm charts
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-cni/values.yaml
  manifests/charts/ztunnel/templates/daemonset.yaml
  manifests/charts/ztunnel/values.yaml
  releasenotes/notes/ambient-customize-updatestrategy.yaml
Labels: ok-to-test, size/M, area/ambient

#55816 add locality info for ServiceEntry endpoints
  pilot/pkg/serviceregistry/serviceentry/conversion.go
Labels: area/networking, size/XS, release-notes-none

#55819 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55832 Update local registry setup
  prow/config/default.yaml
  prow/integ-suite-kind.sh
  prow/lib.sh
Labels: ok-to-test, size/S, release-notes-none

#55824 Update ambient test case
  architecture/ambient/peer-authentication.md
Labels: kind/docs, ok-to-test, size/XS, release-notes-none

#55815 [release-1.25] pilot: fix bug in Alias type RDS cache
  pilot/pkg/networking/core/route/route_cache.go
  releasenotes/notes/rds-cache-alias.yaml
Labels: size/S, release-notes-none

#55837 Update BASE_VERSION to master-2025-04-07T19-01-16
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55827 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55833 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55638 [release-1.24] Fix tests resources cleanup for Openshift
  pkg/kube/client.go
  pkg/test/framework/components/istio/cleanup.go
  pkg/test/kube/dump.go
  pkg/test/kube/util.go
Labels: area/extensions and telemetry, ok-to-test, size/L, release-notes-none

#55692 istioctl: add parameter --tls-server-name to create-remote-secret command
  istioctl/pkg/multicluster/remote_secret.go
  istioctl/pkg/multicluster/remote_secret_test.go
  releasenotes/notes/55692.yaml
Labels: area/environments, size/L, feature/Multi-cluster

#55801 remove obsolete gen-charts Make target
  Makefile.core.mk
Labels: area/test and release, size/XS, release-notes-none

#55840 gateway: fix regression around shared name cross-namespace
  pilot/pkg/config/kube/gateway/gateway_collection.go
Labels: size/XS, release-notes-none

#55845 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55846 [release-1.25] Add customized CA headers/metadata support to istio-agent
  pilot/cmd/pilot-agent/options/security.go
  pilot/cmd/pilot-agent/options/security_test.go
  pkg/security/security.go
  releasenotes/notes/add-customized-ca-metadata-support-to-istio-agent.yaml
  security/pkg/nodeagent/caclient/providers/citadel/client.go
Labels: size/L, release-notes-none

#55822 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/S, auto-merge, release-notes-none

#55847 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55835 Do not split root CA, fixing 1.25.1 regression
  istioctl/pkg/writer/ztunnel/configdump/api.go
  istioctl/pkg/writer/ztunnel/configdump/certificates.go
  security/pkg/server/ca/server.go
Labels: size/S, release-notes-none, cherrypick/release-1.24, cherrypick/release-1.25

#55850 [release-1.24] Do not split root CA, fixing 1.25.1 regression
  istioctl/pkg/writer/ztunnel/configdump/api.go
  istioctl/pkg/writer/ztunnel/configdump/certificates.go
  security/pkg/server/ca/server.go
Labels: size/S, release-notes-none

#55851 [release-1.25] Do not split root CA, fixing 1.25.1 regression
  istioctl/pkg/writer/ztunnel/configdump/api.go
  istioctl/pkg/writer/ztunnel/configdump/certificates.go
  security/pkg/server/ca/server.go
Labels: size/S, release-notes-none

#55854 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55855 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55856 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55857 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55858 Disable metadata lookup on SotW
  pkg/bootstrap/config.go
Labels: size/XS, release-notes-none

#55860 Automator: update common-files@release-1.23 in istio/istio@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55861 Automator: update common-files@release-1.24 in istio/istio@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55862 Automator: update istio/client-go@release-1.23 dependency in istio/istio@release-1.23
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55864 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55863 Automator: update istio/client-go@release-1.24 dependency in istio/istio@release-1.24
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55865 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55868 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55870 bump api and fix test
  go.mod
  go.sum
  pilot/pkg/networking/core/tracing_test.go
Labels: size/M, release-notes-none

#55878 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/XL, auto-merge, release-notes-none

#55876 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55828 bump to golangci-lint v2
  common/config/.golangci.yml
  tools/golangci-override.yaml
Labels: area/test and release, size/L, release-notes-none

#55882 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55883 Automator: update ztunnel@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55884 Automator: update common-files@release-1.25 in istio/istio@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55885 Automator: update istio/client-go@release-1.25 dependency in istio/istio@release-1.25
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55886 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55888 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55889 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55881 debug configz: show all metadata fields
  pilot/pkg/config/kube/crd/conversion.go
Labels: size/XS, release-notes-none

#55369 Remove istiod-remote profile legacy
  operator/pkg/component/component.go
  operator/pkg/uninstall/prune.go
Labels: release-notes-none

#55892 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55893 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55579 [release-1.24] don't warning when se is set workloadSelector with resolution DNS
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/55567.yaml
Labels: size/S, release-notes-none

#55896 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55895 istioctl: fix a regression(s) around warming resources
  istioctl/pkg/proxyconfig/proxyconfig.go
  istioctl/pkg/writer/compare/sds/util.go
  istioctl/pkg/writer/envoy/configdump/testdata/secret/istio/config_dump.json
  istioctl/pkg/writer/envoy/configdump/testdata/secret/istio/output
Labels: size/M, release-notes-none

#55902 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55803 Expose final Helm values used to render the chart in a ConfigMap
  manifests/charts/base/templates/zzz_profile.yaml
  manifests/charts/default/templates/zzz_profile.yaml
  manifests/charts/gateway/templates/zzz_profile.yaml
  manifests/charts/gateways/istio-egress/templates/zzz_profile.yaml
  manifests/charts/gateways/istio-ingress/templates/zzz_profile.yaml
  manifests/charts/istio-cni/templates/zzz_profile.yaml
  manifests/charts/istio-control/istio-discovery/templates/configmap-values.yaml
  manifests/charts/istio-control/istio-discovery/templates/zzz_profile.yaml
  manifests/charts/ztunnel/templates/zzz_profile.yaml
  manifests/zzz_profile.yaml
  releasenotes/notes/55803.yaml
Labels: area/environments, area/user experience, size/M

#55898 Add some sanity checks for distroless image
  tools/build-base-images.sh
Labels: size/M, release-notes-none

#55906 Improve test logging
  pkg/test/framework/test.go
Labels: size/XS, release-notes-none, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#55911 [release-1.25] Improve test logging
  pkg/test/framework/test.go
Labels: size/XS, release-notes-none

#55910 [release-1.24] Improve test logging
  pkg/test/framework/test.go
Labels: size/XS, release-notes-none

#55909 [release-1.23] Improve test logging
  pkg/test/framework/test.go
Labels: size/XS, release-notes-none

#55914 Fix Telemetry api TestStatsFilter/mockprom-to-metrics test
  tests/integration/telemetry/api/stats_test.go
Labels: area/extensions and telemetry, ok-to-test, size/XS, release-notes-none

#55750 Rename BuiltInChainsMap to BuiltInChainsAndTargetsMap
  tools/istio-iptables/pkg/builder/iptables_builder_impl.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: size/S, release-notes-none

#55919 Disable fallback for missing kubeconfig
  pkg/kube/util.go
Labels: size/S, release-notes-none

#55925 add test for multiple FilterIndex
  pkg/kube/krt/collection.go
  pkg/kube/krt/filter.go
  pkg/kube/krt/index_test.go
Labels: release-notes-none

#55786 add helm test for chart
  istioctl/pkg/tag/generate.go
  operator/cmd/mesh/manifest-generate_test.go
  operator/pkg/helm/helm.go
  operator/pkg/helm/helm_test.go
  operator/pkg/helm/testdata/input/gateway-deployment.yaml
  operator/pkg/helm/testdata/output/gateway-deployment.golden.yaml
  operator/pkg/render/manifest.go
  operator/pkg/test/util.go
Labels: size/L, release-notes-none

#55817 default maxconnectionstoacceptpersocketevent to a sensible value
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/listener.go
  pilot/pkg/networking/core/listener_builder.go
  pilot/pkg/networking/core/listener_inbound.go
  releasenotes/notes/max-socket-events.yaml
Labels: size/M, release-notes-none

#55859 pilot: fix verified certificate when mtls and referencegrants
  pilot/pkg/model/gateway.go
  pilot/pkg/model/gateway_test.go
  releasenotes/notes/55859.yaml
Labels: ok-to-test, size/L

#55337 krt: implement folder based collections
  pkg/config/mesh/meshwatcher/collection.go
  pkg/kube/krt/conformance_test.go
  pkg/kube/krt/files.go
  pkg/kube/krt/files/files.go
  pkg/kube/krt/files/files_test.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/static.go
Labels: size/XL, release-notes-none

#55899 gateway: add support for using workload certificate
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
Labels: size/M, release-notes-none

#55947 Update BASE_VERSION to 1.24-2025-04-15T19-02-46
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55946 Update BASE_VERSION to 1.23-2025-04-15T19-01-37
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55592 initial ClusterTrustBundle v1alpha1 support
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  manifests/charts/ztunnel/templates/daemonset.yaml
  pilot/pkg/config/kube/clustertrustbundle/controller.go
  pilot/pkg/config/kube/clustertrustbundle/controller_test.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pilot/pkg/features/pilot.go
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kind/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  prow/config/default.yaml
  releasenotes/notes/43986.yaml
Labels: size/L

#55758 gateway: refactor event handling
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/model/virtualservice.go
  pilot/pkg/model/virtualservice_test.go
  pilot/pkg/networking/core/route/route_cache.go
  pilot/pkg/networking/core/route/route_cache_test.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/cds.go
  pilot/pkg/xds/eds.go
  pilot/pkg/xds/lds.go
  pilot/pkg/xds/nds.go
  pilot/pkg/xds/proxy_dependencies.go
  pilot/pkg/xds/sds.go
Labels: size/L, release-notes-none

#55938 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55950 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55927 ztunnel: revert resource naming
  manifests/charts/ztunnel/templates/_helpers.tpl
  manifests/charts/ztunnel/values.yaml
  releasenotes/notes/ztunnel-helm-chart-revert.yaml
Labels: size/S, release-notes-none

#55948 Update BASE_VERSION to 1.25-2025-04-15T19-03-27
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55926 krt: add test coverage for status deletion
  pkg/kube/krt/status_test.go
Labels: size/S, release-notes-none

#55957 [release-1.25] Fix Telemetry api TestStatsFilter/mockprom-to-metrics test
  tests/integration/telemetry/api/stats_test.go
Labels: size/XS, release-notes-none

#55942 Bump bookinfo samples for 1.26
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-psa.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/bookinfo/src/details/Dockerfile
  samples/bookinfo/src/mongodb/Dockerfile
  samples/bookinfo/src/mysql/Dockerfile
  samples/bookinfo/src/productpage/Dockerfile
  samples/bookinfo/src/productpage/requirements.in
  samples/bookinfo/src/productpage/requirements.txt
  samples/bookinfo/src/ratings/Dockerfile
  samples/bookinfo/src/reviews/Dockerfile
Labels: size/XXL, release-notes-none

#55967 Cleanup follow-up: remove unused nflog package
  cni/pkg/iptables/iptables.go
  go.mod
  go.sum
  licenses/github.com/florianl/go-nflog/v2/LICENSE
  licenses/github.com/josharian/native/license
  licenses/github.com/mdlayher/netlink/LICENSE.md
  licenses/github.com/mdlayher/socket/LICENSE.md
  pilot/cmd/pilot-agent/app/cmd.go
  tests/binary/dependencies_test.go
  tools/istio-iptables/pkg/capture/run_test.go
  tools/istio-iptables/pkg/capture/testdata/logging.golden
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/log/nflog.go
Labels: area/networking, size/L, release-notes-none

#55545 Implement BackendTLSPolicy and BackendTrafficPolicy
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pilot/pkg/config/kube/gateway/backend_policies.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/references.go
  pilot/pkg/config/kube/gateway/testdata/backend-lb-policy.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/backend-lb-policy.yaml
  pilot/pkg/config/kube/gateway/testdata/backend-lb-policy.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/backend-tls-policy.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/backend-tls-policy.yaml
  pilot/pkg/config/kube/gateway/testdata/backend-tls-policy.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mix-backend-policy.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mix-backend-policy.yaml
  pilot/pkg/config/kube/gateway/testdata/mix-backend-policy.yaml.golden
  pilot/pkg/credentials/kube/multicluster.go
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/credentials/model.go
  pilot/pkg/model/credentials/resource.go
  pilot/pkg/model/credentials/resource_test.go
  pilot/pkg/networking/core/cluster_tls.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/xds/sds.go
  pilot/test/xds/fake.go
  pkg/config/schema/codegen/collections.go
  pkg/config/schema/codegen/templates/collections.go.tmpl
  pkg/config/schema/codegen/templates/gvk.go.tmpl
  pkg/config/schema/codegen/templates/kind.go.tmpl
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kind/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/config/validation/agent/validation.go
  pkg/config/validation/agent/validation_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/kube/client.go
  pkg/kube/krt/index.go
  pkg/kube/krt/internal.go
  pkg/slices/slices.go
  pkg/test/echo/fields.go
  pkg/test/echo/parse.go
  pkg/test/echo/response.go
  pkg/test/echo/server/endpoint/http.go
  pkg/test/framework/components/echo/check/checkers.go
  releasenotes/notes/backend-policies.yaml
  tests/integration/pilot/gateway_test.go
Labels: size/XXL, release-notes-none

#55936 Remove dead "zvpn" values in proto
  operator/pkg/apis/values_types.pb.go
  operator/pkg/apis/values_types.proto
Labels: size/S, release-notes-none

#55972 step 1 branch cut 1.26 - update_deps
  docker/Dockerfile.distroless
  go.mod
  go.sum
  istio.deps
  pkg/config/xds/filter_types.gen.go
  prow/release-commit.sh
Labels: size/S, release-notes-none

#55973 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55955 Add resourceFieldRef.divisor to resolve permadiff
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_env_var_from.golden.yaml
Labels: area/environments, ok-to-test, size/XS, release-notes-none

#55977 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55982 [release-1.26] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  prow/release-commit.sh
Labels: size/M, release-notes-none

#55983 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55984 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54942 Ambient East/West Gateway Implementation
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/gateway_collection.go
  pilot/pkg/config/kube/gateway/testdata/deployment/istio-east-west.yaml
  pilot/pkg/config/kube/gateway/testdata/east-west-ambient.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/east-west-ambient.yaml
  pilot/pkg/config/kube/gateway/testdata/east-west-ambient.yaml.golden
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
  pilot/pkg/networking/core/accesslog.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/cluster_waypoint.go
  pilot/pkg/networking/core/listener.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/networking/core/waypoint.go
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/services.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/xds/endpoints/endpoint_builder.go
  pkg/config/analysis/analyzers/service/portname.go
  pkg/config/constants/constants.go
  pkg/workloadapi/workload.proto
Labels: size/XL, release-notes-none

#55976 fix istioctl admin log cannot modify the log level of ip-autoallocate
  istioctl/pkg/admin/istiodconfig.go
  istioctl/pkg/admin/istiodconfig_test.go
  releasenotes/notes/55976.yaml
Labels: size/S

#55924 migrate Ingress Controller to KRT
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pilot/pkg/config/kube/gateway/backend_policies.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/status_test.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/controller_test.go
  pilot/pkg/config/kube/ingress/conversion.go
  pilot/pkg/config/kube/ingress/conversion_test.go
  pilot/pkg/config/kube/ingress/gateways.go
  pilot/pkg/config/kube/ingress/ingress.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/config/kube/ingress/virtualservices.go
  pilot/pkg/status/collections.go
  pilot/test/xds/fake.go
  pkg/config/schema/codegen/templates/crdclient.go.tmpl
  tests/fuzz/kube_ingress_fuzzer.go
  tests/fuzz/regression_test.go
Labels: area/perf and scalability, size/XXL, release-notes-none

#55989 Automator: update istio/client-go@release-1.26 dependency in istio/istio@release-1.26
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#55993 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55992 Automator: update istio/client-go@release-1.26 dependency in istio/istio@release-1.26
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55995 Automator: update common-files@release-1.26 in istio/istio@release-1.26
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55997 Automator: update ztunnel@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55998 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56000 set VERSION on master to 1.27
  VERSION
Labels: size/XS, release-notes-none

#56001 [release-1.26] update UPDATE_BRANCH and deps
  bin/update_deps.sh
  bin/update_ztunnel.sh
  go.mod
  go.sum
  istio.deps
  prow/release-commit.sh
Labels: size/S, release-notes-none

#56002 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56006 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56012 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56013 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56015 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56016 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#56017 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55871 support read header value from env variable
  pilot/pkg/networking/core/tracing.go
  pilot/pkg/networking/core/tracing_test.go
  releasenotes/notes/55871.yaml
  samples/open-telemetry/otel.yaml
  tests/integration/telemetry/tracing/otelcollector/testdata/otel-grpc-with-initial-metadata.yaml
  tests/integration/telemetry/tracing/otelcollector/testdata/otel-tracing-with-auth.yaml
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
Labels: area/environments, area/extensions and telemetry, size/L, cherrypick/release-1.26

#56019 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56008 fix(networking): Add absolute FQDNs (trailing dot) to VirtualHost domains
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/httproute.go
  pilot/pkg/networking/core/httproute_test.go
  releasenotes/notes/fix-enable-absolute-fqdn-domain-vhost.yaml
Labels: area/networking, ok-to-test, size/L, release-notes-none

#55117 doc: fix typo in accesslog test
  pilot/pkg/networking/core/accesslog_test.go
Labels: kind/docs, ok-to-test, size/XS, release-notes-none

#56004 fix istio-revision-tag-default MutatingWebhookConfigurations is not created during installation
  istioctl/pkg/tag/util.go
  releasenotes/notes/56004.yaml
Labels: size/S

#56026 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56023 remove 1.23 compatibility profile
  manifests/charts/base/files/profile-compatibility-version-1.23.yaml
  manifests/charts/default/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.23.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.23.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.23.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.23.yaml
  manifests/helm-profiles/compatibility-version-1.23.yaml
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/route/retry/retry.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
Labels: size/M, release-notes-none

#56030 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56018 [release-1.26] support read header value from env variable
  pilot/pkg/networking/core/tracing.go
  pilot/pkg/networking/core/tracing_test.go
  releasenotes/notes/55871.yaml
  samples/open-telemetry/otel.yaml
  tests/integration/telemetry/tracing/otelcollector/testdata/otel-grpc-with-initial-metadata.yaml
  tests/integration/telemetry/tracing/otelcollector/testdata/otel-tracing-with-auth.yaml
  tests/integration/telemetry/tracing/otelcollector/tracing_test.go
Labels: size/L, release-notes-none

#56011 handle allowedRoutes for PROXY waypoints
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints_test.go
  pkg/config/constants/constants.go
  releasenotes/notes/56011-sandwich-allowedRoutes.yaml
Labels: size/L, area/ambient

#56038 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55760 Support dual certificates in istio gateway and gateway-api
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/conversion_test.go
  pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/networking/core/gateway_test.go
  pilot/pkg/networking/core/listener.go
  pilot/pkg/networking/core/listener_test.go
  pilot/pkg/networking/core/listener_waypoint.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/model/authentication.go
  pilot/pkg/security/model/authentication_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/36181-gateway-rsa-ecdsa.yaml
Labels: ok-to-test, size/XXL

#56040 Automator: update proxy@release-1.26 in istio/istio@release-1.26
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#56043 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55543 Add metadata to krt.Collection
  pkg/kube/krt/collection.go
  pkg/kube/krt/conformance_test.go
  pkg/kube/krt/core.go
  pkg/kube/krt/index.go
  pkg/kube/krt/index_test.go
  pkg/kube/krt/informer.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/join.go
  pkg/kube/krt/options.go
  pkg/kube/krt/singleton.go
  pkg/kube/krt/singleton_test.go
  pkg/kube/krt/static.go
Labels: size/L, release-notes-none

#56049 telemetry: add warn messge for Lightstep/Opencensus
  pilot/pkg/model/push_context.go
  releasenotes/notes/warn-deprecated-provider.yaml
Labels: area/extensions and telemetry, size/S, cherrypick/release-1.26
