Repository istio/istio, pull requests merged in 2025-02, with the labels that each got.

#54892 match vhost on domain in envoyfilter
  pilot/pkg/networking/core/envoyfilter/rc_patch.go
  pilot/pkg/networking/core/envoyfilter/rc_patch_test.go
  releasenotes/notes/54892.yaml
Labels: area/networking, ok-to-test, size/L

#54903 fix missing wasm convert error logs
  pkg/wasm/convert.go
Labels: size/S, release-notes-none

#54938 [release-1.25] Implement ambient pod-level DNS inclusion/exclusion
  cni/pkg/iptables/common_test.go
  cni/pkg/iptables/iptables.go
  cni/pkg/iptables/testdata/dns_pod_disabled_and_on_globally.golden
  cni/pkg/iptables/testdata/dns_pod_disabled_and_on_globally_ipv6.golden
  cni/pkg/iptables/testdata/dns_pod_enabled_and_off_globally.golden
  cni/pkg/iptables/testdata/dns_pod_enabled_and_off_globally_ipv6.golden
  cni/pkg/nodeagent/net.go
  cni/pkg/nodeagent/net_test.go
  cni/pkg/util/podutil.go
  releasenotes/notes/54935.yaml
Labels: size/L, release-notes-none

#54943 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/M, auto-merge, release-notes-none

#54944 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54915 tests: use distroless for ambient helm upgrade test
  tests/integration/helm/upgrade/util.go
Labels: size/XS, release-notes-none

#54956 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54957 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54961 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54963 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54958 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54663 chiron: fix goroutine/memory leak of CSR watcher
  security/pkg/k8s/chiron/utils.go
Labels: area/security, ok-to-test, size/XS, release-notes-none

#54964 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#54980 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54983 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54973 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54993 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55001 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55004 samples: do not inject ext-authz demo
  samples/extauthz/ext-authz.yaml
Labels: size/XS, release-notes-none

#55010 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55012 Update BASE_VERSION to 1.22-2025-02-07T19-02-05
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55014 Update BASE_VERSION to master-2025-02-07T19-01-40
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55013 Update BASE_VERSION to 1.24-2025-02-07T19-01-21
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55018 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55020 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55021 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55031 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55017 addons: Bump addons version
  manifests/addons/gen.sh
  samples/addons/loki.yaml
  samples/addons/prometheus.yaml
Labels: size/M, release-notes-none

#55023 [release-1.24] validation: loosen HTTP header validation which was accidentally made too strict
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  releasenotes/notes/header-validation.yaml
  tests/integration/pilot/common/routing.go
Labels: size/L, release-notes-none

#55026 Documentation fix - `OUTPUT_CERT` should be `OUTPUT_CERTS`
  architecture/security/istio-agent.md
Labels: ok-to-test, size/XS, release-notes-none

#54996 Add upgradeNote for default change to internalAddressConfig
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/listener_builder.go
  releasenotes/notes/53402.yaml
Labels: size/M, cherrypick/release-1.25

#55036 Automator: update istio/client-go@release-1.25 dependency in istio/istio@release-1.25
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#55037 EnvoyFilter: do not re-use struct where not appropriate
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/envoyfilter_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/envoyfilter/cluster_patch.go
  pilot/pkg/networking/core/envoyfilter/extension_configuration_patch.go
  pilot/pkg/networking/core/envoyfilter/listener_patch.go
  pilot/pkg/networking/core/envoyfilter/rc_patch.go
  pilot/pkg/networking/core/httproute.go
  pilot/pkg/networking/core/listener_builder.go
Labels: size/M, release-notes-none

#55040 Automator: update istio/client-go@release-1.25 dependency in istio/istio@release-1.25
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#55032 ambient: support direct usage of ReplicaSet
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
Labels: size/M, release-notes-none

#55039 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#55042 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55043 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55044 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55045 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55048 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55016 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55033 manifest translate: properly annotate cluster wide resources
  operator/cmd/mesh/manifest-translate.go
Labels: size/S, release-notes-none

#55049 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55052 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55047 Fix envoy bootstrap not respecting `WORKLOAD_IDENTITY_SOCKET_FILE`
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/ambient_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
  pkg/bootstrap/testdata/explicit_internal_address_golden.json
  pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/istio-agent/agent.go
  pkg/istio-agent/testdata/grpc-bootstrap.json
  pkg/model/proxy.go
  releasenotes/notes/55047.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: area/environments, area/security, size/L, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#55056 Update BASE_VERSION to 1.25-2025-02-11T19-01-43
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55051 fix function name
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
Labels: size/XS, release-notes-none

#55061 [release-1.23] Manual backport of #55047
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/ambient_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
  pkg/bootstrap/testdata/explicit_internal_address_golden.json
  pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/istio-agent/agent.go
  pkg/istio-agent/testdata/grpc-bootstrap.json
  pkg/model/proxy.go
  releasenotes/notes/55047.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L

#55062 [release-1.24] Manual backport of #55047
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/ambient_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
  pkg/bootstrap/testdata/explicit_internal_address_golden.json
  pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/istio-agent/agent.go
  pkg/istio-agent/testdata/grpc-bootstrap.json
  pkg/model/proxy.go
  releasenotes/notes/55047.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L

#55030 [release-1.25] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  prow/release-commit.sh
Labels: size/M, release-notes-none

#54827 Enable CNI logging temporarily to try and catch better context
  tests/integration/ambient/main_test.go
Labels: size/XS, release-notes-none

#55046 trafficDistribution: align Envoy behavior with ambient
  pilot/pkg/networking/core/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/loadbalancer/loadbalancer_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  tests/integration/pilot/locality_test.go
Labels: size/M, release-notes-none, cherrypick/release-1.25

#55065 [release-1.25] trafficDistribution: align Envoy behavior with ambient
  pilot/pkg/networking/core/loadbalancer/loadbalancer.go
  pilot/pkg/networking/core/loadbalancer/loadbalancer_test.go
  pilot/pkg/serviceregistry/kube/conversion.go
  pilot/pkg/serviceregistry/serviceentry/conversion.go
  tests/integration/pilot/locality_test.go
Labels: size/M, release-notes-none

#55067 e2e: fix telemetry flaky test
  tests/integration/telemetry/api/stats_test.go
Labels: size/M, release-notes-none

#55063 make: add missing pkgs to refresh-goldens target
  Makefile.core.mk
  cni/pkg/iptables/testdata/dns_pod_disabled_and_on_globally.golden
  cni/pkg/iptables/testdata/dns_pod_disabled_and_on_globally_ipv6.golden
  cni/pkg/iptables/testdata/dns_pod_enabled_and_off_globally.golden
  cni/pkg/iptables/testdata/ingress_and_virtual_interfaces.golden
  cni/pkg/iptables/testdata/ingress_and_virtual_interfaces_ipv6.golden
  cni/pkg/iptables/testdata/virtual_interfaces.golden
  cni/pkg/iptables/testdata/virtual_interfaces_ipv6.golden
  istioctl/pkg/workload/testdata/vmconfig/ipv4/hosts.golden
  istioctl/pkg/workload/testdata/vmconfig/ipv6/hosts.golden
  istioctl/pkg/writer/envoy/configdump/testdata/bootstrapdump.json
  istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.json
  istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.txt
  istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.yaml
  istioctl/pkg/writer/envoy/configdump/testdata/routes/empty-gateway/output.txt
  istioctl/pkg/writer/envoy/configdump/testdata/routes/istio-gateway-http-route-prefix/output.txt
  istioctl/pkg/writer/envoy/configdump/testdata/routes/k8s-gateway-http-route-path-prefix/output.txt
Labels: size/M, release-notes-none

#55073 Automator: update common-files@release-1.25 in istio/istio@release-1.25
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55072 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55074 Automator: update istio/client-go@release-1.25 dependency in istio/istio@release-1.25
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55082 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55083 ambient: do not put circuit breakers on internal clusters
  pilot/pkg/networking/core/cluster_waypoint.go
Labels: size/XS, release-notes-none

#55060 serverca: expand signed cert and cert chain PEMs with multiple cert blocks inside
  releasenotes/notes/serverca-expand-certs.yaml
  security/pkg/server/ca/server.go
  security/pkg/server/ca/server_test.go
Labels: area/security, ok-to-test, size/L, area/ambient

#54848 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55088 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55055 initial conditions analyzer
  pilot/pkg/config/file/store.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/conditions/conditions.go
  pkg/config/analysis/analyzers/testdata/condition-analyzer.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  pkg/config/resource/instance.go
  pkg/config/resource/serialization.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.yaml
  releasenotes/notes/55055.yaml
Labels: size/L, cherrypick/release-1.25

#54427 Support simple TLS for MCP
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/configcontroller_test.go
  pilot/pkg/credentials/kube/secrets.go
Labels: size/L, release-notes-none

#55086 [release-1.25] ambient: do not put circuit breakers on internal clusters
  pilot/pkg/networking/core/cluster_waypoint.go
Labels: size/XS, release-notes-none

#55085 Fix *possible* pointer mismatch (re-introduced) by #54565
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/nodeagent/ztunnelserver_test.go
Labels: size/M, release-notes-none, area/ambient

#55093 Ensure `replicas: 0` is correctly rendered in the `istio/gateway` chart
  manifests/charts/gateway/templates/deployment.yaml
  releasenotes/notes/55092.yaml
Labels: area/environments, ok-to-test, size/S

#55069 [release-1.23] e2e: fix telemetry flaky test
  tests/integration/telemetry/api/stats_test.go
Labels: size/M, release-notes-none

#55099 [release-1.25] Fix *possible* pointer mismatch (re-introduced) by #54565
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/nodeagent/ztunnelserver_test.go
Labels: size/M, release-notes-none

#55101 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55103 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55097 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55104 krt: register static collections into debugger
  pkg/kube/krt/static.go
Labels: size/XS, release-notes-none, cherrypick/release-1.25

#55100 Regen based on new build image w/go 1.24
  Makefile.core.mk
  operator/pkg/apis/values_types.pb.go
  pkg/dns/proto/nds.pb.go
  pkg/test/echo/proto/echo.pb.go
  pkg/workloadapi/security/authorization.pb.go
  pkg/workloadapi/workload.pb.go
  pkg/zdsapi/zds.pb.go
  tests/binary/binaries_test.go
Labels: area/test and release, size/XS, release-notes-none

#54897 ambient: optimize node utilization
  pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
  pilot/pkg/serviceregistry/kube/controller/ambient/nodes.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
  pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
Labels: size/L, release-notes-none

#55107 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54575 Allow customization of reinvocationPolicy for revision-tag webhook
  istioctl/pkg/tag/generate.go
  istioctl/pkg/tag/generate_test.go
  manifests/charts/istio-control/istio-discovery/templates/revision-tags.yaml
  releasenotes/notes/54575.yaml
Labels: area/environments, ok-to-test, size/L

#55113 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54851 Fix log message with incorrect formatting
  cni/pkg/install/kubeconfig.go
  cni/pkg/nodeagent/server.go
  cni/pkg/plugin/plugin.go
  pilot/pkg/model/jwks_resolver.go
  pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
  pilot/pkg/xds/sds.go
  pkg/bootstrap/config.go
  pkg/bootstrap/platform/gcp.go
  tests/integration/pilot/common/routing.go
  tests/integration/pilot/revisions/revision_tag_test.go
  tools/istio-iptables/pkg/dependencies/implementation.go
Labels: size/M, release-notes-none

#55105 [release-1.25] krt: register static collections into debugger
  pkg/kube/krt/static.go
Labels: size/XS, release-notes-none

#54923 hbone: disable metadata exchange to the upstream HBONEs
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/cluster.go
  pilot/pkg/networking/core/cluster_builder.go
  tests/integration/ambient/baseline_test.go
Labels: size/M, release-notes-none

#55087 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55119 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55121 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55125 Automator: update go-control-plane in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55126 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55106 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55129 Automator: update proxy@release-1.24 in istio/istio@release-1.24
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55130 Automator: update proxy@release-1.23 in istio/istio@release-1.23
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55128 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55127 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55134 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55118 Ambient - Send on response channel to prevent deadlock if ztunnel disconnects during event process
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/nodeagent/ztunnelserver_mocks.go
  cni/pkg/nodeagent/ztunnelserver_test.go
Labels: size/L, release-notes-none, area/ambient, cherrypick/release-1.25

#55135 addons: Bump addons version
  manifests/addons/gen.sh
  samples/addons/loki.yaml
  samples/addons/prometheus.yaml
Labels: size/M, release-notes-none

#55136 mcp: implement CRL and SAN validation for certs
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/configcontroller_test.go
Labels: size/L, release-notes-none

#55148 [release-1.25] Ambient - Send on response channel to prevent deadlock if ztunnel disconnects during event process
  cni/pkg/nodeagent/ztunnelserver.go
  cni/pkg/nodeagent/ztunnelserver_mocks.go
  cni/pkg/nodeagent/ztunnelserver_test.go
Labels: size/L, release-notes-none

#55115 [release-1.23] Fix compatibility with <1.23 proxies when meshConfig.accessLogEncoding is JSON
  pilot/pkg/model/telemetry_logging.go
  releasenotes/notes/55116.yaml
Labels: area/test and release, area/networking, size/S

#55096 [release-1.25] initial conditions analyzer
  pilot/pkg/config/file/store.go
  pilot/pkg/config/kube/crdclient/types.gen.go
  pkg/config/analysis/analyzers/all.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/conditions/conditions.go
  pkg/config/analysis/analyzers/testdata/condition-analyzer.yaml
  pkg/config/analysis/msg/messages.gen.go
  pkg/config/analysis/msg/messages.yaml
  pkg/config/resource/instance.go
  pkg/config/resource/serialization.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.yaml
  releasenotes/notes/55055.yaml
Labels: size/L, release-notes-none

#55150 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54406 fix broken links in operator doc
  architecture/environments/operator.md
  operator/README.md
Labels: kind/docs, area/environments, ok-to-test, size/S, release-notes-none

#55155 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55038 EnvoyFilter: allow referencing services as annotation
  pilot/pkg/model/envoyfilter.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/cluster.go
Labels: size/L, release-notes-none

#55140 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55098 [release-1.25] update daemonset to prioritize .Values.cniBinDir over autodetection
  manifests/charts/base/files/profile-platform-gke.yaml
  manifests/charts/default/files/profile-platform-gke.yaml
  manifests/charts/gateway/files/profile-platform-gke.yaml
  manifests/charts/gateways/istio-egress/files/profile-platform-gke.yaml
  manifests/charts/gateways/istio-ingress/files/profile-platform-gke.yaml
  manifests/charts/istio-cni/files/profile-platform-gke.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-platform-gke.yaml
  manifests/charts/ztunnel/files/profile-platform-gke.yaml
  manifests/helm-profiles/platform-gke.yaml
Labels: size/S, release-notes-none

#55152 algin default container for gateway injection with sidecar
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml.injected
  releasenotes/notes/55152.yaml
Labels: area/environments, size/L, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#55161 [release-1.25] algin default container for gateway injection with sidecar
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml.injected
  releasenotes/notes/55152.yaml
Labels: size/L, release-notes-none

#55165 Automator: update common-files@master in istio/istio@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#55166 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55167 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55110 disable inbound retry policy for gRPC streaming
  pilot/pkg/networking/core/httproute.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_test.go
  releasenotes/notes/grpc-inbound-retry.yaml
Labels: size/M

#55034 [release-1.25] Add upgradeNote for default change to internalAddressConfig
  pilot/pkg/networking/core/gateway.go
  pilot/pkg/networking/core/listener_builder.go
  releasenotes/notes/53402.yaml
Labels: size/M, release-notes-none

#55174 [release-1.23] algin default container for gateway injection with sidecar
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istiod-remote/files/gateway-injection-template.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml.injected
  pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
  releasenotes/notes/55152.yaml
Labels: size/L

#55175 [release-1.24] algin default container for gateway injection with sidecar
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml
  pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml.injected
  pkg/kube/inject/testdata/inputs/custom-template.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
  releasenotes/notes/55152.yaml
Labels: size/L

#55154 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55176 Automator: update proxy@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55179 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55059 [release-1.25] Fix envoy bootstrap not respecting `WORKLOAD_IDENTITY_SOCKET_FILE`
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/option/instances_test.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/ambient_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
  pkg/bootstrap/testdata/explicit_internal_address_golden.json
  pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  pkg/istio-agent/agent.go
  pkg/istio-agent/testdata/grpc-bootstrap.json
  pkg/model/proxy.go
  releasenotes/notes/55047.yaml
  tools/packaging/common/envoy_bootstrap.json
Labels: size/L, release-notes-none

#54951 [release-1.25] bump Kiali to v2.5 for the Istio 1.25 release
  manifests/addons/gen.sh
  releasenotes/notes/kiali-update-v2.5.yaml
  samples/addons/kiali.yaml
Labels: size/M, release-notes-none

#55185 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#55169 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55171 kube/controller: Prevent leaking stale endpoints
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/serviceregistry_test.go
  releasenotes/notes/eviction-bug.yaml
Labels: area/networking, area/perf and scalability, size/L, feature/Multi-cluster

#55187 Automator: update ztunnel@release-1.25 in istio/istio@release-1.25
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55181 Fix multi-arch builds
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8
  tools/docker-copy.sh
Labels: ok-to-test, size/S, release-notes-none

#55184 dev version bump to 1.26
  VERSION
  operator/version/version.go
  pilot/pkg/xds/bench_test.go
  pkg/test/framework/resource/version_test.go
Labels: size/S, release-notes-none

#55186 [release-1.25] pin envoyproxy/go-control-plane to last change before Envoy v1.33 cut
  go.mod
  go.sum
  pkg/config/xds/filter_types.gen.go
Labels: size/S, release-notes-none

#55192 Revert #54827 now that #54645 has been root-caused
  tests/integration/ambient/main_test.go
Labels: size/XS, release-notes-none, area/ambient

#55190 update bin/update_deps.sh and bin/update_ztunnel.sh to release-1.25
  bin/update_deps.sh
  bin/update_ztunnel.sh
  docker/Dockerfile.distroless
  istio.deps
  prow/release-commit.sh
Labels: size/S, release-notes-none

#55199 Automator: update ztunnel@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#54752 improve istioctl x internal-debug syncz output
  istioctl/pkg/internaldebug/internal-debug.go
Labels: size/XS, release-notes-none

#55194 Refine conditions analyzer
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/conditions/conditions.go
  pkg/config/analysis/analyzers/testdata/condition-analyzer.yaml
  releasenotes/notes/55194.yaml
Labels: size/M, area/ambient

#55205 Remove the compatibility profile for 1.22
  manifests/charts/base/files/profile-compatibility-version-1.22.yaml
  manifests/charts/default/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateway/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-cni/files/profile-compatibility-version-1.22.yaml
  manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.22.yaml
  manifests/charts/ztunnel/files/profile-compatibility-version-1.22.yaml
  manifests/helm-profiles/compatibility-version-1.22.yaml
Labels: area/environments, size/S, release-notes-none

#55209 [release-1.25] Refine conditions analyzer
  pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
  pkg/config/analysis/analyzers/analyzers_test.go
  pkg/config/analysis/analyzers/conditions/conditions.go
  pkg/config/analysis/analyzers/testdata/condition-analyzer.yaml
  releasenotes/notes/55194.yaml
Labels: size/M, release-notes-none

#55200 Fix some invalid log types in CNI
  cni/pkg/nodeagent/ztunnelserver.go
Labels: size/XS, release-notes-none

#55206 Remove ENABLE_DEFERRED_CLUSTER_CREATION flag and code paths
  pilot/pkg/features/experimental.go
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/ambient_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/deferred_cluster_creation.proxycfg
  pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
  pkg/bootstrap/testdata/explicit_internal_address_golden.json
  pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
  pkg/bootstrap/testdata/lrs_golden.json
  pkg/bootstrap/testdata/metrics_no_statsd_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_compression_brotli_golden.json
  pkg/bootstrap/testdata/stats_compression_gzip_golden.json
  pkg/bootstrap/testdata/stats_compression_unknown_golden.json
  pkg/bootstrap/testdata/stats_compression_zstd_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_none_golden.json
  pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
  pkg/bootstrap/testdata/tracing_tls_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  pkg/bootstrap/testdata/xdsproxy_golden.json
  tools/packaging/common/envoy_bootstrap.json
Labels: area/networking, size/XL, release-notes-none

#55207 Remove ENABLE_DELIMITED_STATS_TAG_REGEX flag and code paths
  pilot/pkg/features/telemetry.go
  pilot/pkg/networking/core/cluster_builder_test.go
  pilot/pkg/networking/core/cluster_test.go
  pilot/pkg/networking/util/util.go
  pkg/bootstrap/config.go
  pkg/bootstrap/instance_test.go
  pkg/bootstrap/option/instances.go
  tools/packaging/common/envoy_bootstrap.json
Labels: area/extensions and telemetry, size/M, release-notes-none

#55214 Update BASE_VERSION to 1.24-2025-02-21T19-03-13
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55212 Update BASE_VERSION to master-2025-02-21T19-01-15
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55213 Update BASE_VERSION to 1.25-2025-02-21T19-03-16
  Makefile.core.mk
Labels: size/XS, auto-merge, release-notes-none

#55223 Disable non-host-net `istio-cni` on `master` for now
  manifests/charts/istio-cni/values.yaml
Labels: size/XS, release-notes-none, area/ambient

#55170 Prefer oldest pid (like we do in sidecar repair) #55139
  cni/pkg/nodeagent/fakes_test.go
  cni/pkg/nodeagent/net_test.go
  cni/pkg/nodeagent/netns.go
  cni/pkg/nodeagent/netns_linux.go
  cni/pkg/nodeagent/podcgroupns.go
  cni/pkg/nodeagent/podcgroupns_linux.go
  cni/pkg/nodeagent/podcgroupns_test.go
  cni/pkg/nodeagent/server.go
  cni/pkg/nodeagent/testdata/cgroupns/1/stat
  cni/pkg/nodeagent/testdata/cgroupns/2/cgroup
  cni/pkg/nodeagent/testdata/cgroupns/2/ns/net
  cni/pkg/nodeagent/testdata/cgroupns/2/stat
  releasenotes/notes/55139.yaml
Labels: size/L, area/ambient, cherrypick/release-1.24, cherrypick/release-1.25

#55224 Wrap iptables detect in namespace check
  cni/pkg/iptables/iptables.go
Labels: size/S, release-notes-none, area/ambient

#54431 ra: fix ztunnel CSR validation
  security/pkg/pki/ra/common.go
Labels: area/security, ok-to-test, size/XS, release-notes-none, area/ambient

#55231 Automator: update istio/client-go@master dependency in istio/istio@master
  go.mod
  go.sum
  manifests/charts/base/files/crd-all.gen.yaml
Labels: size/S, auto-merge, release-notes-none

#55204 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55234 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55220 analyzer: fix unknown schema handling
  pilot/pkg/config/file/store.go
  pilot/pkg/config/file/store_test.go
Labels: size/S, release-notes-none

#55237 Automator: update proxy@master in istio/istio@master
  istio.deps
Labels: size/XS, auto-merge, release-notes-none

#55075 inject: Do not remove existing init container
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  pkg/kube/inject/testdata/inject/init-no-intercept-no-native-sidecar.yaml
  pkg/kube/inject/testdata/inject/init-no-intercept-no-native-sidecar.yaml.injected
  releasenotes/notes/54562.yaml
Labels: ok-to-test, size/L, cherrypick/release-1.25
